Matrix3
NAME
Matrix3 -
SYNOPSIS
#include <SbVector3.H>
Inherited by RotMatrix, SBFrame, SBNutation, SBPolus, SBPolusNRO, SBPrecession, and SBPrecNutNRO'.
Public Member Functions
Matrix3 ()
Matrix3 (const Matrix3 &)
Matrix3 (const Vector3 &col0, const Vector3 &col1, const Vector3 &col2)
Matrix3 (double a00, double a01, double a02, double a10, double a11, double a12, double a20, double a21, double a22)
virtual ~Matrix3 ()
virtual QString ClassName () const
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator= (const Matrix3 &)
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Protected Attributes
double mat [3][3]
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
Definition at line 117 of file SbVector3.H'.
Constructor & Destructor Documentation
Matrix3::Matrix3 () [inline]
Definition at line 340 of file SbVector3.H'.
References mat.
Referenced by SBPrecNutNRO::operator()(), and T().
Matrix3::Matrix3 (const Matrix3 &M) [inline]
Definition at line 363 of file SbVector3.H'.
References mat.
Matrix3::Matrix3 (const Vector3 &col0, const Vector3 &col1, const Vector3 &col2) [inline]"Creates object'. Arguments are Vector3, three columns'.
Definition at line 347 of file SbVector3.H'.
References Vector3::at(), mat, X_AXIS, Y_AXIS, and Z_AXIS.
Matrix3::Matrix3 (doublea00, doublea01, doublea02, doublea10, doublea11, doublea12, doublea20, doublea21, doublea22) [inline]"Creates object'. Arguments are doubles: first row, second row and third row'.
Definition at line 354 of file SbVector3.H'.
References mat.
virtual Matrix3::~Matrix3 () [inline, virtual]
Definition at line 136 of file SbVector3.H'.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual]
Definition at line 139 of file SbVector3.H'.
References mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
virtual QString Matrix3::ClassName () const [inline, virtual]
Reimplemented in SBFrameNRO, SBFrameClassic, SBFrame, SBRotate, SBPolusNRO, SBPolus, SBPrecNutNRO, SBNut_IAU2000, SBNut_IAU1980, SBNutation, SBPrec_IAU2000, SBPrec_IAU1976, SBPrecession, Rot2DerMatrix, RotDerMatrix, and RotMatrix'.
Definition at line 137 of file SbVector3.H'.
Referenced by operator~().
double Matrix3::module () const [inline, virtual]
Definition at line 410 of file SbVector3.H'.
References mat.
Referenced by operator~(), and unify().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual]
Definition at line 138 of file SbVector3.H'.
References mat.
Matrix3 & Matrix3::operator*= (doublev) [inline]
Definition at line 394 of file SbVector3.H'.
References mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline]
Definition at line 378 of file SbVector3.H'.
References mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline]
Definition at line 386 of file SbVector3.H'.
References mat.
Matrix3 & Matrix3::operator/= (doublev) [inline]
Definition at line 402 of file SbVector3.H'.
References mat.
Referenced by unify().
Matrix3 & Matrix3::operator= (const Matrix3 &M) [inline]
Definition at line 370 of file SbVector3.H'.
References mat.
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual]
Definition at line 76 of file SbVector3.C'.
References Log, mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
Matrix3 Matrix3::T () const [inline]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References mat, and Matrix3().
Referenced by SBDelay::calcDerivatives().
virtual void Matrix3::unify () [inline, virtual]
Definition at line 142 of file SbVector3.H'.
References module(), and operator/=().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
double Matrix3::mat[3][3] [protected]
Definition at line 120 of file SbVector3.H'.
Referenced by at(), Matrix3(), module(), operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator~(), report2Log(), and T().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.