.TH "QDialog" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSBAliasEditor\fP, \fBSBCablesBrowser\fP, \fBSBClockBreakEditor\fP, \fBSBCoordsEditor\fP, \fBSBFilteringGauss\fP, \fBSBMasterRecBrowser\fP, \fBSBObsVLBIStatSrc\fP, \fBSBObsVLBIStatSta\fP, \fBSBParEditor\fP, \fBSBPlotDialog\fP, \fBSBProjectSel\fP, \fBSBSpectrumAnalyserMEM\fP, \fBSBStaParsEditor\fP, \fBSBStuffAplo\fP, \fBSBStuffEOPs\fP, \fBSBStuffEphem\fP, \fBSBStuffSources\fP, \fBSBStuffStations\fP, \fBSBStuffStationsEcc\fP, \fBSBTest\fP, \fBSBVLBINetEntryEditor\fP, \fBSBVLBINetworkEditor\fP, and \fBSBVLBISetViewBase\fP'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
