.TH "QWidget" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSBBrowseBases\fP, \fBSBBrowseHistory\fP, \fBSBBrowseSessions\fP, \fBSBBrowseSources\fP, \fBSBBrowseStations\fP, \fBSBCentralPanel\fP, \fBSBOLoadEditor\fP, \fBSBPlot\fP, and \fBSBPlotArea\fP'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
