.TH "SB_CRF" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SB_CRF \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoSources\&.H>\fP
.PP
Inherits \fBSBCatalog\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSB_CRF\fP ()"
.br
.ti -1c
.RI "virtual \fB~SB_CRF\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBfind\fP (const \fBSBSource\fP &N) const "
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBfind\fP (const QString &S) const "
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBoperator[]\fP (const \fBSBSource\fP &N) const "
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBoperator[]\fP (const QString &S) const "
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBfirst\fP ()"
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBnext\fP ()"
.br
.ti -1c
.RI "virtual void \fBprepareAliases4Output\fP ()"
.br
.ti -1c
.RI "virtual void \fBreleaseAliases4Output\fP ()"
.br
.ti -1c
.RI "virtual void \fBcollectObjAliases\fP (QString)"
.br
.ti -1c
.RI "virtual void \fBreleaseObjAliases\fP (QString)"
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBlookupAlias\fP (const QString &)"
.br
.ti -1c
.RI "virtual \fBSBSource\fP * \fBlookupNearest\fP (double, double, double &)"
.br
.ti -1c
.RI "virtual void \fBprepare4Run\fP ()"
.br
.ti -1c
.RI "virtual void \fBfinisRun\fP ()"
.br
.ti -1c
.RI "void \fBsetLabel\fP (const \fBSBSolutionName\fP &Label_)"
.br
.ti -1c
.RI "void \fBsetEpoch\fP (const \fBSBMJD\fP &Epoch_)"
.br
.ti -1c
.RI "void \fBsetComment\fP (const QString &Comment_)"
.br
.ti -1c
.RI "const \fBSBSolutionName\fP & \fBlabel\fP () const "
.br
.ti -1c
.RI "const \fBSBMJD\fP & \fBepoch\fP () const "
.br
.ti -1c
.RI "const QString & \fBcomment\fP () const "
.br
.ti -1c
.RI "QDict< QString > * \fBaliasDict\fP ()"
.br
.ti -1c
.RI "virtual void \fBprepareReferences\fP ()"
.br
.ti -1c
.RI "virtual \fBSBNList\fP * \fBreferenceList\fP ()"
.br
.ti -1c
.RI "virtual void \fBclear\fP ()"
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBfind\fP (const \fBSBNamed\fP &N) const "
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBoperator[]\fP (const \fBSBNamed\fP &N) const "
.br
.ti -1c
.RI "virtual void \fBinsert\fP (const \fBSBNamed\fP *N)"
.br
.ti -1c
.RI "virtual void \fBinSort\fP (const \fBSBNamed\fP *N)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP ()"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (uint i)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (const \fBSBNamed\fP *N)"
.br
.ti -1c
.RI "virtual bool \fBremoveFirst\fP ()"
.br
.ti -1c
.RI "virtual bool \fBremoveLast\fP ()"
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBtake\fP ()"
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBtake\fP (uint i)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item Entry) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &Entry)"
.br
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item item1, QCollection::Item item2)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSBSolutionName\fP \fBLabel\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBEpoch\fP"
.br
.ti -1c
.RI "QString \fBComment\fP"
.br
.ti -1c
.RI "QDict< \fBSBNamed\fP > * \fBDict\fP"
.br
.ti -1c
.RI "QDict< QString > * \fBAliases\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator<<\fP (\fBQTextStream\fP &, const \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator>>\fP (\fBQTextStream\fP &, \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_dico\fP & \fBoperator<<\fP (\fBSBTS_dico\fP &, \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_dico\fP & \fBoperator>>\fP (\fBSBTS_dico\fP &, \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_rsc\fP & \fBoperator<<\fP (\fBSBTS_rsc\fP &, const \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_rsc\fP & \fBoperator>>\fP (\fBSBTS_rsc\fP &, \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_car\fP & \fBoperator<<\fP (\fBSBTS_car\fP &, const \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_car\fP & \fBoperator>>\fP (\fBSBTS_car\fP &, \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &, const \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &, \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_report\fP & \fBoperator<<\fP (\fBSBTS_report\fP &, const \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_report4IVS\fP & \fBoperator<<\fP (\fBSBTS_report4IVS\fP &, const \fBSB_CRF\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &, const \fBSBCatalog\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &, \fBSBCatalog\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 305 of file SbGeoSources\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SB_CRF::SB_CRF ()\fC [inline]\fP"
.PP
Definition at line 314 of file SbGeoSources\&.H'\&.
.PP
References SBCatalog::Label, SBSolutionName::setTech(), SBSolutionName::setType(), TECH_VLBI, and SBSolutionName::TYPE_RSC\&.
.SS "virtual SB_CRF::~SB_CRF ()\fC [inline, virtual]\fP"
.PP
Definition at line 319 of file SbGeoSources\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "QDict<QString>* SBCatalog::aliasDict ()\fC [inline, inherited]\fP"
.PP
Definition at line 504 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Aliases\&.
.PP
Referenced by SBAliasEditor::accept(), SBStuffSources::CRFModified(), SBStuffSources::deleteEntryA(), SBStuffStations::deleteEntryA(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBEcc::importEccDat(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStationImport::loadNScodes(), SBStuffSources::reloadCRF(), SBStuffStations::reloadTRF(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), and SBStuffStations::TRFModified()\&.
.SS "virtual QString SB_CRF::ClassName () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 321 of file SbGeoSources\&.H'\&.
.PP
Referenced by lookupNearest(), and prepareAliases4Output()\&.
.SS "virtual void SBCatalog::clear ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 516 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict\&.
.SS "void SB_CRF::collectObjAliases (QStringS)\fC [virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1196 of file SbGeoSources\&.C'\&.
.PP
References SBCatalog::Aliases, SBSource::aList, find(), and SBNamed::name()\&.
.SS "const QString& SBCatalog::comment () const\fC [inline, inherited]\fP"
.PP
Definition at line 503 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Comment\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations()\&.
.SS "virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2)\fC [inline, protected, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP, \fBSBStationList\fP, and \fBSBStationIDList\fP'\&.
.PP
Definition at line 277 of file SbGeo\&.H'\&.
.SS "const \fBSBMJD\fP& SBCatalog::epoch () const\fC [inline, inherited]\fP"
.PP
Definition at line 502 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Epoch\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBAploChunk::import(), SBAploEphem::importHPS(), operator<<(), operator>>(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations()\&.
.SS "virtual \fBSBSource\fP* SB_CRF::find (const \fBSBSource\fP &N) const\fC [inline, virtual]\fP"
.PP
Definition at line 325 of file SbGeoSources\&.H'\&.
.PP
Referenced by collectListOfSINEXParameters4NEQ(), collectObjAliases(), SBRunManager::constraintSourceCoord(), find(), SBSourceImport::importICRF(), lookupAlias(), SBSourceEditor::makeApply(), SBRunManager::makeReportCRFVariations(), operator>>(), operator[](), prepareAliases4Output(), SBRunManager::process_m1(), releaseObjAliases(), SBObsVLBIEntry::source(), and SBBrowseSources::updateList()\&.
.SS "virtual \fBSBSource\fP* SB_CRF::find (const QString &S) const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 326 of file SbGeoSources\&.H'\&.
.PP
References find()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::find (const \fBSBNamed\fP &N) const\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 517 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBNamed::name()\&.
.PP
Referenced by SBCatalog::operator[]()\&.
.SS "void SB_CRF::finisRun ()\fC [virtual]\fP"
.PP
Definition at line 1273 of file SbGeoSources\&.C'\&.
.PP
References first(), and next()\&.
.PP
Referenced by SBSolutionBrowser::updateCRF(), and SBRunManager::~SBRunManager()\&.
.SS "virtual \fBSBSource\fP* SB_CRF::first ()\fC [inline, virtual]\fP"
.PP
Definition at line 329 of file SbGeoSources\&.H'\&.
.PP
Referenced by SBRunManager::fillParameterList(), finisRun(), SBSourceImport::importICRF(), lookupNearest(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), prepare4Run(), SBStuffSources::reloadCRF(), SBStuffSources::SBStuffSources(), sinex_SourceIDBlock(), and SBSolutionBrowser::updateCRF()\&.
.SS "virtual void SBCatalog::insert (const \fBSBNamed\fP *N)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 521 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, SBCatalog::inSort(), and SBNamed::name()\&.
.SS "virtual void SBCatalog::inSort (const \fBSBNamed\fP *N)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 522 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBNamed::name()\&.
.PP
Referenced by SBSourceImport::importICRF(), SBCatalog::insert(), SBSourceEditor::makeApply(), operator>>(), and SBStuffSources::SBStuffSources()\&.
.SS "const \fBSBSolutionName\fP& SBCatalog::label () const\fC [inline, inherited]\fP"
.PP
Definition at line 501 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Label\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator<<(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations()\&.
.SS "\fBSBSource\fP * SB_CRF::lookupAlias (const QString &Alias)\fC [virtual]\fP"
.PP
Definition at line 1222 of file SbGeoSources\&.C'\&.
.PP
References SBCatalog::Aliases, and find()\&.
.SS "\fBSBSource\fP * SB_CRF::lookupNearest (doublera, doubledn, double &MinR)\fC [virtual]\fP"
.PP
Definition at line 1230 of file SbGeoSources\&.C'\&.
.PP
References ClassName(), SBLog::DBG, SBSource::dn(), first(), Log, SBNamed::name(), next(), SBSource::ra(), RAD2DEG, SBLog::SOURCE, and SBLog::write()\&.
.SS "virtual \fBSBSource\fP* SB_CRF::next ()\fC [inline, virtual]\fP"
.PP
Definition at line 330 of file SbGeoSources\&.H'\&.
.PP
Referenced by SBRunManager::fillParameterList(), finisRun(), SBSourceImport::importICRF(), lookupNearest(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), prepare4Run(), SBStuffSources::reloadCRF(), SBStuffSources::SBStuffSources(), sinex_SourceIDBlock(), and SBSolutionBrowser::updateCRF()\&.
.SS "virtual \fBSBSource\fP* SB_CRF::operator[] (const \fBSBSource\fP &N) const\fC [inline, virtual]\fP"
.PP
Definition at line 327 of file SbGeoSources\&.H'\&.
.PP
References find()\&.
.SS "virtual \fBSBSource\fP* SB_CRF::operator[] (const QString &S) const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 328 of file SbGeoSources\&.H'\&.
.PP
References find()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::operator[] (const \fBSBNamed\fP &N) const\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 519 of file SbGeo\&.H'\&.
.PP
References SBCatalog::find()\&.
.SS "void SB_CRF::prepare4Run ()\fC [virtual]\fP"
.PP
Definition at line 1267 of file SbGeoSources\&.C'\&.
.PP
References first(), and next()\&.
.PP
Referenced by SBRunManager::SBRunManager(), and SBSolutionBrowser::updateCRF()\&.
.SS "void SB_CRF::prepareAliases4Output ()\fC [virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1158 of file SbGeoSources\&.C'\&.
.PP
References SBCatalog::Aliases, SBSource::aList, ClassName(), find(), Log, SBLog::SOURCE, SBLog::write(), and SBLog::WRN\&.
.PP
Referenced by SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), operator<<(), SBStuffSources::reloadCRF(), and SBStuffSources::SBStuffSources()\&.
.SS "virtual void SBCatalog::prepareReferences ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 512 of file SbGeo\&.H'\&.
.PP
Referenced by SBAliasEditor::init()\&.
.SS "virtual QDataStream& SB_CRF::read (QDataStream &s, QCollection::Item &Entry)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBSBNList\fP'\&.
.PP
Definition at line 310 of file SbGeoSources\&.H'\&.
.SS "virtual \fBSBNList\fP* SBCatalog::referenceList ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 513 of file SbGeo\&.H'\&.
.PP
Referenced by SBAliasEditor::init()\&.
.SS "void SB_CRF::releaseAliases4Output ()\fC [virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1184 of file SbGeoSources\&.C'\&.
.PP
References SBSource::aList\&.
.PP
Referenced by SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), operator<<(), and SBStuffSources::~SBStuffSources()\&.
.SS "void SB_CRF::releaseObjAliases (QStringS)\fC [virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1215 of file SbGeoSources\&.C'\&.
.PP
References SBSource::clearAliasesList(), and find()\&.
.SS "virtual bool SBCatalog::remove ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 523 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict\&.
.PP
Referenced by SBStuffSources::deleteEntryS(), SBRunManager::makeReportCRF(), SBCatalog::remove(), and SBRunManager::stripCRF()\&.
.SS "virtual bool SBCatalog::remove (uinti)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 524 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBCatalog::remove()\&.
.SS "virtual bool SBCatalog::remove (const \fBSBNamed\fP *N)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 525 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBCatalog::remove()\&.
.SS "virtual bool SBCatalog::removeFirst ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 526 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict\&.
.SS "virtual bool SBCatalog::removeLast ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 527 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict\&.
.SS "void SBCatalog::setComment (const QString &Comment_)\fC [inline, inherited]\fP"
.PP
Definition at line 500 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Comment\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and SBStationImport::importITRF()\&.
.SS "void SBCatalog::setEpoch (const \fBSBMJD\fP &Epoch_)\fC [inline, inherited]\fP"
.PP
Definition at line 499 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Epoch\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and operator>>()\&.
.SS "void SBCatalog::setLabel (const \fBSBSolutionName\fP &Label_)\fC [inline, inherited]\fP"
.PP
Definition at line 498 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Label\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::take ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 528 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict\&.
.PP
Referenced by SBCatalog::take()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::take (uinti)\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP'\&.
.PP
Definition at line 529 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBCatalog::take()\&.
.SS "virtual QDataStream& SB_CRF::write (QDataStream &s, QCollection::ItemEntry) const\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBSBNList\fP'\&.
.PP
Definition at line 308 of file SbGeoSources\&.H'\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBQTextStream\fP& operator<< (\fBQTextStream\fP &, const \fBSB_CRF\fP &)\fC [friend]\fP"
.SS "\fBSBTS_dico\fP& operator<< (\fBSBTS_dico\fP &s, \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1299 of file SbGeoSources\&.C'\&.
.SS "\fBSBTS_rsc\fP& operator<< (\fBSBTS_rsc\fP &s, const \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1416 of file SbGeoSources\&.C'\&.
.SS "\fBSBTS_car\fP& operator<< (\fBSBTS_car\fP &s, const \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1501 of file SbGeoSources\&.C'\&.
.SS "QDataStream& operator<< (QDataStream &s, const \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1287 of file SbGeoSources\&.C'\&.
.SS "\fBSBTS_report\fP& operator<< (\fBSBTS_report\fP &s, const \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1372 of file SbGeoSources\&.C'\&.
.SS "\fBSBTS_report4IVS\fP& operator<< (\fBSBTS_report4IVS\fP &s, const \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1396 of file SbGeoSources\&.C'\&.
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBCatalog\fP &C)\fC [friend, inherited]\fP"
.PP
Definition at line 438 of file SbGeo\&.C'\&.
.SS "\fBQTextStream\fP& operator>> (\fBQTextStream\fP &, \fBSB_CRF\fP &)\fC [friend]\fP"
.SS "\fBSBTS_dico\fP& operator>> (\fBSBTS_dico\fP &s, \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1327 of file SbGeoSources\&.C'\&.
.SS "\fBSBTS_rsc\fP& operator>> (\fBSBTS_rsc\fP &s, \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1451 of file SbGeoSources\&.C'\&.
.SS "\fBSBTS_car\fP& operator>> (\fBSBTS_car\fP &s, \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1526 of file SbGeoSources\&.C'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSB_CRF\fP &CRF)\fC [friend]\fP"
.PP
Definition at line 1293 of file SbGeoSources\&.C'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBCatalog\fP &C)\fC [friend, inherited]\fP"
.PP
Definition at line 450 of file SbGeo\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "QDict<QString>* \fBSBCatalog::Aliases\fP\fC [protected, inherited]\fP"
.PP
Definition at line 490 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::aliasDict(), collectObjAliases(), lookupAlias(), SB_TRF::lookupID(), SB_TRF::lookupStation(), operator<<(), operator>>(), prepareAliases4Output(), SBCatalog::SBCatalog(), and SBCatalog::~SBCatalog()\&.
.SS "QString \fBSBCatalog::Comment\fP\fC [protected, inherited]\fP"
.PP
Definition at line 488 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::comment(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setComment()\&.
.SS "QDict<\fBSBNamed\fP>* \fBSBCatalog::Dict\fP\fC [protected, inherited]\fP"
.PP
Definition at line 489 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::clear(), SBCatalog::find(), SBCatalog::insert(), SBCatalog::inSort(), operator>>(), SBCatalog::remove(), SBCatalog::removeFirst(), SBCatalog::removeLast(), SBCatalog::SBCatalog(), SB_TRF::setSiteName(), SBCatalog::take(), and SBCatalog::~SBCatalog()\&.
.SS "\fBSBMJD\fP \fBSBCatalog::Epoch\fP\fC [protected, inherited]\fP"
.PP
Definition at line 487 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::epoch(), SB_TRF::lookupNearest(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setEpoch()\&.
.SS "\fBSBSolutionName\fP \fBSBCatalog::Label\fP\fC [protected, inherited]\fP"
.PP
Definition at line 486 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::label(), operator<<(), operator>>(), SB_CRF(), SB_TRF::SB_TRF(), SBCatalog::SBCatalog(), and SBCatalog::setLabel()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
