SB_CRF
NAME
SB_CRF -
SYNOPSIS
#include <SbGeoSources.H>
Inherits SBCatalog'.
Public Member Functions
SB_CRF ()
virtual ~SB_CRF ()
virtual QString ClassName () const
virtual SBSource * find (const SBSource &N) const
virtual SBSource * find (const QString &S) const
virtual SBSource * operator[] (const SBSource &N) const
virtual SBSource * operator[] (const QString &S) const
virtual SBSource * first ()
virtual SBSource * next ()
virtual void prepareAliases4Output ()
virtual void releaseAliases4Output ()
virtual void collectObjAliases (QString)
virtual void releaseObjAliases (QString)
virtual SBSource * lookupAlias (const QString &)
virtual SBSource * lookupNearest (double, double, double &)
virtual void prepare4Run ()
virtual void finisRun ()
void setLabel (const SBSolutionName &Label_)
void setEpoch (const SBMJD &Epoch_)
void setComment (const QString &Comment_)
const SBSolutionName & label () const
const SBMJD & epoch () const
const QString & comment () const
QDict< QString > * aliasDict ()
virtual void prepareReferences ()
virtual SBNList * referenceList ()
virtual void clear ()
virtual SBNamed * find (const SBNamed &N) const
virtual SBNamed * operator[] (const SBNamed &N) const
virtual void insert (const SBNamed *N)
virtual void inSort (const SBNamed *N)
virtual bool remove ()
virtual bool remove (uint i)
virtual bool remove (const SBNamed *N)
virtual bool removeFirst ()
virtual bool removeLast ()
virtual SBNamed * take ()
virtual SBNamed * take (uint i)
Protected Member Functions
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
Protected Attributes
SBSolutionName Label
SBMJD Epoch
QString Comment
QDict< SBNamed > * Dict
QDict< QString > * Aliases
Friends
QTextStream & operator<< (QTextStream &, const SB_CRF &)
QTextStream & operator>> (QTextStream &, SB_CRF &)
SBTS_dico & operator<< (SBTS_dico &, SB_CRF &)
SBTS_dico & operator>> (SBTS_dico &, SB_CRF &)
SBTS_rsc & operator<< (SBTS_rsc &, const SB_CRF &)
SBTS_rsc & operator>> (SBTS_rsc &, SB_CRF &)
SBTS_car & operator<< (SBTS_car &, const SB_CRF &)
SBTS_car & operator>> (SBTS_car &, SB_CRF &)
QDataStream & operator<< (QDataStream &, const SB_CRF &)
QDataStream & operator>> (QDataStream &, SB_CRF &)
SBTS_report & operator<< (SBTS_report &, const SB_CRF &)
SBTS_report4IVS & operator<< (SBTS_report4IVS &, const SB_CRF &)
QDataStream & operator<< (QDataStream &, const SBCatalog &)
QDataStream & operator>> (QDataStream &, SBCatalog &)
Detailed Description
Definition at line 305 of file SbGeoSources.H'.
Constructor & Destructor Documentation
SB_CRF::SB_CRF () [inline]
Definition at line 314 of file SbGeoSources.H'.
References SBCatalog::Label, SBSolutionName::setTech(), SBSolutionName::setType(), TECH_VLBI, and SBSolutionName::TYPE_RSC.
virtual SB_CRF::~SB_CRF () [inline, virtual]
Definition at line 319 of file SbGeoSources.H'.
Member Function Documentation
QDict<QString>* SBCatalog::aliasDict () [inline, inherited]
Definition at line 504 of file SbGeo.H'.
References SBCatalog::Aliases.
Referenced by SBAliasEditor::accept(), SBStuffSources::CRFModified(), SBStuffSources::deleteEntryA(), SBStuffStations::deleteEntryA(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBEcc::importEccDat(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStationImport::loadNScodes(), SBStuffSources::reloadCRF(), SBStuffStations::reloadTRF(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), and SBStuffStations::TRFModified().
virtual QString SB_CRF::ClassName () const [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 321 of file SbGeoSources.H'.
Referenced by lookupNearest(), and prepareAliases4Output().
virtual void SBCatalog::clear () [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 516 of file SbGeo.H'.
References SBCatalog::Dict.
void SB_CRF::collectObjAliases (QStringS) [virtual]
Reimplemented from SBCatalog'.
Definition at line 1196 of file SbGeoSources.C'.
References SBCatalog::Aliases, SBSource::aList, find(), and SBNamed::name().
const QString& SBCatalog::comment () const [inline, inherited]
Definition at line 503 of file SbGeo.H'.
References SBCatalog::Comment.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, and SBStationIDList'.
Definition at line 277 of file SbGeo.H'.
const SBMJD& SBCatalog::epoch () const [inline, inherited]
Definition at line 502 of file SbGeo.H'.
References SBCatalog::Epoch.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBAploChunk::import(), SBAploEphem::importHPS(), operator<<(), operator>>(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
virtual SBSource* SB_CRF::find (const SBSource &N) const [inline, virtual]
Definition at line 325 of file SbGeoSources.H'.
Referenced by collectListOfSINEXParameters4NEQ(), collectObjAliases(), SBRunManager::constraintSourceCoord(), find(), SBSourceImport::importICRF(), lookupAlias(), SBSourceEditor::makeApply(), SBRunManager::makeReportCRFVariations(), operator>>(), operator[](), prepareAliases4Output(), SBRunManager::process_m1(), releaseObjAliases(), SBObsVLBIEntry::source(), and SBBrowseSources::updateList().
virtual SBSource* SB_CRF::find (const QString &S) const [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 326 of file SbGeoSources.H'.
References find().
virtual SBNamed* SBCatalog::find (const SBNamed &N) const [inline, virtual, inherited]
Definition at line 517 of file SbGeo.H'.
References SBCatalog::Dict, and SBNamed::name().
Referenced by SBCatalog::operator[]().
void SB_CRF::finisRun () [virtual]
Definition at line 1273 of file SbGeoSources.C'.
References first(), and next().
Referenced by SBSolutionBrowser::updateCRF(), and SBRunManager::~SBRunManager().
virtual SBSource* SB_CRF::first () [inline, virtual]
Definition at line 329 of file SbGeoSources.H'.
Referenced by SBRunManager::fillParameterList(), finisRun(), SBSourceImport::importICRF(), lookupNearest(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), prepare4Run(), SBStuffSources::reloadCRF(), SBStuffSources::SBStuffSources(), sinex_SourceIDBlock(), and SBSolutionBrowser::updateCRF().
virtual void SBCatalog::insert (const SBNamed *N) [inline, virtual, inherited]
Definition at line 521 of file SbGeo.H'.
References SBCatalog::Dict, SBCatalog::inSort(), and SBNamed::name().
virtual void SBCatalog::inSort (const SBNamed *N) [inline, virtual, inherited]
Definition at line 522 of file SbGeo.H'.
References SBCatalog::Dict, and SBNamed::name().
Referenced by SBSourceImport::importICRF(), SBCatalog::insert(), SBSourceEditor::makeApply(), operator>>(), and SBStuffSources::SBStuffSources().
const SBSolutionName& SBCatalog::label () const [inline, inherited]
Definition at line 501 of file SbGeo.H'.
References SBCatalog::Label.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator<<(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
SBSource * SB_CRF::lookupAlias (const QString &Alias) [virtual]
Definition at line 1222 of file SbGeoSources.C'.
References SBCatalog::Aliases, and find().
SBSource * SB_CRF::lookupNearest (doublera, doubledn, double &MinR) [virtual]
Definition at line 1230 of file SbGeoSources.C'.
References ClassName(), SBLog::DBG, SBSource::dn(), first(), Log, SBNamed::name(), next(), SBSource::ra(), RAD2DEG, SBLog::SOURCE, and SBLog::write().
virtual SBSource* SB_CRF::next () [inline, virtual]
Definition at line 330 of file SbGeoSources.H'.
Referenced by SBRunManager::fillParameterList(), finisRun(), SBSourceImport::importICRF(), lookupNearest(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), prepare4Run(), SBStuffSources::reloadCRF(), SBStuffSources::SBStuffSources(), sinex_SourceIDBlock(), and SBSolutionBrowser::updateCRF().
virtual SBSource* SB_CRF::operator[] (const SBSource &N) const [inline, virtual]
Definition at line 327 of file SbGeoSources.H'.
References find().
virtual SBSource* SB_CRF::operator[] (const QString &S) const [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 328 of file SbGeoSources.H'.
References find().
virtual SBNamed* SBCatalog::operator[] (const SBNamed &N) const [inline, virtual, inherited]
Definition at line 519 of file SbGeo.H'.
References SBCatalog::find().
void SB_CRF::prepare4Run () [virtual]
Definition at line 1267 of file SbGeoSources.C'.
References first(), and next().
Referenced by SBRunManager::SBRunManager(), and SBSolutionBrowser::updateCRF().
void SB_CRF::prepareAliases4Output () [virtual]
Reimplemented from SBCatalog'.
Definition at line 1158 of file SbGeoSources.C'.
References SBCatalog::Aliases, SBSource::aList, ClassName(), find(), Log, SBLog::SOURCE, SBLog::write(), and SBLog::WRN.
Referenced by SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), operator<<(), SBStuffSources::reloadCRF(), and SBStuffSources::SBStuffSources().
virtual void SBCatalog::prepareReferences () [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 512 of file SbGeo.H'.
Referenced by SBAliasEditor::init().
virtual QDataStream& SB_CRF::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 310 of file SbGeoSources.H'.
virtual SBNList* SBCatalog::referenceList () [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 513 of file SbGeo.H'.
Referenced by SBAliasEditor::init().
void SB_CRF::releaseAliases4Output () [virtual]
Reimplemented from SBCatalog'.
Definition at line 1184 of file SbGeoSources.C'.
References SBSource::aList.
Referenced by SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), operator<<(), and SBStuffSources::~SBStuffSources().
void SB_CRF::releaseObjAliases (QStringS) [virtual]
Reimplemented from SBCatalog'.
Definition at line 1215 of file SbGeoSources.C'.
References SBSource::clearAliasesList(), and find().
virtual bool SBCatalog::remove () [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 523 of file SbGeo.H'.
References SBCatalog::Dict.
Referenced by SBStuffSources::deleteEntryS(), SBRunManager::makeReportCRF(), SBCatalog::remove(), and SBRunManager::stripCRF().
virtual bool SBCatalog::remove (uinti) [inline, virtual, inherited]
Definition at line 524 of file SbGeo.H'.
References SBCatalog::Dict, and SBCatalog::remove().
virtual bool SBCatalog::remove (const SBNamed *N) [inline, virtual, inherited]
Definition at line 525 of file SbGeo.H'.
References SBCatalog::Dict, and SBCatalog::remove().
virtual bool SBCatalog::removeFirst () [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 526 of file SbGeo.H'.
References SBCatalog::Dict.
virtual bool SBCatalog::removeLast () [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 527 of file SbGeo.H'.
References SBCatalog::Dict.
void SBCatalog::setComment (const QString &Comment_) [inline, inherited]
Definition at line 500 of file SbGeo.H'.
References SBCatalog::Comment.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and SBStationImport::importITRF().
void SBCatalog::setEpoch (const SBMJD &Epoch_) [inline, inherited]
Definition at line 499 of file SbGeo.H'.
References SBCatalog::Epoch.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and operator>>().
void SBCatalog::setLabel (const SBSolutionName &Label_) [inline, inherited]
Definition at line 498 of file SbGeo.H'.
References SBCatalog::Label.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF().
virtual SBNamed* SBCatalog::take () [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 528 of file SbGeo.H'.
References SBCatalog::Dict.
Referenced by SBCatalog::take().
virtual SBNamed* SBCatalog::take (uinti) [inline, virtual, inherited]
Reimplemented in SB_TRF'.
Definition at line 529 of file SbGeo.H'.
References SBCatalog::Dict, and SBCatalog::take().
virtual QDataStream& SB_CRF::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 308 of file SbGeoSources.H'.
Friends And Related Function Documentation
QTextStream& operator<< (QTextStream &, const SB_CRF &) [friend]
SBTS_dico& operator<< (SBTS_dico &s, SB_CRF &CRF) [friend]
Definition at line 1299 of file SbGeoSources.C'.
SBTS_rsc& operator<< (SBTS_rsc &s, const SB_CRF &CRF) [friend]
Definition at line 1416 of file SbGeoSources.C'.
SBTS_car& operator<< (SBTS_car &s, const SB_CRF &CRF) [friend]
Definition at line 1501 of file SbGeoSources.C'.
QDataStream& operator<< (QDataStream &s, const SB_CRF &CRF) [friend]
Definition at line 1287 of file SbGeoSources.C'.
SBTS_report& operator<< (SBTS_report &s, const SB_CRF &CRF) [friend]
Definition at line 1372 of file SbGeoSources.C'.
SBTS_report4IVS& operator<< (SBTS_report4IVS &s, const SB_CRF &CRF) [friend]
Definition at line 1396 of file SbGeoSources.C'.
QDataStream& operator<< (QDataStream &s, const SBCatalog &C) [friend, inherited]
Definition at line 438 of file SbGeo.C'.
QTextStream& operator>> (QTextStream &, SB_CRF &) [friend]
SBTS_dico& operator>> (SBTS_dico &s, SB_CRF &CRF) [friend]
Definition at line 1327 of file SbGeoSources.C'.
SBTS_rsc& operator>> (SBTS_rsc &s, SB_CRF &CRF) [friend]
Definition at line 1451 of file SbGeoSources.C'.
SBTS_car& operator>> (SBTS_car &s, SB_CRF &CRF) [friend]
Definition at line 1526 of file SbGeoSources.C'.
QDataStream& operator>> (QDataStream &s, SB_CRF &CRF) [friend]
Definition at line 1293 of file SbGeoSources.C'.
QDataStream& operator>> (QDataStream &s, SBCatalog &C) [friend, inherited]
Definition at line 450 of file SbGeo.C'.
Member Data Documentation
QDict<QString>* SBCatalog::Aliases [protected, inherited]
Definition at line 490 of file SbGeo.H'.
Referenced by SBCatalog::aliasDict(), collectObjAliases(), lookupAlias(), SB_TRF::lookupID(), SB_TRF::lookupStation(), operator<<(), operator>>(), prepareAliases4Output(), SBCatalog::SBCatalog(), and SBCatalog::~SBCatalog().
QString SBCatalog::Comment [protected, inherited]
Definition at line 488 of file SbGeo.H'.
Referenced by SBCatalog::comment(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setComment().
QDict<SBNamed>* SBCatalog::Dict [protected, inherited]
Definition at line 489 of file SbGeo.H'.
Referenced by SBCatalog::clear(), SBCatalog::find(), SBCatalog::insert(), SBCatalog::inSort(), operator>>(), SBCatalog::remove(), SBCatalog::removeFirst(), SBCatalog::removeLast(), SBCatalog::SBCatalog(), SB_TRF::setSiteName(), SBCatalog::take(), and SBCatalog::~SBCatalog().
SBMJD SBCatalog::Epoch [protected, inherited]
Definition at line 487 of file SbGeo.H'.
Referenced by SBCatalog::epoch(), SB_TRF::lookupNearest(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setEpoch().
SBSolutionName SBCatalog::Label [protected, inherited]
Definition at line 486 of file SbGeo.H'.
Referenced by SBCatalog::label(), operator<<(), operator>>(), SB_CRF(), SB_TRF::SB_TRF(), SBCatalog::SBCatalog(), and SBCatalog::setLabel().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.