.TH "SB_TRF" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SB_TRF \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoStations\&.H>\fP
.PP
Inherits \fBSBCatalog\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSB_TRF\fP ()"
.br
.ti -1c
.RI "\fBSB_TRF\fP (const \fBSB_TRF\fP &TRF_)"
.br
.ti -1c
.RI "virtual \fB~SB_TRF\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual void \fBclear\fP ()"
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBat\fP (uint i)"
.br
.ti -1c
.RI "virtual void \fBinsert\fP (const \fBSBSite\fP *N)"
.br
.ti -1c
.RI "virtual void \fBinSort\fP (const \fBSBSite\fP *)"
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBfirst\fP ()"
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBnext\fP ()"
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBfind\fP (const \fBSBSite\fP &N) const "
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBfind\fP (int DomeMajor_) const "
.br
.ti -1c
.RI "virtual \fBSBStation\fP * \fBfind\fP (const \fBSBStationID\fP &ID_) const "
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBoperator[]\fP (const \fBSBSite\fP &N) const "
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBoperator[]\fP (int DomeMajor_) const "
.br
.ti -1c
.RI "virtual \fBSBStation\fP * \fBoperator[]\fP (const \fBSBStationID\fP &Id_) const "
.br
.ti -1c
.RI "virtual bool \fBremove\fP ()"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (int DomeMajor_)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (const \fBSBSite\fP *N)"
.br
.ti -1c
.RI "virtual bool \fBremoveFirst\fP ()"
.br
.ti -1c
.RI "virtual bool \fBremoveLast\fP ()"
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBtake\fP ()"
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBtake\fP (uint i)"
.br
.ti -1c
.RI "\fBQList\fP< \fBSBStation\fP > * \fBstations\fP ()"
.br
.ti -1c
.RI "bool \fBsetSiteName\fP (int, const QString &)"
.br
.ti -1c
.RI "int \fBlastUnusedNumber\fP () const "
.br
.ti -1c
.RI "void \fBprepareDicts\fP ()"
.br
.ti -1c
.RI "virtual void \fBprepareAliases4Output\fP ()"
.br
.ti -1c
.RI "virtual void \fBreleaseAliases4Output\fP ()"
.br
.ti -1c
.RI "virtual void \fBcollectObjAliases\fP (QString)"
.br
.ti -1c
.RI "virtual void \fBreleaseObjAliases\fP (QString)"
.br
.ti -1c
.RI "virtual void \fBprepareReferences\fP ()"
.br
.ti -1c
.RI "virtual void \fBprepare4Run\fP ()"
.br
.ti -1c
.RI "virtual void \fBprepareEccs4Session\fP (const \fBSBMJD\fP &, \fBSBVLBISession\fP *)"
.br
.ti -1c
.RI "virtual void \fBfinisRun\fP ()"
.br
.ti -1c
.RI "virtual \fBSBNList\fP * \fBreferenceList\fP ()"
.br
.ti -1c
.RI "\fBSBEcc\fP & \fBecc\fP ()"
.br
.ti -1c
.RI "virtual \fBSBStation\fP * \fBlookupStation\fP (const QString &)"
.br
.ti -1c
.RI "virtual \fBSBStation\fP * \fBlookupStation\fP (int CDP_)"
.br
.ti -1c
.RI "virtual \fBSBStationID\fP \fBlookupID\fP (const QString &)"
.br
.ti -1c
.RI "virtual \fBSBStation\fP * \fBlookupNearest\fP (const \fBSBMJD\fP &, const \fBVector3\fP &, double &, \fBTechnique\fP=TECH_VLBI)"
.br
.ti -1c
.RI "void \fBsetLabel\fP (const \fBSBSolutionName\fP &Label_)"
.br
.ti -1c
.RI "void \fBsetEpoch\fP (const \fBSBMJD\fP &Epoch_)"
.br
.ti -1c
.RI "void \fBsetComment\fP (const QString &Comment_)"
.br
.ti -1c
.RI "const \fBSBSolutionName\fP & \fBlabel\fP () const "
.br
.ti -1c
.RI "const \fBSBMJD\fP & \fBepoch\fP () const "
.br
.ti -1c
.RI "const QString & \fBcomment\fP () const "
.br
.ti -1c
.RI "QDict< QString > * \fBaliasDict\fP ()"
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBfind\fP (const \fBSBNamed\fP &N) const "
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBfind\fP (const QString &S) const "
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBoperator[]\fP (const \fBSBNamed\fP &N) const "
.br
.ti -1c
.RI "virtual \fBSBNamed\fP * \fBoperator[]\fP (const QString &S) const "
.br
.ti -1c
.RI "virtual void \fBinsert\fP (const \fBSBNamed\fP *N)"
.br
.ti -1c
.RI "virtual void \fBinSort\fP (const \fBSBNamed\fP *N)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (uint i)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (const \fBSBNamed\fP *N)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item item1, QCollection::Item item2)"
.br
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item Entry) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &Entry)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QIntDict< \fBSBSite\fP > * \fBSiteByDome\fP"
.br
.ti -1c
.RI "QIntDict< \fBSBStation\fP > * \fBStationByCDP\fP"
.br
.ti -1c
.RI "\fBSBNList\fP * \fBStationNames\fP"
.br
.ti -1c
.RI "\fBQList\fP< \fBSBStation\fP > * \fBStations\fP"
.br
.RI "\fIlist of stations (for runner/estimator) \fP"
.ti -1c
.RI "\fBSBEcc\fP \fBECCs\fP"
.br
.ti -1c
.RI "\fBSBSolutionName\fP \fBLabel\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBEpoch\fP"
.br
.ti -1c
.RI "QString \fBComment\fP"
.br
.ti -1c
.RI "QDict< \fBSBNamed\fP > * \fBDict\fP"
.br
.ti -1c
.RI "QDict< QString > * \fBAliases\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSBSite\fP * \fBfind\fP (const QString &S)"
.br
.ti -1c
.RI "virtual \fBSBSite\fP * \fBoperator[]\fP (const QString &S)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator<<\fP (\fBQTextStream\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator>>\fP (\fBQTextStream\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_site1994\fP & \fBoperator<<\fP (\fBSBTS_site1994\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_site1994\fP & \fBoperator>>\fP (\fBSBTS_site1994\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_site2000\fP & \fBoperator<<\fP (\fBSBTS_site2000\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_site2000\fP & \fBoperator>>\fP (\fBSBTS_site2000\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_dir1994\fP & \fBoperator<<\fP (\fBSBTS_dir1994\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_dir1994\fP & \fBoperator>>\fP (\fBSBTS_dir1994\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_dir2000\fP & \fBoperator<<\fP (\fBSBTS_dir2000\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_dir2000\fP & \fBoperator>>\fP (\fBSBTS_dir2000\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_ssc1994\fP & \fBoperator<<\fP (\fBSBTS_ssc1994\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_ssc1994\fP & \fBoperator>>\fP (\fBSBTS_ssc1994\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_ssc2000\fP & \fBoperator<<\fP (\fBSBTS_ssc2000\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_ssc2000\fP & \fBoperator>>\fP (\fBSBTS_ssc2000\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_blq\fP & \fBoperator<<\fP (\fBSBTS_blq\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_blqReq\fP & \fBoperator<<\fP (\fBSBTS_blqReq\fP &, const \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_SINEX\fP & \fBoperator<<\fP (\fBSBTS_SINEX\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "\fBSBTS_SINEX\fP & \fBoperator>>\fP (\fBSBTS_SINEX\fP &, \fBSB_TRF\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &, const \fBSBCatalog\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &, \fBSBCatalog\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1166 of file SbGeoStations\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SB_TRF::SB_TRF ()\fC [inline]\fP"
.PP
Definition at line 1183 of file SbGeoStations\&.H'\&.
.PP
References SBCatalog::Label, prepareDicts(), SBSolutionName::setType(), SiteByDome, StationByCDP, StationNames, Stations, and SBSolutionName::TYPE_SSC\&.
.SS "SB_TRF::SB_TRF (const \fBSB_TRF\fP &TRF_)\fC [inline]\fP"
.PP
Definition at line 1192 of file SbGeoStations\&.H'\&.
.PP
References prepareDicts(), and Stations\&.
.SS "virtual SB_TRF::~SB_TRF ()\fC [inline, virtual]\fP"
.PP
Definition at line 1193 of file SbGeoStations\&.H'\&.
.PP
References SiteByDome, StationByCDP, StationNames, and Stations\&.
.SH "Member Function Documentation"
.PP 
.SS "QDict<QString>* SBCatalog::aliasDict ()\fC [inline, inherited]\fP"
.PP
Definition at line 504 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Aliases\&.
.PP
Referenced by SBAliasEditor::accept(), SBStuffSources::CRFModified(), SBStuffSources::deleteEntryA(), SBStuffStations::deleteEntryA(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBEcc::importEccDat(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStationImport::loadNScodes(), SBStuffSources::reloadCRF(), SBStuffStations::reloadTRF(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), and SBStuffStations::TRFModified()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::at (uinti)\fC [inline, virtual]\fP"
.PP
Definition at line 1221 of file SbGeoStations\&.H'\&.
.PP
Referenced by SBRunManager::makeReportTRF(), SBRunManager::stripTRF(), and take()\&.
.SS "virtual QString SB_TRF::ClassName () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1216 of file SbGeoStations\&.H'\&.
.PP
Referenced by inSort(), lookupNearest(), lookupStation(), and prepareEccs4Session()\&.
.SS "virtual void SB_TRF::clear ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1220 of file SbGeoStations\&.H'\&.
.PP
References SiteByDome, and StationByCDP\&.
.SS "virtual void SB_TRF::collectObjAliases (QString)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1282 of file SbGeoStations\&.H'\&.
.SS "const QString& SBCatalog::comment () const\fC [inline, inherited]\fP"
.PP
Definition at line 503 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Comment\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations()\&.
.SS "virtual int SB_TRF::compareItems (QCollection::Itemitem1, QCollection::Itemitem2)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBSBNList\fP'\&.
.PP
Definition at line 1175 of file SbGeoStations\&.H'\&.
.SS "\fBSBEcc\fP& SB_TRF::ecc ()\fC [inline]\fP"
.PP
Definition at line 1290 of file SbGeoStations\&.H'\&.
.PP
References ECCs\&.
.PP
Referenced by SBStuffStationsEcc::importData(), SBStationImport::loadECCdat(), SBStuffStationsEcc::SBStuffStationsEcc(), and sinex_SiteEccentricityBlock()\&.
.SS "const \fBSBMJD\fP& SBCatalog::epoch () const\fC [inline, inherited]\fP"
.PP
Definition at line 502 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Epoch\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBAploChunk::import(), SBAploEphem::importHPS(), operator<<(), operator>>(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::find (const \fBSBNamed\fP &N) const\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 517 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBNamed::name()\&.
.PP
Referenced by SBCatalog::operator[]()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::find (const QString &S) const\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_CRF\fP'\&.
.PP
Definition at line 518 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict\&.
.SS "virtual \fBSBSite\fP* SB_TRF::find (const \fBSBSite\fP &N) const\fC [inline, virtual]\fP"
.PP
Definition at line 1226 of file SbGeoStations\&.H'\&.
.PP
References SBSite::domeMajor(), and SiteByDome\&.
.PP
Referenced by collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constrainClocks(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), find(), SBStationImport::importITRF(), inSort(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), lookupStation(), SBSiteEditor::makeApply(), SBRunManager::makeReportTRFVariations(), operator<<(), operator[](), setSiteName(), sinex_tro_SiteIDBlock(), sinex_tro_StaCoordinatesBlock(), sinex_tro_TropSolutionBlock(), SBObsVLBIEntry::station1(), and SBObsVLBIEntry::station2()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::find (intDomeMajor_) const\fC [inline, virtual]\fP"
.PP
Definition at line 1228 of file SbGeoStations\&.H'\&.
.PP
References SiteByDome\&.
.SS "virtual \fBSBStation\fP* SB_TRF::find (const \fBSBStationID\fP &ID_) const\fC [inline, virtual]\fP"
.PP
Definition at line 1230 of file SbGeoStations\&.H'\&.
.PP
References SBSite::find(), and SiteByDome\&.
.SS "virtual \fBSBSite\fP* SB_TRF::find (const QString &S)\fC [inline, private, virtual]\fP"
.PP
Definition at line 1326 of file SbGeoStations\&.H'\&.
.PP
References find()\&.
.SS "void SB_TRF::finisRun ()\fC [virtual]\fP"
.PP
Definition at line 2879 of file SbGeoStations\&.C'\&.
.PP
References Stations\&.
.PP
Referenced by SBRunManager::makeReportTRF(), SBSolutionBrowser::updateTRF(), SBRunManager::~SBRunManager(), SBTestAPLoad::~SBTestAPLoad(), SBTestOceanTides::~SBTestOceanTides(), SBTestPolarTides::~SBTestPolarTides(), and SBTestSolidTides::~SBTestSolidTides()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::first ()\fC [inline, virtual]\fP"
.PP
Definition at line 1224 of file SbGeoStations\&.H'\&.
.PP
Referenced by SBStationImport::importITRF(), lookupNearest(), prepare4Run(), prepareDicts(), prepareReferences(), SBStuffStations::reloadTRF(), SBStuffStations::SBStuffStations(), and SBSolutionBrowser::updateTRF()\&.
.SS "virtual void SBCatalog::insert (const \fBSBNamed\fP *N)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 521 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, SBCatalog::inSort(), and SBNamed::name()\&.
.SS "virtual void SB_TRF::insert (const \fBSBSite\fP *N)\fC [inline, virtual]\fP"
.PP
Definition at line 1222 of file SbGeoStations\&.H'\&.
.PP
References inSort()\&.
.PP
Referenced by prepareDicts()\&.
.SS "virtual void SBCatalog::inSort (const \fBSBNamed\fP *N)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 522 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBNamed::name()\&.
.PP
Referenced by SBSourceImport::importICRF(), SBCatalog::insert(), SBSourceEditor::makeApply(), operator>>(), and SBStuffSources::SBStuffSources()\&.
.SS "void SB_TRF::inSort (const \fBSBSite\fP *N)\fC [virtual]\fP"
.PP
Definition at line 2737 of file SbGeoStations\&.C'\&.
.PP
References ClassName(), SBSite::domeMajor(), SBLog::ERR, find(), Log, SBNamed::name(), SiteByDome, SBLog::STATION, and SBLog::write()\&.
.PP
Referenced by SBStationImport::importITRF(), insert(), SBStationImport::loadNScodes(), SBSiteEditor::makeApply(), operator>>(), SBStuffStations::reloadTRF(), and SBStuffStations::SBStuffStations()\&.
.SS "const \fBSBSolutionName\fP& SBCatalog::label () const\fC [inline, inherited]\fP"
.PP
Definition at line 501 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Label\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator<<(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations()\&.
.SS "int SB_TRF::lastUnusedNumber () const"
.PP
Definition at line 2730 of file SbGeoStations\&.C'\&.
.PP
References SiteByDome\&.
.SS "\fBSBStationID\fP SB_TRF::lookupID (const QString &Alias)\fC [virtual]\fP"
.PP
Definition at line 2821 of file SbGeoStations\&.C'\&.
.PP
References SBCatalog::Aliases, and SBStationID::setID()\&.
.PP
Referenced by SBEcc::importEccDat()\&.
.SS "\fBSBStation\fP * SB_TRF::lookupNearest (const \fBSBMJD\fP &MJD, const \fBVector3\fP &R, double &MinR, \fBTechnique\fPTech = \fCTECH_VLBI\fP)\fC [virtual]\fP"
.PP
Definition at line 2830 of file SbGeoStations\&.C'\&.
.PP
References ClassName(), SBLog::DBG, SBCatalog::Epoch, SBStationList::first(), first(), Log, SBNamed::name(), SBStationList::next(), next(), SBStation::r(), SBLog::STATION, SBSite::Stations, SBStation::tech(), TECH_ANY, SBStation::V, and SBLog::write()\&.
.PP
Referenced by SBAploChunk::import(), and SBAploEphem::importHPS()\&.
.SS "\fBSBStation\fP * SB_TRF::lookupStation (const QString &Alias)\fC [virtual]\fP"
.PP
Definition at line 2804 of file SbGeoStations\&.C'\&.
.PP
References SBCatalog::Aliases, ClassName(), find(), SBLog::INF, Log, SBStationID::setID(), SBLog::STATION, and SBLog::write()\&.
.PP
Referenced by SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), and SBStationImport::loadNScodes()\&.
.SS "virtual \fBSBStation\fP* SB_TRF::lookupStation (intCDP_)\fC [inline, virtual]\fP"
.PP
Definition at line 1293 of file SbGeoStations\&.H'\&.
.PP
References StationByCDP\&.
.SS "virtual \fBSBSite\fP* SB_TRF::next ()\fC [inline, virtual]\fP"
.PP
Definition at line 1225 of file SbGeoStations\&.H'\&.
.PP
Referenced by SBStationImport::importITRF(), lookupNearest(), prepare4Run(), prepareDicts(), prepareReferences(), SBStuffStations::reloadTRF(), SBStuffStations::SBStuffStations(), and SBSolutionBrowser::updateTRF()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::operator[] (const \fBSBNamed\fP &N) const\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 519 of file SbGeo\&.H'\&.
.PP
References SBCatalog::find()\&.
.SS "virtual \fBSBNamed\fP* SBCatalog::operator[] (const QString &S) const\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_CRF\fP'\&.
.PP
Definition at line 520 of file SbGeo\&.H'\&.
.PP
References SBCatalog::find()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::operator[] (const \fBSBSite\fP &N) const\fC [inline, virtual]\fP"
.PP
Definition at line 1232 of file SbGeoStations\&.H'\&.
.PP
References find()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::operator[] (intDomeMajor_) const\fC [inline, virtual]\fP"
.PP
Definition at line 1233 of file SbGeoStations\&.H'\&.
.PP
References find()\&.
.SS "virtual \fBSBStation\fP* SB_TRF::operator[] (const \fBSBStationID\fP &Id_) const\fC [inline, virtual]\fP"
.PP
Definition at line 1234 of file SbGeoStations\&.H'\&.
.PP
References find()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::operator[] (const QString &S)\fC [inline, private, virtual]\fP"
.PP
Definition at line 1327 of file SbGeoStations\&.H'\&.
.PP
References find()\&.
.SS "void SB_TRF::prepare4Run ()\fC [virtual]\fP"
.PP
Definition at line 2862 of file SbGeoStations\&.C'\&.
.PP
References first(), next(), SBSetUp::path2Output(), SBSetUp::project(), SetUp, and Stations\&.
.PP
Referenced by SBRunManager::makeReportTRF(), SBRunManager::SBRunManager(), SBTestAPLoad::SBTestAPLoad(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), and SBSolutionBrowser::updateTRF()\&.
.SS "virtual void SB_TRF::prepareAliases4Output ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1280 of file SbGeoStations\&.H'\&.
.SS "void SB_TRF::prepareDicts ()"
.PP
Definition at line 2759 of file SbGeoStations\&.C'\&.
.PP
References first(), insert(), next(), SiteByDome, StationByCDP, and StationNames\&.
.PP
Referenced by SBStationImport::importITRF(), operator>>(), and SB_TRF()\&.
.SS "void SB_TRF::prepareEccs4Session (const \fBSBMJD\fP &T, \fBSBVLBISession\fP *Session)\fC [virtual]\fP"
.PP
Definition at line 2892 of file SbGeoStations\&.C'\&.
.PP
References Vector3::at(), ClassName(), SBLog::DATA, EAST, SBEccentricity::ecc(), ECCs, SBEccentricity::ET_NEU, SBStationInfoList::find(), SBEcc::findEcc(), Log, NORT, SBStation::Pt_Marker, SBStationID::setID(), SBLog::STATION, SBVLBISession::stationList(), Stations, SBEccentricity::type(), VERT, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS\&.
.PP
Referenced by SBRunManager::loadVLBISession_m1()\&.
.SS "void SB_TRF::prepareReferences ()\fC [virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 2793 of file SbGeoStations\&.C'\&.
.PP
References first(), next(), and StationNames\&.
.SS "virtual QDataStream& SB_TRF::read (QDataStream &s, QCollection::Item &Entry)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBSBNList\fP'\&.
.PP
Definition at line 1179 of file SbGeoStations\&.H'\&.
.SS "virtual \fBSBNList\fP* SB_TRF::referenceList ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1288 of file SbGeoStations\&.H'\&.
.PP
References StationNames\&.
.SS "virtual void SB_TRF::releaseAliases4Output ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1281 of file SbGeoStations\&.H'\&.
.SS "virtual void SB_TRF::releaseObjAliases (QString)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1283 of file SbGeoStations\&.H'\&.
.SS "virtual bool SBCatalog::remove (uinti)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 524 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBCatalog::remove()\&.
.SS "virtual bool SBCatalog::remove (const \fBSBNamed\fP *N)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 525 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Dict, and SBCatalog::remove()\&.
.SS "virtual bool SB_TRF::remove ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1236 of file SbGeoStations\&.H'\&.
.PP
References SiteByDome\&.
.PP
Referenced by SBStationImport::applyFilter(), SBStuffStations::deleteEntryS(), SBRunManager::makeReportTRF(), remove(), and SBRunManager::stripTRF()\&.
.SS "virtual bool SB_TRF::remove (intDomeMajor_)\fC [inline, virtual]\fP"
.PP
Definition at line 1241 of file SbGeoStations\&.H'\&.
.PP
References remove(), and SiteByDome\&.
.SS "virtual bool SB_TRF::remove (const \fBSBSite\fP *N)\fC [inline, virtual]\fP"
.PP
Definition at line 1247 of file SbGeoStations\&.H'\&.
.PP
References remove(), and SiteByDome\&.
.SS "virtual bool SB_TRF::removeFirst ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1252 of file SbGeoStations\&.H'\&.
.PP
References SiteByDome\&.
.SS "virtual bool SB_TRF::removeLast ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1257 of file SbGeoStations\&.H'\&.
.PP
References SiteByDome\&.
.SS "void SBCatalog::setComment (const QString &Comment_)\fC [inline, inherited]\fP"
.PP
Definition at line 500 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Comment\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and SBStationImport::importITRF()\&.
.SS "void SBCatalog::setEpoch (const \fBSBMJD\fP &Epoch_)\fC [inline, inherited]\fP"
.PP
Definition at line 499 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Epoch\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and operator>>()\&.
.SS "void SBCatalog::setLabel (const \fBSBSolutionName\fP &Label_)\fC [inline, inherited]\fP"
.PP
Definition at line 498 of file SbGeo\&.H'\&.
.PP
References SBCatalog::Label\&.
.PP
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF()\&.
.SS "bool SB_TRF::setSiteName (intDomeMajor_, const QString &Name_)"
.PP
Definition at line 2852 of file SbGeoStations\&.C'\&.
.PP
References SBCatalog::Dict, find(), SBNamed::name(), and SBNamed::setName()\&.
.PP
Referenced by operator>>()\&.
.SS "\fBQList\fP<\fBSBStation\fP>* SB_TRF::stations ()\fC [inline]\fP"
.PP
Definition at line 1272 of file SbGeoStations\&.H'\&.
.PP
References Stations\&.
.PP
Referenced by SBTestSolidTides::auxWidgetRt(), SBTestOceanTides::auxWidgetRt(), SBTestPolarTides::auxWidgetRt(), SBTestAPLoad::auxWidgetRt(), SBRunManager::fillParameterList(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::process_m1(), SBRunManager::SBRunManager(), SBTestAPLoad::SBTestAPLoad(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), and sinex_SolutionEpochsBlock()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::take ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1262 of file SbGeoStations\&.H'\&.
.PP
References SiteByDome\&.
.PP
Referenced by take()\&.
.SS "virtual \fBSBSite\fP* SB_TRF::take (uinti)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBCatalog\fP'\&.
.PP
Definition at line 1267 of file SbGeoStations\&.H'\&.
.PP
References at(), SiteByDome, and take()\&.
.SS "virtual QDataStream& SB_TRF::write (QDataStream &s, QCollection::ItemEntry) const\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBSBNList\fP'\&.
.PP
Definition at line 1177 of file SbGeoStations\&.H'\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBCatalog\fP &C)\fC [friend, inherited]\fP"
.PP
Definition at line 438 of file SbGeo\&.C'\&.
.SS "\fBQTextStream\fP& operator<< (\fBQTextStream\fP &s, const \fBSB_TRF\fP &)\fC [friend]\fP"
.PP
Definition at line 2947 of file SbGeoStations\&.C'\&.
.SS "QDataStream& operator<< (QDataStream &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 2934 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_site1994\fP& operator<< (\fBSBTS_site1994\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 2957 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_site2000\fP& operator<< (\fBSBTS_site2000\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3002 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_dir1994\fP& operator<< (\fBSBTS_dir1994\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3048 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_dir2000\fP& operator<< (\fBSBTS_dir2000\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3118 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_ssc1994\fP& operator<< (\fBSBTS_ssc1994\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3187 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_ssc2000\fP& operator<< (\fBSBTS_ssc2000\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3208 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_blq\fP& operator<< (\fBSBTS_blq\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3783 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_blqReq\fP& operator<< (\fBSBTS_blqReq\fP &s, const \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3226 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_SINEX\fP& operator<< (\fBSBTS_SINEX\fP &s, \fBSB_TRF\fP &)\fC [friend]\fP"
.PP
Definition at line 1721 of file SbGeoSINEX\&.C'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBCatalog\fP &C)\fC [friend, inherited]\fP"
.PP
Definition at line 450 of file SbGeo\&.C'\&.
.SS "\fBQTextStream\fP& operator>> (\fBQTextStream\fP &s, \fBSB_TRF\fP &)\fC [friend]\fP"
.PP
Definition at line 2952 of file SbGeoStations\&.C'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 2940 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_site1994\fP& operator>> (\fBSBTS_site1994\fP &s, \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 2970 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_site2000\fP& operator>> (\fBSBTS_site2000\fP &s, \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3016 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_dir1994\fP& operator>> (\fBSBTS_dir1994\fP &s, \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3066 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_dir2000\fP& operator>> (\fBSBTS_dir2000\fP &s, \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3131 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_ssc1994\fP& operator>> (\fBSBTS_ssc1994\fP &s, \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3237 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_ssc2000\fP& operator>> (\fBSBTS_ssc2000\fP &s, \fBSB_TRF\fP &TRF)\fC [friend]\fP"
.PP
Definition at line 3498 of file SbGeoStations\&.C'\&.
.SS "\fBSBTS_SINEX\fP& operator>> (\fBSBTS_SINEX\fP &s, \fBSB_TRF\fP &)\fC [friend]\fP"
.PP
Definition at line 2057 of file SbGeoSINEX\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "QDict<QString>* \fBSBCatalog::Aliases\fP\fC [protected, inherited]\fP"
.PP
Definition at line 490 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::aliasDict(), SB_CRF::collectObjAliases(), SB_CRF::lookupAlias(), lookupID(), lookupStation(), operator<<(), operator>>(), SB_CRF::prepareAliases4Output(), SBCatalog::SBCatalog(), and SBCatalog::~SBCatalog()\&.
.SS "QString \fBSBCatalog::Comment\fP\fC [protected, inherited]\fP"
.PP
Definition at line 488 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::comment(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setComment()\&.
.SS "QDict<\fBSBNamed\fP>* \fBSBCatalog::Dict\fP\fC [protected, inherited]\fP"
.PP
Definition at line 489 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::clear(), SBCatalog::find(), SBCatalog::insert(), SBCatalog::inSort(), operator>>(), SBCatalog::remove(), SBCatalog::removeFirst(), SBCatalog::removeLast(), SBCatalog::SBCatalog(), setSiteName(), SBCatalog::take(), and SBCatalog::~SBCatalog()\&.
.SS "\fBSBEcc\fP \fBSB_TRF::ECCs\fP\fC [protected]\fP"
.PP
Definition at line 1173 of file SbGeoStations\&.H'\&.
.PP
Referenced by ecc(), operator<<(), operator>>(), and prepareEccs4Session()\&.
.SS "\fBSBMJD\fP \fBSBCatalog::Epoch\fP\fC [protected, inherited]\fP"
.PP
Definition at line 487 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::epoch(), lookupNearest(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setEpoch()\&.
.SS "\fBSBSolutionName\fP \fBSBCatalog::Label\fP\fC [protected, inherited]\fP"
.PP
Definition at line 486 of file SbGeo\&.H'\&.
.PP
Referenced by SBCatalog::label(), operator<<(), operator>>(), SB_CRF::SB_CRF(), SB_TRF(), SBCatalog::SBCatalog(), and SBCatalog::setLabel()\&.
.SS "QIntDict<\fBSBSite\fP>* \fBSB_TRF::SiteByDome\fP\fC [protected]\fP"
.PP
Definition at line 1169 of file SbGeoStations\&.H'\&.
.PP
Referenced by clear(), find(), inSort(), lastUnusedNumber(), prepareDicts(), remove(), removeFirst(), removeLast(), SB_TRF(), take(), and ~SB_TRF()\&.
.SS "QIntDict<\fBSBStation\fP>* \fBSB_TRF::StationByCDP\fP\fC [protected]\fP"
.PP
Definition at line 1170 of file SbGeoStations\&.H'\&.
.PP
Referenced by clear(), lookupStation(), prepareDicts(), SB_TRF(), and ~SB_TRF()\&.
.SS "\fBSBNList\fP* \fBSB_TRF::StationNames\fP\fC [protected]\fP"
.PP
Definition at line 1171 of file SbGeoStations\&.H'\&.
.PP
Referenced by prepareDicts(), prepareReferences(), referenceList(), SB_TRF(), and ~SB_TRF()\&.
.SS "\fBQList\fP<\fBSBStation\fP>* \fBSB_TRF::Stations\fP\fC [protected]\fP"
.PP
list of stations (for runner/estimator) 
.PP
Definition at line 1172 of file SbGeoStations\&.H'\&.
.PP
Referenced by finisRun(), prepare4Run(), prepareEccs4Session(), SB_TRF(), stations(), and ~SB_TRF()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
