SB_TRF
NAME
SB_TRF -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBCatalog'.
Public Member Functions
SB_TRF ()
SB_TRF (const SB_TRF &TRF_)
virtual ~SB_TRF ()
virtual QString ClassName () const
virtual void clear ()
virtual SBSite * at (uint i)
virtual void insert (const SBSite *N)
virtual void inSort (const SBSite *)
virtual SBSite * first ()
virtual SBSite * next ()
virtual SBSite * find (const SBSite &N) const
virtual SBSite * find (int DomeMajor_) const
virtual SBStation * find (const SBStationID &ID_) const
virtual SBSite * operator[] (const SBSite &N) const
virtual SBSite * operator[] (int DomeMajor_) const
virtual SBStation * operator[] (const SBStationID &Id_) const
virtual bool remove ()
virtual bool remove (int DomeMajor_)
virtual bool remove (const SBSite *N)
virtual bool removeFirst ()
virtual bool removeLast ()
virtual SBSite * take ()
virtual SBSite * take (uint i)
QList< SBStation > * stations ()
bool setSiteName (int, const QString &)
int lastUnusedNumber () const
void prepareDicts ()
virtual void prepareAliases4Output ()
virtual void releaseAliases4Output ()
virtual void collectObjAliases (QString)
virtual void releaseObjAliases (QString)
virtual void prepareReferences ()
virtual void prepare4Run ()
virtual void prepareEccs4Session (const SBMJD &, SBVLBISession *)
virtual void finisRun ()
virtual SBNList * referenceList ()
SBEcc & ecc ()
virtual SBStation * lookupStation (const QString &)
virtual SBStation * lookupStation (int CDP_)
virtual SBStationID lookupID (const QString &)
virtual SBStation * lookupNearest (const SBMJD &, const Vector3 &, double &, Technique=TECH_VLBI)
void setLabel (const SBSolutionName &Label_)
void setEpoch (const SBMJD &Epoch_)
void setComment (const QString &Comment_)
const SBSolutionName & label () const
const SBMJD & epoch () const
const QString & comment () const
QDict< QString > * aliasDict ()
virtual SBNamed * find (const SBNamed &N) const
virtual SBNamed * find (const QString &S) const
virtual SBNamed * operator[] (const SBNamed &N) const
virtual SBNamed * operator[] (const QString &S) const
virtual void insert (const SBNamed *N)
virtual void inSort (const SBNamed *N)
virtual bool remove (uint i)
virtual bool remove (const SBNamed *N)
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Protected Attributes
QIntDict< SBSite > * SiteByDome
QIntDict< SBStation > * StationByCDP
SBNList * StationNames
QList< SBStation > * Stations
list of stations (for runner/estimator)
SBEcc ECCs
SBSolutionName Label
SBMJD Epoch
QString Comment
QDict< SBNamed > * Dict
QDict< QString > * Aliases
Private Member Functions
virtual SBSite * find (const QString &S)
virtual SBSite * operator[] (const QString &S)
Friends
QTextStream & operator<< (QTextStream &, const SB_TRF &)
QTextStream & operator>> (QTextStream &, SB_TRF &)
QDataStream & operator<< (QDataStream &, const SB_TRF &)
QDataStream & operator>> (QDataStream &, SB_TRF &)
SBTS_site1994 & operator<< (SBTS_site1994 &, const SB_TRF &)
SBTS_site1994 & operator>> (SBTS_site1994 &, SB_TRF &)
SBTS_site2000 & operator<< (SBTS_site2000 &, const SB_TRF &)
SBTS_site2000 & operator>> (SBTS_site2000 &, SB_TRF &)
SBTS_dir1994 & operator<< (SBTS_dir1994 &, const SB_TRF &)
SBTS_dir1994 & operator>> (SBTS_dir1994 &, SB_TRF &)
SBTS_dir2000 & operator<< (SBTS_dir2000 &, const SB_TRF &)
SBTS_dir2000 & operator>> (SBTS_dir2000 &, SB_TRF &)
SBTS_ssc1994 & operator<< (SBTS_ssc1994 &, const SB_TRF &)
SBTS_ssc1994 & operator>> (SBTS_ssc1994 &, SB_TRF &)
SBTS_ssc2000 & operator<< (SBTS_ssc2000 &, const SB_TRF &)
SBTS_ssc2000 & operator>> (SBTS_ssc2000 &, SB_TRF &)
SBTS_blq & operator<< (SBTS_blq &, const SB_TRF &)
SBTS_blqReq & operator<< (SBTS_blqReq &, const SB_TRF &)
SBTS_SINEX & operator<< (SBTS_SINEX &, SB_TRF &)
SBTS_SINEX & operator>> (SBTS_SINEX &, SB_TRF &)
QDataStream & operator<< (QDataStream &, const SBCatalog &)
QDataStream & operator>> (QDataStream &, SBCatalog &)
Detailed Description
Definition at line 1166 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SB_TRF::SB_TRF () [inline]
Definition at line 1183 of file SbGeoStations.H'.
References SBCatalog::Label, prepareDicts(), SBSolutionName::setType(), SiteByDome, StationByCDP, StationNames, Stations, and SBSolutionName::TYPE_SSC.
SB_TRF::SB_TRF (const SB_TRF &TRF_) [inline]
Definition at line 1192 of file SbGeoStations.H'.
References prepareDicts(), and Stations.
virtual SB_TRF::~SB_TRF () [inline, virtual]
Definition at line 1193 of file SbGeoStations.H'.
References SiteByDome, StationByCDP, StationNames, and Stations.
Member Function Documentation
QDict<QString>* SBCatalog::aliasDict () [inline, inherited]
Definition at line 504 of file SbGeo.H'.
References SBCatalog::Aliases.
Referenced by SBAliasEditor::accept(), SBStuffSources::CRFModified(), SBStuffSources::deleteEntryA(), SBStuffStations::deleteEntryA(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBEcc::importEccDat(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStationImport::loadNScodes(), SBStuffSources::reloadCRF(), SBStuffStations::reloadTRF(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), and SBStuffStations::TRFModified().
virtual SBSite* SB_TRF::at (uinti) [inline, virtual]
Definition at line 1221 of file SbGeoStations.H'.
Referenced by SBRunManager::makeReportTRF(), SBRunManager::stripTRF(), and take().
virtual QString SB_TRF::ClassName () const [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1216 of file SbGeoStations.H'.
Referenced by inSort(), lookupNearest(), lookupStation(), and prepareEccs4Session().
virtual void SB_TRF::clear () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1220 of file SbGeoStations.H'.
References SiteByDome, and StationByCDP.
virtual void SB_TRF::collectObjAliases (QString) [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1282 of file SbGeoStations.H'.
const QString& SBCatalog::comment () const [inline, inherited]
Definition at line 503 of file SbGeo.H'.
References SBCatalog::Comment.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
virtual int SB_TRF::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 1175 of file SbGeoStations.H'.
SBEcc& SB_TRF::ecc () [inline]
Definition at line 1290 of file SbGeoStations.H'.
References ECCs.
Referenced by SBStuffStationsEcc::importData(), SBStationImport::loadECCdat(), SBStuffStationsEcc::SBStuffStationsEcc(), and sinex_SiteEccentricityBlock().
const SBMJD& SBCatalog::epoch () const [inline, inherited]
Definition at line 502 of file SbGeo.H'.
References SBCatalog::Epoch.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBAploChunk::import(), SBAploEphem::importHPS(), operator<<(), operator>>(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
virtual SBNamed* SBCatalog::find (const SBNamed &N) const [inline, virtual, inherited]
Definition at line 517 of file SbGeo.H'.
References SBCatalog::Dict, and SBNamed::name().
Referenced by SBCatalog::operator[]().
virtual SBNamed* SBCatalog::find (const QString &S) const [inline, virtual, inherited]
Reimplemented in SB_CRF'.
Definition at line 518 of file SbGeo.H'.
References SBCatalog::Dict.
virtual SBSite* SB_TRF::find (const SBSite &N) const [inline, virtual]
Definition at line 1226 of file SbGeoStations.H'.
References SBSite::domeMajor(), and SiteByDome.
Referenced by collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constrainClocks(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), find(), SBStationImport::importITRF(), inSort(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), lookupStation(), SBSiteEditor::makeApply(), SBRunManager::makeReportTRFVariations(), operator<<(), operator[](), setSiteName(), sinex_tro_SiteIDBlock(), sinex_tro_StaCoordinatesBlock(), sinex_tro_TropSolutionBlock(), SBObsVLBIEntry::station1(), and SBObsVLBIEntry::station2().
virtual SBSite* SB_TRF::find (intDomeMajor_) const [inline, virtual]
Definition at line 1228 of file SbGeoStations.H'.
References SiteByDome.
virtual SBStation* SB_TRF::find (const SBStationID &ID_) const [inline, virtual]
Definition at line 1230 of file SbGeoStations.H'.
References SBSite::find(), and SiteByDome.
virtual SBSite* SB_TRF::find (const QString &S) [inline, private, virtual]
Definition at line 1326 of file SbGeoStations.H'.
References find().
void SB_TRF::finisRun () [virtual]
Definition at line 2879 of file SbGeoStations.C'.
References Stations.
Referenced by SBRunManager::makeReportTRF(), SBSolutionBrowser::updateTRF(), SBRunManager::~SBRunManager(), SBTestAPLoad::~SBTestAPLoad(), SBTestOceanTides::~SBTestOceanTides(), SBTestPolarTides::~SBTestPolarTides(), and SBTestSolidTides::~SBTestSolidTides().
virtual SBSite* SB_TRF::first () [inline, virtual]
Definition at line 1224 of file SbGeoStations.H'.
Referenced by SBStationImport::importITRF(), lookupNearest(), prepare4Run(), prepareDicts(), prepareReferences(), SBStuffStations::reloadTRF(), SBStuffStations::SBStuffStations(), and SBSolutionBrowser::updateTRF().
virtual void SBCatalog::insert (const SBNamed *N) [inline, virtual, inherited]
Definition at line 521 of file SbGeo.H'.
References SBCatalog::Dict, SBCatalog::inSort(), and SBNamed::name().
virtual void SB_TRF::insert (const SBSite *N) [inline, virtual]
Definition at line 1222 of file SbGeoStations.H'.
References inSort().
Referenced by prepareDicts().
virtual void SBCatalog::inSort (const SBNamed *N) [inline, virtual, inherited]
Definition at line 522 of file SbGeo.H'.
References SBCatalog::Dict, and SBNamed::name().
Referenced by SBSourceImport::importICRF(), SBCatalog::insert(), SBSourceEditor::makeApply(), operator>>(), and SBStuffSources::SBStuffSources().
void SB_TRF::inSort (const SBSite *N) [virtual]
Definition at line 2737 of file SbGeoStations.C'.
References ClassName(), SBSite::domeMajor(), SBLog::ERR, find(), Log, SBNamed::name(), SiteByDome, SBLog::STATION, and SBLog::write().
Referenced by SBStationImport::importITRF(), insert(), SBStationImport::loadNScodes(), SBSiteEditor::makeApply(), operator>>(), SBStuffStations::reloadTRF(), and SBStuffStations::SBStuffStations().
const SBSolutionName& SBCatalog::label () const [inline, inherited]
Definition at line 501 of file SbGeo.H'.
References SBCatalog::Label.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator<<(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
int SB_TRF::lastUnusedNumber () const
Definition at line 2730 of file SbGeoStations.C'.
References SiteByDome.
SBStationID SB_TRF::lookupID (const QString &Alias) [virtual]
Definition at line 2821 of file SbGeoStations.C'.
References SBCatalog::Aliases, and SBStationID::setID().
Referenced by SBEcc::importEccDat().
SBStation * SB_TRF::lookupNearest (const SBMJD &MJD, const Vector3 &R, double &MinR, TechniqueTech = TECH_VLBI) [virtual]
Definition at line 2830 of file SbGeoStations.C'.
References ClassName(), SBLog::DBG, SBCatalog::Epoch, SBStationList::first(), first(), Log, SBNamed::name(), SBStationList::next(), next(), SBStation::r(), SBLog::STATION, SBSite::Stations, SBStation::tech(), TECH_ANY, SBStation::V, and SBLog::write().
Referenced by SBAploChunk::import(), and SBAploEphem::importHPS().
SBStation * SB_TRF::lookupStation (const QString &Alias) [virtual]
Definition at line 2804 of file SbGeoStations.C'.
References SBCatalog::Aliases, ClassName(), find(), SBLog::INF, Log, SBStationID::setID(), SBLog::STATION, and SBLog::write().
Referenced by SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), and SBStationImport::loadNScodes().
virtual SBStation* SB_TRF::lookupStation (intCDP_) [inline, virtual]
Definition at line 1293 of file SbGeoStations.H'.
References StationByCDP.
virtual SBSite* SB_TRF::next () [inline, virtual]
Definition at line 1225 of file SbGeoStations.H'.
Referenced by SBStationImport::importITRF(), lookupNearest(), prepare4Run(), prepareDicts(), prepareReferences(), SBStuffStations::reloadTRF(), SBStuffStations::SBStuffStations(), and SBSolutionBrowser::updateTRF().
virtual SBNamed* SBCatalog::operator[] (const SBNamed &N) const [inline, virtual, inherited]
Definition at line 519 of file SbGeo.H'.
References SBCatalog::find().
virtual SBNamed* SBCatalog::operator[] (const QString &S) const [inline, virtual, inherited]
Reimplemented in SB_CRF'.
Definition at line 520 of file SbGeo.H'.
References SBCatalog::find().
virtual SBSite* SB_TRF::operator[] (const SBSite &N) const [inline, virtual]
Definition at line 1232 of file SbGeoStations.H'.
References find().
virtual SBSite* SB_TRF::operator[] (intDomeMajor_) const [inline, virtual]
Definition at line 1233 of file SbGeoStations.H'.
References find().
virtual SBStation* SB_TRF::operator[] (const SBStationID &Id_) const [inline, virtual]
Definition at line 1234 of file SbGeoStations.H'.
References find().
virtual SBSite* SB_TRF::operator[] (const QString &S) [inline, private, virtual]
Definition at line 1327 of file SbGeoStations.H'.
References find().
void SB_TRF::prepare4Run () [virtual]
Definition at line 2862 of file SbGeoStations.C'.
References first(), next(), SBSetUp::path2Output(), SBSetUp::project(), SetUp, and Stations.
Referenced by SBRunManager::makeReportTRF(), SBRunManager::SBRunManager(), SBTestAPLoad::SBTestAPLoad(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), and SBSolutionBrowser::updateTRF().
virtual void SB_TRF::prepareAliases4Output () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1280 of file SbGeoStations.H'.
void SB_TRF::prepareDicts ()
Definition at line 2759 of file SbGeoStations.C'.
References first(), insert(), next(), SiteByDome, StationByCDP, and StationNames.
Referenced by SBStationImport::importITRF(), operator>>(), and SB_TRF().
void SB_TRF::prepareEccs4Session (const SBMJD &T, SBVLBISession *Session) [virtual]
Definition at line 2892 of file SbGeoStations.C'.
References Vector3::at(), ClassName(), SBLog::DATA, EAST, SBEccentricity::ecc(), ECCs, SBEccentricity::ET_NEU, SBStationInfoList::find(), SBEcc::findEcc(), Log, NORT, SBStation::Pt_Marker, SBStationID::setID(), SBLog::STATION, SBVLBISession::stationList(), Stations, SBEccentricity::type(), VERT, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBRunManager::loadVLBISession_m1().
void SB_TRF::prepareReferences () [virtual]
Reimplemented from SBCatalog'.
Definition at line 2793 of file SbGeoStations.C'.
References first(), next(), and StationNames.
virtual QDataStream& SB_TRF::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 1179 of file SbGeoStations.H'.
virtual SBNList* SB_TRF::referenceList () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1288 of file SbGeoStations.H'.
References StationNames.
virtual void SB_TRF::releaseAliases4Output () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1281 of file SbGeoStations.H'.
virtual void SB_TRF::releaseObjAliases (QString) [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1283 of file SbGeoStations.H'.
virtual bool SBCatalog::remove (uinti) [inline, virtual, inherited]
Definition at line 524 of file SbGeo.H'.
References SBCatalog::Dict, and SBCatalog::remove().
virtual bool SBCatalog::remove (const SBNamed *N) [inline, virtual, inherited]
Definition at line 525 of file SbGeo.H'.
References SBCatalog::Dict, and SBCatalog::remove().
virtual bool SB_TRF::remove () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1236 of file SbGeoStations.H'.
References SiteByDome.
Referenced by SBStationImport::applyFilter(), SBStuffStations::deleteEntryS(), SBRunManager::makeReportTRF(), remove(), and SBRunManager::stripTRF().
virtual bool SB_TRF::remove (intDomeMajor_) [inline, virtual]
Definition at line 1241 of file SbGeoStations.H'.
References remove(), and SiteByDome.
virtual bool SB_TRF::remove (const SBSite *N) [inline, virtual]
Definition at line 1247 of file SbGeoStations.H'.
References remove(), and SiteByDome.
virtual bool SB_TRF::removeFirst () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1252 of file SbGeoStations.H'.
References SiteByDome.
virtual bool SB_TRF::removeLast () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1257 of file SbGeoStations.H'.
References SiteByDome.
void SBCatalog::setComment (const QString &Comment_) [inline, inherited]
Definition at line 500 of file SbGeo.H'.
References SBCatalog::Comment.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and SBStationImport::importITRF().
void SBCatalog::setEpoch (const SBMJD &Epoch_) [inline, inherited]
Definition at line 499 of file SbGeo.H'.
References SBCatalog::Epoch.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and operator>>().
void SBCatalog::setLabel (const SBSolutionName &Label_) [inline, inherited]
Definition at line 498 of file SbGeo.H'.
References SBCatalog::Label.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF().
bool SB_TRF::setSiteName (intDomeMajor_, const QString &Name_)
Definition at line 2852 of file SbGeoStations.C'.
References SBCatalog::Dict, find(), SBNamed::name(), and SBNamed::setName().
Referenced by operator>>().
QList<SBStation>* SB_TRF::stations () [inline]
Definition at line 1272 of file SbGeoStations.H'.
References Stations.
Referenced by SBTestSolidTides::auxWidgetRt(), SBTestOceanTides::auxWidgetRt(), SBTestPolarTides::auxWidgetRt(), SBTestAPLoad::auxWidgetRt(), SBRunManager::fillParameterList(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::process_m1(), SBRunManager::SBRunManager(), SBTestAPLoad::SBTestAPLoad(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), and sinex_SolutionEpochsBlock().
virtual SBSite* SB_TRF::take () [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1262 of file SbGeoStations.H'.
References SiteByDome.
Referenced by take().
virtual SBSite* SB_TRF::take (uinti) [inline, virtual]
Reimplemented from SBCatalog'.
Definition at line 1267 of file SbGeoStations.H'.
References at(), SiteByDome, and take().
virtual QDataStream& SB_TRF::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 1177 of file SbGeoStations.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBCatalog &C) [friend, inherited]
Definition at line 438 of file SbGeo.C'.
QTextStream& operator<< (QTextStream &s, const SB_TRF &) [friend]
Definition at line 2947 of file SbGeoStations.C'.
QDataStream& operator<< (QDataStream &s, const SB_TRF &TRF) [friend]
Definition at line 2934 of file SbGeoStations.C'.
SBTS_site1994& operator<< (SBTS_site1994 &s, const SB_TRF &TRF) [friend]
Definition at line 2957 of file SbGeoStations.C'.
SBTS_site2000& operator<< (SBTS_site2000 &s, const SB_TRF &TRF) [friend]
Definition at line 3002 of file SbGeoStations.C'.
SBTS_dir1994& operator<< (SBTS_dir1994 &s, const SB_TRF &TRF) [friend]
Definition at line 3048 of file SbGeoStations.C'.
SBTS_dir2000& operator<< (SBTS_dir2000 &s, const SB_TRF &TRF) [friend]
Definition at line 3118 of file SbGeoStations.C'.
SBTS_ssc1994& operator<< (SBTS_ssc1994 &s, const SB_TRF &TRF) [friend]
Definition at line 3187 of file SbGeoStations.C'.
SBTS_ssc2000& operator<< (SBTS_ssc2000 &s, const SB_TRF &TRF) [friend]
Definition at line 3208 of file SbGeoStations.C'.
SBTS_blq& operator<< (SBTS_blq &s, const SB_TRF &TRF) [friend]
Definition at line 3783 of file SbGeoStations.C'.
SBTS_blqReq& operator<< (SBTS_blqReq &s, const SB_TRF &TRF) [friend]
Definition at line 3226 of file SbGeoStations.C'.
SBTS_SINEX& operator<< (SBTS_SINEX &s, SB_TRF &) [friend]
Definition at line 1721 of file SbGeoSINEX.C'.
QDataStream& operator>> (QDataStream &s, SBCatalog &C) [friend, inherited]
Definition at line 450 of file SbGeo.C'.
QTextStream& operator>> (QTextStream &s, SB_TRF &) [friend]
Definition at line 2952 of file SbGeoStations.C'.
QDataStream& operator>> (QDataStream &s, SB_TRF &TRF) [friend]
Definition at line 2940 of file SbGeoStations.C'.
SBTS_site1994& operator>> (SBTS_site1994 &s, SB_TRF &TRF) [friend]
Definition at line 2970 of file SbGeoStations.C'.
SBTS_site2000& operator>> (SBTS_site2000 &s, SB_TRF &TRF) [friend]
Definition at line 3016 of file SbGeoStations.C'.
SBTS_dir1994& operator>> (SBTS_dir1994 &s, SB_TRF &TRF) [friend]
Definition at line 3066 of file SbGeoStations.C'.
SBTS_dir2000& operator>> (SBTS_dir2000 &s, SB_TRF &TRF) [friend]
Definition at line 3131 of file SbGeoStations.C'.
SBTS_ssc1994& operator>> (SBTS_ssc1994 &s, SB_TRF &TRF) [friend]
Definition at line 3237 of file SbGeoStations.C'.
SBTS_ssc2000& operator>> (SBTS_ssc2000 &s, SB_TRF &TRF) [friend]
Definition at line 3498 of file SbGeoStations.C'.
SBTS_SINEX& operator>> (SBTS_SINEX &s, SB_TRF &) [friend]
Definition at line 2057 of file SbGeoSINEX.C'.
Member Data Documentation
QDict<QString>* SBCatalog::Aliases [protected, inherited]
Definition at line 490 of file SbGeo.H'.
Referenced by SBCatalog::aliasDict(), SB_CRF::collectObjAliases(), SB_CRF::lookupAlias(), lookupID(), lookupStation(), operator<<(), operator>>(), SB_CRF::prepareAliases4Output(), SBCatalog::SBCatalog(), and SBCatalog::~SBCatalog().
QString SBCatalog::Comment [protected, inherited]
Definition at line 488 of file SbGeo.H'.
Referenced by SBCatalog::comment(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setComment().
QDict<SBNamed>* SBCatalog::Dict [protected, inherited]
Definition at line 489 of file SbGeo.H'.
Referenced by SBCatalog::clear(), SBCatalog::find(), SBCatalog::insert(), SBCatalog::inSort(), operator>>(), SBCatalog::remove(), SBCatalog::removeFirst(), SBCatalog::removeLast(), SBCatalog::SBCatalog(), setSiteName(), SBCatalog::take(), and SBCatalog::~SBCatalog().
SBEcc SB_TRF::ECCs [protected]
Definition at line 1173 of file SbGeoStations.H'.
Referenced by ecc(), operator<<(), operator>>(), and prepareEccs4Session().
SBMJD SBCatalog::Epoch [protected, inherited]
Definition at line 487 of file SbGeo.H'.
Referenced by SBCatalog::epoch(), lookupNearest(), operator<<(), operator>>(), SBCatalog::SBCatalog(), and SBCatalog::setEpoch().
SBSolutionName SBCatalog::Label [protected, inherited]
Definition at line 486 of file SbGeo.H'.
Referenced by SBCatalog::label(), operator<<(), operator>>(), SB_CRF::SB_CRF(), SB_TRF(), SBCatalog::SBCatalog(), and SBCatalog::setLabel().
QIntDict<SBSite>* SB_TRF::SiteByDome [protected]
Definition at line 1169 of file SbGeoStations.H'.
Referenced by clear(), find(), inSort(), lastUnusedNumber(), prepareDicts(), remove(), removeFirst(), removeLast(), SB_TRF(), take(), and ~SB_TRF().
QIntDict<SBStation>* SB_TRF::StationByCDP [protected]
Definition at line 1170 of file SbGeoStations.H'.
Referenced by clear(), lookupStation(), prepareDicts(), SB_TRF(), and ~SB_TRF().
SBNList* SB_TRF::StationNames [protected]
Definition at line 1171 of file SbGeoStations.H'.
Referenced by prepareDicts(), prepareReferences(), referenceList(), SB_TRF(), and ~SB_TRF().
QList<SBStation>* SB_TRF::Stations [protected]
list of stations (for runner/estimator)
Definition at line 1172 of file SbGeoStations.H'.
Referenced by finisRun(), prepare4Run(), prepareEccs4Session(), SB_TRF(), stations(), and ~SB_TRF().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.