SBAliasEditor
NAME
SBAliasEditor -
SYNOPSIS
#include <SbIStuffSource.H>
Inherits QDialog'.
Signals
void AliasModified (bool)
Public Member Functions
SBAliasEditor (SBAliasListItem *, SBCatalog *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
SBAliasEditor (QListView *, SBCatalog *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBAliasEditor ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Member Functions
virtual void acquireData ()
void init ()
Private Attributes
QListView * AliasesLV
SBAliasListItem * AkaItem
bool isModified
bool isNew
QString Alias
QString Reference
QString OldReference
SBCatalog * Wcrf
QLineEdit * EAlias
QComboBox * CBReference
Detailed Description
Definition at line 378 of file SbIStuffSource.H'.
Constructor & Destructor Documentation
SBAliasEditor::SBAliasEditor (SBAliasListItem *AkaItem_, SBCatalog *Wcrf_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2371 of file SbIStuffSource.C'.
References AkaItem, SBAliasListItem::Alias, Alias, AliasesLV, init(), isNew, OldReference, SBAliasListItem::Reference, Reference, and Wcrf.
SBAliasEditor::SBAliasEditor (QListView *AliasesLV_, SBCatalog *Wcrf_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2386 of file SbIStuffSource.C'.
References AkaItem, Alias, AliasesLV, init(), isNew, OldReference, Reference, and Wcrf.
SBAliasEditor::~SBAliasEditor ()
Definition at line 2511 of file SbIStuffSource.C'.
References AliasModified(), and isModified.
Member Function Documentation
void SBAliasEditor::accept () [protected, slot]
Definition at line 2516 of file SbIStuffSource.C'.
References acquireData(), AkaItem, Alias, SBCatalog::aliasDict(), AliasesLV, ClassName(), SBCatalog::collectObjAliases(), SBLog::DBG, SBLog::INTERFACE, isModified, isNew, Log, OldReference, SBAliasListItem::Reference, Reference, Wcrf, and SBLog::write().
Referenced by init().
void SBAliasEditor::acquireData () [private, virtual]
Definition at line 2577 of file SbIStuffSource.C'.
References Alias, CBReference, EAlias, isModified, isNew, and Reference.
Referenced by accept().
void SBAliasEditor::AliasModified (boolt0) [signal]
Definition at line 674 of file SbIStuffSource.moc.C'.
Referenced by ~SBAliasEditor().
virtual QString SBAliasEditor::ClassName () const [inline, virtual]
Definition at line 387 of file SbIStuffSource.H'.
Referenced by accept().
virtual void SBAliasEditor::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 398 of file SbIStuffSource.H'.
void SBAliasEditor::init () [private]
Definition at line 2401 of file SbIStuffSource.C'.
References accept(), Alias, CBReference, EAlias, isModified, isNew, SBCatalog::prepareReferences(), Reference, SBCatalog::referenceList(), reject(), and Wcrf.
Referenced by SBAliasEditor().
void SBAliasEditor::reject () [protected, slot]
Definition at line 2571 of file SbIStuffSource.C'.
Referenced by init().
Member Data Documentation
SBAliasListItem* SBAliasEditor::AkaItem [private]
Definition at line 405 of file SbIStuffSource.H'.
Referenced by accept(), and SBAliasEditor().
QString SBAliasEditor::Alias [private]
Definition at line 409 of file SbIStuffSource.H'.
Referenced by accept(), acquireData(), init(), and SBAliasEditor().
QListView* SBAliasEditor::AliasesLV [private]
Definition at line 404 of file SbIStuffSource.H'.
Referenced by accept(), and SBAliasEditor().
QComboBox* SBAliasEditor::CBReference [private]
Definition at line 416 of file SbIStuffSource.H'.
Referenced by acquireData(), and init().
QLineEdit* SBAliasEditor::EAlias [private]
Definition at line 415 of file SbIStuffSource.H'.
Referenced by acquireData(), and init().
bool SBAliasEditor::isModified [private]
Definition at line 407 of file SbIStuffSource.H'.
Referenced by accept(), acquireData(), init(), and ~SBAliasEditor().
bool SBAliasEditor::isNew [private]
Definition at line 408 of file SbIStuffSource.H'.
Referenced by accept(), acquireData(), init(), and SBAliasEditor().
QString SBAliasEditor::OldReference [private]
Definition at line 411 of file SbIStuffSource.H'.
Referenced by accept(), and SBAliasEditor().
QString SBAliasEditor::Reference [private]
Definition at line 410 of file SbIStuffSource.H'.
Referenced by accept(), acquireData(), init(), and SBAliasEditor().
SBCatalog* SBAliasEditor::Wcrf [private]
Definition at line 412 of file SbIStuffSource.H'.
Referenced by accept(), init(), and SBAliasEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.