SBAploChunk
NAME
SBAploChunk -
SYNOPSIS
#include <SbGeoAtmLoad.H>
Inherits QList< SBAploEntry >, and SBAploHeader'.
Public Member Functions
SBAploChunk ()
virtual ~SBAploChunk ()
virtual QString ClassName () const
const SBAploHeader & header () const
void import (QTextStream &, SB_TRF *, bool &)
SBAploEntry * entryByID (const SBStationID &)
const SBMJD & tStart () const
void setTStart (const SBMJD &T_)
const SBMJD & tFinis () const
void setTFinis (const SBMJD &T_)
double interval () const
void setInterval (double dt_)
QString name ()
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
void fillDict ()
Protected Attributes
QDict< SBAploEntry > * EntryByID
QIntDict< SBAploEntry > * EntryByDomes
Friends
QDataStream & operator<< (QDataStream &s, const SBAploChunk &C)
QDataStream & operator>> (QDataStream &s, SBAploChunk &C)
QTextStream & operator<< (QTextStream &, const SBAploChunk &)
QTextStream & operator>> (QTextStream &, SBAploChunk &)
QDataStream & operator<< (QDataStream &s, const SBAploHeader &H)
QDataStream & operator>> (QDataStream &s, SBAploHeader &H)
Detailed Description
Definition at line 176 of file SbGeoAtmLoad.H'.
Constructor & Destructor Documentation
SBAploChunk::SBAploChunk ()
Definition at line 79 of file SbGeoAtmLoad.C'.
References EntryByDomes, and EntryByID.
SBAploChunk::~SBAploChunk () [virtual]
Definition at line 89 of file SbGeoAtmLoad.C'.
References EntryByDomes, and EntryByID.
Member Function Documentation
virtual QString SBAploChunk::ClassName () const [inline, virtual]
Reimplemented from SBAploHeader'.
Definition at line 199 of file SbGeoAtmLoad.H'.
Referenced by fillDict(), and import().
virtual int SBAploChunk::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 179 of file SbGeoAtmLoad.H'.
SBAploEntry * SBAploChunk::entryByID (const SBStationID &ID)
Definition at line 103 of file SbGeoAtmLoad.C'.
References SBStationID::domeMajor(), EntryByDomes, EntryByID, and SBStationID::toString().
Referenced by SBAploEphem::getReady().
void SBAploChunk::fillDict () [protected]
Definition at line 111 of file SbGeoAtmLoad.C'.
References ClassName(), SBLog::DBG, EntryByDomes, EntryByID, SBAploEntry::id(), Log, SBNamed::name(), SBLog::TIDES, SBStationID::toString(), SBLog::write(), and SBLog::WRN.
Referenced by import().
const SBAploHeader& SBAploChunk::header () const [inline]
Definition at line 203 of file SbGeoAtmLoad.H'.
Referenced by SBAploEphem::importEphem().
void SBAploChunk::import (QTextStream &s, SB_TRF *TRF, bool &IsTRFModified)
Definition at line 143 of file SbGeoAtmLoad.C'.
References SBAttributed::addAttr(), ClassName(), SBLog::DATA, SBLog::DBG, EAST, SBCatalog::epoch(), SBLog::ERR, fillDict(), SBStation::id(), SBLog::INF, SBAploHeader::interval(), SBMJD::isGood(), SBStationID::isValidId(), Log, SB_TRF::lookupNearest(), SB_TRF::lookupStation(), SBAploHeader::name(), SBNamed::name(), NORT, SBStation::OrigEdited, SBStation::r_first(), SBStation::setCoords(), SBMJD::setDate(), SBAploDRec::setDisplacement(), SBAploHeader::setInterval(), SBAploHeader::setTFinis(), SBMJD::setTime(), SBAploHeader::setTStart(), SBStation::setV(), SBSite::setV(), SBStation::site(), SBLog::STATION, TECH_ANY, SBLog::TIDES, SBStationID::toString(), SBAploHeader::tStart(), TZero, SBSite::v(), v3Unit, v3Zero, SBPMNNR_NUVEL1A::velocity(), VERT, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBAploEphem::importEphem().
double SBAploHeader::interval () const [inline, inherited]
Definition at line 152 of file SbGeoAtmLoad.H'.
References SBAploHeader::Interval.
Referenced by import(), SBAploHeaderLI::key(), and SBAploHeaderLI::text().
QString SBAploHeader::name () [inline, inherited]
Definition at line 157 of file SbGeoAtmLoad.H'.
References SBMJD::F_INTERNAL, SBMJD::toString(), and SBAploHeader::TStart.
Referenced by import(), SBAploEphem::loadChunk(), and SBAploEphem::saveChunk().
virtual QDataStream& SBAploChunk::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 187 of file SbGeoAtmLoad.H'.
void SBAploHeader::setInterval (doubledt_) [inline, inherited]
Definition at line 153 of file SbGeoAtmLoad.H'.
References SBAploHeader::Interval.
Referenced by import().
void SBAploHeader::setTFinis (const SBMJD &T_) [inline, inherited]
Definition at line 151 of file SbGeoAtmLoad.H'.
References SBAploHeader::TFinis.
Referenced by import().
void SBAploHeader::setTStart (const SBMJD &T_) [inline, inherited]
Definition at line 149 of file SbGeoAtmLoad.H'.
References SBAploHeader::TStart.
Referenced by import().
const SBMJD& SBAploHeader::tFinis () const [inline, inherited]
Definition at line 150 of file SbGeoAtmLoad.H'.
References SBAploHeader::TFinis.
Referenced by SBAploHeaderLI::key(), and SBAploHeaderLI::text().
const SBMJD& SBAploHeader::tStart () const [inline, inherited]
Definition at line 148 of file SbGeoAtmLoad.H'.
References SBAploHeader::TStart.
Referenced by import(), SBAploEphem::importEphem(), SBAploHeaderLI::key(), and SBAploHeaderLI::text().
virtual QDataStream& SBAploChunk::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 185 of file SbGeoAtmLoad.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBAploHeader &H) [friend, inherited]
Definition at line 161 of file SbGeoAtmLoad.H'.
QDataStream& operator<< (QDataStream &s, const SBAploChunk &C) [friend]
Definition at line 213 of file SbGeoAtmLoad.H'.
QTextStream& operator<< (QTextStream &s, const SBAploChunk &) [friend]
Definition at line 458 of file SbGeoAtmLoad.C'.
QDataStream& operator>> (QDataStream &s, SBAploHeader &H) [friend, inherited]
Definition at line 163 of file SbGeoAtmLoad.H'.
QDataStream& operator>> (QDataStream &s, SBAploChunk &C) [friend]
Definition at line 215 of file SbGeoAtmLoad.H'.
QTextStream& operator>> (QTextStream &s, SBAploChunk &) [friend]
Definition at line 464 of file SbGeoAtmLoad.C'.
Member Data Documentation
QIntDict<SBAploEntry>* SBAploChunk::EntryByDomes [protected]
Definition at line 191 of file SbGeoAtmLoad.H'.
Referenced by entryByID(), fillDict(), SBAploChunk(), and ~SBAploChunk().
QDict<SBAploEntry>* SBAploChunk::EntryByID [protected]
Definition at line 188 of file SbGeoAtmLoad.H'.
Referenced by entryByID(), fillDict(), SBAploChunk(), and ~SBAploChunk().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.