SBAploHeader
NAME
SBAploHeader -
SYNOPSIS
#include <SbGeoAtmLoad.H>
Inherited by SBAploChunk'.
Public Member Functions
SBAploHeader ()
virtual ~SBAploHeader ()
virtual QString ClassName () const
const SBMJD & tStart () const
void setTStart (const SBMJD &T_)
const SBMJD & tFinis () const
void setTFinis (const SBMJD &T_)
double interval () const
void setInterval (double dt_)
QString name ()
Private Attributes
SBMJD TStart
SBMJD TFinis
double Interval
Friends
QDataStream & operator<< (QDataStream &s, const SBAploHeader &H)
QDataStream & operator>> (QDataStream &s, SBAploHeader &H)
Detailed Description
Definition at line 132 of file SbGeoAtmLoad.H'.
Constructor & Destructor Documentation
SBAploHeader::SBAploHeader ()
Definition at line 64 of file SbGeoAtmLoad.C'.
References Interval, TFinis, TStart, and TZero.
virtual SBAploHeader::~SBAploHeader () [inline, virtual]
Definition at line 143 of file SbGeoAtmLoad.H'.
Member Function Documentation
virtual QString SBAploHeader::ClassName () const [inline, virtual]
Reimplemented in SBAploChunk'.
Definition at line 144 of file SbGeoAtmLoad.H'.
double SBAploHeader::interval () const [inline]
Definition at line 152 of file SbGeoAtmLoad.H'.
References Interval.
Referenced by SBAploChunk::import(), SBAploHeaderLI::key(), and SBAploHeaderLI::text().
QString SBAploHeader::name () [inline]
Definition at line 157 of file SbGeoAtmLoad.H'.
References SBMJD::F_INTERNAL, SBMJD::toString(), and TStart.
Referenced by SBAploChunk::import(), SBAploEphem::loadChunk(), and SBAploEphem::saveChunk().
void SBAploHeader::setInterval (doubledt_) [inline]
Definition at line 153 of file SbGeoAtmLoad.H'.
References Interval.
Referenced by SBAploChunk::import().
void SBAploHeader::setTFinis (const SBMJD &T_) [inline]
Definition at line 151 of file SbGeoAtmLoad.H'.
References TFinis.
Referenced by SBAploChunk::import().
void SBAploHeader::setTStart (const SBMJD &T_) [inline]
Definition at line 149 of file SbGeoAtmLoad.H'.
References TStart.
Referenced by SBAploChunk::import().
const SBMJD& SBAploHeader::tFinis () const [inline]
Definition at line 150 of file SbGeoAtmLoad.H'.
References TFinis.
Referenced by SBAploHeaderLI::key(), and SBAploHeaderLI::text().
const SBMJD& SBAploHeader::tStart () const [inline]
Definition at line 148 of file SbGeoAtmLoad.H'.
References TStart.
Referenced by SBAploChunk::import(), SBAploEphem::importEphem(), SBAploHeaderLI::key(), and SBAploHeaderLI::text().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBAploHeader &H) [friend]
Definition at line 161 of file SbGeoAtmLoad.H'.
QDataStream& operator>> (QDataStream &s, SBAploHeader &H) [friend]
Definition at line 163 of file SbGeoAtmLoad.H'.
Member Data Documentation
double SBAploHeader::Interval [private]
Definition at line 137 of file SbGeoAtmLoad.H'.
Referenced by interval(), SBAploHeader(), and setInterval().
SBMJD SBAploHeader::TFinis [private]
Definition at line 136 of file SbGeoAtmLoad.H'.
Referenced by SBAploHeader(), setTFinis(), and tFinis().
SBMJD SBAploHeader::TStart [private]
Definition at line 135 of file SbGeoAtmLoad.H'.
Referenced by name(), SBAploHeader(), setTStart(), and tStart().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.