SBAploEntryLI
NAME
SBAploEntryLI -
SYNOPSIS
#include <SbIStuff.H>
Inherits QListViewItem'.
Public Member Functions
SBAploEntryLI (QListView *parent, SBAploEntry *E_)
virtual ~SBAploEntryLI ()
virtual QString ClassName () const
virtual QString text (int) const
QString key (int, bool) const
SBAploEntry * entry ()
Private Attributes
SBAploEntry * Entry
Detailed Description
Definition at line 209 of file SbIStuff.H'.
Constructor & Destructor Documentation
SBAploEntryLI::SBAploEntryLI (QListView *parent, SBAploEntry *E_) [inline]
Definition at line 214 of file SbIStuff.H'.
References Entry.
virtual SBAploEntryLI::~SBAploEntryLI () [inline, virtual]
Definition at line 215 of file SbIStuff.H'.
Member Function Documentation
virtual QString SBAploEntryLI::ClassName () const [inline, virtual]
Definition at line 216 of file SbIStuff.H'.
SBAploEntry* SBAploEntryLI::entry () [inline]
Definition at line 219 of file SbIStuff.H'.
References Entry.
QString SBAploEntryLI::key (intcol, bool) const
Definition at line 914 of file SbIStuff.C'.
References Entry, SBAploEntry::id(), SBNamed::name(), TmpString, and SBStationID::toString().
QString SBAploEntryLI::text (intcol) const [virtual]
Definition at line 894 of file SbIStuff.C'.
References Entry, SBAploEntry::id(), SBNamed::name(), TmpString, and SBStationID::toString().
Member Data Documentation
SBAploEntry* SBAploEntryLI::Entry [private]
Definition at line 212 of file SbIStuff.H'.
Referenced by entry(), key(), SBAploEntryLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.