.TH "SBAploEphem" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBAploEphem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoAtmLoad\&.H>\fP
.PP
Inherits \fBQList< SBAploHeader >\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBAploEphem\fP ()"
.br
.ti -1c
.RI "virtual \fB~SBAploEphem\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "const \fBSBMJD\fP & \fBtStart\fP () const "
.br
.ti -1c
.RI "void \fBsetTStart\fP (const \fBSBMJD\fP &T_)"
.br
.ti -1c
.RI "const \fBSBMJD\fP & \fBtFinis\fP () const "
.br
.ti -1c
.RI "void \fBsetTFinis\fP (const \fBSBMJD\fP &T_)"
.br
.ti -1c
.RI "double \fBinterval\fP () const "
.br
.ti -1c
.RI "bool \fBisOK\fP () const "
.br
.ti -1c
.RI "bool \fBimportEphem\fP (const QString &, \fBSB_TRF\fP *, bool &)"
.br
.ti -1c
.RI "void \fBimportHPS\fP (const QString &, \fBSB_TRF\fP *)"
.br
.ti -1c
.RI "void \fBsaveChunk\fP (\fBSBAploChunk\fP *)"
.br
.ti -1c
.RI "void \fBloadChunk\fP (\fBSBAploHeader\fP *, \fBSBAploChunk\fP *&)"
.br
.ti -1c
.RI "void \fBregisterStation\fP (\fBSBStation\fP *)"
.br
.ti -1c
.RI "void \fBgetReady\fP (const \fBSBMJD\fP &, const \fBSBMJD\fP &)"
.br
.ti -1c
.RI "void \fBdismissed\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP \fBdisplacement\fP (const \fBSBStationID\fP &, const \fBSBMJD\fP &)"
.br
.ti -1c
.RI "\fBSBSpline\fP * \fBspline4station\fP (const \fBSBStationID\fP &ID)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item item1, QCollection::Item item2)"
.br
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item Entry) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &Entry)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheckEphem\fP (bool=TRUE)"
.br
.ti -1c
.RI "QString \fBext\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBMJD\fP \fBTStart\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBTFinis\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBTPreparedStart\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBTPreparedFinis\fP"
.br
.ti -1c
.RI "double \fBInterval\fP"
.br
.ti -1c
.RI "bool \fBIsOK\fP"
.br
.ti -1c
.RI "\fBQList\fP< \fBSBStationID\fP > \fBSites\fP"
.br
.ti -1c
.RI "QDict< \fBSBStationID\fP > \fBSiteByID\fP"
.br
.ti -1c
.RI "QDict< \fBSBSpline\fP > \fBSplineByID\fP"
.br
.ti -1c
.RI "QIntDict< \fBSBSpline\fP > \fBSplineByDomes\fP"
.br
.ti -1c
.RI "\fBSBAploWaveList\fP \fBWaves\fP"
.br
.ti -1c
.RI "QDict< \fBSBAploWave\fP > \fBWaveByName\fP"
.br
.ti -1c
.RI "\fBSBAploSiteAmplList\fP \fBSiteAmplitudes\fP"
.br
.ti -1c
.RI "QIntDict< \fBSBAploSiteAmpl\fP > \fBSiteAmplitudeByDomes\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBAploEphem\fP &E)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBAploEphem\fP &E)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 422 of file SbGeoAtmLoad\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBAploEphem::SBAploEphem ()"
.PP
Definition at line 494 of file SbGeoAtmLoad\&.C'\&.
.PP
References checkEphem(), Interval, IsOK, SiteAmplitudeByDomes, SiteAmplitudes, SiteByID, Sites, SplineByDomes, SplineByID, TFinis, TPreparedFinis, TPreparedStart, TStart, TZero, WaveByName, and Waves\&.
.SS "SBAploEphem::~SBAploEphem ()\fC [virtual]\fP"
.PP
Definition at line 517 of file SbGeoAtmLoad\&.C'\&.
.PP
References SiteAmplitudeByDomes, SiteAmplitudes, SiteByID, Sites, SplineByDomes, SplineByID, WaveByName, and Waves\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBAploEphem::checkEphem (boolIsNeedCheckDicts = \fCTRUE\fP)\fC [private]\fP"
.PP
Definition at line 537 of file SbGeoAtmLoad\&.C'\&.
.PP
References ClassName(), SBLog::DATA, SBLog::ERR, Interval, IsOK, Log, SiteAmplitudeByDomes, SiteAmplitudes, TFinis, tFinis(), TStart, TZero, WaveByName, Waves, and SBLog::write()\&.
.PP
Referenced by importEphem(), importHPS(), and SBAploEphem()\&.
.SS "virtual QString SBAploEphem::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 466 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), displacement(), getReady(), importHPS(), registerStation(), and saveChunk()\&.
.SS "virtual int SBAploEphem::compareItems (QCollection::Itemitem1, QCollection::Itemitem2)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 425 of file SbGeoAtmLoad\&.H'\&.
.SS "void SBAploEphem::dismissed ()"
.PP
Definition at line 1032 of file SbGeoAtmLoad\&.C'\&.
.PP
References SiteByID, Sites, SplineByDomes, SplineByID, TPreparedFinis, TPreparedStart, and TZero\&.
.PP
Referenced by SBTestAPLoad::fillData4Plotting(), and SBRunManager::process_m1()\&.
.SS "\fBVector3\fP SBAploEphem::displacement (const \fBSBStationID\fP &ID, const \fBSBMJD\fP &T)"
.PP
Definition at line 1042 of file SbGeoAtmLoad\&.C'\&.
.PP
References SBAploWave::angle(), ClassName(), SBLog::DBG, SBStationID::domeMajor(), EAST, SBMJD::F_Short, interval(), SBLog::isEligible(), SBSpline::isReady(), Log, NORT, Vector3::report2Log(), sincos(), SiteAmplitudeByDomes, SBSpline::spline(), SplineByDomes, SplineByID, SBLog::STATION, SBLog::TIDES, SBStationID::toString(), TPreparedFinis, TPreparedStart, v3Zero, VERT, WaveByName, SBLog::write(), and SBLog::WRN\&.
.PP
Referenced by SBStation::calcDisplacement(), and SBTestAPLoad::fillData4Plotting()\&.
.SS "QString SBAploEphem::ext () const\fC [inline, private]\fP"
.PP
Definition at line 459 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by loadChunk(), and saveChunk()\&.
.SS "void SBAploEphem::getReady (const \fBSBMJD\fP &Tbegin, const \fBSBMJD\fP &Tend)"
.PP
Definition at line 902 of file SbGeoAtmLoad\&.C'\&.
.PP
References SBSpline::b(), ClassName(), SBLog::DBG, EAST, SBAploChunk::entryByID(), SBMJD::F_Short, interval(), loadChunk(), Log, NORT, SBMatrix::set(), Sites, SplineByDomes, SplineByID, SBLog::STATION, TFinis, SBMJD::toString(), TPreparedFinis, TPreparedStart, TStart, VERT, SBLog::write(), and SBLog::WRN\&.
.PP
Referenced by SBTestAPLoad::fillData4Plotting(), and SBRunManager::process_m1()\&.
.SS "bool SBAploEphem::importEphem (const QString &FileName, \fBSB_TRF\fP *TRF, bool &IsTRFmodified)"
.PP
Definition at line 619 of file SbGeoAtmLoad\&.C'\&.
.PP
References checkEphem(), SBFCList::close(), SBSetUp::fcList(), SBAploChunk::header(), SBAploChunk::import(), SBFCList::open4In(), saveChunk(), SetUp, SBAploHeader::tStart(), and TZero\&.
.PP
Referenced by SBStuffAplo::import()\&.
.SS "void SBAploEphem::importHPS (const QString &FileName, \fBSB_TRF\fP *TRF)"
.PP
Definition at line 653 of file SbGeoAtmLoad\&.C'\&.
.PP
References SBAttributed::addAttr(), checkEphem(), ClassName(), SBLog::DATA, SBLog::DBG, SBStationID::domeMajor(), SBCatalog::epoch(), SBLog::ERR, SBAploSiteAmpl::id(), SBStation::id(), SBLog::INF, IsOK, SBStationID::isValidId(), Log, SB_TRF::lookupNearest(), SB_TRF::lookupStation(), SBNamed::name(), SBStation::OrigEdited, SBStation::r_first(), SBAploWave::setAccel(), SBStation::setCoords(), SBAploWaveAmpls::setCosE(), SBAploWaveAmpls::setCosN(), SBAploWaveAmpls::setCosU(), SBAploWave::setFreq(), SBAploWave::setPhase(), SBAploWaveAmpls::setSinE(), SBAploWaveAmpls::setSinN(), SBAploWaveAmpls::setSinU(), SBStation::setV(), SBSite::setV(), SBStation::site(), SiteAmplitudeByDomes, SiteAmplitudes, SBLog::STATION, TECH_ANY, SBLog::TIDES, SBStationID::toString(), TZero, SBSite::v(), v3Unit, v3Zero, SBPMNNR_NUVEL1A::velocity(), SBAploSiteAmpl::waveByName(), WaveByName, Waves, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS\&.
.PP
Referenced by SBStuffAplo::importHPS()\&.
.SS "double SBAploEphem::interval () const\fC [inline]\fP"
.PP
Definition at line 474 of file SbGeoAtmLoad\&.H'\&.
.PP
References Interval\&.
.PP
Referenced by displacement(), SBTestAPLoad::fillData4Plotting(), getReady(), SBRunManager::process_m1(), and SBTestAPLoad::SBTestAPLoad()\&.
.SS "bool SBAploEphem::isOK () const\fC [inline]\fP"
.PP
Definition at line 478 of file SbGeoAtmLoad\&.H'\&.
.PP
References IsOK\&.
.PP
Referenced by SBStuffAplo::SBStuffAplo(), and SBStuffAplo::updateEphem()\&.
.SS "void SBAploEphem::loadChunk (\fBSBAploHeader\fP *Hdr, \fBSBAploChunk\fP *&Chunk)"
.PP
Definition at line 601 of file SbGeoAtmLoad\&.C'\&.
.PP
References SBFCList::close(), ext(), SBSetUp::fcList(), SBAploHeader::name(), SBFCList::open4In(), SBSetUp::path2StuffAplo(), and SetUp\&.
.PP
Referenced by getReady(), SBStuffAplo::headerChanged(), and SBStuffAplo::SBStuffAplo()\&.
.SS "virtual QDataStream& SBAploEphem::read (QDataStream &s, QCollection::Item &Entry)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 433 of file SbGeoAtmLoad\&.H'\&.
.SS "void SBAploEphem::registerStation (\fBSBStation\fP *Station)"
.PP
Definition at line 886 of file SbGeoAtmLoad\&.C'\&.
.PP
References ClassName(), SBStation::id(), Log, SBNamed::name(), SiteByID, Sites, SBLog::STATION, SBStationID::toString(), SBLog::write(), and SBLog::WRN\&.
.PP
Referenced by SBTestAPLoad::fillData4Plotting(), and SBRunManager::process_m1()\&.
.SS "void SBAploEphem::saveChunk (\fBSBAploChunk\fP *Chunk)"
.PP
Definition at line 582 of file SbGeoAtmLoad\&.C'\&.
.PP
References ClassName(), SBFCList::close(), SBLog::DATA, SBLog::ERR, ext(), SBSetUp::fcList(), Log, SBAploHeader::name(), SBFCList::open4Out(), SBSetUp::path2StuffAplo(), SetUp, and SBLog::write()\&.
.PP
Referenced by importEphem()\&.
.SS "void SBAploEphem::setTFinis (const \fBSBMJD\fP &T_)\fC [inline]\fP"
.PP
Definition at line 473 of file SbGeoAtmLoad\&.H'\&.
.PP
References TFinis\&.
.SS "void SBAploEphem::setTStart (const \fBSBMJD\fP &T_)\fC [inline]\fP"
.PP
Definition at line 471 of file SbGeoAtmLoad\&.H'\&.
.PP
References TStart\&.
.SS "\fBSBSpline\fP* SBAploEphem::spline4station (const \fBSBStationID\fP &ID)\fC [inline]\fP"
.PP
Definition at line 488 of file SbGeoAtmLoad\&.H'\&.
.PP
References SplineByID, and SBStationID::toString()\&.
.PP
Referenced by SBTestAPLoad::fillData4Plotting()\&.
.SS "const \fBSBMJD\fP& SBAploEphem::tFinis () const\fC [inline]\fP"
.PP
Definition at line 472 of file SbGeoAtmLoad\&.H'\&.
.PP
References TFinis\&.
.PP
Referenced by checkEphem(), SBStuffAplo::SBStuffAplo(), SBTestAPLoad::SBTestAPLoad(), and SBStuffAplo::updateEphem()\&.
.SS "const \fBSBMJD\fP& SBAploEphem::tStart () const\fC [inline]\fP"
.PP
Definition at line 470 of file SbGeoAtmLoad\&.H'\&.
.PP
References TStart\&.
.PP
Referenced by SBStuffAplo::SBStuffAplo(), SBTestAPLoad::SBTestAPLoad(), and SBStuffAplo::updateEphem()\&.
.SS "virtual QDataStream& SBAploEphem::write (QDataStream &s, QCollection::ItemEntry) const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 431 of file SbGeoAtmLoad\&.H'\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBAploEphem\fP &E)\fC [friend]\fP"
.PP
Definition at line 493 of file SbGeoAtmLoad\&.H'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBAploEphem\fP &E)\fC [friend]\fP"
.PP
Definition at line 495 of file SbGeoAtmLoad\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBAploEphem::Interval\fP\fC [private]\fP"
.PP
Definition at line 441 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), interval(), and SBAploEphem()\&.
.SS "bool \fBSBAploEphem::IsOK\fP\fC [private]\fP"
.PP
Definition at line 442 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), importHPS(), isOK(), and SBAploEphem()\&.
.SS "QIntDict<\fBSBAploSiteAmpl\fP> \fBSBAploEphem::SiteAmplitudeByDomes\fP\fC [private]\fP"
.PP
Definition at line 454 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), displacement(), importHPS(), SBAploEphem(), and ~SBAploEphem()\&.
.SS "\fBSBAploSiteAmplList\fP \fBSBAploEphem::SiteAmplitudes\fP\fC [private]\fP"
.PP
Definition at line 453 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), importHPS(), SBAploEphem(), and ~SBAploEphem()\&.
.SS "QDict<\fBSBStationID\fP> \fBSBAploEphem::SiteByID\fP\fC [private]\fP"
.PP
Definition at line 446 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by dismissed(), registerStation(), SBAploEphem(), and ~SBAploEphem()\&.
.SS "\fBQList\fP<\fBSBStationID\fP> \fBSBAploEphem::Sites\fP\fC [private]\fP"
.PP
Definition at line 445 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by dismissed(), getReady(), registerStation(), SBAploEphem(), and ~SBAploEphem()\&.
.SS "QIntDict<\fBSBSpline\fP> \fBSBAploEphem::SplineByDomes\fP\fC [private]\fP"
.PP
Definition at line 448 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by dismissed(), displacement(), getReady(), SBAploEphem(), and ~SBAploEphem()\&.
.SS "QDict<\fBSBSpline\fP> \fBSBAploEphem::SplineByID\fP\fC [private]\fP"
.PP
Definition at line 447 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by dismissed(), displacement(), getReady(), SBAploEphem(), spline4station(), and ~SBAploEphem()\&.
.SS "\fBSBMJD\fP \fBSBAploEphem::TFinis\fP\fC [private]\fP"
.PP
Definition at line 438 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), getReady(), SBAploEphem(), setTFinis(), and tFinis()\&.
.SS "\fBSBMJD\fP \fBSBAploEphem::TPreparedFinis\fP\fC [private]\fP"
.PP
Definition at line 440 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by dismissed(), displacement(), getReady(), and SBAploEphem()\&.
.SS "\fBSBMJD\fP \fBSBAploEphem::TPreparedStart\fP\fC [private]\fP"
.PP
Definition at line 439 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by dismissed(), displacement(), getReady(), and SBAploEphem()\&.
.SS "\fBSBMJD\fP \fBSBAploEphem::TStart\fP\fC [private]\fP"
.PP
Definition at line 434 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), getReady(), SBAploEphem(), setTStart(), and tStart()\&.
.SS "QDict<\fBSBAploWave\fP> \fBSBAploEphem::WaveByName\fP\fC [private]\fP"
.PP
Definition at line 452 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), displacement(), importHPS(), SBAploEphem(), and ~SBAploEphem()\&.
.SS "\fBSBAploWaveList\fP \fBSBAploEphem::Waves\fP\fC [private]\fP"
.PP
Definition at line 451 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by checkEphem(), importHPS(), SBAploEphem(), and ~SBAploEphem()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
