.TH "SBAploHeader" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBAploHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoAtmLoad\&.H>\fP
.PP
Inherited by \fBSBAploChunk\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBAploHeader\fP ()"
.br
.ti -1c
.RI "virtual \fB~SBAploHeader\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "const \fBSBMJD\fP & \fBtStart\fP () const "
.br
.ti -1c
.RI "void \fBsetTStart\fP (const \fBSBMJD\fP &T_)"
.br
.ti -1c
.RI "const \fBSBMJD\fP & \fBtFinis\fP () const "
.br
.ti -1c
.RI "void \fBsetTFinis\fP (const \fBSBMJD\fP &T_)"
.br
.ti -1c
.RI "double \fBinterval\fP () const "
.br
.ti -1c
.RI "void \fBsetInterval\fP (double dt_)"
.br
.ti -1c
.RI "QString \fBname\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBMJD\fP \fBTStart\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBTFinis\fP"
.br
.ti -1c
.RI "double \fBInterval\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBAploHeader\fP &H)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBAploHeader\fP &H)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 132 of file SbGeoAtmLoad\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBAploHeader::SBAploHeader ()"
.PP
Definition at line 64 of file SbGeoAtmLoad\&.C'\&.
.PP
References Interval, TFinis, TStart, and TZero\&.
.SS "virtual SBAploHeader::~SBAploHeader ()\fC [inline, virtual]\fP"
.PP
Definition at line 143 of file SbGeoAtmLoad\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBAploHeader::ClassName () const\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBSBAploChunk\fP'\&.
.PP
Definition at line 144 of file SbGeoAtmLoad\&.H'\&.
.SS "double SBAploHeader::interval () const\fC [inline]\fP"
.PP
Definition at line 152 of file SbGeoAtmLoad\&.H'\&.
.PP
References Interval\&.
.PP
Referenced by SBAploChunk::import(), SBAploHeaderLI::key(), and SBAploHeaderLI::text()\&.
.SS "QString SBAploHeader::name ()\fC [inline]\fP"
.PP
Definition at line 157 of file SbGeoAtmLoad\&.H'\&.
.PP
References SBMJD::F_INTERNAL, SBMJD::toString(), and TStart\&.
.PP
Referenced by SBAploChunk::import(), SBAploEphem::loadChunk(), and SBAploEphem::saveChunk()\&.
.SS "void SBAploHeader::setInterval (doubledt_)\fC [inline]\fP"
.PP
Definition at line 153 of file SbGeoAtmLoad\&.H'\&.
.PP
References Interval\&.
.PP
Referenced by SBAploChunk::import()\&.
.SS "void SBAploHeader::setTFinis (const \fBSBMJD\fP &T_)\fC [inline]\fP"
.PP
Definition at line 151 of file SbGeoAtmLoad\&.H'\&.
.PP
References TFinis\&.
.PP
Referenced by SBAploChunk::import()\&.
.SS "void SBAploHeader::setTStart (const \fBSBMJD\fP &T_)\fC [inline]\fP"
.PP
Definition at line 149 of file SbGeoAtmLoad\&.H'\&.
.PP
References TStart\&.
.PP
Referenced by SBAploChunk::import()\&.
.SS "const \fBSBMJD\fP& SBAploHeader::tFinis () const\fC [inline]\fP"
.PP
Definition at line 150 of file SbGeoAtmLoad\&.H'\&.
.PP
References TFinis\&.
.PP
Referenced by SBAploHeaderLI::key(), and SBAploHeaderLI::text()\&.
.SS "const \fBSBMJD\fP& SBAploHeader::tStart () const\fC [inline]\fP"
.PP
Definition at line 148 of file SbGeoAtmLoad\&.H'\&.
.PP
References TStart\&.
.PP
Referenced by SBAploChunk::import(), SBAploEphem::importEphem(), SBAploHeaderLI::key(), and SBAploHeaderLI::text()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBAploHeader\fP &H)\fC [friend]\fP"
.PP
Definition at line 161 of file SbGeoAtmLoad\&.H'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBAploHeader\fP &H)\fC [friend]\fP"
.PP
Definition at line 163 of file SbGeoAtmLoad\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBAploHeader::Interval\fP\fC [private]\fP"
.PP
Definition at line 137 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by interval(), SBAploHeader(), and setInterval()\&.
.SS "\fBSBMJD\fP \fBSBAploHeader::TFinis\fP\fC [private]\fP"
.PP
Definition at line 136 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by SBAploHeader(), setTFinis(), and tFinis()\&.
.SS "\fBSBMJD\fP \fBSBAploHeader::TStart\fP\fC [private]\fP"
.PP
Definition at line 135 of file SbGeoAtmLoad\&.H'\&.
.PP
Referenced by name(), SBAploHeader(), setTStart(), and tStart()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
