SBAploHeaderLI
NAME
SBAploHeaderLI -
SYNOPSIS
#include <SbIStuff.H>
Inherits QListViewItem'.
Public Member Functions
SBAploHeaderLI (QListView *parent, SBAploHeader *H_)
virtual ~SBAploHeaderLI ()
virtual QString ClassName () const
virtual QString text (int) const
QString key (int, bool) const
SBAploHeader * header ()
Private Attributes
SBAploHeader * Header
Detailed Description
Definition at line 187 of file SbIStuff.H'.
Constructor & Destructor Documentation
SBAploHeaderLI::SBAploHeaderLI (QListView *parent, SBAploHeader *H_) [inline]
Definition at line 192 of file SbIStuff.H'.
References Header.
virtual SBAploHeaderLI::~SBAploHeaderLI () [inline, virtual]
Definition at line 193 of file SbIStuff.H'.
Member Function Documentation
virtual QString SBAploHeaderLI::ClassName () const [inline, virtual]
Definition at line 194 of file SbIStuff.H'.
SBAploHeader* SBAploHeaderLI::header () [inline]
Definition at line 197 of file SbIStuff.H'.
References Header.
QString SBAploHeaderLI::key (intcol, bool) const
Definition at line 866 of file SbIStuff.C'.
References SBMJD::F_INTERNAL, Header, SBAploHeader::interval(), SBAploHeader::tFinis(), TmpString, SBMJD::toString(), and SBAploHeader::tStart().
QString SBAploHeaderLI::text (intcol) const [virtual]
Definition at line 846 of file SbIStuff.C'.
References SBMJD::F_YYYYMMDDHHMMSSSS, Header, SBAploHeader::interval(), SBAploHeader::tFinis(), TmpString, SBMJD::toString(), and SBAploHeader::tStart().
Member Data Documentation
SBAploHeader* SBAploHeaderLI::Header [private]
Definition at line 190 of file SbIStuff.H'.
Referenced by header(), key(), SBAploHeaderLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.