SBAploEphem
NAME
SBAploEphem -
SYNOPSIS
#include <SbGeoAtmLoad.H>
Inherits QList< SBAploHeader >'.
Public Member Functions
SBAploEphem ()
virtual ~SBAploEphem ()
virtual QString ClassName () const
const SBMJD & tStart () const
void setTStart (const SBMJD &T_)
const SBMJD & tFinis () const
void setTFinis (const SBMJD &T_)
double interval () const
bool isOK () const
bool importEphem (const QString &, SB_TRF *, bool &)
void importHPS (const QString &, SB_TRF *)
void saveChunk (SBAploChunk *)
void loadChunk (SBAploHeader *, SBAploChunk *&)
void registerStation (SBStation *)
void getReady (const SBMJD &, const SBMJD &)
void dismissed ()
Vector3 displacement (const SBStationID &, const SBMJD &)
SBSpline * spline4station (const SBStationID &ID)
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Private Member Functions
void checkEphem (bool=TRUE)
QString ext () const
Private Attributes
SBMJD TStart
SBMJD TFinis
SBMJD TPreparedStart
SBMJD TPreparedFinis
double Interval
bool IsOK
QList< SBStationID > Sites
QDict< SBStationID > SiteByID
QDict< SBSpline > SplineByID
QIntDict< SBSpline > SplineByDomes
SBAploWaveList Waves
QDict< SBAploWave > WaveByName
SBAploSiteAmplList SiteAmplitudes
QIntDict< SBAploSiteAmpl > SiteAmplitudeByDomes
Friends
QDataStream & operator<< (QDataStream &s, const SBAploEphem &E)
QDataStream & operator>> (QDataStream &s, SBAploEphem &E)
Detailed Description
Definition at line 422 of file SbGeoAtmLoad.H'.
Constructor & Destructor Documentation
SBAploEphem::SBAploEphem ()
Definition at line 494 of file SbGeoAtmLoad.C'.
References checkEphem(), Interval, IsOK, SiteAmplitudeByDomes, SiteAmplitudes, SiteByID, Sites, SplineByDomes, SplineByID, TFinis, TPreparedFinis, TPreparedStart, TStart, TZero, WaveByName, and Waves.
SBAploEphem::~SBAploEphem () [virtual]
Definition at line 517 of file SbGeoAtmLoad.C'.
References SiteAmplitudeByDomes, SiteAmplitudes, SiteByID, Sites, SplineByDomes, SplineByID, WaveByName, and Waves.
Member Function Documentation
void SBAploEphem::checkEphem (boolIsNeedCheckDicts = TRUE) [private]
Definition at line 537 of file SbGeoAtmLoad.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, Interval, IsOK, Log, SiteAmplitudeByDomes, SiteAmplitudes, TFinis, tFinis(), TStart, TZero, WaveByName, Waves, and SBLog::write().
Referenced by importEphem(), importHPS(), and SBAploEphem().
virtual QString SBAploEphem::ClassName () const [inline, virtual]
Definition at line 466 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), displacement(), getReady(), importHPS(), registerStation(), and saveChunk().
virtual int SBAploEphem::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 425 of file SbGeoAtmLoad.H'.
void SBAploEphem::dismissed ()
Definition at line 1032 of file SbGeoAtmLoad.C'.
References SiteByID, Sites, SplineByDomes, SplineByID, TPreparedFinis, TPreparedStart, and TZero.
Referenced by SBTestAPLoad::fillData4Plotting(), and SBRunManager::process_m1().
Vector3 SBAploEphem::displacement (const SBStationID &ID, const SBMJD &T)
Definition at line 1042 of file SbGeoAtmLoad.C'.
References SBAploWave::angle(), ClassName(), SBLog::DBG, SBStationID::domeMajor(), EAST, SBMJD::F_Short, interval(), SBLog::isEligible(), SBSpline::isReady(), Log, NORT, Vector3::report2Log(), sincos(), SiteAmplitudeByDomes, SBSpline::spline(), SplineByDomes, SplineByID, SBLog::STATION, SBLog::TIDES, SBStationID::toString(), TPreparedFinis, TPreparedStart, v3Zero, VERT, WaveByName, SBLog::write(), and SBLog::WRN.
Referenced by SBStation::calcDisplacement(), and SBTestAPLoad::fillData4Plotting().
QString SBAploEphem::ext () const [inline, private]
Definition at line 459 of file SbGeoAtmLoad.H'.
Referenced by loadChunk(), and saveChunk().
void SBAploEphem::getReady (const SBMJD &Tbegin, const SBMJD &Tend)
Definition at line 902 of file SbGeoAtmLoad.C'.
References SBSpline::b(), ClassName(), SBLog::DBG, EAST, SBAploChunk::entryByID(), SBMJD::F_Short, interval(), loadChunk(), Log, NORT, SBMatrix::set(), Sites, SplineByDomes, SplineByID, SBLog::STATION, TFinis, SBMJD::toString(), TPreparedFinis, TPreparedStart, TStart, VERT, SBLog::write(), and SBLog::WRN.
Referenced by SBTestAPLoad::fillData4Plotting(), and SBRunManager::process_m1().
bool SBAploEphem::importEphem (const QString &FileName, SB_TRF *TRF, bool &IsTRFmodified)
Definition at line 619 of file SbGeoAtmLoad.C'.
References checkEphem(), SBFCList::close(), SBSetUp::fcList(), SBAploChunk::header(), SBAploChunk::import(), SBFCList::open4In(), saveChunk(), SetUp, SBAploHeader::tStart(), and TZero.
Referenced by SBStuffAplo::import().
void SBAploEphem::importHPS (const QString &FileName, SB_TRF *TRF)
Definition at line 653 of file SbGeoAtmLoad.C'.
References SBAttributed::addAttr(), checkEphem(), ClassName(), SBLog::DATA, SBLog::DBG, SBStationID::domeMajor(), SBCatalog::epoch(), SBLog::ERR, SBAploSiteAmpl::id(), SBStation::id(), SBLog::INF, IsOK, SBStationID::isValidId(), Log, SB_TRF::lookupNearest(), SB_TRF::lookupStation(), SBNamed::name(), SBStation::OrigEdited, SBStation::r_first(), SBAploWave::setAccel(), SBStation::setCoords(), SBAploWaveAmpls::setCosE(), SBAploWaveAmpls::setCosN(), SBAploWaveAmpls::setCosU(), SBAploWave::setFreq(), SBAploWave::setPhase(), SBAploWaveAmpls::setSinE(), SBAploWaveAmpls::setSinN(), SBAploWaveAmpls::setSinU(), SBStation::setV(), SBSite::setV(), SBStation::site(), SiteAmplitudeByDomes, SiteAmplitudes, SBLog::STATION, TECH_ANY, SBLog::TIDES, SBStationID::toString(), TZero, SBSite::v(), v3Unit, v3Zero, SBPMNNR_NUVEL1A::velocity(), SBAploSiteAmpl::waveByName(), WaveByName, Waves, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBStuffAplo::importHPS().
double SBAploEphem::interval () const [inline]
Definition at line 474 of file SbGeoAtmLoad.H'.
References Interval.
Referenced by displacement(), SBTestAPLoad::fillData4Plotting(), getReady(), SBRunManager::process_m1(), and SBTestAPLoad::SBTestAPLoad().
bool SBAploEphem::isOK () const [inline]
Definition at line 478 of file SbGeoAtmLoad.H'.
References IsOK.
Referenced by SBStuffAplo::SBStuffAplo(), and SBStuffAplo::updateEphem().
void SBAploEphem::loadChunk (SBAploHeader *Hdr, SBAploChunk *&Chunk)
Definition at line 601 of file SbGeoAtmLoad.C'.
References SBFCList::close(), ext(), SBSetUp::fcList(), SBAploHeader::name(), SBFCList::open4In(), SBSetUp::path2StuffAplo(), and SetUp.
Referenced by getReady(), SBStuffAplo::headerChanged(), and SBStuffAplo::SBStuffAplo().
virtual QDataStream& SBAploEphem::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 433 of file SbGeoAtmLoad.H'.
void SBAploEphem::registerStation (SBStation *Station)
Definition at line 886 of file SbGeoAtmLoad.C'.
References ClassName(), SBStation::id(), Log, SBNamed::name(), SiteByID, Sites, SBLog::STATION, SBStationID::toString(), SBLog::write(), and SBLog::WRN.
Referenced by SBTestAPLoad::fillData4Plotting(), and SBRunManager::process_m1().
void SBAploEphem::saveChunk (SBAploChunk *Chunk)
Definition at line 582 of file SbGeoAtmLoad.C'.
References ClassName(), SBFCList::close(), SBLog::DATA, SBLog::ERR, ext(), SBSetUp::fcList(), Log, SBAploHeader::name(), SBFCList::open4Out(), SBSetUp::path2StuffAplo(), SetUp, and SBLog::write().
Referenced by importEphem().
void SBAploEphem::setTFinis (const SBMJD &T_) [inline]
Definition at line 473 of file SbGeoAtmLoad.H'.
References TFinis.
void SBAploEphem::setTStart (const SBMJD &T_) [inline]
Definition at line 471 of file SbGeoAtmLoad.H'.
References TStart.
SBSpline* SBAploEphem::spline4station (const SBStationID &ID) [inline]
Definition at line 488 of file SbGeoAtmLoad.H'.
References SplineByID, and SBStationID::toString().
Referenced by SBTestAPLoad::fillData4Plotting().
const SBMJD& SBAploEphem::tFinis () const [inline]
Definition at line 472 of file SbGeoAtmLoad.H'.
References TFinis.
Referenced by checkEphem(), SBStuffAplo::SBStuffAplo(), SBTestAPLoad::SBTestAPLoad(), and SBStuffAplo::updateEphem().
const SBMJD& SBAploEphem::tStart () const [inline]
Definition at line 470 of file SbGeoAtmLoad.H'.
References TStart.
Referenced by SBStuffAplo::SBStuffAplo(), SBTestAPLoad::SBTestAPLoad(), and SBStuffAplo::updateEphem().
virtual QDataStream& SBAploEphem::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 431 of file SbGeoAtmLoad.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBAploEphem &E) [friend]
Definition at line 493 of file SbGeoAtmLoad.H'.
QDataStream& operator>> (QDataStream &s, SBAploEphem &E) [friend]
Definition at line 495 of file SbGeoAtmLoad.H'.
Member Data Documentation
double SBAploEphem::Interval [private]
Definition at line 441 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), interval(), and SBAploEphem().
bool SBAploEphem::IsOK [private]
Definition at line 442 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), importHPS(), isOK(), and SBAploEphem().
QIntDict<SBAploSiteAmpl> SBAploEphem::SiteAmplitudeByDomes [private]
Definition at line 454 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), displacement(), importHPS(), SBAploEphem(), and ~SBAploEphem().
SBAploSiteAmplList SBAploEphem::SiteAmplitudes [private]
Definition at line 453 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), importHPS(), SBAploEphem(), and ~SBAploEphem().
QDict<SBStationID> SBAploEphem::SiteByID [private]
Definition at line 446 of file SbGeoAtmLoad.H'.
Referenced by dismissed(), registerStation(), SBAploEphem(), and ~SBAploEphem().
QList<SBStationID> SBAploEphem::Sites [private]
Definition at line 445 of file SbGeoAtmLoad.H'.
Referenced by dismissed(), getReady(), registerStation(), SBAploEphem(), and ~SBAploEphem().
QIntDict<SBSpline> SBAploEphem::SplineByDomes [private]
Definition at line 448 of file SbGeoAtmLoad.H'.
Referenced by dismissed(), displacement(), getReady(), SBAploEphem(), and ~SBAploEphem().
QDict<SBSpline> SBAploEphem::SplineByID [private]
Definition at line 447 of file SbGeoAtmLoad.H'.
Referenced by dismissed(), displacement(), getReady(), SBAploEphem(), spline4station(), and ~SBAploEphem().
SBMJD SBAploEphem::TFinis [private]
Definition at line 438 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), getReady(), SBAploEphem(), setTFinis(), and tFinis().
SBMJD SBAploEphem::TPreparedFinis [private]
Definition at line 440 of file SbGeoAtmLoad.H'.
Referenced by dismissed(), displacement(), getReady(), and SBAploEphem().
SBMJD SBAploEphem::TPreparedStart [private]
Definition at line 439 of file SbGeoAtmLoad.H'.
Referenced by dismissed(), displacement(), getReady(), and SBAploEphem().
SBMJD SBAploEphem::TStart [private]
Definition at line 434 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), getReady(), SBAploEphem(), setTStart(), and tStart().
QDict<SBAploWave> SBAploEphem::WaveByName [private]
Definition at line 452 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), displacement(), importHPS(), SBAploEphem(), and ~SBAploEphem().
SBAploWaveList SBAploEphem::Waves [private]
Definition at line 451 of file SbGeoAtmLoad.H'.
Referenced by checkEphem(), importHPS(), SBAploEphem(), and ~SBAploEphem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.