SBAttributed
NAME
SBAttributed -
SYNOPSIS
#include <SbGeneral.H>
Inherited by SBCelestBody, SBCoordinates, SBDerivation, SBFilterGauss, SBFilterModel, SBMasterFile, SBMasterRecord, SBMEM, SBObjectObsInfo, SBObservation, SBObsVLBIStatRecord, SBSource, SBSrcMap, SBStation, and SBVLBISesInfo'.
Public Member Functions
SBAttributed ()
SBAttributed (const SBAttributed &A)
SBAttributed & operator= (const SBAttributed &A)
virtual ~SBAttributed ()
virtual QString ClassName () const
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Private Attributes
uint Attr
storage for 32 different attributes (is it enough?)
Friends
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Class SBAttributed'. It describes features of classes with attributes'. Other classes have to inherit this one'.
Definition at line 225 of file SbGeneral.H'.
Constructor & Destructor Documentation
SBAttributed::SBAttributed () [inline]"A constructor'.
Definition at line 231 of file SbGeneral.H'.
References Attr.
SBAttributed::SBAttributed (const SBAttributed &A) [inline]"A constructor'.
Definition at line 233 of file SbGeneral.H'.
References Attr.
virtual SBAttributed::~SBAttributed () [inline, virtual]"A destructor'.
Definition at line 236 of file SbGeneral.H'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
uint SBAttributed::attributes () const [inline]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBAttributed::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented in SBMasterFile, SBMasterRecord, SBVLBISession, SBVLBISesInfo, SBObsVLBIEntry, SBStochParameter, SBStation, SBSourceInfo, SBParameter, SBBaseInfo, SBCoordinates, SBDerivation, SBStationInfo, SBObsVLBIStatStation, SBFilterGauss, SBObsVLBIStatSource, SBSource, SBMEM, SBSrcMap, SBFilterModel, SBSINEXParameter, SBObjectObsInfo, SBCelestBody, SBObservation, and SBObsVLBIStatRecord'.
Definition at line 238 of file SbGeneral.H'.
void SBAttributed::clearAll () [inline]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References Attr.
void SBAttributed::delAttr (uintA_) [inline]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
bool SBAttributed::isAttr (uintA_) const [inline]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
SBAttributed& SBAttributed::operator= (const SBAttributed &A) [inline]
Definition at line 234 of file SbGeneral.H'.
References Attr.
void SBAttributed::setAttributes (uintA_) [inline]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBAttributed::xorAttr (uintA_) [inline]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend]
Definition at line 260 of file SbGeneral.H'.
Member Data Documentation
uint SBAttributed::Attr [private]
storage for 32 different attributes (is it enough?)
Definition at line 228 of file SbGeneral.H'.
Referenced by addAttr(), attributes(), clearAll(), delAttr(), isAttr(), operator=(), SBAttributed(), setAttributes(), and xorAttr().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.