SBBaseInfoList
NAME
SBBaseInfoList -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits QList< SBBaseInfo >'.
Public Member Functions
virtual QString ClassName () const
virtual SBBaseInfo * find (const SBNamed *item)
void dumpUserInfo (QTextStream &ts)
bool restoreUserInfo (QTextStream &)
virtual void clearRMSs ()
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Detailed Description
List of bases infos'.
Definition at line 410 of file SbGeoObsVLBI.H'.
Member Function Documentation
virtual QString SBBaseInfoList::ClassName () const [inline, virtual]
Definition at line 421 of file SbGeoObsVLBI.H'.
Referenced by restoreUserInfo().
virtual void SBBaseInfoList::clearRMSs () [inline, virtual]
Definition at line 430 of file SbGeoObsVLBI.H'.
Referenced by SBProject::clearRMSs(), and SBVLBISession::clearRMSs().
virtual int SBBaseInfoList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 413 of file SbGeoObsVLBI.H'.
void SBBaseInfoList::dumpUserInfo (QTextStream &ts) [inline]
Definition at line 427 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISession::dumpUserInfo().
virtual SBBaseInfo* SBBaseInfoList::find (const SBNamed *item) [inline, virtual]
Definition at line 422 of file SbGeoObsVLBI.H'.
Referenced by SBObsVLBIEntry::isEligible(), SBObsVLBIEntry::process(), and restoreUserInfo().
virtual QDataStream& SBBaseInfoList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 418 of file SbGeoObsVLBI.H'.
bool SBBaseInfoList::restoreUserInfo (QTextStream &ts)
Definition at line 386 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::DBG, find(), SBStationID::isValidId(), Log, SBBaseInfo::restoreUserInfo(), SBStationID::setID(), SBNamed::setName(), SBStationID::toString(), and SBLog::write().
Referenced by SBVLBISession::restoreUserInfo().
virtual QDataStream& SBBaseInfoList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 416 of file SbGeoObsVLBI.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.