SBBasInfoLI
NAME
SBBasInfoLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QListViewItem'.
Public Member Functions
SBBasInfoLI (QListView *parent, SBBaseInfo *BI_)
virtual QString ClassName () const
SBBaseInfo * baseInfo ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBBaseInfo * BasInf
Detailed Description
Definition at line 153 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBBasInfoLI::SBBasInfoLI (QListView *parent, SBBaseInfo *BI_) [inline]
Definition at line 158 of file SbIObsVLBI.H'.
References BasInf.
Member Function Documentation
SBBaseInfo* SBBasInfoLI::baseInfo () [inline]
Definition at line 160 of file SbIObsVLBI.H'.
References BasInf.
virtual QString SBBasInfoLI::ClassName () const [inline, virtual]
Definition at line 159 of file SbIObsVLBI.H'.
QString SBBasInfoLI::key (intcol, bool) const [virtual]
Definition at line 739 of file SbIObsVLBI.C'.
References SBObjectObsInfo::aka(), BasInf, SBObjectObsInfo::idx(), SBAttributed::isAttr(), SBNamed::name(), SBBaseInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBSetUp::scale(), SetUp, TmpString, and SBObjectObsInfo::wrms().
QString SBBasInfoLI::text (intcol) const [virtual]
Definition at line 715 of file SbIObsVLBI.C'.
References SBObjectObsInfo::aka(), BasInf, SBObjectObsInfo::idx(), SBAttributed::isAttr(), SBNamed::name(), SBBaseInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBSetUp::scale(), SetUp, TmpString, and SBObjectObsInfo::wrms().
Member Data Documentation
SBBaseInfo* SBBasInfoLI::BasInf [private]
Definition at line 156 of file SbIObsVLBI.H'.
Referenced by baseInfo(), key(), SBBasInfoLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.