.TH "SBBrowseSources" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBBrowseSources \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBI\&.H>\fP
.PP
Inherits \fBQWidget\fP'\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmodified\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBBrowseSources\fP (\fBSBSourceInfoList\fP *, \fBBrowseMode\fP, \fBSB_CRF\fP *, \fBQWidget\fP *, const char *=0, WFlags=0)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "\fBQListView\fP * \fBlvSources\fP ()"
.br
.ti -1c
.RI "const \fBSBSourceInfoList\fP * \fBsouInfoList\fP () const "
.br
.ti -1c
.RI "void \fBsetSouInfoList\fP (\fBSBSourceInfoList\fP *)"
.br
.ti -1c
.RI "void \fBupdateList\fP (\fBSB_CRF\fP *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSBSourceInfoList\fP * \fBSouInfoList\fP"
.br
.ti -1c
.RI "\fBSBListView\fP * \fBLVSources\fP"
.br
.ti -1c
.RI "\fBBrowseMode\fP \fBMode\fP"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBtoggleEntryMarkEnable\fP (\fBQListViewItem\fP *, const QPoint &, int)"
.br
.ti -1c
.RI "void \fBtoggleEntryMoveEnable\fP (\fBQListViewItem\fP *, int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 318 of file SbIObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBBrowseSources::SBBrowseSources (\fBSBSourceInfoList\fP *SIList_, \fBBrowseMode\fPMode_, \fBSB_CRF\fP *CRF, \fBQWidget\fP *parent, const char *name = \fC0\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 1394 of file SbIObsVLBI\&.C'\&.
.PP
References BM_GENERAL, BM_PROJECT, LVSources, Mode, SBSetUp::scaleName(), SetUp, SouInfoList, toggleEntryMoveEnable(), and updateList()\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBBrowseSources::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 333 of file SbIObsVLBI\&.H'\&.
.SS "\fBQListView\fP* SBBrowseSources::lvSources ()\fC [inline]\fP"
.PP
Definition at line 334 of file SbIObsVLBI\&.H'\&.
.PP
References LVSources\&.
.SS "void SBBrowseSources::modified (boolt0)\fC [signal]\fP"
.PP
Definition at line 254 of file SbIObsVLBI\&.moc\&.C'\&.
.PP
Referenced by toggleEntryMarkEnable(), and toggleEntryMoveEnable()\&.
.SS "void SBBrowseSources::setSouInfoList (\fBSBSourceInfoList\fP *SIList_)"
.PP
Definition at line 1473 of file SbIObsVLBI\&.C'\&.
.PP
References LVSources, SouInfoList, and updateList()\&.
.PP
Referenced by SBVLBIPreProcess::updateSession()\&.
.SS "const \fBSBSourceInfoList\fP* SBBrowseSources::souInfoList () const\fC [inline]\fP"
.PP
Definition at line 335 of file SbIObsVLBI\&.H'\&.
.PP
References SouInfoList\&.
.SS "void SBBrowseSources::toggleEntryMarkEnable (\fBQListViewItem\fP *Item, const QPoint &, intn)\fC [private, slot]\fP"
.PP
Definition at line 1485 of file SbIObsVLBI\&.C'\&.
.PP
References BM_GENERAL, BM_PROJECT, SBSourceInfo::ConstrCoo, SBSourceInfo::EstCoo, Mode, modified(), and SBSourceInfo::notValid\&.
.SS "void SBBrowseSources::toggleEntryMoveEnable (\fBQListViewItem\fP *Item, intn)\fC [private, slot]\fP"
.PP
Definition at line 1522 of file SbIObsVLBI\&.C'\&.
.PP
References BM_GENERAL, BM_PROJECT, SBSourceInfo::ConstrCoo, SBSourceInfo::EstCoo, Mode, modified(), and SBSourceInfo::notValid\&.
.PP
Referenced by SBBrowseSources()\&.
.SS "void SBBrowseSources::updateList (\fBSB_CRF\fP *CRF)"
.PP
Definition at line 1454 of file SbIObsVLBI\&.C'\&.
.PP
References SB_CRF::find(), SBAttributed::isAttr(), LVSources, Mode, SouInfoList, SBSource::status(), SBSource::StatusSuspected, and SBSource::type()\&.
.PP
Referenced by SBBrowseSources(), SBProjectEdit::sessionListChanged(), and setSouInfoList()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBListView\fP* \fBSBBrowseSources::LVSources\fP\fC [protected]\fP"
.PP
Definition at line 323 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by lvSources(), SBBrowseSources(), setSouInfoList(), and updateList()\&.
.SS "\fBBrowseMode\fP \fBSBBrowseSources::Mode\fP\fC [protected]\fP"
.PP
Definition at line 324 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBBrowseSources(), toggleEntryMarkEnable(), toggleEntryMoveEnable(), and updateList()\&.
.SS "\fBSBSourceInfoList\fP* \fBSBBrowseSources::SouInfoList\fP\fC [protected]\fP"
.PP
Definition at line 322 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBBrowseSources(), setSouInfoList(), souInfoList(), and updateList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
