.TH "SBBrowseStations" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBBrowseStations \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBI\&.H>\fP
.PP
Inherits \fBQWidget\fP'\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBwidgetIsBusy\fP (bool)"
.br
.ti -1c
.RI "void \fBmodified\fP (bool)"
.br
.ti -1c
.RI "void \fBrefClockChanged\fP (\fBSBStationInfo\fP *)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBBrowseStations\fP (\fBSBStationInfoList\fP *, \fBBrowseMode\fP, const \fBSBMJD\fP &, \fBQWidget\fP *=0, const char *=0, WFlags=0)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "\fBQListView\fP * \fBlvStations\fP ()"
.br
.ti -1c
.RI "const \fBSBStationInfoList\fP * \fBstaInfoList\fP () const "
.br
.ti -1c
.RI "\fBBrowseMode\fP \fBmode\fP () const "
.br
.ti -1c
.RI "void \fBupdateList\fP ()"
.br
.ti -1c
.RI "void \fBsetStaInfoList\fP (\fBSBStationInfoList\fP *)"
.br
.ti -1c
.RI "void \fBsetT0\fP (const \fBSBMJD\fP &T0_)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSBStationInfoList\fP * \fBStaInfoList\fP"
.br
.ti -1c
.RI "\fBSBListView\fP * \fBLVStations\fP"
.br
.ti -1c
.RI "\fBBrowseMode\fP \fBMode\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBT0\fP"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBtoggleEntryMarkEnable\fP (int, \fBQListViewItem\fP *, const QPoint &, int)"
.br
.ti -1c
.RI "void \fBtoggleEntryMoveEnable\fP (\fBQListViewItem\fP *, int)"
.br
.ti -1c
.RI "void \fBeditEntry\fP (\fBQListViewItem\fP *)"
.br
.ti -1c
.RI "void \fBstainfoModified\fP (bool)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 277 of file SbIObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBBrowseStations::SBBrowseStations (\fBSBStationInfoList\fP *SIList_, \fBBrowseMode\fPMode_, const \fBSBMJD\fP &T0_, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 1123 of file SbIObsVLBI\&.C'\&.
.PP
References BM_GENERAL, BM_PROJECT, editEntry(), LVStations, Mode, SBSetUp::scaleName(), SetUp, StaInfoList, T0, toggleEntryMarkEnable(), toggleEntryMoveEnable(), and updateList()\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBBrowseStations::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 296 of file SbIObsVLBI\&.H'\&.
.SS "void SBBrowseStations::editEntry (\fBQListViewItem\fP *Item)\fC [private, slot]\fP"
.PP
Definition at line 1214 of file SbIObsVLBI\&.C'\&.
.PP
References stainfoModified(), T0, and widgetIsBusy()\&.
.PP
Referenced by SBBrowseStations()\&.
.SS "\fBQListView\fP* SBBrowseStations::lvStations ()\fC [inline]\fP"
.PP
Definition at line 297 of file SbIObsVLBI\&.H'\&.
.PP
References LVStations\&.
.PP
Referenced by SBVLBIPreProcess::blockInput(), and SBVLBIPreProcess::restoreInput()\&.
.SS "\fBBrowseMode\fP SBBrowseStations::mode () const\fC [inline]\fP"
.PP
Definition at line 299 of file SbIObsVLBI\&.H'\&.
.PP
References Mode\&.
.SS "void SBBrowseStations::modified (boolt0)\fC [signal]\fP"
.PP
Definition at line 130 of file SbIObsVLBI\&.moc\&.C'\&.
.PP
Referenced by stainfoModified(), toggleEntryMarkEnable(), and toggleEntryMoveEnable()\&.
.SS "void SBBrowseStations::refClockChanged (\fBSBStationInfo\fP *t0)\fC [signal]\fP"
.PP
Definition at line 139 of file SbIObsVLBI\&.moc\&.C'\&.
.PP
Referenced by toggleEntryMarkEnable()\&.
.SS "void SBBrowseStations::setStaInfoList (\fBSBStationInfoList\fP *SIList_)"
.PP
Definition at line 1228 of file SbIObsVLBI\&.C'\&.
.PP
References LVStations, StaInfoList, and updateList()\&.
.PP
Referenced by SBVLBIPreProcess::updateSession()\&.
.SS "void SBBrowseStations::setT0 (const \fBSBMJD\fP &T0_)\fC [inline]\fP"
.PP
Definition at line 302 of file SbIObsVLBI\&.H'\&.
.PP
References T0\&.
.PP
Referenced by SBVLBIPreProcess::updateSession()\&.
.SS "const \fBSBStationInfoList\fP* SBBrowseStations::staInfoList () const\fC [inline]\fP"
.PP
Definition at line 298 of file SbIObsVLBI\&.H'\&.
.PP
References StaInfoList\&.
.SS "void SBBrowseStations::stainfoModified (boolIsModified_)\fC [private, slot]\fP"
.PP
Definition at line 1222 of file SbIObsVLBI\&.C'\&.
.PP
References modified(), and widgetIsBusy()\&.
.PP
Referenced by editEntry()\&.
.SS "void SBBrowseStations::toggleEntryMarkEnable (intbutton, \fBQListViewItem\fP *Item, const QPoint &, intn)\fC [private, slot]\fP"
.PP
Definition at line 1241 of file SbIObsVLBI\&.C'\&.
.PP
References SBStationInfo::ArtMeteo, BM_GENERAL, BM_PROJECT, SBStationInfo::InvCable, Mode, modified(), SBStationInfo::refClock, refClockChanged(), SBStationInfo::UseLocalClocks, and SBStationInfo::UseLocalZenith\&.
.PP
Referenced by SBBrowseStations()\&.
.SS "void SBBrowseStations::toggleEntryMoveEnable (\fBQListViewItem\fP *Item, intn)\fC [private, slot]\fP"
.PP
Definition at line 1337 of file SbIObsVLBI\&.C'\&.
.PP
References BM_GENERAL, BM_PROJECT, SBStationInfo::ConstrCoo, SBStationInfo::ConstrVel, SBStationInfo::EstCoo, SBStationInfo::EstVel, Mode, modified(), and SBStationInfo::notValid\&.
.PP
Referenced by SBBrowseStations()\&.
.SS "void SBBrowseStations::updateList ()"
.PP
Definition at line 1207 of file SbIObsVLBI\&.C'\&.
.PP
References LVStations, Mode, and StaInfoList\&.
.PP
Referenced by SBBrowseStations(), SBProjectEdit::sessionListChanged(), and setStaInfoList()\&.
.SS "void SBBrowseStations::widgetIsBusy (boolt0)\fC [signal]\fP"
.PP
Definition at line 124 of file SbIObsVLBI\&.moc\&.C'\&.
.PP
Referenced by editEntry(), and stainfoModified()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBListView\fP* \fBSBBrowseStations::LVStations\fP\fC [protected]\fP"
.PP
Definition at line 283 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by lvStations(), SBBrowseStations(), setStaInfoList(), and updateList()\&.
.SS "\fBBrowseMode\fP \fBSBBrowseStations::Mode\fP\fC [protected]\fP"
.PP
Definition at line 284 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by mode(), SBBrowseStations(), toggleEntryMarkEnable(), toggleEntryMoveEnable(), and updateList()\&.
.SS "\fBSBStationInfoList\fP* \fBSBBrowseStations::StaInfoList\fP\fC [protected]\fP"
.PP
Definition at line 282 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBBrowseStations(), setStaInfoList(), staInfoList(), and updateList()\&.
.SS "\fBSBMJD\fP \fBSBBrowseStations::T0\fP\fC [protected]\fP"
.PP
Definition at line 285 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by editEntry(), SBBrowseStations(), and setT0()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
