SBBrowseStations
NAME
SBBrowseStations -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QWidget'.
Signals
void widgetIsBusy (bool)
void modified (bool)
void refClockChanged (SBStationInfo *)
Public Member Functions
SBBrowseStations (SBStationInfoList *, BrowseMode, const SBMJD &, QWidget *=0, const char *=0, WFlags=0)
virtual QString ClassName () const
QListView * lvStations ()
const SBStationInfoList * staInfoList () const
BrowseMode mode () const
void updateList ()
void setStaInfoList (SBStationInfoList *)
void setT0 (const SBMJD &T0_)
Protected Attributes
SBStationInfoList * StaInfoList
SBListView * LVStations
BrowseMode Mode
SBMJD T0
Private Slots
void toggleEntryMarkEnable (int, QListViewItem *, const QPoint &, int)
void toggleEntryMoveEnable (QListViewItem *, int)
void editEntry (QListViewItem *)
void stainfoModified (bool)
Detailed Description
Definition at line 277 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBBrowseStations::SBBrowseStations (SBStationInfoList *SIList_, BrowseModeMode_, const SBMJD &T0_, QWidget *parent = 0, const char *name = 0, WFlagsf = 0)
Definition at line 1123 of file SbIObsVLBI.C'.
References BM_GENERAL, BM_PROJECT, editEntry(), LVStations, Mode, SBSetUp::scaleName(), SetUp, StaInfoList, T0, toggleEntryMarkEnable(), toggleEntryMoveEnable(), and updateList().
Member Function Documentation
virtual QString SBBrowseStations::ClassName () const [inline, virtual]
Definition at line 296 of file SbIObsVLBI.H'.
void SBBrowseStations::editEntry (QListViewItem *Item) [private, slot]
Definition at line 1214 of file SbIObsVLBI.C'.
References stainfoModified(), T0, and widgetIsBusy().
Referenced by SBBrowseStations().
QListView* SBBrowseStations::lvStations () [inline]
Definition at line 297 of file SbIObsVLBI.H'.
References LVStations.
Referenced by SBVLBIPreProcess::blockInput(), and SBVLBIPreProcess::restoreInput().
BrowseMode SBBrowseStations::mode () const [inline]
Definition at line 299 of file SbIObsVLBI.H'.
References Mode.
void SBBrowseStations::modified (boolt0) [signal]
Definition at line 130 of file SbIObsVLBI.moc.C'.
Referenced by stainfoModified(), toggleEntryMarkEnable(), and toggleEntryMoveEnable().
void SBBrowseStations::refClockChanged (SBStationInfo *t0) [signal]
Definition at line 139 of file SbIObsVLBI.moc.C'.
Referenced by toggleEntryMarkEnable().
void SBBrowseStations::setStaInfoList (SBStationInfoList *SIList_)
Definition at line 1228 of file SbIObsVLBI.C'.
References LVStations, StaInfoList, and updateList().
Referenced by SBVLBIPreProcess::updateSession().
void SBBrowseStations::setT0 (const SBMJD &T0_) [inline]
Definition at line 302 of file SbIObsVLBI.H'.
References T0.
Referenced by SBVLBIPreProcess::updateSession().
const SBStationInfoList* SBBrowseStations::staInfoList () const [inline]
Definition at line 298 of file SbIObsVLBI.H'.
References StaInfoList.
void SBBrowseStations::stainfoModified (boolIsModified_) [private, slot]
Definition at line 1222 of file SbIObsVLBI.C'.
References modified(), and widgetIsBusy().
Referenced by editEntry().
void SBBrowseStations::toggleEntryMarkEnable (intbutton, QListViewItem *Item, const QPoint &, intn) [private, slot]
Definition at line 1241 of file SbIObsVLBI.C'.
References SBStationInfo::ArtMeteo, BM_GENERAL, BM_PROJECT, SBStationInfo::InvCable, Mode, modified(), SBStationInfo::refClock, refClockChanged(), SBStationInfo::UseLocalClocks, and SBStationInfo::UseLocalZenith.
Referenced by SBBrowseStations().
void SBBrowseStations::toggleEntryMoveEnable (QListViewItem *Item, intn) [private, slot]
Definition at line 1337 of file SbIObsVLBI.C'.
References BM_GENERAL, BM_PROJECT, SBStationInfo::ConstrCoo, SBStationInfo::ConstrVel, SBStationInfo::EstCoo, SBStationInfo::EstVel, Mode, modified(), and SBStationInfo::notValid.
Referenced by SBBrowseStations().
void SBBrowseStations::updateList ()
Definition at line 1207 of file SbIObsVLBI.C'.
References LVStations, Mode, and StaInfoList.
Referenced by SBBrowseStations(), SBProjectEdit::sessionListChanged(), and setStaInfoList().
void SBBrowseStations::widgetIsBusy (boolt0) [signal]
Definition at line 124 of file SbIObsVLBI.moc.C'.
Referenced by editEntry(), and stainfoModified().
Member Data Documentation
SBListView* SBBrowseStations::LVStations [protected]
Definition at line 283 of file SbIObsVLBI.H'.
Referenced by lvStations(), SBBrowseStations(), setStaInfoList(), and updateList().
BrowseMode SBBrowseStations::Mode [protected]
Definition at line 284 of file SbIObsVLBI.H'.
Referenced by mode(), SBBrowseStations(), toggleEntryMarkEnable(), toggleEntryMoveEnable(), and updateList().
SBStationInfoList* SBBrowseStations::StaInfoList [protected]
Definition at line 282 of file SbIObsVLBI.H'.
Referenced by SBBrowseStations(), setStaInfoList(), staInfoList(), and updateList().
SBMJD SBBrowseStations::T0 [protected]
Definition at line 285 of file SbIObsVLBI.H'.
Referenced by editEntry(), SBBrowseStations(), and setT0().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.