SBBrowseSources
NAME
SBBrowseSources -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QWidget'.
Signals
void modified (bool)
Public Member Functions
SBBrowseSources (SBSourceInfoList *, BrowseMode, SB_CRF *, QWidget *, const char *=0, WFlags=0)
virtual QString ClassName () const
QListView * lvSources ()
const SBSourceInfoList * souInfoList () const
void setSouInfoList (SBSourceInfoList *)
void updateList (SB_CRF *)
Protected Attributes
SBSourceInfoList * SouInfoList
SBListView * LVSources
BrowseMode Mode
Private Slots
void toggleEntryMarkEnable (QListViewItem *, const QPoint &, int)
void toggleEntryMoveEnable (QListViewItem *, int)
Detailed Description
Definition at line 318 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBBrowseSources::SBBrowseSources (SBSourceInfoList *SIList_, BrowseModeMode_, SB_CRF *CRF, QWidget *parent, const char *name = 0, WFlagsf = 0)
Definition at line 1394 of file SbIObsVLBI.C'.
References BM_GENERAL, BM_PROJECT, LVSources, Mode, SBSetUp::scaleName(), SetUp, SouInfoList, toggleEntryMoveEnable(), and updateList().
Member Function Documentation
virtual QString SBBrowseSources::ClassName () const [inline, virtual]
Definition at line 333 of file SbIObsVLBI.H'.
QListView* SBBrowseSources::lvSources () [inline]
Definition at line 334 of file SbIObsVLBI.H'.
References LVSources.
void SBBrowseSources::modified (boolt0) [signal]
Definition at line 254 of file SbIObsVLBI.moc.C'.
Referenced by toggleEntryMarkEnable(), and toggleEntryMoveEnable().
void SBBrowseSources::setSouInfoList (SBSourceInfoList *SIList_)
Definition at line 1473 of file SbIObsVLBI.C'.
References LVSources, SouInfoList, and updateList().
Referenced by SBVLBIPreProcess::updateSession().
const SBSourceInfoList* SBBrowseSources::souInfoList () const [inline]
Definition at line 335 of file SbIObsVLBI.H'.
References SouInfoList.
void SBBrowseSources::toggleEntryMarkEnable (QListViewItem *Item, const QPoint &, intn) [private, slot]
Definition at line 1485 of file SbIObsVLBI.C'.
References BM_GENERAL, BM_PROJECT, SBSourceInfo::ConstrCoo, SBSourceInfo::EstCoo, Mode, modified(), and SBSourceInfo::notValid.
void SBBrowseSources::toggleEntryMoveEnable (QListViewItem *Item, intn) [private, slot]
Definition at line 1522 of file SbIObsVLBI.C'.
References BM_GENERAL, BM_PROJECT, SBSourceInfo::ConstrCoo, SBSourceInfo::EstCoo, Mode, modified(), and SBSourceInfo::notValid.
Referenced by SBBrowseSources().
void SBBrowseSources::updateList (SB_CRF *CRF)
Definition at line 1454 of file SbIObsVLBI.C'.
References SB_CRF::find(), SBAttributed::isAttr(), LVSources, Mode, SouInfoList, SBSource::status(), SBSource::StatusSuspected, and SBSource::type().
Referenced by SBBrowseSources(), SBProjectEdit::sessionListChanged(), and setSouInfoList().
Member Data Documentation
SBListView* SBBrowseSources::LVSources [protected]
Definition at line 323 of file SbIObsVLBI.H'.
Referenced by lvSources(), SBBrowseSources(), setSouInfoList(), and updateList().
BrowseMode SBBrowseSources::Mode [protected]
Definition at line 324 of file SbIObsVLBI.H'.
Referenced by SBBrowseSources(), toggleEntryMarkEnable(), toggleEntryMoveEnable(), and updateList().
SBSourceInfoList* SBBrowseSources::SouInfoList [protected]
Definition at line 322 of file SbIObsVLBI.H'.
Referenced by SBBrowseSources(), setSouInfoList(), souInfoList(), and updateList().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.