SBBrowseSessions
NAME
SBBrowseSessions -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QWidget'.
Public Member Functions
SBBrowseSessions (SBVLBISesInfoList *, BrowseMode, SBProject *=NULL, QWidget *=0, const char *=0, WFlags=0)
virtual QString ClassName () const
void updateList ()
QListView * lvSessions ()
QBoxLayout * layout ()
const SBVLBISesInfoList * sesInfoList () const
int numPPSess () const
int numObs () const
Protected Attributes
SBProject * Project
SBVLBISesInfoList * SesInfoList
QListView * LVSessions
QBoxLayout * Layout
BrowseMode BrwsMode
int NumPPSess
int NumObs
Detailed Description
Definition at line 247 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBBrowseSessions::SBBrowseSessions (SBVLBISesInfoList *SIList_, BrowseModeBrwsMode_, SBProject *Project_ = NULL, QWidget *parent = 0, const char *name = 0, WFlagsf = 0)
Definition at line 1003 of file SbIObsVLBI.C'.
References BM_PREPROCESS, BM_PROJECT, BrwsMode, Layout, LVSessions, Project, SesInfoList, and updateList().
Member Function Documentation
virtual QString SBBrowseSessions::ClassName () const [inline, virtual]
Definition at line 260 of file SbIObsVLBI.H'.
QBoxLayout* SBBrowseSessions::layout () [inline]
Definition at line 263 of file SbIObsVLBI.H'.
References Layout.
Referenced by SBVLBIPreProcess::VLBIList().
QListView* SBBrowseSessions::lvSessions () [inline]
Definition at line 262 of file SbIObsVLBI.H'.
References LVSessions.
Referenced by SBVLBIPreProcess::auxWindowsChanged(), SBVLBIPreProcess::blockInput(), SBProjectCreate::createProject(), SBVLBISetView::deleteEntry(), SBProjectEdit::delSession(), SBProjectCreate::init(), SBVLBIPreProcess::procScenario_4(), SBVLBIPreProcess::restoreInput(), SBProjectEdit::SBProjectEdit(), SBProjectCreate::selectAll(), SBProjectCreate::unselectAll(), SBVLBIPreProcess::VLBIList(), and SBVLBISetViewBase::VLBIList().
int SBBrowseSessions::numObs () const [inline]
Definition at line 266 of file SbIObsVLBI.H'.
References NumObs.
Referenced by SBProjectCreate::drawInfo(), and SBVLBISetViewBase::infoGroup().
int SBBrowseSessions::numPPSess () const [inline]
Definition at line 265 of file SbIObsVLBI.H'.
References NumPPSess.
Referenced by SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
const SBVLBISesInfoList* SBBrowseSessions::sesInfoList () const [inline]
Definition at line 264 of file SbIObsVLBI.H'.
References SesInfoList.
void SBBrowseSessions::updateList ()
Definition at line 1088 of file SbIObsVLBI.C'.
References BM_PREPROCESS, BM_PROJECT, BrwsMode, LVSessions, NumObs, NumPPSess, SBVLBISesInfo::preProc, Project, SesInfoList, and SBProject::sessionByName().
Referenced by SBProjectCreate::createProject(), SBVLBISetView::import(), SBBrowseSessions(), and SBProjectEdit::sessionListChanged().
Member Data Documentation
BrowseMode SBBrowseSessions::BrwsMode [protected]
Definition at line 254 of file SbIObsVLBI.H'.
Referenced by SBBrowseSessions(), and updateList().
QBoxLayout* SBBrowseSessions::Layout [protected]
Definition at line 253 of file SbIObsVLBI.H'.
Referenced by layout(), and SBBrowseSessions().
QListView* SBBrowseSessions::LVSessions [protected]
Definition at line 252 of file SbIObsVLBI.H'.
Referenced by lvSessions(), SBBrowseSessions(), and updateList().
int SBBrowseSessions::NumObs [protected]
Definition at line 256 of file SbIObsVLBI.H'.
Referenced by numObs(), and updateList().
int SBBrowseSessions::NumPPSess [protected]
Definition at line 255 of file SbIObsVLBI.H'.
Referenced by numPPSess(), and updateList().
SBProject* SBBrowseSessions::Project [protected]
Definition at line 250 of file SbIObsVLBI.H'.
Referenced by SBBrowseSessions(), and updateList().
SBVLBISesInfoList* SBBrowseSessions::SesInfoList [protected]
Definition at line 251 of file SbIObsVLBI.H'.
Referenced by SBBrowseSessions(), sesInfoList(), and updateList().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.