SBBrowseBases
NAME
SBBrowseBases -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QWidget'.
Signals
void modified (bool)
Public Member Functions
SBBrowseBases (SBBaseInfoList *, QWidget *=0, const char *=0, WFlags=0)
virtual QString ClassName () const
QListView * lvBases ()
const SBBaseInfoList * basInfoList () const
void setBasInfoList (SBBaseInfoList *)
void updateList ()
Protected Attributes
SBBaseInfoList * BasInfoList
QListView * LVBases
Private Slots
void toggleEntryMarkEnable (QListViewItem *, const QPoint &, int)
Detailed Description
Definition at line 351 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBBrowseBases::SBBrowseBases (SBBaseInfoList *BIList_, QWidget *parent = 0, const char *name = 0, WFlagsf = 0)
Definition at line 1567 of file SbIObsVLBI.C'.
References BasInfoList, LVBases, SBSetUp::scaleName(), SetUp, toggleEntryMarkEnable(), and updateList().
Member Function Documentation
const SBBaseInfoList* SBBrowseBases::basInfoList () const [inline]
Definition at line 366 of file SbIObsVLBI.H'.
References BasInfoList.
virtual QString SBBrowseBases::ClassName () const [inline, virtual]
Definition at line 364 of file SbIObsVLBI.H'.
QListView* SBBrowseBases::lvBases () [inline]
Definition at line 365 of file SbIObsVLBI.H'.
References LVBases.
void SBBrowseBases::modified (boolt0) [signal]
Definition at line 329 of file SbIObsVLBI.moc.C'.
Referenced by toggleEntryMarkEnable().
void SBBrowseBases::setBasInfoList (SBBaseInfoList *BIList_)
Definition at line 1613 of file SbIObsVLBI.C'.
References BasInfoList, LVBases, and updateList().
Referenced by SBVLBIPreProcess::updateSession().
void SBBrowseBases::toggleEntryMarkEnable (QListViewItem *Item, const QPoint &, intn) [private, slot]
Definition at line 1624 of file SbIObsVLBI.C'.
References modified(), and SBBaseInfo::notValid.
Referenced by SBBrowseBases().
void SBBrowseBases::updateList ()
Definition at line 1605 of file SbIObsVLBI.C'.
References BasInfoList, and LVBases.
Referenced by SBBrowseBases(), SBProjectEdit::sessionListChanged(), and setBasInfoList().
Member Data Documentation
SBBaseInfoList* SBBrowseBases::BasInfoList [protected]
Definition at line 355 of file SbIObsVLBI.H'.
Referenced by basInfoList(), SBBrowseBases(), setBasInfoList(), and updateList().
QListView* SBBrowseBases::LVBases [protected]
Definition at line 356 of file SbIObsVLBI.H'.
Referenced by lvBases(), SBBrowseBases(), setBasInfoList(), and updateList().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.