SBBrowseHistory
NAME
SBBrowseHistory -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QWidget'.
Public Slots
void incVersion ()
Signals
void modified (bool)
void versionInced ()
Public Member Functions
SBBrowseHistory (SBHistory *, SBHistory *, int, QWidget *=0, const char *=0, WFlags=0)
virtual QString ClassName () const
QListView * lvHistory ()
const SBHistory * histLocal () const
const SBHistory * histDBH () const
void setHistories (SBHistory *, SBHistory *, int)
Protected Slots
void deleteHistoryLine ()
void addHistoryLine ()
Protected Attributes
SBHistory * HistDBH
SBHistory * HistLocal
QListView * LVHistory
QLineEdit * EHistLine
int Version
Detailed Description
Definition at line 382 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBBrowseHistory::SBBrowseHistory (SBHistory *HistDBH_, SBHistory *HistLocal_, intV_, QWidget *parent = 0, const char *name = 0, WFlagsf = 0)
Definition at line 1643 of file SbIObsVLBI.C'.
References addHistoryLine(), SBHistoryLI::DBH, deleteHistoryLine(), EHistLine, HistDBH, HistLocal, incVersion(), SBHistoryLI::LOCAL, LVHistory, and Version.
Member Function Documentation
void SBBrowseHistory::addHistoryLine () [protected, slot]
Definition at line 1758 of file SbIObsVLBI.C'.
References SBHistory::addHistoryLine(), EHistLine, HistLocal, SBHistoryLI::LOCAL, LVHistory, modified(), and Version.
Referenced by SBBrowseHistory().
virtual QString SBBrowseHistory::ClassName () const [inline, virtual]
Definition at line 407 of file SbIObsVLBI.H'.
Referenced by deleteHistoryLine().
void SBBrowseHistory::deleteHistoryLine () [protected, slot]
Definition at line 1728 of file SbIObsVLBI.C'.
References ClassName(), SBDated::date(), SBLog::DBG, SBLog::ERR, SBMJD::F_Short, SBHistoryLI::hEntry(), HistLocal, SBLog::INTERFACE, SBHistoryLI::LOCAL, Log, LVHistory, modified(), SBHistoryLI::type(), and SBLog::write().
Referenced by SBBrowseHistory().
const SBHistory* SBBrowseHistory::histDBH () const [inline]
Definition at line 410 of file SbIObsVLBI.H'.
References HistDBH.
const SBHistory* SBBrowseHistory::histLocal () const [inline]
Definition at line 409 of file SbIObsVLBI.H'.
References HistLocal.
void SBBrowseHistory::incVersion () [inline, slot]
Definition at line 403 of file SbIObsVLBI.H'.
References Version, and versionInced().
Referenced by SBBrowseHistory().
QListView* SBBrowseHistory::lvHistory () [inline]
Definition at line 408 of file SbIObsVLBI.H'.
References LVHistory.
Referenced by SBVLBIPreProcess::blockInput(), and SBVLBIPreProcess::restoreInput().
void SBBrowseHistory::modified (boolt0) [signal]
Definition at line 424 of file SbIObsVLBI.moc.C'.
Referenced by addHistoryLine(), and deleteHistoryLine().
void SBBrowseHistory::setHistories (SBHistory *HistDBH_, SBHistory *HistLocal_, intV_)
Definition at line 1708 of file SbIObsVLBI.C'.
References SBHistoryLI::DBH, HistDBH, HistLocal, SBHistoryLI::LOCAL, LVHistory, and Version.
Referenced by SBVLBIPreProcess::updateSession().
void SBBrowseHistory::versionInced () [signal]
Definition at line 430 of file SbIObsVLBI.moc.C'.
Referenced by incVersion().
Member Data Documentation
QLineEdit* SBBrowseHistory::EHistLine [protected]
Definition at line 389 of file SbIObsVLBI.H'.
Referenced by addHistoryLine(), and SBBrowseHistory().
SBHistory* SBBrowseHistory::HistDBH [protected]
Definition at line 386 of file SbIObsVLBI.H'.
Referenced by histDBH(), SBBrowseHistory(), and setHistories().
SBHistory* SBBrowseHistory::HistLocal [protected]
Definition at line 387 of file SbIObsVLBI.H'.
Referenced by addHistoryLine(), deleteHistoryLine(), histLocal(), SBBrowseHistory(), and setHistories().
QListView* SBBrowseHistory::LVHistory [protected]
Definition at line 388 of file SbIObsVLBI.H'.
Referenced by addHistoryLine(), deleteHistoryLine(), lvHistory(), SBBrowseHistory(), and setHistories().
int SBBrowseHistory::Version [protected]
Definition at line 390 of file SbIObsVLBI.H'.
Referenced by addHistoryLine(), incVersion(), SBBrowseHistory(), and setHistories().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.