.TH "SBBrowseHistory" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBBrowseHistory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBI\&.H>\fP
.PP
Inherits \fBQWidget\fP'\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBincVersion\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmodified\fP (bool)"
.br
.ti -1c
.RI "void \fBversionInced\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBBrowseHistory\fP (\fBSBHistory\fP *, \fBSBHistory\fP *, int, \fBQWidget\fP *=0, const char *=0, WFlags=0)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "\fBQListView\fP * \fBlvHistory\fP ()"
.br
.ti -1c
.RI "const \fBSBHistory\fP * \fBhistLocal\fP () const "
.br
.ti -1c
.RI "const \fBSBHistory\fP * \fBhistDBH\fP () const "
.br
.ti -1c
.RI "void \fBsetHistories\fP (\fBSBHistory\fP *, \fBSBHistory\fP *, int)"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBdeleteHistoryLine\fP ()"
.br
.ti -1c
.RI "void \fBaddHistoryLine\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSBHistory\fP * \fBHistDBH\fP"
.br
.ti -1c
.RI "\fBSBHistory\fP * \fBHistLocal\fP"
.br
.ti -1c
.RI "\fBQListView\fP * \fBLVHistory\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEHistLine\fP"
.br
.ti -1c
.RI "int \fBVersion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 382 of file SbIObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBBrowseHistory::SBBrowseHistory (\fBSBHistory\fP *HistDBH_, \fBSBHistory\fP *HistLocal_, intV_, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 1643 of file SbIObsVLBI\&.C'\&.
.PP
References addHistoryLine(), SBHistoryLI::DBH, deleteHistoryLine(), EHistLine, HistDBH, HistLocal, incVersion(), SBHistoryLI::LOCAL, LVHistory, and Version\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBBrowseHistory::addHistoryLine ()\fC [protected, slot]\fP"
.PP
Definition at line 1758 of file SbIObsVLBI\&.C'\&.
.PP
References SBHistory::addHistoryLine(), EHistLine, HistLocal, SBHistoryLI::LOCAL, LVHistory, modified(), and Version\&.
.PP
Referenced by SBBrowseHistory()\&.
.SS "virtual QString SBBrowseHistory::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 407 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by deleteHistoryLine()\&.
.SS "void SBBrowseHistory::deleteHistoryLine ()\fC [protected, slot]\fP"
.PP
Definition at line 1728 of file SbIObsVLBI\&.C'\&.
.PP
References ClassName(), SBDated::date(), SBLog::DBG, SBLog::ERR, SBMJD::F_Short, SBHistoryLI::hEntry(), HistLocal, SBLog::INTERFACE, SBHistoryLI::LOCAL, Log, LVHistory, modified(), SBHistoryLI::type(), and SBLog::write()\&.
.PP
Referenced by SBBrowseHistory()\&.
.SS "const \fBSBHistory\fP* SBBrowseHistory::histDBH () const\fC [inline]\fP"
.PP
Definition at line 410 of file SbIObsVLBI\&.H'\&.
.PP
References HistDBH\&.
.SS "const \fBSBHistory\fP* SBBrowseHistory::histLocal () const\fC [inline]\fP"
.PP
Definition at line 409 of file SbIObsVLBI\&.H'\&.
.PP
References HistLocal\&.
.SS "void SBBrowseHistory::incVersion ()\fC [inline, slot]\fP"
.PP
Definition at line 403 of file SbIObsVLBI\&.H'\&.
.PP
References Version, and versionInced()\&.
.PP
Referenced by SBBrowseHistory()\&.
.SS "\fBQListView\fP* SBBrowseHistory::lvHistory ()\fC [inline]\fP"
.PP
Definition at line 408 of file SbIObsVLBI\&.H'\&.
.PP
References LVHistory\&.
.PP
Referenced by SBVLBIPreProcess::blockInput(), and SBVLBIPreProcess::restoreInput()\&.
.SS "void SBBrowseHistory::modified (boolt0)\fC [signal]\fP"
.PP
Definition at line 424 of file SbIObsVLBI\&.moc\&.C'\&.
.PP
Referenced by addHistoryLine(), and deleteHistoryLine()\&.
.SS "void SBBrowseHistory::setHistories (\fBSBHistory\fP *HistDBH_, \fBSBHistory\fP *HistLocal_, intV_)"
.PP
Definition at line 1708 of file SbIObsVLBI\&.C'\&.
.PP
References SBHistoryLI::DBH, HistDBH, HistLocal, SBHistoryLI::LOCAL, LVHistory, and Version\&.
.PP
Referenced by SBVLBIPreProcess::updateSession()\&.
.SS "void SBBrowseHistory::versionInced ()\fC [signal]\fP"
.PP
Definition at line 430 of file SbIObsVLBI\&.moc\&.C'\&.
.PP
Referenced by incVersion()\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* \fBSBBrowseHistory::EHistLine\fP\fC [protected]\fP"
.PP
Definition at line 389 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by addHistoryLine(), and SBBrowseHistory()\&.
.SS "\fBSBHistory\fP* \fBSBBrowseHistory::HistDBH\fP\fC [protected]\fP"
.PP
Definition at line 386 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by histDBH(), SBBrowseHistory(), and setHistories()\&.
.SS "\fBSBHistory\fP* \fBSBBrowseHistory::HistLocal\fP\fC [protected]\fP"
.PP
Definition at line 387 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by addHistoryLine(), deleteHistoryLine(), histLocal(), SBBrowseHistory(), and setHistories()\&.
.SS "\fBQListView\fP* \fBSBBrowseHistory::LVHistory\fP\fC [protected]\fP"
.PP
Definition at line 388 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by addHistoryLine(), deleteHistoryLine(), lvHistory(), SBBrowseHistory(), and setHistories()\&.
.SS "int \fBSBBrowseHistory::Version\fP\fC [protected]\fP"
.PP
Definition at line 390 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by addHistoryLine(), incVersion(), SBBrowseHistory(), and setHistories()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
