SBCableLI
NAME
SBCableLI -
SYNOPSIS
#include <SbIPreProcessing.H>
Inherits QListViewItem'.
Public Member Functions
SBCableLI (QListView *parent_, SBParameter *Par_, SBStationInfo *SI_)
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Protected Attributes
SBParameter * Par
SBStationInfo * SI
Detailed Description
Definition at line 65 of file SbIPreProcessing.H'.
Constructor & Destructor Documentation
SBCableLI::SBCableLI (QListView *parent_, SBParameter *Par_, SBStationInfo *SI_) [inline]
Definition at line 72 of file SbIPreProcessing.H'.
References Par, and SI.
Member Function Documentation
virtual QString SBCableLI::ClassName () const [inline, virtual]
Definition at line 74 of file SbIPreProcessing.H'.
QString SBCableLI::key (intcol, bool) const [virtual]
Definition at line 234 of file SbIPreProcessing.C'.
References SBObjectObsInfo::aka(), SBParameter::e(), SBObjectObsInfo::idx(), Par, SI, TmpString, SBStationID::toString(), and SBParameter::v().
QString SBCableLI::text (intcol) const [virtual]
Definition at line 214 of file SbIPreProcessing.C'.
References SBObjectObsInfo::aka(), SBParameter::e(), SBObjectObsInfo::idx(), Par, SI, TmpString, SBStationID::toString(), and SBParameter::v().
Member Data Documentation
SBParameter* SBCableLI::Par [protected]
Definition at line 68 of file SbIPreProcessing.H'.
Referenced by key(), SBCableLI(), and text().
SBStationInfo* SBCableLI::SI [protected]
Definition at line 69 of file SbIPreProcessing.H'.
Referenced by key(), SBCableLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.