SBCablesBrowser
NAME
SBCablesBrowser -
SYNOPSIS
#include <SbIPreProcessing.H>
Inherits QDialog'.
Public Member Functions
SBCablesBrowser (SBStationInfoList *, SBParameterList *, const QString &, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBCablesBrowser ()
virtual QString ClassName () const
Protected Slots
void reject ()
Private Attributes
SBStationInfoList Stations
SBParameterList * Cables
QListView * CablesLV
Detailed Description
Definition at line 87 of file SbIPreProcessing.H'.
Constructor & Destructor Documentation
SBCablesBrowser::SBCablesBrowser (SBStationInfoList *Stations_, SBParameterList *Cables_, const QString &SessionName_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 262 of file SbIPreProcessing.C'.
References Cables, CablesLV, ClassName(), SBLog::ERR, SBStationInfoList::find(), Log, SBLog::PREPROC, reject(), SBStationID::setID(), Stations, and SBLog::write().
SBCablesBrowser::~SBCablesBrowser () [virtual]
Definition at line 342 of file SbIPreProcessing.C'.
References Cables.
Member Function Documentation
virtual QString SBCablesBrowser::ClassName () const [inline, virtual]
Definition at line 94 of file SbIPreProcessing.H'.
Referenced by SBCablesBrowser().
void SBCablesBrowser::reject () [inline, protected, slot]
Definition at line 99 of file SbIPreProcessing.H'.
Referenced by SBCablesBrowser().
Member Data Documentation
SBParameterList* SBCablesBrowser::Cables [private]
Definition at line 103 of file SbIPreProcessing.H'.
Referenced by SBCablesBrowser(), and ~SBCablesBrowser().
QListView* SBCablesBrowser::CablesLV [private]
Definition at line 106 of file SbIPreProcessing.H'.
Referenced by SBCablesBrowser().
SBStationInfoList SBCablesBrowser::Stations [private]
Definition at line 99 of file SbIPreProcessing.H'.
Referenced by SBCablesBrowser().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.