SBCatalog
NAME
SBCatalog -
SYNOPSIS
#include <SbGeo.H>
Inherits SBNList'.
Inherited by SB_CRF, and SB_TRF'.
Public Member Functions
SBCatalog ()
SBCatalog (const SBCatalog &Catalog)
virtual ~SBCatalog ()
virtual QString ClassName () const
void setLabel (const SBSolutionName &Label_)
void setEpoch (const SBMJD &Epoch_)
void setComment (const QString &Comment_)
const SBSolutionName & label () const
const SBMJD & epoch () const
const QString & comment () const
QDict< QString > * aliasDict ()
virtual void prepareAliases4Output ()
virtual void releaseAliases4Output ()
virtual void collectObjAliases (QString)
virtual void releaseObjAliases (QString)
virtual void prepareReferences ()
virtual SBNList * referenceList ()
virtual void clear ()
virtual SBNamed * find (const SBNamed &N) const
virtual SBNamed * find (const QString &S) const
virtual SBNamed * operator[] (const SBNamed &N) const
virtual SBNamed * operator[] (const QString &S) const
virtual void insert (const SBNamed *N)
virtual void inSort (const SBNamed *N)
virtual bool remove ()
virtual bool remove (uint i)
virtual bool remove (const SBNamed *N)
virtual bool removeFirst ()
virtual bool removeLast ()
virtual SBNamed * take ()
virtual SBNamed * take (uint i)
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Protected Attributes
SBSolutionName Label
SBMJD Epoch
QString Comment
QDict< SBNamed > * Dict
QDict< QString > * Aliases
Friends
QDataStream & operator<< (QDataStream &, const SBCatalog &)
QDataStream & operator>> (QDataStream &, SBCatalog &)
Detailed Description
Definition at line 483 of file SbGeo.H'.
Constructor & Destructor Documentation
SBCatalog::SBCatalog ()
Definition at line 406 of file SbGeo.C'.
References Aliases, Comment, Dict, Epoch, Label, SBSolutionName::setAttr(), TECH_UNKN, SBSolutionName::TYPE_UNKN, and TZero.
SBCatalog::SBCatalog (const SBCatalog &Catalog)
Definition at line 418 of file SbGeo.C'.
References Aliases, Comment, Dict, Epoch, and Label.
virtual SBCatalog::~SBCatalog () [inline, virtual]
Definition at line 494 of file SbGeo.H'.
References Aliases, and Dict.
Member Function Documentation
QDict<QString>* SBCatalog::aliasDict () [inline]
Definition at line 504 of file SbGeo.H'.
References Aliases.
Referenced by SBAliasEditor::accept(), SBStuffSources::CRFModified(), SBStuffSources::deleteEntryA(), SBStuffStations::deleteEntryA(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBEcc::importEccDat(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStationImport::loadNScodes(), SBStuffSources::reloadCRF(), SBStuffStations::reloadTRF(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), and SBStuffStations::TRFModified().
virtual QString SBCatalog::ClassName () const [inline, virtual]
Reimplemented in SB_TRF, and SB_CRF'.
Definition at line 495 of file SbGeo.H'.
virtual void SBCatalog::clear () [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 516 of file SbGeo.H'.
References Dict.
virtual void SBCatalog::collectObjAliases (QString) [inline, virtual]
Reimplemented in SB_TRF, and SB_CRF'.
Definition at line 510 of file SbGeo.H'.
Referenced by SBAliasEditor::accept().
const QString& SBCatalog::comment () const [inline]
Definition at line 503 of file SbGeo.H'.
References Comment.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, and SBStationIDList'.
Definition at line 277 of file SbGeo.H'.
const SBMJD& SBCatalog::epoch () const [inline]
Definition at line 502 of file SbGeo.H'.
References Epoch.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBAploChunk::import(), SBAploEphem::importHPS(), operator<<(), operator>>(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
virtual SBNamed* SBCatalog::find (const SBNamed &N) const [inline, virtual]
Definition at line 517 of file SbGeo.H'.
References Dict, and SBNamed::name().
Referenced by operator[]().
virtual SBNamed* SBCatalog::find (const QString &S) const [inline, virtual]
Reimplemented in SB_CRF'.
Definition at line 518 of file SbGeo.H'.
References Dict.
virtual void SBCatalog::insert (const SBNamed *N) [inline, virtual]
Definition at line 521 of file SbGeo.H'.
References Dict, inSort(), and SBNamed::name().
virtual void SBCatalog::inSort (const SBNamed *N) [inline, virtual]
Definition at line 522 of file SbGeo.H'.
References Dict, and SBNamed::name().
Referenced by SBSourceImport::importICRF(), insert(), SBSourceEditor::makeApply(), operator>>(), and SBStuffSources::SBStuffSources().
const SBSolutionName& SBCatalog::label () const [inline]
Definition at line 501 of file SbGeo.H'.
References Label.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator<<(), SBStuffSources::SBStuffSources(), and SBStuffStations::SBStuffStations().
virtual SBNamed* SBCatalog::operator[] (const SBNamed &N) const [inline, virtual]
Definition at line 519 of file SbGeo.H'.
References find().
virtual SBNamed* SBCatalog::operator[] (const QString &S) const [inline, virtual]
Reimplemented in SB_CRF'.
Definition at line 520 of file SbGeo.H'.
References find().
virtual void SBCatalog::prepareAliases4Output () [inline, virtual]
Reimplemented in SB_TRF, and SB_CRF'.
Definition at line 508 of file SbGeo.H'.
virtual void SBCatalog::prepareReferences () [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 512 of file SbGeo.H'.
Referenced by SBAliasEditor::init().
virtual QDataStream& SBNList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 284 of file SbGeo.H'.
virtual SBNList* SBCatalog::referenceList () [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 513 of file SbGeo.H'.
Referenced by SBAliasEditor::init().
virtual void SBCatalog::releaseAliases4Output () [inline, virtual]
Reimplemented in SB_TRF, and SB_CRF'.
Definition at line 509 of file SbGeo.H'.
virtual void SBCatalog::releaseObjAliases (QString) [inline, virtual]
Reimplemented in SB_TRF, and SB_CRF'.
Definition at line 511 of file SbGeo.H'.
virtual bool SBCatalog::remove () [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 523 of file SbGeo.H'.
References Dict.
Referenced by SBStuffSources::deleteEntryS(), SBRunManager::makeReportCRF(), remove(), and SBRunManager::stripCRF().
virtual bool SBCatalog::remove (uinti) [inline, virtual]
Definition at line 524 of file SbGeo.H'.
References Dict, and remove().
virtual bool SBCatalog::remove (const SBNamed *N) [inline, virtual]
Definition at line 525 of file SbGeo.H'.
References Dict, and remove().
virtual bool SBCatalog::removeFirst () [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 526 of file SbGeo.H'.
References Dict.
virtual bool SBCatalog::removeLast () [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 527 of file SbGeo.H'.
References Dict.
void SBCatalog::setComment (const QString &Comment_) [inline]
Definition at line 500 of file SbGeo.H'.
References Comment.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and SBStationImport::importITRF().
void SBCatalog::setEpoch (const SBMJD &Epoch_) [inline]
Definition at line 499 of file SbGeo.H'.
References Epoch.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), and operator>>().
void SBCatalog::setLabel (const SBSolutionName &Label_) [inline]
Definition at line 498 of file SbGeo.H'.
References Label.
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF().
virtual SBNamed* SBCatalog::take () [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 528 of file SbGeo.H'.
References Dict.
Referenced by take().
virtual SBNamed* SBCatalog::take (uinti) [inline, virtual]
Reimplemented in SB_TRF'.
Definition at line 529 of file SbGeo.H'.
References Dict, and take().
virtual QDataStream& SBNList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 282 of file SbGeo.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBCatalog &C) [friend]
Definition at line 438 of file SbGeo.C'.
QDataStream& operator>> (QDataStream &s, SBCatalog &C) [friend]
Definition at line 450 of file SbGeo.C'.
Member Data Documentation
QDict<QString>* SBCatalog::Aliases [protected]
Definition at line 490 of file SbGeo.H'.
Referenced by aliasDict(), SB_CRF::collectObjAliases(), SB_CRF::lookupAlias(), SB_TRF::lookupID(), SB_TRF::lookupStation(), operator<<(), operator>>(), SB_CRF::prepareAliases4Output(), SBCatalog(), and ~SBCatalog().
QString SBCatalog::Comment [protected]
Definition at line 488 of file SbGeo.H'.
Referenced by comment(), operator<<(), operator>>(), SBCatalog(), and setComment().
QDict<SBNamed>* SBCatalog::Dict [protected]
Definition at line 489 of file SbGeo.H'.
Referenced by clear(), find(), insert(), inSort(), operator>>(), remove(), removeFirst(), removeLast(), SBCatalog(), SB_TRF::setSiteName(), take(), and ~SBCatalog().
SBMJD SBCatalog::Epoch [protected]
Definition at line 487 of file SbGeo.H'.
Referenced by epoch(), SB_TRF::lookupNearest(), operator<<(), operator>>(), SBCatalog(), and setEpoch().
SBSolutionName SBCatalog::Label [protected]
Definition at line 486 of file SbGeo.H'.
Referenced by label(), operator<<(), operator>>(), SB_CRF::SB_CRF(), SB_TRF::SB_TRF(), SBCatalog(), and setLabel().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.