.TH "SBCentralPanel" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBCentralPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIMainWin\&.H>\fP
.PP
Inherits \fBQWidget\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBCentralPanel\fP (\fBQWidget\fP *=0, const char *=0)"
.br
.ti -1c
.RI "\fB~SBCentralPanel\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "QFrame * \fBgenInfoPanel\fP (\fBQWidget\fP *, const char *)"
.br
.ti -1c
.RI "QFrame * \fBdetInfoPanel\fP (\fBQWidget\fP *, const char *)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QLabel * \fBTRFName\fP"
.br
.ti -1c
.RI "QLabel * \fBCRFName\fP"
.br
.ti -1c
.RI "QLabel * \fBEOPName\fP"
.br
.ti -1c
.RI "QLabel * \fBPrjName\fP"
.br
.ti -1c
.RI "QLabel * \fBStatus\fP"
.br
.ti -1c
.RI "QLabel * \fBOperation\fP"
.br
.ti -1c
.RI "QLabel * \fBProcSess\fP"
.br
.ti -1c
.RI "QLabel * \fBProcObs\fP"
.br
.ti -1c
.RI "QLabel * \fBSessName\fP"
.br
.ti -1c
.RI "QLabel * \fBCasheSizes\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSBMainWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file SbIMainWin\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBCentralPanel::SBCentralPanel (\fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP)"
.PP
Definition at line 110 of file SbIMainWin\&.C'\&.
.PP
References detInfoPanel(), genInfoPanel(), and Log\&.
.SS "SBCentralPanel::~SBCentralPanel ()"
.PP
Definition at line 129 of file SbIMainWin\&.C'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBCentralPanel::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 60 of file SbIMainWin\&.H'\&.
.SS "QFrame * SBCentralPanel::detInfoPanel (\fBQWidget\fP *parent, const char *name)\fC [private]\fP"
.PP
Definition at line 197 of file SbIMainWin\&.C'\&.
.PP
References CasheSizes, Operation, ProcObs, ProcSess, and SessName\&.
.PP
Referenced by SBCentralPanel()\&.
.SS "QFrame * SBCentralPanel::genInfoPanel (\fBQWidget\fP *parent, const char *name)\fC [private]\fP"
.PP
Definition at line 133 of file SbIMainWin\&.C'\&.
.PP
References CRFName, EOPName, SBSetUp::eops(), PrjName, SBSetUp::project(), SetUp, SBSetUp::sources(), SBSetUp::stations(), Status, and TRFName\&.
.PP
Referenced by SBCentralPanel()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSBMainWindow\fP\fC [friend]\fP"
.PP
Definition at line 55 of file SbIMainWin\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "QLabel* \fBSBCentralPanel::CasheSizes\fP\fC [private]\fP"
.PP
Definition at line 73 of file SbIMainWin\&.H'\&.
.PP
Referenced by detInfoPanel(), and SBMainWindow::setCacheSizes()\&.
.SS "QLabel* \fBSBCentralPanel::CRFName\fP\fC [private]\fP"
.PP
Definition at line 64 of file SbIMainWin\&.H'\&.
.PP
Referenced by genInfoPanel(), and SBMainWindow::setCRFName()\&.
.SS "QLabel* \fBSBCentralPanel::EOPName\fP\fC [private]\fP"
.PP
Definition at line 65 of file SbIMainWin\&.H'\&.
.PP
Referenced by genInfoPanel(), and SBMainWindow::setEOPName()\&.
.SS "QLabel* \fBSBCentralPanel::Operation\fP\fC [private]\fP"
.PP
Definition at line 69 of file SbIMainWin\&.H'\&.
.PP
Referenced by detInfoPanel(), and SBMainWindow::setOperation()\&.
.SS "QLabel* \fBSBCentralPanel::PrjName\fP\fC [private]\fP"
.PP
Definition at line 66 of file SbIMainWin\&.H'\&.
.PP
Referenced by genInfoPanel(), and SBMainWindow::setPrjName()\&.
.SS "QLabel* \fBSBCentralPanel::ProcObs\fP\fC [private]\fP"
.PP
Definition at line 71 of file SbIMainWin\&.H'\&.
.PP
Referenced by detInfoPanel(), and SBMainWindow::setProcObs()\&.
.SS "QLabel* \fBSBCentralPanel::ProcSess\fP\fC [private]\fP"
.PP
Definition at line 70 of file SbIMainWin\&.H'\&.
.PP
Referenced by detInfoPanel(), and SBMainWindow::setProcSes()\&.
.SS "QLabel* \fBSBCentralPanel::SessName\fP\fC [private]\fP"
.PP
Definition at line 72 of file SbIMainWin\&.H'\&.
.PP
Referenced by detInfoPanel(), and SBMainWindow::setSessName()\&.
.SS "QLabel* \fBSBCentralPanel::Status\fP\fC [private]\fP"
.PP
Definition at line 67 of file SbIMainWin\&.H'\&.
.PP
Referenced by genInfoPanel(), and SBMainWindow::setStatus()\&.
.SS "QLabel* \fBSBCentralPanel::TRFName\fP\fC [private]\fP"
.PP
Definition at line 60 of file SbIMainWin\&.H'\&.
.PP
Referenced by genInfoPanel(), and SBMainWindow::setTRFName()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
