.TH "SBClockBreaksList" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBClockBreaksList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoObsVLBI\&.H>\fP
.PP
Inherits \fBQList< SBParameterBreak >\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBClockBreaksList\fP ()"
.br
.ti -1c
.RI "virtual \fB~SBClockBreaksList\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "double \fBbt\fP (const \fBSBMJD\fP &T_)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item p1, QCollection::Item p2)"
.br
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item B) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &B)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBClockBreaksList\fP &L)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBClockBreaksList\fP &L)"
.br
.in -1c
.SH "Detailed Description"
.PP 
class \fBSBClockBreaksList\fP, uses in the class \fBSBStationInfo\fP to list known breaks in clocks of a station'\&. 
.PP
Definition at line 185 of file SbGeoObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBClockBreaksList::SBClockBreaksList ()\fC [inline]\fP"A constructor'\&. Creates a copy of an object'\&. 
.PP
Definition at line 199 of file SbGeoObsVLBI\&.H'\&.
.SS "virtual SBClockBreaksList::~SBClockBreaksList ()\fC [inline, virtual]\fP"A destructor'\&. 
.PP
Definition at line 201 of file SbGeoObsVLBI\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "double SBClockBreaksList::bt (const \fBSBMJD\fP &T_)\fC [inline]\fP"
.PP
Definition at line 210 of file SbGeoObsVLBI\&.H'\&.
.PP
Referenced by SBObsVLBIEntry::process()\&.
.SS "virtual QString SBClockBreaksList::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info)'\&. 
.PP
Definition at line 203 of file SbGeoObsVLBI\&.H'\&.
.SS "virtual int SBClockBreaksList::compareItems (QCollection::Itemp1, QCollection::Itemp2)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 188 of file SbGeoObsVLBI\&.H'\&.
.SS "virtual QDataStream& SBClockBreaksList::read (QDataStream &s, QCollection::Item &B)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 192 of file SbGeoObsVLBI\&.H'\&.
.SS "virtual QDataStream& SBClockBreaksList::write (QDataStream &s, QCollection::ItemB) const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 190 of file SbGeoObsVLBI\&.H'\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBClockBreaksList\fP &L)\fC [friend]\fP"
.PP
Definition at line 215 of file SbGeoObsVLBI\&.H'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBClockBreaksList\fP &L)\fC [friend]\fP"
.PP
Definition at line 217 of file SbGeoObsVLBI\&.H'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
