SBClockBreakLI
NAME
SBClockBreakLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QListViewItem'.
Public Member Functions
SBClockBreakLI (QListView *parent_, SBParameterBreak *Br_)
SBParameterBreak * clockBreak ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Protected Attributes
SBParameterBreak * Br
Detailed Description
Definition at line 227 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBClockBreakLI::SBClockBreakLI (QListView *parent_, SBParameterBreak *Br_) [inline]
Definition at line 232 of file SbIObsVLBI.H'.
References Br.
Member Function Documentation
virtual QString SBClockBreakLI::ClassName () const [inline, virtual]
Definition at line 234 of file SbIObsVLBI.H'.
SBParameterBreak* SBClockBreakLI::clockBreak () [inline]
Definition at line 233 of file SbIObsVLBI.H'.
References Br.
Referenced by SBStaParsEditor::deleteEntry(), and SBClockBreakEditor::SBClockBreakEditor().
QString SBClockBreakLI::key (intcol, bool) const [virtual]
Definition at line 978 of file SbIObsVLBI.C'.
References SBParameterBreak::b(), Br, and TmpString.
QString SBClockBreakLI::text (intcol) const [virtual]
Definition at line 964 of file SbIObsVLBI.C'.
References SBParameterBreak::b(), Br, SBMJD::F_YYYYMMDDHHMMSSSS, TmpString, and SBMJD::toString().
Member Data Documentation
SBParameterBreak* SBClockBreakLI::Br [protected]
Definition at line 230 of file SbIObsVLBI.H'.
Referenced by clockBreak(), key(), SBClockBreakLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.