SBClockBreakEditor
NAME
SBClockBreakEditor -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QDialog'.
Signals
void clockBreakModified (bool)
Public Member Functions
SBClockBreakEditor (SBClockBreakLI *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBClockBreakEditor ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Private Member Functions
virtual void acquireData ()
Private Attributes
SBClockBreakLI * Bli
SBParameterBreak * B
bool isModified
QLineEdit * leYr
QLineEdit * leMo
QLineEdit * leDy
QLineEdit * leHr
QLineEdit * leMi
QLineEdit * leSe
QLineEdit * leVal
Detailed Description
Definition at line 730 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBClockBreakEditor::SBClockBreakEditor (SBClockBreakLI *Bli_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 3253 of file SbIObsVLBI.C'.
References accept(), SBParameterBreak::b(), B, Bli, SBClockBreakLI::clockBreak(), SBMJD::day(), SBMJD::hour(), isModified, leDy, leHr, leMi, leMo, leSe, leVal, leYr, SBMJD::min(), SBMJD::month(), reject(), SBMJD::sec(), and SBMJD::year().
virtual SBClockBreakEditor::~SBClockBreakEditor () [inline, virtual]
Definition at line 735 of file SbIObsVLBI.H'.
References B.
Member Function Documentation
void SBClockBreakEditor::accept () [protected, slot]
Definition at line 3400 of file SbIObsVLBI.C'.
References acquireData(), Bli, clockBreakModified(), and isModified.
Referenced by SBClockBreakEditor().
void SBClockBreakEditor::acquireData () [private, virtual]
Definition at line 3417 of file SbIObsVLBI.C'.
References SBParameterBreak::b(), B, Bli, isModified, leDy, leHr, leMi, leMo, leSe, leVal, leYr, and SBParameterBreak::setB().
Referenced by accept().
virtual QString SBClockBreakEditor::ClassName () const [inline, virtual]
Definition at line 736 of file SbIObsVLBI.H'.
void SBClockBreakEditor::clockBreakModified (boolt0) [signal]
Definition at line 1279 of file SbIObsVLBI.moc.C'.
Referenced by accept(), and reject().
void SBClockBreakEditor::reject () [protected, slot]
Definition at line 3410 of file SbIObsVLBI.C'.
References clockBreakModified().
Referenced by SBClockBreakEditor().
Member Data Documentation
SBParameterBreak* SBClockBreakEditor::B [private]
Definition at line 748 of file SbIObsVLBI.H'.
Referenced by acquireData(), SBClockBreakEditor(), and ~SBClockBreakEditor().
SBClockBreakLI* SBClockBreakEditor::Bli [private]
Definition at line 747 of file SbIObsVLBI.H'.
Referenced by accept(), acquireData(), and SBClockBreakEditor().
bool SBClockBreakEditor::isModified [private]
Definition at line 749 of file SbIObsVLBI.H'.
Referenced by accept(), acquireData(), and SBClockBreakEditor().
QLineEdit* SBClockBreakEditor::leDy [private]
Definition at line 754 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBClockBreakEditor().
QLineEdit* SBClockBreakEditor::leHr [private]
Definition at line 755 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBClockBreakEditor().
QLineEdit* SBClockBreakEditor::leMi [private]
Definition at line 756 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBClockBreakEditor().
QLineEdit* SBClockBreakEditor::leMo [private]
Definition at line 753 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBClockBreakEditor().
QLineEdit* SBClockBreakEditor::leSe [private]
Definition at line 757 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBClockBreakEditor().
QLineEdit* SBClockBreakEditor::leVal [private]
Definition at line 758 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBClockBreakEditor().
QLineEdit* SBClockBreakEditor::leYr [private]
Definition at line 752 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBClockBreakEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.