.TH "SbCompileInfo.H" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbCompileInfo.H \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSB_COMP_NAME\fP   'gcc'"
.br
.ti -1c
.RI "#define \fBSB_COMP_VERSION\fP   __VERSION__"
.br
.ti -1c
.RI "#define \fBSB_COMP_DATE\fP   __DATE__"
.br
.ti -1c
.RI "#define \fBSB_COMP_TIME\fP   __TIME__"
.br
.ti -1c
.RI "#define \fBSB_COMP_OS\fP   'Linux lacerta #1 SMP PREEMPT 2011-12-19 23:39:38 +0100 2\&.6\&.37\&.6-0\&.11-desktop i686'"
.br
.ti -1c
.RI "#define \fBSB_COMP_DOMAIN_NAME\fP   ''"
.br
.ti -1c
.RI "#define \fBSB_COMP_HOST_NAME\fP   'lacerta'"
.br
.ti -1c
.RI "#define \fBSB_COMP_LOGIN_NAME\fP   'slb'"
.br
.ti -1c
.RI "#define \fBSB_COMP_USER_NAME\fP   'Sergei Bolotin'"
.br
.ti -1c
.RI "#define \fBSB_VER_MAJOR\fP   2"
.br
.ti -1c
.RI "#define \fBSB_VER_MINOR\fP   0"
.br
.ti -1c
.RI "#define \fBSB_VER_PATCHLEVEL\fP   2"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define SB_COMP_DATE   __DATE__"
.PP
Definition at line 27 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_DOMAIN_NAME   ''"
.PP
Definition at line 30 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_HOST_NAME   'lacerta'"
.PP
Definition at line 31 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_LOGIN_NAME   'slb'"
.PP
Definition at line 32 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_NAME   'gcc'"
.PP
Definition at line 25 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_OS   'Linux lacerta #1 SMP PREEMPT 2011-12-19 23:39:38 +0100 2\&.6\&.37\&.6-0\&.11-desktop i686'"
.PP
Definition at line 29 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_TIME   __TIME__"
.PP
Definition at line 28 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_USER_NAME   'Sergei Bolotin'"
.PP
Definition at line 33 of file SbCompileInfo\&.H'\&.
.SS "#define SB_COMP_VERSION   __VERSION__"
.PP
Definition at line 26 of file SbCompileInfo\&.H'\&.
.SS "#define SB_VER_MAJOR   2"
.PP
Definition at line 34 of file SbCompileInfo\&.H'\&.
.SS "#define SB_VER_MINOR   0"
.PP
Definition at line 35 of file SbCompileInfo\&.H'\&.
.SS "#define SB_VER_PATCHLEVEL   2"
.PP
Definition at line 36 of file SbCompileInfo\&.H'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
