SbCompileInfo.C
NAME
SbCompileInfo.C -
SYNOPSIS
#include 'SbGeneral.H'
#include 'SbCompileInfo.H'
Functions
const QString SBCompilerName (SB_COMP_NAME)
const QString SBCompilerVersion (SB_COMP_VERSION)
const QString SBCompilerHostName (SB_COMP_HOST_NAME)
const QString SBCompilerDomainName (SB_COMP_DOMAIN_NAME)
const QString SBCompilerLoginName (SB_COMP_LOGIN_NAME)
const QString SBCompilerUserName (SB_COMP_USER_NAME)
const QString SBCompilerDate (SB_COMP_DATE)
const QString SBCompilerTime (SB_COMP_TIME)
const QString SBCompilerOS (SB_COMP_OS)
Variables
const SBVersion Version (SB_VER_MAJOR, SB_VER_MINOR, SB_VER_PATCHLEVEL)
Function Documentation
const QString SBCompilerDate (SB_COMP_DATE)
const QString SBCompilerDomainName (SB_COMP_DOMAIN_NAME)
const QString SBCompilerHostName (SB_COMP_HOST_NAME)
const QString SBCompilerLoginName (SB_COMP_LOGIN_NAME)
const QString SBCompilerName (SB_COMP_NAME)
const QString SBCompilerOS (SB_COMP_OS)
const QString SBCompilerTime (SB_COMP_TIME)
const QString SBCompilerUserName (SB_COMP_USER_NAME)
const QString SBCompilerVersion (SB_COMP_VERSION)
Variable Documentation
const SBVersion Version(SB_VER_MAJOR, SB_VER_MINOR, SB_VER_PATCHLEVEL)
Referenced by SBSetUp::CheckDir(), SBSolution::checkPath(), SBSolution::dumpParameters(), SBMainWindow::ExecuteDrop(), handlerSIGs(), SBMainWindow::HelpAbout(), SBMainWindow::HelpAboutQt(), SBSetUp::LoadConfig(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRFVariations(), operator<<(), SBEstimator::prepare4Local(), SBPlot::save2PS(), SBEstimator::SBEstimator(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBMainWindow::setupStatusBar(), and sinex_FileReferenceBlock().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.