SBCoordinates
NAME
SBCoordinates -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBMJD, and SBAttributed'.
Public Types
enum Attributes { notValid = 1<< 0, Reserved_1 = 1<< 1 }
enum Format { F_YYYYMMDD, F_DDMonYYYY, F_Short, F_Long, F_Year, F_YYMonDD, F_HHMMSS, F_YYYYMMDDSSSSSS, F_INTERNAL, F_YYYYMMDDHHMMSSSS, F_DateShort, F_TimeShort, F_TimeVShort, F_ECCDAT, F_MJD, F_UNIX, F_SINEX, F_SINEX_S }
Public Member Functions
SBCoordinates ()
SBCoordinates (const SBCoordinates &)
SBCoordinates (const Vector3 &, const Vector3 &, const Vector3 &, const Vector3 &, const SBMJD &, const QString &)
SBCoordinates & operator= (const SBCoordinates &)
virtual ~SBCoordinates ()
QString ClassName () const
const SBMJD & epoch () const
const Vector3 & coo () const
const Vector3 & cooErrors () const
const Vector3 & vel () const
const Vector3 & velErrors () const
const QString & eventName () const
bool isUseVels () const
void setCoo (const Vector3 &C_)
void setCooErrors (const Vector3 &E_)
void setVel (const Vector3 &V_)
void setVelErrors (const Vector3 &E_)
void setEventName (const QString &N_)
void setIsUseVels (bool Is_)
bool operator< (const SBCoordinates &) const
bool operator== (const SBCoordinates &) const
virtual void setMJD (int, int, int, int=0, int=0, double=0.0, bool=TRUE)
virtual void setMJD (Format, QString, bool=TRUE)
virtual void setDate (int Date_)
virtual void setTime (long double Time_)
virtual QString toString (Format=F_Short) const
virtual bool isGood ()
virtual operator long double () const
virtual bool operator== (const SBMJD &) const
virtual bool operator!= (const SBMJD &) const
virtual bool operator< (const SBMJD &) const
virtual bool operator<= (const SBMJD &) const
virtual bool operator> (const SBMJD &) const
virtual bool operator> (double) const
virtual bool operator>= (const SBMJD &) const
virtual SBMJD & operator+= (const SBMJD &MJD)
virtual SBMJD & operator-= (const SBMJD &MJD)
int date () const
long double time () const
int year () const
int month () const
int hour () const
int min () const
double sec () const
QString month2Str () const
int day () const
int dayOfYear () const
int dayOfWeek () const
QString dayOfWeek2Str () const
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Static Public Member Functions
static int MJD_date (int, int, int)
static long double MJD_time (int, int, double)
static void MJD_rev (int, long double, int &, int &, int &, int &, int &, double &)
static SBMJD currentMJD ()
Static Protected Attributes
static const char * monthNames []
static const char * weekdayNames []
Private Attributes
Vector3 Coo
coordinates
Vector3 CooErrors
uncert'. of coordinates
Vector3 Vel
velocities
Vector3 VelErrors
uncert'. of velocities
QString EventName
the cause of a change in the coordinates
bool IsUseVels
Friends
QDataStream & operator<< (QDataStream &s, const SBCoordinates &C)
QDataStream & operator>> (QDataStream &s, SBCoordinates &C)
SBMJD operator+ (const SBMJD &, const SBMJD &)
SBMJD operator+ (const SBMJD &, long double)
SBMJD operator+ (const SBMJD &, double)
SBMJD operator+ (const SBMJD &, float)
SBMJD operator+ (long double, const SBMJD &)
SBMJD operator+ (double, const SBMJD &)
SBMJD operator+ (float, const SBMJD &)
SBMJD operator- (const SBMJD &, const SBMJD &)
SBMJD operator- (const SBMJD &, long double)
SBMJD operator- (const SBMJD &, double)
SBMJD operator- (long double, const SBMJD &)
SBMJD operator- (int, const SBMJD &)
QDataStream & operator<< (QDataStream &, const SBMJD &)
QDataStream & operator>> (QDataStream &, SBMJD &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Definition at line 319 of file SbGeoStations.H'.
Member Enumeration Documentation
enum SBCoordinates::Attributes"Attributes of the coordinates'.
Enumerator:
notValid
omit this info
Reserved_1
reserved
Definition at line 324 of file SbGeoStations.H'.
enum SBMJD::Format [inherited]
Enumerator:
F_YYYYMMDD
F_DDMonYYYY
F_Short
F_Long
F_Year
F_YYMonDD
F_HHMMSS
F_YYYYMMDDSSSSSS
F_INTERNAL
F_YYYYMMDDHHMMSSSS
F_DateShort
F_TimeShort
F_TimeVShort
F_ECCDAT
F_MJD
F_UNIX
F_SINEX
F_SINEX_S
Definition at line 49 of file SbGeoTime.H'.
Constructor & Destructor Documentation
SBCoordinates::SBCoordinates ()
Definition at line 310 of file SbGeoStations.C'.
References Coo, CooErrors, EventName, IsUseVels, v3Zero, Vel, and VelErrors.
SBCoordinates::SBCoordinates (const SBCoordinates &C_)
Definition at line 334 of file SbGeoStations.C'.
References Coo, coo(), CooErrors, cooErrors(), EventName, eventName(), IsUseVels, isUseVels(), Vel, vel(), VelErrors, and velErrors().
SBCoordinates::SBCoordinates (const Vector3 &R, const Vector3 &dR, const Vector3 &V, const Vector3 &dV, const SBMJD &T_, const QString &en_)
Definition at line 321 of file SbGeoStations.C'.
References Coo, CooErrors, EventName, IsUseVels, Vel, and VelErrors.
virtual SBCoordinates::~SBCoordinates () [inline, virtual]
Definition at line 345 of file SbGeoStations.H'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
QString SBCoordinates::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBAttributed'.
Definition at line 346 of file SbGeoStations.H'.
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
const Vector3& SBCoordinates::coo () const [inline]
Definition at line 351 of file SbGeoStations.H'.
References Coo.
Referenced by SBCoordsEditor::acquireData(), SBCoordsListItem::key(), operator<<(), operator=(), operator==(), SBReferencePoint::r(), SBReferencePoint::registerCoords(), SBCoordinates(), SBCoordsEditor::SBCoordsEditor(), and SBCoordsListItem::text().
const Vector3& SBCoordinates::cooErrors () const [inline]
Definition at line 352 of file SbGeoStations.H'.
References CooErrors.
Referenced by SBCoordsEditor::acquireData(), SBReferencePoint::dR(), SBCoordsListItem::key(), operator<<(), operator=(), operator==(), SBReferencePoint::registerCoords(), SBCoordinates(), SBCoordsEditor::SBCoordsEditor(), and SBCoordsListItem::text().
SBMJD SBMJD::currentMJD () [static, inherited]
Definition at line 134 of file SbGeoTime.C'.
Referenced by operator<<(), SBRunManager::process_m1(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and writeNormalEquationSystem().
int SBMJD::date () const [inline, inherited]
Definition at line 121 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBNutation::calcGST(), SBTime::DefineTAI_UTC(), SBRunManager::loadVLBISession_m1(), operator<<(), operator>>(), SBTestEphem::recalc(), and SBTime::setUTC().
int SBMJD::day () const [inherited]
Definition at line 208 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), operator<<(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
int SBMJD::dayOfWeek () const [inherited]
Definition at line 225 of file SbGeoTime.C'.
References SBMJD::Date, and SBMJD::SBMJD().
Referenced by SBMJD::dayOfWeek2Str().
QString SBMJD::dayOfWeek2Str () const [inherited]
Definition at line 231 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::dayOfWeek(), and SBMJD::weekdayNames.
Referenced by SBMJD::toString().
int SBMJD::dayOfYear () const [inherited]
Definition at line 220 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), and SBMJD::year().
Referenced by SBHMf_NMF::operator()(), and SBMJD::toString().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
const SBMJD& SBCoordinates::epoch () const [inline]
Definition at line 350 of file SbGeoStations.H'.
Referenced by SBReferencePoint::registerCoords().
const QString& SBCoordinates::eventName () const [inline]
Definition at line 355 of file SbGeoStations.H'.
References EventName.
Referenced by SBCoordsEditor::acquireData(), SBCoordsListItem::key(), operator=(), operator==(), SBCoordinates(), SBCoordsEditor::SBCoordsEditor(), and SBCoordsListItem::text().
int SBMJD::hour () const [inherited]
Definition at line 167 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
virtual bool SBMJD::isGood () [inline, virtual, inherited]
Definition at line 87 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBSourceEditor::acquireData(), SBAploChunk::import(), SBEcc::importEccDat(), operator>>(), and SBVLBISession::parseObsDumpString().
bool SBCoordinates::isUseVels () const [inline]
Definition at line 356 of file SbGeoStations.H'.
References IsUseVels.
Referenced by SBCoordsEditor::acquireData(), SBCoordsListItem::key(), operator=(), operator==(), SBCoordinates(), SBCoordsEditor::SBCoordsEditor(), SBCoordsListItem::text(), and SBReferencePoint::v().
int SBMJD::min () const [inherited]
Definition at line 179 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
int SBMJD::MJD_date (inty, intm, intd) [static, inherited]
Definition at line 72 of file SbGeoTime.C'.
Referenced by SBMJD::dayOfYear(), and SBMJD::setMJD().
void SBMJD::MJD_rev (intdate_, long doubletime_, int &y, int &m, int &d, int &hr, int &mi, double &se) [static, inherited]
Definition at line 95 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::day(), SBMJD::hour(), SBMJD::min(), SBMJD::month(), SBMJD::sec(), SBMJD::toString(), and SBMJD::year().
long double SBMJD::MJD_time (intHour, intMin, doubleSec) [static, inherited]
Definition at line 90 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::setMJD().
int SBMJD::month () const [inherited]
Definition at line 155 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBMJD::month2Str(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
QString SBMJD::month2Str () const [inherited]
Definition at line 203 of file SbGeoTime.C'.
References SBMJD::month(), and SBMJD::monthNames.
Referenced by operator<<().
virtual SBMJD::operator long double () const [inline, virtual, inherited]
Definition at line 89 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator!= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 206 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator+= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 254 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator-= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 262 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator< (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 211 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBCoordinates::operator< (const SBCoordinates &C_) const
Definition at line 367 of file SbGeoStations.C'.
bool SBMJD::operator<= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 217 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBCoordinates & SBCoordinates::operator= (const SBCoordinates &C_)
Definition at line 345 of file SbGeoStations.C'.
References Coo, coo(), CooErrors, cooErrors(), EventName, eventName(), IsUseVels, isUseVels(), Vel, vel(), VelErrors, and velErrors().
bool SBMJD::operator== (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 201 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBCoordinates::operator== (const SBCoordinates &C_) const
Definition at line 358 of file SbGeoStations.C'.
References SBAttributed::attributes(), Coo, coo(), CooErrors, cooErrors(), EventName, eventName(), IsUseVels, isUseVels(), Vel, vel(), VelErrors, and velErrors().
bool SBMJD::operator> (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 223 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator> (doubled) const [inline, virtual, inherited]
Definition at line 229 of file SbGeoTime.H'.
References SBMJD::SBMJD().
bool SBMJD::operator>= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 234 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
double SBMJD::sec () const [inherited]
Definition at line 191 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBCoordinates::setCoo (const Vector3 &C_) [inline]
Definition at line 358 of file SbGeoStations.H'.
References Coo.
Referenced by SBCoordsEditor::acquireData(), and SBReferencePoint::registerCoords().
void SBCoordinates::setCooErrors (const Vector3 &E_) [inline]
Definition at line 359 of file SbGeoStations.H'.
References CooErrors.
Referenced by SBCoordsEditor::acquireData(), and SBReferencePoint::registerCoords().
virtual void SBMJD::setDate (intDate_) [inline, virtual, inherited]
Definition at line 81 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBAploChunk::import().
void SBCoordinates::setEventName (const QString &N_) [inline]
Definition at line 362 of file SbGeoStations.H'.
References EventName.
Referenced by SBCoordsEditor::acquireData(), and SBReferencePoint::registerCoords().
void SBCoordinates::setIsUseVels (boolIs_) [inline]
Definition at line 363 of file SbGeoStations.H'.
References IsUseVels.
Referenced by SBCoordsEditor::acquireData().
void SBMJD::setMJD (intYear, intMonth, intDay, intHour = 0, intMin = 0, doubleSec = 0.0, bool = TRUE) [virtual, inherited]
Definition at line 64 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), SBMJD::MJD_time(), and SBMJD::Time.
Referenced by SBStuffEOPs::accept(), SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBEcc::importEccDat(), operator>>(), SBVLBISession::parseObsDumpString(), SBTest::recalc(), SBStationInfo::restoreUserInfo(), SBMJD::SBMJD(), and SBMJD::setMJD().
void SBMJD::setMJD (FormatF, QStrings, boolisReset = TRUE) [virtual, inherited]
Definition at line 357 of file SbGeoTime.C'.
References SBMJD::ClassName(), SBMJD::Date, SBLog::ERR, SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::INF, Log, SBMJD::min(), SBMJD::MJD_date(), SBMJD::monthNames, SBMJD::sec(), SBMJD::setMJD(), SBMJD::Time, SBLog::TIME, SBLog::write(), and SBLog::WRN.
virtual void SBMJD::setTime (long doubleTime_) [inline, virtual, inherited]
Definition at line 82 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBAploChunk::import().
void SBCoordinates::setVel (const Vector3 &V_) [inline]
Definition at line 360 of file SbGeoStations.H'.
References Vel.
Referenced by SBCoordsEditor::acquireData(), and SBReferencePoint::registerCoords().
void SBCoordinates::setVelErrors (const Vector3 &E_) [inline]
Definition at line 361 of file SbGeoStations.H'.
References VelErrors.
Referenced by SBCoordsEditor::acquireData(), and SBReferencePoint::registerCoords().
long double SBMJD::time () const [inline, inherited]
Definition at line 122 of file SbGeoTime.H'.
References SBMJD::Time.
Referenced by SBOceanTideLd::ARG_IERS(), SBNutation::calcGST(), and SBTestEOP::fillData4Plotting().
QString SBMJD::toString (FormatF = F_Short) const [virtual, inherited]
Definition at line 243 of file SbGeoTime.C'.
References SBMJD::Date, DAY2SEC, SBMJD::dayOfWeek2Str(), SBMJD::dayOfYear(), SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_MJD, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_UNIX, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBMJD::F_YYYYMMDDSSSSSS, SBMJD::min(), SBMJD::MJD_rev(), SBMJD::monthNames, SBMJD::sec(), SBMJD::Time, TUnix0, TZero, and SBMJD::year().
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBEphem::calcI(), SBRunManager::checkParameterLists(), SBEOP::checkRanges(), SBStuffEOPs::createInfoGroup(), SBTestFrame::createWidget4Test(), SBTest::createWidgets(), SBStationEditor::delCoordinates(), SBStuffStationsEcc::deleteEntry(), SBStaParsEditor::deleteEntry(), SBEOP::dEps(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), SBEOP::dLOD(), SBEOP::dPsi(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBPlotArea::drawXmjdTics(), SBDBHHistTriplet::dump(), SBDBHStartBlock::dump(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBVLBIPreProcess::fillSessAttr(), SBEstimator::GroupList::find(), SBStochParameter::find(), SBAploEphem::getReady(), SBEphem::import(), SBEstimator::GroupList::inSort(), SBEOP::interpolateEOPs(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBSolutionBatchLI::key(), SBObsVLBIStatRecordLI::key(), SBEccListItem::key(), SBCoordsListItem::key(), SBAploHeaderLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBAploHeader::name(), SBEphem::openFile(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), operator<<(), operator>>(), SBEOP::prepare4Date(), SBTest::recalc(), SBStationEcc::registerEcc(), SBEstimator::GroupList::remove(), SBParameterList::report(), SBStochParameter::report(), SBStuffAplo::SBStuffAplo(), SBStuffEphem::SBStuffEphem(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), SBTime::setUTC(), sinex_HeaderLine(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_SiteEccentricityBlock(), sinex_SolutionEpochsBlock(), sinex_tro_HeaderLine(), SBObsVLBIStatSrcLI::text(), SBParameterLI::text(), SBVLBIObsPPLI::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBObsVLBIStatRecordLI::text(), SBEccListItem::text(), SBVLBIObsLI::text(), SBCoordsListItem::text(), SBAploHeaderLI::text(), SBClockBreakLI::text(), SBParameter::timeStamp(), SBStuffEOPs::updateEOP(), SBStuffEphem::updateEphem(), SBStuffAplo::updateEphem(), SBVLBIPreProcess::wAttributes(), SBVLBISessionEditor::wParameters(), and SBSourceEditor::wStats().
const Vector3& SBCoordinates::vel () const [inline]
Definition at line 353 of file SbGeoStations.H'.
References Vel.
Referenced by SBCoordsEditor::acquireData(), SBCoordsListItem::key(), operator=(), operator==(), SBReferencePoint::registerCoords(), SBCoordinates(), SBCoordsEditor::SBCoordsEditor(), SBCoordsListItem::text(), and SBReferencePoint::v().
const Vector3& SBCoordinates::velErrors () const [inline]
Definition at line 354 of file SbGeoStations.H'.
References VelErrors.
Referenced by SBCoordsEditor::acquireData(), SBReferencePoint::dV(), SBCoordsListItem::key(), operator=(), operator==(), SBReferencePoint::registerCoords(), SBCoordinates(), SBCoordsEditor::SBCoordsEditor(), and SBCoordsListItem::text().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
int SBMJD::year () const [inherited]
Definition at line 143 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBVLBISesInfo::checkPath(), SBTest::createWidgets(), SBMJD::dayOfYear(), SBVLBISesInfo::fileName(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), and SBMJD::toString().
Friends And Related Function Documentation
SBMJD operator+ (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 270 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 275 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 280 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, floatb) [friend, inherited]
Definition at line 285 of file SbGeoTime.H'.
SBMJD operator+ (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 290 of file SbGeoTime.H'.
SBMJD operator+ (doublea, const SBMJD &B) [friend, inherited]
Definition at line 295 of file SbGeoTime.H'.
SBMJD operator+ (floata, const SBMJD &B) [friend, inherited]
Definition at line 300 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 305 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 310 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 315 of file SbGeoTime.H'.
SBMJD operator- (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 320 of file SbGeoTime.H'.
SBMJD operator- (inta, const SBMJD &B) [friend, inherited]
Definition at line 325 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBMJD &MJD) [friend, inherited]
Definition at line 330 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator<< (QDataStream &s, const SBCoordinates &C) [friend]
Definition at line 372 of file SbGeoStations.H'.
QDataStream& operator>> (QDataStream &s, SBMJD &MJD) [friend, inherited]
Definition at line 337 of file SbGeoTime.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBCoordinates &C) [friend]
Definition at line 375 of file SbGeoStations.H'.
Member Data Documentation
Vector3 SBCoordinates::Coo [private]
coordinates
Definition at line 331 of file SbGeoStations.H'.
Referenced by coo(), operator=(), operator==(), SBCoordinates(), and setCoo().
Vector3 SBCoordinates::CooErrors [private]
uncert'. of coordinates
Definition at line 332 of file SbGeoStations.H'.
Referenced by cooErrors(), operator=(), operator==(), SBCoordinates(), and setCooErrors().
QString SBCoordinates::EventName [private]
the cause of a change in the coordinates
Definition at line 335 of file SbGeoStations.H'.
Referenced by eventName(), operator=(), operator==(), SBCoordinates(), and setEventName().
bool SBCoordinates::IsUseVels [private]
Definition at line 336 of file SbGeoStations.H'.
Referenced by isUseVels(), operator=(), operator==(), SBCoordinates(), and setIsUseVels().
const char * SBMJD::monthNames [static, protected, inherited]"Initial value:
 
{
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
}
Definition at line 63 of file SbGeoTime.H'.
Referenced by SBMJD::month2Str(), SBMJD::setMJD(), and SBMJD::toString().
Vector3 SBCoordinates::Vel [private]
velocities
Definition at line 333 of file SbGeoStations.H'.
Referenced by operator=(), operator==(), SBCoordinates(), setVel(), and vel().
Vector3 SBCoordinates::VelErrors [private]
uncert'. of velocities
Definition at line 334 of file SbGeoStations.H'.
Referenced by operator=(), operator==(), SBCoordinates(), setVelErrors(), and velErrors().
const char * SBMJD::weekdayNames [static, protected, inherited]"Initial value:
{
  'Mon','Tue','Wed','Thu','Fri','Sat','Sun'
}
Definition at line 64 of file SbGeoTime.H'.
Referenced by SBMJD::dayOfWeek2Str().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.