SBConfig
NAME
SBConfig -
SYNOPSIS
#include <SbGeoProject.H>
Public Types
enum MSysTransform { STR_Classic, STR_NRO }
enum MSolidTideLd { ST_IERS92, ST_IERS96 }
enum MSolidTideDegree { STDEGREE_2, STDEGREE_3 }
enum MEOPDiurnal { EDM_NONE, EDM_Ray1995, EDM_JPL92, EDM_HD1994, EDM_GSFC95, EDM_Gipson1995 }
enum MEOPDiurnalAtm { EDMA_NONE, EDMA_BBP }
enum MEOPDiurnalNonTidal { EDMNT_NONE, EDMNT_Viron }
enum MNutModel { NM_IAU1980, NM_IAU1996, NM_IAU2000 }
enum MNutEqEquinox { NEE_IERS92, NEE_SOVERS, NEE_IERS96 }
enum MEphModel { EM_LEDE200, EM_LEDE403, EM_LEDE405 }
enum MPlateMotion { PM_NNR_NUVEL1A, PM_NUVEL1A, PM_NONE }
enum MRefrDryZenith { RDZ_NONE, RDZ_Saastamoinen, RDZ_Hopfield }
enum MRefrWetZenith { RWZ_NONE, RWZ_Saastamoinen, RWZ_Hopfield }
enum MRefrDryMapping { RDM_NONE, RDM_Chao, RDM_CfA2p2, RDM_Ifadis, RDM_MTT, RDM_NMFH2 }
enum MRefrWetMapping { RWM_NONE, RWM_Chao, RWM_Ifadis, RWM_MTT, RDM_NMFW2 }
Public Member Functions
SBConfig ()
SBConfig (const SBConfig &Cfg_)
virtual ~SBConfig ()
SBConfig & operator= (const SBConfig &)
virtual QString ClassName () const
MSysTransform sysTransform () const
void setSysTransform (MSysTransform E_)
MEphModel ephemModel () const
bool isEphBody (int i) const
bool isGravDelayHO () const
double gravHOThreshold () const
void setEphemModel (MEphModel E_)
void setIsEphBody (int i, bool Is_)
void setIsGravDelayHO (bool Is_)
void setGravHOThreshold (double d_)
MSolidTideLd solidTideLd () const
MSolidTideDegree solidTideDegree () const
bool isSolidTideAnelastic () const
bool isSolidTideLatDepend () const
bool isRemovePermTide () const
void setSolidTideLd (MSolidTideLd S_)
void setSolidTideDegree (MSolidTideDegree D_)
void setIsSolidTideAnelastic (bool Is_)
void setIsSolidTideLatDepend (bool Is_)
void setIsRemovePermTide (bool Is_)
MEOPDiurnal eopDiurnal () const
MEOPDiurnalAtm eopDiurnalAtm () const
MEOPDiurnalNonTidal eopDiurnalNonTidal () const
int eopNumIntrplPoints () const
bool isEOP_IAU2K_XY () const
bool isEOPResrerved_1 () const
void setEopDiurnal (MEOPDiurnal E_)
void setEopDiurnalAtm (MEOPDiurnalAtm E_)
void setEopDiurnalNonTidal (MEOPDiurnalNonTidal E_)
void setEOPNumIntrplPoints (int N_)
void setIsEOP_IAU2K_XY (bool Is_)
void setIsEOPResrerved_1 (bool Is_)
MNutModel nutModel () const
MNutEqEquinox nutEquinox () const
bool isNeedGeodNut () const
void setNutModel (MNutModel M_)
void setNutEquinox (MNutEqEquinox E_)
void setIsNeedGeodNut (bool Is_)
MPlateMotion plateMotion () const
void setPlateMotion (MPlateMotion P_)
bool isUseStationVelocity () const
bool isRollBack2Plates () const
bool isUseAploEphem () const
void setIsUseStationVelocity (bool Is_)
void setIsRollBack2Plates (bool Is_)
void setIsUseAploEphem (bool Is_)
MRefrDryZenith refrDryZenith () const
MRefrWetZenith refrWetZenith () const
MRefrDryMapping refrDryMapping () const
MRefrWetMapping refrWetMapping () const
bool isAltAxsCorr () const
bool isRollBack2NMF () const
void setRefrDryZenith (MRefrDryZenith DZ_)
void setRefrWetZenith (MRefrWetZenith WZ_)
void setRefrDryMapping (MRefrDryMapping DM_)
void setRefrWetMapping (MRefrWetMapping WM_)
void setIsAltAxsCorr (bool Is_)
void setIsRollBack2NMF (bool Is_)
int qCodeThreshold () const
int dUFlagThreshold () const
bool isUseDelay () const
bool isUseRate () const
bool isUseBadIon () const
void setQCodeThreshold (int Threshold_)
void setDUFlagThreshold (int Threshold_)
void setIsUseDelay (bool Is_)
void setIsUseRate (bool Is_)
void setIsUseBadIon (bool Is_)
bool reportMaps () const
bool reportCRF_Changes () const
bool reportTRF_Changes () const
bool reportCRF () const
bool reportTRF_SINEX () const
bool reportEOP () const
bool reportTechDesc () const
bool reportNormalEqs () const
bool reportNormalEqsSRCs () const
bool reportNormalEqsSTCs () const
bool reportNormalEqsEOPs () const
bool reportTroposhere () const
double tropSamplInterval () const
int tropStartSec () const
void setReportMaps (bool Is_)
void setReportCRF_Changes (bool Is_)
void setReportTRF_Changes (bool Is_)
void setReportCRF (bool Is_)
void setReportTRF_SINEX (bool Is_)
void setReportEOP (bool Is_)
void setReportTechDesc (bool Is_)
void setReportNormalEqs (bool Is_)
void setReportNormalEqsSRCs (bool Is_)
void setReportNormalEqsSTCs (bool Is_)
void setReportNormalEqsEOPs (bool Is_)
void setReportTroposhere (bool Is_)
void setTropSamplInterval (double d_)
void setTropStartSec (int n_)
bool useAltStations () const
bool useAltSources () const
bool useAltEOPs () const
const QString & altStations () const
const QString & altSources () const
const QString & altEOPs () const
void setUseAltStations (bool Is_)
void setUseAltSources (bool Is_)
void setUseAltEOPs (bool Is_)
void setAltStations (const QString &S_)
void setAltSources (const QString &S_)
void setAltEOPs (const QString &S_)
bool isGenerateDSINEXes () const
void setIsGenerateDSINEXes (bool Is_)
bool isChanged () const
void setIsChanged (bool Is_=TRUE)
const SBParametersDesc & p () const
void setP (const SBParametersDesc &P_)
void setAllPars2Type (SBParameterCfg::PType)
Private Attributes
bool IsChanged
SBParametersDesc P
MSysTransform SysTransform
Type of CRF<->TRF system transformation'.
MEphModel EphemModel
Ephemerides model'.
bool IsEphBody [11]
Celestial bodies taking into account'.
bool IsGravDelayHO
High order effects'.
double GravHOThreshold
Threshold for high order effects, rad'.
MSolidTideLd SolidTideLd
Site displacement load model due to solid tide'.
MSolidTideDegree SolidTideDegree
Maximum degree of solid tide loading model'.
bool IsSolidTideAnelastic
Anelastic or elastic model'.
bool IsSolidTideLatDepend
Include Solid Tide Latitude dependence'.
bool IsRemovePermTide
Remove permanent tide'.
MEOPDiurnal EOPDiurnal
Take into account diurnal variations in EOP'.
MEOPDiurnalAtm EOPDiurnalAtm
Take into account diurnal variations in EOP (atmosphere)
MEOPDiurnalNonTidal EOPDiurnalNonTidal
Take into account diurnal variations in EOP (non-tidal)
int EOPNumIntrplPoints
Number of points for interpolation'.
bool IsEOP_IAU2K_XY
Nutations in EOP are dX and dY w/ respect to IAU2000'.
bool IsEOPResrerved_1
Reserved for use with EOP'.
MNutModel NutModel
Nutation theory model'.
MNutEqEquinox NutEquinox
Model of the Equation of equinoxes'.
bool IsNutGeodNut
Take into account geodesic nutation'.
MPlateMotion PlateMotion
Tectonic plate motion model'.
bool IsUseStationVelocity
Use velocity of a station from a catalogue'.
bool IsRollBack2Plates
Use plate motion vel'. if V=0'.
bool IsUseAploEphem
Use atmoshperic loading ephemerides'.
MRefrDryZenith RefrDryZenith
Hydrostatic zenith delay model;'.
MRefrWetZenith RefrWetZenith
Wet zenith delay model;'.
MRefrDryMapping RefrDryMapping
Hydrostatic mapping function model;'.
MRefrWetMapping RefrWetMapping
Wet mapping function model;'.
bool IsAltAxsCorr
Take into axis offset altitude correction;'.
bool IsRollBack2NMF
Use NMFs in the case of bad/art metheo;'.
int QCodeThreshold
int DUFlagThreshold
bool IsUseDelay
bool IsUseRate
bool IsUseBadIon
bool ReportMaps
bool ReportCRF_Changes
bool ReportTRF_Changes
bool ReportCRF
bool ReportTRF_SINEX
bool ReportEOP
bool ReportTechDesc
bool ReportNormalEqs
Make report of NEQ in SINEX format;'.
bool ReportNormalEqsSRCs
Include sources in NEQ report;'.
bool ReportNormalEqsSTCs
Include stations in NEQ report;'.
bool ReportNormalEqsEOPs
Include EOP in NEQ report;'.
bool ReportTroposhere
double TropSamplInterval
int TropStartSec
bool UseAltStations
bool UseAltSources
bool UseAltEOPs
QString AltStations
QString AltSources
QString AltEOPs
bool IsGenerateDSINEXes
Friends
QDataStream & operator<< (QDataStream &, const SBConfig &)
QDataStream & operator>> (QDataStream &, SBConfig &)
Detailed Description
Runtime configuration of the models'.
Definition at line 61 of file SbGeoProject.H'.
Member Enumeration Documentation
enum SBConfig::MEOPDiurnal
Enumerator:
EDM_NONE
EDM_Ray1995
EDM_JPL92
EDM_HD1994
EDM_GSFC95
EDM_Gipson1995
Definition at line 67 of file SbGeoProject.H'.
enum SBConfig::MEOPDiurnalAtm
Enumerator:
EDMA_NONE
EDMA_BBP
Definition at line 68 of file SbGeoProject.H'.
enum SBConfig::MEOPDiurnalNonTidal
Enumerator:
EDMNT_NONE
EDMNT_Viron
Definition at line 69 of file SbGeoProject.H'.
enum SBConfig::MEphModel
Enumerator:
EM_LEDE200
EM_LEDE403
EM_LEDE405
Definition at line 72 of file SbGeoProject.H'.
enum SBConfig::MNutEqEquinox
Enumerator:
NEE_IERS92
NEE_SOVERS
NEE_IERS96
Definition at line 71 of file SbGeoProject.H'.
enum SBConfig::MNutModel
Enumerator:
NM_IAU1980
NM_IAU1996
NM_IAU2000
Definition at line 70 of file SbGeoProject.H'.
enum SBConfig::MPlateMotion
Enumerator:
PM_NNR_NUVEL1A
PM_NUVEL1A
PM_NONE
Definition at line 73 of file SbGeoProject.H'.
enum SBConfig::MRefrDryMapping
Enumerator:
RDM_NONE
RDM_Chao
RDM_CfA2p2
RDM_Ifadis
RDM_MTT
RDM_NMFH2
Definition at line 76 of file SbGeoProject.H'.
enum SBConfig::MRefrDryZenith
Enumerator:
RDZ_NONE
RDZ_Saastamoinen
RDZ_Hopfield
Definition at line 74 of file SbGeoProject.H'.
enum SBConfig::MRefrWetMapping
Enumerator:
RWM_NONE
RWM_Chao
RWM_Ifadis
RWM_MTT
RDM_NMFW2
Definition at line 77 of file SbGeoProject.H'.
enum SBConfig::MRefrWetZenith
Enumerator:
RWZ_NONE
RWZ_Saastamoinen
RWZ_Hopfield
Definition at line 75 of file SbGeoProject.H'.
enum SBConfig::MSolidTideDegree
Enumerator:
STDEGREE_2
STDEGREE_3
Definition at line 66 of file SbGeoProject.H'.
enum SBConfig::MSolidTideLd
Enumerator:
ST_IERS92
ST_IERS96
Definition at line 65 of file SbGeoProject.H'.
enum SBConfig::MSysTransform
Enumerator:
STR_Classic
STR_NRO
Definition at line 64 of file SbGeoProject.H'.
Constructor & Destructor Documentation
SBConfig::SBConfig ()"A constructor'.
A constructor'. Creates a copy of object'.
Definition at line 64 of file SbGeoProject.C'.
References AltEOPs, AltSources, AltStations, DEG2RAD, DUFlagThreshold, EDM_Ray1995, EDMA_NONE, EDMNT_NONE, EM_LEDE405, EOPDiurnal, EOPDiurnalAtm, EOPDiurnalNonTidal, EOPNumIntrplPoints, EphemModel, GravHOThreshold, IsAltAxsCorr, IsChanged, IsEOP_IAU2K_XY, IsEOPResrerved_1, IsEphBody, IsGenerateDSINEXes, IsGravDelayHO, IsNutGeodNut, IsRemovePermTide, IsRollBack2NMF, IsRollBack2Plates, IsSolidTideAnelastic, IsSolidTideLatDepend, IsUseAploEphem, IsUseBadIon, IsUseDelay, IsUseRate, IsUseStationVelocity, NEE_IERS96, NM_IAU1980, NutEquinox, NutModel, PlateMotion, PM_NNR_NUVEL1A, QCodeThreshold, RDM_MTT, RDZ_Saastamoinen, RefrDryMapping, RefrDryZenith, RefrWetMapping, RefrWetZenith, ReportCRF, ReportCRF_Changes, ReportEOP, ReportMaps, ReportNormalEqs, ReportNormalEqsEOPs, ReportNormalEqsSRCs, ReportNormalEqsSTCs, ReportTechDesc, ReportTRF_Changes, ReportTRF_SINEX, ReportTroposhere, RWM_MTT, RWZ_Saastamoinen, SolidTideDegree, SolidTideLd, ST_IERS96, STDEGREE_3, STR_Classic, SysTransform, TropSamplInterval, TropStartSec, UseAltEOPs, UseAltSources, and UseAltStations.
SBConfig::SBConfig (const SBConfig &Cfg_) [inline]"A constructor'.
Definition at line 167 of file SbGeoProject.H'.
virtual SBConfig::~SBConfig () [inline, virtual]"A destructor'.
Definition at line 169 of file SbGeoProject.H'.
Member Function Documentation
const QString& SBConfig::altEOPs () const [inline]
Definition at line 295 of file SbGeoProject.H'.
References AltEOPs.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wSysTransform().
const QString& SBConfig::altSources () const [inline]
Definition at line 294 of file SbGeoProject.H'.
References AltSources.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wSysTransform().
const QString& SBConfig::altStations () const [inline]
Definition at line 293 of file SbGeoProject.H'.
References AltStations.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wSysTransform().
virtual QString SBConfig::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Definition at line 172 of file SbGeoProject.H'.
int SBConfig::dUFlagThreshold () const [inline]
Definition at line 249 of file SbGeoProject.H'.
References DUFlagThreshold.
Referenced by SBModelEditor::acquireData(), SBObsVLBIEntry::isEligible(), SBModelEditor::makeDefault(), and SBModelEditor::wDataProcessing().
MEOPDiurnal SBConfig::eopDiurnal () const [inline]
Definition at line 202 of file SbGeoProject.H'.
References EOPDiurnal.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBFrame::SBFrame(), and SBModelEditor::wEOPs().
MEOPDiurnalAtm SBConfig::eopDiurnalAtm () const [inline]
Definition at line 203 of file SbGeoProject.H'.
References EOPDiurnalAtm.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBFrame::SBFrame(), and SBModelEditor::wEOPs().
MEOPDiurnalNonTidal SBConfig::eopDiurnalNonTidal () const [inline]
Definition at line 204 of file SbGeoProject.H'.
References EOPDiurnalNonTidal.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBFrame::SBFrame(), and SBModelEditor::wEOPs().
int SBConfig::eopNumIntrplPoints () const [inline]
Definition at line 205 of file SbGeoProject.H'.
References EOPNumIntrplPoints.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBFrame::SBFrame(), SBTestEOP::SBTestEOP(), SBTestNutation::SBTestNutation(), and SBModelEditor::wEOPs().
MEphModel SBConfig::ephemModel () const [inline]
Definition at line 180 of file SbGeoProject.H'.
References EphemModel.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBStuffEphem::SBStuffEphem(), SBTestEphem::SBTestEphem(), SBTestSolidTides::SBTestSolidTides(), and SBModelEditor::wLightPropagation().
double SBConfig::gravHOThreshold () const [inline]
Definition at line 183 of file SbGeoProject.H'.
References GravHOThreshold.
Referenced by SBModelEditor::acquireData(), SBDelay::calc(), SBModelEditor::makeDefault(), and SBModelEditor::wLightPropagation().
bool SBConfig::isAltAxsCorr () const [inline]
Definition at line 238 of file SbGeoProject.H'.
References IsAltAxsCorr.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRefraction::operator()(), and SBModelEditor::wRefraction().
bool SBConfig::isChanged () const [inline]
Definition at line 308 of file SbGeoProject.H'.
References IsChanged.
Referenced by SBSetUp::SaveStuff().
bool SBConfig::isEOP_IAU2K_XY () const [inline]
Definition at line 206 of file SbGeoProject.H'.
References IsEOP_IAU2K_XY.
Referenced by SBModelEditor::acquireData(), SBEOP::interpolateEOPs(), SBModelEditor::makeDefault(), and SBModelEditor::wEOPs().
bool SBConfig::isEOPResrerved_1 () const [inline]
Definition at line 207 of file SbGeoProject.H'.
References IsEOPResrerved_1.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wEOPs().
bool SBConfig::isEphBody (inti) const [inline]
Definition at line 181 of file SbGeoProject.H'.
References IsEphBody.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBEphem::SBEphem(), and SBModelEditor::wLightPropagation().
bool SBConfig::isGenerateDSINEXes () const [inline]
Definition at line 304 of file SbGeoProject.H'.
References IsGenerateDSINEXes.
Referenced by SBModelEditor::acquireData(), SBEstimator::finisLocal(), SBRunManager::finisRun_m1(), and SBModelEditor::wDataProcessing().
bool SBConfig::isGravDelayHO () const [inline]
Definition at line 182 of file SbGeoProject.H'.
References IsGravDelayHO.
Referenced by SBModelEditor::acquireData(), SBDelay::calc(), SBModelEditor::makeDefault(), and SBModelEditor::wLightPropagation().
bool SBConfig::isNeedGeodNut () const [inline]
Definition at line 218 of file SbGeoProject.H'.
References IsNutGeodNut.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBNut_IAU1980::operator()(), and SBModelEditor::wNutation().
bool SBConfig::isRemovePermTide () const [inline]
Definition at line 194 of file SbGeoProject.H'.
References IsRemovePermTide.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBSolidTideLd::operator()(), and SBModelEditor::wSolidTide().
bool SBConfig::isRollBack2NMF () const [inline]
Definition at line 239 of file SbGeoProject.H'.
References IsRollBack2NMF.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRefraction::SBRefraction(), sinex_tro_TropDescriptionBlock(), and SBModelEditor::wRefraction().
bool SBConfig::isRollBack2Plates () const [inline]
Definition at line 227 of file SbGeoProject.H'.
References IsRollBack2Plates.
Referenced by SBModelEditor::acquireData(), SBStation::calcDisplacement(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBModelEditor::makeDefault(), SBStation::vModel(), and SBModelEditor::wPlateMotion().
bool SBConfig::isSolidTideAnelastic () const [inline]
Definition at line 192 of file SbGeoProject.H'.
References IsSolidTideAnelastic.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBSolidTideLdIERS96::makeStep1(), SBSolidTideLdIERS96::makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::SBSolidTideLd(), SBSolidTideLdIERS96::SBSolidTideLdIERS96(), and SBModelEditor::wSolidTide().
bool SBConfig::isSolidTideLatDepend () const [inline]
Definition at line 193 of file SbGeoProject.H'.
References IsSolidTideLatDepend.
Referenced by SBModelEditor::acquireData(), SBSolidTideLd::h2(), SBSolidTideLd::l2(), SBModelEditor::makeDefault(), SBSolidTideLdIERS96::makeStep1(), SBSolidTideLd::operator()(), and SBModelEditor::wSolidTide().
bool SBConfig::isUseAploEphem () const [inline]
Definition at line 228 of file SbGeoProject.H'.
References IsUseAploEphem.
Referenced by SBModelEditor::acquireData(), SBStation::calcDisplacement(), SBModelEditor::makeDefault(), and SBModelEditor::wPlateMotion().
bool SBConfig::isUseBadIon () const [inline]
Definition at line 252 of file SbGeoProject.H'.
References IsUseBadIon.
Referenced by SBModelEditor::acquireData(), SBObsVLBIEntry::isEligible(), and SBModelEditor::wDataProcessing().
bool SBConfig::isUseDelay () const [inline]
Definition at line 250 of file SbGeoProject.H'.
References IsUseDelay.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wDataProcessing().
bool SBConfig::isUseRate () const [inline]
Definition at line 251 of file SbGeoProject.H'.
References IsUseRate.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wDataProcessing().
bool SBConfig::isUseStationVelocity () const [inline]
Definition at line 226 of file SbGeoProject.H'.
References IsUseStationVelocity.
Referenced by SBModelEditor::acquireData(), SBStation::calcDisplacement(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBModelEditor::makeDefault(), SBStation::vModel(), and SBModelEditor::wPlateMotion().
MNutEqEquinox SBConfig::nutEquinox () const [inline]
Definition at line 217 of file SbGeoProject.H'.
References NutEquinox.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBModelEditor::wNutation().
MNutModel SBConfig::nutModel () const [inline]
Definition at line 216 of file SbGeoProject.H'.
References NutModel.
Referenced by SBModelEditor::acquireData(), SBEOP::interpolateEOPs(), SBModelEditor::makeDefault(), operator<<(), SBFrame::SBFrame(), SBFrameClassic::SBFrameClassic(), SBNut_IAU1980::SBNut_IAU1980(), SBTestEOP::SBTestEOP(), SBTestNutation::SBTestNutation(), SBModelEditor::wNutation(), and writeNormalEquationSystem().
SBConfig & SBConfig::operator= (const SBConfig &C)
Definition at line 148 of file SbGeoProject.C'.
References AltEOPs, AltSources, AltStations, DUFlagThreshold, EOPDiurnal, EOPDiurnalAtm, EOPDiurnalNonTidal, EOPNumIntrplPoints, EphemModel, GravHOThreshold, IsAltAxsCorr, IsChanged, IsEOP_IAU2K_XY, IsEOPResrerved_1, IsEphBody, IsGenerateDSINEXes, IsGravDelayHO, IsNutGeodNut, IsRemovePermTide, IsRollBack2NMF, IsRollBack2Plates, IsSolidTideAnelastic, IsSolidTideLatDepend, IsUseAploEphem, IsUseBadIon, IsUseDelay, IsUseRate, IsUseStationVelocity, NutEquinox, NutModel, P, PlateMotion, QCodeThreshold, RefrDryMapping, RefrDryZenith, RefrWetMapping, RefrWetZenith, ReportCRF, ReportCRF_Changes, ReportEOP, ReportMaps, ReportNormalEqs, ReportNormalEqsEOPs, ReportNormalEqsSRCs, ReportNormalEqsSTCs, ReportTechDesc, ReportTRF_Changes, ReportTRF_SINEX, ReportTroposhere, SolidTideDegree, SolidTideLd, SysTransform, TropSamplInterval, TropStartSec, UseAltEOPs, UseAltSources, and UseAltStations.
const SBParametersDesc& SBConfig::p () const [inline]
Definition at line 310 of file SbGeoProject.H'.
References P.
Referenced by SBDelay::calc(), SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), SBParametersEditor::makeDefault(), SBParEditor::makeDefault(), SBProject::p(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBStationInfo::SBStationInfo(), sinex_tro_TropDescriptionBlock(), and SBVLBIPreProcess::wEstPars().
MPlateMotion SBConfig::plateMotion () const [inline]
Definition at line 224 of file SbGeoProject.H'.
References PlateMotion.
Referenced by SBModelEditor::acquireData(), SBStation::calcDisplacement(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBModelEditor::makeDefault(), SBStation::vModel(), and SBModelEditor::wPlateMotion().
int SBConfig::qCodeThreshold () const [inline]
Definition at line 248 of file SbGeoProject.H'.
References QCodeThreshold.
Referenced by SBModelEditor::acquireData(), SBObsVLBIEntry::isEligible(), SBModelEditor::makeDefault(), and SBModelEditor::wDataProcessing().
MRefrDryMapping SBConfig::refrDryMapping () const [inline]
Definition at line 236 of file SbGeoProject.H'.
References RefrDryMapping.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRefraction::SBRefraction(), sinex_tro_TropDescriptionBlock(), and SBModelEditor::wRefraction().
MRefrDryZenith SBConfig::refrDryZenith () const [inline]
Definition at line 234 of file SbGeoProject.H'.
References RefrDryZenith.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRefraction::SBRefraction(), sinex_tro_TropDescriptionBlock(), and SBModelEditor::wRefraction().
MRefrWetMapping SBConfig::refrWetMapping () const [inline]
Definition at line 237 of file SbGeoProject.H'.
References RefrWetMapping.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRefraction::SBRefraction(), sinex_tro_TropDescriptionBlock(), and SBModelEditor::wRefraction().
MRefrWetZenith SBConfig::refrWetZenith () const [inline]
Definition at line 235 of file SbGeoProject.H'.
References RefrWetZenith.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRefraction::SBRefraction(), sinex_tro_TropDescriptionBlock(), and SBModelEditor::wRefraction().
bool SBConfig::reportCRF () const [inline]
Definition at line 263 of file SbGeoProject.H'.
References ReportCRF.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportCRF_Changes () const [inline]
Definition at line 261 of file SbGeoProject.H'.
References ReportCRF_Changes.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportEOP () const [inline]
Definition at line 265 of file SbGeoProject.H'.
References ReportEOP.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportMaps () const [inline]
Definition at line 260 of file SbGeoProject.H'.
References ReportMaps.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportNormalEqs () const [inline]
Definition at line 267 of file SbGeoProject.H'.
References ReportNormalEqs.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportNormalEqsEOPs () const [inline]
Definition at line 270 of file SbGeoProject.H'.
References ReportNormalEqsEOPs.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), writeNormalEquationSystem(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportNormalEqsSRCs () const [inline]
Definition at line 268 of file SbGeoProject.H'.
References ReportNormalEqsSRCs.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), writeNormalEquationSystem(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportNormalEqsSTCs () const [inline]
Definition at line 269 of file SbGeoProject.H'.
References ReportNormalEqsSTCs.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), writeNormalEquationSystem(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportTechDesc () const [inline]
Definition at line 266 of file SbGeoProject.H'.
References ReportTechDesc.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportTRF_Changes () const [inline]
Definition at line 262 of file SbGeoProject.H'.
References ReportTRF_Changes.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportTRF_SINEX () const [inline]
Definition at line 264 of file SbGeoProject.H'.
References ReportTRF_SINEX.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
bool SBConfig::reportTroposhere () const [inline]
Definition at line 271 of file SbGeoProject.H'.
References ReportTroposhere.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReports(), and SBModelEditor::wSolutionReports().
void SBConfig::setAllPars2Type (SBParameterCfg::PTypeType)
Definition at line 233 of file SbGeoProject.C'.
References SBParametersDesc::num(), P, and SBParametersDesc::setType().
Referenced by SBProject::setAllPars2Type().
void SBConfig::setAltEOPs (const QString &S_) [inline]
Definition at line 301 of file SbGeoProject.H'.
References AltEOPs.
Referenced by SBModelEditor::acquireData().
void SBConfig::setAltSources (const QString &S_) [inline]
Definition at line 300 of file SbGeoProject.H'.
References AltSources.
Referenced by SBModelEditor::acquireData().
void SBConfig::setAltStations (const QString &S_) [inline]
Definition at line 299 of file SbGeoProject.H'.
References AltStations.
Referenced by SBModelEditor::acquireData().
void SBConfig::setDUFlagThreshold (intThreshold_) [inline]
Definition at line 254 of file SbGeoProject.H'.
References DUFlagThreshold.
Referenced by SBModelEditor::acquireData().
void SBConfig::setEopDiurnal (MEOPDiurnalE_) [inline]
Definition at line 208 of file SbGeoProject.H'.
References EOPDiurnal.
Referenced by SBModelEditor::acquireData().
void SBConfig::setEopDiurnalAtm (MEOPDiurnalAtmE_) [inline]
Definition at line 209 of file SbGeoProject.H'.
References EOPDiurnalAtm.
Referenced by SBModelEditor::acquireData().
void SBConfig::setEopDiurnalNonTidal (MEOPDiurnalNonTidalE_) [inline]
Definition at line 210 of file SbGeoProject.H'.
References EOPDiurnalNonTidal.
Referenced by SBModelEditor::acquireData().
void SBConfig::setEOPNumIntrplPoints (intN_) [inline]
Definition at line 211 of file SbGeoProject.H'.
References EOPNumIntrplPoints.
Referenced by SBModelEditor::acquireData().
void SBConfig::setEphemModel (MEphModelE_) [inline]
Definition at line 184 of file SbGeoProject.H'.
References EphemModel.
Referenced by SBModelEditor::acquireData().
void SBConfig::setGravHOThreshold (doubled_) [inline]
Definition at line 187 of file SbGeoProject.H'.
References GravHOThreshold.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsAltAxsCorr (boolIs_) [inline]
Definition at line 244 of file SbGeoProject.H'.
References IsAltAxsCorr.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsChanged (boolIs_ = TRUE) [inline]
Definition at line 309 of file SbGeoProject.H'.
References IsChanged.
Referenced by SBVLBIPreProcess::preProcess().
void SBConfig::setIsEOP_IAU2K_XY (boolIs_) [inline]
Definition at line 212 of file SbGeoProject.H'.
References IsEOP_IAU2K_XY.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsEOPResrerved_1 (boolIs_) [inline]
Definition at line 213 of file SbGeoProject.H'.
References IsEOPResrerved_1.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsEphBody (inti, boolIs_) [inline]
Definition at line 185 of file SbGeoProject.H'.
References IsEphBody.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsGenerateDSINEXes (boolIs_) [inline]
Definition at line 305 of file SbGeoProject.H'.
References IsGenerateDSINEXes.
Referenced by SBModelEditor::acquireData(), and SBRunManager::finisRun_m1().
void SBConfig::setIsGravDelayHO (boolIs_) [inline]
Definition at line 186 of file SbGeoProject.H'.
References IsGravDelayHO.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsNeedGeodNut (boolIs_) [inline]
Definition at line 221 of file SbGeoProject.H'.
References IsNutGeodNut.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsRemovePermTide (boolIs_) [inline]
Definition at line 199 of file SbGeoProject.H'.
References IsRemovePermTide.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsRollBack2NMF (boolIs_) [inline]
Definition at line 245 of file SbGeoProject.H'.
References IsRollBack2NMF.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsRollBack2Plates (boolIs_) [inline]
Definition at line 230 of file SbGeoProject.H'.
References IsRollBack2Plates.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsSolidTideAnelastic (boolIs_) [inline]
Definition at line 197 of file SbGeoProject.H'.
References IsSolidTideAnelastic.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsSolidTideLatDepend (boolIs_) [inline]
Definition at line 198 of file SbGeoProject.H'.
References IsSolidTideLatDepend.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsUseAploEphem (boolIs_) [inline]
Definition at line 231 of file SbGeoProject.H'.
References IsUseAploEphem.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsUseBadIon (boolIs_) [inline]
Definition at line 257 of file SbGeoProject.H'.
References IsUseBadIon.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsUseDelay (boolIs_) [inline]
Definition at line 255 of file SbGeoProject.H'.
References IsUseDelay.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsUseRate (boolIs_) [inline]
Definition at line 256 of file SbGeoProject.H'.
References IsUseRate.
Referenced by SBModelEditor::acquireData().
void SBConfig::setIsUseStationVelocity (boolIs_) [inline]
Definition at line 229 of file SbGeoProject.H'.
References IsUseStationVelocity.
Referenced by SBModelEditor::acquireData().
void SBConfig::setNutEquinox (MNutEqEquinoxE_) [inline]
Definition at line 220 of file SbGeoProject.H'.
References NutEquinox.
Referenced by SBModelEditor::acquireData().
void SBConfig::setNutModel (MNutModelM_) [inline]
Definition at line 219 of file SbGeoProject.H'.
References NutModel.
Referenced by SBModelEditor::acquireData().
void SBConfig::setP (const SBParametersDesc &P_) [inline]
Definition at line 311 of file SbGeoProject.H'.
References P.
Referenced by SBVLBIPreProcess::preProcess(), SBProject::setP(), and SBParametersEditor::~SBParametersEditor().
void SBConfig::setPlateMotion (MPlateMotionP_) [inline]
Definition at line 225 of file SbGeoProject.H'.
References PlateMotion.
Referenced by SBModelEditor::acquireData().
void SBConfig::setQCodeThreshold (intThreshold_) [inline]
Definition at line 253 of file SbGeoProject.H'.
References QCodeThreshold.
Referenced by SBModelEditor::acquireData().
void SBConfig::setRefrDryMapping (MRefrDryMappingDM_) [inline]
Definition at line 242 of file SbGeoProject.H'.
References RefrDryMapping.
Referenced by SBModelEditor::acquireData().
void SBConfig::setRefrDryZenith (MRefrDryZenithDZ_) [inline]
Definition at line 240 of file SbGeoProject.H'.
References RefrDryZenith.
Referenced by SBModelEditor::acquireData().
void SBConfig::setRefrWetMapping (MRefrWetMappingWM_) [inline]
Definition at line 243 of file SbGeoProject.H'.
References RefrWetMapping.
Referenced by SBModelEditor::acquireData().
void SBConfig::setRefrWetZenith (MRefrWetZenithWZ_) [inline]
Definition at line 241 of file SbGeoProject.H'.
References RefrWetZenith.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportCRF (boolIs_) [inline]
Definition at line 277 of file SbGeoProject.H'.
References ReportCRF.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportCRF_Changes (boolIs_) [inline]
Definition at line 275 of file SbGeoProject.H'.
References ReportCRF_Changes.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportEOP (boolIs_) [inline]
Definition at line 279 of file SbGeoProject.H'.
References ReportEOP.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportMaps (boolIs_) [inline]
Definition at line 274 of file SbGeoProject.H'.
References ReportMaps.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportNormalEqs (boolIs_) [inline]
Definition at line 281 of file SbGeoProject.H'.
References ReportNormalEqs.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportNormalEqsEOPs (boolIs_) [inline]
Definition at line 284 of file SbGeoProject.H'.
References ReportNormalEqsEOPs.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportNormalEqsSRCs (boolIs_) [inline]
Definition at line 282 of file SbGeoProject.H'.
References ReportNormalEqsSRCs.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportNormalEqsSTCs (boolIs_) [inline]
Definition at line 283 of file SbGeoProject.H'.
References ReportNormalEqsSTCs.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportTechDesc (boolIs_) [inline]
Definition at line 280 of file SbGeoProject.H'.
References ReportTechDesc.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportTRF_Changes (boolIs_) [inline]
Definition at line 276 of file SbGeoProject.H'.
References ReportTRF_Changes.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportTRF_SINEX (boolIs_) [inline]
Definition at line 278 of file SbGeoProject.H'.
References ReportTRF_SINEX.
Referenced by SBModelEditor::acquireData().
void SBConfig::setReportTroposhere (boolIs_) [inline]
Definition at line 285 of file SbGeoProject.H'.
References ReportTroposhere.
Referenced by SBModelEditor::acquireData().
void SBConfig::setSolidTideDegree (MSolidTideDegreeD_) [inline]
Definition at line 196 of file SbGeoProject.H'.
References SolidTideDegree.
Referenced by SBModelEditor::acquireData().
void SBConfig::setSolidTideLd (MSolidTideLdS_) [inline]
Definition at line 195 of file SbGeoProject.H'.
References SolidTideLd.
Referenced by SBModelEditor::acquireData().
void SBConfig::setSysTransform (MSysTransformE_) [inline]
Definition at line 177 of file SbGeoProject.H'.
References SysTransform.
Referenced by SBModelEditor::acquireData().
void SBConfig::setTropSamplInterval (doubled_) [inline]
Definition at line 286 of file SbGeoProject.H'.
References TropSamplInterval.
Referenced by SBModelEditor::acquireData(), and SBRunManager::makeReportTroposphere().
void SBConfig::setTropStartSec (intn_) [inline]
Definition at line 287 of file SbGeoProject.H'.
References TropStartSec.
Referenced by SBModelEditor::acquireData().
void SBConfig::setUseAltEOPs (boolIs_) [inline]
Definition at line 298 of file SbGeoProject.H'.
References UseAltEOPs.
Referenced by SBModelEditor::acquireData().
void SBConfig::setUseAltSources (boolIs_) [inline]
Definition at line 297 of file SbGeoProject.H'.
References UseAltSources.
Referenced by SBModelEditor::acquireData().
void SBConfig::setUseAltStations (boolIs_) [inline]
Definition at line 296 of file SbGeoProject.H'.
References UseAltStations.
Referenced by SBModelEditor::acquireData().
MSolidTideDegree SBConfig::solidTideDegree () const [inline]
Definition at line 191 of file SbGeoProject.H'.
References SolidTideDegree.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wSolidTide().
MSolidTideLd SBConfig::solidTideLd () const [inline]
Definition at line 190 of file SbGeoProject.H'.
References SolidTideLd.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBTestSolidTides::SBTestSolidTides(), SBTideLd::SBTideLd(), and SBModelEditor::wSolidTide().
MSysTransform SBConfig::sysTransform () const [inline]
Definition at line 176 of file SbGeoProject.H'.
References SysTransform.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReportEOP(), operator<<(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), writeNormalEquationSystem(), and SBModelEditor::wSysTransform().
double SBConfig::tropSamplInterval () const [inline]
Definition at line 272 of file SbGeoProject.H'.
References TropSamplInterval.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), SBRunManager::makeReportTroposphere(), operator<<(), sinex_tro_TropDescriptionBlock(), and SBModelEditor::wSolutionReports().
int SBConfig::tropStartSec () const [inline]
Definition at line 273 of file SbGeoProject.H'.
References TropStartSec.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), operator<<(), and SBModelEditor::wSolutionReports().
bool SBConfig::useAltEOPs () const [inline]
Definition at line 292 of file SbGeoProject.H'.
References UseAltEOPs.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wSysTransform().
bool SBConfig::useAltSources () const [inline]
Definition at line 291 of file SbGeoProject.H'.
References UseAltSources.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wSysTransform().
bool SBConfig::useAltStations () const [inline]
Definition at line 290 of file SbGeoProject.H'.
References UseAltStations.
Referenced by SBModelEditor::acquireData(), SBModelEditor::makeDefault(), and SBModelEditor::wSysTransform().
Friends And Related Function Documentation
QDataStream & operator<< (QDataStream &s, const SBConfig &C) [friend]"Output to the data stream'.
Definition at line 250 of file SbGeoProject.C'.
QDataStream & operator>> (QDataStream &s, SBConfig &C) [friend]"Input from the data stream'.
Definition at line 312 of file SbGeoProject.C'.
Member Data Documentation
QString SBConfig::AltEOPs [private]
Definition at line 156 of file SbGeoProject.H'.
Referenced by altEOPs(), operator=(), SBConfig(), and setAltEOPs().
QString SBConfig::AltSources [private]
Definition at line 155 of file SbGeoProject.H'.
Referenced by altSources(), operator=(), SBConfig(), and setAltSources().
QString SBConfig::AltStations [private]
Definition at line 154 of file SbGeoProject.H'.
Referenced by altStations(), operator=(), SBConfig(), and setAltStations().
int SBConfig::DUFlagThreshold [private]
Definition at line 129 of file SbGeoProject.H'.
Referenced by dUFlagThreshold(), operator=(), SBConfig(), and setDUFlagThreshold().
MEOPDiurnal SBConfig::EOPDiurnal [private]
Take into account diurnal variations in EOP'.
Definition at line 101 of file SbGeoProject.H'.
Referenced by eopDiurnal(), operator=(), SBConfig(), and setEopDiurnal().
MEOPDiurnalAtm SBConfig::EOPDiurnalAtm [private]
Take into account diurnal variations in EOP (atmosphere)
Definition at line 102 of file SbGeoProject.H'.
Referenced by eopDiurnalAtm(), operator=(), SBConfig(), and setEopDiurnalAtm().
MEOPDiurnalNonTidal SBConfig::EOPDiurnalNonTidal [private]
Take into account diurnal variations in EOP (non-tidal)
Definition at line 103 of file SbGeoProject.H'.
Referenced by eopDiurnalNonTidal(), operator=(), SBConfig(), and setEopDiurnalNonTidal().
int SBConfig::EOPNumIntrplPoints [private]
Number of points for interpolation'.
Definition at line 104 of file SbGeoProject.H'.
Referenced by eopNumIntrplPoints(), operator=(), SBConfig(), and setEOPNumIntrplPoints().
MEphModel SBConfig::EphemModel [private]
Ephemerides model'.
Definition at line 88 of file SbGeoProject.H'.
Referenced by ephemModel(), operator=(), SBConfig(), and setEphemModel().
double SBConfig::GravHOThreshold [private]
Threshold for high order effects, rad'.
Definition at line 91 of file SbGeoProject.H'.
Referenced by gravHOThreshold(), operator=(), SBConfig(), and setGravHOThreshold().
bool SBConfig::IsAltAxsCorr [private]
Take into axis offset altitude correction;'.
Definition at line 124 of file SbGeoProject.H'.
Referenced by isAltAxsCorr(), operator=(), SBConfig(), and setIsAltAxsCorr().
bool SBConfig::IsChanged [private]
Definition at line 80 of file SbGeoProject.H'.
Referenced by isChanged(), operator=(), SBConfig(), and setIsChanged().
bool SBConfig::IsEOP_IAU2K_XY [private]
Nutations in EOP are dX and dY w/ respect to IAU2000'.
Definition at line 105 of file SbGeoProject.H'.
Referenced by isEOP_IAU2K_XY(), operator=(), SBConfig(), and setIsEOP_IAU2K_XY().
bool SBConfig::IsEOPResrerved_1 [private]
Reserved for use with EOP'.
Definition at line 106 of file SbGeoProject.H'.
Referenced by isEOPResrerved_1(), operator=(), SBConfig(), and setIsEOPResrerved_1().
bool SBConfig::IsEphBody[11] [private]
Celestial bodies taking into account'.
Definition at line 89 of file SbGeoProject.H'.
Referenced by isEphBody(), operator=(), SBConfig(), and setIsEphBody().
bool SBConfig::IsGenerateDSINEXes [private]
Definition at line 159 of file SbGeoProject.H'.
Referenced by isGenerateDSINEXes(), operator=(), SBConfig(), and setIsGenerateDSINEXes().
bool SBConfig::IsGravDelayHO [private]
High order effects'.
Definition at line 90 of file SbGeoProject.H'.
Referenced by isGravDelayHO(), operator=(), SBConfig(), and setIsGravDelayHO().
bool SBConfig::IsNutGeodNut [private]
Take into account geodesic nutation'.
Definition at line 111 of file SbGeoProject.H'.
Referenced by isNeedGeodNut(), operator=(), SBConfig(), and setIsNeedGeodNut().
bool SBConfig::IsRemovePermTide [private]
Remove permanent tide'.
Definition at line 98 of file SbGeoProject.H'.
Referenced by isRemovePermTide(), operator=(), SBConfig(), and setIsRemovePermTide().
bool SBConfig::IsRollBack2NMF [private]
Use NMFs in the case of bad/art metheo;'.
Definition at line 125 of file SbGeoProject.H'.
Referenced by isRollBack2NMF(), operator=(), SBConfig(), and setIsRollBack2NMF().
bool SBConfig::IsRollBack2Plates [private]
Use plate motion vel'. if V=0'.
Definition at line 116 of file SbGeoProject.H'.
Referenced by isRollBack2Plates(), operator=(), SBConfig(), and setIsRollBack2Plates().
bool SBConfig::IsSolidTideAnelastic [private]
Anelastic or elastic model'.
Definition at line 96 of file SbGeoProject.H'.
Referenced by isSolidTideAnelastic(), operator=(), SBConfig(), and setIsSolidTideAnelastic().
bool SBConfig::IsSolidTideLatDepend [private]
Include Solid Tide Latitude dependence'.
Definition at line 97 of file SbGeoProject.H'.
Referenced by isSolidTideLatDepend(), operator=(), SBConfig(), and setIsSolidTideLatDepend().
bool SBConfig::IsUseAploEphem [private]
Use atmoshperic loading ephemerides'.
Definition at line 117 of file SbGeoProject.H'.
Referenced by isUseAploEphem(), operator=(), SBConfig(), and setIsUseAploEphem().
bool SBConfig::IsUseBadIon [private]
Definition at line 132 of file SbGeoProject.H'.
Referenced by isUseBadIon(), operator=(), SBConfig(), and setIsUseBadIon().
bool SBConfig::IsUseDelay [private]
Definition at line 130 of file SbGeoProject.H'.
Referenced by isUseDelay(), operator=(), SBConfig(), and setIsUseDelay().
bool SBConfig::IsUseRate [private]
Definition at line 131 of file SbGeoProject.H'.
Referenced by isUseRate(), operator=(), SBConfig(), and setIsUseRate().
bool SBConfig::IsUseStationVelocity [private]
Use velocity of a station from a catalogue'.
Definition at line 115 of file SbGeoProject.H'.
Referenced by isUseStationVelocity(), operator=(), SBConfig(), and setIsUseStationVelocity().
MNutEqEquinox SBConfig::NutEquinox [private]
Model of the Equation of equinoxes'.
Definition at line 110 of file SbGeoProject.H'.
Referenced by nutEquinox(), operator=(), SBConfig(), and setNutEquinox().
MNutModel SBConfig::NutModel [private]
Nutation theory model'.
Definition at line 109 of file SbGeoProject.H'.
Referenced by nutModel(), operator=(), SBConfig(), and setNutModel().
SBParametersDesc SBConfig::P [private]
Definition at line 82 of file SbGeoProject.H'.
Referenced by operator=(), p(), setAllPars2Type(), and setP().
MPlateMotion SBConfig::PlateMotion [private]
Tectonic plate motion model'.
Definition at line 114 of file SbGeoProject.H'.
Referenced by operator=(), plateMotion(), SBConfig(), and setPlateMotion().
int SBConfig::QCodeThreshold [private]
Definition at line 128 of file SbGeoProject.H'.
Referenced by operator=(), qCodeThreshold(), SBConfig(), and setQCodeThreshold().
MRefrDryMapping SBConfig::RefrDryMapping [private]
Hydrostatic mapping function model;'.
Definition at line 122 of file SbGeoProject.H'.
Referenced by operator=(), refrDryMapping(), SBConfig(), and setRefrDryMapping().
MRefrDryZenith SBConfig::RefrDryZenith [private]
Hydrostatic zenith delay model;'.
Definition at line 120 of file SbGeoProject.H'.
Referenced by operator=(), refrDryZenith(), SBConfig(), and setRefrDryZenith().
MRefrWetMapping SBConfig::RefrWetMapping [private]
Wet mapping function model;'.
Definition at line 123 of file SbGeoProject.H'.
Referenced by operator=(), refrWetMapping(), SBConfig(), and setRefrWetMapping().
MRefrWetZenith SBConfig::RefrWetZenith [private]
Wet zenith delay model;'.
Definition at line 121 of file SbGeoProject.H'.
Referenced by operator=(), refrWetZenith(), SBConfig(), and setRefrWetZenith().
bool SBConfig::ReportCRF [private]
Definition at line 138 of file SbGeoProject.H'.
Referenced by operator=(), reportCRF(), SBConfig(), and setReportCRF().
bool SBConfig::ReportCRF_Changes [private]
Definition at line 136 of file SbGeoProject.H'.
Referenced by operator=(), reportCRF_Changes(), SBConfig(), and setReportCRF_Changes().
bool SBConfig::ReportEOP [private]
Definition at line 140 of file SbGeoProject.H'.
Referenced by operator=(), reportEOP(), SBConfig(), and setReportEOP().
bool SBConfig::ReportMaps [private]
Definition at line 135 of file SbGeoProject.H'.
Referenced by operator=(), reportMaps(), SBConfig(), and setReportMaps().
bool SBConfig::ReportNormalEqs [private]
Make report of NEQ in SINEX format;'.
Definition at line 142 of file SbGeoProject.H'.
Referenced by operator=(), reportNormalEqs(), SBConfig(), and setReportNormalEqs().
bool SBConfig::ReportNormalEqsEOPs [private]
Include EOP in NEQ report;'.
Definition at line 145 of file SbGeoProject.H'.
Referenced by operator=(), reportNormalEqsEOPs(), SBConfig(), and setReportNormalEqsEOPs().
bool SBConfig::ReportNormalEqsSRCs [private]
Include sources in NEQ report;'.
Definition at line 143 of file SbGeoProject.H'.
Referenced by operator=(), reportNormalEqsSRCs(), SBConfig(), and setReportNormalEqsSRCs().
bool SBConfig::ReportNormalEqsSTCs [private]
Include stations in NEQ report;'.
Definition at line 144 of file SbGeoProject.H'.
Referenced by operator=(), reportNormalEqsSTCs(), SBConfig(), and setReportNormalEqsSTCs().
bool SBConfig::ReportTechDesc [private]
Definition at line 141 of file SbGeoProject.H'.
Referenced by operator=(), reportTechDesc(), SBConfig(), and setReportTechDesc().
bool SBConfig::ReportTRF_Changes [private]
Definition at line 137 of file SbGeoProject.H'.
Referenced by operator=(), reportTRF_Changes(), SBConfig(), and setReportTRF_Changes().
bool SBConfig::ReportTRF_SINEX [private]
Definition at line 139 of file SbGeoProject.H'.
Referenced by operator=(), reportTRF_SINEX(), SBConfig(), and setReportTRF_SINEX().
bool SBConfig::ReportTroposhere [private]
Definition at line 146 of file SbGeoProject.H'.
Referenced by operator=(), reportTroposhere(), SBConfig(), and setReportTroposhere().
MSolidTideDegree SBConfig::SolidTideDegree [private]
Maximum degree of solid tide loading model'.
Definition at line 95 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setSolidTideDegree(), and solidTideDegree().
MSolidTideLd SBConfig::SolidTideLd [private]
Site displacement load model due to solid tide'.
Definition at line 94 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setSolidTideLd(), and solidTideLd().
MSysTransform SBConfig::SysTransform [private]
Type of CRF<->TRF system transformation'.
Definition at line 85 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setSysTransform(), and sysTransform().
double SBConfig::TropSamplInterval [private]
Definition at line 147 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setTropSamplInterval(), and tropSamplInterval().
int SBConfig::TropStartSec [private]
Definition at line 148 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setTropStartSec(), and tropStartSec().
bool SBConfig::UseAltEOPs [private]
Definition at line 153 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setUseAltEOPs(), and useAltEOPs().
bool SBConfig::UseAltSources [private]
Definition at line 152 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setUseAltSources(), and useAltSources().
bool SBConfig::UseAltStations [private]
Definition at line 151 of file SbGeoProject.H'.
Referenced by operator=(), SBConfig(), setUseAltStations(), and useAltStations().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.