SBCoordsEditor
NAME
SBCoordsEditor -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QDialog'.
Signals
void coordinatesModified (bool)
Public Member Functions
SBCoordsEditor (SBCoordsListItem *, SBStation *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBCoordsEditor ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Private Member Functions
virtual void acquireData ()
Private Attributes
SBStation * Station
SBCoordsListItem * Cooli
SBCoordinates * Coo
bool isModified
QLineEdit * leYr
QLineEdit * leMo
QLineEdit * leDy
QLineEdit * leHr
QLineEdit * leMi
QLineEdit * leSe
QLineEdit * le_R [3]
QLineEdit * leDR [3]
QLineEdit * le_V [3]
QLineEdit * leDV [3]
QCheckBox * cbIsUseVels
QLineEdit * leEventName
Detailed Description
Definition at line 614 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBCoordsEditor::SBCoordsEditor (SBCoordsListItem *Cli_, SBStation *Station_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 4044 of file SbIStuffStation.C'.
References accept(), Vector3::at(), cbIsUseVels, SBCoordinates::coo(), Coo, SBCoordinates::cooErrors(), Cooli, SBCoordsListItem::coords(), SBMJD::day(), SBCoordinates::eventName(), SBMJD::hour(), SBStation::id(), isModified, SBCoordinates::isUseVels(), le_R, le_V, leDR, leDV, leDy, leEventName, leHr, leMi, leMo, leSe, leYr, SBMJD::min(), SBMJD::month(), SBNamed::name(), reject(), SBMJD::sec(), Station, SBStationID::toString(), SBCoordinates::vel(), SBCoordinates::velErrors(), and SBMJD::year().
virtual SBCoordsEditor::~SBCoordsEditor () [inline, virtual]
Definition at line 619 of file SbIStuffStation.H'.
Member Function Documentation
void SBCoordsEditor::accept () [protected, slot]
Definition at line 4292 of file SbIStuffStation.C'.
References acquireData(), Cooli, coordinatesModified(), and isModified.
Referenced by SBCoordsEditor().
void SBCoordsEditor::acquireData () [private, virtual]
Definition at line 4309 of file SbIStuffStation.C'.
References cbIsUseVels, SBCoordinates::coo(), Coo, SBCoordinates::cooErrors(), Cooli, SBCoordinates::eventName(), isModified, SBCoordinates::isUseVels(), le_R, le_V, leDR, leDV, leDy, leEventName, leHr, leMi, leMo, leSe, leYr, SBCoordinates::setCoo(), SBCoordinates::setCooErrors(), SBCoordinates::setEventName(), SBCoordinates::setIsUseVels(), SBCoordinates::setVel(), SBCoordinates::setVelErrors(), SBCoordinates::vel(), SBCoordinates::velErrors(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by accept().
virtual QString SBCoordsEditor::ClassName () const [inline, virtual]
Definition at line 620 of file SbIStuffStation.H'.
void SBCoordsEditor::coordinatesModified (boolt0) [signal]
Definition at line 1054 of file SbIStuffStation.moc.C'.
Referenced by accept(), and reject().
void SBCoordsEditor::reject () [protected, slot]
Definition at line 4302 of file SbIStuffStation.C'.
References coordinatesModified().
Referenced by SBCoordsEditor().
Member Data Documentation
QCheckBox* SBCoordsEditor::cbIsUseVels [private]
Definition at line 649 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
SBCoordinates* SBCoordsEditor::Coo [private]
Definition at line 633 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
SBCoordsListItem* SBCoordsEditor::Cooli [private]
Definition at line 632 of file SbIStuffStation.H'.
Referenced by accept(), acquireData(), and SBCoordsEditor().
bool SBCoordsEditor::isModified [private]
Definition at line 634 of file SbIStuffStation.H'.
Referenced by accept(), acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::le_R[3] [private]
Definition at line 644 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::le_V[3] [private]
Definition at line 646 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leDR[3] [private]
Definition at line 645 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leDV[3] [private]
Definition at line 647 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leDy [private]
Definition at line 639 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leEventName [private]
Definition at line 650 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leHr [private]
Definition at line 640 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leMi [private]
Definition at line 641 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leMo [private]
Definition at line 638 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leSe [private]
Definition at line 642 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
QLineEdit* SBCoordsEditor::leYr [private]
Definition at line 637 of file SbIStuffStation.H'.
Referenced by acquireData(), and SBCoordsEditor().
SBStation* SBCoordsEditor::Station [private]
Definition at line 631 of file SbIStuffStation.H'.
Referenced by SBCoordsEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.