SBCoordsListItem
NAME
SBCoordsListItem -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QListViewItem'.
Public Member Functions
SBCoordsListItem (QListView *parent_, SBCoordinates *Coords_)
virtual QString ClassName () const
SBCoordinates * coords ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBCoordinates * Coords
Detailed Description
Definition at line 133 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBCoordsListItem::SBCoordsListItem (QListView *parent_, SBCoordinates *Coords_) [inline]
Definition at line 138 of file SbIStuffStation.H'.
References Coords.
Member Function Documentation
virtual QString SBCoordsListItem::ClassName () const [inline, virtual]
Definition at line 139 of file SbIStuffStation.H'.
SBCoordinates* SBCoordsListItem::coords () [inline]
Definition at line 141 of file SbIStuffStation.H'.
References Coords.
Referenced by SBStationEditor::delCoordinates(), and SBCoordsEditor::SBCoordsEditor().
QString SBCoordsListItem::key (intcol, bool) const [virtual]
Definition at line 412 of file SbIStuffStation.C'.
References Vector3::at(), SBCoordinates::coo(), SBCoordinates::cooErrors(), Coords, SBCoordinates::eventName(), SBMJD::F_INTERNAL, SBCoordinates::isUseVels(), TmpString, SBMJD::toString(), SBCoordinates::vel(), SBCoordinates::velErrors(), X_AXIS, Y_AXIS, and Z_AXIS.
QString SBCoordsListItem::text (intcol) const [virtual]
Definition at line 371 of file SbIStuffStation.C'.
References Vector3::at(), SBCoordinates::coo(), SBCoordinates::cooErrors(), Coords, SBCoordinates::eventName(), SBMJD::F_DateShort, SBCoordinates::isUseVels(), TmpString, SBMJD::toString(), SBCoordinates::vel(), SBCoordinates::velErrors(), X_AXIS, Y_AXIS, and Z_AXIS.
Member Data Documentation
SBCoordinates* SBCoordsListItem::Coords [private]
Definition at line 136 of file SbIStuffStation.H'.
Referenced by coords(), key(), SBCoordsListItem(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.