SBDataSeriesEntry
NAME
SBDataSeriesEntry -
SYNOPSIS
#include <SbMathDataSeries.H>
Public Member Functions
SBDataSeriesEntry ()
SBDataSeriesEntry (const SBDataSeriesEntry &Entry)
virtual ~SBDataSeriesEntry ()
virtual QString ClassName () const
bool isReadOK () const
double t () const
SBVector * data ()
int n () const
Private Attributes
double T
SBVector * Data
bool IsReadOK
Friends
QTextStream & operator<< (QTextStream &, const SBDataSeriesEntry &)
QTextStream & operator>> (QTextStream &, SBDataSeriesEntry &)
Detailed Description
Definition at line 43 of file SbMathDataSeries.H'.
Constructor & Destructor Documentation
SBDataSeriesEntry::SBDataSeriesEntry () [inline]
Definition at line 51 of file SbMathDataSeries.H'.
References Data, IsReadOK, and T.
SBDataSeriesEntry::SBDataSeriesEntry (const SBDataSeriesEntry &Entry) [inline]
Definition at line 52 of file SbMathDataSeries.H'.
References Data, IsReadOK, and T.
virtual SBDataSeriesEntry::~SBDataSeriesEntry () [inline, virtual]
Definition at line 58 of file SbMathDataSeries.H'.
References Data.
Member Function Documentation
virtual QString SBDataSeriesEntry::ClassName () const [inline, virtual]
Definition at line 59 of file SbMathDataSeries.H'.
SBVector* SBDataSeriesEntry::data () [inline]
Definition at line 63 of file SbMathDataSeries.H'.
References Data.
Referenced by SBFilterGauss::calcSigma(), SBFilterModel::eliminateBefore(), SBMEM::readDataFile(), and SBFilterGauss::substractFilter().
bool SBDataSeriesEntry::isReadOK () const [inline]
Definition at line 61 of file SbMathDataSeries.H'.
References IsReadOK.
int SBDataSeriesEntry::n () const [inline]
Definition at line 64 of file SbMathDataSeries.H'.
References Data, and SBVector::n().
double SBDataSeriesEntry::t () const [inline]
Definition at line 62 of file SbMathDataSeries.H'.
References T.
Referenced by SBFilterGauss::calcSigma(), SBMEM::readDataFile(), and SBFilterGauss::substractFilter().
Friends And Related Function Documentation
QTextStream& operator<< (QTextStream &s, const SBDataSeriesEntry &entry) [friend]
Definition at line 35 of file SbMathDataSeries.C'.
QTextStream& operator>> (QTextStream &s, SBDataSeriesEntry &entry) [friend]
Definition at line 48 of file SbMathDataSeries.C'.
Member Data Documentation
SBVector* SBDataSeriesEntry::Data [private]
Definition at line 47 of file SbMathDataSeries.H'.
Referenced by data(), n(), operator<<(), operator>>(), SBDataSeriesEntry(), and ~SBDataSeriesEntry().
bool SBDataSeriesEntry::IsReadOK [private]
Definition at line 48 of file SbMathDataSeries.H'.
Referenced by isReadOK(), operator>>(), and SBDataSeriesEntry().
double SBDataSeriesEntry::T [private]
Definition at line 46 of file SbMathDataSeries.H'.
Referenced by operator<<(), operator>>(), SBDataSeriesEntry(), and t().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.