SBDated
NAME
SBDated -
SYNOPSIS
#include <SbGeo.H>
Inherited by SBHistory::SBHistoryEntry'.
Public Member Functions
SBDated (double d_=0.0)
SBDated (const SBDated &d)
virtual ~SBDated ()
virtual QString ClassName () const
virtual double date () const
virtual void setDate (double d_)
virtual QString date2str ()
Protected Attributes
double Date
Friends
int compare_dated (SBDated *d1, SBDated *d2)
QDataStream & operator<< (QDataStream &s, const SBDated &D)
QDataStream & operator>> (QDataStream &s, SBDated &D)
Detailed Description
Definition at line 155 of file SbGeo.H'.
Constructor & Destructor Documentation
SBDated::SBDated (doubled_ = 0.0) [inline]
Definition at line 161 of file SbGeo.H'.
References Date.
SBDated::SBDated (const SBDated &d) [inline]
Definition at line 162 of file SbGeo.H'.
References Date.
virtual SBDated::~SBDated () [inline, virtual]
Definition at line 163 of file SbGeo.H'.
Member Function Documentation
virtual QString SBDated::ClassName () const [inline, virtual]
Definition at line 164 of file SbGeo.H'.
virtual double SBDated::date () const [inline, virtual]
Definition at line 166 of file SbGeo.H'.
References Date.
Referenced by SBBrowseHistory::deleteHistoryLine(), SBHistoryLI::key(), and SBHistoryLI::text().
QString SBDated::date2str () [virtual]
Definition at line 35 of file SbGeo.C'.
References Date.
virtual void SBDated::setDate (doubled_) [inline, virtual]
Definition at line 167 of file SbGeo.H'.
References Date.
Friends And Related Function Documentation
int compare_dated (SBDated *d1, SBDated *d2) [friend]
Definition at line 170 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBDated &D) [friend]
Definition at line 173 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBDated &D) [friend]
Definition at line 174 of file SbGeo.H'.
Member Data Documentation
double SBDated::Date [protected]
Definition at line 158 of file SbGeo.H'.
Referenced by date(), date2str(), SBDated(), and setDate().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.