SBDataSeries
NAME
SBDataSeries -
SYNOPSIS
#include <SbMathDataSeries.H>
Inherits QList< SBDataSeriesEntry >'.
Public Member Functions
SBDataSeries ()
virtual ~SBDataSeries ()
virtual QString ClassName () const
int numOfDataColumns () const
double dT () const
double dTMin () const
double dTMax () const
bool isEquiDistant () const
bool isChecked () const
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
void checkRecords ()
Private Attributes
int NumOfDataColumns
the number of columns in the data part (not counting the arg)
double DT
[mean] time spacing interval
double DTMin
min time spacing interval
double DTMax
max time spacing interval
bool IsEquiDistant
true if DT is const
bool IsChecked
Friends
QTextStream & operator<< (QTextStream &, const SBDataSeries &)
QTextStream & operator>> (QTextStream &, SBDataSeries &)
Detailed Description
Definition at line 74 of file SbMathDataSeries.H'.
Constructor & Destructor Documentation
SBDataSeries::SBDataSeries ()
Definition at line 134 of file SbMathDataSeries.C'.
References DT, IsChecked, IsEquiDistant, and NumOfDataColumns.
SBDataSeries::~SBDataSeries () [virtual]
Definition at line 143 of file SbMathDataSeries.C'.
Member Function Documentation
void SBDataSeries::checkRecords () [protected]
Definition at line 148 of file SbMathDataSeries.C'.
References ClassName(), SBLog::DATA, SBLog::DBG, DT, DTMax, DTMin, SBLog::ERR, IsChecked, IsEquiDistant, Log, NumOfDataColumns, and SBLog::write().
Referenced by operator>>().
virtual QString SBDataSeries::ClassName () const [inline, virtual]
Definition at line 96 of file SbMathDataSeries.H'.
Referenced by checkRecords().
virtual int SBDataSeries::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 77 of file SbMathDataSeries.H'.
double SBDataSeries::dT () const [inline]
Definition at line 101 of file SbMathDataSeries.H'.
References DT.
Referenced by SBFilterGauss::interpolate(), SBFilterGauss::interpolateMinusModel(), SBFilteringGauss::readDataFile(), SBFilteringGauss::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), and SBFilteringGauss::redrawTFPlot().
double SBDataSeries::dTMax () const [inline]
Definition at line 103 of file SbMathDataSeries.H'.
References DTMax.
Referenced by SBFilteringGauss::readDataFile().
double SBDataSeries::dTMin () const [inline]
Definition at line 102 of file SbMathDataSeries.H'.
References DTMin.
Referenced by SBFilteringGauss::readDataFile().
bool SBDataSeries::isChecked () const [inline]
Definition at line 105 of file SbMathDataSeries.H'.
References IsChecked.
bool SBDataSeries::isEquiDistant () const [inline]
Definition at line 104 of file SbMathDataSeries.H'.
References IsEquiDistant.
int SBDataSeries::numOfDataColumns () const [inline]
Definition at line 100 of file SbMathDataSeries.H'.
References NumOfDataColumns.
Referenced by SBFilteringGauss::readDataFile().
Friends And Related Function Documentation
QTextStream& operator<< (QTextStream &s, const SBDataSeries &series) [friend]
Definition at line 231 of file SbMathDataSeries.C'.
QTextStream& operator>> (QTextStream &s, SBDataSeries &series) [friend]
Definition at line 242 of file SbMathDataSeries.C'.
Member Data Documentation
double SBDataSeries::DT [private]
[mean] time spacing interval
Definition at line 85 of file SbMathDataSeries.H'.
Referenced by checkRecords(), dT(), and SBDataSeries().
double SBDataSeries::DTMax [private]
max time spacing interval
Definition at line 87 of file SbMathDataSeries.H'.
Referenced by checkRecords(), and dTMax().
double SBDataSeries::DTMin [private]
min time spacing interval
Definition at line 86 of file SbMathDataSeries.H'.
Referenced by checkRecords(), and dTMin().
bool SBDataSeries::IsChecked [private]
Definition at line 89 of file SbMathDataSeries.H'.
Referenced by checkRecords(), isChecked(), and SBDataSeries().
bool SBDataSeries::IsEquiDistant [private]
true if DT is const
Definition at line 88 of file SbMathDataSeries.H'.
Referenced by checkRecords(), isEquiDistant(), and SBDataSeries().
int SBDataSeries::NumOfDataColumns [private]
the number of columns in the data part (not counting the arg)
Definition at line 84 of file SbMathDataSeries.H'.
Referenced by checkRecords(), numOfDataColumns(), and SBDataSeries().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.