.TH "SBDated" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBDated \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeo\&.H>\fP
.PP
Inherited by \fBSBHistory::SBHistoryEntry\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBDated\fP (double d_=0\&.0)"
.br
.ti -1c
.RI "\fBSBDated\fP (const \fBSBDated\fP &d)"
.br
.ti -1c
.RI "virtual \fB~SBDated\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual double \fBdate\fP () const "
.br
.ti -1c
.RI "virtual void \fBsetDate\fP (double d_)"
.br
.ti -1c
.RI "virtual QString \fBdate2str\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBDate\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "int \fBcompare_dated\fP (\fBSBDated\fP *d1, \fBSBDated\fP *d2)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBDated\fP &D)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBDated\fP &D)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 155 of file SbGeo\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBDated::SBDated (doubled_ = \fC0\&.0\fP)\fC [inline]\fP"
.PP
Definition at line 161 of file SbGeo\&.H'\&.
.PP
References Date\&.
.SS "SBDated::SBDated (const \fBSBDated\fP &d)\fC [inline]\fP"
.PP
Definition at line 162 of file SbGeo\&.H'\&.
.PP
References Date\&.
.SS "virtual SBDated::~SBDated ()\fC [inline, virtual]\fP"
.PP
Definition at line 163 of file SbGeo\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBDated::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 164 of file SbGeo\&.H'\&.
.SS "virtual double SBDated::date () const\fC [inline, virtual]\fP"
.PP
Definition at line 166 of file SbGeo\&.H'\&.
.PP
References Date\&.
.PP
Referenced by SBBrowseHistory::deleteHistoryLine(), SBHistoryLI::key(), and SBHistoryLI::text()\&.
.SS "QString SBDated::date2str ()\fC [virtual]\fP"
.PP
Definition at line 35 of file SbGeo\&.C'\&.
.PP
References Date\&.
.SS "virtual void SBDated::setDate (doubled_)\fC [inline, virtual]\fP"
.PP
Definition at line 167 of file SbGeo\&.H'\&.
.PP
References Date\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "int compare_dated (\fBSBDated\fP *d1, \fBSBDated\fP *d2)\fC [friend]\fP"
.PP
Definition at line 170 of file SbGeo\&.H'\&.
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBDated\fP &D)\fC [friend]\fP"
.PP
Definition at line 173 of file SbGeo\&.H'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBDated\fP &D)\fC [friend]\fP"
.PP
Definition at line 174 of file SbGeo\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBDated::Date\fP\fC [protected]\fP"
.PP
Definition at line 158 of file SbGeo\&.H'\&.
.PP
Referenced by date(), date2str(), SBDated(), and setDate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
