.TH "SBDBHLRecDE" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBDBHLRecDE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoObsVLBI_IO\&.H>\fP
.PP
Inherits \fBSBDBHLRecPrefixed\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBDBHLRecDE\fP ()"
.br
.ti -1c
.RI "int \fBp1\fP ()"
.br
.ti -1c
.RI "int \fBp2\fP ()"
.br
.ti -1c
.RI "int \fBp3\fP ()"
.br
.ti -1c
.RI "int \fBp4\fP ()"
.br
.ti -1c
.RI "int \fBp5\fP ()"
.br
.ti -1c
.RI "int \fBp6\fP ()"
.br
.ti -1c
.RI "int \fBp7\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisAlter\fP ()"
.br
.ti -1c
.RI "bool \fBisZ3\fP ()"
.br
.ti -1c
.RI "virtual int \fBparseLR\fP (\fBSBDS_dbh\fP &)"
.br
.ti -1c
.RI "void \fBdump\fP (\fBQTextStream\fP &s)"
.br
.ti -1c
.RI "bool \fBisP\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisPrefixParsed\fP (\fBSBDS_dbh\fP &)"
.br
.ti -1c
.RI "bool \fBisOk\fP ()"
.br
.ti -1c
.RI "int \fBlength\fP ()"
.br
.ti -1c
.RI "virtual \fBSBDBHPar::PType\fP \fBtype\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "short \fBP1\fP"
.br
.ti -1c
.RI "short \fBP2\fP"
.br
.ti -1c
.RI "short \fBP3\fP"
.br
.ti -1c
.RI "short \fBP4\fP"
.br
.ti -1c
.RI "short \fBP5\fP"
.br
.ti -1c
.RI "short \fBP6\fP"
.br
.ti -1c
.RI "short \fBP7\fP"
.br
.ti -1c
.RI "bool \fBIsZ3\fP"
.br
.ti -1c
.RI "char \fBPrefix\fP [2]"
.br
.ti -1c
.RI "char \fBP\fP [3]"
.br
.ti -1c
.RI "int \fBLength\fP"
.br
.ti -1c
.RI "char * \fBLogRec\fP"
.br
.ti -1c
.RI "bool \fBisOK\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &, \fBSBDBHPhysRec\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 273 of file SbGeoObsVLBI_IO\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBDBHLRecDE::SBDBHLRecDE ()\fC [inline]\fP"
.PP
Definition at line 279 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References IsZ3, P1, P2, P3, P4, P5, P6, and P7\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBDBHLRecDE::dump (\fBQTextStream\fP &s)\fC [inline]\fP"
.PP
Definition at line 290 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P1, P2, P3, P4, P5, P6, and P7\&.
.SS "virtual bool SBDBHLRecDE::isAlter ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBDBHLRecPrefixed\fP'\&.
.PP
Definition at line 287 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHLRecPrefixed::Prefix\&.
.SS "bool SBDBHPhysRec::isOk ()\fC [inline, inherited]\fP"
.PP
Definition at line 117 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPhysRec::isOK\&.
.PP
Referenced by operator>>()\&.
.SS "bool SBDBHLRecPrefixed::isP ()\fC [inline, inherited]\fP"
.PP
Definition at line 140 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHLRecPrefixed::P, and SBDBHLRecPrefixed::Prefix\&.
.PP
Referenced by SBDBHHistTriplet::isHistLine(), SBDBHLRecPrefixed::isPrefixParsed(), and operator>>()\&.
.SS "bool SBDBHLRecPrefixed::isPrefixParsed (\fBSBDS_dbh\fP &s)\fC [virtual, inherited]\fP"
.PP
Definition at line 2389 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBLog::DATA, SBLog::ERR, SBDBHLRecPrefixed::isAlter(), SBDBHPhysRec::isOK, SBDBHLRecPrefixed::isP(), Log, SBDBHLRecPrefixed::P, SBDBHLRecPrefixed::Prefix, and SBLog::write()\&.
.PP
Referenced by SBDBHLRecPrefixed::parseLR(), SBDBHLRecHS1::parseLR(), SBDBHLRecTE::parseLR(), SBDBHLRecTC::parseLR(), SBDBHLRecDR::parseLR(), parseLR(), and SBDBHLRecZ3::parseLR()\&.
.SS "bool SBDBHLRecDE::isZ3 ()\fC [inline]\fP"
.PP
Definition at line 288 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References IsZ3\&.
.PP
Referenced by SBDBHFormat::getBlock()\&.
.SS "int SBDBHPhysRec::length ()\fC [inline, inherited]\fP"
.PP
Definition at line 118 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPhysRec::Length\&.
.PP
Referenced by operator>>()\&.
.SS "int SBDBHLRecDE::p1 ()\fC [inline]\fP"
.PP
Definition at line 280 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P1\&.
.SS "int SBDBHLRecDE::p2 ()\fC [inline]\fP"
.PP
Definition at line 281 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P2\&.
.SS "int SBDBHLRecDE::p3 ()\fC [inline]\fP"
.PP
Definition at line 282 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P3\&.
.SS "int SBDBHLRecDE::p4 ()\fC [inline]\fP"
.PP
Definition at line 283 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P4\&.
.SS "int SBDBHLRecDE::p5 ()\fC [inline]\fP"
.PP
Definition at line 284 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P5\&.
.SS "int SBDBHLRecDE::p6 ()\fC [inline]\fP"
.PP
Definition at line 285 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P6\&.
.SS "int SBDBHLRecDE::p7 ()\fC [inline]\fP"
.PP
Definition at line 286 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P7\&.
.SS "int SBDBHLRecDE::parseLR (\fBSBDS_dbh\fP &s)\fC [virtual]\fP"
.PP
Reimplemented from \fBSBDBHLRecPrefixed\fP'\&.
.PP
Definition at line 2435 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBDBHPhysRec::isOK, SBDBHLRecPrefixed::isPrefixParsed(), IsZ3, P1, P2, P3, P4, P5, P6, P7, and SBDBHLRecPrefixed::Prefix\&.
.SS "virtual \fBSBDBHPar::PType\fP SBDBHPhysRec::type ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSBDBHDRecString\fP'\&.
.PP
Definition at line 119 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPar::T_UNKN\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHPhysRec\fP &PH)\fC [friend, inherited]\fP"
.PP
Definition at line 2325 of file SbGeoObsVLBI_IO\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSBDBHPhysRec::isOK\fP\fC [protected, inherited]\fP"
.PP
Definition at line 112 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec::SBDBHPhysRec()\&.
.SS "bool \fBSBDBHLRecDE::IsZ3\fP\fC [protected]\fP"
.PP
Definition at line 277 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by isZ3(), parseLR(), and SBDBHLRecDE()\&.
.SS "int \fBSBDBHPhysRec::Length\fP\fC [protected, inherited]\fP"
.PP
Definition at line 110 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec()\&.
.SS "char* \fBSBDBHPhysRec::LogRec\fP\fC [protected, inherited]\fP"
.PP
Definition at line 111 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec::SBDBHPhysRec(), SBDBHDRecString::val(), and SBDBHPhysRec::~SBDBHPhysRec()\&.
.SS "char \fBSBDBHLRecPrefixed::P\fP[3]\fC [protected, inherited]\fP"
.PP
Definition at line 137 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed()\&.
.SS "short \fBSBDBHLRecDE::P1\fP\fC [protected]\fP"
.PP
Definition at line 276 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p1(), parseLR(), and SBDBHLRecDE()\&.
.SS "short \fBSBDBHLRecDE::P2\fP\fC [protected]\fP"
.PP
Definition at line 276 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p2(), parseLR(), and SBDBHLRecDE()\&.
.SS "short \fBSBDBHLRecDE::P3\fP\fC [protected]\fP"
.PP
Definition at line 276 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p3(), parseLR(), and SBDBHLRecDE()\&.
.SS "short \fBSBDBHLRecDE::P4\fP\fC [protected]\fP"
.PP
Definition at line 276 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p4(), parseLR(), and SBDBHLRecDE()\&.
.SS "short \fBSBDBHLRecDE::P5\fP\fC [protected]\fP"
.PP
Definition at line 276 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p5(), parseLR(), and SBDBHLRecDE()\&.
.SS "short \fBSBDBHLRecDE::P6\fP\fC [protected]\fP"
.PP
Definition at line 276 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p6(), parseLR(), and SBDBHLRecDE()\&.
.SS "short \fBSBDBHLRecDE::P7\fP\fC [protected]\fP"
.PP
Definition at line 276 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p7(), parseLR(), and SBDBHLRecDE()\&.
.SS "char \fBSBDBHLRecPrefixed::Prefix\fP[2]\fC [protected, inherited]\fP"
.PP
Definition at line 136 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHLRecDR::dump(), SBDBHLRecTC::isAlter(), isAlter(), SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), SBDBHLRecHS1::isZ1(), SBDBHLRecTC::parseLR(), parseLR(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
