.TH "SBDBHTEBlock::SBDBHLRecP3" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBDBHTEBlock::SBDBHLRecP3 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoObsVLBI_IO\&.H>\fP
.PP
Inherits \fBSBDBHPhysRec\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBDBHLRecP3\fP (\fBSBDBHTEBlock\fP *Owner_)"
.br
.ti -1c
.RI "virtual int \fBparseLR\fP (\fBSBDS_dbh\fP &s)"
.br
.ti -1c
.RI "bool \fBisOk\fP ()"
.br
.ti -1c
.RI "int \fBlength\fP ()"
.br
.ti -1c
.RI "virtual \fBSBDBHPar::PType\fP \fBtype\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSBDBHTEBlock\fP * \fBOwner\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBLength\fP"
.br
.ti -1c
.RI "char * \fBLogRec\fP"
.br
.ti -1c
.RI "bool \fBisOK\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &, \fBSBDBHPhysRec\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 419 of file SbGeoObsVLBI_IO\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBDBHTEBlock::SBDBHLRecP3::SBDBHLRecP3 (\fBSBDBHTEBlock\fP *Owner_)\fC [inline]\fP"
.PP
Definition at line 423 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References Owner\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SBDBHPhysRec::isOk ()\fC [inline, inherited]\fP"
.PP
Definition at line 117 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPhysRec::isOK\&.
.PP
Referenced by operator>>()\&.
.SS "int SBDBHPhysRec::length ()\fC [inline, inherited]\fP"
.PP
Definition at line 118 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPhysRec::Length\&.
.PP
Referenced by operator>>()\&.
.SS "virtual int SBDBHTEBlock::SBDBHLRecP3::parseLR (\fBSBDS_dbh\fP &s)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBDBHPhysRec\fP'\&.
.PP
Definition at line 424 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References Owner, and SBDBHTEBlock::parseP3Rec()\&.
.SS "virtual \fBSBDBHPar::PType\fP SBDBHPhysRec::type ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSBDBHDRecString\fP'\&.
.PP
Definition at line 119 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPar::T_UNKN\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHPhysRec\fP &PH)\fC [friend, inherited]\fP"
.PP
Definition at line 2325 of file SbGeoObsVLBI_IO\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSBDBHPhysRec::isOK\fP\fC [protected, inherited]\fP"
.PP
Definition at line 112 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec::SBDBHPhysRec()\&.
.SS "int \fBSBDBHPhysRec::Length\fP\fC [protected, inherited]\fP"
.PP
Definition at line 110 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec()\&.
.SS "char* \fBSBDBHPhysRec::LogRec\fP\fC [protected, inherited]\fP"
.PP
Definition at line 111 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec::SBDBHPhysRec(), SBDBHDRecString::val(), and SBDBHPhysRec::~SBDBHPhysRec()\&.
.SS "\fBSBDBHTEBlock\fP* \fBSBDBHTEBlock::SBDBHLRecP3::Owner\fP"
.PP
Definition at line 422 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by parseLR(), and SBDBHLRecP3()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
