SBDBHLRecTC
NAME
SBDBHLRecTC -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Inherits SBDBHLRecPrefixed'.
Public Member Functions
SBDBHLRecTC ()
bool isZ2 ()
short numTEBlocks ()
short tocType ()
virtual bool isAlter ()
void dump (QTextStream &s)
virtual int parseLR (SBDS_dbh &)
bool isP ()
virtual bool isPrefixParsed (SBDS_dbh &)
bool isOk ()
int length ()
virtual SBDBHPar::PType type ()
Protected Attributes
short TOCType
short NumTEBlocks
bool IsZ2
char Prefix [2]
char P [3]
int Length
char * LogRec
bool isOK
Friends
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHPhysRec &)
Detailed Description
Definition at line 221 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHLRecTC::SBDBHLRecTC () [inline]
Definition at line 227 of file SbGeoObsVLBI_IO.H'.
References IsZ2, NumTEBlocks, and TOCType.
Member Function Documentation
void SBDBHLRecTC::dump (QTextStream &s) [inline]
Definition at line 233 of file SbGeoObsVLBI_IO.H'.
References NumTEBlocks, and TOCType.
Referenced by SBDBHTCBlock::dump().
virtual bool SBDBHLRecTC::isAlter () [inline, virtual]
Reimplemented from SBDBHLRecPrefixed'.
Definition at line 232 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecPrefixed::Prefix.
bool SBDBHPhysRec::isOk () [inline, inherited]
Definition at line 117 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::isOK.
Referenced by operator>>().
bool SBDBHLRecPrefixed::isP () [inline, inherited]
Definition at line 140 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecPrefixed::P, and SBDBHLRecPrefixed::Prefix.
Referenced by SBDBHHistTriplet::isHistLine(), SBDBHLRecPrefixed::isPrefixParsed(), and operator>>().
bool SBDBHLRecPrefixed::isPrefixParsed (SBDS_dbh &s) [virtual, inherited]
Definition at line 2389 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, SBLog::ERR, SBDBHLRecPrefixed::isAlter(), SBDBHPhysRec::isOK, SBDBHLRecPrefixed::isP(), Log, SBDBHLRecPrefixed::P, SBDBHLRecPrefixed::Prefix, and SBLog::write().
Referenced by SBDBHLRecPrefixed::parseLR(), SBDBHLRecHS1::parseLR(), SBDBHLRecTE::parseLR(), parseLR(), SBDBHLRecDR::parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecZ3::parseLR().
bool SBDBHLRecTC::isZ2 () [inline]
Definition at line 229 of file SbGeoObsVLBI_IO.H'.
References IsZ2.
Referenced by SBDBHTCBlock::isLast().
int SBDBHPhysRec::length () [inline, inherited]
Definition at line 118 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::Length.
Referenced by operator>>().
short SBDBHLRecTC::numTEBlocks () [inline]
Definition at line 230 of file SbGeoObsVLBI_IO.H'.
References NumTEBlocks.
Referenced by SBDBHTCBlock::numTEBlocks(), and operator>>().
int SBDBHLRecTC::parseLR (SBDS_dbh &s) [virtual]
Reimplemented from SBDBHLRecPrefixed'.
Definition at line 2411 of file SbGeoObsVLBI_IO.C'.
References SBDBHPhysRec::isOK, SBDBHLRecPrefixed::isPrefixParsed(), IsZ2, NumTEBlocks, SBDBHLRecPrefixed::Prefix, and TOCType.
short SBDBHLRecTC::tocType () [inline]
Definition at line 231 of file SbGeoObsVLBI_IO.H'.
References TOCType.
Referenced by SBDBHTCBlock::tocType().
virtual SBDBHPar::PType SBDBHPhysRec::type () [inline, virtual, inherited]
Reimplemented in SBDBHDRecString'.
Definition at line 119 of file SbGeoObsVLBI_IO.H'.
References SBDBHPar::T_UNKN.
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHPhysRec &PH) [friend, inherited]
Definition at line 2325 of file SbGeoObsVLBI_IO.C'.
Member Data Documentation
bool SBDBHPhysRec::isOK [protected, inherited]
Definition at line 112 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), parseLR(), SBDBHLRecDE::parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
bool SBDBHLRecTC::IsZ2 [protected]
Definition at line 225 of file SbGeoObsVLBI_IO.H'.
Referenced by isZ2(), parseLR(), and SBDBHLRecTC().
int SBDBHPhysRec::Length [protected, inherited]
Definition at line 110 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
char* SBDBHPhysRec::LogRec [protected, inherited]
Definition at line 111 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec::SBDBHPhysRec(), SBDBHDRecString::val(), and SBDBHPhysRec::~SBDBHPhysRec().
short SBDBHLRecTC::NumTEBlocks [protected]
Definition at line 224 of file SbGeoObsVLBI_IO.H'.
Referenced by dump(), numTEBlocks(), parseLR(), and SBDBHLRecTC().
char SBDBHLRecPrefixed::P[3] [protected, inherited]
Definition at line 137 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed().
char SBDBHLRecPrefixed::Prefix[2] [protected, inherited]
Definition at line 136 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecDR::dump(), isAlter(), SBDBHLRecDE::isAlter(), SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), SBDBHLRecHS1::isZ1(), parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed().
short SBDBHLRecTC::TOCType [protected]
Definition at line 224 of file SbGeoObsVLBI_IO.H'.
Referenced by dump(), parseLR(), SBDBHLRecTC(), and tocType().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.