SBDBHFormat
NAME
SBDBHFormat -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Public Member Functions
SBDBHFormat ()
QList< SBDBHTCBlock > * tcBlocks ()
bool isOk ()
short tcNum ()
void postRead ()
void setDump (QTextStream *Dump_)
void dump (QTextStream &s)
void getBlock (SBDS_dbh &)
SBDBHTCBlock * currentTC ()
SBDBHPhysRec * parRecord (SBDBHPar *Par)
SBDBHPar * lookupPar (const char *)
short i2 (SBDBHPar *Par, int i, int j, int k)
double r8 (SBDBHPar *Par, int i, int j, int k)
double d8 (SBDBHPar *Par, int i, int j, int k)
int j4 (SBDBHPar *Par, int i, int j, int k)
QString str (SBDBHPar *Par, int i, int j)
Protected Attributes
QList< SBDBHTCBlock > ListTCBlock
QTextStream * Dump
bool isOK
short TCcurrent
Friends
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHFormat &)
Detailed Description
Definition at line 532 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHFormat::SBDBHFormat () [inline]
Definition at line 541 of file SbGeoObsVLBI_IO.H'.
References Dump, isOK, ListTCBlock, and TCcurrent.
Member Function Documentation
SBDBHTCBlock* SBDBHFormat::currentTC () [inline]
Definition at line 555 of file SbGeoObsVLBI_IO.H'.
References ListTCBlock, and TCcurrent.
Referenced by lookupPar(), and parRecord().
double SBDBHFormat::d8 (SBDBHPar *Par, inti, intj, intk) [inline]
Definition at line 567 of file SbGeoObsVLBI_IO.H'.
References parRecord().
void SBDBHFormat::dump (QTextStream &s) [inline]
Definition at line 547 of file SbGeoObsVLBI_IO.H'.
References ListTCBlock.
void SBDBHFormat::getBlock (SBDS_dbh &s)
Definition at line 2706 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, Dump, SBLog::ERR, isOK, SBDBHLRecDE::isZ3(), ListTCBlock, Log, SBDBHTEBlock::recs(), SBDBHPar::T_A2, SBDBHPar::T_D8, SBDBHPar::T_I2, SBDBHPar::T_J4, SBDBHPar::T_R8, TCcurrent, SBDBHTCBlock::teBlocks(), and SBLog::write().
short SBDBHFormat::i2 (SBDBHPar *Par, inti, intj, intk) [inline]
Definition at line 563 of file SbGeoObsVLBI_IO.H'.
References parRecord().
bool SBDBHFormat::isOk () [inline]
Definition at line 543 of file SbGeoObsVLBI_IO.H'.
References isOK.
int SBDBHFormat::j4 (SBDBHPar *Par, inti, intj, intk) [inline]
Definition at line 569 of file SbGeoObsVLBI_IO.H'.
References parRecord().
SBDBHPar * SBDBHFormat::lookupPar (const char *Tag)
Definition at line 2802 of file SbGeoObsVLBI_IO.C'.
References currentTC(), SBDBHPar::nTC(), SBDBHPar::nTE(), SBDBHTCBlock::parByAbbrev(), TCcurrent, SBDBHTCBlock::teBlocks(), and SBDBHPar::type().
SBDBHPhysRec* SBDBHFormat::parRecord (SBDBHPar *Par) [inline]
Definition at line 556 of file SbGeoObsVLBI_IO.H'.
References currentTC(), SBDBHPar::nTE(), SBDBHTEBlock::recByType(), SBDBHTCBlock::teBlocks(), and SBDBHPar::type().
Referenced by d8(), i2(), j4(), r8(), and str().
void SBDBHFormat::postRead ()
Definition at line 2622 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, SBLog::DBG, SBLog::ERR, SBLog::INF, ListTCBlock, Log, SBDBHPar::T_A2, SBDBHPar::T_D8, SBDBHPar::T_I2, SBDBHPar::T_J4, SBDBHPar::T_R8, SBDBHPar::T_UNKN, and SBLog::write().
Referenced by operator>>().
double SBDBHFormat::r8 (SBDBHPar *Par, inti, intj, intk) [inline]
Definition at line 565 of file SbGeoObsVLBI_IO.H'.
References parRecord().
void SBDBHFormat::setDump (QTextStream *Dump_) [inline]
Definition at line 546 of file SbGeoObsVLBI_IO.H'.
References Dump.
QString SBDBHFormat::str (SBDBHPar *Par, inti, intj) [inline]
Definition at line 571 of file SbGeoObsVLBI_IO.H'.
References parRecord().
QList<SBDBHTCBlock>* SBDBHFormat::tcBlocks () [inline]
Definition at line 542 of file SbGeoObsVLBI_IO.H'.
References ListTCBlock.
short SBDBHFormat::tcNum () [inline]
Definition at line 544 of file SbGeoObsVLBI_IO.H'.
References TCcurrent.
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHFormat &F) [friend]
Definition at line 2818 of file SbGeoObsVLBI_IO.C'.
Member Data Documentation
QTextStream* SBDBHFormat::Dump [protected]
Definition at line 537 of file SbGeoObsVLBI_IO.H'.
Referenced by getBlock(), SBDBHFormat(), and setDump().
bool SBDBHFormat::isOK [protected]
Definition at line 538 of file SbGeoObsVLBI_IO.H'.
Referenced by getBlock(), isOk(), operator>>(), and SBDBHFormat().
QList<SBDBHTCBlock> SBDBHFormat::ListTCBlock [protected]
Definition at line 535 of file SbGeoObsVLBI_IO.H'.
Referenced by currentTC(), dump(), getBlock(), operator>>(), postRead(), SBDBHFormat(), and tcBlocks().
short SBDBHFormat::TCcurrent [protected]
Definition at line 539 of file SbGeoObsVLBI_IO.H'.
Referenced by currentTC(), getBlock(), lookupPar(), SBDBHFormat(), and tcNum().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.