.TH "SBDBHPhysRec" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBDBHPhysRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoObsVLBI_IO\&.H>\fP
.PP
Inherited by \fBSBDBHDRecString\fP, \fBSBDBHDRecT< Class >\fP, \fBSBDBHDRecT< short >\fP, \fBSBDBHLRecPrefixed\fP, \fBSBDBHTEBlock::SBDBHLRecP3\fP, and \fBSBDBHTEBlock::SBDBHLRecP4\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBDBHPhysRec\fP ()"
.br
.ti -1c
.RI "virtual \fB~SBDBHPhysRec\fP ()"
.br
.ti -1c
.RI "bool \fBisOk\fP ()"
.br
.ti -1c
.RI "int \fBlength\fP ()"
.br
.ti -1c
.RI "virtual \fBSBDBHPar::PType\fP \fBtype\fP ()"
.br
.ti -1c
.RI "virtual int \fBparseLR\fP (\fBSBDS_dbh\fP &s)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBLength\fP"
.br
.ti -1c
.RI "char * \fBLogRec\fP"
.br
.ti -1c
.RI "bool \fBisOK\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &, \fBSBDBHPhysRec\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file SbGeoObsVLBI_IO\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBDBHPhysRec::SBDBHPhysRec ()\fC [inline]\fP"
.PP
Definition at line 114 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References isOK, Length, and LogRec\&.
.SS "virtual SBDBHPhysRec::~SBDBHPhysRec ()\fC [inline, virtual]\fP"
.PP
Definition at line 115 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References LogRec\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SBDBHPhysRec::isOk ()\fC [inline]\fP"
.PP
Definition at line 117 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References isOK\&.
.PP
Referenced by operator>>()\&.
.SS "int SBDBHPhysRec::length ()\fC [inline]\fP"
.PP
Definition at line 118 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References Length\&.
.PP
Referenced by operator>>()\&.
.SS "virtual int SBDBHPhysRec::parseLR (\fBSBDS_dbh\fP &s)\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBSBDBHTEBlock::SBDBHLRecP4\fP, \fBSBDBHTEBlock::SBDBHLRecP3\fP, \fBSBDBHDRecT< Class >\fP, \fBSBDBHDRecT< short >\fP, \fBSBDBHDRecString\fP, \fBSBDBHLRecZ3\fP, \fBSBDBHLRecDE\fP, \fBSBDBHLRecDR\fP, \fBSBDBHLRecTC\fP, \fBSBDBHLRecTE\fP, \fBSBDBHLRecHS1\fP, and \fBSBDBHLRecPrefixed\fP'\&.
.PP
Definition at line 120 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References Length, and LogRec\&.
.PP
Referenced by operator>>()\&.
.SS "virtual \fBSBDBHPar::PType\fP SBDBHPhysRec::type ()\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBSBDBHDRecString\fP'\&.
.PP
Definition at line 119 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPar::T_UNKN\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHPhysRec\fP &PH)\fC [friend]\fP"
.PP
Definition at line 2325 of file SbGeoObsVLBI_IO\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSBDBHPhysRec::isOK\fP\fC [protected]\fP"
.PP
Definition at line 112 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec()\&.
.SS "int \fBSBDBHPhysRec::Length\fP\fC [protected]\fP"
.PP
Definition at line 110 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by length(), operator>>(), parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec()\&.
.SS "char* \fBSBDBHPhysRec::LogRec\fP\fC [protected]\fP"
.PP
Definition at line 111 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec(), SBDBHDRecString::val(), and ~SBDBHPhysRec()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
