SBDBHLRecHS1
NAME
SBDBHLRecHS1 -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Inherits SBDBHLRecPrefixed'.
Public Member Functions
SBDBHLRecHS1 ()
int histLength ()
int verNum ()
SBMJD date ()
bool isZ1 ()
virtual bool isAlter ()
virtual int parseLR (SBDS_dbh &s)
bool isP ()
virtual bool isPrefixParsed (SBDS_dbh &)
bool isOk ()
int length ()
virtual SBDBHPar::PType type ()
Protected Attributes
short HistLength
short Date [5]
short VerNum
char Prefix [2]
char P [3]
int Length
char * LogRec
bool isOK
Friends
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHPhysRec &)
Detailed Description
Definition at line 155 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHLRecHS1::SBDBHLRecHS1 () [inline]
Definition at line 162 of file SbGeoObsVLBI_IO.H'.
References Date, HistLength, and VerNum.
Member Function Documentation
SBMJD SBDBHLRecHS1::date () [inline]
Definition at line 166 of file SbGeoObsVLBI_IO.H'.
References Date.
Referenced by SBDBHHistTriplet::date(), and SBDBHHistTriplet::dump().
int SBDBHLRecHS1::histLength () [inline]
Definition at line 164 of file SbGeoObsVLBI_IO.H'.
References HistLength.
Referenced by operator>>().
virtual bool SBDBHLRecHS1::isAlter () [inline, virtual]
Reimplemented from SBDBHLRecPrefixed'.
Definition at line 168 of file SbGeoObsVLBI_IO.H'.
References isZ1().
bool SBDBHPhysRec::isOk () [inline, inherited]
Definition at line 117 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::isOK.
Referenced by operator>>().
bool SBDBHLRecPrefixed::isP () [inline, inherited]
Definition at line 140 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecPrefixed::P, and SBDBHLRecPrefixed::Prefix.
Referenced by SBDBHHistTriplet::isHistLine(), SBDBHLRecPrefixed::isPrefixParsed(), and operator>>().
bool SBDBHLRecPrefixed::isPrefixParsed (SBDS_dbh &s) [virtual, inherited]
Definition at line 2389 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, SBLog::ERR, SBDBHLRecPrefixed::isAlter(), SBDBHPhysRec::isOK, SBDBHLRecPrefixed::isP(), Log, SBDBHLRecPrefixed::P, SBDBHLRecPrefixed::Prefix, and SBLog::write().
Referenced by SBDBHLRecPrefixed::parseLR(), parseLR(), SBDBHLRecTE::parseLR(), SBDBHLRecTC::parseLR(), SBDBHLRecDR::parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecZ3::parseLR().
bool SBDBHLRecHS1::isZ1 () [inline]
Definition at line 167 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecPrefixed::Prefix.
Referenced by isAlter(), and SBDBHHistTriplet::isLast().
int SBDBHPhysRec::length () [inline, inherited]
Definition at line 118 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::Length.
Referenced by operator>>().
virtual int SBDBHLRecHS1::parseLR (SBDS_dbh &s) [inline, virtual]
Reimplemented from SBDBHLRecPrefixed'.
Definition at line 169 of file SbGeoObsVLBI_IO.H'.
References Date, HistLength, SBDBHLRecPrefixed::isPrefixParsed(), and VerNum.
virtual SBDBHPar::PType SBDBHPhysRec::type () [inline, virtual, inherited]
Reimplemented in SBDBHDRecString'.
Definition at line 119 of file SbGeoObsVLBI_IO.H'.
References SBDBHPar::T_UNKN.
int SBDBHLRecHS1::verNum () [inline]
Definition at line 165 of file SbGeoObsVLBI_IO.H'.
References VerNum.
Referenced by SBDBHHistTriplet::dump(), and SBDBHHistTriplet::verNum().
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHPhysRec &PH) [friend, inherited]
Definition at line 2325 of file SbGeoObsVLBI_IO.C'.
Member Data Documentation
short SBDBHLRecHS1::Date[5] [protected]
Definition at line 159 of file SbGeoObsVLBI_IO.H'.
Referenced by date(), parseLR(), and SBDBHLRecHS1().
short SBDBHLRecHS1::HistLength [protected]
Definition at line 158 of file SbGeoObsVLBI_IO.H'.
Referenced by histLength(), parseLR(), and SBDBHLRecHS1().
bool SBDBHPhysRec::isOK [protected, inherited]
Definition at line 112 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
int SBDBHPhysRec::Length [protected, inherited]
Definition at line 110 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
char* SBDBHPhysRec::LogRec [protected, inherited]
Definition at line 111 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec::SBDBHPhysRec(), SBDBHDRecString::val(), and SBDBHPhysRec::~SBDBHPhysRec().
char SBDBHLRecPrefixed::P[3] [protected, inherited]
Definition at line 137 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed().
char SBDBHLRecPrefixed::Prefix[2] [protected, inherited]
Definition at line 136 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecDR::dump(), SBDBHLRecTC::isAlter(), SBDBHLRecDE::isAlter(), SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), isZ1(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed().
short SBDBHLRecHS1::VerNum [protected]
Definition at line 160 of file SbGeoObsVLBI_IO.H'.
Referenced by parseLR(), SBDBHLRecHS1(), and verNum().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.