SBDBHDRecString
NAME
SBDBHDRecString -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Inherits SBDBHPhysRec'.
Public Member Functions
SBDBHDRecString ()
const QString & text ()
virtual const QString val (SBDBHPar *, int, int)
virtual SBDBHPar::PType type ()
virtual int parseLR (SBDS_dbh &s)
bool isOk ()
int length ()
Protected Attributes
QString Text
int Length
char * LogRec
bool isOK
Friends
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHPhysRec &)
Detailed Description
Definition at line 329 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHDRecString::SBDBHDRecString () [inline]
Definition at line 334 of file SbGeoObsVLBI_IO.H'.
References Text.
Member Function Documentation
bool SBDBHPhysRec::isOk () [inline, inherited]
Definition at line 117 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::isOK.
Referenced by operator>>().
int SBDBHPhysRec::length () [inline, inherited]
Definition at line 118 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::Length.
Referenced by operator>>().
virtual int SBDBHDRecString::parseLR (SBDS_dbh &s) [inline, virtual]
Reimplemented from SBDBHPhysRec'.
Definition at line 338 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::isOK, SBDBHPhysRec::LogRec, and Text.
const QString& SBDBHDRecString::text () [inline]
Definition at line 335 of file SbGeoObsVLBI_IO.H'.
References Text.
Referenced by SBDBHStartBlock::dbName(), SBDBHHistTriplet::dump(), SBDBHStartBlock::dump(), SBDBHStartBlock::expDescr(), operator>>(), SBDBHStartBlock::prevDb(), SBDBHStartBlock::prevDescr(), SBDBHStartBlock::sessID(), and SBDBHHistTriplet::text().
virtual SBDBHPar::PType SBDBHDRecString::type () [inline, virtual]
Reimplemented from SBDBHPhysRec'.
Definition at line 337 of file SbGeoObsVLBI_IO.H'.
References SBDBHPar::T_A2.
const QString SBDBHDRecString::val (SBDBHPar *Par, intdim2, intdim3) [virtual]
Definition at line 2458 of file SbGeoObsVLBI_IO.C'.
References SBDBHPar::dim1(), SBDBHPar::dim2(), SBDBHPhysRec::LogRec, and SBDBHPar::offset().
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHPhysRec &PH) [friend, inherited]
Definition at line 2325 of file SbGeoObsVLBI_IO.C'.
Member Data Documentation
bool SBDBHPhysRec::isOK [protected, inherited]
Definition at line 112 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
int SBDBHPhysRec::Length [protected, inherited]
Definition at line 110 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
char* SBDBHPhysRec::LogRec [protected, inherited]
Definition at line 111 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::parseLR(), parseLR(), SBDBHPhysRec::SBDBHPhysRec(), val(), and SBDBHPhysRec::~SBDBHPhysRec().
QString SBDBHDRecString::Text [protected]
Definition at line 332 of file SbGeoObsVLBI_IO.H'.
Referenced by parseLR(), SBDBHDRecString(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.