.TH "SBDBHStartBlock" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBDBHStartBlock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoObsVLBI_IO\&.H>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBDBHStartBlock\fP ()"
.br
.ti -1c
.RI "bool \fBisOk\fP ()"
.br
.ti -1c
.RI "\fBSBMJD\fP \fBdate\fP ()"
.br
.ti -1c
.RI "int \fBversion\fP ()"
.br
.ti -1c
.RI "const QString & \fBdbName\fP ()"
.br
.ti -1c
.RI "const QString & \fBexpDescr\fP ()"
.br
.ti -1c
.RI "const QString & \fBsessID\fP ()"
.br
.ti -1c
.RI "const QString & \fBprevDb\fP ()"
.br
.ti -1c
.RI "const QString & \fBprevDescr\fP ()"
.br
.ti -1c
.RI "void \fBdump\fP (\fBQTextStream\fP &)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSBDBHDRecString\fP \fBDbName\fP"
.br
.ti -1c
.RI "\fBSBDBHDRecString\fP \fBExpDescr\fP"
.br
.ti -1c
.RI "\fBSBDBHDRecString\fP \fBSessID\fP"
.br
.ti -1c
.RI "\fBSBDBHDRecString\fP \fBPrevDb\fP"
.br
.ti -1c
.RI "\fBSBDBHDRecString\fP \fBPrev\fP"
.br
.ti -1c
.RI "\fBSBDBHDRecT\fP< short > \fBDate\fP"
.br
.ti -1c
.RI "\fBSBDBHDRecT\fP< short > \fBVer\fP"
.br
.ti -1c
.RI "bool \fBisOK\fP"
.br
.ti -1c
.RI "short \fBDateVal\fP [5]"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &, \fBSBDBHStartBlock\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 503 of file SbGeoObsVLBI_IO\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBDBHStartBlock::SBDBHStartBlock ()\fC [inline]\fP"
.PP
Definition at line 511 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References DateVal, and isOK\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSBMJD\fP SBDBHStartBlock::date ()\fC [inline]\fP"
.PP
Definition at line 513 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References DateVal\&.
.SS "const QString& SBDBHStartBlock::dbName ()\fC [inline]\fP"
.PP
Definition at line 515 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References DbName, and SBDBHDRecString::text()\&.
.SS "void SBDBHStartBlock::dump (\fBQTextStream\fP &s)"
.PP
Definition at line 2580 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References Date, DateVal, DbName, ExpDescr, SBMJD::F_Short, Prev, PrevDb, SessID, SBDBHDRecString::text(), SBMJD::toString(), and Ver\&.
.SS "const QString& SBDBHStartBlock::expDescr ()\fC [inline]\fP"
.PP
Definition at line 516 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References ExpDescr, and SBDBHDRecString::text()\&.
.SS "bool SBDBHStartBlock::isOk ()\fC [inline]\fP"
.PP
Definition at line 512 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References isOK\&.
.SS "const QString& SBDBHStartBlock::prevDb ()\fC [inline]\fP"
.PP
Definition at line 518 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References PrevDb, and SBDBHDRecString::text()\&.
.SS "const QString& SBDBHStartBlock::prevDescr ()\fC [inline]\fP"
.PP
Definition at line 519 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References Prev, and SBDBHDRecString::text()\&.
.SS "const QString& SBDBHStartBlock::sessID ()\fC [inline]\fP"
.PP
Definition at line 517 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SessID, and SBDBHDRecString::text()\&.
.SS "int SBDBHStartBlock::version ()\fC [inline]\fP"
.PP
Definition at line 514 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References Ver\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHStartBlock\fP &S)\fC [friend]\fP"
.PP
Definition at line 2599 of file SbGeoObsVLBI_IO\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBDBHDRecT\fP<short> \fBSBDBHStartBlock::Date\fP\fC [protected]\fP"
.PP
Definition at line 507 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), and operator>>()\&.
.SS "short \fBSBDBHStartBlock::DateVal\fP[5]\fC [protected]\fP"
.PP
Definition at line 509 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by date(), dump(), operator>>(), and SBDBHStartBlock()\&.
.SS "\fBSBDBHDRecString\fP \fBSBDBHStartBlock::DbName\fP\fC [protected]\fP"
.PP
Definition at line 506 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dbName(), dump(), and operator>>()\&.
.SS "\fBSBDBHDRecString\fP \fBSBDBHStartBlock::ExpDescr\fP\fC [protected]\fP"
.PP
Definition at line 506 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), expDescr(), and operator>>()\&.
.SS "bool \fBSBDBHStartBlock::isOK\fP\fC [protected]\fP"
.PP
Definition at line 508 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by isOk(), operator>>(), and SBDBHStartBlock()\&.
.SS "\fBSBDBHDRecString\fP \fBSBDBHStartBlock::Prev\fP\fC [protected]\fP"
.PP
Definition at line 506 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), operator>>(), and prevDescr()\&.
.SS "\fBSBDBHDRecString\fP \fBSBDBHStartBlock::PrevDb\fP\fC [protected]\fP"
.PP
Definition at line 506 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), operator>>(), and prevDb()\&.
.SS "\fBSBDBHDRecString\fP \fBSBDBHStartBlock::SessID\fP\fC [protected]\fP"
.PP
Definition at line 506 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), operator>>(), and sessID()\&.
.SS "\fBSBDBHDRecT\fP<short> \fBSBDBHStartBlock::Ver\fP\fC [protected]\fP"
.PP
Definition at line 507 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), operator>>(), and version()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
