SBDBHTCBlock
NAME
SBDBHTCBlock -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Public Member Functions
SBDBHTCBlock ()
~SBDBHTCBlock ()
bool isLast ()
QList< SBDBHTEBlock > * teBlocks ()
QDict< SBDBHPar > * parByAbbrev ()
short numTEBlocks ()
short tocType ()
bool isOk ()
void dump (QTextStream &s)
Protected Attributes
SBDBHLRecTC Rec
QList< SBDBHTEBlock > ListTEBlock
bool isOK
QDict< SBDBHPar > * ParByAbbrev
Friends
class SBDBHFormat
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHTCBlock &)
Detailed Description
Definition at line 467 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHTCBlock::SBDBHTCBlock () [inline]
Definition at line 476 of file SbGeoObsVLBI_IO.H'.
References isOK, ListTEBlock, and ParByAbbrev.
SBDBHTCBlock::~SBDBHTCBlock () [inline]
Definition at line 478 of file SbGeoObsVLBI_IO.H'.
References ParByAbbrev.
Member Function Documentation
void SBDBHTCBlock::dump (QTextStream &s) [inline]
Definition at line 485 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecTC::dump(), ListTEBlock, Rec, and tocType().
bool SBDBHTCBlock::isLast () [inline]
Definition at line 479 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecTC::isZ2(), and Rec.
Referenced by operator>>().
bool SBDBHTCBlock::isOk () [inline]
Definition at line 484 of file SbGeoObsVLBI_IO.H'.
References isOK.
short SBDBHTCBlock::numTEBlocks () [inline]
Definition at line 482 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecTC::numTEBlocks(), and Rec.
QDict<SBDBHPar>* SBDBHTCBlock::parByAbbrev () [inline]
Definition at line 481 of file SbGeoObsVLBI_IO.H'.
References ParByAbbrev.
Referenced by SBDBHFormat::lookupPar().
QList<SBDBHTEBlock>* SBDBHTCBlock::teBlocks () [inline]
Definition at line 480 of file SbGeoObsVLBI_IO.H'.
References ListTEBlock.
Referenced by SBDBHFormat::getBlock(), SBDBHFormat::lookupPar(), and SBDBHFormat::parRecord().
short SBDBHTCBlock::tocType () [inline]
Definition at line 483 of file SbGeoObsVLBI_IO.H'.
References Rec, and SBDBHLRecTC::tocType().
Referenced by dump().
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHTCBlock &B) [friend]
Definition at line 2557 of file SbGeoObsVLBI_IO.C'.
friend class SBDBHFormat [friend]
Definition at line 469 of file SbGeoObsVLBI_IO.H'.
Member Data Documentation
bool SBDBHTCBlock::isOK [protected]
Definition at line 473 of file SbGeoObsVLBI_IO.H'.
Referenced by isOk(), operator>>(), and SBDBHTCBlock().
QList<SBDBHTEBlock> SBDBHTCBlock::ListTEBlock [protected]
Definition at line 472 of file SbGeoObsVLBI_IO.H'.
Referenced by dump(), operator>>(), SBDBHTCBlock(), and teBlocks().
QDict<SBDBHPar>* SBDBHTCBlock::ParByAbbrev [protected]
Definition at line 474 of file SbGeoObsVLBI_IO.H'.
Referenced by parByAbbrev(), SBDBHTCBlock(), and ~SBDBHTCBlock().
SBDBHLRecTC SBDBHTCBlock::Rec [protected]
Definition at line 471 of file SbGeoObsVLBI_IO.H'.
Referenced by dump(), isLast(), numTEBlocks(), operator>>(), and tocType().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.