SBDBHLRecZ3
NAME
SBDBHLRecZ3 -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Inherits SBDBHLRecPrefixed'.
Public Member Functions
SBDBHLRecZ3 ()
int p1 ()
virtual int parseLR (SBDS_dbh &s)
void dump (QTextStream &s)
bool isP ()
virtual bool isAlter ()
virtual bool isPrefixParsed (SBDS_dbh &)
bool isOk ()
int length ()
virtual SBDBHPar::PType type ()
Protected Attributes
short P1
char Prefix [2]
char P [3]
int Length
char * LogRec
bool isOK
Friends
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHPhysRec &)
Detailed Description
Definition at line 302 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHLRecZ3::SBDBHLRecZ3 () [inline]
Definition at line 307 of file SbGeoObsVLBI_IO.H'.
References P1.
Member Function Documentation
void SBDBHLRecZ3::dump (QTextStream &s) [inline]
Definition at line 316 of file SbGeoObsVLBI_IO.H'.
References P1.
virtual bool SBDBHLRecPrefixed::isAlter () [inline, virtual, inherited]
Reimplemented in SBDBHLRecDE, SBDBHLRecTC, and SBDBHLRecHS1'.
Definition at line 141 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecPrefixed::isPrefixParsed().
bool SBDBHPhysRec::isOk () [inline, inherited]
Definition at line 117 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::isOK.
Referenced by operator>>().
bool SBDBHLRecPrefixed::isP () [inline, inherited]
Definition at line 140 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecPrefixed::P, and SBDBHLRecPrefixed::Prefix.
Referenced by SBDBHHistTriplet::isHistLine(), SBDBHLRecPrefixed::isPrefixParsed(), and operator>>().
bool SBDBHLRecPrefixed::isPrefixParsed (SBDS_dbh &s) [virtual, inherited]
Definition at line 2389 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, SBLog::ERR, SBDBHLRecPrefixed::isAlter(), SBDBHPhysRec::isOK, SBDBHLRecPrefixed::isP(), Log, SBDBHLRecPrefixed::P, SBDBHLRecPrefixed::Prefix, and SBLog::write().
Referenced by SBDBHLRecPrefixed::parseLR(), SBDBHLRecHS1::parseLR(), SBDBHLRecTE::parseLR(), SBDBHLRecTC::parseLR(), SBDBHLRecDR::parseLR(), SBDBHLRecDE::parseLR(), and parseLR().
int SBDBHPhysRec::length () [inline, inherited]
Definition at line 118 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::Length.
Referenced by operator>>().
int SBDBHLRecZ3::p1 () [inline]
Definition at line 308 of file SbGeoObsVLBI_IO.H'.
References P1.
virtual int SBDBHLRecZ3::parseLR (SBDS_dbh &s) [inline, virtual]
Reimplemented from SBDBHLRecPrefixed'.
Definition at line 309 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecPrefixed::isPrefixParsed(), and P1.
virtual SBDBHPar::PType SBDBHPhysRec::type () [inline, virtual, inherited]
Reimplemented in SBDBHDRecString'.
Definition at line 119 of file SbGeoObsVLBI_IO.H'.
References SBDBHPar::T_UNKN.
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHPhysRec &PH) [friend, inherited]
Definition at line 2325 of file SbGeoObsVLBI_IO.C'.
Member Data Documentation
bool SBDBHPhysRec::isOK [protected, inherited]
Definition at line 112 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
int SBDBHPhysRec::Length [protected, inherited]
Definition at line 110 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
char* SBDBHPhysRec::LogRec [protected, inherited]
Definition at line 111 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec::SBDBHPhysRec(), SBDBHDRecString::val(), and SBDBHPhysRec::~SBDBHPhysRec().
char SBDBHLRecPrefixed::P[3] [protected, inherited]
Definition at line 137 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed().
short SBDBHLRecZ3::P1 [protected]
Definition at line 305 of file SbGeoObsVLBI_IO.H'.
Referenced by dump(), p1(), parseLR(), and SBDBHLRecZ3().
char SBDBHLRecPrefixed::Prefix[2] [protected, inherited]
Definition at line 136 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecDR::dump(), SBDBHLRecTC::isAlter(), SBDBHLRecDE::isAlter(), SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), SBDBHLRecHS1::isZ1(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.