SBDBHHistTriplet
NAME
SBDBHHistTriplet -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Public Member Functions
SBDBHHistTriplet ()
bool isHistLine ()
bool isLast ()
int verNum ()
SBMJD date ()
const QString & text ()
bool isOk ()
void dump (QTextStream &s)
Protected Attributes
SBDBHLRecHS1 Rec1
SBDBHPhysRec Rec2
SBDBHDRecString Rec3
bool isOK
Friends
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHHistTriplet &)
Detailed Description
Definition at line 384 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHHistTriplet::SBDBHHistTriplet () [inline]
Definition at line 392 of file SbGeoObsVLBI_IO.H'.
References isOK.
Member Function Documentation
SBMJD SBDBHHistTriplet::date () [inline]
Definition at line 396 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecHS1::date(), and Rec1.
void SBDBHHistTriplet::dump (QTextStream &s) [inline]
Definition at line 399 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecHS1::date(), SBMJD::F_Short, Rec1, Rec3, SBDBHDRecString::text(), SBMJD::toString(), and SBDBHLRecHS1::verNum().
bool SBDBHHistTriplet::isHistLine () [inline]
Definition at line 393 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecPrefixed::isP(), and Rec1.
bool SBDBHHistTriplet::isLast () [inline]
Definition at line 394 of file SbGeoObsVLBI_IO.H'.
References SBDBHLRecHS1::isZ1(), and Rec1.
bool SBDBHHistTriplet::isOk () [inline]
Definition at line 398 of file SbGeoObsVLBI_IO.H'.
References isOK.
const QString& SBDBHHistTriplet::text () [inline]
Definition at line 397 of file SbGeoObsVLBI_IO.H'.
References Rec3, and SBDBHDRecString::text().
int SBDBHHistTriplet::verNum () [inline]
Definition at line 395 of file SbGeoObsVLBI_IO.H'.
References Rec1, and SBDBHLRecHS1::verNum().
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHHistTriplet &HT) [friend]
Definition at line 2478 of file SbGeoObsVLBI_IO.C'.
Member Data Documentation
bool SBDBHHistTriplet::isOK [protected]
Definition at line 390 of file SbGeoObsVLBI_IO.H'.
Referenced by isOk(), operator>>(), and SBDBHHistTriplet().
SBDBHLRecHS1 SBDBHHistTriplet::Rec1 [protected]
Definition at line 387 of file SbGeoObsVLBI_IO.H'.
Referenced by date(), dump(), isHistLine(), isLast(), operator>>(), and verNum().
SBDBHPhysRec SBDBHHistTriplet::Rec2 [protected]
Definition at line 388 of file SbGeoObsVLBI_IO.H'.
Referenced by operator>>().
SBDBHDRecString SBDBHHistTriplet::Rec3 [protected]
Definition at line 389 of file SbGeoObsVLBI_IO.H'.
Referenced by dump(), operator>>(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.