SBDBHLRecPrefixed
NAME
SBDBHLRecPrefixed -
SYNOPSIS
#include <SbGeoObsVLBI_IO.H>
Inherits SBDBHPhysRec'.
Inherited by SBDBHLRecDE, SBDBHLRecDR, SBDBHLRecHS1, SBDBHLRecTC, SBDBHLRecTE, and SBDBHLRecZ3'.
Public Member Functions
SBDBHLRecPrefixed (char P_[2])
bool isP ()
virtual bool isAlter ()
virtual bool isPrefixParsed (SBDS_dbh &)
virtual int parseLR (SBDS_dbh &s)
bool isOk ()
int length ()
virtual SBDBHPar::PType type ()
Protected Attributes
char Prefix [2]
char P [3]
int Length
char * LogRec
bool isOK
Friends
SBDS_dbh & operator>> (SBDS_dbh &, SBDBHPhysRec &)
Detailed Description
Definition at line 133 of file SbGeoObsVLBI_IO.H'.
Constructor & Destructor Documentation
SBDBHLRecPrefixed::SBDBHLRecPrefixed (charP_[2]) [inline]
Definition at line 139 of file SbGeoObsVLBI_IO.H'.
References P, and Prefix.
Member Function Documentation
virtual bool SBDBHLRecPrefixed::isAlter () [inline, virtual]
Reimplemented in SBDBHLRecDE, SBDBHLRecTC, and SBDBHLRecHS1'.
Definition at line 141 of file SbGeoObsVLBI_IO.H'.
Referenced by isPrefixParsed().
bool SBDBHPhysRec::isOk () [inline, inherited]
Definition at line 117 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::isOK.
Referenced by operator>>().
bool SBDBHLRecPrefixed::isP () [inline]
Definition at line 140 of file SbGeoObsVLBI_IO.H'.
References P, and Prefix.
Referenced by SBDBHHistTriplet::isHistLine(), isPrefixParsed(), and operator>>().
bool SBDBHLRecPrefixed::isPrefixParsed (SBDS_dbh &s) [virtual]
Definition at line 2389 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, SBLog::ERR, isAlter(), SBDBHPhysRec::isOK, isP(), Log, P, Prefix, and SBLog::write().
Referenced by parseLR(), SBDBHLRecHS1::parseLR(), SBDBHLRecTE::parseLR(), SBDBHLRecTC::parseLR(), SBDBHLRecDR::parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecZ3::parseLR().
int SBDBHPhysRec::length () [inline, inherited]
Definition at line 118 of file SbGeoObsVLBI_IO.H'.
References SBDBHPhysRec::Length.
Referenced by operator>>().
virtual int SBDBHLRecPrefixed::parseLR (SBDS_dbh &s) [inline, virtual]
Reimplemented from SBDBHPhysRec'.
Reimplemented in SBDBHLRecZ3, SBDBHLRecDE, SBDBHLRecDR, SBDBHLRecTC, SBDBHLRecTE, and SBDBHLRecHS1'.
Definition at line 143 of file SbGeoObsVLBI_IO.H'.
References isPrefixParsed().
virtual SBDBHPar::PType SBDBHPhysRec::type () [inline, virtual, inherited]
Reimplemented in SBDBHDRecString'.
Definition at line 119 of file SbGeoObsVLBI_IO.H'.
References SBDBHPar::T_UNKN.
Friends And Related Function Documentation
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHPhysRec &PH) [friend, inherited]
Definition at line 2325 of file SbGeoObsVLBI_IO.C'.
Member Data Documentation
bool SBDBHPhysRec::isOK [protected, inherited]
Definition at line 112 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::isOk(), isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
int SBDBHPhysRec::Length [protected, inherited]
Definition at line 110 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec().
char* SBDBHPhysRec::LogRec [protected, inherited]
Definition at line 111 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHPhysRec::parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec::SBDBHPhysRec(), SBDBHDRecString::val(), and SBDBHPhysRec::~SBDBHPhysRec().
char SBDBHLRecPrefixed::P[3] [protected]
Definition at line 137 of file SbGeoObsVLBI_IO.H'.
Referenced by isP(), isPrefixParsed(), and SBDBHLRecPrefixed().
char SBDBHLRecPrefixed::Prefix[2] [protected]
Definition at line 136 of file SbGeoObsVLBI_IO.H'.
Referenced by SBDBHLRecDR::dump(), SBDBHLRecTC::isAlter(), SBDBHLRecDE::isAlter(), isP(), isPrefixParsed(), SBDBHLRecHS1::isZ1(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecPrefixed().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.