.TH "SBDBHLRecDR" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBDBHLRecDR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoObsVLBI_IO\&.H>\fP
.PP
Inherits \fBSBDBHLRecPrefixed\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBDBHLRecDR\fP ()"
.br
.ti -1c
.RI "int \fBp1\fP ()"
.br
.ti -1c
.RI "int \fBp2\fP ()"
.br
.ti -1c
.RI "virtual int \fBparseLR\fP (\fBSBDS_dbh\fP &s)"
.br
.ti -1c
.RI "void \fBdump\fP (\fBQTextStream\fP &s)"
.br
.ti -1c
.RI "bool \fBisP\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisAlter\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisPrefixParsed\fP (\fBSBDS_dbh\fP &)"
.br
.ti -1c
.RI "bool \fBisOk\fP ()"
.br
.ti -1c
.RI "int \fBlength\fP ()"
.br
.ti -1c
.RI "virtual \fBSBDBHPar::PType\fP \fBtype\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "short \fBP1\fP"
.br
.ti -1c
.RI "short \fBP2\fP"
.br
.ti -1c
.RI "char \fBPrefix\fP [2]"
.br
.ti -1c
.RI "char \fBP\fP [3]"
.br
.ti -1c
.RI "int \fBLength\fP"
.br
.ti -1c
.RI "char * \fBLogRec\fP"
.br
.ti -1c
.RI "bool \fBisOK\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &, \fBSBDBHPhysRec\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 246 of file SbGeoObsVLBI_IO\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBDBHLRecDR::SBDBHLRecDR ()\fC [inline]\fP"
.PP
Definition at line 251 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P1, and P2\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBDBHLRecDR::dump (\fBQTextStream\fP &s)\fC [inline]\fP"
.PP
Definition at line 261 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P1, P2, and SBDBHLRecPrefixed::Prefix\&.
.SS "virtual bool SBDBHLRecPrefixed::isAlter ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSBDBHLRecDE\fP, \fBSBDBHLRecTC\fP, and \fBSBDBHLRecHS1\fP'\&.
.PP
Definition at line 141 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHLRecPrefixed::isPrefixParsed()\&.
.SS "bool SBDBHPhysRec::isOk ()\fC [inline, inherited]\fP"
.PP
Definition at line 117 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPhysRec::isOK\&.
.PP
Referenced by operator>>()\&.
.SS "bool SBDBHLRecPrefixed::isP ()\fC [inline, inherited]\fP"
.PP
Definition at line 140 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHLRecPrefixed::P, and SBDBHLRecPrefixed::Prefix\&.
.PP
Referenced by SBDBHHistTriplet::isHistLine(), SBDBHLRecPrefixed::isPrefixParsed(), and operator>>()\&.
.SS "bool SBDBHLRecPrefixed::isPrefixParsed (\fBSBDS_dbh\fP &s)\fC [virtual, inherited]\fP"
.PP
Definition at line 2389 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBLog::DATA, SBLog::ERR, SBDBHLRecPrefixed::isAlter(), SBDBHPhysRec::isOK, SBDBHLRecPrefixed::isP(), Log, SBDBHLRecPrefixed::P, SBDBHLRecPrefixed::Prefix, and SBLog::write()\&.
.PP
Referenced by SBDBHLRecPrefixed::parseLR(), SBDBHLRecHS1::parseLR(), SBDBHLRecTE::parseLR(), SBDBHLRecTC::parseLR(), parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecZ3::parseLR()\&.
.SS "int SBDBHPhysRec::length ()\fC [inline, inherited]\fP"
.PP
Definition at line 118 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPhysRec::Length\&.
.PP
Referenced by operator>>()\&.
.SS "int SBDBHLRecDR::p1 ()\fC [inline]\fP"
.PP
Definition at line 252 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P1\&.
.SS "int SBDBHLRecDR::p2 ()\fC [inline]\fP"
.PP
Definition at line 253 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References P2\&.
.SS "virtual int SBDBHLRecDR::parseLR (\fBSBDS_dbh\fP &s)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBDBHLRecPrefixed\fP'\&.
.PP
Definition at line 254 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHLRecPrefixed::isPrefixParsed(), P1, and P2\&.
.SS "virtual \fBSBDBHPar::PType\fP SBDBHPhysRec::type ()\fC [inline, virtual, inherited]\fP"
.PP
Reimplemented in \fBSBDBHDRecString\fP'\&.
.PP
Definition at line 119 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
References SBDBHPar::T_UNKN\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHPhysRec\fP &PH)\fC [friend, inherited]\fP"
.PP
Definition at line 2325 of file SbGeoObsVLBI_IO\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSBDBHPhysRec::isOK\fP\fC [protected, inherited]\fP"
.PP
Definition at line 112 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::isOk(), SBDBHLRecPrefixed::isPrefixParsed(), operator>>(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), SBDBHDRecString::parseLR(), and SBDBHPhysRec::SBDBHPhysRec()\&.
.SS "int \fBSBDBHPhysRec::Length\fP\fC [protected, inherited]\fP"
.PP
Definition at line 110 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::length(), operator>>(), SBDBHPhysRec::parseLR(), SBDBHDRecT< short >::parseLR(), and SBDBHPhysRec::SBDBHPhysRec()\&.
.SS "char* \fBSBDBHPhysRec::LogRec\fP\fC [protected, inherited]\fP"
.PP
Definition at line 111 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHPhysRec::parseLR(), SBDBHDRecString::parseLR(), SBDBHPhysRec::SBDBHPhysRec(), SBDBHDRecString::val(), and SBDBHPhysRec::~SBDBHPhysRec()\&.
.SS "char \fBSBDBHLRecPrefixed::P\fP[3]\fC [protected, inherited]\fP"
.PP
Definition at line 137 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed()\&.
.SS "short \fBSBDBHLRecDR::P1\fP\fC [protected]\fP"
.PP
Definition at line 249 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p1(), parseLR(), and SBDBHLRecDR()\&.
.SS "short \fBSBDBHLRecDR::P2\fP\fC [protected]\fP"
.PP
Definition at line 249 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), p2(), parseLR(), and SBDBHLRecDR()\&.
.SS "char \fBSBDBHLRecPrefixed::Prefix\fP[2]\fC [protected, inherited]\fP"
.PP
Definition at line 136 of file SbGeoObsVLBI_IO\&.H'\&.
.PP
Referenced by dump(), SBDBHLRecTC::isAlter(), SBDBHLRecDE::isAlter(), SBDBHLRecPrefixed::isP(), SBDBHLRecPrefixed::isPrefixParsed(), SBDBHLRecHS1::isZ1(), SBDBHLRecTC::parseLR(), SBDBHLRecDE::parseLR(), and SBDBHLRecPrefixed::SBDBHLRecPrefixed()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
