SBDerivation
NAME
SBDerivation -
SYNOPSIS
#include <SbGeoParameter.H>
Inherits SBNamed, and SBAttributed'.
Inherited by SBParameter'.
Public Types
enum Attributes { IsBreak = (1<<0), IsPropagated = (1<<1), IsInRun = (1<<2) }
Public Member Functions
SBDerivation (const QString &)
SBDerivation (const SBDerivation &Der_)
virtual ~SBDerivation ()
SBDerivation & operator= (const SBDerivation &)
virtual QString ClassName () const
virtual double d (const SBMJD &=TZero) const
virtual int num (const SBMJD &=TZero) const
virtual int numSes (const SBMJD &=TZero) const
virtual SBMJD tStart (const SBMJD &=TZero) const
virtual SBMJD tFinis (const SBMJD &=TZero) const
virtual SBMJD tEpoch (const SBMJD &=TZero) const
virtual double tInterval (const SBMJD &=TZero) const
virtual void setD (double, const SBMJD &)
virtual void setNum (int Num_)
virtual void setNumSes (int Num_)
virtual void addNumSes (int Num_)
virtual void setTimes (const SBDerivation &Der)
virtual int num_aux (const SBMJD &=TZero) const
virtual SBMJD tStart_aux (const SBMJD &=TZero) const
virtual SBMJD tFinis_aux (const SBMJD &=TZero) const
virtual SBMJD tEpoch_aux (const SBMJD &=TZero) const
virtual double tInterval_aux (const SBMJD &=TZero) const
virtual void clearValues ()
virtual void clearValues_aux ()
virtual void invertAux ()
virtual void zero ()
const QString & name () const
void setName (const QString &Name_)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Attributes
double D
value of a derivation;
int Num
number of points per derivation;
int NumSes
number of sessions per derivation;
SBMJD TStart
MJD of the first measurement;'.
SBMJD TFinis
MJD of the last measurement;'.
long double TSum
the sum of the epochs of observation;
int Num_aux
number of points per derivation;
SBMJD TStart_aux
MJD of the first measurement;'.
SBMJD TFinis_aux
MJD of the last measurement;'.
long double TSum_aux
the sum of the epochs of observation;
QString Name
Friends
QDataStream & operator<< (QDataStream &, const SBDerivation &)
QDataStream & operator>> (QDataStream &, SBDerivation &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
SBDerivation'. Keeps basic info about derivation'.
Definition at line 278 of file SbGeoParameter.H'.
Member Enumeration Documentation
enum SBDerivation::Attributes
Enumerator:
IsBreak
there is a break in the parameter's behaviour
IsPropagated
the parameter's info have to be propagated in future
IsInRun
Definition at line 281 of file SbGeoParameter.H'.
Constructor & Destructor Documentation
SBDerivation::SBDerivation (const QString &Name_)"A constructor'.
A constructor'. Creates a copy of object'.
Definition at line 255 of file SbGeoParameter.C'.
References D, Num, Num_aux, NumSes, TFinis, TFinis_aux, TStart, TStart_aux, TSum, TSum_aux, and TZero.
SBDerivation::SBDerivation (const SBDerivation &Der_) [inline]"A constructor'.
Definition at line 308 of file SbGeoParameter.H'.
virtual SBDerivation::~SBDerivation () [inline, virtual]"A destructor'.
Definition at line 310 of file SbGeoParameter.H'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
virtual void SBDerivation::addNumSes (intNum_) [inline, virtual]
Definition at line 337 of file SbGeoParameter.H'.
Referenced by SBRunManager::process_m1().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBDerivation::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBAttributed'.
Reimplemented in SBStochParameter, SBParameter, and SBSINEXParameter'.
Definition at line 313 of file SbGeoParameter.H'.
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBDerivation::clearValues () [virtual]
Reimplemented in SBParameter'.
Definition at line 310 of file SbGeoParameter.C'.
References D, Num, NumSes, TFinis, TStart, TSum, and TZero.
void SBDerivation::clearValues_aux () [virtual]
Definition at line 320 of file SbGeoParameter.C'.
References D, Num_aux, TFinis_aux, TStart_aux, TSum_aux, and TZero.
virtual double SBDerivation::d (const SBMJD & = TZero) const [inline, virtual]"Returns the value of the derivation'.
Definition at line 318 of file SbGeoParameter.H'.
References D.
Referenced by SBStatistics::addWPFR(), SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBEstimator::processObs(), SBStatistics::setWPFR(), and SBStatistics::setWRMS().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
virtual void SBDerivation::invertAux () [inline, virtual]
Definition at line 358 of file SbGeoParameter.H'.
References Num_aux, TFinis_aux, TStart_aux, and TSum_aux.
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual int SBDerivation::num (const SBMJD & = TZero) const [inline, virtual]"Returns the number of observations'.
Reimplemented in SBStochParameter'.
Definition at line 320 of file SbGeoParameter.H'.
References Num.
Referenced by SBStochParameter::addPar(), SBStochParameter::dump2File(), SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBSource::getParameters4Report(), SBParameterLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBStochParameter::num(), operator<<(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBParameterLI::text(), SBStochParameter::update(), and SBSolution::updateParameter().
virtual int SBDerivation::num_aux (const SBMJD & = TZero) const [inline, virtual]"Returns the number of observations'.
Definition at line 344 of file SbGeoParameter.H'.
References Num_aux.
virtual int SBDerivation::numSes (const SBMJD & = TZero) const [inline, virtual]"Returns the number of sessions'.
Definition at line 322 of file SbGeoParameter.H'.
References NumSes.
Referenced by SBSource::getGlobalParameters4Report(), and SBSource::getParameters4Report().
SBDerivation & SBDerivation::operator= (const SBDerivation &Der_)
Definition at line 271 of file SbGeoParameter.C'.
References D, Num, Num_aux, NumSes, TFinis, TFinis_aux, TStart, TStart_aux, TSum, and TSum_aux.
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBDerivation::setD (doubleD_, const SBMJD &T) [virtual]"Sets up the value of the derivation'.
Definition at line 291 of file SbGeoParameter.C'.
References D, Num, Num_aux, TFinis, TFinis_aux, TStart, TStart_aux, TSum, TSum_aux, and TZero.
Referenced by SBStation::axisOffsetLenght(), SBDelay::calcDerivatives(), SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), and SBObsVLBIEntry::process().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
virtual void SBDerivation::setNum (intNum_) [inline, virtual]"Sets up the value of the number of observations'.
Definition at line 335 of file SbGeoParameter.H'.
Referenced by SBSolution::updateParameter().
virtual void SBDerivation::setNumSes (intNum_) [inline, virtual]
Definition at line 336 of file SbGeoParameter.H'.
virtual void SBDerivation::setTimes (const SBDerivation &Der) [inline, virtual]
Definition at line 338 of file SbGeoParameter.H'.
References Num, NumSes, TFinis, TStart, and TSum.
Referenced by SBSolution::getGlobalParameter4Report(), and SBSolution::updateParameter().
virtual SBMJD SBDerivation::tEpoch (const SBMJD & = TZero) const [inline, virtual]"Returns date of the mean observation'.
Reimplemented in SBStochParameter'.
Definition at line 328 of file SbGeoParameter.H'.
References TZero.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStochParameter::dump2File(), SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBSource::getParameters4Report(), SBParameterLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTRFVariations(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBStochParameter::tEpoch(), SBParameterLI::text(), SBParameter::timeStamp(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
virtual SBMJD SBDerivation::tEpoch_aux (const SBMJD & = TZero) const [inline, virtual]"Returns date of the mean observation'.
Definition at line 350 of file SbGeoParameter.H'.
References TZero.
virtual SBMJD SBDerivation::tFinis (const SBMJD & = TZero) const [inline, virtual]"Returns date of the last observation'.
Reimplemented in SBStochParameter'.
Definition at line 326 of file SbGeoParameter.H'.
References TFinis.
Referenced by SBSource::getGlobalParameters4Report(), SBSource::getParameters4Report(), SBParameterLI::key(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBParameterLI::text(), and SBStochParameter::tFinis().
virtual SBMJD SBDerivation::tFinis_aux (const SBMJD & = TZero) const [inline, virtual]"Returns date of the last observation'.
Definition at line 348 of file SbGeoParameter.H'.
References TFinis_aux.
virtual double SBDerivation::tInterval (const SBMJD & = TZero) const [inline, virtual]"Returns interval of the observations'.
Reimplemented in SBStochParameter'.
Definition at line 330 of file SbGeoParameter.H'.
References TStart.
Referenced by SBRunManager::makeReportEOP(), and SBStochParameter::tInterval().
virtual double SBDerivation::tInterval_aux (const SBMJD & = TZero) const [inline, virtual]"Returns interval of the observations'.
Definition at line 352 of file SbGeoParameter.H'.
References TStart_aux.
virtual SBMJD SBDerivation::tStart (const SBMJD & = TZero) const [inline, virtual]"Returns date of the first observation'.
Reimplemented in SBStochParameter'.
Definition at line 324 of file SbGeoParameter.H'.
References TStart.
Referenced by SBSource::getGlobalParameters4Report(), SBSource::getParameters4Report(), SBParameterLI::key(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBParameterLI::text(), and SBStochParameter::tStart().
virtual SBMJD SBDerivation::tStart_aux (const SBMJD & = TZero) const [inline, virtual]"Returns date of the first observation'.
Definition at line 346 of file SbGeoParameter.H'.
References TStart_aux.
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
virtual void SBDerivation::zero () [inline, virtual]
Definition at line 361 of file SbGeoParameter.H'.
Referenced by SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), and SBEstimator::processObs().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream & operator<< (QDataStream &s, const SBDerivation &D) [friend]"Output to the data stream'.
Definition at line 342 of file SbGeoParameter.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
QDataStream & operator>> (QDataStream &s, SBDerivation &D) [friend]"Input from the data stream'.
Definition at line 358 of file SbGeoParameter.C'.
Member Data Documentation
double SBDerivation::D [protected]
value of a derivation;
Definition at line 289 of file SbGeoParameter.H'.
Referenced by clearValues(), clearValues_aux(), d(), operator=(), SBDerivation(), and setD().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
int SBDerivation::Num [protected]
number of points per derivation;
Definition at line 290 of file SbGeoParameter.H'.
Referenced by clearValues(), num(), operator=(), SBDerivation(), setD(), and setTimes().
int SBDerivation::Num_aux [protected]
number of points per derivation;
Definition at line 297 of file SbGeoParameter.H'.
Referenced by clearValues_aux(), invertAux(), num_aux(), operator=(), SBDerivation(), and setD().
int SBDerivation::NumSes [protected]
number of sessions per derivation;
Definition at line 291 of file SbGeoParameter.H'.
Referenced by clearValues(), numSes(), operator=(), SBDerivation(), and setTimes().
SBMJD SBDerivation::TFinis [protected]
MJD of the last measurement;'.
Definition at line 293 of file SbGeoParameter.H'.
Referenced by clearValues(), operator=(), SBDerivation(), setD(), setTimes(), and tFinis().
SBMJD SBDerivation::TFinis_aux [protected]
MJD of the last measurement;'.
Definition at line 299 of file SbGeoParameter.H'.
Referenced by clearValues_aux(), invertAux(), operator=(), SBDerivation(), setD(), and tFinis_aux().
SBMJD SBDerivation::TStart [protected]
MJD of the first measurement;'.
Definition at line 292 of file SbGeoParameter.H'.
Referenced by clearValues(), operator=(), SBDerivation(), setD(), setTimes(), SBStatistics::setTStart(), tInterval(), tStart(), and SBStatistics::tStart().
SBMJD SBDerivation::TStart_aux [protected]
MJD of the first measurement;'.
Definition at line 298 of file SbGeoParameter.H'.
Referenced by clearValues_aux(), invertAux(), operator=(), SBDerivation(), setD(), tInterval_aux(), and tStart_aux().
long double SBDerivation::TSum [protected]
the sum of the epochs of observation;
Definition at line 294 of file SbGeoParameter.H'.
Referenced by clearValues(), operator=(), SBDerivation(), setD(), and setTimes().
long double SBDerivation::TSum_aux [protected]
the sum of the epochs of observation;
Definition at line 300 of file SbGeoParameter.H'.
Referenced by clearValues_aux(), invertAux(), operator=(), SBDerivation(), and setD().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.