SBDelay
NAME
SBDelay -
SYNOPSIS
#include <SbGeoDelay.H>
Public Member Functions
SBDelay (const SBConfig *, SBFrame *, SBEphem *, SBTideLd *, SBRefraction *)
virtual ~SBDelay ()
virtual QString ClassName () const
virtual double cLight () const
virtual double aEarth () const
virtual double gamma () const
virtual double totZenithDelay1 () const
virtual double totZenithDelay2 () const
virtual double totalDelay () const
virtual double calc (SBRunManager *, SBStation *, SBStation *, SBSource *, SBObsVLBIEntry *, SBStationInfo *, SBStationInfo *)
Static Public Attributes
static const double CLight = 299792458.0
speed of light (can be differ from Ephem::CLight)
static const double AEarth = 6378136.6
equatorial radius of the Earth
static const double Gamma = 1.0
a PPN Parameter = 1 in general relativity
Private Member Functions
virtual void calcDerivatives (const SBMJD &)
Private Attributes
const SBConfig * Cfg
SBFrame * Frame
SBEphem * Ephem
SBTideLd * Tide
SBRefraction * Refr
SBRunManager * Mgr
SBStation * St_1
SBStation * St_2
SBSource * So
SBObsVLBIEntry * Obs
SBMJD t1
Vector3 K
the unit vector from the barycenter to the source, CRS
Vector3 x1
geocentric radius vector of the 1st receiver , CRS
Vector3 x2
geocentric radius vector of the 2nd receiver , CRS
Vector3 b
geocentric baseline vector , CRS
Vector3 b_TRS
geocentric baseline vector , TRS
Vector3 X1
barycentric radius vector of the 1st receiver , CRS
Vector3 X2
barycentric radius vector of the 2nd receiver , CRS
Vector3 k1
unit vector from the 1st station to the source, abberated, CRS
Vector3 k2
unit vector from the 2nd station to the source, abberated, CRS
Vector3 k1r
unit vector from the 1st station to the source, abber'.+refr'., TRF
Vector3 k2r
unit vector from the 2nd station to the source, abber'.+refr'., TRF
Vector3 Ve
Vector3 w1
Vector3 w2
double kbc
double DTau_Term_1
double DTau_Term_2
double DTau_Term_3
double GravDelay
double VacuumDelay
double GeomDelay
double TotalDelay
double AntennaDelay
double DTAtm1
double DTAtm2
double TotZenithDelay1
double TotZenithDelay2
Detailed Description
Delay & rate calculations
Definition at line 52 of file SbGeoDelay.H'.
Constructor & Destructor Documentation
SBDelay::SBDelay (const SBConfig *Cfg_, SBFrame *Frame_, SBEphem *Ephem_, SBTideLd *Tide_, SBRefraction *Refr_)"A constructor'.
Definition at line 54 of file SbGeoDelay.C'.
References AntennaDelay, Cfg, DTAtm1, DTAtm2, DTau_Term_1, DTau_Term_2, DTau_Term_3, Ephem, Frame, GeomDelay, GravDelay, kbc, Mgr, Obs, Refr, So, St_1, St_2, Tide, TotalDelay, TotZenithDelay1, TotZenithDelay2, and VacuumDelay.
SBDelay::~SBDelay () [virtual]"A destructor'.
Definition at line 87 of file SbGeoDelay.C'.
Member Function Documentation
virtual double SBDelay::aEarth () const [inline, virtual]"Returns equatorial radius of the Earth
Definition at line 120 of file SbGeoDelay.H'.
References AEarth.
double SBDelay::calc (SBRunManager *Mgr_, SBStation *St_1_, SBStation *St_2_, SBSource *So_, SBObsVLBIEntry *Obs_, SBStationInfo *St_1Info, SBStationInfo *St_2Info) [virtual]
Definition at line 91 of file SbGeoDelay.C'.
References SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), AntennaDelay, SBStationInfo::ArtMeteo, Vector3::at(), SBParametersDesc::atmGrad(), SBRefraction::azimuth(), b, b_TRS, SBStationInfo::BadMeteo, SBEphem::calc(), SBFrame::calc(), calcDerivatives(), Cfg, SBProject::cfg(), ClassName(), Vector3::clear(), CLight, cLight(), SBObsVLBIEntry::correlation(), SBFrame::crs2trs(), DAY2SEC, SBLog::DBG, SBLog::DELAYALL, SBFrame::dQ_dt(), DTAtm1, DTAtm2, DTau_Term_1, DTau_Term_2, DTau_Term_3, Ephem, Frame, SBObsVLBIEntry::fringePhase(), gamma(), GeomDelay, SBRefraction::gradMap(), SBLog::GRAVDELAY, GravDelay, SBConfig::gravHOThreshold(), SBAttributed::isAttr(), SBLog::isEligible(), SBCelestBody::IsGravDelay, SBConfig::isGravDelayHO(), K, k1, k1r, k2, k2r, kbc, Log, SBRefraction::makeDebugReport(), Mgr, SBObservation::mjd(), Vector3::module(), Obs, SBConfig::p(), SBRunManager::prj(), SBParameterCfg::PT_NONE, SBObsVLBIEntry::refFreq(), Refr, SBRefraction::refrSource(), Vector3::report2Log(), SBSource::rt(), SBStation::rt(), So, St_1, St_2, t1, SBTime::TDB(), SBFrame::time(), SBMJD::toString(), TotalDelay, SBRefraction::totZenithDelay(), TotZenithDelay1, TotZenithDelay2, SBParameterCfg::type(), TZero, Vector3::unify(), Vector3::unit(), VacuumDelay, Ve, w1, w2, SBRefraction::wetMap(), SBLog::write(), x1, X1, x2, X2, X_AXIS, Y_AXIS, Z_AXIS, SBParametersDesc::zenith(), and SBStationInfo::zw().
Referenced by SBObsVLBIEntry::process().
void SBDelay::calcDerivatives (const SBMJD &t) [private, virtual]
Definition at line 400 of file SbGeoDelay.C'.
References Vector3::at(), b, b_TRS, SBProject::cfg(), cLight(), SBSource::dn_t(), SBFrame::dQ_deps(), SBFrame::dQ_dpsi(), SBFrame::dQ_dUT(), SBFrame::dQ_dxp(), SBFrame::dQ_dyp(), DTau_Term_1, DTau_Term_2, DTau_Term_3, SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBFrame::eop(), Ephem, SBCatalog::epoch(), Frame, K, kbc, SBParametersDesc::love_h2(), SBParametersDesc::love_l2(), Mgr, SBTime::omega(), SBConfig::p(), SBSource::p_DN(), SBStation::p_DRX(), SBStation::p_DRY(), SBStation::p_DRZ(), SBStation::p_DVX(), SBStation::p_DVY(), SBStation::p_DVZ(), SBEOP::p_Neps(), SBEOP::p_Npsi(), SBEOP::p_Put(), SBEOP::p_Px(), SBEOP::p_Py(), SBSource::p_RA(), SBStation::p_TideH2(), SBStation::p_TideL2(), SBStation::p_TideLag(), SBEOP::p_UT_c1(), SBEOP::p_UT_c10(), SBEOP::p_UT_c2(), SBEOP::p_UT_c3(), SBEOP::p_UT_c4(), SBEOP::p_UT_c5(), SBEOP::p_UT_c6(), SBEOP::p_UT_c7(), SBEOP::p_UT_c8(), SBEOP::p_UT_c9(), SBEOP::p_UT_s1(), SBEOP::p_UT_s10(), SBEOP::p_UT_s2(), SBEOP::p_UT_s3(), SBEOP::p_UT_s4(), SBEOP::p_UT_s5(), SBEOP::p_UT_s6(), SBEOP::p_UT_s7(), SBEOP::p_UT_s8(), SBEOP::p_UT_s9(), SBEOP::p_Xp_m10(), SBEOP::p_Xp_m2(), SBEOP::p_Xp_m3(), SBEOP::p_Xp_m4(), SBEOP::p_Xp_m5(), SBEOP::p_Xp_m6(), SBEOP::p_Xp_m7(), SBEOP::p_Xp_m8(), SBEOP::p_Xp_m9(), SBEOP::p_Xp_p1(), SBEOP::p_Xp_p10(), SBEOP::p_Xp_p2(), SBEOP::p_Xp_p3(), SBEOP::p_Xp_p4(), SBEOP::p_Xp_p5(), SBEOP::p_Xp_p6(), SBEOP::p_Xp_p7(), SBEOP::p_Xp_p8(), SBEOP::p_Xp_p9(), SBEOP::p_Yp_m10(), SBEOP::p_Yp_m2(), SBEOP::p_Yp_m3(), SBEOP::p_Yp_m4(), SBEOP::p_Yp_m5(), SBEOP::p_Yp_m6(), SBEOP::p_Yp_m7(), SBEOP::p_Yp_m8(), SBEOP::p_Yp_m9(), SBEOP::p_Yp_p1(), SBEOP::p_Yp_p10(), SBEOP::p_Yp_p2(), SBEOP::p_Yp_p3(), SBEOP::p_Yp_p4(), SBEOP::p_Yp_p5(), SBEOP::p_Yp_p6(), SBEOP::p_Yp_p7(), SBEOP::p_Yp_p8(), SBEOP::p_Yp_p9(), SBParametersDesc::polusNut(), SBParametersDesc::polusUT(), SBParametersDesc::polusXY(), SBRunManager::prj(), SBParameterCfg::PT_NONE, SBSource::ra_t(), SBDerivation::setD(), So, SBTideLd::solidTideLd(), SBParametersDesc::srcCoo(), St_1, St_2, SBParametersDesc::staCoo(), SBParametersDesc::staVel(), Matrix3::T(), SBParametersDesc::test(), Tide, SBParametersDesc::tideLag(), SBFrame::time(), SBRunManager::trf(), SBParameterCfg::type(), Ve, w2, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by calc().
virtual QString SBDelay::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Definition at line 115 of file SbGeoDelay.H'.
Referenced by calc().
virtual double SBDelay::cLight () const [inline, virtual]"Returns speed of light
Definition at line 118 of file SbGeoDelay.H'.
References CLight.
Referenced by calc(), and calcDerivatives().
virtual double SBDelay::gamma () const [inline, virtual]"Returns a PPN Parameter
Definition at line 122 of file SbGeoDelay.H'.
References Gamma.
Referenced by calc().
virtual double SBDelay::totalDelay () const [inline, virtual]
Definition at line 125 of file SbGeoDelay.H'.
References TotalDelay.
Referenced by SBObsVLBIEntry::process().
virtual double SBDelay::totZenithDelay1 () const [inline, virtual]
Definition at line 123 of file SbGeoDelay.H'.
References TotZenithDelay1.
Referenced by SBObsVLBIEntry::process().
virtual double SBDelay::totZenithDelay2 () const [inline, virtual]
Definition at line 124 of file SbGeoDelay.H'.
References TotZenithDelay2.
Referenced by SBObsVLBIEntry::process().
Member Data Documentation
const double SBDelay::AEarth = 6378136.6 [static]
equatorial radius of the Earth
Definition at line 56 of file SbGeoDelay.H'.
Referenced by aEarth().
double SBDelay::AntennaDelay [private]
Definition at line 100 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
Vector3 SBDelay::b [private]
geocentric baseline vector , CRS
Definition at line 78 of file SbGeoDelay.H'.
Referenced by calc(), and calcDerivatives().
Vector3 SBDelay::b_TRS [private]
geocentric baseline vector , TRS
Definition at line 79 of file SbGeoDelay.H'.
Referenced by calc(), and calcDerivatives().
const SBConfig* SBDelay::Cfg [private]
Definition at line 60 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
const double SBDelay::CLight = 299792458.0 [static]
speed of light (can be differ from Ephem::CLight)
Definition at line 55 of file SbGeoDelay.H'.
Referenced by calc(), cLight(), operator<<(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), and SBVLBIObsLI::text().
double SBDelay::DTAtm1 [private]
Definition at line 101 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
double SBDelay::DTAtm2 [private]
Definition at line 102 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
double SBDelay::DTau_Term_1 [private]
Definition at line 90 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
double SBDelay::DTau_Term_2 [private]
Definition at line 91 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
double SBDelay::DTau_Term_3 [private]
Definition at line 92 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
SBEphem* SBDelay::Ephem [private]
Definition at line 62 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
SBFrame* SBDelay::Frame [private]
Definition at line 61 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
const double SBDelay::Gamma = 1.0 [static]
a PPN Parameter = 1 in general relativity
Definition at line 57 of file SbGeoDelay.H'.
Referenced by gamma().
double SBDelay::GeomDelay [private]
Definition at line 98 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
double SBDelay::GravDelay [private]
Definition at line 96 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
Vector3 SBDelay::K [private]
the unit vector from the barycenter to the source, CRS
Definition at line 75 of file SbGeoDelay.H'.
Referenced by calc(), and calcDerivatives().
Vector3 SBDelay::k1 [private]
unit vector from the 1st station to the source, abberated, CRS
Definition at line 82 of file SbGeoDelay.H'.
Referenced by calc().
Vector3 SBDelay::k1r [private]
unit vector from the 1st station to the source, abber'.+refr'., TRF
Definition at line 84 of file SbGeoDelay.H'.
Referenced by calc().
Vector3 SBDelay::k2 [private]
unit vector from the 2nd station to the source, abberated, CRS
Definition at line 83 of file SbGeoDelay.H'.
Referenced by calc().
Vector3 SBDelay::k2r [private]
unit vector from the 2nd station to the source, abber'.+refr'., TRF
Definition at line 85 of file SbGeoDelay.H'.
Referenced by calc().
double SBDelay::kbc [private]
Definition at line 89 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
SBRunManager* SBDelay::Mgr [private]
Definition at line 67 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
SBObsVLBIEntry* SBDelay::Obs [private]
Definition at line 71 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
SBRefraction* SBDelay::Refr [private]
Definition at line 64 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
SBSource* SBDelay::So [private]
Definition at line 70 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
SBStation* SBDelay::St_1 [private]
Definition at line 68 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
SBStation* SBDelay::St_2 [private]
Definition at line 69 of file SbGeoDelay.H'.
Referenced by calc(), calcDerivatives(), and SBDelay().
SBMJD SBDelay::t1 [private]
Definition at line 74 of file SbGeoDelay.H'.
Referenced by calc().
SBTideLd* SBDelay::Tide [private]
Definition at line 63 of file SbGeoDelay.H'.
Referenced by calcDerivatives(), and SBDelay().
double SBDelay::TotalDelay [private]
Definition at line 99 of file SbGeoDelay.H'.
Referenced by calc(), SBDelay(), and totalDelay().
double SBDelay::TotZenithDelay1 [private]
Definition at line 103 of file SbGeoDelay.H'.
Referenced by calc(), SBDelay(), and totZenithDelay1().
double SBDelay::TotZenithDelay2 [private]
Definition at line 104 of file SbGeoDelay.H'.
Referenced by calc(), SBDelay(), and totZenithDelay2().
double SBDelay::VacuumDelay [private]
Definition at line 97 of file SbGeoDelay.H'.
Referenced by calc(), and SBDelay().
Vector3 SBDelay::Ve [private]
Definition at line 86 of file SbGeoDelay.H'.
Referenced by calc(), and calcDerivatives().
Vector3 SBDelay::w1 [private]
Definition at line 87 of file SbGeoDelay.H'.
Referenced by calc().
Vector3 SBDelay::w2 [private]
Definition at line 88 of file SbGeoDelay.H'.
Referenced by calc(), and calcDerivatives().
Vector3 SBDelay::x1 [private]
geocentric radius vector of the 1st receiver , CRS
Definition at line 76 of file SbGeoDelay.H'.
Referenced by calc().
Vector3 SBDelay::X1 [private]
barycentric radius vector of the 1st receiver , CRS
Definition at line 80 of file SbGeoDelay.H'.
Referenced by calc().
Vector3 SBDelay::x2 [private]
geocentric radius vector of the 2nd receiver , CRS
Definition at line 77 of file SbGeoDelay.H'.
Referenced by calc().
Vector3 SBDelay::X2 [private]
barycentric radius vector of the 2nd receiver , CRS
Definition at line 81 of file SbGeoDelay.H'.
Referenced by calc().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.