.TH "SBDS_dat" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBDS_dat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoObsVLBI\&.H>\fP
.PP
Inherits QDataStream'\&.
.SH "Detailed Description"
.PP 
Definition at line 43 of file SbGeoObsVLBI\&.H'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
