.TH "SBEcc" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBEcc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoStations\&.H>\fP
.PP
Inherits \fBQList< SBStationEcc >\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBEcc\fP ()"
.br
.ti -1c
.RI "\fBSBEcc\fP (const \fBSBEcc\fP &)"
.br
.ti -1c
.RI "virtual \fB~SBEcc\fP ()"
.br
.ti -1c
.RI "QString \fBClassName\fP () const "
.br
.ti -1c
.RI "QDict< \fBSBStationEcc\fP > * \fBeccByID\fP ()"
.br
.ti -1c
.RI "\fBSBEccentricity\fP * \fBfindEcc\fP (const \fBSBStationID\fP &, const \fBSBMJD\fP &)"
.br
.ti -1c
.RI "bool \fBregisterEcc\fP (const \fBSBStationID\fP &, const \fBSBEccentricity\fP &)"
.br
.ti -1c
.RI "bool \fBimportEccDat\fP (const QString &, \fBSB_TRF\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item item1, QCollection::Item item2)"
.br
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item Entry) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &Entry)"
.br
.ti -1c
.RI "void \fBfillDicts\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QDict< \fBSBStationEcc\fP > * \fBEccByID\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBEcc\fP &Ecc)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBEcc\fP &Ecc)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1110 of file SbGeoStations\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBEcc::SBEcc ()"
.PP
Definition at line 2474 of file SbGeoStations\&.C'\&.
.PP
References EccByID\&.
.SS "SBEcc::SBEcc (const \fBSBEcc\fP &Ecc_)"
.PP
Definition at line 2492 of file SbGeoStations\&.C'\&.
.PP
References EccByID, and fillDicts()\&.
.SS "SBEcc::~SBEcc ()\fC [virtual]\fP"
.PP
Definition at line 2483 of file SbGeoStations\&.C'\&.
.PP
References EccByID\&.
.SH "Member Function Documentation"
.PP 
.SS "QString SBEcc::ClassName () const\fC [inline]\fP"
.PP
Definition at line 1134 of file SbGeoStations\&.H'\&.
.PP
Referenced by findEcc(), importEccDat(), and registerEcc()\&.
.SS "virtual int SBEcc::compareItems (QCollection::Itemitem1, QCollection::Itemitem2)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 1113 of file SbGeoStations\&.H'\&.
.SS "QDict<\fBSBStationEcc\fP>* SBEcc::eccByID ()\fC [inline]\fP"
.PP
Definition at line 1138 of file SbGeoStations\&.H'\&.
.PP
References EccByID\&.
.PP
Referenced by sinex_SiteEccentricityBlock()\&.
.SS "void SBEcc::fillDicts ()\fC [protected]\fP"
.PP
Definition at line 2501 of file SbGeoStations\&.C'\&.
.PP
References EccByID\&.
.PP
Referenced by SBEcc()\&.
.SS "\fBSBEccentricity\fP * SBEcc::findEcc (const \fBSBStationID\fP &ID_, const \fBSBMJD\fP &T)"
.PP
Definition at line 2512 of file SbGeoStations\&.C'\&.
.PP
References ClassName(), SBLog::DBG, EccByID, SBStationEcc::findEcc(), Log, SBStation::Pt_Marker, SBStationID::ptType(), SBLog::STATION, SBStationID::toString(), and SBLog::write()\&.
.PP
Referenced by SB_TRF::prepareEccs4Session()\&.
.SS "bool SBEcc::importEccDat (const QString &FileName, \fBSB_TRF\fP *Wtrf)"
.PP
Definition at line 2552 of file SbGeoStations\&.C'\&.
.PP
References SBCatalog::aliasDict(), ClassName(), SBLog::DBG, SBEccentricity::ET_NEU, SBEccentricity::ET_XYZ, SBMJD::F_ECCDAT, SBStation::id(), SBMJD::isGood(), SBStationID::isValidId(), Log, SB_TRF::lookupID(), SB_TRF::lookupStation(), SBNamed::name(), registerEcc(), SBEccentricity::setAka(), SBEccentricity::setEcc(), SBStationID::setID(), SBMJD::setMJD(), SBEccentricity::setTFinis(), SBEccentricity::setTStart(), SBEccentricity::setType(), SBLog::STATION, SBStationID::toString(), SBLog::write(), and SBLog::WRN\&.
.PP
Referenced by SBStuffStationsEcc::importData(), and SBStationImport::loadECCdat()\&.
.SS "virtual QDataStream& SBEcc::read (QDataStream &s, QCollection::Item &Entry)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 1121 of file SbGeoStations\&.H'\&.
.SS "bool SBEcc::registerEcc (const \fBSBStationID\fP &ID, const \fBSBEccentricity\fP &Ecc_)"
.PP
Definition at line 2525 of file SbGeoStations\&.C'\&.
.PP
References ClassName(), SBLog::DATA, SBLog::DBG, SBEccentricity::ecc(), EccByID, Log, SBStation::Pt_Antenna, SBStationID::ptType(), SBStationEcc::registerEcc(), SBStationEcc::setID(), SBLog::STATION, SBStationID::toString(), v3Zero, and SBLog::write()\&.
.PP
Referenced by importEccDat()\&.
.SS "virtual QDataStream& SBEcc::write (QDataStream &s, QCollection::ItemEntry) const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 1119 of file SbGeoStations\&.H'\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBEcc\fP &Ecc)\fC [friend]\fP"
.PP
Definition at line 1149 of file SbGeoStations\&.H'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBEcc\fP &Ecc)\fC [friend]\fP"
.PP
Definition at line 1151 of file SbGeoStations\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "QDict<\fBSBStationEcc\fP>* \fBSBEcc::EccByID\fP\fC [protected]\fP"
.PP
Definition at line 1122 of file SbGeoStations\&.H'\&.
.PP
Referenced by eccByID(), fillDicts(), findEcc(), registerEcc(), SBEcc(), and ~SBEcc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
