SBEcc
NAME
SBEcc -
SYNOPSIS
#include <SbGeoStations.H>
Inherits QList< SBStationEcc >'.
Public Member Functions
SBEcc ()
SBEcc (const SBEcc &)
virtual ~SBEcc ()
QString ClassName () const
QDict< SBStationEcc > * eccByID ()
SBEccentricity * findEcc (const SBStationID &, const SBMJD &)
bool registerEcc (const SBStationID &, const SBEccentricity &)
bool importEccDat (const QString &, SB_TRF *)
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
void fillDicts ()
Protected Attributes
QDict< SBStationEcc > * EccByID
Friends
QDataStream & operator<< (QDataStream &s, const SBEcc &Ecc)
QDataStream & operator>> (QDataStream &s, SBEcc &Ecc)
Detailed Description
Definition at line 1110 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBEcc::SBEcc ()
Definition at line 2474 of file SbGeoStations.C'.
References EccByID.
SBEcc::SBEcc (const SBEcc &Ecc_)
Definition at line 2492 of file SbGeoStations.C'.
References EccByID, and fillDicts().
SBEcc::~SBEcc () [virtual]
Definition at line 2483 of file SbGeoStations.C'.
References EccByID.
Member Function Documentation
QString SBEcc::ClassName () const [inline]
Definition at line 1134 of file SbGeoStations.H'.
Referenced by findEcc(), importEccDat(), and registerEcc().
virtual int SBEcc::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 1113 of file SbGeoStations.H'.
QDict<SBStationEcc>* SBEcc::eccByID () [inline]
Definition at line 1138 of file SbGeoStations.H'.
References EccByID.
Referenced by sinex_SiteEccentricityBlock().
void SBEcc::fillDicts () [protected]
Definition at line 2501 of file SbGeoStations.C'.
References EccByID.
Referenced by SBEcc().
SBEccentricity * SBEcc::findEcc (const SBStationID &ID_, const SBMJD &T)
Definition at line 2512 of file SbGeoStations.C'.
References ClassName(), SBLog::DBG, EccByID, SBStationEcc::findEcc(), Log, SBStation::Pt_Marker, SBStationID::ptType(), SBLog::STATION, SBStationID::toString(), and SBLog::write().
Referenced by SB_TRF::prepareEccs4Session().
bool SBEcc::importEccDat (const QString &FileName, SB_TRF *Wtrf)
Definition at line 2552 of file SbGeoStations.C'.
References SBCatalog::aliasDict(), ClassName(), SBLog::DBG, SBEccentricity::ET_NEU, SBEccentricity::ET_XYZ, SBMJD::F_ECCDAT, SBStation::id(), SBMJD::isGood(), SBStationID::isValidId(), Log, SB_TRF::lookupID(), SB_TRF::lookupStation(), SBNamed::name(), registerEcc(), SBEccentricity::setAka(), SBEccentricity::setEcc(), SBStationID::setID(), SBMJD::setMJD(), SBEccentricity::setTFinis(), SBEccentricity::setTStart(), SBEccentricity::setType(), SBLog::STATION, SBStationID::toString(), SBLog::write(), and SBLog::WRN.
Referenced by SBStuffStationsEcc::importData(), and SBStationImport::loadECCdat().
virtual QDataStream& SBEcc::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 1121 of file SbGeoStations.H'.
bool SBEcc::registerEcc (const SBStationID &ID, const SBEccentricity &Ecc_)
Definition at line 2525 of file SbGeoStations.C'.
References ClassName(), SBLog::DATA, SBLog::DBG, SBEccentricity::ecc(), EccByID, Log, SBStation::Pt_Antenna, SBStationID::ptType(), SBStationEcc::registerEcc(), SBStationEcc::setID(), SBLog::STATION, SBStationID::toString(), v3Zero, and SBLog::write().
Referenced by importEccDat().
virtual QDataStream& SBEcc::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 1119 of file SbGeoStations.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBEcc &Ecc) [friend]
Definition at line 1149 of file SbGeoStations.H'.
QDataStream& operator>> (QDataStream &s, SBEcc &Ecc) [friend]
Definition at line 1151 of file SbGeoStations.H'.
Member Data Documentation
QDict<SBStationEcc>* SBEcc::EccByID [protected]
Definition at line 1122 of file SbGeoStations.H'.
Referenced by eccByID(), fillDicts(), findEcc(), registerEcc(), SBEcc(), and ~SBEcc().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.