SBEccentricity
NAME
SBEccentricity -
SYNOPSIS
#include <SbGeoStations.H>
Public Types
enum EccType { ET_NEU, ET_XYZ }
Public Member Functions
SBEccentricity ()
SBEccentricity (const SBEccentricity &)
SBEccentricity & operator= (const SBEccentricity &)
virtual ~SBEccentricity ()
QString ClassName () const
const QString & aka () const
const SBMJD & tStart () const
const SBMJD & tFinis () const
const Vector3 & ecc () const
EccType type () const
const QString & sessionName () const
void setAka (const QString &Aka_)
void setTStart (const SBMJD &T_)
void setTFinis (const SBMJD &T_)
void setEcc (const Vector3 &V_)
void setType (EccType Type_)
void setSessionName (const QString &SN_)
bool operator< (const SBEccentricity &) const
bool operator== (const SBEccentricity &) const
Private Attributes
QString Aka
aka of a station
SBMJD TStart
first obs with the ecc
SBMJD TFinis
last obs with the ecc
Vector3 Ecc
vector of eccentricity
EccType Type
the type of the Ecc vector
QString SessionName
name of the session
Friends
QDataStream & operator<< (QDataStream &s, const SBEccentricity &Ecc)
QDataStream & operator>> (QDataStream &s, SBEccentricity &Ecc)
Detailed Description
Definition at line 989 of file SbGeoStations.H'.
Member Enumeration Documentation
enum SBEccentricity::EccType
Enumerator:
ET_NEU
ET_XYZ
Definition at line 992 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBEccentricity::SBEccentricity ()
Definition at line 2303 of file SbGeoStations.C'.
References Aka, Ecc, ET_XYZ, SessionName, TFinis, TStart, Type, TZero, and v3Zero.
SBEccentricity::SBEccentricity (const SBEccentricity &Ecc_)
Definition at line 2313 of file SbGeoStations.C'.
virtual SBEccentricity::~SBEccentricity () [inline, virtual]
Definition at line 1008 of file SbGeoStations.H'.
Member Function Documentation
const QString& SBEccentricity::aka () const [inline]
Definition at line 1013 of file SbGeoStations.H'.
References Aka.
Referenced by SBStuffStationsEcc::deleteEntry(), SBEccListItem::key(), operator<(), operator=(), operator==(), SBStationEcc::registerEcc(), and SBEccListItem::text().
QString SBEccentricity::ClassName () const [inline]
Definition at line 1009 of file SbGeoStations.H'.
const Vector3& SBEccentricity::ecc () const [inline]
Definition at line 1016 of file SbGeoStations.H'.
References Ecc.
Referenced by SBEccListItem::key(), operator=(), operator==(), SB_TRF::prepareEccs4Session(), SBStationEcc::registerEcc(), SBEcc::registerEcc(), sinex_SiteEccentricityBlock(), and SBEccListItem::text().
bool SBEccentricity::operator< (const SBEccentricity &Ecc_) const
Definition at line 2340 of file SbGeoStations.C'.
References Aka, aka(), TFinis, tFinis(), TStart, and tStart().
SBEccentricity & SBEccentricity::operator= (const SBEccentricity &Ecc_)
Definition at line 2318 of file SbGeoStations.C'.
References Aka, aka(), Ecc, ecc(), SessionName, sessionName(), TFinis, tFinis(), TStart, tStart(), Type, and type().
bool SBEccentricity::operator== (const SBEccentricity &Ecc_) const
Definition at line 2329 of file SbGeoStations.C'.
References Aka, aka(), Ecc, ecc(), SessionName, sessionName(), TFinis, tFinis(), TStart, tStart(), Type, and type().
const QString& SBEccentricity::sessionName () const [inline]
Definition at line 1018 of file SbGeoStations.H'.
References SessionName.
Referenced by SBEccListItem::key(), operator=(), operator==(), and SBEccListItem::text().
void SBEccentricity::setAka (const QString &Aka_) [inline]
Definition at line 1020 of file SbGeoStations.H'.
References Aka.
Referenced by SBEcc::importEccDat().
void SBEccentricity::setEcc (const Vector3 &V_) [inline]
Definition at line 1023 of file SbGeoStations.H'.
References Ecc.
Referenced by SBEcc::importEccDat().
void SBEccentricity::setSessionName (const QString &SN_) [inline]
Definition at line 1025 of file SbGeoStations.H'.
References SessionName.
void SBEccentricity::setTFinis (const SBMJD &T_) [inline]
Definition at line 1022 of file SbGeoStations.H'.
References TFinis.
Referenced by SBEcc::importEccDat(), and SBStationEcc::registerEcc().
void SBEccentricity::setTStart (const SBMJD &T_) [inline]
Definition at line 1021 of file SbGeoStations.H'.
References TStart.
Referenced by SBEcc::importEccDat(), and SBStationEcc::registerEcc().
void SBEccentricity::setType (EccTypeType_) [inline]
Definition at line 1024 of file SbGeoStations.H'.
References Type.
Referenced by SBEcc::importEccDat().
const SBMJD& SBEccentricity::tFinis () const [inline]
Definition at line 1015 of file SbGeoStations.H'.
References TFinis.
Referenced by SBStuffStationsEcc::deleteEntry(), SBEccListItem::key(), operator<(), operator=(), operator==(), SBStationEcc::registerEcc(), sinex_SiteEccentricityBlock(), and SBEccListItem::text().
const SBMJD& SBEccentricity::tStart () const [inline]
Definition at line 1014 of file SbGeoStations.H'.
References TStart.
Referenced by SBStuffStationsEcc::deleteEntry(), SBEccListItem::key(), operator<(), operator=(), operator==(), SBStationEcc::registerEcc(), sinex_SiteEccentricityBlock(), and SBEccListItem::text().
EccType SBEccentricity::type () const [inline]
Definition at line 1017 of file SbGeoStations.H'.
References Type.
Referenced by SBEccListItem::key(), operator=(), operator==(), SB_TRF::prepareEccs4Session(), SBStationEcc::registerEcc(), sinex_SiteEccentricityBlock(), and SBEccListItem::text().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBEccentricity &Ecc) [friend]
Definition at line 1034 of file SbGeoStations.H'.
QDataStream& operator>> (QDataStream &s, SBEccentricity &Ecc) [friend]
Definition at line 1036 of file SbGeoStations.H'.
Member Data Documentation
QString SBEccentricity::Aka [private]
aka of a station
Definition at line 995 of file SbGeoStations.H'.
Referenced by aka(), operator<(), operator=(), operator==(), SBEccentricity(), and setAka().
Vector3 SBEccentricity::Ecc [private]
vector of eccentricity
Definition at line 998 of file SbGeoStations.H'.
Referenced by ecc(), operator=(), operator==(), SBEccentricity(), and setEcc().
QString SBEccentricity::SessionName [private]
name of the session
Definition at line 1000 of file SbGeoStations.H'.
Referenced by operator=(), operator==(), SBEccentricity(), sessionName(), and setSessionName().
SBMJD SBEccentricity::TFinis [private]
last obs with the ecc
Definition at line 997 of file SbGeoStations.H'.
Referenced by operator<(), operator=(), operator==(), SBEccentricity(), setTFinis(), and tFinis().
SBMJD SBEccentricity::TStart [private]
first obs with the ecc
Definition at line 996 of file SbGeoStations.H'.
Referenced by operator<(), operator=(), operator==(), SBEccentricity(), setTStart(), and tStart().
EccType SBEccentricity::Type [private]
the type of the Ecc vector
Definition at line 999 of file SbGeoStations.H'.
Referenced by operator=(), operator==(), SBEccentricity(), setType(), and type().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.