SBEccListItem
NAME
SBEccListItem -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QListViewItem'.
Public Member Functions
SBEccListItem (QListView *, SBStationEcc *, SBEccentricity *)
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
SBStationEcc * stEcc ()
SBEccentricity * ecc ()
Private Attributes
SBStationEcc * StEcc
SBEccentricity * Ecc
Detailed Description
Definition at line 108 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBEccListItem::SBEccListItem (QListView *parent_, SBStationEcc *StEcc_, SBEccentricity *Ecc_)
Definition at line 298 of file SbIStuffStation.C'.
References Ecc, and StEcc.
Member Function Documentation
virtual QString SBEccListItem::ClassName () const [inline, virtual]
Definition at line 115 of file SbIStuffStation.H'.
SBEccentricity* SBEccListItem::ecc () [inline]
Definition at line 120 of file SbIStuffStation.H'.
References Ecc.
Referenced by SBStuffStationsEcc::deleteEntry().
QString SBEccListItem::key (intcol, bool) const [virtual]
Definition at line 334 of file SbIStuffStation.C'.
References SBEccentricity::aka(), Vector3::at(), Ecc, SBEccentricity::ecc(), SBEccentricity::ET_NEU, SBMJD::F_INTERNAL, SBEccentricity::sessionName(), StEcc, SBEccentricity::tFinis(), TmpString, SBMJD::toString(), SBStationID::toString(), SBEccentricity::tStart(), SBEccentricity::type(), X_AXIS, Y_AXIS, and Z_AXIS.
SBStationEcc* SBEccListItem::stEcc () [inline]
Definition at line 119 of file SbIStuffStation.H'.
References StEcc.
Referenced by SBStuffStationsEcc::deleteEntry().
QString SBEccListItem::text (intcol) const [virtual]
Definition at line 305 of file SbIStuffStation.C'.
References SBEccentricity::aka(), Vector3::at(), Ecc, SBEccentricity::ecc(), SBEccentricity::ET_NEU, SBMJD::F_DateShort, SBEccentricity::sessionName(), StEcc, SBEccentricity::tFinis(), TmpString, SBMJD::toString(), SBStationID::toString(), SBEccentricity::tStart(), SBEccentricity::type(), X_AXIS, Y_AXIS, and Z_AXIS.
Member Data Documentation
SBEccentricity* SBEccListItem::Ecc [private]
Definition at line 112 of file SbIStuffStation.H'.
Referenced by ecc(), key(), SBEccListItem(), and text().
SBStationEcc* SBEccListItem::StEcc [private]
Definition at line 111 of file SbIStuffStation.H'.
Referenced by key(), SBEccListItem(), stEcc(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.