SBEOPListItem
NAME
SBEOPListItem -
SYNOPSIS
#include <SbIStuff.H>
Inherits QListViewItem'.
Public Member Functions
SBEOPListItem (QListView *, SBEOPEntry *)
virtual QString ClassName () const
virtual QString text (int) const
QString key (int, bool) const
Private Attributes
SBEOPEntry * EOPEntry
Friends
class SBStuffEOPs
Detailed Description
Definition at line 51 of file SbIStuff.H'.
Constructor & Destructor Documentation
SBEOPListItem::SBEOPListItem (QListView *parent, SBEOPEntry *EOPEntry_)
Definition at line 59 of file SbIStuff.C'.
References EOPEntry.
Member Function Documentation
virtual QString SBEOPListItem::ClassName () const [inline, virtual]
Definition at line 57 of file SbIStuff.H'.
QString SBEOPListItem::key (intcol, bool) const
Definition at line 90 of file SbIStuff.C'.
References EOPEntry, SBEOPEntry::eps(), SBEOPEntry::lod(), SBEOPEntry::psi(), text(), TmpString, SBEOPEntry::ut(), SBEOPEntry::xp(), and SBEOPEntry::yp().
QString SBEOPListItem::text (intcol) const [virtual]
Definition at line 66 of file SbIStuff.C'.
References EOPEntry, and TmpString.
Referenced by key().
Friends And Related Function Documentation
friend class SBStuffEOPs [friend]
Definition at line 60 of file SbIStuff.H'.
Member Data Documentation
SBEOPEntry* SBEOPListItem::EOPEntry [private]
Definition at line 54 of file SbIStuff.H'.
Referenced by key(), SBEOPListItem(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.