SBEOP
NAME
SBEOP -
SYNOPSIS
#include <SbGeoEop.H>
Inherits QList< SBEOPEntry >'.
Public Member Functions
SBEOP ()
virtual ~SBEOP ()
virtual QString ClassName () const
void setLabel (const SBSolutionName &Label_)
void setEpoch (const SBMJD &Epoch_)
void setPtNum (unsigned int)
void setMgr (SBRunManager *Mgr_)
SBMatrix * cache4Interpolation ()
const SBSolutionName & label () const
SBMJD epoch () const
SBMJD tStart () const
SBMJD tFinis () const
unsigned int ptNum () const
SBRunManager * mgr () const
double xp () const
double xps () const
double yp () const
double yps () const
double ut () const
double uts () const
double psi () const
double psis () const
double eps () const
double epss () const
bool utHasHiTide () const
bool utHasLoTide () const
SBParameter * p_Px ()
SBParameter * p_Py ()
SBParameter * p_Put ()
SBParameter * p_Npsi ()
SBParameter * p_Neps ()
SBParameter * p_Xp_m2 ()
SBParameter * p_Yp_m2 ()
SBParameter * p_Xp_m1 ()
SBParameter * p_Yp_m1 ()
SBParameter * p_Xp_p2 ()
SBParameter * p_Yp_p2 ()
SBParameter * p_Xp_p1 ()
SBParameter * p_Yp_p1 ()
SBParameter * p_Xp_m3 ()
SBParameter * p_Yp_m3 ()
SBParameter * p_Xp_p3 ()
SBParameter * p_Yp_p3 ()
SBParameter * p_Xp_m4 ()
SBParameter * p_Yp_m4 ()
SBParameter * p_Xp_p4 ()
SBParameter * p_Yp_p4 ()
SBParameter * p_UT_c1 ()
SBParameter * p_UT_s1 ()
SBParameter * p_UT_c2 ()
SBParameter * p_UT_s2 ()
SBParameter * p_UT_c3 ()
SBParameter * p_UT_s3 ()
SBParameter * p_UT_c4 ()
SBParameter * p_UT_s4 ()
SBParameter * p_Xp_m5 ()
SBParameter * p_Yp_m5 ()
SBParameter * p_Xp_p5 ()
SBParameter * p_Yp_p5 ()
SBParameter * p_UT_c5 ()
SBParameter * p_UT_s5 ()
SBParameter * p_Xp_m6 ()
SBParameter * p_Yp_m6 ()
SBParameter * p_Xp_p6 ()
SBParameter * p_Yp_p6 ()
SBParameter * p_UT_c6 ()
SBParameter * p_UT_s6 ()
SBParameter * p_Xp_m7 ()
SBParameter * p_Yp_m7 ()
SBParameter * p_Xp_p7 ()
SBParameter * p_Yp_p7 ()
SBParameter * p_UT_c7 ()
SBParameter * p_UT_s7 ()
SBParameter * p_Xp_m8 ()
SBParameter * p_Yp_m8 ()
SBParameter * p_Xp_p8 ()
SBParameter * p_Yp_p8 ()
SBParameter * p_UT_c8 ()
SBParameter * p_UT_s8 ()
SBParameter * p_Xp_m9 ()
SBParameter * p_Yp_m9 ()
SBParameter * p_Xp_p9 ()
SBParameter * p_Yp_p9 ()
SBParameter * p_UT_c9 ()
SBParameter * p_UT_s9 ()
SBParameter * p_Xp_m10 ()
SBParameter * p_Yp_m10 ()
SBParameter * p_Xp_p10 ()
SBParameter * p_Yp_p10 ()
SBParameter * p_UT_c10 ()
SBParameter * p_UT_s10 ()
void setXp (double Xp_)
void setXps (double Xps_)
void setYp (double Yp_)
void setYps (double Yps_)
void setUt (double UT_)
void setUts (double UTs_)
void setPsi (double Psi_)
void setPsis (double Psis_)
void setEps (double Eps_)
void setEpss (double Epss_)
void setUtHasHiTide (bool UTHasHiTide_)
void setUtHasLoTide (bool UTHasLoTide_)
virtual void importSeries (QString)
void interpolateEOPs (const SBMJD &)
void prepare4Date (const SBMJD &)
const SBMJD & t_4Prepare () const
void createParameters ()
void releaseParameters ()
void updateParameters (SBRunManager *, const SBMJD &)
virtual double dX (const SBMJD &T) const
virtual double dY (const SBMJD &T) const
virtual double dUT1_UTC (const SBMJD &T) const
virtual double dLOD (const SBMJD &T) const
virtual double dPsi (const SBMJD &T) const
virtual double dEps (const SBMJD &T) const
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Private Member Functions
virtual void checkRanges ()
Private Attributes
SBSolutionName Label
SBMJD Epoch
SBMJD TStart
SBMJD TFinis
double Xp
double Xps
double Yp
double Yps
double UT
double UTs
double Psi
double Psis
double Eps
double Epss
bool UTHasHiTide
bool UTHasLoTide
unsigned int PtNum
SBMatrix * Cache
SBSpline * Spliner
unsigned int Idx
bool IsOK
SBMJD T_4Prepare
SBMJD T_4Spline
double EOP_X
double EOP_Y
double EOP_UT
double EOP_LOD
double EOP_Psi
double EOP_Eps
bool HasLeapSecond
SBMJD T_LeapSecond
int SLSign
SBRunManager * Mgr
SBParameter * P_Px
estimation of the X-polar coordinate;
SBParameter * P_Py
estimation of the Y-polar coordinate;
SBParameter * P_Put
estimation of the UT;
SBParameter * P_Npsi
estimation of the Nutation angle Psi;
SBParameter * P_Neps
estimation of the Nutation angle Eps;
SBParameter * P_Xp_m2
SBParameter * P_Yp_m2
SBParameter * P_Xp_m1
SBParameter * P_Yp_m1
SBParameter * P_Xp_p1
SBParameter * P_Yp_p1
SBParameter * P_Xp_p2
SBParameter * P_Yp_p2
SBParameter * P_Xp_m3
SBParameter * P_Yp_m3
SBParameter * P_Xp_p3
SBParameter * P_Yp_p3
SBParameter * P_Xp_m4
SBParameter * P_Yp_m4
SBParameter * P_Xp_p4
SBParameter * P_Yp_p4
SBParameter * P_UT_c1
SBParameter * P_UT_s1
SBParameter * P_UT_c2
SBParameter * P_UT_s2
SBParameter * P_UT_c3
SBParameter * P_UT_s3
SBParameter * P_UT_c4
SBParameter * P_UT_s4
SBParameter * P_Xp_m5
SBParameter * P_Yp_m5
SBParameter * P_Xp_p5
SBParameter * P_Yp_p5
SBParameter * P_UT_c5
SBParameter * P_UT_s5
SBParameter * P_Xp_m6
SBParameter * P_Yp_m6
SBParameter * P_Xp_p6
SBParameter * P_Yp_p6
SBParameter * P_UT_c6
SBParameter * P_UT_s6
SBParameter * P_Xp_m7
SBParameter * P_Yp_m7
SBParameter * P_Xp_p7
SBParameter * P_Yp_p7
SBParameter * P_UT_c7
SBParameter * P_UT_s7
SBParameter * P_Xp_m8
SBParameter * P_Yp_m8
SBParameter * P_Xp_p8
SBParameter * P_Yp_p8
SBParameter * P_UT_c8
SBParameter * P_UT_s8
SBParameter * P_Xp_m9
SBParameter * P_Yp_m9
SBParameter * P_Xp_p9
SBParameter * P_Yp_p9
SBParameter * P_UT_c9
SBParameter * P_UT_s9
SBParameter * P_Xp_m10
SBParameter * P_Yp_m10
SBParameter * P_Xp_p10
SBParameter * P_Yp_p10
SBParameter * P_UT_c10
SBParameter * P_UT_s10
Friends
QDataStream & operator<< (QDataStream &, const SBEOP &)
QDataStream & operator>> (QDataStream &, SBEOP &)
QTextStream & operator<< (QTextStream &, const SBEOP &)
QTextStream & operator>> (QTextStream &, SBEOP &)
Detailed Description
Definition at line 123 of file SbGeoEop.H'.
Constructor & Destructor Documentation
SBEOP::SBEOP ()
Definition at line 99 of file SbGeoEop.C'.
References Cache, EOP_Eps, EOP_LOD, EOP_Psi, EOP_UT, EOP_X, EOP_Y, Epoch, Eps, Epss, HasLeapSecond, Idx, IsOK, Label, Mgr, P_Neps, P_Npsi, P_Put, P_Px, P_Py, P_UT_c1, P_UT_c10, P_UT_c2, P_UT_c3, P_UT_c4, P_UT_c5, P_UT_c6, P_UT_c7, P_UT_c8, P_UT_c9, P_UT_s1, P_UT_s10, P_UT_s2, P_UT_s3, P_UT_s4, P_UT_s5, P_UT_s6, P_UT_s7, P_UT_s8, P_UT_s9, P_Xp_m1, P_Xp_m10, P_Xp_m2, P_Xp_m3, P_Xp_m4, P_Xp_m5, P_Xp_m6, P_Xp_m7, P_Xp_m8, P_Xp_m9, P_Xp_p1, P_Xp_p10, P_Xp_p2, P_Xp_p3, P_Xp_p4, P_Xp_p5, P_Xp_p6, P_Xp_p7, P_Xp_p8, P_Xp_p9, P_Yp_m1, P_Yp_m10, P_Yp_m2, P_Yp_m3, P_Yp_m4, P_Yp_m5, P_Yp_m6, P_Yp_m7, P_Yp_m8, P_Yp_m9, P_Yp_p1, P_Yp_p10, P_Yp_p2, P_Yp_p3, P_Yp_p4, P_Yp_p5, P_Yp_p6, P_Yp_p7, P_Yp_p8, P_Yp_p9, Psi, Psis, PtNum, SBSolutionName::setAttr(), SLSign, Spliner, T_4Prepare, T_4Spline, T_LeapSecond, TECH_UNKN, TFinis, TStart, SBSolutionName::TYPE_EOP, TZero, UT, UTHasHiTide, UTHasLoTide, UTs, Xp, Xps, Yp, and Yps.
SBEOP::~SBEOP () [virtual]
Definition at line 220 of file SbGeoEop.C'.
References Cache, and Spliner.
Member Function Documentation
SBMatrix* SBEOP::cache4Interpolation () [inline]
Definition at line 270 of file SbGeoEop.H'.
References Cache.
Referenced by SBTestEOP::fillData4Plotting().
void SBEOP::checkRanges () [private, virtual]
Definition at line 234 of file SbGeoEop.C'.
References ClassName(), SBMJD::F_DateShort, Label, Log, SBLog::PINTERP, TFinis, SBMJD::toString(), SBSolutionName::toString(), TStart, SBLog::write(), and SBLog::WRN.
Referenced by importSeries(), and operator>>().
virtual QString SBEOP::ClassName () const [inline, virtual]
Definition at line 261 of file SbGeoEop.H'.
Referenced by checkRanges(), dEps(), dLOD(), dPsi(), dUT1_UTC(), dX(), dY(), importSeries(), interpolateEOPs(), and prepare4Date().
virtual int SBEOP::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 126 of file SbGeoEop.H'.
void SBEOP::createParameters ()
Definition at line 808 of file SbGeoEop.C'.
References P_Neps, P_Npsi, P_Put, P_Px, P_Py, P_UT_c1, P_UT_c10, P_UT_c2, P_UT_c3, P_UT_c4, P_UT_c5, P_UT_c6, P_UT_c7, P_UT_c8, P_UT_c9, P_UT_s1, P_UT_s10, P_UT_s2, P_UT_s3, P_UT_s4, P_UT_s5, P_UT_s6, P_UT_s7, P_UT_s8, P_UT_s9, P_Xp_m1, P_Xp_m10, P_Xp_m2, P_Xp_m3, P_Xp_m4, P_Xp_m5, P_Xp_m6, P_Xp_m7, P_Xp_m8, P_Xp_m9, P_Xp_p1, P_Xp_p10, P_Xp_p2, P_Xp_p3, P_Xp_p4, P_Xp_p5, P_Xp_p6, P_Xp_p7, P_Xp_p8, P_Xp_p9, P_Yp_m1, P_Yp_m10, P_Yp_m2, P_Yp_m3, P_Yp_m4, P_Yp_m5, P_Yp_m6, P_Yp_m7, P_Yp_m8, P_Yp_m9, P_Yp_p1, P_Yp_p10, P_Yp_p2, P_Yp_p3, P_Yp_p4, P_Yp_p5, P_Yp_p6, P_Yp_p7, P_Yp_p8, and P_Yp_p9.
Referenced by SBRunManager::SBRunManager().
double SBEOP::dEps (const SBMJD &T) const [virtual]"returns interpolated value of dEps in rads'.
Definition at line 799 of file SbGeoEop.C'.
References ClassName(), EOP_Eps, Log, SBLog::PINTERP, T_4Spline, SBMJD::toString(), SBLog::write(), and SBLog::WRN.
Referenced by SBTestEOP::fillData4Plotting(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPrecNutNRO::operator()().
double SBEOP::dLOD (const SBMJD &T) const [virtual]"returns interpolated value of LOD in days'.
Definition at line 783 of file SbGeoEop.C'.
References ClassName(), EOP_LOD, Log, SBLog::PINTERP, T_4Spline, SBMJD::toString(), SBLog::write(), and SBLog::WRN.
Referenced by SBTestEOP::fillData4Plotting().
double SBEOP::dPsi (const SBMJD &T) const [virtual]"returns interpolated value of dPsi in rads'.
Definition at line 791 of file SbGeoEop.C'.
References ClassName(), EOP_Psi, Log, SBLog::PINTERP, T_4Spline, SBMJD::toString(), SBLog::write(), and SBLog::WRN.
Referenced by SBTestEOP::fillData4Plotting(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPrecNutNRO::operator()().
double SBEOP::dUT1_UTC (const SBMJD &T) const [virtual]"returns interpolated value of d(UT1-UTC) in days'.
Definition at line 750 of file SbGeoEop.C'.
References ClassName(), EOP_UT, SBRunManager::frame(), Log, Mgr, SBTime::omega(), P_UT_c1, P_UT_c10, P_UT_c2, P_UT_c3, P_UT_c4, P_UT_c5, P_UT_c6, P_UT_c7, P_UT_c8, P_UT_c9, P_UT_s1, P_UT_s10, P_UT_s2, P_UT_s3, P_UT_s4, P_UT_s5, P_UT_s6, P_UT_s7, P_UT_s8, P_UT_s9, SBLog::PINTERP, T_4Spline, SBFrame::time(), SBMJD::toString(), SBParameter::v(), SBLog::write(), and SBLog::WRN.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), SBTestEOP::fillData4Plotting(), and SBTime::setUTC().
double SBEOP::dX (const SBMJD &T) const [virtual]"returns interpolated value of dXp in rads'.
Definition at line 661 of file SbGeoEop.C'.
References ClassName(), EOP_X, SBRunManager::frame(), Log, Mgr, SBTime::omega(), P_Xp_m1, P_Xp_m10, P_Xp_m2, P_Xp_m3, P_Xp_m4, P_Xp_m5, P_Xp_m6, P_Xp_m7, P_Xp_m8, P_Xp_m9, P_Xp_p1, P_Xp_p10, P_Xp_p2, P_Xp_p3, P_Xp_p4, P_Xp_p5, P_Xp_p6, P_Xp_p7, P_Xp_p8, P_Xp_p9, P_Yp_m1, P_Yp_m10, P_Yp_m2, P_Yp_m3, P_Yp_m4, P_Yp_m5, P_Yp_m6, P_Yp_m7, P_Yp_m8, P_Yp_m9, P_Yp_p1, P_Yp_p10, P_Yp_p2, P_Yp_p3, P_Yp_p4, P_Yp_p5, P_Yp_p6, P_Yp_p7, P_Yp_p8, P_Yp_p9, SBLog::PINTERP, T_4Spline, SBFrame::time(), SBMJD::toString(), SBParameter::v(), SBLog::write(), and SBLog::WRN.
Referenced by SBTestEOP::fillData4Plotting(), SBPolarTideLd::operator()(), SBPolus::operator()(), and SBPolusNRO::operator()().
double SBEOP::dY (const SBMJD &T) const [virtual]"returns interpolated value of dYp in rads'.
Definition at line 706 of file SbGeoEop.C'.
References ClassName(), EOP_Y, SBRunManager::frame(), Log, Mgr, SBTime::omega(), P_Xp_m1, P_Xp_m10, P_Xp_m2, P_Xp_m3, P_Xp_m4, P_Xp_m5, P_Xp_m6, P_Xp_m7, P_Xp_m8, P_Xp_m9, P_Xp_p1, P_Xp_p10, P_Xp_p2, P_Xp_p3, P_Xp_p4, P_Xp_p5, P_Xp_p6, P_Xp_p7, P_Xp_p8, P_Xp_p9, P_Yp_m1, P_Yp_m10, P_Yp_m2, P_Yp_m3, P_Yp_m4, P_Yp_m5, P_Yp_m6, P_Yp_m7, P_Yp_m8, P_Yp_m9, P_Yp_p1, P_Yp_p10, P_Yp_p2, P_Yp_p3, P_Yp_p4, P_Yp_p5, P_Yp_p6, P_Yp_p7, P_Yp_p8, P_Yp_p9, SBLog::PINTERP, T_4Spline, SBFrame::time(), SBMJD::toString(), SBParameter::v(), SBLog::write(), and SBLog::WRN.
Referenced by SBTestEOP::fillData4Plotting(), SBPolarTideLd::operator()(), SBPolus::operator()(), and SBPolusNRO::operator()().
SBMJD SBEOP::epoch () const [inline]
Definition at line 273 of file SbGeoEop.H'.
References Epoch.
Referenced by SBStuffEOPs::accept().
double SBEOP::eps () const [inline]
Definition at line 287 of file SbGeoEop.H'.
References Eps.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
double SBEOP::epss () const [inline]
Definition at line 288 of file SbGeoEop.H'.
References Epss.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
void SBEOP::importSeries (QStringFile) [virtual]
Definition at line 253 of file SbGeoEop.C'.
References checkRanges(), ClassName(), SBLog::DATA, SBLog::DBG, SBEOPEntry::Eps, IsOK, SBEOPEntry::LOD, Log, SBEOPEntry::Psi, SBEOPEntry::UT, SBLog::write(), SBLog::WRN, SBEOPEntry::Xp, and SBEOPEntry::Yp.
Referenced by SBStuffEOPs::import().
void SBEOP::interpolateEOPs (const SBMJD &T)
Definition at line 567 of file SbGeoEop.C'.
References SBMatrix::at(), Cache, SBProject::cfg(), ClassName(), Config, DAY2SEC, SBLog::DBG, EOP_Eps, EOP_LOD, EOP_Psi, EOP_UT, EOP_X, EOP_Y, SBMJD::F_DateShort, HasLeapSecond, SBLog::isEligible(), SBConfig::isEOP_IAU2K_XY(), IsOK, Log, Mgr, SBConfig::NM_IAU1980, SBConfig::nutModel(), P_Neps, P_Npsi, P_Put, P_Px, P_Py, SBLog::PINTERP, SBRunManager::prj(), PtNum, SEC2RAD, SLSign, SBSpline::spline(), Spliner, T_4Spline, T_LeapSecond, SBMJD::toString(), updateParameters(), SBParameter::v(), SBLog::write(), and SBLog::WRN.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), SBTestNutation::createWidget4Test(), SBTestEOP::fillData4Plotting(), and SBTestNutation::recalc().
const SBSolutionName& SBEOP::label () const [inline]
Definition at line 272 of file SbGeoEop.H'.
References Label.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createInfoGroup(), SBStuffEOPs::draw(), operator<<(), SBTestEOP::SBTestEOP(), and writeNormalEquationSystem().
SBRunManager* SBEOP::mgr () const [inline]
Definition at line 277 of file SbGeoEop.H'.
References Mgr.
SBParameter* SBEOP::p_Neps () [inline]
Definition at line 295 of file SbGeoEop.H'.
References P_Neps.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::makeReportEOP().
SBParameter* SBEOP::p_Npsi () [inline]
Definition at line 294 of file SbGeoEop.H'.
References P_Npsi.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::makeReportEOP().
SBParameter* SBEOP::p_Put () [inline]
Definition at line 293 of file SbGeoEop.H'.
References P_Put.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::makeReportEOP().
SBParameter* SBEOP::p_Px () [inline]
Definition at line 291 of file SbGeoEop.H'.
References P_Px.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::makeReportEOP().
SBParameter* SBEOP::p_Py () [inline]
Definition at line 292 of file SbGeoEop.H'.
References P_Py.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::makeReportEOP().
SBParameter* SBEOP::p_UT_c1 () [inline]
Definition at line 317 of file SbGeoEop.H'.
References P_UT_c1.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c10 () [inline]
Definition at line 366 of file SbGeoEop.H'.
References P_UT_c10.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c2 () [inline]
Definition at line 319 of file SbGeoEop.H'.
References P_UT_c2.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c3 () [inline]
Definition at line 321 of file SbGeoEop.H'.
References P_UT_c3.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c4 () [inline]
Definition at line 323 of file SbGeoEop.H'.
References P_UT_c4.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c5 () [inline]
Definition at line 331 of file SbGeoEop.H'.
References P_UT_c5.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c6 () [inline]
Definition at line 338 of file SbGeoEop.H'.
References P_UT_c6.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c7 () [inline]
Definition at line 345 of file SbGeoEop.H'.
References P_UT_c7.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c8 () [inline]
Definition at line 352 of file SbGeoEop.H'.
References P_UT_c8.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_c9 () [inline]
Definition at line 359 of file SbGeoEop.H'.
References P_UT_c9.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s1 () [inline]
Definition at line 318 of file SbGeoEop.H'.
References P_UT_s1.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s10 () [inline]
Definition at line 367 of file SbGeoEop.H'.
References P_UT_s10.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s2 () [inline]
Definition at line 320 of file SbGeoEop.H'.
References P_UT_s2.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s3 () [inline]
Definition at line 322 of file SbGeoEop.H'.
References P_UT_s3.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s4 () [inline]
Definition at line 324 of file SbGeoEop.H'.
References P_UT_s4.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s5 () [inline]
Definition at line 332 of file SbGeoEop.H'.
References P_UT_s5.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s6 () [inline]
Definition at line 339 of file SbGeoEop.H'.
References P_UT_s6.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s7 () [inline]
Definition at line 346 of file SbGeoEop.H'.
References P_UT_s7.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s8 () [inline]
Definition at line 353 of file SbGeoEop.H'.
References P_UT_s8.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_UT_s9 () [inline]
Definition at line 360 of file SbGeoEop.H'.
References P_UT_s9.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m1 () [inline]
Definition at line 300 of file SbGeoEop.H'.
References P_Xp_m1.
SBParameter* SBEOP::p_Xp_m10 () [inline]
Definition at line 362 of file SbGeoEop.H'.
References P_Xp_m10.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m2 () [inline]
Definition at line 298 of file SbGeoEop.H'.
References P_Xp_m2.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m3 () [inline]
Definition at line 308 of file SbGeoEop.H'.
References P_Xp_m3.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m4 () [inline]
Definition at line 312 of file SbGeoEop.H'.
References P_Xp_m4.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m5 () [inline]
Definition at line 327 of file SbGeoEop.H'.
References P_Xp_m5.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m6 () [inline]
Definition at line 334 of file SbGeoEop.H'.
References P_Xp_m6.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m7 () [inline]
Definition at line 341 of file SbGeoEop.H'.
References P_Xp_m7.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m8 () [inline]
Definition at line 348 of file SbGeoEop.H'.
References P_Xp_m8.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_m9 () [inline]
Definition at line 355 of file SbGeoEop.H'.
References P_Xp_m9.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p1 () [inline]
Definition at line 304 of file SbGeoEop.H'.
References P_Xp_p1.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p10 () [inline]
Definition at line 364 of file SbGeoEop.H'.
References P_Xp_p10.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p2 () [inline]
Definition at line 302 of file SbGeoEop.H'.
References P_Xp_p2.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p3 () [inline]
Definition at line 310 of file SbGeoEop.H'.
References P_Xp_p3.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p4 () [inline]
Definition at line 314 of file SbGeoEop.H'.
References P_Xp_p4.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p5 () [inline]
Definition at line 329 of file SbGeoEop.H'.
References P_Xp_p5.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p6 () [inline]
Definition at line 336 of file SbGeoEop.H'.
References P_Xp_p6.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p7 () [inline]
Definition at line 343 of file SbGeoEop.H'.
References P_Xp_p7.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p8 () [inline]
Definition at line 350 of file SbGeoEop.H'.
References P_Xp_p8.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Xp_p9 () [inline]
Definition at line 357 of file SbGeoEop.H'.
References P_Xp_p9.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m1 () [inline]
Definition at line 301 of file SbGeoEop.H'.
References P_Yp_m1.
SBParameter* SBEOP::p_Yp_m10 () [inline]
Definition at line 363 of file SbGeoEop.H'.
References P_Yp_m10.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m2 () [inline]
Definition at line 299 of file SbGeoEop.H'.
References P_Yp_m2.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m3 () [inline]
Definition at line 309 of file SbGeoEop.H'.
References P_Yp_m3.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m4 () [inline]
Definition at line 313 of file SbGeoEop.H'.
References P_Yp_m4.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m5 () [inline]
Definition at line 328 of file SbGeoEop.H'.
References P_Yp_m5.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m6 () [inline]
Definition at line 335 of file SbGeoEop.H'.
References P_Yp_m6.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m7 () [inline]
Definition at line 342 of file SbGeoEop.H'.
References P_Yp_m7.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m8 () [inline]
Definition at line 349 of file SbGeoEop.H'.
References P_Yp_m8.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_m9 () [inline]
Definition at line 356 of file SbGeoEop.H'.
References P_Yp_m9.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p1 () [inline]
Definition at line 305 of file SbGeoEop.H'.
References P_Yp_p1.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p10 () [inline]
Definition at line 365 of file SbGeoEop.H'.
References P_Yp_p10.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p2 () [inline]
Definition at line 303 of file SbGeoEop.H'.
References P_Yp_p2.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p3 () [inline]
Definition at line 311 of file SbGeoEop.H'.
References P_Yp_p3.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p4 () [inline]
Definition at line 315 of file SbGeoEop.H'.
References P_Yp_p4.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p5 () [inline]
Definition at line 330 of file SbGeoEop.H'.
References P_Yp_p5.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p6 () [inline]
Definition at line 337 of file SbGeoEop.H'.
References P_Yp_p6.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p7 () [inline]
Definition at line 344 of file SbGeoEop.H'.
References P_Yp_p7.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p8 () [inline]
Definition at line 351 of file SbGeoEop.H'.
References P_Yp_p8.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
SBParameter* SBEOP::p_Yp_p9 () [inline]
Definition at line 358 of file SbGeoEop.H'.
References P_Yp_p9.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
void SBEOP::prepare4Date (const SBMJD &T)
Definition at line 436 of file SbGeoEop.C'.
References SBMatrix::at(), SBSpline::b(), Cache, ClassName(), SBLog::DBG, SBEOPEntry::eps(), SBMJD::F_DateShort, SBMJD::F_Short, HasLeapSecond, Idx, IsOK, SBEOPEntry::lod(), Log, SBLog::PINTERP, SBSpline::prepare4Spline(), SBEOPEntry::psi(), PtNum, SBMatrix::set(), SLSign, Spliner, T_4Prepare, T_LeapSecond, TFinis, SBMJD::toString(), TStart, SBEOPEntry::ut(), SBLog::write(), SBLog::WRN, SBEOPEntry::xp(), and SBEOPEntry::yp().
Referenced by collectListOfSINEXParameters4NEQ(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBRunManager::makeReportEOP(), SBRunManager::process_m1(), SBTestNutation::recalc(), SBTestFrame::recalc(), and SBTestEphem::recalc().
double SBEOP::psi () const [inline]
Definition at line 285 of file SbGeoEop.H'.
References Psi.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
double SBEOP::psis () const [inline]
Definition at line 286 of file SbGeoEop.H'.
References Psis.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
unsigned int SBEOP::ptNum () const [inline]
Definition at line 276 of file SbGeoEop.H'.
References PtNum.
virtual QDataStream& SBEOP::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 131 of file SbGeoEop.H'.
void SBEOP::releaseParameters ()
Definition at line 928 of file SbGeoEop.C'.
References P_Neps, P_Npsi, P_Put, P_Px, P_Py, P_UT_c1, P_UT_c10, P_UT_c2, P_UT_c3, P_UT_c4, P_UT_c5, P_UT_c6, P_UT_c7, P_UT_c8, P_UT_c9, P_UT_s1, P_UT_s10, P_UT_s2, P_UT_s3, P_UT_s4, P_UT_s5, P_UT_s6, P_UT_s7, P_UT_s8, P_UT_s9, P_Xp_m1, P_Xp_m10, P_Xp_m2, P_Xp_m3, P_Xp_m4, P_Xp_m5, P_Xp_m6, P_Xp_m7, P_Xp_m8, P_Xp_m9, P_Xp_p1, P_Xp_p10, P_Xp_p2, P_Xp_p3, P_Xp_p4, P_Xp_p5, P_Xp_p6, P_Xp_p7, P_Xp_p8, P_Xp_p9, P_Yp_m1, P_Yp_m10, P_Yp_m2, P_Yp_m3, P_Yp_m4, P_Yp_m5, P_Yp_m6, P_Yp_m7, P_Yp_m8, P_Yp_m9, P_Yp_p1, P_Yp_p10, P_Yp_p2, P_Yp_p3, P_Yp_p4, P_Yp_p5, P_Yp_p6, P_Yp_p7, P_Yp_p8, and P_Yp_p9.
Referenced by SBRunManager::~SBRunManager().
void SBEOP::setEpoch (const SBMJD &Epoch_) [inline]
Definition at line 266 of file SbGeoEop.H'.
References Epoch.
Referenced by SBStuffEOPs::accept().
void SBEOP::setEps (doubleEps_) [inline]
Definition at line 384 of file SbGeoEop.H'.
References Eps.
Referenced by SBStuffEOPs::accept().
void SBEOP::setEpss (doubleEpss_) [inline]
Definition at line 385 of file SbGeoEop.H'.
References Epss.
Referenced by SBStuffEOPs::accept().
void SBEOP::setLabel (const SBSolutionName &Label_) [inline]
Definition at line 265 of file SbGeoEop.H'.
References Label.
Referenced by SBStuffEOPs::accept().
void SBEOP::setMgr (SBRunManager *Mgr_) [inline]
Definition at line 268 of file SbGeoEop.H'.
References Mgr.
void SBEOP::setPsi (doublePsi_) [inline]
Definition at line 382 of file SbGeoEop.H'.
References Psi.
Referenced by SBStuffEOPs::accept().
void SBEOP::setPsis (doublePsis_) [inline]
Definition at line 383 of file SbGeoEop.H'.
References Psis.
Referenced by SBStuffEOPs::accept().
void SBEOP::setPtNum (unsigned intNum_)
Definition at line 421 of file SbGeoEop.C'.
References Cache, Idx, IsOK, PtNum, SBMatrix::resize(), Spliner, T_4Prepare, and TZero.
Referenced by SBTestEOP::fillData4Plotting(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestEOP::SBTestEOP(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), and SBTestSolidTides::SBTestSolidTides().
void SBEOP::setUt (doubleUT_) [inline]
Definition at line 380 of file SbGeoEop.H'.
References UT.
Referenced by SBStuffEOPs::accept().
void SBEOP::setUtHasHiTide (boolUTHasHiTide_) [inline]
Definition at line 386 of file SbGeoEop.H'.
References UTHasHiTide.
Referenced by SBStuffEOPs::accept().
void SBEOP::setUtHasLoTide (boolUTHasLoTide_) [inline]
Definition at line 387 of file SbGeoEop.H'.
References UTHasLoTide.
Referenced by SBStuffEOPs::accept().
void SBEOP::setUts (doubleUTs_) [inline]
Definition at line 381 of file SbGeoEop.H'.
References UTs.
Referenced by SBStuffEOPs::accept().
void SBEOP::setXp (doubleXp_) [inline]
Definition at line 376 of file SbGeoEop.H'.
References Xp.
Referenced by SBStuffEOPs::accept().
void SBEOP::setXps (doubleXps_) [inline]
Definition at line 377 of file SbGeoEop.H'.
References Xps.
Referenced by SBStuffEOPs::accept().
void SBEOP::setYp (doubleYp_) [inline]
Definition at line 378 of file SbGeoEop.H'.
References Yp.
Referenced by SBStuffEOPs::accept().
void SBEOP::setYps (doubleYps_) [inline]
Definition at line 379 of file SbGeoEop.H'.
References Yps.
Referenced by SBStuffEOPs::accept().
const SBMJD& SBEOP::t_4Prepare () const [inline]
Definition at line 395 of file SbGeoEop.H'.
References T_4Prepare.
Referenced by SBTestEphem::recalc().
SBMJD SBEOP::tFinis () const [inline]
Definition at line 275 of file SbGeoEop.H'.
References TFinis.
Referenced by SBStuffEOPs::createInfoGroup(), SBTestEOP::SBTestEOP(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), and SBStuffEOPs::updateEOP().
SBMJD SBEOP::tStart () const [inline]
Definition at line 274 of file SbGeoEop.H'.
References TStart.
Referenced by SBStuffEOPs::createInfoGroup(), SBTestEOP::SBTestEOP(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), and SBStuffEOPs::updateEOP().
void SBEOP::updateParameters (SBRunManager *Mgr, const SBMJD &T)
Definition at line 1131 of file SbGeoEop.C'.
References P_Neps, P_Npsi, P_Put, P_Px, P_Py, P_UT_c1, P_UT_c10, P_UT_c2, P_UT_c3, P_UT_c4, P_UT_c5, P_UT_c6, P_UT_c7, P_UT_c8, P_UT_c9, P_UT_s1, P_UT_s10, P_UT_s2, P_UT_s3, P_UT_s4, P_UT_s5, P_UT_s6, P_UT_s7, P_UT_s8, P_UT_s9, P_Xp_m1, P_Xp_m10, P_Xp_m2, P_Xp_m3, P_Xp_m4, P_Xp_m5, P_Xp_m6, P_Xp_m7, P_Xp_m8, P_Xp_m9, P_Xp_p1, P_Xp_p10, P_Xp_p2, P_Xp_p3, P_Xp_p4, P_Xp_p5, P_Xp_p6, P_Xp_p7, P_Xp_p8, P_Xp_p9, P_Yp_m1, P_Yp_m10, P_Yp_m2, P_Yp_m3, P_Yp_m4, P_Yp_m5, P_Yp_m6, P_Yp_m7, P_Yp_m8, P_Yp_m9, P_Yp_p1, P_Yp_p10, P_Yp_p2, P_Yp_p3, P_Yp_p4, P_Yp_p5, P_Yp_p6, P_Yp_p7, P_Yp_p8, P_Yp_p9, SBRunManager::solution(), and SBSolution::updateParameter().
Referenced by interpolateEOPs().
double SBEOP::ut () const [inline]
Definition at line 283 of file SbGeoEop.H'.
References UT.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
bool SBEOP::utHasHiTide () const [inline]
Definition at line 289 of file SbGeoEop.H'.
References UTHasHiTide.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
bool SBEOP::utHasLoTide () const [inline]
Definition at line 290 of file SbGeoEop.H'.
References UTHasLoTide.
Referenced by SBStuffEOPs::accept().
double SBEOP::uts () const [inline]
Definition at line 284 of file SbGeoEop.H'.
References UTs.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
virtual QDataStream& SBEOP::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 128 of file SbGeoEop.H'.
double SBEOP::xp () const [inline]
Definition at line 279 of file SbGeoEop.H'.
References Xp.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
double SBEOP::xps () const [inline]
Definition at line 280 of file SbGeoEop.H'.
References Xps.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
double SBEOP::yp () const [inline]
Definition at line 281 of file SbGeoEop.H'.
References Yp.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
double SBEOP::yps () const [inline]
Definition at line 282 of file SbGeoEop.H'.
References Yps.
Referenced by SBStuffEOPs::accept(), SBStuffEOPs::createOptionsGroup(), and SBStuffEOPs::updateEOP().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBEOP &EOP) [friend]
Definition at line 1223 of file SbGeoEop.C'.
QTextStream& operator<< (QTextStream &s, const SBEOP &) [friend]
Definition at line 1245 of file SbGeoEop.C'.
QDataStream& operator>> (QDataStream &s, SBEOP &EOP) [friend]
Definition at line 1233 of file SbGeoEop.C'.
QTextStream& operator>> (QTextStream &s, SBEOP &) [friend]
Definition at line 1250 of file SbGeoEop.C'.
Member Data Documentation
SBMatrix* SBEOP::Cache [private]
Definition at line 157 of file SbGeoEop.H'.
Referenced by cache4Interpolation(), interpolateEOPs(), prepare4Date(), SBEOP(), setPtNum(), and ~SBEOP().
double SBEOP::EOP_Eps [private]
Definition at line 170 of file SbGeoEop.H'.
Referenced by dEps(), interpolateEOPs(), and SBEOP().
double SBEOP::EOP_LOD [private]
Definition at line 168 of file SbGeoEop.H'.
Referenced by dLOD(), interpolateEOPs(), and SBEOP().
double SBEOP::EOP_Psi [private]
Definition at line 169 of file SbGeoEop.H'.
Referenced by dPsi(), interpolateEOPs(), and SBEOP().
double SBEOP::EOP_UT [private]
Definition at line 167 of file SbGeoEop.H'.
Referenced by dUT1_UTC(), interpolateEOPs(), and SBEOP().
double SBEOP::EOP_X [private]
Definition at line 165 of file SbGeoEop.H'.
Referenced by dX(), interpolateEOPs(), and SBEOP().
double SBEOP::EOP_Y [private]
Definition at line 166 of file SbGeoEop.H'.
Referenced by dY(), interpolateEOPs(), and SBEOP().
SBMJD SBEOP::Epoch [private]
Definition at line 136 of file SbGeoEop.H'.
Referenced by epoch(), operator<<(), operator>>(), SBEOP(), and setEpoch().
double SBEOP::Eps [private]
Definition at line 149 of file SbGeoEop.H'.
Referenced by eps(), operator<<(), operator>>(), SBEOP(), and setEps().
double SBEOP::Epss [private]
Definition at line 150 of file SbGeoEop.H'.
Referenced by epss(), operator<<(), operator>>(), SBEOP(), and setEpss().
bool SBEOP::HasLeapSecond [private]
Definition at line 171 of file SbGeoEop.H'.
Referenced by interpolateEOPs(), prepare4Date(), and SBEOP().
unsigned int SBEOP::Idx [private]
Definition at line 159 of file SbGeoEop.H'.
Referenced by prepare4Date(), SBEOP(), and setPtNum().
bool SBEOP::IsOK [private]
Definition at line 160 of file SbGeoEop.H'.
Referenced by importSeries(), interpolateEOPs(), prepare4Date(), SBEOP(), and setPtNum().
SBSolutionName SBEOP::Label [private]
Definition at line 132 of file SbGeoEop.H'.
Referenced by checkRanges(), label(), operator<<(), operator>>(), SBEOP(), and setLabel().
SBRunManager* SBEOP::Mgr [private]
Definition at line 176 of file SbGeoEop.H'.
Referenced by dUT1_UTC(), dX(), dY(), interpolateEOPs(), mgr(), SBEOP(), and setMgr().
SBParameter* SBEOP::P_Neps [private]
estimation of the Nutation angle Eps;
Definition at line 181 of file SbGeoEop.H'.
Referenced by createParameters(), interpolateEOPs(), p_Neps(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Npsi [private]
estimation of the Nutation angle Psi;
Definition at line 180 of file SbGeoEop.H'.
Referenced by createParameters(), interpolateEOPs(), p_Npsi(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Put [private]
estimation of the UT;
Definition at line 179 of file SbGeoEop.H'.
Referenced by createParameters(), interpolateEOPs(), p_Put(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Px [private]
estimation of the X-polar coordinate;
Definition at line 177 of file SbGeoEop.H'.
Referenced by createParameters(), interpolateEOPs(), p_Px(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Py [private]
estimation of the Y-polar coordinate;
Definition at line 178 of file SbGeoEop.H'.
Referenced by createParameters(), interpolateEOPs(), p_Py(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c1 [private]
Definition at line 202 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c1(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c10 [private]
Definition at line 252 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c10(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c2 [private]
Definition at line 204 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c2(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c3 [private]
Definition at line 207 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c3(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c4 [private]
Definition at line 209 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c4(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c5 [private]
Definition at line 217 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c5(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c6 [private]
Definition at line 224 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c6(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c7 [private]
Definition at line 231 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c7(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c8 [private]
Definition at line 238 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c8(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_c9 [private]
Definition at line 245 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_c9(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s1 [private]
Definition at line 203 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s1(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s10 [private]
Definition at line 253 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s10(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s2 [private]
Definition at line 205 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s2(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s3 [private]
Definition at line 208 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s3(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s4 [private]
Definition at line 210 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s4(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s5 [private]
Definition at line 218 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s5(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s6 [private]
Definition at line 225 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s6(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s7 [private]
Definition at line 232 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s7(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s8 [private]
Definition at line 239 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s8(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_UT_s9 [private]
Definition at line 246 of file SbGeoEop.H'.
Referenced by createParameters(), dUT1_UTC(), p_UT_s9(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m1 [private]
Definition at line 186 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m1(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m10 [private]
Definition at line 248 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m10(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m2 [private]
Definition at line 184 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m2(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m3 [private]
Definition at line 193 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m3(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m4 [private]
Definition at line 197 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m4(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m5 [private]
Definition at line 213 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m5(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m6 [private]
Definition at line 220 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m6(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m7 [private]
Definition at line 227 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m7(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m8 [private]
Definition at line 234 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m8(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_m9 [private]
Definition at line 241 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_m9(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p1 [private]
Definition at line 188 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p1(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p10 [private]
Definition at line 250 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p10(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p2 [private]
Definition at line 190 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p2(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p3 [private]
Definition at line 195 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p3(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p4 [private]
Definition at line 199 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p4(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p5 [private]
Definition at line 215 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p5(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p6 [private]
Definition at line 222 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p6(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p7 [private]
Definition at line 229 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p7(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p8 [private]
Definition at line 236 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p8(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Xp_p9 [private]
Definition at line 243 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Xp_p9(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m1 [private]
Definition at line 187 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m1(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m10 [private]
Definition at line 249 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m10(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m2 [private]
Definition at line 185 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m2(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m3 [private]
Definition at line 194 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m3(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m4 [private]
Definition at line 198 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m4(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m5 [private]
Definition at line 214 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m5(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m6 [private]
Definition at line 221 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m6(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m7 [private]
Definition at line 228 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m7(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m8 [private]
Definition at line 235 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m8(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_m9 [private]
Definition at line 242 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_m9(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p1 [private]
Definition at line 189 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p1(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p10 [private]
Definition at line 251 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p10(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p2 [private]
Definition at line 191 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p2(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p3 [private]
Definition at line 196 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p3(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p4 [private]
Definition at line 200 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p4(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p5 [private]
Definition at line 216 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p5(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p6 [private]
Definition at line 223 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p6(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p7 [private]
Definition at line 230 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p7(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p8 [private]
Definition at line 237 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p8(), releaseParameters(), SBEOP(), and updateParameters().
SBParameter* SBEOP::P_Yp_p9 [private]
Definition at line 244 of file SbGeoEop.H'.
Referenced by createParameters(), dX(), dY(), p_Yp_p9(), releaseParameters(), SBEOP(), and updateParameters().
double SBEOP::Psi [private]
Definition at line 147 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), psi(), SBEOP(), and setPsi().
double SBEOP::Psis [private]
Definition at line 148 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), psis(), SBEOP(), and setPsis().
unsigned int SBEOP::PtNum [private]
Definition at line 156 of file SbGeoEop.H'.
Referenced by interpolateEOPs(), prepare4Date(), ptNum(), SBEOP(), and setPtNum().
int SBEOP::SLSign [private]
Definition at line 173 of file SbGeoEop.H'.
Referenced by interpolateEOPs(), prepare4Date(), and SBEOP().
SBSpline* SBEOP::Spliner [private]
Definition at line 158 of file SbGeoEop.H'.
Referenced by interpolateEOPs(), prepare4Date(), SBEOP(), setPtNum(), and ~SBEOP().
SBMJD SBEOP::T_4Prepare [private]
Definition at line 161 of file SbGeoEop.H'.
Referenced by prepare4Date(), SBEOP(), setPtNum(), and t_4Prepare().
SBMJD SBEOP::T_4Spline [private]
Definition at line 164 of file SbGeoEop.H'.
Referenced by dEps(), dLOD(), dPsi(), dUT1_UTC(), dX(), dY(), interpolateEOPs(), and SBEOP().
SBMJD SBEOP::T_LeapSecond [private]
Definition at line 172 of file SbGeoEop.H'.
Referenced by interpolateEOPs(), prepare4Date(), and SBEOP().
SBMJD SBEOP::TFinis [private]
Definition at line 138 of file SbGeoEop.H'.
Referenced by checkRanges(), prepare4Date(), SBEOP(), and tFinis().
SBMJD SBEOP::TStart [private]
Definition at line 137 of file SbGeoEop.H'.
Referenced by checkRanges(), prepare4Date(), SBEOP(), and tStart().
double SBEOP::UT [private]
Definition at line 145 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setUt(), and ut().
bool SBEOP::UTHasHiTide [private]
Definition at line 152 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setUtHasHiTide(), and utHasHiTide().
bool SBEOP::UTHasLoTide [private]
Definition at line 153 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setUtHasLoTide(), and utHasLoTide().
double SBEOP::UTs [private]
Definition at line 146 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setUts(), and uts().
double SBEOP::Xp [private]
Definition at line 141 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setXp(), and xp().
double SBEOP::Xps [private]
Definition at line 142 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setXps(), and xps().
double SBEOP::Yp [private]
Definition at line 143 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setYp(), and yp().
double SBEOP::Yps [private]
Definition at line 144 of file SbGeoEop.H'.
Referenced by operator<<(), operator>>(), SBEOP(), setYps(), and yps().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.