.TH "SBEOPListItem" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBEOPListItem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIStuff\&.H>\fP
.PP
Inherits \fBQListViewItem\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBEOPListItem\fP (\fBQListView\fP *, \fBSBEOPEntry\fP *)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.ti -1c
.RI "QString \fBkey\fP (int, bool) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBEOPEntry\fP * \fBEOPEntry\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSBStuffEOPs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file SbIStuff\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBEOPListItem::SBEOPListItem (\fBQListView\fP *parent, \fBSBEOPEntry\fP *EOPEntry_)"
.PP
Definition at line 59 of file SbIStuff\&.C'\&.
.PP
References EOPEntry\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBEOPListItem::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 57 of file SbIStuff\&.H'\&.
.SS "QString SBEOPListItem::key (intcol, bool) const"
.PP
Definition at line 90 of file SbIStuff\&.C'\&.
.PP
References EOPEntry, SBEOPEntry::eps(), SBEOPEntry::lod(), SBEOPEntry::psi(), text(), TmpString, SBEOPEntry::ut(), SBEOPEntry::xp(), and SBEOPEntry::yp()\&.
.SS "QString SBEOPListItem::text (intcol) const\fC [virtual]\fP"
.PP
Definition at line 66 of file SbIStuff\&.C'\&.
.PP
References EOPEntry, and TmpString\&.
.PP
Referenced by key()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSBStuffEOPs\fP\fC [friend]\fP"
.PP
Definition at line 60 of file SbIStuff\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBEOPEntry\fP* \fBSBEOPListItem::EOPEntry\fP\fC [private]\fP"
.PP
Definition at line 54 of file SbIStuff\&.H'\&.
.PP
Referenced by key(), SBEOPListItem(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
