SBEphem
NAME
SBEphem -
SYNOPSIS
#include <SbGeoEphem.H>
Inherits SBNamed'.
Inherited by SBEphemDE200, SBEphemDE403, and SBEphemDE405'.
Classes
struct Entry
Public Member Functions
virtual ~SBEphem ()
virtual QString ClassName () const
virtual QString fileName () const
virtual void calc (const SBMJD &)
virtual void calcI (int, const SBMJD &)
virtual bool import (const QString &)
virtual double dt () const
virtual double au () const
virtual double cLight () const
virtual double emRat () const
const SBCelestBody & mercury ()
const SBCelestBody & venus ()
const SBCelestBody & earth ()
const SBCelestBody & mars ()
const SBCelestBody & jupiter ()
const SBCelestBody & saturn ()
const SBCelestBody & uran ()
const SBCelestBody & neptun ()
const SBCelestBody & pluto ()
const SBCelestBody & moon ()
const SBCelestBody & geoMoon ()
const SBCelestBody & sun ()
const SBCelestBody & body (int i)
virtual unsigned int nRecCoef () const
const SBMJD & tStart ()
const SBMJD & tFinis ()
bool isOK ()
int numRecs ()
const QString & name () const
void setName (const QString &Name_)
Protected Member Functions
SBEphem (const SBConfig *, const QString &='LE/DEXXX general interface')
virtual void initData ()
virtual void checkData ()
virtual void openFile ()
virtual long calcOffset (const SBMJD &T)
virtual void interp (double, int, int, int, SBCelestBody &)
Protected Attributes
const SBConfig * Cfg
SBCelestBody Mercury
Mercury'.
SBCelestBody Venus
Venus'.
SBCelestBody Earth
Earth'.
SBCelestBody Mars
Mars'.
SBCelestBody Jupiter
Jupiter'.
SBCelestBody Saturn
Saturn'.
SBCelestBody Uran
Uran'.
SBCelestBody Neptun
Neptun'.
SBCelestBody Pluto
Pluto'.
SBCelestBody Moon
Moon'.
SBCelestBody Sun
Sun'.
SBCelestBody GeoMoon
Geocentric Moon'.
SBCelestBody * Solary [11]
SBMJD TStart
time of the first entry of ephemerides
SBMJD TFinis
time of the last entry of ephemerides
SBMJD TBlStart
time of block's begin;
SBMJD TBlFinis
time of block's end;
FILE * EphemFile
file containing data;
bool IsOK
double * buff
buffer for a record;
double DT
a record's interval;
unsigned int NRecCoef
number of coefficients per record;
int NumRecs
number of records;
long FileOffset
file offset;
double AU
number of meters per astronomical unit
double CLight
Speed of light (m/s)
double EMRat
Earth-Moon mass ratio'.
const Entry * Loc
QString Name
Static Protected Attributes
static const Entry LocAbstract [13]
Friends
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Ephemerides (general)'. Describes genereal interface to ephemerides'.
Definition at line 88 of file SbGeoEphem.H'.
Constructor & Destructor Documentation
SBEphem::SBEphem (const SBConfig *Cfg_, const QString &Name_ = 'LE/DEXXX general interface') [protected]"A constructor'.
A constructor'. Creates a copy of object'.
Definition at line 84 of file SbGeoEphem.C'.
References SBAttributed::addAttr(), AU, Cfg, CLight, SBAttributed::delAttr(), DT, Earth, EMRat, FileOffset, SBCelestBody::IsEligible, SBConfig::isEphBody(), SBCelestBody::IsGravDelay, IsOK, Jupiter, Loc, LocAbstract, Mars, Mercury, Moon, Neptun, NRecCoef, NumRecs, Pluto, Saturn, Solary, Sun, Uran, and Venus.
SBEphem::~SBEphem () [virtual]"A destructor'.
Definition at line 136 of file SbGeoEphem.C'.
References buff, ClassName(), SBLog::EPHEM, EphemFile, SBLog::ERR, fileName(), SBLog::IO, isOK(), Log, and SBLog::write().
Member Function Documentation
virtual double SBEphem::au () const [inline, virtual]"Returns number of meters per Astronomical unit used in this Ephemerides'.
Definition at line 161 of file SbGeoEphem.H'.
References AU.
Referenced by SBStuffEphem::SBStuffEphem(), SBTestEphem::SBTestEphem(), and SBStuffEphem::updateEphem().
const SBCelestBody& SBEphem::body (inti) [inline]"Returns i-th body state relative to the SSB i: 0(Mercury), 1(Venus), 2(Earth), 3(Mars), 4(Jupiter), 5(Saturn), 6(Uranus), 7(Neptune), 8(Pluto), 9(Moon), 10(Sun)'.
Definition at line 195 of file SbGeoEphem.H'.
References Solary.
Referenced by SBTestEphem::createWidget4Test(), SBTestEphem::displayCoo(), SBTestEphem::originChanged(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
void SBEphem::calc (const SBMJD &T) [virtual]"Calcs states of the celestial bodies for corresponded date'.
Definition at line 190 of file SbGeoEphem.C'.
References SBCelestBody::A, SBCelestBody::a(), buff, calcOffset(), ClassName(), SBLog::DBG, dt(), Earth, emRat(), SBLog::EPHEM, EphemFile, SBLog::ERR, SBMJD::F_Short, FileOffset, GeoMoon, interp(), SBLog::IO, SBCelestBody::IsEligible, SBLog::isEligible(), isOK(), Loc, Log, Moon, SBNamed::name(), nRecCoef(), SBCelestBody::R, SBCelestBody::r(), Vector3::report2Log(), SBCelestBody::setTCurrent(), Solary, TBlFinis, TBlStart, TFinis, SBMJD::toString(), TStart, SBCelestBody::V, SBCelestBody::v(), and SBLog::write().
Referenced by SBDelay::calc(), SBTestEphem::createWidget4Test(), SBTestSolidTides::fillData4Plotting(), and SBTestEphem::recalc().
void SBEphem::calcI (intI, const SBMJD &T) [virtual]"Calcs state of the i-th celestial body for corresponded date'.
Definition at line 271 of file SbGeoEphem.C'.
References SBCelestBody::A, buff, calcOffset(), ClassName(), dt(), Earth, emRat(), SBLog::EPHEM, EphemFile, SBLog::ERR, SBMJD::F_Short, FileOffset, GeoMoon, interp(), SBLog::IO, isOK(), Loc, Log, Moon, nRecCoef(), SBCelestBody::R, SBCelestBody::setTCurrent(), Solary, TBlFinis, TBlStart, TFinis, SBMJD::toString(), TStart, SBCelestBody::V, and SBLog::write().
virtual long SBEphem::calcOffset (const SBMJD &T) [inline, protected, virtual]"Calculates file offset for a corresponding time'.
Definition at line 138 of file SbGeoEphem.H'.
References dt(), TFinis, and TStart.
Referenced by calc(), and calcI().
virtual void SBEphem::checkData () [inline, protected, virtual]"Addition check of data'.
Definition at line 134 of file SbGeoEphem.H'.
References IsOK.
Referenced by openFile().
virtual QString SBEphem::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBNamed'.
Reimplemented in SBEphemDE405, SBEphemDE403, and SBEphemDE200'.
Definition at line 147 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), import(), initData(), openFile(), and ~SBEphem().
virtual double SBEphem::cLight () const [inline, virtual]"Returns speed of light used in this Ephemerides'.
Definition at line 163 of file SbGeoEphem.H'.
References CLight.
Referenced by SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
virtual double SBEphem::dt () const [inline, virtual]"Returns time interval of a record'.
Definition at line 159 of file SbGeoEphem.H'.
References DT.
Referenced by calc(), calcI(), calcOffset(), import(), interp(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
const SBCelestBody& SBEphem::earth () [inline]"Returns Earth (not E-M baricenter) state'.
Definition at line 172 of file SbGeoEphem.H'.
References Earth.
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), SBSolidTideLdIERS96::makeStep1(), and SBSolidTideLd::operator()().
virtual double SBEphem::emRat () const [inline, virtual]"Returns Earth-Moon mass ratio used in this Ephemerides'.
Definition at line 165 of file SbGeoEphem.H'.
References EMRat.
Referenced by calc(), calcI(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), SBSolidTideLdIERS96::makeStep1(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
virtual QString SBEphem::fileName () const [inline, virtual]"Returns a file name'.
Reimplemented in SBEphemDE405, SBEphemDE403, and SBEphemDE200'.
Definition at line 150 of file SbGeoEphem.H'.
Referenced by import(), openFile(), and ~SBEphem().
const SBCelestBody& SBEphem::geoMoon () [inline]"Returns Moon state (relative to the Geocenter)'.
Definition at line 188 of file SbGeoEphem.H'.
References GeoMoon.
Referenced by SBSolidTideLd::operator()().
bool SBEphem::import (const QString &ImpFName) [virtual]"Makes data imortation from the ASCII file'.
Definition at line 383 of file SbGeoEphem.C'.
References ClassName(), SBFCList::close(), SBLog::DBG, dt(), SBLog::EPHEM, EphemFile, SBLog::ERR, SBMJD::F_Short, SBSetUp::fcList(), fileName(), SBLog::IO, IsOK, isOK(), Log, mainMessage(), mainPrBarReset(), mainPrBarSetProgress(), mainPrBarSetTotalSteps(), nRecCoef(), numRecs(), SBFCList::open4In(), openFile(), SBSetUp::path2Stuff(), SetUp, tFinis(), SBMJD::toString(), tStart(), TZero, and SBLog::write().
Referenced by SBStuffEphem::import().
void SBEphem::initData () [protected, virtual]"Allocates buffer for one record, then calls openFile()'.
Definition at line 144 of file SbGeoEphem.C'.
References buff, ClassName(), SBLog::DBG, SBLog::EPHEM, Log, nRecCoef(), openFile(), and SBLog::write().
Referenced by SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
void SBEphem::interp (doubleT, intOffset, intNCo, intNSets, SBCelestBody &B) [protected, virtual]"Makes interpolation of a vector state for specified body'.
Definition at line 339 of file SbGeoEphem.C'.
References SBCelestBody::A, buff, DAY2SEC, dt(), SBCelestBody::R, and SBCelestBody::V.
Referenced by calc(), and calcI().
bool SBEphem::isOK () [inline]"Returns TRUE if data is OK'.
Definition at line 204 of file SbGeoEphem.H'.
References IsOK.
Referenced by calc(), calcI(), import(), openFile(), SBTestEphem::recalc(), SBStuffEphem::SBStuffEphem(), SBStuffEphem::updateEphem(), and ~SBEphem().
const SBCelestBody& SBEphem::jupiter () [inline]"Returns Jupiter state'.
Definition at line 176 of file SbGeoEphem.H'.
References Jupiter.
const SBCelestBody& SBEphem::mars () [inline]"Returns Mars state'.
Definition at line 174 of file SbGeoEphem.H'.
References Mars.
const SBCelestBody& SBEphem::mercury () [inline]"Returns Mercury state'.
Definition at line 168 of file SbGeoEphem.H'.
References Mercury.
const SBCelestBody& SBEphem::moon () [inline]"Returns Moon state (relative to the Solar System Barycenter)'.
Definition at line 186 of file SbGeoEphem.H'.
References Moon.
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
const SBCelestBody& SBEphem::neptun () [inline]"Returns Neptune state'.
Definition at line 182 of file SbGeoEphem.H'.
References Neptun.
virtual unsigned int SBEphem::nRecCoef () const [inline, virtual]"Returns number of coefficients (+2 time stamps)'.
Definition at line 198 of file SbGeoEphem.H'.
References NRecCoef.
Referenced by calc(), calcI(), import(), initData(), openFile(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
int SBEphem::numRecs () [inline]"Returns number of records stored in the file'.
Definition at line 206 of file SbGeoEphem.H'.
References NumRecs.
Referenced by import(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
void SBEphem::openFile () [protected, virtual]"Opens binary file and checks it'.
Definition at line 152 of file SbGeoEphem.C'.
References buff, checkData(), ClassName(), SBLog::EPHEM, EphemFile, SBLog::ERR, SBMJD::F_Short, fileName(), FileOffset, SBLog::INF, SBLog::IO, isOK(), Log, SBNamed::name(), nRecCoef(), NumRecs, SBSetUp::path2Stuff(), SetUp, TBlFinis, TBlStart, TFinis, SBMJD::toString(), TStart, SBLog::write(), and SBLog::WRN.
Referenced by import(), and initData().
const SBCelestBody& SBEphem::pluto () [inline]"Returns Pluto state'.
Definition at line 184 of file SbGeoEphem.H'.
References Pluto.
const SBCelestBody& SBEphem::saturn () [inline]"Returns Saturn state'.
Definition at line 178 of file SbGeoEphem.H'.
References Saturn.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
const SBCelestBody& SBEphem::sun () [inline]"Returns Sun state'.
Definition at line 190 of file SbGeoEphem.H'.
References Sun.
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), SBSolidTideLdIERS96::makeStep1(), SBSolidTideLd::operator()(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
const SBMJD& SBEphem::tFinis () [inline]"Returns the last available MJD'.
Definition at line 202 of file SbGeoEphem.H'.
References TFinis.
Referenced by import(), SBStuffEphem::SBStuffEphem(), SBTestEphem::SBTestEphem(), SBTestSolidTides::SBTestSolidTides(), and SBStuffEphem::updateEphem().
const SBMJD& SBEphem::tStart () [inline]"Returns the first available MJD'.
Definition at line 200 of file SbGeoEphem.H'.
References TStart.
Referenced by import(), SBStuffEphem::SBStuffEphem(), SBTestEphem::SBTestEphem(), SBTestSolidTides::SBTestSolidTides(), and SBStuffEphem::updateEphem().
const SBCelestBody& SBEphem::uran () [inline]"Returns Uranus state'.
Definition at line 180 of file SbGeoEphem.H'.
References Uran.
const SBCelestBody& SBEphem::venus () [inline]"Returns Venus state'.
Definition at line 170 of file SbGeoEphem.H'.
References Venus.
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
Member Data Documentation
double SBEphem::AU [protected]
number of meters per astronomical unit
Definition at line 116 of file SbGeoEphem.H'.
Referenced by au(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
double* SBEphem::buff [protected]
buffer for a record;
Definition at line 111 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), initData(), interp(), openFile(), and ~SBEphem().
const SBConfig* SBEphem::Cfg [protected]
Definition at line 91 of file SbGeoEphem.H'.
Referenced by SBEphem().
double SBEphem::CLight [protected]
Speed of light (m/s)
Definition at line 117 of file SbGeoEphem.H'.
Referenced by cLight(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
double SBEphem::DT [protected]
a record's interval;
Definition at line 112 of file SbGeoEphem.H'.
Referenced by dt(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
SBCelestBody SBEphem::Earth [protected]
Earth'.
Definition at line 94 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), earth(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
double SBEphem::EMRat [protected]
Earth-Moon mass ratio'.
Definition at line 118 of file SbGeoEphem.H'.
Referenced by emRat(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
FILE* SBEphem::EphemFile [protected]
file containing data;
Definition at line 109 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), import(), openFile(), and ~SBEphem().
long SBEphem::FileOffset [protected]
file offset;
Definition at line 115 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), openFile(), and SBEphem().
SBCelestBody SBEphem::GeoMoon [protected]
Geocentric Moon'.
Definition at line 103 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), geoMoon(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
bool SBEphem::IsOK [protected]
Definition at line 110 of file SbGeoEphem.H'.
Referenced by checkData(), import(), isOK(), and SBEphem().
SBCelestBody SBEphem::Jupiter [protected]
Jupiter'.
Definition at line 96 of file SbGeoEphem.H'.
Referenced by jupiter(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
const Entry* SBEphem::Loc [protected]
Definition at line 126 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
const SBEphem::Entry SBEphem::LocAbstract [static, protected]"Initial value:
{
  { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0},
  { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0},
  { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}
}
Definition at line 127 of file SbGeoEphem.H'.
Referenced by SBEphem().
SBCelestBody SBEphem::Mars [protected]
Mars'.
Definition at line 95 of file SbGeoEphem.H'.
Referenced by mars(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
SBCelestBody SBEphem::Mercury [protected]
Mercury'.
Definition at line 92 of file SbGeoEphem.H'.
Referenced by mercury(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
SBCelestBody SBEphem::Moon [protected]
Moon'.
Definition at line 101 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), moon(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
SBCelestBody SBEphem::Neptun [protected]
Neptun'.
Definition at line 99 of file SbGeoEphem.H'.
Referenced by neptun(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
unsigned int SBEphem::NRecCoef [protected]
number of coefficients per record;
Definition at line 113 of file SbGeoEphem.H'.
Referenced by nRecCoef(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
int SBEphem::NumRecs [protected]
number of records;
Definition at line 114 of file SbGeoEphem.H'.
Referenced by numRecs(), openFile(), and SBEphem().
SBCelestBody SBEphem::Pluto [protected]
Pluto'.
Definition at line 100 of file SbGeoEphem.H'.
Referenced by pluto(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
SBCelestBody SBEphem::Saturn [protected]
Saturn'.
Definition at line 97 of file SbGeoEphem.H'.
Referenced by saturn(), SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405::SBEphemDE405().
SBCelestBody* SBEphem::Solary[11] [protected]
Definition at line 104 of file SbGeoEphem.H'.
Referenced by body(), calc(), calcI(), and SBEphem().
SBCelestBody SBEphem::Sun [protected]
Sun'.
Definition at line 102 of file SbGeoEphem.H'.
Referenced by SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), SBEphemDE405::SBEphemDE405(), and sun().
SBMJD SBEphem::TBlFinis [protected]
time of block's end;
Definition at line 108 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), and openFile().
SBMJD SBEphem::TBlStart [protected]
time of block's begin;
Definition at line 107 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), and openFile().
SBMJD SBEphem::TFinis [protected]
time of the last entry of ephemerides
Definition at line 106 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), calcOffset(), openFile(), and tFinis().
SBMJD SBEphem::TStart [protected]
time of the first entry of ephemerides
Definition at line 105 of file SbGeoEphem.H'.
Referenced by calc(), calcI(), calcOffset(), openFile(), and tStart().
SBCelestBody SBEphem::Uran [protected]
Uran'.
Definition at line 98 of file SbGeoEphem.H'.
Referenced by SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), SBEphemDE405::SBEphemDE405(), and uran().
SBCelestBody SBEphem::Venus [protected]
Venus'.
Definition at line 93 of file SbGeoEphem.H'.
Referenced by SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), SBEphemDE405::SBEphemDE405(), and venus().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.