SBEphemDE405
NAME
SBEphemDE405 -
SYNOPSIS
#include <SbGeoEphem.H>
Inherits SBEphem'.
Public Member Functions
SBEphemDE405 (const SBConfig *)
virtual QString ClassName () const
virtual QString fileName () const
virtual void calc (const SBMJD &)
virtual void calcI (int, const SBMJD &)
virtual bool import (const QString &)
virtual double dt () const
virtual double au () const
virtual double cLight () const
virtual double emRat () const
const SBCelestBody & mercury ()
const SBCelestBody & venus ()
const SBCelestBody & earth ()
const SBCelestBody & mars ()
const SBCelestBody & jupiter ()
const SBCelestBody & saturn ()
const SBCelestBody & uran ()
const SBCelestBody & neptun ()
const SBCelestBody & pluto ()
const SBCelestBody & moon ()
const SBCelestBody & geoMoon ()
const SBCelestBody & sun ()
const SBCelestBody & body (int i)
virtual unsigned int nRecCoef () const
const SBMJD & tStart ()
const SBMJD & tFinis ()
bool isOK ()
int numRecs ()
const QString & name () const
void setName (const QString &Name_)
Protected Member Functions
virtual void initData ()
virtual void checkData ()
virtual void openFile ()
virtual long calcOffset (const SBMJD &T)
virtual void interp (double, int, int, int, SBCelestBody &)
Protected Attributes
const SBConfig * Cfg
SBCelestBody Mercury
Mercury'.
SBCelestBody Venus
Venus'.
SBCelestBody Earth
Earth'.
SBCelestBody Mars
Mars'.
SBCelestBody Jupiter
Jupiter'.
SBCelestBody Saturn
Saturn'.
SBCelestBody Uran
Uran'.
SBCelestBody Neptun
Neptun'.
SBCelestBody Pluto
Pluto'.
SBCelestBody Moon
Moon'.
SBCelestBody Sun
Sun'.
SBCelestBody GeoMoon
Geocentric Moon'.
SBCelestBody * Solary [11]
SBMJD TStart
time of the first entry of ephemerides
SBMJD TFinis
time of the last entry of ephemerides
SBMJD TBlStart
time of block's begin;
SBMJD TBlFinis
time of block's end;
FILE * EphemFile
file containing data;
bool IsOK
double * buff
buffer for a record;
double DT
a record's interval;
unsigned int NRecCoef
number of coefficients per record;
int NumRecs
number of records;
long FileOffset
file offset;
double AU
number of meters per astronomical unit
double CLight
Speed of light (m/s)
double EMRat
Earth-Moon mass ratio'.
const Entry * Loc
QString Name
Static Protected Attributes
static const Entry LocAbstract [13]
Friends
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Ephemerides LE/DE405'. LE/DE405 model implementation'. from nav's README (ftp://nav.jpl.nasa.gov/pub/ephem/export/README): "DE405 : (includes both nutations and librations)
JED 2305424'.50 (1599 DEC 09) to JED 2525008'.50 (2201 FEB 20)
Our latest ephemeris; it is based upon the International Celestial Reference Frame (ICRF)'. (DE200 is within 0'.01 arcseconds of the frame of the ICRF)'. DE405 was created in May-June 1997'."
Definition at line 285 of file SbGeoEphem.H'.
Constructor & Destructor Documentation
SBEphemDE405::SBEphemDE405 (const SBConfig *Cfg_)"A constructor'.
A constructor'. Creates a copy of object'.
Definition at line 707 of file SbGeoEphem.C'.
References SBEphem::AU, SBEphem::CLight, DAY2SEC, SBEphem::DT, SBEphem::Earth, SBEphem::EMRat, SBEphem::GeoMoon, SBCelestBody::gm(), SBEphem::initData(), SBEphem::Jupiter, SBEphem::Loc, SBEphem::Mars, SBEphem::Mercury, SBEphem::Moon, SBEphem::Neptun, SBEphem::NRecCoef, SBEphem::Pluto, SBEphem::Saturn, SBCelestBody::setGM(), SBEphem::Sun, SBEphem::Uran, and SBEphem::Venus.
Member Function Documentation
virtual double SBEphem::au () const [inline, virtual, inherited]"Returns number of meters per Astronomical unit used in this Ephemerides'.
Definition at line 161 of file SbGeoEphem.H'.
References SBEphem::AU.
Referenced by SBStuffEphem::SBStuffEphem(), SBTestEphem::SBTestEphem(), and SBStuffEphem::updateEphem().
const SBCelestBody& SBEphem::body (inti) [inline, inherited]"Returns i-th body state relative to the SSB i: 0(Mercury), 1(Venus), 2(Earth), 3(Mars), 4(Jupiter), 5(Saturn), 6(Uranus), 7(Neptune), 8(Pluto), 9(Moon), 10(Sun)'.
Definition at line 195 of file SbGeoEphem.H'.
References SBEphem::Solary.
Referenced by SBTestEphem::createWidget4Test(), SBTestEphem::displayCoo(), SBTestEphem::originChanged(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
void SBEphem::calc (const SBMJD &T) [virtual, inherited]"Calcs states of the celestial bodies for corresponded date'.
Definition at line 190 of file SbGeoEphem.C'.
References SBCelestBody::A, SBCelestBody::a(), SBEphem::buff, SBEphem::calcOffset(), SBEphem::ClassName(), SBLog::DBG, SBEphem::dt(), SBEphem::Earth, SBEphem::emRat(), SBLog::EPHEM, SBEphem::EphemFile, SBLog::ERR, SBMJD::F_Short, SBEphem::FileOffset, SBEphem::GeoMoon, SBEphem::interp(), SBLog::IO, SBCelestBody::IsEligible, SBLog::isEligible(), SBEphem::isOK(), SBEphem::Loc, Log, SBEphem::Moon, SBNamed::name(), SBEphem::nRecCoef(), SBCelestBody::R, SBCelestBody::r(), Vector3::report2Log(), SBCelestBody::setTCurrent(), SBEphem::Solary, SBEphem::TBlFinis, SBEphem::TBlStart, SBEphem::TFinis, SBMJD::toString(), SBEphem::TStart, SBCelestBody::V, SBCelestBody::v(), and SBLog::write().
Referenced by SBDelay::calc(), SBTestEphem::createWidget4Test(), SBTestSolidTides::fillData4Plotting(), and SBTestEphem::recalc().
void SBEphem::calcI (intI, const SBMJD &T) [virtual, inherited]"Calcs state of the i-th celestial body for corresponded date'.
Definition at line 271 of file SbGeoEphem.C'.
References SBCelestBody::A, SBEphem::buff, SBEphem::calcOffset(), SBEphem::ClassName(), SBEphem::dt(), SBEphem::Earth, SBEphem::emRat(), SBLog::EPHEM, SBEphem::EphemFile, SBLog::ERR, SBMJD::F_Short, SBEphem::FileOffset, SBEphem::GeoMoon, SBEphem::interp(), SBLog::IO, SBEphem::isOK(), SBEphem::Loc, Log, SBEphem::Moon, SBEphem::nRecCoef(), SBCelestBody::R, SBCelestBody::setTCurrent(), SBEphem::Solary, SBEphem::TBlFinis, SBEphem::TBlStart, SBEphem::TFinis, SBMJD::toString(), SBEphem::TStart, SBCelestBody::V, and SBLog::write().
virtual long SBEphem::calcOffset (const SBMJD &T) [inline, protected, virtual, inherited]"Calculates file offset for a corresponding time'.
Definition at line 138 of file SbGeoEphem.H'.
References SBEphem::dt(), SBEphem::TFinis, and SBEphem::TStart.
Referenced by SBEphem::calc(), and SBEphem::calcI().
virtual void SBEphem::checkData () [inline, protected, virtual, inherited]"Addition check of data'.
Definition at line 134 of file SbGeoEphem.H'.
References SBEphem::IsOK.
Referenced by SBEphem::openFile().
virtual QString SBEphemDE405::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBEphem'.
Definition at line 291 of file SbGeoEphem.H'.
virtual double SBEphem::cLight () const [inline, virtual, inherited]"Returns speed of light used in this Ephemerides'.
Definition at line 163 of file SbGeoEphem.H'.
References SBEphem::CLight.
Referenced by SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
virtual double SBEphem::dt () const [inline, virtual, inherited]"Returns time interval of a record'.
Definition at line 159 of file SbGeoEphem.H'.
References SBEphem::DT.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::calcOffset(), SBEphem::import(), SBEphem::interp(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
const SBCelestBody& SBEphem::earth () [inline, inherited]"Returns Earth (not E-M baricenter) state'.
Definition at line 172 of file SbGeoEphem.H'.
References SBEphem::Earth.
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), SBSolidTideLdIERS96::makeStep1(), and SBSolidTideLd::operator()().
virtual double SBEphem::emRat () const [inline, virtual, inherited]"Returns Earth-Moon mass ratio used in this Ephemerides'.
Definition at line 165 of file SbGeoEphem.H'.
References SBEphem::EMRat.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), SBSolidTideLdIERS96::makeStep1(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
virtual QString SBEphemDE405::fileName () const [inline, virtual]"Returns LE/DE403 file name'.
Reimplemented from SBEphem'.
Definition at line 293 of file SbGeoEphem.H'.
const SBCelestBody& SBEphem::geoMoon () [inline, inherited]"Returns Moon state (relative to the Geocenter)'.
Definition at line 188 of file SbGeoEphem.H'.
References SBEphem::GeoMoon.
Referenced by SBSolidTideLd::operator()().
bool SBEphem::import (const QString &ImpFName) [virtual, inherited]"Makes data imortation from the ASCII file'.
Definition at line 383 of file SbGeoEphem.C'.
References SBEphem::ClassName(), SBFCList::close(), SBLog::DBG, SBEphem::dt(), SBLog::EPHEM, SBEphem::EphemFile, SBLog::ERR, SBMJD::F_Short, SBSetUp::fcList(), SBEphem::fileName(), SBLog::IO, SBEphem::IsOK, SBEphem::isOK(), Log, mainMessage(), mainPrBarReset(), mainPrBarSetProgress(), mainPrBarSetTotalSteps(), SBEphem::nRecCoef(), SBEphem::numRecs(), SBFCList::open4In(), SBEphem::openFile(), SBSetUp::path2Stuff(), SetUp, SBEphem::tFinis(), SBMJD::toString(), SBEphem::tStart(), TZero, and SBLog::write().
Referenced by SBStuffEphem::import().
void SBEphem::initData () [protected, virtual, inherited]"Allocates buffer for one record, then calls openFile()'.
Definition at line 144 of file SbGeoEphem.C'.
References SBEphem::buff, SBEphem::ClassName(), SBLog::DBG, SBLog::EPHEM, Log, SBEphem::nRecCoef(), SBEphem::openFile(), and SBLog::write().
Referenced by SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
void SBEphem::interp (doubleT, intOffset, intNCo, intNSets, SBCelestBody &B) [protected, virtual, inherited]"Makes interpolation of a vector state for specified body'.
Definition at line 339 of file SbGeoEphem.C'.
References SBCelestBody::A, SBEphem::buff, DAY2SEC, SBEphem::dt(), SBCelestBody::R, and SBCelestBody::V.
Referenced by SBEphem::calc(), and SBEphem::calcI().
bool SBEphem::isOK () [inline, inherited]"Returns TRUE if data is OK'.
Definition at line 204 of file SbGeoEphem.H'.
References SBEphem::IsOK.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::import(), SBEphem::openFile(), SBTestEphem::recalc(), SBStuffEphem::SBStuffEphem(), SBStuffEphem::updateEphem(), and SBEphem::~SBEphem().
const SBCelestBody& SBEphem::jupiter () [inline, inherited]"Returns Jupiter state'.
Definition at line 176 of file SbGeoEphem.H'.
References SBEphem::Jupiter.
const SBCelestBody& SBEphem::mars () [inline, inherited]"Returns Mars state'.
Definition at line 174 of file SbGeoEphem.H'.
References SBEphem::Mars.
const SBCelestBody& SBEphem::mercury () [inline, inherited]"Returns Mercury state'.
Definition at line 168 of file SbGeoEphem.H'.
References SBEphem::Mercury.
const SBCelestBody& SBEphem::moon () [inline, inherited]"Returns Moon state (relative to the Solar System Barycenter)'.
Definition at line 186 of file SbGeoEphem.H'.
References SBEphem::Moon.
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
const SBCelestBody& SBEphem::neptun () [inline, inherited]"Returns Neptune state'.
Definition at line 182 of file SbGeoEphem.H'.
References SBEphem::Neptun.
virtual unsigned int SBEphem::nRecCoef () const [inline, virtual, inherited]"Returns number of coefficients (+2 time stamps)'.
Definition at line 198 of file SbGeoEphem.H'.
References SBEphem::NRecCoef.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::import(), SBEphem::initData(), SBEphem::openFile(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
int SBEphem::numRecs () [inline, inherited]"Returns number of records stored in the file'.
Definition at line 206 of file SbGeoEphem.H'.
References SBEphem::NumRecs.
Referenced by SBEphem::import(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
void SBEphem::openFile () [protected, virtual, inherited]"Opens binary file and checks it'.
Definition at line 152 of file SbGeoEphem.C'.
References SBEphem::buff, SBEphem::checkData(), SBEphem::ClassName(), SBLog::EPHEM, SBEphem::EphemFile, SBLog::ERR, SBMJD::F_Short, SBEphem::fileName(), SBEphem::FileOffset, SBLog::INF, SBLog::IO, SBEphem::isOK(), Log, SBNamed::name(), SBEphem::nRecCoef(), SBEphem::NumRecs, SBSetUp::path2Stuff(), SetUp, SBEphem::TBlFinis, SBEphem::TBlStart, SBEphem::TFinis, SBMJD::toString(), SBEphem::TStart, SBLog::write(), and SBLog::WRN.
Referenced by SBEphem::import(), and SBEphem::initData().
const SBCelestBody& SBEphem::pluto () [inline, inherited]"Returns Pluto state'.
Definition at line 184 of file SbGeoEphem.H'.
References SBEphem::Pluto.
const SBCelestBody& SBEphem::saturn () [inline, inherited]"Returns Saturn state'.
Definition at line 178 of file SbGeoEphem.H'.
References SBEphem::Saturn.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
const SBCelestBody& SBEphem::sun () [inline, inherited]"Returns Sun state'.
Definition at line 190 of file SbGeoEphem.H'.
References SBEphem::Sun.
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), SBSolidTideLdIERS96::makeStep1(), SBSolidTideLd::operator()(), SBStuffEphem::SBStuffEphem(), and SBStuffEphem::updateEphem().
const SBMJD& SBEphem::tFinis () [inline, inherited]"Returns the last available MJD'.
Definition at line 202 of file SbGeoEphem.H'.
References SBEphem::TFinis.
Referenced by SBEphem::import(), SBStuffEphem::SBStuffEphem(), SBTestEphem::SBTestEphem(), SBTestSolidTides::SBTestSolidTides(), and SBStuffEphem::updateEphem().
const SBMJD& SBEphem::tStart () [inline, inherited]"Returns the first available MJD'.
Definition at line 200 of file SbGeoEphem.H'.
References SBEphem::TStart.
Referenced by SBEphem::import(), SBStuffEphem::SBStuffEphem(), SBTestEphem::SBTestEphem(), SBTestSolidTides::SBTestSolidTides(), and SBStuffEphem::updateEphem().
const SBCelestBody& SBEphem::uran () [inline, inherited]"Returns Uranus state'.
Definition at line 180 of file SbGeoEphem.H'.
References SBEphem::Uran.
const SBCelestBody& SBEphem::venus () [inline, inherited]"Returns Venus state'.
Definition at line 170 of file SbGeoEphem.H'.
References SBEphem::Venus.
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
Member Data Documentation
double SBEphem::AU [protected, inherited]
number of meters per astronomical unit
Definition at line 116 of file SbGeoEphem.H'.
Referenced by SBEphem::au(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
double* SBEphem::buff [protected, inherited]
buffer for a record;
Definition at line 111 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::initData(), SBEphem::interp(), SBEphem::openFile(), and SBEphem::~SBEphem().
const SBConfig* SBEphem::Cfg [protected, inherited]
Definition at line 91 of file SbGeoEphem.H'.
Referenced by SBEphem::SBEphem().
double SBEphem::CLight [protected, inherited]
Speed of light (m/s)
Definition at line 117 of file SbGeoEphem.H'.
Referenced by SBEphem::cLight(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
double SBEphem::DT [protected, inherited]
a record's interval;
Definition at line 112 of file SbGeoEphem.H'.
Referenced by SBEphem::dt(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
SBCelestBody SBEphem::Earth [protected, inherited]
Earth'.
Definition at line 94 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::earth(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
double SBEphem::EMRat [protected, inherited]
Earth-Moon mass ratio'.
Definition at line 118 of file SbGeoEphem.H'.
Referenced by SBEphem::emRat(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
FILE* SBEphem::EphemFile [protected, inherited]
file containing data;
Definition at line 109 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::import(), SBEphem::openFile(), and SBEphem::~SBEphem().
long SBEphem::FileOffset [protected, inherited]
file offset;
Definition at line 115 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::openFile(), and SBEphem::SBEphem().
SBCelestBody SBEphem::GeoMoon [protected, inherited]
Geocentric Moon'.
Definition at line 103 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::geoMoon(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
bool SBEphem::IsOK [protected, inherited]
Definition at line 110 of file SbGeoEphem.H'.
Referenced by SBEphem::checkData(), SBEphem::import(), SBEphem::isOK(), and SBEphem::SBEphem().
SBCelestBody SBEphem::Jupiter [protected, inherited]
Jupiter'.
Definition at line 96 of file SbGeoEphem.H'.
Referenced by SBEphem::jupiter(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
const Entry* SBEphem::Loc [protected, inherited]
Definition at line 126 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
const SBEphem::Entry SBEphem::LocAbstract [static, protected, inherited]"Initial value:
{
  { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0},
  { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0},
  { 0, 0, 0}, { 0, 0, 0}, { 0, 0, 0}
}
Definition at line 127 of file SbGeoEphem.H'.
Referenced by SBEphem::SBEphem().
SBCelestBody SBEphem::Mars [protected, inherited]
Mars'.
Definition at line 95 of file SbGeoEphem.H'.
Referenced by SBEphem::mars(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
SBCelestBody SBEphem::Mercury [protected, inherited]
Mercury'.
Definition at line 92 of file SbGeoEphem.H'.
Referenced by SBEphem::mercury(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
SBCelestBody SBEphem::Moon [protected, inherited]
Moon'.
Definition at line 101 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::moon(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
SBCelestBody SBEphem::Neptun [protected, inherited]
Neptun'.
Definition at line 99 of file SbGeoEphem.H'.
Referenced by SBEphem::neptun(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
unsigned int SBEphem::NRecCoef [protected, inherited]
number of coefficients per record;
Definition at line 113 of file SbGeoEphem.H'.
Referenced by SBEphem::nRecCoef(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
int SBEphem::NumRecs [protected, inherited]
number of records;
Definition at line 114 of file SbGeoEphem.H'.
Referenced by SBEphem::numRecs(), SBEphem::openFile(), and SBEphem::SBEphem().
SBCelestBody SBEphem::Pluto [protected, inherited]
Pluto'.
Definition at line 100 of file SbGeoEphem.H'.
Referenced by SBEphem::pluto(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
SBCelestBody SBEphem::Saturn [protected, inherited]
Saturn'.
Definition at line 97 of file SbGeoEphem.H'.
Referenced by SBEphem::saturn(), SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), and SBEphemDE405().
SBCelestBody* SBEphem::Solary[11] [protected, inherited]
Definition at line 104 of file SbGeoEphem.H'.
Referenced by SBEphem::body(), SBEphem::calc(), SBEphem::calcI(), and SBEphem::SBEphem().
SBCelestBody SBEphem::Sun [protected, inherited]
Sun'.
Definition at line 102 of file SbGeoEphem.H'.
Referenced by SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), SBEphemDE405(), and SBEphem::sun().
SBMJD SBEphem::TBlFinis [protected, inherited]
time of block's end;
Definition at line 108 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), and SBEphem::openFile().
SBMJD SBEphem::TBlStart [protected, inherited]
time of block's begin;
Definition at line 107 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), and SBEphem::openFile().
SBMJD SBEphem::TFinis [protected, inherited]
time of the last entry of ephemerides
Definition at line 106 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::calcOffset(), SBEphem::openFile(), and SBEphem::tFinis().
SBMJD SBEphem::TStart [protected, inherited]
time of the first entry of ephemerides
Definition at line 105 of file SbGeoEphem.H'.
Referenced by SBEphem::calc(), SBEphem::calcI(), SBEphem::calcOffset(), SBEphem::openFile(), and SBEphem::tStart().
SBCelestBody SBEphem::Uran [protected, inherited]
Uran'.
Definition at line 98 of file SbGeoEphem.H'.
Referenced by SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), SBEphemDE405(), and SBEphem::uran().
SBCelestBody SBEphem::Venus [protected, inherited]
Venus'.
Definition at line 93 of file SbGeoEphem.H'.
Referenced by SBEphem::SBEphem(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), SBEphemDE405(), and SBEphem::venus().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.