.TH "SBEphem::Entry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBEphem::Entry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoEphem\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBOffset\fP"
.br
.RI "\fIstarting location in each data record of the coeff'\&. \fP"
.ti -1c
.RI "int \fBNCoef\fP"
.br
.RI "\fInumber of chebychev coefficients per component \fP"
.ti -1c
.RI "int \fBNSets\fP"
.br
.RI "\fInum'\&. of complete sets of coeff'\&. in each data record \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file SbGeoEphem\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBSBEphem::Entry::NCoef\fP"
.PP
number of chebychev coefficients per component 
.PP
Definition at line 122 of file SbGeoEphem\&.H'\&.
.SS "int \fBSBEphem::Entry::NSets\fP"
.PP
num'\&. of complete sets of coeff'\&. in each data record 
.PP
Definition at line 123 of file SbGeoEphem\&.H'\&.
.SS "int \fBSBEphem::Entry::Offset\fP"
.PP
starting location in each data record of the coeff'\&. 
.PP
Definition at line 121 of file SbGeoEphem\&.H'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
