.TH "SBEstimator::GroupList" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBEstimator::GroupList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoEstimator\&.H>\fP
.PP
Inherits \fBQList< Group >\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGroupList\fP ()"
.br
.ti -1c
.RI "\fBGroupList\fP (const \fBGroupList\fP &L_)"
.br
.ti -1c
.RI "\fBGroupList\fP & \fBoperator=\fP (const \fBGroupList\fP &)"
.br
.ti -1c
.RI "virtual \fB~GroupList\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual void \fBinSort\fP (const \fBGroup\fP *)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (const QString &)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (const \fBGroup\fP *)"
.br
.ti -1c
.RI "virtual \fBGroup\fP * \fBfind\fP (const \fBSBMJD\fP &t_) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item p1, QCollection::Item p2)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QDict< \fBGroup\fP > * \fBValByDate\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBremove\fP (uint idx_)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
SBMJDList'\&. List of MJDs, ordered by date value'\&. 
.PP
Definition at line 86 of file SbGeoEstimator\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBEstimator::GroupList::GroupList ()\fC [inline]\fP"A constructor'\&. Creates a copy of the object'\&. 
.PP
Definition at line 98 of file SbGeoEstimator\&.H'\&.
.PP
References ValByDate\&.
.SS "SBEstimator::GroupList::GroupList (const \fBGroupList\fP &L_)\fC [inline]\fP"A constructor'\&. Creates a copy of the object'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIL_\fP is value to copy in'\&. 
.RE
.PP

.PP
Definition at line 108 of file SbGeoEstimator\&.H'\&.
.SS "virtual SBEstimator::GroupList::~GroupList ()\fC [inline, virtual]\fP"A destructor'\&. 
.PP
Definition at line 111 of file SbGeoEstimator\&.H'\&.
.PP
References ValByDate\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBEstimator::GroupList::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info)'\&. 
.PP
Definition at line 113 of file SbGeoEstimator\&.H'\&.
.SS "virtual int SBEstimator::GroupList::compareItems (QCollection::Itemp1, QCollection::Itemp2)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 90 of file SbGeoEstimator\&.H'\&.
.SS "virtual \fBGroup\fP* SBEstimator::GroupList::find (const \fBSBMJD\fP &t_) const\fC [inline, virtual]\fP"
.PP
Definition at line 123 of file SbGeoEstimator\&.H'\&.
.PP
References SBMJD::F_INTERNAL, SBMJD::toString(), and ValByDate\&.
.SS "void SBEstimator::GroupList::inSort (const \fBGroup\fP *d)\fC [virtual]\fP"
.PP
Definition at line 103 of file SbGeoEstimator\&.C'\&.
.PP
References SBEstimator::ClassName(), SBLog::ERR, SBMJD::F_INTERNAL, Log, SBLog::TIME, SBMJD::toString(), and SBLog::write()\&.
.SS "\fBSBEstimator::GroupList\fP & SBEstimator::GroupList::operator= (const \fBGroupList\fP &L_)"
.PP
Definition at line 84 of file SbGeoEstimator\&.C'\&.
.SS "bool SBEstimator::GroupList::remove (const QString &key)\fC [virtual]\fP"
.PP
Definition at line 125 of file SbGeoEstimator\&.C'\&.
.PP
References SBEstimator::ClassName(), SBLog::ERR, SBParameterList::find(), Log, SBParameterList::remove(), SBLog::TIME, and SBLog::write()\&.
.SS "bool SBEstimator::GroupList::remove (const \fBGroup\fP *d)\fC [virtual]\fP"
.PP
Definition at line 139 of file SbGeoEstimator\&.C'\&.
.PP
References SBEstimator::ClassName(), SBLog::ERR, SBMJD::F_INTERNAL, Log, SBLog::TIME, SBMJD::toString(), and SBLog::write()\&.
.SS "virtual bool SBEstimator::GroupList::remove (uintidx_)\fC [inline, private, virtual]\fP"
.PP
Definition at line 127 of file SbGeoEstimator\&.H'\&.
.PP
References SBMJD::F_INTERNAL, remove(), and ValByDate\&.
.SS "virtual bool SBEstimator::GroupList::remove ()\fC [inline, private, virtual]\fP"
.PP
Definition at line 131 of file SbGeoEstimator\&.H'\&.
.PP
References SBMJD::F_INTERNAL, and ValByDate\&.
.PP
Referenced by remove()\&.
.SH "Member Data Documentation"
.PP 
.SS "QDict<\fBGroup\fP>* \fBSBEstimator::GroupList::ValByDate\fP\fC [protected]\fP"
.PP
Definition at line 89 of file SbGeoEstimator\&.H'\&.
.PP
Referenced by find(), GroupList(), remove(), and ~GroupList()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
