SBEstimator
NAME
SBEstimator -
SYNOPSIS
#include <SbGeoEstimator.H>
Classes
class Group
class GroupList
class SmoothCarrier
Public Member Functions
SBEstimator (SBProject *, SBRunManager *, SBSolution *)
virtual ~SBEstimator ()
virtual QString ClassName () const
virtual void prepare4Run (SBParameterList *)
virtual void parameterListsAboutToChange ()
virtual void parameterListsChanged ()
virtual void prepare4Local (int, const SBMJD &)
virtual void finisRun ()
virtual void finisLocal ()
virtual void processObs (const SBMJD &, const SBMJD &, const SBVector &, const SBVector &)
virtual void addParameter (const SBParameter *, const SBMJD &)
virtual void delParameter (const SBParameter *, const SBMJD &)
virtual void rearrangeGroups ()
virtual void prepare4GlobConstr (int)
virtual void processConstr (double, double)
virtual void processGlobalConstr (double, double)
virtual void finisGlobConstr ()
Private Member Functions
void moveGlobalInfo ()
void moveGlobalInfo_Old ()
void propagateStochasticPars (const SBMJD &, double)
void save4Smoothing ()
void dataUpdate ()
void dataUpdateGlobalConstr ()
void solveGlobals ()
void solveLocals ()
void solveStochs (const QString *, int)
QString workDir4Loc (const QString &BatchName_)
void collectContStochs4NextBatch ()
void mapContStochs4NewBatch (const SBMJD &)
Private Attributes
SBProject * Prj
project (not an owner of);
SBRunManager * RunMgr
run manager (not an owner of);
SBSolution * Solution
unsigned int NyAll
SBParameterList * YsAll
list of all global parameters;
SBVector * YAll
SBVector * ZyAll
SBUpperMatrix * RyAll
SBSymMatrix * PyAll
unsigned int Ny
SBParameterList * Ys
list of global parameters;
SBVector * Y
SBVector * Zy
SBUpperMatrix * Ry
SBSymMatrix * Py
unsigned int Nx
SBParameterList * Xs
list of local parameters;
SBVector * X
SBVector * Zx
SBUpperMatrix * Rx
SBMatrix * Rxy
SBSymMatrix * Px
SBMJD TofBatch
unsigned int Np
SBParameterList * Ps
list of stochastic parameters;
SBVector * P
SBVector * Zp
SBUpperMatrix * Rp
SBMatrix * Rpx
SBMatrix * Rpy
SBSymMatrix * Pp
SBMatrix * SR
SBUpperMatrix * Rp_s
SBMatrix * Rpp_s
SBMatrix * Rpx_s
SBMatrix * Rpy_s
SBVector * Zp_s
SBMJD TLastProcessed
unsigned int NStochsCont
SBParameterList * PsCont
SBVector * ZpCont
SBUpperMatrix * RpCont
SBMatrix * RpyCont
SBParameterList * PsAux
SBVector * PAux
SBSymMatrix * Pp_Aux
unsigned int Nz
SBVector * Z
SBMatrix * Ap
SBMatrix * Ax
SBMatrix * Ay
SBVector * U
QString WorkDir
QString BatchName
QFile file4Stoch
QDataStream stream4Stoch
FILE * pipe4Stoch
unsigned int NumOfStochs
QStack< QString > Stack
bool IsNeedRmTemp
Detailed Description
Class SBEstimator, describes estimator'.
Definition at line 53 of file SbGeoEstimator.H'.
Constructor & Destructor Documentation
SBEstimator::SBEstimator (SBProject *Prj_, SBRunManager *RunMgr_, SBSolution *Solution_)
Definition at line 159 of file SbGeoEstimator.C'.
References Ap, Ax, Ay, ClassName(), SBLog::ERR, SBLog::ESTIMATOR, IsNeedRmTemp, Log, SBNamed::name(), Np, NStochsCont, Nx, Ny, NyAll, Nz, P, SBSetUp::path2Work(), PAux, pipe4Stoch, Pp, Pp_Aux, Prj, Ps, PsAux, PsCont, Px, Py, PyAll, Rp, Rp_s, RpCont, Rpp_s, Rpx, Rpx_s, Rpy, Rpy_s, RpyCont, RunMgr, Rx, Rxy, Ry, RyAll, SBVersion::selfName(), SetUp, Solution, SR, TLastProcessed, TZero, U, Version, WorkDir, SBLog::write(), X, Xs, Y, YAll, Ys, YsAll, Z, Zp, Zp_s, ZpCont, Zx, Zy, and ZyAll.
SBEstimator::~SBEstimator () [virtual]
Definition at line 241 of file SbGeoEstimator.C'.
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, SBLog::IO, IsNeedRmTemp, Log, WorkDir, and SBLog::write().
Member Function Documentation
void SBEstimator::addParameter (const SBParameter *, const SBMJD &) [virtual]
Definition at line 278 of file SbGeoEstimator.C'.
virtual QString SBEstimator::ClassName () const [inline, virtual]
Definition at line 276 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), dataUpdate(), dataUpdateGlobalConstr(), SBEstimator::GroupList::inSort(), mapContStochs4NewBatch(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Local(), SBEstimator::GroupList::remove(), SBEstimator(), solveGlobals(), solveLocals(), solveStochs(), and ~SBEstimator().
void SBEstimator::collectContStochs4NextBatch () [private]
Definition at line 1636 of file SbGeoEstimator.C'.
References SBParameterList::append(), SBMatrix::at(), ClassName(), SBParameterList::clear(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBParameterList::idx(), Log, SBNamed::name(), Np, Ny, NyAll, Ps, PsCont, Rp, RpCont, Rpy, RpyCont, SBMatrix::set(), SBLog::write(), Ys, YsAll, Zp, and ZpCont.
Referenced by finisLocal().
void SBEstimator::dataUpdate () [private]
Definition at line 1187 of file SbGeoEstimator.C'.
References SBStatistics::addNumObs(), SBStatistics::addWPFR(), Ap, SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), Ax, Ay, ClassName(), SBVector::clear(), SBLog::ERR, SBLog::ESTIMATOR, Log, Np, Nx, Ny, Nz, Rp, Rpx, Rpy, Rx, Rxy, Ry, SBVector::set(), SBUpperMatrix::set(), sign(), Solution, SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), U, SBLog::write(), Z, Zp, Zx, and Zy.
Referenced by finisLocal(), processConstr(), and processObs().
void SBEstimator::dataUpdateGlobalConstr () [private]
Definition at line 1319 of file SbGeoEstimator.C'.
References SBStatistics::addNumObs(), SBStatistics::addWPFR(), Ap, SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), Ax, Ay, ClassName(), SBVector::clear(), SBLog::ERR, SBLog::ESTIMATOR, Log, Np, Nx, NyAll, Nz, Rp, Rpx, Rpy, Rx, Rxy, RyAll, SBVector::set(), SBUpperMatrix::set(), sign(), Solution, SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), U, SBLog::write(), Z, Zp, Zx, and ZyAll.
Referenced by processGlobalConstr().
void SBEstimator::delParameter (const SBParameter *, const SBMJD &) [virtual]
Definition at line 291 of file SbGeoEstimator.C'.
void SBEstimator::finisGlobConstr () [virtual]
Definition at line 1100 of file SbGeoEstimator.C'.
References Ay, Nz, U, and Z.
Referenced by SBRunManager::process_m1().
void SBEstimator::finisLocal () [virtual]
Definition at line 423 of file SbGeoEstimator.C'.
References Ap, Ax, Ay, BatchName, SBProject::cfg(), SBFCList::close(), collectContStochs4NextBatch(), dataUpdate(), SBSetUp::fcList(), file4Stoch, SBConfig::isGenerateDSINEXes(), SBDerivation::IsPropagated, moveGlobalInfo(), Np, NStochsCont, NumOfStochs, Nx, Ny, Nz, SBFCList::open4Out(), pipe4Stoch, Prj, Ps, Rp, Rp_s, Rpp_s, Rpx, Rpx_s, Rpy, Rpy_s, Rx, Rxy, Ry, SBSolution::saveNormalEqs(), SetUp, Solution, SR, Stack, stream4Stoch, TofBatch, U, workDir4Loc(), Xs, Ys, Z, Zp, Zp_s, Zx, and Zy.
Referenced by SBRunManager::process_m1().
void SBEstimator::finisRun () [virtual]
Definition at line 514 of file SbGeoEstimator.C'.
References NyAll, PsCont, PyAll, RyAll, solveGlobals(), Stack, YAll, YsAll, and ZyAll.
Referenced by SBRunManager::finisRun_m1(), and SBRunManager::finisRun_m2().
void SBEstimator::mapContStochs4NewBatch (const SBMJD &Tnew) [private]
Definition at line 1689 of file SbGeoEstimator.C'.
References SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), BatchName, ClassName(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBParameterList::idx(), SBDerivation::IsPropagated, Log, SBParameter::m(), SBNamed::name(), Ny, NyAll, Ps, PsCont, Rp, RpCont, Rpy, RpyCont, SBParameter::rw(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), TLastProcessed, workDir4Loc(), SBLog::write(), Ys, YsAll, Zp, and ZpCont.
Referenced by prepare4Local().
void SBEstimator::moveGlobalInfo () [private]
Definition at line 1452 of file SbGeoEstimator.C'.
References SBStatistics::addWPFR(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), ClassName(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBParameterList::idx(), Log, SBNamed::name(), Ny, NyAll, Ry, RyAll, SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), Solution, SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), SBLog::write(), Ys, YsAll, Zy, and ZyAll.
Referenced by finisLocal().
void SBEstimator::moveGlobalInfo_Old () [private]
Definition at line 1554 of file SbGeoEstimator.C'.
References SBStatistics::addWPFR(), SBVector::at(), SBUpperMatrix::at(), ClassName(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBParameterList::idx(), Log, SBNamed::name(), Ny, NyAll, Ry, RyAll, SBVector::set(), SBUpperMatrix::set(), sign(), Solution, SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), SBLog::write(), Ys, YsAll, Zy, and ZyAll.
void SBEstimator::parameterListsAboutToChange () [virtual]
Definition at line 256 of file SbGeoEstimator.C'.
Referenced by SBRunManager::checkParameterLists().
void SBEstimator::parameterListsChanged () [virtual]
Definition at line 263 of file SbGeoEstimator.C'.
Referenced by SBRunManager::checkParameterLists().
void SBEstimator::prepare4GlobConstr (intNz_) [virtual]
Definition at line 1088 of file SbGeoEstimator.C'.
References Ay, NumOfStochs, NyAll, Nz, U, and Z.
Referenced by SBRunManager::process_m1().
void SBEstimator::prepare4Local (intNz_, const SBMJD &T_) [virtual]
Definition at line 341 of file SbGeoEstimator.C'.
References Ap, Ax, Ay, BatchName, ClassName(), SBParameterList::clearPValues(), SBParameterList::clearPValues_aux(), SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), file4Stoch, SBRunManager::globalList(), SBRunManager::listOfCurrentSessNames(), SBRunManager::localList(), Log, mapContStochs4NewBatch(), SBNamed::name(), Np, NStochsCont, NumOfStochs, Nx, Ny, Nz, SBFCList::open4Out(), pipe4Stoch, Prj, Ps, Rp, Rp_s, Rpp_s, Rpx, Rpx_s, Rpy, Rpy_s, RunMgr, Rx, Rxy, Ry, SBVersion::selfName(), SBUpperMatrix::set(), SetUp, SR, SBRunManager::stochList(), stream4Stoch, TofBatch, U, Version, workDir4Loc(), SBLog::write(), Xs, Ys, Z, Zp, Zp_s, Zx, and Zy.
Referenced by SBRunManager::process_m1().
void SBEstimator::prepare4Run (SBParameterList *AllGlobalList_) [virtual]
Definition at line 324 of file SbGeoEstimator.C'.
References SBParameterList::clearPValues(), NyAll, PsCont, RyAll, SBUpperMatrix::set(), Stack, YsAll, and ZyAll.
Referenced by SBRunManager::prepare4Run_m1(), and SBRunManager::prepare4Run_m2().
void SBEstimator::processConstr (doubleO_C, doubleSigma) [virtual]
Definition at line 1002 of file SbGeoEstimator.C'.
References SBStatistics::addNumConstr(), Ap, Ax, Ay, SBDerivation::d(), dataUpdate(), Np, Nx, Ny, Nz, Ps, SBVector::set(), SBMatrix::set(), Solution, SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), Xs, Ys, Z, and SBDerivation::zero().
Referenced by SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), and SBRunManager::constraintStationVeloc().
void SBEstimator::processGlobalConstr (doubleO_C, doubleSigma) [virtual]
Definition at line 1045 of file SbGeoEstimator.C'.
References SBStatistics::addNumConstr(), Ap, Ax, Ay, SBDerivation::d(), dataUpdateGlobalConstr(), Np, Nx, NyAll, Nz, Ps, SBVector::set(), SBMatrix::set(), Solution, SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), Xs, YsAll, Z, and SBDerivation::zero().
Referenced by SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), and SBRunManager::constraintStationVeloc().
void SBEstimator::processObs (const SBMJD &T, const SBMJD &Tnext, const SBVector &O_C, const SBVector &Sigma) [virtual]
Definition at line 952 of file SbGeoEstimator.C'.
References SBStatistics::addWRMS(), Ap, SBVector::at(), Ax, Ay, SBParameterList::clearPValues(), SBDerivation::d(), dataUpdate(), Np, Nx, Ny, Nz, propagateStochasticPars(), Ps, save4Smoothing(), SBVector::set(), SBMatrix::set(), Solution, SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), TLastProcessed, Xs, Ys, Z, and SBDerivation::zero().
Referenced by SBRunManager::process_m1().
void SBEstimator::propagateStochasticPars (const SBMJD &, doubledT) [private]
Definition at line 1111 of file SbGeoEstimator.C'.
References SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBVector::clear(), SBMatrix::clear(), SBParameter::m(), Np, Nx, Ny, Ps, Rp, Rp_s, Rpp_s, Rpx, Rpx_s, Rpy, Rpy_s, SBParameter::rw(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), SR, U, Zp, and Zp_s.
Referenced by processObs().
void SBEstimator::rearrangeGroups () [virtual]
Definition at line 310 of file SbGeoEstimator.C'.
void SBEstimator::save4Smoothing () [inline, private]
Definition at line 259 of file SbGeoEstimator.H'.
References NumOfStochs, Ps, Rp_s, Rpp_s, Rpx_s, Rpy_s, stream4Stoch, and Zp_s.
Referenced by processObs().
void SBEstimator::solveGlobals () [private]
Definition at line 535 of file SbGeoEstimator.C'.
References ClassName(), SBLog::DBG, SBLog::ESTIMATOR, Log, NyAll, PsAux, PsCont, PyAll, SBSolution::reportGlobalParameters(), RRT(), RyAll, Solution, Solve(), solveLocals(), SBSolution::submitGlobalParameters(), SBParameterList::updateSolution(), SBLog::write(), YAll, YsAll, and ZyAll.
Referenced by finisRun().
void SBEstimator::solveLocals () [private]
Definition at line 575 of file SbGeoEstimator.C'.
References SBVector::at(), SBSymMatrix::at(), ClassName(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), SBParameterList::idx(), SBLog::IO, IsNeedRmTemp, Log, SBNamed::name(), NStochsCont, NumOfStochs, Nx, Ny, SBFCList::open4In(), SBSolution::prepare4Batch(), Px, Py, PyAll, QuadraticForm(), SBSolution::reportLocalParameters(), RRT(), Rx, Rxy, SBVector::set(), SBUpperMatrix::set(), SBStatistics::setTStart(), SetUp, Solution, Solve(), solveStochs(), Stack, SBSolution::stat4CurrentBatch(), SBSolution::submitLocalParameters(), TofBatch, SBParameterList::updateSolution(), workDir4Loc(), SBLog::write(), X, Xs, Y, YAll, Ys, YsAll, and Zx.
Referenced by solveGlobals().
void SBEstimator::solveStochs (const QString *wd, intNum) [private]
Definition at line 683 of file SbGeoEstimator.C'.
References SBParameterList::append(), SBVector::at(), SBSymMatrix::at(), ClassName(), SBParameterList::clear(), SBUpperMatrix::clear(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), file4Stoch, SBParameterList::idx(), SBLog::IO, IsNeedRmTemp, SBDerivation::IsPropagated, SBEstimator::SmoothCarrier::load(), Log, Np, NStochsCont, Nx, Ny, SBFCList::open4In(), P, PAux, pipe4Stoch, Pp, Pp_Aux, SBEstimator::SmoothCarrier::Ps, Ps, PsAux, PsCont, Px, Py, QuadraticForm(), SBSolution::reportStochasticParameters(), Rp, SBEstimator::SmoothCarrier::Rp_s, Rp_s, SBEstimator::SmoothCarrier::Rpp_s, Rpp_s, Rpx, SBEstimator::SmoothCarrier::Rpx_s, Rpx_s, Rpy, SBEstimator::SmoothCarrier::Rpy_s, Rpy_s, RRT(), SBSolution::saveStochasticParameters(), SBVector::set(), SBUpperMatrix::set(), SetUp, Solution, Solve(), stream4Stoch, SBSolution::submitStochasticParameters(), SBUpperMatrix::T(), workDir4Loc(), SBLog::write(), X, Y, YAll, Zp, SBEstimator::SmoothCarrier::Zp_s, and Zp_s.
Referenced by solveLocals().
QString SBEstimator::workDir4Loc (const QString &BatchName_) [inline, private]
Definition at line 266 of file SbGeoEstimator.H'.
References WorkDir.
Referenced by finisLocal(), mapContStochs4NewBatch(), prepare4Local(), solveLocals(), and solveStochs().
Member Data Documentation
SBMatrix* SBEstimator::Ap [private]
Definition at line 239 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), and SBEstimator().
SBMatrix* SBEstimator::Ax [private]
Definition at line 240 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), and SBEstimator().
SBMatrix* SBEstimator::Ay [private]
Definition at line 241 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisGlobConstr(), finisLocal(), prepare4GlobConstr(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), and SBEstimator().
QString SBEstimator::BatchName [private]
Definition at line 246 of file SbGeoEstimator.H'.
Referenced by finisLocal(), mapContStochs4NewBatch(), and prepare4Local().
QFile SBEstimator::file4Stoch [private]
Definition at line 247 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), and solveStochs().
bool SBEstimator::IsNeedRmTemp [private]
Definition at line 253 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), solveLocals(), solveStochs(), and ~SBEstimator().
unsigned int SBEstimator::Np [private]
Definition at line 209 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), propagateStochasticPars(), SBEstimator(), and solveStochs().
unsigned int SBEstimator::NStochsCont [private]
Definition at line 226 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), SBEstimator(), solveLocals(), and solveStochs().
unsigned int SBEstimator::NumOfStochs [private]
Definition at line 250 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4GlobConstr(), prepare4Local(), save4Smoothing(), and solveLocals().
unsigned int SBEstimator::Nx [private]
Definition at line 199 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), propagateStochasticPars(), SBEstimator(), solveLocals(), and solveStochs().
unsigned int SBEstimator::Ny [private]
Definition at line 190 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), dataUpdate(), finisLocal(), mapContStochs4NewBatch(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Local(), processConstr(), processObs(), propagateStochasticPars(), SBEstimator(), solveLocals(), and solveStochs().
unsigned int SBEstimator::NyAll [private]
Definition at line 183 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), dataUpdateGlobalConstr(), finisRun(), mapContStochs4NewBatch(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4GlobConstr(), prepare4Run(), processGlobalConstr(), SBEstimator(), and solveGlobals().
unsigned int SBEstimator::Nz [private]
Definition at line 237 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisGlobConstr(), finisLocal(), prepare4GlobConstr(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), and SBEstimator().
SBVector* SBEstimator::P [private]
Definition at line 211 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), and solveStochs().
SBVector* SBEstimator::PAux [private]
Definition at line 232 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), and solveStochs().
FILE* SBEstimator::pipe4Stoch [private]
Definition at line 249 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), SBEstimator(), and solveStochs().
SBSymMatrix* SBEstimator::Pp [private]
Definition at line 216 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), and solveStochs().
SBSymMatrix* SBEstimator::Pp_Aux [private]
Definition at line 233 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), and solveStochs().
SBProject* SBEstimator::Prj [private]
project (not an owner of);
Definition at line 175 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), and SBEstimator().
SBParameterList* SBEstimator::Ps [private]
list of stochastic parameters;
Definition at line 210 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), finisLocal(), mapContStochs4NewBatch(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), propagateStochasticPars(), save4Smoothing(), SBEstimator(), and solveStochs().
SBParameterList* SBEstimator::PsAux [private]
Definition at line 231 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), solveGlobals(), and solveStochs().
SBParameterList* SBEstimator::PsCont [private]
Definition at line 227 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), finisRun(), mapContStochs4NewBatch(), prepare4Run(), SBEstimator(), solveGlobals(), and solveStochs().
SBSymMatrix* SBEstimator::Px [private]
Definition at line 205 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), solveLocals(), and solveStochs().
SBSymMatrix* SBEstimator::Py [private]
Definition at line 195 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), solveLocals(), and solveStochs().
SBSymMatrix* SBEstimator::PyAll [private]
Definition at line 188 of file SbGeoEstimator.H'.
Referenced by finisRun(), SBEstimator(), solveGlobals(), and solveLocals().
SBUpperMatrix* SBEstimator::Rp [private]
Definition at line 213 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), mapContStochs4NewBatch(), prepare4Local(), propagateStochasticPars(), SBEstimator(), and solveStochs().
SBUpperMatrix* SBEstimator::Rp_s [private]
Definition at line 219 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), propagateStochasticPars(), save4Smoothing(), SBEstimator(), and solveStochs().
SBUpperMatrix* SBEstimator::RpCont [private]
Definition at line 229 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), mapContStochs4NewBatch(), and SBEstimator().
SBMatrix* SBEstimator::Rpp_s [private]
Definition at line 220 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), propagateStochasticPars(), save4Smoothing(), SBEstimator(), and solveStochs().
SBMatrix* SBEstimator::Rpx [private]
Definition at line 214 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), propagateStochasticPars(), SBEstimator(), and solveStochs().
SBMatrix* SBEstimator::Rpx_s [private]
Definition at line 221 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), propagateStochasticPars(), save4Smoothing(), SBEstimator(), and solveStochs().
SBMatrix* SBEstimator::Rpy [private]
Definition at line 215 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), mapContStochs4NewBatch(), prepare4Local(), propagateStochasticPars(), SBEstimator(), and solveStochs().
SBMatrix* SBEstimator::Rpy_s [private]
Definition at line 222 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), propagateStochasticPars(), save4Smoothing(), SBEstimator(), and solveStochs().
SBMatrix* SBEstimator::RpyCont [private]
Definition at line 230 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), mapContStochs4NewBatch(), and SBEstimator().
SBRunManager* SBEstimator::RunMgr [private]
run manager (not an owner of);
Definition at line 176 of file SbGeoEstimator.H'.
Referenced by prepare4Local(), and SBEstimator().
SBUpperMatrix* SBEstimator::Rx [private]
Definition at line 203 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), SBEstimator(), and solveLocals().
SBMatrix* SBEstimator::Rxy [private]
Definition at line 204 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), SBEstimator(), and solveLocals().
SBUpperMatrix* SBEstimator::Ry [private]
Definition at line 194 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), finisLocal(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Local(), and SBEstimator().
SBUpperMatrix* SBEstimator::RyAll [private]
Definition at line 187 of file SbGeoEstimator.H'.
Referenced by dataUpdateGlobalConstr(), finisRun(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Run(), SBEstimator(), and solveGlobals().
SBSolution* SBEstimator::Solution [private]
Definition at line 177 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), moveGlobalInfo(), moveGlobalInfo_Old(), processConstr(), processGlobalConstr(), processObs(), SBEstimator(), solveGlobals(), solveLocals(), and solveStochs().
SBMatrix* SBEstimator::SR [private]
Definition at line 217 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), propagateStochasticPars(), and SBEstimator().
QStack<QString> SBEstimator::Stack [private]
Definition at line 251 of file SbGeoEstimator.H'.
Referenced by finisLocal(), finisRun(), prepare4Run(), and solveLocals().
QDataStream SBEstimator::stream4Stoch [private]
Definition at line 248 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), save4Smoothing(), and solveStochs().
SBMJD SBEstimator::TLastProcessed [private]
Definition at line 225 of file SbGeoEstimator.H'.
Referenced by mapContStochs4NewBatch(), processObs(), and SBEstimator().
SBMJD SBEstimator::TofBatch [private]
Definition at line 206 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), and solveLocals().
SBVector* SBEstimator::U [private]
Definition at line 242 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisGlobConstr(), finisLocal(), prepare4GlobConstr(), prepare4Local(), propagateStochasticPars(), and SBEstimator().
QString SBEstimator::WorkDir [private]
Definition at line 245 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), workDir4Loc(), and ~SBEstimator().
SBVector* SBEstimator::X [private]
Definition at line 201 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), solveLocals(), and solveStochs().
SBParameterList* SBEstimator::Xs [private]
list of local parameters;
Definition at line 200 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), SBEstimator(), and solveLocals().
SBVector* SBEstimator::Y [private]
Definition at line 192 of file SbGeoEstimator.H'.
Referenced by SBEstimator(), solveLocals(), and solveStochs().
SBVector* SBEstimator::YAll [private]
Definition at line 185 of file SbGeoEstimator.H'.
Referenced by finisRun(), SBEstimator(), solveGlobals(), solveLocals(), and solveStochs().
SBParameterList* SBEstimator::Ys [private]
list of global parameters;
Definition at line 191 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), finisLocal(), mapContStochs4NewBatch(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Local(), processConstr(), processObs(), SBEstimator(), and solveLocals().
SBParameterList* SBEstimator::YsAll [private]
list of all global parameters;
Definition at line 184 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), finisRun(), mapContStochs4NewBatch(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Run(), processGlobalConstr(), SBEstimator(), solveGlobals(), and solveLocals().
SBVector* SBEstimator::Z [private]
Definition at line 238 of file SbGeoEstimator.H'.
Referenced by SBEstimator::Group::afterRun(), SBEstimator::Group::beforeRun(), dataUpdate(), dataUpdateGlobalConstr(), finisGlobConstr(), finisLocal(), prepare4GlobConstr(), prepare4Local(), processConstr(), processGlobalConstr(), processObs(), and SBEstimator().
SBVector* SBEstimator::Zp [private]
Definition at line 212 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), mapContStochs4NewBatch(), prepare4Local(), propagateStochasticPars(), SBEstimator(), and solveStochs().
SBVector* SBEstimator::Zp_s [private]
Definition at line 223 of file SbGeoEstimator.H'.
Referenced by finisLocal(), prepare4Local(), propagateStochasticPars(), save4Smoothing(), SBEstimator(), and solveStochs().
SBVector* SBEstimator::ZpCont [private]
Definition at line 228 of file SbGeoEstimator.H'.
Referenced by collectContStochs4NextBatch(), mapContStochs4NewBatch(), and SBEstimator().
SBVector* SBEstimator::Zx [private]
Definition at line 202 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), dataUpdateGlobalConstr(), finisLocal(), prepare4Local(), SBEstimator(), and solveLocals().
SBVector* SBEstimator::Zy [private]
Definition at line 193 of file SbGeoEstimator.H'.
Referenced by dataUpdate(), finisLocal(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Local(), and SBEstimator().
SBVector* SBEstimator::ZyAll [private]
Definition at line 186 of file SbGeoEstimator.H'.
Referenced by dataUpdateGlobalConstr(), finisRun(), moveGlobalInfo(), moveGlobalInfo_Old(), prepare4Run(), SBEstimator(), and solveGlobals().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.