SBEstimator::Group
NAME
SBEstimator::Group -
SYNOPSIS
#include <SbGeoEstimator.H>
Inherits SBParameterList, and SBMJD'.
Public Types
enum Format { F_YYYYMMDD, F_DDMonYYYY, F_Short, F_Long, F_Year, F_YYMonDD, F_HHMMSS, F_YYYYMMDDSSSSSS, F_INTERNAL, F_YYYYMMDDHHMMSSSS, F_DateShort, F_TimeShort, F_TimeVShort, F_ECCDAT, F_MJD, F_UNIX, F_SINEX, F_SINEX_S }
Public Member Functions
Group (const SBMJD &=TZero)
~Group ()
void addParameter (const SBParameter *)
void delParameter (const SBParameter *)
void beforeRun (int, GroupList *)
void afterRun (int, GroupList *)
const SBMJD & ttl ()
virtual QString ClassName () const
virtual void append (const SBParameter *)
virtual void inSort (const SBParameter *)
virtual bool remove (const QString &)
virtual SBParameter * find (const QString &p_) const
virtual int idx (const SBParameter *p_)
virtual int idx (const QString &p_)
virtual void clear ()
virtual void updateSolution (const SBVector *, const SBSymMatrix *)
virtual void report ()
virtual void clearPValues ()
virtual void clearPValues_aux ()
virtual QString ClassName () const
virtual void setMJD (int, int, int, int=0, int=0, double=0.0, bool=TRUE)
virtual void setMJD (Format, QString, bool=TRUE)
virtual void setDate (int Date_)
virtual void setTime (long double Time_)
virtual QString toString (Format=F_Short) const
virtual bool isGood ()
virtual operator long double () const
virtual bool operator== (const SBMJD &) const
virtual bool operator!= (const SBMJD &) const
virtual bool operator< (const SBMJD &) const
virtual bool operator<= (const SBMJD &) const
virtual bool operator> (const SBMJD &) const
virtual bool operator> (double) const
virtual bool operator>= (const SBMJD &) const
virtual SBMJD & operator+= (const SBMJD &MJD)
virtual SBMJD & operator-= (const SBMJD &MJD)
int date () const
long double time () const
int year () const
int month () const
int hour () const
int min () const
double sec () const
QString month2Str () const
int day () const
int dayOfYear () const
int dayOfWeek () const
QString dayOfWeek2Str () const
Static Public Member Functions
static int MJD_date (int, int, int)
static long double MJD_time (int, int, double)
static void MJD_rev (int, long double, int &, int &, int &, int &, int &, double &)
static SBMJD currentMJD ()
Protected Member Functions
virtual int compareItems (QCollection::Item p1, QCollection::Item p2)
virtual QDataStream & write (QDataStream &s, QCollection::Item E) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &E)
Protected Attributes
SBUpperMatrix * R
diagonal matrix for the set of par-s'.
QList< SBMatrix > * CrossCorr
the list of non-diagonal matrices;
SBVector * Z
z-vector corresponded to the set of par-s;
QDict< SBParameter > * ParByName
Static Protected Attributes
static const char * monthNames []
static const char * weekdayNames []
Friends
QDataStream & operator<< (QDataStream &, const SBParameterList &)
QDataStream & operator>> (QDataStream &, SBParameterList &)
SBMJD operator+ (const SBMJD &, const SBMJD &)
SBMJD operator+ (const SBMJD &, long double)
SBMJD operator+ (const SBMJD &, double)
SBMJD operator+ (const SBMJD &, float)
SBMJD operator+ (long double, const SBMJD &)
SBMJD operator+ (double, const SBMJD &)
SBMJD operator+ (float, const SBMJD &)
SBMJD operator- (const SBMJD &, const SBMJD &)
SBMJD operator- (const SBMJD &, long double)
SBMJD operator- (const SBMJD &, double)
SBMJD operator- (long double, const SBMJD &)
SBMJD operator- (int, const SBMJD &)
QDataStream & operator<< (QDataStream &, const SBMJD &)
QDataStream & operator>> (QDataStream &, SBMJD &)
Related Functions
(Note that these are not member functions'.)
QDataStream & operator>> (QDataStream &s, SBStochParameterList &P)
Detailed Description
Class SBEstimator::Group introduces a part of the information array'. It is assumed that elements of the information array are separated on the basis of the TTL value'.
Definition at line 61 of file SbGeoEstimator.H'.
Member Enumeration Documentation
enum SBMJD::Format [inherited]
Enumerator:
F_YYYYMMDD
F_DDMonYYYY
F_Short
F_Long
F_Year
F_YYMonDD
F_HHMMSS
F_YYYYMMDDSSSSSS
F_INTERNAL
F_YYYYMMDDHHMMSSSS
F_DateShort
F_TimeShort
F_TimeVShort
F_ECCDAT
F_MJD
F_UNIX
F_SINEX
F_SINEX_S
Definition at line 49 of file SbGeoTime.H'.
Constructor & Destructor Documentation
SBEstimator::Group::Group (const SBMJD &TTL_ = TZero)
Definition at line 39 of file SbGeoEstimator.C'.
SBEstimator::Group::~Group ()
Definition at line 44 of file SbGeoEstimator.C'.
Member Function Documentation
void SBEstimator::Group::addParameter (const SBParameter *P)"Adds a parameter for the set'.
Definition at line 48 of file SbGeoEstimator.C'.
References SBParameterList::inSort().
void SBEstimator::Group::afterRun (int, GroupList *)"Finishes the set and aux data after running'.
Definition at line 69 of file SbGeoEstimator.C'.
References SBEstimator::Z.
void SBParameterList::append (const SBParameter *p) [virtual, inherited]
Definition at line 548 of file SbGeoParameter.C'.
References SBParameterList::ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBNamed::name(), SBParameterList::ParByName, and SBLog::write().
Referenced by SBEstimator::collectContStochs4NextBatch(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::solveStochs(), and writeNormalEquationSystem().
void SBEstimator::Group::beforeRun (intNumInGroups, GroupList *groups)"Prepares the set and aux data for running'.
Definition at line 58 of file SbGeoEstimator.C'.
References SBEstimator::Z.
virtual QString SBMJD::ClassName () const [inline, virtual, inherited]
Reimplemented in SBObsVLBIEntry, SBCoordinates, SBTropRecord, SBTime, SBParameterBreak, SBEOPEntry, SBObservation, and SBAploDRec'.
Definition at line 74 of file SbGeoTime.H'.
Referenced by SBMJD::setMJD().
virtual QString SBParameterList::ClassName () const [inline, virtual, inherited]"Refers to a class name (debug info)'.
Definition at line 506 of file SbGeoParameter.H'.
Referenced by SBParameterList::append(), SBParameterList::inSort(), SBParameterList::remove(), SBParameterList::report(), and SBParameterList::updateSolution().
virtual void SBParameterList::clear () [inline, virtual, inherited]
Definition at line 521 of file SbGeoParameter.H'.
Referenced by SBEstimator::collectContStochs4NextBatch(), SBRunManager::fillParameterList(), SBSolution::loadGlbCor(), SBSolution::loadGlbPar(), SBSolution::loadLocCor(), SBSolution::loadLocPar(), SBSolution::loadNormalEqs(), SBParameterList::operator=(), SBSolution::SBSolution(), SBEstimator::solveStochs(), and writeNormalEquationSystem().
void SBParameterList::clearPValues () [virtual, inherited]
Definition at line 661 of file SbGeoParameter.C'.
Referenced by SBEstimator::prepare4Local(), SBEstimator::prepare4Run(), and SBEstimator::processObs().
void SBParameterList::clearPValues_aux () [virtual, inherited]
Definition at line 667 of file SbGeoParameter.C'.
Referenced by SBEstimator::prepare4Local().
virtual int SBParameterList::compareItems (QCollection::Itemp1, QCollection::Itemp2) [inline, protected, virtual, inherited]
Definition at line 474 of file SbGeoParameter.H'.
References SBParameter::str4compare().
SBMJD SBMJD::currentMJD () [static, inherited]
Definition at line 134 of file SbGeoTime.C'.
Referenced by operator<<(), SBRunManager::process_m1(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and writeNormalEquationSystem().
int SBMJD::date () const [inline, inherited]
Definition at line 121 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBNutation::calcGST(), SBTime::DefineTAI_UTC(), SBRunManager::loadVLBISession_m1(), operator<<(), operator>>(), SBTestEphem::recalc(), and SBTime::setUTC().
int SBMJD::day () const [inherited]
Definition at line 208 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), operator<<(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
int SBMJD::dayOfWeek () const [inherited]
Definition at line 225 of file SbGeoTime.C'.
References SBMJD::Date, and SBMJD::SBMJD().
Referenced by SBMJD::dayOfWeek2Str().
QString SBMJD::dayOfWeek2Str () const [inherited]
Definition at line 231 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::dayOfWeek(), and SBMJD::weekdayNames.
Referenced by SBMJD::toString().
int SBMJD::dayOfYear () const [inherited]
Definition at line 220 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), and SBMJD::year().
Referenced by SBHMf_NMF::operator()(), and SBMJD::toString().
void SBEstimator::Group::delParameter (const SBParameter *P)"Deletes a parameter from the set'.
Definition at line 53 of file SbGeoEstimator.C'.
References SBNamed::name(), and SBParameterList::remove().
virtual SBParameter* SBParameterList::find (const QString &p_) const [inline, virtual, inherited]
Definition at line 516 of file SbGeoParameter.H'.
Referenced by SBSolution::getGlobalParameter4Report(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTRFVariations(), SBRunManager::process_m1(), SBEstimator::GroupList::remove(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SolutionEpochsBlock(), sinex_SourceIDBlock(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::updateParameter(), and writeNormalEquationSystem().
int SBMJD::hour () const [inherited]
Definition at line 167 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
virtual int SBParameterList::idx (const SBParameter *p_) [inline, virtual, inherited]"Returns an index of the parameter in the list
Definition at line 519 of file SbGeoParameter.H'.
Referenced by SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), SBSolutionBrowser::updateCRF(), and writeNormalEquationSystem().
virtual int SBParameterList::idx (const QString &p_) [inline, virtual, inherited]
Definition at line 520 of file SbGeoParameter.H'.
void SBParameterList::inSort (const SBParameter *p) [virtual, inherited]
Definition at line 568 of file SbGeoParameter.C'.
References SBParameterList::ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBNamed::name(), SBParameterList::ParByName, and SBLog::write().
Referenced by addParameter(), SBRunManager::fillParameterList(), SBParameterList::operator=(), SBVLBIPreProcess::procScenario_2(), SBSolution::submitGlobalParameters(), and SBSolution::submitLocalParameters().
virtual bool SBMJD::isGood () [inline, virtual, inherited]
Definition at line 87 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBSourceEditor::acquireData(), SBAploChunk::import(), SBEcc::importEccDat(), operator>>(), and SBVLBISession::parseObsDumpString().
int SBMJD::min () const [inherited]
Definition at line 179 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
int SBMJD::MJD_date (inty, intm, intd) [static, inherited]
Definition at line 72 of file SbGeoTime.C'.
Referenced by SBMJD::dayOfYear(), and SBMJD::setMJD().
void SBMJD::MJD_rev (intdate_, long doubletime_, int &y, int &m, int &d, int &hr, int &mi, double &se) [static, inherited]
Definition at line 95 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::day(), SBMJD::hour(), SBMJD::min(), SBMJD::month(), SBMJD::sec(), SBMJD::toString(), and SBMJD::year().
long double SBMJD::MJD_time (intHour, intMin, doubleSec) [static, inherited]
Definition at line 90 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::setMJD().
int SBMJD::month () const [inherited]
Definition at line 155 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBMJD::month2Str(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
QString SBMJD::month2Str () const [inherited]
Definition at line 203 of file SbGeoTime.C'.
References SBMJD::month(), and SBMJD::monthNames.
Referenced by operator<<().
virtual SBMJD::operator long double () const [inline, virtual, inherited]
Definition at line 89 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator!= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 206 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator+= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 254 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator-= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 262 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator< (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 211 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator<= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 217 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator== (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 201 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator> (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 223 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator> (doubled) const [inline, virtual, inherited]
Definition at line 229 of file SbGeoTime.H'.
References SBMJD::SBMJD().
bool SBMJD::operator>= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 234 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
virtual QDataStream& SBParameterList::read (QDataStream &s, QCollection::Item &E) [inline, protected, virtual, inherited]
Definition at line 482 of file SbGeoParameter.H'.
bool SBParameterList::remove (const QString &key) [virtual, inherited]
Definition at line 588 of file SbGeoParameter.C'.
References SBParameterList::ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBParameterList::ParByName, SBParameterList::remove(), and SBLog::write().
Referenced by SBEstimator::GroupList::remove().
void SBParameterList::report () [virtual, inherited]
Definition at line 642 of file SbGeoParameter.C'.
References SBParameterList::ClassName(), SBLog::DBG, SBParameter::e(), SBLog::ESTIMATOR, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::isEligible(), Log, SBNamed::name(), SBDerivation::num(), SBParameter::s(), SBParameter::scale(), SBDerivation::tEpoch(), SBDerivation::tFinis(), SBMJD::toString(), SBDerivation::tStart(), SBParameter::v(), and SBLog::write().
Referenced by SBSolution::reportGlobalParameters(), and SBSolution::reportLocalParameters().
double SBMJD::sec () const [inherited]
Definition at line 191 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
virtual void SBMJD::setDate (intDate_) [inline, virtual, inherited]
Definition at line 81 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBAploChunk::import().
void SBMJD::setMJD (intYear, intMonth, intDay, intHour = 0, intMin = 0, doubleSec = 0.0, bool = TRUE) [virtual, inherited]
Definition at line 64 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), SBMJD::MJD_time(), and SBMJD::Time.
Referenced by SBStuffEOPs::accept(), SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBEcc::importEccDat(), operator>>(), SBVLBISession::parseObsDumpString(), SBTest::recalc(), SBStationInfo::restoreUserInfo(), SBMJD::SBMJD(), and SBMJD::setMJD().
void SBMJD::setMJD (FormatF, QStrings, boolisReset = TRUE) [virtual, inherited]
Definition at line 357 of file SbGeoTime.C'.
References SBMJD::ClassName(), SBMJD::Date, SBLog::ERR, SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::INF, Log, SBMJD::min(), SBMJD::MJD_date(), SBMJD::monthNames, SBMJD::sec(), SBMJD::setMJD(), SBMJD::Time, SBLog::TIME, SBLog::write(), and SBLog::WRN.
virtual void SBMJD::setTime (long doubleTime_) [inline, virtual, inherited]
Definition at line 82 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBAploChunk::import().
long double SBMJD::time () const [inline, inherited]
Definition at line 122 of file SbGeoTime.H'.
References SBMJD::Time.
Referenced by SBOceanTideLd::ARG_IERS(), SBNutation::calcGST(), and SBTestEOP::fillData4Plotting().
QString SBMJD::toString (FormatF = F_Short) const [virtual, inherited]
Definition at line 243 of file SbGeoTime.C'.
References SBMJD::Date, DAY2SEC, SBMJD::dayOfWeek2Str(), SBMJD::dayOfYear(), SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_MJD, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_UNIX, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBMJD::F_YYYYMMDDSSSSSS, SBMJD::min(), SBMJD::MJD_rev(), SBMJD::monthNames, SBMJD::sec(), SBMJD::Time, TUnix0, TZero, and SBMJD::year().
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBEphem::calcI(), SBRunManager::checkParameterLists(), SBEOP::checkRanges(), SBStuffEOPs::createInfoGroup(), SBTestFrame::createWidget4Test(), SBTest::createWidgets(), SBStationEditor::delCoordinates(), SBStuffStationsEcc::deleteEntry(), SBStaParsEditor::deleteEntry(), SBEOP::dEps(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), SBEOP::dLOD(), SBEOP::dPsi(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBPlotArea::drawXmjdTics(), SBDBHHistTriplet::dump(), SBDBHStartBlock::dump(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBVLBIPreProcess::fillSessAttr(), SBEstimator::GroupList::find(), SBStochParameter::find(), SBAploEphem::getReady(), SBEphem::import(), SBEstimator::GroupList::inSort(), SBEOP::interpolateEOPs(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBSolutionBatchLI::key(), SBObsVLBIStatRecordLI::key(), SBEccListItem::key(), SBCoordsListItem::key(), SBAploHeaderLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBAploHeader::name(), SBEphem::openFile(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), operator<<(), operator>>(), SBEOP::prepare4Date(), SBTest::recalc(), SBStationEcc::registerEcc(), SBEstimator::GroupList::remove(), SBParameterList::report(), SBStochParameter::report(), SBStuffAplo::SBStuffAplo(), SBStuffEphem::SBStuffEphem(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), SBTime::setUTC(), sinex_HeaderLine(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_SiteEccentricityBlock(), sinex_SolutionEpochsBlock(), sinex_tro_HeaderLine(), SBObsVLBIStatSrcLI::text(), SBParameterLI::text(), SBVLBIObsPPLI::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBObsVLBIStatRecordLI::text(), SBEccListItem::text(), SBVLBIObsLI::text(), SBCoordsListItem::text(), SBAploHeaderLI::text(), SBClockBreakLI::text(), SBParameter::timeStamp(), SBStuffEOPs::updateEOP(), SBStuffEphem::updateEphem(), SBStuffAplo::updateEphem(), SBVLBIPreProcess::wAttributes(), SBVLBISessionEditor::wParameters(), and SBSourceEditor::wStats().
const SBMJD& SBEstimator::Group::ttl () [inline]"Returns the TTL value'.
Definition at line 79 of file SbGeoEstimator.H'.
void SBParameterList::updateSolution (const SBVector *X, const SBSymMatrix *P) [virtual, inherited]
Definition at line 602 of file SbGeoParameter.C'.
References SBVector::at(), SBSymMatrix::at(), SBParameterList::ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBVector::n(), SBUpperMatrix::n(), SBNamed::name(), SBParameter::setS(), and SBLog::write().
Referenced by SBEstimator::solveGlobals(), and SBEstimator::solveLocals().
virtual QDataStream& SBParameterList::write (QDataStream &s, QCollection::ItemE) const [inline, protected, virtual, inherited]
Definition at line 480 of file SbGeoParameter.H'.
int SBMJD::year () const [inherited]
Definition at line 143 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBVLBISesInfo::checkPath(), SBTest::createWidgets(), SBMJD::dayOfYear(), SBVLBISesInfo::fileName(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), and SBMJD::toString().
Friends And Related Function Documentation
SBMJD operator+ (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 270 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 275 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 280 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, floatb) [friend, inherited]
Definition at line 285 of file SbGeoTime.H'.
SBMJD operator+ (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 290 of file SbGeoTime.H'.
SBMJD operator+ (doublea, const SBMJD &B) [friend, inherited]
Definition at line 295 of file SbGeoTime.H'.
SBMJD operator+ (floata, const SBMJD &B) [friend, inherited]
Definition at line 300 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 305 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 310 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 315 of file SbGeoTime.H'.
SBMJD operator- (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 320 of file SbGeoTime.H'.
SBMJD operator- (inta, const SBMJD &B) [friend, inherited]
Definition at line 325 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBMJD &MJD) [friend, inherited]
Definition at line 330 of file SbGeoTime.H'.
QDataStream & operator<< (QDataStream &s, const SBParameterList &P) [friend, inherited]"Output to the data stream'.
Definition at line 684 of file SbGeoParameter.C'.
QDataStream& operator>> (QDataStream &s, SBMJD &MJD) [friend, inherited]
Definition at line 337 of file SbGeoTime.H'.
QDataStream & operator>> (QDataStream &s, SBParameterList &P) [friend, inherited]"Input from the data stream'.
Definition at line 692 of file SbGeoParameter.C'.
QDataStream & operator>> (QDataStream &s, SBStochParameterList &P) [related]"Input from the data stream'.
Definition at line 999 of file SbGeoParameter.C'.
References SBStochParameterList::clear(), and SBStochParameterList::ParByName.
Member Data Documentation
QList<SBMatrix>* SBEstimator::Group::CrossCorr [protected]
the list of non-diagonal matrices;
Definition at line 65 of file SbGeoEstimator.H'.
const char * SBMJD::monthNames [static, protected, inherited]"Initial value:
 
{
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
}
Definition at line 63 of file SbGeoTime.H'.
Referenced by SBMJD::month2Str(), SBMJD::setMJD(), and SBMJD::toString().
QDict<SBParameter>* SBParameterList::ParByName [protected, inherited]
Definition at line 473 of file SbGeoParameter.H'.
Referenced by SBParameterList::append(), SBParameterList::inSort(), SBParameterList::operator=(), and SBParameterList::remove().
SBUpperMatrix* SBEstimator::Group::R [protected]
diagonal matrix for the set of par-s'.
Definition at line 64 of file SbGeoEstimator.H'.
const char * SBMJD::weekdayNames [static, protected, inherited]"Initial value:
{
  'Mon','Tue','Wed','Thu','Fri','Sat','Sun'
}
Definition at line 64 of file SbGeoTime.H'.
Referenced by SBMJD::dayOfWeek2Str().
SBVector* SBEstimator::Group::Z [protected]
z-vector corresponded to the set of par-s;
Definition at line 66 of file SbGeoEstimator.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.