SBEstimator::GroupList
NAME
SBEstimator::GroupList -
SYNOPSIS
#include <SbGeoEstimator.H>
Inherits QList< Group >'.
Public Member Functions
GroupList ()
GroupList (const GroupList &L_)
GroupList & operator= (const GroupList &)
virtual ~GroupList ()
virtual QString ClassName () const
virtual void inSort (const Group *)
virtual bool remove (const QString &)
virtual bool remove (const Group *)
virtual Group * find (const SBMJD &t_) const
Protected Member Functions
virtual int compareItems (QCollection::Item p1, QCollection::Item p2)
Protected Attributes
QDict< Group > * ValByDate
Private Member Functions
virtual bool remove (uint idx_)
virtual bool remove ()
Detailed Description
SBMJDList'. List of MJDs, ordered by date value'.
Definition at line 86 of file SbGeoEstimator.H'.
Constructor & Destructor Documentation
SBEstimator::GroupList::GroupList () [inline]"A constructor'. Creates a copy of the object'.
Definition at line 98 of file SbGeoEstimator.H'.
References ValByDate.
SBEstimator::GroupList::GroupList (const GroupList &L_) [inline]"A constructor'. Creates a copy of the object'.
Parameters:
L_ is value to copy in'.
Definition at line 108 of file SbGeoEstimator.H'.
virtual SBEstimator::GroupList::~GroupList () [inline, virtual]"A destructor'.
Definition at line 111 of file SbGeoEstimator.H'.
References ValByDate.
Member Function Documentation
virtual QString SBEstimator::GroupList::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Definition at line 113 of file SbGeoEstimator.H'.
virtual int SBEstimator::GroupList::compareItems (QCollection::Itemp1, QCollection::Itemp2) [inline, protected, virtual]
Definition at line 90 of file SbGeoEstimator.H'.
virtual Group* SBEstimator::GroupList::find (const SBMJD &t_) const [inline, virtual]
Definition at line 123 of file SbGeoEstimator.H'.
References SBMJD::F_INTERNAL, SBMJD::toString(), and ValByDate.
void SBEstimator::GroupList::inSort (const Group *d) [virtual]
Definition at line 103 of file SbGeoEstimator.C'.
References SBEstimator::ClassName(), SBLog::ERR, SBMJD::F_INTERNAL, Log, SBLog::TIME, SBMJD::toString(), and SBLog::write().
SBEstimator::GroupList & SBEstimator::GroupList::operator= (const GroupList &L_)
Definition at line 84 of file SbGeoEstimator.C'.
bool SBEstimator::GroupList::remove (const QString &key) [virtual]
Definition at line 125 of file SbGeoEstimator.C'.
References SBEstimator::ClassName(), SBLog::ERR, SBParameterList::find(), Log, SBParameterList::remove(), SBLog::TIME, and SBLog::write().
bool SBEstimator::GroupList::remove (const Group *d) [virtual]
Definition at line 139 of file SbGeoEstimator.C'.
References SBEstimator::ClassName(), SBLog::ERR, SBMJD::F_INTERNAL, Log, SBLog::TIME, SBMJD::toString(), and SBLog::write().
virtual bool SBEstimator::GroupList::remove (uintidx_) [inline, private, virtual]
Definition at line 127 of file SbGeoEstimator.H'.
References SBMJD::F_INTERNAL, remove(), and ValByDate.
virtual bool SBEstimator::GroupList::remove () [inline, private, virtual]
Definition at line 131 of file SbGeoEstimator.H'.
References SBMJD::F_INTERNAL, and ValByDate.
Referenced by remove().
Member Data Documentation
QDict<Group>* SBEstimator::GroupList::ValByDate [protected]
Definition at line 89 of file SbGeoEstimator.H'.
Referenced by find(), GroupList(), remove(), and ~GroupList().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.