SBFCList
NAME
SBFCList -
SYNOPSIS
#include <SbSetup.H>
Inherits SBNList'.
Public Member Functions
SBFCList ()
SBFCList (const SBFCList &)
virtual SBFCList & operator= (const SBFCList &)
virtual ~SBFCList ()
virtual QString ClassName () const
SBFileConv * guessFileType (const QString &)
SBFileConv * defaultFC ()
QString defaultName ()
QString defaultExt ()
void setDefault (const QString &)
FILE * open4In (const QString &, QFile &, QDataStream &)
FILE * open4In (const QString &, QFile &, QTextStream &)
FILE * open4Out (const QString &, QFile &, QDataStream &)
FILE * open4Out (const QString &, QFile &, QTextStream &)
FILE * open4OutDflt (const QString &, QFile &, QDataStream &)
FILE * open4OutDflt (const QString &, QFile &, QTextStream &)
void close (QFile &file, FILE *&p, QDataStream &ds)
void close (QFile &file, FILE *&p, QTextStream &ts)
virtual void clear ()
virtual bool insert (const SBFileConv *)
virtual bool remove (const SBFileConv *N)
Protected Member Functions
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
Private Attributes
QDict< SBFileConv > * ExtDict
SBFileConv * DefaultFC
QString Default
Friends
QDataStream & operator<< (QDataStream &, const SBFCList &)
QDataStream & operator>> (QDataStream &, SBFCList &)
Detailed Description
SBFCList, a list of SBFileConv`s'.
Definition at line 109 of file SbSetup.H'.
Constructor & Destructor Documentation
SBFCList::SBFCList ()"A constructor'.
Definition at line 260 of file SbSetup.C'.
References Default, DefaultFC, and ExtDict.
SBFCList::SBFCList (const SBFCList &L)
Definition at line 269 of file SbSetup.C'.
References Default, ExtDict, and setDefault().
SBFCList::~SBFCList () [virtual]"A destructor'.
Definition at line 296 of file SbSetup.C'.
References DefaultFC, and ExtDict.
Member Function Documentation
virtual QString SBFCList::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Definition at line 128 of file SbSetup.H'.
Referenced by insert().
virtual void SBFCList::clear () [inline, virtual]
Definition at line 146 of file SbSetup.H'.
References ExtDict.
Referenced by operator=().
void SBFCList::close (QFile &file, FILE *&p, QDataStream &ds) [inline]
Definition at line 143 of file SbSetup.H'.
Referenced by close(), SBVLBISession::dumpUserInfo(), SBEstimator::finisLocal(), SBEphem::import(), SBVLBISet::import(), SBAploEphem::importEphem(), SBAploEphem::loadChunk(), SBSolution::loadGlbCor(), SBSolution::loadGlbPar(), SBSolution::loadLocCor(), SBSolution::loadLocPar(), SBSolution::loadNormalEqs(), SBSolution::loadStcPar(), SBVLBISession::restoreUserInfo(), SBAploEphem::saveChunk(), SBSolution::saveGlbCor(), SBSolution::saveGlbPar(), SBSolution::saveLocCor(), SBSolution::saveLocPar(), SBSolution::saveNormalEqs(), SBSolution::saveStcPar(), SBEstimator::solveLocals(), and SBEstimator::solveStochs().
void SBFCList::close (QFile &file, FILE *&p, QTextStream &ts) [inline]
Definition at line 144 of file SbSetup.H'.
References close().
virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, and SBStationIDList'.
Definition at line 277 of file SbGeo.H'.
QString SBFCList::defaultExt () [inline]
Definition at line 135 of file SbSetup.H'.
References DefaultFC, and SBFileConv::ext().
Referenced by SBVLBISession::dumpUserInfo(), and SBVLBISet::import().
SBFileConv* SBFCList::defaultFC () [inline]
Definition at line 133 of file SbSetup.H'.
References DefaultFC.
QString SBFCList::defaultName () [inline]
Definition at line 134 of file SbSetup.H'.
References Default.
Referenced by SBSetupDialog::packer(), and SBSetupDialog::setData().
SBFileConv * SBFCList::guessFileType (const QString &FileName)"Lookups a type, returns NULL if failed'.
Definition at line 302 of file SbSetup.C'.
References ExtDict.
Referenced by open4In(), open4Out(), and SBVLBISession::restoreUserInfo().
bool SBFCList::insert (const SBFileConv *F) [virtual]
Definition at line 370 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBFileConv::ext(), ExtDict, SBLog::IO, Log, SBNamed::name(), and SBLog::write().
Referenced by SBSetupDialog::addPacker(), operator=(), and SBSetUp::SetDefaults().
FILE * SBFCList::open4In (const QString &FileName, QFile &file, QDataStream &ds)
Definition at line 308 of file SbSetup.C'.
References guessFileType(), and SBFileConv::open4In().
Referenced by SBEphem::import(), SBVLBISet::import(), SBAploEphem::importEphem(), SBAploEphem::loadChunk(), SBSolution::loadGlbCor(), SBSolution::loadGlbPar(), SBSolution::loadLocCor(), SBSolution::loadLocPar(), SBSolution::loadNormalEqs(), SBSolution::loadStcPar(), SBVLBISession::restoreUserInfo(), SBEstimator::solveLocals(), and SBEstimator::solveStochs().
FILE * SBFCList::open4In (const QString &FileName, QFile &file, QTextStream &ts)
Definition at line 319 of file SbSetup.C'.
References guessFileType(), and SBFileConv::open4In().
FILE * SBFCList::open4Out (const QString &FileName, QFile &file, QDataStream &ds)
Definition at line 330 of file SbSetup.C'.
References guessFileType(), and SBFileConv::open4Out().
Referenced by SBEstimator::finisLocal(), SBEstimator::prepare4Local(), SBAploEphem::saveChunk(), SBSolution::saveGlbCor(), SBSolution::saveGlbPar(), SBSolution::saveLocCor(), SBSolution::saveLocPar(), SBSolution::saveNormalEqs(), and SBSolution::saveStcPar().
FILE * SBFCList::open4Out (const QString &FileName, QFile &file, QTextStream &ts)
Definition at line 341 of file SbSetup.C'.
References guessFileType(), and SBFileConv::open4Out().
FILE * SBFCList::open4OutDflt (const QString &FileName, QFile &file, QDataStream &ds)
Definition at line 352 of file SbSetup.C'.
References DefaultFC, and SBFileConv::open4Out().
Referenced by SBVLBISession::dumpUserInfo().
FILE * SBFCList::open4OutDflt (const QString &FileName, QFile &file, QTextStream &ts)
Definition at line 361 of file SbSetup.C'.
References DefaultFC, and SBFileConv::open4Out().
SBFCList & SBFCList::operator= (const SBFCList &L) [virtual]
Definition at line 278 of file SbSetup.C'.
References clear(), Default, ExtDict, insert(), and setDefault().
virtual QDataStream& SBFCList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 114 of file SbSetup.H'.
virtual bool SBFCList::remove (const SBFileConv *N) [inline, virtual]
Definition at line 148 of file SbSetup.H'.
References ExtDict.
Referenced by SBSetupDialog::delPacker().
void SBFCList::setDefault (const QString &Default_)
Definition at line 388 of file SbSetup.C'.
References SBFileConv::comCompr(), Default, DefaultFC, and SBNamed::name().
Referenced by SBSetupDialog::acquireData(), operator=(), operator>>(), and SBFCList().
virtual QDataStream& SBFCList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 112 of file SbSetup.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBFCList &L) [friend]
Definition at line 406 of file SbSetup.C'.
QDataStream& operator>> (QDataStream &s, SBFCList &L) [friend]
Definition at line 411 of file SbSetup.C'.
Member Data Documentation
QString SBFCList::Default [private]
Definition at line 119 of file SbSetup.H'.
Referenced by defaultName(), operator<<(), operator=(), operator>>(), SBFCList(), and setDefault().
SBFileConv* SBFCList::DefaultFC [private]
Definition at line 118 of file SbSetup.H'.
Referenced by defaultExt(), defaultFC(), open4OutDflt(), SBFCList(), setDefault(), and ~SBFCList().
QDict<SBFileConv>* SBFCList::ExtDict [private]
Definition at line 115 of file SbSetup.H'.
Referenced by clear(), guessFileType(), insert(), operator=(), operator>>(), remove(), SBFCList(), and ~SBFCList().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.