SBFilterGauss
NAME
SBFilterGauss -
SYNOPSIS
#include <SbMathFilters.H>
Inherits SBAttributed'.
Public Types
enum Attributes { IsOmit3Sigma = 1<<0 }
Public Member Functions
SBFilterGauss ()
virtual ~SBFilterGauss ()
virtual QString ClassName () const
SBDataSeries * series ()
SBDataSeries * seriesMinusModel ()
double fwhm () const
unsigned int nColOfData () const
unsigned int n () const
bool isOK () const
double tStart () const
double tFinis () const
void setFWHM (double w_)
QList< SBFilterModel > * modelList ()
QIntDict< SBFilterModel > * modelByIdx ()
void readDataFile (const QString &)
void calcSigma (unsigned int, unsigned int)
double interpolate (double, unsigned int=0, unsigned int=0)
double stdVar () const
double respFunc (double)
double sigma (unsigned int Idx) const
void addModel (unsigned int, unsigned int)
void prepareModels ()
void rmModels ()
double interpolateMinusModel (double, unsigned int=0, unsigned int=0)
void substractFilter (bool, int)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Attributes
SBDataSeries * Series
SBDataSeries * SeriesMinusModel
SBVector * DataAttribute
bool IsOK
double FWHM
double TStart
double TFinis
unsigned int NColOfData
unsigned int N
SBVector * vAux
SBVector * Sigmas
SBMatrix * mAux
double StdVar
QList< SBFilterModel > ModelList
QIntDict< SBFilterModel > ModelByIdx
Friends
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Definition at line 153 of file SbMathFilters.H'.
Member Enumeration Documentation
enum SBFilterGauss::Attributes
Enumerator:
IsOmit3Sigma
test
Definition at line 156 of file SbMathFilters.H'.
Constructor & Destructor Documentation
SBFilterGauss::SBFilterGauss ()
Definition at line 552 of file SbMathFilters.C'.
References DataAttribute, FWHM, IsOK, mAux, ModelByIdx, ModelList, N, NColOfData, Series, SeriesMinusModel, Sigmas, StdVar, TFinis, TStart, and vAux.
SBFilterGauss::~SBFilterGauss () [virtual]"A destructor'.
Definition at line 572 of file SbMathFilters.C'.
References DataAttribute, mAux, Series, SeriesMinusModel, and vAux.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
void SBFilterGauss::addModel (unsigned intIdx_, unsigned intIdxSig_)
Definition at line 806 of file SbMathFilters.C'.
References ModelList.
Referenced by SBFilteringGauss::redrawDataPlot_ExpMode().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBFilterGauss::calcSigma (unsigned intIdx, unsigned intSigIdx)
Definition at line 785 of file SbMathFilters.C'.
References SBVector::at(), SBDataSeriesEntry::data(), interpolate(), mAux, Series, SBVector::set(), SBMatrix::set(), Sigmas, and SBDataSeriesEntry::t().
Referenced by SBFilteringGauss::calcSigmas().
virtual QString SBFilterGauss::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBAttributed'.
Definition at line 193 of file SbMathFilters.H'.
Referenced by prepareModels(), readDataFile(), and substractFilter().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
double SBFilterGauss::fwhm () const [inline]
Definition at line 200 of file SbMathFilters.H'.
References FWHM.
double SBFilterGauss::interpolate (doublet, unsigned intIdx = 0, unsigned intSigIdx = 0)
Definition at line 704 of file SbMathFilters.C'.
References SBVector::at(), SBMatrix::at(), SBDataSeries::dT(), FWHM, SBAttributed::isAttr(), IsOmit3Sigma, mAux, NColOfData, Series, SBVector::set(), Sigmas, StdVar, TFinis, and vAux.
Referenced by calcSigma(), SBFilteringGauss::redrawDataPlot(), and substractFilter().
double SBFilterGauss::interpolateMinusModel (doublet, unsigned intIdx = 0, unsigned intSigIdx = 0)
Definition at line 1036 of file SbMathFilters.C'.
References SBVector::at(), DataAttribute, SBDataSeries::dT(), FWHM, ModelByIdx, ModelList, NColOfData, SeriesMinusModel, SBVector::set(), StdVar, TFinis, and vAux.
Referenced by SBFilteringGauss::redrawDataPlot_ExpMode(), and substractFilter().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
bool SBFilterGauss::isOK () const [inline]
Definition at line 203 of file SbMathFilters.H'.
References IsOK.
Referenced by SBFilteringGauss::calcSigmas(), SBFilteringGauss::changeByNum(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBFilteringGauss::readDataFile(), SBFilteringGauss::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBFilteringGauss::redrawTFPlot(), SBFilteringGauss::substractFilter(), and SBFilteringGauss::wrote2File().
QIntDict<SBFilterModel>* SBFilterGauss::modelByIdx () [inline]
Definition at line 210 of file SbMathFilters.H'.
References ModelByIdx.
Referenced by SBFilteringGauss::redrawDataPlot_ExpMode().
QList<SBFilterModel>* SBFilterGauss::modelList () [inline]
Definition at line 209 of file SbMathFilters.H'.
References ModelList.
Referenced by SBFilteringGauss::redrawDataPlot_ExpMode().
unsigned int SBFilterGauss::n () const [inline]
Definition at line 202 of file SbMathFilters.H'.
References N.
Referenced by SBFilteringGauss::readDataFile(), SBFilteringGauss::redrawDataPlot(), and SBFilteringGauss::redrawDataPlot_ExpMode().
unsigned int SBFilterGauss::nColOfData () const [inline]
Definition at line 201 of file SbMathFilters.H'.
References NColOfData.
void SBFilterGauss::prepareModels ()
Definition at line 811 of file SbMathFilters.C'.
References SBAttributed::addAttr(), SBFilterModel::analyseSeries(), SBVector::at(), ClassName(), SBLog::DATA, DataAttribute, SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBFilterModel::idx(), SBLog::INF, SBFilterModel::isCanRun(), SBFilterModel::IsOmit3SigmaBefore, Log, ModelByIdx, SBFilterModel::modelFull(), ModelList, N, SBFilterModel::periods(), Series, SeriesMinusModel, SBVector::set(), SBFilterModel::setDataAttribute(), SBFilterModel::setNumOfHarmonics(), SBFilterModel::setNumOfPolinoms(), SBFilterModel::setSeries(), SBFilterModel::setT0(), SBFilterModel::setTermToKeep(), and SBLog::write().
Referenced by SBFilteringGauss::redrawDataPlot_ExpMode().
void SBFilterGauss::readDataFile (const QString &FileName)
Definition at line 601 of file SbMathFilters.C'.
References ClassName(), SBLog::DATA, DataAttribute, SBLog::DBG, SBLog::ERR, IsOK, Log, mAux, ModelList, SBVector::n(), N, SBMatrix::nCol(), NColOfData, SBMatrix::nRow(), rmModels(), Series, SBVector::set(), Sigmas, TFinis, TStart, vAux, SBLog::write(), and SBLog::WRN.
Referenced by SBFilteringGauss::readDataFile().
double SBFilterGauss::respFunc (doublef)
Definition at line 778 of file SbMathFilters.C'.
References FWHM.
Referenced by SBFilteringGauss::redrawTFPlot().
void SBFilterGauss::rmModels () [inline]
Definition at line 224 of file SbMathFilters.H'.
References ModelByIdx, and ModelList.
Referenced by readDataFile().
SBDataSeries* SBFilterGauss::series () [inline]
Definition at line 198 of file SbMathFilters.H'.
References Series.
Referenced by SBFilteringGauss::readDataFile(), SBFilteringGauss::redrawDataPlot(), SBFilteringGauss::redrawTFPlot(), and SBFilteringGauss::wrote2File().
SBDataSeries* SBFilterGauss::seriesMinusModel () [inline]
Definition at line 199 of file SbMathFilters.H'.
References SeriesMinusModel.
Referenced by SBFilteringGauss::redrawDataPlot_ExpMode().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBFilterGauss::setFWHM (doublew_) [inline]
Definition at line 207 of file SbMathFilters.H'.
References FWHM.
Referenced by SBFilteringGauss::changeFWHM().
double SBFilterGauss::sigma (unsigned intIdx) const [inline]
Definition at line 220 of file SbMathFilters.H'.
References SBVector::at(), and Sigmas.
Referenced by SBFilteringGauss::calcSigmas(), and SBFilteringGauss::makeAnalysisWith3Sigma().
double SBFilterGauss::stdVar () const [inline]
Definition at line 218 of file SbMathFilters.H'.
References StdVar.
Referenced by SBFilteringGauss::redrawDataPlot(), and SBFilteringGauss::redrawDataPlot_ExpMode().
void SBFilterGauss::substractFilter (boolIsUseModel, intSMode)
Definition at line 1090 of file SbMathFilters.C'.
References ClassName(), SBDataSeriesEntry::data(), SBLog::DATA, SBLog::ERR, interpolate(), interpolateMinusModel(), Log, NColOfData, Series, SBDataSeriesEntry::t(), and SBLog::write().
Referenced by SBFilteringGauss::substractFilter().
double SBFilterGauss::tFinis () const [inline]
Definition at line 205 of file SbMathFilters.H'.
References TFinis.
Referenced by SBFilteringGauss::changeByNum(), SBFilteringGauss::readDataFile(), SBFilteringGauss::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), and SBFilteringGauss::redrawTFPlot().
double SBFilterGauss::tStart () const [inline]
Definition at line 204 of file SbMathFilters.H'.
References TStart.
Referenced by SBFilteringGauss::changeByNum(), SBFilteringGauss::readDataFile(), SBFilteringGauss::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), and SBFilteringGauss::redrawTFPlot().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
Member Data Documentation
SBVector* SBFilterGauss::DataAttribute [protected]
Definition at line 166 of file SbMathFilters.H'.
Referenced by interpolateMinusModel(), prepareModels(), readDataFile(), SBFilterGauss(), and ~SBFilterGauss().
double SBFilterGauss::FWHM [protected]
Definition at line 169 of file SbMathFilters.H'.
Referenced by fwhm(), interpolate(), interpolateMinusModel(), respFunc(), SBFilterGauss(), and setFWHM().
bool SBFilterGauss::IsOK [protected]
Definition at line 167 of file SbMathFilters.H'.
Referenced by isOK(), readDataFile(), and SBFilterGauss().
SBMatrix* SBFilterGauss::mAux [protected]
Definition at line 177 of file SbMathFilters.H'.
Referenced by calcSigma(), interpolate(), readDataFile(), SBFilterGauss(), and ~SBFilterGauss().
QIntDict<SBFilterModel> SBFilterGauss::ModelByIdx [protected]
Definition at line 184 of file SbMathFilters.H'.
Referenced by interpolateMinusModel(), modelByIdx(), prepareModels(), rmModels(), and SBFilterGauss().
QList<SBFilterModel> SBFilterGauss::ModelList [protected]
Definition at line 183 of file SbMathFilters.H'.
Referenced by addModel(), interpolateMinusModel(), modelList(), prepareModels(), readDataFile(), rmModels(), and SBFilterGauss().
unsigned int SBFilterGauss::N [protected]
Definition at line 173 of file SbMathFilters.H'.
Referenced by n(), prepareModels(), readDataFile(), and SBFilterGauss().
unsigned int SBFilterGauss::NColOfData [protected]
Definition at line 172 of file SbMathFilters.H'.
Referenced by interpolate(), interpolateMinusModel(), nColOfData(), readDataFile(), SBFilterGauss(), and substractFilter().
SBDataSeries* SBFilterGauss::Series [protected]
Definition at line 164 of file SbMathFilters.H'.
Referenced by calcSigma(), interpolate(), prepareModels(), readDataFile(), SBFilterGauss(), series(), substractFilter(), and ~SBFilterGauss().
SBDataSeries* SBFilterGauss::SeriesMinusModel [protected]
Definition at line 165 of file SbMathFilters.H'.
Referenced by interpolateMinusModel(), prepareModels(), SBFilterGauss(), seriesMinusModel(), and ~SBFilterGauss().
SBVector* SBFilterGauss::Sigmas [protected]
Definition at line 176 of file SbMathFilters.H'.
Referenced by calcSigma(), interpolate(), readDataFile(), SBFilterGauss(), and sigma().
double SBFilterGauss::StdVar [protected]
Definition at line 180 of file SbMathFilters.H'.
Referenced by interpolate(), interpolateMinusModel(), SBFilterGauss(), and stdVar().
double SBFilterGauss::TFinis [protected]
Definition at line 171 of file SbMathFilters.H'.
Referenced by interpolate(), interpolateMinusModel(), readDataFile(), SBFilterGauss(), and tFinis().
double SBFilterGauss::TStart [protected]
Definition at line 170 of file SbMathFilters.H'.
Referenced by readDataFile(), SBFilterGauss(), and tStart().
SBVector* SBFilterGauss::vAux [protected]
Definition at line 175 of file SbMathFilters.H'.
Referenced by interpolate(), interpolateMinusModel(), readDataFile(), SBFilterGauss(), and ~SBFilterGauss().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.