.TH "SBFileConvLI" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBFileConvLI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbISetup\&.H>\fP
.PP
Inherits \fBQListViewItem\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBFileConvLI\fP (\fBQListView\fP *parent, \fBSBFileConv\fP *Entry_)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "\fBSBFileConv\fP * \fBentry\fP ()"
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBFileConv\fP * \fBEntry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file SbISetup\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBFileConvLI::SBFileConvLI (\fBQListView\fP *parent, \fBSBFileConv\fP *Entry_)\fC [inline]\fP"
.PP
Definition at line 45 of file SbISetup\&.H'\&.
.PP
References Entry\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBFileConvLI::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 47 of file SbISetup\&.H'\&.
.SS "\fBSBFileConv\fP* SBFileConvLI::entry ()\fC [inline]\fP"
.PP
Definition at line 48 of file SbISetup\&.H'\&.
.PP
References Entry\&.
.PP
Referenced by SBSetupDialog::chkPacker(), and SBSetupDialog::delPacker()\&.
.SS "QString SBFileConvLI::text (intcol) const\fC [virtual]\fP"
.PP
Definition at line 92 of file SbISetup\&.C'\&.
.PP
References SBFileConv::comCompr(), SBFileConv::comUncom(), Entry, SBFileConv::ext(), SBNamed::name(), and TmpString\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBFileConv\fP* \fBSBFileConvLI::Entry\fP\fC [private]\fP"
.PP
Definition at line 43 of file SbISetup\&.H'\&.
.PP
Referenced by entry(), SBFileConvLI(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
