SBFilterModel
NAME
SBFilterModel -
SYNOPSIS
#include <SbMathFilters.H>
Inherits SBAttributed'.
Public Types
enum Attributes { IsOmit3SigmaBefore = 1<<0, IsOmit3SigmaAfter = 2<<0 }
Public Member Functions
SBFilterModel (unsigned int=0, unsigned int=0)
virtual ~SBFilterModel ()
virtual QString ClassName () const
double t0 () const
unsigned int numOfPolinoms () const
unsigned int numOfHarmonics () const
unsigned int numOfUnknowns () const
SBVector * periods ()
SBVector * polinoms ()
SBVector * polinomsSigma ()
SBVector * dataAttribute ()
SBMatrix * harmonics ()
SBMatrix * harmonicsSigma ()
bool isOK () const
unsigned int idx () const
unsigned int idxSig () const
void setT0 (double t_)
void setNumOfPolinoms (unsigned int)
void setNumOfHarmonics (unsigned int)
void setSeries (SBDataSeries *series)
void setDataAttribute (SBVector *DA_)
void setIsRunSM (bool Is_)
void setUpSpecModel (unsigned int, double, bool)
bool isCanRun ()
void analyseSeries ()
unsigned int eliminateBefore ()
unsigned int eliminateAfter ()
double modelFull (double)
double modelKeep (double)
void setTermToKeep (unsigned int, bool)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Attributes
double T0
unsigned int NumOfData
unsigned int NumOfPolinoms
unsigned int NumOfHarmonics
SBVector * Periods
SBVector * Polinoms
SBVector * PolinomsSigma
SBMatrix * Harmonics
SBMatrix * HarmonicsSigma
bool * IsKeepTerm
bool IsRunSM
unsigned int NumOfSMTerms
SBMatrix * SMPolinoms
SBMatrix * SMPolinomsSigma
double SMPeriod
bool IsKeepSM
SBDataSeries * Series
SBVector * DataAttribute
unsigned int Idx
unsigned int IdxSig
bool IsOK
double VTPV
double SumW2
Friends
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Definition at line 48 of file SbMathFilters.H'.
Member Enumeration Documentation
enum SBFilterModel::Attributes
Enumerator:
IsOmit3SigmaBefore
ignore data with sig>3(mean_sigma)
IsOmit3SigmaAfter
test
Definition at line 51 of file SbMathFilters.H'.
Constructor & Destructor Documentation
SBFilterModel::SBFilterModel (unsigned intIdx_ = 0, unsigned intIdxSig_ = 0)
Definition at line 88 of file SbMathFilters.C'.
References Harmonics, HarmonicsSigma, Idx, IdxSig, IsKeepSM, IsKeepTerm, IsOK, IsRunSM, NumOfData, NumOfHarmonics, NumOfPolinoms, NumOfSMTerms, Periods, Polinoms, PolinomsSigma, Series, SMPeriod, SMPolinoms, SMPolinomsSigma, SumW2, T0, and VTPV.
SBFilterModel::~SBFilterModel () [virtual]"A destructor'.
Definition at line 120 of file SbMathFilters.C'.
References Harmonics, HarmonicsSigma, IsKeepTerm, Periods, Polinoms, PolinomsSigma, SMPolinoms, and SMPolinomsSigma.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
void SBFilterModel::analyseSeries ()
Definition at line 330 of file SbMathFilters.C'.
References SBVector::at(), SBMatrix::at(), SBSymMatrix::at(), ClassName(), SBLog::DATA, DataAttribute, SBLog::DBG, Harmonics, HarmonicsSigma, Idx, IdxSig, IsOK, IsRunSM, Log, makeHouseholder(), NumOfData, NumOfHarmonics, NumOfPolinoms, NumOfSMTerms, numOfUnknowns(), Periods, Polinoms, PolinomsSigma, RRT(), Series, SBVector::set(), SBUpperMatrix::set(), SMPeriod, SMPolinoms, SMPolinomsSigma, Solve(), SumW2, T0, VTPV, and SBLog::write().
Referenced by SBFilterGauss::prepareModels().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBFilterModel::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBAttributed'.
Definition at line 95 of file SbMathFilters.H'.
Referenced by analyseSeries(), isCanRun(), and setTermToKeep().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
SBVector* SBFilterModel::dataAttribute () [inline]
Definition at line 109 of file SbMathFilters.H'.
References DataAttribute.
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
unsigned int SBFilterModel::eliminateAfter ()
Definition at line 522 of file SbMathFilters.C'.
References DataAttribute, Idx, SBAttributed::isAttr(), IsOmit3SigmaAfter, modelFull(), Series, SBVector::set(), SumW2, and VTPV.
Referenced by SBFilterGauss::prepareModels().
unsigned int SBFilterModel::eliminateBefore ()
Definition at line 304 of file SbMathFilters.C'.
References SBVector::at(), SBDataSeriesEntry::data(), DataAttribute, IdxSig, SBAttributed::isAttr(), IsOmit3SigmaBefore, Series, and SBVector::set().
Referenced by SBFilterGauss::prepareModels().
SBMatrix* SBFilterModel::harmonics () [inline]
Definition at line 110 of file SbMathFilters.H'.
References Harmonics.
SBMatrix* SBFilterModel::harmonicsSigma () [inline]
Definition at line 111 of file SbMathFilters.H'.
References HarmonicsSigma.
unsigned int SBFilterModel::idx () const [inline]
Definition at line 113 of file SbMathFilters.H'.
References Idx.
Referenced by SBFilterGauss::prepareModels().
unsigned int SBFilterModel::idxSig () const [inline]
Definition at line 114 of file SbMathFilters.H'.
References IdxSig.
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), eliminateAfter(), eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
bool SBFilterModel::isCanRun ()
Definition at line 239 of file SbMathFilters.C'.
References ClassName(), SBLog::DATA, DataAttribute, SBLog::DBG, Harmonics, HarmonicsSigma, IsOK, Log, NumOfHarmonics, NumOfPolinoms, Periods, Polinoms, PolinomsSigma, Series, and SBLog::write().
Referenced by SBFilterGauss::prepareModels().
bool SBFilterModel::isOK () const [inline]
Definition at line 112 of file SbMathFilters.H'.
References IsOK.
double SBFilterModel::modelFull (doublet)
Definition at line 455 of file SbMathFilters.C'.
References SBVector::at(), SBMatrix::at(), Harmonics, IsRunSM, NumOfHarmonics, NumOfPolinoms, NumOfSMTerms, Periods, Polinoms, SMPeriod, SMPolinoms, and T0.
Referenced by eliminateAfter(), SBFilterGauss::prepareModels(), and SBFilteringGauss::redrawDataPlot_ExpMode().
double SBFilterModel::modelKeep (doublet)
Definition at line 487 of file SbMathFilters.C'.
References SBVector::at(), SBMatrix::at(), Harmonics, IsKeepSM, IsKeepTerm, IsRunSM, NumOfHarmonics, NumOfSMTerms, Periods, SMPeriod, SMPolinoms, and T0.
Referenced by SBFilteringGauss::redrawDataPlot_ExpMode().
unsigned int SBFilterModel::numOfHarmonics () const [inline]
Definition at line 102 of file SbMathFilters.H'.
References NumOfHarmonics.
unsigned int SBFilterModel::numOfPolinoms () const [inline]
Definition at line 101 of file SbMathFilters.H'.
References NumOfPolinoms.
unsigned int SBFilterModel::numOfUnknowns () const [inline]
Definition at line 103 of file SbMathFilters.H'.
References IsRunSM, NumOfHarmonics, NumOfPolinoms, and NumOfSMTerms.
Referenced by analyseSeries().
SBVector* SBFilterModel::periods () [inline]
Definition at line 106 of file SbMathFilters.H'.
References Periods.
Referenced by SBFilterGauss::prepareModels().
SBVector* SBFilterModel::polinoms () [inline]
Definition at line 107 of file SbMathFilters.H'.
References Polinoms.
SBVector* SBFilterModel::polinomsSigma () [inline]
Definition at line 108 of file SbMathFilters.H'.
References PolinomsSigma.
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBFilterModel::setDataAttribute (SBVector *DA_) [inline]
Definition at line 120 of file SbMathFilters.H'.
References DataAttribute.
Referenced by SBFilterGauss::prepareModels().
void SBFilterModel::setIsRunSM (boolIs_) [inline]
Definition at line 123 of file SbMathFilters.H'.
References IsRunSM.
void SBFilterModel::setNumOfHarmonics (unsigned intn_)
Definition at line 182 of file SbMathFilters.C'.
References SBVector::clear(), SBMatrix::clear(), Harmonics, HarmonicsSigma, IsKeepTerm, NumOfHarmonics, and Periods.
Referenced by SBFilterGauss::prepareModels().
void SBFilterModel::setNumOfPolinoms (unsigned intn_)
Definition at line 166 of file SbMathFilters.C'.
References SBVector::clear(), NumOfPolinoms, Polinoms, and PolinomsSigma.
Referenced by SBFilterGauss::prepareModels().
void SBFilterModel::setSeries (SBDataSeries *series) [inline]
Definition at line 119 of file SbMathFilters.H'.
References Series.
Referenced by SBFilterGauss::prepareModels().
void SBFilterModel::setT0 (doublet_) [inline]
Definition at line 116 of file SbMathFilters.H'.
References T0.
Referenced by SBFilterGauss::prepareModels().
void SBFilterModel::setTermToKeep (unsigned inti, boolIsToKeep)
Definition at line 229 of file SbMathFilters.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, IsKeepTerm, Log, NumOfHarmonics, and SBLog::write().
Referenced by SBFilterGauss::prepareModels().
void SBFilterModel::setUpSpecModel (unsigned intn_, doubleP_, boolIs_)
Definition at line 207 of file SbMathFilters.C'.
References SBMatrix::clear(), IsKeepSM, IsRunSM, NumOfSMTerms, SMPeriod, SMPolinoms, and SMPolinomsSigma.
double SBFilterModel::t0 () const [inline]
Definition at line 100 of file SbMathFilters.H'.
References T0.
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
Member Data Documentation
SBVector* SBFilterModel::DataAttribute [protected]
Definition at line 81 of file SbMathFilters.H'.
Referenced by analyseSeries(), dataAttribute(), eliminateAfter(), eliminateBefore(), isCanRun(), and setDataAttribute().
SBMatrix* SBFilterModel::Harmonics [protected]
Definition at line 67 of file SbMathFilters.H'.
Referenced by analyseSeries(), harmonics(), isCanRun(), modelFull(), modelKeep(), SBFilterModel(), setNumOfHarmonics(), and ~SBFilterModel().
SBMatrix* SBFilterModel::HarmonicsSigma [protected]
Definition at line 68 of file SbMathFilters.H'.
Referenced by analyseSeries(), harmonicsSigma(), isCanRun(), SBFilterModel(), setNumOfHarmonics(), and ~SBFilterModel().
unsigned int SBFilterModel::Idx [protected]
Definition at line 82 of file SbMathFilters.H'.
Referenced by analyseSeries(), eliminateAfter(), idx(), and SBFilterModel().
unsigned int SBFilterModel::IdxSig [protected]
Definition at line 83 of file SbMathFilters.H'.
Referenced by analyseSeries(), eliminateBefore(), idxSig(), and SBFilterModel().
bool SBFilterModel::IsKeepSM [protected]
Definition at line 77 of file SbMathFilters.H'.
Referenced by modelKeep(), SBFilterModel(), and setUpSpecModel().
bool* SBFilterModel::IsKeepTerm [protected]
Definition at line 69 of file SbMathFilters.H'.
Referenced by modelKeep(), SBFilterModel(), setNumOfHarmonics(), setTermToKeep(), and ~SBFilterModel().
bool SBFilterModel::IsOK [protected]
Definition at line 84 of file SbMathFilters.H'.
Referenced by analyseSeries(), isCanRun(), isOK(), and SBFilterModel().
bool SBFilterModel::IsRunSM [protected]
Definition at line 72 of file SbMathFilters.H'.
Referenced by analyseSeries(), modelFull(), modelKeep(), numOfUnknowns(), SBFilterModel(), setIsRunSM(), and setUpSpecModel().
unsigned int SBFilterModel::NumOfData [protected]
Definition at line 60 of file SbMathFilters.H'.
Referenced by analyseSeries(), and SBFilterModel().
unsigned int SBFilterModel::NumOfHarmonics [protected]
Definition at line 62 of file SbMathFilters.H'.
Referenced by analyseSeries(), isCanRun(), modelFull(), modelKeep(), numOfHarmonics(), numOfUnknowns(), SBFilterModel(), setNumOfHarmonics(), and setTermToKeep().
unsigned int SBFilterModel::NumOfPolinoms [protected]
Definition at line 61 of file SbMathFilters.H'.
Referenced by analyseSeries(), isCanRun(), modelFull(), numOfPolinoms(), numOfUnknowns(), SBFilterModel(), and setNumOfPolinoms().
unsigned int SBFilterModel::NumOfSMTerms [protected]
Definition at line 73 of file SbMathFilters.H'.
Referenced by analyseSeries(), modelFull(), modelKeep(), numOfUnknowns(), SBFilterModel(), and setUpSpecModel().
SBVector* SBFilterModel::Periods [protected]
Definition at line 63 of file SbMathFilters.H'.
Referenced by analyseSeries(), isCanRun(), modelFull(), modelKeep(), periods(), SBFilterModel(), setNumOfHarmonics(), and ~SBFilterModel().
SBVector* SBFilterModel::Polinoms [protected]
Definition at line 65 of file SbMathFilters.H'.
Referenced by analyseSeries(), isCanRun(), modelFull(), polinoms(), SBFilterModel(), setNumOfPolinoms(), and ~SBFilterModel().
SBVector* SBFilterModel::PolinomsSigma [protected]
Definition at line 66 of file SbMathFilters.H'.
Referenced by analyseSeries(), isCanRun(), polinomsSigma(), SBFilterModel(), setNumOfPolinoms(), and ~SBFilterModel().
SBDataSeries* SBFilterModel::Series [protected]
Definition at line 80 of file SbMathFilters.H'.
Referenced by analyseSeries(), eliminateAfter(), eliminateBefore(), isCanRun(), SBFilterModel(), and setSeries().
double SBFilterModel::SMPeriod [protected]
Definition at line 76 of file SbMathFilters.H'.
Referenced by analyseSeries(), modelFull(), modelKeep(), SBFilterModel(), and setUpSpecModel().
SBMatrix* SBFilterModel::SMPolinoms [protected]
Definition at line 74 of file SbMathFilters.H'.
Referenced by analyseSeries(), modelFull(), modelKeep(), SBFilterModel(), setUpSpecModel(), and ~SBFilterModel().
SBMatrix* SBFilterModel::SMPolinomsSigma [protected]
Definition at line 75 of file SbMathFilters.H'.
Referenced by analyseSeries(), SBFilterModel(), setUpSpecModel(), and ~SBFilterModel().
double SBFilterModel::SumW2 [protected]
Definition at line 86 of file SbMathFilters.H'.
Referenced by analyseSeries(), eliminateAfter(), and SBFilterModel().
double SBFilterModel::T0 [protected]
Definition at line 58 of file SbMathFilters.H'.
Referenced by analyseSeries(), modelFull(), modelKeep(), SBFilterModel(), setT0(), and t0().
double SBFilterModel::VTPV [protected]
Definition at line 85 of file SbMathFilters.H'.
Referenced by analyseSeries(), eliminateAfter(), and SBFilterModel().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.