SBFileConvLI
NAME
SBFileConvLI -
SYNOPSIS
#include <SbISetup.H>
Inherits QListViewItem'.
Public Member Functions
SBFileConvLI (QListView *parent, SBFileConv *Entry_)
virtual QString ClassName () const
SBFileConv * entry ()
virtual QString text (int) const
Private Attributes
SBFileConv * Entry
Detailed Description
Definition at line 40 of file SbISetup.H'.
Constructor & Destructor Documentation
SBFileConvLI::SBFileConvLI (QListView *parent, SBFileConv *Entry_) [inline]
Definition at line 45 of file SbISetup.H'.
References Entry.
Member Function Documentation
virtual QString SBFileConvLI::ClassName () const [inline, virtual]
Definition at line 47 of file SbISetup.H'.
SBFileConv* SBFileConvLI::entry () [inline]
Definition at line 48 of file SbISetup.H'.
References Entry.
Referenced by SBSetupDialog::chkPacker(), and SBSetupDialog::delPacker().
QString SBFileConvLI::text (intcol) const [virtual]
Definition at line 92 of file SbISetup.C'.
References SBFileConv::comCompr(), SBFileConv::comUncom(), Entry, SBFileConv::ext(), SBNamed::name(), and TmpString.
Member Data Documentation
SBFileConv* SBFileConvLI::Entry [private]
Definition at line 43 of file SbISetup.H'.
Referenced by entry(), SBFileConvLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.