SBFileConv
NAME
SBFileConv -
SYNOPSIS
#include <SbSetup.H>
Inherits SBNamed'.
Public Member Functions
SBFileConv (const QString &Name_='NONE', const QString &ComC_='cat', const QString &ComU_='cat', const QString &Ext_=' ')
SBFileConv (const SBFileConv &W)
virtual SBFileConv & operator= (const SBFileConv &W)
virtual ~SBFileConv ()
virtual QString ClassName () const
const QString & comCompr () const
const QString & comUncom () const
const QString & ext () const
void setComCompr (const QString &C_)
void setComUncom (const QString &C_)
void setExt (const QString &C_)
FILE * open4In (const QString &, QFile &, QDataStream &)
FILE * open4In (const QString &, QFile &, QTextStream &)
FILE * open4Out (const QString &, QFile &, QDataStream &)
FILE * open4Out (const QString &, QFile &, QTextStream &)
bool check ()
const QString & name () const
void setName (const QString &Name_)
Static Public Member Functions
static void close (QFile &, FILE *&, QDataStream &)
static void close (QFile &, FILE *&, QTextStream &)
Protected Attributes
QString Name
Private Attributes
QString ComCompr
QString ComUncom
QString Ext
Friends
class SBFCList
QDataStream & operator<< (QDataStream &s, const SBFileConv &F)
QDataStream & operator>> (QDataStream &s, SBFileConv &F)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
SBFileConv'.
Definition at line 49 of file SbSetup.H'.
Constructor & Destructor Documentation
SBFileConv::SBFileConv (const QString &Name_ = 'NONE', const QString &ComC_ = 'cat', const QString &ComU_ = 'cat', const QString &Ext_ = ' ') [inline]"A constructor'.
Definition at line 58 of file SbSetup.H'.
References ComCompr, ComUncom, and Ext.
SBFileConv::SBFileConv (const SBFileConv &W) [inline]
Definition at line 61 of file SbSetup.H'.
References ComCompr, ComUncom, and Ext.
virtual SBFileConv::~SBFileConv () [inline, virtual]"A destructor'.
Definition at line 73 of file SbSetup.H'.
Member Function Documentation
bool SBFileConv::check ()
Definition at line 219 of file SbSetup.C'.
References ClassName(), close(), ComCompr, ComUncom, SBLog::DBG, SBLog::ERR, SBLog::IO, Log, open4In(), open4Out(), and SBLog::write().
Referenced by SBSetupDialog::addPacker(), and SBSetupDialog::chkPacker().
virtual QString SBFileConv::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBNamed'.
Definition at line 75 of file SbSetup.H'.
Referenced by check(), open4In(), and open4Out().
void SBFileConv::close (QFile &file, FILE *&p, QDataStream &ds) [static]"Closes compressed in/output'. Closes a pipe and corresponded QFile object'.
Definition at line 197 of file SbSetup.C'.
Referenced by check().
void SBFileConv::close (QFile &file, FILE *&p, QTextStream &ts) [static]
Definition at line 208 of file SbSetup.C'.
const QString& SBFileConv::comCompr () const [inline]
Definition at line 78 of file SbSetup.H'.
References ComCompr.
Referenced by SBSetupDialog::chkPacker(), SBFCList::setDefault(), and SBFileConvLI::text().
const QString& SBFileConv::comUncom () const [inline]
Definition at line 79 of file SbSetup.H'.
References ComUncom.
Referenced by SBSetupDialog::chkPacker(), and SBFileConvLI::text().
const QString& SBFileConv::ext () const [inline]
Definition at line 80 of file SbSetup.H'.
References Ext.
Referenced by SBFCList::defaultExt(), SBFCList::insert(), and SBFileConvLI::text().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), open4In(), open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
FILE * SBFileConv::open4In (const QString &FileName, QFile &file, QDataStream &ds)"Create compressed input'. Opens a pipe through uncompress command, opens corresponded QFile, returns opened pipe or NULL if popen failed'.
Warning:
caller have to pclose returned value manually or call a SBFileConv::close'.
Definition at line 121 of file SbSetup.C'.
References ClassName(), ComUncom, SBLog::ERR, SBLog::IO, Log, SBNamed::name(), and SBLog::write().
Referenced by check(), and SBFCList::open4In().
FILE * SBFileConv::open4In (const QString &FileName, QFile &file, QTextStream &ts)
Definition at line 138 of file SbSetup.C'.
References ClassName(), ComUncom, SBLog::ERR, SBLog::IO, Log, SBNamed::name(), and SBLog::write().
FILE * SBFileConv::open4Out (const QString &FileName, QFile &file, QDataStream &ds)"Create compressed output'. Opens a pipe through compress command, opens corresponded QFile, returns opened pipe or NULL if popen failed'.
Warning:
caller have to pclose returned value manually or call a SBFileConv::close()'.
Definition at line 160 of file SbSetup.C'.
References ClassName(), ComCompr, SBLog::ERR, SBLog::IO, Log, SBNamed::name(), and SBLog::write().
Referenced by check(), SBFCList::open4Out(), and SBFCList::open4OutDflt().
FILE * SBFileConv::open4Out (const QString &FileName, QFile &file, QTextStream &ts)
Definition at line 177 of file SbSetup.C'.
References ClassName(), ComCompr, SBLog::ERR, SBLog::IO, Log, SBNamed::name(), and SBLog::write().
virtual SBFileConv& SBFileConv::operator= (const SBFileConv &W) [inline, virtual]
Definition at line 63 of file SbSetup.H'.
References ComCompr, ComUncom, and Ext.
void SBFileConv::setComCompr (const QString &C_) [inline]
Definition at line 81 of file SbSetup.H'.
References ComCompr.
void SBFileConv::setComUncom (const QString &C_) [inline]
Definition at line 82 of file SbSetup.H'.
References ComUncom.
void SBFileConv::setExt (const QString &C_) [inline]
Definition at line 83 of file SbSetup.H'.
References Ext.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBFileConv &F) [friend]
Definition at line 95 of file SbSetup.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBFileConv &F) [friend]
Definition at line 97 of file SbSetup.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
friend class SBFCList [friend]
Definition at line 51 of file SbSetup.H'.
Member Data Documentation
QString SBFileConv::ComCompr [private]
Definition at line 53 of file SbSetup.H'.
Referenced by check(), comCompr(), open4Out(), operator=(), SBFileConv(), and setComCompr().
QString SBFileConv::ComUncom [private]
Definition at line 54 of file SbSetup.H'.
Referenced by check(), comUncom(), open4In(), operator=(), SBFileConv(), and setComUncom().
QString SBFileConv::Ext [private]
Definition at line 55 of file SbSetup.H'.
Referenced by ext(), operator=(), SBFileConv(), and setExt().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.