SBFilteringGauss
NAME
SBFilteringGauss -
SYNOPSIS
#include <SbIFilters.H>
Inherits QDialog'.
Public Member Functions
SBFilteringGauss (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBFilteringGauss ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
void readDataFile ()
void makeAnalysis ()
void wrote2File ()
void changeNInterpolate (const QString &)
void changeFWHM (const QString &)
void changeStep (const QString &)
void changeEpoch (const QString &)
void changeByNum (int)
void setSigmasMode (int)
void setFilterType (int)
void calcSigmas ()
void makeAnalysisWith3Sigma ()
void substractFilter ()
Private Types
enum SIGMASMODE { SIG_MODE_0 = 0, SIG_MODE_1 = 1, SIG_MODE_2 = 2 }
enum FILTERTYPE { FILT_GAUSS = 0, FILT_GAUSS_APRIORY = 1 }
Private Member Functions
QWidget * wOptions ()
QWidget * wBrowseData ()
QWidget * wBrowseTF ()
void collectData ()
void redrawDataPlot ()
void redrawDataPlot_ExpMode ()
void redrawTFPlot ()
Private Attributes
QString Name
unsigned int NInterpolate
double Step
unsigned int NumOfCols
unsigned int NumOfDataCols
unsigned int NperTF
double FWHM
double Epoch
SBFilterGauss * Filter
bool IsByNum
bool IsFilterSubstracted
SIGMASMODE SMode
FILTERTYPE FType
QTabWidget * Tab
QLabel * lImportedFileName
QLabel * lNumOfPts
QLabel * lNumOfCols
QLabel * lDT
QLabel * lDTMinMax
QLabel * lInterval
QRadioButton * rbFilterType [1]
QRadioButton * rbSigmasMode [3]
QLineEdit * leNInterpolate
QLineEdit * leStep
QLineEdit * leFWHM
QLineEdit * leEpoch
QPushButton * Save
QPushButton * GetData
QPushButton * Analyse
QPushButton * Ok
SBPlotCarrier * PCData
SBPlot * PlotData
SBPlotCarrier * PCTF
SBPlot * PlotTF
QAccel * accel
Detailed Description
Definition at line 53 of file SbIFilters.H'.
Member Enumeration Documentation
enum SBFilteringGauss::FILTERTYPE [private]
Enumerator:
FILT_GAUSS
FILT_GAUSS_APRIORY
Definition at line 84 of file SbIFilters.H'.
enum SBFilteringGauss::SIGMASMODE [private]
Enumerator:
SIG_MODE_0
SIG_MODE_1
SIG_MODE_2
Definition at line 83 of file SbIFilters.H'.
Constructor & Destructor Documentation
SBFilteringGauss::SBFilteringGauss (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 58 of file SbIFilters.C'.
References accel, accept(), Analyse, calcSigmas(), Epoch, FILT_GAUSS, Filter, FType, FWHM, GetData, IsByNum, IsFilterSubstracted, makeAnalysis(), makeAnalysisWith3Sigma(), Name, NInterpolate, NperTF, NumOfCols, NumOfDataCols, Ok, readDataFile(), Save, SIG_MODE_0, SMode, Step, substractFilter(), Tab, wBrowseData(), wBrowseTF(), wOptions(), and wrote2File().
SBFilteringGauss::~SBFilteringGauss ()
Definition at line 130 of file SbIFilters.C'.
References Filter, PCData, and PlotData.
Member Function Documentation
void SBFilteringGauss::accept () [protected, slot]
Definition at line 401 of file SbIFilters.C'.
Referenced by SBFilteringGauss().
void SBFilteringGauss::calcSigmas () [protected, slot]
Definition at line 799 of file SbIFilters.C'.
References SBFilterGauss::calcSigma(), ClassName(), SBLog::DATA, Filter, SBLog::INF, SBFilterGauss::isOK(), Log, NumOfDataCols, SIG_MODE_0, SIG_MODE_1, SIG_MODE_2, SBFilterGauss::sigma(), SMode, and SBLog::write().
Referenced by SBFilteringGauss().
void SBFilteringGauss::changeByNum (intid) [protected, slot]
Definition at line 647 of file SbIFilters.C'.
References Filter, IsByNum, SBFilterGauss::isOK(), leNInterpolate, leStep, NInterpolate, Step, SBFilterGauss::tFinis(), and SBFilterGauss::tStart().
Referenced by wOptions().
void SBFilteringGauss::changeEpoch (const QString &Str) [protected, slot]
Definition at line 610 of file SbIFilters.C'.
References Epoch.
Referenced by wOptions().
void SBFilteringGauss::changeFWHM (const QString &Str) [protected, slot]
Definition at line 619 of file SbIFilters.C'.
References Filter, FWHM, redrawTFPlot(), and SBFilterGauss::setFWHM().
Referenced by wOptions().
void SBFilteringGauss::changeNInterpolate (const QString &Str) [protected, slot]
Definition at line 592 of file SbIFilters.C'.
References NInterpolate.
Referenced by wOptions().
void SBFilteringGauss::changeStep (const QString &Str) [protected, slot]
Definition at line 601 of file SbIFilters.C'.
References Step.
Referenced by wOptions().
virtual QString SBFilteringGauss::ClassName () const [inline, virtual]
Definition at line 59 of file SbIFilters.H'.
Referenced by calcSigmas(), makeAnalysisWith3Sigma(), readDataFile(), redrawDataPlot_ExpMode(), and wrote2File().
void SBFilteringGauss::collectData () [private]
Definition at line 537 of file SbIFilters.C'.
void SBFilteringGauss::makeAnalysis () [protected, slot]
Definition at line 542 of file SbIFilters.C'.
References FILT_GAUSS_APRIORY, FType, redrawDataPlot(), and redrawDataPlot_ExpMode().
Referenced by SBFilteringGauss(), and substractFilter().
void SBFilteringGauss::makeAnalysisWith3Sigma () [protected, slot]
Definition at line 566 of file SbIFilters.C'.
References SBAttributed::addAttr(), ClassName(), SBLog::DATA, SBAttributed::delAttr(), Filter, SBLog::INF, SBFilterGauss::isOK(), SBFilterGauss::IsOmit3Sigma, Log, NumOfDataCols, redrawDataPlot(), SIG_MODE_0, SIG_MODE_1, SIG_MODE_2, SBFilterGauss::sigma(), SMode, and SBLog::write().
Referenced by SBFilteringGauss().
void SBFilteringGauss::readDataFile () [protected, slot]
Definition at line 472 of file SbIFilters.C'.
References ClassName(), SBLog::DATA, SBLog::DBG, SBDataSeries::dT(), SBDataSeries::dTMax(), SBDataSeries::dTMin(), Filter, SBLog::INF, IsByNum, IsFilterSubstracted, SBFilterGauss::isOK(), lDT, lDTMinMax, leNInterpolate, leStep, lImportedFileName, lInterval, lNumOfCols, lNumOfPts, Log, SBFilterGauss::n(), Name, NInterpolate, NumOfCols, NumOfDataCols, SBDataSeries::numOfDataColumns(), SBSetUp::path2TimeSeries(), rbSigmasMode, SBFilterGauss::readDataFile(), redrawDataPlot(), redrawTFPlot(), SBFilterGauss::series(), SetUp, SIG_MODE_0, SMode, Step, SBFilterGauss::tFinis(), SBFilterGauss::tStart(), and SBLog::write().
Referenced by SBFilteringGauss().
void SBFilteringGauss::redrawDataPlot () [private]
Definition at line 671 of file SbIFilters.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, SBPlotBranch::data(), SBPlot::dataChanged(), SBDataSeries::dT(), Epoch, Filter, SBFilterGauss::interpolate(), IsByNum, SBFilterGauss::isOK(), leNInterpolate, leStep, SBFilterGauss::n(), Name, NInterpolate, NumOfDataCols, SBSetUp::path2TimeSeries(), PCData, PlotData, SBFilterGauss::series(), SBMatrix::set(), SBPlotCarrier::setAbsFile4SaveBaseName(), SetUp, SIG_MODE_0, SIG_MODE_1, SIG_MODE_2, SMode, SBFilterGauss::stdVar(), Step, SBFilterGauss::tFinis(), and SBFilterGauss::tStart().
Referenced by makeAnalysis(), makeAnalysisWith3Sigma(), and readDataFile().
void SBFilteringGauss::redrawDataPlot_ExpMode () [private]
Definition at line 827 of file SbIFilters.C'.
References SBFilterGauss::addModel(), SBPlotCarrier::branches(), ClassName(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, SBPlotBranch::data(), SBLog::DATA, SBPlot::dataChanged(), SBDataSeries::dT(), Epoch, SBLog::ERR, Filter, SBPlotBranchList::find(), SBFilterGauss::interpolateMinusModel(), IsByNum, SBFilterGauss::isOK(), leNInterpolate, leStep, Log, SBFilterGauss::modelByIdx(), SBFilterModel::modelFull(), SBFilterModel::modelKeep(), SBFilterGauss::modelList(), SBFilterGauss::n(), Name, NInterpolate, NumOfDataCols, SBSetUp::path2TimeSeries(), PCData, PlotData, SBFilterGauss::prepareModels(), SBFilterGauss::seriesMinusModel(), SBMatrix::set(), SBPlotCarrier::setAbsFile4SaveBaseName(), SBNamed::setName(), SetUp, SIG_MODE_0, SIG_MODE_1, SIG_MODE_2, SMode, SBFilterGauss::stdVar(), Step, SBFilterGauss::tFinis(), SBFilterGauss::tStart(), and SBLog::write().
Referenced by makeAnalysis().
void SBFilteringGauss::redrawTFPlot () [private]
Definition at line 772 of file SbIFilters.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::DA_IGN, SBPlotBranch::data(), SBPlot::dataChanged(), SBDataSeries::dT(), Filter, SBFilterGauss::isOK(), NperTF, PCTF, PlotTF, SBFilterGauss::respFunc(), SBFilterGauss::series(), SBMatrix::set(), SBPlotBranch::setDataAttr(), SBFilterGauss::tFinis(), and SBFilterGauss::tStart().
Referenced by changeFWHM(), and readDataFile().
void SBFilteringGauss::reject () [protected, slot]
Definition at line 407 of file SbIFilters.C'.
void SBFilteringGauss::setFilterType (intid) [protected, slot]
Definition at line 641 of file SbIFilters.C'.
References FType.
Referenced by wOptions().
void SBFilteringGauss::setSigmasMode (intid) [protected, slot]
Definition at line 635 of file SbIFilters.C'.
References SMode.
Referenced by wOptions().
void SBFilteringGauss::substractFilter () [protected, slot]
Definition at line 550 of file SbIFilters.C'.
References FILT_GAUSS_APRIORY, Filter, FType, IsFilterSubstracted, SBFilterGauss::isOK(), makeAnalysis(), SMode, and SBFilterGauss::substractFilter().
Referenced by SBFilteringGauss().
QWidget * SBFilteringGauss::wBrowseData () [private]
Definition at line 344 of file SbIFilters.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, Name, SBSetUp::path2TimeSeries(), PCData, PlotData, SBPlotCarrier::setAbsFile4SaveBaseName(), SBPlotCarrier::setStdVarIdx(), and SetUp.
Referenced by SBFilteringGauss().
QWidget * SBFilteringGauss::wBrowseTF () [private]
Definition at line 370 of file SbIFilters.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, SBPlotBranch::data(), Name, NperTF, SBSetUp::path2TimeSeries(), PCTF, PlotTF, SBPlot::PM_HAS_HAVE_ZERO, SBPlot::PM_LINES, SBPlot::PM_WO_BRANCH_NAMES, SBPlot::PM_WO_DOTS, SBMatrix::set(), SBPlotCarrier::setAbsFile4SaveBaseName(), SBPlotBranch::setDataAttr(), and SetUp.
Referenced by SBFilteringGauss().
QWidget * SBFilteringGauss::wOptions () [private]
Definition at line 150 of file SbIFilters.C'.
References changeByNum(), changeEpoch(), changeFWHM(), changeNInterpolate(), changeStep(), Epoch, FWHM, lDT, lDTMinMax, leEpoch, leFWHM, leNInterpolate, leStep, lImportedFileName, lInterval, lNumOfCols, lNumOfPts, NInterpolate, NumOfCols, rbFilterType, rbSigmasMode, setFilterType(), setSigmasMode(), SMode, and Step.
Referenced by SBFilteringGauss().
void SBFilteringGauss::wrote2File () [protected, slot]
Definition at line 413 of file SbIFilters.C'.
References SBPlotCarrier::branches(), ClassName(), SBLog::DATA, SBLog::DBG, Filter, IsFilterSubstracted, SBFilterGauss::isOK(), Log, Name, NInterpolate, NumOfCols, NumOfDataCols, SBSetUp::path2TimeSeries(), PCData, SBFilterGauss::series(), SetUp, and SBLog::write().
Referenced by SBFilteringGauss().
Member Data Documentation
QAccel* SBFilteringGauss::accel [private]
Definition at line 147 of file SbIFilters.H'.
Referenced by SBFilteringGauss().
QPushButton* SBFilteringGauss::Analyse [private]
Definition at line 124 of file SbIFilters.H'.
Referenced by SBFilteringGauss().
double SBFilteringGauss::Epoch [private]
Definition at line 93 of file SbIFilters.H'.
Referenced by changeEpoch(), redrawDataPlot(), redrawDataPlot_ExpMode(), SBFilteringGauss(), and wOptions().
SBFilterGauss* SBFilteringGauss::Filter [private]
Definition at line 94 of file SbIFilters.H'.
Referenced by calcSigmas(), changeByNum(), changeFWHM(), makeAnalysisWith3Sigma(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), redrawTFPlot(), SBFilteringGauss(), substractFilter(), wrote2File(), and ~SBFilteringGauss().
FILTERTYPE SBFilteringGauss::FType [private]
Definition at line 98 of file SbIFilters.H'.
Referenced by makeAnalysis(), SBFilteringGauss(), setFilterType(), and substractFilter().
double SBFilteringGauss::FWHM [private]
Definition at line 92 of file SbIFilters.H'.
Referenced by changeFWHM(), SBFilteringGauss(), and wOptions().
QPushButton* SBFilteringGauss::GetData [private]
Definition at line 123 of file SbIFilters.H'.
Referenced by SBFilteringGauss().
bool SBFilteringGauss::IsByNum [private]
Definition at line 95 of file SbIFilters.H'.
Referenced by changeByNum(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), and SBFilteringGauss().
bool SBFilteringGauss::IsFilterSubstracted [private]
Definition at line 96 of file SbIFilters.H'.
Referenced by readDataFile(), SBFilteringGauss(), substractFilter(), and wrote2File().
QLabel* SBFilteringGauss::lDT [private]
Definition at line 108 of file SbIFilters.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBFilteringGauss::lDTMinMax [private]
Definition at line 109 of file SbIFilters.H'.
Referenced by readDataFile(), and wOptions().
QLineEdit* SBFilteringGauss::leEpoch [private]
Definition at line 118 of file SbIFilters.H'.
Referenced by wOptions().
QLineEdit* SBFilteringGauss::leFWHM [private]
Definition at line 117 of file SbIFilters.H'.
Referenced by wOptions().
QLineEdit* SBFilteringGauss::leNInterpolate [private]
Definition at line 115 of file SbIFilters.H'.
Referenced by changeByNum(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), and wOptions().
QLineEdit* SBFilteringGauss::leStep [private]
Definition at line 116 of file SbIFilters.H'.
Referenced by changeByNum(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), and wOptions().
QLabel* SBFilteringGauss::lImportedFileName [private]
Definition at line 105 of file SbIFilters.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBFilteringGauss::lInterval [private]
Definition at line 110 of file SbIFilters.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBFilteringGauss::lNumOfCols [private]
Definition at line 107 of file SbIFilters.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBFilteringGauss::lNumOfPts [private]
Definition at line 106 of file SbIFilters.H'.
Referenced by readDataFile(), and wOptions().
QString SBFilteringGauss::Name [private]
Definition at line 86 of file SbIFilters.H'.
Referenced by readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), SBFilteringGauss(), wBrowseData(), wBrowseTF(), and wrote2File().
unsigned int SBFilteringGauss::NInterpolate [private]
Definition at line 87 of file SbIFilters.H'.
Referenced by changeByNum(), changeNInterpolate(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), SBFilteringGauss(), wOptions(), and wrote2File().
unsigned int SBFilteringGauss::NperTF [private]
Definition at line 91 of file SbIFilters.H'.
Referenced by redrawTFPlot(), SBFilteringGauss(), and wBrowseTF().
unsigned int SBFilteringGauss::NumOfCols [private]
Definition at line 89 of file SbIFilters.H'.
Referenced by readDataFile(), SBFilteringGauss(), wOptions(), and wrote2File().
unsigned int SBFilteringGauss::NumOfDataCols [private]
Definition at line 90 of file SbIFilters.H'.
Referenced by calcSigmas(), makeAnalysisWith3Sigma(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), SBFilteringGauss(), and wrote2File().
QPushButton* SBFilteringGauss::Ok [private]
Definition at line 125 of file SbIFilters.H'.
Referenced by SBFilteringGauss().
SBPlotCarrier* SBFilteringGauss::PCData [private]
Definition at line 136 of file SbIFilters.H'.
Referenced by redrawDataPlot(), redrawDataPlot_ExpMode(), wBrowseData(), wrote2File(), and ~SBFilteringGauss().
SBPlotCarrier* SBFilteringGauss::PCTF [private]
Definition at line 142 of file SbIFilters.H'.
Referenced by redrawTFPlot(), and wBrowseTF().
SBPlot* SBFilteringGauss::PlotData [private]
Definition at line 137 of file SbIFilters.H'.
Referenced by redrawDataPlot(), redrawDataPlot_ExpMode(), wBrowseData(), and ~SBFilteringGauss().
SBPlot* SBFilteringGauss::PlotTF [private]
Definition at line 143 of file SbIFilters.H'.
Referenced by redrawTFPlot(), and wBrowseTF().
QRadioButton* SBFilteringGauss::rbFilterType[1] [private]
Definition at line 112 of file SbIFilters.H'.
Referenced by wOptions().
QRadioButton* SBFilteringGauss::rbSigmasMode[3] [private]
Definition at line 113 of file SbIFilters.H'.
Referenced by readDataFile(), and wOptions().
QPushButton* SBFilteringGauss::Save [private]
Definition at line 122 of file SbIFilters.H'.
Referenced by SBFilteringGauss().
SIGMASMODE SBFilteringGauss::SMode [private]
Definition at line 97 of file SbIFilters.H'.
Referenced by calcSigmas(), makeAnalysisWith3Sigma(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), SBFilteringGauss(), setSigmasMode(), substractFilter(), and wOptions().
double SBFilteringGauss::Step [private]
Definition at line 88 of file SbIFilters.H'.
Referenced by changeByNum(), changeStep(), readDataFile(), redrawDataPlot(), redrawDataPlot_ExpMode(), SBFilteringGauss(), and wOptions().
QTabWidget* SBFilteringGauss::Tab [private]
Definition at line 101 of file SbIFilters.H'.
Referenced by SBFilteringGauss().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.