SBFrame
NAME
SBFrame -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits Matrix3, and SBNamed'.
Inherited by SBFrameClassic, and SBFrameNRO'.
Public Member Functions
SBFrame (const SBConfig *, SBRunManager *, const QString &='Frame transformation general interface')
virtual ~SBFrame ()
virtual QString ClassName () const
virtual void calc (const SBMJD &)=0
virtual double gst () const =0
virtual double gmst () const =0
virtual double diurnalDUT1 () const
virtual double diurnalDX () const
virtual double diurnalDY () const
const SBTime & time () const
SBEOP * eop ()
const SBOTideEOPGeneral * eopDiurnal () const
virtual const Matrix3 & crs2trs () const
virtual const Matrix3 & dQ_dt () const
virtual const Matrix3 & dQ_dUT () const
virtual const Matrix3 & dQ_dxp ()
virtual const Matrix3 & dQ_dyp ()
virtual const Matrix3 & dQ_dpsi ()
virtual const Matrix3 & dQ_deps ()
virtual const Matrix3 & dQ_dprec ()
virtual double polar_X () const =0
virtual double polar_Y () const =0
virtual double polar_UT1_UTC () const
virtual double dNutation_Psi () const =0
virtual double dNutation_Eps () const =0
virtual double totNutationLongitude () const =0
virtual double totNutationObliquity () const =0
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
const SBConfig * Cfg
SBRunManager * Mgr
SBTime Time
SBOTideEOPGeneral * EOPdiurnal
SBOTideEOPGeneral * EOPdiurnalAtm
SBOTideEOPGeneral * EOPdiurnalNTd
SBOTideEOPGeneral * EOPdiurnalGrv
SBEOP * EOP
double UT1_UTC
Matrix3 CRS2TRS
Matrix3 DQ_dt
Matrix3 DQ_dUT
Matrix3 DQ_dxp
Matrix3 DQ_dyp
Matrix3 DQ_dpsi
Matrix3 DQ_deps
Matrix3 DQ_dprec
double mat [3][3]
QString Name
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Matrix transformation TRS to CRS (i'.e'., [CRS] = *this*[TRS]), general'. Describes general interface for system transformation'.
Definition at line 612 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBFrame::SBFrame (const SBConfig *Cfg_, SBRunManager *Mgr_, const QString &Name_ = 'Frame transformation general interface')"A constructor'. Creates a copy of object'.
Definition at line 775 of file SbGeoRefFrame.C'.
References Cfg, SBConfig::EDM_Gipson1995, SBConfig::EDM_GSFC95, SBConfig::EDM_HD1994, SBConfig::EDM_JPL92, SBConfig::EDM_NONE, SBConfig::EDM_Ray1995, SBConfig::EDMA_BBP, SBConfig::EDMA_NONE, SBConfig::EDMNT_NONE, SBConfig::EDMNT_Viron, EOP, SBConfig::eopDiurnal(), EOPdiurnal, SBConfig::eopDiurnalAtm(), EOPdiurnalAtm, EOPdiurnalGrv, SBConfig::eopDiurnalNonTidal(), EOPdiurnalNTd, SBConfig::eopNumIntrplPoints(), SBSetUp::loadEOP(), Mgr, SBConfig::NM_IAU2000, SBConfig::nutModel(), SBTime::setEOP(), SetUp, Time, and UT1_UTC.
SBFrame::~SBFrame () [virtual]"A destructor'.
Definition at line 827 of file SbGeoRefFrame.C'.
References EOP, EOPdiurnal, EOPdiurnalAtm, EOPdiurnalGrv, and EOPdiurnalNTd.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
virtual void SBFrame::calc (const SBMJD &) [pure virtual]"Calculates matrixes for the time T'.
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by SBDelay::calc(), collectListOfSINEXParameters4NEQ(), SBTestFrame::createWidget4Test(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestEphem::frameChanged(), SBRunManager::makeReportEOP(), SBTestFrame::recalc(), and SBTestEphem::recalc().
virtual QString SBFrame::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBNamed'.
Reimplemented in SBFrameNRO, and SBFrameClassic'.
Definition at line 645 of file SbGeoRefFrame.H'.
virtual const Matrix3& SBFrame::crs2trs () const [inline, virtual]
Definition at line 677 of file SbGeoRefFrame.H'.
References CRS2TRS.
Referenced by SBDelay::calc(), and SBSolidTideLd::operator()().
virtual double SBFrame::diurnalDUT1 () const [inline, virtual]"Returns diurnal variations in UT1'.
Definition at line 653 of file SbGeoRefFrame.H'.
References SBOTideEOPGeneral::dUT1_UT1D(), EOPdiurnal, EOPdiurnalAtm, EOPdiurnalGrv, and EOPdiurnalNTd.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), SBTestFrame::createWidget4Test(), and SBTestFrame::displayValues().
virtual double SBFrame::diurnalDX () const [inline, virtual]"Returns diurnal variations in X-pole'.
Definition at line 660 of file SbGeoRefFrame.H'.
References SBOTideEOPGeneral::dx_xD(), EOPdiurnal, EOPdiurnalAtm, EOPdiurnalGrv, and EOPdiurnalNTd.
Referenced by SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBPolus::operator()(), and SBPolusNRO::operator()().
virtual double SBFrame::diurnalDY () const [inline, virtual]"Returns diurnal variations in Y-pole'.
Definition at line 667 of file SbGeoRefFrame.H'.
References SBOTideEOPGeneral::dy_yD(), EOPdiurnal, EOPdiurnalAtm, EOPdiurnalGrv, and EOPdiurnalNTd.
Referenced by SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBPolus::operator()(), and SBPolusNRO::operator()().
virtual double SBFrame::dNutation_Eps () const [pure virtual]
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by SBRunManager::makeReportEOP().
virtual double SBFrame::dNutation_Psi () const [pure virtual]
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by SBRunManager::makeReportEOP().
virtual const Matrix3& SBFrame::dQ_deps () [inline, virtual]
Reimplemented in SBFrameNRO, and SBFrameClassic'.
Definition at line 683 of file SbGeoRefFrame.H'.
References DQ_deps.
Referenced by SBDelay::calcDerivatives().
virtual const Matrix3& SBFrame::dQ_dprec () [inline, virtual]
Reimplemented in SBFrameClassic'.
Definition at line 685 of file SbGeoRefFrame.H'.
References DQ_dprec.
virtual const Matrix3& SBFrame::dQ_dpsi () [inline, virtual]
Reimplemented in SBFrameNRO, and SBFrameClassic'.
Definition at line 682 of file SbGeoRefFrame.H'.
References DQ_dpsi.
Referenced by SBDelay::calcDerivatives().
virtual const Matrix3& SBFrame::dQ_dt () const [inline, virtual]
Definition at line 678 of file SbGeoRefFrame.H'.
References DQ_dt.
Referenced by SBDelay::calc().
virtual const Matrix3& SBFrame::dQ_dUT () const [inline, virtual]
Definition at line 679 of file SbGeoRefFrame.H'.
References DQ_dUT.
Referenced by SBDelay::calcDerivatives().
virtual const Matrix3& SBFrame::dQ_dxp () [inline, virtual]
Reimplemented in SBFrameNRO, and SBFrameClassic'.
Definition at line 680 of file SbGeoRefFrame.H'.
References DQ_dxp.
Referenced by SBDelay::calcDerivatives().
virtual const Matrix3& SBFrame::dQ_dyp () [inline, virtual]
Reimplemented in SBFrameNRO, and SBFrameClassic'.
Definition at line 681 of file SbGeoRefFrame.H'.
References DQ_dyp.
Referenced by SBDelay::calcDerivatives().
SBEOP* SBFrame::eop () [inline]
Definition at line 675 of file SbGeoRefFrame.H'.
References EOP.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBTestFrame::createWidget4Test(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBRunManager::fillParameterList(), SBRunManager::makeReportEOP(), SBTideLd::operator()(), operator<<(), SBRunManager::process_m1(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBRunManager::SBRunManager(), SBTestFrame::SBTestFrame(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), writeNormalEquationSystem(), and SBRunManager::~SBRunManager().
const SBOTideEOPGeneral* SBFrame::eopDiurnal () const [inline]
Definition at line 676 of file SbGeoRefFrame.H'.
References EOPdiurnal.
Referenced by SBTestFrame::createWidget4Test().
virtual double SBFrame::gmst () const [pure virtual]"Returns Mean Greenwich Sidereal Time, rad
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBSolidTideLd::makeStep2(), SBSolidTideLdIERS96::makeStep2(), and SBRefraction::operator()().
virtual double SBFrame::gst () const [pure virtual]"Returns Apparent Greenwich Sidereal Time, rad
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by SBTestFrame::createWidget4Test(), and SBTestFrame::displayValues().
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
virtual double SBFrame::polar_UT1_UTC () const [inline, virtual]
Definition at line 689 of file SbGeoRefFrame.H'.
References UT1_UTC.
Referenced by collectListOfSINEXParameters4NEQ(), and SBRunManager::makeReportEOP().
virtual double SBFrame::polar_X () const [pure virtual]
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by collectListOfSINEXParameters4NEQ(), and SBRunManager::makeReportEOP().
virtual double SBFrame::polar_Y () const [pure virtual]
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by collectListOfSINEXParameters4NEQ(), and SBRunManager::makeReportEOP().
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
const SBTime& SBFrame::time () const [inline]"Returns time T'.
Definition at line 674 of file SbGeoRefFrame.H'.
References Time.
Referenced by SBDelay::calc(), SBDelay::calcDerivatives(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBSolidTideLdIERS96::makeStep2(), SBSolidTideLd::operator()(), SBTideLd::operator()(), and SBRefraction::operator()().
virtual double SBFrame::totNutationLongitude () const [pure virtual]
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by collectListOfSINEXParameters4NEQ().
virtual double SBFrame::totNutationObliquity () const [pure virtual]
Implemented in SBFrameNRO, and SBFrameClassic'.
Referenced by collectListOfSINEXParameters4NEQ().
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
const SBConfig* SBFrame::Cfg [protected]
Definition at line 615 of file SbGeoRefFrame.H'.
Referenced by SBFrame(), and SBFrameClassic::SBFrameClassic().
Matrix3 SBFrame::CRS2TRS [protected]
Definition at line 625 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), and crs2trs().
Matrix3 SBFrame::DQ_deps [protected]
Definition at line 633 of file SbGeoRefFrame.H'.
Referenced by dQ_deps(), SBFrameClassic::dQ_deps(), and SBFrameNRO::dQ_deps().
Matrix3 SBFrame::DQ_dprec [protected]
Definition at line 635 of file SbGeoRefFrame.H'.
Referenced by dQ_dprec(), and SBFrameClassic::dQ_dprec().
Matrix3 SBFrame::DQ_dpsi [protected]
Definition at line 632 of file SbGeoRefFrame.H'.
Referenced by dQ_dpsi(), SBFrameClassic::dQ_dpsi(), and SBFrameNRO::dQ_dpsi().
Matrix3 SBFrame::DQ_dt [protected]
Definition at line 626 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), and dQ_dt().
Matrix3 SBFrame::DQ_dUT [protected]
Definition at line 629 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), and dQ_dUT().
Matrix3 SBFrame::DQ_dxp [protected]
Definition at line 630 of file SbGeoRefFrame.H'.
Referenced by dQ_dxp(), SBFrameClassic::dQ_dxp(), and SBFrameNRO::dQ_dxp().
Matrix3 SBFrame::DQ_dyp [protected]
Definition at line 631 of file SbGeoRefFrame.H'.
Referenced by dQ_dyp(), SBFrameClassic::dQ_dyp(), and SBFrameNRO::dQ_dyp().
SBEOP* SBFrame::EOP [protected]
Definition at line 623 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), eop(), SBFrame(), SBFrameClassic::SBFrameClassic(), and ~SBFrame().
SBOTideEOPGeneral* SBFrame::EOPdiurnal [protected]
Definition at line 618 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), diurnalDUT1(), diurnalDX(), diurnalDY(), eopDiurnal(), SBFrame(), and ~SBFrame().
SBOTideEOPGeneral* SBFrame::EOPdiurnalAtm [protected]
Definition at line 619 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), diurnalDUT1(), diurnalDX(), diurnalDY(), SBFrame(), and ~SBFrame().
SBOTideEOPGeneral* SBFrame::EOPdiurnalGrv [protected]
Definition at line 621 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), diurnalDUT1(), diurnalDX(), diurnalDY(), SBFrame(), and ~SBFrame().
SBOTideEOPGeneral* SBFrame::EOPdiurnalNTd [protected]
Definition at line 620 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), diurnalDUT1(), diurnalDX(), diurnalDY(), SBFrame(), and ~SBFrame().
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
SBRunManager* SBFrame::Mgr [protected]
Definition at line 616 of file SbGeoRefFrame.H'.
Referenced by SBFrame().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
SBTime SBFrame::Time [protected]
Definition at line 617 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), SBFrame(), and time().
double SBFrame::UT1_UTC [protected]
Definition at line 624 of file SbGeoRefFrame.H'.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), polar_UT1_UTC(), and SBFrame().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.