SbGeoObsVLBI_IO.C
NAME
SbGeoObsVLBI_IO.C -
SYNOPSIS
#include <math.h>
#include <stdio.h>
#include <qmessagebox.h>
#include <qregexp.h>
#include <qdir.h>
#include <qfile.h>
#include 'SbGeoObsVLBI_IO.H'
#include 'SbGeoStations.H'
#include 'SbGeoSources.H'
#include 'SbSetup.H'
Functions
SBTS_ngs & operator<< (SBTS_ngs &s, const SBVLBISession &)
SBDS_dbh & operator>> (SBDS_dbh &s, SBDBHPhysRec &PH)
SBDS_dbh & operator>> (SBDS_dbh &s, SBDBHHistTriplet &HT)
SBDS_dbh & operator>> (SBDS_dbh &s, SBDBHTCBlock &B)
SBDS_dbh & operator>> (SBDS_dbh &s, SBDBHStartBlock &S)
SBDS_dbh & operator>> (SBDS_dbh &s, SBDBHFormat &F)
Function Documentation
SBTS_ngs& operator<< (SBTS_ngs &s, const SBVLBISession &)
Definition at line 47 of file SbGeoObsVLBI_IO.C'.
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHPhysRec &PH)
Definition at line 2325 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, SBLog::ERR, SBDBHPhysRec::isOK, SBDBHPhysRec::Length, Log, SBDBHPhysRec::parseLR(), and SBLog::write().
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHHistTriplet &HT)
Definition at line 2478 of file SbGeoObsVLBI_IO.C'.
References SBLog::DATA, SBLog::ERR, SBDBHLRecHS1::histLength(), SBDBHPhysRec::isOk(), SBDBHHistTriplet::isOK, SBDBHLRecPrefixed::isP(), SBDBHPhysRec::length(), Log, SBDBHHistTriplet::Rec1, SBDBHHistTriplet::Rec2, SBDBHHistTriplet::Rec3, SBDBHDRecString::text(), and SBLog::write().
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHTCBlock &B)
Definition at line 2557 of file SbGeoObsVLBI_IO.C'.
References SBDBHTCBlock::isLast(), SBDBHPhysRec::isOk(), SBDBHTCBlock::isOK, SBDBHTCBlock::ListTEBlock, SBDBHLRecTC::numTEBlocks(), and SBDBHTCBlock::Rec.
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHStartBlock &S)
Definition at line 2599 of file SbGeoObsVLBI_IO.C'.
References SBDBHStartBlock::Date, SBDBHStartBlock::DateVal, SBDBHStartBlock::DbName, SBDBHStartBlock::ExpDescr, SBDBHPhysRec::isOk(), SBDBHStartBlock::isOK, SBDBHStartBlock::Prev, SBDBHStartBlock::PrevDb, SBDBHStartBlock::SessID, and SBDBHStartBlock::Ver.
SBDS_dbh& operator>> (SBDS_dbh &s, SBDBHFormat &F)
Definition at line 2818 of file SbGeoObsVLBI_IO.C'.
References SBDBHTCBlock::isLast(), SBDBHFormat::isOK, SBDBHFormat::ListTCBlock, and SBDBHFormat::postRead().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.