.TH "SbGeoProject.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoProject.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <qapplication\&.h>\fP
.br
\fC#include <qdatetime\&.h>\fP
.br
\fC#include <qdir\&.h>\fP
.br
\fC#include <qfile\&.h>\fP
.br
\fC#include <qfileinfo\&.h>\fP
.br
\fC#include <qmessagebox\&.h>\fP
.br
\fC#include <qregexp\&.h>\fP
.br
\fC#include 'SbGeoAtmLoad\&.H'\fP
.br
\fC#include 'SbGeoEstimator\&.H'\fP
.br
\fC#include 'SbGeoParameter\&.H'\fP
.br
\fC#include 'SbGeoEphem\&.H'\fP
.br
\fC#include 'SbGeoProject\&.H'\fP
.br
\fC#include 'SbGeoStations\&.H'\fP
.br
\fC#include 'SbGeoSources\&.H'\fP
.br
\fC#include 'SbGeoRefFrame\&.H'\fP
.br
\fC#include 'SbGeoEop\&.H'\fP
.br
\fC#include 'SbSetup\&.H'\fP
.br
\fC#include 'SbGeoDelay\&.H'\fP
.br
\fC#include 'SbGeoTide\&.H'\fP
.br
\fC#include 'SbGeoRefraction\&.H'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBSBConfig\fP \fBDefaultConfig\fP"
.br
.ti -1c
.RI "\fBSBConfig\fP \fBConfig\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBSBConfig\fP \fBConfig\fP"
.PP
Definition at line 52 of file SbGeoProject\&.C'\&.
.PP
Referenced by SBEOP::interpolateEOPs(), SBSetUp::LoadStuff(), SBVLBIPreProcess::preProcess(), SBSetUp::SaveStuff(), SBStuffEphem::SBStuffEphem(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBMainWindow::StuffModels(), SBVLBIPreProcess::wEstPars(), SBModelEditor::~SBModelEditor(), and SBParametersEditor::~SBParametersEditor()\&.
.SS "const \fBSBConfig\fP \fBDefaultConfig\fP"
.PP
Definition at line 51 of file SbGeoProject\&.C'\&.
.PP
Referenced by SBSetUp::LoadStuff(), SBModelEditor::makeDefault(), SBParametersEditor::makeDefault(), SBParEditor::makeDefault(), and SBStationInfo::SBStationInfo()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
