SbGeoSINEX.C
NAME
SbGeoSINEX.C -
SYNOPSIS
#include 'sys/utsname.h'
#include 'SbGeoSINEX.H'
#include 'SbGeoStations.H'
#include 'SbGeoSources.H'
#include <qmessagebox.h>
#include <qfile.h>
#include 'SbSetup.H'
#include 'SbGeoAtmLoad.H'
#include 'SbGeoDelay.H'
#include 'SbGeoEop.H'
#include 'SbGeoProject.H'
#include 'SbGeoRefFrame.H'
Functions
void collectListOfSINEXParameters (SBParameterList *LastGlb, SBSymMatrix *LastP, SBSINEXParameterList *SINEX_List, SBSymMatrix *&SINEX_P, SBRunManager *RunMgr)
void collectListOfSINEXParameters4NEQ (SBParameterList *PList, SBSINEXParameterList *SINEX_List, SBRunManager *RunMgr)
void sinex_Comments (QTextStream &s, const QString &Comments)
void sinex_HeaderLine (QTextStream &s, double SINEX_VER, const SBMJD &CreationTime, const SBMJD &TStart, const SBMJD &TFinis, int NumberOfPars, unsigned int SContents, bool IsNEQ)
void sinex_TrailerLine (QTextStream &s)
void sinex_FileReferenceBlock (QTextStream &s, const QString &DescriptionItem, const QString &OutputItem, const QString &InputItem)
void sinex_FileCommentBlock (QTextStream &s, const QString &Comment)
void sinex_InputHistoryBlock (QTextStream &s, double SINEX_VER, const SBMJD &CreationTime, const SBMJD &TStart, const SBMJD &TFinis, int NumberOfPars, unsigned int SContents, bool IsNEQ)
void sinex_InputFilesBlock (QTextStream &s, const SBMJD &CreationTime, const QString &FileName, const QString &FileDescr)
void sinex_InputAcknowledgementsBlock (QTextStream &s)
void sinex_NutationDataBlock (QTextStream &s, const QString &NutCode, const QString &NutDescr)
void sinex_PrecessionDataBlock (QTextStream &s, const QString &PrecCode, const QString &PrecDescr)
void sinex_SourceIDBlock (QTextStream &s, SB_CRF *CRF, SBProject *Prj, SBParameterList *List, SBSINEXParameterList *SINEX_List)
void sinex_SiteIDBlock (QTextStream &s, SB_TRF *TRF, SBProject *Prj, SBParameterList *List)
void sinex_SiteEccentricityBlock (QTextStream &s, SB_TRF *TRF, SBProject *Prj, SBVLBISet *VLBI, SBParameterList *List)
void sinex_SolutionEpochsBlock (QTextStream &s, SB_TRF *TRF, SBParameterList *List)
void sinex_SolutionStatisticsBlock (QTextStream &s, SBStatistics *Statistics)
void sinex_SolutionEstimateBlock (QTextStream &s, SBSINEXParameterList *SINEX_List)
void sinex_SolutionAprioriBlock (QTextStream &s, SBSINEXParameterList *SINEX_List)
void sinex_SolutionMatrixEstimateBlock (QTextStream &s, bool IsEstimate, SBSymMatrix *P)
void sinex_SolutionNormalEquationMatrixBlock (QTextStream &s, SBSymMatrix *N)
void sinex_SolutionNormalEquationVectorBlock (QTextStream &s, SBSINEXParameterList *SINEX_List, SBVector *B)
void sinex_tro_HeaderLine (QTextStream &s, double SINEX_TRO_VER, const SBMJD &CreationTime, const SBMJD &TStart, const SBMJD &TFinis)
void sinex_tro_TrailerLine (QTextStream &s)
void sinex_tro_SiteIDBlock (QTextStream &s, SB_TRF *TRF, SBStationInfoList *Stations)
void sinex_tro_StaCoordinatesBlock (QTextStream &s, SB_TRF *TRF, SBStationInfoList *Stations, SBRunManager *RunMgr, const SBMJD &T)
void sinex_tro_TropDescriptionBlock (QTextStream &s, SBRunManager *RunMgr, SBVLBISession &Session)
void sinex_tro_TropSolutionStation (QTextStream &s, SBRunManager *, SBVLBISession &, SBStationInfo *SI, SBStation *Station, SBTropRecordList *Trops)
void sinex_tro_TropSolutionBlock (QTextStream &s, SBRunManager *RunMgr, SBVLBISession &Session, QDict< SBTropRecordList > *TropByAka)
void sinex_tro_MakeMeansTrops (double dt_, int StartSec_, SBTropRecordList *TropsOrig, SBTropRecordList *TropsMeans)
SBTS_SINEX & operator<< (SBTS_SINEX &s, SB_TRF &)
SBTS_SINEX & operator<< (SBTS_SINEX &s, SBVLBISession &Session)
SBTS_SINEX & operator>> (SBTS_SINEX &s, SB_TRF &)
void writeNormalEquationSystem (SBTS_SINEX &s, SBParameterList *Ys, SBVector *Zy, SBUpperMatrix *Ry, SBParameterList *Xs, SBVector *Zx, SBUpperMatrix *Rx, SBMatrix *Rxy, const QString &BatchName, const QString &File4Output)
Function Documentation
void collectListOfSINEXParameters (SBParameterList *LastGlb, SBSymMatrix *LastP, SBSINEXParameterList *SINEX_List, SBSymMatrix *&SINEX_P, SBRunManager *RunMgr)
Definition at line 320 of file SbGeoSINEX.C'.
References Vector3::at(), SBSymMatrix::at(), SBProject::cfg(), SBStation::charID4SINEX(), SBStationInfo::ConstrCoo, SBStationInfo::ConstrVel, SBCatalog::epoch(), SBLog::ERR, SBLog::ESTIMATOR, SBStationInfoList::find(), SB_TRF::find(), SBParameterList::idx(), SBAttributed::isAttr(), Log, SBNamed::name(), SBConfig::p(), SBRunManager::prj(), SBStation::r(), SBUpperMatrix::set(), SBSINEXParameter::setAPrioriValue(), SBStation::setCharID(), SBSINEXParameter::setConstraintCode(), SBSINEXParameter::setIdx(), SBSINEXParameter::setPointCode(), SBSINEXParameter::setSiteCode(), SBSINEXParameter::setSolutionID(), SBSINEXParameter::setTValidEpoch(), SBSINEXParameter::setType(), SBSINEXParameter::ST_STAX, SBSINEXParameter::ST_STAY, SBSINEXParameter::ST_STAZ, SBSINEXParameter::ST_VELX, SBSINEXParameter::ST_VELY, SBSINEXParameter::ST_VELZ, SBParametersDesc::staCoo(), SBProject::stationList(), SBParametersDesc::staVel(), SBDerivation::tEpoch(), SBRunManager::trf(), SBParameter::tuneParameter(), SBSINEXParameter::type(), SBStation::vModel(), SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by operator<<().
void collectListOfSINEXParameters4NEQ (SBParameterList *PList, SBSINEXParameterList *SINEX_List, SBRunManager *RunMgr)
Definition at line 463 of file SbGeoSINEX.C'.
References Vector3::at(), SBFrame::calc(), SBStation::calcDisplacement(), SBProject::cfg(), SBStation::charID4SINEX(), SBRunManager::crf(), DAY2SEC, SBSource::dn_t(), SBFrame::eop(), SBCatalog::epoch(), SBLog::ERR, SBLog::ESTIMATOR, SB_CRF::find(), SB_TRF::find(), SBRunManager::frame(), Log, SBNamed::name(), SBConfig::p(), SBSource::p_DN(), SBStation::p_DRX(), SBStation::p_DRY(), SBStation::p_DRZ(), SBEOP::p_Neps(), SBEOP::p_Npsi(), SBEOP::p_Put(), SBEOP::p_Px(), SBEOP::p_Py(), SBSource::p_RA(), SBFrame::polar_UT1_UTC(), SBFrame::polar_X(), SBFrame::polar_Y(), SBParametersDesc::polusNut(), SBParametersDesc::polusUT(), SBParametersDesc::polusXY(), SBEOP::prepare4Date(), SBRunManager::prj(), SBSource::ra_t(), RAD2SEC, SBStation::rt(), SBSINEXParameter::setAPrioriValue(), SBStation::setCharID(), SBSINEXParameter::setConstraintCode(), SBSINEXParameter::setIdx(), SBSINEXParameter::setPointCode(), SBParameter::setSigmaAPriori(), SBSource::setSINEXCharID(), SBSINEXParameter::setSiteCode(), SBSINEXParameter::setSolutionID(), SBSINEXParameter::setTValidEpoch(), SBSINEXParameter::setType(), SBParameter::sigmaAPriori(), SBSource::sinexCharID(), SBParametersDesc::srcCoo(), SBSINEXParameter::ST_NUT_LN, SBSINEXParameter::ST_NUT_OB, SBSINEXParameter::ST_RS_DE, SBSINEXParameter::ST_RS_RA, SBSINEXParameter::ST_STAX, SBSINEXParameter::ST_STAY, SBSINEXParameter::ST_STAZ, SBSINEXParameter::ST_UT, SBSINEXParameter::ST_XPO, SBSINEXParameter::ST_YPO, SBParametersDesc::staCoo(), SBDerivation::tEpoch(), SBFrame::totNutationLongitude(), SBFrame::totNutationObliquity(), SBRunManager::trf(), SBParameter::tuneParameter(), SBSource::updateParameters(), SBParameter::v(), SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by writeNormalEquationSystem().
SBTS_SINEX& operator<< (SBTS_SINEX &s, SB_TRF &)
Definition at line 1721 of file SbGeoSINEX.C'.
References SBProject::cfg(), collectListOfSINEXParameters(), SBRunManager::crf(), SBMJD::currentMJD(), SBFrame::eop(), SBRunManager::frame(), SBEOP::label(), SBSolution::loadGlbCor(), Log, SBConfig::NM_IAU1980, SBConfig::NM_IAU1996, SBConfig::NM_IAU2000, SBConfig::nutModel(), SBRunManager::prj(), SBLog::RUN, SBTS_SINEX::runMgr(), sinex_FileCommentBlock(), sinex_FileReferenceBlock(), sinex_HeaderLine(), sinex_InputAcknowledgementsBlock(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_NutationDataBlock(), sinex_PrecessionDataBlock(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SolutionAprioriBlock(), sinex_SolutionEpochsBlock(), sinex_SolutionEstimateBlock(), sinex_SolutionMatrixEstimateBlock(), sinex_SolutionStatisticsBlock(), sinex_SourceIDBlock(), sinex_TrailerLine(), SNX_SC_STATIONS, SBRunManager::solution(), SBSolution::statGeneral(), SBConfig::STR_Classic, SBConfig::sysTransform(), SBProject::tFinis(), SBSolutionName::toString(), SBRunManager::trf(), SBProject::tStart(), SBRunManager::vlbi(), SBLog::write(), and SBLog::WRN.
SBTS_SINEX& operator<< (SBTS_SINEX &s, SBVLBISession &Session)
Definition at line 1845 of file SbGeoSINEX.C'.
References SBObjectObsInfo::aka(), SBStationInfo::ArtMeteo, SBStationInfo::BadMeteo, SBStation::calcDisplacement(), SBProject::cfg(), SBDelay::CLight, SBRunManager::crf(), SBMJD::currentMJD(), SBLog::DELAYALL, SBParameter::e(), SBLog::ERR, SB_TRF::find(), SBVLBISession::first(), SBAttributed::isAttr(), Log, SBNamed::name(), SBVLBISession::next(), SBDerivation::num(), SBVLBISesInfo::officialName(), SBStation::p_AtmGradE(), SBStation::p_AtmGradN(), SBStation::p_Zenith(), SBRunManager::prj(), SBObsVLBIEntry::processed, SBLog::RUN, SBTS_SINEX::runMgr(), SBTropRecord::setGradEast(), SBTropRecord::setGradEastErr(), SBTropRecord::setGradNorth(), SBTropRecord::setGradNorthErr(), SBTropRecord::setNumPts(), SBTropRecord::setPres(), SBTropRecord::setRH(), SBTropRecord::setTemp(), SBTropRecord::setTotZenith(), SBTropRecord::setWetZenith(), SBTropRecord::setWetZenithErr(), sinex_FileReferenceBlock(), sinex_tro_HeaderLine(), sinex_tro_MakeMeansTrops(), sinex_tro_SiteIDBlock(), sinex_tro_StaCoordinatesBlock(), sinex_tro_TrailerLine(), sinex_tro_TropDescriptionBlock(), sinex_tro_TropSolutionBlock(), SBLog::SOURCE, SBLog::STATION, SBVLBISession::stationList(), SBVLBISesInfo::tMean(), SBStationID::toString(), SBRunManager::trf(), SBConfig::tropSamplInterval(), SBConfig::tropStartSec(), SBSource::updateParameters(), SBParameter::v(), SBVLBISesInfo::version(), SBLog::write(), and SBStationInfo::zw().
SBTS_SINEX& operator>> (SBTS_SINEX &s, SB_TRF &)
Definition at line 2057 of file SbGeoSINEX.C'.
void sinex_Comments (QTextStream &s, const QString &Comments)
Definition at line 665 of file SbGeoSINEX.C'.
Referenced by sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SolutionAprioriBlock(), sinex_SolutionEpochsBlock(), sinex_SolutionEstimateBlock(), sinex_SolutionMatrixEstimateBlock(), sinex_SolutionNormalEquationMatrixBlock(), sinex_SolutionNormalEquationVectorBlock(), sinex_SolutionStatisticsBlock(), sinex_SourceIDBlock(), sinex_tro_SiteIDBlock(), sinex_tro_StaCoordinatesBlock(), sinex_tro_TropDescriptionBlock(), sinex_tro_TropSolutionStation(), and writeNormalEquationSystem().
void sinex_FileCommentBlock (QTextStream &s, const QString &Comment)
Definition at line 739 of file SbGeoSINEX.C'.
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_FileReferenceBlock (QTextStream &s, const QString &DescriptionItem, const QString &OutputItem, const QString &InputItem)
Definition at line 704 of file SbGeoSINEX.C'.
References SBCompilerDomainName, SBCompilerHostName, SBCompilerLoginName, SBCompilerOS, SBCompilerUserName, SBVersion::selfName(), SBVersion::toString(), and Version.
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_HeaderLine (QTextStream &s, doubleSINEX_VER, const SBMJD &CreationTime, const SBMJD &TStart, const SBMJD &TFinis, intNumberOfPars, unsigned intSContents, boolIsNEQ)
Definition at line 670 of file SbGeoSINEX.C'.
References SBMJD::F_SINEX, SNX_SC_EOP, SNX_SC_ORBITS, SNX_SC_SOURCES, SNX_SC_STATIONS, SNX_SC_TROPOSPHERE, and SBMJD::toString().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_InputAcknowledgementsBlock (QTextStream &s)
Definition at line 795 of file SbGeoSINEX.C'.
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_InputFilesBlock (QTextStream &s, const SBMJD &CreationTime, const QString &FileName, const QString &FileDescr)
Definition at line 779 of file SbGeoSINEX.C'.
References SBMJD::F_SINEX, sinex_Comments(), and SBMJD::toString().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_InputHistoryBlock (QTextStream &s, doubleSINEX_VER, const SBMJD &CreationTime, const SBMJD &TStart, const SBMJD &TFinis, intNumberOfPars, unsigned intSContents, boolIsNEQ)
Definition at line 747 of file SbGeoSINEX.C'.
References SBMJD::F_SINEX, sinex_Comments(), SNX_SC_EOP, SNX_SC_ORBITS, SNX_SC_SOURCES, SNX_SC_STATIONS, SNX_SC_TROPOSPHERE, and SBMJD::toString().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_NutationDataBlock (QTextStream &s, const QString &NutCode, const QString &NutDescr)
Definition at line 808 of file SbGeoSINEX.C'.
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_PrecessionDataBlock (QTextStream &s, const QString &PrecCode, const QString &PrecDescr)
Definition at line 819 of file SbGeoSINEX.C'.
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_SiteEccentricityBlock (QTextStream &s, SB_TRF *TRF, SBProject *Prj, SBVLBISet *VLBI, SBParameterList *List)
Definition at line 931 of file SbGeoSINEX.C'.
References Vector3::at(), SBEccentricity::ecc(), SB_TRF::ecc(), SBEcc::eccByID(), SBStationEcc::eccs(), SBEccentricity::ET_XYZ, SBMJD::F_SINEX, SBStationInfoList::find(), SBParameterList::find(), SBAttributed::isAttr(), SBVLBISet::loadSession(), SBStationInfo::notValid, SBStationEcc::setID(), sinex_Comments(), SBVLBISession::stationList(), SB_TRF::stations(), SBProject::tFinis(), SBEccentricity::tFinis(), SBMJD::toString(), SBProject::tStart(), SBEccentricity::tStart(), SBEccentricity::type(), TZero, SBProject::VLBIsessionList(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_SiteIDBlock (QTextStream &s, SB_TRF *TRF, SBProject *Prj, SBParameterList *List)
Definition at line 879 of file SbGeoSINEX.C'.
References SBLog::ERR, SBStationInfo::EstCoo, SBStationInfoList::find(), SBParameterList::find(), SBAttributed::isAttr(), Log, SBStationInfo::notValid, rad2dms(), rad2dmsl(), SBLog::RUN, sinex_Comments(), SBProject::stationList(), SB_TRF::stations(), and SBLog::write().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_SolutionAprioriBlock (QTextStream &s, SBSINEXParameterList *SINEX_List)
Definition at line 1172 of file SbGeoSINEX.C'.
References SBMJD::F_SINEX, and sinex_Comments().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_SolutionEpochsBlock (QTextStream &s, SB_TRF *TRF, SBParameterList *List)
Definition at line 1062 of file SbGeoSINEX.C'.
References SBLog::ERR, SBMJD::F_SINEX, SBParameterList::find(), Log, SBDerivation::num(), SBLog::RUN, sinex_Comments(), SB_TRF::stations(), SBDerivation::tEpoch(), SBDerivation::tFinis(), SBMJD::toString(), SBDerivation::tStart(), TZero, and SBLog::write().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_SolutionEstimateBlock (QTextStream &s, SBSINEXParameterList *SINEX_List)
Definition at line 1146 of file SbGeoSINEX.C'.
References SBMJD::F_SINEX, and sinex_Comments().
Referenced by operator<<().
void sinex_SolutionMatrixEstimateBlock (QTextStream &s, boolIsEstimate, SBSymMatrix *P)
Definition at line 1198 of file SbGeoSINEX.C'.
References SBSymMatrix::at(), SBMatrix::nCol(), and sinex_Comments().
Referenced by operator<<().
void sinex_SolutionNormalEquationMatrixBlock (QTextStream &s, SBSymMatrix *N)
Definition at line 1236 of file SbGeoSINEX.C'.
References SBSymMatrix::at(), SBMatrix::nCol(), and sinex_Comments().
Referenced by writeNormalEquationSystem().
void sinex_SolutionNormalEquationVectorBlock (QTextStream &s, SBSINEXParameterList *SINEX_List, SBVector *B)
Definition at line 1274 of file SbGeoSINEX.C'.
References SBVector::at(), SBMJD::F_SINEX, and sinex_Comments().
Referenced by writeNormalEquationSystem().
void sinex_SolutionStatisticsBlock (QTextStream &s, SBStatistics *Statistics)
Definition at line 1113 of file SbGeoSINEX.C'.
References SBStatistics::dof(), SBStatistics::numberOfObservations(), SBStatistics::numPars(), sinex_Comments(), SBStatistics::varFactor(), SBStatistics::wpfr(), and SBStatistics::wrms().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_SourceIDBlock (QTextStream &s, SB_CRF *CRF, SBProject *Prj, SBParameterList *List, SBSINEXParameterList *SINEX_List)
Definition at line 830 of file SbGeoSINEX.C'.
References SBSourceInfo::ConstrCoo, SBLog::ERR, SBSourceInfo::EstCoo, SBSourceInfoList::find(), SBParameterList::find(), SB_CRF::first(), SBAttributed::isAttr(), Log, SB_CRF::next(), SBSourceInfo::notValid, SBLog::RUN, sinex_Comments(), SBSINEXParameter::siteCode(), SBProject::sourceList(), and SBLog::write().
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_TrailerLine (QTextStream &s)
Definition at line 698 of file SbGeoSINEX.C'.
Referenced by operator<<(), and writeNormalEquationSystem().
void sinex_tro_HeaderLine (QTextStream &s, doubleSINEX_TRO_VER, const SBMJD &CreationTime, const SBMJD &TStart, const SBMJD &TFinis)
Definition at line 1302 of file SbGeoSINEX.C'.
References SBMJD::F_SINEX, and SBMJD::toString().
Referenced by operator<<().
void sinex_tro_MakeMeansTrops (doubledt_, intStartSec_, SBTropRecordList *TropsOrig, SBTropRecordList *TropsMeans)
Definition at line 1669 of file SbGeoSINEX.C'.
References SBTropRecord::collect(), and DAY2SEC.
Referenced by operator<<().
void sinex_tro_SiteIDBlock (QTextStream &s, SB_TRF *TRF, SBStationInfoList *Stations)
Definition at line 1322 of file SbGeoSINEX.C'.
References SBStation::charID4SINEX(), SBStation::description(), SBLog::ERR, SB_TRF::find(), SBStation::height(), SBStation::id(), SBStation::latitude(), Log, SBStation::longitude(), rad2dms(), rad2dmsl(), sinex_Comments(), SBLog::STATION, SBStationID::toString(), and SBLog::write().
Referenced by operator<<().
void sinex_tro_StaCoordinatesBlock (QTextStream &s, SB_TRF *TRF, SBStationInfoList *Stations, SBRunManager *RunMgr, const SBMJD &T)
Definition at line 1366 of file SbGeoSINEX.C'.
References Vector3::at(), SBStation::charID4SINEX(), SBLog::ERR, SB_TRF::find(), Log, SBStation::p_DRX(), SBStation::p_DRY(), SBStation::p_DRZ(), SBStation::r(), sinex_Comments(), SBLog::STATION, SBStation::updateParameters(), SBParameter::v(), v3Zero, SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by operator<<().
void sinex_tro_TrailerLine (QTextStream &s)
Definition at line 1316 of file SbGeoSINEX.C'.
Referenced by operator<<().
void sinex_tro_TropDescriptionBlock (QTextStream &s, SBRunManager *RunMgr, SBVLBISession &Session)
Definition at line 1409 of file SbGeoSINEX.C'.
References SBStationInfo::ArtMeteo, SBParametersDesc::atmGrad(), SBStationInfo::BadMeteo, SBProject::cfg(), SBConfig::isRollBack2NMF(), SBConfig::p(), SBRunManager::prj(), SBParameterCfg::PT_ARC, SBParameterCfg::PT_STH, SBConfig::RDM_CfA2p2, SBConfig::RDM_Chao, SBConfig::RDM_Ifadis, SBConfig::RDM_MTT, SBConfig::RDM_NMFH2, SBConfig::RDM_NMFW2, SBConfig::RDM_NONE, SBConfig::RDZ_Hopfield, SBConfig::RDZ_NONE, SBConfig::RDZ_Saastamoinen, SBConfig::refrDryMapping(), SBConfig::refrDryZenith(), SBConfig::refrWetMapping(), SBConfig::refrWetZenith(), SBConfig::RWM_Chao, SBConfig::RWM_Ifadis, SBConfig::RWM_MTT, SBConfig::RWM_NONE, SBConfig::RWZ_Hopfield, SBConfig::RWZ_NONE, SBConfig::RWZ_Saastamoinen, SBParameterCfg::scaleName(), sinex_Comments(), SBParameterCfg::ST_MARKOVPROCESS, SBParameterCfg::ST_RANDWALK, SBParameterCfg::ST_UNKN, SBParameterCfg::ST_WHITENOISE, SBVLBISession::stationList(), SBParameterCfg::stochasticType(), SBConfig::tropSamplInterval(), SBParameterCfg::type(), SBParameterCfg::whiteNoise(), and SBParametersDesc::zenith().
Referenced by operator<<().
void sinex_tro_TropSolutionBlock (QTextStream &s, SBRunManager *RunMgr, SBVLBISession &Session, QDict< SBTropRecordList > *TropByAka)
Definition at line 1642 of file SbGeoSINEX.C'.
References SBLog::ERR, SB_TRF::find(), Log, sinex_tro_TropSolutionStation(), SBLog::STATION, SBVLBISession::stationList(), SBRunManager::trf(), and SBLog::write().
Referenced by operator<<().
void sinex_tro_TropSolutionStation (QTextStream &s, SBRunManager *, SBVLBISession &, SBStationInfo *SI, SBStation *Station, SBTropRecordList *Trops)
Definition at line 1593 of file SbGeoSINEX.C'.
References SBObjectObsInfo::aka(), SBStation::charID4SINEX(), SBMJD::F_SINEX, and sinex_Comments().
Referenced by sinex_tro_TropSolutionBlock().
void writeNormalEquationSystem (SBTS_SINEX &s, SBParameterList *Ys, SBVector *Zy, SBUpperMatrix *Ry, SBParameterList *Xs, SBVector *Zx, SBUpperMatrix *Rx, SBMatrix *Rxy, const QString &BatchName, const QString &File4Output)
Definition at line 2066 of file SbGeoSINEX.C'.
References SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBProject::cfg(), SBVector::clear(), SBParameterList::clear(), collectListOfSINEXParameters4NEQ(), SBRunManager::crf(), SBMJD::currentMJD(), DAY2SEC, SBLog::DBG, SBFrame::eop(), SBLog::ERR, SBLog::ESTIMATOR, SBParameterList::find(), SBRunManager::frame(), SBParameterList::idx(), SBLog::INF, SBLog::IO, SBEOP::label(), Log, SBNamed::name(), SBConfig::NM_IAU1980, SBConfig::NM_IAU1996, SBConfig::NM_IAU2000, SBConfig::nutModel(), SBRunManager::prj(), RAD2MAS, SBConfig::reportNormalEqsEOPs(), SBConfig::reportNormalEqsSRCs(), SBConfig::reportNormalEqsSTCs(), RTR(), SBLog::RUN, SBTS_SINEX::runMgr(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), sinex_Comments(), sinex_FileCommentBlock(), sinex_FileReferenceBlock(), sinex_HeaderLine(), sinex_InputAcknowledgementsBlock(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_NutationDataBlock(), sinex_PrecessionDataBlock(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SolutionAprioriBlock(), sinex_SolutionEpochsBlock(), sinex_SolutionNormalEquationMatrixBlock(), sinex_SolutionNormalEquationVectorBlock(), sinex_SolutionStatisticsBlock(), sinex_SourceIDBlock(), sinex_TrailerLine(), SNX_SC_EOP, SNX_SC_SOURCES, SNX_SC_STATIONS, SBRunManager::solution(), SBSolution::stat4CurrentBatch(), SBConfig::STR_Classic, SBConfig::sysTransform(), SBSolutionName::toString(), SBRunManager::trf(), TZero, SBRunManager::vlbi(), and SBLog::write().
Referenced by SBRunManager::makeReportNormalEqs().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.