SbGeoStations.C
NAME
SbGeoStations.C -
SYNOPSIS
#include 'SbGeoStations.H'
#include 'SbGeoSources.H'
#include <qmessagebox.h>
#include <qfile.h>
#include <qregexp.h>
#include 'SbSetup.H'
#include 'SbGeoAtmLoad.H'
#include 'SbGeoParameter.H'
#include 'SbGeoProject.H'
Functions
QDataStream & operator<< (QDataStream &s, const SBOLoad &Ol)
QDataStream & operator>> (QDataStream &s, SBOLoad &Ol)
QDataStream & operator<< (QDataStream &s, const SBStation &S)
QDataStream & operator>> (QDataStream &s, SBStation &S)
SBTS_dir1994 & operator<< (SBTS_dir1994 &s, const SBStation &S)
SBTS_dir1994 & operator>> (SBTS_dir1994 &s, SBStation &S)
SBTS_dir2000 & operator<< (SBTS_dir2000 &s, const SBStation &S)
SBTS_dir2000 & operator>> (SBTS_dir2000 &s, SBStation &S)
SBTS_ssc1994 & operator<< (SBTS_ssc1994 &s, const SBStation &S)
SBTS_ssc2000 & operator<< (SBTS_ssc2000 &s, const SBStation &S)
SBTS_blqReq & operator<< (SBTS_blqReq &s, const SBStation &S)
QDataStream & operator<< (QDataStream &s, const SBSite &S)
QDataStream & operator>> (QDataStream &s, SBSite &S)
SBTS_site1994 & operator<< (SBTS_site1994 &s, const SBSite &S)
SBTS_site1994 & operator>> (SBTS_site1994 &s, SBSite &S)
SBTS_site2000 & operator<< (SBTS_site2000 &s, const SBSite &S)
SBTS_site2000 & operator>> (SBTS_site2000 &s, SBSite &S)
SBTS_dir1994 & operator<< (SBTS_dir1994 &s, const SBSite &S)
SBTS_dir1994 & operator>> (SBTS_dir1994 &s, SBSite &S)
SBTS_dir2000 & operator<< (SBTS_dir2000 &s, const SBSite &S)
SBTS_dir2000 & operator>> (SBTS_dir2000 &s, SBSite &S)
SBTS_ssc1994 & operator<< (SBTS_ssc1994 &s, const SBSite &S)
SBTS_ssc2000 & operator<< (SBTS_ssc2000 &s, const SBSite &S)
SBTS_blqReq & operator<< (SBTS_blqReq &s, const SBSite &S)
QTextStream & operator>> (QTextStream &s, SBEccentricity &)
QDataStream & operator<< (QDataStream &s, const SB_TRF &TRF)
QDataStream & operator>> (QDataStream &s, SB_TRF &TRF)
QTextStream & operator<< (QTextStream &s, const SB_TRF &)
QTextStream & operator>> (QTextStream &s, SB_TRF &)
SBTS_site1994 & operator<< (SBTS_site1994 &s, const SB_TRF &TRF)
SBTS_site1994 & operator>> (SBTS_site1994 &s, SB_TRF &TRF)
SBTS_site2000 & operator<< (SBTS_site2000 &s, const SB_TRF &TRF)
SBTS_site2000 & operator>> (SBTS_site2000 &s, SB_TRF &TRF)
SBTS_dir1994 & operator<< (SBTS_dir1994 &s, const SB_TRF &TRF)
SBTS_dir1994 & operator>> (SBTS_dir1994 &s, SB_TRF &TRF)
SBTS_dir2000 & operator<< (SBTS_dir2000 &s, const SB_TRF &TRF)
SBTS_dir2000 & operator>> (SBTS_dir2000 &s, SB_TRF &TRF)
SBTS_ssc1994 & operator<< (SBTS_ssc1994 &s, const SB_TRF &TRF)
SBTS_ssc2000 & operator<< (SBTS_ssc2000 &s, const SB_TRF &TRF)
SBTS_blqReq & operator<< (SBTS_blqReq &s, const SB_TRF &TRF)
SBTS_ssc1994 & operator>> (SBTS_ssc1994 &s, SB_TRF &TRF)
SBTS_ssc2000 & operator>> (SBTS_ssc2000 &s, SB_TRF &TRF)
SBTS_blq & operator<< (SBTS_blq &s, const SB_TRF &TRF)
SBTS_blq & operator>> (SBTS_blq &s, SBOLoadCarrier &OLC)
SBTS_blq & operator<< (SBTS_blq &s, const SBOLoadCarrier &OLC)
SBTS_blq & operator>> (SBTS_blq &s, SBOLoadList &OLL)
Variables
const SBStationID SidZero (0, SBStation::Pt_Antenna, 0)
Function Documentation
QDataStream& operator<< (QDataStream &s, const SBOLoad &Ol)
Definition at line 164 of file SbGeoStations.C'.
References SBOLoad::Amplitude, SBOLoad::CommentLine1, SBOLoad::CommentLine2, SBOLoad::Dist, SBOLoad::Info, SBOLoad::Phase, and SBOLoad::PickedUp.
QDataStream& operator<< (QDataStream &s, const SBStation &S)
Definition at line 1393 of file SbGeoStations.C'.
References SBStation::AxisOffset, SBStation::CDPNum, SBStation::CharID, SBStation::ClassCoord, SBStation::Comments, SBStation::Description, SBStation::DomeMinor, SBStation::dV, SBStation::hasOwnOLoad, SBAttributed::isAttr(), SBStation::MountType, SBStation::OLoad, SBStation::PointType, SBStation::RefPt, SBStation::Tech, and SBStation::V.
SBTS_dir1994& operator<< (SBTS_dir1994 &s, const SBStation &S)
Definition at line 1425 of file SbGeoStations.C'.
References SBStation::CDP(), SBStation::charID(), SBStation::classCoord(), SBStation::description(), SBStation::domeMinor(), and SBStation::pointType().
SBTS_dir2000& operator<< (SBTS_dir2000 &s, const SBStation &S)
Definition at line 1487 of file SbGeoStations.C'.
References SBStation::CDP(), SBStation::charID(), SBStation::description(), SBStation::domeMinor(), and SBStation::pointType().
SBTS_ssc1994& operator<< (SBTS_ssc1994 &s, const SBStation &S)
Definition at line 1568 of file SbGeoStations.C'.
References Vector3::at(), SBStation::CDP(), SBStation::charID(), SBStation::dR_first(), SBStation::dV, SBStation::id(), SBNamed::name(), SBStation::tech(), SBStationID::toString(), X_AXIS, Y_AXIS, and Z_AXIS.
SBTS_ssc2000& operator<< (SBTS_ssc2000 &s, const SBStation &S)
Definition at line 1593 of file SbGeoStations.C'.
References Vector3::at(), SBStation::CDP(), SBStation::charID(), SBCoordinates::coo(), SBCoordinates::cooErrors(), SBStation::dV, SBMJD::F_SINEX_S, SBStation::id(), SBAttributed::isAttr(), SBNamed::name(), SBCoordinates::notValid, SBStation::RefPt, SBStation::tech(), SBMJD::toString(), SBStationID::toString(), X_AXIS, Y_AXIS, and Z_AXIS.
SBTS_blqReq& operator<< (SBTS_blqReq &s, const SBStation &S)
Definition at line 1651 of file SbGeoStations.C'.
References Vector3::at(), SBStation::id(), SBNamed::name(), SBStation::r_first(), SBStationID::toString(), v3Zero, X_AXIS, Y_AXIS, and Z_AXIS.
QDataStream& operator<< (QDataStream &s, const SBSite &S)
Definition at line 1988 of file SbGeoStations.C'.
References SBSite::Country, SBSite::DomeMajor, SBSite::dV, SBSite::OLoad, SBSite::Plate, SBSite::Stations, and SBSite::V.
SBTS_site1994& operator<< (SBTS_site1994 &s, const SBSite &S)
Definition at line 2003 of file SbGeoStations.C'.
References SBSite::country(), SBSite::domeMajor(), SBSite::latitude(), SBSite::longitude(), SBNamed::name(), SBSite::plate(), rad2dms(), and rad2dmsl().
SBTS_site2000& operator<< (SBTS_site2000 &s, const SBSite &S)
Definition at line 2055 of file SbGeoStations.C'.
References SBSite::country(), SBSite::domeMajor(), SBSite::latitude(), SBSite::longitude(), SBNamed::name(), SBSite::plate(), rad2dms(), and rad2dmsl().
SBTS_dir1994& operator<< (SBTS_dir1994 &s, const SBSite &S)
Definition at line 2109 of file SbGeoStations.C'.
References SBSite::domeMajor(), SBNamed::name(), and SBSite::Stations.
SBTS_dir2000& operator<< (SBTS_dir2000 &s, const SBSite &S)
Definition at line 2183 of file SbGeoStations.C'.
References SBSite::domeMajor(), SBNamed::name(), and SBSite::Stations.
SBTS_ssc1994& operator<< (SBTS_ssc1994 &s, const SBSite &S)
Definition at line 2271 of file SbGeoStations.C'.
References SBTS_ssc1994::ClassCoord, and SBSite::Stations.
SBTS_ssc2000& operator<< (SBTS_ssc2000 &s, const SBSite &S)
Definition at line 2279 of file SbGeoStations.C'.
References SBSite::Stations.
SBTS_blqReq& operator<< (SBTS_blqReq &s, const SBSite &S)
Definition at line 2287 of file SbGeoStations.C'.
References SBSite::Stations.
QDataStream& operator<< (QDataStream &s, const SB_TRF &TRF)
Definition at line 2934 of file SbGeoStations.C'.
References SB_TRF::ECCs.
QTextStream& operator<< (QTextStream &s, const SB_TRF &)
Definition at line 2947 of file SbGeoStations.C'.
SBTS_site1994& operator<< (SBTS_site1994 &s, const SB_TRF &TRF)
Definition at line 2957 of file SbGeoStations.C'.
SBTS_site2000& operator<< (SBTS_site2000 &s, const SB_TRF &TRF)
Definition at line 3002 of file SbGeoStations.C'.
SBTS_dir1994& operator<< (SBTS_dir1994 &s, const SB_TRF &TRF)
Definition at line 3048 of file SbGeoStations.C'.
SBTS_dir2000& operator<< (SBTS_dir2000 &s, const SB_TRF &TRF)
Definition at line 3118 of file SbGeoStations.C'.
SBTS_ssc1994& operator<< (SBTS_ssc1994 &s, const SB_TRF &TRF)
Definition at line 3187 of file SbGeoStations.C'.
References SBTS_ssc1994::ClassCoord, SBCatalog::epoch(), SBMJD::F_Year, SBCatalog::label(), and SBMJD::toString().
SBTS_ssc2000& operator<< (SBTS_ssc2000 &s, const SB_TRF &TRF)
Definition at line 3208 of file SbGeoStations.C'.
References SBCatalog::epoch(), SBMJD::F_Year, and SBMJD::toString().
SBTS_blqReq& operator<< (SBTS_blqReq &s, const SB_TRF &TRF)
Definition at line 3226 of file SbGeoStations.C'.
SBTS_blq& operator<< (SBTS_blq &s, const SB_TRF &TRF)
Definition at line 3783 of file SbGeoStations.C'.
References SBStation::hasOwnOLoad, and SBOLoad::P_Domes.
SBTS_blq& operator<< (SBTS_blq &s, const SBOLoadCarrier &OLC)
Definition at line 4117 of file SbGeoStations.C'.
References SBOLoad::Amplitude, SBOLoadCarrier::CDPNum, SBOLoad::commentLine1(), SBOLoad::commentLine2(), SBStationID::domeMajor(), SBOLoadCarrier::Id, SBOLoadCarrier::Latitude, SBOLoadCarrier::Longitude, SBNamed::Name, SBOLoadCarrier::OLoad, SBOLoad::Phase, RAD2DEG, and SBStationID::toString().
QDataStream& operator>> (QDataStream &s, SBOLoad &Ol)
Definition at line 171 of file SbGeoStations.C'.
References SBOLoad::Amplitude, SBOLoad::CommentLine1, SBOLoad::CommentLine2, SBOLoad::Dist, SBOLoad::Info, SBOLoad::Phase, and SBOLoad::PickedUp.
QDataStream& operator>> (QDataStream &s, SBStation &S)
Definition at line 1403 of file SbGeoStations.C'.
References SBStation::AxisOffset, SBStation::calcRLF(), SBStation::CDPNum, SBStation::CharID, SBStation::ClassCoord, SBStation::Comments, SBStation::Description, SBStation::DomeMinor, SBStation::dV, EAST, SBStation::FmVEN, SBStation::hasOwnOLoad, SBStation::Height, SBAttributed::isAttr(), SBStation::Latitude, SBStation::Longitude, SBStation::MountType, NORT, SBStation::OLoad, SBStation::PointType, SBReferencePoint::r(), SBStation::RefPt, SBStation::Rt, SBStation::Tech, TZero, SBStation::V, and v3Zero.
SBTS_dir1994& operator>> (SBTS_dir1994 &s, SBStation &S)
Definition at line 1441 of file SbGeoStations.C'.
References SBLog::DBG, SBStation::DomeMinor, SBLog::INF, Log, SBStation::Pt_Antenna, SBStation::Pt_Marker, SBStation::setCDP(), SBStation::setCharID(), SBStation::setDescription(), SBStation::setDomeMinor(), SBStation::setPointType(), SBLog::STATION, and SBLog::write().
SBTS_dir2000& operator>> (SBTS_dir2000 &s, SBStation &S)
Definition at line 1502 of file SbGeoStations.C'.
References SBLog::DBG, SBStation::DomeMinor, SBLog::INF, Log, SBStation::Pt_Antenna, SBStation::Pt_Marker, SBStation::setCDP(), SBStation::setCharID(), SBStation::setDescription(), SBStation::setDomeMinor(), SBStation::setPointType(), SBLog::STATION, and SBLog::write().
QDataStream& operator>> (QDataStream &s, SBSite &S)
Definition at line 1994 of file SbGeoStations.C'.
References SBSite::calcRLF(), SBSite::Country, SBSite::DomeMajor, SBSite::dV, SBSite::OLoad, SBSite::Plate, SBSite::prepareDicts(), SBSite::Stations, and SBSite::V.
SBTS_site1994& operator>> (SBTS_site1994 &s, SBSite &S)
Definition at line 2019 of file SbGeoStations.C'.
References SBLog::DBG, SBSite::DomeMajor, Log, SBSite::setCountry(), SBSite::setDomeMajor(), SBNamed::setName(), SBSite::setPlate(), SBLog::STATION, and SBLog::write().
SBTS_site2000& operator>> (SBTS_site2000 &s, SBSite &S)
Definition at line 2071 of file SbGeoStations.C'.
References SBLog::DBG, SBSite::DomeMajor, Log, SBSite::setCountry(), SBSite::setDomeMajor(), SBNamed::setName(), SBSite::setPlate(), SBLog::STATION, and SBLog::write().
SBTS_dir1994& operator>> (SBTS_dir1994 &s, SBSite &S)
Definition at line 2119 of file SbGeoStations.C'.
References SBSite::addStation(), SBStationList::at(), SBStation::CDP(), SBLog::DBG, SBStation::description(), SBSite::DomeMajor, SBStation::domeMinor(), Log, SBNamed::name(), SBStation::pointType(), SBStation::Pt_Antenna, SBSite::setDomeMajor(), SBNamed::setName(), SBLog::STATION, SBSite::Stations, and SBLog::write().
SBTS_dir2000& operator>> (SBTS_dir2000 &s, SBSite &S)
Definition at line 2193 of file SbGeoStations.C'.
References SBSite::addStation(), SBStationList::at(), SBLog::DBG, SBStation::description(), SBSite::DomeMajor, SBStation::domeMinor(), Log, SBNamed::name(), SBStation::pointType(), SBStation::Pt_Antenna, SBStation::setDescription(), SBSite::setDomeMajor(), SBNamed::setName(), SBLog::STATION, SBSite::Stations, and SBLog::write().
QTextStream& operator>> (QTextStream &s, SBEccentricity &)
Definition at line 2362 of file SbGeoStations.C'.
QDataStream& operator>> (QDataStream &s, SB_TRF &TRF)
Definition at line 2940 of file SbGeoStations.C'.
References SB_TRF::ECCs, and SB_TRF::prepareDicts().
QTextStream& operator>> (QTextStream &s, SB_TRF &)
Definition at line 2952 of file SbGeoStations.C'.
SBTS_site1994& operator>> (SBTS_site1994 &s, SB_TRF &TRF)
Definition at line 2970 of file SbGeoStations.C'.
References SBLog::DBG, SB_TRF::inSort(), Log, SB_TRF::setSiteName(), SBLog::STATION, and SBLog::write().
SBTS_site2000& operator>> (SBTS_site2000 &s, SB_TRF &TRF)
Definition at line 3016 of file SbGeoStations.C'.
References SBLog::DBG, SB_TRF::inSort(), Log, SB_TRF::setSiteName(), SBLog::STATION, and SBLog::write().
SBTS_dir1994& operator>> (SBTS_dir1994 &s, SB_TRF &TRF)
Definition at line 3066 of file SbGeoStations.C'.
References SBSite::addStation(), SBStationList::at(), SBStation::CDP(), SBLog::DBG, SBStation::description(), SB_TRF::inSort(), Log, SBNamed::name(), SBStation::setCDP(), SBStation::setDescription(), SBNamed::setName(), SB_TRF::setSiteName(), SBLog::STATION, SBSite::Stations, and SBLog::write().
SBTS_dir2000& operator>> (SBTS_dir2000 &s, SB_TRF &TRF)
Definition at line 3131 of file SbGeoStations.C'.
References SBSite::addStation(), SBStationList::at(), SBStation::CDP(), SBLog::DBG, SBStation::description(), SB_TRF::inSort(), Log, SBNamed::name(), SBStation::setCDP(), SBStation::setDescription(), SBNamed::setName(), SB_TRF::setSiteName(), SBLog::STATION, SBSite::Stations, and SBLog::write().
SBTS_ssc1994& operator>> (SBTS_ssc1994 &s, SB_TRF &TRF)
Definition at line 3237 of file SbGeoStations.C'.
References SBAttributed::addAttr(), SBSite::addStation(), SBStation::CDP(), SBStation::Class_A, SBStation::Class_B, SBStation::Class_C, SBStation::Class_D, SBStation::Class_E, SBStation::Class_Z, SBLog::DBG, SBStationID::domeMajor(), SBStationID::domeMinor(), SBCatalog::epoch(), SBLog::ERR, SBMJD::F_Short, SBMJD::F_Year, SBLog::INF, SB_TRF::inSort(), SBStationID::isValidStr(), Log, SBStation::OrigImported, SBStationID::ptType(), SBStation::setCDP(), SBStation::setCharID(), SBStation::setClassCoord(), SBStation::setComments(), SBStation::setCoords(), SBStation::setDomeMinor(), SBCatalog::setEpoch(), SBStationID::setID(), SBNamed::setName(), SBStation::setPointType(), SBStation::setTech(), SBStation::setV(), SBStation::setV_err(), SBLog::STATION, TECH_DORIS, TECH_GPS, TECH_LLR, TECH_SLR, TECH_TIE, TECH_UNKN, TECH_VLBI, SBMJD::toString(), SBStationID::toString(), TZero, v3Unit, v3Zero, SBStation::VelocImported, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS.
SBTS_ssc2000& operator>> (SBTS_ssc2000 &s, SB_TRF &TRF)
Definition at line 3498 of file SbGeoStations.C'.
References SBAttributed::addAttr(), SBSite::addStation(), SBStation::CDP(), SBStation::Class_A, SBLog::DBG, SBStationID::domeMajor(), SBStationID::domeMinor(), SBCatalog::epoch(), SBLog::ERR, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_Year, SBLog::INF, SB_TRF::inSort(), SBMJD::isGood(), SBStationID::isValidStr(), Log, SBNamed::name(), SBStation::OrigImported, SBStationID::ptType(), SBStation::setCDP(), SBStation::setCharID(), SBStation::setClassCoord(), SBStation::setComments(), SBStation::setCoords(), SBStation::setDomeMinor(), SBCatalog::setEpoch(), SBStationID::setID(), SBMJD::setMJD(), SBNamed::setName(), SBStation::setPointType(), SBStation::setTech(), SBStation::setV(), SBStation::setV_err(), SBLog::STATION, TECH_DORIS, TECH_GPS, TECH_LLR, TECH_SLR, TECH_TIE, TECH_UNKN, TECH_VLBI, SBMJD::toString(), SBStationID::toString(), TZero, v3Unit, v3Zero, SBStation::VelocImported, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS.
SBTS_blq& operator>> (SBTS_blq &s, SBOLoadCarrier &OLC)
Definition at line 3920 of file SbGeoStations.C'.
References SBOLoad::Amplitude, SBOLoadCarrier::CDPNum, SBOLoadCarrier::CharID, DEG2RAD, SBOLoadCarrier::Id, SBOLoadCarrier::isSuccessfulLoad, SBStationID::isValidStr(), SBOLoadCarrier::Latitude, Log, SBOLoadCarrier::Longitude, SBNamed::Name, SBOLoadCarrier::OLoad, SBOLoad::Phase, SBOLoad::setCommentLine1(), SBOLoad::setCommentLine2(), SBStationID::setDomeMajor(), SBStationID::setID(), SBLog::STATION, SBLog::write(), and SBLog::WRN.
SBTS_blq& operator>> (SBTS_blq &s, SBOLoadList &OLL)
Definition at line 4159 of file SbGeoStations.C'.
References SBLog::DBG, Log, SBLog::STATION, and SBLog::write().
Variable Documentation
const SBStationID SidZero(0, SBStation::Pt_Antenna, 0)
Referenced by SBAploSiteAmplList::read().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.