SbGeoSINEX.H
NAME
SbGeoSINEX.H -
SYNOPSIS
#include <config.h>
#include 'SbGeo.H'
#include 'SbGeoParameter.H'
#include <qdatastream.h>
#include <qintdict.h>
#include <qlist.h>
#include <qstring.h>
Classes
class SBSINEXParameter
class SBSINEXParameterList
class SBTropRecord
class SBTropRecordList
Enumerations
enum SINEX_SolutionContents { SNX_SC_STATIONS = 1<< 0, SNX_SC_ORBITS = 1<< 1, SNX_SC_EOP = 1<< 2, SNX_SC_TROPOSPHERE = 1<< 3, SNX_SC_SOURCES = 1<< 4 }
Functions
void writeNormalEquationSystem (SBTS_SINEX &, SBParameterList *, SBVector *, SBUpperMatrix *, SBParameterList *, SBVector *, SBUpperMatrix *, SBMatrix *, const QString &, const QString &)
Enumeration Type Documentation
enum SINEX_SolutionContents
Enumerator:
SNX_SC_STATIONS
SNX_SC_ORBITS
SNX_SC_EOP
SNX_SC_TROPOSPHERE
SNX_SC_SOURCES
Definition at line 44 of file SbGeoSINEX.H'.
Function Documentation
void writeNormalEquationSystem (SBTS_SINEX &, SBParameterList *, SBVector *, SBUpperMatrix *, SBParameterList *, SBVector *, SBUpperMatrix *, SBMatrix *, const QString &, const QString &)
Definition at line 2066 of file SbGeoSINEX.C'.
References SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBProject::cfg(), SBVector::clear(), SBParameterList::clear(), collectListOfSINEXParameters4NEQ(), SBRunManager::crf(), SBMJD::currentMJD(), DAY2SEC, SBLog::DBG, SBFrame::eop(), SBLog::ERR, SBLog::ESTIMATOR, SBParameterList::find(), SBRunManager::frame(), SBParameterList::idx(), SBLog::INF, SBLog::IO, SBEOP::label(), Log, SBNamed::name(), SBConfig::NM_IAU1980, SBConfig::NM_IAU1996, SBConfig::NM_IAU2000, SBConfig::nutModel(), SBRunManager::prj(), RAD2MAS, SBConfig::reportNormalEqsEOPs(), SBConfig::reportNormalEqsSRCs(), SBConfig::reportNormalEqsSTCs(), RTR(), SBLog::RUN, SBTS_SINEX::runMgr(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), sinex_Comments(), sinex_FileCommentBlock(), sinex_FileReferenceBlock(), sinex_HeaderLine(), sinex_InputAcknowledgementsBlock(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_NutationDataBlock(), sinex_PrecessionDataBlock(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SolutionAprioriBlock(), sinex_SolutionEpochsBlock(), sinex_SolutionNormalEquationMatrixBlock(), sinex_SolutionNormalEquationVectorBlock(), sinex_SolutionStatisticsBlock(), sinex_SourceIDBlock(), sinex_TrailerLine(), SNX_SC_EOP, SNX_SC_SOURCES, SNX_SC_STATIONS, SBRunManager::solution(), SBSolution::stat4CurrentBatch(), SBConfig::STR_Classic, SBConfig::sysTransform(), SBSolutionName::toString(), SBRunManager::trf(), TZero, SBRunManager::vlbi(), and SBLog::write().
Referenced by SBRunManager::makeReportNormalEqs().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.