.TH "SbGeoRefraction.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoRefraction.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include 'SbGeneral\&.H'\fP
.br
\fC#include 'SbGeoRefraction\&.H'\fP
.br
\fC#include 'SbGeoProject\&.H'\fP
.br
\fC#include 'SbGeoStations\&.H'\fP
.br
\fC#include 'SbGeoSources\&.H'\fP
.br
\fC#include 'SbGeoRefFrame\&.H'\fP
.br
\fC#include 'SbSetup\&.H'\fP
.br
\fC#include 'SbMathSpline\&.H'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
