.TH "SbGeoEstimator.H" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoEstimator.H \- 
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br
\fC#include 'SbGeo\&.H'\fP
.br
\fC#include 'SbGeoProject\&.H'\fP
.br
\fC#include 'SbGeoParameter\&.H'\fP
.br
\fC#include <qdatastream\&.h>\fP
.br
\fC#include <qfile\&.h>\fP
.br
\fC#include <qintdict\&.h>\fP
.br
\fC#include <qlist\&.h>\fP
.br
\fC#include <qstack\&.h>\fP
.br
\fC#include <qstring\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSBEstimator\fP"
.br
.ti -1c
.RI "class \fBSBEstimator::Group\fP"
.br
.ti -1c
.RI "class \fBSBEstimator::GroupList\fP"
.br
.ti -1c
.RI "class \fBSBEstimator::SmoothCarrier\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
