.TH "SbGeoAtmLoad.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoAtmLoad.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <qfile\&.h>\fP
.br
\fC#include <qregexp\&.h>\fP
.br
\fC#include 'SbGeoAtmLoad\&.H'\fP
.br
\fC#include 'SbGeoObsVLBI\&.H'\fP
.br
\fC#include 'SbMathSpline\&.H'\fP
.br
\fC#include 'SbSetup\&.H'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator<<\fP (\fBQTextStream\fP &s, const \fBSBAploChunk\fP &)"
.br
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator>>\fP (\fBQTextStream\fP &s, \fBSBAploChunk\fP &)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBQTextStream\fP& operator<< (\fBQTextStream\fP &s, const \fBSBAploChunk\fP &)"
.PP
Definition at line 458 of file SbGeoAtmLoad\&.C'\&.
.SS "\fBQTextStream\fP& operator>> (\fBQTextStream\fP &s, \fBSBAploChunk\fP &)"
.PP
Definition at line 464 of file SbGeoAtmLoad\&.C'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
