SbGeoSources.C
NAME
SbGeoSources.C -
SYNOPSIS
#include 'SbGeoSources.H'
#include <qmessagebox.h>
#include 'SbSetup.H'
#include 'SbGeoParameter.H'
#include 'SbGeoProject.H'
Functions
QDataStream & operator<< (QDataStream &s, const SBSource &S)
QDataStream & operator>> (QDataStream &s, SBSource &S)
SBTS_report & operator<< (SBTS_report &s, const SBSource &S)
SBTS_report4IVS & operator<< (SBTS_report4IVS &s, const SBSource &S)
SBTS_rsc & operator<< (SBTS_rsc &s, const SBSource &S)
SBTS_rsc & operator>> (SBTS_rsc &s, SBSource &S)
SBTS_car & operator<< (SBTS_car &s, const SBSource &S)
SBTS_car & operator>> (SBTS_car &s, SBSource &S)
QDataStream & operator<< (QDataStream &s, const SB_CRF &CRF)
QDataStream & operator>> (QDataStream &s, SB_CRF &CRF)
SBTS_dico & operator<< (SBTS_dico &s, SB_CRF &CRF)
SBTS_dico & operator>> (SBTS_dico &s, SB_CRF &CRF)
SBTS_report & operator<< (SBTS_report &s, const SB_CRF &CRF)
SBTS_report4IVS & operator<< (SBTS_report4IVS &s, const SB_CRF &CRF)
SBTS_rsc & operator<< (SBTS_rsc &s, const SB_CRF &CRF)
SBTS_rsc & operator>> (SBTS_rsc &s, SB_CRF &CRF)
SBTS_car & operator<< (SBTS_car &s, const SB_CRF &CRF)
SBTS_car & operator>> (SBTS_car &s, SB_CRF &CRF)
Function Documentation
QDataStream& operator<< (QDataStream &s, const SBSource &S)
Definition at line 281 of file SbGeoSources.C'.
References SBSource::dDN, SBSource::DN, SBSource::dRA, SBSource::FirstMJD, SBSource::Flux1, SBSource::Flux2, SBSource::ICRF, SBSource::IsHLink, SBSource::LastMJD, SBSource::MeanMJD, SBSource::Mv, SBSource::NObsApr, SBSource::NSessApr, SBSource::RA, SBSource::RA_DN, SBSource::RedShift, SBSource::SpectrumClass, SBSource::SpIdx, SBSource::Status, SBSource::StructIdxS, SBSource::StructIdxX, and SBSource::Type.
SBTS_report& operator<< (SBTS_report &s, const SBSource &S)
Definition at line 305 of file SbGeoSources.C'.
References SBSource::corrRA_DN(), SBSource::dn_err(), SBSource::dn_t(), SBSource::firstMJD(), SBSource::ICRF, SBSource::lastMJD(), SBSource::meanMJD(), SBNamed::name(), SBSource::nObsApr(), SBSource::nSessApr(), SBSource::ra_err(), SBSource::ra_t(), RAD2DEG, rad2dms(), rad2hms(), and RAD2HR.
SBTS_report4IVS& operator<< (SBTS_report4IVS &s, const SBSource &S)
Definition at line 379 of file SbGeoSources.C'.
References SBSource::aList, SBSource::AnalysConstr, SBSource::corrRA_DN(), SBSource::dn_err(), SBSource::dn_t(), SBSource::firstMJD(), SBAttributed::isAttr(), SBSource::lastMJD(), SBSource::meanMJD(), SBNamed::name(), SBSource::nObsApr(), SBSource::nSessApr(), SBSource::ra_err(), SBSource::ra_t(), RAD2DEG, rad2dms(), rad2hms(), and RAD2HR.
SBTS_rsc& operator<< (SBTS_rsc &s, const SBSource &S)
Definition at line 441 of file SbGeoSources.C'.
References SBSource::corrRA_DN(), SBSource::dn_err(), SBSource::dn_t(), SBSource::firstMJD(), SBSource::ICRF, SBSource::isHLink(), SBSource::lastMJD(), SBSource::meanMJD(), SBNamed::name(), SBSource::nObsApr(), SBSource::nSessApr(), SBSource::ra_err(), SBSource::ra_t(), RAD2DEG, rad2dms(), rad2hms(), RAD2HR, SBSource::Status, SBSource::STATUS_CAND, SBSource::STATUS_DEF, SBSource::STATUS_NEW, SBSource::STATUS_OTHER, and SBSource::STATUS_UNKN.
SBTS_car& operator<< (SBTS_car &s, const SBSource &S)
Definition at line 930 of file SbGeoSources.C'.
References SBSource::flux1(), SBSource::flux2(), SBSource::ICRF, SBSource::mv(), SBNamed::name(), SBSource::redShift(), SBSource::SP_HP, SBSource::SP_OTHER, SBSource::SP_SEYFERT, SBSource::SP_SEYFERT1, SBSource::SP_SEYFERT1_2, SBSource::SP_SEYFERT2, SBSource::SP_SEYFERT3, SBSource::SP_UNKN, SBSource::SpectrumClass, SBSource::spIdx(), SBSource::Type, SBSource::TYPE_BL_LAC, SBSource::TYPE_BL_LAC_C, SBSource::TYPE_GALAXY, SBSource::TYPE_OTHER, SBSource::TYPE_QUASAR, and SBSource::TYPE_UNKN.
QDataStream& operator<< (QDataStream &s, const SB_CRF &CRF)
Definition at line 1287 of file SbGeoSources.C'.
SBTS_dico& operator<< (SBTS_dico &s, SB_CRF &CRF)
Definition at line 1299 of file SbGeoSources.C'.
References SBSource::aList, SBSource::ICRF, SBNamed::name(), SB_CRF::prepareAliases4Output(), and SB_CRF::releaseAliases4Output().
SBTS_report& operator<< (SBTS_report &s, const SB_CRF &CRF)
Definition at line 1372 of file SbGeoSources.C'.
References SBCatalog::Label.
SBTS_report4IVS& operator<< (SBTS_report4IVS &s, const SB_CRF &CRF)
Definition at line 1396 of file SbGeoSources.C'.
References SBSource::Analysed.
SBTS_rsc& operator<< (SBTS_rsc &s, const SB_CRF &CRF)
Definition at line 1416 of file SbGeoSources.C'.
References SBCatalog::Label.
SBTS_car& operator<< (SBTS_car &s, const SB_CRF &CRF)
Definition at line 1501 of file SbGeoSources.C'.
QDataStream& operator>> (QDataStream &s, SBSource &S)
Definition at line 291 of file SbGeoSources.C'.
References SBSource::dDN, SBSource::DN, SBSource::DNt, SBSource::dRA, SBSource::FirstMJD, SBSource::Flux1, SBSource::Flux2, SBSource::ICRF, SBSource::IsHLink, SBSource::LastMJD, SBSource::MeanMJD, SBSource::Mv, SBSource::NObsApr, SBSource::NSessApr, SBSource::RA, SBSource::RA_DN, SBSource::RAt, SBSource::RedShift, SBSource::SINEXCharID, SBSource::SpectrumClass, SBSource::SpIdx, SBSource::Status, SBSource::StructIdxS, SBSource::StructIdxX, and SBSource::Type.
SBTS_rsc& operator>> (SBTS_rsc &s, SBSource &S)
Definition at line 494 of file SbGeoSources.C'.
References SBAttributed::addAttr(), SBTS_rsc::assignedStatus(), SBLog::DBG, dms2rad(), hms2rad(), SBSource::ICRF, SBLog::INF, SBSource::isValidICRFName(), Log, SBSource::OrigImported, SBSource::setCorrRA_DN(), SBSource::setDN(), SBSource::setDN_err(), SBSource::setFirstMJD(), SBSource::setIsHLink(), SBSource::setLastMJD(), SBSource::setMeanMJD(), SBNamed::setName(), SBSource::setNObsApr(), SBSource::setNSessApr(), SBSource::setRA(), SBSource::setRA_err(), SBSource::setStructIdxS(), SBSource::setStructIdxX(), SBLog::SOURCE, SBSource::Status, SBSource::STATUS_CAND, SBSource::STATUS_DEF, SBSource::STATUS_NEW, SBSource::STATUS_OTHER, SBSource::STATUS_UNKN, SBSource::StatusSuspected, and SBLog::write().
SBTS_car& operator>> (SBTS_car &s, SBSource &S)
Definition at line 1009 of file SbGeoSources.C'.
References SBLog::DBG, SBSource::ICRF, SBLog::INF, SBSource::isValidICRFName(), Log, SBSource::setFlux1(), SBSource::setFlux2(), SBSource::setMv(), SBNamed::setName(), SBSource::setRedShift(), SBSource::setSpectrum(), SBSource::setSpIdx(), SBLog::SOURCE, SBSource::SP_HP, SBSource::SP_OTHER, SBSource::SP_SEYFERT, SBSource::SP_SEYFERT1, SBSource::SP_SEYFERT1_2, SBSource::SP_SEYFERT2, SBSource::SP_SEYFERT3, SBSource::SP_UNKN, SBSource::Type, SBSource::TYPE_BL_LAC, SBSource::TYPE_BL_LAC_C, SBSource::TYPE_GALAXY, SBSource::TYPE_OTHER, SBSource::TYPE_QUASAR, SBSource::TYPE_UNKN, and SBLog::write().
QDataStream& operator>> (QDataStream &s, SB_CRF &CRF)
Definition at line 1293 of file SbGeoSources.C'.
SBTS_dico& operator>> (SBTS_dico &s, SB_CRF &CRF)
Definition at line 1327 of file SbGeoSources.C'.
References SBCatalog::Aliases, SBLog::DBG, SBLog::ERR, SB_CRF::find(), SBSource::isValidICRFName(), Log, SBLog::SOURCE, SBLog::write(), and SBLog::WRN.
SBTS_rsc& operator>> (SBTS_rsc &s, SB_CRF &CRF)
Definition at line 1451 of file SbGeoSources.C'.
References SBLog::DBG, SBLog::ERR, SB_CRF::find(), SBSource::ICRFName(), SBCatalog::inSort(), Log, SBSource::OrigImported, SBLog::SOURCE, and SBLog::write().
SBTS_car& operator>> (SBTS_car &s, SB_CRF &CRF)
Definition at line 1526 of file SbGeoSources.C'.
References SBLog::DBG, SBLog::ERR, SB_CRF::find(), SBSource::ICRFName(), SBCatalog::inSort(), Log, SBLog::SOURCE, and SBLog::write().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.