SbGeoEop.C
NAME
SbGeoEop.C -
SYNOPSIS
#include 'SbGeoEop.H'
#include <qdir.h>
#include <qfile.h>
#include <qmessagebox.h>
#include 'SbSetup.H'
#include 'SbGeoParameter.H'
#include 'SbGeoProject.H'
#include 'SbMathSpline.H'
#include 'SbVector.H'
#include 'SbGeoRefFrame.H'
Functions
QTextStream & operator<< (QTextStream &s, const SBEOPEntry &eop)
QTextStream & operator>> (QTextStream &s, SBEOPEntry &eop)
QDataStream & operator<< (QDataStream &s, const SBEOP &EOP)
QDataStream & operator>> (QDataStream &s, SBEOP &EOP)
QTextStream & operator<< (QTextStream &s, const SBEOP &)
QTextStream & operator>> (QTextStream &s, SBEOP &)
Function Documentation
QTextStream& operator<< (QTextStream &s, const SBEOPEntry &eop)
Definition at line 55 of file SbGeoEop.C'.
References SBMJD::date(), SBMJD::day(), SBEOPEntry::Eps, SBEOPEntry::LOD, SBMJD::month2Str(), SBEOPEntry::Psi, SBEOPEntry::UT, SBEOPEntry::Xp, and SBEOPEntry::Yp.
QDataStream& operator<< (QDataStream &s, const SBEOP &EOP)
Definition at line 1223 of file SbGeoEop.C'.
References SBEOP::Epoch, SBEOP::Eps, SBEOP::Epss, SBEOP::Label, SBEOP::Psi, SBEOP::Psis, SBEOP::UT, SBEOP::UTHasHiTide, SBEOP::UTHasLoTide, SBEOP::UTs, SBEOP::Xp, SBEOP::Xps, SBEOP::Yp, and SBEOP::Yps.
QTextStream& operator<< (QTextStream &s, const SBEOP &)
Definition at line 1245 of file SbGeoEop.C'.
QTextStream& operator>> (QTextStream &s, SBEOPEntry &eop)
Definition at line 70 of file SbGeoEop.C'.
References SBMJD::date(), SBEOPEntry::Eps, SBEOPEntry::LOD, SBEOPEntry::Psi, SBEOPEntry::UT, SBEOPEntry::Xp, and SBEOPEntry::Yp.
QDataStream& operator>> (QDataStream &s, SBEOP &EOP)
Definition at line 1233 of file SbGeoEop.C'.
References SBEOP::checkRanges(), SBEOP::Epoch, SBEOP::Eps, SBEOP::Epss, SBEOP::Label, SBEOP::Psi, SBEOP::Psis, SBEOP::UT, SBEOP::UTHasHiTide, SBEOP::UTHasLoTide, SBEOP::UTs, SBEOP::Xp, SBEOP::Xps, SBEOP::Yp, and SBEOP::Yps.
QTextStream& operator>> (QTextStream &s, SBEOP &)
Definition at line 1250 of file SbGeoEop.C'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.