.TH "SbGeoRefraction.H" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoRefraction.H \- 
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br
\fC#include <qstring\&.h>\fP
.br
\fC#include 'SbGeoTime\&.H'\fP
.br
\fC#include 'SbVector3\&.H'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSBZenithDelay\fP"
.br
.ti -1c
.RI "class \fBSBMappingFunc\fP"
.br
.ti -1c
.RI "class \fBSBHZD_Hopfield\fP"
.br
.ti -1c
.RI "class \fBSBHZD_Saastamoinen\fP"
.br
.ti -1c
.RI "class \fBSBWZD_Hopfield\fP"
.br
.ti -1c
.RI "class \fBSBWZD_Saastamoinen\fP"
.br
.ti -1c
.RI "class \fBSBHMf_Chao\fP"
.br
.ti -1c
.RI "class \fBSBWMf_Chao\fP"
.br
.ti -1c
.RI "class \fBSBHMf_CfA2p2\fP"
.br
.ti -1c
.RI "class \fBSBHMf_Ifadis\fP"
.br
.ti -1c
.RI "class \fBSBWMf_Ifadis\fP"
.br
.ti -1c
.RI "class \fBSBHMf_MTT\fP"
.br
.ti -1c
.RI "class \fBSBWMf_MTT\fP"
.br
.ti -1c
.RI "class \fBSBHMf_NMF\fP"
.br
.ti -1c
.RI "class \fBSBWMf_NMF\fP"
.br
.ti -1c
.RI "class \fBSBGMf_CH\fP"
.br
.ti -1c
.RI "class \fBSBRefraction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
