.TH "SbGeoObsVLBI_IO.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoObsVLBI_IO.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <qmessagebox\&.h>\fP
.br
\fC#include <qregexp\&.h>\fP
.br
\fC#include <qdir\&.h>\fP
.br
\fC#include <qfile\&.h>\fP
.br
\fC#include 'SbGeoObsVLBI_IO\&.H'\fP
.br
\fC#include 'SbGeoStations\&.H'\fP
.br
\fC#include 'SbGeoSources\&.H'\fP
.br
\fC#include 'SbSetup\&.H'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSBTS_ngs\fP & \fBoperator<<\fP (\fBSBTS_ngs\fP &s, const \fBSBVLBISession\fP &)"
.br
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &s, \fBSBDBHPhysRec\fP &PH)"
.br
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &s, \fBSBDBHHistTriplet\fP &HT)"
.br
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &s, \fBSBDBHTCBlock\fP &B)"
.br
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &s, \fBSBDBHStartBlock\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_dbh\fP & \fBoperator>>\fP (\fBSBDS_dbh\fP &s, \fBSBDBHFormat\fP &F)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBSBTS_ngs\fP& operator<< (\fBSBTS_ngs\fP &s, const \fBSBVLBISession\fP &)"
.PP
Definition at line 47 of file SbGeoObsVLBI_IO\&.C'\&.
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHPhysRec\fP &PH)"
.PP
Definition at line 2325 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBLog::DATA, SBLog::ERR, SBDBHPhysRec::isOK, SBDBHPhysRec::Length, Log, SBDBHPhysRec::parseLR(), and SBLog::write()\&.
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHHistTriplet\fP &HT)"
.PP
Definition at line 2478 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBLog::DATA, SBLog::ERR, SBDBHLRecHS1::histLength(), SBDBHPhysRec::isOk(), SBDBHHistTriplet::isOK, SBDBHLRecPrefixed::isP(), SBDBHPhysRec::length(), Log, SBDBHHistTriplet::Rec1, SBDBHHistTriplet::Rec2, SBDBHHistTriplet::Rec3, SBDBHDRecString::text(), and SBLog::write()\&.
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHTCBlock\fP &B)"
.PP
Definition at line 2557 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBDBHTCBlock::isLast(), SBDBHPhysRec::isOk(), SBDBHTCBlock::isOK, SBDBHTCBlock::ListTEBlock, SBDBHLRecTC::numTEBlocks(), and SBDBHTCBlock::Rec\&.
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHStartBlock\fP &S)"
.PP
Definition at line 2599 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBDBHStartBlock::Date, SBDBHStartBlock::DateVal, SBDBHStartBlock::DbName, SBDBHStartBlock::ExpDescr, SBDBHPhysRec::isOk(), SBDBHStartBlock::isOK, SBDBHStartBlock::Prev, SBDBHStartBlock::PrevDb, SBDBHStartBlock::SessID, and SBDBHStartBlock::Ver\&.
.SS "\fBSBDS_dbh\fP& operator>> (\fBSBDS_dbh\fP &s, \fBSBDBHFormat\fP &F)"
.PP
Definition at line 2818 of file SbGeoObsVLBI_IO\&.C'\&.
.PP
References SBDBHTCBlock::isLast(), SBDBHFormat::isOK, SBDBHFormat::ListTCBlock, and SBDBHFormat::postRead()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
