.TH "SbGeoObsVLBI.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoObsVLBI.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <qapplication\&.h>\fP
.br
\fC#include <qdir\&.h>\fP
.br
\fC#include <qmessagebox\&.h>\fP
.br
\fC#include 'SbGeoObsVLBI\&.H'\fP
.br
\fC#include 'SbGeoObsVLBI_IO\&.H'\fP
.br
\fC#include 'SbSetup\&.H'\fP
.br
\fC#include 'SbGeoDelay\&.H'\fP
.br
\fC#include 'SbGeoProject\&.H'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBStationInfo\fP &St)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBStationInfo\fP &St)"
.br
.ti -1c
.RI "\fBSBDS_dat\fP & \fBoperator<<\fP (\fBSBDS_dat\fP &s, const \fBSBObsVLBIEntry\fP &Entry)"
.br
.ti -1c
.RI "\fBSBDS_dat\fP & \fBoperator>>\fP (\fBSBDS_dat\fP &s, \fBSBObsVLBIEntry\fP &Entry)"
.br
.ti -1c
.RI "\fBSBDS_aux\fP & \fBoperator<<\fP (\fBSBDS_aux\fP &s, const \fBSBObsVLBIEntry\fP &Entry)"
.br
.ti -1c
.RI "\fBSBDS_aux\fP & \fBoperator>>\fP (\fBSBDS_aux\fP &s, \fBSBObsVLBIEntry\fP &Entry)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBVLBISesInfo\fP &S)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBVLBISesInfo\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_dat\fP & \fBoperator<<\fP (\fBSBDS_dat\fP &s, const \fBSBVLBISesInfo\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_dat\fP & \fBoperator>>\fP (\fBSBDS_dat\fP &s, \fBSBVLBISesInfo\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_aux\fP & \fBoperator<<\fP (\fBSBDS_aux\fP &s, const \fBSBVLBISesInfo\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_aux\fP & \fBoperator>>\fP (\fBSBDS_aux\fP &s, \fBSBVLBISesInfo\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_dat\fP & \fBoperator<<\fP (\fBSBDS_dat\fP &s, const \fBSBVLBISession\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_dat\fP & \fBoperator>>\fP (\fBSBDS_dat\fP &s, \fBSBVLBISession\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_aux\fP & \fBoperator<<\fP (\fBSBDS_aux\fP &s, \fBSBVLBISession\fP &S)"
.br
.ti -1c
.RI "\fBSBDS_aux\fP & \fBoperator>>\fP (\fBSBDS_aux\fP &s, \fBSBVLBISession\fP &S)"
.br
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator>>\fP (\fBQTextStream\fP &s, \fBSBMasterFile\fP &F)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBStationInfo\fP &St)\fC [related]\fP"Saves to the data stream'\&. 
.PP
Definition at line 267 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBStationInfo::Cl_E, SBStationInfo::Cl_Order, SBStationInfo::Cl_V, SBStationInfo::ClockBreaks, SBStationInfo::Clocks, SBStationInfo::ErrZw, SBStationInfo::Zenith, and SBStationInfo::Zw\&.
.SS "\fBSBDS_dat\fP& operator<< (\fBSBDS_dat\fP &s, const \fBSBObsVLBIEntry\fP &Entry)"
.PP
Definition at line 1009 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBObsVLBIEntry::AtmHum_1, SBObsVLBIEntry::AtmHum_2, SBObsVLBIEntry::AtmPress_1, SBObsVLBIEntry::AtmPress_2, SBObsVLBIEntry::AtmTemp_1, SBObsVLBIEntry::AtmTemp_2, SBObsVLBIEntry::Cable_1, SBObsVLBIEntry::Cable_2, SBObsVLBIEntry::Correlation, SBObsVLBIEntry::Delay, SBObsVLBIEntry::DelayErr, SBObsVLBIEntry::DelayIon, SBObsVLBIEntry::DelayIonErr, SBObsVLBIEntry::DUFlag, SBObsVLBIEntry::FringePhase, SBObsVLBIEntry::GrDelayAmbig, SBObservation::Idx, SBObsVLBIEntry::IonErrorFlag, SBObsVLBIEntry::QualCode, SBObsVLBIEntry::Rate, SBObsVLBIEntry::RateErr, SBObsVLBIEntry::RateIon, SBObsVLBIEntry::RateIonErr, SBObsVLBIEntry::RefFreq, SBObsVLBIEntry::RUFlag, SBObsVLBIEntry::Source, SBObsVLBIEntry::Station_1, and SBObsVLBIEntry::Station_2\&.
.SS "\fBSBDS_aux\fP& operator<< (\fBSBDS_aux\fP &s, const \fBSBObsVLBIEntry\fP &Entry)"
.PP
Definition at line 1042 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBObsVLBIEntry::AltAtmHum_1, SBObsVLBIEntry::AltAtmHum_2, SBObsVLBIEntry::AltAtmPress_1, SBObsVLBIEntry::AltAtmPress_2, SBObsVLBIEntry::AltAtmTemp_1, SBObsVLBIEntry::AltAtmTemp_2, SBObsVLBIEntry::AmbiguityFactor, SBObsVLBIEntry::DelayRes, SBObservation::Idx, SBObsVLBIEntry::RateRes, SBObsVLBIEntry::ZenithDelay_1, and SBObsVLBIEntry::ZenithDelay_2\&.
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBVLBISesInfo\fP &S)"
.PP
Definition at line 1188 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayRMS2, SBVLBISesInfo::DelaySumW2, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, SBVLBISesInfo::NumBas, SBVLBISesInfo::NumObs, SBVLBISesInfo::NumSou, SBVLBISesInfo::NumSta, SBVLBISesInfo::OfficialName, SBVLBISesInfo::RateRMS2, SBVLBISesInfo::RateSumW2, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, SBVLBISesInfo::UserFlag, and SBVLBISesInfo::Version\&.
.SS "\fBSBDS_dat\fP& operator<< (\fBSBDS_dat\fP &s, const \fBSBVLBISesInfo\fP &S)"
.PP
Definition at line 1214 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::OfficialName, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, and SBVLBISesInfo::Version\&.
.SS "\fBSBDS_aux\fP& operator<< (\fBSBDS_aux\fP &s, const \fBSBVLBISesInfo\fP &S)"
.PP
Definition at line 1230 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, and SBVLBISesInfo::UserFlag\&.
.SS "\fBSBDS_dat\fP& operator<< (\fBSBDS_dat\fP &s, const \fBSBVLBISession\fP &S)"
.PP
Definition at line 1867 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISession::DBHHistory\&.
.SS "\fBSBDS_aux\fP& operator<< (\fBSBDS_aux\fP &s, \fBSBVLBISession\fP &S)"
.PP
Definition at line 1880 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISession::BaseList, SBVLBISession::first(), SBVLBISession::GrDelayAmbig, SBVLBISession::LocalHistory, SBVLBISession::next(), SBVLBISession::RefFreq, SBVLBISession::SourceList, and SBVLBISession::StationList\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBStationInfo\fP &St)\fC [related]\fP"Loads from the data stream'\&. 
.PP
Definition at line 278 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBStationInfo::Cl_E, SBStationInfo::Cl_Order, SBStationInfo::Cl_V, SBStationInfo::ClockBreaks, SBStationInfo::Clocks, SBStationInfo::ErrZw, SBStationInfo::Zenith, and SBStationInfo::Zw\&.
.SS "\fBSBDS_dat\fP& operator>> (\fBSBDS_dat\fP &s, \fBSBObsVLBIEntry\fP &Entry)"
.PP
Definition at line 1025 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBObsVLBIEntry::AtmHum_1, SBObsVLBIEntry::AtmHum_2, SBObsVLBIEntry::AtmPress_1, SBObsVLBIEntry::AtmPress_2, SBObsVLBIEntry::AtmTemp_1, SBObsVLBIEntry::AtmTemp_2, SBObsVLBIEntry::Cable_1, SBObsVLBIEntry::Cable_2, SBObsVLBIEntry::Correlation, SBObsVLBIEntry::Delay, SBObsVLBIEntry::DelayErr, SBObsVLBIEntry::DelayIon, SBObsVLBIEntry::DelayIonErr, SBObsVLBIEntry::DUFlag, SBObsVLBIEntry::FringePhase, SBObsVLBIEntry::GrDelayAmbig, SBObservation::Idx, SBObsVLBIEntry::IonErrorFlag, SBObsVLBIEntry::QualCode, SBObsVLBIEntry::Rate, SBObsVLBIEntry::RateErr, SBObsVLBIEntry::RateIon, SBObsVLBIEntry::RateIonErr, SBObsVLBIEntry::RefFreq, SBObsVLBIEntry::RUFlag, SBObservation::setTech(), SBObsVLBIEntry::Source, SBObsVLBIEntry::Station_1, SBObsVLBIEntry::Station_2, and TECH_VLBI\&.
.SS "\fBSBDS_aux\fP& operator>> (\fBSBDS_aux\fP &s, \fBSBObsVLBIEntry\fP &Entry)"
.PP
Definition at line 1052 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBObsVLBIEntry::AltAtmHum_1, SBObsVLBIEntry::AltAtmHum_2, SBObsVLBIEntry::AltAtmPress_1, SBObsVLBIEntry::AltAtmPress_2, SBObsVLBIEntry::AltAtmTemp_1, SBObsVLBIEntry::AltAtmTemp_2, SBObsVLBIEntry::AmbiguityFactor, SBObsVLBIEntry::DelayRes, SBObservation::Idx, SBObsVLBIEntry::RateRes, SBObservation::setTech(), TECH_VLBI, SBObsVLBIEntry::ZenithDelay_1, and SBObsVLBIEntry::ZenithDelay_2\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBVLBISesInfo\fP &S)"
.PP
Definition at line 1200 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayRMS2, SBVLBISesInfo::DelaySumW2, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, SBVLBISesInfo::NumBas, SBVLBISesInfo::NumObs, SBVLBISesInfo::NumSou, SBVLBISesInfo::NumSta, SBVLBISesInfo::OfficialName, SBVLBISesInfo::RateRMS2, SBVLBISesInfo::RateSumW2, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, SBVLBISesInfo::UserFlag, and SBVLBISesInfo::Version\&.
.SS "\fBSBDS_dat\fP& operator>> (\fBSBDS_dat\fP &s, \fBSBVLBISesInfo\fP &S)"
.PP
Definition at line 1222 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::OfficialName, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, and SBVLBISesInfo::Version\&.
.SS "\fBSBDS_aux\fP& operator>> (\fBSBDS_aux\fP &s, \fBSBVLBISesInfo\fP &S)"
.PP
Definition at line 1235 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, and SBVLBISesInfo::UserFlag\&.
.SS "\fBSBDS_dat\fP& operator>> (\fBSBDS_dat\fP &s, \fBSBVLBISession\fP &S)"
.PP
Definition at line 1873 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISession::DBHHistory, and SBVLBISesInfo::NumObs\&.
.SS "\fBSBDS_aux\fP& operator>> (\fBSBDS_aux\fP &s, \fBSBVLBISession\fP &S)"
.PP
Definition at line 1888 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBVLBISession::BaseList, SBLog::DATA, SBLog::ERR, SBVLBISession::fillDicts(), SBVLBISession::first(), SBVLBISession::GrDelayAmbig, SBLog::IO, SBVLBISession::LocalHistory, Log, SBVLBISession::next(), SBVLBISesInfo::NumBas, SBVLBISesInfo::NumSou, SBVLBISesInfo::NumSta, SBVLBISession::RefFreq, SBVLBISession::SourceList, SBVLBISession::StationList, and SBLog::write()\&.
.SS "\fBQTextStream\fP& operator>> (\fBQTextStream\fP &s, \fBSBMasterFile\fP &F)"
.PP
Definition at line 2020 of file SbGeoObsVLBI\&.C'\&.
.PP
References SBAttributed::addAttr(), SBMasterFile::ClassName(), SBLog::DBG, SBMasterRecord::Intensive, SBMasterFile::Intensive, SBAttributed::isAttr(), Log, SBLog::STATION, SBLog::write(), and SBMasterFile::yr()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
