SbGeoObsVLBI.C
NAME
SbGeoObsVLBI.C -
SYNOPSIS
#include <qapplication.h>
#include <qdir.h>
#include <qmessagebox.h>
#include 'SbGeoObsVLBI.H'
#include 'SbGeoObsVLBI_IO.H'
#include 'SbSetup.H'
#include 'SbGeoDelay.H'
#include 'SbGeoProject.H'
Functions
QDataStream & operator<< (QDataStream &s, const SBStationInfo &St)
QDataStream & operator>> (QDataStream &s, SBStationInfo &St)
SBDS_dat & operator<< (SBDS_dat &s, const SBObsVLBIEntry &Entry)
SBDS_dat & operator>> (SBDS_dat &s, SBObsVLBIEntry &Entry)
SBDS_aux & operator<< (SBDS_aux &s, const SBObsVLBIEntry &Entry)
SBDS_aux & operator>> (SBDS_aux &s, SBObsVLBIEntry &Entry)
QDataStream & operator<< (QDataStream &s, const SBVLBISesInfo &S)
QDataStream & operator>> (QDataStream &s, SBVLBISesInfo &S)
SBDS_dat & operator<< (SBDS_dat &s, const SBVLBISesInfo &S)
SBDS_dat & operator>> (SBDS_dat &s, SBVLBISesInfo &S)
SBDS_aux & operator<< (SBDS_aux &s, const SBVLBISesInfo &S)
SBDS_aux & operator>> (SBDS_aux &s, SBVLBISesInfo &S)
SBDS_dat & operator<< (SBDS_dat &s, const SBVLBISession &S)
SBDS_dat & operator>> (SBDS_dat &s, SBVLBISession &S)
SBDS_aux & operator<< (SBDS_aux &s, SBVLBISession &S)
SBDS_aux & operator>> (SBDS_aux &s, SBVLBISession &S)
QTextStream & operator>> (QTextStream &s, SBMasterFile &F)
Function Documentation
QDataStream& operator<< (QDataStream &s, const SBStationInfo &St) [related]"Saves to the data stream'.
Definition at line 267 of file SbGeoObsVLBI.C'.
References SBStationInfo::Cl_E, SBStationInfo::Cl_Order, SBStationInfo::Cl_V, SBStationInfo::ClockBreaks, SBStationInfo::Clocks, SBStationInfo::ErrZw, SBStationInfo::Zenith, and SBStationInfo::Zw.
SBDS_dat& operator<< (SBDS_dat &s, const SBObsVLBIEntry &Entry)
Definition at line 1009 of file SbGeoObsVLBI.C'.
References SBObsVLBIEntry::AtmHum_1, SBObsVLBIEntry::AtmHum_2, SBObsVLBIEntry::AtmPress_1, SBObsVLBIEntry::AtmPress_2, SBObsVLBIEntry::AtmTemp_1, SBObsVLBIEntry::AtmTemp_2, SBObsVLBIEntry::Cable_1, SBObsVLBIEntry::Cable_2, SBObsVLBIEntry::Correlation, SBObsVLBIEntry::Delay, SBObsVLBIEntry::DelayErr, SBObsVLBIEntry::DelayIon, SBObsVLBIEntry::DelayIonErr, SBObsVLBIEntry::DUFlag, SBObsVLBIEntry::FringePhase, SBObsVLBIEntry::GrDelayAmbig, SBObservation::Idx, SBObsVLBIEntry::IonErrorFlag, SBObsVLBIEntry::QualCode, SBObsVLBIEntry::Rate, SBObsVLBIEntry::RateErr, SBObsVLBIEntry::RateIon, SBObsVLBIEntry::RateIonErr, SBObsVLBIEntry::RefFreq, SBObsVLBIEntry::RUFlag, SBObsVLBIEntry::Source, SBObsVLBIEntry::Station_1, and SBObsVLBIEntry::Station_2.
SBDS_aux& operator<< (SBDS_aux &s, const SBObsVLBIEntry &Entry)
Definition at line 1042 of file SbGeoObsVLBI.C'.
References SBObsVLBIEntry::AltAtmHum_1, SBObsVLBIEntry::AltAtmHum_2, SBObsVLBIEntry::AltAtmPress_1, SBObsVLBIEntry::AltAtmPress_2, SBObsVLBIEntry::AltAtmTemp_1, SBObsVLBIEntry::AltAtmTemp_2, SBObsVLBIEntry::AmbiguityFactor, SBObsVLBIEntry::DelayRes, SBObservation::Idx, SBObsVLBIEntry::RateRes, SBObsVLBIEntry::ZenithDelay_1, and SBObsVLBIEntry::ZenithDelay_2.
QDataStream& operator<< (QDataStream &s, const SBVLBISesInfo &S)
Definition at line 1188 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayRMS2, SBVLBISesInfo::DelaySumW2, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, SBVLBISesInfo::NumBas, SBVLBISesInfo::NumObs, SBVLBISesInfo::NumSou, SBVLBISesInfo::NumSta, SBVLBISesInfo::OfficialName, SBVLBISesInfo::RateRMS2, SBVLBISesInfo::RateSumW2, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, SBVLBISesInfo::UserFlag, and SBVLBISesInfo::Version.
SBDS_dat& operator<< (SBDS_dat &s, const SBVLBISesInfo &S)
Definition at line 1214 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::OfficialName, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, and SBVLBISesInfo::Version.
SBDS_aux& operator<< (SBDS_aux &s, const SBVLBISesInfo &S)
Definition at line 1230 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, and SBVLBISesInfo::UserFlag.
SBDS_dat& operator<< (SBDS_dat &s, const SBVLBISession &S)
Definition at line 1867 of file SbGeoObsVLBI.C'.
References SBVLBISession::DBHHistory.
SBDS_aux& operator<< (SBDS_aux &s, SBVLBISession &S)
Definition at line 1880 of file SbGeoObsVLBI.C'.
References SBVLBISession::BaseList, SBVLBISession::first(), SBVLBISession::GrDelayAmbig, SBVLBISession::LocalHistory, SBVLBISession::next(), SBVLBISession::RefFreq, SBVLBISession::SourceList, and SBVLBISession::StationList.
QDataStream& operator>> (QDataStream &s, SBStationInfo &St) [related]"Loads from the data stream'.
Definition at line 278 of file SbGeoObsVLBI.C'.
References SBStationInfo::Cl_E, SBStationInfo::Cl_Order, SBStationInfo::Cl_V, SBStationInfo::ClockBreaks, SBStationInfo::Clocks, SBStationInfo::ErrZw, SBStationInfo::Zenith, and SBStationInfo::Zw.
SBDS_dat& operator>> (SBDS_dat &s, SBObsVLBIEntry &Entry)
Definition at line 1025 of file SbGeoObsVLBI.C'.
References SBObsVLBIEntry::AtmHum_1, SBObsVLBIEntry::AtmHum_2, SBObsVLBIEntry::AtmPress_1, SBObsVLBIEntry::AtmPress_2, SBObsVLBIEntry::AtmTemp_1, SBObsVLBIEntry::AtmTemp_2, SBObsVLBIEntry::Cable_1, SBObsVLBIEntry::Cable_2, SBObsVLBIEntry::Correlation, SBObsVLBIEntry::Delay, SBObsVLBIEntry::DelayErr, SBObsVLBIEntry::DelayIon, SBObsVLBIEntry::DelayIonErr, SBObsVLBIEntry::DUFlag, SBObsVLBIEntry::FringePhase, SBObsVLBIEntry::GrDelayAmbig, SBObservation::Idx, SBObsVLBIEntry::IonErrorFlag, SBObsVLBIEntry::QualCode, SBObsVLBIEntry::Rate, SBObsVLBIEntry::RateErr, SBObsVLBIEntry::RateIon, SBObsVLBIEntry::RateIonErr, SBObsVLBIEntry::RefFreq, SBObsVLBIEntry::RUFlag, SBObservation::setTech(), SBObsVLBIEntry::Source, SBObsVLBIEntry::Station_1, SBObsVLBIEntry::Station_2, and TECH_VLBI.
SBDS_aux& operator>> (SBDS_aux &s, SBObsVLBIEntry &Entry)
Definition at line 1052 of file SbGeoObsVLBI.C'.
References SBObsVLBIEntry::AltAtmHum_1, SBObsVLBIEntry::AltAtmHum_2, SBObsVLBIEntry::AltAtmPress_1, SBObsVLBIEntry::AltAtmPress_2, SBObsVLBIEntry::AltAtmTemp_1, SBObsVLBIEntry::AltAtmTemp_2, SBObsVLBIEntry::AmbiguityFactor, SBObsVLBIEntry::DelayRes, SBObservation::Idx, SBObsVLBIEntry::RateRes, SBObservation::setTech(), TECH_VLBI, SBObsVLBIEntry::ZenithDelay_1, and SBObsVLBIEntry::ZenithDelay_2.
QDataStream& operator>> (QDataStream &s, SBVLBISesInfo &S)
Definition at line 1200 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayRMS2, SBVLBISesInfo::DelaySumW2, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, SBVLBISesInfo::NumBas, SBVLBISesInfo::NumObs, SBVLBISesInfo::NumSou, SBVLBISesInfo::NumSta, SBVLBISesInfo::OfficialName, SBVLBISesInfo::RateRMS2, SBVLBISesInfo::RateSumW2, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, SBVLBISesInfo::UserFlag, and SBVLBISesInfo::Version.
SBDS_dat& operator>> (SBDS_dat &s, SBVLBISesInfo &S)
Definition at line 1222 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::Code, SBVLBISesInfo::CorrelatorName, SBVLBISesInfo::DateCreat, SBVLBISesInfo::DelayType, SBVLBISesInfo::ExpDescr, SBVLBISesInfo::ImportedFrom, SBVLBISesInfo::OfficialName, SBVLBISesInfo::SubKey, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, SBVLBISesInfo::TStart, and SBVLBISesInfo::Version.
SBDS_aux& operator>> (SBDS_aux &s, SBVLBISesInfo &S)
Definition at line 1235 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::LocalVersion, SBVLBISesInfo::NetworkID, and SBVLBISesInfo::UserFlag.
SBDS_dat& operator>> (SBDS_dat &s, SBVLBISession &S)
Definition at line 1873 of file SbGeoObsVLBI.C'.
References SBVLBISession::DBHHistory, and SBVLBISesInfo::NumObs.
SBDS_aux& operator>> (SBDS_aux &s, SBVLBISession &S)
Definition at line 1888 of file SbGeoObsVLBI.C'.
References SBVLBISession::BaseList, SBLog::DATA, SBLog::ERR, SBVLBISession::fillDicts(), SBVLBISession::first(), SBVLBISession::GrDelayAmbig, SBLog::IO, SBVLBISession::LocalHistory, Log, SBVLBISession::next(), SBVLBISesInfo::NumBas, SBVLBISesInfo::NumSou, SBVLBISesInfo::NumSta, SBVLBISession::RefFreq, SBVLBISession::SourceList, SBVLBISession::StationList, and SBLog::write().
QTextStream& operator>> (QTextStream &s, SBMasterFile &F)
Definition at line 2020 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), SBMasterFile::ClassName(), SBLog::DBG, SBMasterRecord::Intensive, SBMasterFile::Intensive, SBAttributed::isAttr(), Log, SBLog::STATION, SBLog::write(), and SBMasterFile::yr().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.