.TH "SbGeoRefFrame.H" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoRefFrame.H \- 
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br
\fC#include 'SbGeneral\&.H'\fP
.br
\fC#include 'SbVector3\&.H'\fP
.br
\fC#include 'SbGeo\&.H'\fP
.br
\fC#include 'SbGeoTime\&.H'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSBNutThGeneral\fP"
.br
.ti -1c
.RI "class \fBSBNROThGeneral\fP"
.br
.ti -1c
.RI "class \fBSBSTideUT1\fP"
.br
.ti -1c
.RI "struct \fBSBSTideUT1::TableEntry\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOPGeneral\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOPGenS\fP"
.br
.ti -1c
.RI "struct \fBSBOTideEOPGenS::TableEntry\fP"
.br
.ti -1c
.RI "class \fBSBPrecession\fP"
.br
.ti -1c
.RI "class \fBSBPrec_IAU1976\fP"
.br
.ti -1c
.RI "class \fBSBPrec_IAU2000\fP"
.br
.ti -1c
.RI "class \fBSBNutation\fP"
.br
.ti -1c
.RI "class \fBSBNut_IAU1980\fP"
.br
.ti -1c
.RI "class \fBSBNut_IAU2000\fP"
.br
.ti -1c
.RI "class \fBSBPrecNutNRO\fP"
.br
.ti -1c
.RI "class \fBSBPolus\fP"
.br
.ti -1c
.RI "class \fBSBPolusNRO\fP"
.br
.ti -1c
.RI "class \fBSBRotate\fP"
.br
.ti -1c
.RI "class \fBSBFrame\fP"
.br
.ti -1c
.RI "class \fBSBFrameClassic\fP"
.br
.ti -1c
.RI "class \fBSBFrameNRO\fP"
.br
.ti -1c
.RI "class \fBSBNutThIAU1980\fP"
.br
.ti -1c
.RI "struct \fBSBNutThIAU1980::TableEntry\fP"
.br
.ti -1c
.RI "class \fBSBNROThIAU1980\fP"
.br
.ti -1c
.RI "class \fBSBNutThIAU1996\fP"
.br
.ti -1c
.RI "struct \fBSBNutThIAU1996::TableEntry\fP"
.br
.ti -1c
.RI "struct \fBSBNutThIAU1996::PlanetTableEntry\fP"
.br
.ti -1c
.RI "class \fBSBNROThIAU1996\fP"
.br
.ti -1c
.RI "class \fBSBNutThIAU2000A\fP"
.br
.ti -1c
.RI "struct \fBSBNutThIAU2000A::SolLunTableEntry\fP"
.br
.ti -1c
.RI "struct \fBSBNutThIAU2000A::PlanetTableEntry\fP"
.br
.ti -1c
.RI "class \fBSBNROThIAU2000A\fP"
.br
.ti -1c
.RI "struct \fBSBNROThIAU2000A::GeneralTableEntry\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOPRay1994_1996\fP"
.br
.ti -1c
.RI "struct \fBSBOTideEOPRay1994_1996::TableEntry\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOPRay1994_2003\fP"
.br
.ti -1c
.RI "struct \fBSBOTideEOPRay1994_2003::TableEntry\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOP_JPL92\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOP_HD1994\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOP_GSFC95\fP"
.br
.ti -1c
.RI "class \fBSBOTideEOP_Gipson1995\fP"
.br
.ti -1c
.RI "class \fBSBATideEOP_BBP_02\fP"
.br
.ti -1c
.RI "struct \fBSBATideEOP_BBP_02::TableEntry\fP"
.br
.ti -1c
.RI "class \fBSBNonTideEOP_Viron_02\fP"
.br
.ti -1c
.RI "struct \fBSBNonTideEOP_Viron_02::TableEntry\fP"
.br
.ti -1c
.RI "class \fBSBGravTideEOP_B_02\fP"
.br
.ti -1c
.RI "struct \fBSBGravTideEOP_B_02::TableEntry\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
