SbGeo.H
NAME
SbGeo.H -
SYNOPSIS
#include <config.h>
#include <qdatetime.h>
#include <qdict.h>
#include <qtextstream.h>
#include 'SbGeneral.H'
#include 'SbGeoTime.H'
Classes
class SBDated
class SBDList
class SBNamed
class SBNList
class SBInstitution
class SBInstitutionList
class SBSolutionName
class SBCatalog
Defines
#define RAD2DEG (180.0/M_PI)
#define RAD2HR (12.0 /M_PI)
#define DEG2RAD (M_PI/180.0)
#define HR2RAD (M_PI/ 12.0)
#define SEC2RAD (DEG2RAD/3600.0)
#define RAD2SEC (RAD2DEG*3600.0)
#define DAY2SEC (86400.0)
#define RAD2MAS (RAD2SEC*1000.0)
#define RAD2MS (RAD2HR*3600.0*1000.0)
Typedefs
typedef QList< SBDated > SBDoubleList
typedef QListIterator< SBDated > SBDIterator
typedef QListIterator< SBNamed > SBNIterator
Enumerations
enum Technique { TECH_VLBI, TECH_OA, TECH_LLR, TECH_GPS, TECH_SLR, TECH_DORIS, TECH_COMBINED, TECH_CG, TECH_AD, TECH_TIE, TECH_UNKN, TECH_ANY }
Functions
double sign (const double x)
double sign (const double a1, const double a2)
double hms2rad (int h, int m, double s)
double dms2rad (int d, int m, double s)
void rad2hms (double, int &, int &, double &)
void rad2dms (double, int &, int &, double &)
void rad2dmsl (double, int &, int &, double &)
QString rad2hmsStr (double)
QString rad2dmsStr (double)
QString rad2dmslStr (double)
Variables
SBInstitutionList * Institutions
Define Documentation
#define DAY2SEC (86400.0)"seconds in one day
Definition at line 56 of file SbGeo.H'.
Referenced by SBDelay::calc(), SBNutation::calcGST(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBTestFrame::createWidget4Test(), SBTime::DefineTAI_UTC(), SBTestFrame::displayValues(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBRunManager::fillParameterList(), SBEphem::interp(), SBEOP::interpolateEOPs(), SBRunManager::makeReportEOP(), SBMJD::MJD_rev(), SBMJD::MJD_time(), SBEphemDE200::SBEphemDE200(), SBEphemDE403::SBEphemDE403(), SBEphemDE405::SBEphemDE405(), SBParametersDesc::SBParametersDesc(), SBTime::setUTC(), sinex_tro_MakeMeansTrops(), SBMJD::toString(), and writeNormalEquationSystem().
#define DEG2RAD (M_PI/180.0)"degrees to radians
Definition at line 44 of file SbGeo.H'.
Referenced by SBModelEditor::acquireData(), SBRefraction::altitudeCorr(), SBOceanTideLd::ARG_IERS(), SBStation::axisOffsetLenght(), SBNutThIAU1996::calc(), SBOTideEOPRay1994_1996::calc(), dms2rad(), SBOceanTideLd::operator()(), operator>>(), SBConfig::SBConfig(), SBSource::SBSource(), and SBTime::setUTC().
#define HR2RAD (M_PI/ 12.0)"hours to radians
Definition at line 47 of file SbGeo.H'.
Referenced by hms2rad(), and SBSource::SBSource().
#define RAD2DEG (180.0/M_PI)"radians to degrees
Definition at line 38 of file SbGeo.H'.
Referenced by SBSourceListItem::key(), SB_CRF::lookupNearest(), SBRefraction::makeDebugReport(), SBModelEditor::makeDefault(), SBRunManager::makeReportMaps(), operator<<(), rad2dms(), rad2dmsl(), SBSourceListItem::text(), and SBModelEditor::wLightPropagation().
#define RAD2HR (12.0 /M_PI)"radians to hours
Definition at line 41 of file SbGeo.H'.
Referenced by SBSourceListItem::key(), operator<<(), rad2hms(), and SBSourceListItem::text().
#define RAD2MAS (RAD2SEC*1000.0)"radians to mas
Definition at line 59 of file SbGeo.H'.
Referenced by writeNormalEquationSystem().
#define RAD2MS (RAD2HR*3600.0*1000.0)"radians to ms
Definition at line 62 of file SbGeo.H'.
#define RAD2SEC (RAD2DEG*3600.0)"radians to arc seconds
Definition at line 53 of file SbGeo.H'.
Referenced by collectListOfSINEXParameters4NEQ(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), SBRunManager::fillParameterList(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBPolarTideLd::operator()(), and SBParametersDesc::SBParametersDesc().
#define SEC2RAD (DEG2RAD/3600.0)"arc seconds to radians
Definition at line 50 of file SbGeo.H'.
Referenced by SBOTideEOPGenS::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBOTideEOPRay1994_2003::calc(), SBATideEOP_BBP_02::calc(), SBNonTideEOP_Viron_02::calc(), SBGravTideEOP_B_02::calc(), SBNut_IAU2000::calcGST(), SBRunManager::constraintEOP(), SBRunManager::constraintSourceCoord(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTime::FundamentalArgs(), SBNut_IAU1980::geodesicNutation(), SBPrecNutNRO::geodesicNutation(), SBEOP::interpolateEOPs(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), SBPolusNRO::operator()(), and SBFrameClassic::SBFrameClassic().
Typedef Documentation
typedef QListIterator<SBDated> SBDIterator
Definition at line 186 of file SbGeo.H'.
typedef QList<SBDated> SBDoubleList
Definition at line 185 of file SbGeo.H'.
typedef QListIterator<SBNamed> SBNIterator
Definition at line 263 of file SbGeo.H'.
Enumeration Type Documentation
enum Technique"Known techniques'.
Enumerator:
TECH_VLBI
R: Radio interferometry;'.
TECH_OA
A: optical astrometry;'.
TECH_LLR
M: Lunar laser ranging;'.
TECH_GPS
P: Global Positioning System;'.
TECH_SLR
L: satellite laser ranging;'.
TECH_DORIS
D: satellite Doppler tracking;'.
TECH_COMBINED
C: combined data;'.
TECH_CG
G: conventional geodesy (for SSC)
TECH_AD
*: atmospheric data
TECH_TIE
T: ties;'.
TECH_UNKN
?: uknown'.
TECH_ANY
_: any above
Definition at line 127 of file SbGeo.H'.
Function Documentation
double dms2rad (intd, intm, doubles) [inline]"Converts Degree, Min and Sec to Radians'.
Definition at line 73 of file SbGeo.H'.
References DEG2RAD.
Referenced by SBSourceEditor::acquireData(), and operator>>().
double hms2rad (inth, intm, doubles) [inline]"Converts Hour, Min and Sec to Radians'.
Definition at line 70 of file SbGeo.H'.
References HR2RAD.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void rad2dms (double, int &, int &, double &)"Converts Radians to Degree, Min and Sec'. [-M_PI; M_PI]
Definition at line 494 of file SbGeo.C'.
References RAD2DEG.
Referenced by SBSource::DN2str(), SBStationEditor::makeApply(), operator<<(), rad2dmsStr(), sinex_SiteIDBlock(), sinex_tro_SiteIDBlock(), SBSiteListItem::text(), SBSourceEditor::wCoordinates(), and SBStationEditor::wCoordinates().
void rad2dmsl (double, int &, int &, double &)"Converts Radians to Degree, Min and Sec'. [0; 2'.0*M_PI]
Definition at line 503 of file SbGeo.C'.
References RAD2DEG.
Referenced by SBStationEditor::makeApply(), operator<<(), rad2dmslStr(), sinex_SiteIDBlock(), sinex_tro_SiteIDBlock(), SBSiteListItem::text(), and SBStationEditor::wCoordinates().
QString rad2dmslStr (double)"Converts Radians to string with Degree, Min and Sec'. [0; 2'.0*M_PI]
Definition at line 521 of file SbGeo.C'.
References rad2dmsl().
Referenced by SBFrameClassic::calc(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBTime::setUTC().
QString rad2dmsStr (double)"Converts Radians to string with Degree, Min and Sec'. [-M_PI; M_PI]
Definition at line 512 of file SbGeo.C'.
References rad2dms().
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestEphem::displayCoo(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), and SBRefraction::operator()().
void rad2hms (double, int &, int &, double &)"Converts Radians to Hour, Min and Sec'.
Definition at line 485 of file SbGeo.C'.
References RAD2HR.
Referenced by operator<<(), SBSource::RA2str(), rad2hmsStr(), SBVLBISesInfoLI::text(), and SBSourceEditor::wCoordinates().
QString rad2hmsStr (double)"Converts Radians to string with Hour, Min and Sec'.
Definition at line 530 of file SbGeo.C'.
References rad2hms().
Referenced by SBFrameClassic::calc(), SBTestEphem::displayCoo(), and SBTime::setUTC().
double sign (const doublex) [inline]
Definition at line 66 of file SbGeo.H'.
Referenced by SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), SBStation::calcRLF(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), makeHouseholder(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBEstimator::propagateStochasticPars(), sign(), and writeNormalEquationSystem().
double sign (const doublea1, const doublea2) [inline]
Definition at line 67 of file SbGeo.H'.
References sign().
Variable Documentation
SBInstitutionList* Institutions
Definition at line 27 of file SbGeo.C'.
Referenced by SBSetUp::LoadStuff(), SBSetupDialog::makeApply(), SBSetUp::SaveStuff(), SBSetupDialog::SBSetupDialog(), SBSetUp::SetDefaults(), and SBMainWindow::~SBMainWindow().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.