SbGeoTime.C
NAME
SbGeoTime.C -
SYNOPSIS
#include 'SbGeoTime.H'
#include 'SbGeoEop.H'
#include <qdatetime.h>
Variables
const SBMJD TEphem (51544.5)
const SBMJD TZero (1943, 9, 6)
const SBMJD TInf (2100, 1, 1)
const SBMJD TUnix0 (1970, 1, 1)
Variable Documentation
const SBMJD TEphem(51544.5)
Referenced by SBAploWave::angle(), SBFrameNRO::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBNutation::calcGST(), SBNut_IAU2000::calcGST(), SBTime::FundamentalArgs(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolusNRO::operator()(), and SBTime::setUTC().
const SBMJD TInf(2100, 1, 1)
Referenced by SBSolution::dumpParameters(), SBRunManager::makeReportCRFVariations(), and SBRunManager::makeReportTRFVariations().
const SBMJD TUnix0(1970, 1, 1)
Referenced by SBMJD::toString().
const SBMJD TZero(1943, 9, 6)
Referenced by SBStationEditor::addCoordinates(), SBDelay::calc(), SBStation::calcDisplacement(), SBObsVLBIEntry::check(), SBAploEphem::checkEphem(), SBObsVLBIStatRecord::clear(), SBStatistics::clearStatistics(), SBDerivation::clearValues(), SBDerivation::clearValues_aux(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBAploEphem::dismissed(), SBSolution::dumpParameters(), SBSource::getParameters4Report(), SBEphem::import(), SBAploChunk::import(), SBAploEphem::importEphem(), SBAploEphem::importHPS(), SBStationEditor::makeApply(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), operator>>(), SBStochParameter::report(), SBAploEphem::SBAploEphem(), SBAploHeader::SBAploHeader(), SBCatalog::SBCatalog(), SBDerivation::SBDerivation(), SBEccentricity::SBEccentricity(), SBEOP::SBEOP(), SBEstimator::SBEstimator(), SBMasterFile::SBMasterFile(), SBRunManager::SBRunManager(), SBSINEXParameter::SBSINEXParameter(), SBStatistics::SBStatistics(), SBVLBISesInfo::SBVLBISesInfo(), SBDerivation::setD(), SBEOP::setPtNum(), sinex_SiteEccentricityBlock(), sinex_SolutionEpochsBlock(), SBDerivation::tEpoch(), SBStochParameter::tEpoch(), SBDerivation::tEpoch_aux(), SBObsVLBIStatSrcLI::text(), SBObsVLBIStatStaLI::text(), SBObsVLBIStatRecordLI::text(), SBProject::tFinis(), SBStochParameter::tFinis(), SBMJD::toString(), SBProject::tStart(), SBStochParameter::tStart(), and writeNormalEquationSystem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.