.TH "SbGeoParameter.H" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoParameter.H \- 
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br
\fC#include 'SbGeo\&.H'\fP
.br
\fC#include <qdatastream\&.h>\fP
.br
\fC#include <qintdict\&.h>\fP
.br
\fC#include <qlist\&.h>\fP
.br
\fC#include <qstring\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSBParameterCfg\fP"
.br
.ti -1c
.RI "class \fBSBParametersDesc\fP"
.br
.ti -1c
.RI "class \fBSBDerivation\fP"
.br
.ti -1c
.RI "class \fBSBParameter\fP"
.br
.ti -1c
.RI "class \fBSBParameterList\fP"
.br
.ti -1c
.RI "class \fBSBStochParameter\fP"
.br
.ti -1c
.RI "class \fBSBStochParameterList\fP"
.br
.ti -1c
.RI "class \fBSBStatistics\fP"
.br
.ti -1c
.RI "class \fBSBStatisticsList\fP"
.br
.ti -1c
.RI "class \fBSBSolution\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNUMBER_OF_PARAMETERS\fP   20"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define NUMBER_OF_PARAMETERS   20"
.PP
Definition at line 134 of file SbGeoParameter\&.H'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
