.TH "SbGeoProject.H" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbGeoProject.H \- 
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <qdatastream\&.h>\fP
.br
\fC#include <qlist\&.h>\fP
.br
\fC#include <qstring\&.h>\fP
.br
\fC#include <qtextstream\&.h>\fP
.br
\fC#include 'SbGeoObs\&.H'\fP
.br
\fC#include 'SbGeoObsVLBI\&.H'\fP
.br
\fC#include 'SbGeoParameter\&.H'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSBConfig\fP"
.br
.ti -1c
.RI "class \fBSBProject\fP"
.br
.ti -1c
.RI "class \fBSBRunManager\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBSBConfig\fP \fBDefaultConfig\fP"
.br
.ti -1c
.RI "\fBSBConfig\fP \fBConfig\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBSBConfig\fP \fBConfig\fP"
.PP
Definition at line 52 of file SbGeoProject\&.C'\&.
.PP
Referenced by SBEOP::interpolateEOPs(), SBSetUp::LoadStuff(), SBVLBIPreProcess::preProcess(), SBSetUp::SaveStuff(), SBStuffEphem::SBStuffEphem(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBMainWindow::StuffModels(), SBVLBIPreProcess::wEstPars(), SBModelEditor::~SBModelEditor(), and SBParametersEditor::~SBParametersEditor()\&.
.SS "const \fBSBConfig\fP \fBDefaultConfig\fP"
.PP
Definition at line 51 of file SbGeoProject\&.C'\&.
.PP
Referenced by SBSetUp::LoadStuff(), SBModelEditor::makeDefault(), SBParametersEditor::makeDefault(), SBParEditor::makeDefault(), and SBStationInfo::SBStationInfo()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
