SbGeo.C
NAME
SbGeo.C -
SYNOPSIS
#include 'SbGeo.H'
Functions
QDataStream & operator<< (QDataStream &s, const SBInstitutionList &L)
QDataStream & operator>> (QDataStream &s, SBInstitutionList &L)
QDataStream & operator<< (QDataStream &s, const SBSolutionName &Sol)
QDataStream & operator>> (QDataStream &s, SBSolutionName &Sol)
QTextStream & operator<< (QTextStream &s, const SBSolutionName &Sol)
QTextStream & operator>> (QTextStream &s, SBSolutionName &Sol)
QDataStream & operator<< (QDataStream &s, const SBCatalog &C)
QDataStream & operator>> (QDataStream &s, SBCatalog &C)
void rad2hms (double rad, int &h, int &m, double &s)
void rad2dms (double rad, int &d, int &m, double &s)
void rad2dmsl (double rad, int &d, int &m, double &s)
QString rad2dmsStr (double DN_)
QString rad2dmslStr (double DN_)
QString rad2hmsStr (double RA_)
Variables
SBInstitutionList * Institutions
Function Documentation
QDataStream& operator<< (QDataStream &s, const SBInstitutionList &L)
Definition at line 135 of file SbGeo.C'.
QDataStream& operator<< (QDataStream &s, const SBSolutionName &Sol)
Definition at line 223 of file SbGeo.C'.
References SBSolutionName::Acronym, SBSolutionName::Serial, SBSolutionName::Tech, SBSolutionName::Type, and SBSolutionName::Year.
QTextStream& operator<< (QTextStream &s, const SBSolutionName &Sol)
Definition at line 233 of file SbGeo.C'.
References SBSolutionName::toString().
QDataStream& operator<< (QDataStream &s, const SBCatalog &C)
Definition at line 438 of file SbGeo.C'.
References SBCatalog::Aliases, SBCatalog::Comment, SBCatalog::Epoch, and SBCatalog::Label.
QDataStream& operator>> (QDataStream &s, SBInstitutionList &L)
Definition at line 140 of file SbGeo.C'.
References SBInstitutionList::ClassName(), SBLog::CONFIG, SBLog::INF, SBInstitutionList::InstByAcronym, SBLog::IO, SBInstitutionList::IsChanged, Log, and SBLog::write().
QDataStream& operator>> (QDataStream &s, SBSolutionName &Sol)
Definition at line 228 of file SbGeo.C'.
References SBSolutionName::Acronym, SBSolutionName::Serial, SBSolutionName::Tech, SBSolutionName::Type, and SBSolutionName::Year.
QTextStream& operator>> (QTextStream &s, SBSolutionName &Sol)
Definition at line 238 of file SbGeo.C'.
References SBSolutionName::Acronym, SBLog::DBG, SBInstitution::descr(), SBLog::ERR, SBInstitutionList::find(), SBLog::INF, SBLog::IO, Log, SBSolutionName::Serial, SBSolutionName::Tech, TECH_AD, TECH_CG, TECH_COMBINED, TECH_DORIS, TECH_GPS, TECH_LLR, TECH_OA, TECH_SLR, TECH_TIE, TECH_UNKN, TECH_VLBI, SBSolutionName::Type, SBSolutionName::TYPE_AAM, SBSolutionName::TYPE_EOP, SBSolutionName::TYPE_RSC, SBSolutionName::TYPE_SSC, SBSolutionName::TYPE_SSV, SBSolutionName::TYPE_UNKN, SBLog::write(), SBLog::WRN, and SBSolutionName::Year.
QDataStream& operator>> (QDataStream &s, SBCatalog &C)
Definition at line 450 of file SbGeo.C'.
References SBCatalog::Aliases, SBCatalog::Comment, SBCatalog::Dict, SBCatalog::Epoch, and SBCatalog::Label.
void rad2dms (double, int &, int &, double &)"Converts Radians to Degree, Min and Sec'. [-M_PI; M_PI]
Definition at line 494 of file SbGeo.C'.
References RAD2DEG.
Referenced by SBSource::DN2str(), SBStationEditor::makeApply(), operator<<(), rad2dmsStr(), sinex_SiteIDBlock(), sinex_tro_SiteIDBlock(), SBSiteListItem::text(), SBSourceEditor::wCoordinates(), and SBStationEditor::wCoordinates().
void rad2dmsl (double, int &, int &, double &)"Converts Radians to Degree, Min and Sec'. [0; 2'.0*M_PI]
Definition at line 503 of file SbGeo.C'.
References RAD2DEG.
Referenced by SBStationEditor::makeApply(), operator<<(), rad2dmslStr(), sinex_SiteIDBlock(), sinex_tro_SiteIDBlock(), SBSiteListItem::text(), and SBStationEditor::wCoordinates().
QString rad2dmslStr (double)"Converts Radians to string with Degree, Min and Sec'. [0; 2'.0*M_PI]
Definition at line 521 of file SbGeo.C'.
References rad2dmsl().
Referenced by SBFrameClassic::calc(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBTime::setUTC().
QString rad2dmsStr (double)"Converts Radians to string with Degree, Min and Sec'. [-M_PI; M_PI]
Definition at line 512 of file SbGeo.C'.
References rad2dms().
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestEphem::displayCoo(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), and SBRefraction::operator()().
void rad2hms (double, int &, int &, double &)"Converts Radians to Hour, Min and Sec'.
Definition at line 485 of file SbGeo.C'.
References RAD2HR.
Referenced by operator<<(), SBSource::RA2str(), rad2hmsStr(), SBVLBISesInfoLI::text(), and SBSourceEditor::wCoordinates().
QString rad2hmsStr (double)"Converts Radians to string with Hour, Min and Sec'.
Definition at line 530 of file SbGeo.C'.
References rad2hms().
Referenced by SBFrameClassic::calc(), SBTestEphem::displayCoo(), and SBTime::setUTC().
Variable Documentation
SBInstitutionList* Institutions
Definition at line 27 of file SbGeo.C'.
Referenced by SBSetUp::LoadStuff(), SBSetupDialog::makeApply(), SBSetUp::SaveStuff(), SBSetupDialog::SBSetupDialog(), SBSetUp::SetDefaults(), and SBMainWindow::~SBMainWindow().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.