.TH "SBGravTideEOP_B_02::TableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBGravTideEOP_B_02::TableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBk\fP [6]"
.br
.ti -1c
.RI "double \fBSinX\fP"
.br
.ti -1c
.RI "double \fBCosX\fP"
.br
.ti -1c
.RI "double \fBSinY\fP"
.br
.ti -1c
.RI "double \fBCosY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1209 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBGravTideEOP_B_02::TableEntry::CosX\fP"
.PP
Definition at line 1212 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBGravTideEOP_B_02::calc()\&.
.SS "double \fBSBGravTideEOP_B_02::TableEntry::CosY\fP"
.PP
Definition at line 1212 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBGravTideEOP_B_02::calc()\&.
.SS "short \fBSBGravTideEOP_B_02::TableEntry::k\fP[6]"
.PP
Definition at line 1211 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBGravTideEOP_B_02::calc()\&.
.SS "double \fBSBGravTideEOP_B_02::TableEntry::SinX\fP"
.PP
Definition at line 1212 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBGravTideEOP_B_02::calc()\&.
.SS "double \fBSBGravTideEOP_B_02::TableEntry::SinY\fP"
.PP
Definition at line 1212 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBGravTideEOP_B_02::calc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
