SBHistoryLI
NAME
SBHistoryLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QListViewItem'.
Public Types
enum OType { DBH, LOCAL, UNKN }
Public Member Functions
SBHistoryLI (QListView *parent, OType Type_, SBHistory::SBHistoryEntry *HEntry_)
virtual QString ClassName () const
SBHistory::SBHistoryEntry * hEntry ()
OType type ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBHistory::SBHistoryEntry * HEntry
OType Type
Detailed Description
Definition at line 202 of file SbIObsVLBI.H'.
Member Enumeration Documentation
enum SBHistoryLI::OType
Enumerator:
DBH
LOCAL
UNKN
Definition at line 205 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBHistoryLI::SBHistoryLI (QListView *parent, OTypeType_, SBHistory::SBHistoryEntry *HEntry_) [inline]
Definition at line 210 of file SbIObsVLBI.H'.
References HEntry, and Type.
Member Function Documentation
virtual QString SBHistoryLI::ClassName () const [inline, virtual]
Definition at line 212 of file SbIObsVLBI.H'.
SBHistory::SBHistoryEntry* SBHistoryLI::hEntry () [inline]
Definition at line 213 of file SbIObsVLBI.H'.
References HEntry.
Referenced by SBBrowseHistory::deleteHistoryLine().
QString SBHistoryLI::key (intcol, bool) const [virtual]
Definition at line 937 of file SbIObsVLBI.C'.
References SBDated::date(), DBH, HEntry, SBHistory::SBHistoryEntry::text(), TmpString, Type, and SBHistory::SBHistoryEntry::version().
QString SBHistoryLI::text (intcol) const [virtual]
Definition at line 919 of file SbIObsVLBI.C'.
References SBDated::date(), DBH, SBMJD::F_Short, HEntry, SBHistory::SBHistoryEntry::text(), TmpString, Type, and SBHistory::SBHistoryEntry::version().
OType SBHistoryLI::type () [inline]
Definition at line 214 of file SbIObsVLBI.H'.
References Type.
Referenced by SBBrowseHistory::deleteHistoryLine().
Member Data Documentation
SBHistory::SBHistoryEntry* SBHistoryLI::HEntry [private]
Definition at line 207 of file SbIObsVLBI.H'.
Referenced by hEntry(), key(), SBHistoryLI(), and text().
OType SBHistoryLI::Type [private]
Definition at line 208 of file SbIObsVLBI.H'.
Referenced by key(), SBHistoryLI(), text(), and type().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.