SBHistory::SBHistoryEntry
NAME
SBHistory::SBHistoryEntry -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBDated'.
Public Member Functions
SBHistoryEntry (int Version_=0, const SBMJD &MJD_=TZero, const QString &Text_='')
const QString & text ()
int version ()
virtual QString ClassName () const
virtual double date () const
virtual void setDate (double d_)
virtual QString date2str ()
Protected Attributes
double Date
Private Attributes
int Version
Datafile's version when the entry was entered'.
QString Text
Text of the history line'.
Friends
QDataStream & operator<< (QDataStream &s, const SBHistoryEntry &E)
QDataStream & operator>> (QDataStream &s, SBHistoryEntry &E)
int compare_dated (SBDated *d1, SBDated *d2)
QDataStream & operator<< (QDataStream &s, const SBDated &D)
QDataStream & operator>> (QDataStream &s, SBDated &D)
Detailed Description
History entry'. Consist of date of creation, version and history text line'. The idea is stolen from MkIII DBH format'.
Definition at line 539 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBHistory::SBHistoryEntry::SBHistoryEntry (intVersion_ = 0, const SBMJD &MJD_ = TZero, const QString &Text_ = '') [inline]"A constructor'. Creates a copy of object'.
Parameters:
Version_ version;
MJD_ date of history;
Text_ text'.
Definition at line 550 of file SbGeoObsVLBI.H'.
References Text, and Version.
Member Function Documentation
virtual QString SBDated::ClassName () const [inline, virtual, inherited]
Definition at line 164 of file SbGeo.H'.
virtual double SBDated::date () const [inline, virtual, inherited]
Definition at line 166 of file SbGeo.H'.
References SBDated::Date.
Referenced by SBBrowseHistory::deleteHistoryLine(), SBHistoryLI::key(), and SBHistoryLI::text().
QString SBDated::date2str () [virtual, inherited]
Definition at line 35 of file SbGeo.C'.
References SBDated::Date.
virtual void SBDated::setDate (doubled_) [inline, virtual, inherited]
Definition at line 167 of file SbGeo.H'.
References SBDated::Date.
const QString& SBHistory::SBHistoryEntry::text () [inline]"Returns history's text'.
Definition at line 553 of file SbGeoObsVLBI.H'.
References Text.
Referenced by SBHistoryLI::key(), and SBHistoryLI::text().
int SBHistory::SBHistoryEntry::version () [inline]"Returns history's version'.
Definition at line 555 of file SbGeoObsVLBI.H'.
References Version.
Referenced by SBHistoryLI::key(), and SBHistoryLI::text().
Friends And Related Function Documentation
int compare_dated (SBDated *d1, SBDated *d2) [friend, inherited]
Definition at line 170 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBDated &D) [friend, inherited]
Definition at line 173 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBHistoryEntry &E) [friend]
Definition at line 556 of file SbGeoObsVLBI.H'.
QDataStream& operator>> (QDataStream &s, SBDated &D) [friend, inherited]
Definition at line 174 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBHistoryEntry &E) [friend]
Definition at line 558 of file SbGeoObsVLBI.H'.
Member Data Documentation
double SBDated::Date [protected, inherited]
Definition at line 158 of file SbGeo.H'.
Referenced by SBDated::date(), SBDated::date2str(), SBDated::SBDated(), and SBDated::setDate().
QString SBHistory::SBHistoryEntry::Text [private]
Text of the history line'.
Definition at line 542 of file SbGeoObsVLBI.H'.
Referenced by SBHistoryEntry(), and text().
int SBHistory::SBHistoryEntry::Version [private]
Datafile's version when the entry was entered'.
Definition at line 541 of file SbGeoObsVLBI.H'.
Referenced by SBHistoryEntry(), and version().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.