SBHistory
NAME
SBHistory -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBDList'.
Classes
class SBHistoryEntry
Public Member Functions
SBHistory ()
virtual QString ClassName () const
void addHistoryLine (int Version_, const QString &Text_, const SBMJD &MJD_=SBMJD::currentMJD())
Protected Member Functions
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
Detailed Description
History list'. Keeps sorted by date list of history entries SBHistory::SBHistoryEntry'.
Definition at line 532 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBHistory::SBHistory () [inline]"A constructor'. Creates a copy of object'.
Definition at line 572 of file SbGeoObsVLBI.H'.
Member Function Documentation
void SBHistory::addHistoryLine (intVersion_, const QString &Text_, const SBMJD &MJD_ = SBMJD::currentMJD()) [inline]"Adds a new history line'.
Parameters:
Version_ version;
Text_ text;
MJD_ date of creation, MJD (default is current system time)'.
Definition at line 582 of file SbGeoObsVLBI.H'.
Referenced by SBProject::addHistoryLine(), SBBrowseHistory::addHistoryLine(), and SBVLBISession::addHistoryLine().
virtual QString SBHistory::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Definition at line 574 of file SbGeoObsVLBI.H'.
virtual int SBDList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Definition at line 191 of file SbGeo.H'.
virtual QDataStream& SBHistory::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 565 of file SbGeoObsVLBI.H'.
virtual QDataStream& SBHistory::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 563 of file SbGeoObsVLBI.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.