SbIMainWin.C
NAME
SbIMainWin.C -
SYNOPSIS
#include 'SbIMainWin.H'
#include <unistd.h>
#include <qaccel.h>
#include <qapplication.h>
#include <qdatetime.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qfont.h>
#include <qfontdialog.h>
#include <qlabel.h>
#include <qlayout.h>
#include <qmenubar.h>
#include <qmessagebox.h>
#include <qpixmap.h>
#include <qpopupmenu.h>
#include <qprogressbar.h>
#include <qsplitter.h>
#include <qstatusbar.h>
#include <qmotifstyle.h>
#include <qwindowsstyle.h>
#include <qplatinumstyle.h>
#include <qcdestyle.h>
#include <qinterlacestyle.h>
#include <qmotifplusstyle.h>
#include <qsgistyle.h>
#include <qtoolbar.h>
#include <qtoolbutton.h>
#include <qtooltip.h>
#include <qwhatsthis.h>
#include 'SbSetup.H'
#include 'SbGeoEop.H'
#include 'SbGeoObsVLBIStat.H'
#include 'SbGeoProject.H'
#include 'SbISetup.H'
#include 'SbIStuff.H'
#include 'SbIStuffSource.H'
#include 'SbIStuffStation.H'
#include 'SbIObsVLBI.H'
#include 'SbISolution.H'
#include 'SbITest.H'
#include 'SbIProject.H'
#include 'SbIPreProcessing.H'
#include 'SbIObsVLBIStat.H'
#include 'SbIMEM.H'
#include 'SbIFilters.H'
#include 'xpm/Settings.xpm'
#include 'xpm/Exit.xpm'
#include 'xpm/Antenna.xpm'
#include 'xpm/Quasar.xpm'
#include 'xpm/Earth.xpm'
#include 'xpm/Database.xpm'
#include 'xpm/Stop.xpm'
#include 'xpm/Stop_disabled.xpm'
#include 'xpm/SrcStatusDefining.xpm'
#include 'xpm/SrcStatusCandidate.xpm'
#include 'xpm/SrcStatusOther.xpm'
#include 'xpm/SrcStatusNew.xpm'
#include 'xpm/SrcStatusUnknown.xpm'
#include 'xpm/SrcHLink.xpm'
Functions
void mainMessage (const QString &S)
void mainPrBarReset ()
void mainPrBarSetTotalSteps (int ts)
void mainPrBarSetProgress (int p)
void mainSetTRFName (const QString &S)
void mainSetCRFName (const QString &S)
void mainSetEOPName (const QString &S)
void mainSetPrjName (const QString &S)
void mainSetStatus (const QString &S)
void mainSetOperation (const QString &S)
void mainSetProcSes (int n, int Total)
void mainSetProcObs (int n, int Total)
void mainSetSessName (const QString &N_)
void mainSetCacheSizes (int nObs, int nSes, int nCRF, int nTRF)
Variables
SBMainWindow * MainWin
bool IsNeedToStop = FALSE
Function Documentation
void mainMessage (const QString &S)
Definition at line 1255 of file SbIMainWin.C'.
References SBMainWindow::setMessage().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::dumpUserInfo(), SBStuffEOPs::import(), SBEphem::import(), SBVLBISet::restoreUserInfo(), and SBStuffEOPs::showSeries().
void mainPrBarReset ()
Definition at line 1256 of file SbIMainWin.C'.
References SBMainWindow::stBarReset().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::dumpUserInfo(), SBStuffEOPs::import(), SBEphem::import(), and SBVLBISet::restoreUserInfo().
void mainPrBarSetProgress (intp)
Definition at line 1258 of file SbIMainWin.C'.
References SBMainWindow::stBarSetProgress().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::dumpUserInfo(), SBStuffEOPs::import(), SBEphem::import(), SBRunManager::process_m1(), SBRunManager::process_m2(), and SBVLBISet::restoreUserInfo().
void mainPrBarSetTotalSteps (intts)
Definition at line 1257 of file SbIMainWin.C'.
References SBMainWindow::stBarSetTotalSteps().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::dumpUserInfo(), SBStuffEOPs::import(), SBEphem::import(), SBRunManager::process_m1(), SBRunManager::process_m2(), and SBVLBISet::restoreUserInfo().
void mainSetCacheSizes (intnObs, intnSes, intnCRF, intnTRF)
Definition at line 1270 of file SbIMainWin.C'.
References SBMainWindow::setCacheSizes().
Referenced by SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SBRunManager::saveVLBISessions_m1(), and SBRunManager::saveVLBISessions_m2().
void mainSetCRFName (const QString &S)
Definition at line 1261 of file SbIMainWin.C'.
References SBMainWindow::setCRFName().
Referenced by SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), and SBSetUp::setSources().
void mainSetEOPName (const QString &S)
Definition at line 1262 of file SbIMainWin.C'.
References SBMainWindow::setEOPName().
Referenced by SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), and SBSetUp::setEOPs().
void mainSetOperation (const QString &S)
Definition at line 1266 of file SbIMainWin.C'.
References SBMainWindow::setOperation().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::dumpUserInfo(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTroposphere(), SBRunManager::prepare4Run_m1(), SBRunManager::prepare4Run_m2(), SBVLBISet::restoreUserInfo(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBRunManager::SBRunManager(), and SBSolutionBrowser::SBSolutionBrowser().
void mainSetPrjName (const QString &S)
Definition at line 1263 of file SbIMainWin.C'.
References SBMainWindow::setPrjName().
Referenced by SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), and SBSetUp::setProject().
void mainSetProcObs (intn, intTotal)
Definition at line 1268 of file SbIMainWin.C'.
References SBMainWindow::setProcObs().
Referenced by SBRunManager::process_m1(), and SBRunManager::process_m2().
void mainSetProcSes (intn, intTotal)
Definition at line 1267 of file SbIMainWin.C'.
References SBMainWindow::setProcSes().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::dumpUserInfo(), SBVLBISet::restoreUserInfo(), SBRunManager::saveVLBISessions_m1(), and SBRunManager::saveVLBISessions_m2().
void mainSetSessName (const QString &N_)
Definition at line 1269 of file SbIMainWin.C'.
References SBMainWindow::setSessName().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::dumpUserInfo(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SBRunManager::process_m1(), SBVLBISet::restoreUserInfo(), SBRunManager::saveVLBISessions_m1(), and SBRunManager::saveVLBISessions_m2().
void mainSetStatus (const QString &S)
Definition at line 1264 of file SbIMainWin.C'.
References SBMainWindow::setStatus().
void mainSetTRFName (const QString &S)
Definition at line 1260 of file SbIMainWin.C'.
References SBMainWindow::setTRFName().
Referenced by SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), and SBSetUp::setStations().
Variable Documentation
bool IsNeedToStop = FALSE
Definition at line 101 of file SbIMainWin.C'.
Referenced by SBMainWindow::ExecuteDoubleRunProj(), SBMainWindow::ExecuteRunProj(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBMainWindow::SBMainWindow(), and SBMainWindow::stopRunning().
SBMainWindow* MainWin
Definition at line 100 of file SbIMainWin.C'.
Referenced by SBProjectCreate::init(), SBVLBIPreProcess::init(), SBVLBISetView::init(), main(), SBStuffAplo::SBStuffAplo(), and SBStuffEphem::SBStuffEphem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.