.TH "SbInterface.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbInterface.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SbInterface\&.H'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <qapplication\&.h>\fP
.br
\fC#include <qtableview\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBTmpString\fP ('Temporary string')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QString TmpString ('Temporary string')"
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
