SBInstitutionList
NAME
SBInstitutionList -
SYNOPSIS
#include <SbGeo.H>
Inherits SBNList'.
Public Member Functions
SBInstitutionList ()
~SBInstitutionList ()
virtual SBInstitutionList & operator= (const SBInstitutionList &)
virtual QString ClassName () const
virtual SBInstitution * find (const QString &A_)
virtual bool insert (const QString &, const QString &)
virtual bool insert (const SBInstitution *)
virtual bool remove (const SBInstitution *)
virtual bool remove (const QString &)
bool isChanged () const
virtual QString descr (const QString &A_) const
Protected Member Functions
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
Protected Attributes
QDict< SBInstitution > * InstByAcronym
bool IsChanged
Friends
QDataStream & operator<< (QDataStream &, const SBInstitutionList &)
QDataStream & operator>> (QDataStream &, SBInstitutionList &)
Detailed Description
Definition at line 330 of file SbGeo.H'.
Constructor & Destructor Documentation
SBInstitutionList::SBInstitutionList ()
Definition at line 49 of file SbGeo.C'.
References InstByAcronym, and IsChanged.
SBInstitutionList::~SBInstitutionList ()
Definition at line 58 of file SbGeo.C'.
References InstByAcronym.
Member Function Documentation
virtual QString SBInstitutionList::ClassName () const [inline, virtual]
Definition at line 344 of file SbGeo.H'.
Referenced by insert(), and operator>>().
virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, and SBStationIDList'.
Definition at line 277 of file SbGeo.H'.
virtual QString SBInstitutionList::descr (const QString &A_) const [inline, virtual]
Definition at line 351 of file SbGeo.H'.
References SBInstitution::descr(), and InstByAcronym.
Referenced by SBSolutionName::Acronym2Str(), and operator=().
virtual SBInstitution* SBInstitutionList::find (const QString &A_) [inline, virtual]
Definition at line 345 of file SbGeo.H'.
References InstByAcronym.
Referenced by SBSetupDialog::addInst(), insert(), operator>>(), and remove().
bool SBInstitutionList::insert (const QString &A_, const QString &D_) [virtual]
Definition at line 79 of file SbGeo.C'.
References ClassName(), SBLog::CONFIG, SBLog::ERR, find(), InstByAcronym, SBLog::IO, IsChanged, Log, SBNamed::name(), and SBLog::write().
Referenced by SBSetupDialog::addInst(), and operator=().
bool SBInstitutionList::insert (const SBInstitution *W) [virtual]
Definition at line 97 of file SbGeo.C'.
References ClassName(), SBLog::CONFIG, SBLog::ERR, find(), InstByAcronym, SBLog::IO, IsChanged, Log, SBNamed::name(), and SBLog::write().
bool SBInstitutionList::isChanged () const [inline]
Definition at line 350 of file SbGeo.H'.
References IsChanged.
Referenced by SBSetUp::SaveStuff().
SBInstitutionList & SBInstitutionList::operator= (const SBInstitutionList &L) [virtual]
Definition at line 63 of file SbGeo.C'.
References descr(), insert(), InstByAcronym, and IsChanged.
virtual QDataStream& SBInstitutionList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 336 of file SbGeo.H'.
bool SBInstitutionList::remove (const SBInstitution *W) [virtual]
Definition at line 113 of file SbGeo.C'.
References InstByAcronym, IsChanged, and SBNamed::name().
Referenced by SBSetupDialog::delInst().
bool SBInstitutionList::remove (const QString &A) [virtual]
Definition at line 119 of file SbGeo.C'.
References find(), InstByAcronym, IsChanged, and SBNamed::name().
virtual QDataStream& SBInstitutionList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 334 of file SbGeo.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBInstitutionList &L) [friend]
Definition at line 135 of file SbGeo.C'.
QDataStream& operator>> (QDataStream &s, SBInstitutionList &L) [friend]
Definition at line 140 of file SbGeo.C'.
Member Data Documentation
QDict<SBInstitution>* SBInstitutionList::InstByAcronym [protected]
Definition at line 337 of file SbGeo.H'.
Referenced by descr(), find(), insert(), operator=(), operator>>(), remove(), SBInstitutionList(), and ~SBInstitutionList().
bool SBInstitutionList::IsChanged [protected]
Definition at line 339 of file SbGeo.H'.
Referenced by insert(), isChanged(), operator=(), operator>>(), remove(), and SBInstitutionList().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.