.TH "SbIPlot.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbIPlot.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <qbuttongroup\&.h>\fP
.br
\fC#include <qcombobox\&.h>\fP
.br
\fC#include <qcheckbox\&.h>\fP
.br
\fC#include <qfile\&.h>\fP
.br
\fC#include <qgroupbox\&.h>\fP
.br
\fC#include <qlabel\&.h>\fP
.br
\fC#include <qlayout\&.h>\fP
.br
\fC#include <qlistbox\&.h>\fP
.br
\fC#include <qpaintdevicemetrics\&.h>\fP
.br
\fC#include <qprinter\&.h>\fP
.br
\fC#include <qpushbutton\&.h>\fP
.br
\fC#include <qslider\&.h>\fP
.br
\fC#include <qtextstream\&.h>\fP
.br
\fC#include 'SbIPlot\&.H'\fP
.br
\fC#include 'SbSetup\&.H'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
