SBListView
NAME
SBListView -
SYNOPSIS
#include <SbInterface.H>
Inherits QListView'.
Signals
void moveUponItem (QListViewItem *, int)
void selChanged4Item (QListViewItem *, bool)
Public Member Functions
SBListView (QWidget *=0, const char *=0)
virtual void setSelected (QListViewItem *, bool)
Protected Member Functions
void contentsMouseMoveEvent (QMouseEvent *)
void contentsMouseReleaseEvent (QMouseEvent *)
Private Slots
void movingStarted (QListViewItem *, const QPoint &, int)
Private Attributes
bool IsMoving
int MCol
QListViewItem * MItem
Detailed Description
Definition at line 102 of file SbInterface.H'.
Constructor & Destructor Documentation
SBListView::SBListView (QWidget *parent = 0, const char *name = 0)
Definition at line 86 of file SbInterface.C'.
References IsMoving, MCol, MItem, and movingStarted().
Member Function Documentation
void SBListView::contentsMouseMoveEvent (QMouseEvent *e) [protected]
Definition at line 115 of file SbInterface.C'.
References IsMoving, MCol, MItem, and moveUponItem().
void SBListView::contentsMouseReleaseEvent (QMouseEvent *e) [protected]
Definition at line 130 of file SbInterface.C'.
References IsMoving, MCol, and MItem.
void SBListView::moveUponItem (QListViewItem *t0, intt1) [signal]
Definition at line 176 of file SbInterface.moc.C'.
Referenced by contentsMouseMoveEvent(), and movingStarted().
void SBListView::movingStarted (QListViewItem *item, const QPoint &, intc) [private, slot]
Definition at line 104 of file SbInterface.C'.
References IsMoving, MCol, MItem, and moveUponItem().
Referenced by SBListView().
void SBListView::selChanged4Item (QListViewItem *t0, boolt1) [signal]
Definition at line 225 of file SbInterface.moc.C'.
Referenced by setSelected().
void SBListView::setSelected (QListViewItem *item, boolselected) [virtual]
Definition at line 98 of file SbInterface.C'.
References selChanged4Item().
Member Data Documentation
bool SBListView::IsMoving [private]
Definition at line 111 of file SbInterface.H'.
Referenced by contentsMouseMoveEvent(), contentsMouseReleaseEvent(), movingStarted(), and SBListView().
int SBListView::MCol [private]
Definition at line 112 of file SbInterface.H'.
Referenced by contentsMouseMoveEvent(), contentsMouseReleaseEvent(), movingStarted(), and SBListView().
QListViewItem* SBListView::MItem [private]
Definition at line 113 of file SbInterface.H'.
Referenced by contentsMouseMoveEvent(), contentsMouseReleaseEvent(), movingStarted(), and SBListView().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.