SBLogger
NAME
SBLogger -
SYNOPSIS
#include <SbInterface.H>
Inherits SBLog, and QMultiLineEdit'.
Public Types
enum LogLevel { ERR, WRN, INF, DBG }
enum LogFacility { IO = 1<< 0, DATA = 1<< 1, TIME = 1<< 2, PRECESSION = 1<< 3, NUTATION = 1<< 4, R3 = 1<< 5, PMOTION = 1<< 6, PINTERP = 1<< 7, TIDES = 1<< 8, AXISOFF = 1<< 9, PLATES = 1<<10, REFRACT = 1<<11, GRAVDELAY = 1<<12, DELAYALL = 1<<13, EPHEM = 1<<14, ESTIMATOR = 1<<15, CONFIG = 1<<16, INTERFACE = 1<<17, SOURCE = 1<<18, STATION = 1<<19, MATRIX3D = 1<<20, MATRIX = 1<<21, RUN = 1<<22, STOCHPARS = 1<<23, SPLINE = 1<<24, PREPROC = 1<<25, RES_07 = 1<<26, RES_08 = 1<<27, RES_09 = 1<<28, RES_10 = 1<<29, TEST = 1<<30, TEMPORARY = 1<<31 }
Public Member Functions
SBLogger (QWidget *, int=100, bool=TRUE, const QString &='stbreeze.log', const char *=0)
~SBLogger ()
virtual void startUp ()
virtual void clearSpool ()
virtual void write (LogLevel, uint, const QString &, bool=FALSE)
virtual bool isEligible (LogLevel Level_, uint Facility_)
virtual bool isEligible (LogLevel Lvl, uint F) const
virtual void setLogFileName (const QString &Tmp)
virtual void setCapacity (int Tmp)
virtual void setStoreInFile (bool isTmp)
virtual void setTimeLabel (bool isTmp)
virtual void setLogFacilities (LogLevel Lvl, uint Tmp)
virtual const QString & fileName () const
virtual int capacity () const
virtual bool isStoreInFile () const
virtual bool isTimeLabel () const
virtual uint logFacilities (LogLevel Lvl) const
virtual void addLogFacility (LogLevel Lvl, uint Tmp)
virtual void rmLogFacility (LogLevel Lvl, uint Tmp)
Protected Member Functions
virtual QString ClassName () const
virtual void MakeOutput (const QString &, bool)
virtual void ClearSpool ()
Protected Attributes
bool IsStoreInFile
bool IsTimeLabel
QString FileName
QString TmpStr
QList< QString > Spool
uint LogFacilities [4]
uint Capacity
Detailed Description
Definition at line 49 of file SbInterface.H'.
Member Enumeration Documentation
enum SBLog::LogFacility [inherited]
Enumerator:
IO
DATA
TIME
PRECESSION
NUTATION
R3
PMOTION
PINTERP
TIDES
AXISOFF
PLATES
REFRACT
GRAVDELAY
DELAYALL
EPHEM
ESTIMATOR
CONFIG
INTERFACE
SOURCE
STATION
MATRIX3D
MATRIX
RUN
STOCHPARS
SPLINE
PREPROC
RES_07
RES_08
RES_09
RES_10
TEST
TEMPORARY
Definition at line 80 of file SbGeneral.H'.
enum SBLog::LogLevel [inherited]
Enumerator:
ERR
WRN
INF
DBG
Definition at line 73 of file SbGeneral.H'.
Constructor & Destructor Documentation
SBLogger::SBLogger (QWidget *parent, intCapacity_ = 100, boolisStoreInFile_ = TRUE, const QString &FileName_ = 'stbreeze.log', const char *name = 0)
Definition at line 41 of file SbInterface.C'.
SBLogger::~SBLogger () [inline]
Definition at line 53 of file SbInterface.H'.
Member Function Documentation
virtual void SBLog::addLogFacility (LogLevelLvl, uintTmp) [inline, virtual, inherited]
Definition at line 149 of file SbGeneral.H'.
References SBLog::LogFacilities.
virtual int SBLog::capacity () const [inline, virtual, inherited]
Definition at line 144 of file SbGeneral.H'.
References SBLog::Capacity.
virtual QString SBLogger::ClassName () const [inline, protected, virtual]
Reimplemented from SBLog'.
Definition at line 55 of file SbInterface.H'.
Referenced by ClearSpool().
void SBLogger::ClearSpool () [protected, virtual]
Definition at line 65 of file SbInterface.C'.
References SBLog::Capacity, ClassName(), SBLog::clearSpool(), SBLog::DBG, SBLog::IO, Log, and SBLog::write().
void SBLog::clearSpool () [virtual, inherited]
Definition at line 90 of file SbGeneral.C'.
References SBLog::FileName, SBLog::IsStoreInFile, and SBLog::Spool.
Referenced by ClearSpool(), SBMainWindow::ControlFlushLog(), SBLog::write(), and SBLog::~SBLog().
virtual const QString& SBLog::fileName () const [inline, virtual, inherited]
Definition at line 143 of file SbGeneral.H'.
References SBLog::FileName.
virtual bool SBLog::isEligible (LogLevelLevel_, uintFacility_) [inline, virtual, inherited]
Definition at line 134 of file SbGeneral.H'.
References SBLog::LogFacilities.
Referenced by SBStation::axisOffsetLenght(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBStation::calcDisplacement(), SBPlateMotion::displacement(), SBAploEphem::displacement(), SBEOP::interpolateEOPs(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), SBParameterList::report(), SBStochParameter::report(), SBTime::setUTC(), and SBPlateMotion::velocity().
virtual bool SBLog::isEligible (LogLevelLvl, uintF) const [inline, virtual, inherited]
Definition at line 147 of file SbGeneral.H'.
References SBLog::LogFacilities.
virtual bool SBLog::isStoreInFile () const [inline, virtual, inherited]
Definition at line 145 of file SbGeneral.H'.
References SBLog::IsStoreInFile.
virtual bool SBLog::isTimeLabel () const [inline, virtual, inherited]
Definition at line 146 of file SbGeneral.H'.
References SBLog::IsTimeLabel.
virtual uint SBLog::logFacilities (LogLevelLvl) const [inline, virtual, inherited]
Definition at line 148 of file SbGeneral.H'.
References SBLog::LogFacilities.
Referenced by SBRunManager::process_m1().
void SBLogger::MakeOutput (const QString &s, boolIsAsync) [protected, virtual]
Reimplemented from SBLog'.
Definition at line 49 of file SbInterface.C'.
virtual void SBLog::rmLogFacility (LogLevelLvl, uintTmp) [inline, virtual, inherited]
Definition at line 150 of file SbGeneral.H'.
References SBLog::LogFacilities.
virtual void SBLog::setCapacity (intTmp) [inline, virtual, inherited]
Definition at line 138 of file SbGeneral.H'.
References SBLog::Capacity.
Referenced by SBSetUp::UpdateLogger().
virtual void SBLog::setLogFacilities (LogLevelLvl, uintTmp) [inline, virtual, inherited]
Definition at line 141 of file SbGeneral.H'.
References SBLog::LogFacilities.
Referenced by SBRunManager::process_m1(), and SBSetUp::UpdateLogger().
virtual void SBLog::setLogFileName (const QString &Tmp) [inline, virtual, inherited]
Definition at line 137 of file SbGeneral.H'.
References SBLog::FileName.
Referenced by SBSetUp::UpdateLogger().
virtual void SBLog::setStoreInFile (boolisTmp) [inline, virtual, inherited]
Definition at line 139 of file SbGeneral.H'.
References SBLog::IsStoreInFile.
Referenced by SBSetUp::UpdateLogger().
virtual void SBLog::setTimeLabel (boolisTmp) [inline, virtual, inherited]
Definition at line 140 of file SbGeneral.H'.
References SBLog::IsTimeLabel.
Referenced by SBSetUp::UpdateLogger().
void SBLog::startUp () [virtual, inherited]
Definition at line 58 of file SbGeneral.C'.
References SBLog::Capacity, SBLog::ClassName(), SBLog::DBG, SBLog::FileName, SBLog::IO, SBLog::IsStoreInFile, and SBLog::write().
void SBLog::write (LogLevelLevel, uintFacility, const QString &s, boolIsAsync = FALSE) [virtual, inherited]
Definition at line 71 of file SbGeneral.C'.
References SBLog::Capacity, SBLog::clearSpool(), SBLog::IsTimeLabel, SBLog::LogFacilities, SBLog::MakeOutput(), SBLog::Spool, and SBLog::TmpStr.
Referenced by SBSourceImport::accept(), SBStationImport::accept(), SBAliasEditor::accept(), SBVLBINetworkEditor::addEntry(), SBStochParameter::addPar(), SBProjectEdit::addSession(), SBProject::addSession(), SBSite::addStation(), SBFilterModel::analyseSeries(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBStuffStations::browseEcc(), SBVLBISetView::browseMRecords(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBStation::calcDisplacement(), SBEphem::calcI(), SBFilteringGauss::calcSigmas(), SBFileConv::check(), SBSetUp::CheckDir(), SBAploEphem::checkEphem(), SBSpectrumAnalyserMEM::checkLine(), SBRunManager::checkParameterLists(), SBVLBISesInfo::checkPath(), SBSolution::checkPath(), SBEOP::checkRanges(), SBDataSeries::checkRecords(), SBVLBIPreProcess::clearPars(), ClearSpool(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBMainWindow::ControlConfigure(), SBMainWindow::ControlDefault(), SBMainWindow::ControlFlushLog(), SBMainWindow::ControlSelectFont(), SBMEM::createAuxVectors(), SBVLBIPreProcess::currentSesChange(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), SBStationEditor::delCoordinates(), SBStuffStationsEcc::deleteEntry(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBVLBINetworkEditor::deleteEntry(), SBStaParsEditor::deleteEntry(), SBStuffSources::deleteEntryA(), SBStuffStations::deleteEntryA(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBBrowseHistory::deleteHistoryLine(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBEOP::dEps(), SBPlateMotion::displacement(), SBAploEphem::displacement(), SBEOP::dLOD(), SBEOP::dPsi(), SBStuffEOPs::draw(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBVLBISession::dumpUserInfo(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBProjectCreate::editEntry(), SBStuffStationsEcc::editEntry(), SBSiteEditor::editEntry(), SBVLBISetView::editEntry(), SBVLBINetworkEditor::editEntry(), SBStuffSources::editEntryA(), SBStuffStations::editEntryA(), SBStuffSources::editEntryS(), SBStuffStations::editEntryS(), SBVLBISetView::editNetworks(), SBMainWindow::ExecuteBrowseSolution(), SBMainWindow::ExecuteDoubleRunProj(), SBMainWindow::ExecuteDrop(), SBMainWindow::ExecuteEditProj(), SBMainWindow::ExecuteGenProj(), SBMainWindow::ExecuteModels(), SBMainWindow::ExecuteParameters(), SBMainWindow::ExecuteReportProj(), SBMainWindow::ExecuteRunProj(), SBMainWindow::ExecuteSelProj(), SBStuffSources::exportData(), SBStuffStations::exportData(), SBProject::fillBaseDict(), SBAploChunk::fillDict(), SBVLBISession::fillDicts(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBProject::fillSessionDict(), SBProject::fillSourceDict(), SBProject::fillStationDict(), SBEcc::findEcc(), SBDBHFormat::getBlock(), SBAploEphem::getReady(), handlerSIGs(), SBMainWindow::HelpAbout(), SBMainWindow::HelpAboutQt(), SBMainWindow::HelpHelp(), SBEphem::import(), SBAploChunk::import(), SBVLBISetView::import(), SBVLBISet::import(), SBStuffSources::importData(), SBStuffStations::importData(), SBStuffStationsEcc::importData(), SBEcc::importEccDat(), SBSrcMap::importFITS(), SBAploEphem::importHPS(), SBSourceImport::importICRF(), SBStationImport::importITRF(), SBMaster::importMF(), SBEOP::importSeries(), SBEphem::initData(), SBFCList::insert(), SBInstitutionList::insert(), SBStuffStationsEcc::insertEntry(), SBSiteEditor::insertEntry(), SBStuffSources::insertEntryA(), SBStuffStations::insertEntryA(), SBStuffSources::insertEntryS(), SBStuffStations::insertEntryS(), SBEstimator::GroupList::inSort(), SBParameterList::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBEOP::interpolateEOPs(), SBFilterModel::isCanRun(), SBObsVLBIEntry::isEligible(), SBDBHLRecPrefixed::isPrefixParsed(), SBSetUp::loadAploEphem(), SBSetUp::LoadConfig(), SBSetUp::loadCRF(), SBStationImport::loadECCdat(), SBSetUp::loadEOP(), SBStationImport::loadFile1994(), SBSourceImport::loadFile1995(), SBStationImport::loadFile2000(), SBSolution::loadGlbCor(), SBSolution::loadGlbPar(), SBSolution::loadLocCor(), SBSolution::loadLocPar(), SBSolution::loadNormalEqs(), SBStationImport::loadNScodes(), SBSetUp::loadObsVLBIStatistics(), SBStationImport::loadOLoad(), SBSetUp::loadProject(), SBVLBISet::loadSession(), SBSolution::loadStatistics(), SBSolution::loadStcPar(), SBSetUp::LoadStuff(), SBSetUp::loadTRF(), SBSetUp::loadVLBI(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SB_TRF::lookupStation(), SBSpectrumAnalyserMEM::makeAnalysis(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSetupDialog::makeApply(), SBProjectEdit::makeApply(), SBModelEditor::makeApply(), SBSourceEditor::makeApply(), SBParametersEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBVLBISessionEditor::makeApply(), SBModelEditor::makeDefault(), SBParametersEditor::makeDefault(), SBParEditor::makeDefault(), SBSetupDialog::makeDefaults(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTechDescription(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), SBVector::operator()(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVector::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBVLBISession::parseObsDumpString(), SBDBHFormat::postRead(), SBEOP::prepare4Date(), SBEstimator::prepare4Local(), SBRunManager::prepare4Run_m1(), SBRunManager::prepare4Run_m2(), SBSpline::prepare4Spline(), SB_CRF::prepareAliases4Output(), SBSite::prepareDicts(), SB_TRF::prepareEccs4Session(), SBFilterGauss::prepareModels(), SBMEM::prepareSpectrum(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), QuadraticForm(), SBFilteringGauss::readDataFile(), SBSpectrumAnalyserMEM::readDataFile(), SBMEM::readDataFile(), SBFilterGauss::readDataFile(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBRefraction::refrDir(), SBStationEcc::registerEcc(), SBEcc::registerEcc(), SBAploEphem::registerStation(), SBEstimator::GroupList::remove(), SBProjectSel::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBStochParameterList::report(), Vector3::report2Log(), Matrix3::report2Log(), SBStationInfo::restoreUserInfo(), SBStationInfoList::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBBaseInfoList::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBSetUp::saveAploEphem(), SBAploEphem::saveChunk(), SBSetUp::SaveConfig(), SBSetUp::saveCRF(), SBSetUp::saveEOP(), SBSolution::saveGlbCor(), SBSolution::saveGlbPar(), SBSolution::saveLocCor(), SBSolution::saveLocPar(), SBSolution::saveNormalEqs(), SBSetUp::saveObsVLBIStatistics(), SBSetUp::saveProject(), SBVLBISet::saveSession(), SBSolution::saveStatistics(), SBSolution::saveStcPar(), SBSetUp::SaveStuff(), SBSetUp::saveTRF(), SBSetUp::saveVLBI(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCablesBrowser::SBCablesBrowser(), SBEstimator::SBEstimator(), SBMainWindow::SBMainWindow(), SBPlot::SBPlot(), SBPolus::SBPolus(), SBPolusNRO::SBPolusNRO(), SBPrecNutNRO::SBPrecNutNRO(), SBProjectSel::SBProjectSel(), SBRunManager::SBRunManager(), SBSetUp::SBSetUp(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBSpline::SBSpline(), SBVLBISessionEditor::SBVLBISessionEditor(), SBSpectrumAnalyserMEM::scan4FPE(), SBPlotCarrier::selfCheck(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBMJD::setMJD(), SBFilterModel::setTermToKeep(), SBTime::setUTC(), SBMatrix::setVector(), SBUpperMatrix::setVector(), sinex_SiteIDBlock(), sinex_SolutionEpochsBlock(), sinex_SourceIDBlock(), sinex_tro_SiteIDBlock(), sinex_tro_StaCoordinatesBlock(), sinex_tro_TropSolutionBlock(), Solve(), SBEstimator::solveGlobals(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), SBObsVLBIEntry::source(), SBSpline::spline(), SBLog::startUp(), SBObsVLBIEntry::station1(), SBObsVLBIEntry::station2(), SBRunManager::stripCRF(), SBRunManager::stripTRF(), SBMainWindow::StuffAplo(), SBMainWindow::StuffEccenticities(), SBMainWindow::StuffEOPs(), SBMainWindow::StuffEphemerides(), SBMainWindow::StuffModels(), SBMainWindow::StuffModelsNutEps(), SBMainWindow::StuffModelsNutPsi(), SBMainWindow::StuffModelsPolDiurn(), SBMainWindow::StuffModelsUT1Diurn(), SBMainWindow::StuffModelsUT1High(), SBMainWindow::StuffModelsUT1Low(), SBMainWindow::StuffPlateMotion(), SBMainWindow::StuffSources(), SBMainWindow::StuffStations(), SBMainWindow::StuffVLBIObs(), SBFilterGauss::substractFilter(), SBMainWindow::TestAplo(), SBMainWindow::TestDiurnalEOPs(), SBMainWindow::TestEOPs(), SBMainWindow::TestEphemerides(), SBMainWindow::TestJustATest(), SBMainWindow::TestNutation(), SBMainWindow::TestOceanTide(), SBMainWindow::TestPoleTide(), SBMainWindow::TestPrecession(), SBMainWindow::TestRotation(), SBMainWindow::TestSolidTide(), SBParameter::update(), SBStochParameter::update(), SBSolutionBrowser::updateCRF(), SBParameterList::updateSolution(), SBSolutionBrowser::updateTRF(), SBMainWindow::UtilitiesBrowseStat4All(), SBMainWindow::UtilitiesBrowseStat4Prj(), SBMainWindow::UtilitiesCollectStat4All(), SBMainWindow::UtilitiesCollectStat4Prj(), SBMainWindow::UtilitiesDumpUI(), SBMainWindow::UtilitiesFilters(), SBMainWindow::UtilitiesPreProc(), SBMainWindow::UtilitiesRestoreUI(), SBMainWindow::UtilitiesSpectrum(), SBPlateMotion::velocity(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBVLBISessionEditor::wObservs(), writeNormalEquationSystem(), SBFilteringGauss::wrote2File(), SBEphem::~SBEphem(), and SBEstimator::~SBEstimator().
Member Data Documentation
uint SBLog::Capacity [protected, inherited]
Definition at line 124 of file SbGeneral.H'.
Referenced by SBLog::capacity(), ClearSpool(), SBLog::SBLog(), SBLog::setCapacity(), SBLog::startUp(), and SBLog::write().
QString SBLog::FileName [protected, inherited]
Definition at line 120 of file SbGeneral.H'.
Referenced by SBLog::clearSpool(), SBLog::fileName(), SBLog::SBLog(), SBLog::setLogFileName(), and SBLog::startUp().
bool SBLog::IsStoreInFile [protected, inherited]
Definition at line 118 of file SbGeneral.H'.
Referenced by SBLog::clearSpool(), SBLog::isStoreInFile(), SBLog::SBLog(), SBLog::setStoreInFile(), and SBLog::startUp().
bool SBLog::IsTimeLabel [protected, inherited]
Definition at line 119 of file SbGeneral.H'.
Referenced by SBLog::isTimeLabel(), SBLog::SBLog(), SBLog::setTimeLabel(), and SBLog::write().
uint SBLog::LogFacilities[4] [protected, inherited]
Definition at line 123 of file SbGeneral.H'.
Referenced by SBLog::addLogFacility(), SBLog::isEligible(), SBLog::logFacilities(), SBLog::rmLogFacility(), SBLog::SBLog(), SBLog::setLogFacilities(), and SBLog::write().
QList<QString> SBLog::Spool [protected, inherited]
Definition at line 122 of file SbGeneral.H'.
Referenced by SBLog::clearSpool(), SBLog::SBLog(), and SBLog::write().
QString SBLog::TmpStr [protected, inherited]
Definition at line 121 of file SbGeneral.H'.
Referenced by SBLog::write().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.