.TH "SbMathFilters.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbMathFilters.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SbMathFilters\&.H'\fP
.br
\fC#include <qfile\&.h>\fP
.br
\fC#include <qmessagebox\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBmakeHouseholder\fP (\fBSBUpperMatrix\fP *R, \fBSBVector\fP *Z, \fBSBMatrix\fP *AObs, \fBSBVector\fP *ZObs, unsigned int NumOfData)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double makeHouseholder (\fBSBUpperMatrix\fP *R, \fBSBVector\fP *Z, \fBSBMatrix\fP *AObs, \fBSBVector\fP *ZObs, unsigned intNumOfData)"
.PP
Definition at line 35 of file SbMathFilters\&.C'\&.
.PP
References SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBVector::clear(), SBUpperMatrix::n(), SBMatrix::nRow(), SBVector::set(), SBUpperMatrix::set(), and sign()\&.
.PP
Referenced by SBFilterModel::analyseSeries()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
