SbMathDataSeries.C
NAME
SbMathDataSeries.C -
SYNOPSIS
#include 'SbMathDataSeries.H'
Functions
QTextStream & operator<< (QTextStream &s, const SBDataSeriesEntry &entry)
QTextStream & operator>> (QTextStream &s, SBDataSeriesEntry &entry)
QTextStream & operator<< (QTextStream &s, const SBDataSeries &series)
QTextStream & operator>> (QTextStream &s, SBDataSeries &series)
Function Documentation
QTextStream& operator<< (QTextStream &s, const SBDataSeriesEntry &entry)
Definition at line 35 of file SbMathDataSeries.C'.
References SBVector::at(), SBDataSeriesEntry::Data, SBVector::n(), and SBDataSeriesEntry::T.
QTextStream& operator<< (QTextStream &s, const SBDataSeries &series)
Definition at line 231 of file SbMathDataSeries.C'.
QTextStream& operator>> (QTextStream &s, SBDataSeriesEntry &entry)
Definition at line 48 of file SbMathDataSeries.C'.
References SBDataSeriesEntry::Data, SBDataSeriesEntry::IsReadOK, SBVector::set(), and SBDataSeriesEntry::T.
QTextStream& operator>> (QTextStream &s, SBDataSeries &series)
Definition at line 242 of file SbMathDataSeries.C'.
References SBDataSeries::checkRecords().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.