SBMasterRecBrowser::SBMRListItem
NAME
SBMasterRecBrowser::SBMRListItem -
SYNOPSIS
Inherits QListViewItem'.
Public Member Functions
SBMRListItem (QListView *parent, SBMasterRecord *R_, const QString &MFName_)
virtual QString text (int) const
virtual QString key (int, bool) const
SBMasterRecord * record ()
Private Attributes
SBMasterRecord * Rec
QString MFName
Detailed Description
Definition at line 698 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBMasterRecBrowser::SBMRListItem::SBMRListItem (QListView *parent, SBMasterRecord *R_, const QString &MFName_) [inline]
Definition at line 704 of file SbIObsVLBI.H'.
References MFName, and Rec.
Member Function Documentation
QString SBMasterRecBrowser::SBMRListItem::key (intcol, bool) const [virtual]
Definition at line 3129 of file SbIObsVLBI.C'.
References SBMasterRecord::Exists, and TmpString.
SBMasterRecord* SBMasterRecBrowser::SBMRListItem::record () [inline]
Definition at line 708 of file SbIObsVLBI.H'.
References Rec.
QString SBMasterRecBrowser::SBMRListItem::text (intcol) const [virtual]
Definition at line 3103 of file SbIObsVLBI.C'.
References SBMasterRecord::correlatorName(), SBMasterRecord::Exists, SBAttributed::isAttr(), MFName, SBNamed::name(), Rec, SBMasterRecord::sessionCode(), SBMasterRecord::sessionDate(), SBMasterRecord::sessionName(), and TmpString.
Member Data Documentation
QString SBMasterRecBrowser::SBMRListItem::MFName [private]
Definition at line 702 of file SbIObsVLBI.H'.
Referenced by SBMRListItem(), and text().
SBMasterRecord* SBMasterRecBrowser::SBMRListItem::Rec [private]
Definition at line 701 of file SbIObsVLBI.H'.
Referenced by record(), SBMRListItem(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.