SbMathFilters.C
NAME
SbMathFilters.C -
SYNOPSIS
#include 'SbMathFilters.H'
#include <qfile.h>
#include <qmessagebox.h>
Functions
double makeHouseholder (SBUpperMatrix *R, SBVector *Z, SBMatrix *AObs, SBVector *ZObs, unsigned int NumOfData)
Function Documentation
double makeHouseholder (SBUpperMatrix *R, SBVector *Z, SBMatrix *AObs, SBVector *ZObs, unsigned intNumOfData)
Definition at line 35 of file SbMathFilters.C'.
References SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBVector::clear(), SBUpperMatrix::n(), SBMatrix::nRow(), SBVector::set(), SBUpperMatrix::set(), and sign().
Referenced by SBFilterModel::analyseSeries().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.