.TH "SBMasterRecBrowser" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBMasterRecBrowser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBI\&.H>\fP
.PP
Inherits \fBQDialog\fP'\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSBMRListItem\fP"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmasterRecordModified\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBMasterRecBrowser\fP (\fBSBVLBISet\fP *, \fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "\fB~SBMasterRecBrowser\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.ti -1c
.RI "void \fBreject\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBVLBISet\fP * \fBVLBI\fP"
.br
.ti -1c
.RI "\fBSBMaster\fP * \fBMaster\fP"
.br
.ti -1c
.RI "\fBQListView\fP * \fBMRecLV\fP"
.br
.ti -1c
.RI "bool \fBisModified\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 679 of file SbIObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBMasterRecBrowser::SBMasterRecBrowser (\fBSBVLBISet\fP *W_, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 3164 of file SbIObsVLBI\&.C'\&.
.PP
References accept(), SBMasterRecord::Exists, isModified, SBVLBISet::loadMaster(), Master, SBVLBISet::master(), MRecLV, reject(), SBVLBISet::sessionInfo(), and VLBI\&.
.SS "SBMasterRecBrowser::~SBMasterRecBrowser ()"
.PP
Definition at line 3239 of file SbIObsVLBI\&.C'\&.
.PP
References isModified, masterRecordModified(), SBVLBISet::releaseMaster(), and VLBI\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBMasterRecBrowser::accept ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 693 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBMasterRecBrowser()\&.
.SS "virtual QString SBMasterRecBrowser::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 685 of file SbIObsVLBI\&.H'\&.
.SS "virtual void SBMasterRecBrowser::closeEvent (QCloseEvent)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 719 of file SbIObsVLBI\&.H'\&.
.SS "void SBMasterRecBrowser::masterRecordModified (boolt0)\fC [signal]\fP"
.PP
Definition at line 1197 of file SbIObsVLBI\&.moc\&.C'\&.
.PP
Referenced by ~SBMasterRecBrowser()\&.
.SS "void SBMasterRecBrowser::reject ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 694 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBMasterRecBrowser()\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSBMasterRecBrowser::isModified\fP\fC [private]\fP"
.PP
Definition at line 716 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBMasterRecBrowser(), and ~SBMasterRecBrowser()\&.
.SS "\fBSBMaster\fP* \fBSBMasterRecBrowser::Master\fP\fC [private]\fP"
.PP
Definition at line 712 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBMasterRecBrowser()\&.
.SS "\fBQListView\fP* \fBSBMasterRecBrowser::MRecLV\fP\fC [private]\fP"
.PP
Definition at line 714 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBMasterRecBrowser()\&.
.SS "\fBSBVLBISet\fP* \fBSBMasterRecBrowser::VLBI\fP\fC [private]\fP"
.PP
Definition at line 711 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBMasterRecBrowser(), and ~SBMasterRecBrowser()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
