.TH "SbMathDataSeries.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SbMathDataSeries.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SbMathDataSeries\&.H'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator<<\fP (\fBQTextStream\fP &s, const \fBSBDataSeriesEntry\fP &entry)"
.br
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator>>\fP (\fBQTextStream\fP &s, \fBSBDataSeriesEntry\fP &entry)"
.br
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator<<\fP (\fBQTextStream\fP &s, const \fBSBDataSeries\fP &series)"
.br
.ti -1c
.RI "\fBQTextStream\fP & \fBoperator>>\fP (\fBQTextStream\fP &s, \fBSBDataSeries\fP &series)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBQTextStream\fP& operator<< (\fBQTextStream\fP &s, const \fBSBDataSeriesEntry\fP &entry)"
.PP
Definition at line 35 of file SbMathDataSeries\&.C'\&.
.PP
References SBVector::at(), SBDataSeriesEntry::Data, SBVector::n(), and SBDataSeriesEntry::T\&.
.SS "\fBQTextStream\fP& operator<< (\fBQTextStream\fP &s, const \fBSBDataSeries\fP &series)"
.PP
Definition at line 231 of file SbMathDataSeries\&.C'\&.
.SS "\fBQTextStream\fP& operator>> (\fBQTextStream\fP &s, \fBSBDataSeriesEntry\fP &entry)"
.PP
Definition at line 48 of file SbMathDataSeries\&.C'\&.
.PP
References SBDataSeriesEntry::Data, SBDataSeriesEntry::IsReadOK, SBVector::set(), and SBDataSeriesEntry::T\&.
.SS "\fBQTextStream\fP& operator>> (\fBQTextStream\fP &s, \fBSBDataSeries\fP &series)"
.PP
Definition at line 242 of file SbMathDataSeries\&.C'\&.
.PP
References SBDataSeries::checkRecords()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
