SBMainWindow
NAME
SBMainWindow -
SYNOPSIS
#include <SbIMainWin.H>
Inherits QMainWindow'.
Public Slots
void ControlConfigure ()
void ControlDefault ()
void ControlSelectFont ()
void ControlFlushLog ()
void ControlStyleDefault ()
void ControlStyleMotifPlus ()
void ControlStyleCDE ()
void ControlStyleSGI ()
void ControlStyleInterlace ()
void ControlStyleWindows ()
void ControlStylePlatinum ()
void StuffStations ()
void StuffSources ()
void StuffEOPs ()
void StuffVLBIObs ()
void StuffEccenticities ()
void StuffEphemerides ()
void StuffAplo ()
void StuffPlateMotion ()
void StuffModels ()
void StuffModelsNutPsi ()
void StuffModelsNutEps ()
void StuffModelsUT1High ()
void StuffModelsUT1Low ()
void StuffModelsUT1Diurn ()
void StuffModelsPolDiurn ()
void ExecuteGenProj ()
void ExecuteSelProj ()
void ExecuteEditProj ()
void ExecuteModels ()
void ExecuteParameters ()
void ExecuteRunProj ()
void ExecuteDoubleRunProj ()
void ExecuteReportProj ()
void ExecuteBrowseSolution ()
void ExecuteDrop ()
void UtilitiesPreProc ()
void UtilitiesSpectrum ()
void UtilitiesFilters ()
void UtilitiesDumpUI ()
void UtilitiesRestoreUI ()
void UtilitiesCollectStat4Prj ()
void UtilitiesCollectStat4All ()
void UtilitiesBrowseStat4Prj ()
void UtilitiesBrowseStat4All ()
void TestPrecession ()
void TestNutation ()
void TestRotation ()
void TestEphemerides ()
void TestEOPs ()
void TestDiurnalEOPs ()
void TestSolidTide ()
void TestOceanTide ()
void TestPoleTide ()
void TestAplo ()
void TestJustATest ()
void HelpHelp ()
void HelpAboutQt ()
void HelpAbout ()
void setMessage (const QString &)
void toggleToolBar ()
void toggleStatusBar ()
void toggleTBLabels ()
void stBarReset ()
void stBarSetTotalSteps (int)
void stBarSetProgress (int)
void setTRFName (const QString &)
void setCRFName (const QString &)
void setEOPName (const QString &)
void setPrjName (const QString &)
void setStatus (const QString &)
void setOperation (const QString &)
void setProcSes (int, int)
void setProcObs (int, int)
void setSessName (const QString &)
void setCacheSizes (int, int, int, int)
void setRunning (bool)
void stopRunning (void)
Signals
void run (bool)
Public Member Functions
SBMainWindow (QWidget *=0, const char *=0, WFlags=0)
virtual ~SBMainWindow ()
virtual QString ClassName () const
Protected Member Functions
virtual void resizeEvent (QResizeEvent *)
virtual void moveEvent (QMoveEvent *)
void changeStyle (SBSetUp::GUIStyle)
void setupMenu ()
void setupStatusBar ()
void setupToolBar ()
Protected Attributes
SBCentralPanel * CentralWidget
QIconSet * isStop
QToolButton * bStop
QToolButton * bExit
QPopupMenu * ControlMenu
QPopupMenu * StyleMenu
int toolbarChk
int statusbarChk
int labelsChk
int Styles [8]
QLabel * StBarLabel
QProgressBar * StBarProgress
QLabel * StBarMessage
QToolBar * ToolBar
Detailed Description
Definition at line 89 of file SbIMainWin.H'.
Constructor & Destructor Documentation
SBMainWindow::SBMainWindow (QWidget *parent = 0, const char *name = 0, WFlagsf = 0)
Definition at line 271 of file SbIMainWin.C'.
References SBSetUp::centralPanelPosition(), SBSetUp::centralPanelSize(), CentralWidget, SBSetUp::defaultFont(), SBSetUp::eops(), SBLog::INF, SBLog::IO, IsNeedToStop, SBSetUp::loadProject(), Log, pmSrcHLink, pmSrcStatus, SBSetUp::project(), run(), setCRFName(), setEOPName(), setMessage(), setPrjName(), setProcObs(), setProcSes(), setRunning(), setSessName(), setTRFName(), SetUp, setupMenu(), setupStatusBar(), setupToolBar(), SBSetUp::sources(), SBSetUp::stations(), and SBLog::write().
SBMainWindow::~SBMainWindow () [virtual]
Definition at line 340 of file SbIMainWin.C'.
References Institutions, isStop, Log, pmSrcHLink, pmSrcStatus, SBSetUp::SaveConfig(), SBSetUp::SaveStuff(), SBSetUp::setCentralPanelPosition(), SBSetUp::setCentralPanelSize(), and SetUp.
Member Function Documentation
void SBMainWindow::changeStyle (SBSetUp::GUIStyleStyle) [protected]
Definition at line 716 of file SbIMainWin.C'.
References SBSetUp::S_CDE, SBSetUp::S_Default, SBSetUp::S_Interlace, SBSetUp::S_MotifPlus, SBSetUp::S_Platinum, SBSetUp::S_SGI, SBSetUp::S_Windows, SBSetUp::setGUIStyle(), SetUp, StyleMenu, and Styles.
Referenced by ControlStyleCDE(), ControlStyleDefault(), ControlStyleInterlace(), ControlStyleMotifPlus(), ControlStylePlatinum(), ControlStyleSGI(), ControlStyleWindows(), and setupMenu().
virtual QString SBMainWindow::ClassName () const [inline, virtual]
Definition at line 96 of file SbIMainWin.H'.
Referenced by ControlConfigure(), ControlDefault(), ControlFlushLog(), ControlSelectFont(), ExecuteBrowseSolution(), ExecuteDoubleRunProj(), ExecuteDrop(), ExecuteEditProj(), ExecuteGenProj(), ExecuteModels(), ExecuteParameters(), ExecuteReportProj(), ExecuteRunProj(), ExecuteSelProj(), HelpAbout(), HelpAboutQt(), HelpHelp(), StuffAplo(), StuffEccenticities(), StuffEOPs(), StuffEphemerides(), StuffModels(), StuffModelsNutEps(), StuffModelsNutPsi(), StuffModelsPolDiurn(), StuffModelsUT1Diurn(), StuffModelsUT1High(), StuffModelsUT1Low(), StuffPlateMotion(), StuffSources(), StuffStations(), StuffVLBIObs(), TestAplo(), TestDiurnalEOPs(), TestEOPs(), TestEphemerides(), TestJustATest(), TestNutation(), TestOceanTide(), TestPoleTide(), TestPrecession(), TestRotation(), TestSolidTide(), UtilitiesBrowseStat4All(), UtilitiesBrowseStat4Prj(), UtilitiesCollectStat4All(), UtilitiesCollectStat4Prj(), UtilitiesDumpUI(), UtilitiesFilters(), UtilitiesPreProc(), UtilitiesRestoreUI(), and UtilitiesSpectrum().
void SBMainWindow::ControlConfigure () [slot]
Definition at line 657 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu(), and setupToolBar().
void SBMainWindow::ControlDefault () [slot]
Definition at line 663 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBSetUp::SetDefaults(), SetUp, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::ControlFlushLog () [slot]
Definition at line 749 of file SbIMainWin.C'.
References ClassName(), SBLog::clearSpool(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::ControlSelectFont () [slot]
Definition at line 669 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBSetUp::defaultFont(), SBLog::INTERFACE, Log, SBSetUp::setDefaultFont(), SetUp, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::ControlStyleCDE () [slot]
Definition at line 691 of file SbIMainWin.C'.
References changeStyle(), and SBSetUp::S_CDE.
Referenced by setupMenu().
void SBMainWindow::ControlStyleDefault () [slot]
Definition at line 681 of file SbIMainWin.C'.
References changeStyle(), and SBSetUp::S_Default.
Referenced by setupMenu().
void SBMainWindow::ControlStyleInterlace () [slot]
Definition at line 701 of file SbIMainWin.C'.
References changeStyle(), and SBSetUp::S_Interlace.
Referenced by setupMenu().
void SBMainWindow::ControlStyleMotifPlus () [slot]
Definition at line 686 of file SbIMainWin.C'.
References changeStyle(), and SBSetUp::S_MotifPlus.
Referenced by setupMenu().
void SBMainWindow::ControlStylePlatinum () [slot]
Definition at line 711 of file SbIMainWin.C'.
References changeStyle(), and SBSetUp::S_Platinum.
Referenced by setupMenu().
void SBMainWindow::ControlStyleSGI () [slot]
Definition at line 696 of file SbIMainWin.C'.
References changeStyle(), and SBSetUp::S_SGI.
Referenced by setupMenu().
void SBMainWindow::ControlStyleWindows () [slot]
Definition at line 706 of file SbIMainWin.C'.
References changeStyle(), and SBSetUp::S_Windows.
Referenced by setupMenu().
void SBMainWindow::ExecuteBrowseSolution () [slot]
Definition at line 963 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::ExecuteDoubleRunProj () [slot]
Definition at line 909 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, IsNeedToStop, Log, SBRunManager::process(), SBSetUp::project(), SBSetUp::ProjectFileName(), SBLog::RUN, run(), SetUp, stBarReset(), SBLog::write(), and SBLog::WRN.
Referenced by setupMenu().
void SBMainWindow::ExecuteDrop () [slot]
Definition at line 969 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBSolution::deleteSolution(), SBLog::INTERFACE, SBSetUp::loadProject(), Log, SBSetUp::project(), SBVersion::selfName(), SetUp, Version, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::ExecuteEditProj () [slot]
Definition at line 849 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBSetUp::project(), SBSetUp::ProjectFileName(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by setupMenu().
void SBMainWindow::ExecuteGenProj () [slot]
Definition at line 837 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::ExecuteModels () [slot]
Definition at line 859 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBSetUp::project(), SBSetUp::ProjectFileName(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by setupMenu().
void SBMainWindow::ExecuteParameters () [slot]
Definition at line 869 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBSetUp::project(), SBSetUp::ProjectFileName(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by setupMenu().
void SBMainWindow::ExecuteReportProj () [slot]
Definition at line 947 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBRunManager::makeReports(), SBSetUp::project(), SBSetUp::ProjectFileName(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by setupMenu().
void SBMainWindow::ExecuteRunProj () [slot]
Definition at line 879 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, IsNeedToStop, Log, SBRunManager::process(), SBSetUp::project(), SBSetUp::ProjectFileName(), SBLog::RUN, run(), SetUp, stBarReset(), SBLog::write(), and SBLog::WRN.
Referenced by setupMenu().
void SBMainWindow::ExecuteSelProj () [slot]
Definition at line 843 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::HelpAbout () [slot]
Definition at line 1144 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBCompilerDate, SBCompilerDomainName, SBCompilerHostName, SBCompilerLoginName, SBCompilerName, SBCompilerOS, SBCompilerTime, SBCompilerUserName, SBCompilerVersion, SBVersion::selfName(), SBVersion::toString(), Version, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::HelpAboutQt () [slot]
Definition at line 1138 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBVersion::selfName(), Version, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::HelpHelp () [slot]
Definition at line 1133 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::moveEvent (QMoveEvent *QME) [protected, virtual]
Definition at line 640 of file SbIMainWin.C'.
References SBSetUp::setCentralPanelPosition(), and SetUp.
void SBMainWindow::resizeEvent (QResizeEvent *QRE) [protected, virtual]
Definition at line 634 of file SbIMainWin.C'.
References SBSetUp::setCentralPanelSize(), and SetUp.
void SBMainWindow::run (boolt0) [signal]
Definition at line 684 of file SbIMainWin.moc.C'.
Referenced by ExecuteDoubleRunProj(), ExecuteRunProj(), and SBMainWindow().
void SBMainWindow::setCacheSizes (intnObs, intnSes, intnCRF, intnTRF) [slot]
Definition at line 1245 of file SbIMainWin.C'.
References SBCentralPanel::CasheSizes, and CentralWidget.
Referenced by mainSetCacheSizes().
void SBMainWindow::setCRFName (const QString &N_) [slot]
Definition at line 1197 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::CRFName.
Referenced by mainSetCRFName(), and SBMainWindow().
void SBMainWindow::setEOPName (const QString &N_) [slot]
Definition at line 1203 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::EOPName.
Referenced by mainSetEOPName(), and SBMainWindow().
void SBMainWindow::setMessage (const QString &message_) [slot]
Definition at line 629 of file SbIMainWin.C'.
References StBarMessage.
Referenced by mainMessage(), and SBMainWindow().
void SBMainWindow::setOperation (const QString &O_) [slot]
Definition at line 1221 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::Operation.
Referenced by mainSetOperation().
void SBMainWindow::setPrjName (const QString &N_) [slot]
Definition at line 1209 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::PrjName.
Referenced by mainSetPrjName(), and SBMainWindow().
void SBMainWindow::setProcObs (intn, intTotal) [slot]
Definition at line 1233 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::ProcObs.
Referenced by mainSetProcObs(), and SBMainWindow().
void SBMainWindow::setProcSes (intn, intTotal) [slot]
Definition at line 1227 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::ProcSess.
Referenced by mainSetProcSes(), and SBMainWindow().
void SBMainWindow::setRunning (boolisRun) [slot]
Definition at line 646 of file SbIMainWin.C'.
References bExit, and bStop.
Referenced by SBMainWindow().
void SBMainWindow::setSessName (const QString &N_) [slot]
Definition at line 1239 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::SessName.
Referenced by mainSetSessName(), and SBMainWindow().
void SBMainWindow::setStatus (const QString &S_) [slot]
Definition at line 1215 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::Status.
Referenced by mainSetStatus().
void SBMainWindow::setTRFName (const QString &N_) [slot]
Definition at line 1191 of file SbIMainWin.C'.
References CentralWidget, and SBCentralPanel::TRFName.
Referenced by mainSetTRFName(), and SBMainWindow().
void SBMainWindow::setupMenu () [protected]
Definition at line 467 of file SbIMainWin.C'.
References changeStyle(), ControlConfigure(), ControlDefault(), ControlFlushLog(), ControlMenu, ControlSelectFont(), ControlStyleCDE(), ControlStyleDefault(), ControlStyleInterlace(), ControlStyleMotifPlus(), ControlStylePlatinum(), ControlStyleSGI(), ControlStyleWindows(), ExecuteBrowseSolution(), ExecuteDoubleRunProj(), ExecuteDrop(), ExecuteEditProj(), ExecuteGenProj(), ExecuteModels(), ExecuteParameters(), ExecuteReportProj(), ExecuteRunProj(), ExecuteSelProj(), SBSetUp::guiStyle(), HelpAbout(), HelpAboutQt(), HelpHelp(), labelsChk, SBSetUp::S_Default, SetUp, statusbarChk, StuffAplo(), StuffEccenticities(), StuffEOPs(), StuffEphemerides(), StuffModels(), StuffPlateMotion(), StuffSources(), StuffStations(), StuffVLBIObs(), StyleMenu, Styles, TestAplo(), TestDiurnalEOPs(), TestEOPs(), TestEphemerides(), TestJustATest(), TestNutation(), TestOceanTide(), TestPoleTide(), TestPrecession(), TestRotation(), TestSolidTide(), toggleStatusBar(), toggleTBLabels(), toggleToolBar(), toolbarChk, UtilitiesBrowseStat4All(), UtilitiesBrowseStat4Prj(), UtilitiesCollectStat4All(), UtilitiesCollectStat4Prj(), UtilitiesDumpUI(), UtilitiesFilters(), UtilitiesPreProc(), UtilitiesRestoreUI(), and UtilitiesSpectrum().
Referenced by SBMainWindow().
void SBMainWindow::setupStatusBar () [protected]
Definition at line 443 of file SbIMainWin.C'.
References SBVersion::name(), StBarLabel, StBarMessage, StBarProgress, and Version.
Referenced by SBMainWindow().
void SBMainWindow::setupToolBar () [protected]
Definition at line 364 of file SbIMainWin.C'.
References bExit, bStop, ControlConfigure(), isStop, stopRunning(), StuffEOPs(), StuffSources(), StuffStations(), StuffVLBIObs(), and ToolBar.
Referenced by SBMainWindow().
void SBMainWindow::stBarReset () [slot]
Definition at line 1176 of file SbIMainWin.C'.
References StBarProgress.
Referenced by ExecuteDoubleRunProj(), ExecuteRunProj(), and mainPrBarReset().
void SBMainWindow::stBarSetProgress (intp) [slot]
Definition at line 1186 of file SbIMainWin.C'.
References StBarProgress.
Referenced by mainPrBarSetProgress().
void SBMainWindow::stBarSetTotalSteps (intts) [slot]
Definition at line 1181 of file SbIMainWin.C'.
References StBarProgress.
Referenced by mainPrBarSetTotalSteps().
void SBMainWindow::stopRunning (void) [slot]
Definition at line 652 of file SbIMainWin.C'.
References IsNeedToStop.
Referenced by setupToolBar().
void SBMainWindow::StuffAplo () [slot]
Definition at line 785 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::StuffEccenticities () [slot]
Definition at line 791 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::StuffEOPs () [slot]
Definition at line 767 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu(), and setupToolBar().
void SBMainWindow::StuffEphemerides () [slot]
Definition at line 779 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::StuffModels () [slot]
Definition at line 801 of file SbIMainWin.C'.
References ClassName(), Config, SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::StuffModelsNutEps () [slot]
Definition at line 812 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
void SBMainWindow::StuffModelsNutPsi () [slot]
Definition at line 807 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
void SBMainWindow::StuffModelsPolDiurn () [slot]
Definition at line 832 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
void SBMainWindow::StuffModelsUT1Diurn () [slot]
Definition at line 827 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
void SBMainWindow::StuffModelsUT1High () [slot]
Definition at line 817 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
void SBMainWindow::StuffModelsUT1Low () [slot]
Definition at line 822 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
void SBMainWindow::StuffPlateMotion () [slot]
Definition at line 796 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::StuffSources () [slot]
Definition at line 761 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu(), and setupToolBar().
void SBMainWindow::StuffStations () [slot]
Definition at line 755 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu(), and setupToolBar().
void SBMainWindow::StuffVLBIObs () [slot]
Definition at line 773 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu(), and setupToolBar().
void SBMainWindow::TestAplo () [slot]
Definition at line 1110 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestDiurnalEOPs () [slot]
Definition at line 1086 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestEOPs () [slot]
Definition at line 1080 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestEphemerides () [slot]
Definition at line 1074 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestJustATest () [slot]
Definition at line 1116 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestNutation () [slot]
Definition at line 1062 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestOceanTide () [slot]
Definition at line 1098 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestPoleTide () [slot]
Definition at line 1104 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestPrecession () [slot]
Definition at line 1056 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestRotation () [slot]
Definition at line 1068 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::TestSolidTide () [slot]
Definition at line 1092 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::toggleStatusBar () [slot]
Definition at line 615 of file SbIMainWin.C'.
References ControlMenu, and statusbarChk.
Referenced by setupMenu().
void SBMainWindow::toggleTBLabels () [slot]
Definition at line 601 of file SbIMainWin.C'.
References ControlMenu, and labelsChk.
Referenced by setupMenu().
void SBMainWindow::toggleToolBar () [slot]
Definition at line 587 of file SbIMainWin.C'.
References ControlMenu, ToolBar, and toolbarChk.
Referenced by setupMenu().
void SBMainWindow::UtilitiesBrowseStat4All () [slot]
Definition at line 1050 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesBrowseStat4Prj () [slot]
Definition at line 1044 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesCollectStat4All () [slot]
Definition at line 1035 of file SbIMainWin.C'.
References ClassName(), SBObsVLBIStatistics::collectStatistics(), SBLog::DBG, SBLog::INTERFACE, Log, SBSetUp::saveObsVLBIStatistics(), SetUp, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesCollectStat4Prj () [slot]
Definition at line 1019 of file SbIMainWin.C'.
References ClassName(), SBObsVLBIStatistics::collectStatistics(), SBLog::DBG, SBLog::ERR, SBLog::INTERFACE, SBSetUp::loadProject(), Log, SBNamed::name(), SBSetUp::saveObsVLBIStatistics(), SetUp, SBProject::VLBIsessionList(), and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesDumpUI () [slot]
Definition at line 1002 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBVLBISet::dumpUserInfo(), SBLog::INTERFACE, SBSetUp::loadVLBI(), Log, SetUp, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesFilters () [slot]
Definition at line 996 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesPreProc () [slot]
Definition at line 984 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesRestoreUI () [slot]
Definition at line 1011 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, SBSetUp::loadVLBI(), Log, SBVLBISet::restoreUserInfo(), SetUp, and SBLog::write().
Referenced by setupMenu().
void SBMainWindow::UtilitiesSpectrum () [slot]
Definition at line 990 of file SbIMainWin.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by setupMenu().
Member Data Documentation
QToolButton* SBMainWindow::bExit [protected]
Definition at line 213 of file SbIMainWin.H'.
Referenced by setRunning(), and setupToolBar().
QToolButton* SBMainWindow::bStop [protected]
Definition at line 212 of file SbIMainWin.H'.
Referenced by setRunning(), and setupToolBar().
SBCentralPanel* SBMainWindow::CentralWidget [protected]
Definition at line 202 of file SbIMainWin.H'.
Referenced by SBMainWindow(), setCacheSizes(), setCRFName(), setEOPName(), setOperation(), setPrjName(), setProcObs(), setProcSes(), setSessName(), setStatus(), and setTRFName().
QPopupMenu* SBMainWindow::ControlMenu [protected]
Definition at line 216 of file SbIMainWin.H'.
Referenced by setupMenu(), toggleStatusBar(), toggleTBLabels(), and toggleToolBar().
QIconSet* SBMainWindow::isStop [protected]
Definition at line 209 of file SbIMainWin.H'.
Referenced by setupToolBar(), and ~SBMainWindow().
int SBMainWindow::labelsChk [protected]
Definition at line 221 of file SbIMainWin.H'.
Referenced by setupMenu(), and toggleTBLabels().
int SBMainWindow::statusbarChk [protected]
Definition at line 220 of file SbIMainWin.H'.
Referenced by setupMenu(), and toggleStatusBar().
QLabel* SBMainWindow::StBarLabel [protected]
Definition at line 225 of file SbIMainWin.H'.
Referenced by setupStatusBar().
QLabel* SBMainWindow::StBarMessage [protected]
Definition at line 227 of file SbIMainWin.H'.
Referenced by setMessage(), and setupStatusBar().
QProgressBar* SBMainWindow::StBarProgress [protected]
Definition at line 226 of file SbIMainWin.H'.
Referenced by setupStatusBar(), stBarReset(), stBarSetProgress(), and stBarSetTotalSteps().
QPopupMenu* SBMainWindow::StyleMenu [protected]
Definition at line 217 of file SbIMainWin.H'.
Referenced by changeStyle(), and setupMenu().
int SBMainWindow::Styles[8] [protected]
Definition at line 222 of file SbIMainWin.H'.
Referenced by changeStyle(), and setupMenu().
QToolBar* SBMainWindow::ToolBar [protected]
Definition at line 231 of file SbIMainWin.H'.
Referenced by setupToolBar(), and toggleToolBar().
int SBMainWindow::toolbarChk [protected]
Definition at line 219 of file SbIMainWin.H'.
Referenced by setupMenu(), and toggleToolBar().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.