SBMatrix
NAME
SBMatrix -
SYNOPSIS
#include <SbVector.H>
Inherits SBNamed'.
Inherited by SBUpperMatrix'.
Public Member Functions
SBMatrix ()
SBMatrix (unsigned int, unsigned int, const QString &, bool=TRUE)
SBMatrix (const SBMatrix &)
virtual ~SBMatrix ()
virtual QString ClassName () const
virtual unsigned int nRow () const
virtual unsigned int nCol () const
virtual double & operator() (unsigned int, unsigned int)
virtual double at (unsigned int, unsigned int) const
virtual void set (unsigned int, unsigned int, double)
SBMatrix & operator= (const SBMatrix &)
virtual SBMatrix & operator= (double)
SBMatrix & setCol (unsigned int, const SBVector &)
SBVector & setVector (unsigned int, SBVector &)
virtual void clear ()
virtual SBMatrix T ()
virtual SBMatrix & operator+= (const SBMatrix &)
virtual SBMatrix & operator-= (const SBMatrix &)
SBMatrix & operator*= (double)
SBMatrix & operator/= (double)
void resize (unsigned int, unsigned int)
const QString & name () const
void setName (const QString &Name_)
Protected Member Functions
SBMatrix (const QString &Name_)
Protected Attributes
unsigned int NRow
unsigned int NCol
double ** B
double dTmp
QString Name
Private Member Functions
SBMatrix operator~ ()
SBMatrix operator* (const SBSymMatrix &)
Friends
class SBUpperMatrix
SBMatrix operator/ (const SBMatrix &M, double f)
SBMatrix operator* (const SBMatrix &M, double f)
SBMatrix operator* (double f, const SBMatrix &M)
SBMatrix operator- (const SBMatrix &M)
SBMatrix operator+ (const SBMatrix &, const SBMatrix &)
SBMatrix operator- (const SBMatrix &, const SBMatrix &)
SBMatrix operator* (const SBMatrix &, const SBMatrix &)
SBSymMatrix QuadraticForm (const SBSymMatrix &, const SBMatrix &)
SBMatrix matT_x_mat (const SBMatrix &, const SBMatrix &)
SBVector operator* (const SBMatrix &, const SBVector &)
SBVector matT_x_vec (const SBMatrix &, const SBVector &)
QDataStream & operator<< (QDataStream &, const SBMatrix &)
QDataStream & operator>> (QDataStream &, SBMatrix &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
class SBMatrix'.'. just a matrix'.
Definition at line 276 of file SbVector.H'.
Constructor & Destructor Documentation
SBMatrix::SBMatrix (const QString &Name_) [inline, protected]"A constructor'. Creates an empty matrix (for inheritated objects)'.
Definition at line 288 of file SbVector.H'.
References B, dTmp, NCol, and NRow.
SBMatrix::SBMatrix () [inline]"A constructor'. Creates an empty matrix (for I/O purposes)'.
Definition at line 296 of file SbVector.H'.
References B, dTmp, NCol, and NRow.
Referenced by operator*(), and SBSymMatrix::operator*().
SBMatrix::SBMatrix (unsigned intNRow_, unsigned intNCol_, const QString &Name_, boolIsNeedClear = TRUE) [inline]"A constructor'. Creates a copy of object'.
Parameters:
NRow_ number of rows;
NCol_ number of columns'.
Definition at line 402 of file SbVector.H'.
References B, dTmp, NCol, and NRow.
SBMatrix::SBMatrix (const SBMatrix &M) [inline]"A constructor'. Creates a copy of object'.
Parameters:
M values of the new object'.
Definition at line 417 of file SbVector.H'.
References B, dTmp, NCol, and NRow.
SBMatrix::~SBMatrix () [inline, virtual]"A destructor'.
Definition at line 431 of file SbVector.H'.
References B, and NCol.
Member Function Documentation
double SBMatrix::at (unsigned inti, unsigned intj) const [inline, virtual]"Returns value of the (i,j)-th element'.
Reimplemented in SBSymMatrix, and SBUpperMatrix'.
Definition at line 464 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), NCol, NRow, and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), SBSpectrumAnalyserMEM::checkLine(), SBEstimator::collectContStochs4NextBatch(), SBPlotBranch::dataAttr(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), SBTestEOP::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBPlotArea::getLimits(), SBSpline::h(), SBFilterGauss::interpolate(), SBEOP::interpolateEOPs(), makeHouseholder(), SBEstimator::mapContStochs4NewBatch(), SBFilterModel::modelFull(), SBFilterModel::modelKeep(), SBEstimator::moveGlobalInfo(), SBEOP::prepare4Date(), SBSpline::prepare4Spline(), SBEstimator::propagateStochasticPars(), QuadraticForm(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBSpline::solveSpline(), SBSpline::spline(), and writeNormalEquationSystem().
virtual QString SBMatrix::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBNamed'.
Reimplemented in SBSymMatrix, and SBUpperMatrix'.
Definition at line 311 of file SbVector.H'.
Referenced by at(), matT_x_mat(), operator()(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator=(), set(), setCol(), and setVector().
void SBMatrix::clear () [inline, virtual]"Fills matrix with zeros'.
Reimplemented in SBUpperMatrix'.
Definition at line 442 of file SbVector.H'.
References B, NCol, and NRow.
Referenced by SBEstimator::propagateStochasticPars(), SBFilterModel::setNumOfHarmonics(), and SBFilterModel::setUpSpecModel().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), set(), SBUpperMatrix::set(), setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual unsigned int SBMatrix::nCol () const [inline, virtual]"Returns number of columns'.
Definition at line 318 of file SbVector.H'.
References NCol.
Referenced by SBPlotBranch::dataAttr(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBFilterGauss::readDataFile(), SBPlotBranch::setDataAttr(), sinex_SolutionMatrixEstimateBlock(), and sinex_SolutionNormalEquationMatrixBlock().
virtual unsigned int SBMatrix::nRow () const [inline, virtual]"Returns number of rows'.
Definition at line 316 of file SbVector.H'.
References NRow.
Referenced by SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBPlotArea::getLimits(), makeHouseholder(), SBUpperMatrix::n(), QuadraticForm(), and SBFilterGauss::readDataFile().
double & SBMatrix::operator() (unsigned inti, unsigned intj) [inline, virtual]"Returns reference to the (i,j)-th element'.
Reimplemented in SBUpperMatrix'.
Definition at line 449 of file SbVector.H'.
References B, ClassName(), dTmp, SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), NCol, NRow, and SBLog::write().
SBMatrix SBMatrix::operator* (const SBSymMatrix &) [inline, private]
Definition at line 377 of file SbVector.H'.
References SBMatrix().
SBMatrix & SBMatrix::operator*= (doublef) [inline]"Multiplies the matrix by a double'.
Reimplemented in SBSymMatrix, and SBUpperMatrix'.
Definition at line 551 of file SbVector.H'.
References B, NCol, and NRow.
SBMatrix & SBMatrix::operator+= (const SBMatrix &M) [inline, virtual]"Adds a matrix to the matrix'.
Definition at line 517 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), NCol, NRow, and SBLog::write().
SBMatrix & SBMatrix::operator-= (const SBMatrix &M) [inline, virtual]"Substracts a matrix from the matrix'.
Definition at line 534 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), NCol, NRow, and SBLog::write().
SBMatrix & SBMatrix::operator/= (doublef) [inline]"Divides the matrix by a double'.
Reimplemented in SBSymMatrix, and SBUpperMatrix'.
Definition at line 560 of file SbVector.H'.
References B, NCol, and NRow.
SBMatrix & SBMatrix::operator= (const SBMatrix &M) [inline]"Assign the matix to another one'.
Definition at line 491 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), NCol, NRow, and SBLog::write().
SBMatrix & SBMatrix::operator= (doublef) [inline, virtual]"Fills the matix with the double'.
Reimplemented in SBSymMatrix, and SBUpperMatrix'.
Definition at line 508 of file SbVector.H'.
References B, NCol, and NRow.
SBMatrix SBMatrix::operator~ () [private]"Returns inversed matrix'. This is time consumed operation, shouldn't use in ordinary operations'. M*~M==~M*M==1 (original matrix doesn't change)'.
Reimplemented in SBSymMatrix'.
Definition at line 85 of file SbVector.C'.
void SBMatrix::resize (unsigned intNRow_, unsigned intNCol_)"Changes the size of a matrix'.
Definition at line 66 of file SbVector.C'.
References B, dTmp, NCol, and NRow.
Referenced by SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), and SBEOP::setPtNum().
void SBMatrix::set (unsigned inti, unsigned intj, doubleA_) [inline, virtual]"Sets the (i,j)-th element to the double'.
Reimplemented in SBUpperMatrix'.
Definition at line 477 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), NCol, NRow, and SBLog::write().
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), SBFilterGauss::calcSigma(), SBEstimator::collectContStochs4NextBatch(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBVLBIPreProcess::fillObsListView(), SBAploEphem::getReady(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEOP::prepare4Date(), SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBEstimator::processObs(), SBEstimator::propagateStochasticPars(), SBFilteringGauss::redrawDataPlot(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBSpectrumAnalyserMEM::redrawFPEPlot(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBFilteringGauss::redrawTFPlot(), SBPlotBranch::setDataAttr(), SBFilteringGauss::wBrowseTF(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBVLBISessionEditor::wObservs(), writeNormalEquationSystem(), and SBSolutionBrowser::wWRMSs().
SBMatrix & SBMatrix::setCol (unsigned intN_, const SBVector &V) [inline]"Sets i-th column to a Vector'.
Reimplemented in SBSymMatrix, and SBUpperMatrix'.
Definition at line 579 of file SbVector.H'.
References SBVector::B, B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBVector::N, SBNamed::name(), NCol, NRow, and SBLog::write().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
SBVector & SBMatrix::setVector (unsigned intN_, SBVector &V) [inline]"Assign to the vector the values of matrix'es column'.
Reimplemented in SBUpperMatrix'.
Definition at line 594 of file SbVector.H'.
References SBVector::B, B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBVector::N, SBNamed::name(), NCol, NRow, and SBLog::write().
SBMatrix SBMatrix::T () [inline, virtual]"Returns transposed matrix (original matrix doesn't change)'.
Reimplemented in SBSymMatrix, and SBUpperMatrix'.
Definition at line 569 of file SbVector.H'.
References B, SBNamed::name(), NCol, and NRow.
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
SBMatrix matT_x_mat (const SBMatrix &M1, const SBMatrix &M2) [friend]"Returns a product of a transposed matrix and a matrix'. This function is equal to `M1'.T()*M2', but implements a more efficient realization'.
Definition at line 116 of file SbVector.C'.
SBVector matT_x_vec (const SBMatrix &M, const SBVector &V) [friend]"Returns a product of a transposed matrix and a vector'. This function is equal to `M'.T()*V', but implements a more efficient realization'.
Definition at line 419 of file SbVector.C'.
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
SBMatrix operator* (const SBMatrix &M, doublef) [friend]"Returns matrix multiplied by float'.
Definition at line 356 of file SbVector.H'.
SBMatrix operator* (doublef, const SBMatrix &M) [friend]"Returns matrix multiplied by float'.
Definition at line 358 of file SbVector.H'.
SBMatrix operator* (const SBMatrix &M1, const SBMatrix &M2) [friend]"Returns product of two matrices'.
Definition at line 98 of file SbVector.C'.
SBVector operator* (const SBMatrix &M, const SBVector &V) [friend]"Returns a product of a matrix and a vector'.
Definition at line 397 of file SbVector.C'.
SBMatrix operator+ (const SBMatrix &M1, const SBMatrix &M2) [friend]"Returns a sum of two matrices'.
Definition at line 1133 of file SbVector.H'.
SBMatrix operator- (const SBMatrix &M) [friend]"Returns matrix with reversed sign'.
Definition at line 360 of file SbVector.H'.
SBMatrix operator- (const SBMatrix &M1, const SBMatrix &M2) [friend]"Returns a difference of two matrices'.
Definition at line 1146 of file SbVector.H'.
SBMatrix operator/ (const SBMatrix &M, doublef) [friend]"Returns matrix divided by float'.
Definition at line 354 of file SbVector.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBMatrix &M) [friend]
Definition at line 135 of file SbVector.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBMatrix &M) [friend]
Definition at line 143 of file SbVector.C'.
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBMatrix &A) [friend]
Reimplemented in SBSymMatrix'.
Definition at line 468 of file SbVector.C'.
friend class SBUpperMatrix [friend]
Definition at line 278 of file SbVector.H'.
Member Data Documentation
double** SBMatrix::B [protected]
Definition at line 282 of file SbVector.H'.
Referenced by at(), SBUpperMatrix::at(), SBSymMatrix::at(), clear(), SBUpperMatrix::clear(), matT_x_mat(), operator()(), SBUpperMatrix::operator()(), operator*(), operator*=(), SBUpperMatrix::operator*=(), operator+=(), SBUpperMatrix::operator+=(), operator-=(), SBUpperMatrix::operator-=(), operator/=(), SBUpperMatrix::operator/=(), operator<<(), operator=(), SBUpperMatrix::operator=(), operator>>(), resize(), SBMatrix(), SBSymMatrix::SBSymMatrix(), SBUpperMatrix::SBUpperMatrix(), set(), SBUpperMatrix::set(), setCol(), SBUpperMatrix::setCol(), setVector(), SBUpperMatrix::setVector(), T(), SBUpperMatrix::T(), ~SBMatrix(), and SBUpperMatrix::~SBUpperMatrix().
double SBMatrix::dTmp [protected]
Definition at line 283 of file SbVector.H'.
Referenced by operator()(), SBUpperMatrix::operator()(), resize(), SBMatrix(), SBSymMatrix::SBSymMatrix(), and SBUpperMatrix::SBUpperMatrix().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
unsigned int SBMatrix::NCol [protected]
Definition at line 281 of file SbVector.H'.
Referenced by at(), SBUpperMatrix::at(), SBSymMatrix::at(), clear(), SBUpperMatrix::clear(), matT_x_mat(), nCol(), operator()(), SBUpperMatrix::operator()(), operator*(), operator*=(), SBUpperMatrix::operator*=(), operator+(), operator+=(), SBUpperMatrix::operator+=(), operator-(), operator-=(), SBUpperMatrix::operator-=(), operator/=(), SBUpperMatrix::operator/=(), operator<<(), operator=(), SBUpperMatrix::operator=(), operator>>(), QuadraticForm(), resize(), RRT(), RTR(), SBMatrix(), SBSymMatrix::SBSymMatrix(), SBUpperMatrix::SBUpperMatrix(), set(), SBUpperMatrix::set(), setCol(), SBUpperMatrix::setCol(), setVector(), SBUpperMatrix::setVector(), T(), SBUpperMatrix::T(), ~SBMatrix(), and SBUpperMatrix::~SBUpperMatrix().
unsigned int SBMatrix::NRow [protected]
Definition at line 280 of file SbVector.H'.
Referenced by at(), SBUpperMatrix::at(), SBSymMatrix::at(), clear(), matT_x_mat(), nRow(), operator()(), SBUpperMatrix::operator()(), operator*(), operator*=(), operator+(), operator+=(), SBUpperMatrix::operator+=(), operator-(), operator-=(), SBUpperMatrix::operator-=(), operator/=(), operator<<(), operator=(), SBUpperMatrix::operator=(), operator>>(), QuadraticForm(), resize(), RRT(), RTR(), SBMatrix(), SBSymMatrix::SBSymMatrix(), SBUpperMatrix::SBUpperMatrix(), set(), SBUpperMatrix::set(), setCol(), SBUpperMatrix::setCol(), setVector(), SBUpperMatrix::setVector(), Solve(), T(), and SBUpperMatrix::T().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.