SBMaster
NAME
SBMaster -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits QList< SBMasterFile >'.
Public Member Functions
SBMaster ()
virtual ~SBMaster ()
virtual QString ClassName () const
SBMasterRecord * lookupMR (const QString &)
void importMF (const QString &)
void checkNewFiles (const QString &)
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
void mapRecords ()
void mapFiles ()
Protected Attributes
QDict< SBMasterRecord > * RecordByName
QDict< SBMasterFile > * FileByName
Friends
QDataStream & operator<< (QDataStream &s, const SBMaster &M)
QDataStream & operator>> (QDataStream &s, SBMaster &M)
Detailed Description
Definition at line 1197 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBMaster::SBMaster ()"A constructor'.
A constructor'. Creates a copy of object'.
Definition at line 2147 of file SbGeoObsVLBI.C'.
References FileByName, and RecordByName.
SBMaster::~SBMaster () [virtual]"A destructor'.
Definition at line 2158 of file SbGeoObsVLBI.C'.
References FileByName, and RecordByName.
Member Function Documentation
void SBMaster::checkNewFiles (const QString &DirName)
Definition at line 2323 of file SbGeoObsVLBI.C'.
References importMF().
Referenced by SBSetUp::LoadStuff().
virtual QString SBMaster::ClassName () const [inline, virtual]
Definition at line 1219 of file SbGeoObsVLBI.H'.
Referenced by importMF(), mapFiles(), and mapRecords().
virtual int SBMaster::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 1200 of file SbGeoObsVLBI.H'.
void SBMaster::importMF (const QString &FName)
Definition at line 2241 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), ClassName(), SBLog::DATA, SBLog::DBG, SBLog::ERR, FileByName, SBMasterFile::Intensive, SBLog::IO, Log, SBNamed::name(), SBMasterFile::tModified(), SBLog::write(), and SBLog::WRN.
Referenced by checkNewFiles().
SBMasterRecord * SBMaster::lookupMR (const QString &name_)
Definition at line 2225 of file SbGeoObsVLBI.C'.
References RecordByName.
Referenced by SBVLBISet::import(), SBRunManager::makeReportEOP(), and SBRunManager::makeReportTroposphere().
void SBMaster::mapFiles () [protected]
Definition at line 2202 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, FileByName, Log, SBNamed::name(), and SBLog::write().
void SBMaster::mapRecords () [protected]
Definition at line 2172 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, Log, SBNamed::name(), RecordByName, SBLog::write(), and SBLog::WRN.
virtual QDataStream& SBMaster::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 1204 of file SbGeoObsVLBI.H'.
virtual QDataStream& SBMaster::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 1202 of file SbGeoObsVLBI.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBMaster &M) [friend]
Definition at line 1228 of file SbGeoObsVLBI.H'.
QDataStream& operator>> (QDataStream &s, SBMaster &M) [friend]
Definition at line 1230 of file SbGeoObsVLBI.H'.
Member Data Documentation
QDict<SBMasterFile>* SBMaster::FileByName [protected]
Definition at line 1208 of file SbGeoObsVLBI.H'.
Referenced by importMF(), mapFiles(), SBMaster(), and ~SBMaster().
QDict<SBMasterRecord>* SBMaster::RecordByName [protected]
Definition at line 1205 of file SbGeoObsVLBI.H'.
Referenced by lookupMR(), mapRecords(), SBMaster(), and ~SBMaster().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.