SBMasterRecBrowser
NAME
SBMasterRecBrowser -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QDialog'.
Classes
class SBMRListItem
Signals
void masterRecordModified (bool)
Public Member Functions
SBMasterRecBrowser (SBVLBISet *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBMasterRecBrowser ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual void closeEvent (QCloseEvent)
Private Attributes
SBVLBISet * VLBI
SBMaster * Master
QListView * MRecLV
bool isModified
Detailed Description
Definition at line 679 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBMasterRecBrowser::SBMasterRecBrowser (SBVLBISet *W_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 3164 of file SbIObsVLBI.C'.
References accept(), SBMasterRecord::Exists, isModified, SBVLBISet::loadMaster(), Master, SBVLBISet::master(), MRecLV, reject(), SBVLBISet::sessionInfo(), and VLBI.
SBMasterRecBrowser::~SBMasterRecBrowser ()
Definition at line 3239 of file SbIObsVLBI.C'.
References isModified, masterRecordModified(), SBVLBISet::releaseMaster(), and VLBI.
Member Function Documentation
void SBMasterRecBrowser::accept () [inline, protected, slot]
Definition at line 693 of file SbIObsVLBI.H'.
Referenced by SBMasterRecBrowser().
virtual QString SBMasterRecBrowser::ClassName () const [inline, virtual]
Definition at line 685 of file SbIObsVLBI.H'.
virtual void SBMasterRecBrowser::closeEvent (QCloseEvent) [inline, protected, virtual]
Definition at line 719 of file SbIObsVLBI.H'.
void SBMasterRecBrowser::masterRecordModified (boolt0) [signal]
Definition at line 1197 of file SbIObsVLBI.moc.C'.
Referenced by ~SBMasterRecBrowser().
void SBMasterRecBrowser::reject () [inline, protected, slot]
Definition at line 694 of file SbIObsVLBI.H'.
Referenced by SBMasterRecBrowser().
Member Data Documentation
bool SBMasterRecBrowser::isModified [private]
Definition at line 716 of file SbIObsVLBI.H'.
Referenced by SBMasterRecBrowser(), and ~SBMasterRecBrowser().
SBMaster* SBMasterRecBrowser::Master [private]
Definition at line 712 of file SbIObsVLBI.H'.
Referenced by SBMasterRecBrowser().
QListView* SBMasterRecBrowser::MRecLV [private]
Definition at line 714 of file SbIObsVLBI.H'.
Referenced by SBMasterRecBrowser().
SBVLBISet* SBMasterRecBrowser::VLBI [private]
Definition at line 711 of file SbIObsVLBI.H'.
Referenced by SBMasterRecBrowser(), and ~SBMasterRecBrowser().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.