SBMEM
NAME
SBMEM -
SYNOPSIS
#include <SbMathMEM.H>
Inherits SBAttributed'.
Public Types
enum MEMType { Type_Recursion = 0, Type_LSF = 1, Type_LSB = 2, Type_LSFnB = 3 }
enum Attributes { ignoreNotEquidistant = 1<<0, fillMissingImag = 1<<1, removeShifts = 1<<2, removeTrends = 1<<3 }
Public Member Functions
SBMEM ()
virtual ~SBMEM ()
virtual QString ClassName () const
unsigned int m () const
unsigned int n () const
SBVector * x ()
SBVector * z_r ()
SBVector * z_i ()
bool isReady () const
bool isOK () const
MEMType type () const
double dt () const
double shiftR () const
double trendR () const
double shiftI () const
double trendI () const
double sampleVar () const
void setM (unsigned int M_)
void setType (MEMType T_)
unsigned int validM ()
std::complex< double > am (unsigned int i)
void readDataFile (const QString &)
bool prepareSpectrum ()
double fN () const
double pm () const
double psd (double)
double interval () const
double fpe () const
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Member Functions
void calcA_Recusion ()
void calcA_LSForward ()
void calcA_LSBackward ()
void calcA_LSFnB ()
void createAuxVectors ()
void removeShiftsFromData ()
void removeTrendsFromData ()
double mod2 (double r, double i) const
double mod2 (std::complex< double > c) const
Protected Attributes
SBVector * X
the argument
SBVector * Z_r
real part of data
SBVector * Z_i
imagenary part of data
std::complex< double > * Am
std::complex< double > * Am_1
std::complex< double > * EFm
std::complex< double > * EFm_1
std::complex< double > * EBm
std::complex< double > * EBm_1
double Pm
double Pm_1
double DT
sample interval
bool IsOK
bool IsReady
double ShiftR
double ShiftI
double TrendR
double TrendI
bool IsMSet
unsigned int M
the length of the filter
unsigned int N
the number of points
MEMType Type
the method of a's calculation
unsigned int MAuxCreated
double SampleVar
Static Protected Attributes
static const std::complex< double > CZero = std::complex<double>(0.0, 0.0)
static const std::complex< double > CI = std::complex<double>(0.0, 1.0)
Friends
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Definition at line 45 of file SbMathMEM.H'.
Member Enumeration Documentation
enum SBMEM::Attributes
Enumerator:
ignoreNotEquidistant
assume data are equidistant
fillMissingImag
fill missing imag-column with zero
removeShifts
remove shifts from data
removeTrends
remove shifts+trends from data
Definition at line 50 of file SbMathMEM.H'.
enum SBMEM::MEMType
Enumerator:
Type_Recursion
Type_LSF
Type_LSB
Type_LSFnB
Definition at line 48 of file SbMathMEM.H'.
Constructor & Destructor Documentation
SBMEM::SBMEM ()
Definition at line 39 of file SbMathMEM.C'.
References Am, Am_1, DT, EBm, EBm_1, EFm, EFm_1, IsMSet, IsOK, IsReady, M, MAuxCreated, N, Pm, Pm_1, SampleVar, ShiftI, ShiftR, TrendI, TrendR, Type, Type_Recursion, X, Z_i, and Z_r.
SBMEM::~SBMEM () [virtual]"A destructor'.
Definition at line 67 of file SbMathMEM.C'.
References Am, Am_1, EBm, EBm_1, EFm, EFm_1, X, Z_i, and Z_r.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
std::complex<double> SBMEM::am (unsigned inti) [inline]
Definition at line 142 of file SbMathMEM.H'.
References Am, CZero, IsMSet, and M.
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBMEM::calcA_LSBackward () [protected]
Definition at line 585 of file SbMathMEM.C'.
References Am, SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), IsReady, M, N, Pm, SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), Solve(), Z_i, and Z_r.
Referenced by prepareSpectrum().
void SBMEM::calcA_LSFnB () [protected]
Definition at line 674 of file SbMathMEM.C'.
References Am, SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), IsReady, M, N, Pm, SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), Solve(), Z_i, and Z_r.
Referenced by prepareSpectrum().
void SBMEM::calcA_LSForward () [protected]
Definition at line 470 of file SbMathMEM.C'.
References Am, SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), IsReady, M, N, Pm, SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), sign(), Solve(), Z_i, and Z_r.
Referenced by prepareSpectrum().
void SBMEM::calcA_Recusion () [protected]
Definition at line 395 of file SbMathMEM.C'.
References Am, Am_1, SBVector::at(), CZero, EBm, EBm_1, EFm, EFm_1, IsReady, M, m(), mod2(), N, Pm, Pm_1, Z_i, and Z_r.
Referenced by prepareSpectrum().
virtual QString SBMEM::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBAttributed'.
Definition at line 117 of file SbMathMEM.H'.
Referenced by createAuxVectors(), prepareSpectrum(), and readDataFile().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBMEM::createAuxVectors () [protected]
Definition at line 251 of file SbMathMEM.C'.
References Am, Am_1, ClassName(), SBLog::DATA, EBm, EBm_1, EFm, EFm_1, SBLog::ERR, IsMSet, Log, M, MAuxCreated, N, and SBLog::write().
Referenced by prepareSpectrum().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
double SBMEM::dt () const [inline]
Definition at line 129 of file SbMathMEM.H'.
References DT.
Referenced by SBSpectrumAnalyserMEM::readDataFile(), and SBSpectrumAnalyserMEM::wOptions().
double SBMEM::fN () const [inline]
Definition at line 149 of file SbMathMEM.H'.
References DT, and IsOK.
Referenced by psd(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBSpectrumAnalyserMEM::resetLimits(), and SBSpectrumAnalyserMEM::setScalingCPD2CPY().
double SBMEM::fpe () const [inline]
Definition at line 153 of file SbMathMEM.H'.
References SBAttributed::isAttr(), IsOK, M, N, Pm, removeShifts, and removeTrends.
Referenced by SBSpectrumAnalyserMEM::makeAnalysis(), and SBSpectrumAnalyserMEM::redrawFPEPlot().
double SBMEM::interval () const [inline]
Definition at line 152 of file SbMathMEM.H'.
References SBVector::at(), IsOK, N, and X.
Referenced by SBSpectrumAnalyserMEM::resetLimits().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
bool SBMEM::isOK () const [inline]
Definition at line 127 of file SbMathMEM.H'.
References IsOK.
Referenced by SBSpectrumAnalyserMEM::makeAnalysis(), SBSpectrumAnalyserMEM::readDataFile(), SBSpectrumAnalyserMEM::redrawDataPlot(), and SBSpectrumAnalyserMEM::scan4FPE().
bool SBMEM::isReady () const [inline]
Definition at line 126 of file SbMathMEM.H'.
References IsReady.
Referenced by SBSpectrumAnalyserMEM::checkLine(), SBSpectrumAnalyserMEM::makeAnalysis(), SBSpectrumAnalyserMEM::redrawFPEPlot(), and SBSpectrumAnalyserMEM::redrawSpectrumPlot().
unsigned int SBMEM::m () const [inline]
Definition at line 121 of file SbMathMEM.H'.
References M.
Referenced by calcA_Recusion(), SBSpectrumAnalyserMEM::checkLine(), SBSpectrumAnalyserMEM::makeAnalysis(), SBSpectrumAnalyserMEM::redrawFPEPlot(), and validM().
double SBMEM::mod2 (doubler, doublei) const [inline, protected]
Definition at line 106 of file SbMathMEM.H'.
Referenced by calcA_Recusion(), and psd().
double SBMEM::mod2 (std::complex< double >c) const [inline, protected]
Definition at line 107 of file SbMathMEM.H'.
unsigned int SBMEM::n () const [inline]
Definition at line 122 of file SbMathMEM.H'.
References N.
Referenced by SBSpectrumAnalyserMEM::checkLine(), SBSpectrumAnalyserMEM::readDataFile(), SBSpectrumAnalyserMEM::redrawDataPlot(), and SBSpectrumAnalyserMEM::wOptions().
double SBMEM::pm () const [inline]
Definition at line 150 of file SbMathMEM.H'.
References Pm.
bool SBMEM::prepareSpectrum ()
Definition at line 357 of file SbMathMEM.C'.
References calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), ClassName(), createAuxVectors(), SBLog::DATA, SBLog::INF, IsOK, IsReady, Log, M, Type, Type_LSB, Type_LSF, Type_LSFnB, Type_Recursion, and SBLog::write().
Referenced by SBSpectrumAnalyserMEM::makeAnalysis().
double SBMEM::psd (doublef)
Definition at line 779 of file SbMathMEM.C'.
References Am, CI, CZero, DT, fN(), M, mod2(), and Pm.
Referenced by SBSpectrumAnalyserMEM::checkLine(), and SBSpectrumAnalyserMEM::redrawSpectrumPlot().
void SBMEM::readDataFile (const QString &FileName)
Definition at line 118 of file SbMathMEM.C'.
References SBVector::at(), ClassName(), SBDataSeriesEntry::data(), SBLog::DATA, SBLog::DBG, DT, SBLog::ERR, fillMissingImag, ignoreNotEquidistant, SBAttributed::isAttr(), IsMSet, IsOK, Log, M, MAuxCreated, N, removeShifts, removeShiftsFromData(), removeTrends, removeTrendsFromData(), SampleVar, SBVector::set(), ShiftI, ShiftR, SBDataSeriesEntry::t(), TrendI, TrendR, SBLog::write(), X, Z_i, and Z_r.
Referenced by SBSpectrumAnalyserMEM::readDataFile().
void SBMEM::removeShiftsFromData () [protected]
Definition at line 305 of file SbMathMEM.C'.
References SBVector::at(), N, SBVector::set(), ShiftI, ShiftR, Z_i, and Z_r.
Referenced by readDataFile().
void SBMEM::removeTrendsFromData () [protected]
Definition at line 324 of file SbMathMEM.C'.
References SBVector::at(), N, SBVector::set(), ShiftI, ShiftR, TrendI, TrendR, X, Z_i, and Z_r.
Referenced by readDataFile().
double SBMEM::sampleVar () const [inline]
Definition at line 134 of file SbMathMEM.H'.
References SampleVar.
Referenced by SBSpectrumAnalyserMEM::checkLine(), SBSpectrumAnalyserMEM::readDataFile(), and SBSpectrumAnalyserMEM::wOptions().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBMEM::setM (unsigned intM_) [inline]
Definition at line 138 of file SbMathMEM.H'.
References IsMSet, IsReady, M, and validM().
Referenced by SBSpectrumAnalyserMEM::makeAnalysis().
void SBMEM::setType (MEMTypeT_) [inline]
Definition at line 140 of file SbMathMEM.H'.
References IsReady, and Type.
Referenced by SBSpectrumAnalyserMEM::SBSpectrumAnalyserMEM(), and SBSpectrumAnalyserMEM::setMEMType().
double SBMEM::shiftI () const [inline]
Definition at line 132 of file SbMathMEM.H'.
References ShiftI.
Referenced by SBSpectrumAnalyserMEM::readDataFile(), and SBSpectrumAnalyserMEM::wOptions().
double SBMEM::shiftR () const [inline]
Definition at line 130 of file SbMathMEM.H'.
References ShiftR.
Referenced by SBSpectrumAnalyserMEM::readDataFile(), and SBSpectrumAnalyserMEM::wOptions().
double SBMEM::trendI () const [inline]
Definition at line 133 of file SbMathMEM.H'.
References TrendI.
Referenced by SBSpectrumAnalyserMEM::readDataFile(), and SBSpectrumAnalyserMEM::wOptions().
double SBMEM::trendR () const [inline]
Definition at line 131 of file SbMathMEM.H'.
References TrendR.
Referenced by SBSpectrumAnalyserMEM::readDataFile(), and SBSpectrumAnalyserMEM::wOptions().
MEMType SBMEM::type () const [inline]
Definition at line 128 of file SbMathMEM.H'.
References Type.
Referenced by SBSpectrumAnalyserMEM::wOptions().
unsigned int SBMEM::validM ()
Definition at line 232 of file SbMathMEM.C'.
References m(), N, Type, Type_LSB, Type_LSF, Type_LSFnB, and Type_Recursion.
Referenced by SBSpectrumAnalyserMEM::readDataFile(), setM(), and SBSpectrumAnalyserMEM::setMEMType().
SBVector* SBMEM::x () [inline]
Definition at line 123 of file SbMathMEM.H'.
References X.
Referenced by SBSpectrumAnalyserMEM::redrawDataPlot().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
SBVector* SBMEM::z_i () [inline]
Definition at line 125 of file SbMathMEM.H'.
References Z_i.
Referenced by SBSpectrumAnalyserMEM::redrawDataPlot().
SBVector* SBMEM::z_r () [inline]
Definition at line 124 of file SbMathMEM.H'.
References Z_r.
Referenced by SBSpectrumAnalyserMEM::redrawDataPlot().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
Member Data Documentation
std::complex<double>* SBMEM::Am [protected]
Definition at line 65 of file SbMathMEM.H'.
Referenced by am(), calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), createAuxVectors(), psd(), SBMEM(), and ~SBMEM().
std::complex<double>* SBMEM::Am_1 [protected]
Definition at line 66 of file SbMathMEM.H'.
Referenced by calcA_Recusion(), createAuxVectors(), SBMEM(), and ~SBMEM().
const std::complex< double > SBMEM::CI = std::complex<double>(0.0, 1.0) [static, protected]
Definition at line 94 of file SbMathMEM.H'.
Referenced by psd().
const std::complex< double > SBMEM::CZero = std::complex<double>(0.0, 0.0) [static, protected]
Definition at line 93 of file SbMathMEM.H'.
Referenced by am(), calcA_Recusion(), and psd().
double SBMEM::DT [protected]
sample interval
Definition at line 75 of file SbMathMEM.H'.
Referenced by dt(), fN(), psd(), readDataFile(), and SBMEM().
std::complex<double>* SBMEM::EBm [protected]
Definition at line 69 of file SbMathMEM.H'.
Referenced by calcA_Recusion(), createAuxVectors(), SBMEM(), and ~SBMEM().
std::complex<double>* SBMEM::EBm_1 [protected]
Definition at line 70 of file SbMathMEM.H'.
Referenced by calcA_Recusion(), createAuxVectors(), SBMEM(), and ~SBMEM().
std::complex<double>* SBMEM::EFm [protected]
Definition at line 67 of file SbMathMEM.H'.
Referenced by calcA_Recusion(), createAuxVectors(), SBMEM(), and ~SBMEM().
std::complex<double>* SBMEM::EFm_1 [protected]
Definition at line 68 of file SbMathMEM.H'.
Referenced by calcA_Recusion(), createAuxVectors(), SBMEM(), and ~SBMEM().
bool SBMEM::IsMSet [protected]
Definition at line 83 of file SbMathMEM.H'.
Referenced by am(), createAuxVectors(), readDataFile(), SBMEM(), and setM().
bool SBMEM::IsOK [protected]
Definition at line 76 of file SbMathMEM.H'.
Referenced by fN(), fpe(), interval(), isOK(), prepareSpectrum(), readDataFile(), and SBMEM().
bool SBMEM::IsReady [protected]
Definition at line 77 of file SbMathMEM.H'.
Referenced by calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), isReady(), prepareSpectrum(), SBMEM(), setM(), and setType().
unsigned int SBMEM::M [protected]
the length of the filter
Definition at line 85 of file SbMathMEM.H'.
Referenced by am(), calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), createAuxVectors(), fpe(), m(), prepareSpectrum(), psd(), readDataFile(), SBMEM(), and setM().
unsigned int SBMEM::MAuxCreated [protected]
Definition at line 89 of file SbMathMEM.H'.
Referenced by createAuxVectors(), readDataFile(), and SBMEM().
unsigned int SBMEM::N [protected]
the number of points
Definition at line 86 of file SbMathMEM.H'.
Referenced by calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), createAuxVectors(), fpe(), interval(), n(), readDataFile(), removeShiftsFromData(), removeTrendsFromData(), SBMEM(), and validM().
double SBMEM::Pm [protected]
Definition at line 71 of file SbMathMEM.H'.
Referenced by calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), fpe(), pm(), psd(), and SBMEM().
double SBMEM::Pm_1 [protected]
Definition at line 72 of file SbMathMEM.H'.
Referenced by calcA_Recusion(), and SBMEM().
double SBMEM::SampleVar [protected]
Definition at line 90 of file SbMathMEM.H'.
Referenced by readDataFile(), sampleVar(), and SBMEM().
double SBMEM::ShiftI [protected]
Definition at line 79 of file SbMathMEM.H'.
Referenced by readDataFile(), removeShiftsFromData(), removeTrendsFromData(), SBMEM(), and shiftI().
double SBMEM::ShiftR [protected]
Definition at line 78 of file SbMathMEM.H'.
Referenced by readDataFile(), removeShiftsFromData(), removeTrendsFromData(), SBMEM(), and shiftR().
double SBMEM::TrendI [protected]
Definition at line 81 of file SbMathMEM.H'.
Referenced by readDataFile(), removeTrendsFromData(), SBMEM(), and trendI().
double SBMEM::TrendR [protected]
Definition at line 80 of file SbMathMEM.H'.
Referenced by readDataFile(), removeTrendsFromData(), SBMEM(), and trendR().
MEMType SBMEM::Type [protected]
the method of a's calculation
Definition at line 87 of file SbMathMEM.H'.
Referenced by prepareSpectrum(), SBMEM(), setType(), type(), and validM().
SBVector* SBMEM::X [protected]
the argument
Definition at line 61 of file SbMathMEM.H'.
Referenced by interval(), readDataFile(), removeTrendsFromData(), SBMEM(), x(), and ~SBMEM().
SBVector* SBMEM::Z_i [protected]
imagenary part of data
Definition at line 63 of file SbMathMEM.H'.
Referenced by calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), readDataFile(), removeShiftsFromData(), removeTrendsFromData(), SBMEM(), z_i(), and ~SBMEM().
SBVector* SBMEM::Z_r [protected]
real part of data
Definition at line 62 of file SbMathMEM.H'.
Referenced by calcA_LSBackward(), calcA_LSFnB(), calcA_LSForward(), calcA_Recusion(), readDataFile(), removeShiftsFromData(), removeTrendsFromData(), SBMEM(), z_r(), and ~SBMEM().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.