SBMJD
NAME
SBMJD -
SYNOPSIS
#include <SbGeoTime.H>
Inherited by SBAploDRec, SBCoordinates, SBEOPEntry, SBEstimator::Group, SBObservation, SBParameterBreak, SBTime, and SBTropRecord'.
Public Types
enum Format { F_YYYYMMDD, F_DDMonYYYY, F_Short, F_Long, F_Year, F_YYMonDD, F_HHMMSS, F_YYYYMMDDSSSSSS, F_INTERNAL, F_YYYYMMDDHHMMSSSS, F_DateShort, F_TimeShort, F_TimeVShort, F_ECCDAT, F_MJD, F_UNIX, F_SINEX, F_SINEX_S }
Public Member Functions
SBMJD ()
SBMJD (const SBMJD &MJD)
SBMJD (long double MJD)
SBMJD (int d, long double t)
SBMJD (int, int, int, int=0, int=0, double=0.0)
SBMJD (short[5])
virtual ~SBMJD ()
virtual QString ClassName () const
virtual void setMJD (int, int, int, int=0, int=0, double=0.0, bool=TRUE)
virtual void setMJD (Format, QString, bool=TRUE)
virtual void setDate (int Date_)
virtual void setTime (long double Time_)
virtual QString toString (Format=F_Short) const
virtual bool isGood ()
virtual operator long double () const
virtual SBMJD & operator= (const SBMJD &)
virtual SBMJD & operator= (long double)
virtual bool operator== (const SBMJD &) const
virtual bool operator!= (const SBMJD &) const
virtual bool operator< (const SBMJD &) const
virtual bool operator<= (const SBMJD &) const
virtual bool operator> (const SBMJD &) const
virtual bool operator> (double) const
virtual bool operator>= (const SBMJD &) const
virtual SBMJD & operator+= (const SBMJD &MJD)
virtual SBMJD & operator-= (const SBMJD &MJD)
int date () const
long double time () const
int year () const
int month () const
int hour () const
int min () const
double sec () const
QString month2Str () const
int day () const
int dayOfYear () const
int dayOfWeek () const
QString dayOfWeek2Str () const
Static Public Member Functions
static int MJD_date (int, int, int)
static long double MJD_time (int, int, double)
static void MJD_rev (int, long double, int &, int &, int &, int &, int &, double &)
static SBMJD currentMJD ()
Static Protected Attributes
static const char * monthNames []
static const char * weekdayNames []
Private Attributes
int Date
long double Time
Friends
SBMJD operator+ (const SBMJD &, const SBMJD &)
SBMJD operator+ (const SBMJD &, long double)
SBMJD operator+ (const SBMJD &, double)
SBMJD operator+ (const SBMJD &, float)
SBMJD operator+ (long double, const SBMJD &)
SBMJD operator+ (double, const SBMJD &)
SBMJD operator+ (float, const SBMJD &)
SBMJD operator- (const SBMJD &, const SBMJD &)
SBMJD operator- (const SBMJD &, long double)
SBMJD operator- (const SBMJD &, double)
SBMJD operator- (long double, const SBMJD &)
SBMJD operator- (int, const SBMJD &)
QDataStream & operator<< (QDataStream &, const SBMJD &)
QDataStream & operator>> (QDataStream &, SBMJD &)
Detailed Description
Definition at line 46 of file SbGeoTime.H'.
Member Enumeration Documentation
enum SBMJD::Format
Enumerator:
F_YYYYMMDD
F_DDMonYYYY
F_Short
F_Long
F_Year
F_YYMonDD
F_HHMMSS
F_YYYYMMDDSSSSSS
F_INTERNAL
F_YYYYMMDDHHMMSSSS
F_DateShort
F_TimeShort
F_TimeVShort
F_ECCDAT
F_MJD
F_UNIX
F_SINEX
F_SINEX_S
Definition at line 49 of file SbGeoTime.H'.
Constructor & Destructor Documentation
SBMJD::SBMJD () [inline]
Definition at line 67 of file SbGeoTime.H'.
References Date, and Time.
Referenced by dayOfWeek(), operator>(), SBTime::TAI(), SBTime::TDB(), SBTime::TT(), and SBTime::UT1().
SBMJD::SBMJD (const SBMJD &MJD) [inline]
Definition at line 68 of file SbGeoTime.H'.
References Date, and Time.
SBMJD::SBMJD (long doubleMJD) [inline]
Definition at line 69 of file SbGeoTime.H'.
References Date, and Time.
SBMJD::SBMJD (intd, long doublet) [inline]
Definition at line 70 of file SbGeoTime.H'.
References Date, and Time.
SBMJD::SBMJD (intYear, intMonth, intDay, intHour = 0, intMin = 0, doubleSec = 0.0)
Definition at line 53 of file SbGeoTime.C'.
References setMJD().
SBMJD::SBMJD (shortdate[5])
Definition at line 58 of file SbGeoTime.C'.
References setMJD().
virtual SBMJD::~SBMJD () [inline, virtual]
Definition at line 73 of file SbGeoTime.H'.
Member Function Documentation
virtual QString SBMJD::ClassName () const [inline, virtual]
Reimplemented in SBObsVLBIEntry, SBCoordinates, SBTropRecord, SBTime, SBParameterBreak, SBEOPEntry, SBObservation, and SBAploDRec'.
Definition at line 74 of file SbGeoTime.H'.
Referenced by setMJD().
SBMJD SBMJD::currentMJD () [static]
Definition at line 134 of file SbGeoTime.C'.
Referenced by operator<<(), SBRunManager::process_m1(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and writeNormalEquationSystem().
int SBMJD::date () const [inline]
Definition at line 121 of file SbGeoTime.H'.
References Date.
Referenced by SBNutation::calcGST(), SBTime::DefineTAI_UTC(), SBRunManager::loadVLBISession_m1(), operator<<(), operator>>(), SBTestEphem::recalc(), and SBTime::setUTC().
int SBMJD::day () const
Definition at line 208 of file SbGeoTime.C'.
References Date, MJD_rev(), and Time.
Referenced by SBTest::createWidgets(), operator<<(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
int SBMJD::dayOfWeek () const
Definition at line 225 of file SbGeoTime.C'.
References Date, and SBMJD().
Referenced by dayOfWeek2Str().
QString SBMJD::dayOfWeek2Str () const
Definition at line 231 of file SbGeoTime.C'.
References Date, dayOfWeek(), and weekdayNames.
Referenced by toString().
int SBMJD::dayOfYear () const
Definition at line 220 of file SbGeoTime.C'.
References Date, MJD_date(), and year().
Referenced by SBHMf_NMF::operator()(), and toString().
int SBMJD::hour () const
Definition at line 167 of file SbGeoTime.C'.
References Date, MJD_rev(), and Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
virtual bool SBMJD::isGood () [inline, virtual]
Definition at line 87 of file SbGeoTime.H'.
References Date, and Time.
Referenced by SBSourceEditor::acquireData(), SBAploChunk::import(), SBEcc::importEccDat(), operator>>(), and SBVLBISession::parseObsDumpString().
int SBMJD::min () const
Definition at line 179 of file SbGeoTime.C'.
References Date, MJD_rev(), and Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), setMJD(), and toString().
int SBMJD::MJD_date (inty, intm, intd) [static]
Definition at line 72 of file SbGeoTime.C'.
Referenced by dayOfYear(), and setMJD().
void SBMJD::MJD_rev (intdate_, long doubletime_, int &y, int &m, int &d, int &hr, int &mi, double &se) [static]
Definition at line 95 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by day(), hour(), min(), month(), sec(), toString(), and year().
long double SBMJD::MJD_time (intHour, intMin, doubleSec) [static]
Definition at line 90 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by setMJD().
int SBMJD::month () const
Definition at line 155 of file SbGeoTime.C'.
References Date, MJD_rev(), and Time.
Referenced by SBTest::createWidgets(), month2Str(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
QString SBMJD::month2Str () const
Definition at line 203 of file SbGeoTime.C'.
References month(), and monthNames.
Referenced by operator<<().
virtual SBMJD::operator long double () const [inline, virtual]
Definition at line 89 of file SbGeoTime.H'.
References Date, and Time.
bool SBMJD::operator!= (const SBMJD &MJD) const [inline, virtual]
Definition at line 206 of file SbGeoTime.H'.
References Date, and Time.
SBMJD & SBMJD::operator+= (const SBMJD &MJD) [inline, virtual]
Definition at line 254 of file SbGeoTime.H'.
References Date, and Time.
SBMJD & SBMJD::operator-= (const SBMJD &MJD) [inline, virtual]
Definition at line 262 of file SbGeoTime.H'.
References Date, and Time.
bool SBMJD::operator< (const SBMJD &MJD) const [inline, virtual]
Definition at line 211 of file SbGeoTime.H'.
References Date, and Time.
bool SBMJD::operator<= (const SBMJD &MJD) const [inline, virtual]
Definition at line 217 of file SbGeoTime.H'.
References Date, and Time.
SBMJD & SBMJD::operator= (const SBMJD &MJD) [inline, virtual]
Definition at line 240 of file SbGeoTime.H'.
References Date, and Time.
Referenced by SBTime::setUTC().
SBMJD & SBMJD::operator= (long doubleMJD) [inline, virtual]
Definition at line 247 of file SbGeoTime.H'.
References Date, and Time.
bool SBMJD::operator== (const SBMJD &MJD) const [inline, virtual]
Definition at line 201 of file SbGeoTime.H'.
References Date, and Time.
bool SBMJD::operator> (const SBMJD &MJD) const [inline, virtual]
Definition at line 223 of file SbGeoTime.H'.
References Date, and Time.
bool SBMJD::operator> (doubled) const [inline, virtual]
Definition at line 229 of file SbGeoTime.H'.
References SBMJD().
bool SBMJD::operator>= (const SBMJD &MJD) const [inline, virtual]
Definition at line 234 of file SbGeoTime.H'.
References Date, and Time.
double SBMJD::sec () const
Definition at line 191 of file SbGeoTime.C'.
References Date, MJD_rev(), and Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), setMJD(), and toString().
virtual void SBMJD::setDate (intDate_) [inline, virtual]
Definition at line 81 of file SbGeoTime.H'.
References Date.
Referenced by SBAploChunk::import().
void SBMJD::setMJD (intYear, intMonth, intDay, intHour = 0, intMin = 0, doubleSec = 0.0, bool = TRUE) [virtual]
Definition at line 64 of file SbGeoTime.C'.
References Date, MJD_date(), MJD_time(), and Time.
Referenced by SBStuffEOPs::accept(), SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBEcc::importEccDat(), operator>>(), SBVLBISession::parseObsDumpString(), SBTest::recalc(), SBStationInfo::restoreUserInfo(), SBMJD(), and setMJD().
void SBMJD::setMJD (FormatF, QStrings, boolisReset = TRUE) [virtual]
Definition at line 357 of file SbGeoTime.C'.
References ClassName(), Date, SBLog::ERR, F_DateShort, F_DDMonYYYY, F_ECCDAT, F_HHMMSS, F_INTERNAL, F_Long, F_Short, F_SINEX, F_SINEX_S, F_TimeShort, F_TimeVShort, F_Year, F_YYMonDD, F_YYYYMMDD, F_YYYYMMDDHHMMSSSS, SBLog::INF, Log, min(), MJD_date(), monthNames, sec(), setMJD(), Time, SBLog::TIME, SBLog::write(), and SBLog::WRN.
virtual void SBMJD::setTime (long doubleTime_) [inline, virtual]
Definition at line 82 of file SbGeoTime.H'.
References Date, and Time.
Referenced by SBAploChunk::import().
long double SBMJD::time () const [inline]
Definition at line 122 of file SbGeoTime.H'.
References Time.
Referenced by SBOceanTideLd::ARG_IERS(), SBNutation::calcGST(), and SBTestEOP::fillData4Plotting().
QString SBMJD::toString (FormatF = F_Short) const [virtual]
Definition at line 243 of file SbGeoTime.C'.
References Date, DAY2SEC, dayOfWeek2Str(), dayOfYear(), F_DateShort, F_DDMonYYYY, F_ECCDAT, F_HHMMSS, F_INTERNAL, F_Long, F_MJD, F_Short, F_SINEX, F_SINEX_S, F_TimeShort, F_TimeVShort, F_UNIX, F_Year, F_YYMonDD, F_YYYYMMDD, F_YYYYMMDDHHMMSSSS, F_YYYYMMDDSSSSSS, min(), MJD_rev(), monthNames, sec(), Time, TUnix0, TZero, and year().
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBEphem::calcI(), SBRunManager::checkParameterLists(), SBEOP::checkRanges(), SBStuffEOPs::createInfoGroup(), SBTestFrame::createWidget4Test(), SBTest::createWidgets(), SBStationEditor::delCoordinates(), SBStuffStationsEcc::deleteEntry(), SBStaParsEditor::deleteEntry(), SBEOP::dEps(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), SBEOP::dLOD(), SBEOP::dPsi(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBPlotArea::drawXmjdTics(), SBDBHHistTriplet::dump(), SBDBHStartBlock::dump(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBVLBIPreProcess::fillSessAttr(), SBEstimator::GroupList::find(), SBStochParameter::find(), SBAploEphem::getReady(), SBEphem::import(), SBEstimator::GroupList::inSort(), SBEOP::interpolateEOPs(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBSolutionBatchLI::key(), SBObsVLBIStatRecordLI::key(), SBEccListItem::key(), SBCoordsListItem::key(), SBAploHeaderLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBAploHeader::name(), SBEphem::openFile(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), operator<<(), operator>>(), SBEOP::prepare4Date(), SBTest::recalc(), SBStationEcc::registerEcc(), SBEstimator::GroupList::remove(), SBParameterList::report(), SBStochParameter::report(), SBStuffAplo::SBStuffAplo(), SBStuffEphem::SBStuffEphem(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), SBTime::setUTC(), sinex_HeaderLine(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_SiteEccentricityBlock(), sinex_SolutionEpochsBlock(), sinex_tro_HeaderLine(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBVLBIObsPPLI::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBObsVLBIStatRecordLI::text(), SBEccListItem::text(), SBVLBIObsLI::text(), SBCoordsListItem::text(), SBAploHeaderLI::text(), SBClockBreakLI::text(), SBParameter::timeStamp(), SBStuffEOPs::updateEOP(), SBStuffEphem::updateEphem(), SBStuffAplo::updateEphem(), SBVLBIPreProcess::wAttributes(), SBVLBISessionEditor::wParameters(), and SBSourceEditor::wStats().
int SBMJD::year () const
Definition at line 143 of file SbGeoTime.C'.
References Date, MJD_rev(), and Time.
Referenced by SBVLBISesInfo::checkPath(), SBTest::createWidgets(), dayOfYear(), SBVLBISesInfo::fileName(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), and toString().
Friends And Related Function Documentation
SBMJD operator+ (const SBMJD &A, const SBMJD &B) [friend]
Definition at line 270 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, long doubleb) [friend]
Definition at line 275 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, doubleb) [friend]
Definition at line 280 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, floatb) [friend]
Definition at line 285 of file SbGeoTime.H'.
SBMJD operator+ (long doublea, const SBMJD &B) [friend]
Definition at line 290 of file SbGeoTime.H'.
SBMJD operator+ (doublea, const SBMJD &B) [friend]
Definition at line 295 of file SbGeoTime.H'.
SBMJD operator+ (floata, const SBMJD &B) [friend]
Definition at line 300 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, const SBMJD &B) [friend]
Definition at line 305 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, long doubleb) [friend]
Definition at line 310 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, doubleb) [friend]
Definition at line 315 of file SbGeoTime.H'.
SBMJD operator- (long doublea, const SBMJD &B) [friend]
Definition at line 320 of file SbGeoTime.H'.
SBMJD operator- (inta, const SBMJD &B) [friend]
Definition at line 325 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBMJD &MJD) [friend]
Definition at line 330 of file SbGeoTime.H'.
QDataStream& operator>> (QDataStream &s, SBMJD &MJD) [friend]
Definition at line 337 of file SbGeoTime.H'.
Member Data Documentation
int SBMJD::Date [private]
Definition at line 59 of file SbGeoTime.H'.
Referenced by date(), day(), dayOfWeek(), dayOfWeek2Str(), dayOfYear(), hour(), isGood(), min(), month(), operator long double(), operator!=(), operator+=(), operator-=(), operator<(), operator<<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), operator>>(), SBMJD(), sec(), setDate(), setMJD(), setTime(), toString(), and year().
const char * SBMJD::monthNames [static, protected]"Initial value:
 
{
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
}
Definition at line 63 of file SbGeoTime.H'.
Referenced by month2Str(), setMJD(), and toString().
long double SBMJD::Time [private]
Definition at line 60 of file SbGeoTime.H'.
Referenced by day(), hour(), isGood(), min(), month(), operator long double(), operator!=(), operator+=(), operator-=(), operator<(), operator<<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), operator>>(), SBMJD(), sec(), setMJD(), setTime(), time(), toString(), and year().
const char * SBMJD::weekdayNames [static, protected]"Initial value:
{
  'Mon','Tue','Wed','Thu','Fri','Sat','Sun'
}
Definition at line 64 of file SbGeoTime.H'.
Referenced by dayOfWeek2Str().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.