SBModelEditor
NAME
SBModelEditor -
SYNOPSIS
#include <SbIProject.H>
Inherits SBTabDialog'.
Public Member Functions
SBModelEditor (SBConfig *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBModelEditor ()
virtual QString ClassName () const
Protected Slots
virtual void makeApply ()
virtual void makeDefault ()
void solidTideIERS92 (bool)
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Member Functions
virtual void acquireData ()
QWidget * wSysTransform ()
QWidget * wLightPropagation ()
QWidget * wSolidTide ()
QWidget * wEOPs ()
QWidget * wNutation ()
QWidget * wPlateMotion ()
QWidget * wRefraction ()
QWidget * wDataProcessing ()
QWidget * wSolutionReports ()
Private Attributes
SBConfig * Cfg
SBProject * Project
bool isModified
bool isGlobal
QString Str
QRadioButton * rbSysTransform [2]
QCheckBox * cbUseAltStations
QCheckBox * cbUseAltSources
QCheckBox * cbUseAltEOPs
QLineEdit * leAltStations
QLineEdit * leAltSources
QLineEdit * leAltEOPs
QRadioButton * rbEphem [3]
QCheckBox * cbIsHO
QLineEdit * leHOThreshold
QCheckBox * cbBody [11]
QGroupBox * gbSTIERS96
QButtonGroup * bgSTOrder
QRadioButton * rbSTide [2]
QCheckBox * cbPTide
QRadioButton * rbDegree [2]
QCheckBox * cbAnelastic
QCheckBox * cbLatDepend
QRadioButton * rbEOPDiurn [6]
QRadioButton * rbEOPDiurnAtm [2]
QRadioButton * rbEOPDiurnNonTidal [2]
QLineEdit * leEOPNInterp
QCheckBox * cbEOP_IAU2K_XY
QCheckBox * cbEOPResrerved_1
QRadioButton * rbNutModel [3]
QRadioButton * rbNutEquinox [3]
QCheckBox * cbNutGeod
QRadioButton * rbTPMModel [3]
QCheckBox * cbStatVel
QCheckBox * cbRB2Plates
QCheckBox * cbAplo
QRadioButton * rbDryZenith [3]
QRadioButton * rbWetZenith [3]
QRadioButton * rbDryMap [6]
QRadioButton * rbWetMap [6]
QCheckBox * cbAxissAlt
QCheckBox * cbRB2NMF
QLineEdit * eDelayQThreshold
QLineEdit * eRateQThreshold
QCheckBox * cbUseDelay
QCheckBox * cbUseRate
QCheckBox * cbUseBadIon
QCheckBox * cbGenerateDSINEXes
QCheckBox * cbReportMaps
QCheckBox * cbReportTRF_Changes
QCheckBox * cbReportCRF_Changes
QCheckBox * cbReportCRF
QCheckBox * cbReportTRF_SINEX
QCheckBox * cbReportEOP
QCheckBox * cbReportTechDesc
QCheckBox * cbReportNormalEqs
QCheckBox * cbReportNormalEqsSta
QCheckBox * cbReportNormalEqsSou
QCheckBox * cbReportNormalEqsEOP
QCheckBox * cbReportTroposhere
QLineEdit * leTropSamplInterval
QLineEdit * leTropStartSec
Detailed Description
Definition at line 214 of file SbIProject.H'.
Constructor & Destructor Documentation
SBModelEditor::SBModelEditor (SBConfig *Cfg_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 711 of file SbIProject.C'.
References Cfg, SBProject::cfg(), isGlobal, isModified, SBSetUp::loadProject(), makeApply(), makeDefault(), SBNamed::name(), Project, SetUp, wDataProcessing(), wEOPs(), wLightPropagation(), wNutation(), wPlateMotion(), wRefraction(), wSolidTide(), wSolutionReports(), and wSysTransform().
SBModelEditor::~SBModelEditor () [virtual]
Definition at line 748 of file SbIProject.C'.
References Cfg, Config, isGlobal, isModified, Project, SBSetUp::saveProject(), SBProject::setCfg(), and SetUp.
Member Function Documentation
void SBModelEditor::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 1552 of file SbIProject.C'.
References SBConfig::altEOPs(), SBConfig::altSources(), SBConfig::altStations(), cbAnelastic, cbAplo, cbAxissAlt, cbBody, cbEOP_IAU2K_XY, cbEOPResrerved_1, cbGenerateDSINEXes, cbIsHO, cbLatDepend, cbNutGeod, cbPTide, cbRB2NMF, cbRB2Plates, cbReportCRF, cbReportCRF_Changes, cbReportEOP, cbReportMaps, cbReportNormalEqs, cbReportNormalEqsEOP, cbReportNormalEqsSou, cbReportNormalEqsSta, cbReportTechDesc, cbReportTRF_Changes, cbReportTRF_SINEX, cbReportTroposhere, cbStatVel, cbUseAltEOPs, cbUseAltSources, cbUseAltStations, cbUseBadIon, cbUseDelay, cbUseRate, Cfg, DEG2RAD, SBConfig::dUFlagThreshold(), eDelayQThreshold, SBConfig::EDM_Gipson1995, SBConfig::EDM_GSFC95, SBConfig::EDM_HD1994, SBConfig::EDM_JPL92, SBConfig::EDM_NONE, SBConfig::EDM_Ray1995, SBConfig::EDMA_BBP, SBConfig::EDMA_NONE, SBConfig::EDMNT_NONE, SBConfig::EDMNT_Viron, SBConfig::EM_LEDE200, SBConfig::EM_LEDE403, SBConfig::EM_LEDE405, SBConfig::eopDiurnal(), SBConfig::eopDiurnalAtm(), SBConfig::eopDiurnalNonTidal(), SBConfig::eopNumIntrplPoints(), SBConfig::ephemModel(), eRateQThreshold, SBConfig::gravHOThreshold(), SBConfig::isAltAxsCorr(), SBConfig::isEOP_IAU2K_XY(), SBConfig::isEOPResrerved_1(), SBConfig::isEphBody(), SBConfig::isGenerateDSINEXes(), isGlobal, SBConfig::isGravDelayHO(), isModified, SBConfig::isNeedGeodNut(), SBConfig::isRemovePermTide(), SBConfig::isRollBack2NMF(), SBConfig::isRollBack2Plates(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), SBConfig::isUseAploEphem(), SBConfig::isUseBadIon(), SBConfig::isUseDelay(), SBConfig::isUseRate(), SBConfig::isUseStationVelocity(), leAltEOPs, leAltSources, leAltStations, leEOPNInterp, leHOThreshold, leTropSamplInterval, leTropStartSec, SBConfig::NEE_IERS92, SBConfig::NEE_IERS96, SBConfig::NEE_SOVERS, SBConfig::NM_IAU1980, SBConfig::NM_IAU1996, SBConfig::NM_IAU2000, SBConfig::nutEquinox(), SBConfig::nutModel(), SBConfig::plateMotion(), SBConfig::PM_NNR_NUVEL1A, SBConfig::PM_NONE, SBConfig::PM_NUVEL1A, SBConfig::qCodeThreshold(), rbDegree, rbDryMap, rbDryZenith, rbEOPDiurn, rbEOPDiurnAtm, rbEOPDiurnNonTidal, rbEphem, rbNutEquinox, rbNutModel, rbSTide, rbSysTransform, rbTPMModel, rbWetMap, rbWetZenith, SBConfig::RDM_CfA2p2, SBConfig::RDM_Chao, SBConfig::RDM_Ifadis, SBConfig::RDM_MTT, SBConfig::RDM_NMFH2, SBConfig::RDM_NMFW2, SBConfig::RDM_NONE, SBConfig::RDZ_Hopfield, SBConfig::RDZ_NONE, SBConfig::RDZ_Saastamoinen, SBConfig::refrDryMapping(), SBConfig::refrDryZenith(), SBConfig::refrWetMapping(), SBConfig::refrWetZenith(), SBConfig::reportCRF(), SBConfig::reportCRF_Changes(), SBConfig::reportEOP(), SBConfig::reportMaps(), SBConfig::reportNormalEqs(), SBConfig::reportNormalEqsEOPs(), SBConfig::reportNormalEqsSRCs(), SBConfig::reportNormalEqsSTCs(), SBConfig::reportTechDesc(), SBConfig::reportTRF_Changes(), SBConfig::reportTRF_SINEX(), SBConfig::reportTroposhere(), SBConfig::RWM_Chao, SBConfig::RWM_Ifadis, SBConfig::RWM_MTT, SBConfig::RWM_NONE, SBConfig::RWZ_Hopfield, SBConfig::RWZ_NONE, SBConfig::RWZ_Saastamoinen, SBConfig::setAltEOPs(), SBConfig::setAltSources(), SBConfig::setAltStations(), SBConfig::setDUFlagThreshold(), SBConfig::setEopDiurnal(), SBConfig::setEopDiurnalAtm(), SBConfig::setEopDiurnalNonTidal(), SBConfig::setEOPNumIntrplPoints(), SBConfig::setEphemModel(), SBConfig::setGravHOThreshold(), SBConfig::setIsAltAxsCorr(), SBConfig::setIsEOP_IAU2K_XY(), SBConfig::setIsEOPResrerved_1(), SBConfig::setIsEphBody(), SBConfig::setIsGenerateDSINEXes(), SBConfig::setIsGravDelayHO(), SBConfig::setIsNeedGeodNut(), SBConfig::setIsRemovePermTide(), SBConfig::setIsRollBack2NMF(), SBConfig::setIsRollBack2Plates(), SBConfig::setIsSolidTideAnelastic(), SBConfig::setIsSolidTideLatDepend(), SBConfig::setIsUseAploEphem(), SBConfig::setIsUseBadIon(), SBConfig::setIsUseDelay(), SBConfig::setIsUseRate(), SBConfig::setIsUseStationVelocity(), SBConfig::setNutEquinox(), SBConfig::setNutModel(), SBConfig::setPlateMotion(), SBConfig::setQCodeThreshold(), SBConfig::setRefrDryMapping(), SBConfig::setRefrDryZenith(), SBConfig::setRefrWetMapping(), SBConfig::setRefrWetZenith(), SBConfig::setReportCRF(), SBConfig::setReportCRF_Changes(), SBConfig::setReportEOP(), SBConfig::setReportMaps(), SBConfig::setReportNormalEqs(), SBConfig::setReportNormalEqsEOPs(), SBConfig::setReportNormalEqsSRCs(), SBConfig::setReportNormalEqsSTCs(), SBConfig::setReportTechDesc(), SBConfig::setReportTRF_Changes(), SBConfig::setReportTRF_SINEX(), SBConfig::setReportTroposhere(), SBConfig::setSolidTideDegree(), SBConfig::setSolidTideLd(), SBConfig::setSysTransform(), SBConfig::setTropSamplInterval(), SBConfig::setTropStartSec(), SBConfig::setUseAltEOPs(), SBConfig::setUseAltSources(), SBConfig::setUseAltStations(), SBConfig::solidTideDegree(), SBConfig::solidTideLd(), SBConfig::ST_IERS92, SBConfig::ST_IERS96, SBConfig::STDEGREE_2, SBConfig::STDEGREE_3, Str, SBConfig::STR_Classic, SBConfig::STR_NRO, SBConfig::sysTransform(), SBConfig::tropSamplInterval(), SBConfig::tropStartSec(), SBConfig::useAltEOPs(), SBConfig::useAltSources(), and SBConfig::useAltStations().
Referenced by makeApply().
virtual QString SBModelEditor::ClassName () const [inline, virtual]
Definition at line 220 of file SbIProject.H'.
Referenced by makeApply(), and makeDefault().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
void SBModelEditor::makeApply () [protected, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 837 of file SbIProject.C'.
References acquireData(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by SBModelEditor().
void SBModelEditor::makeDefault () [protected, virtual, slot]
Definition at line 763 of file SbIProject.C'.
References SBConfig::altEOPs(), SBConfig::altSources(), SBConfig::altStations(), cbAnelastic, cbAplo, cbAxissAlt, cbBody, cbEOP_IAU2K_XY, cbEOPResrerved_1, cbIsHO, cbLatDepend, cbNutGeod, cbPTide, cbRB2NMF, cbRB2Plates, cbReportCRF, cbReportCRF_Changes, cbReportEOP, cbReportMaps, cbReportNormalEqs, cbReportNormalEqsEOP, cbReportNormalEqsSou, cbReportNormalEqsSta, cbReportTechDesc, cbReportTRF_Changes, cbReportTRF_SINEX, cbReportTroposhere, cbStatVel, cbUseAltEOPs, cbUseAltSources, cbUseAltStations, cbUseDelay, cbUseRate, Cfg, ClassName(), SBLog::DBG, DefaultConfig, SBConfig::dUFlagThreshold(), eDelayQThreshold, SBConfig::eopDiurnal(), SBConfig::eopDiurnalAtm(), SBConfig::eopDiurnalNonTidal(), SBConfig::eopNumIntrplPoints(), SBConfig::ephemModel(), eRateQThreshold, SBConfig::gravHOThreshold(), SBLog::INTERFACE, SBConfig::isAltAxsCorr(), SBConfig::isEOP_IAU2K_XY(), SBConfig::isEOPResrerved_1(), SBConfig::isEphBody(), isGlobal, SBConfig::isGravDelayHO(), SBConfig::isNeedGeodNut(), SBConfig::isRemovePermTide(), SBConfig::isRollBack2NMF(), SBConfig::isRollBack2Plates(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), SBConfig::isUseAploEphem(), SBConfig::isUseDelay(), SBConfig::isUseRate(), SBConfig::isUseStationVelocity(), leAltEOPs, leAltSources, leAltStations, leEOPNInterp, leHOThreshold, leTropSamplInterval, leTropStartSec, Log, SBConfig::nutEquinox(), SBConfig::nutModel(), SBConfig::plateMotion(), SBConfig::qCodeThreshold(), RAD2DEG, rbDegree, rbDryMap, rbDryZenith, rbEOPDiurn, rbEOPDiurnAtm, rbEOPDiurnNonTidal, rbEphem, rbNutEquinox, rbNutModel, rbSTide, rbSysTransform, rbTPMModel, rbWetMap, rbWetZenith, SBConfig::refrDryMapping(), SBConfig::refrDryZenith(), SBConfig::refrWetMapping(), SBConfig::refrWetZenith(), SBConfig::reportCRF(), SBConfig::reportCRF_Changes(), SBConfig::reportEOP(), SBConfig::reportMaps(), SBConfig::reportNormalEqs(), SBConfig::reportNormalEqsEOPs(), SBConfig::reportNormalEqsSRCs(), SBConfig::reportNormalEqsSTCs(), SBConfig::reportTechDesc(), SBConfig::reportTRF_Changes(), SBConfig::reportTRF_SINEX(), SBConfig::reportTroposhere(), SBConfig::solidTideDegree(), SBConfig::solidTideLd(), Str, SBConfig::sysTransform(), SBConfig::tropSamplInterval(), SBConfig::tropStartSec(), SBConfig::useAltEOPs(), SBConfig::useAltSources(), SBConfig::useAltStations(), and SBLog::write().
Referenced by SBModelEditor().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBModelEditor::solidTideIERS92 (boolon) [protected, slot]
Definition at line 1049 of file SbIProject.C'.
References bgSTOrder, cbAnelastic, cbLatDepend, gbSTIERS96, and rbDegree.
Referenced by wSolidTide().
QWidget * SBModelEditor::wDataProcessing () [private]
Definition at line 1356 of file SbIProject.C'.
References cbGenerateDSINEXes, cbUseBadIon, cbUseDelay, cbUseRate, Cfg, SBConfig::dUFlagThreshold(), eDelayQThreshold, eRateQThreshold, SBConfig::isGenerateDSINEXes(), SBConfig::isUseBadIon(), SBConfig::isUseDelay(), SBConfig::isUseRate(), and SBConfig::qCodeThreshold().
Referenced by SBModelEditor().
QWidget * SBModelEditor::wEOPs () [private]
Definition at line 1059 of file SbIProject.C'.
References cbEOP_IAU2K_XY, cbEOPResrerved_1, Cfg, SBConfig::eopDiurnal(), SBConfig::eopDiurnalAtm(), SBConfig::eopDiurnalNonTidal(), SBConfig::eopNumIntrplPoints(), SBConfig::isEOP_IAU2K_XY(), SBConfig::isEOPResrerved_1(), leEOPNInterp, rbEOPDiurn, rbEOPDiurnAtm, rbEOPDiurnNonTidal, and Str.
Referenced by SBModelEditor().
QWidget * SBModelEditor::wLightPropagation () [private]
Definition at line 917 of file SbIProject.C'.
References cbBody, cbIsHO, Cfg, SBConfig::ephemModel(), SBConfig::gravHOThreshold(), SBConfig::isEphBody(), SBConfig::isGravDelayHO(), leHOThreshold, RAD2DEG, rbEphem, and Str.
Referenced by SBModelEditor().
QWidget * SBModelEditor::wNutation () [private]
Definition at line 1149 of file SbIProject.C'.
References cbNutGeod, Cfg, SBConfig::isNeedGeodNut(), SBConfig::nutEquinox(), SBConfig::nutModel(), rbNutEquinox, and rbNutModel.
Referenced by SBModelEditor().
QWidget * SBModelEditor::wPlateMotion () [private]
Definition at line 1198 of file SbIProject.C'.
References cbAplo, cbRB2Plates, cbStatVel, Cfg, SBConfig::isRollBack2Plates(), SBConfig::isUseAploEphem(), SBConfig::isUseStationVelocity(), SBConfig::plateMotion(), SBConfig::PM_NONE, and rbTPMModel.
Referenced by SBModelEditor().
QWidget * SBModelEditor::wRefraction () [private]
Definition at line 1251 of file SbIProject.C'.
References cbAxissAlt, cbRB2NMF, Cfg, SBConfig::isAltAxsCorr(), SBConfig::isRollBack2NMF(), rbDryMap, rbDryZenith, rbWetMap, rbWetZenith, SBConfig::refrDryMapping(), SBConfig::refrDryZenith(), SBConfig::refrWetMapping(), and SBConfig::refrWetZenith().
Referenced by SBModelEditor().
QWidget * SBModelEditor::wSolidTide () [private]
Definition at line 988 of file SbIProject.C'.
References bgSTOrder, cbAnelastic, cbLatDepend, cbPTide, Cfg, gbSTIERS96, SBConfig::isRemovePermTide(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), rbDegree, rbSTide, SBConfig::solidTideDegree(), solidTideIERS92(), and SBConfig::solidTideLd().
Referenced by SBModelEditor().
QWidget * SBModelEditor::wSolutionReports () [private]
Definition at line 1444 of file SbIProject.C'.
References cbReportCRF, cbReportCRF_Changes, cbReportEOP, cbReportMaps, cbReportNormalEqs, cbReportNormalEqsEOP, cbReportNormalEqsSou, cbReportNormalEqsSta, cbReportTechDesc, cbReportTRF_Changes, cbReportTRF_SINEX, cbReportTroposhere, Cfg, leTropSamplInterval, leTropStartSec, SBConfig::reportCRF(), SBConfig::reportCRF_Changes(), SBConfig::reportEOP(), SBConfig::reportMaps(), SBConfig::reportNormalEqs(), SBConfig::reportNormalEqsEOPs(), SBConfig::reportNormalEqsSRCs(), SBConfig::reportNormalEqsSTCs(), SBConfig::reportTechDesc(), SBConfig::reportTRF_Changes(), SBConfig::reportTRF_SINEX(), SBConfig::reportTroposhere(), SBConfig::tropSamplInterval(), and SBConfig::tropStartSec().
Referenced by SBModelEditor().
QWidget * SBModelEditor::wSysTransform () [private]
Definition at line 844 of file SbIProject.C'.
References SBConfig::altEOPs(), SBConfig::altSources(), SBConfig::altStations(), cbUseAltEOPs, cbUseAltSources, cbUseAltStations, Cfg, isGlobal, leAltEOPs, leAltSources, leAltStations, rbSysTransform, SBConfig::sysTransform(), SBConfig::useAltEOPs(), SBConfig::useAltSources(), and SBConfig::useAltStations().
Referenced by SBModelEditor().
Member Data Documentation
QButtonGroup* SBModelEditor::bgSTOrder [private]
Definition at line 260 of file SbIProject.H'.
Referenced by solidTideIERS92(), and wSolidTide().
QCheckBox* SBModelEditor::cbAnelastic [private]
Definition at line 264 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), solidTideIERS92(), and wSolidTide().
QCheckBox* SBModelEditor::cbAplo [private]
Definition at line 287 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wPlateMotion().
QCheckBox* SBModelEditor::cbAxissAlt [private]
Definition at line 295 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wRefraction().
QCheckBox* SBModelEditor::cbBody[11] [private]
Definition at line 255 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wLightPropagation().
QCheckBox* SBModelEditor::cbEOP_IAU2K_XY [private]
Definition at line 273 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wEOPs().
QCheckBox* SBModelEditor::cbEOPResrerved_1 [private]
Definition at line 274 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wEOPs().
QCheckBox* SBModelEditor::cbGenerateDSINEXes [private]
Definition at line 305 of file SbIProject.H'.
Referenced by acquireData(), and wDataProcessing().
QCheckBox* SBModelEditor::cbIsHO [private]
Definition at line 253 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wLightPropagation().
QCheckBox* SBModelEditor::cbLatDepend [private]
Definition at line 265 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), solidTideIERS92(), and wSolidTide().
QCheckBox* SBModelEditor::cbNutGeod [private]
Definition at line 280 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wNutation().
QCheckBox* SBModelEditor::cbPTide [private]
Definition at line 262 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolidTide().
QCheckBox* SBModelEditor::cbRB2NMF [private]
Definition at line 296 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wRefraction().
QCheckBox* SBModelEditor::cbRB2Plates [private]
Definition at line 286 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wPlateMotion().
QCheckBox* SBModelEditor::cbReportCRF [private]
Definition at line 313 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportCRF_Changes [private]
Definition at line 312 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportEOP [private]
Definition at line 315 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportMaps [private]
Definition at line 310 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportNormalEqs [private]
Definition at line 317 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportNormalEqsEOP [private]
Definition at line 321 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportNormalEqsSou [private]
Definition at line 320 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportNormalEqsSta [private]
Definition at line 319 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportTechDesc [private]
Definition at line 316 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportTRF_Changes [private]
Definition at line 311 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportTRF_SINEX [private]
Definition at line 314 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbReportTroposhere [private]
Definition at line 323 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QCheckBox* SBModelEditor::cbStatVel [private]
Definition at line 285 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wPlateMotion().
QCheckBox* SBModelEditor::cbUseAltEOPs [private]
Definition at line 244 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSysTransform().
QCheckBox* SBModelEditor::cbUseAltSources [private]
Definition at line 243 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSysTransform().
QCheckBox* SBModelEditor::cbUseAltStations [private]
Definition at line 242 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSysTransform().
QCheckBox* SBModelEditor::cbUseBadIon [private]
Definition at line 304 of file SbIProject.H'.
Referenced by acquireData(), and wDataProcessing().
QCheckBox* SBModelEditor::cbUseDelay [private]
Definition at line 302 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wDataProcessing().
QCheckBox* SBModelEditor::cbUseRate [private]
Definition at line 303 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wDataProcessing().
SBConfig* SBModelEditor::Cfg [private]
Definition at line 229 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), SBModelEditor(), wDataProcessing(), wEOPs(), wLightPropagation(), wNutation(), wPlateMotion(), wRefraction(), wSolidTide(), wSolutionReports(), wSysTransform(), and ~SBModelEditor().
QLineEdit* SBModelEditor::eDelayQThreshold [private]
Definition at line 300 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wDataProcessing().
QLineEdit* SBModelEditor::eRateQThreshold [private]
Definition at line 301 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wDataProcessing().
QGroupBox* SBModelEditor::gbSTIERS96 [private]
Definition at line 259 of file SbIProject.H'.
Referenced by solidTideIERS92(), and wSolidTide().
bool SBModelEditor::isGlobal [private]
Definition at line 232 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), SBModelEditor(), wSysTransform(), and ~SBModelEditor().
bool SBModelEditor::isModified [private]
Definition at line 231 of file SbIProject.H'.
Referenced by acquireData(), SBModelEditor(), and ~SBModelEditor().
QLineEdit* SBModelEditor::leAltEOPs [private]
Definition at line 247 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSysTransform().
QLineEdit* SBModelEditor::leAltSources [private]
Definition at line 246 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSysTransform().
QLineEdit* SBModelEditor::leAltStations [private]
Definition at line 245 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSysTransform().
QLineEdit* SBModelEditor::leEOPNInterp [private]
Definition at line 272 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wEOPs().
QLineEdit* SBModelEditor::leHOThreshold [private]
Definition at line 254 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wLightPropagation().
QLineEdit* SBModelEditor::leTropSamplInterval [private]
Definition at line 324 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
QLineEdit* SBModelEditor::leTropStartSec [private]
Definition at line 325 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolutionReports().
SBProject* SBModelEditor::Project [private]
Definition at line 230 of file SbIProject.H'.
Referenced by SBModelEditor(), and ~SBModelEditor().
QRadioButton* SBModelEditor::rbDegree[2] [private]
Definition at line 263 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), solidTideIERS92(), and wSolidTide().
QRadioButton* SBModelEditor::rbDryMap[6] [private]
Definition at line 293 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wRefraction().
QRadioButton* SBModelEditor::rbDryZenith[3] [private]
Definition at line 291 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wRefraction().
QRadioButton* SBModelEditor::rbEOPDiurn[6] [private]
Definition at line 269 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wEOPs().
QRadioButton* SBModelEditor::rbEOPDiurnAtm[2] [private]
Definition at line 270 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wEOPs().
QRadioButton* SBModelEditor::rbEOPDiurnNonTidal[2] [private]
Definition at line 271 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wEOPs().
QRadioButton* SBModelEditor::rbEphem[3] [private]
Definition at line 252 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wLightPropagation().
QRadioButton* SBModelEditor::rbNutEquinox[3] [private]
Definition at line 279 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wNutation().
QRadioButton* SBModelEditor::rbNutModel[3] [private]
Definition at line 278 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wNutation().
QRadioButton* SBModelEditor::rbSTide[2] [private]
Definition at line 261 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSolidTide().
QRadioButton* SBModelEditor::rbSysTransform[2] [private]
Definition at line 240 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wSysTransform().
QRadioButton* SBModelEditor::rbTPMModel[3] [private]
Definition at line 284 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wPlateMotion().
QRadioButton* SBModelEditor::rbWetMap[6] [private]
Definition at line 294 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wRefraction().
QRadioButton* SBModelEditor::rbWetZenith[3] [private]
Definition at line 292 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), and wRefraction().
QString SBModelEditor::Str [private]
Definition at line 233 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), wEOPs(), and wLightPropagation().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.