SBNamed
NAME
SBNamed -
SYNOPSIS
#include <SbGeo.H>
Inherited by SBAploEntry, SBAploSiteAmpl, SBAploWave, SBAploWaveAmpls, SBBaseInfo, SBCelestBody, SBDerivation, SBEphem, SBFileConv, SBFrame, SBInstitution, SBMasterFile, SBMasterRecord, SBMatrix, SBNROThGeneral, SBNutThGeneral, SBObsVLBIStatistics, SBObsVLBIStatRecord, SBOLoadCarrier, SBOTideEOPGeneral, SBParameterCfg, SBPlateEntry, SBPlotBranch, SBPlotCarrier, SBProject, SBSite, SBSource, SBSourceInfo, SBStation, SBStatistics, SBVector, SBVLBISesInfo, and SBVLBISet::Network'.
Public Member Functions
SBNamed (const QString &Name_='NONAME')
SBNamed (const SBNamed &W)
virtual ~SBNamed ()
virtual QString ClassName () const
virtual SBNamed & operator= (const SBNamed &W)
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
QString Name
Friends
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Definition at line 203 of file SbGeo.H'.
Constructor & Destructor Documentation
SBNamed::SBNamed (const QString &Name_ = 'NONAME') [inline]
Definition at line 208 of file SbGeo.H'.
References Name.
Referenced by SBOLoadCarrier::operator=().
SBNamed::SBNamed (const SBNamed &W) [inline]
Definition at line 209 of file SbGeo.H'.
References Name.
virtual SBNamed::~SBNamed () [inline, virtual]
Definition at line 210 of file SbGeo.H'.
Member Function Documentation
virtual QString SBNamed::ClassName () const [inline, virtual]
Reimplemented in SBOLoadCarrier, SBGravTideEOP_B_02, SBNonTideEOP_Viron_02, SBMasterFile, SBATideEOP_BBP_02, SBMasterRecord, SBOTideEOPRay1994_2003, SBOTideEOPRay1994_1996, SBNROThIAU2000A, SBVLBISession, SBSymMatrix, SBNutThIAU2000A, SBNROThIAU1996, SBSite, SBNutThIAU1996, SBNROThIAU1980, SBVLBISesInfo, SBNutThIAU1980, SBFrameNRO, SBFrameClassic, SBStatistics, SBFrame, SBUpperMatrix, SBStochParameter, SBStation, SBSourceInfo, SBParameter, SBBaseInfo, SBAploSiteAmpl, SBProject, SBObsVLBIStatistics, SBDerivation, SBAploWaveAmpls, SBMatrix, SBInstitution, SBEphemDE405, SBEphemDE403, SBObsVLBIStatStation, SBAploWave, SBEphemDE200, SBPlateEntry, SBOTideEOPGenS, SBOTideEOPGeneral, SBObsVLBIStatSource, SBSource, SBEphem, SBAploEntry, SBNROThGeneral, SBSINEXParameter, SBVector, SBParameterCfg, SBFileConv, SBCelestBody, SBObsVLBIStatRecord, and SBNutThGeneral'.
Definition at line 211 of file SbGeo.H'.
Referenced by SBPlotCarrier::selfCheck().
const QString& SBNamed::name () const [inline]
Definition at line 215 of file SbGeo.H'.
References Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual SBNamed& SBNamed::operator= (const SBNamed &W) [inline, virtual]
Definition at line 212 of file SbGeo.H'.
References Name.
void SBNamed::setName (const QString &Name_) [inline]
Definition at line 216 of file SbGeo.H'.
References Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
Member Data Documentation
QString SBNamed::Name [protected]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), name(), operator<<(), operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed(), setName(), SBSite::updateSite(), and SBStation::updateStation().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.