.TH "SBNList" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBNList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeo\&.H>\fP
.PP
Inherits \fBQList< SBNamed >\fP'\&.
.PP
Inherited by \fBSBCatalog\fP, \fBSBFCList\fP, \fBSBInstitutionList\fP, \fBSBOLoadList\fP, \fBSBPlateMotion\fP, \fBSBStationIDList\fP, and \fBSBStationList\fP'\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item item1, QCollection::Item item2)"
.br
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item Entry) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &Entry)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 274 of file SbGeo\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBSB_TRF\fP, \fBSBStationList\fP, and \fBSBStationIDList\fP'\&.
.PP
Definition at line 277 of file SbGeo\&.H'\&.
.SS "virtual QDataStream& SBNList::read (QDataStream &s, QCollection::Item &Entry)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBSB_TRF\fP, \fBSBStationList\fP, \fBSBStationIDList\fP, \fBSBInstitutionList\fP, \fBSB_CRF\fP, and \fBSBFCList\fP'\&.
.PP
Definition at line 284 of file SbGeo\&.H'\&.
.SS "virtual QDataStream& SBNList::write (QDataStream &s, QCollection::ItemEntry) const\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBSB_TRF\fP, \fBSBStationList\fP, \fBSBStationIDList\fP, \fBSBInstitutionList\fP, \fBSB_CRF\fP, and \fBSBFCList\fP'\&.
.PP
Definition at line 282 of file SbGeo\&.H'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
