.TH "SBNonTideEOP_Viron_02::TableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBNonTideEOP_Viron_02::TableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBk\fP [6]"
.br
.ti -1c
.RI "double \fBA_in\fP"
.br
.ti -1c
.RI "double \fBA_op\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1183 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBNonTideEOP_Viron_02::TableEntry::a\fP"
.PP
Definition at line 1186 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNonTideEOP_Viron_02::calc()\&.
.SS "double \fBSBNonTideEOP_Viron_02::TableEntry::A_in\fP"
.PP
Definition at line 1186 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNonTideEOP_Viron_02::calc()\&.
.SS "double \fBSBNonTideEOP_Viron_02::TableEntry::A_op\fP"
.PP
Definition at line 1186 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNonTideEOP_Viron_02::calc()\&.
.SS "double \fBSBNonTideEOP_Viron_02::TableEntry::b\fP"
.PP
Definition at line 1186 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNonTideEOP_Viron_02::calc()\&.
.SS "short \fBSBNonTideEOP_Viron_02::TableEntry::k\fP[6]"
.PP
Definition at line 1185 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNonTideEOP_Viron_02::calc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
