SBNROThIAU2000A
NAME
SBNROThIAU2000A -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits SBNROThGeneral'.
Classes
struct GeneralTableEntry
Public Member Functions
SBNROThIAU2000A ()
virtual QString ClassName () const
virtual void calc (const SBTime &)
virtual double x () const
virtual double y () const
virtual double s () const
virtual double dT () const
const QString & name () const
void setName (const QString &Name_)
Protected Member Functions
double sum (int, const GeneralTableEntry *, double *)
Protected Attributes
double X
X'.
double Y
Y'.
double S
s
double DT
dT
QString Name
Static Protected Attributes
static const int NXT0
static const int NXT1
static const int NXT2
static const int NXT3
static const int NXT4
static const int NYT0
static const int NYT1
static const int NYT2
static const int NYT3
static const int NYT4
static const int NDThetaT0
static const int NDThetaT1
static const int NDThetaT2
static const int NDThetaT3
static const int NDThetaT4
static const int NDtT0
static const int NDtT1
static const GeneralTableEntry XTabT0 []
static const GeneralTableEntry XTabT1 []
static const GeneralTableEntry XTabT2 []
static const GeneralTableEntry XTabT3 []
static const GeneralTableEntry XTabT4 []
static const GeneralTableEntry YTabT0 []
static const GeneralTableEntry YTabT1 []
static const GeneralTableEntry YTabT2 []
static const GeneralTableEntry YTabT3 []
static const GeneralTableEntry YTabT4 []
static const GeneralTableEntry DThetaTabT0 []
static const GeneralTableEntry DThetaTabT1 []
static const GeneralTableEntry DThetaTabT2 []
static const GeneralTableEntry DThetaTabT3 []
static const GeneralTableEntry DThetaTabT4 []
static const GeneralTableEntry DtTabT0 []
static const GeneralTableEntry DtTabT1 []
Friends
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
IAU 2000A Nutation theory'. Implements The IAU 2000A Theory of Nutation'.
Definition at line 967 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBNROThIAU2000A::SBNROThIAU2000A () [inline]
Definition at line 1019 of file SbGeoRefFrame.H'.
Member Function Documentation
void SBNROThIAU2000A::calc (const SBTime &) [virtual]"Calculates nutation angles for the time T'.
Implements SBNROThGeneral'.
Definition at line 1409 of file SbGeoRefFrame.C'.
References SBNROThGeneral::DT, DThetaTabT0, DThetaTabT1, DThetaTabT2, DThetaTabT3, DThetaTabT4, DtTabT0, DtTabT1, SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), NDThetaT0, NDThetaT1, NDThetaT2, NDThetaT3, NDThetaT4, NDtT0, NDtT1, NXT0, NXT1, NXT2, NXT3, NXT4, NYT0, NYT1, NYT2, NYT3, NYT4, SBNROThGeneral::S, SEC2RAD, sum(), TEphem, SBTime::TT(), SBNROThGeneral::X, XTabT0, XTabT1, XTabT2, XTabT3, XTabT4, SBNROThGeneral::Y, YTabT0, YTabT1, YTabT2, YTabT3, and YTabT4.
virtual QString SBNROThIAU2000A::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBNROThGeneral'.
Definition at line 1020 of file SbGeoRefFrame.H'.
virtual double SBNROThGeneral::dT () const [inline, virtual, inherited]"Returns calculated dT'.
Definition at line 106 of file SbGeoRefFrame.H'.
References SBNROThGeneral::DT.
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual double SBNROThGeneral::s () const [inline, virtual, inherited]"Returns calculated s'.
Definition at line 104 of file SbGeoRefFrame.H'.
References SBNROThGeneral::S.
Referenced by SBPrecNutNRO::operator()().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
double SBNROThIAU2000A::sum (intN, const GeneralTableEntry *Table, double *Arg) [protected]
Definition at line 1389 of file SbGeoRefFrame.C'.
References SBNROThIAU2000A::GeneralTableEntry::C, SBNROThIAU2000A::GeneralTableEntry::N, SBNROThIAU2000A::GeneralTableEntry::S, and sincos().
Referenced by calc().
virtual double SBNROThGeneral::x () const [inline, virtual, inherited]"Returns calculated X'.
Definition at line 100 of file SbGeoRefFrame.H'.
References SBNROThGeneral::X.
Referenced by SBPrecNutNRO::operator()().
virtual double SBNROThGeneral::y () const [inline, virtual, inherited]"Returns calculated Y'.
Definition at line 102 of file SbGeoRefFrame.H'.
References SBNROThGeneral::Y.
Referenced by SBPrecNutNRO::operator()().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
Member Data Documentation
double SBNROThGeneral::DT [protected, inherited]
dT
Definition at line 86 of file SbGeoRefFrame.H'.
Referenced by calc(), and SBNROThGeneral::dT().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::DThetaTabT0 [static, protected]
Definition at line 1008 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::DThetaTabT1 [static, protected]"Initial value:
{
  { -0.07, 3.57, { 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 1.71, -0.03, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.00, 0.48, { 0, 0, 2, -2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1009 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::DThetaTabT2 [static, protected]"Initial value:
{
  { 743.53, -0.17, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 56.91, 0.06, { 0, 0, 2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 9.84, -0.01, { 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -8.85, 0.01, { 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -6.38, -0.05, { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -3.07, 0.00, { 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 2.23, 0.00, { 0, 1, 2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 1.67, 0.00, { 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 1.30, 0.00, { 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.93, 0.00, { 0, 1, -2, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.68, 0.00, { 1, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.55, 0.00, { 0, 0, 2, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.53, 0.00, { 1, 0, -2, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.27, 0.00, { 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.27, 0.00, { 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.26, 0.00, { 1, 0, -2, -2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.25, 0.00, { 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.22, 0.00, { 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.21, 0.00, { 2, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.20, 0.00, { 2, 0, -2, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.17, 0.00, { 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.13, 0.00, { 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.13, 0.00, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.12, 0.00, { 1, 0, 2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.11, 0.00, { 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1010 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::DThetaTabT3 [static, protected]"Initial value:
{
  { 0.30, -23.51, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.03, -1.39, { 0, 0, 2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.01, -0.24, { 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.00, 0.22, { 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1011 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::DThetaTabT4 [static, protected]"Initial value:
{
  { -0.26, -0.01, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1012 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::DtTabT0 [static, protected]
Definition at line 1014 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::DtTabT1 [static, protected]"Initial value:
{
  { -0.87, 0.00, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1015 of file SbGeoRefFrame.H'.
Referenced by calc().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
const int SBNROThIAU2000A::NDThetaT0 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::DThetaTabT0)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 987 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NDThetaT1 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::DThetaTabT1)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 988 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NDThetaT2 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::DThetaTabT2)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 989 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NDThetaT3 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::DThetaTabT3)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 990 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NDThetaT4 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::DThetaTabT4)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 991 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NDtT0 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::DtTabT0)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 993 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NDtT1 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::DtTabT1)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 994 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NXT0 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::XTabT0)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 975 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NXT1 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::XTabT1)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 976 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NXT2 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::XTabT2)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 977 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NXT3 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::XTabT3)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 978 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NXT4 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::XTabT4)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 979 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NYT0 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::YTabT0)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 981 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NYT1 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::YTabT1)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 982 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NYT2 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::YTabT2)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 983 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NYT3 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::YTabT3)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 984 of file SbGeoRefFrame.H'.
Referenced by calc().
const int SBNROThIAU2000A::NYT4 [static, protected]"Initial value:
sizeof(SBNROThIAU2000A::YTabT4)/sizeof(struct SBNROThIAU2000A::GeneralTableEntry)
Definition at line 985 of file SbGeoRefFrame.H'.
Referenced by calc().
double SBNROThGeneral::S [protected, inherited]
s
Definition at line 85 of file SbGeoRefFrame.H'.
Referenced by calc(), SBNROThGeneral::s(), and SBNROThGeneral::SBNROThGeneral().
double SBNROThGeneral::X [protected, inherited]
X'.
Definition at line 83 of file SbGeoRefFrame.H'.
Referenced by calc(), SBNROThGeneral::SBNROThGeneral(), and SBNROThGeneral::x().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::XTabT0 [static, protected]
Definition at line 996 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::XTabT1 [static, protected]
Definition at line 997 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::XTabT2 [static, protected]
Definition at line 998 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::XTabT3 [static, protected]"Initial value:
{
  { 1.76, -20.39, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.00, -1.27, { 0, 0, 2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.00, -0.22, { 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.00, 0.20, { 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 999 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::XTabT4 [static, protected]"Initial value:
{
  { -0.10, -0.02, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1000 of file SbGeoRefFrame.H'.
Referenced by calc().
double SBNROThGeneral::Y [protected, inherited]
Y'.
Definition at line 84 of file SbGeoRefFrame.H'.
Referenced by calc(), SBNROThGeneral::SBNROThGeneral(), and SBNROThGeneral::y().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::YTabT0 [static, protected]
Definition at line 1002 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::YTabT1 [static, protected]
Definition at line 1003 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::YTabT2 [static, protected]
Definition at line 1004 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::YTabT3 [static, protected]"Initial value:
{
  { -15.23, -1.62, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -1.16, -0.01, { 0, 0, 2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { -0.20, 0.00, { 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.18, 0.00, { 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
  { 0.13, 0.00, { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1005 of file SbGeoRefFrame.H'.
Referenced by calc().
const SBNROThIAU2000A::GeneralTableEntry SBNROThIAU2000A::YTabT4 [static, protected]"Initial value:
{
  { -0.01, 0.11, { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
}
Definition at line 1006 of file SbGeoRefFrame.H'.
Referenced by calc().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.