.TH "SBNROThIAU2000A::GeneralTableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBNROThIAU2000A::GeneralTableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBS\fP"
.br
.ti -1c
.RI "double \fBC\fP"
.br
.RI "\fIsin & cos coefficients \fP"
.ti -1c
.RI "short \fBN\fP [14]"
.br
.RI "\fImultipliers \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 970 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBNROThIAU2000A::GeneralTableEntry::C\fP"
.PP
sin & cos coefficients 
.PP
Definition at line 972 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNROThIAU2000A::sum()\&.
.SS "short \fBSBNROThIAU2000A::GeneralTableEntry::N\fP[14]"
.PP
multipliers 
.PP
Definition at line 973 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNROThIAU2000A::sum()\&.
.SS "double \fBSBNROThIAU2000A::GeneralTableEntry::S\fP"
.PP
Definition at line 972 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNROThIAU2000A::sum()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
