SBNutation
NAME
SBNutation -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits Matrix3'.
Inherited by SBNut_IAU1980, and SBNut_IAU2000'.
Public Member Functions
SBNutation (const SBConfig *, SBEOP *=NULL)
virtual ~SBNutation ()
virtual QString ClassName () const
virtual const Matrix3 & operator() (const SBTime &)=0
virtual double geodesicNutation (const SBTime &)
virtual double meanEps () const
virtual double trueEps () const
virtual double deltaEps () const
virtual double deltaPsi () const
virtual double eqEquinox () const
virtual double gmst () const
virtual double gst () const
virtual double r () const
virtual void calcGST (const SBTime &)
const SBNutThGeneral * theory () const
virtual const Matrix3 & r1 () const
virtual const Matrix3 & r2 () const
virtual const Matrix3 & r3 () const
virtual const Matrix3 & dR3deps () const
virtual const Matrix3 & dR2dpsi () const
virtual double dPsi () const
virtual double dEps () const
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Static Public Member Functions
static double ephemEps ()
Protected Attributes
const SBConfig * Cfg
double Eps
mean obliquity
double DeltaEps
nutation in obliquity
double DeltaPsi
nutation in longitude
double AlphaE
equation of equinox
SBNutThGeneral * Theory
nutation theory
SBEOP * EOP
EOP database'.
RotMatrix R1
RotMatrix R2
RotMatrix R3
RotDerMatrix DR2dpsi
RotDerMatrix DR3deps
double DPsi
double DEps
double GMST
Greenwich Mean Sidereal Time'.
double GST
Greenwich Sidereal Time'.
double R
double mat [3][3]
Static Protected Attributes
static const double EphemEps = 84381.448*SEC2RAD
obliquity at J2000'.0
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
Nutation matrix'. General interface'.
Definition at line 321 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBNutation::SBNutation (const SBConfig *Cfg_, SBEOP *EOP_ = NULL)"A constructor'. Creates a copy of object'.
Definition at line 201 of file SbGeoRefFrame.C'.
References AlphaE, Cfg, DeltaEps, DeltaPsi, DEps, DPsi, EOP, Eps, GMST, GST, R, and Theory.
virtual SBNutation::~SBNutation () [inline, virtual]"A destructor'.
Definition at line 350 of file SbGeoRefFrame.H'.
References EOP, and Theory.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
void SBNutation::calcGST (const SBTime &T) [virtual]
Reimplemented in SBNut_IAU2000'.
Definition at line 217 of file SbGeoRefFrame.C'.
References SBMJD::date(), DAY2SEC, eqEquinox(), GMST, GST, R, TEphem, SBMJD::time(), and SBTime::UT1().
Referenced by SBNut_IAU1980::operator()().
virtual QString SBNutation::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from Matrix3'.
Reimplemented in SBNut_IAU2000, and SBNut_IAU1980'.
Definition at line 352 of file SbGeoRefFrame.H'.
virtual double SBNutation::deltaEps () const [inline, virtual]"Returns current DeltaEps'.
Definition at line 364 of file SbGeoRefFrame.H'.
References DeltaEps.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBFrameClassic::totNutationObliquity().
virtual double SBNutation::deltaPsi () const [inline, virtual]"Returns current DeltaPsi'.
Definition at line 366 of file SbGeoRefFrame.H'.
References DeltaPsi.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBFrameClassic::totNutationLongitude().
virtual double SBNutation::dEps () const [inline, virtual]
Definition at line 386 of file SbGeoRefFrame.H'.
References DEps.
Referenced by SBFrameClassic::dNutation_Eps().
virtual double SBNutation::dPsi () const [inline, virtual]
Definition at line 385 of file SbGeoRefFrame.H'.
References DPsi.
Referenced by SBFrameClassic::dNutation_Psi().
virtual const Matrix3& SBNutation::dR2dpsi () const [inline, virtual]
Definition at line 383 of file SbGeoRefFrame.H'.
References DR2dpsi.
Referenced by SBFrameClassic::dQ_dpsi().
virtual const Matrix3& SBNutation::dR3deps () const [inline, virtual]
Definition at line 382 of file SbGeoRefFrame.H'.
References DR3deps.
Referenced by SBFrameClassic::dQ_deps().
static double SBNutation::ephemEps () [inline, static]"Returns obliquity at J2000'.0'.
Definition at line 358 of file SbGeoRefFrame.H'.
References EphemEps.
Referenced by SBPrecNutNRO::geodesicNutation(), SBPrec_IAU2000::operator()(), and SBFrameClassic::SBFrameClassic().
virtual double SBNutation::eqEquinox () const [inline, virtual]"Returns current equation of equinoxes'.
Definition at line 368 of file SbGeoRefFrame.H'.
References AlphaE.
Referenced by SBFrameClassic::calc(), calcGST(), SBNut_IAU2000::calcGST(), SBTestNutation::createWidget4Test(), and SBTestNutation::displayValues().
virtual double SBNutation::geodesicNutation (const SBTime &) [inline, virtual]"Calcs geodesic nutation'.
Reimplemented in SBNut_IAU1980'.
Definition at line 356 of file SbGeoRefFrame.H'.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBNut_IAU2000::operator()().
virtual double SBNutation::gmst () const [inline, virtual]"Returns Greenwich Mean Sidereal Time'.
Definition at line 370 of file SbGeoRefFrame.H'.
References GMST.
Referenced by SBFrameClassic::gmst().
virtual double SBNutation::gst () const [inline, virtual]"Returns Greenwich Mean Sidereal Time'.
Definition at line 372 of file SbGeoRefFrame.H'.
References GST.
Referenced by SBFrameClassic::calc(), and SBFrameClassic::gst().
virtual double SBNutation::meanEps () const [inline, virtual]"Returns current mean obliquity'.
Definition at line 360 of file SbGeoRefFrame.H'.
References Eps.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBFrameClassic::dQ_dpsi().
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
virtual const Matrix3& SBNutation::operator() (const SBTime &) [pure virtual]"Calculates nutation angles and returns matrix corresponds to time T'.
Implemented in SBNut_IAU2000, and SBNut_IAU1980'.
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
virtual double SBNutation::r () const [inline, virtual]
Definition at line 373 of file SbGeoRefFrame.H'.
References R.
Referenced by SBFrameClassic::calc().
virtual const Matrix3& SBNutation::r1 () const [inline, virtual]
Definition at line 378 of file SbGeoRefFrame.H'.
References R1.
Referenced by SBFrameClassic::dQ_deps(), and SBFrameClassic::dQ_dpsi().
virtual const Matrix3& SBNutation::r2 () const [inline, virtual]
Definition at line 379 of file SbGeoRefFrame.H'.
References R2.
Referenced by SBFrameClassic::dQ_deps().
virtual const Matrix3& SBNutation::r3 () const [inline, virtual]
Definition at line 380 of file SbGeoRefFrame.H'.
References R3.
Referenced by SBFrameClassic::dQ_dpsi().
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
const SBNutThGeneral* SBNutation::theory () const [inline]
Definition at line 376 of file SbGeoRefFrame.H'.
References Theory.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBTestNutation::SBTestNutation().
virtual double SBNutation::trueEps () const [inline, virtual]"Returns current true obliquity'.
Definition at line 362 of file SbGeoRefFrame.H'.
References DeltaEps, and Eps.
Referenced by SBTestNutation::createWidget4Test(), and SBTestNutation::displayValues().
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
double SBNutation::AlphaE [protected]
equation of equinox
Definition at line 328 of file SbGeoRefFrame.H'.
Referenced by eqEquinox(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBNutation().
const SBConfig* SBNutation::Cfg [protected]
Definition at line 324 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBNut_IAU1980::SBNut_IAU1980(), and SBNutation().
double SBNutation::DeltaEps [protected]
nutation in obliquity
Definition at line 326 of file SbGeoRefFrame.H'.
Referenced by deltaEps(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBNutation(), and trueEps().
double SBNutation::DeltaPsi [protected]
nutation in longitude
Definition at line 327 of file SbGeoRefFrame.H'.
Referenced by deltaPsi(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBNutation().
double SBNutation::DEps [protected]
Definition at line 338 of file SbGeoRefFrame.H'.
Referenced by dEps(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBNutation().
double SBNutation::DPsi [protected]
Definition at line 337 of file SbGeoRefFrame.H'.
Referenced by dPsi(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBNutation().
RotDerMatrix SBNutation::DR2dpsi [protected]
Definition at line 335 of file SbGeoRefFrame.H'.
Referenced by dR2dpsi(), SBNut_IAU1980::operator()(), and SBNut_IAU2000::operator()().
RotDerMatrix SBNutation::DR3deps [protected]
Definition at line 336 of file SbGeoRefFrame.H'.
Referenced by dR3deps(), SBNut_IAU1980::operator()(), and SBNut_IAU2000::operator()().
SBEOP* SBNutation::EOP [protected]
EOP database'.
Definition at line 331 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBNutation(), and ~SBNutation().
const double SBNutation::EphemEps = 84381.448*SEC2RAD [static, protected]
obliquity at J2000'.0
Definition at line 329 of file SbGeoRefFrame.H'.
Referenced by ephemEps(), SBNut_IAU1980::operator()(), and SBNut_IAU2000::operator()().
double SBNutation::Eps [protected]
mean obliquity
Definition at line 325 of file SbGeoRefFrame.H'.
Referenced by meanEps(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBNutation(), and trueEps().
double SBNutation::GMST [protected]
Greenwich Mean Sidereal Time'.
Definition at line 340 of file SbGeoRefFrame.H'.
Referenced by calcGST(), SBNut_IAU2000::calcGST(), gmst(), and SBNutation().
double SBNutation::GST [protected]
Greenwich Sidereal Time'.
Definition at line 341 of file SbGeoRefFrame.H'.
Referenced by calcGST(), SBNut_IAU2000::calcGST(), gst(), and SBNutation().
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
double SBNutation::R [protected]
Definition at line 342 of file SbGeoRefFrame.H'.
Referenced by calcGST(), SBNut_IAU2000::calcGST(), r(), and SBNutation().
RotMatrix SBNutation::R1 [protected]
Definition at line 332 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and r1().
RotMatrix SBNutation::R2 [protected]
Definition at line 333 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and r2().
RotMatrix SBNutation::R3 [protected]
Definition at line 334 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and r3().
SBNutThGeneral* SBNutation::Theory [protected]
nutation theory
Definition at line 330 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBNut_IAU1980::SBNut_IAU1980(), SBNut_IAU2000::SBNut_IAU2000(), SBNutation(), theory(), and ~SBNutation().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.