.TH "SBNutThIAU1996::TableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBNutThIAU1996::TableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBN\fP [5]"
.br
.ti -1c
.RI "double \fBA\fP [2]"
.br
.ti -1c
.RI "double \fBB\fP [2]"
.br
.ti -1c
.RI "double \fBC\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 881 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBNutThIAU1996::TableEntry::A\fP[2]"
.PP
Definition at line 884 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU1996::calc()\&.
.SS "double \fBSBNutThIAU1996::TableEntry::B\fP[2]"
.PP
Definition at line 884 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU1996::calc()\&.
.SS "double \fBSBNutThIAU1996::TableEntry::C\fP[2]"
.PP
Definition at line 884 of file SbGeoRefFrame\&.H'\&.
.SS "short \fBSBNutThIAU1996::TableEntry::N\fP[5]"
.PP
Definition at line 883 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU1996::calc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
