.TH "SBNutThIAU2000A::SolLunTableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBNutThIAU2000A::SolLunTableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBN\fP [5]"
.br
.ti -1c
.RI "double \fBPsi_in\fP [2]"
.br
.ti -1c
.RI "double \fBEps_in\fP [2]"
.br
.ti -1c
.RI "double \fBPsi_out\fP [2]"
.br
.ti -1c
.RI "double \fBEps_out\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 939 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBNutThIAU2000A::SolLunTableEntry::Eps_in\fP[2]"
.PP
Definition at line 942 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU2000A::calc()\&.
.SS "double \fBSBNutThIAU2000A::SolLunTableEntry::Eps_out\fP[2]"
.PP
Definition at line 942 of file SbGeoRefFrame\&.H'\&.
.SS "short \fBSBNutThIAU2000A::SolLunTableEntry::N\fP[5]"
.PP
Definition at line 941 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU2000A::calc()\&.
.SS "double \fBSBNutThIAU2000A::SolLunTableEntry::Psi_in\fP[2]"
.PP
Definition at line 942 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU2000A::calc()\&.
.SS "double \fBSBNutThIAU2000A::SolLunTableEntry::Psi_out\fP[2]"
.PP
Definition at line 942 of file SbGeoRefFrame\&.H'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
