SBNut_IAU2000
NAME
SBNut_IAU2000 -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits SBNutation'.
Public Member Functions
SBNut_IAU2000 (const SBConfig *, SBEOP *=NULL)
virtual ~SBNut_IAU2000 ()
virtual QString ClassName () const
virtual const Matrix3 & operator() (const SBTime &)
virtual void calcGST (const SBTime &)
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double geodesicNutation (const SBTime &)
virtual double meanEps () const
virtual double trueEps () const
virtual double deltaEps () const
virtual double deltaPsi () const
virtual double eqEquinox () const
virtual double gmst () const
virtual double gst () const
virtual double r () const
const SBNutThGeneral * theory () const
virtual const Matrix3 & r1 () const
virtual const Matrix3 & r2 () const
virtual const Matrix3 & r3 () const
virtual const Matrix3 & dR3deps () const
virtual const Matrix3 & dR2dpsi () const
virtual double dPsi () const
virtual double dEps () const
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Static Public Member Functions
static double ephemEps ()
Protected Attributes
const SBConfig * Cfg
double Eps
mean obliquity
double DeltaEps
nutation in obliquity
double DeltaPsi
nutation in longitude
double AlphaE
equation of equinox
SBNutThGeneral * Theory
nutation theory
SBEOP * EOP
EOP database'.
RotMatrix R1
RotMatrix R2
RotMatrix R3
RotDerMatrix DR2dpsi
RotDerMatrix DR3deps
double DPsi
double DEps
double GMST
Greenwich Mean Sidereal Time'.
double GST
Greenwich Sidereal Time'.
double R
double mat [3][3]
Static Protected Attributes
static const double EphemEps = 84381.448*SEC2RAD
obliquity at J2000'.0
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
Nutation matrix'. Calculates nutation quantities and the matrix of the nutation for the theory IAU-2000'.
Definition at line 427 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBNut_IAU2000::SBNut_IAU2000 (const SBConfig *Cfg_, SBEOP *EOP_ = NULL)"A constructor'. Creates a copy of object'.
Definition at line 406 of file SbGeoRefFrame.C'.
References SBNutation::Theory.
virtual SBNut_IAU2000::~SBNut_IAU2000 () [inline, virtual]"A destructor'.
Definition at line 437 of file SbGeoRefFrame.H'.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
void SBNut_IAU2000::calcGST (const SBTime &T) [virtual]
Reimplemented from SBNutation'.
Definition at line 412 of file SbGeoRefFrame.C'.
References SBNutation::eqEquinox(), SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), SBNutation::GMST, SBNutation::GST, SBNutation::R, SEC2RAD, TEphem, SBTime::TT(), and SBTime::UT1().
Referenced by operator()().
virtual QString SBNut_IAU2000::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBNutation'.
Definition at line 439 of file SbGeoRefFrame.H'.
Referenced by operator()().
virtual double SBNutation::deltaEps () const [inline, virtual, inherited]"Returns current DeltaEps'.
Definition at line 364 of file SbGeoRefFrame.H'.
References SBNutation::DeltaEps.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBFrameClassic::totNutationObliquity().
virtual double SBNutation::deltaPsi () const [inline, virtual, inherited]"Returns current DeltaPsi'.
Definition at line 366 of file SbGeoRefFrame.H'.
References SBNutation::DeltaPsi.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBFrameClassic::totNutationLongitude().
virtual double SBNutation::dEps () const [inline, virtual, inherited]
Definition at line 386 of file SbGeoRefFrame.H'.
References SBNutation::DEps.
Referenced by SBFrameClassic::dNutation_Eps().
virtual double SBNutation::dPsi () const [inline, virtual, inherited]
Definition at line 385 of file SbGeoRefFrame.H'.
References SBNutation::DPsi.
Referenced by SBFrameClassic::dNutation_Psi().
virtual const Matrix3& SBNutation::dR2dpsi () const [inline, virtual, inherited]
Definition at line 383 of file SbGeoRefFrame.H'.
References SBNutation::DR2dpsi.
Referenced by SBFrameClassic::dQ_dpsi().
virtual const Matrix3& SBNutation::dR3deps () const [inline, virtual, inherited]
Definition at line 382 of file SbGeoRefFrame.H'.
References SBNutation::DR3deps.
Referenced by SBFrameClassic::dQ_deps().
static double SBNutation::ephemEps () [inline, static, inherited]"Returns obliquity at J2000'.0'.
Definition at line 358 of file SbGeoRefFrame.H'.
References SBNutation::EphemEps.
Referenced by SBPrecNutNRO::geodesicNutation(), SBPrec_IAU2000::operator()(), and SBFrameClassic::SBFrameClassic().
virtual double SBNutation::eqEquinox () const [inline, virtual, inherited]"Returns current equation of equinoxes'.
Definition at line 368 of file SbGeoRefFrame.H'.
References SBNutation::AlphaE.
Referenced by SBFrameClassic::calc(), SBNutation::calcGST(), calcGST(), SBTestNutation::createWidget4Test(), and SBTestNutation::displayValues().
virtual double SBNutation::geodesicNutation (const SBTime &) [inline, virtual, inherited]"Calcs geodesic nutation'.
Reimplemented in SBNut_IAU1980'.
Definition at line 356 of file SbGeoRefFrame.H'.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and operator()().
virtual double SBNutation::gmst () const [inline, virtual, inherited]"Returns Greenwich Mean Sidereal Time'.
Definition at line 370 of file SbGeoRefFrame.H'.
References SBNutation::GMST.
Referenced by SBFrameClassic::gmst().
virtual double SBNutation::gst () const [inline, virtual, inherited]"Returns Greenwich Mean Sidereal Time'.
Definition at line 372 of file SbGeoRefFrame.H'.
References SBNutation::GST.
Referenced by SBFrameClassic::calc(), and SBFrameClassic::gst().
virtual double SBNutation::meanEps () const [inline, virtual, inherited]"Returns current mean obliquity'.
Definition at line 360 of file SbGeoRefFrame.H'.
References SBNutation::Eps.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBFrameClassic::dQ_dpsi().
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
const Matrix3 & SBNut_IAU2000::operator() (const SBTime &T) [virtual]"Calculates nutation angles and returns matrix corresponds to time T'.
Implements SBNutation'.
Definition at line 484 of file SbGeoRefFrame.C'.
References SBNutation::AlphaE, RotMatrix::angle(), SBNutThGeneral::calc(), calcGST(), SBNutation::Cfg, ClassName(), SBLog::DBG, SBNutThGeneral::deltaEps(), SBNutation::DeltaEps, SBNutThGeneral::deltaPsi(), SBNutation::DeltaPsi, SBNutation::DEps, SBEOP::dEps(), SBNutation::DPsi, SBEOP::dPsi(), SBNutation::DR2dpsi, SBNutation::DR3deps, SBNutation::EOP, SBNutation::EphemEps, SBNutation::Eps, SBNutation::geodesicNutation(), SBLog::isEligible(), Log, Matrix3::mat, SBConfig::NEE_SOVERS, SBLog::NUTATION, SBConfig::nutEquinox(), SBNutation::R1, SBNutation::R2, SBNutation::R3, rad2dmslStr(), Matrix3::report2Log(), SEC2RAD, SBTime::TDB(), TEphem, SBNutation::Theory, SBMJD::toString(), SBTime::TT(), and SBLog::write().
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
virtual double SBNutation::r () const [inline, virtual, inherited]
Definition at line 373 of file SbGeoRefFrame.H'.
References SBNutation::R.
Referenced by SBFrameClassic::calc().
virtual const Matrix3& SBNutation::r1 () const [inline, virtual, inherited]
Definition at line 378 of file SbGeoRefFrame.H'.
References SBNutation::R1.
Referenced by SBFrameClassic::dQ_deps(), and SBFrameClassic::dQ_dpsi().
virtual const Matrix3& SBNutation::r2 () const [inline, virtual, inherited]
Definition at line 379 of file SbGeoRefFrame.H'.
References SBNutation::R2.
Referenced by SBFrameClassic::dQ_deps().
virtual const Matrix3& SBNutation::r3 () const [inline, virtual, inherited]
Definition at line 380 of file SbGeoRefFrame.H'.
References SBNutation::R3.
Referenced by SBFrameClassic::dQ_dpsi().
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), operator()(), and SBPolus::operator()().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
const SBNutThGeneral* SBNutation::theory () const [inline, inherited]
Definition at line 376 of file SbGeoRefFrame.H'.
References SBNutation::Theory.
Referenced by SBTestNutation::createWidget4Test(), SBTestNutation::displayValues(), and SBTestNutation::SBTestNutation().
virtual double SBNutation::trueEps () const [inline, virtual, inherited]"Returns current true obliquity'.
Definition at line 362 of file SbGeoRefFrame.H'.
References SBNutation::DeltaEps, and SBNutation::Eps.
Referenced by SBTestNutation::createWidget4Test(), and SBTestNutation::displayValues().
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
double SBNutation::AlphaE [protected, inherited]
equation of equinox
Definition at line 328 of file SbGeoRefFrame.H'.
Referenced by SBNutation::eqEquinox(), SBNut_IAU1980::operator()(), operator()(), and SBNutation::SBNutation().
const SBConfig* SBNutation::Cfg [protected, inherited]
Definition at line 324 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), operator()(), SBNut_IAU1980::SBNut_IAU1980(), and SBNutation::SBNutation().
double SBNutation::DeltaEps [protected, inherited]
nutation in obliquity
Definition at line 326 of file SbGeoRefFrame.H'.
Referenced by SBNutation::deltaEps(), SBNut_IAU1980::operator()(), operator()(), SBNutation::SBNutation(), and SBNutation::trueEps().
double SBNutation::DeltaPsi [protected, inherited]
nutation in longitude
Definition at line 327 of file SbGeoRefFrame.H'.
Referenced by SBNutation::deltaPsi(), SBNut_IAU1980::operator()(), operator()(), and SBNutation::SBNutation().
double SBNutation::DEps [protected, inherited]
Definition at line 338 of file SbGeoRefFrame.H'.
Referenced by SBNutation::dEps(), SBNut_IAU1980::operator()(), operator()(), and SBNutation::SBNutation().
double SBNutation::DPsi [protected, inherited]
Definition at line 337 of file SbGeoRefFrame.H'.
Referenced by SBNutation::dPsi(), SBNut_IAU1980::operator()(), operator()(), and SBNutation::SBNutation().
RotDerMatrix SBNutation::DR2dpsi [protected, inherited]
Definition at line 335 of file SbGeoRefFrame.H'.
Referenced by SBNutation::dR2dpsi(), SBNut_IAU1980::operator()(), and operator()().
RotDerMatrix SBNutation::DR3deps [protected, inherited]
Definition at line 336 of file SbGeoRefFrame.H'.
Referenced by SBNutation::dR3deps(), SBNut_IAU1980::operator()(), and operator()().
SBEOP* SBNutation::EOP [protected, inherited]
EOP database'.
Definition at line 331 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), operator()(), SBNutation::SBNutation(), and SBNutation::~SBNutation().
const double SBNutation::EphemEps = 84381.448*SEC2RAD [static, protected, inherited]
obliquity at J2000'.0
Definition at line 329 of file SbGeoRefFrame.H'.
Referenced by SBNutation::ephemEps(), SBNut_IAU1980::operator()(), and operator()().
double SBNutation::Eps [protected, inherited]
mean obliquity
Definition at line 325 of file SbGeoRefFrame.H'.
Referenced by SBNutation::meanEps(), SBNut_IAU1980::operator()(), operator()(), SBNutation::SBNutation(), and SBNutation::trueEps().
double SBNutation::GMST [protected, inherited]
Greenwich Mean Sidereal Time'.
Definition at line 340 of file SbGeoRefFrame.H'.
Referenced by SBNutation::calcGST(), calcGST(), SBNutation::gmst(), and SBNutation::SBNutation().
double SBNutation::GST [protected, inherited]
Greenwich Sidereal Time'.
Definition at line 341 of file SbGeoRefFrame.H'.
Referenced by SBNutation::calcGST(), calcGST(), SBNutation::gst(), and SBNutation::SBNutation().
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
double SBNutation::R [protected, inherited]
Definition at line 342 of file SbGeoRefFrame.H'.
Referenced by SBNutation::calcGST(), calcGST(), SBNutation::r(), and SBNutation::SBNutation().
RotMatrix SBNutation::R1 [protected, inherited]
Definition at line 332 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), operator()(), and SBNutation::r1().
RotMatrix SBNutation::R2 [protected, inherited]
Definition at line 333 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), operator()(), and SBNutation::r2().
RotMatrix SBNutation::R3 [protected, inherited]
Definition at line 334 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), operator()(), and SBNutation::r3().
SBNutThGeneral* SBNutation::Theory [protected, inherited]
nutation theory
Definition at line 330 of file SbGeoRefFrame.H'.
Referenced by SBNut_IAU1980::operator()(), operator()(), SBNut_IAU1980::SBNut_IAU1980(), SBNut_IAU2000(), SBNutation::SBNutation(), SBNutation::theory(), and SBNutation::~SBNutation().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.