.TH "SBNutThIAU1996::PlanetTableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBNutThIAU1996::PlanetTableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBN\fP [10]"
.br
.ti -1c
.RI "double \fBA\fP [2]"
.br
.ti -1c
.RI "double \fBB\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 886 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBNutThIAU1996::PlanetTableEntry::A\fP[2]"
.PP
Definition at line 889 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU1996::calc()\&.
.SS "double \fBSBNutThIAU1996::PlanetTableEntry::B\fP[2]"
.PP
Definition at line 889 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU1996::calc()\&.
.SS "short \fBSBNutThIAU1996::PlanetTableEntry::N\fP[10]"
.PP
Definition at line 888 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBNutThIAU1996::calc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
