SBObsVLBIEntry
NAME
SBObsVLBIEntry -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBObservation'.
Public Types
enum Attributes { breakClock1 = 1<<1, breakClock2 = 1<<2, BadMeteo1 = 1<<3, BadMeteo2 = 1<<4, BadCable1 = 1<<5, BadCable2 = 1<<6, processed = 1<<7 }
enum Format { F_YYYYMMDD, F_DDMonYYYY, F_Short, F_Long, F_Year, F_YYMonDD, F_HHMMSS, F_YYYYMMDDSSSSSS, F_INTERNAL, F_YYYYMMDDHHMMSSSS, F_DateShort, F_TimeShort, F_TimeVShort, F_ECCDAT, F_MJD, F_UNIX, F_SINEX, F_SINEX_S }
Public Member Functions
SBObsVLBIEntry (SBVLBISession *)
SBObsVLBIEntry (const SBObsVLBIEntry &)
SBObsVLBIEntry & operator= (const SBObsVLBIEntry &)
virtual ~SBObsVLBIEntry ()
virtual QString ClassName () const
short int station_1Idx () const
short int station_2Idx () const
short int sourceIdx () const
double delay () const
double delayErr () const
double rate () const
double rateErr () const
QString qualCode () const
int quality () const
int dUFlag () const
int rUFlag () const
float correlation () const
double fringePhase () const
float cable_1 () const
float cable_2 () const
float atmTemp_1 () const
float atmTemp_2 () const
float atmPress_1 () const
float atmPress_2 () const
float atmHum_1 () const
float atmHum_2 () const
double delayIon () const
double delayIonErr () const
double rateIon () const
double rateIonErr () const
double refFreq () const
double grDelayAmbig () const
int ionErrorFlag () const
int ambiguityFactor () const
double delayRes () const
double rateRes () const
float altAtmTemp_1 () const
float altAtmTemp_2 () const
float altAtmPress_1 () const
float altAtmPress_2 () const
float altAtmHum_1 () const
float altAtmHum_2 () const
double zenithDelay_1 () const
double zenithDelay_2 () const
SBVLBISession * owner () const
void setAltAtmTemp_1 (double t_)
void setAltAtmTemp_2 (double t_)
void setAltAtmPress_1 (double p_)
void setAltAtmPress_2 (double p_)
void setAltAtmHum_1 (double h_)
void setAltAtmHum_2 (double h_)
void setAmbiguityFactor (int j)
void incAmbigFactor (int j=1)
void decAmbigFactor (int j=1)
virtual bool operator== (const SBObsVLBIEntry &O) const
virtual bool operator!= (const SBObsVLBIEntry &O) const
virtual bool operator< (const SBObsVLBIEntry &O) const
virtual int cmp (const SBObservation &O) const
virtual bool isEligible (SBRunManager *)
virtual bool check () const
virtual void process (SBRunManager *)
virtual const SBVector & O_C ()
virtual const SBVector & Sigma ()
float ambientT_1 (bool IsArtMeteo) const
float ambientT_2 (bool IsArtMeteo) const
float ambientP_1 (bool IsArtMeteo, double scale=1.0) const
float ambientP_2 (bool IsArtMeteo, double scale=1.0) const
float ambientH_1 (bool IsArtMeteo) const
float ambientH_2 (bool IsArtMeteo) const
SBStationInfo * station1Info () const
SBStationInfo * station2Info () const
SBSourceInfo * sourceInfo () const
SBStation * station1 (const SB_TRF *, SBStationInfo *&) const
SBStation * station2 (const SB_TRF *, SBStationInfo *&) const
SBSource * source (const SB_CRF *, SBSourceInfo *&) const
virtual int idx () const
virtual Technique tech () const
virtual void setIdx (int Idx_)
virtual void setTech (Technique Tech_)
virtual const SBMJD & mjd ()
virtual bool operator== (const SBObservation &O) const
virtual bool operator== (const SBMJD &) const
virtual bool operator!= (const SBObservation &O) const
virtual bool operator!= (const SBMJD &) const
virtual bool operator< (const SBObservation &O) const
virtual bool operator< (const SBMJD &) const
virtual void setMJD (int, int, int, int=0, int=0, double=0.0, bool=TRUE)
virtual void setMJD (Format, QString, bool=TRUE)
virtual void setDate (int Date_)
virtual void setTime (long double Time_)
virtual QString toString (Format=F_Short) const
virtual bool isGood ()
virtual operator long double () const
virtual bool operator<= (const SBMJD &) const
virtual bool operator> (const SBMJD &) const
virtual bool operator> (double) const
virtual bool operator>= (const SBMJD &) const
virtual SBMJD & operator+= (const SBMJD &MJD)
virtual SBMJD & operator-= (const SBMJD &MJD)
int date () const
long double time () const
int year () const
int month () const
int hour () const
int min () const
double sec () const
QString month2Str () const
int day () const
int dayOfYear () const
int dayOfWeek () const
QString dayOfWeek2Str () const
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Static Public Member Functions
static int MJD_date (int, int, int)
static long double MJD_time (int, int, double)
static void MJD_rev (int, long double, int &, int &, int &, int &, int &, double &)
static SBMJD currentMJD ()
Protected Attributes
int Idx
an index;
Technique Tech
technique of the observation;
Static Protected Attributes
static const char * monthNames []
static const char * weekdayNames []
Private Attributes
short int Station_1
Station#1'.
short int Station_2
Station#2'.
short int Source
Source'.
double Delay
observed delay, sec
double DelayErr
formal error for observed delay
double Rate
observed delayrate, sec/sec
double RateErr
formal error for observed delay rate
char QualCode [2]
quality code
int DUFlag
delay unweight flag
int RUFlag
rate unweight flag
float Correlation
correlation coefficient
double FringePhase
total fringe phase (deg)
float Cable_1
cable calib correction (one-way) for site 1, sec
float Cable_2
cable calib correction (one-way) for site 2, sec
float AtmTemp_1
ambient atmospheric temp at site 1, C
float AtmTemp_2
ambient atmospheric temp at site 2, C
float AtmPress_1
ambient atmospheric pressure at site 1, mb
float AtmPress_2
ambient atmospheric pressure at site 2, mb
float AtmHum_1
ambient atmospheric humidity at site 1
float AtmHum_2
ambient atmospheric humidity at site 2
double DelayIon
delay ionosphere correction, sec
double DelayIonErr
delay ionosphere correction formal error
double RateIon
delay rate ionosphere correction, sec/sec
double RateIonErr
delay rate ionosphere correction formal error
double RefFreq
Reference frequency (MHz)
double GrDelayAmbig
Group delay ambiguity spacing (sec)
int IonErrorFlag
ionosphere error flag
int AmbiguityFactor
group delay ambiguity factor
double DelayRes
delay residual
double RateRes
delay rate residual
float AltAtmTemp_1
alternate ambient atmospheric temp at site 1, C
float AltAtmTemp_2
alternate ambient atmospheric temp at site 2, C
float AltAtmPress_1
alternate ambient atmospheric pressure at site 1, mb
float AltAtmPress_2
alternate ambient atmospheric pressure at site 2, mb
float AltAtmHum_1
alternate ambient atmospheric humidity at site 1
float AltAtmHum_2
alternate ambient atmospheric humidity at site 2
double ZenithDelay_1
calculated+est zenith delay at site 1 (just for curiosity)
double ZenithDelay_2
calculated+est zenith delay at site 2 (just for curiosity)
SBVLBISession * Owner
an owner of the observation;
Static Private Attributes
static SBVector VLBI_Obs2SRIF
static SBVector VLBI_Sig2SRIF
Friends
class SBVLBISession
SBDS_dat & operator<< (SBDS_dat &, const SBObsVLBIEntry &)
SBDS_dat & operator>> (SBDS_dat &, SBObsVLBIEntry &)
SBDS_aux & operator<< (SBDS_aux &, const SBObsVLBIEntry &)
SBDS_aux & operator>> (SBDS_aux &, SBObsVLBIEntry &)
SBDS_dat & operator<< (SBDS_dat &, const SBVLBISession &)
SBDS_dat & operator>> (SBDS_dat &, SBVLBISession &)
SBDS_aux & operator<< (SBDS_aux &, const SBVLBISession &)
SBDS_aux & operator>> (SBDS_aux &, SBVLBISession &)
SBTS_ngs & operator>> (SBTS_ngs &, SBVLBISession &)
SBDS_dbh & operator>> (SBDS_dbh &, SBVLBISession &)
SBMJD operator+ (const SBMJD &, const SBMJD &)
SBMJD operator+ (const SBMJD &, long double)
SBMJD operator+ (const SBMJD &, double)
SBMJD operator+ (const SBMJD &, float)
SBMJD operator+ (long double, const SBMJD &)
SBMJD operator+ (double, const SBMJD &)
SBMJD operator+ (float, const SBMJD &)
SBMJD operator- (const SBMJD &, const SBMJD &)
SBMJD operator- (const SBMJD &, long double)
SBMJD operator- (const SBMJD &, double)
SBMJD operator- (long double, const SBMJD &)
SBMJD operator- (int, const SBMJD &)
QDataStream & operator<< (QDataStream &, const SBMJD &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &, SBMJD &)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
One record of the VLBI observation'.
Definition at line 594 of file SbGeoObsVLBI.H'.
Member Enumeration Documentation
enum SBObsVLBIEntry::Attributes"Observation's attributes'.
Enumerator:
breakClock1
there is a clock break at Station #1;
breakClock2
there is a clock break at Station #2;
BadMeteo1
there is strange thing about meteo data @1
BadMeteo2
there is strange thing about meteo data @2
BadCable1
there is strange thing about cable correction @1
BadCable2
there is strange thing about cable correction @2
processed
observation has been processed
Reimplemented from SBObservation'.
Definition at line 600 of file SbGeoObsVLBI.H'.
enum SBMJD::Format [inherited]
Enumerator:
F_YYYYMMDD
F_DDMonYYYY
F_Short
F_Long
F_Year
F_YYMonDD
F_HHMMSS
F_YYYYMMDDSSSSSS
F_INTERNAL
F_YYYYMMDDHHMMSSSS
F_DateShort
F_TimeShort
F_TimeVShort
F_ECCDAT
F_MJD
F_UNIX
F_SINEX
F_SINEX_S
Definition at line 49 of file SbGeoTime.H'.
Constructor & Destructor Documentation
SBObsVLBIEntry::SBObsVLBIEntry (SBVLBISession *Owner_)"A constructor'. Creates a copy of object, fills data with zeros'.
Definition at line 528 of file SbGeoObsVLBI.C'.
References AltAtmHum_1, AltAtmHum_2, AltAtmPress_1, AltAtmPress_2, AltAtmTemp_1, AltAtmTemp_2, AmbiguityFactor, AtmHum_1, AtmHum_2, AtmPress_1, AtmPress_2, AtmTemp_1, AtmTemp_2, Cable_1, Cable_2, Correlation, Delay, DelayErr, DelayIon, DelayIonErr, DelayRes, DUFlag, FringePhase, GrDelayAmbig, IonErrorFlag, Owner, QualCode, Rate, RateErr, RateIon, RateIonErr, RateRes, RefFreq, RUFlag, SBObservation::setTech(), Source, Station_1, Station_2, TECH_VLBI, ZenithDelay_1, and ZenithDelay_2.
SBObsVLBIEntry::SBObsVLBIEntry (const SBObsVLBIEntry &Obs_)
Definition at line 578 of file SbGeoObsVLBI.C'.
References AltAtmHum_1, altAtmHum_1(), AltAtmHum_2, altAtmHum_2(), AltAtmPress_1, altAtmPress_1(), AltAtmPress_2, altAtmPress_2(), AltAtmTemp_1, altAtmTemp_1(), AltAtmTemp_2, altAtmTemp_2(), AmbiguityFactor, ambiguityFactor(), AtmHum_1, atmHum_1(), AtmHum_2, atmHum_2(), AtmPress_1, atmPress_1(), AtmPress_2, atmPress_2(), AtmTemp_1, atmTemp_1(), AtmTemp_2, atmTemp_2(), Cable_1, cable_1(), Cable_2, cable_2(), Correlation, correlation(), Delay, delay(), DelayErr, delayErr(), DelayIon, delayIon(), DelayIonErr, delayIonErr(), DelayRes, delayRes(), DUFlag, dUFlag(), FringePhase, fringePhase(), GrDelayAmbig, grDelayAmbig(), IonErrorFlag, ionErrorFlag(), Owner, owner(), QualCode, Rate, rate(), RateErr, rateErr(), RateIon, rateIon(), RateIonErr, rateIonErr(), RateRes, rateRes(), RefFreq, refFreq(), RUFlag, rUFlag(), SBObservation::setTech(), Source, sourceIdx(), Station_1, station_1Idx(), Station_2, station_2Idx(), TECH_VLBI, ZenithDelay_1, zenithDelay_1(), ZenithDelay_2, and zenithDelay_2().
virtual SBObsVLBIEntry::~SBObsVLBIEntry () [inline, virtual]
Definition at line 674 of file SbGeoObsVLBI.H'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
float SBObsVLBIEntry::altAtmHum_1 () const [inline]
Definition at line 716 of file SbGeoObsVLBI.H'.
References AltAtmHum_1.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::altAtmHum_2 () const [inline]
Definition at line 717 of file SbGeoObsVLBI.H'.
References AltAtmHum_2.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::altAtmPress_1 () const [inline]
Definition at line 714 of file SbGeoObsVLBI.H'.
References AltAtmPress_1.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::altAtmPress_2 () const [inline]
Definition at line 715 of file SbGeoObsVLBI.H'.
References AltAtmPress_2.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::altAtmTemp_1 () const [inline]
Definition at line 712 of file SbGeoObsVLBI.H'.
References AltAtmTemp_1.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::altAtmTemp_2 () const [inline]
Definition at line 713 of file SbGeoObsVLBI.H'.
References AltAtmTemp_2.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::ambientH_1 (boolIsArtMeteo) const [inline]
Definition at line 756 of file SbGeoObsVLBI.H'.
References AltAtmHum_1, AtmHum_1, BadMeteo1, and SBAttributed::isAttr().
Referenced by SBDelay::calc().
float SBObsVLBIEntry::ambientH_2 (boolIsArtMeteo) const [inline]
Definition at line 757 of file SbGeoObsVLBI.H'.
References AltAtmHum_2, AtmHum_2, BadMeteo2, and SBAttributed::isAttr().
Referenced by SBDelay::calc().
float SBObsVLBIEntry::ambientP_1 (boolIsArtMeteo, doublescale = 1.0) const [inline]
Definition at line 754 of file SbGeoObsVLBI.H'.
References AltAtmPress_1, AtmPress_1, BadMeteo1, and SBAttributed::isAttr().
Referenced by SBDelay::calc().
float SBObsVLBIEntry::ambientP_2 (boolIsArtMeteo, doublescale = 1.0) const [inline]
Definition at line 755 of file SbGeoObsVLBI.H'.
References AltAtmPress_2, AtmPress_2, BadMeteo2, and SBAttributed::isAttr().
Referenced by SBDelay::calc().
float SBObsVLBIEntry::ambientT_1 (boolIsArtMeteo) const [inline]
Definition at line 752 of file SbGeoObsVLBI.H'.
References AltAtmTemp_1, AtmTemp_1, BadMeteo1, and SBAttributed::isAttr().
Referenced by SBDelay::calc().
float SBObsVLBIEntry::ambientT_2 (boolIsArtMeteo) const [inline]
Definition at line 753 of file SbGeoObsVLBI.H'.
References AltAtmTemp_2, AtmTemp_2, BadMeteo2, and SBAttributed::isAttr().
Referenced by SBDelay::calc().
int SBObsVLBIEntry::ambiguityFactor () const [inline]
Definition at line 708 of file SbGeoObsVLBI.H'.
References AmbiguityFactor.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
float SBObsVLBIEntry::atmHum_1 () const [inline]
Definition at line 699 of file SbGeoObsVLBI.H'.
References AtmHum_1.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::atmHum_2 () const [inline]
Definition at line 700 of file SbGeoObsVLBI.H'.
References AtmHum_2.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::atmPress_1 () const [inline]
Definition at line 697 of file SbGeoObsVLBI.H'.
References AtmPress_1.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::atmPress_2 () const [inline]
Definition at line 698 of file SbGeoObsVLBI.H'.
References AtmPress_2.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::atmTemp_1 () const [inline]
Definition at line 695 of file SbGeoObsVLBI.H'.
References AtmTemp_1.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::atmTemp_2 () const [inline]
Definition at line 696 of file SbGeoObsVLBI.H'.
References AtmTemp_2.
Referenced by operator=(), and SBObsVLBIEntry().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
float SBObsVLBIEntry::cable_1 () const [inline]
Definition at line 693 of file SbGeoObsVLBI.H'.
References Cable_1.
Referenced by operator=(), and SBObsVLBIEntry().
float SBObsVLBIEntry::cable_2 () const [inline]
Definition at line 694 of file SbGeoObsVLBI.H'.
References Cable_2.
Referenced by operator=(), and SBObsVLBIEntry().
virtual bool SBObsVLBIEntry::check () const [inline, virtual]
Implements SBObservation'.
Definition at line 745 of file SbGeoObsVLBI.H'.
References Source, Station_1, Station_2, and TZero.
virtual QString SBObsVLBIEntry::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBObservation'.
Definition at line 675 of file SbGeoObsVLBI.H'.
Referenced by isEligible(), process(), source(), station1(), and station2().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
virtual int SBObsVLBIEntry::cmp (const SBObservation &O) const [inline, virtual]
Reimplemented from SBObservation'.
Definition at line 737 of file SbGeoObsVLBI.H'.
float SBObsVLBIEntry::correlation () const [inline]
Definition at line 691 of file SbGeoObsVLBI.H'.
References Correlation.
Referenced by SBDelay::calc(), operator=(), and SBObsVLBIEntry().
SBMJD SBMJD::currentMJD () [static, inherited]
Definition at line 134 of file SbGeoTime.C'.
Referenced by operator<<(), SBRunManager::process_m1(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and writeNormalEquationSystem().
int SBMJD::date () const [inline, inherited]
Definition at line 121 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBNutation::calcGST(), SBTime::DefineTAI_UTC(), SBRunManager::loadVLBISession_m1(), operator<<(), operator>>(), SBTestEphem::recalc(), and SBTime::setUTC().
int SBMJD::day () const [inherited]
Definition at line 208 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), operator<<(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
int SBMJD::dayOfWeek () const [inherited]
Definition at line 225 of file SbGeoTime.C'.
References SBMJD::Date, and SBMJD::SBMJD().
Referenced by SBMJD::dayOfWeek2Str().
QString SBMJD::dayOfWeek2Str () const [inherited]
Definition at line 231 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::dayOfWeek(), and SBMJD::weekdayNames.
Referenced by SBMJD::toString().
int SBMJD::dayOfYear () const [inherited]
Definition at line 220 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), and SBMJD::year().
Referenced by SBHMf_NMF::operator()(), and SBMJD::toString().
void SBObsVLBIEntry::decAmbigFactor (intj = 1) [inline]
Definition at line 731 of file SbGeoObsVLBI.H'.
References AmbiguityFactor, DelayRes, and GrDelayAmbig.
Referenced by SBVLBISessionEditor::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
double SBObsVLBIEntry::delay () const [inline]
Definition at line 683 of file SbGeoObsVLBI.H'.
References Delay.
Referenced by operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::delayErr () const [inline]
Definition at line 684 of file SbGeoObsVLBI.H'.
References DelayErr.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
double SBObsVLBIEntry::delayIon () const [inline]
Definition at line 701 of file SbGeoObsVLBI.H'.
References DelayIon.
Referenced by operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::delayIonErr () const [inline]
Definition at line 702 of file SbGeoObsVLBI.H'.
References DelayIonErr.
Referenced by operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::delayRes () const [inline]
Definition at line 710 of file SbGeoObsVLBI.H'.
References DelayRes.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
int SBObsVLBIEntry::dUFlag () const [inline]
Definition at line 689 of file SbGeoObsVLBI.H'.
References DUFlag.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
double SBObsVLBIEntry::fringePhase () const [inline]
Definition at line 692 of file SbGeoObsVLBI.H'.
References FringePhase.
Referenced by SBDelay::calc(), operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::grDelayAmbig () const [inline]
Definition at line 706 of file SbGeoObsVLBI.H'.
References GrDelayAmbig.
Referenced by operator=(), and SBObsVLBIEntry().
int SBMJD::hour () const [inherited]
Definition at line 167 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
virtual int SBObservation::idx () const [inline, virtual, inherited]
Definition at line 71 of file SbGeoObs.H'.
References SBObservation::Idx.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), SBObservation::operator<(), operator<(), SBObservation::operator=(), SBObservation::operator==(), SBObservation::SBObservation(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
void SBObsVLBIEntry::incAmbigFactor (intj = 1) [inline]
Definition at line 730 of file SbGeoObsVLBI.H'.
References AmbiguityFactor, DelayRes, and GrDelayAmbig.
Referenced by SBVLBISessionEditor::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
int SBObsVLBIEntry::ionErrorFlag () const [inline]
Definition at line 707 of file SbGeoObsVLBI.H'.
References IonErrorFlag.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), ambientH_1(), ambientH_2(), ambientP_1(), ambientP_2(), ambientT_1(), ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
bool SBObsVLBIEntry::isEligible (SBRunManager *Mgr) [virtual]
Reimplemented from SBObservation'.
Definition at line 702 of file SbGeoObsVLBI.C'.
References SBObjectObsInfo::aka(), SBProject::baseList(), SBProject::cfg(), ClassName(), SBLog::DATA, SBAttributed::delAttr(), DelayRes, DUFlag, SBConfig::dUFlagThreshold(), SBLog::ERR, SBStationInfoList::find(), SBBaseInfoList::find(), SBSourceInfoList::find(), IonErrorFlag, SBAttributed::isAttr(), SBConfig::isUseBadIon(), Log, SBStationInfo::notValid, SBBaseInfo::notValid, SBSourceInfo::notValid, owner(), SBRunManager::prj(), processed, SBConfig::qCodeThreshold(), quality(), RateRes, Source, SBVLBISession::sourceInfo(), SBProject::sourceList(), Station_1, Station_2, SBVLBISession::stationInfo(), SBProject::stationList(), SBStationID::toString(), and SBLog::write().
virtual bool SBMJD::isGood () [inline, virtual, inherited]
Definition at line 87 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBSourceEditor::acquireData(), SBAploChunk::import(), SBEcc::importEccDat(), operator>>(), and SBVLBISession::parseObsDumpString().
int SBMJD::min () const [inherited]
Definition at line 179 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
virtual const SBMJD& SBObservation::mjd () [inline, virtual, inherited]
Definition at line 75 of file SbGeoObs.H'.
Referenced by SBDelay::calc(), SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), and SBRunManager::process_m1().
int SBMJD::MJD_date (inty, intm, intd) [static, inherited]
Definition at line 72 of file SbGeoTime.C'.
Referenced by SBMJD::dayOfYear(), and SBMJD::setMJD().
void SBMJD::MJD_rev (intdate_, long doubletime_, int &y, int &m, int &d, int &hr, int &mi, double &se) [static, inherited]
Definition at line 95 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::day(), SBMJD::hour(), SBMJD::min(), SBMJD::month(), SBMJD::sec(), SBMJD::toString(), and SBMJD::year().
long double SBMJD::MJD_time (intHour, intMin, doubleSec) [static, inherited]
Definition at line 90 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::setMJD().
int SBMJD::month () const [inherited]
Definition at line 155 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBMJD::month2Str(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
QString SBMJD::month2Str () const [inherited]
Definition at line 203 of file SbGeoTime.C'.
References SBMJD::month(), and SBMJD::monthNames.
Referenced by operator<<().
const SBVector & SBObsVLBIEntry::O_C () [virtual]
Implements SBObservation'.
Definition at line 991 of file SbGeoObsVLBI.C'.
References VLBI_Obs2SRIF.
Referenced by process().
virtual SBMJD::operator long double () const [inline, virtual, inherited]
Definition at line 89 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
virtual bool SBObservation::operator!= (const SBObservation &O) const [inline, virtual, inherited]
Definition at line 88 of file SbGeoObs.H'.
bool SBMJD::operator!= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 206 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
virtual bool SBObsVLBIEntry::operator!= (const SBObsVLBIEntry &O) const [inline, virtual]
Definition at line 735 of file SbGeoObsVLBI.H'.
SBMJD & SBMJD::operator+= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 254 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator-= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 262 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
virtual bool SBObservation::operator< (const SBObservation &O) const [inline, virtual, inherited]
Definition at line 90 of file SbGeoObs.H'.
References SBObservation::idx(), SBObservation::operator==(), and SBObservation::tech().
bool SBMJD::operator< (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 211 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool operator< (const SBObsVLBIEntry &O) const [inline, virtual]"Compares two instances of SBObsVLBIEntry'.
Definition at line 1345 of file SbGeoObsVLBI.H'.
References SBObservation::idx(), SBNamed::name(), operator==(), Owner, owner(), and SBObservation::tech().
bool SBMJD::operator<= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 217 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBObsVLBIEntry & SBObsVLBIEntry::operator= (const SBObsVLBIEntry &Obs_)
Definition at line 627 of file SbGeoObsVLBI.C'.
References AltAtmHum_1, altAtmHum_1(), AltAtmHum_2, altAtmHum_2(), AltAtmPress_1, altAtmPress_1(), AltAtmPress_2, altAtmPress_2(), AltAtmTemp_1, altAtmTemp_1(), AltAtmTemp_2, altAtmTemp_2(), AmbiguityFactor, ambiguityFactor(), AtmHum_1, atmHum_1(), AtmHum_2, atmHum_2(), AtmPress_1, atmPress_1(), AtmPress_2, atmPress_2(), AtmTemp_1, atmTemp_1(), AtmTemp_2, atmTemp_2(), Cable_1, cable_1(), Cable_2, cable_2(), Correlation, correlation(), Delay, delay(), DelayErr, delayErr(), DelayIon, delayIon(), DelayIonErr, delayIonErr(), DelayRes, delayRes(), DUFlag, dUFlag(), FringePhase, fringePhase(), GrDelayAmbig, grDelayAmbig(), IonErrorFlag, ionErrorFlag(), QualCode, Rate, rate(), RateErr, rateErr(), RateIon, rateIon(), RateIonErr, rateIonErr(), RateRes, rateRes(), RefFreq, refFreq(), RUFlag, rUFlag(), SBObservation::setTech(), Source, sourceIdx(), Station_1, station_1Idx(), Station_2, station_2Idx(), TECH_VLBI, ZenithDelay_1, zenithDelay_1(), ZenithDelay_2, and zenithDelay_2().
virtual bool SBObservation::operator== (const SBObservation &O) const [inline, virtual, inherited]
Definition at line 85 of file SbGeoObs.H'.
References SBObservation::idx(), and SBObservation::tech().
Referenced by SBObservation::operator<().
bool SBMJD::operator== (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 201 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool operator== (const SBObsVLBIEntry &O) const [inline, virtual]"Compares two instances of SBObsVLBIEntry'.
Definition at line 1337 of file SbGeoObsVLBI.H'.
References SBNamed::name(), Owner, and owner().
Referenced by operator<().
bool SBMJD::operator> (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 223 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator> (doubled) const [inline, virtual, inherited]
Definition at line 229 of file SbGeoTime.H'.
References SBMJD::SBMJD().
bool SBMJD::operator>= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 234 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBVLBISession* SBObsVLBIEntry::owner () const [inline]
Definition at line 720 of file SbGeoObsVLBI.H'.
References Owner.
Referenced by isEligible(), operator<(), operator==(), process(), SBObsVLBIEntry(), sourceInfo(), station1Info(), and station2Info().
void SBObsVLBIEntry::process (SBRunManager *Mgr) [virtual]
Implements SBObservation'.
Definition at line 773 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), SBVLBISesInfo::addDelayRMS(), SBObjectObsInfo::addWRMS(), SBObjectObsInfo::aka(), AmbiguityFactor, SBStationInfo::BadCable, SBProject::baseList(), breakClock1, breakClock2, SBClockBreaksList::bt(), Cable_1, Cable_2, SBDelay::calc(), SBStation::calcDisplacement(), SBProject::cfg(), SBStationInfo::cl_Order(), ClassName(), SBParametersDesc::clock0(), SBStationInfo::clockBreaks(), SBStationInfo::clocksValue(), SBRunManager::crf(), SBLog::DATA, SBRunManager::delay(), Delay, SBLog::DELAYALL, DelayErr, DelayIon, DelayIonErr, DelayRes, SBLog::ERR, SBStationInfoList::find(), SBBaseInfoList::find(), SBSourceInfoList::find(), GrDelayAmbig, SBStation::id(), SBStationInfo::InvCable, SBAttributed::isAttr(), SBDerivation::IsBreak, SBDerivation::IsInRun, Log, SBNamed::name(), O_C(), Owner, owner(), SBConfig::p(), SBStation::p_C0(), SBStation::p_Cable(), SBStation::p_Clock(), SBRunManager::prj(), processed, SBParameterCfg::PT_STH, refFreq(), SBVector::set(), SBDerivation::setD(), SBLog::SOURCE, source(), SBProject::sourceList(), SBLog::STATION, station1(), station2(), SBProject::stationList(), SBVLBISesInfo::tMean(), SBStationID::toString(), SBDelay::totalDelay(), SBDelay::totZenithDelay1(), SBDelay::totZenithDelay2(), SBRunManager::trf(), SBParameterCfg::type(), SBSource::updateParameters(), SBParameter::v(), VLBI_Obs2SRIF, VLBI_Sig2SRIF, SBLog::write(), ZenithDelay_1, and ZenithDelay_2.
QString SBObsVLBIEntry::qualCode () const [inline]
Definition at line 687 of file SbGeoObsVLBI.H'.
References QualCode.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
int SBObsVLBIEntry::quality () const
Definition at line 679 of file SbGeoObsVLBI.C'.
References QualCode.
Referenced by isEligible().
double SBObsVLBIEntry::rate () const [inline]
Definition at line 685 of file SbGeoObsVLBI.H'.
References Rate.
Referenced by operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::rateErr () const [inline]
Definition at line 686 of file SbGeoObsVLBI.H'.
References RateErr.
Referenced by SBVLBIObsLI::key(), operator=(), SBObsVLBIEntry(), and SBVLBIObsLI::text().
double SBObsVLBIEntry::rateIon () const [inline]
Definition at line 703 of file SbGeoObsVLBI.H'.
References RateIon.
Referenced by operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::rateIonErr () const [inline]
Definition at line 704 of file SbGeoObsVLBI.H'.
References RateIonErr.
Referenced by operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::rateRes () const [inline]
Definition at line 711 of file SbGeoObsVLBI.H'.
References RateRes.
Referenced by SBVLBIObsLI::key(), operator=(), SBObsVLBIEntry(), and SBVLBIObsLI::text().
double SBObsVLBIEntry::refFreq () const [inline]
Definition at line 705 of file SbGeoObsVLBI.H'.
References RefFreq.
Referenced by SBDelay::calc(), operator=(), process(), and SBObsVLBIEntry().
int SBObsVLBIEntry::rUFlag () const [inline]
Definition at line 690 of file SbGeoObsVLBI.H'.
References RUFlag.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
double SBMJD::sec () const [inherited]
Definition at line 191 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
void SBObsVLBIEntry::setAltAtmHum_1 (doubleh_) [inline]
Definition at line 726 of file SbGeoObsVLBI.H'.
References AltAtmHum_1.
void SBObsVLBIEntry::setAltAtmHum_2 (doubleh_) [inline]
Definition at line 727 of file SbGeoObsVLBI.H'.
References AltAtmHum_2.
void SBObsVLBIEntry::setAltAtmPress_1 (doublep_) [inline]
Definition at line 724 of file SbGeoObsVLBI.H'.
References AltAtmPress_1.
void SBObsVLBIEntry::setAltAtmPress_2 (doublep_) [inline]
Definition at line 725 of file SbGeoObsVLBI.H'.
References AltAtmPress_2.
void SBObsVLBIEntry::setAltAtmTemp_1 (doublet_) [inline]
Definition at line 722 of file SbGeoObsVLBI.H'.
References AltAtmTemp_1.
void SBObsVLBIEntry::setAltAtmTemp_2 (doublet_) [inline]
Definition at line 723 of file SbGeoObsVLBI.H'.
References AltAtmTemp_2.
void SBObsVLBIEntry::setAmbiguityFactor (intj) [inline]
Definition at line 728 of file SbGeoObsVLBI.H'.
References AmbiguityFactor.
Referenced by SBVLBISession::restoreUserInfo().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual void SBMJD::setDate (intDate_) [inline, virtual, inherited]
Definition at line 81 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBAploChunk::import().
virtual void SBObservation::setIdx (intIdx_) [inline, virtual, inherited]
Definition at line 73 of file SbGeoObs.H'.
References SBObservation::Idx.
Referenced by SBObservation::operator=(), and SBObservation::SBObservation().
void SBMJD::setMJD (intYear, intMonth, intDay, intHour = 0, intMin = 0, doubleSec = 0.0, bool = TRUE) [virtual, inherited]
Definition at line 64 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), SBMJD::MJD_time(), and SBMJD::Time.
Referenced by SBStuffEOPs::accept(), SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBEcc::importEccDat(), operator>>(), SBVLBISession::parseObsDumpString(), SBTest::recalc(), SBStationInfo::restoreUserInfo(), SBMJD::SBMJD(), and SBMJD::setMJD().
void SBMJD::setMJD (FormatF, QStrings, boolisReset = TRUE) [virtual, inherited]
Definition at line 357 of file SbGeoTime.C'.
References SBMJD::ClassName(), SBMJD::Date, SBLog::ERR, SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::INF, Log, SBMJD::min(), SBMJD::MJD_date(), SBMJD::monthNames, SBMJD::sec(), SBMJD::setMJD(), SBMJD::Time, SBLog::TIME, SBLog::write(), and SBLog::WRN.
virtual void SBObservation::setTech (TechniqueTech_) [inline, virtual, inherited]
Definition at line 74 of file SbGeoObs.H'.
References SBObservation::Tech.
Referenced by SBObservation::operator=(), operator=(), operator>>(), SBObservation::SBObservation(), and SBObsVLBIEntry().
virtual void SBMJD::setTime (long doubleTime_) [inline, virtual, inherited]
Definition at line 82 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBAploChunk::import().
const SBVector & SBObsVLBIEntry::Sigma () [virtual]
Implements SBObservation'.
Definition at line 996 of file SbGeoObsVLBI.C'.
References VLBI_Sig2SRIF.
SBSource * source (const SB_CRF *CRF, SBSourceInfo *&SrInfo) const [inline]"Returns Source'.
Definition at line 1421 of file SbGeoObsVLBI.H'.
References ClassName(), SBLog::DELAYALL, SBLog::ERR, SB_CRF::find(), Log, SBNamed::name(), SBLog::SOURCE, Source, sourceInfo(), and SBLog::write().
Referenced by process().
short int SBObsVLBIEntry::sourceIdx () const [inline]
Definition at line 682 of file SbGeoObsVLBI.H'.
References Source.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBVLBISession::parseObsDumpString(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
SBSourceInfo * sourceInfo () const [inline]"Returns Source Info for source'.
Definition at line 1413 of file SbGeoObsVLBI.H'.
References owner(), Source, and SBVLBISession::sourceInfo().
Referenced by source().
SBStation * station1 (const SB_TRF *TRF, SBStationInfo *&StInfo) const [inline]"Returns Station corresponded to station#1'.
Definition at line 1377 of file SbGeoObsVLBI.H'.
References ClassName(), SBLog::DELAYALL, SBLog::ERR, SB_TRF::find(), Log, SBLog::STATION, station1Info(), Station_1, and SBLog::write().
Referenced by process().
SBStationInfo * station1Info () const [inline]"Returns Station Info for station#1'.
Definition at line 1369 of file SbGeoObsVLBI.H'.
References owner(), Station_1, and SBVLBISession::stationInfo().
Referenced by station1().
SBStation * station2 (const SB_TRF *TRF, SBStationInfo *&StInfo) const [inline]"Returns Station corresponded to station#2'.
Definition at line 1399 of file SbGeoObsVLBI.H'.
References ClassName(), SBLog::DELAYALL, SBLog::ERR, SB_TRF::find(), Log, SBLog::STATION, station2Info(), Station_1, and SBLog::write().
Referenced by process().
SBStationInfo * station2Info () const [inline]"Returns Station Info for station#2'.
Definition at line 1391 of file SbGeoObsVLBI.H'.
References owner(), Station_2, and SBVLBISession::stationInfo().
Referenced by station2().
short int SBObsVLBIEntry::station_1Idx () const [inline]
Definition at line 680 of file SbGeoObsVLBI.H'.
References Station_1.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBVLBISession::parseObsDumpString(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
short int SBObsVLBIEntry::station_2Idx () const [inline]
Definition at line 681 of file SbGeoObsVLBI.H'.
References Station_2.
Referenced by SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), operator=(), SBVLBISession::parseObsDumpString(), SBObsVLBIEntry(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
virtual Technique SBObservation::tech () const [inline, virtual, inherited]
Definition at line 72 of file SbGeoObs.H'.
References SBObservation::Tech.
Referenced by SBObservation::operator<(), operator<(), SBObservation::operator=(), SBObservation::operator==(), and SBObservation::SBObservation().
long double SBMJD::time () const [inline, inherited]
Definition at line 122 of file SbGeoTime.H'.
References SBMJD::Time.
Referenced by SBOceanTideLd::ARG_IERS(), SBNutation::calcGST(), and SBTestEOP::fillData4Plotting().
QString SBMJD::toString (FormatF = F_Short) const [virtual, inherited]
Definition at line 243 of file SbGeoTime.C'.
References SBMJD::Date, DAY2SEC, SBMJD::dayOfWeek2Str(), SBMJD::dayOfYear(), SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_MJD, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_UNIX, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBMJD::F_YYYYMMDDSSSSSS, SBMJD::min(), SBMJD::MJD_rev(), SBMJD::monthNames, SBMJD::sec(), SBMJD::Time, TUnix0, TZero, and SBMJD::year().
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBEphem::calcI(), SBRunManager::checkParameterLists(), SBEOP::checkRanges(), SBStuffEOPs::createInfoGroup(), SBTestFrame::createWidget4Test(), SBTest::createWidgets(), SBStationEditor::delCoordinates(), SBStuffStationsEcc::deleteEntry(), SBStaParsEditor::deleteEntry(), SBEOP::dEps(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), SBEOP::dLOD(), SBEOP::dPsi(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBPlotArea::drawXmjdTics(), SBDBHHistTriplet::dump(), SBDBHStartBlock::dump(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBVLBIPreProcess::fillSessAttr(), SBEstimator::GroupList::find(), SBStochParameter::find(), SBAploEphem::getReady(), SBEphem::import(), SBEstimator::GroupList::inSort(), SBEOP::interpolateEOPs(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBSolutionBatchLI::key(), SBObsVLBIStatRecordLI::key(), SBEccListItem::key(), SBCoordsListItem::key(), SBAploHeaderLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBAploHeader::name(), SBEphem::openFile(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), operator<<(), operator>>(), SBEOP::prepare4Date(), SBTest::recalc(), SBStationEcc::registerEcc(), SBEstimator::GroupList::remove(), SBParameterList::report(), SBStochParameter::report(), SBStuffAplo::SBStuffAplo(), SBStuffEphem::SBStuffEphem(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), SBTime::setUTC(), sinex_HeaderLine(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_SiteEccentricityBlock(), sinex_SolutionEpochsBlock(), sinex_tro_HeaderLine(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBVLBIObsPPLI::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBObsVLBIStatRecordLI::text(), SBEccListItem::text(), SBVLBIObsLI::text(), SBCoordsListItem::text(), SBAploHeaderLI::text(), SBClockBreakLI::text(), SBParameter::timeStamp(), SBStuffEOPs::updateEOP(), SBStuffEphem::updateEphem(), SBStuffAplo::updateEphem(), SBVLBIPreProcess::wAttributes(), SBVLBISessionEditor::wParameters(), and SBSourceEditor::wStats().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
int SBMJD::year () const [inherited]
Definition at line 143 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBVLBISesInfo::checkPath(), SBTest::createWidgets(), SBMJD::dayOfYear(), SBVLBISesInfo::fileName(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), and SBMJD::toString().
double SBObsVLBIEntry::zenithDelay_1 () const [inline]
Definition at line 718 of file SbGeoObsVLBI.H'.
References ZenithDelay_1.
Referenced by operator=(), and SBObsVLBIEntry().
double SBObsVLBIEntry::zenithDelay_2 () const [inline]
Definition at line 719 of file SbGeoObsVLBI.H'.
References ZenithDelay_2.
Referenced by operator=(), and SBObsVLBIEntry().
Friends And Related Function Documentation
SBMJD operator+ (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 270 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 275 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 280 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, floatb) [friend, inherited]
Definition at line 285 of file SbGeoTime.H'.
SBMJD operator+ (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 290 of file SbGeoTime.H'.
SBMJD operator+ (doublea, const SBMJD &B) [friend, inherited]
Definition at line 295 of file SbGeoTime.H'.
SBMJD operator+ (floata, const SBMJD &B) [friend, inherited]
Definition at line 300 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 305 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 310 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 315 of file SbGeoTime.H'.
SBMJD operator- (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 320 of file SbGeoTime.H'.
SBMJD operator- (inta, const SBMJD &B) [friend, inherited]
Definition at line 325 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBMJD &MJD) [friend, inherited]
Definition at line 330 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
SBDS_dat& operator<< (SBDS_dat &s, const SBObsVLBIEntry &Entry) [friend]
Definition at line 1009 of file SbGeoObsVLBI.C'.
SBDS_aux& operator<< (SBDS_aux &s, const SBObsVLBIEntry &Entry) [friend]
Definition at line 1042 of file SbGeoObsVLBI.C'.
SBDS_dat& operator<< (SBDS_dat &s, const SBVLBISession &S) [friend]
Definition at line 1867 of file SbGeoObsVLBI.C'.
SBDS_aux& operator<< (SBDS_aux &, const SBVLBISession &) [friend]
QDataStream& operator>> (QDataStream &s, SBMJD &MJD) [friend, inherited]
Definition at line 337 of file SbGeoTime.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
SBDS_dat& operator>> (SBDS_dat &s, SBObsVLBIEntry &Entry) [friend]
Definition at line 1025 of file SbGeoObsVLBI.C'.
SBDS_aux& operator>> (SBDS_aux &s, SBObsVLBIEntry &Entry) [friend]
Definition at line 1052 of file SbGeoObsVLBI.C'.
SBDS_dat& operator>> (SBDS_dat &s, SBVLBISession &S) [friend]
Definition at line 1873 of file SbGeoObsVLBI.C'.
SBDS_aux& operator>> (SBDS_aux &s, SBVLBISession &S) [friend]
Definition at line 1888 of file SbGeoObsVLBI.C'.
SBTS_ngs& operator>> (SBTS_ngs &, SBVLBISession &) [friend]
SBDS_dbh& operator>> (SBDS_dbh &, SBVLBISession &) [friend]
friend class SBVLBISession [friend]
Definition at line 596 of file SbGeoObsVLBI.H'.
Member Data Documentation
float SBObsVLBIEntry::AltAtmHum_1 [private]
alternate ambient atmospheric humidity at site 1
Definition at line 655 of file SbGeoObsVLBI.H'.
Referenced by altAtmHum_1(), ambientH_1(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), and setAltAtmHum_1().
float SBObsVLBIEntry::AltAtmHum_2 [private]
alternate ambient atmospheric humidity at site 2
Definition at line 656 of file SbGeoObsVLBI.H'.
Referenced by altAtmHum_2(), ambientH_2(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), and setAltAtmHum_2().
float SBObsVLBIEntry::AltAtmPress_1 [private]
alternate ambient atmospheric pressure at site 1, mb
Definition at line 653 of file SbGeoObsVLBI.H'.
Referenced by altAtmPress_1(), ambientP_1(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), and setAltAtmPress_1().
float SBObsVLBIEntry::AltAtmPress_2 [private]
alternate ambient atmospheric pressure at site 2, mb
Definition at line 654 of file SbGeoObsVLBI.H'.
Referenced by altAtmPress_2(), ambientP_2(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), and setAltAtmPress_2().
float SBObsVLBIEntry::AltAtmTemp_1 [private]
alternate ambient atmospheric temp at site 1, C
Definition at line 651 of file SbGeoObsVLBI.H'.
Referenced by altAtmTemp_1(), ambientT_1(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), and setAltAtmTemp_1().
float SBObsVLBIEntry::AltAtmTemp_2 [private]
alternate ambient atmospheric temp at site 2, C
Definition at line 652 of file SbGeoObsVLBI.H'.
Referenced by altAtmTemp_2(), ambientT_2(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), and setAltAtmTemp_2().
int SBObsVLBIEntry::AmbiguityFactor [private]
group delay ambiguity factor
Definition at line 645 of file SbGeoObsVLBI.H'.
Referenced by ambiguityFactor(), decAmbigFactor(), incAmbigFactor(), operator<<(), operator=(), operator>>(), process(), SBObsVLBIEntry(), and setAmbiguityFactor().
float SBObsVLBIEntry::AtmHum_1 [private]
ambient atmospheric humidity at site 1
Definition at line 633 of file SbGeoObsVLBI.H'.
Referenced by ambientH_1(), atmHum_1(), SBVLBISession::checkArtMeteo(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
float SBObsVLBIEntry::AtmHum_2 [private]
ambient atmospheric humidity at site 2
Definition at line 634 of file SbGeoObsVLBI.H'.
Referenced by ambientH_2(), atmHum_2(), SBVLBISession::checkArtMeteo(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
float SBObsVLBIEntry::AtmPress_1 [private]
ambient atmospheric pressure at site 1, mb
Definition at line 631 of file SbGeoObsVLBI.H'.
Referenced by ambientP_1(), atmPress_1(), SBVLBISession::checkArtMeteo(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
float SBObsVLBIEntry::AtmPress_2 [private]
ambient atmospheric pressure at site 2, mb
Definition at line 632 of file SbGeoObsVLBI.H'.
Referenced by ambientP_2(), atmPress_2(), SBVLBISession::checkArtMeteo(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
float SBObsVLBIEntry::AtmTemp_1 [private]
ambient atmospheric temp at site 1, C
Definition at line 629 of file SbGeoObsVLBI.H'.
Referenced by ambientT_1(), atmTemp_1(), SBVLBISession::checkArtMeteo(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
float SBObsVLBIEntry::AtmTemp_2 [private]
ambient atmospheric temp at site 2, C
Definition at line 630 of file SbGeoObsVLBI.H'.
Referenced by ambientT_2(), atmTemp_2(), SBVLBISession::checkArtMeteo(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
float SBObsVLBIEntry::Cable_1 [private]
cable calib correction (one-way) for site 1, sec
Definition at line 627 of file SbGeoObsVLBI.H'.
Referenced by cable_1(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
float SBObsVLBIEntry::Cable_2 [private]
cable calib correction (one-way) for site 2, sec
Definition at line 628 of file SbGeoObsVLBI.H'.
Referenced by cable_2(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
float SBObsVLBIEntry::Correlation [private]
correlation coefficient
Definition at line 625 of file SbGeoObsVLBI.H'.
Referenced by correlation(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
double SBObsVLBIEntry::Delay [private]
observed delay, sec
Definition at line 618 of file SbGeoObsVLBI.H'.
Referenced by delay(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
double SBObsVLBIEntry::DelayErr [private]
formal error for observed delay
Definition at line 619 of file SbGeoObsVLBI.H'.
Referenced by delayErr(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
double SBObsVLBIEntry::DelayIon [private]
delay ionosphere correction, sec
Definition at line 636 of file SbGeoObsVLBI.H'.
Referenced by delayIon(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
double SBObsVLBIEntry::DelayIonErr [private]
delay ionosphere correction formal error
Definition at line 637 of file SbGeoObsVLBI.H'.
Referenced by delayIonErr(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
double SBObsVLBIEntry::DelayRes [private]
delay residual
Definition at line 648 of file SbGeoObsVLBI.H'.
Referenced by decAmbigFactor(), delayRes(), incAmbigFactor(), isEligible(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
int SBObsVLBIEntry::DUFlag [private]
delay unweight flag
Definition at line 623 of file SbGeoObsVLBI.H'.
Referenced by dUFlag(), isEligible(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
double SBObsVLBIEntry::FringePhase [private]
total fringe phase (deg)
Definition at line 626 of file SbGeoObsVLBI.H'.
Referenced by fringePhase(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
double SBObsVLBIEntry::GrDelayAmbig [private]
Group delay ambiguity spacing (sec)
Definition at line 642 of file SbGeoObsVLBI.H'.
Referenced by decAmbigFactor(), grDelayAmbig(), incAmbigFactor(), operator<<(), operator=(), operator>>(), process(), and SBObsVLBIEntry().
int SBObservation::Idx [protected, inherited]
an index;
Definition at line 55 of file SbGeoObs.H'.
Referenced by SBObservation::idx(), operator<<(), operator>>(), SBObservation::SBObservation(), and SBObservation::setIdx().
int SBObsVLBIEntry::IonErrorFlag [private]
ionosphere error flag
Definition at line 644 of file SbGeoObsVLBI.H'.
Referenced by ionErrorFlag(), isEligible(), operator<<(), operator=(), operator>>(), and SBObsVLBIEntry().
const char * SBMJD::monthNames [static, protected, inherited]"Initial value:
 
{
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
}
Definition at line 63 of file SbGeoTime.H'.
Referenced by SBMJD::month2Str(), SBMJD::setMJD(), and SBMJD::toString().
SBVLBISession* SBObsVLBIEntry::Owner [private]
an owner of the observation;
Definition at line 662 of file SbGeoObsVLBI.H'.
Referenced by operator<(), operator==(), owner(), process(), and SBObsVLBIEntry().
char SBObsVLBIEntry::QualCode[2] [private]
quality code
Definition at line 622 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), qualCode(), quality(), and SBObsVLBIEntry().
double SBObsVLBIEntry::Rate [private]
observed delayrate, sec/sec
Definition at line 620 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), rate(), and SBObsVLBIEntry().
double SBObsVLBIEntry::RateErr [private]
formal error for observed delay rate
Definition at line 621 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), rateErr(), and SBObsVLBIEntry().
double SBObsVLBIEntry::RateIon [private]
delay rate ionosphere correction, sec/sec
Definition at line 638 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), rateIon(), and SBObsVLBIEntry().
double SBObsVLBIEntry::RateIonErr [private]
delay rate ionosphere correction formal error
Definition at line 639 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), rateIonErr(), and SBObsVLBIEntry().
double SBObsVLBIEntry::RateRes [private]
delay rate residual
Definition at line 649 of file SbGeoObsVLBI.H'.
Referenced by isEligible(), operator<<(), operator=(), operator>>(), rateRes(), and SBObsVLBIEntry().
double SBObsVLBIEntry::RefFreq [private]
Reference frequency (MHz)
Definition at line 641 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), refFreq(), and SBObsVLBIEntry().
int SBObsVLBIEntry::RUFlag [private]
rate unweight flag
Definition at line 624 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), rUFlag(), and SBObsVLBIEntry().
short int SBObsVLBIEntry::Source [private]
Source'.
Definition at line 617 of file SbGeoObsVLBI.H'.
Referenced by check(), isEligible(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), source(), sourceIdx(), and sourceInfo().
short int SBObsVLBIEntry::Station_1 [private]
Station#1'.
Definition at line 615 of file SbGeoObsVLBI.H'.
Referenced by check(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), isEligible(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), station1(), station1Info(), station2(), and station_1Idx().
short int SBObsVLBIEntry::Station_2 [private]
Station#2'.
Definition at line 616 of file SbGeoObsVLBI.H'.
Referenced by check(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), isEligible(), operator<<(), operator=(), operator>>(), SBObsVLBIEntry(), station2Info(), and station_2Idx().
Technique SBObservation::Tech [protected, inherited]
technique of the observation;
Definition at line 56 of file SbGeoObs.H'.
Referenced by SBObservation::SBObservation(), SBObservation::setTech(), and SBObservation::tech().
SBVector SBObsVLBIEntry::VLBI_Obs2SRIF [static, private]
Definition at line 665 of file SbGeoObsVLBI.H'.
Referenced by O_C(), and process().
SBVector SBObsVLBIEntry::VLBI_Sig2SRIF [static, private]
Definition at line 666 of file SbGeoObsVLBI.H'.
Referenced by process(), and Sigma().
const char * SBMJD::weekdayNames [static, protected, inherited]"Initial value:
{
  'Mon','Tue','Wed','Thu','Fri','Sat','Sun'
}
Definition at line 64 of file SbGeoTime.H'.
Referenced by SBMJD::dayOfWeek2Str().
double SBObsVLBIEntry::ZenithDelay_1 [private]
calculated+est zenith delay at site 1 (just for curiosity)
Definition at line 658 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), process(), SBObsVLBIEntry(), and zenithDelay_1().
double SBObsVLBIEntry::ZenithDelay_2 [private]
calculated+est zenith delay at site 2 (just for curiosity)
Definition at line 659 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator=(), operator>>(), process(), SBObsVLBIEntry(), and zenithDelay_2().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.