.TH "SBObsVLBIStatRecordLI" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBObsVLBIStatRecordLI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBIStat\&.H>\fP
.PP
Inherits \fBQListViewItem\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBObsVLBIStatRecordLI\fP (\fBQListView\fP *parent, \fBSBObsVLBIStatRecord\fP *SR_)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "\fBSBObsVLBIStatRecord\fP * \fBstatRecord\fP ()"
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.ti -1c
.RI "virtual QString \fBkey\fP (int, bool) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBObsVLBIStatRecord\fP * \fBSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file SbIObsVLBIStat\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBObsVLBIStatRecordLI::SBObsVLBIStatRecordLI (\fBQListView\fP *parent, \fBSBObsVLBIStatRecord\fP *SR_)\fC [inline]\fP"
.PP
Definition at line 90 of file SbIObsVLBIStat\&.H'\&.
.PP
References SR\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBObsVLBIStatRecordLI::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 92 of file SbIObsVLBIStat\&.H'\&.
.SS "QString SBObsVLBIStatRecordLI::key (intcol, bool) const\fC [virtual]\fP"
.PP
Definition at line 212 of file SbIObsVLBIStat\&.C'\&.
.PP
References SBObsVLBIStatRecord::aka(), SBMJD::F_MJD, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SBObsVLBIStatRecord::rms(), SBSetUp::scale(), SetUp, SR, SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), and SBObsVLBIStatRecord::tStartTotal()\&.
.SS "\fBSBObsVLBIStatRecord\fP* SBObsVLBIStatRecordLI::statRecord ()\fC [inline]\fP"
.PP
Definition at line 93 of file SbIObsVLBIStat\&.H'\&.
.PP
References SR\&.
.SS "QString SBObsVLBIStatRecordLI::text (intcol) const\fC [virtual]\fP"
.PP
Definition at line 183 of file SbIObsVLBIStat\&.C'\&.
.PP
References SBObsVLBIStatRecord::aka(), SBMJD::F_DDMonYYYY, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SBObsVLBIStatRecord::rms(), SBSetUp::scale(), SetUp, SR, SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), SBObsVLBIStatRecord::tStartTotal(), and TZero\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBObsVLBIStatRecord\fP* \fBSBObsVLBIStatRecordLI::SR\fP\fC [private]\fP"
.PP
Definition at line 88 of file SbIObsVLBIStat\&.H'\&.
.PP
Referenced by key(), SBObsVLBIStatRecordLI(), statRecord(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
