SBObsVLBIStatSrcLI
NAME
SBObsVLBIStatSrcLI -
SYNOPSIS
#include <SbIObsVLBIStat.H>
Inherits QListViewItem'.
Public Member Functions
SBObsVLBIStatSrcLI (QListView *parent, SBObsVLBIStatSource *SS_)
virtual QString ClassName () const
SBObsVLBIStatSource * sourceStatistics ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBObsVLBIStatSource * SS
Detailed Description
Definition at line 43 of file SbIObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatSrcLI::SBObsVLBIStatSrcLI (QListView *parent, SBObsVLBIStatSource *SS_) [inline]
Definition at line 48 of file SbIObsVLBIStat.H'.
References SS.
Member Function Documentation
virtual QString SBObsVLBIStatSrcLI::ClassName () const [inline, virtual]
Definition at line 50 of file SbIObsVLBIStat.H'.
QString SBObsVLBIStatSrcLI::key (intcol, bool) const [virtual]
Definition at line 71 of file SbIObsVLBIStat.C'.
References SBObsVLBIStatSource::aka(), SBMJD::F_MJD, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SS, SBObsVLBIStatSource::statPerSession(), SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), and SBObsVLBIStatRecord::tStartTotal().
SBObsVLBIStatSource* SBObsVLBIStatSrcLI::sourceStatistics () [inline]
Definition at line 51 of file SbIObsVLBIStat.H'.
References SS.
QString SBObsVLBIStatSrcLI::text (intcol) const [virtual]
Definition at line 41 of file SbIObsVLBIStat.C'.
References SBObsVLBIStatSource::aka(), SBMJD::F_DDMonYYYY, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SS, SBObsVLBIStatSource::statPerSession(), SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), SBObsVLBIStatRecord::tStartTotal(), and TZero.
Member Data Documentation
SBObsVLBIStatSource* SBObsVLBIStatSrcLI::SS [private]
Definition at line 46 of file SbIObsVLBIStat.H'.
Referenced by key(), SBObsVLBIStatSrcLI(), sourceStatistics(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.