SBObsVLBIStatStaLI
NAME
SBObsVLBIStatStaLI -
SYNOPSIS
#include <SbIObsVLBIStat.H>
Inherits QListViewItem'.
Public Member Functions
SBObsVLBIStatStaLI (QListView *parent, SBObsVLBIStatStation *SS_)
virtual QString ClassName () const
SBObsVLBIStatStation * stationStatistics ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBObsVLBIStatStation * SS
Detailed Description
Definition at line 64 of file SbIObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatStaLI::SBObsVLBIStatStaLI (QListView *parent, SBObsVLBIStatStation *SS_) [inline]
Definition at line 69 of file SbIObsVLBIStat.H'.
References SS.
Member Function Documentation
virtual QString SBObsVLBIStatStaLI::ClassName () const [inline, virtual]
Definition at line 71 of file SbIObsVLBIStat.H'.
QString SBObsVLBIStatStaLI::key (intcol, bool) const [virtual]
Definition at line 142 of file SbIObsVLBIStat.C'.
References SBObsVLBIStatStation::aka(), SBMJD::F_MJD, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SS, SBObsVLBIStatStation::statPerSession(), SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), and SBObsVLBIStatRecord::tStartTotal().
SBObsVLBIStatStation* SBObsVLBIStatStaLI::stationStatistics () [inline]
Definition at line 72 of file SbIObsVLBIStat.H'.
References SS.
QString SBObsVLBIStatStaLI::text (intcol) const [virtual]
Definition at line 112 of file SbIObsVLBIStat.C'.
References SBObsVLBIStatStation::aka(), SBMJD::F_DDMonYYYY, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SS, SBObsVLBIStatStation::statPerSession(), SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), SBObsVLBIStatRecord::tStartTotal(), and TZero.
Member Data Documentation
SBObsVLBIStatStation* SBObsVLBIStatStaLI::SS [private]
Definition at line 67 of file SbIObsVLBIStat.H'.
Referenced by key(), SBObsVLBIStatStaLI(), stationStatistics(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.