SBObsVLBIStatSta
NAME
SBObsVLBIStatSta -
SYNOPSIS
#include <SbIObsVLBIStat.H>
Inherits QDialog'.
Public Member Functions
SBObsVLBIStatSta (SBObsVLBIStatStation *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBObsVLBIStatSta ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Private Member Functions
virtual void acquireData ()
Private Attributes
SBObsVLBIStatStation * StaStat
QListView * SessionLV
Detailed Description
Definition at line 177 of file SbIObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatSta::SBObsVLBIStatSta (SBObsVLBIStatStation *StaStat_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 485 of file SbIObsVLBIStat.C'.
References accept(), SBNamed::name(), SessionLV, StaStat, and SBObsVLBIStatStation::statPerSession().
SBObsVLBIStatSta::~SBObsVLBIStatSta () [virtual]
Definition at line 543 of file SbIObsVLBIStat.C'.
References StaStat.
Member Function Documentation
void SBObsVLBIStatSta::accept () [protected, slot]
Definition at line 548 of file SbIObsVLBIStat.C'.
References acquireData().
Referenced by SBObsVLBIStatSta().
void SBObsVLBIStatSta::acquireData () [private, virtual]
Definition at line 555 of file SbIObsVLBIStat.C'.
Referenced by accept().
virtual QString SBObsVLBIStatSta::ClassName () const [inline, virtual]
Definition at line 183 of file SbIObsVLBIStat.H'.
void SBObsVLBIStatSta::reject () [inline, protected, slot]
Definition at line 189 of file SbIObsVLBIStat.H'.
Member Data Documentation
QListView* SBObsVLBIStatSta::SessionLV [private]
Definition at line 193 of file SbIObsVLBIStat.H'.
Referenced by SBObsVLBIStatSta().
SBObsVLBIStatStation* SBObsVLBIStatSta::StaStat [private]
Definition at line 189 of file SbIObsVLBIStat.H'.
Referenced by SBObsVLBIStatSta(), and ~SBObsVLBIStatSta().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.