SBObsVLBIStatBrowser
NAME
SBObsVLBIStatBrowser -
SYNOPSIS
#include <SbIObsVLBIStat.H>
Inherits SBTabDialog'.
Public Member Functions
SBObsVLBIStatBrowser (bool=FALSE, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBObsVLBIStatBrowser ()
virtual QString ClassName () const
Protected Slots
void editSrcEntry (QListViewItem *)
void editStaEntry (QListViewItem *)
virtual void makeApply ()
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual void acquireData ()
Private Member Functions
QWidget * wStationStatistics ()
QWidget * wSourceStatistics ()
Private Attributes
SBObsVLBIStatistics * Statistics
QListView * StaLV
QListView * SrcLV
Detailed Description
Definition at line 106 of file SbIObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatBrowser::SBObsVLBIStatBrowser (boolIsGlobal = FALSE, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 250 of file SbIObsVLBIStat.C'.
References SBSetUp::loadObsVLBIStatistics(), SBNamed::name(), SetUp, Statistics, wSourceStatistics(), and wStationStatistics().
SBObsVLBIStatBrowser::~SBObsVLBIStatBrowser () [virtual]
Definition at line 270 of file SbIObsVLBIStat.C'.
References Statistics.
Member Function Documentation
virtual void SBTabDialog::acquireData () [inline, protected, virtual, inherited]
Reimplemented in SBVLBISessionEditor, SBStationEditor, SBSiteEditor, SBParametersEditor, SBSourceEditor, SBModelEditor, SBProjectEdit, and SBSetupDialog'.
Definition at line 91 of file SbInterface.H'.
Referenced by SBTabDialog::done(), and SBTabDialog::makeApply().
virtual QString SBObsVLBIStatBrowser::ClassName () const [inline, virtual]
Definition at line 112 of file SbIObsVLBIStat.H'.
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
void SBObsVLBIStatBrowser::editSrcEntry (QListViewItem *Item) [protected, slot]
Definition at line 381 of file SbIObsVLBIStat.C'.
Referenced by wSourceStatistics().
void SBObsVLBIStatBrowser::editStaEntry (QListViewItem *Item) [protected, slot]
Definition at line 388 of file SbIObsVLBIStat.C'.
Referenced by wStationStatistics().
virtual void SBTabDialog::makeApply () [inline, protected, virtual, slot, inherited]
Reimplemented in SBVLBISessionEditor, SBStationEditor, SBSiteEditor, SBParametersEditor, SBSourceEditor, SBModelEditor, SBProjectEdit, and SBSetupDialog'.
Definition at line 78 of file SbInterface.H'.
References SBTabDialog::acquireData().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
QWidget * SBObsVLBIStatBrowser::wSourceStatistics () [private]
Definition at line 330 of file SbIObsVLBIStat.C'.
References editSrcEntry(), SBObsVLBIStatistics::sourcesStatistics(), SrcLV, and Statistics.
Referenced by SBObsVLBIStatBrowser().
QWidget * SBObsVLBIStatBrowser::wStationStatistics () [private]
Definition at line 279 of file SbIObsVLBIStat.C'.
References editStaEntry(), StaLV, SBObsVLBIStatistics::stationsStatistics(), and Statistics.
Referenced by SBObsVLBIStatBrowser().
Member Data Documentation
QListView* SBObsVLBIStatBrowser::SrcLV [private]
Definition at line 129 of file SbIObsVLBIStat.H'.
Referenced by wSourceStatistics().
QListView* SBObsVLBIStatBrowser::StaLV [private]
Definition at line 125 of file SbIObsVLBIStat.H'.
Referenced by wStationStatistics().
SBObsVLBIStatistics* SBObsVLBIStatBrowser::Statistics [private]
Definition at line 120 of file SbIObsVLBIStat.H'.
Referenced by SBObsVLBIStatBrowser(), wSourceStatistics(), wStationStatistics(), and ~SBObsVLBIStatBrowser().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.