SBObjectObsInfo
NAME
SBObjectObsInfo -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBAttributed'.
Inherited by SBBaseInfo, SBSourceInfo, and SBStationInfo'.
Public Member Functions
SBObjectObsInfo (int Idx_=0, const QString &Aka_='unkn')
virtual ~SBObjectObsInfo ()
virtual QString ClassName () const
short int idx () const
unsigned int num () const
unsigned int procNum () const
const QString & aka () const
double wrms () const
void setIdx (int Idx_)
void setNum (unsigned int Num_)
void setProcNum (unsigned int ProcNum_)
void setAka (const QString &Aka_)
void incNum ()
void addWRMS (double o_c_, double w_)
void clearRMSs ()
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Private Attributes
short int Idx
session's local index
unsigned int Num
number of obs per object
unsigned int ProcNum
number of processed observations per object
QString Aka
an alias (how it's called in datafile)
double SWRMS2
sum of WRMS^2 per object
double SWeight
sum of weights per object
Friends
QDataStream & operator<< (QDataStream &, const SBObjectObsInfo &)
QDataStream & operator>> (QDataStream &, SBObjectObsInfo &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Provides basic session's objects information for SBVLBISession'. Keeps necessary information on objects (stations, sources, etc) to make a reasonably quick/usefull session management'.
Definition at line 69 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBObjectObsInfo::SBObjectObsInfo (intIdx_ = 0, const QString &Aka_ = 'unkn') [inline]"A constructor'. Creates a copy of object'.
Parameters:
Idx_ session index of the object (default is 0);
Aka_ session alias of the object (default is 'unkn')'.
Definition at line 84 of file SbGeoObsVLBI.H'.
References Aka, Idx, Num, ProcNum, SWeight, and SWRMS2.
virtual SBObjectObsInfo::~SBObjectObsInfo () [inline, virtual]"A destructor'.
Definition at line 87 of file SbGeoObsVLBI.H'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
void SBObjectObsInfo::addWRMS (doubleo_c_, doublew_) [inline]"Increments number of observation by one, adds RMS^2 to sum of (RMS^2)'.
Definition at line 112 of file SbGeoObsVLBI.H'.
References ProcNum, SWeight, and SWRMS2.
Referenced by SBObsVLBIEntry::process().
const QString& SBObjectObsInfo::aka () const [inline]"Returns alias'.
Definition at line 98 of file SbGeoObsVLBI.H'.
References Aka.
Referenced by SBProject::addSession(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBProject::delSession(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBSolution::guessParameterName(), SBObsVLBIEntry::isEligible(), SBCableLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRFVariations(), operator<<(), SBObsVLBIEntry::process(), SBSourceInfo::restoreUserInfo(), SBStaParsEditor::SBStaParsEditor(), sinex_tro_TropSolutionStation(), SBCableLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), and SBVLBISessionEditor::wObservs().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBObjectObsInfo::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBAttributed'.
Reimplemented in SBSourceInfo, SBBaseInfo, and SBStationInfo'.
Definition at line 89 of file SbGeoObsVLBI.H'.
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBObjectObsInfo::clearRMSs () [inline]
Definition at line 113 of file SbGeoObsVLBI.H'.
References ProcNum, SWeight, and SWRMS2.
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
short int SBObjectObsInfo::idx () const [inline]"Returns local index'.
Definition at line 92 of file SbGeoObsVLBI.H'.
References Idx.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBVLBISession::fillDicts(), SBCableLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBVLBISession::parseObsDumpString(), SBStationInfo::restoreUserInfo(), SBCableLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), and SBSouInfoLI::text().
void SBObjectObsInfo::incNum () [inline]"Increments number of observation by one'.
Definition at line 110 of file SbGeoObsVLBI.H'.
References Num.
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
unsigned int SBObjectObsInfo::num () const [inline]"Returns number of observations'.
Definition at line 94 of file SbGeoObsVLBI.H'.
References Num.
Referenced by SBProject::addSession(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBProject::delSession(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBRunManager::makeReportCRFVariations4IVS(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
unsigned int SBObjectObsInfo::procNum () const [inline]"Returns number of processed observations'.
Definition at line 96 of file SbGeoObsVLBI.H'.
References ProcNum.
Referenced by SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStaInfoLI::text(), SBBasInfoLI::text(), and SBSouInfoLI::text().
void SBObjectObsInfo::setAka (const QString &Aka_) [inline]"Sets up alias'.
Definition at line 108 of file SbGeoObsVLBI.H'.
References Aka.
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBObjectObsInfo::setIdx (intIdx_) [inline]"Sets up index'.
Definition at line 102 of file SbGeoObsVLBI.H'.
References Idx.
void SBObjectObsInfo::setNum (unsigned intNum_) [inline]"Sets up number of observations per object'.
Definition at line 104 of file SbGeoObsVLBI.H'.
References Num.
Referenced by SBProject::addSession(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBProject::delSession(), and SBSolutionBrowser::lookupParameters().
void SBObjectObsInfo::setProcNum (unsigned intProcNum_) [inline]"Sets up number of processed observations per object'.
Definition at line 106 of file SbGeoObsVLBI.H'.
References ProcNum.
double SBObjectObsInfo::wrms () const [inline]
Definition at line 99 of file SbGeoObsVLBI.H'.
References SWeight, and SWRMS2.
Referenced by SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStaInfoLI::text(), SBBasInfoLI::text(), and SBSouInfoLI::text().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
QDataStream & operator<< (QDataStream &s, const SBObjectObsInfo &Oi) [friend]"Output to the data stream'.
Definition at line 122 of file SbGeoObsVLBI.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream & operator>> (QDataStream &s, SBObjectObsInfo &Oi) [friend]"Input from the data stream'.
Definition at line 128 of file SbGeoObsVLBI.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
Member Data Documentation
QString SBObjectObsInfo::Aka [private]
an alias (how it's called in datafile)
Definition at line 75 of file SbGeoObsVLBI.H'.
Referenced by aka(), SBObjectObsInfo(), and setAka().
short int SBObjectObsInfo::Idx [private]
session's local index
Definition at line 72 of file SbGeoObsVLBI.H'.
Referenced by idx(), SBObjectObsInfo(), and setIdx().
unsigned int SBObjectObsInfo::Num [private]
number of obs per object
Definition at line 73 of file SbGeoObsVLBI.H'.
Referenced by incNum(), num(), SBObjectObsInfo(), and setNum().
unsigned int SBObjectObsInfo::ProcNum [private]
number of processed observations per object
Definition at line 74 of file SbGeoObsVLBI.H'.
Referenced by addWRMS(), clearRMSs(), procNum(), SBObjectObsInfo(), and setProcNum().
double SBObjectObsInfo::SWeight [private]
sum of weights per object
Definition at line 77 of file SbGeoObsVLBI.H'.
Referenced by addWRMS(), clearRMSs(), SBObjectObsInfo(), and wrms().
double SBObjectObsInfo::SWRMS2 [private]
sum of WRMS^2 per object
Definition at line 76 of file SbGeoObsVLBI.H'.
Referenced by addWRMS(), clearRMSs(), SBObjectObsInfo(), and wrms().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.