SBObsVLBIStatSrc
NAME
SBObsVLBIStatSrc -
SYNOPSIS
#include <SbIObsVLBIStat.H>
Inherits QDialog'.
Public Member Functions
SBObsVLBIStatSrc (SBObsVLBIStatSource *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBObsVLBIStatSrc ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Private Member Functions
virtual void acquireData ()
Private Attributes
SBObsVLBIStatSource * SrcStat
QListView * SessionLV
Detailed Description
Definition at line 148 of file SbIObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatSrc::SBObsVLBIStatSrc (SBObsVLBIStatSource *SrcStat_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 403 of file SbIObsVLBIStat.C'.
References accept(), SBNamed::name(), SessionLV, SrcStat, and SBObsVLBIStatSource::statPerSession().
SBObsVLBIStatSrc::~SBObsVLBIStatSrc () [virtual]
Definition at line 461 of file SbIObsVLBIStat.C'.
References SrcStat.
Member Function Documentation
void SBObsVLBIStatSrc::accept () [protected, slot]
Definition at line 466 of file SbIObsVLBIStat.C'.
References acquireData().
Referenced by SBObsVLBIStatSrc().
void SBObsVLBIStatSrc::acquireData () [private, virtual]
Definition at line 473 of file SbIObsVLBIStat.C'.
Referenced by accept().
virtual QString SBObsVLBIStatSrc::ClassName () const [inline, virtual]
Definition at line 154 of file SbIObsVLBIStat.H'.
void SBObsVLBIStatSrc::reject () [inline, protected, slot]
Definition at line 160 of file SbIObsVLBIStat.H'.
Member Data Documentation
QListView* SBObsVLBIStatSrc::SessionLV [private]
Definition at line 164 of file SbIObsVLBIStat.H'.
Referenced by SBObsVLBIStatSrc().
SBObsVLBIStatSource* SBObsVLBIStatSrc::SrcStat [private]
Definition at line 160 of file SbIObsVLBIStat.H'.
Referenced by SBObsVLBIStatSrc(), and ~SBObsVLBIStatSrc().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.