SBObsVLBIStatStation
NAME
SBObsVLBIStatStation -
SYNOPSIS
#include <SbGeoObsVLBIStat.H>
Inherits SBObsVLBIStatRecord'.
Public Member Functions
SBObsVLBIStatStation (const QString &Name_, const QString &Aka_='unkn')
virtual ~SBObsVLBIStatStation ()
virtual QString ClassName () const
const QString & aka () const
void setAka (const QString &Aka_)
SBObsVLBIStatList & statPerSession ()
const SBMJD & tStartTotal () const
const SBMJD & tFinisTotal () const
const SBMJD & tStartProc () const
const SBMJD & tFinisProc () const
unsigned int numTotal () const
unsigned int numProc () const
double rms () const
void setTStartTotal (const SBMJD &T_)
void setTFinisTotal (const SBMJD &T_)
void setTStartProc (const SBMJD &T_)
void setTFinisProc (const SBMJD &T_)
void setNumTotal (int N_)
void setNumProc (int N_)
void setRMS (double RMS_)
void incNumTotal (int N_)
void incNumProc (int N_)
void clear ()
const QString & name () const
void setName (const QString &Name_)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Attributes
QString Name
Private Attributes
SBObsVLBIStatList StatPerSession
QString Aka
Friends
QDataStream & operator<< (QDataStream &, const SBObsVLBIStatStation &)
QDataStream & operator>> (QDataStream &, SBObsVLBIStatStation &)
QDataStream & operator<< (QDataStream &, const SBObsVLBIStatRecord &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &, SBObsVLBIStatRecord &)
QDataStream & operator>> (QDataStream &, SBNamed &)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
Detailed Description
Definition at line 227 of file SbGeoObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatStation::SBObsVLBIStatStation (const QString &Name_, const QString &Aka_ = 'unkn') [inline]"A constructor'. Creates a copy of object'.
Definition at line 239 of file SbGeoObsVLBIStat.H'.
References Aka, and StatPerSession.
virtual SBObsVLBIStatStation::~SBObsVLBIStatStation () [inline, virtual]"A destructor'.
Definition at line 242 of file SbGeoObsVLBIStat.H'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
const QString& SBObsVLBIStatStation::aka () const [inline]
Reimplemented from SBObsVLBIStatRecord'.
Definition at line 248 of file SbGeoObsVLBIStat.H'.
References Aka.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBObsVLBIStatStaLI::key(), and SBObsVLBIStatStaLI::text().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBObsVLBIStatStation::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBObsVLBIStatRecord'.
Definition at line 244 of file SbGeoObsVLBIStat.H'.
void SBObsVLBIStatRecord::clear () [inline, inherited]
Definition at line 93 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::NumProc, SBObsVLBIStatRecord::NumTotal, SBObsVLBIStatRecord::RMS, SBObsVLBIStatRecord::TFinisProc, SBObsVLBIStatRecord::TFinisTotal, SBObsVLBIStatRecord::TStartProc, SBObsVLBIStatRecord::TStartTotal, and TZero.
Referenced by SBObsVLBIStatistics::collectStatistics(), and SBObsVLBIStatRecord::SBObsVLBIStatRecord().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
void SBObsVLBIStatRecord::incNumProc (intN_) [inline, inherited]
Definition at line 89 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::NumProc.
Referenced by SBObsVLBIStatistics::collectStatistics().
void SBObsVLBIStatRecord::incNumTotal (intN_) [inline, inherited]
Definition at line 88 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::NumTotal.
Referenced by SBObsVLBIStatistics::collectStatistics().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
unsigned int SBObsVLBIStatRecord::numProc () const [inline, inherited]
Definition at line 75 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::NumProc.
Referenced by SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBObsVLBIStatRecordLI::key(), SBObsVLBIStatSrcLI::text(), SBObsVLBIStatStaLI::text(), and SBObsVLBIStatRecordLI::text().
unsigned int SBObsVLBIStatRecord::numTotal () const [inline, inherited]
Definition at line 74 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::NumTotal.
Referenced by SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBObsVLBIStatRecordLI::key(), SBObsVLBIStatSrcLI::text(), SBObsVLBIStatStaLI::text(), and SBObsVLBIStatRecordLI::text().
double SBObsVLBIStatRecord::rms () const [inline, inherited]
Definition at line 77 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::RMS.
Referenced by SBObsVLBIStatRecordLI::key(), and SBObsVLBIStatRecordLI::text().
void SBObsVLBIStatStation::setAka (const QString &Aka_) [inline]
Reimplemented from SBObsVLBIStatRecord'.
Definition at line 249 of file SbGeoObsVLBIStat.H'.
References Aka.
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBObsVLBIStatRecord::setNumProc (intN_) [inline, inherited]
Definition at line 84 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::NumProc.
Referenced by SBObsVLBIStatistics::collectStatistics().
void SBObsVLBIStatRecord::setNumTotal (intN_) [inline, inherited]
Definition at line 83 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::NumTotal.
Referenced by SBObsVLBIStatistics::collectStatistics().
void SBObsVLBIStatRecord::setRMS (doubleRMS_) [inline, inherited]
Definition at line 86 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::RMS.
Referenced by SBObsVLBIStatistics::collectStatistics().
void SBObsVLBIStatRecord::setTFinisProc (const SBMJD &T_) [inline, inherited]
Definition at line 82 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TFinisProc.
Referenced by SBObsVLBIStatistics::collectStatistics().
void SBObsVLBIStatRecord::setTFinisTotal (const SBMJD &T_) [inline, inherited]
Definition at line 80 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TFinisTotal.
Referenced by SBObsVLBIStatistics::collectStatistics().
void SBObsVLBIStatRecord::setTStartProc (const SBMJD &T_) [inline, inherited]
Definition at line 81 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TStartProc.
Referenced by SBObsVLBIStatistics::collectStatistics().
void SBObsVLBIStatRecord::setTStartTotal (const SBMJD &T_) [inline, inherited]
Definition at line 79 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TStartTotal.
Referenced by SBObsVLBIStatistics::collectStatistics().
SBObsVLBIStatList& SBObsVLBIStatStation::statPerSession () [inline]
Definition at line 250 of file SbGeoObsVLBIStat.H'.
References StatPerSession.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBObsVLBIStatStaLI::key(), SBObsVLBIStatSta::SBObsVLBIStatSta(), and SBObsVLBIStatStaLI::text().
const SBMJD& SBObsVLBIStatRecord::tFinisProc () const [inline, inherited]
Definition at line 73 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TFinisProc.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBObsVLBIStatRecordLI::key(), SBObsVLBIStatSrcLI::text(), SBObsVLBIStatStaLI::text(), and SBObsVLBIStatRecordLI::text().
const SBMJD& SBObsVLBIStatRecord::tFinisTotal () const [inline, inherited]
Definition at line 71 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TFinisTotal.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBObsVLBIStatRecordLI::key(), SBObsVLBIStatSrcLI::text(), SBObsVLBIStatStaLI::text(), and SBObsVLBIStatRecordLI::text().
const SBMJD& SBObsVLBIStatRecord::tStartProc () const [inline, inherited]
Definition at line 72 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TStartProc.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBObsVLBIStatRecordLI::key(), SBObsVLBIStatSrcLI::text(), SBObsVLBIStatStaLI::text(), and SBObsVLBIStatRecordLI::text().
const SBMJD& SBObsVLBIStatRecord::tStartTotal () const [inline, inherited]
Definition at line 70 of file SbGeoObsVLBIStat.H'.
References SBObsVLBIStatRecord::TStartTotal.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBObsVLBIStatRecordLI::key(), SBObsVLBIStatSrcLI::text(), SBObsVLBIStatStaLI::text(), and SBObsVLBIStatRecordLI::text().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBObsVLBIStatRecord &SR) [friend, inherited]"Output to the data stream'.
Definition at line 103 of file SbGeoObsVLBIStat.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBObsVLBIStatStation &SS) [friend]"Output to the data stream'.
Definition at line 263 of file SbGeoObsVLBIStat.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBObsVLBIStatRecord &SR) [friend, inherited]"Input from the data stream'.
Definition at line 110 of file SbGeoObsVLBIStat.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBObsVLBIStatStation &SS) [friend]"Input from the data stream'.
Definition at line 269 of file SbGeoObsVLBIStat.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
Member Data Documentation
QString SBObsVLBIStatStation::Aka [private]
Reimplemented from SBObsVLBIStatRecord'.
Definition at line 231 of file SbGeoObsVLBIStat.H'.
Referenced by aka(), SBObsVLBIStatStation(), and setAka().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
SBObsVLBIStatList SBObsVLBIStatStation::StatPerSession [private]
Definition at line 230 of file SbGeoObsVLBIStat.H'.
Referenced by SBObsVLBIStatStation(), and statPerSession().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.