SBObsVLBIStatistics
NAME
SBObsVLBIStatistics -
SYNOPSIS
#include <SbGeoObsVLBIStat.H>
Inherits SBNamed'.
Public Member Functions
SBObsVLBIStatistics (const QString &)
virtual ~SBObsVLBIStatistics ()
virtual QString ClassName () const
SBObsVLBIStatRecord & generalStatistics ()
SBObsVLBIStatSrcList & sourcesStatistics ()
SBObsVLBIStatStaList & stationsStatistics ()
bool isGlobal () const
void seIsGlobal (bool Is_)
void collectStatistics (SBVLBISesInfoList *=NULL)
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
QString Name
Private Attributes
SBObsVLBIStatRecord GeneralStatistics
SBObsVLBIStatSrcList SourcesStatistics
SBObsVLBIStatStaList StationsStatistics
bool IsGlobal
Friends
QDataStream & operator<< (QDataStream &, const SBObsVLBIStatistics &)
QDataStream & operator>> (QDataStream &, SBObsVLBIStatistics &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Definition at line 306 of file SbGeoObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatistics::SBObsVLBIStatistics (const QString &Name_)"A constructor'. Creates a copy of object'.
Definition at line 39 of file SbGeoObsVLBIStat.C'.
References IsGlobal, SourcesStatistics, and StationsStatistics.
virtual SBObsVLBIStatistics::~SBObsVLBIStatistics () [inline, virtual]"A destructor'.
Definition at line 323 of file SbGeoObsVLBIStat.H'.
Member Function Documentation
virtual QString SBObsVLBIStatistics::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBNamed'.
Definition at line 325 of file SbGeoObsVLBIStat.H'.
Referenced by collectStatistics().
void SBObsVLBIStatistics::collectStatistics (SBVLBISesInfoList *SessionList = NULL)
Definition at line 46 of file SbGeoObsVLBIStat.C'.
References SBObsVLBIStatSource::aka(), SBObsVLBIStatStation::aka(), ClassName(), SBObsVLBIStatRecord::clear(), SBLog::DATA, SBLog::ERR, SBObsVLBIStatList::find(), SBObsVLBIStatSrcList::find(), SBObsVLBIStatStaList::find(), GeneralStatistics, SBObsVLBIStatRecord::incNumProc(), SBObsVLBIStatRecord::incNumTotal(), SBLog::IO, IsGlobal, SBVLBISet::loadSession(), SBSetUp::loadVLBI(), Log, mainMessage(), mainPrBarReset(), mainPrBarSetProgress(), mainPrBarSetTotalSteps(), mainSetOperation(), mainSetProcSes(), mainSetSessName(), SBNamed::name(), SBVLBISesInfo::notValid, SBVLBISession::numObs(), SBObsVLBIStatRecord::setAka(), SBNamed::setName(), SBObsVLBIStatRecord::setNumProc(), SBObsVLBIStatRecord::setNumTotal(), SBObsVLBIStatRecord::setRMS(), SBObsVLBIStatRecord::setTFinisProc(), SBObsVLBIStatRecord::setTFinisTotal(), SBObsVLBIStatRecord::setTStartProc(), SBObsVLBIStatRecord::setTStartTotal(), SetUp, SBVLBISession::sourceList(), SourcesStatistics, SBVLBISession::stationList(), StationsStatistics, SBObsVLBIStatSource::statPerSession(), SBObsVLBIStatStation::statPerSession(), SBVLBISesInfo::tFinis(), SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), SBVLBISesInfo::tStart(), SBObsVLBIStatRecord::tStartProc(), SBObsVLBIStatRecord::tStartTotal(), TZero, SBLog::write(), and SBLog::WRN.
Referenced by SBMainWindow::UtilitiesCollectStat4All(), and SBMainWindow::UtilitiesCollectStat4Prj().
SBObsVLBIStatRecord& SBObsVLBIStatistics::generalStatistics () [inline]
Definition at line 329 of file SbGeoObsVLBIStat.H'.
References GeneralStatistics.
bool SBObsVLBIStatistics::isGlobal () const [inline]
Definition at line 332 of file SbGeoObsVLBIStat.H'.
References IsGlobal.
Referenced by SBSetUp::saveObsVLBIStatistics().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
void SBObsVLBIStatistics::seIsGlobal (boolIs_) [inline]
Definition at line 333 of file SbGeoObsVLBIStat.H'.
References IsGlobal.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
SBObsVLBIStatSrcList& SBObsVLBIStatistics::sourcesStatistics () [inline]
Definition at line 330 of file SbGeoObsVLBIStat.H'.
References SourcesStatistics.
Referenced by SBObsVLBIStatBrowser::wSourceStatistics().
SBObsVLBIStatStaList& SBObsVLBIStatistics::stationsStatistics () [inline]
Definition at line 331 of file SbGeoObsVLBIStat.H'.
References StationsStatistics.
Referenced by SBObsVLBIStatBrowser::wStationStatistics().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBObsVLBIStatistics &S) [friend]"Output to the data stream'.
Definition at line 348 of file SbGeoObsVLBIStat.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBObsVLBIStatistics &S) [friend]"Input from the data stream'.
Definition at line 354 of file SbGeoObsVLBIStat.H'.
Member Data Documentation
SBObsVLBIStatRecord SBObsVLBIStatistics::GeneralStatistics [private]
Definition at line 309 of file SbGeoObsVLBIStat.H'.
Referenced by collectStatistics(), and generalStatistics().
bool SBObsVLBIStatistics::IsGlobal [private]
Definition at line 312 of file SbGeoObsVLBIStat.H'.
Referenced by collectStatistics(), isGlobal(), SBObsVLBIStatistics(), and seIsGlobal().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
SBObsVLBIStatSrcList SBObsVLBIStatistics::SourcesStatistics [private]
Definition at line 310 of file SbGeoObsVLBIStat.H'.
Referenced by collectStatistics(), SBObsVLBIStatistics(), and sourcesStatistics().
SBObsVLBIStatStaList SBObsVLBIStatistics::StationsStatistics [private]
Definition at line 311 of file SbGeoObsVLBIStat.H'.
Referenced by collectStatistics(), SBObsVLBIStatistics(), and stationsStatistics().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.