SBObsVLBIStatRecordLI
NAME
SBObsVLBIStatRecordLI -
SYNOPSIS
#include <SbIObsVLBIStat.H>
Inherits QListViewItem'.
Public Member Functions
SBObsVLBIStatRecordLI (QListView *parent, SBObsVLBIStatRecord *SR_)
virtual QString ClassName () const
SBObsVLBIStatRecord * statRecord ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBObsVLBIStatRecord * SR
Detailed Description
Definition at line 85 of file SbIObsVLBIStat.H'.
Constructor & Destructor Documentation
SBObsVLBIStatRecordLI::SBObsVLBIStatRecordLI (QListView *parent, SBObsVLBIStatRecord *SR_) [inline]
Definition at line 90 of file SbIObsVLBIStat.H'.
References SR.
Member Function Documentation
virtual QString SBObsVLBIStatRecordLI::ClassName () const [inline, virtual]
Definition at line 92 of file SbIObsVLBIStat.H'.
QString SBObsVLBIStatRecordLI::key (intcol, bool) const [virtual]
Definition at line 212 of file SbIObsVLBIStat.C'.
References SBObsVLBIStatRecord::aka(), SBMJD::F_MJD, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SBObsVLBIStatRecord::rms(), SBSetUp::scale(), SetUp, SR, SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), and SBObsVLBIStatRecord::tStartTotal().
SBObsVLBIStatRecord* SBObsVLBIStatRecordLI::statRecord () [inline]
Definition at line 93 of file SbIObsVLBIStat.H'.
References SR.
QString SBObsVLBIStatRecordLI::text (intcol) const [virtual]
Definition at line 183 of file SbIObsVLBIStat.C'.
References SBObsVLBIStatRecord::aka(), SBMJD::F_DDMonYYYY, SBNamed::name(), SBObsVLBIStatRecord::numProc(), SBObsVLBIStatRecord::numTotal(), SBObsVLBIStatRecord::rms(), SBSetUp::scale(), SetUp, SR, SBObsVLBIStatRecord::tFinisProc(), SBObsVLBIStatRecord::tFinisTotal(), TmpString, SBMJD::toString(), SBObsVLBIStatRecord::tStartProc(), SBObsVLBIStatRecord::tStartTotal(), and TZero.
Member Data Documentation
SBObsVLBIStatRecord* SBObsVLBIStatRecordLI::SR [private]
Definition at line 88 of file SbIObsVLBIStat.H'.
Referenced by key(), SBObsVLBIStatRecordLI(), statRecord(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.