.TH "SBObsVLBIStatSta" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBObsVLBIStatSta \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBIStat\&.H>\fP
.PP
Inherits \fBQDialog\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBObsVLBIStatSta\fP (\fBSBObsVLBIStatStation\fP *, \fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "virtual \fB~SBObsVLBIStatSta\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.ti -1c
.RI "void \fBreject\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBacquireData\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBObsVLBIStatStation\fP * \fBStaStat\fP"
.br
.ti -1c
.RI "\fBQListView\fP * \fBSessionLV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 177 of file SbIObsVLBIStat\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBObsVLBIStatSta::SBObsVLBIStatSta (\fBSBObsVLBIStatStation\fP *StaStat_, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 485 of file SbIObsVLBIStat\&.C'\&.
.PP
References accept(), SBNamed::name(), SessionLV, StaStat, and SBObsVLBIStatStation::statPerSession()\&.
.SS "SBObsVLBIStatSta::~SBObsVLBIStatSta ()\fC [virtual]\fP"
.PP
Definition at line 543 of file SbIObsVLBIStat\&.C'\&.
.PP
References StaStat\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBObsVLBIStatSta::accept ()\fC [protected, slot]\fP"
.PP
Definition at line 548 of file SbIObsVLBIStat\&.C'\&.
.PP
References acquireData()\&.
.PP
Referenced by SBObsVLBIStatSta()\&.
.SS "void SBObsVLBIStatSta::acquireData ()\fC [private, virtual]\fP"
.PP
Definition at line 555 of file SbIObsVLBIStat\&.C'\&.
.PP
Referenced by accept()\&.
.SS "virtual QString SBObsVLBIStatSta::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 183 of file SbIObsVLBIStat\&.H'\&.
.SS "void SBObsVLBIStatSta::reject ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 189 of file SbIObsVLBIStat\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBQListView\fP* \fBSBObsVLBIStatSta::SessionLV\fP\fC [private]\fP"
.PP
Definition at line 193 of file SbIObsVLBIStat\&.H'\&.
.PP
Referenced by SBObsVLBIStatSta()\&.
.SS "\fBSBObsVLBIStatStation\fP* \fBSBObsVLBIStatSta::StaStat\fP\fC [private]\fP"
.PP
Definition at line 189 of file SbIObsVLBIStat\&.H'\&.
.PP
Referenced by SBObsVLBIStatSta(), and ~SBObsVLBIStatSta()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
