SBOceanTideLd
NAME
SBOceanTideLd -
SYNOPSIS
#include <SbGeoTide.H>
Inherits Vector3'.
Public Member Functions
SBOceanTideLd (const SBConfig *)
virtual ~SBOceanTideLd ()
virtual QString ClassName () const
virtual const Vector3 & operator() (const SBOLoad *, const SBTime &)
double & operator[] (DIRECTION i)
double at (DIRECTION i) const
double module () const
double phi () const
double lambda () const
Vector3 & unify ()
Vector3 unit () const
void clear ()
Vector3 & operator+= (const Vector3 &)
Vector3 & operator-= (const Vector3 &)
Vector3 & operator*= (double)
Vector3 & operator/= (double)
virtual void report2Log (SBLog::LogLevel, uint, const QString &, int, int, double=1.0) const
bool operator== (const Vector3 &v) const
bool operator!= (const Vector3 &v) const
Protected Member Functions
void ARG_IERS (const SBTime &)
Protected Attributes
const SBConfig * Cfg
double ANGLE [11]
double vec [3]
Static Protected Attributes
static const double SPEED [11]
static const double ANGFAC [4][11]
static const SBMJD _1975
Friends
Vector3 operator- (const Vector3 &)
Vector3 operator- (const Vector3 &, const Vector3 &)
Vector3 operator+ (const Vector3 &, const Vector3 &)
Vector3 operator/ (const Vector3 &, double)
Vector3 operator* (const Vector3 &, double)
Vector3 operator* (double, const Vector3 &)
double operator* (const Vector3 &, const Vector3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Vector3 operator% (const Vector3 &, const Vector3 &)
QDataStream & operator<< (QDataStream &s, const Vector3 &v)
QDataStream & operator>> (QDataStream &s, Vector3 &v)
Detailed Description
Ocean Tides Load displacements'. Inherits Vector3 representing VEN local tide displacement'.
Todo
Need some redesigning with respect to SBStation::oLoad() implementation'.
Definition at line 49 of file SbGeoTide.H'.
Constructor & Destructor Documentation
SBOceanTideLd::SBOceanTideLd (const SBConfig *Cfg_)"A constructor'.
A constructor'. Creates a copy of object'.
Definition at line 126 of file SbGeoTide.C'.
References ANGLE, and Cfg.
virtual SBOceanTideLd::~SBOceanTideLd () [inline, virtual]"A destructor'.
Definition at line 62 of file SbGeoTide.H'.
Member Function Documentation
void SBOceanTideLd::ARG_IERS (const SBTime &Time) [protected]"COMPUTES THE ANGULAR ARGUMENT WHICH DEPENDS ON TIME FOR 11 TIDAL ARGUMENT CALCULATIONS'. This strange subroutine has been printed in the IERS Technical Note 21, IERS Conventions (1996)'. It is assumed that it calculates the '(omega_j*t + hi_j)' part of the equation (4), p'.53 (however, it is not stated explicitly)'.
Definition at line 137 of file SbGeoTide.C'.
References _1975, ANGFAC, ANGLE, DEG2RAD, SPEED, SBMJD::time(), and SBTime::UT1().
Referenced by operator()().
double Vector3::at (DIRECTIONi) const [inline, inherited]
Definition at line 72 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBStationEditor::acquireData(), SBDelay::calc(), SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBTestEphem::createWidget4Test(), SBPlateMotion::displacement(), SBTestEphem::displayCoo(), SBTestAPLoad::fillData4Plotting(), SBEccListItem::key(), SBCoordsListItem::key(), SBRunManager::makeReportMaps(), Matrix3::Matrix3(), operator<<(), SB_TRF::prepareEccs4Session(), SBRefraction::refrDir(), SBStationEcc::registerEcc(), SBCoordsEditor::SBCoordsEditor(), sinex_SiteEccentricityBlock(), sinex_tro_StaCoordinatesBlock(), SBEccListItem::text(), SBCoordsListItem::text(), SBPlateEntry::velocity(), SBPlateMotion::velocity(), SBStationEditor::wCoordinates(), and SBSiteEditor::wSite().
virtual QString SBOceanTideLd::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from Vector3'.
Definition at line 64 of file SbGeoTide.H'.
Referenced by operator()().
void Vector3::clear () [inline, inherited]
Definition at line 79 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), operator()(), SBPolarTideLd::operator()(), and SBSolidTideLd::operator()().
double Vector3::lambda () const [inline, inherited]
Definition at line 75 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), and SBSolidTideLd::operator()().
double Vector3::module () const [inline, inherited]
Definition at line 73 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBSolidTideLdIERS96::deg3InPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBStationImport::importITRF(), Vector3::lambda(), SBSolidTideLdIERS96::latDepend(), SBRunManager::makeReportMaps(), SBSolidTideLd::makeStep1(), Vector3::phi(), Vector3::report2Log(), Vector3::unify(), and Vector3::unit().
bool Vector3::operator!= (const Vector3 &v) const [inline, inherited]
Definition at line 102 of file SbVector3.H'.
const Vector3 & SBOceanTideLd::operator() (const SBOLoad *OLoad, const SBTime &Time) [virtual]"Calculates site's displacements due to ocean loading corresponds to time T'.
Definition at line 176 of file SbGeoTide.C'.
References SBOLoad::amplitude(), ANGLE, ARG_IERS(), ClassName(), Vector3::clear(), DEG2RAD, SBLog::ERR, SBTime::fArg_Omega(), Log, SBOLoad::phase(), sincos(), SBLog::TIDES, Vector3::vec, and SBLog::write().
Vector3 & Vector3::operator*= (doublev) [inline, inherited]
Definition at line 247 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator+= (const Vector3 &V) [inline, inherited]
Definition at line 235 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator-= (const Vector3 &V) [inline, inherited]
Definition at line 241 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator/= (doublev) [inline, inherited]
Definition at line 253 of file SbVector3.H'.
References Vector3::vec.
bool Vector3::operator== (const Vector3 &v) const [inline, inherited]
Definition at line 100 of file SbVector3.H'.
References Vector3::vec.
double& Vector3::operator[] (DIRECTIONi) [inline, inherited]
Definition at line 71 of file SbVector3.H'.
References Vector3::vec.
double Vector3::phi () const [inline, inherited]
Definition at line 74 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dLag(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::permTide(), and SBSolidTideLdIERS96::permTide().
void Vector3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref, intw_, intd_, doubleScale = 1.0) const [virtual, inherited]
Definition at line 39 of file SbVector3.C'.
References Log, Vector3::module(), Vector3::vec, and SBLog::write().
Referenced by SBStation::axisOffsetLenght(), SBDelay::calc(), SBEphem::calc(), SBAploEphem::displacement(), SBSolidTideLd::operator()(), SBTideLd::operator()(), and SBRefraction::operator()().
Vector3& Vector3::unify () [inline, inherited]
Definition at line 77 of file SbVector3.H'.
References Vector3::module().
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg3InPhase(), and SBSolidTideLdIERS96::latDepend().
Vector3 Vector3::unit () const [inline, inherited]
Definition at line 78 of file SbVector3.H'.
References Vector3::module(), and Vector3::Vector3().
Referenced by SBDelay::calc(), SBRunManager::constraintStationVeloc(), SBSolidTideLd::dTide_dH2(), and SBSolidTideLd::dTide_dL2().
Friends And Related Function Documentation
Vector3 operator% (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a vector product of two vectors (because '%' has a priority of '*')
makes vector product of two vectors'.
Definition at line 326 of file SbVector3.H'.
Vector3 operator* (const Vector3 &V1, doublev2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 302 of file SbVector3.H'.
Vector3 operator* (doublev1, const Vector3 &V2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 310 of file SbVector3.H'.
double operator* (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a scalar product of two vectors
makes scalar product of two vectors'.
Definition at line 318 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &M, const Vector3 &V) [friend, inherited]"makes a product of matrix and vector
Matrix3 makes product of matrix and vector'.
Definition at line 519 of file SbVector3.H'.
Vector3 operator+ (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 278 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V) [friend, inherited]
Definition at line 270 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 286 of file SbVector3.H'.
Vector3 operator/ (const Vector3 &V1, doublev2) [friend, inherited]
Definition at line 294 of file SbVector3.H'.
QDataStream& operator<< (QDataStream &s, const Vector3 &v) [friend, inherited]
Definition at line 103 of file SbVector3.H'.
QDataStream& operator>> (QDataStream &s, Vector3 &v) [friend, inherited]
Definition at line 105 of file SbVector3.H'.
Member Data Documentation
const SBMJD SBOceanTideLd::_1975 [static, protected]
Definition at line 55 of file SbGeoTide.H'.
Referenced by ARG_IERS().
const double SBOceanTideLd::ANGFAC [static, protected]"Initial value:
{
  { 2.0, 0.0, 2.0, 2.0, 1.0 , 1.0 ,-1.0 , 1.0 , 0.0, 0.0, 2.0},
  { -2.0, 0.0,-3.0, 0.0, 0.0 ,-2.0 , 0.0 ,-3.0 , 2.0, 1.0, 0.0},
  { 0.0, 0.0, 1.0, 0.0, 0.0 , 0.0 , 0.0 , 1.0 , 0.0,-1.0, 0.0},
  { 0.0, 0.0, 0.0, 0.0, 0.25,-0.25,-0.25,-0.25, 0.0, 0.0, 0.0}
}
Definition at line 54 of file SbGeoTide.H'.
Referenced by ARG_IERS().
double SBOceanTideLd::ANGLE[11] [protected]
Definition at line 56 of file SbGeoTide.H'.
Referenced by ARG_IERS(), operator()(), and SBOceanTideLd().
const SBConfig* SBOceanTideLd::Cfg [protected]
Definition at line 52 of file SbGeoTide.H'.
Referenced by SBOceanTideLd().
const double SBOceanTideLd::SPEED [static, protected]"Initial value:
{
  1.40519e-04, 1.45444e-04, 1.37880e-04, 1.45842e-04, 0.72921e-04,
  0.67598e-04, 0.72523e-04, 0.64959e-04, 0.53234e-05, 0.26392e-05, 0.03982e-05
}
Definition at line 53 of file SbGeoTide.H'.
Referenced by ARG_IERS().
double Vector3::vec[3] [protected, inherited]
Definition at line 53 of file SbVector3.H'.
Referenced by Vector3::at(), Vector3::clear(), Vector3::lambda(), Vector3::module(), operator()(), SBPolarTideLd::operator()(), Vector3::operator*=(), Vector3::operator+=(), Vector3::operator-=(), Vector3::operator/=(), Vector3::operator=(), Vector3::operator==(), Vector3::operator[](), Vector3::phi(), Vector3::report2Log(), and Vector3::Vector3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.