SBOLoadCarrier
NAME
SBOLoadCarrier -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBNamed'.
Public Member Functions
SBOLoadCarrier ()
SBOLoadCarrier (const SBOLoadCarrier &)
SBOLoadCarrier (SBSite &)
SBOLoadCarrier (const SBStation &)
virtual ~SBOLoadCarrier ()
virtual QString ClassName () const
virtual SBOLoadCarrier & operator= (const SBOLoadCarrier &)
virtual bool operator== (const SBOLoadCarrier &) const
virtual bool operator!= (const SBOLoadCarrier &) const
virtual bool IsSuccessfulLoad () const
virtual const SBStationID & id () const
virtual int CDP () const
virtual const SBOLoad & oLoad () const
virtual const QString & charID () const
double calcDistance (double, double) const
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
QString Name
Private Attributes
SBOLoad OLoad
double Longitude
double Latitude
QString CharID
int CDPNum
SBStationID Id
bool isSuccessfulLoad
Friends
SBTS_blq & operator<< (SBTS_blq &, const SBOLoadCarrier &)
SBTS_blq & operator>> (SBTS_blq &, SBOLoadCarrier &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Definition at line 1344 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBOLoadCarrier::SBOLoadCarrier ()
Definition at line 3830 of file SbGeoStations.C'.
References CDPNum, CharID, SBOLoad::clear(), Id, isSuccessfulLoad, Latitude, Longitude, OLoad, SBStation::Pt_Antenna, SBStationID::setDomeMajor(), SBStationID::setDomeMinor(), and SBStationID::setPtType().
SBOLoadCarrier::SBOLoadCarrier (const SBOLoadCarrier &OLC)
Definition at line 3868 of file SbGeoStations.C'.
References CDPNum, CharID, Id, isSuccessfulLoad, Latitude, Longitude, and OLoad.
SBOLoadCarrier::SBOLoadCarrier (SBSite &Site)
Definition at line 3843 of file SbGeoStations.C'.
References CDPNum, CharID, SBSite::domeMajor(), Id, isSuccessfulLoad, SBSite::latitude(), Latitude, SBSite::longitude(), Longitude, SBSite::oLoad(), OLoad, SBStation::Pt_Antenna, SBStationID::setDomeMajor(), SBStationID::setDomeMinor(), and SBStationID::setPtType().
SBOLoadCarrier::SBOLoadCarrier (const SBStation &Station)
Definition at line 3856 of file SbGeoStations.C'.
References SBStation::CDP(), CDPNum, SBStation::charID(), CharID, SBOLoad::clear(), SBStation::id(), Id, isSuccessfulLoad, SBStation::latitude(), Latitude, SBStation::longitude(), Longitude, SBStation::oLoad(), and OLoad.
virtual SBOLoadCarrier::~SBOLoadCarrier () [inline, virtual]
Definition at line 1360 of file SbGeoStations.H'.
Member Function Documentation
double SBOLoadCarrier::calcDistance (doublelon, doublelat) const
Definition at line 3904 of file SbGeoStations.C'.
References Latitude, and Longitude.
Referenced by SBStationImport::loadOLoad().
virtual int SBOLoadCarrier::CDP () const [inline, virtual]
Definition at line 1369 of file SbGeoStations.H'.
References CDPNum.
Referenced by SBStationImport::loadOLoad().
virtual const QString& SBOLoadCarrier::charID () const [inline, virtual]
Definition at line 1371 of file SbGeoStations.H'.
References CharID.
Referenced by SBStationImport::loadOLoad().
virtual QString SBOLoadCarrier::ClassName () const [inline, virtual]
Reimplemented from SBNamed'.
Definition at line 1361 of file SbGeoStations.H'.
virtual const SBStationID& SBOLoadCarrier::id () const [inline, virtual]
Definition at line 1368 of file SbGeoStations.H'.
References Id.
Referenced by SBStationImport::loadOLoad().
virtual bool SBOLoadCarrier::IsSuccessfulLoad () const [inline, virtual]
Definition at line 1367 of file SbGeoStations.H'.
References isSuccessfulLoad.
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual const SBOLoad& SBOLoadCarrier::oLoad () const [inline, virtual]
Definition at line 1370 of file SbGeoStations.H'.
References OLoad.
Referenced by SBStationImport::loadOLoad().
bool SBOLoadCarrier::operator!= (const SBOLoadCarrier &OLC) const [virtual]
Definition at line 3899 of file SbGeoStations.C'.
References operator==().
SBOLoadCarrier & SBOLoadCarrier::operator= (const SBOLoadCarrier &OLC) [virtual]
Definition at line 3880 of file SbGeoStations.C'.
References CDPNum, CharID, Id, isSuccessfulLoad, Latitude, Longitude, OLoad, and SBNamed::SBNamed().
bool SBOLoadCarrier::operator== (const SBOLoadCarrier &OLC) const [virtual]
Definition at line 3893 of file SbGeoStations.C'.
References CDPNum, CharID, Latitude, Longitude, and SBNamed::Name.
Referenced by operator!=().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
SBTS_blq& operator<< (SBTS_blq &s, const SBOLoadCarrier &OLC) [friend]
Definition at line 4117 of file SbGeoStations.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
SBTS_blq& operator>> (SBTS_blq &s, SBOLoadCarrier &OLC) [friend]
Definition at line 3920 of file SbGeoStations.C'.
Member Data Documentation
int SBOLoadCarrier::CDPNum [private]
Definition at line 1352 of file SbGeoStations.H'.
Referenced by CDP(), operator<<(), operator=(), operator==(), operator>>(), and SBOLoadCarrier().
QString SBOLoadCarrier::CharID [private]
Definition at line 1351 of file SbGeoStations.H'.
Referenced by charID(), operator=(), operator==(), operator>>(), and SBOLoadCarrier().
SBStationID SBOLoadCarrier::Id [private]
Definition at line 1353 of file SbGeoStations.H'.
Referenced by id(), operator<<(), operator=(), operator>>(), and SBOLoadCarrier().
bool SBOLoadCarrier::isSuccessfulLoad [private]
Definition at line 1354 of file SbGeoStations.H'.
Referenced by IsSuccessfulLoad(), operator=(), operator>>(), and SBOLoadCarrier().
double SBOLoadCarrier::Latitude [private]
Definition at line 1349 of file SbGeoStations.H'.
Referenced by calcDistance(), operator<<(), operator=(), operator==(), operator>>(), and SBOLoadCarrier().
double SBOLoadCarrier::Longitude [private]
Definition at line 1348 of file SbGeoStations.H'.
Referenced by calcDistance(), operator<<(), operator=(), operator==(), operator>>(), and SBOLoadCarrier().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
SBOLoad SBOLoadCarrier::OLoad [private]
Definition at line 1347 of file SbGeoStations.H'.
Referenced by oLoad(), operator<<(), operator=(), operator>>(), and SBOLoadCarrier().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.