SBOLoadEditor
NAME
SBOLoadEditor -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QWidget'.
Public Member Functions
SBOLoadEditor (SBOLoad *, bool, QWidget *=0, const char *=0)
~SBOLoadEditor ()
virtual QString ClassName () const
virtual bool collectData ()
Protected Slots
void createOLoad ()
void deleteOLoad ()
Private Attributes
bool isSite
bool isDisabled
bool isModified
SBOLoad * OLoad
QLineEdit * EAmplitude [3][11]
QLineEdit * EPhase [3][11]
QLineEdit * EInfo
QLineEdit * EComment1
QLineEdit * EComment2
QLabel * LStatus
Friends
class SBStationEditor
class SBSiteEditor
Detailed Description
Definition at line 574 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBOLoadEditor::SBOLoadEditor (SBOLoad *OLoad_, boolisSite_, QWidget *parent = 0, const char *name = 0)
Definition at line 3815 of file SbIStuffStation.C'.
References SBOLoad::amplitude(), SBOLoad::commentLine1(), SBOLoad::commentLine2(), createOLoad(), deleteOLoad(), EAmplitude, EComment1, EComment2, EInfo, EPhase, SBOLoad::info(), isDisabled, isModified, isSite, OLoad, and SBOLoad::phase().
SBOLoadEditor::~SBOLoadEditor ()
Definition at line 3946 of file SbIStuffStation.C'.
References isSite, and OLoad.
Member Function Documentation
virtual QString SBOLoadEditor::ClassName () const [inline, virtual]
Definition at line 580 of file SbIStuffStation.H'.
bool SBOLoadEditor::collectData () [virtual]
Definition at line 3989 of file SbIStuffStation.C'.
References SBOLoad::amplitude(), SBOLoad::commentLine1(), SBOLoad::commentLine2(), EAmplitude, EComment1, EComment2, EInfo, EPhase, SBOLoad::info(), isDisabled, isModified, OLoad, SBOLoad::phase(), SBOLoad::setAmplitude(), SBOLoad::setCommentLine1(), SBOLoad::setCommentLine2(), SBOLoad::setInfo(), and SBOLoad::setPhase().
Referenced by SBSiteEditor::acquireData(), and SBStationEditor::acquireData().
void SBOLoadEditor::createOLoad () [protected, slot]
Definition at line 3951 of file SbIStuffStation.C'.
References EAmplitude, EComment1, EComment2, EInfo, EPhase, isDisabled, isModified, OLoad, SBOLoad::P_Manual, and SBOLoad::setPickedUp().
Referenced by SBOLoadEditor().
void SBOLoadEditor::deleteOLoad () [protected, slot]
Definition at line 3970 of file SbIStuffStation.C'.
References EAmplitude, EComment1, EComment2, EInfo, EPhase, isDisabled, isModified, OLoad, SBOLoad::P_NA, and SBOLoad::setPickedUp().
Referenced by SBOLoadEditor().
Friends And Related Function Documentation
friend class SBSiteEditor [friend]
Definition at line 603 of file SbIStuffStation.H'.
friend class SBStationEditor [friend]
Definition at line 602 of file SbIStuffStation.H'.
Member Data Documentation
QLineEdit* SBOLoadEditor::EAmplitude[3][11] [private]
Definition at line 593 of file SbIStuffStation.H'.
Referenced by collectData(), createOLoad(), deleteOLoad(), and SBOLoadEditor().
QLineEdit* SBOLoadEditor::EComment1 [private]
Definition at line 597 of file SbIStuffStation.H'.
Referenced by collectData(), createOLoad(), deleteOLoad(), and SBOLoadEditor().
QLineEdit* SBOLoadEditor::EComment2 [private]
Definition at line 598 of file SbIStuffStation.H'.
Referenced by collectData(), createOLoad(), deleteOLoad(), and SBOLoadEditor().
QLineEdit* SBOLoadEditor::EInfo [private]
Definition at line 596 of file SbIStuffStation.H'.
Referenced by collectData(), createOLoad(), deleteOLoad(), and SBOLoadEditor().
QLineEdit* SBOLoadEditor::EPhase[3][11] [private]
Definition at line 594 of file SbIStuffStation.H'.
Referenced by collectData(), createOLoad(), deleteOLoad(), and SBOLoadEditor().
bool SBOLoadEditor::isDisabled [private]
Definition at line 590 of file SbIStuffStation.H'.
Referenced by SBStationEditor::acquireData(), collectData(), createOLoad(), deleteOLoad(), and SBOLoadEditor().
bool SBOLoadEditor::isModified [private]
Definition at line 591 of file SbIStuffStation.H'.
Referenced by collectData(), createOLoad(), deleteOLoad(), and SBOLoadEditor().
bool SBOLoadEditor::isSite [private]
Definition at line 589 of file SbIStuffStation.H'.
Referenced by SBOLoadEditor(), and ~SBOLoadEditor().
QLabel* SBOLoadEditor::LStatus [private]
Definition at line 600 of file SbIStuffStation.H'.
SBOLoad* SBOLoadEditor::OLoad [private]
Definition at line 592 of file SbIStuffStation.H'.
Referenced by SBStationEditor::acquireData(), collectData(), createOLoad(), deleteOLoad(), SBOLoadEditor(), and ~SBOLoadEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.