SBOLoad
NAME
SBOLoad -
SYNOPSIS
#include <SbGeoStations.H>
Public Types
enum PickUpBy { P_DomesNum = 0, P_CDPNum = 1, P_Domes = 2, P_Name = 3, P_Distance = 4, P_Manual = 5, P_NA = 6 }
Public Member Functions
SBOLoad ()
SBOLoad (const SBOLoad &)
virtual ~SBOLoad ()
virtual QString ClassName () const
virtual SBOLoad & operator= (const SBOLoad &)
virtual bool operator== (const SBOLoad &) const
virtual bool operator!= (const SBOLoad &) const
double amplitude (int i, int j) const
double phase (int i, int j) const
double dist () const
QString info () const
QString commentLine1 () const
QString commentLine2 () const
PickUpBy pickedUp () const
void setAmplitude (const double A_[3][11])
void setAmplitude (int c, int j, double a)
void setPhase (const double P_[11][3])
void setPhase (int c, int j, double p)
void setDist (double Dist_)
void setInfo (const char *Info_)
void setPickedUp (PickUpBy PickedUp_)
void setCommentLine1 (const char *CommentLine1_)
void setCommentLine2 (const char *CommentLine2_)
void clear ()
Private Attributes
double Amplitude [3][11]
double Phase [3][11]
double Dist
PickUpBy PickedUp
QString Info
QString CommentLine1
QString CommentLine2
Friends
class SBSite
class SBStation
QDataStream & operator<< (QDataStream &, const SBOLoad &)
QDataStream & operator>> (QDataStream &, SBOLoad &)
SBTS_blq & operator<< (SBTS_blq &, const SBOLoadCarrier &)
SBTS_blq & operator>> (SBTS_blq &, SBOLoadCarrier &)
Detailed Description
Definition at line 146 of file SbGeoStations.H'.
Member Enumeration Documentation
enum SBOLoad::PickUpBy
Enumerator:
P_DomesNum
P_CDPNum
P_Domes
P_Name
P_Distance
P_Manual
P_NA
Definition at line 151 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBOLoad::SBOLoad ()
Definition at line 93 of file SbGeoStations.C'.
References Amplitude, CommentLine1, CommentLine2, Dist, Info, P_NA, Phase, and PickedUp.
SBOLoad::SBOLoad (const SBOLoad &Ol)
Definition at line 107 of file SbGeoStations.C'.
References Amplitude, CommentLine1, CommentLine2, Dist, Info, Phase, and PickedUp.
virtual SBOLoad::~SBOLoad () [inline, virtual]
Definition at line 165 of file SbGeoStations.H'.
Member Function Documentation
double SBOLoad::amplitude (inti, intj) const [inline]
Definition at line 172 of file SbGeoStations.H'.
References Amplitude.
Referenced by SBOLoadEditor::collectData(), SBOceanTideLd::operator()(), and SBOLoadEditor::SBOLoadEditor().
virtual QString SBOLoad::ClassName () const [inline, virtual]
Definition at line 166 of file SbGeoStations.H'.
void SBOLoad::clear () [inline]
Definition at line 195 of file SbGeoStations.H'.
References Amplitude, and Phase.
Referenced by SBOLoadCarrier::SBOLoadCarrier().
QString SBOLoad::commentLine1 () const [inline]
Definition at line 176 of file SbGeoStations.H'.
References CommentLine1.
Referenced by SBOLoadEditor::collectData(), operator<<(), and SBOLoadEditor::SBOLoadEditor().
QString SBOLoad::commentLine2 () const [inline]
Definition at line 177 of file SbGeoStations.H'.
References CommentLine2.
Referenced by SBOLoadEditor::collectData(), operator<<(), and SBOLoadEditor::SBOLoadEditor().
double SBOLoad::dist () const [inline]
Definition at line 174 of file SbGeoStations.H'.
References Dist.
Referenced by SBStationImport::loadOLoad().
QString SBOLoad::info () const [inline]
Definition at line 175 of file SbGeoStations.H'.
References Info.
Referenced by SBOLoadEditor::collectData(), SBStationImport::loadOLoad(), and SBOLoadEditor::SBOLoadEditor().
bool SBOLoad::operator!= (const SBOLoad &Ol) const [virtual]
Definition at line 151 of file SbGeoStations.C'.
SBOLoad & SBOLoad::operator= (const SBOLoad &Ol) [virtual]
Definition at line 121 of file SbGeoStations.C'.
References Amplitude, CommentLine1, CommentLine2, Dist, Info, Phase, and PickedUp.
bool SBOLoad::operator== (const SBOLoad &Ol) const [virtual]
Definition at line 136 of file SbGeoStations.C'.
References Amplitude, CommentLine1, CommentLine2, Dist, Info, Phase, and PickedUp.
double SBOLoad::phase (inti, intj) const [inline]
Definition at line 173 of file SbGeoStations.H'.
References Phase.
Referenced by SBOLoadEditor::collectData(), SBOceanTideLd::operator()(), and SBOLoadEditor::SBOLoadEditor().
PickUpBy SBOLoad::pickedUp () const [inline]
Definition at line 178 of file SbGeoStations.H'.
References PickedUp.
Referenced by SBSiteListItem::key(), SBStationImport::loadOLoad(), and SBSiteListItem::text().
void SBOLoad::setAmplitude (const doubleA_[3][11]) [inline]
Definition at line 180 of file SbGeoStations.H'.
References Amplitude.
Referenced by SBOLoadEditor::collectData().
void SBOLoad::setAmplitude (intc, intj, doublea) [inline]
Definition at line 182 of file SbGeoStations.H'.
References Amplitude.
void SBOLoad::setCommentLine1 (const char *CommentLine1_) [inline]
Definition at line 191 of file SbGeoStations.H'.
References CommentLine1.
Referenced by SBOLoadEditor::collectData(), and operator>>().
void SBOLoad::setCommentLine2 (const char *CommentLine2_) [inline]
Definition at line 192 of file SbGeoStations.H'.
References CommentLine2.
Referenced by SBOLoadEditor::collectData(), and operator>>().
void SBOLoad::setDist (doubleDist_) [inline]
Definition at line 188 of file SbGeoStations.H'.
References Dist.
Referenced by SBStationImport::loadOLoad().
void SBOLoad::setInfo (const char *Info_) [inline]
Definition at line 189 of file SbGeoStations.H'.
References Info.
Referenced by SBOLoadEditor::collectData(), and SBStationImport::loadOLoad().
void SBOLoad::setPhase (const doubleP_[11][3]) [inline]
Definition at line 184 of file SbGeoStations.H'.
References Phase.
Referenced by SBOLoadEditor::collectData().
void SBOLoad::setPhase (intc, intj, doublep) [inline]
Definition at line 186 of file SbGeoStations.H'.
References Phase.
void SBOLoad::setPickedUp (PickUpByPickedUp_) [inline]
Definition at line 190 of file SbGeoStations.H'.
References PickedUp.
Referenced by SBOLoadEditor::createOLoad(), SBOLoadEditor::deleteOLoad(), and SBStationImport::loadOLoad().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBOLoad &Ol) [friend]
Definition at line 164 of file SbGeoStations.C'.
SBTS_blq& operator<< (SBTS_blq &s, const SBOLoadCarrier &OLC) [friend]
Definition at line 4117 of file SbGeoStations.C'.
QDataStream& operator>> (QDataStream &s, SBOLoad &Ol) [friend]
Definition at line 171 of file SbGeoStations.C'.
SBTS_blq& operator>> (SBTS_blq &s, SBOLoadCarrier &OLC) [friend]
Definition at line 3920 of file SbGeoStations.C'.
friend class SBSite [friend]
Definition at line 148 of file SbGeoStations.H'.
friend class SBStation [friend]
Definition at line 149 of file SbGeoStations.H'.
Member Data Documentation
double SBOLoad::Amplitude[3][11] [private]
Definition at line 154 of file SbGeoStations.H'.
Referenced by amplitude(), clear(), operator<<(), operator=(), operator==(), operator>>(), SBOLoad(), and setAmplitude().
QString SBOLoad::CommentLine1 [private]
Definition at line 159 of file SbGeoStations.H'.
Referenced by commentLine1(), operator<<(), operator=(), operator==(), operator>>(), SBOLoad(), and setCommentLine1().
QString SBOLoad::CommentLine2 [private]
Definition at line 160 of file SbGeoStations.H'.
Referenced by commentLine2(), operator<<(), operator=(), operator==(), operator>>(), SBOLoad(), and setCommentLine2().
double SBOLoad::Dist [private]
Definition at line 156 of file SbGeoStations.H'.
Referenced by dist(), operator<<(), operator=(), operator==(), operator>>(), SBOLoad(), and setDist().
QString SBOLoad::Info [private]
Definition at line 158 of file SbGeoStations.H'.
Referenced by info(), operator<<(), operator=(), operator==(), operator>>(), SBOLoad(), and setInfo().
double SBOLoad::Phase[3][11] [private]
Definition at line 155 of file SbGeoStations.H'.
Referenced by clear(), operator<<(), operator=(), operator==(), operator>>(), phase(), SBOLoad(), and setPhase().
PickUpBy SBOLoad::PickedUp [private]
Definition at line 157 of file SbGeoStations.H'.
Referenced by operator<<(), operator=(), operator==(), operator>>(), pickedUp(), SBOLoad(), and setPickedUp().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.