.TH "SBOTideEOPRay1994_2003::TableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBOTideEOPRay1994_2003::TableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBk\fP [6]"
.br
.ti -1c
.RI "double \fBA\fP"
.br
.ti -1c
.RI "double \fBB\fP"
.br
.ti -1c
.RI "double \fBC\fP"
.br
.ti -1c
.RI "double \fBD\fP"
.br
.ti -1c
.RI "double \fBE\fP"
.br
.ti -1c
.RI "double \fBF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1062 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBOTideEOPRay1994_2003::TableEntry::A\fP"
.PP
Definition at line 1065 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBOTideEOPRay1994_2003::calc()\&.
.SS "double \fBSBOTideEOPRay1994_2003::TableEntry::B\fP"
.PP
Definition at line 1065 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBOTideEOPRay1994_2003::calc()\&.
.SS "double \fBSBOTideEOPRay1994_2003::TableEntry::C\fP"
.PP
Definition at line 1065 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBOTideEOPRay1994_2003::calc()\&.
.SS "double \fBSBOTideEOPRay1994_2003::TableEntry::D\fP"
.PP
Definition at line 1065 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBOTideEOPRay1994_2003::calc()\&.
.SS "double \fBSBOTideEOPRay1994_2003::TableEntry::E\fP"
.PP
Definition at line 1065 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBOTideEOPRay1994_2003::calc()\&.
.SS "double \fBSBOTideEOPRay1994_2003::TableEntry::F\fP"
.PP
Definition at line 1065 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBOTideEOPRay1994_2003::calc()\&.
.SS "short \fBSBOTideEOPRay1994_2003::TableEntry::k\fP[6]"
.PP
Definition at line 1064 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBOTideEOPRay1994_2003::calc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
