.TH "SBParEditor" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBParEditor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIProject\&.H>\fP
.PP
Inherits \fBQDialog\fP'\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBvalueModified\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBParEditor\fP (\fBSBParameterCfg\fP *, const QString &, int, \fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "virtual \fB~SBParEditor\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBmakeDefault\fP ()"
.br
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.ti -1c
.RI "void \fBreject\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBacquireData\fP ()"
.br
.ti -1c
.RI "virtual void \fBbrowseData\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBParameterCfg\fP * \fBP\fP"
.br
.ti -1c
.RI "bool \fBisModified\fP"
.br
.ti -1c
.RI "bool \fBisConstrained\fP"
.br
.ti -1c
.RI "int \fBIdx\fP"
.br
.ti -1c
.RI "QString \fBParName\fP"
.br
.ti -1c
.RI "QLineEdit * \fBConvApriori\fP"
.br
.ti -1c
.RI "QLineEdit * \fBStocApriori\fP"
.br
.ti -1c
.RI "QLineEdit * \fBRuledWNoise\fP"
.br
.ti -1c
.RI "QLineEdit * \fBBreaksNoise\fP"
.br
.ti -1c
.RI "QLineEdit * \fBTau\fP"
.br
.ti -1c
.RI "QCheckBox * \fBPropagate\fP"
.br
.ti -1c
.RI "QRadioButton * \fBType\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 416 of file SbIProject\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBParEditor::SBParEditor (\fBSBParameterCfg\fP *P_, const QString &ParName_, intIdx_, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 2533 of file SbIProject\&.C'\&.
.PP
References accept(), SBParameterCfg::breakNoise(), BreaksNoise, SBParameterCfg::convAPriori(), ConvApriori, Idx, isModified, SBParameterCfg::isPropagated(), makeDefault(), SBParametersDesc::n(), P, ParName, Propagate, reject(), RuledWNoise, SBParameterCfg::scaleName(), SBParameterCfg::stocAPriori(), StocApriori, SBParameterCfg::stochasticType(), SBParameterCfg::tau(), Tau, Type, and SBParameterCfg::whiteNoise()\&.
.SS "SBParEditor::~SBParEditor ()\fC [virtual]\fP"
.PP
Definition at line 2663 of file SbIProject\&.C'\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBParEditor::accept ()\fC [protected, slot]\fP"
.PP
Definition at line 2668 of file SbIProject\&.C'\&.
.PP
References acquireData(), isModified, and valueModified()\&.
.PP
Referenced by SBParEditor()\&.
.SS "void SBParEditor::acquireData ()\fC [private, virtual]\fP"
.PP
Definition at line 2698 of file SbIProject\&.C'\&.
.PP
References SBParameterCfg::breakNoise(), BreaksNoise, SBParameterCfg::convAPriori(), ConvApriori, isModified, SBParameterCfg::isPropagated(), P, Propagate, RuledWNoise, SBParameterCfg::setBreakNoise(), SBParameterCfg::setConvAPriori(), SBParameterCfg::setPropagated(), SBParameterCfg::setStocAPriori(), SBParameterCfg::setStochasticType(), SBParameterCfg::setTau(), SBParameterCfg::setWhiteNoise(), SBParameterCfg::ST_MARKOVPROCESS, SBParameterCfg::ST_NONE, SBParameterCfg::ST_RANDWALK, SBParameterCfg::ST_UNKN, SBParameterCfg::ST_WHITENOISE, SBParameterCfg::stocAPriori(), StocApriori, SBParameterCfg::stochasticType(), SBParameterCfg::tau(), Tau, Type, and SBParameterCfg::whiteNoise()\&.
.PP
Referenced by accept()\&.
.SS "void SBParEditor::browseData ()\fC [private, virtual]\fP"
.PP
Definition at line 2685 of file SbIProject\&.C'\&.
.PP
References SBParameterCfg::breakNoise(), BreaksNoise, SBParameterCfg::convAPriori(), ConvApriori, SBParameterCfg::isPropagated(), P, Propagate, RuledWNoise, SBParameterCfg::stocAPriori(), StocApriori, SBParameterCfg::stochasticType(), SBParameterCfg::tau(), Tau, Type, and SBParameterCfg::whiteNoise()\&.
.PP
Referenced by makeDefault()\&.
.SS "virtual QString SBParEditor::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 423 of file SbIProject\&.H'\&.
.PP
Referenced by makeDefault()\&.
.SS "void SBParEditor::makeDefault ()\fC [protected, slot]\fP"
.PP
Definition at line 2676 of file SbIProject\&.C'\&.
.PP
References browseData(), ClassName(), SBLog::DBG, DefaultConfig, Idx, SBLog::INTERFACE, isModified, Log, SBConfig::p(), P, SBParametersDesc::par(), and SBLog::write()\&.
.PP
Referenced by SBParEditor()\&.
.SS "void SBParEditor::reject ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 432 of file SbIProject\&.H'\&.
.PP
References valueModified()\&.
.PP
Referenced by SBParEditor()\&.
.SS "void SBParEditor::valueModified (boolt0)\fC [signal]\fP"
.PP
Definition at line 805 of file SbIProject\&.moc\&.C'\&.
.PP
Referenced by accept(), and reject()\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* \fBSBParEditor::BreaksNoise\fP\fC [private]\fP"
.PP
Definition at line 444 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), and SBParEditor()\&.
.SS "QLineEdit* \fBSBParEditor::ConvApriori\fP\fC [private]\fP"
.PP
Definition at line 441 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), and SBParEditor()\&.
.SS "int \fBSBParEditor::Idx\fP\fC [private]\fP"
.PP
Definition at line 438 of file SbIProject\&.H'\&.
.PP
Referenced by makeDefault(), and SBParEditor()\&.
.SS "bool \fBSBParEditor::isConstrained\fP\fC [private]\fP"
.PP
Definition at line 437 of file SbIProject\&.H'\&.
.SS "bool \fBSBParEditor::isModified\fP\fC [private]\fP"
.PP
Definition at line 436 of file SbIProject\&.H'\&.
.PP
Referenced by accept(), acquireData(), makeDefault(), and SBParEditor()\&.
.SS "\fBSBParameterCfg\fP* \fBSBParEditor::P\fP\fC [private]\fP"
.PP
Definition at line 432 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), makeDefault(), and SBParEditor()\&.
.SS "QString \fBSBParEditor::ParName\fP\fC [private]\fP"
.PP
Definition at line 439 of file SbIProject\&.H'\&.
.PP
Referenced by SBParEditor()\&.
.SS "QCheckBox* \fBSBParEditor::Propagate\fP\fC [private]\fP"
.PP
Definition at line 446 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), and SBParEditor()\&.
.SS "QLineEdit* \fBSBParEditor::RuledWNoise\fP\fC [private]\fP"
.PP
Definition at line 443 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), and SBParEditor()\&.
.SS "QLineEdit* \fBSBParEditor::StocApriori\fP\fC [private]\fP"
.PP
Definition at line 442 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), and SBParEditor()\&.
.SS "QLineEdit* \fBSBParEditor::Tau\fP\fC [private]\fP"
.PP
Definition at line 445 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), and SBParEditor()\&.
.SS "QRadioButton* \fBSBParEditor::Type\fP[5]\fC [private]\fP"
.PP
Definition at line 447 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), and SBParEditor()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
