SBParametersDesc
NAME
SBParametersDesc -
SYNOPSIS
#include <SbGeoParameter.H>
Public Member Functions
SBParametersDesc ()
SBParametersDesc (const SBParametersDesc &D)
virtual ~SBParametersDesc ()
SBParametersDesc & operator= (const SBParametersDesc &)
virtual QString ClassName () const
virtual const SBParameterCfg & clock0 () const
virtual void setClock0 (const SBParameterCfg &P)
virtual void setClock0Type (SBParameterCfg::PType T_)
virtual const SBParameterCfg & clock1 () const
virtual void setClock1 (const SBParameterCfg &P)
virtual void setClock1Type (SBParameterCfg::PType T_)
virtual const SBParameterCfg & clock2 () const
virtual void setClock2 (const SBParameterCfg &P)
virtual void setClock2Type (SBParameterCfg::PType T_)
virtual const SBParameterCfg & clock3 () const
virtual void setClock3 (const SBParameterCfg &P)
virtual void setClock3Type (SBParameterCfg::PType T_)
virtual const SBParameterCfg & srcCoo () const
virtual void setSrcCoo (const SBParameterCfg &P)
virtual const SBParameterCfg & staCoo () const
virtual void setStaCoo (const SBParameterCfg &P)
virtual const SBParameterCfg & staVel () const
virtual void setStaVel (const SBParameterCfg &P)
virtual const SBParameterCfg & zenith () const
virtual void setZenith (const SBParameterCfg &P)
virtual void setZenithType (SBParameterCfg::PType T_)
virtual const SBParameterCfg & atmGrad () const
virtual void setAtmGrad (const SBParameterCfg &P)
virtual const SBParameterCfg & axisOffset () const
virtual void setAxisOffset (const SBParameterCfg &P)
virtual const SBParameterCfg & polusXY () const
virtual void setPolusXY (const SBParameterCfg &P)
virtual const SBParameterCfg & polusUT () const
virtual void setPolusUT (const SBParameterCfg &P)
virtual const SBParameterCfg & polusNut () const
virtual void setPolusNut (const SBParameterCfg &P)
virtual const SBParameterCfg & test () const
virtual void setTest (const SBParameterCfg &P)
virtual const SBParameterCfg & cable () const
virtual void setCable (const SBParameterCfg &P)
virtual void setCableType (SBParameterCfg::PType T_)
virtual const SBParameterCfg & love_h2 () const
virtual void setLove_h2 (const SBParameterCfg &P)
virtual void setLove_h2Type (SBParameterCfg::PType T_)
virtual const SBParameterCfg & love_l2 () const
virtual void setLove_l2 (const SBParameterCfg &P)
virtual void setLove_l2Type (SBParameterCfg::PType T_)
virtual const SBParameterCfg & tideLag () const
virtual void setTideLag (const SBParameterCfg &P)
virtual void setTideLagType (SBParameterCfg::PType T_)
virtual const SBParameterCfg & par (int i) const
virtual void setPar (int i, const SBParameterCfg &P)
virtual void setType (int i, SBParameterCfg::PType T_)
Static Public Member Functions
static int num ()
static int n ()
Private Attributes
SBParameterCfg Pars [NUMBER_OF_PARAMETERS]
The array of the parameters'.
Static Private Attributes
static const int Num
The number of elemenths in the array'.
Friends
QDataStream & operator<< (QDataStream &, const SBParametersDesc &)
QDataStream & operator>> (QDataStream &, SBParametersDesc &)
Detailed Description
Class ParametersDesc'. Just an array (and some other structures) of SBParameterCfgs, describes estimated parameters
Definition at line 131 of file SbGeoParameter.H'.
Constructor & Destructor Documentation
SBParametersDesc::SBParametersDesc ()"A constructor'.
Definition at line 140 of file SbGeoParameter.C'.
References DAY2SEC, Pars, SBParameterCfg::PT_LOC, SBParameterCfg::PT_NONE, and RAD2SEC.
SBParametersDesc::SBParametersDesc (const SBParametersDesc &D) [inline]"A constructor'. Creates a copy of object'.
Parameters:
D_ the Parameters' descriptor'.
Definition at line 146 of file SbGeoParameter.H'.
virtual SBParametersDesc::~SBParametersDesc () [inline, virtual]"A destructor'.
Definition at line 148 of file SbGeoParameter.H'.
Member Function Documentation
virtual const SBParameterCfg& SBParametersDesc::atmGrad () const [inline, virtual]"Returns atmospheric gradient parameter'.
Definition at line 194 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calc(), SBRunManager::fillParameterList(), and sinex_tro_TropDescriptionBlock().
virtual const SBParameterCfg& SBParametersDesc::axisOffset () const [inline, virtual]"Returns Axis offset'.
Definition at line 198 of file SbGeoParameter.H'.
References Pars.
Referenced by SBRunManager::fillParameterList().
virtual const SBParameterCfg& SBParametersDesc::cable () const [inline, virtual]"Returns cable correction'.
Definition at line 219 of file SbGeoParameter.H'.
References Pars.
Referenced by SBRunManager::fillParameterList(), and SBVLBIPreProcess::preProcess().
virtual QString SBParametersDesc::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Definition at line 151 of file SbGeoParameter.H'.
virtual const SBParameterCfg& SBParametersDesc::clock0 () const [inline, virtual]"Returns Clock at station (zero order)'.
Definition at line 156 of file SbGeoParameter.H'.
References Pars.
Referenced by SBRunManager::constrainClocks(), SBRunManager::fillParameterList(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), and SBVLBIPreProcess::wEstPars().
virtual const SBParameterCfg& SBParametersDesc::clock1 () const [inline, virtual]"Returns Clock at station (first order)'.
Definition at line 161 of file SbGeoParameter.H'.
References Pars.
Referenced by SBRunManager::constrainClocks(), and SBRunManager::fillParameterList().
virtual const SBParameterCfg& SBParametersDesc::clock2 () const [inline, virtual]"Returns Clock at station (second order)'.
Definition at line 166 of file SbGeoParameter.H'.
References Pars.
Referenced by SBRunManager::constrainClocks(), and SBRunManager::fillParameterList().
virtual const SBParameterCfg& SBParametersDesc::clock3 () const [inline, virtual]"Returns Clock at station (third order)'.
Definition at line 171 of file SbGeoParameter.H'.
References Pars.
virtual const SBParameterCfg& SBParametersDesc::love_h2 () const [inline, virtual]"Returns love number h2'.
Definition at line 225 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
virtual const SBParameterCfg& SBParametersDesc::love_l2 () const [inline, virtual]"Returns love number l2'.
Definition at line 230 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
static int SBParametersDesc::n () [inline, static]"Returns currently used number of the parameters'.
Definition at line 250 of file SbGeoParameter.H'.
Referenced by SBParametersEditor::acquireData(), SBParametersEditor::browseData(), and SBParEditor::SBParEditor().
static int SBParametersDesc::num () [inline, static]"Returns total number of the parameters'.
Definition at line 248 of file SbGeoParameter.H'.
References Num.
Referenced by operator=(), SBParameterCfg::operator>>(), and SBConfig::setAllPars2Type().
SBParametersDesc & SBParametersDesc::operator= (const SBParametersDesc &D)
Definition at line 207 of file SbGeoParameter.C'.
References num(), par(), and setPar().
virtual const SBParameterCfg& SBParametersDesc::par (inti) const [inline, virtual]"Returns i-th parameter'.
Definition at line 244 of file SbGeoParameter.H'.
References Num, and Pars.
Referenced by SBParametersEditor::acquireData(), SBParametersEditor::browseData(), SBParametersEditor::editParameter(), SBParEditor::makeDefault(), operator=(), SBStationInfo::SBStationInfo(), SBParametersEditor::wEOPParameters(), SBParametersEditor::wOtherParameters(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), and SBParametersEditor::wTestParameters().
virtual const SBParameterCfg& SBParametersDesc::polusNut () const [inline, virtual]"Returns Nutation in obliquity and longitude'.
Definition at line 210 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::process_m1().
virtual const SBParameterCfg& SBParametersDesc::polusUT () const [inline, virtual]"Returns Polus d(UT1-UTC)'.
Definition at line 206 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::process_m1().
virtual const SBParameterCfg& SBParametersDesc::polusXY () const [inline, virtual]"Returns Polus coordinates'.
Definition at line 202 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), and SBRunManager::process_m1().
virtual void SBParametersDesc::setAtmGrad (const SBParameterCfg &P) [inline, virtual]"Sets atmospheric parameter'.
Definition at line 196 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setAxisOffset (const SBParameterCfg &P) [inline, virtual]"Sets Axis offset'.
Definition at line 200 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setCable (const SBParameterCfg &P) [inline, virtual]"Sets cable correction'.
Definition at line 221 of file SbGeoParameter.H'.
References Pars.
Referenced by SBVLBIPreProcess::preProcess().
virtual void SBParametersDesc::setCableType (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 222 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
Referenced by SBVLBIPreProcess::preProcess().
virtual void SBParametersDesc::setClock0 (const SBParameterCfg &P) [inline, virtual]"Sets Clock at station (zero order)'.
Definition at line 158 of file SbGeoParameter.H'.
References Pars.
Referenced by SBVLBIPreProcess::preProcess().
virtual void SBParametersDesc::setClock0Type (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 159 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
Referenced by SBVLBIPreProcess::preProcess().
virtual void SBParametersDesc::setClock1 (const SBParameterCfg &P) [inline, virtual]"Sets Clock at station (first order)'.
Definition at line 163 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setClock1Type (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 164 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
Referenced by SBVLBIPreProcess::preProcess().
virtual void SBParametersDesc::setClock2 (const SBParameterCfg &P) [inline, virtual]"Sets Clock at station (second order)'.
Definition at line 168 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setClock2Type (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 169 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
Referenced by SBVLBIPreProcess::preProcess().
virtual void SBParametersDesc::setClock3 (const SBParameterCfg &P) [inline, virtual]"Sets Clock at station (third order)'.
Definition at line 173 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setClock3Type (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 174 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
virtual void SBParametersDesc::setLove_h2 (const SBParameterCfg &P) [inline, virtual]"Sets love number h2'.
Definition at line 227 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setLove_h2Type (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 228 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
virtual void SBParametersDesc::setLove_l2 (const SBParameterCfg &P) [inline, virtual]"Sets love number l2'.
Definition at line 232 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setLove_l2Type (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 233 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
virtual void SBParametersDesc::setPar (inti, const SBParameterCfg &P) [inline, virtual]"Sets i-th parameter'.
Definition at line 246 of file SbGeoParameter.H'.
References Num, and Pars.
Referenced by operator=(), and SBParameterCfg::operator>>().
virtual void SBParametersDesc::setPolusNut (const SBParameterCfg &P) [inline, virtual]"Sets Nutation in obliquity and longitude'.
Definition at line 212 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setPolusUT (const SBParameterCfg &P) [inline, virtual]"Sets Polus d(UT1-UTC)'.
Definition at line 208 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setPolusXY (const SBParameterCfg &P) [inline, virtual]"Sets Polus coordinates'.
Definition at line 204 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setSrcCoo (const SBParameterCfg &P) [inline, virtual]"Sets Coordinates of a radio source'.
Definition at line 178 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setStaCoo (const SBParameterCfg &P) [inline, virtual]"Sets Coordinates of a station'.
Definition at line 182 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setStaVel (const SBParameterCfg &P) [inline, virtual]"Sets Velocities of a station'.
Definition at line 186 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setTest (const SBParameterCfg &P) [inline, virtual]"Sets test parameter'.
Definition at line 216 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setTideLag (const SBParameterCfg &P) [inline, virtual]"Sets Tide Lag'.
Definition at line 237 of file SbGeoParameter.H'.
References Pars.
virtual void SBParametersDesc::setTideLagType (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 238 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
virtual void SBParametersDesc::setType (inti, SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 254 of file SbGeoParameter.H'.
References Num, Pars, and SBParameterCfg::setType().
Referenced by SBParametersEditor::acquireData(), and SBConfig::setAllPars2Type().
virtual void SBParametersDesc::setZenith (const SBParameterCfg &P) [inline, virtual]"Sets Zenith delay'.
Definition at line 191 of file SbGeoParameter.H'.
References Pars.
Referenced by SBVLBIPreProcess::preProcess().
virtual void SBParametersDesc::setZenithType (SBParameterCfg::PTypeT_) [inline, virtual]
Definition at line 192 of file SbGeoParameter.H'.
References Pars, and SBParameterCfg::setType().
Referenced by SBVLBIPreProcess::preProcess().
virtual const SBParameterCfg& SBParametersDesc::srcCoo () const [inline, virtual]"Returns Coordinates of a radio source'.
Definition at line 176 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::fillParameterList(), and SBRunManager::process_m1().
virtual const SBParameterCfg& SBParametersDesc::staCoo () const [inline, virtual]"Returns Coordinates of a station'.
Definition at line 180 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::fillParameterList(), and SBRunManager::process_m1().
virtual const SBParameterCfg& SBParametersDesc::staVel () const [inline, virtual]"Returns Velocities of a station'.
Definition at line 184 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters(), SBRunManager::fillParameterList(), and SBRunManager::process_m1().
virtual const SBParameterCfg& SBParametersDesc::test () const [inline, virtual]"Returns test parameter'.
Definition at line 214 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
virtual const SBParameterCfg& SBParametersDesc::tideLag () const [inline, virtual]"Returns love number h2'.
Definition at line 235 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::fillParameterList().
virtual const SBParameterCfg& SBParametersDesc::zenith () const [inline, virtual]"Returns Zenith delay'.
Definition at line 189 of file SbGeoParameter.H'.
References Pars.
Referenced by SBDelay::calc(), SBRunManager::fillParameterList(), SBVLBIPreProcess::preProcess(), sinex_tro_TropDescriptionBlock(), and SBVLBIPreProcess::wEstPars().
Friends And Related Function Documentation
QDataStream & operator<< (QDataStream &s, const SBParametersDesc &D) [friend]"Output to the data stream'.
Definition at line 224 of file SbGeoParameter.C'.
QDataStream& operator>> (QDataStream &, SBParametersDesc &) [friend]
Member Data Documentation
const int SBParametersDesc::Num [static, private]
The number of elemenths in the array'.
Definition at line 135 of file SbGeoParameter.H'.
Referenced by num(), par(), setPar(), and setType().
SBParameterCfg SBParametersDesc::Pars[NUMBER_OF_PARAMETERS] [private]
The array of the parameters'.
Definition at line 136 of file SbGeoParameter.H'.
Referenced by atmGrad(), axisOffset(), cable(), clock0(), clock1(), clock2(), clock3(), love_h2(), love_l2(), par(), polusNut(), polusUT(), polusXY(), SBParametersDesc(), setAtmGrad(), setAxisOffset(), setCable(), setCableType(), setClock0(), setClock0Type(), setClock1(), setClock1Type(), setClock2(), setClock2Type(), setClock3(), setClock3Type(), setLove_h2(), setLove_h2Type(), setLove_l2(), setLove_l2Type(), setPar(), setPolusNut(), setPolusUT(), setPolusXY(), setSrcCoo(), setStaCoo(), setStaVel(), setTest(), setTideLag(), setTideLagType(), setType(), setZenith(), setZenithType(), srcCoo(), staCoo(), staVel(), test(), tideLag(), and zenith().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.