SBParameterLI
NAME
SBParameterLI -
SYNOPSIS
#include <SbISolution.H>
Inherits QListViewItem'.
Public Member Functions
SBParameterLI (QListView *parent, SBParameter *P_)
SBParameter * parameter ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBParameter * P
Detailed Description
Definition at line 43 of file SbISolution.H'.
Constructor & Destructor Documentation
SBParameterLI::SBParameterLI (QListView *parent, SBParameter *P_) [inline]
Definition at line 49 of file SbISolution.H'.
References P.
Member Function Documentation
virtual QString SBParameterLI::ClassName () const [inline, virtual]
Definition at line 51 of file SbISolution.H'.
QString SBParameterLI::key (intcol, bool) const [virtual]
Definition at line 86 of file SbISolution.C'.
References SBParameter::e(), SBNamed::name(), SBDerivation::num(), P, SBParameter::scale(), SBDerivation::tEpoch(), SBDerivation::tFinis(), TmpString, SBDerivation::tStart(), and SBParameter::v().
SBParameter* SBParameterLI::parameter () [inline]
Definition at line 50 of file SbISolution.H'.
References P.
QString SBParameterLI::text (intcol) const [virtual]
Definition at line 61 of file SbISolution.C'.
References SBParameter::e(), SBMJD::F_YYYYMMDDHHMMSSSS, SBNamed::name(), SBDerivation::num(), P, SBParameter::scale(), SBDerivation::tEpoch(), SBDerivation::tFinis(), TmpString, SBMJD::toString(), SBDerivation::tStart(), and SBParameter::v().
Member Data Documentation
SBParameter* SBParameterLI::P [private]
Definition at line 46 of file SbISolution.H'.
Referenced by key(), parameter(), SBParameterLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.