SBParametersEditor
NAME
SBParametersEditor -
SYNOPSIS
#include <SbIProject.H>
Inherits SBTabDialog'.
Public Member Functions
SBParametersEditor (SBParametersDesc *=NULL, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBParametersEditor ()
virtual QString ClassName () const
Protected Slots
virtual void makeDefault ()
virtual void makeApply ()
void ParameterModified (bool)
void editParameter (int)
void editPar__0 ()
void editPar__1 ()
void editPar__2 ()
void editPar__3 ()
void editPar__4 ()
void editPar__5 ()
void editPar__6 ()
void editPar__7 ()
void editPar__8 ()
void editPar__9 ()
void editPar_10 ()
void editPar_11 ()
void editPar_12 ()
void editPar_13 ()
void editPar_14 ()
void editPar_15 ()
void editPar_16 ()
void editPar_17 ()
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Private Member Functions
QWidget * wStationParameters ()
QWidget * wSourceParameters ()
QWidget * wEOPParameters ()
QWidget * wOtherParameters ()
QWidget * wTestParameters ()
virtual void acquireData ()
virtual void browseData ()
Private Attributes
SBParametersDesc * P
SBProject * Project
bool isModified
bool isGlobal
int numOpenedWindows
QRadioButton * RB [NUMBER_OF_PARAMETERS][5]
Detailed Description
Definition at line 336 of file SbIProject.H'.
Constructor & Destructor Documentation
SBParametersEditor::SBParametersEditor (SBParametersDesc *P_ = NULL, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1970 of file SbIProject.C'.
References isGlobal, isModified, SBSetUp::loadProject(), makeApply(), makeDefault(), SBNamed::name(), numOpenedWindows, P, SBProject::p(), Project, SetUp, wEOPParameters(), wOtherParameters(), wSourceParameters(), wStationParameters(), and wTestParameters().
SBParametersEditor::~SBParametersEditor () [virtual]
Definition at line 2004 of file SbIProject.C'.
References Config, isGlobal, isModified, P, Project, SBSetUp::saveProject(), SBConfig::setP(), SBProject::setP(), and SetUp.
Member Function Documentation
void SBParametersEditor::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 2041 of file SbIProject.C'.
References isModified, SBParametersDesc::n(), P, SBParametersDesc::par(), SBParameterCfg::PT_ARC, SBParameterCfg::PT_GLB, SBParameterCfg::PT_LOC, SBParameterCfg::PT_NONE, SBParameterCfg::PT_STH, RB, SBParameterCfg::setType(), SBParametersDesc::setType(), and SBParameterCfg::type().
Referenced by makeApply().
void SBParametersEditor::browseData () [private, virtual]
Definition at line 2035 of file SbIProject.C'.
References SBParametersDesc::n(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type().
Referenced by makeDefault().
virtual QString SBParametersEditor::ClassName () const [inline, virtual]
Definition at line 342 of file SbIProject.H'.
Referenced by makeApply(), and makeDefault().
virtual void SBParametersEditor::closeEvent (QCloseEvent *e) [inline, protected, virtual]
Reimplemented from SBTabDialog'.
Definition at line 405 of file SbIProject.H'.
References numOpenedWindows.
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
void SBParametersEditor::editPar_10 () [inline, protected, slot]
Definition at line 363 of file SbIProject.H'.
References editParameter().
Referenced by wEOPParameters().
void SBParametersEditor::editPar_11 () [inline, protected, slot]
Definition at line 364 of file SbIProject.H'.
References editParameter().
Referenced by wEOPParameters().
void SBParametersEditor::editPar_12 () [inline, protected, slot]
Definition at line 365 of file SbIProject.H'.
References editParameter().
Referenced by wEOPParameters().
void SBParametersEditor::editPar_13 () [inline, protected, slot]
Definition at line 366 of file SbIProject.H'.
References editParameter().
Referenced by wTestParameters().
void SBParametersEditor::editPar_14 () [inline, protected, slot]
Definition at line 367 of file SbIProject.H'.
References editParameter().
Referenced by wOtherParameters().
void SBParametersEditor::editPar_15 () [inline, protected, slot]
Definition at line 368 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar_16 () [inline, protected, slot]
Definition at line 369 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar_17 () [inline, protected, slot]
Definition at line 370 of file SbIProject.H'.
Referenced by wStationParameters().
void SBParametersEditor::editPar__0 () [inline, protected, slot]
Definition at line 353 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__1 () [inline, protected, slot]
Definition at line 354 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__2 () [inline, protected, slot]
Definition at line 355 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__3 () [inline, protected, slot]
Definition at line 356 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__4 () [inline, protected, slot]
Definition at line 357 of file SbIProject.H'.
References editParameter().
Referenced by wSourceParameters().
void SBParametersEditor::editPar__5 () [inline, protected, slot]
Definition at line 358 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__6 () [inline, protected, slot]
Definition at line 359 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__7 () [inline, protected, slot]
Definition at line 360 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__8 () [inline, protected, slot]
Definition at line 361 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editPar__9 () [inline, protected, slot]
Definition at line 362 of file SbIProject.H'.
References editParameter().
Referenced by wStationParameters().
void SBParametersEditor::editParameter (intN_) [protected, slot]
Definition at line 2516 of file SbIProject.C'.
References SBNamed::name(), numOpenedWindows, P, SBParametersDesc::par(), and ParameterModified().
Referenced by editPar_10(), editPar_11(), editPar_12(), editPar_13(), editPar_14(), editPar_15(), editPar_16(), editPar__0(), editPar__1(), editPar__2(), editPar__3(), editPar__4(), editPar__5(), editPar__6(), editPar__7(), editPar__8(), and editPar__9().
void SBParametersEditor::makeApply () [protected, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 2019 of file SbIProject.C'.
References acquireData(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by SBParametersEditor().
void SBParametersEditor::makeDefault () [protected, virtual, slot]
Definition at line 2026 of file SbIProject.C'.
References browseData(), ClassName(), SBLog::DBG, DefaultConfig, SBLog::INTERFACE, isModified, Log, SBConfig::p(), P, and SBLog::write().
Referenced by SBParametersEditor().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBParametersEditor::ParameterModified (boolModified) [protected, slot]
Definition at line 2507 of file SbIProject.C'.
References isModified, and numOpenedWindows.
Referenced by editParameter().
QWidget * SBParametersEditor::wEOPParameters () [private]
Definition at line 2244 of file SbIProject.C'.
References editPar_10(), editPar_11(), editPar_12(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type().
Referenced by SBParametersEditor().
QWidget * SBParametersEditor::wOtherParameters () [private]
Definition at line 2333 of file SbIProject.C'.
References editPar_14(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type().
Referenced by SBParametersEditor().
QWidget * SBParametersEditor::wSourceParameters () [private]
Definition at line 2157 of file SbIProject.C'.
References editPar__4(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type().
Referenced by SBParametersEditor().
QWidget * SBParametersEditor::wStationParameters () [private]
Definition at line 2059 of file SbIProject.C'.
References editPar_15(), editPar_16(), editPar_17(), editPar__0(), editPar__1(), editPar__2(), editPar__3(), editPar__5(), editPar__6(), editPar__7(), editPar__8(), editPar__9(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type().
Referenced by SBParametersEditor().
QWidget * SBParametersEditor::wTestParameters () [private]
Definition at line 2420 of file SbIProject.C'.
References editPar_13(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type().
Referenced by SBParametersEditor().
Member Data Documentation
bool SBParametersEditor::isGlobal [private]
Definition at line 377 of file SbIProject.H'.
Referenced by SBParametersEditor(), and ~SBParametersEditor().
bool SBParametersEditor::isModified [private]
Definition at line 376 of file SbIProject.H'.
Referenced by acquireData(), makeDefault(), ParameterModified(), SBParametersEditor(), and ~SBParametersEditor().
int SBParametersEditor::numOpenedWindows [private]
Definition at line 378 of file SbIProject.H'.
Referenced by closeEvent(), editParameter(), ParameterModified(), and SBParametersEditor().
SBParametersDesc* SBParametersEditor::P [private]
Definition at line 370 of file SbIProject.H'.
Referenced by acquireData(), browseData(), editParameter(), makeDefault(), SBParametersEditor(), wEOPParameters(), wOtherParameters(), wSourceParameters(), wStationParameters(), wTestParameters(), and ~SBParametersEditor().
SBProject* SBParametersEditor::Project [private]
Definition at line 375 of file SbIProject.H'.
Referenced by SBParametersEditor(), and ~SBParametersEditor().
QRadioButton* SBParametersEditor::RB[NUMBER_OF_PARAMETERS][5] [private]
Definition at line 380 of file SbIProject.H'.
Referenced by acquireData(), browseData(), wEOPParameters(), wOtherParameters(), wSourceParameters(), wStationParameters(), and wTestParameters().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.