.TH "SBParameterLI" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBParameterLI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbISolution\&.H>\fP
.PP
Inherits \fBQListViewItem\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBParameterLI\fP (\fBQListView\fP *parent, \fBSBParameter\fP *P_)"
.br
.ti -1c
.RI "\fBSBParameter\fP * \fBparameter\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.ti -1c
.RI "virtual QString \fBkey\fP (int, bool) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBParameter\fP * \fBP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file SbISolution\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBParameterLI::SBParameterLI (\fBQListView\fP *parent, \fBSBParameter\fP *P_)\fC [inline]\fP"
.PP
Definition at line 49 of file SbISolution\&.H'\&.
.PP
References P\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBParameterLI::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 51 of file SbISolution\&.H'\&.
.SS "QString SBParameterLI::key (intcol, bool) const\fC [virtual]\fP"
.PP
Definition at line 86 of file SbISolution\&.C'\&.
.PP
References SBParameter::e(), SBNamed::name(), SBDerivation::num(), P, SBParameter::scale(), SBDerivation::tEpoch(), SBDerivation::tFinis(), TmpString, SBDerivation::tStart(), and SBParameter::v()\&.
.SS "\fBSBParameter\fP* SBParameterLI::parameter ()\fC [inline]\fP"
.PP
Definition at line 50 of file SbISolution\&.H'\&.
.PP
References P\&.
.SS "QString SBParameterLI::text (intcol) const\fC [virtual]\fP"
.PP
Definition at line 61 of file SbISolution\&.C'\&.
.PP
References SBParameter::e(), SBMJD::F_YYYYMMDDHHMMSSSS, SBNamed::name(), SBDerivation::num(), P, SBParameter::scale(), SBDerivation::tEpoch(), SBDerivation::tFinis(), TmpString, SBMJD::toString(), SBDerivation::tStart(), and SBParameter::v()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBParameter\fP* \fBSBParameterLI::P\fP\fC [private]\fP"
.PP
Definition at line 46 of file SbISolution\&.H'\&.
.PP
Referenced by key(), parameter(), SBParameterLI(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
