.TH "SBParameterList" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBParameterList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoParameter\&.H>\fP
.PP
Inherits \fBQList< SBParameter >\fP'\&.
.PP
Inherited by \fBSBEstimator::Group\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBParameterList\fP ()"
.br
.ti -1c
.RI "\fBSBParameterList\fP (const \fBSBParameterList\fP &L_)"
.br
.ti -1c
.RI "\fBSBParameterList\fP & \fBoperator=\fP (const \fBSBParameterList\fP &)"
.br
.ti -1c
.RI "virtual \fB~SBParameterList\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual void \fBappend\fP (const \fBSBParameter\fP *)"
.br
.ti -1c
.RI "virtual void \fBinSort\fP (const \fBSBParameter\fP *)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP (const QString &)"
.br
.ti -1c
.RI "virtual \fBSBParameter\fP * \fBfind\fP (const QString &p_) const "
.br
.ti -1c
.RI "virtual int \fBidx\fP (const \fBSBParameter\fP *p_)"
.br
.ti -1c
.RI "virtual int \fBidx\fP (const QString &p_)"
.br
.ti -1c
.RI "virtual void \fBclear\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdateSolution\fP (const \fBSBVector\fP *, const \fBSBSymMatrix\fP *)"
.br
.ti -1c
.RI "virtual void \fBreport\fP ()"
.br
.ti -1c
.RI "virtual void \fBclearPValues\fP ()"
.br
.ti -1c
.RI "virtual void \fBclearPValues_aux\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item p1, QCollection::Item p2)"
.br
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item E) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &E)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QDict< \fBSBParameter\fP > * \fBParByName\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBremove\fP (uint idx_)"
.br
.ti -1c
.RI "virtual bool \fBremove\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &, const \fBSBParameterList\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &, \fBSBParameterList\fP &)"
.br
.in -1c
.SS "Related Functions"
(Note that these are not member functions'\&.) 
.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBStochParameterList\fP &P)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSBParameterList\fP'\&. List of parameters, ordered by name'\&. Not an owner of inserted parameters'\&. 
.PP
Definition at line 470 of file SbGeoParameter\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBParameterList::SBParameterList ()\fC [inline]\fP"A constructor'\&. Creates a copy of the object'\&. 
.PP
Definition at line 491 of file SbGeoParameter\&.H'\&.
.SS "SBParameterList::SBParameterList (const \fBSBParameterList\fP &L_)\fC [inline]\fP"A constructor'\&. Creates a copy of the object'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIL_\fP is value to copy in'\&. 
.RE
.PP

.PP
Definition at line 501 of file SbGeoParameter\&.H'\&.
.SS "virtual SBParameterList::~SBParameterList ()\fC [inline, virtual]\fP"A destructor'\&. 
.PP
Definition at line 504 of file SbGeoParameter\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBParameterList::append (const \fBSBParameter\fP *p)\fC [virtual]\fP"
.PP
Definition at line 548 of file SbGeoParameter\&.C'\&.
.PP
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBNamed::name(), ParByName, and SBLog::write()\&.
.PP
Referenced by SBEstimator::collectContStochs4NextBatch(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::solveStochs(), and writeNormalEquationSystem()\&.
.SS "virtual QString SBParameterList::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info)'\&. 
.PP
Definition at line 506 of file SbGeoParameter\&.H'\&.
.PP
Referenced by append(), inSort(), remove(), report(), and updateSolution()\&.
.SS "virtual void SBParameterList::clear ()\fC [inline, virtual]\fP"
.PP
Definition at line 521 of file SbGeoParameter\&.H'\&.
.PP
Referenced by SBEstimator::collectContStochs4NextBatch(), SBRunManager::fillParameterList(), SBSolution::loadGlbCor(), SBSolution::loadGlbPar(), SBSolution::loadLocCor(), SBSolution::loadLocPar(), SBSolution::loadNormalEqs(), operator=(), SBSolution::SBSolution(), SBEstimator::solveStochs(), and writeNormalEquationSystem()\&.
.SS "void SBParameterList::clearPValues ()\fC [virtual]\fP"
.PP
Definition at line 661 of file SbGeoParameter\&.C'\&.
.PP
Referenced by SBEstimator::prepare4Local(), SBEstimator::prepare4Run(), and SBEstimator::processObs()\&.
.SS "void SBParameterList::clearPValues_aux ()\fC [virtual]\fP"
.PP
Definition at line 667 of file SbGeoParameter\&.C'\&.
.PP
Referenced by SBEstimator::prepare4Local()\&.
.SS "virtual int SBParameterList::compareItems (QCollection::Itemp1, QCollection::Itemp2)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 474 of file SbGeoParameter\&.H'\&.
.PP
References SBParameter::str4compare()\&.
.SS "virtual \fBSBParameter\fP* SBParameterList::find (const QString &p_) const\fC [inline, virtual]\fP"
.PP
Definition at line 516 of file SbGeoParameter\&.H'\&.
.PP
Referenced by SBSolution::getGlobalParameter4Report(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTRFVariations(), SBRunManager::process_m1(), SBEstimator::GroupList::remove(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SolutionEpochsBlock(), sinex_SourceIDBlock(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::updateParameter(), and writeNormalEquationSystem()\&.
.SS "virtual int SBParameterList::idx (const \fBSBParameter\fP *p_)\fC [inline, virtual]\fP"Returns an index of the parameter in the list 
.PP
Definition at line 519 of file SbGeoParameter\&.H'\&.
.PP
Referenced by SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), SBSolutionBrowser::updateCRF(), and writeNormalEquationSystem()\&.
.SS "virtual int SBParameterList::idx (const QString &p_)\fC [inline, virtual]\fP"
.PP
Definition at line 520 of file SbGeoParameter\&.H'\&.
.SS "void SBParameterList::inSort (const \fBSBParameter\fP *p)\fC [virtual]\fP"
.PP
Definition at line 568 of file SbGeoParameter\&.C'\&.
.PP
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBNamed::name(), ParByName, and SBLog::write()\&.
.PP
Referenced by SBEstimator::Group::addParameter(), SBRunManager::fillParameterList(), operator=(), SBVLBIPreProcess::procScenario_2(), SBSolution::submitGlobalParameters(), and SBSolution::submitLocalParameters()\&.
.SS "\fBSBParameterList\fP & SBParameterList::operator= (const \fBSBParameterList\fP &L_)"
.PP
Definition at line 532 of file SbGeoParameter\&.C'\&.
.PP
References clear(), inSort(), and ParByName\&.
.SS "virtual QDataStream& SBParameterList::read (QDataStream &s, QCollection::Item &E)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 482 of file SbGeoParameter\&.H'\&.
.SS "bool SBParameterList::remove (const QString &key)\fC [virtual]\fP"
.PP
Definition at line 588 of file SbGeoParameter\&.C'\&.
.PP
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, ParByName, remove(), and SBLog::write()\&.
.PP
Referenced by SBEstimator::GroupList::remove()\&.
.SS "virtual bool SBParameterList::remove (uintidx_)\fC [inline, private, virtual]\fP"
.PP
Definition at line 528 of file SbGeoParameter\&.H'\&.
.PP
References SBNamed::name()\&.
.SS "virtual bool SBParameterList::remove ()\fC [inline, private, virtual]\fP"
.PP
Definition at line 531 of file SbGeoParameter\&.H'\&.
.PP
References SBNamed::name()\&.
.PP
Referenced by SBEstimator::Group::delParameter(), and remove()\&.
.SS "void SBParameterList::report ()\fC [virtual]\fP"
.PP
Definition at line 642 of file SbGeoParameter\&.C'\&.
.PP
References ClassName(), SBLog::DBG, SBParameter::e(), SBLog::ESTIMATOR, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::isEligible(), Log, SBNamed::name(), SBDerivation::num(), SBParameter::s(), SBParameter::scale(), SBDerivation::tEpoch(), SBDerivation::tFinis(), SBMJD::toString(), SBDerivation::tStart(), SBParameter::v(), and SBLog::write()\&.
.PP
Referenced by SBSolution::reportGlobalParameters(), and SBSolution::reportLocalParameters()\&.
.SS "void SBParameterList::updateSolution (const \fBSBVector\fP *X, const \fBSBSymMatrix\fP *P)\fC [virtual]\fP"
.PP
Definition at line 602 of file SbGeoParameter\&.C'\&.
.PP
References SBVector::at(), SBSymMatrix::at(), ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBVector::n(), SBUpperMatrix::n(), SBNamed::name(), SBParameter::setS(), and SBLog::write()\&.
.PP
Referenced by SBEstimator::solveGlobals(), and SBEstimator::solveLocals()\&.
.SS "virtual QDataStream& SBParameterList::write (QDataStream &s, QCollection::ItemE) const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 480 of file SbGeoParameter\&.H'\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream & operator<< (QDataStream &s, const \fBSBParameterList\fP &P)\fC [friend]\fP"Output to the data stream'\&. 
.PP
Definition at line 684 of file SbGeoParameter\&.C'\&.
.SS "QDataStream & operator>> (QDataStream &s, \fBSBParameterList\fP &P)\fC [friend]\fP"Input from the data stream'\&. 
.PP
Definition at line 692 of file SbGeoParameter\&.C'\&.
.SS "QDataStream & operator>> (QDataStream &s, \fBSBStochParameterList\fP &P)\fC [related]\fP"Input from the data stream'\&. 
.PP
Definition at line 999 of file SbGeoParameter\&.C'\&.
.PP
References SBStochParameterList::clear(), and SBStochParameterList::ParByName\&.
.SH "Member Data Documentation"
.PP 
.SS "QDict<\fBSBParameter\fP>* \fBSBParameterList::ParByName\fP\fC [protected]\fP"
.PP
Definition at line 473 of file SbGeoParameter\&.H'\&.
.PP
Referenced by append(), inSort(), operator=(), and remove()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
