SBParameterList
NAME
SBParameterList -
SYNOPSIS
#include <SbGeoParameter.H>
Inherits QList< SBParameter >'.
Inherited by SBEstimator::Group'.
Public Member Functions
SBParameterList ()
SBParameterList (const SBParameterList &L_)
SBParameterList & operator= (const SBParameterList &)
virtual ~SBParameterList ()
virtual QString ClassName () const
virtual void append (const SBParameter *)
virtual void inSort (const SBParameter *)
virtual bool remove (const QString &)
virtual SBParameter * find (const QString &p_) const
virtual int idx (const SBParameter *p_)
virtual int idx (const QString &p_)
virtual void clear ()
virtual void updateSolution (const SBVector *, const SBSymMatrix *)
virtual void report ()
virtual void clearPValues ()
virtual void clearPValues_aux ()
Protected Member Functions
virtual int compareItems (QCollection::Item p1, QCollection::Item p2)
virtual QDataStream & write (QDataStream &s, QCollection::Item E) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &E)
Protected Attributes
QDict< SBParameter > * ParByName
Private Member Functions
virtual bool remove (uint idx_)
virtual bool remove ()
Friends
QDataStream & operator<< (QDataStream &, const SBParameterList &)
QDataStream & operator>> (QDataStream &, SBParameterList &)
Related Functions
(Note that these are not member functions'.)
QDataStream & operator>> (QDataStream &s, SBStochParameterList &P)
Detailed Description
SBParameterList'. List of parameters, ordered by name'. Not an owner of inserted parameters'.
Definition at line 470 of file SbGeoParameter.H'.
Constructor & Destructor Documentation
SBParameterList::SBParameterList () [inline]"A constructor'. Creates a copy of the object'.
Definition at line 491 of file SbGeoParameter.H'.
SBParameterList::SBParameterList (const SBParameterList &L_) [inline]"A constructor'. Creates a copy of the object'.
Parameters:
L_ is value to copy in'.
Definition at line 501 of file SbGeoParameter.H'.
virtual SBParameterList::~SBParameterList () [inline, virtual]"A destructor'.
Definition at line 504 of file SbGeoParameter.H'.
Member Function Documentation
void SBParameterList::append (const SBParameter *p) [virtual]
Definition at line 548 of file SbGeoParameter.C'.
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBNamed::name(), ParByName, and SBLog::write().
Referenced by SBEstimator::collectContStochs4NextBatch(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::solveStochs(), and writeNormalEquationSystem().
virtual QString SBParameterList::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Definition at line 506 of file SbGeoParameter.H'.
Referenced by append(), inSort(), remove(), report(), and updateSolution().
virtual void SBParameterList::clear () [inline, virtual]
Definition at line 521 of file SbGeoParameter.H'.
Referenced by SBEstimator::collectContStochs4NextBatch(), SBRunManager::fillParameterList(), SBSolution::loadGlbCor(), SBSolution::loadGlbPar(), SBSolution::loadLocCor(), SBSolution::loadLocPar(), SBSolution::loadNormalEqs(), operator=(), SBSolution::SBSolution(), SBEstimator::solveStochs(), and writeNormalEquationSystem().
void SBParameterList::clearPValues () [virtual]
Definition at line 661 of file SbGeoParameter.C'.
Referenced by SBEstimator::prepare4Local(), SBEstimator::prepare4Run(), and SBEstimator::processObs().
void SBParameterList::clearPValues_aux () [virtual]
Definition at line 667 of file SbGeoParameter.C'.
Referenced by SBEstimator::prepare4Local().
virtual int SBParameterList::compareItems (QCollection::Itemp1, QCollection::Itemp2) [inline, protected, virtual]
Definition at line 474 of file SbGeoParameter.H'.
References SBParameter::str4compare().
virtual SBParameter* SBParameterList::find (const QString &p_) const [inline, virtual]
Definition at line 516 of file SbGeoParameter.H'.
Referenced by SBSolution::getGlobalParameter4Report(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTRFVariations(), SBRunManager::process_m1(), SBEstimator::GroupList::remove(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SolutionEpochsBlock(), sinex_SourceIDBlock(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::updateParameter(), and writeNormalEquationSystem().
virtual int SBParameterList::idx (const SBParameter *p_) [inline, virtual]"Returns an index of the parameter in the list
Definition at line 519 of file SbGeoParameter.H'.
Referenced by SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), SBSolutionBrowser::updateCRF(), and writeNormalEquationSystem().
virtual int SBParameterList::idx (const QString &p_) [inline, virtual]
Definition at line 520 of file SbGeoParameter.H'.
void SBParameterList::inSort (const SBParameter *p) [virtual]
Definition at line 568 of file SbGeoParameter.C'.
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBNamed::name(), ParByName, and SBLog::write().
Referenced by SBEstimator::Group::addParameter(), SBRunManager::fillParameterList(), operator=(), SBVLBIPreProcess::procScenario_2(), SBSolution::submitGlobalParameters(), and SBSolution::submitLocalParameters().
SBParameterList & SBParameterList::operator= (const SBParameterList &L_)
Definition at line 532 of file SbGeoParameter.C'.
References clear(), inSort(), and ParByName.
virtual QDataStream& SBParameterList::read (QDataStream &s, QCollection::Item &E) [inline, protected, virtual]
Definition at line 482 of file SbGeoParameter.H'.
bool SBParameterList::remove (const QString &key) [virtual]
Definition at line 588 of file SbGeoParameter.C'.
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, ParByName, remove(), and SBLog::write().
Referenced by SBEstimator::GroupList::remove().
virtual bool SBParameterList::remove (uintidx_) [inline, private, virtual]
Definition at line 528 of file SbGeoParameter.H'.
References SBNamed::name().
virtual bool SBParameterList::remove () [inline, private, virtual]
Definition at line 531 of file SbGeoParameter.H'.
References SBNamed::name().
Referenced by SBEstimator::Group::delParameter(), and remove().
void SBParameterList::report () [virtual]
Definition at line 642 of file SbGeoParameter.C'.
References ClassName(), SBLog::DBG, SBParameter::e(), SBLog::ESTIMATOR, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::isEligible(), Log, SBNamed::name(), SBDerivation::num(), SBParameter::s(), SBParameter::scale(), SBDerivation::tEpoch(), SBDerivation::tFinis(), SBMJD::toString(), SBDerivation::tStart(), SBParameter::v(), and SBLog::write().
Referenced by SBSolution::reportGlobalParameters(), and SBSolution::reportLocalParameters().
void SBParameterList::updateSolution (const SBVector *X, const SBSymMatrix *P) [virtual]
Definition at line 602 of file SbGeoParameter.C'.
References SBVector::at(), SBSymMatrix::at(), ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBVector::n(), SBUpperMatrix::n(), SBNamed::name(), SBParameter::setS(), and SBLog::write().
Referenced by SBEstimator::solveGlobals(), and SBEstimator::solveLocals().
virtual QDataStream& SBParameterList::write (QDataStream &s, QCollection::ItemE) const [inline, protected, virtual]
Definition at line 480 of file SbGeoParameter.H'.
Friends And Related Function Documentation
QDataStream & operator<< (QDataStream &s, const SBParameterList &P) [friend]"Output to the data stream'.
Definition at line 684 of file SbGeoParameter.C'.
QDataStream & operator>> (QDataStream &s, SBParameterList &P) [friend]"Input from the data stream'.
Definition at line 692 of file SbGeoParameter.C'.
QDataStream & operator>> (QDataStream &s, SBStochParameterList &P) [related]"Input from the data stream'.
Definition at line 999 of file SbGeoParameter.C'.
References SBStochParameterList::clear(), and SBStochParameterList::ParByName.
Member Data Documentation
QDict<SBParameter>* SBParameterList::ParByName [protected]
Definition at line 473 of file SbGeoParameter.H'.
Referenced by append(), inSort(), operator=(), and remove().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.