SBParEditor
NAME
SBParEditor -
SYNOPSIS
#include <SbIProject.H>
Inherits QDialog'.
Signals
void valueModified (bool)
Public Member Functions
SBParEditor (SBParameterCfg *, const QString &, int, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBParEditor ()
virtual QString ClassName () const
Protected Slots
void makeDefault ()
void accept ()
void reject ()
Private Member Functions
virtual void acquireData ()
virtual void browseData ()
Private Attributes
SBParameterCfg * P
bool isModified
bool isConstrained
int Idx
QString ParName
QLineEdit * ConvApriori
QLineEdit * StocApriori
QLineEdit * RuledWNoise
QLineEdit * BreaksNoise
QLineEdit * Tau
QCheckBox * Propagate
QRadioButton * Type [5]
Detailed Description
Definition at line 416 of file SbIProject.H'.
Constructor & Destructor Documentation
SBParEditor::SBParEditor (SBParameterCfg *P_, const QString &ParName_, intIdx_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2533 of file SbIProject.C'.
References accept(), SBParameterCfg::breakNoise(), BreaksNoise, SBParameterCfg::convAPriori(), ConvApriori, Idx, isModified, SBParameterCfg::isPropagated(), makeDefault(), SBParametersDesc::n(), P, ParName, Propagate, reject(), RuledWNoise, SBParameterCfg::scaleName(), SBParameterCfg::stocAPriori(), StocApriori, SBParameterCfg::stochasticType(), SBParameterCfg::tau(), Tau, Type, and SBParameterCfg::whiteNoise().
SBParEditor::~SBParEditor () [virtual]
Definition at line 2663 of file SbIProject.C'.
Member Function Documentation
void SBParEditor::accept () [protected, slot]
Definition at line 2668 of file SbIProject.C'.
References acquireData(), isModified, and valueModified().
Referenced by SBParEditor().
void SBParEditor::acquireData () [private, virtual]
Definition at line 2698 of file SbIProject.C'.
References SBParameterCfg::breakNoise(), BreaksNoise, SBParameterCfg::convAPriori(), ConvApriori, isModified, SBParameterCfg::isPropagated(), P, Propagate, RuledWNoise, SBParameterCfg::setBreakNoise(), SBParameterCfg::setConvAPriori(), SBParameterCfg::setPropagated(), SBParameterCfg::setStocAPriori(), SBParameterCfg::setStochasticType(), SBParameterCfg::setTau(), SBParameterCfg::setWhiteNoise(), SBParameterCfg::ST_MARKOVPROCESS, SBParameterCfg::ST_NONE, SBParameterCfg::ST_RANDWALK, SBParameterCfg::ST_UNKN, SBParameterCfg::ST_WHITENOISE, SBParameterCfg::stocAPriori(), StocApriori, SBParameterCfg::stochasticType(), SBParameterCfg::tau(), Tau, Type, and SBParameterCfg::whiteNoise().
Referenced by accept().
void SBParEditor::browseData () [private, virtual]
Definition at line 2685 of file SbIProject.C'.
References SBParameterCfg::breakNoise(), BreaksNoise, SBParameterCfg::convAPriori(), ConvApriori, SBParameterCfg::isPropagated(), P, Propagate, RuledWNoise, SBParameterCfg::stocAPriori(), StocApriori, SBParameterCfg::stochasticType(), SBParameterCfg::tau(), Tau, Type, and SBParameterCfg::whiteNoise().
Referenced by makeDefault().
virtual QString SBParEditor::ClassName () const [inline, virtual]
Definition at line 423 of file SbIProject.H'.
Referenced by makeDefault().
void SBParEditor::makeDefault () [protected, slot]
Definition at line 2676 of file SbIProject.C'.
References browseData(), ClassName(), SBLog::DBG, DefaultConfig, Idx, SBLog::INTERFACE, isModified, Log, SBConfig::p(), P, SBParametersDesc::par(), and SBLog::write().
Referenced by SBParEditor().
void SBParEditor::reject () [inline, protected, slot]
Definition at line 432 of file SbIProject.H'.
References valueModified().
Referenced by SBParEditor().
void SBParEditor::valueModified (boolt0) [signal]
Definition at line 805 of file SbIProject.moc.C'.
Referenced by accept(), and reject().
Member Data Documentation
QLineEdit* SBParEditor::BreaksNoise [private]
Definition at line 444 of file SbIProject.H'.
Referenced by acquireData(), browseData(), and SBParEditor().
QLineEdit* SBParEditor::ConvApriori [private]
Definition at line 441 of file SbIProject.H'.
Referenced by acquireData(), browseData(), and SBParEditor().
int SBParEditor::Idx [private]
Definition at line 438 of file SbIProject.H'.
Referenced by makeDefault(), and SBParEditor().
bool SBParEditor::isConstrained [private]
Definition at line 437 of file SbIProject.H'.
bool SBParEditor::isModified [private]
Definition at line 436 of file SbIProject.H'.
Referenced by accept(), acquireData(), makeDefault(), and SBParEditor().
SBParameterCfg* SBParEditor::P [private]
Definition at line 432 of file SbIProject.H'.
Referenced by acquireData(), browseData(), makeDefault(), and SBParEditor().
QString SBParEditor::ParName [private]
Definition at line 439 of file SbIProject.H'.
Referenced by SBParEditor().
QCheckBox* SBParEditor::Propagate [private]
Definition at line 446 of file SbIProject.H'.
Referenced by acquireData(), browseData(), and SBParEditor().
QLineEdit* SBParEditor::RuledWNoise [private]
Definition at line 443 of file SbIProject.H'.
Referenced by acquireData(), browseData(), and SBParEditor().
QLineEdit* SBParEditor::StocApriori [private]
Definition at line 442 of file SbIProject.H'.
Referenced by acquireData(), browseData(), and SBParEditor().
QLineEdit* SBParEditor::Tau [private]
Definition at line 445 of file SbIProject.H'.
Referenced by acquireData(), browseData(), and SBParEditor().
QRadioButton* SBParEditor::Type[5] [private]
Definition at line 447 of file SbIProject.H'.
Referenced by acquireData(), browseData(), and SBParEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.