.TH "SBParametersEditor" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBParametersEditor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIProject\&.H>\fP
.PP
Inherits \fBSBTabDialog\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBParametersEditor\fP (\fBSBParametersDesc\fP *=NULL, \fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "virtual \fB~SBParametersEditor\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBmakeDefault\fP ()"
.br
.ti -1c
.RI "virtual void \fBmakeApply\fP ()"
.br
.ti -1c
.RI "void \fBParameterModified\fP (bool)"
.br
.ti -1c
.RI "void \fBeditParameter\fP (int)"
.br
.ti -1c
.RI "void \fBeditPar__0\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__1\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__2\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__3\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__4\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__5\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__6\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__7\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__8\fP ()"
.br
.ti -1c
.RI "void \fBeditPar__9\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_10\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_11\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_12\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_13\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_14\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_15\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_16\fP ()"
.br
.ti -1c
.RI "void \fBeditPar_17\fP ()"
.br
.ti -1c
.RI "virtual void \fBmakeDefaults\fP ()"
.br
.ti -1c
.RI "virtual void \fBdone\fP (int r)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *e)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBQWidget\fP * \fBwStationParameters\fP ()"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBwSourceParameters\fP ()"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBwEOPParameters\fP ()"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBwOtherParameters\fP ()"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBwTestParameters\fP ()"
.br
.ti -1c
.RI "virtual void \fBacquireData\fP ()"
.br
.ti -1c
.RI "virtual void \fBbrowseData\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBParametersDesc\fP * \fBP\fP"
.br
.ti -1c
.RI "\fBSBProject\fP * \fBProject\fP"
.br
.ti -1c
.RI "bool \fBisModified\fP"
.br
.ti -1c
.RI "bool \fBisGlobal\fP"
.br
.ti -1c
.RI "int \fBnumOpenedWindows\fP"
.br
.ti -1c
.RI "QRadioButton * \fBRB\fP [NUMBER_OF_PARAMETERS][5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 336 of file SbIProject\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBParametersEditor::SBParametersEditor (\fBSBParametersDesc\fP *P_ = \fCNULL\fP, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 1970 of file SbIProject\&.C'\&.
.PP
References isGlobal, isModified, SBSetUp::loadProject(), makeApply(), makeDefault(), SBNamed::name(), numOpenedWindows, P, SBProject::p(), Project, SetUp, wEOPParameters(), wOtherParameters(), wSourceParameters(), wStationParameters(), and wTestParameters()\&.
.SS "SBParametersEditor::~SBParametersEditor ()\fC [virtual]\fP"
.PP
Definition at line 2004 of file SbIProject\&.C'\&.
.PP
References Config, isGlobal, isModified, P, Project, SBSetUp::saveProject(), SBConfig::setP(), SBProject::setP(), and SetUp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBParametersEditor::acquireData ()\fC [private, virtual]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 2041 of file SbIProject\&.C'\&.
.PP
References isModified, SBParametersDesc::n(), P, SBParametersDesc::par(), SBParameterCfg::PT_ARC, SBParameterCfg::PT_GLB, SBParameterCfg::PT_LOC, SBParameterCfg::PT_NONE, SBParameterCfg::PT_STH, RB, SBParameterCfg::setType(), SBParametersDesc::setType(), and SBParameterCfg::type()\&.
.PP
Referenced by makeApply()\&.
.SS "void SBParametersEditor::browseData ()\fC [private, virtual]\fP"
.PP
Definition at line 2035 of file SbIProject\&.C'\&.
.PP
References SBParametersDesc::n(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type()\&.
.PP
Referenced by makeDefault()\&.
.SS "virtual QString SBParametersEditor::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 342 of file SbIProject\&.H'\&.
.PP
Referenced by makeApply(), and makeDefault()\&.
.SS "virtual void SBParametersEditor::closeEvent (QCloseEvent *e)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 405 of file SbIProject\&.H'\&.
.PP
References numOpenedWindows\&.
.SS "virtual void SBTabDialog::done (intr)\fC [inline, protected, virtual, slot, inherited]\fP"
.PP
Reimplemented in \fBSBSiteEditor\fP, and \fBSBProjectEdit\fP'\&.
.PP
Definition at line 82 of file SbInterface\&.H'\&.
.PP
References SBTabDialog::acquireData()\&.
.SS "void SBParametersEditor::editPar_10 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 363 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wEOPParameters()\&.
.SS "void SBParametersEditor::editPar_11 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 364 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wEOPParameters()\&.
.SS "void SBParametersEditor::editPar_12 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 365 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wEOPParameters()\&.
.SS "void SBParametersEditor::editPar_13 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 366 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wTestParameters()\&.
.SS "void SBParametersEditor::editPar_14 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 367 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wOtherParameters()\&.
.SS "void SBParametersEditor::editPar_15 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 368 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar_16 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 369 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar_17 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 370 of file SbIProject\&.H'\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__0 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 353 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__1 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 354 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__2 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 355 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__3 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 356 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__4 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 357 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wSourceParameters()\&.
.SS "void SBParametersEditor::editPar__5 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 358 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__6 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 359 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__7 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 360 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__8 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 361 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editPar__9 ()\fC [inline, protected, slot]\fP"
.PP
Definition at line 362 of file SbIProject\&.H'\&.
.PP
References editParameter()\&.
.PP
Referenced by wStationParameters()\&.
.SS "void SBParametersEditor::editParameter (intN_)\fC [protected, slot]\fP"
.PP
Definition at line 2516 of file SbIProject\&.C'\&.
.PP
References SBNamed::name(), numOpenedWindows, P, SBParametersDesc::par(), and ParameterModified()\&.
.PP
Referenced by editPar_10(), editPar_11(), editPar_12(), editPar_13(), editPar_14(), editPar_15(), editPar_16(), editPar__0(), editPar__1(), editPar__2(), editPar__3(), editPar__4(), editPar__5(), editPar__6(), editPar__7(), editPar__8(), and editPar__9()\&.
.SS "void SBParametersEditor::makeApply ()\fC [protected, virtual, slot]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 2019 of file SbIProject\&.C'\&.
.PP
References acquireData(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write()\&.
.PP
Referenced by SBParametersEditor()\&.
.SS "void SBParametersEditor::makeDefault ()\fC [protected, virtual, slot]\fP"
.PP
Definition at line 2026 of file SbIProject\&.C'\&.
.PP
References browseData(), ClassName(), SBLog::DBG, DefaultConfig, SBLog::INTERFACE, isModified, Log, SBConfig::p(), P, and SBLog::write()\&.
.PP
Referenced by SBParametersEditor()\&.
.SS "virtual void SBTabDialog::makeDefaults ()\fC [inline, protected, virtual, slot, inherited]\fP"
.PP
Reimplemented in \fBSBSetupDialog\fP'\&.
.PP
Definition at line 79 of file SbInterface\&.H'\&.
.SS "void SBParametersEditor::ParameterModified (boolModified)\fC [protected, slot]\fP"
.PP
Definition at line 2507 of file SbIProject\&.C'\&.
.PP
References isModified, and numOpenedWindows\&.
.PP
Referenced by editParameter()\&.
.SS "\fBQWidget\fP * SBParametersEditor::wEOPParameters ()\fC [private]\fP"
.PP
Definition at line 2244 of file SbIProject\&.C'\&.
.PP
References editPar_10(), editPar_11(), editPar_12(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type()\&.
.PP
Referenced by SBParametersEditor()\&.
.SS "\fBQWidget\fP * SBParametersEditor::wOtherParameters ()\fC [private]\fP"
.PP
Definition at line 2333 of file SbIProject\&.C'\&.
.PP
References editPar_14(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type()\&.
.PP
Referenced by SBParametersEditor()\&.
.SS "\fBQWidget\fP * SBParametersEditor::wSourceParameters ()\fC [private]\fP"
.PP
Definition at line 2157 of file SbIProject\&.C'\&.
.PP
References editPar__4(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type()\&.
.PP
Referenced by SBParametersEditor()\&.
.SS "\fBQWidget\fP * SBParametersEditor::wStationParameters ()\fC [private]\fP"
.PP
Definition at line 2059 of file SbIProject\&.C'\&.
.PP
References editPar_15(), editPar_16(), editPar_17(), editPar__0(), editPar__1(), editPar__2(), editPar__3(), editPar__5(), editPar__6(), editPar__7(), editPar__8(), editPar__9(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type()\&.
.PP
Referenced by SBParametersEditor()\&.
.SS "\fBQWidget\fP * SBParametersEditor::wTestParameters ()\fC [private]\fP"
.PP
Definition at line 2420 of file SbIProject\&.C'\&.
.PP
References editPar_13(), SBNamed::name(), P, SBParametersDesc::par(), RB, and SBParameterCfg::type()\&.
.PP
Referenced by SBParametersEditor()\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSBParametersEditor::isGlobal\fP\fC [private]\fP"
.PP
Definition at line 377 of file SbIProject\&.H'\&.
.PP
Referenced by SBParametersEditor(), and ~SBParametersEditor()\&.
.SS "bool \fBSBParametersEditor::isModified\fP\fC [private]\fP"
.PP
Definition at line 376 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), makeDefault(), ParameterModified(), SBParametersEditor(), and ~SBParametersEditor()\&.
.SS "int \fBSBParametersEditor::numOpenedWindows\fP\fC [private]\fP"
.PP
Definition at line 378 of file SbIProject\&.H'\&.
.PP
Referenced by closeEvent(), editParameter(), ParameterModified(), and SBParametersEditor()\&.
.SS "\fBSBParametersDesc\fP* \fBSBParametersEditor::P\fP\fC [private]\fP"
.PP
Definition at line 370 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), editParameter(), makeDefault(), SBParametersEditor(), wEOPParameters(), wOtherParameters(), wSourceParameters(), wStationParameters(), wTestParameters(), and ~SBParametersEditor()\&.
.SS "\fBSBProject\fP* \fBSBParametersEditor::Project\fP\fC [private]\fP"
.PP
Definition at line 375 of file SbIProject\&.H'\&.
.PP
Referenced by SBParametersEditor(), and ~SBParametersEditor()\&.
.SS "QRadioButton* \fBSBParametersEditor::RB\fP[NUMBER_OF_PARAMETERS][5]\fC [private]\fP"
.PP
Definition at line 380 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), browseData(), wEOPParameters(), wOtherParameters(), wSourceParameters(), wStationParameters(), and wTestParameters()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
