SBParameterCfg
NAME
SBParameterCfg -
SYNOPSIS
#include <SbGeoParameter.H>
Inherits SBNamed'.
Public Types
enum PType { PT_NONE = 0, PT_GLB = 1, PT_ARC = 2, PT_LOC = 3, PT_STH = 4 }
enum StochType { ST_NONE = 0, ST_WHITENOISE = 1, ST_MARKOVPROCESS = 2, ST_RANDWALK = 3, ST_UNKN = 4 }
Public Member Functions
SBParameterCfg ()
SBParameterCfg (const QString &, bool, bool, PType, double, double, double, double, double, double, const QString &, StochType=ST_RANDWALK)
SBParameterCfg (const SBParameterCfg &P_)
virtual ~SBParameterCfg ()
SBParameterCfg & operator= (const SBParameterCfg &)
virtual QString ClassName () const
virtual bool isPropagated () const
virtual bool isConstrained () const
virtual PType type () const
virtual StochType stochasticType () const
virtual double convAPriori () const
virtual double stocAPriori () const
virtual double breakNoise () const
virtual double tau () const
virtual double whiteNoise () const
virtual double scale () const
virtual const QString & scaleName () const
virtual void setPropagated (bool Is_)
virtual void setConstrained (bool Is_)
virtual void setType (PType T_)
virtual void setStochasticType (StochType T_)
virtual void setConvAPriori (double d_)
virtual void setStocAPriori (double d_)
virtual void setBreakNoise (double d_)
virtual void setTau (double d_)
virtual void setWhiteNoise (double d_)
virtual void setScale (double d_)
virtual void setScaleName (const QString &_)
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
QString Name
Private Attributes
bool IsPropagated
Propagate the parameter in time'.
bool IsConstrained
The parameter needs constrains'.
PType Type
StochType StochasticType
double ConvAPriori
a priori std'. deviation (conventional pars)
double StocAPriori
a priori std'. deviation (stochastic pars)
double BreakNoise
psd of noise process used for 'breaks'
double Tau
time of relaxation
double WhiteNoise
psd of ruled white noise
double Scale
Value of the scale factor'.
QString ScaleName
Name of the scale factor'.
Friends
QDataStream & operator<< (QDataStream &, const SBParameterCfg &)
QDataStream & operator>> (QDataStream &, SBParameterCfg &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Related Functions
(Note that these are not member functions'.)
QDataStream & operator>> (QDataStream &s, SBParametersDesc &D)
Detailed Description
Class SBParameterCfg, the Parameter's configuration'. It just describes the config for each estimated parameter'.
Definition at line 50 of file SbGeoParameter.H'.
Member Enumeration Documentation
enum SBParameterCfg::PType
Enumerator:
PT_NONE
PT_GLB
PT_ARC
PT_LOC
PT_STH
Definition at line 53 of file SbGeoParameter.H'.
enum SBParameterCfg::StochType
Enumerator:
ST_NONE
ST_WHITENOISE
ST_MARKOVPROCESS
ST_RANDWALK
ST_UNKN
Definition at line 54 of file SbGeoParameter.H'.
Constructor & Destructor Documentation
SBParameterCfg::SBParameterCfg ()"A constructor'.
Definition at line 44 of file SbGeoParameter.C'.
References BreakNoise, ConvAPriori, IsConstrained, IsPropagated, PT_NONE, Scale, ST_RANDWALK, StocAPriori, StochasticType, Tau, Type, and WhiteNoise.
SBParameterCfg::SBParameterCfg (const QString &Name_, boolIsPropagated_, boolIsConstrained_, PTypeType_, doubleConvAPriori_, doubleStocAPriori_, doubleBreakNoise_, doubleTau_, doubleWhiteNoise_, doubleScale_, const QString &ScaleName_, StochTypeStochasticType_ = ST_RANDWALK)"A constructor'.
Definition at line 59 of file SbGeoParameter.C'.
References BreakNoise, ConvAPriori, IsConstrained, IsPropagated, Scale, ScaleName, StocAPriori, StochasticType, Tau, Type, and WhiteNoise.
SBParameterCfg::SBParameterCfg (const SBParameterCfg &P_) [inline]"A constructor'.
Definition at line 79 of file SbGeoParameter.H'.
virtual SBParameterCfg::~SBParameterCfg () [inline, virtual]"A destructor'.
Definition at line 81 of file SbGeoParameter.H'.
Member Function Documentation
virtual double SBParameterCfg::breakNoise () const [inline, virtual]
Definition at line 94 of file SbGeoParameter.H'.
References BreakNoise.
Referenced by SBParEditor::acquireData(), SBParEditor::browseData(), SBStationInfo::dumpUserInfo(), operator=(), SBParEditor::SBParEditor(), and SBParameter::tuneParameter().
virtual QString SBParameterCfg::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBNamed'.
Definition at line 84 of file SbGeoParameter.H'.
virtual double SBParameterCfg::convAPriori () const [inline, virtual]
Definition at line 92 of file SbGeoParameter.H'.
References ConvAPriori.
Referenced by SBParEditor::acquireData(), SBParEditor::browseData(), operator=(), SBParEditor::SBParEditor(), and SBParameter::tuneParameter().
virtual bool SBParameterCfg::isConstrained () const [inline, virtual]
Definition at line 89 of file SbGeoParameter.H'.
References IsConstrained.
Referenced by operator=().
virtual bool SBParameterCfg::isPropagated () const [inline, virtual]
Definition at line 88 of file SbGeoParameter.H'.
References IsPropagated.
Referenced by SBParEditor::acquireData(), SBParEditor::browseData(), operator=(), SBParEditor::SBParEditor(), and SBParameter::tuneParameter().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
SBParameterCfg & SBParameterCfg::operator= (const SBParameterCfg &P)
Definition at line 80 of file SbGeoParameter.C'.
References breakNoise(), convAPriori(), isConstrained(), isPropagated(), scale(), scaleName(), setBreakNoise(), setConstrained(), setConvAPriori(), setPropagated(), setScale(), setScaleName(), setStocAPriori(), setStochasticType(), setTau(), setType(), setWhiteNoise(), stocAPriori(), stochasticType(), tau(), type(), and whiteNoise().
virtual double SBParameterCfg::scale () const [inline, virtual]
Definition at line 97 of file SbGeoParameter.H'.
References Scale.
Referenced by operator=(), and SBParameter::tuneParameter().
virtual const QString& SBParameterCfg::scaleName () const [inline, virtual]
Definition at line 98 of file SbGeoParameter.H'.
References ScaleName.
Referenced by operator=(), SBParEditor::SBParEditor(), and sinex_tro_TropDescriptionBlock().
virtual void SBParameterCfg::setBreakNoise (doubled_) [inline, virtual]
Definition at line 106 of file SbGeoParameter.H'.
References BreakNoise.
Referenced by SBParEditor::acquireData(), operator=(), and SBStationInfo::restoreUserInfo().
virtual void SBParameterCfg::setConstrained (boolIs_) [inline, virtual]
Definition at line 101 of file SbGeoParameter.H'.
References IsConstrained.
Referenced by operator=().
virtual void SBParameterCfg::setConvAPriori (doubled_) [inline, virtual]
Definition at line 104 of file SbGeoParameter.H'.
References ConvAPriori.
Referenced by SBParEditor::acquireData(), operator=(), and SBVLBIPreProcess::preProcess().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
virtual void SBParameterCfg::setPropagated (boolIs_) [inline, virtual]
Definition at line 100 of file SbGeoParameter.H'.
References IsPropagated.
Referenced by SBParEditor::acquireData(), and operator=().
virtual void SBParameterCfg::setScale (doubled_) [inline, virtual]
Definition at line 109 of file SbGeoParameter.H'.
References Scale.
Referenced by SBRunManager::fillParameterList(), and operator=().
virtual void SBParameterCfg::setScaleName (const QString &_) [inline, virtual]
Definition at line 110 of file SbGeoParameter.H'.
References ScaleName.
Referenced by operator=().
virtual void SBParameterCfg::setStocAPriori (doubled_) [inline, virtual]
Definition at line 105 of file SbGeoParameter.H'.
References StocAPriori.
Referenced by SBParEditor::acquireData(), and operator=().
virtual void SBParameterCfg::setStochasticType (StochTypeT_) [inline, virtual]
Definition at line 103 of file SbGeoParameter.H'.
References StochasticType.
Referenced by SBParEditor::acquireData(), and operator=().
virtual void SBParameterCfg::setTau (doubled_) [inline, virtual]
Definition at line 107 of file SbGeoParameter.H'.
References Tau.
Referenced by SBParEditor::acquireData(), and operator=().
virtual void SBParameterCfg::setType (PTypeT_) [inline, virtual]
Definition at line 102 of file SbGeoParameter.H'.
References Type.
Referenced by SBParametersEditor::acquireData(), operator=(), SBParametersDesc::setCableType(), SBParametersDesc::setClock0Type(), SBParametersDesc::setClock1Type(), SBParametersDesc::setClock2Type(), SBParametersDesc::setClock3Type(), SBParametersDesc::setLove_h2Type(), SBParametersDesc::setLove_l2Type(), SBParametersDesc::setTideLagType(), SBParametersDesc::setType(), and SBParametersDesc::setZenithType().
virtual void SBParameterCfg::setWhiteNoise (doubled_) [inline, virtual]
Definition at line 108 of file SbGeoParameter.H'.
References WhiteNoise.
Referenced by SBParEditor::acquireData(), operator=(), SBVLBIPreProcess::preProcess(), and SBStationInfo::restoreUserInfo().
virtual double SBParameterCfg::stocAPriori () const [inline, virtual]
Definition at line 93 of file SbGeoParameter.H'.
References StocAPriori.
Referenced by SBParEditor::acquireData(), SBParEditor::browseData(), operator=(), SBParEditor::SBParEditor(), and SBParameter::tuneParameter().
virtual StochType SBParameterCfg::stochasticType () const [inline, virtual]
Definition at line 91 of file SbGeoParameter.H'.
References StochasticType.
Referenced by SBParEditor::acquireData(), SBParEditor::browseData(), operator=(), SBParEditor::SBParEditor(), sinex_tro_TropDescriptionBlock(), and SBParameter::tuneParameter().
virtual double SBParameterCfg::tau () const [inline, virtual]
Definition at line 95 of file SbGeoParameter.H'.
References Tau.
Referenced by SBParEditor::acquireData(), SBParEditor::browseData(), operator=(), SBParEditor::SBParEditor(), and SBParameter::tuneParameter().
virtual PType SBParameterCfg::type () const [inline, virtual]
Definition at line 90 of file SbGeoParameter.H'.
References Type.
Referenced by SBParametersEditor::acquireData(), SBParametersEditor::browseData(), SBDelay::calc(), SBDelay::calcDerivatives(), SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), operator=(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), sinex_tro_TropDescriptionBlock(), SBParameter::tuneParameter(), SBParametersEditor::wEOPParameters(), SBParametersEditor::wOtherParameters(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), and SBParametersEditor::wTestParameters().
virtual double SBParameterCfg::whiteNoise () const [inline, virtual]
Definition at line 96 of file SbGeoParameter.H'.
References WhiteNoise.
Referenced by SBParEditor::acquireData(), SBParEditor::browseData(), SBStationInfo::dumpUserInfo(), operator=(), SBVLBIPreProcess::preProcess(), SBParEditor::SBParEditor(), sinex_tro_TropDescriptionBlock(), SBParameter::tuneParameter(), and SBVLBIPreProcess::wEstPars().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBParameterCfg &P) [friend]"Output to the data stream'.
Definition at line 108 of file SbGeoParameter.C'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBParameterCfg &P) [friend]"Input from the data stream'.
Definition at line 121 of file SbGeoParameter.C'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBParametersDesc &D) [related]"Input from the data stream'.
Definition at line 233 of file SbGeoParameter.C'.
References SBParametersDesc::num(), and SBParametersDesc::setPar().
Member Data Documentation
double SBParameterCfg::BreakNoise [private]
psd of noise process used for 'breaks'
Definition at line 64 of file SbGeoParameter.H'.
Referenced by breakNoise(), SBParameterCfg(), and setBreakNoise().
double SBParameterCfg::ConvAPriori [private]
a priori std'. deviation (conventional pars)
Definition at line 62 of file SbGeoParameter.H'.
Referenced by convAPriori(), SBParameterCfg(), and setConvAPriori().
bool SBParameterCfg::IsConstrained [private]
The parameter needs constrains'.
Definition at line 59 of file SbGeoParameter.H'.
Referenced by isConstrained(), SBParameterCfg(), and setConstrained().
bool SBParameterCfg::IsPropagated [private]
Propagate the parameter in time'. Some Comment:
Definition at line 58 of file SbGeoParameter.H'.
Referenced by isPropagated(), SBParameterCfg(), and setPropagated().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
double SBParameterCfg::Scale [private]
Value of the scale factor'.
Definition at line 67 of file SbGeoParameter.H'.
Referenced by SBParameterCfg(), scale(), and setScale().
QString SBParameterCfg::ScaleName [private]
Name of the scale factor'.
Definition at line 68 of file SbGeoParameter.H'.
Referenced by SBParameterCfg(), scaleName(), and setScaleName().
double SBParameterCfg::StocAPriori [private]
a priori std'. deviation (stochastic pars)
Definition at line 63 of file SbGeoParameter.H'.
Referenced by SBParameterCfg(), setStocAPriori(), and stocAPriori().
StochType SBParameterCfg::StochasticType [private]
Definition at line 61 of file SbGeoParameter.H'.
Referenced by SBParameterCfg(), setStochasticType(), and stochasticType().
double SBParameterCfg::Tau [private]
time of relaxation
Definition at line 65 of file SbGeoParameter.H'.
Referenced by SBParameterCfg(), setTau(), and tau().
PType SBParameterCfg::Type [private]
Definition at line 60 of file SbGeoParameter.H'.
Referenced by SBParameterCfg(), setType(), and type().
double SBParameterCfg::WhiteNoise [private]
psd of ruled white noise
Definition at line 66 of file SbGeoParameter.H'.
Referenced by SBParameterCfg(), setWhiteNoise(), and whiteNoise().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.