.TH "SBPlotBranchList" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBPlotBranchList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIPlot\&.H>\fP
.PP
Inherits \fBQList< SBPlotBranch >\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSBPlotBranch\fP * \fBfind\fP (const \fBSBNamed\fP *n)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item item1, QCollection::Item item2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file SbIPlot\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int SBPlotBranchList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 75 of file SbIPlot\&.H'\&.
.SS "virtual \fBSBPlotBranch\fP* SBPlotBranchList::find (const \fBSBNamed\fP *n)\fC [inline, virtual]\fP"
.PP
Definition at line 81 of file SbIPlot\&.H'\&.
.PP
Referenced by SBPlotCarrier::findBranch(), and SBFilteringGauss::redrawDataPlot_ExpMode()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
