SBPlot
NAME
SBPlot -
SYNOPSIS
#include <SbIPlot.H>
Inherits QWidget'.
Public Types
enum PlotMode { PM_HAS_HAVE_ZERO = 1<<0, PM_IMPULSE = 1<<1, PM_WO_BRANCH_NAMES = 1<<2, PM_WO_AXIS_NAMES = 1<<3, PM_WO_DOTS = 1<<4, PM_LINES = 1<<5 }
Public Member Functions
SBPlot (SBPlotCarrier *, QWidget *=0, unsigned int=0, const char *=0)
virtual ~SBPlot ()
void dataChanged ()
Protected Slots
void xAxisChanged (int)
void yAxisChanged (int)
void colorSChanged (int)
void colorVChanged (int)
void branchChanged ()
void DMPointsChanged (bool)
void DMLinesChanged (bool)
void DMErrBarsChanged (bool)
void DMImpulsesChanged (bool)
void ODataAllChanged (bool)
void OVisRang (bool)
void OWStdVar (bool)
void zoomIn ()
void zoomOut ()
void zoomXIn ()
void zoomXOut ()
void zoomYIn ()
void zoomYOut ()
void zoomNormalView ()
void save2File ()
void save2PS ()
Protected Member Functions
virtual QString ClassName () const
virtual void resizeEvent (QResizeEvent *)
QWidget * control ()
void fillAxisNames ()
void fillBranchesNames ()
Private Attributes
QScrollView * Plotter
SBPlotArea * Area
QFrame * Controls
double scaleX
double scaleY
unsigned int Modes
SBPlotCarrier * PlotCarrier
QComboBox * CBXAxis
QComboBox * CBYAxis
QListBox * LBBranches
QCheckBox * CBPoints
QCheckBox * CBLines
QCheckBox * CBErrBars
QCheckBox * CBImpulses
QCheckBox * CBAllData
QCheckBox * CBRangeVisible
QCheckBox * CBWStdVar
QPushButton * PBZommIn
QPushButton * PBZommOut
QPushButton * PBZommXIn
QPushButton * PBZommXOut
QPushButton * PBZommYIn
QPushButton * PBZommYOut
Static Private Attributes
static const double ScaleFactor = M_2_SQRTPI
Detailed Description
Definition at line 313 of file SbIPlot.H'.
Member Enumeration Documentation
enum SBPlot::PlotMode
Enumerator:
PM_HAS_HAVE_ZERO
PM_IMPULSE
PM_WO_BRANCH_NAMES
PM_WO_AXIS_NAMES
PM_WO_DOTS
PM_LINES
Definition at line 319 of file SbIPlot.H'.
Constructor & Destructor Documentation
SBPlot::SBPlot (SBPlotCarrier *PlotCarrier_, QWidget *parent = 0, unsigned intModes_ = 0, const char *name = 0)
Definition at line 1371 of file SbIPlot.C'.
References Area, ClassName(), control(), SBLog::DBG, SBLog::INTERFACE, Log, Modes, SBNamed::name(), PlotCarrier, Plotter, PM_HAS_HAVE_ZERO, scaleX, scaleY, SBPlotCarrier::selfCheck(), SBPlotArea::setIsHasHaveZero(), and SBLog::write().
SBPlot::~SBPlot () [virtual]
Definition at line 1398 of file SbIPlot.C'.
References Plotter.
Member Function Documentation
void SBPlot::branchChanged () [protected, slot]
Definition at line 1752 of file SbIPlot.C'.
References Area, SBPlotCarrier::branches(), LBBranches, and PlotCarrier.
Referenced by control().
virtual QString SBPlot::ClassName () const [inline, protected, virtual]
Definition at line 368 of file SbIPlot.H'.
Referenced by save2PS(), and SBPlot().
void SBPlot::colorSChanged (intn) [protected, slot]
Definition at line 1742 of file SbIPlot.C'.
References Area, and SBPlotArea::setBPSaturation().
Referenced by control().
void SBPlot::colorVChanged (intn) [protected, slot]
Definition at line 1747 of file SbIPlot.C'.
References Area, and SBPlotArea::setBPValue().
Referenced by control().
QWidget * SBPlot::control () [protected]
Definition at line 1414 of file SbIPlot.C'.
References branchChanged(), SBPlotCarrier::branches(), CBAllData, CBErrBars, CBImpulses, CBLines, CBPoints, CBRangeVisible, CBWStdVar, CBXAxis, CBYAxis, colorSChanged(), colorVChanged(), SBPlotCarrier::columnNames(), Controls, DMErrBarsChanged(), DMImpulsesChanged(), DMLinesChanged(), DMPointsChanged(), LBBranches, Modes, SBPlotCarrier::nCE(), SBPlotCarrier::nCV(), ODataAllChanged(), OVisRang(), OWStdVar(), PBZommIn, PBZommOut, PBZommXIn, PBZommXOut, PBZommYIn, PBZommYOut, PlotCarrier, PM_IMPULSE, PM_LINES, PM_WO_AXIS_NAMES, PM_WO_BRANCH_NAMES, PM_WO_DOTS, save2File(), save2PS(), xAxisChanged(), yAxisChanged(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), and zoomYOut().
Referenced by SBPlot().
void SBPlot::dataChanged ()
Definition at line 1722 of file SbIPlot.C'.
References Area, SBPlotArea::dataChanged(), fillAxisNames(), and fillBranchesNames().
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), SBFilteringGauss::redrawDataPlot(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBSpectrumAnalyserMEM::redrawFPEPlot(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBFilteringGauss::redrawTFPlot(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBPlot::DMErrBarsChanged (boolIs) [protected, slot]
Definition at line 1776 of file SbIPlot.C'.
References Area, and SBPlotArea::setIsPlotErrBars().
Referenced by control().
void SBPlot::DMImpulsesChanged (boolIs) [protected, slot]
Definition at line 1782 of file SbIPlot.C'.
References Area, and SBPlotArea::setIsPlotImpulses().
Referenced by control().
void SBPlot::DMLinesChanged (boolIs) [protected, slot]
Definition at line 1770 of file SbIPlot.C'.
References Area, and SBPlotArea::setIsPlotLines().
Referenced by control().
void SBPlot::DMPointsChanged (boolIs) [protected, slot]
Definition at line 1764 of file SbIPlot.C'.
References Area, and SBPlotArea::setIsPlotPoints().
Referenced by control().
void SBPlot::fillAxisNames () [protected]
Definition at line 1650 of file SbIPlot.C'.
References CBXAxis, CBYAxis, SBPlotCarrier::columnNames(), Modes, SBPlotCarrier::nCE(), SBPlotCarrier::nCV(), PlotCarrier, and PM_WO_AXIS_NAMES.
Referenced by dataChanged().
void SBPlot::fillBranchesNames () [protected]
Definition at line 1700 of file SbIPlot.C'.
References SBPlotCarrier::branches(), LBBranches, Modes, PlotCarrier, and PM_WO_BRANCH_NAMES.
Referenced by dataChanged().
void SBPlot::ODataAllChanged (boolIs) [protected, slot]
Definition at line 1788 of file SbIPlot.C'.
References Area, and SBPlotArea::setIsAllData().
Referenced by control().
void SBPlot::OVisRang (boolIs) [protected, slot]
Definition at line 1794 of file SbIPlot.C'.
References Area, and SBPlotArea::setIsLimitsOnVisible().
Referenced by control().
void SBPlot::OWStdVar (boolIs) [protected, slot]
Definition at line 1800 of file SbIPlot.C'.
References Area, and SBPlotArea::setIsStdVar().
Referenced by control().
void SBPlot::resizeEvent (QResizeEvent *ev) [protected, virtual]
Definition at line 1407 of file SbIPlot.C'.
References Area, Plotter, scaleX, and scaleY.
void SBPlot::save2File () [protected, slot]
Definition at line 1930 of file SbIPlot.C'.
References Area, and SBPlotArea::output4Files().
Referenced by control().
void SBPlot::save2PS () [protected, slot]
Definition at line 1935 of file SbIPlot.C'.
References Area, ClassName(), SBLog::DBG, SBPlotCarrier::file4SaveBaseName(), SBLog::IO, Log, SBNamed::name(), SBPlotArea::output4Print(), PlotCarrier, SBVersion::selfName(), SBVersion::toString(), Version, SBLog::write(), SBPlotArea::xCol(), and SBPlotArea::yCol().
Referenced by control().
void SBPlot::xAxisChanged (intn) [protected, slot]
Definition at line 1730 of file SbIPlot.C'.
References Area, and SBPlotArea::setXCol().
Referenced by control().
void SBPlot::yAxisChanged (intn) [protected, slot]
Definition at line 1736 of file SbIPlot.C'.
References Area, and SBPlotArea::setYCol().
Referenced by control().
void SBPlot::zoomIn () [protected, slot]
Definition at line 1826 of file SbIPlot.C'.
References Area, PBZommIn, PBZommOut, Plotter, ScaleFactor, scaleX, and scaleY.
Referenced by control().
void SBPlot::zoomNormalView () [protected, slot]
Definition at line 1806 of file SbIPlot.C'.
References Area, PBZommIn, PBZommOut, PBZommXIn, PBZommXOut, PBZommYIn, PBZommYOut, Plotter, scaleX, and scaleY.
Referenced by control().
void SBPlot::zoomOut () [protected, slot]
Definition at line 1844 of file SbIPlot.C'.
References Area, PBZommIn, PBZommOut, Plotter, ScaleFactor, scaleX, and scaleY.
Referenced by control().
void SBPlot::zoomXIn () [protected, slot]
Definition at line 1862 of file SbIPlot.C'.
References Area, PBZommXIn, PBZommXOut, Plotter, ScaleFactor, and scaleX.
Referenced by control().
void SBPlot::zoomXOut () [protected, slot]
Definition at line 1879 of file SbIPlot.C'.
References Area, PBZommXIn, PBZommXOut, Plotter, ScaleFactor, and scaleX.
Referenced by control().
void SBPlot::zoomYIn () [protected, slot]
Definition at line 1896 of file SbIPlot.C'.
References Area, PBZommYIn, PBZommYOut, Plotter, ScaleFactor, and scaleY.
Referenced by control().
void SBPlot::zoomYOut () [protected, slot]
Definition at line 1913 of file SbIPlot.C'.
References Area, PBZommYIn, PBZommYOut, Plotter, ScaleFactor, and scaleY.
Referenced by control().
Member Data Documentation
SBPlotArea* SBPlot::Area [private]
Definition at line 333 of file SbIPlot.H'.
Referenced by branchChanged(), colorSChanged(), colorVChanged(), dataChanged(), DMErrBarsChanged(), DMImpulsesChanged(), DMLinesChanged(), DMPointsChanged(), ODataAllChanged(), OVisRang(), OWStdVar(), resizeEvent(), save2File(), save2PS(), SBPlot(), xAxisChanged(), yAxisChanged(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), and zoomYOut().
QCheckBox* SBPlot::CBAllData [private]
Definition at line 351 of file SbIPlot.H'.
Referenced by control().
QCheckBox* SBPlot::CBErrBars [private]
Definition at line 348 of file SbIPlot.H'.
Referenced by control().
QCheckBox* SBPlot::CBImpulses [private]
Definition at line 349 of file SbIPlot.H'.
Referenced by control().
QCheckBox* SBPlot::CBLines [private]
Definition at line 347 of file SbIPlot.H'.
Referenced by control().
QCheckBox* SBPlot::CBPoints [private]
Definition at line 346 of file SbIPlot.H'.
Referenced by control().
QCheckBox* SBPlot::CBRangeVisible [private]
Definition at line 352 of file SbIPlot.H'.
Referenced by control().
QCheckBox* SBPlot::CBWStdVar [private]
Definition at line 353 of file SbIPlot.H'.
Referenced by control().
QComboBox* SBPlot::CBXAxis [private]
Definition at line 342 of file SbIPlot.H'.
Referenced by control(), and fillAxisNames().
QComboBox* SBPlot::CBYAxis [private]
Definition at line 343 of file SbIPlot.H'.
Referenced by control(), and fillAxisNames().
QFrame* SBPlot::Controls [private]
Definition at line 334 of file SbIPlot.H'.
Referenced by control().
QListBox* SBPlot::LBBranches [private]
Definition at line 344 of file SbIPlot.H'.
Referenced by branchChanged(), control(), and fillBranchesNames().
unsigned int SBPlot::Modes [private]
Definition at line 338 of file SbIPlot.H'.
Referenced by control(), fillAxisNames(), fillBranchesNames(), and SBPlot().
QPushButton* SBPlot::PBZommIn [private]
Definition at line 355 of file SbIPlot.H'.
Referenced by control(), zoomIn(), zoomNormalView(), and zoomOut().
QPushButton* SBPlot::PBZommOut [private]
Definition at line 356 of file SbIPlot.H'.
Referenced by control(), zoomIn(), zoomNormalView(), and zoomOut().
QPushButton* SBPlot::PBZommXIn [private]
Definition at line 357 of file SbIPlot.H'.
Referenced by control(), zoomNormalView(), zoomXIn(), and zoomXOut().
QPushButton* SBPlot::PBZommXOut [private]
Definition at line 358 of file SbIPlot.H'.
Referenced by control(), zoomNormalView(), zoomXIn(), and zoomXOut().
QPushButton* SBPlot::PBZommYIn [private]
Definition at line 359 of file SbIPlot.H'.
Referenced by control(), zoomNormalView(), zoomYIn(), and zoomYOut().
QPushButton* SBPlot::PBZommYOut [private]
Definition at line 360 of file SbIPlot.H'.
Referenced by control(), zoomNormalView(), zoomYIn(), and zoomYOut().
SBPlotCarrier* SBPlot::PlotCarrier [private]
Definition at line 339 of file SbIPlot.H'.
Referenced by branchChanged(), control(), fillAxisNames(), fillBranchesNames(), save2PS(), and SBPlot().
QScrollView* SBPlot::Plotter [private]
Definition at line 332 of file SbIPlot.H'.
Referenced by resizeEvent(), SBPlot(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), zoomYOut(), and ~SBPlot().
const double SBPlot::ScaleFactor = M_2_SQRTPI [static, private]
Definition at line 331 of file SbIPlot.H'.
Referenced by zoomIn(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), and zoomYOut().
double SBPlot::scaleX [private]
Definition at line 335 of file SbIPlot.H'.
Referenced by resizeEvent(), SBPlot(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), and zoomXOut().
double SBPlot::scaleY [private]
Definition at line 336 of file SbIPlot.H'.
Referenced by resizeEvent(), SBPlot(), zoomIn(), zoomNormalView(), zoomOut(), zoomYIn(), and zoomYOut().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.