.TH "SBPlot" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBPlot \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIPlot\&.H>\fP
.PP
Inherits \fBQWidget\fP'\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPlotMode\fP { \fBPM_HAS_HAVE_ZERO\fP =  1<<0, \fBPM_IMPULSE\fP =  1<<1, \fBPM_WO_BRANCH_NAMES\fP =  1<<2, \fBPM_WO_AXIS_NAMES\fP =  1<<3, \fBPM_WO_DOTS\fP =  1<<4, \fBPM_LINES\fP =  1<<5 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBPlot\fP (\fBSBPlotCarrier\fP *, \fBQWidget\fP *=0, unsigned int=0, const char *=0)"
.br
.ti -1c
.RI "virtual \fB~SBPlot\fP ()"
.br
.ti -1c
.RI "void \fBdataChanged\fP ()"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBxAxisChanged\fP (int)"
.br
.ti -1c
.RI "void \fByAxisChanged\fP (int)"
.br
.ti -1c
.RI "void \fBcolorSChanged\fP (int)"
.br
.ti -1c
.RI "void \fBcolorVChanged\fP (int)"
.br
.ti -1c
.RI "void \fBbranchChanged\fP ()"
.br
.ti -1c
.RI "void \fBDMPointsChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBDMLinesChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBDMErrBarsChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBDMImpulsesChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBODataAllChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBOVisRang\fP (bool)"
.br
.ti -1c
.RI "void \fBOWStdVar\fP (bool)"
.br
.ti -1c
.RI "void \fBzoomIn\fP ()"
.br
.ti -1c
.RI "void \fBzoomOut\fP ()"
.br
.ti -1c
.RI "void \fBzoomXIn\fP ()"
.br
.ti -1c
.RI "void \fBzoomXOut\fP ()"
.br
.ti -1c
.RI "void \fBzoomYIn\fP ()"
.br
.ti -1c
.RI "void \fBzoomYOut\fP ()"
.br
.ti -1c
.RI "void \fBzoomNormalView\fP ()"
.br
.ti -1c
.RI "void \fBsave2File\fP ()"
.br
.ti -1c
.RI "void \fBsave2PS\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual void \fBresizeEvent\fP (QResizeEvent *)"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBcontrol\fP ()"
.br
.ti -1c
.RI "void \fBfillAxisNames\fP ()"
.br
.ti -1c
.RI "void \fBfillBranchesNames\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QScrollView * \fBPlotter\fP"
.br
.ti -1c
.RI "\fBSBPlotArea\fP * \fBArea\fP"
.br
.ti -1c
.RI "QFrame * \fBControls\fP"
.br
.ti -1c
.RI "double \fBscaleX\fP"
.br
.ti -1c
.RI "double \fBscaleY\fP"
.br
.ti -1c
.RI "unsigned int \fBModes\fP"
.br
.ti -1c
.RI "\fBSBPlotCarrier\fP * \fBPlotCarrier\fP"
.br
.ti -1c
.RI "QComboBox * \fBCBXAxis\fP"
.br
.ti -1c
.RI "QComboBox * \fBCBYAxis\fP"
.br
.ti -1c
.RI "QListBox * \fBLBBranches\fP"
.br
.ti -1c
.RI "QCheckBox * \fBCBPoints\fP"
.br
.ti -1c
.RI "QCheckBox * \fBCBLines\fP"
.br
.ti -1c
.RI "QCheckBox * \fBCBErrBars\fP"
.br
.ti -1c
.RI "QCheckBox * \fBCBImpulses\fP"
.br
.ti -1c
.RI "QCheckBox * \fBCBAllData\fP"
.br
.ti -1c
.RI "QCheckBox * \fBCBRangeVisible\fP"
.br
.ti -1c
.RI "QCheckBox * \fBCBWStdVar\fP"
.br
.ti -1c
.RI "QPushButton * \fBPBZommIn\fP"
.br
.ti -1c
.RI "QPushButton * \fBPBZommOut\fP"
.br
.ti -1c
.RI "QPushButton * \fBPBZommXIn\fP"
.br
.ti -1c
.RI "QPushButton * \fBPBZommXOut\fP"
.br
.ti -1c
.RI "QPushButton * \fBPBZommYIn\fP"
.br
.ti -1c
.RI "QPushButton * \fBPBZommYOut\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static const double \fBScaleFactor\fP = M_2_SQRTPI"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 313 of file SbIPlot\&.H'\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSBPlot::PlotMode\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIPM_HAS_HAVE_ZERO \fP\fP
.TP
\fB\fIPM_IMPULSE \fP\fP
.TP
\fB\fIPM_WO_BRANCH_NAMES \fP\fP
.TP
\fB\fIPM_WO_AXIS_NAMES \fP\fP
.TP
\fB\fIPM_WO_DOTS \fP\fP
.TP
\fB\fIPM_LINES \fP\fP

.PP
Definition at line 319 of file SbIPlot\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBPlot::SBPlot (\fBSBPlotCarrier\fP *PlotCarrier_, \fBQWidget\fP *parent = \fC0\fP, unsigned intModes_ = \fC0\fP, const char *name = \fC0\fP)"
.PP
Definition at line 1371 of file SbIPlot\&.C'\&.
.PP
References Area, ClassName(), control(), SBLog::DBG, SBLog::INTERFACE, Log, Modes, SBNamed::name(), PlotCarrier, Plotter, PM_HAS_HAVE_ZERO, scaleX, scaleY, SBPlotCarrier::selfCheck(), SBPlotArea::setIsHasHaveZero(), and SBLog::write()\&.
.SS "SBPlot::~SBPlot ()\fC [virtual]\fP"
.PP
Definition at line 1398 of file SbIPlot\&.C'\&.
.PP
References Plotter\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBPlot::branchChanged ()\fC [protected, slot]\fP"
.PP
Definition at line 1752 of file SbIPlot\&.C'\&.
.PP
References Area, SBPlotCarrier::branches(), LBBranches, and PlotCarrier\&.
.PP
Referenced by control()\&.
.SS "virtual QString SBPlot::ClassName () const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 368 of file SbIPlot\&.H'\&.
.PP
Referenced by save2PS(), and SBPlot()\&.
.SS "void SBPlot::colorSChanged (intn)\fC [protected, slot]\fP"
.PP
Definition at line 1742 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setBPSaturation()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::colorVChanged (intn)\fC [protected, slot]\fP"
.PP
Definition at line 1747 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setBPValue()\&.
.PP
Referenced by control()\&.
.SS "\fBQWidget\fP * SBPlot::control ()\fC [protected]\fP"
.PP
Definition at line 1414 of file SbIPlot\&.C'\&.
.PP
References branchChanged(), SBPlotCarrier::branches(), CBAllData, CBErrBars, CBImpulses, CBLines, CBPoints, CBRangeVisible, CBWStdVar, CBXAxis, CBYAxis, colorSChanged(), colorVChanged(), SBPlotCarrier::columnNames(), Controls, DMErrBarsChanged(), DMImpulsesChanged(), DMLinesChanged(), DMPointsChanged(), LBBranches, Modes, SBPlotCarrier::nCE(), SBPlotCarrier::nCV(), ODataAllChanged(), OVisRang(), OWStdVar(), PBZommIn, PBZommOut, PBZommXIn, PBZommXOut, PBZommYIn, PBZommYOut, PlotCarrier, PM_IMPULSE, PM_LINES, PM_WO_AXIS_NAMES, PM_WO_BRANCH_NAMES, PM_WO_DOTS, save2File(), save2PS(), xAxisChanged(), yAxisChanged(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), and zoomYOut()\&.
.PP
Referenced by SBPlot()\&.
.SS "void SBPlot::dataChanged ()"
.PP
Definition at line 1722 of file SbIPlot\&.C'\&.
.PP
References Area, SBPlotArea::dataChanged(), fillAxisNames(), and fillBranchesNames()\&.
.PP
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), SBFilteringGauss::redrawDataPlot(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBSpectrumAnalyserMEM::redrawFPEPlot(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBFilteringGauss::redrawTFPlot(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession()\&.
.SS "void SBPlot::DMErrBarsChanged (boolIs)\fC [protected, slot]\fP"
.PP
Definition at line 1776 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setIsPlotErrBars()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::DMImpulsesChanged (boolIs)\fC [protected, slot]\fP"
.PP
Definition at line 1782 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setIsPlotImpulses()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::DMLinesChanged (boolIs)\fC [protected, slot]\fP"
.PP
Definition at line 1770 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setIsPlotLines()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::DMPointsChanged (boolIs)\fC [protected, slot]\fP"
.PP
Definition at line 1764 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setIsPlotPoints()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::fillAxisNames ()\fC [protected]\fP"
.PP
Definition at line 1650 of file SbIPlot\&.C'\&.
.PP
References CBXAxis, CBYAxis, SBPlotCarrier::columnNames(), Modes, SBPlotCarrier::nCE(), SBPlotCarrier::nCV(), PlotCarrier, and PM_WO_AXIS_NAMES\&.
.PP
Referenced by dataChanged()\&.
.SS "void SBPlot::fillBranchesNames ()\fC [protected]\fP"
.PP
Definition at line 1700 of file SbIPlot\&.C'\&.
.PP
References SBPlotCarrier::branches(), LBBranches, Modes, PlotCarrier, and PM_WO_BRANCH_NAMES\&.
.PP
Referenced by dataChanged()\&.
.SS "void SBPlot::ODataAllChanged (boolIs)\fC [protected, slot]\fP"
.PP
Definition at line 1788 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setIsAllData()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::OVisRang (boolIs)\fC [protected, slot]\fP"
.PP
Definition at line 1794 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setIsLimitsOnVisible()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::OWStdVar (boolIs)\fC [protected, slot]\fP"
.PP
Definition at line 1800 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setIsStdVar()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::resizeEvent (QResizeEvent *ev)\fC [protected, virtual]\fP"
.PP
Definition at line 1407 of file SbIPlot\&.C'\&.
.PP
References Area, Plotter, scaleX, and scaleY\&.
.SS "void SBPlot::save2File ()\fC [protected, slot]\fP"
.PP
Definition at line 1930 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::output4Files()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::save2PS ()\fC [protected, slot]\fP"
.PP
Definition at line 1935 of file SbIPlot\&.C'\&.
.PP
References Area, ClassName(), SBLog::DBG, SBPlotCarrier::file4SaveBaseName(), SBLog::IO, Log, SBNamed::name(), SBPlotArea::output4Print(), PlotCarrier, SBVersion::selfName(), SBVersion::toString(), Version, SBLog::write(), SBPlotArea::xCol(), and SBPlotArea::yCol()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::xAxisChanged (intn)\fC [protected, slot]\fP"
.PP
Definition at line 1730 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setXCol()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::yAxisChanged (intn)\fC [protected, slot]\fP"
.PP
Definition at line 1736 of file SbIPlot\&.C'\&.
.PP
References Area, and SBPlotArea::setYCol()\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::zoomIn ()\fC [protected, slot]\fP"
.PP
Definition at line 1826 of file SbIPlot\&.C'\&.
.PP
References Area, PBZommIn, PBZommOut, Plotter, ScaleFactor, scaleX, and scaleY\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::zoomNormalView ()\fC [protected, slot]\fP"
.PP
Definition at line 1806 of file SbIPlot\&.C'\&.
.PP
References Area, PBZommIn, PBZommOut, PBZommXIn, PBZommXOut, PBZommYIn, PBZommYOut, Plotter, scaleX, and scaleY\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::zoomOut ()\fC [protected, slot]\fP"
.PP
Definition at line 1844 of file SbIPlot\&.C'\&.
.PP
References Area, PBZommIn, PBZommOut, Plotter, ScaleFactor, scaleX, and scaleY\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::zoomXIn ()\fC [protected, slot]\fP"
.PP
Definition at line 1862 of file SbIPlot\&.C'\&.
.PP
References Area, PBZommXIn, PBZommXOut, Plotter, ScaleFactor, and scaleX\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::zoomXOut ()\fC [protected, slot]\fP"
.PP
Definition at line 1879 of file SbIPlot\&.C'\&.
.PP
References Area, PBZommXIn, PBZommXOut, Plotter, ScaleFactor, and scaleX\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::zoomYIn ()\fC [protected, slot]\fP"
.PP
Definition at line 1896 of file SbIPlot\&.C'\&.
.PP
References Area, PBZommYIn, PBZommYOut, Plotter, ScaleFactor, and scaleY\&.
.PP
Referenced by control()\&.
.SS "void SBPlot::zoomYOut ()\fC [protected, slot]\fP"
.PP
Definition at line 1913 of file SbIPlot\&.C'\&.
.PP
References Area, PBZommYIn, PBZommYOut, Plotter, ScaleFactor, and scaleY\&.
.PP
Referenced by control()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBPlotArea\fP* \fBSBPlot::Area\fP\fC [private]\fP"
.PP
Definition at line 333 of file SbIPlot\&.H'\&.
.PP
Referenced by branchChanged(), colorSChanged(), colorVChanged(), dataChanged(), DMErrBarsChanged(), DMImpulsesChanged(), DMLinesChanged(), DMPointsChanged(), ODataAllChanged(), OVisRang(), OWStdVar(), resizeEvent(), save2File(), save2PS(), SBPlot(), xAxisChanged(), yAxisChanged(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), and zoomYOut()\&.
.SS "QCheckBox* \fBSBPlot::CBAllData\fP\fC [private]\fP"
.PP
Definition at line 351 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QCheckBox* \fBSBPlot::CBErrBars\fP\fC [private]\fP"
.PP
Definition at line 348 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QCheckBox* \fBSBPlot::CBImpulses\fP\fC [private]\fP"
.PP
Definition at line 349 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QCheckBox* \fBSBPlot::CBLines\fP\fC [private]\fP"
.PP
Definition at line 347 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QCheckBox* \fBSBPlot::CBPoints\fP\fC [private]\fP"
.PP
Definition at line 346 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QCheckBox* \fBSBPlot::CBRangeVisible\fP\fC [private]\fP"
.PP
Definition at line 352 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QCheckBox* \fBSBPlot::CBWStdVar\fP\fC [private]\fP"
.PP
Definition at line 353 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QComboBox* \fBSBPlot::CBXAxis\fP\fC [private]\fP"
.PP
Definition at line 342 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), and fillAxisNames()\&.
.SS "QComboBox* \fBSBPlot::CBYAxis\fP\fC [private]\fP"
.PP
Definition at line 343 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), and fillAxisNames()\&.
.SS "QFrame* \fBSBPlot::Controls\fP\fC [private]\fP"
.PP
Definition at line 334 of file SbIPlot\&.H'\&.
.PP
Referenced by control()\&.
.SS "QListBox* \fBSBPlot::LBBranches\fP\fC [private]\fP"
.PP
Definition at line 344 of file SbIPlot\&.H'\&.
.PP
Referenced by branchChanged(), control(), and fillBranchesNames()\&.
.SS "unsigned int \fBSBPlot::Modes\fP\fC [private]\fP"
.PP
Definition at line 338 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), fillAxisNames(), fillBranchesNames(), and SBPlot()\&.
.SS "QPushButton* \fBSBPlot::PBZommIn\fP\fC [private]\fP"
.PP
Definition at line 355 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), zoomIn(), zoomNormalView(), and zoomOut()\&.
.SS "QPushButton* \fBSBPlot::PBZommOut\fP\fC [private]\fP"
.PP
Definition at line 356 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), zoomIn(), zoomNormalView(), and zoomOut()\&.
.SS "QPushButton* \fBSBPlot::PBZommXIn\fP\fC [private]\fP"
.PP
Definition at line 357 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), zoomNormalView(), zoomXIn(), and zoomXOut()\&.
.SS "QPushButton* \fBSBPlot::PBZommXOut\fP\fC [private]\fP"
.PP
Definition at line 358 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), zoomNormalView(), zoomXIn(), and zoomXOut()\&.
.SS "QPushButton* \fBSBPlot::PBZommYIn\fP\fC [private]\fP"
.PP
Definition at line 359 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), zoomNormalView(), zoomYIn(), and zoomYOut()\&.
.SS "QPushButton* \fBSBPlot::PBZommYOut\fP\fC [private]\fP"
.PP
Definition at line 360 of file SbIPlot\&.H'\&.
.PP
Referenced by control(), zoomNormalView(), zoomYIn(), and zoomYOut()\&.
.SS "\fBSBPlotCarrier\fP* \fBSBPlot::PlotCarrier\fP\fC [private]\fP"
.PP
Definition at line 339 of file SbIPlot\&.H'\&.
.PP
Referenced by branchChanged(), control(), fillAxisNames(), fillBranchesNames(), save2PS(), and SBPlot()\&.
.SS "QScrollView* \fBSBPlot::Plotter\fP\fC [private]\fP"
.PP
Definition at line 332 of file SbIPlot\&.H'\&.
.PP
Referenced by resizeEvent(), SBPlot(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), zoomYOut(), and ~SBPlot()\&.
.SS "const double \fBSBPlot::ScaleFactor\fP = M_2_SQRTPI\fC [static, private]\fP"
.PP
Definition at line 331 of file SbIPlot\&.H'\&.
.PP
Referenced by zoomIn(), zoomOut(), zoomXIn(), zoomXOut(), zoomYIn(), and zoomYOut()\&.
.SS "double \fBSBPlot::scaleX\fP\fC [private]\fP"
.PP
Definition at line 335 of file SbIPlot\&.H'\&.
.PP
Referenced by resizeEvent(), SBPlot(), zoomIn(), zoomNormalView(), zoomOut(), zoomXIn(), and zoomXOut()\&.
.SS "double \fBSBPlot::scaleY\fP\fC [private]\fP"
.PP
Definition at line 336 of file SbIPlot\&.H'\&.
.PP
Referenced by resizeEvent(), SBPlot(), zoomIn(), zoomNormalView(), zoomOut(), zoomYIn(), and zoomYOut()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
