SBPlotDialog
NAME
SBPlotDialog -
SYNOPSIS
#include <SbIPlot.H>
Inherits QDialog'.
Signals
void windowClosed ()
Public Member Functions
SBPlotDialog (SBPlotCarrier *, bool=FALSE, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBPlotDialog ()
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Slots
void accept ()
Private Attributes
bool IsNeedDeletePC
SBPlotCarrier * Carrier
SBPlot * Plot
Detailed Description
Definition at line 414 of file SbIPlot.H'.
Constructor & Destructor Documentation
SBPlotDialog::SBPlotDialog (SBPlotCarrier *Carrier_, boolIsNeedDeletePC_ = FALSE, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1973 of file SbIPlot.C'.
References accept(), Carrier, IsNeedDeletePC, SBNamed::name(), and Plot.
SBPlotDialog::~SBPlotDialog () [virtual]
Definition at line 2019 of file SbIPlot.C'.
References Carrier, IsNeedDeletePC, Plot, and windowClosed().
Member Function Documentation
void SBPlotDialog::accept () [private, slot]
Definition at line 2036 of file SbIPlot.C'.
Referenced by SBPlotDialog().
virtual QString SBPlotDialog::ClassName () const [inline, virtual]
Definition at line 421 of file SbIPlot.H'.
virtual void SBPlotDialog::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 432 of file SbIPlot.H'.
void SBPlotDialog::windowClosed () [signal]
Definition at line 347 of file SbIPlot.moc.C'.
Referenced by ~SBPlotDialog().
Member Data Documentation
SBPlotCarrier* SBPlotDialog::Carrier [private]
Definition at line 436 of file SbIPlot.H'.
Referenced by SBPlotDialog(), and ~SBPlotDialog().
bool SBPlotDialog::IsNeedDeletePC [private]
Definition at line 432 of file SbIPlot.H'.
Referenced by SBPlotDialog(), and ~SBPlotDialog().
SBPlot* SBPlotDialog::Plot [private]
Definition at line 437 of file SbIPlot.H'.
Referenced by SBPlotDialog(), and ~SBPlotDialog().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.