SBPlateMotion
NAME
SBPlateMotion -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBNList'.
Inherited by SBPMNNR_NUVEL1A, and SBPMNUVEL1A'.
Public Member Functions
SBPlateMotion (const SBPlateEntry[]=NULL, int=0)
virtual ~SBPlateMotion ()
virtual Vector3 operator() (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const
virtual Vector3 velocity (SBStation &Station) const
virtual QString modelName () const
Protected Member Functions
virtual QString ClassName () const
virtual Vector3 displacement (const SBMJD &, const SBMJD &, SBStation &) const
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Protected Attributes
int N
const SBPlateEntry * Plates
QDict< SBPlateEntry > * PlDict
Detailed Description
Definition at line 239 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBPlateMotion::SBPlateMotion (const SBPlateEntryMod_[] = NULL, intN_ = 0)
Definition at line 218 of file SbGeoStations.C'.
References N, SBNamed::name(), Plates, and PlDict.
SBPlateMotion::~SBPlateMotion () [virtual]
Definition at line 229 of file SbGeoStations.C'.
References PlDict.
Member Function Documentation
virtual QString SBPlateMotion::ClassName () const [inline, protected, virtual]
Reimplemented in SBPMNNR_NUVEL1A, and SBPMNUVEL1A'.
Definition at line 245 of file SbGeoStations.H'.
Referenced by displacement(), and velocity().
virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, and SBStationIDList'.
Definition at line 277 of file SbGeo.H'.
Vector3 SBPlateMotion::displacement (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const [protected, virtual]
Definition at line 234 of file SbGeoStations.C'.
References Vector3::at(), ClassName(), SBLog::DBG, SBPlateEntry::displacement(), SBLog::ERR, SBStation::id(), SBLog::isEligible(), Log, SBNamed::name(), SBSite::plate(), SBLog::PLATES, PlDict, SBStation::rt(), SBStation::site(), SBStationID::toString(), v3Zero, SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by operator()(), SBPMNUVEL1A::operator()(), and SBPMNNR_NUVEL1A::operator()().
virtual QString SBPlateMotion::modelName () const [inline, virtual]
Reimplemented in SBPMNNR_NUVEL1A, and SBPMNUVEL1A'.
Definition at line 256 of file SbGeoStations.H'.
Referenced by SBRunManager::constraintStationVeloc().
virtual Vector3 SBPlateMotion::operator() (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const [inline, virtual]"Calculates station's displacement due to plate motion'. This is a fake entry, returns zero displacement, (0,0,0)'.
Reimplemented in SBPMNNR_NUVEL1A, and SBPMNUVEL1A'.
Definition at line 253 of file SbGeoStations.H'.
References displacement().
virtual QDataStream& SBNList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 284 of file SbGeo.H'.
Vector3 SBPlateMotion::velocity (SBStation &Station) const [virtual]
Reimplemented in SBPMNNR_NUVEL1A, and SBPMNUVEL1A'.
Definition at line 268 of file SbGeoStations.C'.
References Vector3::at(), ClassName(), SBLog::DBG, SBLog::ERR, SBStation::id(), SBLog::isEligible(), Log, SBNamed::name(), SBSite::plate(), SBLog::PLATES, PlDict, SBStation::r_first(), SBStation::site(), SBStationID::toString(), v3Zero, SBPlateEntry::velocity(), SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBStation::calcDisplacement(), SBRunManager::constraintStationVeloc(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBRunManager::makeReportMaps(), and SBStation::vModel().
virtual QDataStream& SBNList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 282 of file SbGeo.H'.
Member Data Documentation
int SBPlateMotion::N [protected]
Definition at line 242 of file SbGeoStations.H'.
Referenced by SBPlateMotion().
const SBPlateEntry* SBPlateMotion::Plates [protected]
Definition at line 243 of file SbGeoStations.H'.
Referenced by SBPlateMotion().
QDict<SBPlateEntry>* SBPlateMotion::PlDict [protected]
Definition at line 244 of file SbGeoStations.H'.
Referenced by displacement(), SBPlateMotion(), velocity(), and ~SBPlateMotion().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.