SBPlotCarrier
NAME
SBPlotCarrier -
SYNOPSIS
#include <SbIPlot.H>
Inherits SBNamed'.
Public Types
enum AxisType { AT_DATA = 0, AT_MJD = 1 }
enum DataAttr { DA_IGN = 1<<0, DA_BAR = 1<<1 }
Public Member Functions
SBPlotCarrier (unsigned int, unsigned int, const QString &)
~SBPlotCarrier ()
void createBranch (unsigned int, const QString &)
void setType (unsigned int NC_, AxisType Type_)
AxisType type (unsigned int NC_) const
void setStdVarIdx (unsigned int NC_, unsigned int StdErr_)
unsigned int stdVarIdx (unsigned int NC_) const
void setAttr (unsigned int NC_, int Attr_)
SBPlotBranchList * branches ()
SBPlotBranch * findBranch (const QString &Name_)
QList< QString > * columnNames ()
bool selfCheck ()
bool isOK () const
unsigned int numOfCols () const
unsigned int nCV () const
unsigned int nCE () const
const QString & file4SaveBaseName () const
void setFile4SaveBaseName (const QString &)
void setAbsFile4SaveBaseName (const QString &)
virtual QString ClassName () const
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
QString Name
Private Attributes
SBPlotBranchList Branches
unsigned int NCV
unsigned int NCE
QList< QString > * ColumnNames
int * DatTypes
unsigned int * DatStdVarIdx
unsigned int * DatAttr
QString File4SaveBaseName
bool IsOK
Friends
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Definition at line 96 of file SbIPlot.H'.
Member Enumeration Documentation
enum SBPlotCarrier::AxisType
Enumerator:
AT_DATA
AT_MJD
Definition at line 100 of file SbIPlot.H'.
enum SBPlotCarrier::DataAttr
Enumerator:
DA_IGN
DA_BAR
Definition at line 102 of file SbIPlot.H'.
Constructor & Destructor Documentation
SBPlotCarrier::SBPlotCarrier (unsigned intNCV_, unsigned intNCE_, const QString &Name_)
Definition at line 86 of file SbIPlot.C'.
References AT_DATA, Branches, ColumnNames, DatAttr, DatStdVarIdx, DatTypes, File4SaveBaseName, IsOK, NCE, NCV, SBSetUp::path2Output(), and SetUp.
SBPlotCarrier::~SBPlotCarrier ()
Definition at line 110 of file SbIPlot.C'.
References ColumnNames, DatAttr, DatStdVarIdx, and DatTypes.
Member Function Documentation
SBPlotBranchList* SBPlotCarrier::branches () [inline]
Definition at line 138 of file SbIPlot.H'.
References Branches.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBPlot::branchChanged(), SBPlot::control(), SBVLBIPreProcess::currentSesChange(), SBStuffEOPs::draw(), SBStuffAplo::draw(), SBPlotArea::drawData(), SBPlot::fillBranchesNames(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBPlotArea::getLimits(), SBPlotArea::initBranchPens(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBSpectrumAnalyserMEM::redrawFPEPlot(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBFilteringGauss::redrawTFPlot(), SBPlotArea::setBranchColors(), SBVLBIPreProcess::updateSession(), SBFilteringGauss::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseSpectrum(), SBFilteringGauss::wBrowseTF(), SBSolutionBrowser::wLocalEOPPars(), SBSpectrumAnalyserMEM::wMEMCoeffList(), SBFilteringGauss::wrote2File(), and SBSolutionBrowser::wWRMSs().
virtual QString SBNamed::ClassName () const [inline, virtual, inherited]
Reimplemented in SBOLoadCarrier, SBGravTideEOP_B_02, SBNonTideEOP_Viron_02, SBMasterFile, SBATideEOP_BBP_02, SBMasterRecord, SBOTideEOPRay1994_2003, SBOTideEOPRay1994_1996, SBNROThIAU2000A, SBVLBISession, SBSymMatrix, SBNutThIAU2000A, SBNROThIAU1996, SBSite, SBNutThIAU1996, SBNROThIAU1980, SBVLBISesInfo, SBNutThIAU1980, SBFrameNRO, SBFrameClassic, SBStatistics, SBFrame, SBUpperMatrix, SBStochParameter, SBStation, SBSourceInfo, SBParameter, SBBaseInfo, SBAploSiteAmpl, SBProject, SBObsVLBIStatistics, SBDerivation, SBAploWaveAmpls, SBMatrix, SBInstitution, SBEphemDE405, SBEphemDE403, SBObsVLBIStatStation, SBAploWave, SBEphemDE200, SBPlateEntry, SBOTideEOPGenS, SBOTideEOPGeneral, SBObsVLBIStatSource, SBSource, SBEphem, SBAploEntry, SBNROThGeneral, SBSINEXParameter, SBVector, SBParameterCfg, SBFileConv, SBCelestBody, SBObsVLBIStatRecord, and SBNutThGeneral'.
Definition at line 211 of file SbGeo.H'.
Referenced by selfCheck().
QList<QString>* SBPlotCarrier::columnNames () [inline]
Definition at line 140 of file SbIPlot.H'.
References ColumnNames.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBPlot::control(), SBStuffEOPs::draw(), SBStuffAplo::draw(), SBPlot::fillAxisNames(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBIPreProcess::SBVLBIPreProcess(), SBVLBISessionEditor::SBVLBISessionEditor(), SBPlotArea::setXCol(), SBPlotArea::setYCol(), SBFilteringGauss::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseSpectrum(), SBFilteringGauss::wBrowseTF(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBSpectrumAnalyserMEM::wMEMCoeffList(), and SBSolutionBrowser::wWRMSs().
void SBPlotCarrier::createBranch (unsigned intNR_, const QString &BranchName)
Definition at line 134 of file SbIPlot.C'.
References Branches, NCE, and NCV.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBVLBIPreProcess::currentSesChange(), SBStuffEOPs::draw(), SBStuffAplo::draw(), SBFilteringGauss::redrawDataPlot(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBSpectrumAnalyserMEM::redrawFPEPlot(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::updateSession(), SBFilteringGauss::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseSpectrum(), SBFilteringGauss::wBrowseTF(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBSpectrumAnalyserMEM::wMEMCoeffList(), and SBSolutionBrowser::wWRMSs().
const QString& SBPlotCarrier::file4SaveBaseName () const [inline]
Definition at line 148 of file SbIPlot.H'.
References File4SaveBaseName.
Referenced by SBPlotArea::output4Files(), and SBPlot::save2PS().
SBPlotBranch* SBPlotCarrier::findBranch (const QString &Name_) [inline]
Definition at line 139 of file SbIPlot.H'.
References Branches, and SBPlotBranchList::find().
Referenced by SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBSpectrumAnalyserMEM::checkLine(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBVLBIPreProcess::fillObsListView(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), and SBVLBISessionEditor::wObservs().
bool SBPlotCarrier::isOK () const [inline]
Definition at line 142 of file SbIPlot.H'.
References IsOK.
Referenced by SBPlotArea::drawData(), SBPlotArea::getLimits(), SBPlotArea::setXCol(), and SBPlotArea::setYCol().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
unsigned int SBPlotCarrier::nCE () const [inline]
Definition at line 146 of file SbIPlot.H'.
References NCE.
Referenced by SBPlot::control(), and SBPlot::fillAxisNames().
unsigned int SBPlotCarrier::nCV () const [inline]
Definition at line 145 of file SbIPlot.H'.
References NCV.
Referenced by SBPlot::control(), and SBPlot::fillAxisNames().
unsigned int SBPlotCarrier::numOfCols () const [inline]
Definition at line 144 of file SbIPlot.H'.
References NCE, and NCV.
Referenced by SBPlotArea::setXCol(), and SBPlotArea::setYCol().
bool SBPlotCarrier::selfCheck ()
Definition at line 140 of file SbIPlot.C'.
References Branches, SBNamed::ClassName(), SBLog::DBG, SBLog::IO, IsOK, Log, and SBLog::write().
Referenced by SBPlot::SBPlot().
void SBPlotCarrier::setAbsFile4SaveBaseName (const QString &AbsFile4SaveBaseName_)
Definition at line 158 of file SbIPlot.C'.
References File4SaveBaseName.
Referenced by SBFilteringGauss::redrawDataPlot(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBSpectrumAnalyserMEM::redrawFPEPlot(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBFilteringGauss::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseSpectrum(), SBFilteringGauss::wBrowseTF(), and SBSpectrumAnalyserMEM::wMEMCoeffList().
void SBPlotCarrier::setAttr (unsigned intNC_, intAttr_) [inline]
Definition at line 135 of file SbIPlot.H'.
References DatAttr, and NCV.
void SBPlotCarrier::setFile4SaveBaseName (const QString &File4SaveBaseName_)
Definition at line 153 of file SbIPlot.C'.
References File4SaveBaseName, SBSetUp::path2Output(), and SetUp.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBVLBIPreProcess::currentSesChange(), SBStuffEOPs::draw(), SBStuffAplo::draw(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::updateSession(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), and SBSolutionBrowser::wWRMSs().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBPlotCarrier::setStdVarIdx (unsigned intNC_, unsigned intStdErr_) [inline]
Definition at line 131 of file SbIPlot.H'.
References DatStdVarIdx, NCE, and NCV.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBVLBIPreProcess::SBVLBIPreProcess(), SBVLBISessionEditor::SBVLBISessionEditor(), SBFilteringGauss::wBrowseData(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
void SBPlotCarrier::setType (unsigned intNC_, AxisTypeType_) [inline]
Definition at line 127 of file SbIPlot.H'.
References DatTypes, and NCV.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBStuffEOPs::draw(), SBStuffAplo::draw(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBIPreProcess::SBVLBIPreProcess(), SBVLBISessionEditor::SBVLBISessionEditor(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), and SBSolutionBrowser::wWRMSs().
unsigned int SBPlotCarrier::stdVarIdx (unsigned intNC_) const [inline]
Definition at line 133 of file SbIPlot.H'.
References DatStdVarIdx, and NCV.
Referenced by SBPlotArea::drawData(), SBPlotArea::getLimits(), and SBPlotArea::output4Files().
AxisType SBPlotCarrier::type (unsigned intNC_) const [inline]
Definition at line 129 of file SbIPlot.H'.
References AT_DATA, DatTypes, and NCV.
Referenced by SBPlotArea::getLimits(), and SBPlotArea::setXCol().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
Member Data Documentation
SBPlotBranchList SBPlotCarrier::Branches [private]
Definition at line 110 of file SbIPlot.H'.
Referenced by branches(), createBranch(), findBranch(), SBPlotCarrier(), and selfCheck().
QList<QString>* SBPlotCarrier::ColumnNames [private]
Definition at line 115 of file SbIPlot.H'.
Referenced by columnNames(), SBPlotCarrier(), and ~SBPlotCarrier().
unsigned int* SBPlotCarrier::DatAttr [private]
Definition at line 118 of file SbIPlot.H'.
Referenced by SBPlotCarrier(), setAttr(), and ~SBPlotCarrier().
unsigned int* SBPlotCarrier::DatStdVarIdx [private]
Definition at line 117 of file SbIPlot.H'.
Referenced by SBPlotCarrier(), setStdVarIdx(), stdVarIdx(), and ~SBPlotCarrier().
int* SBPlotCarrier::DatTypes [private]
Definition at line 116 of file SbIPlot.H'.
Referenced by SBPlotCarrier(), setType(), type(), and ~SBPlotCarrier().
QString SBPlotCarrier::File4SaveBaseName [private]
Definition at line 119 of file SbIPlot.H'.
Referenced by file4SaveBaseName(), SBPlotCarrier(), setAbsFile4SaveBaseName(), and setFile4SaveBaseName().
bool SBPlotCarrier::IsOK [private]
Definition at line 121 of file SbIPlot.H'.
Referenced by isOK(), SBPlotCarrier(), and selfCheck().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
unsigned int SBPlotCarrier::NCE [private]
Definition at line 114 of file SbIPlot.H'.
Referenced by createBranch(), nCE(), numOfCols(), SBPlotCarrier(), and setStdVarIdx().
unsigned int SBPlotCarrier::NCV [private]
Definition at line 113 of file SbIPlot.H'.
Referenced by createBranch(), nCV(), numOfCols(), SBPlotCarrier(), setAttr(), setStdVarIdx(), setType(), stdVarIdx(), and type().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.