SBPMNNR_NUVEL1A
NAME
SBPMNNR_NUVEL1A -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBPlateMotion'.
Public Member Functions
SBPMNNR_NUVEL1A ()
virtual QString ClassName () const
virtual Vector3 operator() (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const
virtual Vector3 velocity (SBStation &Station) const
virtual QString modelName () const
Protected Member Functions
virtual Vector3 displacement (const SBMJD &, const SBMJD &, SBStation &) const
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Protected Attributes
int N
const SBPlateEntry * Plates
QDict< SBPlateEntry > * PlDict
Static Protected Attributes
static const SBPlateEntry NNR_NUVEL1A [16]
Detailed Description
Definition at line 293 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBPMNNR_NUVEL1A::SBPMNNR_NUVEL1A () [inline]
Definition at line 298 of file SbGeoStations.H'.
Member Function Documentation
virtual QString SBPMNNR_NUVEL1A::ClassName () const [inline, virtual]
Reimplemented from SBPlateMotion'.
Definition at line 299 of file SbGeoStations.H'.
virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, and SBStationIDList'.
Definition at line 277 of file SbGeo.H'.
Vector3 SBPlateMotion::displacement (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const [protected, virtual, inherited]
Definition at line 234 of file SbGeoStations.C'.
References Vector3::at(), SBPlateMotion::ClassName(), SBLog::DBG, SBPlateEntry::displacement(), SBLog::ERR, SBStation::id(), SBLog::isEligible(), Log, SBNamed::name(), SBSite::plate(), SBLog::PLATES, SBPlateMotion::PlDict, SBStation::rt(), SBStation::site(), SBStationID::toString(), v3Zero, SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBPlateMotion::operator()(), SBPMNUVEL1A::operator()(), and operator()().
virtual QString SBPMNNR_NUVEL1A::modelName () const [inline, virtual]
Reimplemented from SBPlateMotion'.
Definition at line 308 of file SbGeoStations.H'.
virtual Vector3 SBPMNNR_NUVEL1A::operator() (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const [inline, virtual]"Calculates station's displacement due to plate motion'. Look up the plate, then calls SBPlateEntry::displacement(long double, SBStation&)
Parameters:
dt time in days
Reimplemented from SBPlateMotion'.
Definition at line 304 of file SbGeoStations.H'.
References SBPlateMotion::displacement().
virtual QDataStream& SBNList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 284 of file SbGeo.H'.
virtual Vector3 SBPMNNR_NUVEL1A::velocity (SBStation &Station) const [inline, virtual]
Reimplemented from SBPlateMotion'.
Definition at line 306 of file SbGeoStations.H'.
Referenced by SBAploChunk::import(), and SBAploEphem::importHPS().
virtual QDataStream& SBNList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 282 of file SbGeo.H'.
Member Data Documentation
int SBPlateMotion::N [protected, inherited]
Definition at line 242 of file SbGeoStations.H'.
Referenced by SBPlateMotion::SBPlateMotion().
const SBPlateEntry SBPMNNR_NUVEL1A::NNR_NUVEL1A [static, protected]"Initial value:
{
  SBPlateEntry('AFRC', 0.891, -3.099, 3.922),
  SBPlateEntry('ANTA', -0.821, -1.701, 3.706),
  SBPlateEntry('ARAB', 6.685, -0.521, 6.760),
  SBPlateEntry('AUST', 7.839, 5.124, 6.282),
  SBPlateEntry('CARB', -0.178, -3.385, 1.581),
  SBPlateEntry('COCO',-10.425,-21.605, 10.925),
  SBPlateEntry('EURA', -0.981, -2.395, 3.153),
  SBPlateEntry('INDI', 6.670, 0.040, 6.790),
  SBPlateEntry('JUFU', 5.200, 8.610, -5.820),
  SBPlateEntry('NAZC', -1.532, -8.577, 9.609),
  SBPlateEntry('NOAM', 0.258, -3.599, -0.153),
  SBPlateEntry('PCFC', -1.510, 4.840, -9.970),
  SBPlateEntry('PHIL', 10.090, -7.160, -9.670),
  SBPlateEntry('RIVR', -9.390,-30.960, 12.050),
  SBPlateEntry('SCOT', -0.410, -2.660, -1.270),
  SBPlateEntry('SOAM', -1.038, -1.515, -0.870)
}
Definition at line 296 of file SbGeoStations.H'.
const SBPlateEntry* SBPlateMotion::Plates [protected, inherited]
Definition at line 243 of file SbGeoStations.H'.
Referenced by SBPlateMotion::SBPlateMotion().
QDict<SBPlateEntry>* SBPlateMotion::PlDict [protected, inherited]
Definition at line 244 of file SbGeoStations.H'.
Referenced by SBPlateMotion::displacement(), SBPlateMotion::SBPlateMotion(), SBPlateMotion::velocity(), and SBPlateMotion::~SBPlateMotion().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.