.TH "SBPMNUVEL1A" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBPMNUVEL1A \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoStations\&.H>\fP
.PP
Inherits \fBSBPlateMotion\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBPMNUVEL1A\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual \fBVector3\fP \fBoperator()\fP (const \fBSBMJD\fP &T_, const \fBSBMJD\fP &T0_, \fBSBStation\fP &Station) const "
.br
.ti -1c
.RI "virtual \fBVector3\fP \fBvelocity\fP (\fBSBStation\fP &Station) const "
.br
.ti -1c
.RI "virtual QString \fBmodelName\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBVector3\fP \fBdisplacement\fP (const \fBSBMJD\fP &, const \fBSBMJD\fP &, \fBSBStation\fP &) const "
.br
.ti -1c
.RI "virtual int \fBcompareItems\fP (QCollection::Item item1, QCollection::Item item2)"
.br
.ti -1c
.RI "virtual QDataStream & \fBwrite\fP (QDataStream &s, QCollection::Item Entry) const "
.br
.ti -1c
.RI "virtual QDataStream & \fBread\fP (QDataStream &s, QCollection::Item &Entry)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBN\fP"
.br
.ti -1c
.RI "const \fBSBPlateEntry\fP * \fBPlates\fP"
.br
.ti -1c
.RI "QDict< \fBSBPlateEntry\fP > * \fBPlDict\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const \fBSBPlateEntry\fP \fBNUVEL1A\fP [14]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 267 of file SbGeoStations\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBPMNUVEL1A::SBPMNUVEL1A ()\fC [inline]\fP"
.PP
Definition at line 272 of file SbGeoStations\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBPMNUVEL1A::ClassName () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBPlateMotion\fP'\&.
.PP
Definition at line 273 of file SbGeoStations\&.H'\&.
.SS "virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2)\fC [inline, protected, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP, \fBSBStationList\fP, and \fBSBStationIDList\fP'\&.
.PP
Definition at line 277 of file SbGeo\&.H'\&.
.SS "\fBVector3\fP SBPlateMotion::displacement (const \fBSBMJD\fP &T_, const \fBSBMJD\fP &T0_, \fBSBStation\fP &Station) const\fC [protected, virtual, inherited]\fP"
.PP
Definition at line 234 of file SbGeoStations\&.C'\&.
.PP
References Vector3::at(), SBPlateMotion::ClassName(), SBLog::DBG, SBPlateEntry::displacement(), SBLog::ERR, SBStation::id(), SBLog::isEligible(), Log, SBNamed::name(), SBSite::plate(), SBLog::PLATES, SBPlateMotion::PlDict, SBStation::rt(), SBStation::site(), SBStationID::toString(), v3Zero, SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS\&.
.PP
Referenced by SBPlateMotion::operator()(), operator()(), and SBPMNNR_NUVEL1A::operator()()\&.
.SS "virtual QString SBPMNUVEL1A::modelName () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBPlateMotion\fP'\&.
.PP
Definition at line 282 of file SbGeoStations\&.H'\&.
.SS "virtual \fBVector3\fP SBPMNUVEL1A::operator() (const \fBSBMJD\fP &T_, const \fBSBMJD\fP &T0_, \fBSBStation\fP &Station) const\fC [inline, virtual]\fP"Calculates station's displacement due to plate motion'\&. Looks up the plate, then calls SBPlateEntry::displacement(long double, SBStation&) 
.PP
\fBParameters:\fP
.RS 4
\fIdt\fP time in days 
.RE
.PP

.PP
Reimplemented from \fBSBPlateMotion\fP'\&.
.PP
Definition at line 278 of file SbGeoStations\&.H'\&.
.PP
References SBPlateMotion::displacement()\&.
.SS "virtual QDataStream& SBNList::read (QDataStream &s, QCollection::Item &Entry)\fC [inline, protected, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP, \fBSBStationList\fP, \fBSBStationIDList\fP, \fBSBInstitutionList\fP, \fBSB_CRF\fP, and \fBSBFCList\fP'\&.
.PP
Definition at line 284 of file SbGeo\&.H'\&.
.SS "virtual \fBVector3\fP SBPMNUVEL1A::velocity (\fBSBStation\fP &Station) const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBPlateMotion\fP'\&.
.PP
Definition at line 280 of file SbGeoStations\&.H'\&.
.SS "virtual QDataStream& SBNList::write (QDataStream &s, QCollection::ItemEntry) const\fC [inline, protected, virtual, inherited]\fP"
.PP
Reimplemented in \fBSB_TRF\fP, \fBSBStationList\fP, \fBSBStationIDList\fP, \fBSBInstitutionList\fP, \fBSB_CRF\fP, and \fBSBFCList\fP'\&.
.PP
Definition at line 282 of file SbGeo\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBSBPlateMotion::N\fP\fC [protected, inherited]\fP"
.PP
Definition at line 242 of file SbGeoStations\&.H'\&.
.PP
Referenced by SBPlateMotion::SBPlateMotion()\&.
.SS "const \fBSBPlateEntry\fP \fBSBPMNUVEL1A::NUVEL1A\fP\fC [static, protected]\fP"\fBInitial value:\fP
.PP
.nf

{
  SBPlateEntry('AFRC',  2\&.401, -7\&.939, 13\&.893),
  SBPlateEntry('ANTA',  0\&.689, -6\&.541, 13\&.676),
  SBPlateEntry('ARAB',  8\&.195, -5\&.361, 16\&.730),
  SBPlateEntry('AUST',  9\&.349,  0\&.284, 16\&.253),
  SBPlateEntry('CARB',  1\&.332, -8\&.225, 11\&.551),
  SBPlateEntry('COCO', -8\&.915,-26\&.445, 20\&.896),
  SBPlateEntry('EURA',  0\&.529, -7\&.236, 13\&.123),
  SBPlateEntry('INDI',  8\&.180, -4\&.800, 16\&.760),
  SBPlateEntry('JDEF',  6\&.51 ,  3\&.17 ,  5\&.08 ),
  SBPlateEntry('NAZC', -0\&.022,-13\&.417, 19\&.579),
  SBPlateEntry('NOAM',  1\&.768, -8\&.439,  9\&.817),
  SBPlateEntry('PCFC',  0\&.0  ,  0\&.0  ,  0\&.0  ),
  SBPlateEntry('PHIL', 11\&.4  , 12\&.2  ,  0\&.0  ),
  SBPlateEntry('SOAM',  0\&.472, -6\&.355,  9\&.100)
}
.fi
.PP
Definition at line 270 of file SbGeoStations\&.H'\&.
.SS "const \fBSBPlateEntry\fP* \fBSBPlateMotion::Plates\fP\fC [protected, inherited]\fP"
.PP
Definition at line 243 of file SbGeoStations\&.H'\&.
.PP
Referenced by SBPlateMotion::SBPlateMotion()\&.
.SS "QDict<\fBSBPlateEntry\fP>* \fBSBPlateMotion::PlDict\fP\fC [protected, inherited]\fP"
.PP
Definition at line 244 of file SbGeoStations\&.H'\&.
.PP
Referenced by SBPlateMotion::displacement(), SBPlateMotion::SBPlateMotion(), SBPlateMotion::velocity(), and SBPlateMotion::~SBPlateMotion()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
