SBPMNUVEL1A
NAME
SBPMNUVEL1A -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBPlateMotion'.
Public Member Functions
SBPMNUVEL1A ()
virtual QString ClassName () const
virtual Vector3 operator() (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const
virtual Vector3 velocity (SBStation &Station) const
virtual QString modelName () const
Protected Member Functions
virtual Vector3 displacement (const SBMJD &, const SBMJD &, SBStation &) const
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Protected Attributes
int N
const SBPlateEntry * Plates
QDict< SBPlateEntry > * PlDict
Static Protected Attributes
static const SBPlateEntry NUVEL1A [14]
Detailed Description
Definition at line 267 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBPMNUVEL1A::SBPMNUVEL1A () [inline]
Definition at line 272 of file SbGeoStations.H'.
Member Function Documentation
virtual QString SBPMNUVEL1A::ClassName () const [inline, virtual]
Reimplemented from SBPlateMotion'.
Definition at line 273 of file SbGeoStations.H'.
virtual int SBNList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, and SBStationIDList'.
Definition at line 277 of file SbGeo.H'.
Vector3 SBPlateMotion::displacement (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const [protected, virtual, inherited]
Definition at line 234 of file SbGeoStations.C'.
References Vector3::at(), SBPlateMotion::ClassName(), SBLog::DBG, SBPlateEntry::displacement(), SBLog::ERR, SBStation::id(), SBLog::isEligible(), Log, SBNamed::name(), SBSite::plate(), SBLog::PLATES, SBPlateMotion::PlDict, SBStation::rt(), SBStation::site(), SBStationID::toString(), v3Zero, SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBPlateMotion::operator()(), operator()(), and SBPMNNR_NUVEL1A::operator()().
virtual QString SBPMNUVEL1A::modelName () const [inline, virtual]
Reimplemented from SBPlateMotion'.
Definition at line 282 of file SbGeoStations.H'.
virtual Vector3 SBPMNUVEL1A::operator() (const SBMJD &T_, const SBMJD &T0_, SBStation &Station) const [inline, virtual]"Calculates station's displacement due to plate motion'. Looks up the plate, then calls SBPlateEntry::displacement(long double, SBStation&)
Parameters:
dt time in days
Reimplemented from SBPlateMotion'.
Definition at line 278 of file SbGeoStations.H'.
References SBPlateMotion::displacement().
virtual QDataStream& SBNList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 284 of file SbGeo.H'.
virtual Vector3 SBPMNUVEL1A::velocity (SBStation &Station) const [inline, virtual]
Reimplemented from SBPlateMotion'.
Definition at line 280 of file SbGeoStations.H'.
virtual QDataStream& SBNList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual, inherited]
Reimplemented in SB_TRF, SBStationList, SBStationIDList, SBInstitutionList, SB_CRF, and SBFCList'.
Definition at line 282 of file SbGeo.H'.
Member Data Documentation
int SBPlateMotion::N [protected, inherited]
Definition at line 242 of file SbGeoStations.H'.
Referenced by SBPlateMotion::SBPlateMotion().
const SBPlateEntry SBPMNUVEL1A::NUVEL1A [static, protected]"Initial value:
{
  SBPlateEntry('AFRC', 2.401, -7.939, 13.893),
  SBPlateEntry('ANTA', 0.689, -6.541, 13.676),
  SBPlateEntry('ARAB', 8.195, -5.361, 16.730),
  SBPlateEntry('AUST', 9.349, 0.284, 16.253),
  SBPlateEntry('CARB', 1.332, -8.225, 11.551),
  SBPlateEntry('COCO', -8.915,-26.445, 20.896),
  SBPlateEntry('EURA', 0.529, -7.236, 13.123),
  SBPlateEntry('INDI', 8.180, -4.800, 16.760),
  SBPlateEntry('JDEF', 6.51 , 3.17 , 5.08 ),
  SBPlateEntry('NAZC', -0.022,-13.417, 19.579),
  SBPlateEntry('NOAM', 1.768, -8.439, 9.817),
  SBPlateEntry('PCFC', 0.0 , 0.0 , 0.0 ),
  SBPlateEntry('PHIL', 11.4 , 12.2 , 0.0 ),
  SBPlateEntry('SOAM', 0.472, -6.355, 9.100)
}
Definition at line 270 of file SbGeoStations.H'.
const SBPlateEntry* SBPlateMotion::Plates [protected, inherited]
Definition at line 243 of file SbGeoStations.H'.
Referenced by SBPlateMotion::SBPlateMotion().
QDict<SBPlateEntry>* SBPlateMotion::PlDict [protected, inherited]
Definition at line 244 of file SbGeoStations.H'.
Referenced by SBPlateMotion::displacement(), SBPlateMotion::SBPlateMotion(), SBPlateMotion::velocity(), and SBPlateMotion::~SBPlateMotion().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.