SBPolusNRO
NAME
SBPolusNRO -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits Matrix3'.
Public Member Functions
SBPolusNRO (SBEOP *)
virtual ~SBPolusNRO ()
virtual QString ClassName () const
virtual const Matrix3 & operator() (const SBTime &, SBFrame *)
virtual double xp () const
virtual double yp () const
virtual const Matrix3 & r1y () const
virtual const Matrix3 & r2x () const
virtual const Matrix3 & r3s () const
virtual const Matrix3 & dR1dy () const
virtual const Matrix3 & dR2dx () const
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Protected Attributes
RotMatrix R1
RotMatrix R2
RotMatrix R3
RotDerMatrix DR1dy
RotDerMatrix DR2dx
double Xp
double Yp
double s_prime
SBEOP * EOP
EOP database'.
double mat [3][3]
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
NRO polus rotation matrix'. Matrix describes rotation due to polar motion (dX and dY)'.
Definition at line 546 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBPolusNRO::SBPolusNRO (SBEOP *EOP_)"A constructor'.
A constructor'. Creates a copy of object'.
Definition at line 729 of file SbGeoRefFrame.C'.
References ClassName(), EOP, Log, SBLog::NUTATION, s_prime, SBLog::write(), SBLog::WRN, Xp, and Yp.
virtual SBPolusNRO::~SBPolusNRO () [inline, virtual]"A destructor'.
Definition at line 563 of file SbGeoRefFrame.H'.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
virtual QString SBPolusNRO::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from Matrix3'.
Definition at line 565 of file SbGeoRefFrame.H'.
Referenced by SBPolusNRO().
virtual const Matrix3& SBPolusNRO::dR1dy () const [inline, virtual]
Definition at line 578 of file SbGeoRefFrame.H'.
References DR1dy.
Referenced by SBFrameNRO::dQ_dyp().
virtual const Matrix3& SBPolusNRO::dR2dx () const [inline, virtual]
Definition at line 579 of file SbGeoRefFrame.H'.
References DR2dx.
Referenced by SBFrameNRO::dQ_dxp().
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
const Matrix3 & SBPolusNRO::operator() (const SBTime &T, SBFrame *Frame) [virtual]"Returns matrix for the time T'. Returns matrix R1(y_p)*R2(x_p) for the time T'. Should be considered as Polus'.calc(T)'.
Definition at line 739 of file SbGeoRefFrame.C'.
References SBFrame::diurnalDX(), SBFrame::diurnalDY(), DR1dy, DR2dx, SBEOP::dX(), SBEOP::dY(), EOP, R1, R2, R3, s_prime, SEC2RAD, TEphem, SBTime::TT(), Xp, and Yp.
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
virtual const Matrix3& SBPolusNRO::r1y () const [inline, virtual]
Definition at line 575 of file SbGeoRefFrame.H'.
References R1.
Referenced by SBFrameNRO::dQ_dxp().
virtual const Matrix3& SBPolusNRO::r2x () const [inline, virtual]
Definition at line 576 of file SbGeoRefFrame.H'.
References R2.
Referenced by SBFrameNRO::dQ_dyp().
virtual const Matrix3& SBPolusNRO::r3s () const [inline, virtual]
Definition at line 577 of file SbGeoRefFrame.H'.
References R3.
Referenced by SBFrameNRO::dQ_dxp(), and SBFrameNRO::dQ_dyp().
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
virtual double SBPolusNRO::xp () const [inline, virtual]"Returns X-pole coordinate (splined EOP + estimated) without diurnals'.
Definition at line 571 of file SbGeoRefFrame.H'.
References Xp.
Referenced by SBFrameNRO::polar_X().
virtual double SBPolusNRO::yp () const [inline, virtual]"Returns Y-pole coordinate (splined EOP + estimated) without diurnals'.
Definition at line 573 of file SbGeoRefFrame.H'.
References Yp.
Referenced by SBFrameNRO::polar_Y().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
RotDerMatrix SBPolusNRO::DR1dy [protected]
Definition at line 552 of file SbGeoRefFrame.H'.
Referenced by dR1dy(), and operator()().
RotDerMatrix SBPolusNRO::DR2dx [protected]
Definition at line 553 of file SbGeoRefFrame.H'.
Referenced by dR2dx(), and operator()().
SBEOP* SBPolusNRO::EOP [protected]
EOP database'.
Definition at line 557 of file SbGeoRefFrame.H'.
Referenced by operator()(), and SBPolusNRO().
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
RotMatrix SBPolusNRO::R1 [protected]
Definition at line 549 of file SbGeoRefFrame.H'.
Referenced by operator()(), and r1y().
RotMatrix SBPolusNRO::R2 [protected]
Definition at line 550 of file SbGeoRefFrame.H'.
Referenced by operator()(), and r2x().
RotMatrix SBPolusNRO::R3 [protected]
Definition at line 551 of file SbGeoRefFrame.H'.
Referenced by operator()(), and r3s().
double SBPolusNRO::s_prime [protected]
Definition at line 556 of file SbGeoRefFrame.H'.
Referenced by operator()(), and SBPolusNRO().
double SBPolusNRO::Xp [protected]
Definition at line 554 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPolusNRO(), and xp().
double SBPolusNRO::Yp [protected]
Definition at line 555 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPolusNRO(), and yp().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.