SBPolarTideLd
NAME
SBPolarTideLd -
SYNOPSIS
#include <SbGeoTide.H>
Inherits Vector3'.
Public Member Functions
SBPolarTideLd (const SBConfig *Cfg_)
virtual ~SBPolarTideLd ()
virtual QString ClassName () const
virtual const Vector3 & operator() (SBStation *, const SBEOP *, const SBTime &)
double & operator[] (DIRECTION i)
double at (DIRECTION i) const
double module () const
double phi () const
double lambda () const
Vector3 & unify ()
Vector3 unit () const
void clear ()
Vector3 & operator+= (const Vector3 &)
Vector3 & operator-= (const Vector3 &)
Vector3 & operator*= (double)
Vector3 & operator/= (double)
virtual void report2Log (SBLog::LogLevel, uint, const QString &, int, int, double=1.0) const
bool operator== (const Vector3 &v) const
bool operator!= (const Vector3 &v) const
Protected Attributes
const SBConfig * Cfg
double vec [3]
Friends
Vector3 operator- (const Vector3 &)
Vector3 operator- (const Vector3 &, const Vector3 &)
Vector3 operator+ (const Vector3 &, const Vector3 &)
Vector3 operator/ (const Vector3 &, double)
Vector3 operator* (const Vector3 &, double)
Vector3 operator* (double, const Vector3 &)
double operator* (const Vector3 &, const Vector3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Vector3 operator% (const Vector3 &, const Vector3 &)
QDataStream & operator<< (QDataStream &s, const Vector3 &v)
QDataStream & operator>> (QDataStream &s, Vector3 &v)
Detailed Description
Polar Tide displacements'. Inherits Vector3 representing VEN local tide displacement'.
Definition at line 78 of file SbGeoTide.H'.
Constructor & Destructor Documentation
SBPolarTideLd::SBPolarTideLd (const SBConfig *Cfg_) [inline]"A constructor'.
Definition at line 84 of file SbGeoTide.H'.
References Cfg.
virtual SBPolarTideLd::~SBPolarTideLd () [inline, virtual]"A destructor'.
Definition at line 86 of file SbGeoTide.H'.
Member Function Documentation
double Vector3::at (DIRECTIONi) const [inline, inherited]
Definition at line 72 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBStationEditor::acquireData(), SBDelay::calc(), SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBTestEphem::createWidget4Test(), SBPlateMotion::displacement(), SBTestEphem::displayCoo(), SBTestAPLoad::fillData4Plotting(), SBEccListItem::key(), SBCoordsListItem::key(), SBRunManager::makeReportMaps(), Matrix3::Matrix3(), operator<<(), SB_TRF::prepareEccs4Session(), SBRefraction::refrDir(), SBStationEcc::registerEcc(), SBCoordsEditor::SBCoordsEditor(), sinex_SiteEccentricityBlock(), sinex_tro_StaCoordinatesBlock(), SBEccListItem::text(), SBCoordsListItem::text(), SBPlateEntry::velocity(), SBPlateMotion::velocity(), SBStationEditor::wCoordinates(), and SBSiteEditor::wSite().
virtual QString SBPolarTideLd::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from Vector3'.
Definition at line 88 of file SbGeoTide.H'.
Referenced by operator()().
void Vector3::clear () [inline, inherited]
Definition at line 79 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), SBOceanTideLd::operator()(), operator()(), and SBSolidTideLd::operator()().
double Vector3::lambda () const [inline, inherited]
Definition at line 75 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), and SBSolidTideLd::operator()().
double Vector3::module () const [inline, inherited]
Definition at line 73 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBSolidTideLdIERS96::deg3InPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBStationImport::importITRF(), Vector3::lambda(), SBSolidTideLdIERS96::latDepend(), SBRunManager::makeReportMaps(), SBSolidTideLd::makeStep1(), Vector3::phi(), Vector3::report2Log(), Vector3::unify(), and Vector3::unit().
bool Vector3::operator!= (const Vector3 &v) const [inline, inherited]
Definition at line 102 of file SbVector3.H'.
const Vector3 & SBPolarTideLd::operator() (SBStation *Station, const SBEOP *EOP, const SBTime &T) [virtual]"Calculates rotational deformation due to Polar Motion corresponds to time T'.
Definition at line 250 of file SbGeoTide.C'.
References ClassName(), Vector3::clear(), SBEOP::dX(), SBEOP::dY(), SBLog::ERR, SBStation::latitude(), Log, SBStation::longitude(), RAD2SEC, sincos(), SBLog::TIDES, Vector3::vec, and SBLog::write().
Vector3 & Vector3::operator*= (doublev) [inline, inherited]
Definition at line 247 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator+= (const Vector3 &V) [inline, inherited]
Definition at line 235 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator-= (const Vector3 &V) [inline, inherited]
Definition at line 241 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator/= (doublev) [inline, inherited]
Definition at line 253 of file SbVector3.H'.
References Vector3::vec.
bool Vector3::operator== (const Vector3 &v) const [inline, inherited]
Definition at line 100 of file SbVector3.H'.
References Vector3::vec.
double& Vector3::operator[] (DIRECTIONi) [inline, inherited]
Definition at line 71 of file SbVector3.H'.
References Vector3::vec.
double Vector3::phi () const [inline, inherited]
Definition at line 74 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dLag(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::permTide(), and SBSolidTideLdIERS96::permTide().
void Vector3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref, intw_, intd_, doubleScale = 1.0) const [virtual, inherited]
Definition at line 39 of file SbVector3.C'.
References Log, Vector3::module(), Vector3::vec, and SBLog::write().
Referenced by SBStation::axisOffsetLenght(), SBDelay::calc(), SBEphem::calc(), SBAploEphem::displacement(), SBSolidTideLd::operator()(), SBTideLd::operator()(), and SBRefraction::operator()().
Vector3& Vector3::unify () [inline, inherited]
Definition at line 77 of file SbVector3.H'.
References Vector3::module().
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg3InPhase(), and SBSolidTideLdIERS96::latDepend().
Vector3 Vector3::unit () const [inline, inherited]
Definition at line 78 of file SbVector3.H'.
References Vector3::module(), and Vector3::Vector3().
Referenced by SBDelay::calc(), SBRunManager::constraintStationVeloc(), SBSolidTideLd::dTide_dH2(), and SBSolidTideLd::dTide_dL2().
Friends And Related Function Documentation
Vector3 operator% (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a vector product of two vectors (because '%' has a priority of '*')
makes vector product of two vectors'.
Definition at line 326 of file SbVector3.H'.
Vector3 operator* (const Vector3 &V1, doublev2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 302 of file SbVector3.H'.
Vector3 operator* (doublev1, const Vector3 &V2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 310 of file SbVector3.H'.
double operator* (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a scalar product of two vectors
makes scalar product of two vectors'.
Definition at line 318 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &M, const Vector3 &V) [friend, inherited]"makes a product of matrix and vector
Matrix3 makes product of matrix and vector'.
Definition at line 519 of file SbVector3.H'.
Vector3 operator+ (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 278 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V) [friend, inherited]
Definition at line 270 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 286 of file SbVector3.H'.
Vector3 operator/ (const Vector3 &V1, doublev2) [friend, inherited]
Definition at line 294 of file SbVector3.H'.
QDataStream& operator<< (QDataStream &s, const Vector3 &v) [friend, inherited]
Definition at line 103 of file SbVector3.H'.
QDataStream& operator>> (QDataStream &s, Vector3 &v) [friend, inherited]
Definition at line 105 of file SbVector3.H'.
Member Data Documentation
const SBConfig* SBPolarTideLd::Cfg [protected]
Definition at line 81 of file SbGeoTide.H'.
Referenced by SBPolarTideLd().
double Vector3::vec[3] [protected, inherited]
Definition at line 53 of file SbVector3.H'.
Referenced by Vector3::at(), Vector3::clear(), Vector3::lambda(), Vector3::module(), SBOceanTideLd::operator()(), operator()(), Vector3::operator*=(), Vector3::operator+=(), Vector3::operator-=(), Vector3::operator/=(), Vector3::operator=(), Vector3::operator==(), Vector3::operator[](), Vector3::phi(), Vector3::report2Log(), and Vector3::Vector3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.