SBPrec_IAU2000
NAME
SBPrec_IAU2000 -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits SBPrecession'.
Public Member Functions
SBPrec_IAU2000 ()
virtual ~SBPrec_IAU2000 ()
virtual QString ClassName () const
virtual const Matrix3 & operator() (SBTime &)
double psi () const
double omega () const
double chi () const
virtual const Matrix3 & dP_dpsi ()
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Protected Attributes
double t
double Psi
double Omega
double Chi
RotMatrix R1
RotMatrix R2
RotMatrix R3
RotMatrix R4
Matrix3 DP_dPsi
double mat [3][3]
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
SBPrec_IAU2000'. Calculates precession quantities and the matrix of the precession theory IAU-2000(sp?)'.
Definition at line 277 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBPrec_IAU2000::SBPrec_IAU2000 ()"A constructor'. Creates a copy of object'.
Definition at line 116 of file SbGeoRefFrame.C'.
References Chi, Omega, Psi, and t.
virtual SBPrec_IAU2000::~SBPrec_IAU2000 () [inline, virtual]"A destructor'.
Definition at line 296 of file SbGeoRefFrame.H'.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
double SBPrec_IAU2000::chi () const [inline]"Returns Theta (for debug purposes)'.
Definition at line 306 of file SbGeoRefFrame.H'.
References Chi.
virtual QString SBPrec_IAU2000::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBPrecession'.
Definition at line 298 of file SbGeoRefFrame.H'.
Referenced by operator()().
const Matrix3 & SBPrec_IAU2000::dP_dpsi () [virtual]
Implements SBPrecession'.
Definition at line 183 of file SbGeoRefFrame.C'.
References DP_dPsi, Psi, R1, R3, R4, t, and Z_AXIS.
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
double SBPrec_IAU2000::omega () const [inline]"Returns Z (for debug purposes)'.
Definition at line 304 of file SbGeoRefFrame.H'.
References Omega.
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
const Matrix3 & SBPrec_IAU2000::operator() (SBTime &T) [virtual]"Calculates precession angles and returns matrix corresponds to time T'.
Implements SBPrecession'.
Definition at line 125 of file SbGeoRefFrame.C'.
References RotMatrix::angle(), Chi, ClassName(), SBLog::DBG, SBNutation::ephemEps(), SBLog::isEligible(), Log, SBLog::NUTATION, Omega, SBLog::PRECESSION, Psi, R1, R2, R3, R4, Matrix3::report2Log(), SEC2RAD, t, SBTime::TDB(), TEphem, SBMJD::toString(), SBTime::TT(), and SBLog::write().
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
double SBPrec_IAU2000::psi () const [inline]"Returns Zeta (for debug purposes)'.
Definition at line 302 of file SbGeoRefFrame.H'.
References Psi.
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
double SBPrec_IAU2000::Chi [protected]
Definition at line 283 of file SbGeoRefFrame.H'.
Referenced by chi(), operator()(), and SBPrec_IAU2000().
Matrix3 SBPrec_IAU2000::DP_dPsi [protected]
Definition at line 288 of file SbGeoRefFrame.H'.
Referenced by dP_dpsi().
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
double SBPrec_IAU2000::Omega [protected]
Definition at line 282 of file SbGeoRefFrame.H'.
Referenced by omega(), operator()(), and SBPrec_IAU2000().
double SBPrec_IAU2000::Psi [protected]
Definition at line 281 of file SbGeoRefFrame.H'.
Referenced by dP_dpsi(), operator()(), psi(), and SBPrec_IAU2000().
RotMatrix SBPrec_IAU2000::R1 [protected]
Definition at line 284 of file SbGeoRefFrame.H'.
Referenced by dP_dpsi(), and operator()().
RotMatrix SBPrec_IAU2000::R2 [protected]
Definition at line 285 of file SbGeoRefFrame.H'.
Referenced by operator()().
RotMatrix SBPrec_IAU2000::R3 [protected]
Definition at line 286 of file SbGeoRefFrame.H'.
Referenced by dP_dpsi(), and operator()().
RotMatrix SBPrec_IAU2000::R4 [protected]
Definition at line 287 of file SbGeoRefFrame.H'.
Referenced by dP_dpsi(), and operator()().
double SBPrec_IAU2000::t [protected]
Definition at line 280 of file SbGeoRefFrame.H'.
Referenced by dP_dpsi(), operator()(), and SBPrec_IAU2000().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.