SBPrecNutNRO
NAME
SBPrecNutNRO -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits Matrix3'.
Public Member Functions
SBPrecNutNRO (const SBConfig *, SBEOP *=NULL)
virtual ~SBPrecNutNRO ()
virtual QString ClassName () const
virtual const Matrix3 & operator() (const SBTime &)
virtual double geodesicNutation (const SBTime &)
virtual double x () const
virtual double y () const
virtual double s () const
virtual double dX () const
virtual double dY () const
const SBNROThGeneral * theory () const
virtual const Matrix3 & rs () const
virtual const Matrix3 & q () const
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Protected Attributes
const SBConfig * Cfg
double X
X coordinate of the CEP in the CRS'.
double Y
Y coordinate of the CEP in the CRS'.
double S
s
double DX
double DY
SBNROThGeneral * Theory
theoretical values of X, Y and s
SBEOP * EOP
EOP database'.
RotMatrix R
Matrix3 Q
double mat [3][3]
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
Precession-Nutation matrix for NRO'. Calculates combined precession-nutation matrix in the case of NRO'.
Definition at line 454 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBPrecNutNRO::SBPrecNutNRO (const SBConfig *Cfg_, SBEOP *EOP_ = NULL)"A constructor'. Creates a copy of object'.
Definition at line 594 of file SbGeoRefFrame.C'.
References Cfg, ClassName(), DX, DY, EOP, Log, SBLog::NUTATION, S, Theory, SBLog::write(), SBLog::WRN, X, and Y.
virtual SBPrecNutNRO::~SBPrecNutNRO () [inline, virtual]"A destructor'.
Definition at line 473 of file SbGeoRefFrame.H'.
References EOP, and Theory.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
virtual QString SBPrecNutNRO::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from Matrix3'.
Definition at line 475 of file SbGeoRefFrame.H'.
Referenced by SBPrecNutNRO().
virtual double SBPrecNutNRO::dX () const [inline, virtual]"Returns current DeltaEps'.
Definition at line 487 of file SbGeoRefFrame.H'.
References DX.
Referenced by SBFrameNRO::dNutation_Psi().
virtual double SBPrecNutNRO::dY () const [inline, virtual]
Definition at line 488 of file SbGeoRefFrame.H'.
References DY.
Referenced by SBFrameNRO::dNutation_Eps().
double SBPrecNutNRO::geodesicNutation (const SBTime &T) [virtual]"Calcs geodesic nutation'.
Definition at line 637 of file SbGeoRefFrame.C'.
References SBNutation::ephemEps(), SBTime::fArg_lPrime(), and SEC2RAD.
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
const Matrix3 & SBPrecNutNRO::operator() (const SBTime &T) [virtual]"Calculates nutation angles and returns matrix corresponds to time T'.
Definition at line 615 of file SbGeoRefFrame.C'.
References SBNROThGeneral::calc(), SBEOP::dEps(), SBEOP::dPsi(), DX, DY, EOP, Matrix3::Matrix3(), Q, R, SBNROThGeneral::s(), S, Theory, SBNROThGeneral::x(), X, SBNROThGeneral::y(), and Y.
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
virtual const Matrix3& SBPrecNutNRO::q () const [inline, virtual]
Definition at line 491 of file SbGeoRefFrame.H'.
References Q.
Referenced by SBFrameNRO::dQ_deps(), and SBFrameNRO::dQ_dpsi().
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
virtual const Matrix3& SBPrecNutNRO::rs () const [inline, virtual]
Definition at line 490 of file SbGeoRefFrame.H'.
References R.
Referenced by SBFrameNRO::dQ_deps(), and SBFrameNRO::dQ_dpsi().
virtual double SBPrecNutNRO::s () const [inline, virtual]"Returns current true obliquity'.
Definition at line 485 of file SbGeoRefFrame.H'.
References S.
Referenced by SBFrameNRO::dQ_deps(), and SBFrameNRO::dQ_dpsi().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
const SBNROThGeneral* SBPrecNutNRO::theory () const [inline]
Definition at line 489 of file SbGeoRefFrame.H'.
References Theory.
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
virtual double SBPrecNutNRO::x () const [inline, virtual]"Returns obliquity at J2000'.0'.
Definition at line 481 of file SbGeoRefFrame.H'.
References X.
Referenced by SBFrameNRO::dQ_deps(), SBFrameNRO::dQ_dpsi(), and SBFrameNRO::totNutationLongitude().
virtual double SBPrecNutNRO::y () const [inline, virtual]"Returns current mean obliquity'.
Definition at line 483 of file SbGeoRefFrame.H'.
References Y.
Referenced by SBFrameNRO::dQ_deps(), SBFrameNRO::dQ_dpsi(), and SBFrameNRO::totNutationObliquity().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
const SBConfig* SBPrecNutNRO::Cfg [protected]
Definition at line 457 of file SbGeoRefFrame.H'.
Referenced by SBPrecNutNRO().
double SBPrecNutNRO::DX [protected]
Definition at line 461 of file SbGeoRefFrame.H'.
Referenced by dX(), operator()(), and SBPrecNutNRO().
double SBPrecNutNRO::DY [protected]
Definition at line 462 of file SbGeoRefFrame.H'.
Referenced by dY(), operator()(), and SBPrecNutNRO().
SBEOP* SBPrecNutNRO::EOP [protected]
EOP database'.
Definition at line 464 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPrecNutNRO(), and ~SBPrecNutNRO().
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
Matrix3 SBPrecNutNRO::Q [protected]
Definition at line 466 of file SbGeoRefFrame.H'.
Referenced by operator()(), and q().
RotMatrix SBPrecNutNRO::R [protected]
Definition at line 465 of file SbGeoRefFrame.H'.
Referenced by operator()(), and rs().
double SBPrecNutNRO::S [protected]
s
Definition at line 460 of file SbGeoRefFrame.H'.
Referenced by operator()(), s(), and SBPrecNutNRO().
SBNROThGeneral* SBPrecNutNRO::Theory [protected]
theoretical values of X, Y and s
Definition at line 463 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPrecNutNRO(), theory(), and ~SBPrecNutNRO().
double SBPrecNutNRO::X [protected]
X coordinate of the CEP in the CRS'.
Definition at line 458 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPrecNutNRO(), and x().
double SBPrecNutNRO::Y [protected]
Y coordinate of the CEP in the CRS'.
Definition at line 459 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPrecNutNRO(), and y().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.