SBProject
NAME
SBProject -
SYNOPSIS
#include <SbGeoProject.H>
Inherits SBNamed'.
Public Member Functions
SBProject (const QString &)
virtual ~SBProject ()
virtual QString ClassName () const
SBConfig & cfg ()
const QString & comments () const
int version () const
SBHistory * history ()
void setCfg (const SBConfig &Cfg_)
void incVersion ()
void addHistoryLine (const QString &Txt_)
bool delHistoryLine (const SBHistory::SBHistoryEntry *E_)
void setComments (const QString &Comments_)
const SBParametersDesc & p () const
void setP (const SBParametersDesc &P_)
void setAllPars2Type (SBParameterCfg::PType Type)
SBVLBISesInfoList * VLBIsessionList ()
SBStationInfoList * stationList ()
SBSourceInfoList * sourceList ()
SBBaseInfoList * baseList ()
SBVLBISesInfo * sessionByName (const char *Name_)
SBStationInfo * stationByAka (const char *Aka_)
SBSourceInfo * sourceByAka (const char *Aka_)
SBBaseInfo * baseByAka (const char *Aka_)
bool addSession (const SBVLBISet *, const SBVLBISesInfo *)
bool delSession (const SBVLBISet *, const SBVLBISesInfo *)
int numObs () const
int numVLBISessions () const
int numStations () const
int numSources () const
int numBases () const
const SBMJD & tStart () const
const SBMJD & tFinis () const
double tInterval () const
virtual void clearRMSs ()
const QString & name () const
void setName (const QString &Name_)
Protected Member Functions
void fillDicts ()
void fillSessionDict (int=5)
void fillStationDict (int=5)
void fillSourceDict (int=5)
void fillBaseDict (int=5)
Protected Attributes
SBConfig Cfg
project's config
int Version
project's version
SBHistory History
project's history
QString Comments
some comments
SBVLBISesInfoList VLBISessionList
list of VLBI sessions
QDict< SBVLBISesInfo > * SessionByName
SBStationInfoList StationList
list of stations
QDict< SBStationInfo > * StationByAka
SBSourceInfoList SourceList
list of sources
QDict< SBSourceInfo > * SourceByAka
SBBaseInfoList BaseList
list of bases
QDict< SBBaseInfo > * BaseByAka
int NumObs
QString Name
Friends
QDataStream & operator<< (QDataStream &, const SBProject &)
QDataStream & operator>> (QDataStream &, SBProject &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Project'.
Definition at line 328 of file SbGeoProject.H'.
Constructor & Destructor Documentation
SBProject::SBProject (const QString &Name_)"A constructor'.
Definition at line 389 of file SbGeoProject.C'.
References BaseByAka, BaseList, NumObs, SessionByName, SourceByAka, SourceList, StationByAka, StationList, Version, and VLBISessionList.
SBProject::~SBProject () [virtual]"A destructor'.
Definition at line 411 of file SbGeoProject.C'.
References BaseByAka, SessionByName, SourceByAka, and StationByAka.
Member Function Documentation
void SBProject::addHistoryLine (const QString &Txt_) [inline]
Definition at line 375 of file SbGeoProject.H'.
References SBHistory::addHistoryLine(), History, and Version.
Referenced by SBProjectCreate::createProject().
bool SBProject::addSession (const SBVLBISet *Wvlbi, const SBVLBISesInfo *SI)"Adds a session to the list of sessions, returns TRUE if success'.
Definition at line 474 of file SbGeoProject.C'.
References SBObjectObsInfo::aka(), BaseByAka, BaseList, SBVLBISession::baseList(), ClassName(), SBVLBISesInfo::clearRMSs(), SBLog::DATA, SBLog::DBG, SBAttributed::delAttr(), fillBaseDict(), fillSessionDict(), fillSourceDict(), fillStationDict(), SBVLBISet::loadSession(), Log, SBNamed::name(), SBVLBISesInfo::notValid, SBObjectObsInfo::num(), SessionByName, SBObjectObsInfo::setNum(), SourceByAka, SourceList, SBVLBISession::sourceList(), StationByAka, StationList, SBVLBISession::stationList(), VLBISessionList, SBLog::write(), and SBLog::WRN.
Referenced by SBProjectCreate::createProject(), SBVLBIPreProcess::currentSesChange(), and SBVLBIPreProcess::preProcess().
SBBaseInfo* SBProject::baseByAka (const char *Aka_) [inline]"Returns BaseInfo corresponding to the name;
Definition at line 401 of file SbGeoProject.H'.
References BaseByAka.
SBBaseInfoList* SBProject::baseList () [inline]"Returns list of the bases;
Definition at line 392 of file SbGeoProject.H'.
References BaseList.
Referenced by SBObsVLBIEntry::isEligible(), SBObsVLBIEntry::process(), and SBProjectEdit::SBProjectEdit().
SBConfig& SBProject::cfg () [inline]
Definition at line 368 of file SbGeoProject.H'.
References Cfg.
Referenced by SBDelay::calc(), SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::fillParameterList(), SBEstimator::finisLocal(), SBRunManager::finisRun_m1(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBEOP::interpolateEOPs(), SBObsVLBIEntry::isEligible(), SBRunManager::makeReportEOP(), SBRunManager::makeReports(), SBRunManager::makeReportTroposphere(), operator<<(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBModelEditor::SBModelEditor(), SBRunManager::SBRunManager(), sinex_tro_TropDescriptionBlock(), SBStation::vModel(), and writeNormalEquationSystem().
virtual QString SBProject::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBNamed'.
Definition at line 363 of file SbGeoProject.H'.
Referenced by addSession(), delSession(), fillBaseDict(), fillSessionDict(), fillSourceDict(), and fillStationDict().
virtual void SBProject::clearRMSs () [inline, virtual]
Definition at line 431 of file SbGeoProject.H'.
References BaseList, SBStationInfoList::clearRMSs(), SBBaseInfoList::clearRMSs(), SBSourceInfoList::clearRMSs(), SourceList, and StationList.
Referenced by SBRunManager::prepare4Run_m1().
const QString& SBProject::comments () const [inline]
Definition at line 369 of file SbGeoProject.H'.
References Comments.
Referenced by SBProjectEdit::comments().
bool SBProject::delHistoryLine (const SBHistory::SBHistoryEntry *E_) [inline]
Definition at line 377 of file SbGeoProject.H'.
References History.
bool SBProject::delSession (const SBVLBISet *Wvlbi, const SBVLBISesInfo *SI)"Deletes a session from the list of sessions, returns TRUE if success'.
Definition at line 543 of file SbGeoProject.C'.
References SBObjectObsInfo::aka(), BaseByAka, BaseList, SBVLBISession::baseList(), ClassName(), SBLog::DATA, SBLog::DBG, SBVLBISet::loadSession(), Log, SBNamed::name(), SBObjectObsInfo::num(), SessionByName, SBObjectObsInfo::setNum(), SourceByAka, SourceList, SBVLBISession::sourceList(), StationByAka, StationList, SBVLBISession::stationList(), VLBISessionList, SBLog::write(), and SBLog::WRN.
Referenced by SBProjectEdit::delSession().
void SBProject::fillBaseDict (intN = 5) [protected]
Definition at line 461 of file SbGeoProject.C'.
References BaseByAka, BaseList, ClassName(), SBLog::DATA, SBLog::ERR, Log, and SBLog::write().
Referenced by addSession(), and fillDicts().
void SBProject::fillDicts () [inline, protected]
Definition at line 349 of file SbGeoProject.H'.
References fillBaseDict(), fillSessionDict(), fillSourceDict(), and fillStationDict().
void SBProject::fillSessionDict (intN = 5) [protected]
Definition at line 419 of file SbGeoProject.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, Log, NumObs, SessionByName, VLBISessionList, and SBLog::write().
Referenced by addSession(), and fillDicts().
void SBProject::fillSourceDict (intN = 5) [protected]
Definition at line 448 of file SbGeoProject.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, Log, SourceByAka, SourceList, and SBLog::write().
Referenced by addSession(), and fillDicts().
void SBProject::fillStationDict (intN = 5) [protected]
Definition at line 435 of file SbGeoProject.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, Log, StationByAka, StationList, and SBLog::write().
Referenced by addSession(), and fillDicts().
SBHistory* SBProject::history () [inline]
Definition at line 371 of file SbGeoProject.H'.
References History.
Referenced by SBProjectEdit::SBProjectEdit().
void SBProject::incVersion () [inline]
Definition at line 374 of file SbGeoProject.H'.
References Version.
Referenced by SBProjectEdit::histVerInced().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
int SBProject::numBases () const [inline]"Returns number of the bases in the project'.
Definition at line 418 of file SbGeoProject.H'.
References BaseList.
Referenced by SBProjectSel::ProjectListItem::ProjectListItem().
int SBProject::numObs () const [inline]"Returns number of the observations in the project'.
Definition at line 410 of file SbGeoProject.H'.
References NumObs.
Referenced by SBRunManager::process_m1(), SBRunManager::process_m2(), and SBProjectSel::ProjectListItem::ProjectListItem().
int SBProject::numSources () const [inline]"Returns number of the sources in the project'.
Definition at line 416 of file SbGeoProject.H'.
References SourceList.
Referenced by SBProjectSel::ProjectListItem::ProjectListItem().
int SBProject::numStations () const [inline]"Returns number of the stations in the project'.
Definition at line 414 of file SbGeoProject.H'.
References StationList.
Referenced by SBProjectSel::ProjectListItem::ProjectListItem().
int SBProject::numVLBISessions () const [inline]"Returns number of the VLBI sessions in the project'.
Definition at line 412 of file SbGeoProject.H'.
References VLBISessionList.
Referenced by SBProjectSel::ProjectListItem::ProjectListItem(), SBRunManager::saveVLBISessions_m1(), and SBRunManager::saveVLBISessions_m2().
const SBParametersDesc& SBProject::p () const [inline]
Definition at line 380 of file SbGeoProject.H'.
References Cfg, and SBConfig::p().
Referenced by SBVLBIPreProcess::preProcess(), and SBParametersEditor::SBParametersEditor().
SBVLBISesInfo* SBProject::sessionByName (const char *Name_) [inline]"Returns SessionInfo corresponding to the name;
Definition at line 395 of file SbGeoProject.H'.
References SessionByName.
Referenced by SBBrowseSessions::updateList().
void SBProject::setAllPars2Type (SBParameterCfg::PTypeType) [inline]
Definition at line 382 of file SbGeoProject.H'.
References Cfg, and SBConfig::setAllPars2Type().
Referenced by SBVLBIPreProcess::preProcess().
void SBProject::setCfg (const SBConfig &Cfg_) [inline]
Definition at line 373 of file SbGeoProject.H'.
References Cfg.
Referenced by SBRunManager::makeReportTroposphere(), SBVLBIPreProcess::preProcess(), and SBModelEditor::~SBModelEditor().
void SBProject::setComments (const QString &Comments_) [inline]
Definition at line 379 of file SbGeoProject.H'.
References Comments.
Referenced by SBProjectEdit::acquireData().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBProject::setP (const SBParametersDesc &P_) [inline]
Definition at line 381 of file SbGeoProject.H'.
References Cfg, and SBConfig::setP().
Referenced by SBVLBIPreProcess::preProcess(), and SBParametersEditor::~SBParametersEditor().
SBSourceInfo* SBProject::sourceByAka (const char *Aka_) [inline]"Returns SourceInfo corresponding to the name;
Definition at line 399 of file SbGeoProject.H'.
References SourceByAka.
SBSourceInfoList* SBProject::sourceList () [inline]"Returns list of the sources;
Definition at line 390 of file SbGeoProject.H'.
References SourceList.
Referenced by SBSolutionBrowser::batch4StochSoChanged(), SBRunManager::constraintSourceCoord(), SBRunManager::fillParameterList(), SBObsVLBIEntry::isEligible(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBObsVLBIEntry::process(), SBProjectEdit::SBProjectEdit(), sinex_SourceIDBlock(), SBRunManager::stripCRF(), and SBSolutionBrowser::updateCRF().
SBStationInfo* SBProject::stationByAka (const char *Aka_) [inline]"Returns StationInfo corresponding to the name;
Definition at line 397 of file SbGeoProject.H'.
References StationByAka.
SBStationInfoList* SBProject::stationList () [inline]"Returns list of the stations;
Definition at line 388 of file SbGeoProject.H'.
References StationList.
Referenced by SBSolutionBrowser::batch4StochStChanged(), collectListOfSINEXParameters(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBRunManager::fillParameterList(), SBSolution::guessParameterName(), SBObsVLBIEntry::isEligible(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBObsVLBIEntry::process(), SBProjectEdit::SBProjectEdit(), sinex_SiteIDBlock(), SBRunManager::stripTRF(), and SBSolutionBrowser::updateTRF().
const SBMJD& SBProject::tFinis () const [inline]"Returns last date of observations'.
Definition at line 425 of file SbGeoProject.H'.
References TZero, and VLBISessionList.
Referenced by operator<<(), SBProjectSel::ProjectListItem::ProjectListItem(), SBRunManager::SBRunManager(), sinex_SiteEccentricityBlock(), and tInterval().
double SBProject::tInterval () const [inline]"Returns the interval of the observations'.
Definition at line 430 of file SbGeoProject.H'.
References tFinis(), and tStart().
Referenced by SBProjectSel::ProjectListItem::ProjectListItem().
const SBMJD& SBProject::tStart () const [inline]"Returns first date of observations'.
Definition at line 420 of file SbGeoProject.H'.
References TZero, and VLBISessionList.
Referenced by operator<<(), SBProjectSel::ProjectListItem::ProjectListItem(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), sinex_SiteEccentricityBlock(), and tInterval().
int SBProject::version () const [inline]
Definition at line 370 of file SbGeoProject.H'.
References Version.
Referenced by SBProjectSel::ProjectListItem::ProjectListItem(), and SBProjectEdit::SBProjectEdit().
SBVLBISesInfoList* SBProject::VLBIsessionList () [inline]"Returns list of the VLBI sessions;
Definition at line 386 of file SbGeoProject.H'.
References VLBISessionList.
Referenced by SBRunManager::makeReportSessionStatistics(), SBRunManager::prepare4Run_m1(), SBRunManager::prepare4Run_m2(), SBProjectEdit::SBProjectEdit(), sinex_SiteEccentricityBlock(), SBMainWindow::UtilitiesCollectStat4Prj(), and SBSolutionBrowser::wWRMSs().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBProject &P) [friend]"Output to the data stream'.
Definition at line 650 of file SbGeoProject.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBProject &P) [friend]"Input from the data stream'.
Definition at line 659 of file SbGeoProject.C'.
Member Data Documentation
QDict<SBBaseInfo>* SBProject::BaseByAka [protected]
Definition at line 346 of file SbGeoProject.H'.
Referenced by addSession(), baseByAka(), delSession(), fillBaseDict(), SBProject(), and ~SBProject().
SBBaseInfoList SBProject::BaseList [protected]
list of bases
Definition at line 345 of file SbGeoProject.H'.
Referenced by addSession(), baseList(), clearRMSs(), delSession(), fillBaseDict(), numBases(), and SBProject().
SBConfig SBProject::Cfg [protected]
project's config
Definition at line 331 of file SbGeoProject.H'.
Referenced by cfg(), p(), setAllPars2Type(), setCfg(), and setP().
QString SBProject::Comments [protected]
some comments
Definition at line 334 of file SbGeoProject.H'.
Referenced by comments(), and setComments().
SBHistory SBProject::History [protected]
project's history
Definition at line 333 of file SbGeoProject.H'.
Referenced by addHistoryLine(), delHistoryLine(), and history().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
int SBProject::NumObs [protected]
Definition at line 347 of file SbGeoProject.H'.
Referenced by fillSessionDict(), numObs(), and SBProject().
QDict<SBVLBISesInfo>* SBProject::SessionByName [protected]
Definition at line 337 of file SbGeoProject.H'.
Referenced by addSession(), delSession(), fillSessionDict(), SBProject(), sessionByName(), and ~SBProject().
QDict<SBSourceInfo>* SBProject::SourceByAka [protected]
Definition at line 343 of file SbGeoProject.H'.
Referenced by addSession(), delSession(), fillSourceDict(), SBProject(), sourceByAka(), and ~SBProject().
SBSourceInfoList SBProject::SourceList [protected]
list of sources
Definition at line 342 of file SbGeoProject.H'.
Referenced by addSession(), clearRMSs(), delSession(), fillSourceDict(), numSources(), SBProject(), and sourceList().
QDict<SBStationInfo>* SBProject::StationByAka [protected]
Definition at line 340 of file SbGeoProject.H'.
Referenced by addSession(), delSession(), fillStationDict(), SBProject(), stationByAka(), and ~SBProject().
SBStationInfoList SBProject::StationList [protected]
list of stations
Definition at line 339 of file SbGeoProject.H'.
Referenced by addSession(), clearRMSs(), delSession(), fillStationDict(), numStations(), SBProject(), and stationList().
int SBProject::Version [protected]
project's version
Definition at line 332 of file SbGeoProject.H'.
Referenced by addHistoryLine(), incVersion(), SBProject(), and version().
SBVLBISesInfoList SBProject::VLBISessionList [protected]
list of VLBI sessions
Definition at line 336 of file SbGeoProject.H'.
Referenced by addSession(), delSession(), fillSessionDict(), numVLBISessions(), SBProject(), tFinis(), tStart(), and VLBIsessionList().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.