SBProjectCreate
NAME
SBProjectCreate -
SYNOPSIS
#include <SbIProject.H>
Inherits SBVLBISetViewBase'.
Signals
void stBarReset ()
void stBarSetTotalSteps (int)
void stBarSetProgress (int)
void message (const QString &)
void sessionsAdded ()
Public Member Functions
SBProjectCreate (SBProject *=NULL, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBProjectCreate ()
virtual QString ClassName () const
Protected Member Functions
virtual QWidget * VLBIList (QWidget *, BrowseMode, SBProject *)
virtual QWidget * unitsGroup (QWidget *)
virtual QWidget * infoGroup (QWidget *)
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
SBVLBISet * Wvlbi
QString str
SBBrowseSessions * brwsSes
QLabel * LNumSes
QLabel * LNumObs
QLabel * LNumPPS
QRadioButton * RBUnit [3]
bool isModified
int numOpenedWindows
Private Slots
void selChanged (QListViewItem *, bool)
void editEntry (QListViewItem *)
void createProject ()
void selectAll ()
void unselectAll ()
Private Member Functions
virtual void init ()
virtual void drawInfo ()
virtual QWidget * optionsGroup (QWidget *)
Private Attributes
SBProject * Project
int NumObsSel
int NumSessSel
int NumPPSessSel
bool IsProcessing
QLineEdit * EPrjName
Detailed Description
Definition at line 44 of file SbIProject.H'.
Constructor & Destructor Documentation
SBProjectCreate::SBProjectCreate (SBProject *Project_ = NULL, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 57 of file SbIProject.C'.
References init(), IsProcessing, NumObsSel, NumPPSessSel, NumSessSel, and Project.
virtual SBProjectCreate::~SBProjectCreate () [inline, virtual]
Definition at line 49 of file SbIProject.H'.
Member Function Documentation
virtual QString SBProjectCreate::ClassName () const [inline, virtual]
Reimplemented from SBVLBISetViewBase'.
Definition at line 51 of file SbIProject.H'.
Referenced by editEntry().
virtual void SBVLBISetViewBase::closeEvent (QCloseEvent *e) [inline, protected, virtual, inherited]
Definition at line 456 of file SbIObsVLBI.H'.
References SBVLBISetViewBase::numOpenedWindows.
void SBProjectCreate::createProject () [private, slot]
Definition at line 218 of file SbIProject.C'.
References SBProject::addHistoryLine(), SBProject::addSession(), SBVLBISetViewBase::brwsSes, SBSolution::deleteSolution(), EPrjName, IsProcessing, SBBrowseSessions::lvSessions(), message(), SBNamed::name(), NumSessSel, Project, SBSetUp::saveProject(), sessionsAdded(), SBSetUp::setProject(), SetUp, stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), SBBrowseSessions::updateList(), and SBVLBISetViewBase::Wvlbi.
Referenced by init().
void SBProjectCreate::drawInfo () [private, virtual]
Reimplemented from SBVLBISetViewBase'.
Definition at line 170 of file SbIProject.C'.
References SBVLBISetViewBase::brwsSes, SBVLBISetViewBase::LNumObs, SBVLBISetViewBase::LNumPPS, SBVLBISetViewBase::LNumSes, SBBrowseSessions::numObs(), NumObsSel, SBBrowseSessions::numPPSess(), NumPPSessSel, NumSessSel, SBVLBISetViewBase::str, and SBVLBISetViewBase::Wvlbi.
Referenced by selChanged().
void SBProjectCreate::editEntry (QListViewItem *SesItem) [private, slot]
Definition at line 177 of file SbIProject.C'.
References SBVLBISetViewBase::childWindowClosed(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBVLBISetViewBase::modified(), SBVLBISetViewBase::numOpenedWindows, SBLog::write(), and SBVLBISetViewBase::Wvlbi.
QWidget * SBVLBISetViewBase::infoGroup (QWidget *parent) [protected, virtual, inherited]
Definition at line 1828 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, SBVLBISetViewBase::drawInfo(), SBVLBISetViewBase::LNumObs, SBVLBISetViewBase::LNumPPS, SBVLBISetViewBase::LNumSes, SBBrowseSessions::numObs(), SBBrowseSessions::numPPSess(), SBVLBISetViewBase::str, and SBVLBISetViewBase::Wvlbi.
Referenced by init(), and SBVLBISetView::init().
void SBProjectCreate::init () [private, virtual]
Implements SBVLBISetViewBase'.
Definition at line 69 of file SbIProject.C'.
References SBVLBISetViewBase::accept(), BM_PROJECT, SBVLBISetViewBase::brwsSes, createProject(), EPrjName, SBVLBISetViewBase::infoGroup(), SBBrowseSessions::lvSessions(), MainWin, message(), SBNamed::name(), optionsGroup(), Project, SBVLBISetViewBase::reject(), selChanged(), selectAll(), stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), SBVLBISetViewBase::unitsGroup(), unselectAll(), and SBVLBISetViewBase::VLBIList().
Referenced by SBProjectCreate().
void SBProjectCreate::message (const QString &t0) [signal]
Definition at line 161 of file SbIProject.moc.C'.
Referenced by createProject(), and init().
QWidget * SBProjectCreate::optionsGroup (QWidget *parent) [private, virtual]
Reimplemented from SBVLBISetViewBase'.
Definition at line 153 of file SbIProject.C'.
Referenced by init().
void SBProjectCreate::selChanged (QListViewItem *Item, boolsel) [private, slot]
Definition at line 187 of file SbIProject.C'.
References drawInfo(), SBAttributed::isAttr(), SBVLBISesInfo::numObs(), NumObsSel, NumPPSessSel, NumSessSel, and SBVLBISesInfo::preProc.
Referenced by init().
void SBProjectCreate::selectAll () [private, slot]
Definition at line 206 of file SbIProject.C'.
References SBVLBISetViewBase::brwsSes, and SBBrowseSessions::lvSessions().
Referenced by init().
void SBProjectCreate::sessionsAdded () [signal]
Definition at line 167 of file SbIProject.moc.C'.
Referenced by createProject().
void SBProjectCreate::stBarReset () [signal]
Definition at line 143 of file SbIProject.moc.C'.
Referenced by createProject(), and init().
void SBProjectCreate::stBarSetProgress (intt0) [signal]
Definition at line 155 of file SbIProject.moc.C'.
Referenced by createProject(), and init().
void SBProjectCreate::stBarSetTotalSteps (intt0) [signal]
Definition at line 149 of file SbIProject.moc.C'.
Referenced by createProject(), and init().
QWidget * SBVLBISetViewBase::unitsGroup (QWidget *parent) [protected, virtual, inherited]
Definition at line 1803 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::RBUnit, SetUp, SBSetUp::units(), and SBVLBISetViewBase::unitsChanged().
Referenced by init(), and SBVLBISetView::init().
void SBProjectCreate::unselectAll () [private, slot]
Definition at line 212 of file SbIProject.C'.
References SBVLBISetViewBase::brwsSes, and SBBrowseSessions::lvSessions().
Referenced by init().
QWidget * SBVLBISetViewBase::VLBIList (QWidget *parent, BrowseModeMode_, SBProject *Prj) [protected, virtual, inherited]
Reimplemented in SBVLBIPreProcess'.
Definition at line 1793 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, SBBrowseSessions::lvSessions(), and SBVLBISetViewBase::Wvlbi.
Referenced by init(), and SBVLBISetView::init().
Member Data Documentation
SBBrowseSessions* SBVLBISetViewBase::brwsSes [protected, inherited]
Definition at line 441 of file SbIObsVLBI.H'.
Referenced by SBVLBIPreProcess::auxWindowsChanged(), SBVLBIPreProcess::blockInput(), createProject(), SBVLBISetView::deleteEntry(), drawInfo(), SBVLBISetViewBase::drawInfo(), SBVLBISetView::import(), SBVLBISetViewBase::infoGroup(), init(), SBVLBIPreProcess::procScenario_4(), SBVLBIPreProcess::restoreInput(), selectAll(), unselectAll(), SBVLBIPreProcess::VLBIList(), and SBVLBISetViewBase::VLBIList().
QLineEdit* SBProjectCreate::EPrjName [private]
Definition at line 77 of file SbIProject.H'.
Referenced by createProject(), and init().
bool SBVLBISetViewBase::isModified [protected, inherited]
Definition at line 446 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), SBVLBISetView::deleteEntry(), SBVLBISetView::import(), SBVLBISetView::masterRecordModified(), SBVLBISetViewBase::modified(), SBVLBISetView::networksModified(), SBVLBIPreProcess::saveSession(), SBVLBISetViewBase::SBVLBISetViewBase(), SBVLBIPreProcess::toggleEntryMarkEnable(), SBVLBIPreProcess::toggleEntryMoveEnable(), and SBVLBIPreProcess::~SBVLBIPreProcess().
bool SBProjectCreate::IsProcessing [private]
Definition at line 75 of file SbIProject.H'.
Referenced by createProject(), and SBProjectCreate().
QLabel* SBVLBISetViewBase::LNumObs [protected, inherited]
Definition at line 443 of file SbIObsVLBI.H'.
Referenced by drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
QLabel* SBVLBISetViewBase::LNumPPS [protected, inherited]
Definition at line 444 of file SbIObsVLBI.H'.
Referenced by drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
QLabel* SBVLBISetViewBase::LNumSes [protected, inherited]
Definition at line 442 of file SbIObsVLBI.H'.
Referenced by drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
int SBProjectCreate::NumObsSel [private]
Definition at line 72 of file SbIProject.H'.
Referenced by drawInfo(), SBProjectCreate(), and selChanged().
int SBVLBISetViewBase::numOpenedWindows [protected, inherited]
Definition at line 447 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), SBVLBISetView::browseMRecords(), SBVLBISetViewBase::childWindowClosed(), SBVLBISetViewBase::closeEvent(), editEntry(), SBVLBISetView::editEntry(), SBVLBISetView::editNetworks(), SBVLBISetView::import(), SBVLBISetView::masterRecordModified(), SBVLBISetView::networksModified(), SBVLBISetViewBase::reject(), and SBVLBISetViewBase::SBVLBISetViewBase().
int SBProjectCreate::NumPPSessSel [private]
Definition at line 74 of file SbIProject.H'.
Referenced by drawInfo(), SBProjectCreate(), and selChanged().
int SBProjectCreate::NumSessSel [private]
Definition at line 73 of file SbIProject.H'.
Referenced by createProject(), drawInfo(), SBProjectCreate(), and selChanged().
SBProject* SBProjectCreate::Project [private]
Definition at line 70 of file SbIProject.H'.
Referenced by createProject(), init(), and SBProjectCreate().
QRadioButton* SBVLBISetViewBase::RBUnit[3] [protected, inherited]
Definition at line 445 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::unitsGroup().
QString SBVLBISetViewBase::str [protected, inherited]
Definition at line 439 of file SbIObsVLBI.H'.
Referenced by SBVLBISetView::deleteEntry(), drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
SBVLBISet* SBVLBISetViewBase::Wvlbi [protected, inherited]
Definition at line 436 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), SBVLBISetView::browseMRecords(), SBVLBIPreProcess::clearPars(), createProject(), SBVLBIPreProcess::currentSesChange(), SBVLBISetView::deleteEntry(), drawInfo(), SBVLBISetViewBase::drawInfo(), editEntry(), SBVLBISetView::editEntry(), SBVLBISetView::editNetworks(), SBVLBIPreProcess::fillSessAttr(), SBVLBIPreProcess::fixSession(), SBVLBISetView::import(), SBVLBISetViewBase::infoGroup(), SBVLBISetView::networksModified(), SBVLBIPreProcess::preProcess(), SBVLBIPreProcess::saveSession(), SBVLBISetViewBase::SBVLBISetViewBase(), SBVLBIPreProcess::VLBIList(), SBVLBISetViewBase::VLBIList(), SBVLBIPreProcess::wAttributes(), SBVLBIPreProcess::~SBVLBIPreProcess(), and SBVLBISetViewBase::~SBVLBISetViewBase().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.