SBPrec_IAU1976
NAME
SBPrec_IAU1976 -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits SBPrecession'.
Public Member Functions
SBPrec_IAU1976 ()
virtual ~SBPrec_IAU1976 ()
virtual QString ClassName () const
virtual const Matrix3 & operator() (SBTime &)
double zeta () const
double z () const
double theta () const
virtual const Matrix3 & dP_dpsi ()
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Protected Attributes
double Zeta
double Z
double Theta
RotMatrix R1
RotMatrix R2
RotMatrix R3
double mat [3][3]
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
SBPrec_IAU1976'. Calculates precession quantities and the matrix of the precession theory IAU-1976'.
Definition at line 239 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBPrec_IAU1976::SBPrec_IAU1976 ()"A constructor'. Creates a copy of object'.
Definition at line 44 of file SbGeoRefFrame.C'.
References Theta, Z, and Zeta.
virtual SBPrec_IAU1976::~SBPrec_IAU1976 () [inline, virtual]"A destructor'.
Definition at line 254 of file SbGeoRefFrame.H'.
Member Function Documentation
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
virtual QString SBPrec_IAU1976::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBPrecession'.
Definition at line 256 of file SbGeoRefFrame.H'.
Referenced by operator()().
virtual const Matrix3& SBPrec_IAU1976::dP_dpsi () [inline, virtual]
Implements SBPrecession'.
Definition at line 265 of file SbGeoRefFrame.H'.
References R1.
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
const Matrix3 & SBPrec_IAU1976::operator() (SBTime &T) [virtual]"Calculates precession angles and returns matrix corresponds to time T'.
Implements SBPrecession'.
Definition at line 51 of file SbGeoRefFrame.C'.
References RotMatrix::angle(), ClassName(), SBLog::DBG, SBLog::isEligible(), Log, SBLog::NUTATION, SBLog::PRECESSION, R1, R2, R3, Matrix3::report2Log(), SEC2RAD, SBTime::TDB(), TEphem, Theta, SBMJD::toString(), SBTime::TT(), SBLog::write(), Z, and Zeta.
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
double SBPrec_IAU1976::theta () const [inline]"Returns Theta (for debug purposes)'.
Definition at line 264 of file SbGeoRefFrame.H'.
References Theta.
Referenced by SBTestPrecession::createWidget4Test(), and SBTestPrecession::displayValues().
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
double SBPrec_IAU1976::z () const [inline]"Returns Z (for debug purposes)'.
Definition at line 262 of file SbGeoRefFrame.H'.
References Z.
Referenced by SBTestPrecession::createWidget4Test(), and SBTestPrecession::displayValues().
double SBPrec_IAU1976::zeta () const [inline]"Returns Zeta (for debug purposes)'.
Definition at line 260 of file SbGeoRefFrame.H'.
References Zeta.
Referenced by SBTestPrecession::createWidget4Test(), and SBTestPrecession::displayValues().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
RotMatrix SBPrec_IAU1976::R1 [protected]
Definition at line 245 of file SbGeoRefFrame.H'.
Referenced by dP_dpsi(), and operator()().
RotMatrix SBPrec_IAU1976::R2 [protected]
Definition at line 246 of file SbGeoRefFrame.H'.
Referenced by operator()().
RotMatrix SBPrec_IAU1976::R3 [protected]
Definition at line 247 of file SbGeoRefFrame.H'.
Referenced by operator()().
double SBPrec_IAU1976::Theta [protected]
Definition at line 244 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPrec_IAU1976(), and theta().
double SBPrec_IAU1976::Z [protected]
Definition at line 243 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPrec_IAU1976(), and z().
double SBPrec_IAU1976::Zeta [protected]
Definition at line 242 of file SbGeoRefFrame.H'.
Referenced by operator()(), SBPrec_IAU1976(), and zeta().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.