SBProjectSel
NAME
SBProjectSel -
SYNOPSIS
#include <SbIProject.H>
Inherits QDialog'.
Classes
class ProjectListItem
Public Member Functions
SBProjectSel (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBProjectSel ()
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Slots
void accept ()
void reject ()
void remove ()
Private Attributes
QString Str
QListView * lvProject
Detailed Description
Definition at line 158 of file SbIProject.H'.
Constructor & Destructor Documentation
SBProjectSel::SBProjectSel (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 581 of file SbIProject.C'.
References accept(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, lvProject, SBSetUp::path2Proj(), reject(), SetUp, and SBLog::write().
virtual SBProjectSel::~SBProjectSel () [inline, virtual]
Definition at line 163 of file SbIProject.H'.
Member Function Documentation
void SBProjectSel::accept () [private, slot]
Definition at line 677 of file SbIProject.C'.
References lvProject, SBSetUp::setProject(), and SetUp.
Referenced by SBProjectSel().
virtual QString SBProjectSel::ClassName () const [inline, virtual]
Definition at line 165 of file SbIProject.H'.
Referenced by remove(), and SBProjectSel().
virtual void SBProjectSel::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 197 of file SbIProject.H'.
void SBProjectSel::reject () [inline, private, slot]
Definition at line 170 of file SbIProject.H'.
Referenced by SBProjectSel().
void SBProjectSel::remove () [private, slot]
Definition at line 685 of file SbIProject.C'.
References ClassName(), SBLog::DBG, SBLog::IO, Log, lvProject, SBProjectSel::ProjectListItem::name(), SBSetUp::path2Proj(), SetUp, and SBLog::write().
Member Data Documentation
QListView* SBProjectSel::lvProject [private]
Definition at line 195 of file SbIProject.H'.
Referenced by accept(), remove(), and SBProjectSel().
QString SBProjectSel::Str [private]
Definition at line 194 of file SbIProject.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.