SBProjectSel::ProjectListItem
NAME
SBProjectSel::ProjectListItem -
SYNOPSIS
Inherits QListViewItem'.
Public Member Functions
ProjectListItem (QListView *, SBProject *)
virtual QString text (int) const
virtual QString key (int, bool) const
const QString & name ()
Private Attributes
QString Name
SBMJD TStart
SBMJD TFinis
double Interval
int NumObs
int NumSes
int NumSta
int NumBas
int NumSou
int Ver
Detailed Description
Definition at line 174 of file SbIProject.H'.
Constructor & Destructor Documentation
SBProjectSel::ProjectListItem::ProjectListItem (QListView *parent, SBProject *P_)
Definition at line 500 of file SbIProject.C'.
References Interval, Name, SBNamed::name(), NumBas, SBProject::numBases(), NumObs, SBProject::numObs(), NumSes, NumSou, SBProject::numSources(), NumSta, SBProject::numStations(), SBProject::numVLBISessions(), TFinis, SBProject::tFinis(), SBProject::tInterval(), TStart, SBProject::tStart(), Ver, and SBProject::version().
Member Function Documentation
QString SBProjectSel::ProjectListItem::key (intcol, bool) const [virtual]
Definition at line 544 of file SbIProject.C'.
References TmpString.
const QString& SBProjectSel::ProjectListItem::name () [inline]
Definition at line 191 of file SbIProject.H'.
References Name.
Referenced by SBProjectSel::remove().
QString SBProjectSel::ProjectListItem::text (intcol) const [virtual]
Definition at line 515 of file SbIProject.C'.
References SBMJD::F_DDMonYYYY, and TmpString.
Member Data Documentation
double SBProjectSel::ProjectListItem::Interval [private]
Definition at line 180 of file SbIProject.H'.
Referenced by ProjectListItem().
QString SBProjectSel::ProjectListItem::Name [private]
Definition at line 177 of file SbIProject.H'.
Referenced by name(), and ProjectListItem().
int SBProjectSel::ProjectListItem::NumBas [private]
Definition at line 184 of file SbIProject.H'.
Referenced by ProjectListItem().
int SBProjectSel::ProjectListItem::NumObs [private]
Definition at line 181 of file SbIProject.H'.
Referenced by ProjectListItem().
int SBProjectSel::ProjectListItem::NumSes [private]
Definition at line 182 of file SbIProject.H'.
Referenced by ProjectListItem().
int SBProjectSel::ProjectListItem::NumSou [private]
Definition at line 185 of file SbIProject.H'.
Referenced by ProjectListItem().
int SBProjectSel::ProjectListItem::NumSta [private]
Definition at line 183 of file SbIProject.H'.
Referenced by ProjectListItem().
SBMJD SBProjectSel::ProjectListItem::TFinis [private]
Definition at line 179 of file SbIProject.H'.
Referenced by ProjectListItem().
SBMJD SBProjectSel::ProjectListItem::TStart [private]
Definition at line 178 of file SbIProject.H'.
Referenced by ProjectListItem().
int SBProjectSel::ProjectListItem::Ver [private]
Definition at line 186 of file SbIProject.H'.
Referenced by ProjectListItem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.