.TH "SBPrec_IAU2000" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBPrec_IAU2000 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.PP
Inherits \fBSBPrecession\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBPrec_IAU2000\fP ()"
.br
.ti -1c
.RI "virtual \fB~SBPrec_IAU2000\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual const \fBMatrix3\fP & \fBoperator()\fP (\fBSBTime\fP &)"
.br
.ti -1c
.RI "double \fBpsi\fP () const "
.br
.ti -1c
.RI "double \fBomega\fP () const "
.br
.ti -1c
.RI "double \fBchi\fP () const "
.br
.ti -1c
.RI "virtual const \fBMatrix3\fP & \fBdP_dpsi\fP ()"
.br
.ti -1c
.RI "virtual double & \fBoperator()\fP (\fBDIRECTION\fP i, \fBDIRECTION\fP j)"
.br
.ti -1c
.RI "virtual double \fBat\fP (\fBDIRECTION\fP i, \fBDIRECTION\fP j) const "
.br
.ti -1c
.RI "virtual void \fBreport2Log\fP (\fBSBLog::LogLevel\fP, uint, const QString &) const "
.br
.ti -1c
.RI "virtual double \fBmodule\fP () const "
.br
.ti -1c
.RI "virtual void \fBunify\fP ()"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBT\fP () const "
.br
.ti -1c
.RI "\fBMatrix3\fP & \fBoperator+=\fP (const \fBMatrix3\fP &)"
.br
.ti -1c
.RI "\fBMatrix3\fP & \fBoperator-=\fP (const \fBMatrix3\fP &)"
.br
.ti -1c
.RI "\fBMatrix3\fP & \fBoperator*=\fP (double)"
.br
.ti -1c
.RI "\fBMatrix3\fP & \fBoperator/=\fP (double)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBt\fP"
.br
.ti -1c
.RI "double \fBPsi\fP"
.br
.ti -1c
.RI "double \fBOmega\fP"
.br
.ti -1c
.RI "double \fBChi\fP"
.br
.ti -1c
.RI "\fBRotMatrix\fP \fBR1\fP"
.br
.ti -1c
.RI "\fBRotMatrix\fP \fBR2\fP"
.br
.ti -1c
.RI "\fBRotMatrix\fP \fBR3\fP"
.br
.ti -1c
.RI "\fBRotMatrix\fP \fBR4\fP"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBDP_dPsi\fP"
.br
.ti -1c
.RI "double \fBmat\fP [3][3]"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBMatrix3\fP \fBoperator+\fP (const \fBMatrix3\fP &, const \fBMatrix3\fP &)"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBoperator-\fP (const \fBMatrix3\fP &, const \fBMatrix3\fP &)"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBoperator-\fP (const \fBMatrix3\fP &)"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBoperator/\fP (const \fBMatrix3\fP &, double)"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBoperator*\fP (const \fBMatrix3\fP &, double)"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBoperator*\fP (double, const \fBMatrix3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator*\fP (const \fBMatrix3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBoperator*\fP (const \fBMatrix3\fP &, const \fBMatrix3\fP &)"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBoperator~\fP (const \fBMatrix3\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSBPrec_IAU2000\fP'\&. Calculates precession quantities and the matrix of the precession theory IAU-2000(sp?)'\&. 
.PP
Definition at line 277 of file SbGeoRefFrame\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBPrec_IAU2000::SBPrec_IAU2000 ()"A constructor'\&. Creates a copy of object'\&. 
.PP
Definition at line 116 of file SbGeoRefFrame\&.C'\&.
.PP
References Chi, Omega, Psi, and t\&.
.SS "virtual SBPrec_IAU2000::~SBPrec_IAU2000 ()\fC [inline, virtual]\fP"A destructor'\&. 
.PP
Definition at line 296 of file SbGeoRefFrame\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual double Matrix3::at (\fBDIRECTION\fPi, \fBDIRECTION\fPj) const\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 139 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat\&.
.PP
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations()\&.
.SS "double SBPrec_IAU2000::chi () const\fC [inline]\fP"Returns Theta (for debug purposes)'\&. 
.PP
Definition at line 306 of file SbGeoRefFrame\&.H'\&.
.PP
References Chi\&.
.SS "virtual QString SBPrec_IAU2000::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info) 
.PP
Reimplemented from \fBSBPrecession\fP'\&.
.PP
Definition at line 298 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by operator()()\&.
.SS "const \fBMatrix3\fP & SBPrec_IAU2000::dP_dpsi ()\fC [virtual]\fP"
.PP
Implements \fBSBPrecession\fP'\&.
.PP
Definition at line 183 of file SbGeoRefFrame\&.C'\&.
.PP
References DP_dPsi, Psi, R1, R3, R4, t, and Z_AXIS\&.
.SS "double Matrix3::module () const\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 410 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat\&.
.PP
Referenced by operator~(), and Matrix3::unify()\&.
.SS "double SBPrec_IAU2000::omega () const\fC [inline]\fP"Returns Z (for debug purposes)'\&. 
.PP
Definition at line 304 of file SbGeoRefFrame\&.H'\&.
.PP
References Omega\&.
.SS "virtual double& Matrix3::operator() (\fBDIRECTION\fPi, \fBDIRECTION\fPj)\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 138 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat\&.
.SS "const \fBMatrix3\fP & SBPrec_IAU2000::operator() (\fBSBTime\fP &T)\fC [virtual]\fP"Calculates precession angles and returns matrix corresponds to time T'\&. 
.PP
Implements \fBSBPrecession\fP'\&.
.PP
Definition at line 125 of file SbGeoRefFrame\&.C'\&.
.PP
References RotMatrix::angle(), Chi, ClassName(), SBLog::DBG, SBNutation::ephemEps(), SBLog::isEligible(), Log, SBLog::NUTATION, Omega, SBLog::PRECESSION, Psi, R1, R2, R3, R4, Matrix3::report2Log(), SEC2RAD, t, SBTime::TDB(), TEphem, SBMJD::toString(), SBTime::TT(), and SBLog::write()\&.
.SS "\fBMatrix3\fP & Matrix3::operator*= (doublev)\fC [inline, inherited]\fP"
.PP
Definition at line 394 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat\&.
.SS "\fBMatrix3\fP & Matrix3::operator+= (const \fBMatrix3\fP &M)\fC [inline, inherited]\fP"
.PP
Definition at line 378 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat\&.
.SS "\fBMatrix3\fP & Matrix3::operator-= (const \fBMatrix3\fP &M)\fC [inline, inherited]\fP"
.PP
Definition at line 386 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat\&.
.SS "\fBMatrix3\fP & Matrix3::operator/= (doublev)\fC [inline, inherited]\fP"
.PP
Definition at line 402 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat\&.
.PP
Referenced by Matrix3::unify()\&.
.SS "double SBPrec_IAU2000::psi () const\fC [inline]\fP"Returns Zeta (for debug purposes)'\&. 
.PP
Definition at line 302 of file SbGeoRefFrame\&.H'\&.
.PP
References Psi\&.
.SS "void Matrix3::report2Log (\fBSBLog::LogLevel\fPLev, uintFac, const QString &Pref) const\fC [virtual, inherited]\fP"
.PP
Definition at line 76 of file SbVector3\&.C'\&.
.PP
References Log, Matrix3::mat, and SBLog::write()\&.
.PP
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()()\&.
.SS "\fBMatrix3\fP Matrix3::T () const\fC [inline, inherited]\fP"Returns transposed matrix (original matrix does'n change)'\&. 
.PP
Definition at line 418 of file SbVector3\&.H'\&.
.PP
References Matrix3::mat, and Matrix3::Matrix3()\&.
.PP
Referenced by SBDelay::calcDerivatives()\&.
.SS "virtual void Matrix3::unify ()\fC [inline, virtual, inherited]\fP"
.PP
Definition at line 142 of file SbVector3\&.H'\&.
.PP
References Matrix3::module(), and Matrix3::operator/=()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBMatrix3\fP operator* (const \fBMatrix3\fP &M1, doublev2)\fC [friend, inherited]\fP"
.PP
Definition at line 493 of file SbVector3\&.H'\&.
.SS "\fBMatrix3\fP operator* (doublev1, const \fBMatrix3\fP &M2)\fC [friend, inherited]\fP"
.PP
Definition at line 502 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator* (const \fBMatrix3\fP &, const \fBVector3\fP &)\fC [friend, inherited]\fP"
.SS "\fBMatrix3\fP operator* (const \fBMatrix3\fP &M1, const \fBMatrix3\fP &M2)\fC [friend, inherited]\fP"
.PP
Definition at line 59 of file SbVector3\&.C'\&.
.SS "\fBMatrix3\fP operator+ (const \fBMatrix3\fP &M1, const \fBMatrix3\fP &M2)\fC [friend, inherited]\fP"
.PP
Definition at line 450 of file SbVector3\&.H'\&.
.SS "\fBMatrix3\fP operator- (const \fBMatrix3\fP &M1, const \fBMatrix3\fP &M2)\fC [friend, inherited]\fP"
.PP
Definition at line 467 of file SbVector3\&.H'\&.
.SS "\fBMatrix3\fP operator- (const \fBMatrix3\fP &M1)\fC [friend, inherited]\fP"
.PP
Definition at line 433 of file SbVector3\&.H'\&.
.SS "\fBMatrix3\fP operator/ (const \fBMatrix3\fP &M1, doublev2)\fC [friend, inherited]\fP"
.PP
Definition at line 484 of file SbVector3\&.H'\&.
.SS "\fBMatrix3\fP operator~ (const \fBMatrix3\fP &M1)\fC [friend, inherited]\fP"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'\&. 
.PP
Definition at line 95 of file SbVector3\&.C'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBPrec_IAU2000::Chi\fP\fC [protected]\fP"
.PP
Definition at line 283 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by chi(), operator()(), and SBPrec_IAU2000()\&.
.SS "\fBMatrix3\fP \fBSBPrec_IAU2000::DP_dPsi\fP\fC [protected]\fP"
.PP
Definition at line 288 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by dP_dpsi()\&.
.SS "double \fBMatrix3::mat\fP[3][3]\fC [protected, inherited]\fP"
.PP
Definition at line 120 of file SbVector3\&.H'\&.
.PP
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T()\&.
.SS "double \fBSBPrec_IAU2000::Omega\fP\fC [protected]\fP"
.PP
Definition at line 282 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by omega(), operator()(), and SBPrec_IAU2000()\&.
.SS "double \fBSBPrec_IAU2000::Psi\fP\fC [protected]\fP"
.PP
Definition at line 281 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by dP_dpsi(), operator()(), psi(), and SBPrec_IAU2000()\&.
.SS "\fBRotMatrix\fP \fBSBPrec_IAU2000::R1\fP\fC [protected]\fP"
.PP
Definition at line 284 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by dP_dpsi(), and operator()()\&.
.SS "\fBRotMatrix\fP \fBSBPrec_IAU2000::R2\fP\fC [protected]\fP"
.PP
Definition at line 285 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by operator()()\&.
.SS "\fBRotMatrix\fP \fBSBPrec_IAU2000::R3\fP\fC [protected]\fP"
.PP
Definition at line 286 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by dP_dpsi(), and operator()()\&.
.SS "\fBRotMatrix\fP \fBSBPrec_IAU2000::R4\fP\fC [protected]\fP"
.PP
Definition at line 287 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by dP_dpsi(), and operator()()\&.
.SS "double \fBSBPrec_IAU2000::t\fP\fC [protected]\fP"
.PP
Definition at line 280 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by dP_dpsi(), operator()(), and SBPrec_IAU2000()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
