SBProjectEdit
NAME
SBProjectEdit -
SYNOPSIS
#include <SbIProject.H>
Inherits SBTabDialog'.
Signals
void stBarReset ()
void stBarSetTotalSteps (int)
void stBarSetProgress (int)
void message (const QString &)
Public Member Functions
SBProjectEdit (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBProjectEdit ()
virtual QString ClassName () const
Protected Slots
virtual void makeDefaults ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Slots
void modified (bool)
void commentsChanged ()
void childWindowClosed ()
virtual void done (int)
virtual void makeApply ()
virtual void delSession ()
virtual void addSession ()
void sessionListChanged ()
void editEntry (QListViewItem *)
void toggleEntryMarkEnable (QListViewItem *, const QPoint &, int)
void histModified (bool B)
void histVerInced ()
Private Member Functions
virtual void acquireData ()
QWidget * comments ()
Private Attributes
SBVLBISet * Wvlbi
SBProject * Project
bool isModified
bool isCommentsChanged
int numOpenedWindows
QString Str
QMultiLineEdit * mleComments
SBBrowseSessions * brwsSes
SBBrowseStations * brwsSta
SBBrowseSources * brwsSou
SBBrowseBases * brwsBas
SBBrowseHistory * brwsHist
SB_CRF * CRF
Detailed Description
Definition at line 94 of file SbIProject.H'.
Constructor & Destructor Documentation
SBProjectEdit::SBProjectEdit (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 292 of file SbIProject.C'.
References addSession(), SBProject::baseList(), BM_PROJECT, brwsBas, brwsHist, brwsSes, brwsSou, brwsSta, comments(), CRF, delSession(), editEntry(), histModified(), SBProject::history(), histVerInced(), isCommentsChanged, isModified, SBSetUp::loadCRF(), SBSetUp::loadProject(), SBSetUp::loadVLBI(), SBBrowseSessions::lvSessions(), makeApply(), modified(), SBNamed::name(), numOpenedWindows, Project, SetUp, SBProject::sourceList(), SBProject::stationList(), Str, toggleEntryMarkEnable(), SBProject::tStart(), SBProject::version(), SBProject::VLBIsessionList(), and Wvlbi.
SBProjectEdit::~SBProjectEdit () [virtual]
Definition at line 342 of file SbIProject.C'.
References CRF, isModified, Project, SBSetUp::saveProject(), SetUp, and Wvlbi.
Member Function Documentation
void SBProjectEdit::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 439 of file SbIProject.C'.
References isCommentsChanged, isModified, mleComments, Project, and SBProject::setComments().
Referenced by done(), and makeApply().
void SBProjectEdit::addSession () [private, virtual, slot]
Definition at line 430 of file SbIProject.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, Project, sessionListChanged(), and SBLog::write().
Referenced by SBProjectEdit().
void SBProjectEdit::childWindowClosed () [private, slot]
Definition at line 481 of file SbIProject.C'.
References numOpenedWindows.
Referenced by editEntry().
virtual QString SBProjectEdit::ClassName () const [inline, virtual]
Definition at line 101 of file SbIProject.H'.
Referenced by addSession(), delSession(), and makeApply().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
QWidget * SBProjectEdit::comments () [private]
Definition at line 361 of file SbIProject.C'.
References SBProject::comments(), commentsChanged(), mleComments, and Project.
Referenced by SBProjectEdit().
void SBProjectEdit::commentsChanged () [private, slot]
Definition at line 373 of file SbIProject.C'.
References isCommentsChanged, and mleComments.
Referenced by comments().
void SBProjectEdit::delSession () [private, virtual, slot]
Definition at line 396 of file SbIProject.C'.
References brwsSes, ClassName(), SBLog::DBG, SBProject::delSession(), SBLog::INTERFACE, Log, SBBrowseSessions::lvSessions(), SBNamed::name(), Project, SBVLBISesInfoLI::sessionInfo(), sessionListChanged(), SBLog::write(), SBLog::WRN, and Wvlbi.
Referenced by SBProjectEdit().
void SBProjectEdit::done (intr) [private, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 352 of file SbIProject.C'.
References acquireData(), and numOpenedWindows.
void SBProjectEdit::editEntry (QListViewItem *SesItem) [private, slot]
Definition at line 467 of file SbIProject.C'.
References childWindowClosed(), modified(), numOpenedWindows, and Wvlbi.
Referenced by SBProjectEdit().
void SBProjectEdit::histModified (boolB) [inline, private, slot]
Definition at line 126 of file SbIProject.H'.
References isModified.
Referenced by SBProjectEdit().
void SBProjectEdit::histVerInced () [private, slot]
Definition at line 486 of file SbIProject.C'.
References SBProject::incVersion(), isModified, and Project.
Referenced by SBProjectEdit().
void SBProjectEdit::makeApply () [private, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 389 of file SbIProject.C'.
References acquireData(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by SBProjectEdit().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBProjectEdit::message (const QString &t0) [signal]
Definition at line 355 of file SbIProject.moc.C'.
void SBProjectEdit::modified (boolisModified_) [private, slot]
Definition at line 476 of file SbIProject.C'.
References isModified.
Referenced by editEntry(), and SBProjectEdit().
void SBProjectEdit::sessionListChanged () [private, slot]
Definition at line 379 of file SbIProject.C'.
References brwsBas, brwsSes, brwsSou, brwsSta, CRF, isCommentsChanged, isModified, SBBrowseSessions::updateList(), SBBrowseStations::updateList(), SBBrowseSources::updateList(), and SBBrowseBases::updateList().
Referenced by addSession(), and delSession().
void SBProjectEdit::stBarReset () [signal]
Definition at line 337 of file SbIProject.moc.C'.
void SBProjectEdit::stBarSetProgress (intt0) [signal]
Definition at line 349 of file SbIProject.moc.C'.
void SBProjectEdit::stBarSetTotalSteps (intt0) [signal]
Definition at line 343 of file SbIProject.moc.C'.
void SBProjectEdit::toggleEntryMarkEnable (QListViewItem *SesItem, const QPoint &, intn) [private, slot]
Definition at line 448 of file SbIProject.C'.
References SBVLBISesInfo::ConstrEOP, isModified, and SBVLBISesInfo::notValid.
Referenced by SBProjectEdit().
Member Data Documentation
SBBrowseBases* SBProjectEdit::brwsBas [private]
Definition at line 144 of file SbIProject.H'.
Referenced by SBProjectEdit(), and sessionListChanged().
SBBrowseHistory* SBProjectEdit::brwsHist [private]
Definition at line 145 of file SbIProject.H'.
Referenced by SBProjectEdit().
SBBrowseSessions* SBProjectEdit::brwsSes [private]
Definition at line 141 of file SbIProject.H'.
Referenced by delSession(), SBProjectEdit(), and sessionListChanged().
SBBrowseSources* SBProjectEdit::brwsSou [private]
Definition at line 143 of file SbIProject.H'.
Referenced by SBProjectEdit(), and sessionListChanged().
SBBrowseStations* SBProjectEdit::brwsSta [private]
Definition at line 142 of file SbIProject.H'.
Referenced by SBProjectEdit(), and sessionListChanged().
SB_CRF* SBProjectEdit::CRF [private]
Definition at line 147 of file SbIProject.H'.
Referenced by SBProjectEdit(), sessionListChanged(), and ~SBProjectEdit().
bool SBProjectEdit::isCommentsChanged [private]
Definition at line 135 of file SbIProject.H'.
Referenced by acquireData(), commentsChanged(), SBProjectEdit(), and sessionListChanged().
bool SBProjectEdit::isModified [private]
Definition at line 134 of file SbIProject.H'.
Referenced by acquireData(), histModified(), histVerInced(), modified(), SBProjectEdit(), sessionListChanged(), toggleEntryMarkEnable(), and ~SBProjectEdit().
QMultiLineEdit* SBProjectEdit::mleComments [private]
Definition at line 140 of file SbIProject.H'.
Referenced by acquireData(), comments(), and commentsChanged().
int SBProjectEdit::numOpenedWindows [private]
Definition at line 136 of file SbIProject.H'.
Referenced by childWindowClosed(), done(), editEntry(), and SBProjectEdit().
SBProject* SBProjectEdit::Project [private]
Definition at line 133 of file SbIProject.H'.
Referenced by acquireData(), addSession(), comments(), delSession(), histVerInced(), SBProjectEdit(), and ~SBProjectEdit().
QString SBProjectEdit::Str [private]
Definition at line 137 of file SbIProject.H'.
Referenced by SBProjectEdit().
SBVLBISet* SBProjectEdit::Wvlbi [private]
Definition at line 132 of file SbIProject.H'.
Referenced by delSession(), editEntry(), SBProjectEdit(), and ~SBProjectEdit().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.