.TH "SBProjectEdit" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBProjectEdit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIProject\&.H>\fP
.PP
Inherits \fBSBTabDialog\fP'\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstBarReset\fP ()"
.br
.ti -1c
.RI "void \fBstBarSetTotalSteps\fP (int)"
.br
.ti -1c
.RI "void \fBstBarSetProgress\fP (int)"
.br
.ti -1c
.RI "void \fBmessage\fP (const QString &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBProjectEdit\fP (\fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "virtual \fB~SBProjectEdit\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBmakeDefaults\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *)"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBmodified\fP (bool)"
.br
.ti -1c
.RI "void \fBcommentsChanged\fP ()"
.br
.ti -1c
.RI "void \fBchildWindowClosed\fP ()"
.br
.ti -1c
.RI "virtual void \fBdone\fP (int)"
.br
.ti -1c
.RI "virtual void \fBmakeApply\fP ()"
.br
.ti -1c
.RI "virtual void \fBdelSession\fP ()"
.br
.ti -1c
.RI "virtual void \fBaddSession\fP ()"
.br
.ti -1c
.RI "void \fBsessionListChanged\fP ()"
.br
.ti -1c
.RI "void \fBeditEntry\fP (\fBQListViewItem\fP *)"
.br
.ti -1c
.RI "void \fBtoggleEntryMarkEnable\fP (\fBQListViewItem\fP *, const QPoint &, int)"
.br
.ti -1c
.RI "void \fBhistModified\fP (bool B)"
.br
.ti -1c
.RI "void \fBhistVerInced\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBacquireData\fP ()"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBcomments\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBVLBISet\fP * \fBWvlbi\fP"
.br
.ti -1c
.RI "\fBSBProject\fP * \fBProject\fP"
.br
.ti -1c
.RI "bool \fBisModified\fP"
.br
.ti -1c
.RI "bool \fBisCommentsChanged\fP"
.br
.ti -1c
.RI "int \fBnumOpenedWindows\fP"
.br
.ti -1c
.RI "QString \fBStr\fP"
.br
.ti -1c
.RI "\fBQMultiLineEdit\fP * \fBmleComments\fP"
.br
.ti -1c
.RI "\fBSBBrowseSessions\fP * \fBbrwsSes\fP"
.br
.ti -1c
.RI "\fBSBBrowseStations\fP * \fBbrwsSta\fP"
.br
.ti -1c
.RI "\fBSBBrowseSources\fP * \fBbrwsSou\fP"
.br
.ti -1c
.RI "\fBSBBrowseBases\fP * \fBbrwsBas\fP"
.br
.ti -1c
.RI "\fBSBBrowseHistory\fP * \fBbrwsHist\fP"
.br
.ti -1c
.RI "\fBSB_CRF\fP * \fBCRF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file SbIProject\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBProjectEdit::SBProjectEdit (\fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 292 of file SbIProject\&.C'\&.
.PP
References addSession(), SBProject::baseList(), BM_PROJECT, brwsBas, brwsHist, brwsSes, brwsSou, brwsSta, comments(), CRF, delSession(), editEntry(), histModified(), SBProject::history(), histVerInced(), isCommentsChanged, isModified, SBSetUp::loadCRF(), SBSetUp::loadProject(), SBSetUp::loadVLBI(), SBBrowseSessions::lvSessions(), makeApply(), modified(), SBNamed::name(), numOpenedWindows, Project, SetUp, SBProject::sourceList(), SBProject::stationList(), Str, toggleEntryMarkEnable(), SBProject::tStart(), SBProject::version(), SBProject::VLBIsessionList(), and Wvlbi\&.
.SS "SBProjectEdit::~SBProjectEdit ()\fC [virtual]\fP"
.PP
Definition at line 342 of file SbIProject\&.C'\&.
.PP
References CRF, isModified, Project, SBSetUp::saveProject(), SetUp, and Wvlbi\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBProjectEdit::acquireData ()\fC [private, virtual]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 439 of file SbIProject\&.C'\&.
.PP
References isCommentsChanged, isModified, mleComments, Project, and SBProject::setComments()\&.
.PP
Referenced by done(), and makeApply()\&.
.SS "void SBProjectEdit::addSession ()\fC [private, virtual, slot]\fP"
.PP
Definition at line 430 of file SbIProject\&.C'\&.
.PP
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, Project, sessionListChanged(), and SBLog::write()\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "void SBProjectEdit::childWindowClosed ()\fC [private, slot]\fP"
.PP
Definition at line 481 of file SbIProject\&.C'\&.
.PP
References numOpenedWindows\&.
.PP
Referenced by editEntry()\&.
.SS "virtual QString SBProjectEdit::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 101 of file SbIProject\&.H'\&.
.PP
Referenced by addSession(), delSession(), and makeApply()\&.
.SS "virtual void SBTabDialog::closeEvent (QCloseEvent *)\fC [inline, protected, virtual, inherited]\fP"
.PP
Reimplemented in \fBSBSiteEditor\fP, and \fBSBParametersEditor\fP'\&.
.PP
Definition at line 90 of file SbInterface\&.H'\&.
.SS "\fBQWidget\fP * SBProjectEdit::comments ()\fC [private]\fP"
.PP
Definition at line 361 of file SbIProject\&.C'\&.
.PP
References SBProject::comments(), commentsChanged(), mleComments, and Project\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "void SBProjectEdit::commentsChanged ()\fC [private, slot]\fP"
.PP
Definition at line 373 of file SbIProject\&.C'\&.
.PP
References isCommentsChanged, and mleComments\&.
.PP
Referenced by comments()\&.
.SS "void SBProjectEdit::delSession ()\fC [private, virtual, slot]\fP"
.PP
Definition at line 396 of file SbIProject\&.C'\&.
.PP
References brwsSes, ClassName(), SBLog::DBG, SBProject::delSession(), SBLog::INTERFACE, Log, SBBrowseSessions::lvSessions(), SBNamed::name(), Project, SBVLBISesInfoLI::sessionInfo(), sessionListChanged(), SBLog::write(), SBLog::WRN, and Wvlbi\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "void SBProjectEdit::done (intr)\fC [private, virtual, slot]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 352 of file SbIProject\&.C'\&.
.PP
References acquireData(), and numOpenedWindows\&.
.SS "void SBProjectEdit::editEntry (\fBQListViewItem\fP *SesItem)\fC [private, slot]\fP"
.PP
Definition at line 467 of file SbIProject\&.C'\&.
.PP
References childWindowClosed(), modified(), numOpenedWindows, and Wvlbi\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "void SBProjectEdit::histModified (boolB)\fC [inline, private, slot]\fP"
.PP
Definition at line 126 of file SbIProject\&.H'\&.
.PP
References isModified\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "void SBProjectEdit::histVerInced ()\fC [private, slot]\fP"
.PP
Definition at line 486 of file SbIProject\&.C'\&.
.PP
References SBProject::incVersion(), isModified, and Project\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "void SBProjectEdit::makeApply ()\fC [private, virtual, slot]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 389 of file SbIProject\&.C'\&.
.PP
References acquireData(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write()\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "virtual void SBTabDialog::makeDefaults ()\fC [inline, protected, virtual, slot, inherited]\fP"
.PP
Reimplemented in \fBSBSetupDialog\fP'\&.
.PP
Definition at line 79 of file SbInterface\&.H'\&.
.SS "void SBProjectEdit::message (const QString &t0)\fC [signal]\fP"
.PP
Definition at line 355 of file SbIProject\&.moc\&.C'\&.
.SS "void SBProjectEdit::modified (boolisModified_)\fC [private, slot]\fP"
.PP
Definition at line 476 of file SbIProject\&.C'\&.
.PP
References isModified\&.
.PP
Referenced by editEntry(), and SBProjectEdit()\&.
.SS "void SBProjectEdit::sessionListChanged ()\fC [private, slot]\fP"
.PP
Definition at line 379 of file SbIProject\&.C'\&.
.PP
References brwsBas, brwsSes, brwsSou, brwsSta, CRF, isCommentsChanged, isModified, SBBrowseSessions::updateList(), SBBrowseStations::updateList(), SBBrowseSources::updateList(), and SBBrowseBases::updateList()\&.
.PP
Referenced by addSession(), and delSession()\&.
.SS "void SBProjectEdit::stBarReset ()\fC [signal]\fP"
.PP
Definition at line 337 of file SbIProject\&.moc\&.C'\&.
.SS "void SBProjectEdit::stBarSetProgress (intt0)\fC [signal]\fP"
.PP
Definition at line 349 of file SbIProject\&.moc\&.C'\&.
.SS "void SBProjectEdit::stBarSetTotalSteps (intt0)\fC [signal]\fP"
.PP
Definition at line 343 of file SbIProject\&.moc\&.C'\&.
.SS "void SBProjectEdit::toggleEntryMarkEnable (\fBQListViewItem\fP *SesItem, const QPoint &, intn)\fC [private, slot]\fP"
.PP
Definition at line 448 of file SbIProject\&.C'\&.
.PP
References SBVLBISesInfo::ConstrEOP, isModified, and SBVLBISesInfo::notValid\&.
.PP
Referenced by SBProjectEdit()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBBrowseBases\fP* \fBSBProjectEdit::brwsBas\fP\fC [private]\fP"
.PP
Definition at line 144 of file SbIProject\&.H'\&.
.PP
Referenced by SBProjectEdit(), and sessionListChanged()\&.
.SS "\fBSBBrowseHistory\fP* \fBSBProjectEdit::brwsHist\fP\fC [private]\fP"
.PP
Definition at line 145 of file SbIProject\&.H'\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "\fBSBBrowseSessions\fP* \fBSBProjectEdit::brwsSes\fP\fC [private]\fP"
.PP
Definition at line 141 of file SbIProject\&.H'\&.
.PP
Referenced by delSession(), SBProjectEdit(), and sessionListChanged()\&.
.SS "\fBSBBrowseSources\fP* \fBSBProjectEdit::brwsSou\fP\fC [private]\fP"
.PP
Definition at line 143 of file SbIProject\&.H'\&.
.PP
Referenced by SBProjectEdit(), and sessionListChanged()\&.
.SS "\fBSBBrowseStations\fP* \fBSBProjectEdit::brwsSta\fP\fC [private]\fP"
.PP
Definition at line 142 of file SbIProject\&.H'\&.
.PP
Referenced by SBProjectEdit(), and sessionListChanged()\&.
.SS "\fBSB_CRF\fP* \fBSBProjectEdit::CRF\fP\fC [private]\fP"
.PP
Definition at line 147 of file SbIProject\&.H'\&.
.PP
Referenced by SBProjectEdit(), sessionListChanged(), and ~SBProjectEdit()\&.
.SS "bool \fBSBProjectEdit::isCommentsChanged\fP\fC [private]\fP"
.PP
Definition at line 135 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), commentsChanged(), SBProjectEdit(), and sessionListChanged()\&.
.SS "bool \fBSBProjectEdit::isModified\fP\fC [private]\fP"
.PP
Definition at line 134 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), histModified(), histVerInced(), modified(), SBProjectEdit(), sessionListChanged(), toggleEntryMarkEnable(), and ~SBProjectEdit()\&.
.SS "\fBQMultiLineEdit\fP* \fBSBProjectEdit::mleComments\fP\fC [private]\fP"
.PP
Definition at line 140 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), comments(), and commentsChanged()\&.
.SS "int \fBSBProjectEdit::numOpenedWindows\fP\fC [private]\fP"
.PP
Definition at line 136 of file SbIProject\&.H'\&.
.PP
Referenced by childWindowClosed(), done(), editEntry(), and SBProjectEdit()\&.
.SS "\fBSBProject\fP* \fBSBProjectEdit::Project\fP\fC [private]\fP"
.PP
Definition at line 133 of file SbIProject\&.H'\&.
.PP
Referenced by acquireData(), addSession(), comments(), delSession(), histVerInced(), SBProjectEdit(), and ~SBProjectEdit()\&.
.SS "QString \fBSBProjectEdit::Str\fP\fC [private]\fP"
.PP
Definition at line 137 of file SbIProject\&.H'\&.
.PP
Referenced by SBProjectEdit()\&.
.SS "\fBSBVLBISet\fP* \fBSBProjectEdit::Wvlbi\fP\fC [private]\fP"
.PP
Definition at line 132 of file SbIProject\&.H'\&.
.PP
Referenced by delSession(), editEntry(), SBProjectEdit(), and ~SBProjectEdit()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
