.TH "SBRefraction" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBRefraction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefraction\&.H>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBRefraction\fP (const \fBSBConfig\fP *)"
.br
.ti -1c
.RI "virtual \fB~SBRefraction\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual double \fBelev\fP () const "
.br
.ti -1c
.RI "virtual double \fBrefrElev\fP () const "
.br
.ti -1c
.RI "virtual double \fBazimuth\fP () const "
.br
.ti -1c
.RI "virtual double \fBwetMap\fP () const "
.br
.ti -1c
.RI "virtual double \fBgradMap\fP () const "
.br
.ti -1c
.RI "virtual double \fBtotZenithDelay\fP () const "
.br
.ti -1c
.RI "virtual const \fBVector3\fP & \fBrefrSource\fP () const "
.br
.ti -1c
.RI "virtual double \fBoperator()\fP (float, float, float, const \fBSBFrame\fP *, \fBSBStation\fP *, const \fBSBSource\fP *, const \fBVector3\fP &, double, bool)"
.br
.ti -1c
.RI "void \fBmakeDebugReport\fP (const \fBSBMJD\fP &, \fBSBStation\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual const \fBVector3\fP \fBrefrDir\fP (float, double, double, const \fBSBStation\fP *, const \fBSBSource\fP *, const \fBVector3\fP &)"
.br
.ti -1c
.RI "virtual double \fBaltitudeCorr\fP (float, double, double, const \fBSBStation\fP *, const \fBSBSource\fP *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBSBConfig\fP * \fBCfg\fP"
.br
.ti -1c
.RI "\fBSBZenithDelay\fP * \fBDryZDelay\fP"
.br
.ti -1c
.RI "\fBSBZenithDelay\fP * \fBWetZDelay\fP"
.br
.ti -1c
.RI "\fBSBMappingFunc\fP * \fBDryMapping\fP"
.br
.ti -1c
.RI "\fBSBMappingFunc\fP * \fBWetMapping\fP"
.br
.ti -1c
.RI "\fBSBMappingFunc\fP * \fBAltDryMapping\fP"
.br
.ti -1c
.RI "\fBSBMappingFunc\fP * \fBAltWetMapping\fP"
.br
.ti -1c
.RI "\fBSBMappingFunc\fP * \fBGradMapping\fP"
.br
.ti -1c
.RI "double \fBWetMap\fP"
.br
.ti -1c
.RI "double \fBGradMap\fP"
.br
.ti -1c
.RI "double \fBElev\fP"
.br
.RI "\fIantenna's elevation angle \fP"
.ti -1c
.RI "double \fBRefrElev\fP"
.br
.RI "\fIantenna's elevation angle with refraction \fP"
.ti -1c
.RI "double \fBdE\fP"
.br
.RI "\fIcorrection of the antenna's elevation angle w/refr \fP"
.ti -1c
.RI "double \fBDelta\fP"
.br
.RI "\fIthe troposphere scale height, m \fP"
.ti -1c
.RI "double \fBAzimuth\fP"
.br
.RI "\fIantenna's azimuth \fP"
.ti -1c
.RI "double \fBTotZenithDelay\fP"
.br
.RI "\fItotal zenith delay, m \fP"
.ti -1c
.RI "\fBVector3\fP \fBRefrSource\fP"
.br
.RI "\fIunit vector to the refracted source \fP"
.in -1c
.SH "Detailed Description"
.PP 
Refraction'\&. Implements calculations of the refraction and related effects'\&. 
.PP
Definition at line 358 of file SbGeoRefraction\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBRefraction::SBRefraction (const \fBSBConfig\fP *Cfg_)"A constructor'\&. 
.PP
Definition at line 575 of file SbGeoRefraction\&.C'\&.
.PP
References AltDryMapping, AltWetMapping, Azimuth, Cfg, dE, Delta, DryMapping, DryZDelay, Elev, GradMapping, SBConfig::isRollBack2NMF(), SBConfig::RDM_CfA2p2, SBConfig::RDM_Chao, SBConfig::RDM_Ifadis, SBConfig::RDM_MTT, SBConfig::RDM_NMFH2, SBConfig::RDM_NMFW2, SBConfig::RDM_NONE, SBConfig::RDZ_Hopfield, SBConfig::RDZ_NONE, SBConfig::RDZ_Saastamoinen, SBConfig::refrDryMapping(), SBConfig::refrDryZenith(), RefrElev, SBConfig::refrWetMapping(), SBConfig::refrWetZenith(), SBConfig::RWM_Chao, SBConfig::RWM_Ifadis, SBConfig::RWM_MTT, SBConfig::RWM_NONE, SBConfig::RWZ_Hopfield, SBConfig::RWZ_NONE, SBConfig::RWZ_Saastamoinen, TotZenithDelay, WetMapping, and WetZDelay\&.
.SS "SBRefraction::~SBRefraction ()\fC [virtual]\fP"A destructor'\&. 
.PP
Definition at line 634 of file SbGeoRefraction\&.C'\&.
.PP
References AltDryMapping, AltWetMapping, DryMapping, DryZDelay, GradMapping, WetMapping, and WetZDelay\&.
.SH "Member Function Documentation"
.PP 
.SS "double SBRefraction::altitudeCorr (float, doubleDryZD, doubleStarTime, const \fBSBStation\fP *Station, const \fBSBSource\fP *Source)\fC [protected, virtual]\fP"Antenna axiss offset altitude correction'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIT\fP is an atmospheric temperature, C; 
.br
\fIDryZD\fP is a hydrostatic zenith delay, m; 
.br
\fIStarTime\fP is a GMST, rad; 
.br
\fIStation\fP is a pointer to the \fBSBStation\fP'\&. 
.br
\fISource\fP is a pointer to the \fBSBSource\fP'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
axiss offset altitude correction to hydrostatic zenith delay, meter'\&. 
.RE
.PP

.PP
Definition at line 728 of file SbGeoRefraction\&.C'\&.
.PP
References SBStation::axisOffset(), azimuth(), DEG2RAD, Delta, SBStation::latitude(), SBStation::longitude(), SBStation::Mnt_AZEL, SBStation::Mnt_EQUA, SBStation::Mnt_Richmond, SBStation::Mnt_Unkn, SBStation::Mnt_X_YE, SBStation::Mnt_X_YN, SBStation::mountType(), SBSource::ra_t(), refrElev(), and sincos()\&.
.PP
Referenced by operator()()\&.
.SS "virtual double SBRefraction::azimuth () const\fC [inline, virtual]\fP"
.PP
Definition at line 389 of file SbGeoRefraction\&.H'\&.
.PP
References Azimuth\&.
.PP
Referenced by altitudeCorr(), and SBDelay::calc()\&.
.SS "virtual QString SBRefraction::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info) 
.PP
Definition at line 386 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), and refrDir()\&.
.SS "virtual double SBRefraction::elev () const\fC [inline, virtual]\fP"
.PP
Definition at line 387 of file SbGeoRefraction\&.H'\&.
.PP
References Elev\&.
.PP
Referenced by operator()()\&.
.SS "virtual double SBRefraction::gradMap () const\fC [inline, virtual]\fP"
.PP
Definition at line 391 of file SbGeoRefraction\&.H'\&.
.PP
References GradMap\&.
.PP
Referenced by SBDelay::calc()\&.
.SS "void SBRefraction::makeDebugReport (const \fBSBMJD\fP &, \fBSBStation\fP *)"
.PP
Definition at line 889 of file SbGeoRefraction\&.C'\&.
.PP
References Elev, SBMJD::F_UNIX, RAD2DEG, and RefrElev\&.
.PP
Referenced by SBDelay::calc()\&.
.SS "double SBRefraction::operator() (floatT, floatP, floatRH, const \fBSBFrame\fP *Frame, \fBSBStation\fP *Station, const \fBSBSource\fP *Source, const \fBVector3\fP &S, doubleZw_, boolIsWrongMetheo)\fC [virtual]\fP"Calcs refraction delay'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIT\fP is an atmospheric temperature, C; 
.br
\fIP\fP is an atmospheric pressure, mbar; 
.br
\fIRH\fP is an atmospheric relative humidity, %; 
.br
\fIFrame\fP is a pointer to the \fBSBFrame\fP; 
.br
\fIStation\fP is a pointer to the \fBSBStation\fP; 
.br
\fISource\fP is a pointer to the \fBSBSource\fP; 
.br
\fIS\fP is a TRS vector of the radiosource, abberated; 
.br
\fIZw_\fP is a predicted wet zenith delay; 
.br
\fIIsWrongMetheo\fP is set to TRUE if a station has bad or suspicious metheo parameters'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
refraction delay, meter'\&. 
.RE
.PP

.PP
Definition at line 782 of file SbGeoRefraction\&.C'\&.
.PP
References AltDryMapping, altitudeCorr(), AltWetMapping, Azimuth, Cfg, SBZenithDelay::ClassName(), SBMappingFunc::ClassName(), ClassName(), SBLog::DBG, dE, Delta, DryMapping, DryZDelay, Elev, elev(), SBFrame::gmst(), GradMap, SBStation::id(), SBConfig::isAltAxsCorr(), SBLog::isEligible(), Log, SBNamed::name(), SBStation::p_AtmGradE(), SBStation::p_AtmGradN(), SBStation::p_Zenith(), rad2dmslStr(), rad2dmsStr(), SBLog::REFRACT, refrDir(), RefrElev, RefrSource, Vector3::report2Log(), SBFrame::time(), SBMJD::toString(), SBStationID::toString(), TotZenithDelay, SBParameter::v(), SBZenithDelay::vapourPress(), WetMap, WetMapping, WetZDelay, and SBLog::write()\&.
.SS "const \fBVector3\fP SBRefraction::refrDir (floatT, doubleDryZD, doubleWetZD, const \fBSBStation\fP *Station, const \fBSBSource\fP *Source, const \fBVector3\fP &S)\fC [protected, virtual]\fP"Calcs refracted antenna's direction in TRF'\&. This function calulates angles of azimuth and refracted elevation of an antenna direction too'\&. It has to be called after zenith delays calculation and before mapping functions'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIT\fP is an atmospheric temperature, C; 
.br
\fIDryZD\fP is a hydrostatic zenith delay, m; 
.br
\fIWetZD\fP is a wet zenith delay, m; 
.br
\fIStation\fP is a pointer to the \fBSBStation\fP; 
.br
\fIS\fP is a TRS vector of the radiosource, abberated'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
antenna's direction in TRF corrected for refraction'\&. 
.RE
.PP

.PP
Definition at line 684 of file SbGeoRefraction\&.C'\&.
.PP
References Vector3::at(), Azimuth, ClassName(), dE, Delta, EAST, Elev, SBLog::ERR, SBStation::fmVEN(), Log, SBNamed::name(), NORT, SBLog::REFRACT, RefrElev, sincos(), VERT, and SBLog::write()\&.
.PP
Referenced by operator()()\&.
.SS "virtual double SBRefraction::refrElev () const\fC [inline, virtual]\fP"
.PP
Definition at line 388 of file SbGeoRefraction\&.H'\&.
.PP
References RefrElev\&.
.PP
Referenced by altitudeCorr()\&.
.SS "virtual const \fBVector3\fP& SBRefraction::refrSource () const\fC [inline, virtual]\fP"Returns unit vector in refracted source direction, TRF'\&. 
.PP
Definition at line 394 of file SbGeoRefraction\&.H'\&.
.PP
References RefrSource\&.
.PP
Referenced by SBDelay::calc()\&.
.SS "virtual double SBRefraction::totZenithDelay () const\fC [inline, virtual]\fP"
.PP
Definition at line 392 of file SbGeoRefraction\&.H'\&.
.PP
References TotZenithDelay\&.
.PP
Referenced by SBDelay::calc()\&.
.SS "virtual double SBRefraction::wetMap () const\fC [inline, virtual]\fP"
.PP
Definition at line 390 of file SbGeoRefraction\&.H'\&.
.PP
References WetMap\&.
.PP
Referenced by SBDelay::calc()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBMappingFunc\fP* \fBSBRefraction::AltDryMapping\fP\fC [protected]\fP"
.PP
Definition at line 366 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), SBRefraction(), and ~SBRefraction()\&.
.SS "\fBSBMappingFunc\fP* \fBSBRefraction::AltWetMapping\fP\fC [protected]\fP"
.PP
Definition at line 367 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), SBRefraction(), and ~SBRefraction()\&.
.SS "double \fBSBRefraction::Azimuth\fP\fC [protected]\fP"
.PP
antenna's azimuth 
.PP
Definition at line 375 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by azimuth(), operator()(), refrDir(), and SBRefraction()\&.
.SS "const \fBSBConfig\fP* \fBSBRefraction::Cfg\fP\fC [protected]\fP"
.PP
Definition at line 361 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), and SBRefraction()\&.
.SS "double \fBSBRefraction::dE\fP\fC [protected]\fP"
.PP
correction of the antenna's elevation angle w/refr 
.PP
Definition at line 373 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), refrDir(), and SBRefraction()\&.
.SS "double \fBSBRefraction::Delta\fP\fC [protected]\fP"
.PP
the troposphere scale height, m 
.PP
Definition at line 374 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by altitudeCorr(), operator()(), refrDir(), and SBRefraction()\&.
.SS "\fBSBMappingFunc\fP* \fBSBRefraction::DryMapping\fP\fC [protected]\fP"
.PP
Definition at line 364 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), SBRefraction(), and ~SBRefraction()\&.
.SS "\fBSBZenithDelay\fP* \fBSBRefraction::DryZDelay\fP\fC [protected]\fP"
.PP
Definition at line 362 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), SBRefraction(), and ~SBRefraction()\&.
.SS "double \fBSBRefraction::Elev\fP\fC [protected]\fP"
.PP
antenna's elevation angle 
.PP
Definition at line 371 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by elev(), makeDebugReport(), operator()(), refrDir(), and SBRefraction()\&.
.SS "double \fBSBRefraction::GradMap\fP\fC [protected]\fP"
.PP
Definition at line 370 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by gradMap(), and operator()()\&.
.SS "\fBSBMappingFunc\fP* \fBSBRefraction::GradMapping\fP\fC [protected]\fP"
.PP
Definition at line 368 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by SBRefraction(), and ~SBRefraction()\&.
.SS "double \fBSBRefraction::RefrElev\fP\fC [protected]\fP"
.PP
antenna's elevation angle with refraction 
.PP
Definition at line 372 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by makeDebugReport(), operator()(), refrDir(), refrElev(), and SBRefraction()\&.
.SS "\fBVector3\fP \fBSBRefraction::RefrSource\fP\fC [protected]\fP"
.PP
unit vector to the refracted source 
.PP
Definition at line 377 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), and refrSource()\&.
.SS "double \fBSBRefraction::TotZenithDelay\fP\fC [protected]\fP"
.PP
total zenith delay, m 
.PP
Definition at line 376 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), SBRefraction(), and totZenithDelay()\&.
.SS "double \fBSBRefraction::WetMap\fP\fC [protected]\fP"
.PP
Definition at line 369 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), and wetMap()\&.
.SS "\fBSBMappingFunc\fP* \fBSBRefraction::WetMapping\fP\fC [protected]\fP"
.PP
Definition at line 365 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), SBRefraction(), and ~SBRefraction()\&.
.SS "\fBSBZenithDelay\fP* \fBSBRefraction::WetZDelay\fP\fC [protected]\fP"
.PP
Definition at line 363 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()(), SBRefraction(), and ~SBRefraction()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
