SBReferencePoint
NAME
SBReferencePoint -
SYNOPSIS
#include <SbGeoStations.H>
Inherits QList< SBCoordinates >'.
Public Member Functions
SBReferencePoint ()
SBReferencePoint (const SBReferencePoint &)
virtual ~SBReferencePoint ()
QString ClassName () const
SBReferencePoint & operator= (const SBReferencePoint &)
SBCoordinates * findCoords (const SBMJD &)
bool registerCoords (const Vector3 &, const Vector3 &, const Vector3 &, const Vector3 &, const SBMJD &, const QString &)
const Vector3 & r (const SBMJD &)
const Vector3 & dR (const SBMJD &)
const Vector3 & v (const SBMJD &)
const Vector3 & dV (const SBMJD &)
const Vector3 & r_0 () const
const Vector3 & dR_0 () const
const Vector3 & v_0 () const
const Vector3 & dV_0 () const
void checkRanges ()
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Protected Attributes
const Vector3 * R_0
const Vector3 * DR_0
const Vector3 * V_0
const Vector3 * DV_0
Friends
QDataStream & operator<< (QDataStream &s, const SBReferencePoint &RP_)
QDataStream & operator>> (QDataStream &s, SBReferencePoint &RP_)
Detailed Description
Definition at line 388 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBReferencePoint::SBReferencePoint () [inline]
Definition at line 410 of file SbGeoStations.H'.
References DR_0, DV_0, R_0, and V_0.
SBReferencePoint::SBReferencePoint (const SBReferencePoint &RP_)
Definition at line 380 of file SbGeoStations.C'.
References checkRanges().
virtual SBReferencePoint::~SBReferencePoint () [inline, virtual]
Definition at line 412 of file SbGeoStations.H'.
Member Function Documentation
void SBReferencePoint::checkRanges ()
Definition at line 491 of file SbGeoStations.C'.
References DR_0, DV_0, R_0, and V_0.
Referenced by operator=(), registerCoords(), and SBReferencePoint().
QString SBReferencePoint::ClassName () const [inline]
Definition at line 413 of file SbGeoStations.H'.
virtual int SBReferencePoint::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 391 of file SbGeoStations.H'.
const Vector3 & SBReferencePoint::dR (const SBMJD &t)
Definition at line 473 of file SbGeoStations.C'.
References SBCoordinates::cooErrors(), findCoords(), and v3Zero.
Referenced by SBStation::dR().
const Vector3& SBReferencePoint::dR_0 () const [inline]
Definition at line 429 of file SbGeoStations.H'.
References DR_0, and v3Zero.
Referenced by SBStation::dR_first().
const Vector3 & SBReferencePoint::dV (const SBMJD &t)
Definition at line 485 of file SbGeoStations.C'.
References findCoords(), v3Zero, and SBCoordinates::velErrors().
const Vector3& SBReferencePoint::dV_0 () const [inline]
Definition at line 431 of file SbGeoStations.H'.
References DV_0, and v3Zero.
SBCoordinates * SBReferencePoint::findCoords (const SBMJD &T)
Definition at line 417 of file SbGeoStations.C'.
Referenced by dR(), dV(), r(), registerCoords(), and v().
SBReferencePoint & SBReferencePoint::operator= (const SBReferencePoint &RP)
Definition at line 399 of file SbGeoStations.C'.
References checkRanges().
const Vector3 & SBReferencePoint::r (const SBMJD &t)
Definition at line 467 of file SbGeoStations.C'.
References SBCoordinates::coo(), findCoords(), and v3Zero.
Referenced by SBStation::calcDisplacement(), SBStation::getGlobalParameters4Report(), operator>>(), SBStation::r(), and SBStation::updateGeodCoo().
const Vector3& SBReferencePoint::r_0 () const [inline]
Definition at line 428 of file SbGeoStations.H'.
References R_0, and v3Zero.
Referenced by SBStation::r_first().
virtual QDataStream& SBReferencePoint::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 399 of file SbGeoStations.H'.
bool SBReferencePoint::registerCoords (const Vector3 &R_, const Vector3 &dR_, const Vector3 &V_, const Vector3 &dV_, const SBMJD &T_, const QString &Name_)
Definition at line 431 of file SbGeoStations.C'.
References checkRanges(), SBCoordinates::coo(), SBCoordinates::cooErrors(), DR_0, DV_0, SBCoordinates::epoch(), findCoords(), R_0, SBCoordinates::setCoo(), SBCoordinates::setCooErrors(), SBCoordinates::setEventName(), SBCoordinates::setVel(), SBCoordinates::setVelErrors(), v3Zero, V_0, SBCoordinates::vel(), and SBCoordinates::velErrors().
Referenced by SBStation::setCoords().
const Vector3 & SBReferencePoint::v (const SBMJD &t)
Definition at line 479 of file SbGeoStations.C'.
References findCoords(), SBCoordinates::isUseVels(), v3Zero, and SBCoordinates::vel().
Referenced by SBStation::calcDisplacement(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), and SBStation::getGlobalParameters4UpdateTRF().
const Vector3& SBReferencePoint::v_0 () const [inline]
Definition at line 430 of file SbGeoStations.H'.
References v3Zero, and V_0.
virtual QDataStream& SBReferencePoint::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 397 of file SbGeoStations.H'.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBReferencePoint &RP_) [friend]
Definition at line 436 of file SbGeoStations.H'.
QDataStream& operator>> (QDataStream &s, SBReferencePoint &RP_) [friend]
Definition at line 438 of file SbGeoStations.H'.
Member Data Documentation
const Vector3* SBReferencePoint::DR_0 [protected]
Definition at line 403 of file SbGeoStations.H'.
Referenced by checkRanges(), dR_0(), registerCoords(), and SBReferencePoint().
const Vector3* SBReferencePoint::DV_0 [protected]
Definition at line 405 of file SbGeoStations.H'.
Referenced by checkRanges(), dV_0(), registerCoords(), and SBReferencePoint().
const Vector3* SBReferencePoint::R_0 [protected]
Definition at line 400 of file SbGeoStations.H'.
Referenced by checkRanges(), r_0(), registerCoords(), and SBReferencePoint().
const Vector3* SBReferencePoint::V_0 [protected]
Definition at line 404 of file SbGeoStations.H'.
Referenced by checkRanges(), registerCoords(), SBReferencePoint(), and v_0().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.