SBRefraction
NAME
SBRefraction -
SYNOPSIS
#include <SbGeoRefraction.H>
Public Member Functions
SBRefraction (const SBConfig *)
virtual ~SBRefraction ()
virtual QString ClassName () const
virtual double elev () const
virtual double refrElev () const
virtual double azimuth () const
virtual double wetMap () const
virtual double gradMap () const
virtual double totZenithDelay () const
virtual const Vector3 & refrSource () const
virtual double operator() (float, float, float, const SBFrame *, SBStation *, const SBSource *, const Vector3 &, double, bool)
void makeDebugReport (const SBMJD &, SBStation *)
Protected Member Functions
virtual const Vector3 refrDir (float, double, double, const SBStation *, const SBSource *, const Vector3 &)
virtual double altitudeCorr (float, double, double, const SBStation *, const SBSource *)
Protected Attributes
const SBConfig * Cfg
SBZenithDelay * DryZDelay
SBZenithDelay * WetZDelay
SBMappingFunc * DryMapping
SBMappingFunc * WetMapping
SBMappingFunc * AltDryMapping
SBMappingFunc * AltWetMapping
SBMappingFunc * GradMapping
double WetMap
double GradMap
double Elev
antenna's elevation angle
double RefrElev
antenna's elevation angle with refraction
double dE
correction of the antenna's elevation angle w/refr
double Delta
the troposphere scale height, m
double Azimuth
antenna's azimuth
double TotZenithDelay
total zenith delay, m
Vector3 RefrSource
unit vector to the refracted source
Detailed Description
Refraction'. Implements calculations of the refraction and related effects'.
Definition at line 358 of file SbGeoRefraction.H'.
Constructor & Destructor Documentation
SBRefraction::SBRefraction (const SBConfig *Cfg_)"A constructor'.
Definition at line 575 of file SbGeoRefraction.C'.
References AltDryMapping, AltWetMapping, Azimuth, Cfg, dE, Delta, DryMapping, DryZDelay, Elev, GradMapping, SBConfig::isRollBack2NMF(), SBConfig::RDM_CfA2p2, SBConfig::RDM_Chao, SBConfig::RDM_Ifadis, SBConfig::RDM_MTT, SBConfig::RDM_NMFH2, SBConfig::RDM_NMFW2, SBConfig::RDM_NONE, SBConfig::RDZ_Hopfield, SBConfig::RDZ_NONE, SBConfig::RDZ_Saastamoinen, SBConfig::refrDryMapping(), SBConfig::refrDryZenith(), RefrElev, SBConfig::refrWetMapping(), SBConfig::refrWetZenith(), SBConfig::RWM_Chao, SBConfig::RWM_Ifadis, SBConfig::RWM_MTT, SBConfig::RWM_NONE, SBConfig::RWZ_Hopfield, SBConfig::RWZ_NONE, SBConfig::RWZ_Saastamoinen, TotZenithDelay, WetMapping, and WetZDelay.
SBRefraction::~SBRefraction () [virtual]"A destructor'.
Definition at line 634 of file SbGeoRefraction.C'.
References AltDryMapping, AltWetMapping, DryMapping, DryZDelay, GradMapping, WetMapping, and WetZDelay.
Member Function Documentation
double SBRefraction::altitudeCorr (float, doubleDryZD, doubleStarTime, const SBStation *Station, const SBSource *Source) [protected, virtual]"Antenna axiss offset altitude correction'.
Parameters:
T is an atmospheric temperature, C;
DryZD is a hydrostatic zenith delay, m;
StarTime is a GMST, rad;
Station is a pointer to the SBStation'.
Source is a pointer to the SBSource'.
Returns:
axiss offset altitude correction to hydrostatic zenith delay, meter'.
Definition at line 728 of file SbGeoRefraction.C'.
References SBStation::axisOffset(), azimuth(), DEG2RAD, Delta, SBStation::latitude(), SBStation::longitude(), SBStation::Mnt_AZEL, SBStation::Mnt_EQUA, SBStation::Mnt_Richmond, SBStation::Mnt_Unkn, SBStation::Mnt_X_YE, SBStation::Mnt_X_YN, SBStation::mountType(), SBSource::ra_t(), refrElev(), and sincos().
Referenced by operator()().
virtual double SBRefraction::azimuth () const [inline, virtual]
Definition at line 389 of file SbGeoRefraction.H'.
References Azimuth.
Referenced by altitudeCorr(), and SBDelay::calc().
virtual QString SBRefraction::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Definition at line 386 of file SbGeoRefraction.H'.
Referenced by operator()(), and refrDir().
virtual double SBRefraction::elev () const [inline, virtual]
Definition at line 387 of file SbGeoRefraction.H'.
References Elev.
Referenced by operator()().
virtual double SBRefraction::gradMap () const [inline, virtual]
Definition at line 391 of file SbGeoRefraction.H'.
References GradMap.
Referenced by SBDelay::calc().
void SBRefraction::makeDebugReport (const SBMJD &, SBStation *)
Definition at line 889 of file SbGeoRefraction.C'.
References Elev, SBMJD::F_UNIX, RAD2DEG, and RefrElev.
Referenced by SBDelay::calc().
double SBRefraction::operator() (floatT, floatP, floatRH, const SBFrame *Frame, SBStation *Station, const SBSource *Source, const Vector3 &S, doubleZw_, boolIsWrongMetheo) [virtual]"Calcs refraction delay'.
Parameters:
T is an atmospheric temperature, C;
P is an atmospheric pressure, mbar;
RH is an atmospheric relative humidity, %;
Frame is a pointer to the SBFrame;
Station is a pointer to the SBStation;
Source is a pointer to the SBSource;
S is a TRS vector of the radiosource, abberated;
Zw_ is a predicted wet zenith delay;
IsWrongMetheo is set to TRUE if a station has bad or suspicious metheo parameters'.
Returns:
refraction delay, meter'.
Definition at line 782 of file SbGeoRefraction.C'.
References AltDryMapping, altitudeCorr(), AltWetMapping, Azimuth, Cfg, SBZenithDelay::ClassName(), SBMappingFunc::ClassName(), ClassName(), SBLog::DBG, dE, Delta, DryMapping, DryZDelay, Elev, elev(), SBFrame::gmst(), GradMap, SBStation::id(), SBConfig::isAltAxsCorr(), SBLog::isEligible(), Log, SBNamed::name(), SBStation::p_AtmGradE(), SBStation::p_AtmGradN(), SBStation::p_Zenith(), rad2dmslStr(), rad2dmsStr(), SBLog::REFRACT, refrDir(), RefrElev, RefrSource, Vector3::report2Log(), SBFrame::time(), SBMJD::toString(), SBStationID::toString(), TotZenithDelay, SBParameter::v(), SBZenithDelay::vapourPress(), WetMap, WetMapping, WetZDelay, and SBLog::write().
const Vector3 SBRefraction::refrDir (floatT, doubleDryZD, doubleWetZD, const SBStation *Station, const SBSource *Source, const Vector3 &S) [protected, virtual]"Calcs refracted antenna's direction in TRF'. This function calulates angles of azimuth and refracted elevation of an antenna direction too'. It has to be called after zenith delays calculation and before mapping functions'.
Parameters:
T is an atmospheric temperature, C;
DryZD is a hydrostatic zenith delay, m;
WetZD is a wet zenith delay, m;
Station is a pointer to the SBStation;
S is a TRS vector of the radiosource, abberated'.
Returns:
antenna's direction in TRF corrected for refraction'.
Definition at line 684 of file SbGeoRefraction.C'.
References Vector3::at(), Azimuth, ClassName(), dE, Delta, EAST, Elev, SBLog::ERR, SBStation::fmVEN(), Log, SBNamed::name(), NORT, SBLog::REFRACT, RefrElev, sincos(), VERT, and SBLog::write().
Referenced by operator()().
virtual double SBRefraction::refrElev () const [inline, virtual]
Definition at line 388 of file SbGeoRefraction.H'.
References RefrElev.
Referenced by altitudeCorr().
virtual const Vector3& SBRefraction::refrSource () const [inline, virtual]"Returns unit vector in refracted source direction, TRF'.
Definition at line 394 of file SbGeoRefraction.H'.
References RefrSource.
Referenced by SBDelay::calc().
virtual double SBRefraction::totZenithDelay () const [inline, virtual]
Definition at line 392 of file SbGeoRefraction.H'.
References TotZenithDelay.
Referenced by SBDelay::calc().
virtual double SBRefraction::wetMap () const [inline, virtual]
Definition at line 390 of file SbGeoRefraction.H'.
References WetMap.
Referenced by SBDelay::calc().
Member Data Documentation
SBMappingFunc* SBRefraction::AltDryMapping [protected]
Definition at line 366 of file SbGeoRefraction.H'.
Referenced by operator()(), SBRefraction(), and ~SBRefraction().
SBMappingFunc* SBRefraction::AltWetMapping [protected]
Definition at line 367 of file SbGeoRefraction.H'.
Referenced by operator()(), SBRefraction(), and ~SBRefraction().
double SBRefraction::Azimuth [protected]
antenna's azimuth
Definition at line 375 of file SbGeoRefraction.H'.
Referenced by azimuth(), operator()(), refrDir(), and SBRefraction().
const SBConfig* SBRefraction::Cfg [protected]
Definition at line 361 of file SbGeoRefraction.H'.
Referenced by operator()(), and SBRefraction().
double SBRefraction::dE [protected]
correction of the antenna's elevation angle w/refr
Definition at line 373 of file SbGeoRefraction.H'.
Referenced by operator()(), refrDir(), and SBRefraction().
double SBRefraction::Delta [protected]
the troposphere scale height, m
Definition at line 374 of file SbGeoRefraction.H'.
Referenced by altitudeCorr(), operator()(), refrDir(), and SBRefraction().
SBMappingFunc* SBRefraction::DryMapping [protected]
Definition at line 364 of file SbGeoRefraction.H'.
Referenced by operator()(), SBRefraction(), and ~SBRefraction().
SBZenithDelay* SBRefraction::DryZDelay [protected]
Definition at line 362 of file SbGeoRefraction.H'.
Referenced by operator()(), SBRefraction(), and ~SBRefraction().
double SBRefraction::Elev [protected]
antenna's elevation angle
Definition at line 371 of file SbGeoRefraction.H'.
Referenced by elev(), makeDebugReport(), operator()(), refrDir(), and SBRefraction().
double SBRefraction::GradMap [protected]
Definition at line 370 of file SbGeoRefraction.H'.
Referenced by gradMap(), and operator()().
SBMappingFunc* SBRefraction::GradMapping [protected]
Definition at line 368 of file SbGeoRefraction.H'.
Referenced by SBRefraction(), and ~SBRefraction().
double SBRefraction::RefrElev [protected]
antenna's elevation angle with refraction
Definition at line 372 of file SbGeoRefraction.H'.
Referenced by makeDebugReport(), operator()(), refrDir(), refrElev(), and SBRefraction().
Vector3 SBRefraction::RefrSource [protected]
unit vector to the refracted source
Definition at line 377 of file SbGeoRefraction.H'.
Referenced by operator()(), and refrSource().
double SBRefraction::TotZenithDelay [protected]
total zenith delay, m
Definition at line 376 of file SbGeoRefraction.H'.
Referenced by operator()(), SBRefraction(), and totZenithDelay().
double SBRefraction::WetMap [protected]
Definition at line 369 of file SbGeoRefraction.H'.
Referenced by operator()(), and wetMap().
SBMappingFunc* SBRefraction::WetMapping [protected]
Definition at line 365 of file SbGeoRefraction.H'.
Referenced by operator()(), SBRefraction(), and ~SBRefraction().
SBZenithDelay* SBRefraction::WetZDelay [protected]
Definition at line 363 of file SbGeoRefraction.H'.
Referenced by operator()(), SBRefraction(), and ~SBRefraction().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.