SBRotate
NAME
SBRotate -
SYNOPSIS
#include <SbGeoRefFrame.H>
Inherits RotMatrix'.
Public Member Functions
SBRotate ()
virtual QString ClassName () const
virtual RotDerMatrix & dRdt ()
virtual const Matrix3 & operator() (double)
virtual double & operator() (DIRECTION i, DIRECTION j)
virtual double angle () const
virtual DIRECTION axis () const
virtual double at (DIRECTION i, DIRECTION j) const
virtual void report2Log (SBLog::LogLevel, uint, const QString &) const
virtual double module () const
virtual void unify ()
Matrix3 T () const
Matrix3 & operator+= (const Matrix3 &)
Matrix3 & operator-= (const Matrix3 &)
Matrix3 & operator*= (double)
Matrix3 & operator/= (double)
Protected Attributes
double Angle
double sa
double ca
DIRECTION Axis
double mat [3][3]
Private Attributes
RotDerMatrix DRdt
Friends
Matrix3 operator+ (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &, const Matrix3 &)
Matrix3 operator- (const Matrix3 &)
Matrix3 operator/ (const Matrix3 &, double)
Matrix3 operator* (const Matrix3 &, double)
Matrix3 operator* (double, const Matrix3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Matrix3 operator* (const Matrix3 &, const Matrix3 &)
Matrix3 operator~ (const Matrix3 &)
Detailed Description
Earth rotation matrix (general)'. Matrix describes Earth rotation'.
Definition at line 591 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBRotate::SBRotate () [inline]"A constructor'.
Definition at line 597 of file SbGeoRefFrame.H'.
Member Function Documentation
virtual double RotMatrix::angle () const [inline, virtual, inherited]
Definition at line 183 of file SbVector3.H'.
References RotMatrix::Angle.
Referenced by SBFrameClassic::calc(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
virtual double Matrix3::at (DIRECTIONi, DIRECTIONj) const [inline, virtual, inherited]
Definition at line 139 of file SbVector3.H'.
References Matrix3::mat.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), and SBRunManager::makeReportTRFVariations().
virtual DIRECTION RotMatrix::axis () const [inline, virtual, inherited]
Definition at line 184 of file SbVector3.H'.
References RotMatrix::Axis.
virtual QString SBRotate::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from RotMatrix'.
Definition at line 599 of file SbGeoRefFrame.H'.
virtual RotDerMatrix& SBRotate::dRdt () [inline, virtual]
Definition at line 600 of file SbGeoRefFrame.H'.
References DRdt.
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), and SBFrameClassic::dQ_dpsi().
double Matrix3::module () const [inline, virtual, inherited]
Definition at line 410 of file SbVector3.H'.
References Matrix3::mat.
Referenced by operator~(), and Matrix3::unify().
virtual double& Matrix3::operator() (DIRECTIONi, DIRECTIONj) [inline, virtual, inherited]
Definition at line 138 of file SbVector3.H'.
References Matrix3::mat.
const Matrix3 & RotMatrix::operator() (doubleAngle_) [virtual, inherited]
Reimplemented in Rot2DerMatrix, and RotDerMatrix'.
Definition at line 139 of file SbVector3.C'.
References RotMatrix::Angle, RotMatrix::Axis, RotMatrix::ca, Matrix3::mat, RotMatrix::sa, X_AXIS, Y_AXIS, and Z_AXIS.
Matrix3 & Matrix3::operator*= (doublev) [inline, inherited]
Definition at line 394 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator+= (const Matrix3 &M) [inline, inherited]
Definition at line 378 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator-= (const Matrix3 &M) [inline, inherited]
Definition at line 386 of file SbVector3.H'.
References Matrix3::mat.
Matrix3 & Matrix3::operator/= (doublev) [inline, inherited]
Definition at line 402 of file SbVector3.H'.
References Matrix3::mat.
Referenced by Matrix3::unify().
void Matrix3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref) const [virtual, inherited]
Definition at line 76 of file SbVector3.C'.
References Log, Matrix3::mat, and SBLog::write().
Referenced by SBFrameClassic::calc(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and SBPolus::operator()().
Matrix3 Matrix3::T () const [inline, inherited]"Returns transposed matrix (original matrix does'n change)'.
Definition at line 418 of file SbVector3.H'.
References Matrix3::mat, and Matrix3::Matrix3().
Referenced by SBDelay::calcDerivatives().
virtual void Matrix3::unify () [inline, virtual, inherited]
Definition at line 142 of file SbVector3.H'.
References Matrix3::module(), and Matrix3::operator/=().
Friends And Related Function Documentation
Matrix3 operator* (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 493 of file SbVector3.H'.
Matrix3 operator* (doublev1, const Matrix3 &M2) [friend, inherited]
Definition at line 502 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &, const Vector3 &) [friend, inherited]
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 59 of file SbVector3.C'.
Matrix3 operator+ (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 450 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1, const Matrix3 &M2) [friend, inherited]
Definition at line 467 of file SbVector3.H'.
Matrix3 operator- (const Matrix3 &M1) [friend, inherited]
Definition at line 433 of file SbVector3.H'.
Matrix3 operator/ (const Matrix3 &M1, doublev2) [friend, inherited]
Definition at line 484 of file SbVector3.H'.
Matrix3 operator~ (const Matrix3 &M1) [friend, inherited]"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
Member Data Documentation
double RotMatrix::Angle [protected, inherited]
Definition at line 175 of file SbVector3.H'.
Referenced by RotMatrix::angle(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), and RotMatrix::RotMatrix().
DIRECTION RotMatrix::Axis [protected, inherited]
Definition at line 176 of file SbVector3.H'.
Referenced by RotMatrix::axis(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), and RotMatrix::RotMatrix().
double RotMatrix::ca [protected, inherited]
Definition at line 175 of file SbVector3.H'.
Referenced by RotMatrix::operator()(), RotDerMatrix::operator()(), and Rot2DerMatrix::operator()().
RotDerMatrix SBRotate::DRdt [private]
Definition at line 594 of file SbGeoRefFrame.H'.
Referenced by dRdt().
double Matrix3::mat[3][3] [protected, inherited]
Definition at line 120 of file SbVector3.H'.
Referenced by Matrix3::at(), Matrix3::Matrix3(), Matrix3::module(), Matrix3::operator()(), RotMatrix::operator()(), RotDerMatrix::operator()(), Rot2DerMatrix::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), operator*(), Matrix3::operator*=(), operator+(), Matrix3::operator+=(), operator-(), Matrix3::operator-=(), operator/(), Matrix3::operator/=(), Matrix3::operator=(), operator~(), Matrix3::report2Log(), and Matrix3::T().
double RotMatrix::sa [protected, inherited]
Definition at line 175 of file SbVector3.H'.
Referenced by RotMatrix::operator()(), RotDerMatrix::operator()(), and Rot2DerMatrix::operator()().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.