SBRunManager
NAME
SBRunManager -
SYNOPSIS
#include <SbGeoProject.H>
Public Member Functions
SBRunManager (SBProject *=NULL, SBVLBISet *=NULL, SBSolution *=NULL)
virtual ~SBRunManager ()
virtual QString ClassName () const
SBProject * prj ()
SBVLBISet * vlbi () const
SBFrame * frame () const
const SBEphem * ephem () const
SB_TRF * trf ()
const SBPlateMotion * plates () const
const SBPlateMotion * refPlates () const
SB_CRF * crf () const
SBAploEphem * aploEphem ()
SBObservationList * obsList ()
SBSolution * solution ()
SBEstimator * estimator ()
SBObsIterator * obsIt ()
SBTideLd * tideLd ()
SBRefraction * refr ()
SBDelay * delay ()
SBParameterList * allGlobalList ()
SBParameterList * globalList ()
SBParameterList * arcList ()
SBParameterList * localList ()
SBParameterList * stochList ()
QString listOfCurrentSessNames ()
void process ()
void makeReports ()
void makeReportMaps ()
void makeReportTRFVariations ()
void makeReportCRFVariations ()
void makeReportCRFVariations4IVS ()
void makeReportTRF ()
void makeReportCRF ()
void makeReportEOP ()
void makeReportTroposphere ()
void makeReportTechDescription ()
void makeReportNormalEqs ()
void makeReportSessionStatistics ()
int numOpenedVLBISessions () const
Protected Member Functions
void stripCRF ()
void stripTRF ()
void fillParameterList (SBParameterList *&, SBParameterCfg::PType, const SBMJD &)
void checkParameterLists (const SBMJD &)
const SBMJD & findT_2load ()
SBMJD findT_2save ()
bool isObsEligible (SBObservation *)
void constrainClocks (bool)
void constraintStationCoord (bool)
void constraintStationVeloc (bool)
void constraintSourceCoord (bool)
void constraintEOP (bool)
void process_m1 ()
bool prepare4Run_m1 ()
void finisRun_m1 ()
void saveVLBISessions_m1 ()
void loadVLBISession_m1 (const QString &)
void process_m2 ()
bool prepare4Run_m2 ()
void finisRun_m2 ()
void saveVLBISessions_m2 (const SBMJD &)
void loadVLBISessions_m2 (SBMJD &)
SBObservation * nextObs_m2 ()
Protected Attributes
SBProject * Prj
Current project;'.
bool IsPrjOwner
Set if manager is project owner;'.
SBSolution * Solution
solution;
bool IsSolutionOwner
SBEstimator * Estimator
estimator;
SBObservationList ObsList
Current/cached list of observations;'.
SBObsIterator * ObsIt
Iterator to traverse through the obs'.list;'.
SB_TRF * TRF
TRF;'.
SBPlateMotion * Plates
Tectonic plate motion model;'.
SBPlateMotion * RefPlates
Reference model of tectonic plate motion;'.
SBFrame * Frame
Reference frame transformer;'.
SBEphem * Ephem
Ephemeris;'.
SBTideLd * TideLd
Tide loading calculator;'.
SBRefraction * Refr
Refration calculator;'.
SBAploEphem * AploEphem
Ephemerides of atmospheric pressure loading;'.
SBVLBISet * VLBI
VLBI dataset;'.
bool IsVLBIOwner
SB_CRF * CRF
CRF;'.
SBDelay * Delay
Delay and rate calculator;'.
int prcsVLBISess
number of processed VLBI sessions;
QList< SBVLBISession > VLBISessCache
List of current opened sessions;'.
SBVLBISesInfoList VLBISessions
List of VLBI ses' infos ordered by TStart;'.
SBVLBISesInfoIterator * VLBISessIt
Iterator to traverse through VLBI SessInfo'.s'.
SBMJD T_2load
MJD date of the next session to load;'.
SBMJD T_2save
MJD date of the session to save;'.
SBMJD Tb
SBMJD Te
SBParameterList * AllGlobalList
List of all global parameters;'.
SBParameterList * GlobalList
List of global parameters;'.
SBParameterList * ArcList
List of arc parameters;'.
SBParameterList * LocalList
List of local parameters;'.
SBParameterList * StochList
List of stochastic parameters;'.
Detailed Description
Class SBRunManager'. This class manages observations (different types: VLBI, ) data processing'.
Definition at line 458 of file SbGeoProject.H'.
Constructor & Destructor Documentation
SBRunManager::SBRunManager (SBProject *Prj_ = NULL, SBVLBISet *VLBI_ = NULL, SBSolution *Solution_ = NULL)"A constructor'. Creates a copy of object'.
Parameters:
Prj_ the project'.
Definition at line 676 of file SbGeoProject.C'.
References AllGlobalList, AploEphem, ArcList, SBProject::cfg(), ClassName(), SBEOP::createParameters(), CRF, SBLog::DATA, SBLog::DBG, Delay, SBConfig::EM_LEDE200, SBConfig::EM_LEDE403, SBConfig::EM_LEDE405, SBFrame::eop(), Ephem, Estimator, Frame, GlobalList, IsPrjOwner, IsSolutionOwner, IsVLBIOwner, SBSetUp::loadAploEphem(), SBSetUp::loadCRF(), SBSetUp::loadProject(), SBSetUp::loadTRF(), LocalList, Log, mainSetOperation(), SBNamed::name(), ObsIt, ObsList, Plates, SBConfig::PM_NNR_NUVEL1A, SBConfig::PM_NONE, SBConfig::PM_NUVEL1A, prcsVLBISess, SB_CRF::prepare4Run(), SB_TRF::prepare4Run(), Prj, prj(), RefPlates, Refr, SetUp, Solution, SBLog::STATION, SB_TRF::stations(), StochList, SBConfig::STR_Classic, SBConfig::STR_NRO, stripCRF(), stripTRF(), T_2load, T_2save, Tb, Te, SBProject::tFinis(), TideLd, TRF, SBProject::tStart(), TZero, VLBI, VLBISessCache, VLBISessions, VLBISessIt, SBLog::write(), and SBLog::WRN.
SBRunManager::~SBRunManager () [virtual]"A destructor'.
Definition at line 841 of file SbGeoProject.C'.
References AllGlobalList, AploEphem, ArcList, CRF, Delay, SBFrame::eop(), Ephem, Estimator, SB_CRF::finisRun(), SB_TRF::finisRun(), Frame, GlobalList, IsPrjOwner, IsSolutionOwner, IsVLBIOwner, LocalList, ObsIt, Plates, Prj, RefPlates, Refr, SBEOP::releaseParameters(), Solution, StochList, TideLd, TRF, VLBI, and VLBISessIt.
Member Function Documentation
SBParameterList* SBRunManager::allGlobalList () [inline]"Returns the list of all global parameters'.
Definition at line 588 of file SbGeoProject.H'.
References AllGlobalList.
SBAploEphem* SBRunManager::aploEphem () [inline]
Definition at line 578 of file SbGeoProject.H'.
References AploEphem.
Referenced by SBStation::calcDisplacement().
SBParameterList* SBRunManager::arcList () [inline]"Returns the list of arc parameters'.
Definition at line 592 of file SbGeoProject.H'.
References ArcList.
void SBRunManager::checkParameterLists (const SBMJD &T) [protected]"Updates the lists of parameters'. This function is called after each saving and loading of session'. The lists are containing only actual (currently processing) parameters'.
Definition at line 2304 of file SbGeoProject.C'.
References ArcList, ClassName(), SBLog::DBG, Estimator, fillParameterList(), GlobalList, LocalList, Log, SBEstimator::parameterListsAboutToChange(), SBEstimator::parameterListsChanged(), SBParameterCfg::PT_ARC, SBParameterCfg::PT_GLB, SBParameterCfg::PT_LOC, SBParameterCfg::PT_STH, SBLog::RUN, StochList, SBMJD::toString(), and SBLog::write().
Referenced by nextObs_m2(), prepare4Run_m2(), and process_m1().
virtual QString SBRunManager::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Definition at line 566 of file SbGeoProject.H'.
Referenced by checkParameterLists(), constrainClocks(), constraintEOP(), constraintSourceCoord(), constraintStationCoord(), constraintStationVeloc(), fillParameterList(), loadVLBISession_m1(), loadVLBISessions_m2(), makeReportCRF(), makeReportCRFVariations(), makeReportCRFVariations4IVS(), makeReportEOP(), makeReportMaps(), makeReportNormalEqs(), makeReports(), makeReportSessionStatistics(), makeReportTechDescription(), makeReportTRF(), makeReportTRFVariations(), makeReportTroposphere(), prepare4Run_m1(), prepare4Run_m2(), process_m1(), process_m2(), saveVLBISessions_m1(), saveVLBISessions_m2(), SBRunManager(), stripCRF(), and stripTRF().
void SBRunManager::constrainClocks (boolIsGlobal) [protected]
Definition at line 1011 of file SbGeoProject.C'.
References SBProject::cfg(), ClassName(), SBParametersDesc::clock0(), SBParametersDesc::clock1(), SBParametersDesc::clock2(), SBLog::DBG, SBLog::ERR, Estimator, SB_TRF::find(), Log, SBConfig::p(), SBStation::p_C0(), SBStation::p_C1(), SBStation::p_C2(), Prj, SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBParameterCfg::PT_NONE, SBStationInfo::refClock, SBLog::RUN, SBDerivation::setD(), TRF, SBParameterCfg::type(), TZero, VLBISessCache, SBLog::write(), and SBLog::WRN.
Referenced by process_m1().
void SBRunManager::constraintEOP (boolIsGlobal) [protected]
Definition at line 1408 of file SbGeoProject.C'.
References SBProject::cfg(), ClassName(), DAY2SEC, SBLog::DBG, SBFrame::eop(), Estimator, Frame, Log, SBConfig::p(), SBEOP::p_Neps(), SBEOP::p_Npsi(), SBEOP::p_Put(), SBEOP::p_Px(), SBEOP::p_Py(), SBParametersDesc::polusNut(), SBParametersDesc::polusUT(), SBParametersDesc::polusXY(), Prj, SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBParameterCfg::PT_NONE, SBLog::RUN, SEC2RAD, SBDerivation::setD(), SBParameterCfg::type(), TZero, and SBLog::write().
Referenced by process_m1().
void SBRunManager::constraintSourceCoord (boolIsGlobal) [protected]
Definition at line 1463 of file SbGeoProject.C'.
References ClassName(), SBSourceInfo::ConstrCoo, CRF, SBLog::DBG, SBSource::dn(), SBLog::ERR, Estimator, SB_CRF::find(), SBCatalog::label(), Log, SBNamed::name(), SBSource::p_DN(), SBSource::p_RA(), Prj, SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBSource::ra(), SBLog::RUN, SEC2RAD, SBDerivation::setD(), sincos(), SBProject::sourceList(), SBSolutionName::toString(), TZero, and SBLog::write().
Referenced by process_m1().
void SBRunManager::constraintStationCoord (boolIsGlobal) [protected]
Definition at line 1077 of file SbGeoProject.C'.
References Vector3::at(), SBStation::calcDisplacement(), ClassName(), SBStationInfo::ConstrCoo, SBLog::DBG, SBLog::ERR, Estimator, SB_TRF::find(), SBStation::id(), SBCatalog::label(), Log, SBNamed::name(), SBStation::p_DRX(), SBStation::p_DRY(), SBStation::p_DRZ(), Prj, SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBStation::r(), SBLog::RUN, SBDerivation::setD(), SBProject::stationList(), SBSolutionName::toString(), SBStationID::toString(), TRF, TZero, SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by process_m1().
void SBRunManager::constraintStationVeloc (boolIsGlobal) [protected]
Definition at line 1204 of file SbGeoProject.C'.
References Vector3::at(), SBStation::calcDisplacement(), ClassName(), SBStationInfo::ConstrVel, SBLog::DBG, SBLog::ERR, Estimator, SB_TRF::find(), SBStation::id(), SBCatalog::label(), Log, SBPlateMotion::modelName(), SBNamed::name(), SBStation::p_DVX(), SBStation::p_DVY(), SBStation::p_DVZ(), Prj, SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBStation::r(), RefPlates, SBLog::RUN, SBDerivation::setD(), SBProject::stationList(), SBSolutionName::toString(), SBStationID::toString(), TRF, TZero, Vector3::unit(), v3Zero, SBPlateMotion::velocity(), SBStation::vt(), SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by process_m1().
SB_CRF* SBRunManager::crf () const [inline]
Definition at line 577 of file SbGeoProject.H'.
References CRF.
Referenced by collectListOfSINEXParameters4NEQ(), operator<<(), SBObsVLBIEntry::process(), and writeNormalEquationSystem().
SBDelay* SBRunManager::delay () [inline]
Definition at line 586 of file SbGeoProject.H'.
References Delay.
Referenced by SBObsVLBIEntry::process().
const SBEphem* SBRunManager::ephem () const [inline]
Definition at line 573 of file SbGeoProject.H'.
References Ephem.
SBEstimator* SBRunManager::estimator () [inline]
Definition at line 582 of file SbGeoProject.H'.
References Estimator.
void SBRunManager::fillParameterList (SBParameterList *&List, SBParameterCfg::PTypeType, const SBMJD &T) [protected]"Fills a list of parameters according to the config'.
Definition at line 2335 of file SbGeoProject.C'.
References SBParametersDesc::atmGrad(), SBParametersDesc::axisOffset(), SBStationInfo::BadCable, SBParametersDesc::cable(), SBProject::cfg(), SBStationInfo::cl_Order(), ClassName(), SBParameterList::clear(), SBParametersDesc::clock0(), SBParametersDesc::clock1(), SBParametersDesc::clock2(), SBStationInfo::clocks(), CRF, DAY2SEC, SBFrame::eop(), SBLog::ERR, SBStationInfo::EstCoo, SBSourceInfo::EstCoo, SBStationInfo::EstVel, SBStationInfoList::find(), SBSourceInfoList::find(), SB_CRF::first(), Frame, SBParameterList::inSort(), SBAttributed::isAttr(), SBDerivation::IsInRun, Log, SBParametersDesc::love_h2(), SBParametersDesc::love_l2(), SB_CRF::next(), SBStationInfo::notValid, SBSourceInfo::notValid, SBVLBISesInfo::notValid, SBConfig::p(), SBEOP::p_Neps(), SBEOP::p_Npsi(), SBEOP::p_Put(), SBEOP::p_Px(), SBEOP::p_Py(), SBEOP::p_UT_c1(), SBEOP::p_UT_c10(), SBEOP::p_UT_c2(), SBEOP::p_UT_c3(), SBEOP::p_UT_c4(), SBEOP::p_UT_c5(), SBEOP::p_UT_c6(), SBEOP::p_UT_c7(), SBEOP::p_UT_c8(), SBEOP::p_UT_c9(), SBEOP::p_UT_s1(), SBEOP::p_UT_s10(), SBEOP::p_UT_s2(), SBEOP::p_UT_s3(), SBEOP::p_UT_s4(), SBEOP::p_UT_s5(), SBEOP::p_UT_s6(), SBEOP::p_UT_s7(), SBEOP::p_UT_s8(), SBEOP::p_UT_s9(), SBEOP::p_Xp_m10(), SBEOP::p_Xp_m2(), SBEOP::p_Xp_m3(), SBEOP::p_Xp_m4(), SBEOP::p_Xp_m5(), SBEOP::p_Xp_m6(), SBEOP::p_Xp_m7(), SBEOP::p_Xp_m8(), SBEOP::p_Xp_m9(), SBEOP::p_Xp_p1(), SBEOP::p_Xp_p10(), SBEOP::p_Xp_p2(), SBEOP::p_Xp_p3(), SBEOP::p_Xp_p4(), SBEOP::p_Xp_p5(), SBEOP::p_Xp_p6(), SBEOP::p_Xp_p7(), SBEOP::p_Xp_p8(), SBEOP::p_Xp_p9(), SBEOP::p_Yp_m10(), SBEOP::p_Yp_m2(), SBEOP::p_Yp_m3(), SBEOP::p_Yp_m4(), SBEOP::p_Yp_m5(), SBEOP::p_Yp_m6(), SBEOP::p_Yp_m7(), SBEOP::p_Yp_m8(), SBEOP::p_Yp_m9(), SBEOP::p_Yp_p1(), SBEOP::p_Yp_p10(), SBEOP::p_Yp_p2(), SBEOP::p_Yp_p3(), SBEOP::p_Yp_p4(), SBEOP::p_Yp_p5(), SBEOP::p_Yp_p6(), SBEOP::p_Yp_p7(), SBEOP::p_Yp_p8(), SBEOP::p_Yp_p9(), SBParametersDesc::polusNut(), SBParametersDesc::polusUT(), SBParametersDesc::polusXY(), Prj, SBParameterCfg::PT_ARC, SBParameterCfg::PT_GLB, SBParameterCfg::PT_LOC, SBParameterCfg::PT_NONE, SBParameterCfg::PT_STH, RAD2SEC, SBLog::RUN, SBParameterCfg::setScale(), SBProject::sourceList(), SBParametersDesc::srcCoo(), SBParametersDesc::staCoo(), SBProject::stationList(), SB_TRF::stations(), SBParametersDesc::staVel(), SBParametersDesc::test(), SBParametersDesc::tideLag(), TRF, SBParameter::tuneParameter(), SBParameterCfg::type(), SBStationInfo::UseLocalClocks, SBStationInfo::UseLocalZenith, VLBISessCache, SBLog::write(), SBParametersDesc::zenith(), and SBStationInfo::zenith().
Referenced by checkParameterLists(), prepare4Run_m1(), and prepare4Run_m2().
const SBMJD & SBRunManager::findT_2load () [inline, protected]
Definition at line 627 of file SbGeoProject.H'.
References Te, and VLBISessIt.
Referenced by nextObs_m2(), and prepare4Run_m2().
SBMJD SBRunManager::findT_2save () [inline, protected]
Definition at line 633 of file SbGeoProject.H'.
References Te, and VLBISessCache.
Referenced by nextObs_m2(), and prepare4Run_m2().
void SBRunManager::finisRun_m1 () [protected]
Definition at line 1890 of file SbGeoProject.C'.
References AllGlobalList, ArcList, SBProject::cfg(), Estimator, SBEstimator::finisRun(), GlobalList, SBConfig::isGenerateDSINEXes(), IsPrjOwner, IsVLBIOwner, LocalList, ObsIt, Prj, SBSetUp::saveProject(), SBSetUp::saveVLBI(), SBConfig::setIsGenerateDSINEXes(), SetUp, StochList, VLBI, VLBISessions, and VLBISessIt.
Referenced by process_m1().
void SBRunManager::finisRun_m2 () [protected]"Makes a post-processing manipulations'.
Definition at line 2128 of file SbGeoProject.C'.
References AllGlobalList, ArcList, Estimator, SBEstimator::finisRun(), GlobalList, LocalList, ObsIt, ObsList, saveVLBISessions_m2(), StochList, Te, VLBISessCache, VLBISessions, and VLBISessIt.
Referenced by process_m2().
SBFrame* SBRunManager::frame () const [inline]
Definition at line 572 of file SbGeoProject.H'.
References Frame.
Referenced by collectListOfSINEXParameters4NEQ(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), operator<<(), and writeNormalEquationSystem().
SBParameterList* SBRunManager::globalList () [inline]"Returns the list of global parameters'.
Definition at line 590 of file SbGeoProject.H'.
References GlobalList.
Referenced by SBEstimator::prepare4Local().
bool SBRunManager::isObsEligible (SBObservation *Obs) [protected]
Definition at line 1004 of file SbGeoProject.C'.
References SBObservation::isEligible().
Referenced by loadVLBISession_m1().
QString SBRunManager::listOfCurrentSessNames ()"Returns a list of currently processing sessions'.
Definition at line 991 of file SbGeoProject.C'.
References VLBISessCache.
Referenced by loadVLBISession_m1(), loadVLBISessions_m2(), SBEstimator::prepare4Local(), process_m1(), saveVLBISessions_m1(), and saveVLBISessions_m2().
void SBRunManager::loadVLBISession_m1 (const QString &Name_) [protected]
Definition at line 1945 of file SbGeoProject.C'.
References ClassName(), SBVLBISession::clearRMSs(), CRF, SBLog::DATA, SBMJD::date(), SBLog::DBG, SBLog::ERR, SBVLBISession::first(), SBLog::IO, isObsEligible(), listOfCurrentSessNames(), SBVLBISet::loadSession(), Log, mainSetCacheSizes(), mainSetOperation(), mainSetSessName(), SBNamed::name(), SBVLBISession::next(), ObsList, SB_TRF::prepareEccs4Session(), SBVLBISesInfo::tFinis(), TRF, VLBI, VLBISessCache, SBLog::write(), and SBLog::WRN.
Referenced by process_m1().
void SBRunManager::loadVLBISessions_m2 (SBMJD &T) [protected]"Loads a VLBI session'.
Definition at line 2223 of file SbGeoProject.C'.
References ClassName(), CRF, SBLog::DATA, SBLog::DBG, SBLog::ERR, SBVLBISession::first(), SBLog::IO, listOfCurrentSessNames(), SBVLBISet::loadSession(), Log, mainSetCacheSizes(), mainSetOperation(), mainSetSessName(), SBNamed::name(), SBVLBISession::next(), ObsList, TRF, VLBI, VLBISessCache, VLBISessIt, SBLog::write(), and SBLog::WRN.
Referenced by nextObs_m2(), and prepare4Run_m2().
SBParameterList* SBRunManager::localList () [inline]"Returns the list of local parameters'.
Definition at line 594 of file SbGeoProject.H'.
References LocalList.
Referenced by SBEstimator::prepare4Local().
void SBRunManager::makeReportCRF ()
Definition at line 1391 of file SbGeoProjectReports.C'.
References SBAttributed::addAttr(), SBSource::AnalysConstr, SBSource::Analysed, SBSymMatrix::at(), ClassName(), SBSourceInfo::ConstrCoo, CRF, SBLog::DBG, SBAttributed::delAttr(), SBLog::ERR, SBSourceInfo::EstCoo, SBSourceInfoList::find(), SB_CRF::first(), SBSource::getGlobalParameters4Report(), SBParameterList::idx(), SBLog::IO, SBAttributed::isAttr(), SBCatalog::label(), SBSolution::loadGlbCor(), Log, SBNamed::name(), SB_CRF::next(), SBSourceInfo::notValid, SBSource::p_DN(), SBSource::p_RA(), SBSetUp::path2Output(), SB_CRF::prepareAliases4Output(), Prj, SB_CRF::releaseAliases4Output(), SBCatalog::remove(), SBLog::RUN, SBSolutionName::setAcronym(), SBSource::setCorrRA_DN(), SBCatalog::setLabel(), SBSolutionName::setSerial(), SetUp, SBSolutionName::setYear(), Solution, SBLog::SOURCE, SBProject::sourceList(), and SBLog::write().
Referenced by makeReports().
void SBRunManager::makeReportCRFVariations ()"fi'.exists() &&
Definition at line 348 of file SbGeoProjectReports.C'.
References SBObjectObsInfo::aka(), ClassName(), CRF, SBLog::DBG, SBSource::dn(), SBParameter::e(), SBStochParameter::e(), SBLog::ERR, SBSourceInfo::EstCoo, SBMJD::F_MJD, SBMJD::F_UNIX, SB_CRF::find(), SBSourceInfoList::find(), SBParameterList::find(), SBStochParameterList::find(), SB_CRF::first(), SBSolution::global(), SBAttributed::isAttr(), SBSolution::local(), Log, SBVersion::name(), SBNamed::name(), SB_CRF::next(), SBSourceInfo::notValid, SBDerivation::num(), SBStochParameter::num(), SBSource::p_DN(), SBSource::p_RA(), SBSetUp::path2Output(), SBSolution::prepare4Batch(), Prj, SBSource::ra(), SBLog::RUN, SBParameter::scale(), SBVersion::selfName(), SetUp, Solution, SBProject::sourceList(), SBSolution::statByBatch(), SBSolution::stochastic(), SBDerivation::tEpoch(), SBStochParameter::tEpoch(), SBStochParameter::tFinis(), TInf, SBMJD::toString(), SBStochParameter::tStart(), TZero, SBParameter::v(), SBStochParameter::v(), Version, SBLog::write(), and SBLog::WRN.
void SBRunManager::makeReportCRFVariations4IVS ()
Definition at line 1489 of file SbGeoProjectReports.C'.
References SBAttributed::addAttr(), SBSource::Analysed, SBSymMatrix::at(), ClassName(), SBUpperMatrix::clear(), CRF, SBLog::DATA, SBLog::DBG, SBAttributed::delAttr(), SBLog::ERR, SBSourceInfo::EstCoo, SBSourceInfoList::find(), SB_CRF::first(), SBSource::getParameters4Report(), SBParameterList::idx(), SBLog::IO, SBAttributed::isAttr(), IsVLBIOwner, SBCatalog::label(), SBSolution::loadLocCor(), SBVLBISet::loadSession(), SBSetUp::loadVLBI(), Log, mainSetOperation(), SBNamed::name(), SB_CRF::next(), SBSourceInfo::notValid, SBObjectObsInfo::num(), SBDerivation::num(), SBSource::p_DN(), SBSource::p_RA(), SBSetUp::path2Output(), SBSolution::prepare4Batch(), SB_CRF::prepareAliases4Output(), Prj, SB_CRF::releaseAliases4Output(), SBLog::RUN, SBSolutionName::setAcronym(), SBSource::setCorrRA_DN(), SBCatalog::setLabel(), SBSolutionName::setSerial(), SetUp, SBSolutionName::setYear(), Solution, SBProject::sourceList(), SBVLBISession::sourceList(), SBSolution::statByBatch(), VLBI, SBLog::write(), and SBLog::WRN.
Referenced by makeReports().
void SBRunManager::makeReportEOP ()
Definition at line 1650 of file SbGeoProjectReports.C'.
References SBSymMatrix::at(), SBFrame::calc(), SBProject::cfg(), ClassName(), SBLog::DATA, DAY2SEC, SBLog::DBG, SBFrame::dNutation_Eps(), SBFrame::dNutation_Psi(), SBParameter::e(), SBFrame::eop(), SBLog::ERR, SBParameterList::find(), Frame, SBParameterList::idx(), SBLog::IO, IsVLBIOwner, SBSolution::loadLocCor(), SBVLBISet::loadMaster(), SBSetUp::loadVLBI(), SBSolution::local(), Log, SBMaster::lookupMR(), mainSetOperation(), SBVLBISet::master(), SBNamed::name(), SBDerivation::num(), SBEOP::p_Neps(), SBEOP::p_Npsi(), SBEOP::p_Put(), SBEOP::p_Px(), SBEOP::p_Py(), SBSetUp::path2Output(), SBFrame::polar_UT1_UTC(), SBFrame::polar_X(), SBFrame::polar_Y(), SBSolution::prepare4Batch(), SBEOP::prepare4Date(), Prj, RAD2SEC, SBVLBISet::releaseMaster(), SBLog::RUN, SBMasterRecord::sessionCode(), SetUp, Solution, SBSolution::statByBatch(), SBConfig::STR_Classic, SBConfig::sysTransform(), SBDerivation::tEpoch(), SBDerivation::tInterval(), VLBI, SBLog::write(), and SBLog::WRN.
Referenced by makeReports().
void SBRunManager::makeReportMaps ()
Definition at line 56 of file SbGeoProjectReports.C'.
References SBObjectObsInfo::aka(), Vector3::at(), ClassName(), SBStationInfo::ConstrCoo, SBSourceInfo::ConstrCoo, SBStationInfo::ConstrVel, CRF, SBLog::DBG, EAST, SBLog::ERR, SBStationInfo::EstCoo, SBSourceInfo::EstCoo, SBStationInfo::EstVel, SBStationInfoList::find(), SBSourceInfoList::find(), SB_CRF::first(), SBAttributed::isAttr(), Log, Vector3::module(), SBVersion::name(), SBNamed::name(), SB_CRF::next(), NORT, SBStationInfo::notValid, SBSourceInfo::notValid, SBSetUp::path2Output(), Prj, RAD2DEG, RAD2SEC, RefPlates, SBLog::RUN, SBVersion::selfName(), SBStationID::setID(), SetUp, SBProject::sourceList(), SBProject::stationList(), SB_TRF::stations(), TRF, SBPlateMotion::velocity(), Version, VERT, and SBLog::write().
Referenced by makeReports().
void SBRunManager::makeReportNormalEqs ()
Definition at line 2244 of file SbGeoProjectReports.C'.
References ClassName(), SBLog::DATA, SBLog::DBG, SBLog::ERR, SBLog::IO, IsVLBIOwner, SBSolution::loadNormalEqs(), SBSetUp::loadVLBI(), Log, mainSetOperation(), SBNamed::name(), SBSetUp::path2Output(), SBSolution::prepare4Batch(), Prj, SBVLBISet::releaseMaster(), SBLog::RUN, SBTS_SINEX::setRunMgr(), SetUp, Solution, SBSolution::statByBatch(), VLBI, SBLog::write(), writeNormalEquationSystem(), and SBLog::WRN.
Referenced by makeReports().
void SBRunManager::makeReports ()
Definition at line 2792 of file SbGeoProject.C'.
References SBProject::cfg(), ClassName(), SBLog::DBG, SBLog::INF, Log, makeReportCRF(), makeReportCRFVariations4IVS(), makeReportEOP(), makeReportMaps(), makeReportNormalEqs(), makeReportSessionStatistics(), makeReportTechDescription(), makeReportTRF(), makeReportTRFVariations(), makeReportTroposphere(), SBNamed::name(), Prj, SBConfig::reportCRF(), SBConfig::reportCRF_Changes(), SBConfig::reportEOP(), SBConfig::reportMaps(), SBConfig::reportNormalEqs(), SBConfig::reportTechDesc(), SBConfig::reportTRF_Changes(), SBConfig::reportTRF_SINEX(), SBConfig::reportTroposhere(), SBLog::RUN, and SBLog::write().
Referenced by SBMainWindow::ExecuteReportProj().
void SBRunManager::makeReportSessionStatistics ()
Definition at line 2344 of file SbGeoProjectReports.C'.
References ClassName(), SBVLBISesInfo::code(), SBLog::DATA, SBLog::DBG, SBLog::IO, IsVLBIOwner, SBVLBISet::loadSession(), SBSetUp::loadVLBI(), Log, mainSetOperation(), SBNamed::name(), SBVLBISesInfo::notValid, SBVLBISession::numObs(), SBVLBISession::numSou(), SBVLBISession::numSta(), SBVLBISesInfo::officialName(), SBSetUp::path2Output(), Prj, SBLog::RUN, SetUp, SBVLBISession::sourceList(), SBVLBISession::stationList(), SBVLBISesInfo::tFinis(), SBVLBISesInfo::tStart(), VLBI, SBProject::VLBIsessionList(), SBLog::write(), and SBLog::WRN.
Referenced by makeReports().
void SBRunManager::makeReportTechDescription ()
Definition at line 2239 of file SbGeoProjectReports.C'.
References ClassName(), SBLog::DBG, Log, SBLog::RUN, and SBLog::write().
Referenced by makeReports().
void SBRunManager::makeReportTRF ()
Definition at line 1269 of file SbGeoProjectReports.C'.
References SBAttributed::addAttr(), SBStation::Analysed, SB_TRF::at(), ClassName(), SBLog::DATA, SBLog::DBG, SBAttributed::delAttr(), SBLog::ERR, SBStationInfo::EstCoo, SBStationInfo::EstVel, SBStationInfoList::find(), SB_TRF::finisRun(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::id(), SBLog::IO, SBAttributed::isAttr(), IsVLBIOwner, SBCatalog::label(), SBSetUp::loadVLBI(), Log, mainSetOperation(), SBNamed::name(), SBStationInfo::notValid, SBSetUp::path2Output(), SB_TRF::prepare4Run(), Prj, SB_TRF::remove(), SBLog::RUN, SBSolutionName::setAcronym(), SBCatalog::setLabel(), SBTS_SINEX::setRunMgr(), SBSolutionName::setSerial(), SetUp, SBSolutionName::setYear(), SBLog::STATION, SBProject::stationList(), SB_TRF::stations(), TRF, VLBI, SBLog::write(), and SBLog::WRN.
Referenced by makeReports().
void SBRunManager::makeReportTRFVariations ()
Definition at line 747 of file SbGeoProjectReports.C'.
References SBObjectObsInfo::aka(), Matrix3::at(), ClassName(), SBLog::DBG, SBParameter::e(), SBStochParameter::e(), EAST, SBLog::ERR, SBMJD::F_MJD, SBMJD::F_UNIX, SBStationInfoList::find(), SBParameterList::find(), SBStochParameterList::find(), SB_TRF::find(), SBStation::fmVEN(), SBSolution::global(), SBAttributed::isAttr(), SBSolution::local(), Log, SBVersion::name(), SBNamed::name(), NORT, SBStationInfo::notValid, SBStation::p_DRX(), SBStation::p_DRY(), SBStation::p_DRZ(), SBSetUp::path2Output(), SBSolution::prepare4Batch(), Prj, SBStation::r_first(), SBLog::RUN, SBVersion::selfName(), SetUp, SBStation::site(), Solution, SBSolution::statByBatch(), SBProject::stationList(), SB_TRF::stations(), SBSolution::stochastic(), SBDerivation::tEpoch(), SBStochParameter::tEpoch(), SBStochParameter::tFinis(), TInf, SBMJD::toString(), TRF, SBStochParameter::tStart(), TZero, SBParameter::v(), SBStochParameter::v(), v3Zero, Version, VERT, SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by makeReports().
void SBRunManager::makeReportTroposphere ()
Definition at line 2101 of file SbGeoProjectReports.C'.
References SBProject::cfg(), ClassName(), SBLog::DATA, SBLog::DBG, SBLog::ERR, SBLog::IO, IsVLBIOwner, SBVLBISet::loadMaster(), SBVLBISet::loadSession(), SBSetUp::loadVLBI(), Log, SBMaster::lookupMR(), mainSetOperation(), SBVLBISet::master(), SBNamed::name(), SBSetUp::path2Output(), SBSolution::prepare4Batch(), Prj, SBVLBISet::releaseMaster(), SBLog::RUN, SBMasterRecord::sessionCode(), SBProject::setCfg(), SBTS_SINEX::setRunMgr(), SBConfig::setTropSamplInterval(), SetUp, Solution, SBSolution::statByBatch(), SBConfig::tropSamplInterval(), VLBI, SBLog::write(), and SBLog::WRN.
Referenced by makeReports().
SBObservation * SBRunManager::nextObs_m2 () [protected]"Makes the succeeding observation current and returns the new current observation'. Retuns NULL if the current obs() is the last in the list'.
Definition at line 2259 of file SbGeoProject.C'.
References checkParameterLists(), findT_2load(), findT_2save(), loadVLBISessions_m2(), ObsIt, saveVLBISessions_m2(), T_2load, T_2save, and Te.
Referenced by process_m2().
int SBRunManager::numOpenedVLBISessions () const [inline]"Returns the number of current opened VLBI sessions'.
Definition at line 621 of file SbGeoProject.H'.
References VLBISessCache.
SBObsIterator* SBRunManager::obsIt () [inline]
Definition at line 583 of file SbGeoProject.H'.
References ObsIt.
SBObservationList* SBRunManager::obsList () [inline]
Definition at line 580 of file SbGeoProject.H'.
References ObsList.
const SBPlateMotion* SBRunManager::plates () const [inline]
Definition at line 575 of file SbGeoProject.H'.
References Plates.
Referenced by SBStation::calcDisplacement(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), and SBStation::vModel().
bool SBRunManager::prepare4Run_m1 () [protected]
Definition at line 1841 of file SbGeoProject.C'.
References SBStatistics::addNumPars(), AllGlobalList, ArcList, ClassName(), SBProject::clearRMSs(), SBStatistics::clearStatistics(), SBLog::DATA, SBLog::DBG, Estimator, fillParameterList(), GlobalList, SBLog::IO, IsVLBIOwner, SBSetUp::loadVLBI(), LocalList, Log, mainSetOperation(), SBVLBISesInfo::notValid, ObsIt, ObsList, SBEstimator::prepare4Run(), Prj, SBParameterCfg::PT_GLB, SBLog::RUN, SetUp, Solution, SBSolution::statGeneral(), StochList, Te, VLBI, SBProject::VLBIsessionList(), VLBISessions, VLBISessIt, SBLog::write(), and SBLog::WRN.
Referenced by process_m1().
bool SBRunManager::prepare4Run_m2 () [protected]"Prepares the lists for processing'. Returns TRUE if at least one observation exists in a list'.
Definition at line 2071 of file SbGeoProject.C'.
References AllGlobalList, ArcList, checkParameterLists(), ClassName(), SBLog::DATA, SBLog::DBG, Estimator, fillParameterList(), findT_2load(), findT_2save(), GlobalList, SBLog::IO, SBSetUp::loadVLBI(), loadVLBISessions_m2(), LocalList, Log, mainSetOperation(), SBVLBISesInfo::notValid, ObsIt, ObsList, SBEstimator::prepare4Run(), Prj, SBParameterCfg::PT_GLB, SBLog::RUN, SetUp, StochList, T_2load, T_2save, Tb, Te, VLBI, SBProject::VLBIsessionList(), VLBISessions, VLBISessIt, SBLog::write(), and SBLog::WRN.
Referenced by process_m2().
SBProject* SBRunManager::prj () [inline]
Definition at line 570 of file SbGeoProject.H'.
References Prj.
Referenced by SBDelay::calc(), SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBEOP::interpolateEOPs(), SBObsVLBIEntry::isEligible(), operator<<(), SBObsVLBIEntry::process(), process_m1(), SBRunManager(), sinex_tro_TropDescriptionBlock(), SBStation::vModel(), and writeNormalEquationSystem().
void SBRunManager::process () [inline]"Makes a data processing for observations described in Project'.
Definition at line 604 of file SbGeoProject.H'.
References process_m1().
Referenced by SBMainWindow::ExecuteDoubleRunProj(), SBMainWindow::ExecuteRunProj(), and SBVLBIPreProcess::preProcess().
void SBRunManager::process_m1 () [protected]
Definition at line 1575 of file SbGeoProject.C'.
References SBStatistics::addNumPars(), SBDerivation::addNumSes(), AploEphem, SBProject::cfg(), checkParameterLists(), ClassName(), SBParametersDesc::clock0(), constrainClocks(), constraintEOP(), constraintSourceCoord(), constraintStationCoord(), constraintStationVeloc(), SBVLBISesInfo::ConstrEOP, CRF, SBMJD::currentMJD(), SBLog::DBG, SBAploEphem::dismissed(), SBFrame::eop(), SBLog::ERR, SBSourceInfo::EstCoo, Estimator, SB_CRF::find(), SBParameterList::find(), SBEstimator::finisGlobConstr(), SBEstimator::finisLocal(), finisRun_m1(), Frame, SBAploEphem::getReady(), GlobalList, SBLog::INF, SBAploEphem::interval(), SBAttributed::isAttr(), IsNeedToStop, listOfCurrentSessNames(), loadVLBISession_m1(), LocalList, Log, SBLog::logFacilities(), mainPrBarSetProgress(), mainPrBarSetTotalSteps(), mainSetProcObs(), mainSetSessName(), SBObservation::mjd(), SBNamed::name(), SBSourceInfo::notValid, SBProject::numObs(), SBStatistics::numObs(), SBStatistics::numPars(), SBObservation::O_C(), ObsList, SBConfig::p(), SBSource::p_DN(), SBSource::p_RA(), SBParametersDesc::polusNut(), SBParametersDesc::polusUT(), SBParametersDesc::polusXY(), SBSolution::prepare4Batch(), SBEOP::prepare4Date(), SBEstimator::prepare4GlobConstr(), SBEstimator::prepare4Local(), prepare4Run_m1(), Prj, prj(), SBObservation::process(), SBEstimator::processObs(), SBParameterCfg::PT_GLB, SBParameterCfg::PT_NONE, SBParameterCfg::PT_STH, SBAploEphem::registerStation(), SBLog::RUN, saveVLBISessions_m1(), SBSetUp::scale(), SBSetUp::scaleName(), SBLog::setLogFacilities(), SetUp, SBObservation::Sigma(), Solution, SBParametersDesc::srcCoo(), SBParametersDesc::staCoo(), SBSolution::stat4CurrentBatch(), SBSolution::statGeneral(), SB_TRF::stations(), SBParametersDesc::staVel(), StochList, TRF, SBParameterCfg::type(), SBStatistics::VarFactor_unit(), VLBISessCache, VLBISessIt, SBLog::write(), and SBStatistics::WRMS_unit().
Referenced by process().
void SBRunManager::process_m2 () [protected]"Starts data processing using mode 2'.
Definition at line 2035 of file SbGeoProject.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, finisRun_m2(), IsNeedToStop, Log, mainPrBarSetProgress(), mainPrBarSetTotalSteps(), mainSetProcObs(), SBNamed::name(), nextObs_m2(), SBProject::numObs(), ObsIt, prepare4Run_m2(), Prj, SBLog::RUN, and SBLog::write().
const SBPlateMotion* SBRunManager::refPlates () const [inline]
Definition at line 576 of file SbGeoProject.H'.
References RefPlates.
Referenced by SBStation::calcDisplacement(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), and SBStation::vModel().
SBRefraction* SBRunManager::refr () [inline]
Definition at line 585 of file SbGeoProject.H'.
References Refr.
void SBRunManager::saveVLBISessions_m1 () [protected]"Some other very important comments'. We're testing the doxygen (test)'.
Definition at line 1985 of file SbGeoProject.C'.
References ClassName(), CRF, SBLog::DATA, SBLog::DBG, SBVLBISesInfo::delayRMS2(), SBVLBISesInfo::delaySumW2(), SBLog::ERR, listOfCurrentSessNames(), Log, mainSetCacheSizes(), mainSetOperation(), mainSetProcSes(), mainSetSessName(), SBNamed::name(), SBProject::numVLBISessions(), ObsList, prcsVLBISess, Prj, SBVLBISesInfo::rateRMS2(), SBVLBISesInfo::rateSumW2(), SBVLBISet::saveSession(), SBVLBISesInfo::setDelayRMS2(), SBVLBISesInfo::setDelaySumW2(), SBVLBISesInfo::setRateRMS2(), SBVLBISesInfo::setRateSumW2(), TRF, VLBI, VLBISessCache, VLBISessions, and SBLog::write().
Referenced by process_m1().
void SBRunManager::saveVLBISessions_m2 (const SBMJD &T) [protected]"Saves processed VLBI session'. Some other very important comments'. We're testing the doxygen (test)'.
Definition at line 2178 of file SbGeoProject.C'.
References ClassName(), CRF, SBLog::DATA, SBLog::DBG, SBLog::ERR, SBVLBISession::first(), listOfCurrentSessNames(), Log, mainSetCacheSizes(), mainSetOperation(), mainSetProcSes(), mainSetSessName(), SBNamed::name(), SBVLBISession::next(), SBProject::numVLBISessions(), ObsList, prcsVLBISess, Prj, SBVLBISet::saveSession(), TRF, VLBI, VLBISessCache, and SBLog::write().
Referenced by finisRun_m2(), and nextObs_m2().
SBSolution* SBRunManager::solution () [inline]
Definition at line 581 of file SbGeoProject.H'.
References Solution.
Referenced by SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), operator<<(), SBSource::updateParameters(), SBEOP::updateParameters(), SBStation::updateParameters(), and writeNormalEquationSystem().
SBParameterList* SBRunManager::stochList () [inline]"Returns the list of stochastic parameters'.
Definition at line 596 of file SbGeoProject.H'.
References StochList.
Referenced by SBEstimator::prepare4Local().
void SBRunManager::stripCRF () [protected]"Removes unused sources from the CRF catalogue'.
Definition at line 932 of file SbGeoProject.C'.
References ClassName(), CRF, SBLog::DBG, SBLog::ERR, SBSourceInfoList::find(), Log, Prj, SBCatalog::remove(), SBLog::SOURCE, SBProject::sourceList(), and SBLog::write().
Referenced by SBRunManager().
void SBRunManager::stripTRF () [protected]"Removes unused sites and stations from the TRF catalogue'.
Definition at line 952 of file SbGeoProject.C'.
References SB_TRF::at(), ClassName(), SBLog::DBG, SBLog::ERR, SBStationInfoList::find(), SBStation::id(), Log, SBNamed::name(), Prj, SB_TRF::remove(), SBLog::STATION, SBProject::stationList(), TRF, and SBLog::write().
Referenced by SBRunManager().
SBTideLd* SBRunManager::tideLd () [inline]
Definition at line 584 of file SbGeoProject.H'.
References TideLd.
SB_TRF* SBRunManager::trf () [inline]
Definition at line 574 of file SbGeoProject.H'.
References TRF.
Referenced by SBDelay::calcDerivatives(), SBStation::calcDisplacement(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), operator<<(), SBObsVLBIEntry::process(), sinex_tro_TropSolutionBlock(), and writeNormalEquationSystem().
SBVLBISet* SBRunManager::vlbi () const [inline]
Definition at line 571 of file SbGeoProject.H'.
References VLBI.
Referenced by operator<<(), and writeNormalEquationSystem().
Member Data Documentation
SBParameterList* SBRunManager::AllGlobalList [protected]
List of all global parameters;'.
Definition at line 499 of file SbGeoProject.H'.
Referenced by allGlobalList(), finisRun_m1(), finisRun_m2(), prepare4Run_m1(), prepare4Run_m2(), SBRunManager(), and ~SBRunManager().
SBAploEphem* SBRunManager::AploEphem [protected]
Ephemerides of atmospheric pressure loading;'.
Definition at line 480 of file SbGeoProject.H'.
Referenced by aploEphem(), process_m1(), SBRunManager(), and ~SBRunManager().
SBParameterList* SBRunManager::ArcList [protected]
List of arc parameters;'.
Definition at line 501 of file SbGeoProject.H'.
Referenced by arcList(), checkParameterLists(), finisRun_m1(), finisRun_m2(), prepare4Run_m1(), prepare4Run_m2(), SBRunManager(), and ~SBRunManager().
SB_CRF* SBRunManager::CRF [protected]
CRF;'.
Definition at line 485 of file SbGeoProject.H'.
Referenced by constraintSourceCoord(), crf(), fillParameterList(), loadVLBISession_m1(), loadVLBISessions_m2(), makeReportCRF(), makeReportCRFVariations(), makeReportCRFVariations4IVS(), makeReportMaps(), process_m1(), saveVLBISessions_m1(), saveVLBISessions_m2(), SBRunManager(), stripCRF(), and ~SBRunManager().
SBDelay* SBRunManager::Delay [protected]
Delay and rate calculator;'.
Definition at line 486 of file SbGeoProject.H'.
Referenced by delay(), SBRunManager(), and ~SBRunManager().
SBEphem* SBRunManager::Ephem [protected]
Ephemeris;'.
Definition at line 477 of file SbGeoProject.H'.
Referenced by ephem(), SBRunManager(), and ~SBRunManager().
SBEstimator* SBRunManager::Estimator [protected]
estimator;
Definition at line 466 of file SbGeoProject.H'.
Referenced by checkParameterLists(), constrainClocks(), constraintEOP(), constraintSourceCoord(), constraintStationCoord(), constraintStationVeloc(), estimator(), finisRun_m1(), finisRun_m2(), prepare4Run_m1(), prepare4Run_m2(), process_m1(), SBRunManager(), and ~SBRunManager().
SBFrame* SBRunManager::Frame [protected]
Reference frame transformer;'.
Definition at line 476 of file SbGeoProject.H'.
Referenced by constraintEOP(), fillParameterList(), frame(), makeReportEOP(), process_m1(), SBRunManager(), and ~SBRunManager().
SBParameterList* SBRunManager::GlobalList [protected]
List of global parameters;'.
Definition at line 500 of file SbGeoProject.H'.
Referenced by checkParameterLists(), finisRun_m1(), finisRun_m2(), globalList(), prepare4Run_m1(), prepare4Run_m2(), process_m1(), SBRunManager(), and ~SBRunManager().
bool SBRunManager::IsPrjOwner [protected]
Set if manager is project owner;'.
Definition at line 463 of file SbGeoProject.H'.
Referenced by finisRun_m1(), SBRunManager(), and ~SBRunManager().
bool SBRunManager::IsSolutionOwner [protected]
Definition at line 465 of file SbGeoProject.H'.
Referenced by SBRunManager(), and ~SBRunManager().
bool SBRunManager::IsVLBIOwner [protected]
Definition at line 484 of file SbGeoProject.H'.
Referenced by finisRun_m1(), makeReportCRFVariations4IVS(), makeReportEOP(), makeReportNormalEqs(), makeReportSessionStatistics(), makeReportTRF(), makeReportTroposphere(), prepare4Run_m1(), SBRunManager(), and ~SBRunManager().
SBParameterList* SBRunManager::LocalList [protected]
List of local parameters;'.
Definition at line 502 of file SbGeoProject.H'.
Referenced by checkParameterLists(), finisRun_m1(), finisRun_m2(), localList(), prepare4Run_m1(), prepare4Run_m2(), process_m1(), SBRunManager(), and ~SBRunManager().
SBObsIterator* SBRunManager::ObsIt [protected]
Iterator to traverse through the obs'.list;'.
Definition at line 470 of file SbGeoProject.H'.
Referenced by finisRun_m1(), finisRun_m2(), nextObs_m2(), obsIt(), prepare4Run_m1(), prepare4Run_m2(), process_m2(), SBRunManager(), and ~SBRunManager().
SBObservationList SBRunManager::ObsList [protected]
Current/cached list of observations;'.
Definition at line 469 of file SbGeoProject.H'.
Referenced by finisRun_m2(), loadVLBISession_m1(), loadVLBISessions_m2(), obsList(), prepare4Run_m1(), prepare4Run_m2(), process_m1(), saveVLBISessions_m1(), saveVLBISessions_m2(), and SBRunManager().
SBPlateMotion* SBRunManager::Plates [protected]
Tectonic plate motion model;'.
Definition at line 474 of file SbGeoProject.H'.
Referenced by plates(), SBRunManager(), and ~SBRunManager().
int SBRunManager::prcsVLBISess [protected]
number of processed VLBI sessions;
Definition at line 487 of file SbGeoProject.H'.
Referenced by saveVLBISessions_m1(), saveVLBISessions_m2(), and SBRunManager().
SBProject* SBRunManager::Prj [protected]
Current project;'.
Definition at line 462 of file SbGeoProject.H'.
Referenced by constrainClocks(), constraintEOP(), constraintSourceCoord(), constraintStationCoord(), constraintStationVeloc(), fillParameterList(), finisRun_m1(), makeReportCRF(), makeReportCRFVariations(), makeReportCRFVariations4IVS(), makeReportEOP(), makeReportMaps(), makeReportNormalEqs(), makeReports(), makeReportSessionStatistics(), makeReportTRF(), makeReportTRFVariations(), makeReportTroposphere(), prepare4Run_m1(), prepare4Run_m2(), prj(), process_m1(), process_m2(), saveVLBISessions_m1(), saveVLBISessions_m2(), SBRunManager(), stripCRF(), stripTRF(), and ~SBRunManager().
SBPlateMotion* SBRunManager::RefPlates [protected]
Reference model of tectonic plate motion;'.
Definition at line 475 of file SbGeoProject.H'.
Referenced by constraintStationVeloc(), makeReportMaps(), refPlates(), SBRunManager(), and ~SBRunManager().
SBRefraction* SBRunManager::Refr [protected]
Refration calculator;'.
Definition at line 479 of file SbGeoProject.H'.
Referenced by refr(), SBRunManager(), and ~SBRunManager().
SBSolution* SBRunManager::Solution [protected]
solution;
Definition at line 464 of file SbGeoProject.H'.
Referenced by makeReportCRF(), makeReportCRFVariations(), makeReportCRFVariations4IVS(), makeReportEOP(), makeReportNormalEqs(), makeReportTRFVariations(), makeReportTroposphere(), prepare4Run_m1(), process_m1(), SBRunManager(), solution(), and ~SBRunManager().
SBParameterList* SBRunManager::StochList [protected]
List of stochastic parameters;'.
Definition at line 503 of file SbGeoProject.H'.
Referenced by checkParameterLists(), finisRun_m1(), finisRun_m2(), prepare4Run_m1(), prepare4Run_m2(), process_m1(), SBRunManager(), stochList(), and ~SBRunManager().
SBMJD SBRunManager::T_2load [protected]
MJD date of the next session to load;'.
Definition at line 493 of file SbGeoProject.H'.
Referenced by nextObs_m2(), prepare4Run_m2(), and SBRunManager().
SBMJD SBRunManager::T_2save [protected]
MJD date of the session to save;'.
Definition at line 494 of file SbGeoProject.H'.
Referenced by nextObs_m2(), prepare4Run_m2(), and SBRunManager().
SBMJD SBRunManager::Tb [protected]
Definition at line 495 of file SbGeoProject.H'.
Referenced by prepare4Run_m2(), and SBRunManager().
SBMJD SBRunManager::Te [protected]
Definition at line 496 of file SbGeoProject.H'.
Referenced by findT_2load(), findT_2save(), finisRun_m2(), nextObs_m2(), prepare4Run_m1(), prepare4Run_m2(), and SBRunManager().
SBTideLd* SBRunManager::TideLd [protected]
Tide loading calculator;'.
Definition at line 478 of file SbGeoProject.H'.
Referenced by SBRunManager(), tideLd(), and ~SBRunManager().
SB_TRF* SBRunManager::TRF [protected]
TRF;'.
Definition at line 473 of file SbGeoProject.H'.
Referenced by constrainClocks(), constraintStationCoord(), constraintStationVeloc(), fillParameterList(), loadVLBISession_m1(), loadVLBISessions_m2(), makeReportMaps(), makeReportTRF(), makeReportTRFVariations(), process_m1(), saveVLBISessions_m1(), saveVLBISessions_m2(), SBRunManager(), stripTRF(), trf(), and ~SBRunManager().
SBVLBISet* SBRunManager::VLBI [protected]
VLBI dataset;'.
Definition at line 483 of file SbGeoProject.H'.
Referenced by finisRun_m1(), loadVLBISession_m1(), loadVLBISessions_m2(), makeReportCRFVariations4IVS(), makeReportEOP(), makeReportNormalEqs(), makeReportSessionStatistics(), makeReportTRF(), makeReportTroposphere(), prepare4Run_m1(), prepare4Run_m2(), saveVLBISessions_m1(), saveVLBISessions_m2(), SBRunManager(), vlbi(), and ~SBRunManager().
QList<SBVLBISession> SBRunManager::VLBISessCache [protected]
List of current opened sessions;'.
Definition at line 490 of file SbGeoProject.H'.
Referenced by constrainClocks(), fillParameterList(), findT_2save(), finisRun_m2(), listOfCurrentSessNames(), loadVLBISession_m1(), loadVLBISessions_m2(), numOpenedVLBISessions(), process_m1(), saveVLBISessions_m1(), saveVLBISessions_m2(), and SBRunManager().
SBVLBISesInfoList SBRunManager::VLBISessions [protected]
List of VLBI ses' infos ordered by TStart;'.
Definition at line 491 of file SbGeoProject.H'.
Referenced by finisRun_m1(), finisRun_m2(), prepare4Run_m1(), prepare4Run_m2(), saveVLBISessions_m1(), and SBRunManager().
SBVLBISesInfoIterator* SBRunManager::VLBISessIt [protected]
Iterator to traverse through VLBI SessInfo'.s'.
Definition at line 492 of file SbGeoProject.H'.
Referenced by findT_2load(), finisRun_m1(), finisRun_m2(), loadVLBISessions_m2(), prepare4Run_m1(), prepare4Run_m2(), process_m1(), SBRunManager(), and ~SBRunManager().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.