SBSetupDialog::SBInstLI
NAME
SBSetupDialog::SBInstLI -
SYNOPSIS
Inherits QListViewItem'.
Public Member Functions
SBInstLI (QListView *parent, SBInstitution *I_)
SBInstitution * inst ()
virtual QString text (int) const
Private Attributes
SBInstitution * Inst
Detailed Description
Definition at line 90 of file SbISetup.H'.
Constructor & Destructor Documentation
SBSetupDialog::SBInstLI::SBInstLI (QListView *parent, SBInstitution *I_) [inline]
Definition at line 95 of file SbISetup.H'.
References Inst.
Member Function Documentation
SBInstitution* SBSetupDialog::SBInstLI::inst () [inline]
Definition at line 97 of file SbISetup.H'.
References Inst.
Referenced by SBSetupDialog::delInst().
QString SBSetupDialog::SBInstLI::text (intcol) const [virtual]
Definition at line 118 of file SbISetup.C'.
References SBInstitution::descr(), Inst, SBNamed::name(), and TmpString.
Member Data Documentation
SBInstitution* SBSetupDialog::SBInstLI::Inst [private]
Definition at line 93 of file SbISetup.H'.
Referenced by inst(), SBInstLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.