SBSetUp
NAME
SBSetUp -
SYNOPSIS
#include <SbSetup.H>
Public Types
enum DUnits { U_SEC = 0, U_METER = 1, U_INCH = 2 }
enum GUIStyle { S_Default = 0, S_MotifPlus = 1, S_CDE = 2, S_SGI = 3, S_Interlace = 4, S_Windows = 5, S_Platinum = 6 }
Public Member Functions
SBSetUp ()
SBSetUp (const SBSetUp &)
virtual ~SBSetUp ()
virtual QString ClassName () const
virtual void SetDefaults ()
virtual void PeekUpOldConfig (QDataStream &)
virtual void CheckConfig ()
virtual void SaveConfig ()
virtual void SaveStuff ()
virtual void LoadConfig ()
virtual void LoadStuff ()
virtual const SBSetUp & operator= (const SBSetUp &)
virtual const QString & homeDir () const
virtual const QString & dataDir () const
virtual const QString & compileDir () const
virtual const QString & stuffDir () const
virtual const QString & outputDir () const
virtual const QString & solutionsDir () const
virtual const QString & projectDir () const
virtual const QString & logDir () const
virtual const QString & workDir () const
virtual const QString & importDir () const
virtual const QString & importEOPDir () const
virtual const QString & importITRFDir () const
virtual const QString & importICRFDir () const
virtual const QString & importOLoadDir () const
virtual const QString & importMFilesDir () const
virtual const QString & importAploDir () const
virtual const QString & stations () const
virtual const QString & sources () const
virtual const QString & eops () const
virtual const QString & ephem () const
virtual const QString & project () const
virtual int logStoreInFile () const
virtual int logTimeLabel () const
virtual const QString & logFileName () const
virtual uint logFacilities (SBLog::LogLevel _) const
virtual uint logCapacity () const
virtual const QPoint & centralPanelPosition () const
virtual const QSize & centralPanelSize () const
virtual const QFont & defaultFont () const
virtual GUIStyle guiStyle () const
virtual DUnits units () const
virtual SBFCList * fcList ()
virtual void setHomeDir (const QString &S)
virtual void setDataDir (const QString &S)
virtual void setCompileDir (const QString &S)
virtual void setStuffDir (const QString &S)
virtual void setOutputDir (const QString &S)
virtual void setSolutionsDir (const QString &S)
virtual void setProjectDir (const QString &S)
virtual void setLogDir (const QString &S)
virtual void setWorkDir (const QString &S)
virtual void setImportDir (const QString &S)
virtual void setImportEOPDir (const QString &S)
virtual void setImportITRFDir (const QString &S)
virtual void setImportICRFDir (const QString &S)
virtual void setImportOLoadDir (const QString &S)
virtual void setImportMFilesDir (const QString &S)
virtual void setImportAploDir (const QString &S)
virtual void setStations (const QString &S)
virtual void setSources (const QString &S)
virtual void setEOPs (const QString &S)
virtual void setEphem (const QString &S)
virtual void setProject (const QString &S)
virtual void setLogStoreInFile (const int V)
virtual void setLogTimeLabel (const int V)
virtual void setLogFileName (const QString &S)
virtual void setLogFacilities (SBLog::LogLevel Lvl, const uint V)
virtual void setLogCapacity (const uint V)
virtual void setCentralPanelPosition (const QPoint &P)
virtual void setCentralPanelSize (const QSize &S)
virtual void setDefaultFont (const QFont &F)
virtual void setGUIStyle (const GUIStyle S)
virtual void setUnits (const DUnits U)
virtual void UpdateLogger ()
virtual const QString path2Home () const
virtual const QString path2Data () const
virtual const QString path2Log () const
virtual const QString path2Compil () const
virtual const QString path2Stuff () const
virtual const QString path2StuffAplo () const
virtual const QString path2StuffObsStat () const
virtual const QString path2UIDump () const
virtual const QString path2Output () const
virtual const QString path2Sols (const QString &) const
virtual const QString path2Proj () const
virtual const QString path2Work () const
virtual const QString path2Import () const
virtual const QString path2ImpEOP () const
virtual const QString path2ImpITRF () const
virtual const QString path2ImpICRF () const
virtual const QString path2ImpOLoad () const
virtual const QString path2ImpMFiles () const
virtual const QString path2ImpAplo () const
virtual const QString EOPfileName () const
virtual const QString EphemfileName () const
virtual const QString CRFfileName () const
virtual const QString TRFfileName () const
virtual const QString AploFileName () const
virtual const QString VLBIfileName () const
virtual const QString modelsFileName () const
virtual const QString masterFileName () const
virtual const QString ProjectFileName () const
virtual const QString ObsStatFileName (bool IsGlb) const
const QString path2TimeSeries () const
double scale () const
QString scaleName () const
virtual const QString InstitutionsFileName ()
SBEOP * loadEOP (SBEOP *=NULL)
void saveEOP (SBEOP *)
SB_CRF * loadCRF (SB_CRF *=NULL)
void saveCRF (SB_CRF *)
SB_TRF * loadTRF (SB_TRF *=NULL)
void saveTRF (SB_TRF *)
SBVLBISet * loadVLBI (SBVLBISet *=NULL)
void saveVLBI (SBVLBISet *)
SBProject * loadProject (SBProject *=NULL)
void saveProject (SBProject *)
SBAploEphem * loadAploEphem (SBAploEphem *=NULL)
void saveAploEphem (SBAploEphem *)
SBObsVLBIStatistics * loadObsVLBIStatistics (bool)
void saveObsVLBIStatistics (SBObsVLBIStatistics *)
Private Member Functions
void CheckDir (const QString, bool=TRUE)
Private Attributes
QString SetUpFName
bool HaveToSave
QString HomeDir
QString DataDir
QString CompileDir
QString StuffDir
QString OutputDir
QString SolutionsDir
QString ProjectDir
QString LogDir
QString WorkDir
QString ImportDir
QString ImportEOPDir
QString ImportITRFDir
QString ImportICRFDir
QString ImportOLoadDir
QString ImportMFilesDir
QString ImportAploDir
QString Stations
QString Sources
QString EOPs
QString Ephem
QString Project
int LogStoreInFile
int LogTimeLabel
QString LogFileName
uint LogFacilities [4]
uint LogCapacity
QPoint CentralPanelPosition
QSize CentralPanelSize
GUIStyle GUI_Style
QFont DefaultFont
DUnits Units
SBFCList FCL
Static Private Attributes
static const char * sInstitutions = 'institutions.bin'
Friends
QDataStream & operator<< (QDataStream &, const SBSetUp &)
QDataStream & operator>> (QDataStream &, SBSetUp &)
Detailed Description
Definition at line 170 of file SbSetup.H'.
Member Enumeration Documentation
enum SBSetUp::DUnits
Enumerator:
U_SEC
U_METER
U_INCH
Definition at line 173 of file SbSetup.H'.
enum SBSetUp::GUIStyle
Enumerator:
S_Default
S_MotifPlus
S_CDE
S_SGI
S_Interlace
S_Windows
S_Platinum
Definition at line 174 of file SbSetup.H'.
Constructor & Destructor Documentation
SBSetUp::SBSetUp ()
Definition at line 432 of file SbSetup.C'.
References ClassName(), SBLog::CONFIG, HaveToSave, SBLog::INF, Log, SetDefaults(), SetUpFName, and SBLog::write().
SBSetUp::SBSetUp (const SBSetUp &SetUp_)
Definition at line 860 of file SbSetup.C'.
SBSetUp::~SBSetUp () [virtual]
Definition at line 440 of file SbSetup.C'.
Member Function Documentation
virtual const QString SBSetUp::AploFileName () const [inline, virtual]
Definition at line 350 of file SbSetup.H'.
References path2Stuff().
Referenced by loadAploEphem(), and saveAploEphem().
virtual const QPoint& SBSetUp::centralPanelPosition () const [inline, virtual]
Definition at line 280 of file SbSetup.H'.
References CentralPanelPosition.
Referenced by SBMainWindow::SBMainWindow().
virtual const QSize& SBSetUp::centralPanelSize () const [inline, virtual]
Definition at line 281 of file SbSetup.H'.
References CentralPanelSize.
Referenced by SBMainWindow::SBMainWindow().
void SBSetUp::CheckConfig () [virtual]
Definition at line 555 of file SbSetup.C'.
References CheckDir(), HomeDir, path2Compil(), path2Data(), path2Home(), path2ImpAplo(), path2ImpEOP(), path2ImpICRF(), path2ImpITRF(), path2ImpMFiles(), path2ImpOLoad(), path2Import(), path2Log(), path2Output(), path2Proj(), path2Stuff(), path2StuffAplo(), path2StuffObsStat(), path2TimeSeries(), path2UIDump(), path2Work(), and SolutionsDir.
void SBSetUp::CheckDir (const QStringDir, boolhave2write = TRUE) [private]
Definition at line 523 of file SbSetup.C'.
References ClassName(), SBLog::CONFIG, Log, SBVersion::selfName(), Version, SBLog::write(), and SBLog::WRN.
Referenced by CheckConfig().
virtual QString SBSetUp::ClassName () const [inline, virtual]
Definition at line 236 of file SbSetup.H'.
Referenced by CheckDir(), loadAploEphem(), LoadConfig(), loadCRF(), loadEOP(), loadObsVLBIStatistics(), loadProject(), LoadStuff(), loadTRF(), loadVLBI(), saveAploEphem(), SaveConfig(), saveCRF(), saveEOP(), saveObsVLBIStatistics(), saveProject(), SaveStuff(), saveTRF(), saveVLBI(), and SBSetUp().
virtual const QString& SBSetUp::compileDir () const [inline, virtual]
Definition at line 256 of file SbSetup.H'.
References CompileDir.
Referenced by SBSetupDialog::setData().
virtual const QString SBSetUp::CRFfileName () const [inline, virtual]
Definition at line 348 of file SbSetup.H'.
References path2Stuff(), and Sources.
Referenced by loadCRF(), and saveCRF().
virtual const QString& SBSetUp::dataDir () const [inline, virtual]
Definition at line 255 of file SbSetup.H'.
References DataDir.
Referenced by SBSetupDialog::setData().
virtual const QFont& SBSetUp::defaultFont () const [inline, virtual]
Definition at line 282 of file SbSetup.H'.
References DefaultFont.
Referenced by SBMainWindow::ControlSelectFont(), and SBMainWindow::SBMainWindow().
virtual const QString SBSetUp::EOPfileName () const [inline, virtual]
Definition at line 346 of file SbSetup.H'.
References EOPs, and path2Stuff().
Referenced by loadEOP(), and saveEOP().
virtual const QString& SBSetUp::eops () const [inline, virtual]
Definition at line 272 of file SbSetup.H'.
References EOPs.
Referenced by SBCentralPanel::genInfoPanel(), SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), SBMainWindow::SBMainWindow(), and SBSetupDialog::setData().
virtual const QString& SBSetUp::ephem () const [inline, virtual]
Definition at line 273 of file SbSetup.H'.
References Ephem.
virtual const QString SBSetUp::EphemfileName () const [inline, virtual]
Definition at line 347 of file SbSetup.H'.
References Ephem, and path2Stuff().
virtual SBFCList* SBSetUp::fcList () [inline, virtual]
Definition at line 285 of file SbSetup.H'.
References FCL.
Referenced by SBSetupDialog::acquireData(), SBSetupDialog::addPacker(), SBSetupDialog::delPacker(), SBVLBISession::dumpUserInfo(), SBEstimator::finisLocal(), SBEphem::import(), SBVLBISet::import(), SBAploEphem::importEphem(), SBAploEphem::loadChunk(), SBSolution::loadGlbCor(), SBSolution::loadGlbPar(), SBSolution::loadLocCor(), SBSolution::loadLocPar(), SBSolution::loadNormalEqs(), SBSolution::loadStcPar(), SBSetupDialog::packer(), SBEstimator::prepare4Local(), SBVLBISession::restoreUserInfo(), SBAploEphem::saveChunk(), SBSolution::saveGlbCor(), SBSolution::saveGlbPar(), SBSolution::saveLocCor(), SBSolution::saveLocPar(), SBSolution::saveNormalEqs(), SBSolution::saveStcPar(), SBSetupDialog::setData(), SBEstimator::solveLocals(), and SBEstimator::solveStochs().
virtual GUIStyle SBSetUp::guiStyle () const [inline, virtual]
Definition at line 283 of file SbSetup.H'.
References GUI_Style.
Referenced by SBMainWindow::setupMenu().
virtual const QString& SBSetUp::homeDir () const [inline, virtual]
Definition at line 254 of file SbSetup.H'.
References HomeDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::importAploDir () const [inline, virtual]
Definition at line 269 of file SbSetup.H'.
References ImportAploDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::importDir () const [inline, virtual]
Definition at line 263 of file SbSetup.H'.
References ImportDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::importEOPDir () const [inline, virtual]
Definition at line 264 of file SbSetup.H'.
References ImportEOPDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::importICRFDir () const [inline, virtual]
Definition at line 266 of file SbSetup.H'.
References ImportICRFDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::importITRFDir () const [inline, virtual]
Definition at line 265 of file SbSetup.H'.
References ImportITRFDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::importMFilesDir () const [inline, virtual]
Definition at line 268 of file SbSetup.H'.
References ImportMFilesDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::importOLoadDir () const [inline, virtual]
Definition at line 267 of file SbSetup.H'.
References ImportOLoadDir.
Referenced by SBSetupDialog::setData().
virtual const QString SBSetUp::InstitutionsFileName () [inline, virtual]
Definition at line 388 of file SbSetup.H'.
References path2Stuff(), and sInstitutions.
Referenced by LoadStuff(), and SaveStuff().
SBAploEphem * SBSetUp::loadAploEphem (SBAploEphem *Aplo = NULL)
Definition at line 1247 of file SbSetup.C'.
References AploFileName(), ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, and SBLog::write().
Referenced by SBRunManager::SBRunManager(), SBStuffAplo::SBStuffAplo(), and SBTestAPLoad::SBTestAPLoad().
void SBSetUp::LoadConfig () [virtual]
Definition at line 449 of file SbSetup.C'.
References ClassName(), SBLog::CONFIG, SBLog::DBG, SBLog::ERR, HaveToSave, SBLog::INF, Log, PeekUpOldConfig(), SaveConfig(), SBVersion::selfName(), SetDefaults(), SetUpFName, Version, SBLog::write(), and SBLog::WRN.
SB_CRF * SBSetUp::loadCRF (SB_CRF *W = NULL)
Definition at line 1092 of file SbSetup.C'.
References ClassName(), CRFfileName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, and SBLog::write().
Referenced by SBSourceImport::importICRF(), SBStuffSources::reloadCRF(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBStuffSources::SBStuffSources(), and SBSolutionBrowser::updateCRF().
SBEOP * SBSetUp::loadEOP (SBEOP *W = NULL)
Definition at line 1053 of file SbSetup.C'.
References ClassName(), SBLog::DBG, EOPfileName(), SBLog::ERR, SBLog::IO, Log, and SBLog::write().
Referenced by SBStuffEOPs::import(), SBFrame::SBFrame(), SBStuffEOPs::SBStuffEOPs(), SBTestEOP::SBTestEOP(), SBTestNutation::SBTestNutation(), and SBStuffEOPs::updateEOP().
SBObsVLBIStatistics * SBSetUp::loadObsVLBIStatistics (boolIsGlb)
Definition at line 1287 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, ObsStatFileName(), and SBLog::write().
Referenced by SBObsVLBIStatBrowser::SBObsVLBIStatBrowser().
SBProject * SBSetUp::loadProject (SBProject *P = NULL)
Definition at line 1207 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, ProjectFileName(), and SBLog::write().
Referenced by SBMainWindow::ExecuteDrop(), SBMainWindow::SBMainWindow(), SBModelEditor::SBModelEditor(), SBParametersEditor::SBParametersEditor(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolutionBrowser::SBSolutionBrowser(), and SBMainWindow::UtilitiesCollectStat4Prj().
void SBSetUp::LoadStuff () [virtual]
Definition at line 581 of file SbSetup.C'.
References SBMaster::checkNewFiles(), ClassName(), Config, SBLog::DBG, DefaultConfig, SBInstitution::descr(), SBLog::ERR, SBLog::INF, Institutions, InstitutionsFileName(), SBLog::IO, Log, masterFileName(), modelsFileName(), path2ImpMFiles(), VLBIfileName(), and SBLog::write().
SB_TRF * SBSetUp::loadTRF (SB_TRF *W = NULL)
Definition at line 1131 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, TRFfileName(), and SBLog::write().
Referenced by SBStuffAplo::import(), SBStuffAplo::importHPS(), SBStationImport::importITRF(), SBStuffStations::reloadTRF(), SBRunManager::SBRunManager(), SBStuffStations::SBStuffStations(), SBTestAPLoad::SBTestAPLoad(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), and SBSolutionBrowser::updateTRF().
SBVLBISet * SBSetUp::loadVLBI (SBVLBISet *W = NULL)
Definition at line 1169 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, VLBIfileName(), and SBLog::write().
Referenced by SBObsVLBIStatistics::collectStatistics(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTroposphere(), SBRunManager::prepare4Run_m1(), SBRunManager::prepare4Run_m2(), SBProjectEdit::SBProjectEdit(), SBVLBISetViewBase::SBVLBISetViewBase(), SBMainWindow::UtilitiesDumpUI(), and SBMainWindow::UtilitiesRestoreUI().
virtual uint SBSetUp::logCapacity () const [inline, virtual]
Definition at line 279 of file SbSetup.H'.
References LogCapacity.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::logDir () const [inline, virtual]
Definition at line 261 of file SbSetup.H'.
References LogDir.
Referenced by SBSetupDialog::setData().
virtual uint SBSetUp::logFacilities (SBLog::LogLevel_) const [inline, virtual]
Definition at line 278 of file SbSetup.H'.
References LogFacilities.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::logFileName () const [inline, virtual]
Definition at line 277 of file SbSetup.H'.
References LogFileName.
Referenced by SBSetupDialog::setData().
virtual int SBSetUp::logStoreInFile () const [inline, virtual]
Definition at line 275 of file SbSetup.H'.
References LogStoreInFile.
Referenced by SBSetupDialog::setData().
virtual int SBSetUp::logTimeLabel () const [inline, virtual]
Definition at line 276 of file SbSetup.H'.
References LogTimeLabel.
Referenced by SBSetupDialog::setData().
virtual const QString SBSetUp::masterFileName () const [inline, virtual]
Definition at line 353 of file SbSetup.H'.
References path2Stuff().
Referenced by SBVLBISet::loadMaster(), and LoadStuff().
virtual const QString SBSetUp::modelsFileName () const [inline, virtual]
Definition at line 352 of file SbSetup.H'.
References path2Stuff().
Referenced by LoadStuff(), and SaveStuff().
virtual const QString SBSetUp::ObsStatFileName (boolIsGlb) const [inline, virtual]
Definition at line 356 of file SbSetup.H'.
References path2StuffObsStat(), and Project.
Referenced by loadObsVLBIStatistics(), and saveObsVLBIStatistics().
const SBSetUp & SBSetUp::operator= (const SBSetUp &SetUp_) [virtual]
Definition at line 865 of file SbSetup.C'.
References CentralPanelPosition, CentralPanelSize, CompileDir, DataDir, DefaultFont, EOPs, Ephem, FCL, GUI_Style, HomeDir, ImportAploDir, ImportDir, ImportEOPDir, ImportICRFDir, ImportITRFDir, ImportMFilesDir, ImportOLoadDir, LogCapacity, LogDir, LogFacilities, LogFileName, LogStoreInFile, LogTimeLabel, OutputDir, Project, ProjectDir, SolutionsDir, Sources, Stations, StuffDir, Units, and WorkDir.
virtual const QString& SBSetUp::outputDir () const [inline, virtual]
Definition at line 258 of file SbSetup.H'.
References OutputDir.
Referenced by SBSetupDialog::setData().
const QString SBSetUp::path2Compil () const [virtual]
Definition at line 790 of file SbSetup.C'.
References CompileDir, and HomeDir.
Referenced by CheckConfig(), SBVLBISetView::import(), and SBVLBISet::import().
const QString SBSetUp::path2Data () const [virtual]
Definition at line 780 of file SbSetup.C'.
References DataDir, HomeDir, and LogDir.
Referenced by CheckConfig(), SBVLBISesInfo::checkPath(), and SBVLBISesInfo::fileName().
virtual const QString SBSetUp::path2Home () const [inline, virtual]
Definition at line 327 of file SbSetup.H'.
References HomeDir.
Referenced by CheckConfig().
const QString SBSetUp::path2ImpAplo () const [virtual]
Definition at line 855 of file SbSetup.C'.
References HomeDir, and ImportAploDir.
Referenced by CheckConfig(), SBStuffAplo::import(), and SBStuffAplo::importHPS().
const QString SBSetUp::path2ImpEOP () const [virtual]
Definition at line 830 of file SbSetup.C'.
References HomeDir, and ImportEOPDir.
Referenced by CheckConfig(), and SBStuffEOPs::import().
const QString SBSetUp::path2ImpICRF () const [virtual]
Definition at line 840 of file SbSetup.C'.
References HomeDir, and ImportICRFDir.
Referenced by CheckConfig(), SBSourceImport::selectFile1995(), SBSourceImport::selectFile1999(), SBSourceImport::selectFile2009(), SBSourceImport::setupPage2_1(), SBSourceImport::setupPage2_2(), and SBSourceImport::setupPage2_3().
const QString SBSetUp::path2ImpITRF () const [virtual]
Definition at line 835 of file SbSetup.C'.
References HomeDir, and ImportITRFDir.
Referenced by CheckConfig(), SBStationImport::selectFile1994(), SBStationImport::selectFile2000(), SBStationImport::setupPage2_1(), and SBStationImport::setupPage2_2().
const QString SBSetUp::path2ImpMFiles () const [virtual]
Definition at line 850 of file SbSetup.C'.
References HomeDir, and ImportMFilesDir.
Referenced by CheckConfig(), and LoadStuff().
const QString SBSetUp::path2ImpOLoad () const [virtual]
Definition at line 845 of file SbSetup.C'.
References HomeDir, and ImportOLoadDir.
Referenced by CheckConfig(), SBStationImport::selectFileAux(), and SBStationImport::setupPage3().
const QString SBSetUp::path2Import () const [virtual]
Definition at line 825 of file SbSetup.C'.
References HomeDir, and ImportDir.
Referenced by CheckConfig(), SBStuffEphem::import(), SBStuffStationsEcc::importData(), SBStationImport::selectFileAux(), and SBStationImport::setupPage3().
const QString SBSetUp::path2Log () const [virtual]
Definition at line 785 of file SbSetup.C'.
References HomeDir, and LogDir.
Referenced by CheckConfig(), and UpdateLogger().
const QString SBSetUp::path2Output () const [virtual]
Definition at line 805 of file SbSetup.C'.
References HomeDir, and OutputDir.
Referenced by CheckConfig(), SBSolution::dumpParameters(), SBStuffSources::exportData(), SBStuffStations::exportData(), SBVLBISet::import(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SB_TRF::prepare4Run(), SBPlotCarrier::SBPlotCarrier(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), and SBPlotCarrier::setFile4SaveBaseName().
const QString SBSetUp::path2Proj () const [virtual]
Definition at line 815 of file SbSetup.C'.
References HomeDir, and ProjectDir.
Referenced by CheckConfig(), ProjectFileName(), SBProjectSel::remove(), and SBProjectSel::SBProjectSel().
const QString SBSetUp::path2Sols (const QString &PrjName_) const [virtual]
Definition at line 810 of file SbSetup.C'.
References HomeDir, and SolutionsDir.
Referenced by SBSolution::deleteSolution(), SBSolution::loadStatistics(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), and SBSolution::SBSolution().
const QString SBSetUp::path2Stuff () const [virtual]
Definition at line 795 of file SbSetup.C'.
References HomeDir, and StuffDir.
Referenced by AploFileName(), CheckConfig(), CRFfileName(), EOPfileName(), EphemfileName(), SBEphem::import(), InstitutionsFileName(), masterFileName(), modelsFileName(), SBEphem::openFile(), path2StuffAplo(), path2StuffObsStat(), path2UIDump(), TRFfileName(), and VLBIfileName().
virtual const QString SBSetUp::path2StuffAplo () const [inline, virtual]
Definition at line 332 of file SbSetup.H'.
References path2Stuff().
Referenced by CheckConfig(), SBAploEphem::loadChunk(), and SBAploEphem::saveChunk().
virtual const QString SBSetUp::path2StuffObsStat () const [inline, virtual]
Definition at line 333 of file SbSetup.H'.
References path2Stuff().
Referenced by CheckConfig(), and ObsStatFileName().
const QString SBSetUp::path2TimeSeries () const [inline]
Definition at line 359 of file SbSetup.H'.
References HomeDir.
Referenced by CheckConfig(), SBFilteringGauss::readDataFile(), SBSpectrumAnalyserMEM::readDataFile(), SBFilteringGauss::redrawDataPlot(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBSpectrumAnalyserMEM::redrawFPEPlot(), SBSpectrumAnalyserMEM::redrawSpectrumPlot(), SBFilteringGauss::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseData(), SBSpectrumAnalyserMEM::wBrowseSpectrum(), SBFilteringGauss::wBrowseTF(), SBSpectrumAnalyserMEM::wMEMCoeffList(), and SBFilteringGauss::wrote2File().
const QString SBSetUp::path2UIDump () const [virtual]
Definition at line 800 of file SbSetup.C'.
References path2Stuff().
Referenced by CheckConfig(), SBVLBIPreProcess::dumpUI(), SBVLBISet::dumpUserInfo(), SBVLBIPreProcess::restoreUI(), and SBVLBISet::restoreUserInfo().
const QString SBSetUp::path2Work () const [virtual]
Definition at line 820 of file SbSetup.C'.
References HomeDir, and WorkDir.
Referenced by CheckConfig(), and SBEstimator::SBEstimator().
void SBSetUp::PeekUpOldConfig (QDataStream &s) [virtual]
Definition at line 998 of file SbSetup.C'.
References CentralPanelPosition, CentralPanelSize, CompileDir, DataDir, DefaultFont, EOPs, Ephem, FCL, GUI_Style, HomeDir, ImportAploDir, ImportDir, ImportEOPDir, ImportICRFDir, ImportITRFDir, ImportMFilesDir, ImportOLoadDir, LogCapacity, LogDir, LogFacilities, LogFileName, LogStoreInFile, LogTimeLabel, OutputDir, Project, ProjectDir, SetDefaults(), SolutionsDir, Sources, Stations, StuffDir, Units, and WorkDir.
Referenced by LoadConfig().
virtual const QString& SBSetUp::project () const [inline, virtual]
Definition at line 274 of file SbSetup.H'.
References Project.
Referenced by SBMainWindow::ExecuteDoubleRunProj(), SBMainWindow::ExecuteDrop(), SBMainWindow::ExecuteEditProj(), SBMainWindow::ExecuteModels(), SBMainWindow::ExecuteParameters(), SBMainWindow::ExecuteReportProj(), SBMainWindow::ExecuteRunProj(), SBCentralPanel::genInfoPanel(), SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), SB_TRF::prepare4Run(), and SBMainWindow::SBMainWindow().
virtual const QString& SBSetUp::projectDir () const [inline, virtual]
Definition at line 260 of file SbSetup.H'.
References ProjectDir.
Referenced by SBSetupDialog::setData().
virtual const QString SBSetUp::ProjectFileName () const [inline, virtual]
Definition at line 354 of file SbSetup.H'.
References path2Proj(), and Project.
Referenced by SBMainWindow::ExecuteDoubleRunProj(), SBMainWindow::ExecuteEditProj(), SBMainWindow::ExecuteModels(), SBMainWindow::ExecuteParameters(), SBMainWindow::ExecuteReportProj(), SBMainWindow::ExecuteRunProj(), loadProject(), and saveProject().
void SBSetUp::saveAploEphem (SBAploEphem *Aplo)
Definition at line 1271 of file SbSetup.C'.
References AploFileName(), ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, and SBLog::write().
Referenced by SBStuffAplo::accept().
void SBSetUp::SaveConfig () [virtual]
Definition at line 693 of file SbSetup.C'.
References ClassName(), SBLog::CONFIG, SBLog::INF, Log, SetUpFName, and SBLog::write().
Referenced by LoadConfig(), and SBMainWindow::~SBMainWindow().
void SBSetUp::saveCRF (SB_CRF *W)
Definition at line 1115 of file SbSetup.C'.
References ClassName(), CRFfileName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, and SBLog::write().
Referenced by SBStuffSources::accept(), SBStuffSources::importData(), SBSourceImport::importICRF(), and SBSolutionBrowser::updateCRF().
void SBSetUp::saveEOP (SBEOP *W)
Definition at line 1076 of file SbSetup.C'.
References ClassName(), SBLog::DBG, EOPfileName(), SBLog::ERR, SBLog::IO, Log, and SBLog::write().
Referenced by SBStuffEOPs::accept(), and SBStuffEOPs::import().
void SBSetUp::saveObsVLBIStatistics (SBObsVLBIStatistics *Stats)
Definition at line 1312 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, SBObsVLBIStatistics::isGlobal(), Log, ObsStatFileName(), and SBLog::write().
Referenced by SBMainWindow::UtilitiesCollectStat4All(), and SBMainWindow::UtilitiesCollectStat4Prj().
void SBSetUp::saveProject (SBProject *P)
Definition at line 1231 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, ProjectFileName(), and SBLog::write().
Referenced by SBProjectCreate::createProject(), SBRunManager::finisRun_m1(), SBModelEditor::~SBModelEditor(), SBParametersEditor::~SBParametersEditor(), and SBProjectEdit::~SBProjectEdit().
void SBSetUp::SaveStuff () [virtual]
Definition at line 665 of file SbSetup.C'.
References ClassName(), Config, SBLog::DBG, Institutions, InstitutionsFileName(), SBLog::IO, SBConfig::isChanged(), SBInstitutionList::isChanged(), Log, modelsFileName(), and SBLog::write().
Referenced by SBMainWindow::~SBMainWindow().
void SBSetUp::saveTRF (SB_TRF *W)
Definition at line 1154 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, TRFfileName(), and SBLog::write().
Referenced by SBStuffStations::accept(), SBStuffAplo::import(), SBStuffStations::importData(), SBStuffAplo::importHPS(), SBStationImport::importITRF(), and SBSolutionBrowser::updateTRF().
void SBSetUp::saveVLBI (SBVLBISet *W)
Definition at line 1192 of file SbSetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, VLBIfileName(), and SBLog::write().
Referenced by SBVLBISetViewBase::accept(), SBRunManager::finisRun_m1(), and SBVLBIPreProcess::fixSession().
double SBSetUp::scale () const [inline]
Definition at line 361 of file SbSetup.H'.
References U_INCH, U_METER, U_SEC, and Units.
Referenced by SBVLBIPreProcess::fillObsListView(), SBVLBISesInfoLI::key(), SBObsVLBIStatRecordLI::key(), SBVLBISesPreProcLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBRunManager::process_m1(), SBSolutionBrowser::SBSolutionBrowser(), SBVLBIObsPPLI::text(), SBObsVLBIStatRecordLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), and SBSolutionBrowser::wWRMSs().
QString SBSetUp::scaleName () const [inline]
Definition at line 373 of file SbSetup.H'.
References U_INCH, U_METER, U_SEC, and Units.
Referenced by SBRunManager::process_m1(), SBBrowseBases::SBBrowseBases(), SBBrowseSources::SBBrowseSources(), SBBrowseStations::SBBrowseStations(), SBSolutionBrowser::SBSolutionBrowser(), SBVLBIPreProcess::SBVLBIPreProcess(), and SBSolutionBrowser::wWRMSs().
virtual void SBSetUp::setCentralPanelPosition (const QPoint &P) [inline, virtual]
Definition at line 313 of file SbSetup.H'.
References CentralPanelPosition.
Referenced by SBMainWindow::moveEvent(), and SBMainWindow::~SBMainWindow().
virtual void SBSetUp::setCentralPanelSize (const QSize &S) [inline, virtual]
Definition at line 314 of file SbSetup.H'.
References CentralPanelSize.
Referenced by SBMainWindow::resizeEvent(), and SBMainWindow::~SBMainWindow().
virtual void SBSetUp::setCompileDir (const QString &S) [inline, virtual]
Definition at line 289 of file SbSetup.H'.
References CompileDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setDataDir (const QString &S) [inline, virtual]
Definition at line 288 of file SbSetup.H'.
References DataDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setDefaultFont (const QFont &F) [inline, virtual]
Definition at line 315 of file SbSetup.H'.
References DefaultFont.
Referenced by SBMainWindow::ControlSelectFont().
void SBSetUp::SetDefaults () [virtual]
Definition at line 704 of file SbSetup.C'.
References CentralPanelPosition, CentralPanelSize, CompileDir, DataDir, DefaultFont, SBInstitution::descr(), EOPs, Ephem, FCL, GUI_Style, HomeDir, ImportAploDir, ImportDir, ImportEOPDir, ImportICRFDir, ImportITRFDir, ImportMFilesDir, ImportOLoadDir, SBFCList::insert(), Institutions, LogCapacity, LogDir, LogFacilities, LogFileName, LogStoreInFile, LogTimeLabel, OutputDir, Project, ProjectDir, S_Default, SolutionsDir, Sources, Stations, StuffDir, U_SEC, Units, and WorkDir.
Referenced by SBMainWindow::ControlDefault(), LoadConfig(), SBSetupDialog::makeDefaults(), PeekUpOldConfig(), and SBSetUp().
virtual void SBSetUp::setEOPs (const QString &S) [inline, virtual]
Definition at line 305 of file SbSetup.H'.
References EOPs, and mainSetEOPName().
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setEphem (const QString &S) [inline, virtual]
Definition at line 306 of file SbSetup.H'.
References Ephem.
virtual void SBSetUp::setGUIStyle (const GUIStyleS) [inline, virtual]
Definition at line 316 of file SbSetup.H'.
References GUI_Style.
Referenced by SBMainWindow::changeStyle().
virtual void SBSetUp::setHomeDir (const QString &S) [inline, virtual]
Definition at line 287 of file SbSetup.H'.
References HomeDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setImportAploDir (const QString &S) [inline, virtual]
Definition at line 302 of file SbSetup.H'.
References ImportAploDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setImportDir (const QString &S) [inline, virtual]
Definition at line 296 of file SbSetup.H'.
References ImportDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setImportEOPDir (const QString &S) [inline, virtual]
Definition at line 297 of file SbSetup.H'.
References ImportEOPDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setImportICRFDir (const QString &S) [inline, virtual]
Definition at line 299 of file SbSetup.H'.
References ImportICRFDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setImportITRFDir (const QString &S) [inline, virtual]
Definition at line 298 of file SbSetup.H'.
References ImportITRFDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setImportMFilesDir (const QString &S) [inline, virtual]
Definition at line 301 of file SbSetup.H'.
References ImportMFilesDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setImportOLoadDir (const QString &S) [inline, virtual]
Definition at line 300 of file SbSetup.H'.
References ImportOLoadDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setLogCapacity (const uintV) [inline, virtual]
Definition at line 312 of file SbSetup.H'.
References LogCapacity.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setLogDir (const QString &S) [inline, virtual]
Definition at line 294 of file SbSetup.H'.
References LogDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setLogFacilities (SBLog::LogLevelLvl, const uintV) [inline, virtual]
Definition at line 311 of file SbSetup.H'.
References LogFacilities.
virtual void SBSetUp::setLogFileName (const QString &S) [inline, virtual]
Definition at line 310 of file SbSetup.H'.
References LogFileName.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setLogStoreInFile (const intV) [inline, virtual]
Definition at line 308 of file SbSetup.H'.
References LogStoreInFile.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setLogTimeLabel (const intV) [inline, virtual]
Definition at line 309 of file SbSetup.H'.
References LogTimeLabel.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setOutputDir (const QString &S) [inline, virtual]
Definition at line 291 of file SbSetup.H'.
References OutputDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setProject (const QString &S) [inline, virtual]
Definition at line 307 of file SbSetup.H'.
References mainSetPrjName(), and Project.
Referenced by SBProjectSel::accept(), and SBProjectCreate::createProject().
virtual void SBSetUp::setProjectDir (const QString &S) [inline, virtual]
Definition at line 293 of file SbSetup.H'.
References ProjectDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setSolutionsDir (const QString &S) [inline, virtual]
Definition at line 292 of file SbSetup.H'.
References SolutionsDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setSources (const QString &S) [inline, virtual]
Definition at line 304 of file SbSetup.H'.
References mainSetCRFName(), and Sources.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setStations (const QString &S) [inline, virtual]
Definition at line 303 of file SbSetup.H'.
References mainSetTRFName(), and Stations.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setStuffDir (const QString &S) [inline, virtual]
Definition at line 290 of file SbSetup.H'.
References StuffDir.
Referenced by SBSetupDialog::acquireData().
virtual void SBSetUp::setUnits (const DUnitsU) [inline, virtual]
Definition at line 317 of file SbSetup.H'.
References Units.
Referenced by SBSetupDialog::acquireData(), and SBVLBISetViewBase::unitsChanged().
virtual void SBSetUp::setWorkDir (const QString &S) [inline, virtual]
Definition at line 295 of file SbSetup.H'.
References WorkDir.
Referenced by SBSetupDialog::acquireData().
virtual const QString& SBSetUp::solutionsDir () const [inline, virtual]
Definition at line 259 of file SbSetup.H'.
References SolutionsDir.
Referenced by SBSetupDialog::setData().
virtual const QString& SBSetUp::sources () const [inline, virtual]
Definition at line 271 of file SbSetup.H'.
References Sources.
Referenced by SBStuffSources::exportData(), SBCentralPanel::genInfoPanel(), SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), SBMainWindow::SBMainWindow(), and SBSetupDialog::setData().
virtual const QString& SBSetUp::stations () const [inline, virtual]
Definition at line 270 of file SbSetup.H'.
References Stations.
Referenced by SBStuffStations::exportData(), SBCentralPanel::genInfoPanel(), SBSetupDialog::makeApply(), SBSetupDialog::makeDefaults(), SBMainWindow::SBMainWindow(), and SBSetupDialog::setData().
virtual const QString& SBSetUp::stuffDir () const [inline, virtual]
Definition at line 257 of file SbSetup.H'.
References StuffDir.
Referenced by SBSetupDialog::setData().
virtual const QString SBSetUp::TRFfileName () const [inline, virtual]
Definition at line 349 of file SbSetup.H'.
References path2Stuff(), and Stations.
Referenced by loadTRF(), and saveTRF().
virtual DUnits SBSetUp::units () const [inline, virtual]
Definition at line 284 of file SbSetup.H'.
References Units.
Referenced by SBSetupDialog::misc(), SBVLBISessionEditor::SBVLBISessionEditor(), SBSetupDialog::setData(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), and SBVLBISetViewBase::unitsGroup().
void SBSetUp::UpdateLogger () [virtual]
Definition at line 768 of file SbSetup.C'.
References SBLog::DBG, SBLog::ERR, SBLog::INF, Log, LogCapacity, LogFacilities, LogFileName, LogStoreInFile, LogTimeLabel, path2Log(), SBLog::setCapacity(), SBLog::setLogFacilities(), SBLog::setLogFileName(), SBLog::setStoreInFile(), SBLog::setTimeLabel(), and SBLog::WRN.
Referenced by SBSetupDialog::makeApply().
virtual const QString SBSetUp::VLBIfileName () const [inline, virtual]
Definition at line 351 of file SbSetup.H'.
References path2Stuff().
Referenced by LoadStuff(), loadVLBI(), and saveVLBI().
virtual const QString& SBSetUp::workDir () const [inline, virtual]
Definition at line 262 of file SbSetup.H'.
References WorkDir.
Referenced by SBSetupDialog::setData().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBSetUp &SetUp_) [friend]
Definition at line 905 of file SbSetup.C'.
QDataStream& operator>> (QDataStream &s, SBSetUp &SetUp_) [friend]
Definition at line 950 of file SbSetup.C'.
Member Data Documentation
QPoint SBSetUp::CentralPanelPosition [private]
Definition at line 219 of file SbSetup.H'.
Referenced by centralPanelPosition(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), setCentralPanelPosition(), and SetDefaults().
QSize SBSetUp::CentralPanelSize [private]
Definition at line 220 of file SbSetup.H'.
Referenced by centralPanelSize(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), setCentralPanelSize(), and SetDefaults().
QString SBSetUp::CompileDir [private]
Definition at line 189 of file SbSetup.H'.
Referenced by compileDir(), operator<<(), operator=(), operator>>(), path2Compil(), PeekUpOldConfig(), setCompileDir(), and SetDefaults().
QString SBSetUp::DataDir [private]
Definition at line 188 of file SbSetup.H'.
Referenced by dataDir(), operator<<(), operator=(), operator>>(), path2Data(), PeekUpOldConfig(), setDataDir(), and SetDefaults().
QFont SBSetUp::DefaultFont [private]
Definition at line 222 of file SbSetup.H'.
Referenced by defaultFont(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), setDefaultFont(), and SetDefaults().
QString SBSetUp::EOPs [private]
Definition at line 206 of file SbSetup.H'.
Referenced by EOPfileName(), eops(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), and setEOPs().
QString SBSetUp::Ephem [private]
Definition at line 207 of file SbSetup.H'.
Referenced by ephem(), EphemfileName(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), and setEphem().
SBFCList SBSetUp::FCL [private]
Definition at line 226 of file SbSetup.H'.
Referenced by fcList(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), and SetDefaults().
GUIStyle SBSetUp::GUI_Style [private]
Definition at line 221 of file SbSetup.H'.
Referenced by guiStyle(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), and setGUIStyle().
bool SBSetUp::HaveToSave [private]
Definition at line 181 of file SbSetup.H'.
Referenced by LoadConfig(), and SBSetUp().
QString SBSetUp::HomeDir [private]
Definition at line 187 of file SbSetup.H'.
Referenced by CheckConfig(), homeDir(), operator<<(), operator=(), operator>>(), path2Compil(), path2Data(), path2Home(), path2ImpAplo(), path2ImpEOP(), path2ImpICRF(), path2ImpITRF(), path2ImpMFiles(), path2ImpOLoad(), path2Import(), path2Log(), path2Output(), path2Proj(), path2Sols(), path2Stuff(), path2TimeSeries(), path2Work(), PeekUpOldConfig(), SetDefaults(), and setHomeDir().
QString SBSetUp::ImportAploDir [private]
Definition at line 202 of file SbSetup.H'.
Referenced by importAploDir(), operator<<(), operator=(), operator>>(), path2ImpAplo(), PeekUpOldConfig(), SetDefaults(), and setImportAploDir().
QString SBSetUp::ImportDir [private]
Definition at line 196 of file SbSetup.H'.
Referenced by importDir(), operator<<(), operator=(), operator>>(), path2Import(), PeekUpOldConfig(), SetDefaults(), and setImportDir().
QString SBSetUp::ImportEOPDir [private]
Definition at line 197 of file SbSetup.H'.
Referenced by importEOPDir(), operator<<(), operator=(), operator>>(), path2ImpEOP(), PeekUpOldConfig(), SetDefaults(), and setImportEOPDir().
QString SBSetUp::ImportICRFDir [private]
Definition at line 199 of file SbSetup.H'.
Referenced by importICRFDir(), operator<<(), operator=(), operator>>(), path2ImpICRF(), PeekUpOldConfig(), SetDefaults(), and setImportICRFDir().
QString SBSetUp::ImportITRFDir [private]
Definition at line 198 of file SbSetup.H'.
Referenced by importITRFDir(), operator<<(), operator=(), operator>>(), path2ImpITRF(), PeekUpOldConfig(), SetDefaults(), and setImportITRFDir().
QString SBSetUp::ImportMFilesDir [private]
Definition at line 201 of file SbSetup.H'.
Referenced by importMFilesDir(), operator<<(), operator=(), operator>>(), path2ImpMFiles(), PeekUpOldConfig(), SetDefaults(), and setImportMFilesDir().
QString SBSetUp::ImportOLoadDir [private]
Definition at line 200 of file SbSetup.H'.
Referenced by importOLoadDir(), operator<<(), operator=(), operator>>(), path2ImpOLoad(), PeekUpOldConfig(), SetDefaults(), and setImportOLoadDir().
uint SBSetUp::LogCapacity [private]
Definition at line 217 of file SbSetup.H'.
Referenced by logCapacity(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), setLogCapacity(), and UpdateLogger().
QString SBSetUp::LogDir [private]
Definition at line 194 of file SbSetup.H'.
Referenced by logDir(), operator<<(), operator=(), operator>>(), path2Data(), path2Log(), PeekUpOldConfig(), SetDefaults(), and setLogDir().
uint SBSetUp::LogFacilities[4] [private]
Definition at line 216 of file SbSetup.H'.
Referenced by logFacilities(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), setLogFacilities(), and UpdateLogger().
QString SBSetUp::LogFileName [private]
Definition at line 215 of file SbSetup.H'.
Referenced by logFileName(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), setLogFileName(), and UpdateLogger().
int SBSetUp::LogStoreInFile [private]
Definition at line 213 of file SbSetup.H'.
Referenced by logStoreInFile(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), setLogStoreInFile(), and UpdateLogger().
int SBSetUp::LogTimeLabel [private]
Definition at line 214 of file SbSetup.H'.
Referenced by logTimeLabel(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), setLogTimeLabel(), and UpdateLogger().
QString SBSetUp::OutputDir [private]
Definition at line 191 of file SbSetup.H'.
Referenced by operator<<(), operator=(), operator>>(), outputDir(), path2Output(), PeekUpOldConfig(), SetDefaults(), and setOutputDir().
QString SBSetUp::Project [private]
Definition at line 208 of file SbSetup.H'.
Referenced by ObsStatFileName(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), project(), ProjectFileName(), SetDefaults(), and setProject().
QString SBSetUp::ProjectDir [private]
Definition at line 193 of file SbSetup.H'.
Referenced by operator<<(), operator=(), operator>>(), path2Proj(), PeekUpOldConfig(), projectDir(), SetDefaults(), and setProjectDir().
QString SBSetUp::SetUpFName [private]
Definition at line 180 of file SbSetup.H'.
Referenced by LoadConfig(), SaveConfig(), and SBSetUp().
const char * SBSetUp::sInstitutions = 'institutions.bin' [static, private]
Definition at line 177 of file SbSetup.H'.
Referenced by InstitutionsFileName().
QString SBSetUp::SolutionsDir [private]
Definition at line 192 of file SbSetup.H'.
Referenced by CheckConfig(), operator<<(), operator=(), operator>>(), path2Sols(), PeekUpOldConfig(), SetDefaults(), setSolutionsDir(), and solutionsDir().
QString SBSetUp::Sources [private]
Definition at line 205 of file SbSetup.H'.
Referenced by CRFfileName(), operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), setSources(), and sources().
QString SBSetUp::Stations [private]
Definition at line 204 of file SbSetup.H'.
Referenced by operator<<(), operator=(), operator>>(), PeekUpOldConfig(), SetDefaults(), setStations(), stations(), and TRFfileName().
QString SBSetUp::StuffDir [private]
Definition at line 190 of file SbSetup.H'.
Referenced by operator<<(), operator=(), operator>>(), path2Stuff(), PeekUpOldConfig(), SetDefaults(), setStuffDir(), and stuffDir().
DUnits SBSetUp::Units [private]
Definition at line 224 of file SbSetup.H'.
Referenced by operator<<(), operator=(), operator>>(), PeekUpOldConfig(), scale(), scaleName(), SetDefaults(), setUnits(), and units().
QString SBSetUp::WorkDir [private]
Definition at line 195 of file SbSetup.H'.
Referenced by operator<<(), operator=(), operator>>(), path2Work(), PeekUpOldConfig(), SetDefaults(), setWorkDir(), and workDir().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.