SBSetupDialog
NAME
SBSetupDialog -
SYNOPSIS
#include <SbISetup.H>
Inherits SBTabDialog'.
Classes
class SBInstLI
Public Member Functions
SBSetupDialog (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBSetupDialog ()
virtual QString ClassName () const
Protected Slots
virtual void done (int r)
Protected Member Functions
QWidget * pathes ()
QWidget * logger ()
QWidget * packer ()
QWidget * misc ()
QWidget * institutions ()
virtual void closeEvent (QCloseEvent *)
Protected Attributes
SBSetUp * setup
QLineEdit * PathLE [19]
QCheckBox * cbLogStoreInFile
QCheckBox * cbLogTimeLabel
QLineEdit * eLogFileName
QSpinBox * sLogCapacity
QCheckBox * cbLLevel [4][32]
QListView * FConv
QLineEdit * FCName
QLineEdit * FCComp
QLineEdit * FCExtr
QLineEdit * FCExt
QComboBox * FCDefault
QRadioButton * rbUnitNames [3]
SBInstitutionList * InstList
QListView * lvInst
QLineEdit * leAcronym
QLineEdit * leDescr
Private Slots
virtual void setData ()
virtual void makeApply ()
virtual void makeDefaults ()
void addPacker ()
void delPacker ()
void chkPacker ()
void addInst ()
void delInst ()
Private Member Functions
virtual void acquireData ()
Detailed Description
SBSetupDialog'. Allows users to configure the software (general thingth, not related to geodynamics at all)'.
Definition at line 69 of file SbISetup.H'.
Constructor & Destructor Documentation
SBSetupDialog::SBSetupDialog (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 132 of file SbISetup.C'.
References Institutions, institutions(), InstList, logger(), makeApply(), makeDefaults(), misc(), packer(), pathes(), setData(), SetUp, and setup.
SBSetupDialog::~SBSetupDialog ()
Definition at line 588 of file SbISetup.C'.
References InstList, and setup.
Member Function Documentation
void SBSetupDialog::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 840 of file SbISetup.C'.
References cbLLevel, cbLogStoreInFile, cbLogTimeLabel, SBLog::DBG, eLogFileName, SBLog::ERR, FCDefault, SBSetUp::fcList(), SBLog::INF, LogFacilities, PathLE, rbUnitNames, SBSetUp::setCompileDir(), SBSetUp::setDataDir(), SBFCList::setDefault(), SBSetUp::setEOPs(), SBSetUp::setHomeDir(), SBSetUp::setImportAploDir(), SBSetUp::setImportDir(), SBSetUp::setImportEOPDir(), SBSetUp::setImportICRFDir(), SBSetUp::setImportITRFDir(), SBSetUp::setImportMFilesDir(), SBSetUp::setImportOLoadDir(), SBSetUp::setLogCapacity(), SBSetUp::setLogDir(), SBSetUp::setLogFileName(), SBSetUp::setLogStoreInFile(), SBSetUp::setLogTimeLabel(), SBSetUp::setOutputDir(), SBSetUp::setProjectDir(), SBSetUp::setSolutionsDir(), SBSetUp::setSources(), SBSetUp::setStations(), SBSetUp::setStuffDir(), SBSetUp::setUnits(), setup, SBSetUp::setWorkDir(), sLogCapacity, SBSetUp::U_INCH, SBSetUp::U_METER, SBSetUp::U_SEC, and SBLog::WRN.
void SBSetupDialog::addInst () [private, slot]
Definition at line 594 of file SbISetup.C'.
References SBInstitutionList::find(), SBInstitutionList::insert(), InstList, leAcronym, leDescr, and lvInst.
Referenced by institutions().
void SBSetupDialog::addPacker () [private, slot]
Definition at line 695 of file SbISetup.C'.
References SBFileConv::check(), FCComp, FCExt, FCExtr, SBSetUp::fcList(), FCName, FConv, SBFCList::insert(), and setup.
Referenced by packer().
void SBSetupDialog::chkPacker () [private, slot]
Definition at line 680 of file SbISetup.C'.
References SBFileConv::check(), SBFileConv::comCompr(), SBFileConv::comUncom(), SBFileConvLI::entry(), FConv, and SBNamed::name().
Referenced by packer().
virtual QString SBSetupDialog::ClassName () const [inline, virtual]
Definition at line 76 of file SbISetup.H'.
Referenced by delInst(), delPacker(), makeApply(), and makeDefaults().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
void SBSetupDialog::delInst () [private, slot]
Definition at line 622 of file SbISetup.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBSetupDialog::SBInstLI::inst(), InstList, SBLog::INTERFACE, Log, lvInst, SBNamed::name(), SBInstitutionList::remove(), and SBLog::write().
Referenced by institutions().
void SBSetupDialog::delPacker () [private, slot]
Definition at line 651 of file SbISetup.C'.
References ClassName(), SBLog::DBG, SBFileConvLI::entry(), SBLog::ERR, SBSetUp::fcList(), FConv, SBLog::INTERFACE, Log, SBNamed::name(), SBFCList::remove(), setup, and SBLog::write().
Referenced by packer().
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
QWidget * SBSetupDialog::institutions () [protected]
Definition at line 529 of file SbISetup.C'.
References addInst(), delInst(), InstList, leAcronym, leDescr, and lvInst.
Referenced by SBSetupDialog().
QWidget * SBSetupDialog::logger () [protected]
Definition at line 228 of file SbISetup.C'.
References cbLLevel, cbLogStoreInFile, cbLogTimeLabel, eLogFileName, and sLogCapacity.
Referenced by SBSetupDialog().
void SBSetupDialog::makeApply () [private, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 806 of file SbISetup.C'.
References ClassName(), SBLog::DBG, SBSetUp::eops(), Institutions, InstList, SBLog::INTERFACE, Log, mainSetCRFName(), mainSetEOPName(), mainSetPrjName(), mainSetTRFName(), SBSetUp::project(), SetUp, setup, SBSetUp::sources(), SBSetUp::stations(), SBSetUp::UpdateLogger(), and SBLog::write().
Referenced by SBSetupDialog().
void SBSetupDialog::makeDefaults () [private, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 824 of file SbISetup.C'.
References ClassName(), SBLog::DBG, SBSetUp::eops(), SBLog::INTERFACE, Log, mainSetCRFName(), mainSetEOPName(), mainSetPrjName(), mainSetTRFName(), SBSetUp::project(), setData(), SBSetUp::SetDefaults(), setup, SBSetUp::sources(), SBSetUp::stations(), and SBLog::write().
Referenced by SBSetupDialog().
QWidget * SBSetupDialog::misc () [protected]
Definition at line 494 of file SbISetup.C'.
References rbUnitNames, setup, and SBSetUp::units().
Referenced by SBSetupDialog().
QWidget * SBSetupDialog::packer () [protected]
Definition at line 386 of file SbISetup.C'.
References addPacker(), chkPacker(), SBFCList::defaultName(), delPacker(), FCComp, FCDefault, FCExt, FCExtr, SBSetUp::fcList(), FCName, FConv, and setup.
Referenced by SBSetupDialog().
QWidget * SBSetupDialog::pathes () [protected]
Definition at line 158 of file SbISetup.C'.
References PathLE.
Referenced by SBSetupDialog().
void SBSetupDialog::setData () [private, virtual, slot]
Definition at line 736 of file SbISetup.C'.
References cbLLevel, cbLogStoreInFile, cbLogTimeLabel, SBSetUp::compileDir(), SBSetUp::dataDir(), SBLog::DBG, SBFCList::defaultName(), eLogFileName, SBSetUp::eops(), SBLog::ERR, FCDefault, SBSetUp::fcList(), FConv, SBSetUp::homeDir(), SBSetUp::importAploDir(), SBSetUp::importDir(), SBSetUp::importEOPDir(), SBSetUp::importICRFDir(), SBSetUp::importITRFDir(), SBSetUp::importMFilesDir(), SBSetUp::importOLoadDir(), SBLog::INF, InstList, leAcronym, leDescr, SBSetUp::logCapacity(), SBSetUp::logDir(), LogFacilities, SBSetUp::logFacilities(), SBSetUp::logFileName(), SBSetUp::logStoreInFile(), SBSetUp::logTimeLabel(), lvInst, SBSetUp::outputDir(), PathLE, SBSetUp::projectDir(), rbUnitNames, setup, sLogCapacity, SBSetUp::solutionsDir(), SBSetUp::sources(), SBSetUp::stations(), SBSetUp::stuffDir(), SBSetUp::units(), SBSetUp::workDir(), and SBLog::WRN.
Referenced by makeDefaults(), and SBSetupDialog().
Member Data Documentation
QCheckBox* SBSetupDialog::cbLLevel[4][32] [protected]
Definition at line 115 of file SbISetup.H'.
Referenced by acquireData(), logger(), and setData().
QCheckBox* SBSetupDialog::cbLogStoreInFile [protected]
Definition at line 111 of file SbISetup.H'.
Referenced by acquireData(), logger(), and setData().
QCheckBox* SBSetupDialog::cbLogTimeLabel [protected]
Definition at line 112 of file SbISetup.H'.
Referenced by acquireData(), logger(), and setData().
QLineEdit* SBSetupDialog::eLogFileName [protected]
Definition at line 113 of file SbISetup.H'.
Referenced by acquireData(), logger(), and setData().
QLineEdit* SBSetupDialog::FCComp [protected]
Definition at line 121 of file SbISetup.H'.
Referenced by addPacker(), and packer().
QComboBox* SBSetupDialog::FCDefault [protected]
Definition at line 124 of file SbISetup.H'.
Referenced by acquireData(), packer(), and setData().
QLineEdit* SBSetupDialog::FCExt [protected]
Definition at line 123 of file SbISetup.H'.
Referenced by addPacker(), and packer().
QLineEdit* SBSetupDialog::FCExtr [protected]
Definition at line 122 of file SbISetup.H'.
Referenced by addPacker(), and packer().
QLineEdit* SBSetupDialog::FCName [protected]
Definition at line 120 of file SbISetup.H'.
Referenced by addPacker(), and packer().
QListView* SBSetupDialog::FConv [protected]
Definition at line 119 of file SbISetup.H'.
Referenced by addPacker(), chkPacker(), delPacker(), packer(), and setData().
SBInstitutionList* SBSetupDialog::InstList [protected]
Definition at line 132 of file SbISetup.H'.
Referenced by addInst(), delInst(), institutions(), makeApply(), SBSetupDialog(), setData(), and ~SBSetupDialog().
QLineEdit* SBSetupDialog::leAcronym [protected]
Definition at line 134 of file SbISetup.H'.
Referenced by addInst(), institutions(), and setData().
QLineEdit* SBSetupDialog::leDescr [protected]
Definition at line 135 of file SbISetup.H'.
Referenced by addInst(), institutions(), and setData().
QListView* SBSetupDialog::lvInst [protected]
Definition at line 133 of file SbISetup.H'.
Referenced by addInst(), delInst(), institutions(), and setData().
QLineEdit* SBSetupDialog::PathLE[19] [protected]
Definition at line 107 of file SbISetup.H'.
Referenced by acquireData(), pathes(), and setData().
QRadioButton* SBSetupDialog::rbUnitNames[3] [protected]
Definition at line 128 of file SbISetup.H'.
Referenced by acquireData(), misc(), and setData().
SBSetUp* SBSetupDialog::setup [protected]
Definition at line 103 of file SbISetup.H'.
Referenced by acquireData(), addPacker(), delPacker(), makeApply(), makeDefaults(), misc(), packer(), SBSetupDialog(), setData(), and ~SBSetupDialog().
QSpinBox* SBSetupDialog::sLogCapacity [protected]
Definition at line 114 of file SbISetup.H'.
Referenced by acquireData(), logger(), and setData().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.