SBSiteEditor
NAME
SBSiteEditor -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits SBTabDialog'.
Signals
void siteModified (bool)
Public Member Functions
SBSiteEditor (SBSiteListItem *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
SBSiteEditor (QListView *, SB_TRF *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBSiteEditor ()
virtual QString ClassName () const
Protected Slots
virtual void makeDefaults ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Private Slots
void makeApply ()
virtual void done (int)
void editEntry (QListViewItem *)
void insertEntry ()
void deleteEntry ()
void stationModified (bool)
Private Member Functions
virtual void acquireData ()
void init ()
QWidget * wSite ()
QWidget * wOLoad ()
Private Attributes
QListView * SitesLV
SBSiteListItem * SiteItem
SBSite * Site
SB_TRF * Wtrf
bool isModified
bool isNew
int numOpenedWindows
SBOLoadEditor * OLoadEditor
QString str
QListView * StationsLV
QLineEdit * EName
QLineEdit * EDome
QLineEdit * ECountry
QLineEdit * EPlate
QGroupBox * NameGBox
QLineEdit * EV [3]
QLineEdit * EdV [3]
Detailed Description
Definition at line 431 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBSiteEditor::SBSiteEditor (SBSiteListItem *SiteItem_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2600 of file SbIStuffStation.C'.
References init(), isNew, SBSiteListItem::Site, Site, SiteItem, SitesLV, and Wtrf.
SBSiteEditor::SBSiteEditor (QListView *SitesLV_, SB_TRF *Wtrf_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2613 of file SbIStuffStation.C'.
References init(), isNew, Site, SiteItem, SitesLV, and Wtrf.
SBSiteEditor::~SBSiteEditor ()
Definition at line 2627 of file SbIStuffStation.C'.
References isModified, isNew, Site, and siteModified().
Member Function Documentation
void SBSiteEditor::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 2937 of file SbIStuffStation.C'.
References SBOLoadEditor::collectData(), SBSite::country(), SBSite::domeMajor(), ECountry, EDome, EdV, EName, EPlate, EV, isModified, isNew, SBNamed::name(), OLoadEditor, SBSite::plate(), SBSite::setCountry(), SBSite::setDomeMajor(), SBNamed::setName(), SBSite::setPlate(), SBSite::setV(), SBSite::setV_err(), Site, str, SBSite::v(), SBSite::v_err(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by done(), and makeApply().
virtual QString SBSiteEditor::ClassName () const [inline, virtual]
Definition at line 438 of file SbIStuffStation.H'.
Referenced by deleteEntry(), editEntry(), insertEntry(), and makeApply().
virtual void SBSiteEditor::closeEvent (QCloseEvent *e) [inline, protected, virtual]
Reimplemented from SBTabDialog'.
Definition at line 486 of file SbIStuffStation.H'.
References numOpenedWindows.
void SBSiteEditor::deleteEntry () [private, slot]
Definition at line 2899 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBSite::delStation(), SBLog::INTERFACE, isModified, Log, SBNamed::name(), Site, SBStationListItem::Station, StationsLV, str, and SBLog::write().
Referenced by wSite().
void SBSiteEditor::done (intr) [private, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 2871 of file SbIStuffStation.C'.
References acquireData(), and numOpenedWindows.
void SBSiteEditor::editEntry (QListViewItem *StationItem) [private, slot]
Definition at line 2879 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, stationModified(), and SBLog::write().
Referenced by wSite().
void SBSiteEditor::init () [private]
Definition at line 2633 of file SbIStuffStation.C'.
References isModified, makeApply(), numOpenedWindows, wOLoad(), and wSite().
Referenced by SBSiteEditor().
void SBSiteEditor::insertEntry () [private, slot]
Definition at line 2889 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, Site, stationModified(), StationsLV, and SBLog::write().
Referenced by wSite().
void SBSiteEditor::makeApply () [private, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 2824 of file SbIStuffStation.C'.
References acquireData(), ClassName(), SBLog::DBG, SBSite::domeMajor(), EDome, SB_TRF::find(), SB_TRF::inSort(), SBLog::INTERFACE, isModified, isNew, Log, SBNamed::name(), Site, SiteItem, SitesLV, str, SBLog::write(), and Wtrf.
Referenced by init().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBSiteEditor::siteModified (boolt0) [signal]
Definition at line 800 of file SbIStuffStation.moc.C'.
Referenced by ~SBSiteEditor().
void SBSiteEditor::stationModified (boolModified) [private, slot]
Definition at line 2926 of file SbIStuffStation.C'.
References isModified, and numOpenedWindows.
Referenced by editEntry(), and insertEntry().
QWidget * SBSiteEditor::wOLoad () [private]
Definition at line 2811 of file SbIStuffStation.C'.
References SBSite::OLoad, OLoadEditor, and Site.
Referenced by init().
QWidget * SBSiteEditor::wSite () [private]
Definition at line 2647 of file SbIStuffStation.C'.
References Vector3::at(), SBSite::country(), deleteEntry(), SBSite::domeMajor(), ECountry, editEntry(), EDome, EdV, EName, EPlate, EV, insertEntry(), isNew, SBNamed::name(), SBSite::plate(), Site, SBSite::stations(), StationsLV, str, SBSite::v(), and SBSite::v_err().
Referenced by init().
Member Data Documentation
QLineEdit* SBSiteEditor::ECountry [private]
Definition at line 477 of file SbIStuffStation.H'.
Referenced by acquireData(), and wSite().
QLineEdit* SBSiteEditor::EDome [private]
Definition at line 476 of file SbIStuffStation.H'.
Referenced by acquireData(), makeApply(), and wSite().
QLineEdit* SBSiteEditor::EdV[3] [private]
Definition at line 483 of file SbIStuffStation.H'.
Referenced by acquireData(), and wSite().
QLineEdit* SBSiteEditor::EName [private]
Definition at line 475 of file SbIStuffStation.H'.
Referenced by acquireData(), and wSite().
QLineEdit* SBSiteEditor::EPlate [private]
Definition at line 478 of file SbIStuffStation.H'.
Referenced by acquireData(), and wSite().
QLineEdit* SBSiteEditor::EV[3] [private]
Definition at line 482 of file SbIStuffStation.H'.
Referenced by acquireData(), and wSite().
bool SBSiteEditor::isModified [private]
Definition at line 467 of file SbIStuffStation.H'.
Referenced by acquireData(), deleteEntry(), init(), makeApply(), stationModified(), and ~SBSiteEditor().
bool SBSiteEditor::isNew [private]
Definition at line 468 of file SbIStuffStation.H'.
Referenced by acquireData(), makeApply(), SBSiteEditor(), wSite(), and ~SBSiteEditor().
QGroupBox* SBSiteEditor::NameGBox [private]
Definition at line 480 of file SbIStuffStation.H'.
int SBSiteEditor::numOpenedWindows [private]
Definition at line 469 of file SbIStuffStation.H'.
Referenced by closeEvent(), done(), editEntry(), init(), insertEntry(), and stationModified().
SBOLoadEditor* SBSiteEditor::OLoadEditor [private]
Definition at line 470 of file SbIStuffStation.H'.
Referenced by acquireData(), and wOLoad().
SBSite* SBSiteEditor::Site [private]
Definition at line 465 of file SbIStuffStation.H'.
Referenced by acquireData(), deleteEntry(), insertEntry(), makeApply(), SBSiteEditor(), wOLoad(), wSite(), and ~SBSiteEditor().
SBSiteListItem* SBSiteEditor::SiteItem [private]
Definition at line 464 of file SbIStuffStation.H'.
Referenced by makeApply(), and SBSiteEditor().
QListView* SBSiteEditor::SitesLV [private]
Definition at line 463 of file SbIStuffStation.H'.
Referenced by makeApply(), and SBSiteEditor().
QListView* SBSiteEditor::StationsLV [private]
Definition at line 474 of file SbIStuffStation.H'.
Referenced by deleteEntry(), insertEntry(), and wSite().
QString SBSiteEditor::str [private]
Definition at line 473 of file SbIStuffStation.H'.
Referenced by acquireData(), deleteEntry(), makeApply(), and wSite().
SB_TRF* SBSiteEditor::Wtrf [private]
Definition at line 466 of file SbIStuffStation.H'.
Referenced by makeApply(), and SBSiteEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.