SBSiteListItem
NAME
SBSiteListItem -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QListViewItem'.
Public Member Functions
SBSiteListItem (QListView *, SBSite *)
~SBSiteListItem ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBSite * Site
bool isFaked
Friends
class SBStuffStations
class SBSiteEditor
Detailed Description
Definition at line 84 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBSiteListItem::SBSiteListItem (QListView *parent, SBSite *Site_)
Definition at line 184 of file SbIStuffStation.C'.
References isFaked, and Site.
SBSiteListItem::~SBSiteListItem ()
Definition at line 196 of file SbIStuffStation.C'.
References isFaked, and Site.
Member Function Documentation
virtual QString SBSiteListItem::ClassName () const [inline, virtual]
Definition at line 92 of file SbIStuffStation.H'.
QString SBSiteListItem::key (intcol, bool) const [virtual]
Definition at line 238 of file SbIStuffStation.C'.
References SBSite::country(), SBSite::domeMajor(), SBSite::height(), SBSite::latitude(), SBSite::longitude(), SBNamed::name(), SBSite::oLoad(), SBOLoad::pickedUp(), SBSite::plate(), Site, SBSite::stations(), and TmpString.
QString SBSiteListItem::text (intcol) const [virtual]
Definition at line 202 of file SbIStuffStation.C'.
References SBSite::country(), SBSite::domeMajor(), SBSite::height(), SBSite::latitude(), SBSite::longitude(), SBNamed::name(), SBSite::oLoad(), SBOLoad::pickedUp(), SBSite::plate(), rad2dms(), rad2dmsl(), Site, SBSite::stations(), and TmpString.
Friends And Related Function Documentation
friend class SBSiteEditor [friend]
Definition at line 97 of file SbIStuffStation.H'.
friend class SBStuffStations [friend]
Definition at line 96 of file SbIStuffStation.H'.
Member Data Documentation
bool SBSiteListItem::isFaked [private]
Definition at line 88 of file SbIStuffStation.H'.
Referenced by SBSiteListItem(), and ~SBSiteListItem().
SBSite* SBSiteListItem::Site [private]
Definition at line 87 of file SbIStuffStation.H'.
Referenced by SBStuffStations::deleteEntryS(), key(), SBSiteEditor::SBSiteEditor(), SBSiteListItem(), text(), and ~SBSiteListItem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.