.TH "SBSiteEditor" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBSiteEditor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIStuffStation\&.H>\fP
.PP
Inherits \fBSBTabDialog\fP'\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsiteModified\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBSiteEditor\fP (\fBSBSiteListItem\fP *, \fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "\fBSBSiteEditor\fP (\fBQListView\fP *, \fBSB_TRF\fP *, \fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "\fB~SBSiteEditor\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBmakeDefaults\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *e)"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBmakeApply\fP ()"
.br
.ti -1c
.RI "virtual void \fBdone\fP (int)"
.br
.ti -1c
.RI "void \fBeditEntry\fP (\fBQListViewItem\fP *)"
.br
.ti -1c
.RI "void \fBinsertEntry\fP ()"
.br
.ti -1c
.RI "void \fBdeleteEntry\fP ()"
.br
.ti -1c
.RI "void \fBstationModified\fP (bool)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBacquireData\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBwSite\fP ()"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBwOLoad\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBQListView\fP * \fBSitesLV\fP"
.br
.ti -1c
.RI "\fBSBSiteListItem\fP * \fBSiteItem\fP"
.br
.ti -1c
.RI "\fBSBSite\fP * \fBSite\fP"
.br
.ti -1c
.RI "\fBSB_TRF\fP * \fBWtrf\fP"
.br
.ti -1c
.RI "bool \fBisModified\fP"
.br
.ti -1c
.RI "bool \fBisNew\fP"
.br
.ti -1c
.RI "int \fBnumOpenedWindows\fP"
.br
.ti -1c
.RI "\fBSBOLoadEditor\fP * \fBOLoadEditor\fP"
.br
.ti -1c
.RI "QString \fBstr\fP"
.br
.ti -1c
.RI "\fBQListView\fP * \fBStationsLV\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEName\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEDome\fP"
.br
.ti -1c
.RI "QLineEdit * \fBECountry\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEPlate\fP"
.br
.ti -1c
.RI "QGroupBox * \fBNameGBox\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEV\fP [3]"
.br
.ti -1c
.RI "QLineEdit * \fBEdV\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 431 of file SbIStuffStation\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBSiteEditor::SBSiteEditor (\fBSBSiteListItem\fP *SiteItem_, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 2600 of file SbIStuffStation\&.C'\&.
.PP
References init(), isNew, SBSiteListItem::Site, Site, SiteItem, SitesLV, and Wtrf\&.
.SS "SBSiteEditor::SBSiteEditor (\fBQListView\fP *SitesLV_, \fBSB_TRF\fP *Wtrf_, \fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 2613 of file SbIStuffStation\&.C'\&.
.PP
References init(), isNew, Site, SiteItem, SitesLV, and Wtrf\&.
.SS "SBSiteEditor::~SBSiteEditor ()"
.PP
Definition at line 2627 of file SbIStuffStation\&.C'\&.
.PP
References isModified, isNew, Site, and siteModified()\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBSiteEditor::acquireData ()\fC [private, virtual]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 2937 of file SbIStuffStation\&.C'\&.
.PP
References SBOLoadEditor::collectData(), SBSite::country(), SBSite::domeMajor(), ECountry, EDome, EdV, EName, EPlate, EV, isModified, isNew, SBNamed::name(), OLoadEditor, SBSite::plate(), SBSite::setCountry(), SBSite::setDomeMajor(), SBNamed::setName(), SBSite::setPlate(), SBSite::setV(), SBSite::setV_err(), Site, str, SBSite::v(), SBSite::v_err(), X_AXIS, Y_AXIS, and Z_AXIS\&.
.PP
Referenced by done(), and makeApply()\&.
.SS "virtual QString SBSiteEditor::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 438 of file SbIStuffStation\&.H'\&.
.PP
Referenced by deleteEntry(), editEntry(), insertEntry(), and makeApply()\&.
.SS "virtual void SBSiteEditor::closeEvent (QCloseEvent *e)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 486 of file SbIStuffStation\&.H'\&.
.PP
References numOpenedWindows\&.
.SS "void SBSiteEditor::deleteEntry ()\fC [private, slot]\fP"
.PP
Definition at line 2899 of file SbIStuffStation\&.C'\&.
.PP
References ClassName(), SBLog::DBG, SBSite::delStation(), SBLog::INTERFACE, isModified, Log, SBNamed::name(), Site, SBStationListItem::Station, StationsLV, str, and SBLog::write()\&.
.PP
Referenced by wSite()\&.
.SS "void SBSiteEditor::done (intr)\fC [private, virtual, slot]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 2871 of file SbIStuffStation\&.C'\&.
.PP
References acquireData(), and numOpenedWindows\&.
.SS "void SBSiteEditor::editEntry (\fBQListViewItem\fP *StationItem)\fC [private, slot]\fP"
.PP
Definition at line 2879 of file SbIStuffStation\&.C'\&.
.PP
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, stationModified(), and SBLog::write()\&.
.PP
Referenced by wSite()\&.
.SS "void SBSiteEditor::init ()\fC [private]\fP"
.PP
Definition at line 2633 of file SbIStuffStation\&.C'\&.
.PP
References isModified, makeApply(), numOpenedWindows, wOLoad(), and wSite()\&.
.PP
Referenced by SBSiteEditor()\&.
.SS "void SBSiteEditor::insertEntry ()\fC [private, slot]\fP"
.PP
Definition at line 2889 of file SbIStuffStation\&.C'\&.
.PP
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, Site, stationModified(), StationsLV, and SBLog::write()\&.
.PP
Referenced by wSite()\&.
.SS "void SBSiteEditor::makeApply ()\fC [private, virtual, slot]\fP"
.PP
Reimplemented from \fBSBTabDialog\fP'\&.
.PP
Definition at line 2824 of file SbIStuffStation\&.C'\&.
.PP
References acquireData(), ClassName(), SBLog::DBG, SBSite::domeMajor(), EDome, SB_TRF::find(), SB_TRF::inSort(), SBLog::INTERFACE, isModified, isNew, Log, SBNamed::name(), Site, SiteItem, SitesLV, str, SBLog::write(), and Wtrf\&.
.PP
Referenced by init()\&.
.SS "virtual void SBTabDialog::makeDefaults ()\fC [inline, protected, virtual, slot, inherited]\fP"
.PP
Reimplemented in \fBSBSetupDialog\fP'\&.
.PP
Definition at line 79 of file SbInterface\&.H'\&.
.SS "void SBSiteEditor::siteModified (boolt0)\fC [signal]\fP"
.PP
Definition at line 800 of file SbIStuffStation\&.moc\&.C'\&.
.PP
Referenced by ~SBSiteEditor()\&.
.SS "void SBSiteEditor::stationModified (boolModified)\fC [private, slot]\fP"
.PP
Definition at line 2926 of file SbIStuffStation\&.C'\&.
.PP
References isModified, and numOpenedWindows\&.
.PP
Referenced by editEntry(), and insertEntry()\&.
.SS "\fBQWidget\fP * SBSiteEditor::wOLoad ()\fC [private]\fP"
.PP
Definition at line 2811 of file SbIStuffStation\&.C'\&.
.PP
References SBSite::OLoad, OLoadEditor, and Site\&.
.PP
Referenced by init()\&.
.SS "\fBQWidget\fP * SBSiteEditor::wSite ()\fC [private]\fP"
.PP
Definition at line 2647 of file SbIStuffStation\&.C'\&.
.PP
References Vector3::at(), SBSite::country(), deleteEntry(), SBSite::domeMajor(), ECountry, editEntry(), EDome, EdV, EName, EPlate, EV, insertEntry(), isNew, SBNamed::name(), SBSite::plate(), Site, SBSite::stations(), StationsLV, str, SBSite::v(), and SBSite::v_err()\&.
.PP
Referenced by init()\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* \fBSBSiteEditor::ECountry\fP\fC [private]\fP"
.PP
Definition at line 477 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), and wSite()\&.
.SS "QLineEdit* \fBSBSiteEditor::EDome\fP\fC [private]\fP"
.PP
Definition at line 476 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), makeApply(), and wSite()\&.
.SS "QLineEdit* \fBSBSiteEditor::EdV\fP[3]\fC [private]\fP"
.PP
Definition at line 483 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), and wSite()\&.
.SS "QLineEdit* \fBSBSiteEditor::EName\fP\fC [private]\fP"
.PP
Definition at line 475 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), and wSite()\&.
.SS "QLineEdit* \fBSBSiteEditor::EPlate\fP\fC [private]\fP"
.PP
Definition at line 478 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), and wSite()\&.
.SS "QLineEdit* \fBSBSiteEditor::EV\fP[3]\fC [private]\fP"
.PP
Definition at line 482 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), and wSite()\&.
.SS "bool \fBSBSiteEditor::isModified\fP\fC [private]\fP"
.PP
Definition at line 467 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), deleteEntry(), init(), makeApply(), stationModified(), and ~SBSiteEditor()\&.
.SS "bool \fBSBSiteEditor::isNew\fP\fC [private]\fP"
.PP
Definition at line 468 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), makeApply(), SBSiteEditor(), wSite(), and ~SBSiteEditor()\&.
.SS "QGroupBox* \fBSBSiteEditor::NameGBox\fP\fC [private]\fP"
.PP
Definition at line 480 of file SbIStuffStation\&.H'\&.
.SS "int \fBSBSiteEditor::numOpenedWindows\fP\fC [private]\fP"
.PP
Definition at line 469 of file SbIStuffStation\&.H'\&.
.PP
Referenced by closeEvent(), done(), editEntry(), init(), insertEntry(), and stationModified()\&.
.SS "\fBSBOLoadEditor\fP* \fBSBSiteEditor::OLoadEditor\fP\fC [private]\fP"
.PP
Definition at line 470 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), and wOLoad()\&.
.SS "\fBSBSite\fP* \fBSBSiteEditor::Site\fP\fC [private]\fP"
.PP
Definition at line 465 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), deleteEntry(), insertEntry(), makeApply(), SBSiteEditor(), wOLoad(), wSite(), and ~SBSiteEditor()\&.
.SS "\fBSBSiteListItem\fP* \fBSBSiteEditor::SiteItem\fP\fC [private]\fP"
.PP
Definition at line 464 of file SbIStuffStation\&.H'\&.
.PP
Referenced by makeApply(), and SBSiteEditor()\&.
.SS "\fBQListView\fP* \fBSBSiteEditor::SitesLV\fP\fC [private]\fP"
.PP
Definition at line 463 of file SbIStuffStation\&.H'\&.
.PP
Referenced by makeApply(), and SBSiteEditor()\&.
.SS "\fBQListView\fP* \fBSBSiteEditor::StationsLV\fP\fC [private]\fP"
.PP
Definition at line 474 of file SbIStuffStation\&.H'\&.
.PP
Referenced by deleteEntry(), insertEntry(), and wSite()\&.
.SS "QString \fBSBSiteEditor::str\fP\fC [private]\fP"
.PP
Definition at line 473 of file SbIStuffStation\&.H'\&.
.PP
Referenced by acquireData(), deleteEntry(), makeApply(), and wSite()\&.
.SS "\fBSB_TRF\fP* \fBSBSiteEditor::Wtrf\fP\fC [private]\fP"
.PP
Definition at line 466 of file SbIStuffStation\&.H'\&.
.PP
Referenced by makeApply(), and SBSiteEditor()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
