SBSite
NAME
SBSite -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBNamed'.
Public Member Functions
SBSite (const QString &='Zabriski Point')
SBSite (const SBSite &)
virtual ~SBSite ()
virtual QString ClassName () const
virtual SBSite & operator= (const SBSite &)
int domeMajor () const
QString country () const
QString plate () const
SBOLoad & oLoad ()
const Vector3 & r () const
const Vector3 & v () const
const Vector3 & v_err () const
double longitude () const
double latitude () const
double height () const
void setDomeMajor (int Domes_)
void setCountry (const char *Country_)
void setPlate (const char *Plate_)
void setOLoad (const SBOLoad &OLoad_)
void setV (const Vector3 &V_)
void setV_err (const Vector3 &dV_)
void setLongitude (double Longitude_)
void setLatitude (double Latitude_)
void setHeight (double Height_)
SBStationList & stations ()
SBStation * operator[] (const SBStationID &ID)
SBStation * find (const SBStationID &)
virtual void addStation (SBStation *)
virtual bool delStation (SBStation *)
void calcRLF ()
int firstUnusedNumber (SBStation::SPointType)
int lastUnusedNumber (SBStation::SPointType)
void updateSite (const SBSite &)
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
QString Name
Private Member Functions
void copyStationsList (const SBStationList &)
void updateStationsList (const SBStationList &)
void prepareDicts ()
Private Attributes
int DomeMajor
QString Country
QString Plate
SBOLoad OLoad
Vector3 R
Vector3 V
Vector3 dV
double Longitude
double Latitude
double Height
SBStationList Stations
QIntDict< SBStation > * St_S
QIntDict< SBStation > * St_M
Friends
class SB_TRF
class SBStation
class SBSiteEditor
bool operator== (const SBSite &S1, const SBSite &S2)
bool operator!= (const SBSite &S1, const SBSite &S2)
bool operator< (const SBSite &S1, const SBSite &S2)
bool operator> (const SBSite &S1, const SBSite &S2)
QDataStream & operator<< (QDataStream &, const SBSite &)
QDataStream & operator>> (QDataStream &, SBSite &)
SBTS_site1994 & operator<< (SBTS_site1994 &, const SBSite &)
SBTS_site1994 & operator>> (SBTS_site1994 &, SBSite &)
SBTS_site2000 & operator<< (SBTS_site2000 &, const SBSite &)
SBTS_site2000 & operator>> (SBTS_site2000 &, SBSite &)
SBTS_dir1994 & operator<< (SBTS_dir1994 &, const SBSite &)
SBTS_dir1994 & operator>> (SBTS_dir1994 &, SBSite &)
SBTS_dir1994 & operator>> (SBTS_dir1994 &, SB_TRF &)
SBTS_dir2000 & operator<< (SBTS_dir2000 &, const SBSite &)
SBTS_dir2000 & operator>> (SBTS_dir2000 &, SBSite &)
SBTS_dir2000 & operator>> (SBTS_dir2000 &, SB_TRF &)
SBTS_ssc1994 & operator<< (SBTS_ssc1994 &, const SBSite &)
SBTS_ssc1994 & operator>> (SBTS_ssc1994 &, SB_TRF &)
SBTS_ssc2000 & operator<< (SBTS_ssc2000 &, const SBSite &)
SBTS_ssc2000 & operator>> (SBTS_ssc2000 &, SB_TRF &)
SBTS_blqReq & operator<< (SBTS_blqReq &, const SBSite &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Definition at line 886 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBSite::SBSite (const QString &Name_ = 'Zabriski Point')
Definition at line 1720 of file SbGeoStations.C'.
References Country, DomeMajor, Height, Latitude, Longitude, Plate, prepareDicts(), St_M, St_S, and Stations.
SBSite::SBSite (const SBSite &S)
Definition at line 1735 of file SbGeoStations.C'.
References copyStationsList(), Country, DomeMajor, Height, Latitude, Longitude, Plate, prepareDicts(), St_M, St_S, and Stations.
virtual SBSite::~SBSite () [inline, virtual]
Definition at line 920 of file SbGeoStations.H'.
References St_M, and St_S.
Member Function Documentation
void SBSite::addStation (SBStation *Station) [virtual]
Definition at line 1882 of file SbGeoStations.C'.
References ClassName(), SBStation::domeMinor(), SBLog::ERR, SBStation::id(), Log, SBNamed::name(), SBStation::pointType(), SBStation::Pt_Antenna, SBStation::Pt_Unkn, St_M, St_S, SBLog::STATION, Stations, SBStationID::toString(), and SBLog::write().
Referenced by SBStationImport::loadNScodes(), SBStationEditor::makeApply(), operator>>(), SBStuffStations::reloadTRF(), SBStuffStations::SBStuffStations(), and updateStationsList().
void SBSite::calcRLF ()
Definition at line 1938 of file SbGeoStations.C'.
References SBStationList::first(), Height, Latitude, Longitude, SBStationList::next(), R, Stations, and v3Zero.
Referenced by SBStationImport::loadOLoad(), and operator>>().
virtual QString SBSite::ClassName () const [inline, virtual]
Reimplemented from SBNamed'.
Definition at line 921 of file SbGeoStations.H'.
Referenced by addStation(), delStation(), and prepareDicts().
void SBSite::copyStationsList (const SBStationList &SL) [private]
Definition at line 1768 of file SbGeoStations.C'.
References SBStation, and Stations.
Referenced by operator=(), and SBSite().
QString SBSite::country () const [inline]
Definition at line 926 of file SbGeoStations.H'.
References Country.
Referenced by SBSiteEditor::acquireData(), SBSiteListItem::key(), operator<<(), SBSiteListItem::text(), and SBSiteEditor::wSite().
bool SBSite::delStation (SBStation *Station) [virtual]
Definition at line 1913 of file SbGeoStations.C'.
References ClassName(), SBStation::domeMinor(), SBLog::ERR, find(), SBStation::id(), Log, SBNamed::name(), SBStation::pointType(), SBStation::Pt_Antenna, St_M, St_S, SBLog::STATION, Stations, and SBLog::write().
Referenced by SBStationImport::applyFilter(), and SBSiteEditor::deleteEntry().
int SBSite::domeMajor () const [inline]
Definition at line 925 of file SbGeoStations.H'.
References DomeMajor.
Referenced by SBSiteEditor::acquireData(), SB_TRF::find(), SBStation::id(), SB_TRF::inSort(), SBSiteListItem::key(), SBSiteEditor::makeApply(), operator<<(), SBOLoadCarrier::SBOLoadCarrier(), SBSiteListItem::text(), and SBSiteEditor::wSite().
SBStation * SBSite::find (const SBStationID &ID)
Definition at line 1866 of file SbGeoStations.C'.
References SBStationID::DomeMinor, SBStation::Pt_Antenna, SBStation::Pt_Marker, SBStation::Pt_Unkn, SBStationID::PtType, St_M, and St_S.
Referenced by delStation(), SB_TRF::find(), SBStationEditor::makeApply(), operator[](), and updateStationsList().
int SBSite::firstUnusedNumber (SBStation::SPointTypeTp)"Returns first unused domes number
Returns:
least unused DomeMinor for this site (int)'.
Definition at line 1955 of file SbGeoStations.C'.
References SBStationID::domeMinor(), SBStation::id(), SBStation::Pt_Antenna, SBStation::Pt_Unkn, St_M, and St_S.
double SBSite::height () const [inline]
Definition at line 934 of file SbGeoStations.H'.
References Height.
Referenced by SBSiteListItem::key(), and SBSiteListItem::text().
int SBSite::lastUnusedNumber (SBStation::SPointTypeTp)"Returns last unused domes number
Returns:
largest unused DomeMinor for this site (int)'.
Definition at line 1969 of file SbGeoStations.C'.
References SBStation::Pt_Antenna, SBStation::Pt_Unkn, St_M, and St_S.
double SBSite::latitude () const [inline]
Definition at line 933 of file SbGeoStations.H'.
References Latitude.
Referenced by SBSiteListItem::key(), SBStationImport::loadOLoad(), operator<<(), SBOLoadCarrier::SBOLoadCarrier(), and SBSiteListItem::text().
double SBSite::longitude () const [inline]
Definition at line 932 of file SbGeoStations.H'.
References Longitude.
Referenced by SBSiteListItem::key(), SBStationImport::loadOLoad(), operator<<(), SBOLoadCarrier::SBOLoadCarrier(), and SBSiteListItem::text().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
SBOLoad& SBSite::oLoad () [inline]
Definition at line 928 of file SbGeoStations.H'.
References OLoad.
Referenced by SBTestOceanTides::fillData4Plotting(), SBSiteListItem::key(), SBStationImport::loadOLoad(), SBTideLd::operator()(), SBOLoadCarrier::SBOLoadCarrier(), and SBSiteListItem::text().
SBSite & SBSite::operator= (const SBSite &S) [virtual]
Definition at line 1751 of file SbGeoStations.C'.
References copyStationsList(), Country, dV, Height, Latitude, Longitude, SBNamed::Name, OLoad, Plate, prepareDicts(), Stations, and V.
SBStation* SBSite::operator[] (const SBStationID &ID) [inline]
Definition at line 947 of file SbGeoStations.H'.
References find().
QString SBSite::plate () const [inline]
Definition at line 927 of file SbGeoStations.H'.
References Plate.
Referenced by SBSiteEditor::acquireData(), SBPlateMotion::displacement(), SBSiteListItem::key(), operator<<(), SBSiteListItem::text(), SBPlateMotion::velocity(), and SBSiteEditor::wSite().
void SBSite::prepareDicts () [private]
Definition at line 1836 of file SbGeoStations.C'.
References ClassName(), SBStation::domeMinor(), SBLog::ERR, SBStation::id(), Log, SBNamed::name(), SBStation::pointType(), SBStation::Pt_Antenna, SBStation::Pt_Marker, SBStation::Site, St_M, St_S, SBLog::STATION, Stations, SBStationID::toString(), and SBLog::write().
Referenced by operator=(), operator>>(), SBSite(), and updateSite().
const Vector3& SBSite::r () const [inline]
Definition at line 929 of file SbGeoStations.H'.
References R.
Referenced by SBStationListItem::key(), SBStationImport::loadOLoad(), and SBStationListItem::text().
void SBSite::setCountry (const char *Country_) [inline]
Definition at line 937 of file SbGeoStations.H'.
References Country.
Referenced by SBSiteEditor::acquireData(), and operator>>().
void SBSite::setDomeMajor (intDomes_) [inline]
Definition at line 936 of file SbGeoStations.H'.
References DomeMajor.
Referenced by SBSiteEditor::acquireData(), and operator>>().
void SBSite::setHeight (doubleHeight_) [inline]
Definition at line 944 of file SbGeoStations.H'.
References Height.
void SBSite::setLatitude (doubleLatitude_) [inline]
Definition at line 943 of file SbGeoStations.H'.
References Latitude.
void SBSite::setLongitude (doubleLongitude_) [inline]
Definition at line 942 of file SbGeoStations.H'.
References Longitude.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBSite::setOLoad (const SBOLoad &OLoad_) [inline]
Definition at line 939 of file SbGeoStations.H'.
References OLoad.
Referenced by SBStationImport::loadOLoad().
void SBSite::setPlate (const char *Plate_) [inline]
Definition at line 938 of file SbGeoStations.H'.
References Plate.
Referenced by SBSiteEditor::acquireData(), and operator>>().
void SBSite::setV (const Vector3 &V_) [inline]
Definition at line 940 of file SbGeoStations.H'.
References V.
Referenced by SBSiteEditor::acquireData(), SBAploChunk::import(), SBAploEphem::importHPS(), and SBStationImport::importITRF().
void SBSite::setV_err (const Vector3 &dV_) [inline]
Definition at line 941 of file SbGeoStations.H'.
References dV.
Referenced by SBSiteEditor::acquireData(), and SBStationImport::importITRF().
SBStationList& SBSite::stations () [inline]
Definition at line 946 of file SbGeoStations.H'.
References Stations.
Referenced by SBStationImport::applyFilter(), SBStationImport::importITRF(), SBSiteListItem::key(), SBStationImport::loadOLoad(), SBSiteListItem::text(), SBSolutionBrowser::updateTRF(), and SBSiteEditor::wSite().
void SBSite::updateSite (const SBSite &S)
Definition at line 1782 of file SbGeoStations.C'.
References Country, dV, Height, Latitude, Longitude, SBNamed::Name, OLoad, Plate, prepareDicts(), Stations, updateStationsList(), and V.
Referenced by SBStationImport::importITRF().
void SBSite::updateStationsList (const SBStationList &SL) [private]
Definition at line 1818 of file SbGeoStations.C'.
References addStation(), find(), SBStation::id(), and SBStation::updateStation().
Referenced by updateSite().
const Vector3& SBSite::v () const [inline]
Definition at line 930 of file SbGeoStations.H'.
References V.
Referenced by SBSiteEditor::acquireData(), SBAploChunk::import(), SBAploEphem::importHPS(), SBStationListItem::key(), SBStationListItem::text(), and SBSiteEditor::wSite().
const Vector3& SBSite::v_err () const [inline]
Definition at line 931 of file SbGeoStations.H'.
References dV.
Referenced by SBSiteEditor::acquireData(), and SBSiteEditor::wSite().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator!= (const SBSite &S1, const SBSite &S2) [friend]
Definition at line 911 of file SbGeoStations.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
bool operator< (const SBSite &S1, const SBSite &S2) [friend]
Definition at line 913 of file SbGeoStations.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBSite &S) [friend]
Definition at line 1988 of file SbGeoStations.C'.
SBTS_site1994& operator<< (SBTS_site1994 &s, const SBSite &S) [friend]
Definition at line 2003 of file SbGeoStations.C'.
SBTS_site2000& operator<< (SBTS_site2000 &s, const SBSite &S) [friend]
Definition at line 2055 of file SbGeoStations.C'.
SBTS_dir1994& operator<< (SBTS_dir1994 &s, const SBSite &S) [friend]
Definition at line 2109 of file SbGeoStations.C'.
SBTS_dir2000& operator<< (SBTS_dir2000 &s, const SBSite &S) [friend]
Definition at line 2183 of file SbGeoStations.C'.
SBTS_ssc1994& operator<< (SBTS_ssc1994 &s, const SBSite &S) [friend]
Definition at line 2271 of file SbGeoStations.C'.
SBTS_ssc2000& operator<< (SBTS_ssc2000 &s, const SBSite &S) [friend]
Definition at line 2279 of file SbGeoStations.C'.
SBTS_blqReq& operator<< (SBTS_blqReq &s, const SBSite &S) [friend]
Definition at line 2287 of file SbGeoStations.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator== (const SBSite &S1, const SBSite &S2) [friend]
Definition at line 909 of file SbGeoStations.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
bool operator> (const SBSite &S1, const SBSite &S2) [friend]
Definition at line 915 of file SbGeoStations.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBSite &S) [friend]
Definition at line 1994 of file SbGeoStations.C'.
SBTS_site1994& operator>> (SBTS_site1994 &s, SBSite &S) [friend]
Definition at line 2019 of file SbGeoStations.C'.
SBTS_site2000& operator>> (SBTS_site2000 &s, SBSite &S) [friend]
Definition at line 2071 of file SbGeoStations.C'.
SBTS_dir1994& operator>> (SBTS_dir1994 &s, SBSite &S) [friend]
Definition at line 2119 of file SbGeoStations.C'.
SBTS_dir1994& operator>> (SBTS_dir1994 &s, SB_TRF &TRF) [friend]
Definition at line 3066 of file SbGeoStations.C'.
SBTS_dir2000& operator>> (SBTS_dir2000 &s, SBSite &S) [friend]
Definition at line 2193 of file SbGeoStations.C'.
SBTS_dir2000& operator>> (SBTS_dir2000 &s, SB_TRF &TRF) [friend]
Definition at line 3131 of file SbGeoStations.C'.
SBTS_ssc1994& operator>> (SBTS_ssc1994 &s, SB_TRF &TRF) [friend]
Definition at line 3237 of file SbGeoStations.C'.
SBTS_ssc2000& operator>> (SBTS_ssc2000 &s, SB_TRF &TRF) [friend]
Definition at line 3498 of file SbGeoStations.C'.
friend class SB_TRF [friend]
Definition at line 888 of file SbGeoStations.H'.
friend class SBSiteEditor [friend]
Definition at line 890 of file SbGeoStations.H'.
friend class SBStation [friend]
Definition at line 889 of file SbGeoStations.H'.
Referenced by copyStationsList().
Member Data Documentation
QString SBSite::Country [private]
Definition at line 893 of file SbGeoStations.H'.
Referenced by country(), operator<<(), operator=(), operator>>(), SBSite(), setCountry(), and updateSite().
int SBSite::DomeMajor [private]
Definition at line 892 of file SbGeoStations.H'.
Referenced by domeMajor(), operator<<(), operator>>(), SBSite(), and setDomeMajor().
Vector3 SBSite::dV [private]
Definition at line 898 of file SbGeoStations.H'.
Referenced by operator<<(), operator=(), operator>>(), setV_err(), updateSite(), and v_err().
double SBSite::Height [private]
Definition at line 901 of file SbGeoStations.H'.
Referenced by calcRLF(), height(), operator=(), SBSite(), setHeight(), and updateSite().
double SBSite::Latitude [private]
Definition at line 900 of file SbGeoStations.H'.
Referenced by calcRLF(), latitude(), operator=(), SBSite(), setLatitude(), and updateSite().
double SBSite::Longitude [private]
Definition at line 899 of file SbGeoStations.H'.
Referenced by calcRLF(), longitude(), operator=(), SBSite(), setLongitude(), and updateSite().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), updateSite(), and SBStation::updateStation().
SBOLoad SBSite::OLoad [private]
Definition at line 895 of file SbGeoStations.H'.
Referenced by oLoad(), operator<<(), operator=(), operator>>(), setOLoad(), updateSite(), and SBSiteEditor::wOLoad().
QString SBSite::Plate [private]
Definition at line 894 of file SbGeoStations.H'.
Referenced by operator<<(), operator=(), operator>>(), plate(), SBSite(), setPlate(), and updateSite().
Vector3 SBSite::R [private]
Definition at line 896 of file SbGeoStations.H'.
Referenced by calcRLF(), and r().
QIntDict<SBStation>* SBSite::St_M [private]
Definition at line 904 of file SbGeoStations.H'.
Referenced by addStation(), delStation(), find(), firstUnusedNumber(), lastUnusedNumber(), prepareDicts(), SBSite(), and ~SBSite().
QIntDict<SBStation>* SBSite::St_S [private]
Definition at line 903 of file SbGeoStations.H'.
Referenced by addStation(), delStation(), find(), firstUnusedNumber(), lastUnusedNumber(), prepareDicts(), SBSite(), and ~SBSite().
SBStationList SBSite::Stations [private]
Definition at line 902 of file SbGeoStations.H'.
Referenced by addStation(), calcRLF(), copyStationsList(), delStation(), SB_TRF::lookupNearest(), operator<<(), operator=(), operator>>(), prepareDicts(), SBSite(), stations(), and updateSite().
Vector3 SBSite::V [private]
Definition at line 897 of file SbGeoStations.H'.
Referenced by operator<<(), operator=(), operator>>(), setV(), updateSite(), and v().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.