SBSINEXParameter
NAME
SBSINEXParameter -
SYNOPSIS
#include <SbGeoSINEX.H>
Inherits SBParameter'.
Public Types
enum SType { ST_STAX, ST_STAY, ST_STAZ, ST_VELX, ST_VELY, ST_VELZ, ST_XGC, ST_YGC, ST_ZGC, ST_RS_RA, ST_RS_DE, ST_RS_RAR, ST_RS_DER, ST_RS_PL, ST_LOD, ST_UT, ST_XPO, ST_YPO, ST_XPOR, ST_YPOR, ST_NUT_LN, ST_NUT_OB, ST_NUTRLN, ST_NUTROB, ST_UNKN }
enum Attributes { IsBreak = (1<<0), IsPropagated = (1<<1), IsInRun = (1<<2) }
Public Member Functions
SBSINEXParameter (const SBSINEXParameter &)
SBSINEXParameter (SBParameter *)
virtual ~SBSINEXParameter ()
virtual QString ClassName () const
int idx () const
SType type () const
const QString & siteCode () const
const QString & pointCode () const
const QString & solutionID () const
double aPrioriValue () const
double totValue () const
const SBMJD & tValidEpoch () const
const QString & constraintCode () const
void setIdx (int I_)
void setType (SType T_)
void setSiteCode (const QString &S_)
void setPointCode (const QString &P_)
void setSolutionID (const QString &ID_)
void setAPrioriValue (double Val_)
void setTValidEpoch (const SBMJD &T_)
void setConstraintCode (const QString &C_)
QString parameterUnits ()
QString parameterType ()
virtual double v (const SBMJD &=TZero) const
virtual double s (const SBMJD &=TZero) const
virtual double e (const SBMJD &=TZero) const
virtual double scale () const
virtual double sigmaAPriori () const
virtual double tau () const
virtual double psd_RWN () const
virtual double psd_BN () const
virtual SBParameterCfg::StochType sType () const
virtual char prefix () const
virtual void setV (double d_)
virtual void setS (double d_)
virtual void setE (double d_)
virtual void setScale (double s_)
virtual void setSigmaAPriori (double d_)
virtual void setTau (double d_)
virtual void setPSD_RWN (double d_)
virtual void setPSD_BN (double d_)
virtual void setSType (SBParameterCfg::StochType ST_)
virtual void setPrefix (char c_)
virtual void tuneParameter (const SBParameterCfg &)
virtual void update (const SBParameter *)
QString timeStamp () const
virtual double m (double)
virtual double rw (double)
virtual void clearValues ()
virtual QString str4compare () const
virtual double d (const SBMJD &=TZero) const
virtual int num (const SBMJD &=TZero) const
virtual int numSes (const SBMJD &=TZero) const
virtual SBMJD tStart (const SBMJD &=TZero) const
virtual SBMJD tFinis (const SBMJD &=TZero) const
virtual SBMJD tEpoch (const SBMJD &=TZero) const
virtual double tInterval (const SBMJD &=TZero) const
virtual void setD (double, const SBMJD &)
virtual void setNum (int Num_)
virtual void setNumSes (int Num_)
virtual void addNumSes (int Num_)
virtual void setTimes (const SBDerivation &Der)
virtual int num_aux (const SBMJD &=TZero) const
virtual SBMJD tStart_aux (const SBMJD &=TZero) const
virtual SBMJD tFinis_aux (const SBMJD &=TZero) const
virtual SBMJD tEpoch_aux (const SBMJD &=TZero) const
virtual double tInterval_aux (const SBMJD &=TZero) const
virtual void clearValues_aux ()
virtual void invertAux ()
virtual void zero ()
const QString & name () const
void setName (const QString &Name_)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Attributes
double APrioriValue
int Idx
SType Type
QString SiteCode
QString PointCode
QString SolutionID
SBMJD TValidEpoch
QString ConstraintCode
double V
value of the parameter;
double S
value of the solution;
double E
formal error;
double Scale
scale factor;
double SigmaAPriori
a priori std'. deviation (to init the Inform'. matrix)
double Tau
time of relaxation (for stochastic parameters)
double PSD_RWN
PSD of Ruled White Noise'.
double PSD_BN
PSD of White Noise used in break'.
char Prefix
double D
value of a derivation;
int Num
number of points per derivation;
int NumSes
number of sessions per derivation;
SBMJD TStart
MJD of the first measurement;'.
SBMJD TFinis
MJD of the last measurement;'.
long double TSum
the sum of the epochs of observation;
int Num_aux
number of points per derivation;
SBMJD TStart_aux
MJD of the first measurement;'.
SBMJD TFinis_aux
MJD of the last measurement;'.
long double TSum_aux
the sum of the epochs of observation;
QString Name
Friends
QDataStream & operator<< (QDataStream &, const SBParameter &)
QDataStream & operator<< (QDataStream &, const SBDerivation &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &, SBParameter &)
QDataStream & operator>> (QDataStream &, SBDerivation &)
QDataStream & operator>> (QDataStream &, SBNamed &)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
Detailed Description
Class SBSINEXParameter
Definition at line 61 of file SbGeoSINEX.H'.
Member Enumeration Documentation
enum SBDerivation::Attributes [inherited]
Enumerator:
IsBreak
there is a break in the parameter's behaviour
IsPropagated
the parameter's info have to be propagated in future
IsInRun
Definition at line 281 of file SbGeoParameter.H'.
enum SBSINEXParameter::SType"Types of SINEX parameters
Enumerator:
ST_STAX
ST_STAY
ST_STAZ
ST_VELX
ST_VELY
ST_VELZ
ST_XGC
ST_YGC
ST_ZGC
ST_RS_RA
ST_RS_DE
ST_RS_RAR
ST_RS_DER
ST_RS_PL
ST_LOD
ST_UT
ST_XPO
ST_YPO
ST_XPOR
ST_YPOR
ST_NUT_LN
ST_NUT_OB
ST_NUTRLN
ST_NUTROB
ST_UNKN
Reimplemented from SBParameter'.
Definition at line 65 of file SbGeoSINEX.H'.
Constructor & Destructor Documentation
SBSINEXParameter::SBSINEXParameter (const SBSINEXParameter &P)"A constructor'.
Definition at line 51 of file SbGeoSINEX.C'.
References APrioriValue, ConstraintCode, Idx, PointCode, SiteCode, SolutionID, ST_UNKN, TValidEpoch, Type, and TZero.
SBSINEXParameter::SBSINEXParameter (SBParameter *P)
Definition at line 64 of file SbGeoSINEX.C'.
References APrioriValue, ConstraintCode, Idx, PointCode, SiteCode, SolutionID, ST_UNKN, TValidEpoch, Type, and TZero.
virtual SBSINEXParameter::~SBSINEXParameter () [inline, virtual]"A destructor'.
Definition at line 90 of file SbGeoSINEX.H'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
virtual void SBDerivation::addNumSes (intNum_) [inline, virtual, inherited]
Definition at line 337 of file SbGeoParameter.H'.
Referenced by SBRunManager::process_m1().
double SBSINEXParameter::aPrioriValue () const [inline]
Definition at line 101 of file SbGeoSINEX.H'.
References APrioriValue.
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBSINEXParameter::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBParameter'.
Definition at line 92 of file SbGeoSINEX.H'.
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBParameter::clearValues () [virtual, inherited]
Reimplemented from SBDerivation'.
Definition at line 438 of file SbGeoParameter.C'.
References SBParameter::E, SBParameter::S, and SBParameter::V.
void SBDerivation::clearValues_aux () [virtual, inherited]
Definition at line 320 of file SbGeoParameter.C'.
References SBDerivation::D, SBDerivation::Num_aux, SBDerivation::TFinis_aux, SBDerivation::TStart_aux, SBDerivation::TSum_aux, and TZero.
const QString& SBSINEXParameter::constraintCode () const [inline]
Definition at line 104 of file SbGeoSINEX.H'.
References ConstraintCode.
virtual double SBDerivation::d (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns the value of the derivation'.
Definition at line 318 of file SbGeoParameter.H'.
References SBDerivation::D.
Referenced by SBStatistics::addWPFR(), SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBEstimator::processObs(), SBStatistics::setWPFR(), and SBStatistics::setWRMS().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
virtual double SBParameter::e (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns value of the formal error'.
Reimplemented in SBStochParameter'.
Definition at line 415 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBStochParameter::dump2File(), SBStochParameter::e(), SBSolution::getGlobalParameter4Report(), SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBSource::getParameters4Report(), SBParameterLI::key(), SBCableLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTRFVariations(), operator<<(), SBVLBIPreProcess::preProcess(), SBParameterList::report(), SBStochParameter::report(), SBParameterLI::text(), SBCableLI::text(), SBParameter::update(), SBSolution::updateParameter(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
int SBSINEXParameter::idx () const [inline]
Definition at line 96 of file SbGeoSINEX.H'.
References Idx.
virtual void SBDerivation::invertAux () [inline, virtual, inherited]
Definition at line 358 of file SbGeoParameter.H'.
References SBDerivation::Num_aux, SBDerivation::TFinis_aux, SBDerivation::TStart_aux, and SBDerivation::TSum_aux.
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
double SBParameter::m (doubledT) [virtual, inherited]
Definition at line 444 of file SbGeoParameter.C'.
References SBAttributed::isAttr(), SBDerivation::IsBreak, SBParameterCfg::ST_MARKOVPROCESS, SBParameterCfg::ST_NONE, SBParameterCfg::ST_RANDWALK, SBParameterCfg::ST_UNKN, SBParameterCfg::ST_WHITENOISE, SBParameter::SType, and SBParameter::Tau.
Referenced by SBEstimator::mapContStochs4NewBatch(), SBEstimator::propagateStochasticPars(), and SBParameter::rw().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual int SBDerivation::num (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns the number of observations'.
Reimplemented in SBStochParameter'.
Definition at line 320 of file SbGeoParameter.H'.
References SBDerivation::Num.
Referenced by SBStochParameter::addPar(), SBStochParameter::dump2File(), SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBSource::getParameters4Report(), SBParameterLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBStochParameter::num(), operator<<(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBParameterLI::text(), SBStochParameter::update(), and SBSolution::updateParameter().
virtual int SBDerivation::num_aux (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns the number of observations'.
Definition at line 344 of file SbGeoParameter.H'.
References SBDerivation::Num_aux.
virtual int SBDerivation::numSes (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns the number of sessions'.
Definition at line 322 of file SbGeoParameter.H'.
References SBDerivation::NumSes.
Referenced by SBSource::getGlobalParameters4Report(), and SBSource::getParameters4Report().
QString SBSINEXParameter::parameterType ()
Definition at line 122 of file SbGeoSINEX.C'.
References ST_NUT_LN, ST_NUT_OB, ST_RS_DE, ST_RS_RA, ST_STAX, ST_STAY, ST_STAZ, ST_UNKN, ST_UT, ST_VELX, ST_VELY, ST_VELZ, ST_XPO, ST_YPO, and Type.
QString SBSINEXParameter::parameterUnits ()
Definition at line 77 of file SbGeoSINEX.C'.
References ST_NUT_LN, ST_NUT_OB, ST_RS_DE, ST_RS_RA, ST_STAX, ST_STAY, ST_STAZ, ST_UNKN, ST_UT, ST_VELX, ST_VELY, ST_VELZ, ST_XPO, ST_YPO, and Type.
const QString& SBSINEXParameter::pointCode () const [inline]
Definition at line 99 of file SbGeoSINEX.H'.
References PointCode.
virtual char SBParameter::prefix () const [inline, virtual, inherited]
Definition at line 424 of file SbGeoParameter.H'.
Referenced by SBParameter::operator=().
virtual double SBParameter::psd_BN () const [inline, virtual, inherited]
Definition at line 422 of file SbGeoParameter.H'.
virtual double SBParameter::psd_RWN () const [inline, virtual, inherited]
Definition at line 421 of file SbGeoParameter.H'.
double SBParameter::rw (doubledT) [virtual, inherited]
Definition at line 468 of file SbGeoParameter.C'.
References SBParameter::ClassName(), SBAttributed::delAttr(), SBParameter::E, SBLog::ESTIMATOR, SBLog::INF, SBAttributed::isAttr(), SBDerivation::IsBreak, Log, SBParameter::m(), SBNamed::name(), SBParameter::PSD_BN, SBParameter::PSD_RWN, SBParameter::SigmaAPriori, SBParameterCfg::ST_MARKOVPROCESS, SBParameterCfg::ST_NONE, SBParameterCfg::ST_RANDWALK, SBParameterCfg::ST_UNKN, SBParameterCfg::ST_WHITENOISE, SBParameter::SType, SBParameter::Tau, and SBLog::write().
Referenced by SBEstimator::mapContStochs4NewBatch(), and SBEstimator::propagateStochasticPars().
virtual double SBParameter::s (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns value of the last solution'.
Reimplemented in SBStochParameter'.
Definition at line 413 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBParameterList::report(), SBStochParameter::report(), SBStochParameter::s(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBParameter::update(), SBStochParameter::update(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
virtual double SBParameter::scale () const [inline, virtual, inherited]"Returns value of the scale factor'.
Definition at line 417 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBStochParameter::dump2File(), SBParameterLI::key(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBParameter::operator=(), SBParameterList::report(), SBStochParameter::report(), SBSolution::submitStochasticParameters(), SBParameterLI::text(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
void SBSINEXParameter::setAPrioriValue (doubleVal_) [inline]
Definition at line 112 of file SbGeoSINEX.H'.
References APrioriValue.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBSINEXParameter::setConstraintCode (const QString &C_) [inline]
Definition at line 114 of file SbGeoSINEX.H'.
References ConstraintCode.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
void SBDerivation::setD (doubleD_, const SBMJD &T) [virtual, inherited]"Sets up the value of the derivation'.
Definition at line 291 of file SbGeoParameter.C'.
References SBDerivation::D, SBDerivation::Num, SBDerivation::Num_aux, SBDerivation::TFinis, SBDerivation::TFinis_aux, SBDerivation::TStart, SBDerivation::TStart_aux, SBDerivation::TSum, SBDerivation::TSum_aux, and TZero.
Referenced by SBStation::axisOffsetLenght(), SBDelay::calcDerivatives(), SBRunManager::constrainClocks(), SBRunManager::constraintEOP(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), and SBObsVLBIEntry::process().
virtual void SBParameter::setE (doubled_) [inline, virtual, inherited]"Sets the value of the formal error'.
Definition at line 431 of file SbGeoParameter.H'.
Referenced by SBSolution::getGlobalParameter4Report(), and SBSolution::updateParameter().
void SBSINEXParameter::setIdx (intI_) [inline]
Definition at line 107 of file SbGeoSINEX.H'.
References Idx.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
virtual void SBDerivation::setNum (intNum_) [inline, virtual, inherited]"Sets up the value of the number of observations'.
Definition at line 335 of file SbGeoParameter.H'.
Referenced by SBSolution::updateParameter().
virtual void SBDerivation::setNumSes (intNum_) [inline, virtual, inherited]
Definition at line 336 of file SbGeoParameter.H'.
void SBSINEXParameter::setPointCode (const QString &P_) [inline]
Definition at line 110 of file SbGeoSINEX.H'.
References PointCode.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
virtual void SBParameter::setPrefix (charc_) [inline, virtual, inherited]
Definition at line 440 of file SbGeoParameter.H'.
virtual void SBParameter::setPSD_BN (doubled_) [inline, virtual, inherited]
Definition at line 438 of file SbGeoParameter.H'.
virtual void SBParameter::setPSD_RWN (doubled_) [inline, virtual, inherited]
Definition at line 437 of file SbGeoParameter.H'.
virtual void SBParameter::setS (doubled_) [inline, virtual, inherited]"Sets the value of the last udjustment'.
Definition at line 429 of file SbGeoParameter.H'.
Referenced by SBVLBIPreProcess::preProcess(), and SBParameterList::updateSolution().
virtual void SBParameter::setScale (doubles_) [inline, virtual, inherited]"Sets the value of the scale factor'.
Definition at line 433 of file SbGeoParameter.H'.
virtual void SBParameter::setSigmaAPriori (doubled_) [inline, virtual, inherited]
Definition at line 435 of file SbGeoParameter.H'.
Referenced by collectListOfSINEXParameters4NEQ().
void SBSINEXParameter::setSiteCode (const QString &S_) [inline]
Definition at line 109 of file SbGeoSINEX.H'.
References SiteCode.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
void SBSINEXParameter::setSolutionID (const QString &ID_) [inline]
Definition at line 111 of file SbGeoSINEX.H'.
References SolutionID.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
virtual void SBParameter::setSType (SBParameterCfg::StochTypeST_) [inline, virtual, inherited]
Definition at line 439 of file SbGeoParameter.H'.
virtual void SBParameter::setTau (doubled_) [inline, virtual, inherited]
Definition at line 436 of file SbGeoParameter.H'.
virtual void SBDerivation::setTimes (const SBDerivation &Der) [inline, virtual, inherited]
Definition at line 338 of file SbGeoParameter.H'.
References SBDerivation::Num, SBDerivation::NumSes, SBDerivation::TFinis, SBDerivation::TStart, and SBDerivation::TSum.
Referenced by SBSolution::getGlobalParameter4Report(), and SBSolution::updateParameter().
void SBSINEXParameter::setTValidEpoch (const SBMJD &T_) [inline]
Definition at line 113 of file SbGeoSINEX.H'.
References TValidEpoch.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
void SBSINEXParameter::setType (STypeT_) [inline]
Definition at line 108 of file SbGeoSINEX.H'.
References Type.
Referenced by collectListOfSINEXParameters(), and collectListOfSINEXParameters4NEQ().
virtual void SBParameter::setV (doubled_) [inline, virtual, inherited]"Sets the value of the parameter'.
Definition at line 427 of file SbGeoParameter.H'.
Referenced by SBSolution::getGlobalParameter4Report(), SBVLBIPreProcess::preProcess(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBStochParameter::update(), and SBSolution::updateParameter().
virtual double SBParameter::sigmaAPriori () const [inline, virtual, inherited]
Definition at line 419 of file SbGeoParameter.H'.
Referenced by collectListOfSINEXParameters4NEQ().
const QString& SBSINEXParameter::siteCode () const [inline]
Definition at line 98 of file SbGeoSINEX.H'.
References SiteCode.
Referenced by sinex_SourceIDBlock().
const QString& SBSINEXParameter::solutionID () const [inline]
Definition at line 100 of file SbGeoSINEX.H'.
References SolutionID.
virtual QString SBParameter::str4compare () const [inline, virtual, inherited]
Definition at line 452 of file SbGeoParameter.H'.
References SBAttributed::isAttr(), SBDerivation::IsPropagated, and SBNamed::name().
Referenced by SBSINEXParameterList::compareItems(), and SBParameterList::compareItems().
virtual SBParameterCfg::StochType SBParameter::sType () const [inline, virtual, inherited]
Definition at line 423 of file SbGeoParameter.H'.
virtual double SBParameter::tau () const [inline, virtual, inherited]
Definition at line 420 of file SbGeoParameter.H'.
virtual SBMJD SBDerivation::tEpoch (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns date of the mean observation'.
Reimplemented in SBStochParameter'.
Definition at line 328 of file SbGeoParameter.H'.
References TZero.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStochParameter::dump2File(), SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBSource::getParameters4Report(), SBParameterLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTRFVariations(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBStochParameter::tEpoch(), SBParameterLI::text(), SBParameter::timeStamp(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
virtual SBMJD SBDerivation::tEpoch_aux (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns date of the mean observation'.
Definition at line 350 of file SbGeoParameter.H'.
References TZero.
virtual SBMJD SBDerivation::tFinis (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns date of the last observation'.
Reimplemented in SBStochParameter'.
Definition at line 326 of file SbGeoParameter.H'.
References SBDerivation::TFinis.
Referenced by SBSource::getGlobalParameters4Report(), SBSource::getParameters4Report(), SBParameterLI::key(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBParameterLI::text(), and SBStochParameter::tFinis().
virtual SBMJD SBDerivation::tFinis_aux (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns date of the last observation'.
Definition at line 348 of file SbGeoParameter.H'.
References SBDerivation::TFinis_aux.
QString SBParameter::timeStamp () const [inline, inherited]
Definition at line 447 of file SbGeoParameter.H'.
References SBMJD::F_INTERNAL, SBDerivation::tEpoch(), and SBMJD::toString().
Referenced by SBStochParameter::addPar(), SBStochParameter::operator=(), and SBStochParameter::update().
virtual double SBDerivation::tInterval (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns interval of the observations'.
Reimplemented in SBStochParameter'.
Definition at line 330 of file SbGeoParameter.H'.
References SBDerivation::TStart.
Referenced by SBRunManager::makeReportEOP(), and SBStochParameter::tInterval().
virtual double SBDerivation::tInterval_aux (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns interval of the observations'.
Definition at line 352 of file SbGeoParameter.H'.
References SBDerivation::TStart_aux.
double SBSINEXParameter::totValue () const [inline]
Definition at line 102 of file SbGeoSINEX.H'.
References APrioriValue, and SBParameter::v().
virtual SBMJD SBDerivation::tStart (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns date of the first observation'.
Reimplemented in SBStochParameter'.
Definition at line 324 of file SbGeoParameter.H'.
References SBDerivation::TStart.
Referenced by SBSource::getGlobalParameters4Report(), SBSource::getParameters4Report(), SBParameterLI::key(), SBParameterList::report(), SBStochParameter::report(), sinex_SolutionEpochsBlock(), SBParameterLI::text(), and SBStochParameter::tStart().
virtual SBMJD SBDerivation::tStart_aux (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns date of the first observation'.
Definition at line 346 of file SbGeoParameter.H'.
References SBDerivation::TStart_aux.
void SBParameter::tuneParameter (const SBParameterCfg &Cfg) [virtual, inherited]
Definition at line 412 of file SbGeoParameter.C'.
References SBAttributed::addAttr(), SBParameterCfg::breakNoise(), SBParameterCfg::convAPriori(), SBAttributed::delAttr(), SBParameterCfg::isPropagated(), SBDerivation::IsPropagated, SBParameter::PSD_BN, SBParameter::PSD_RWN, SBParameterCfg::PT_STH, SBParameterCfg::scale(), SBParameter::Scale, SBParameter::SigmaAPriori, SBParameterCfg::stocAPriori(), SBParameterCfg::stochasticType(), SBParameter::SType, SBParameterCfg::tau(), SBParameter::Tau, SBParameterCfg::type(), and SBParameterCfg::whiteNoise().
Referenced by collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), and SBRunManager::fillParameterList().
const SBMJD& SBSINEXParameter::tValidEpoch () const [inline]
Definition at line 103 of file SbGeoSINEX.H'.
References TValidEpoch.
SType SBSINEXParameter::type () const [inline]
Definition at line 97 of file SbGeoSINEX.H'.
References Type.
Referenced by collectListOfSINEXParameters().
void SBParameter::update (const SBParameter *P_) [virtual, inherited]
Reimplemented in SBStochParameter'.
Definition at line 426 of file SbGeoParameter.C'.
References SBParameter::ClassName(), SBParameter::E, SBParameter::e(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBParameter::S, SBParameter::s(), SBParameter::V, and SBLog::write().
Referenced by SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), and SBStochParameter::update().
virtual double SBParameter::v (const SBMJD & = TZero) const [inline, virtual, inherited]"Returns value of the parameter'.
Reimplemented in SBStochParameter'.
Definition at line 411 of file SbGeoParameter.H'.
Referenced by SBStation::axisOffsett(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBStation::calcDisplacement(), collectListOfSINEXParameters4NEQ(), SBSolidTideLd::deg2InPhase(), SBSolidTideLd::dTide_dLag(), SBStochParameter::dump2File(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBSolution::getGlobalParameter4Report(), SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBSolidTideLd::h2(), SBSolidTideLdIERS92::h2(), SBEOP::interpolateEOPs(), SBParameterLI::key(), SBCableLI::key(), SBSolidTideLd::l2(), SBSolidTideLdIERS92::l2(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBRefraction::operator()(), operator<<(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBParameterList::report(), SBStochParameter::report(), sinex_tro_StaCoordinatesBlock(), SBSolution::submitGlobalParameters(), SBParameterLI::text(), SBCableLI::text(), totValue(), SBSolution::updateParameter(), SBSource::updateParameters(), SBStochParameter::v(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
virtual void SBDerivation::zero () [inline, virtual, inherited]
Definition at line 361 of file SbGeoParameter.H'.
Referenced by SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), and SBEstimator::processObs().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream & operator<< (QDataStream &s, const SBDerivation &D) [friend, inherited]"Output to the data stream'.
Definition at line 342 of file SbGeoParameter.C'.
QDataStream & operator<< (QDataStream &s, const SBParameter &P) [friend, inherited]"Output to the data stream'.
Definition at line 511 of file SbGeoParameter.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
QDataStream & operator>> (QDataStream &s, SBDerivation &D) [friend, inherited]"Input from the data stream'.
Definition at line 358 of file SbGeoParameter.C'.
QDataStream & operator>> (QDataStream &s, SBParameter &P) [friend, inherited]"Input from the data stream'.
Definition at line 519 of file SbGeoParameter.C'.
Member Data Documentation
double SBSINEXParameter::APrioriValue [protected]
Definition at line 73 of file SbGeoSINEX.H'.
Referenced by aPrioriValue(), SBSINEXParameter(), setAPrioriValue(), and totValue().
QString SBSINEXParameter::ConstraintCode [protected]
Definition at line 81 of file SbGeoSINEX.H'.
Referenced by constraintCode(), SBSINEXParameter(), and setConstraintCode().
double SBDerivation::D [protected, inherited]
value of a derivation;
Definition at line 289 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues(), SBDerivation::clearValues_aux(), SBDerivation::d(), SBDerivation::operator=(), SBDerivation::SBDerivation(), and SBDerivation::setD().
double SBParameter::E [protected, inherited]
formal error;
Definition at line 383 of file SbGeoParameter.H'.
Referenced by SBParameter::clearValues(), SBParameter::operator=(), SBParameter::rw(), SBParameter::SBParameter(), and SBParameter::update().
int SBSINEXParameter::Idx [protected]
Definition at line 74 of file SbGeoSINEX.H'.
Referenced by idx(), SBSINEXParameter(), and setIdx().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
int SBDerivation::Num [protected, inherited]
number of points per derivation;
Definition at line 290 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues(), SBDerivation::num(), SBDerivation::operator=(), SBDerivation::SBDerivation(), SBDerivation::setD(), and SBDerivation::setTimes().
int SBDerivation::Num_aux [protected, inherited]
number of points per derivation;
Definition at line 297 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues_aux(), SBDerivation::invertAux(), SBDerivation::num_aux(), SBDerivation::operator=(), SBDerivation::SBDerivation(), and SBDerivation::setD().
int SBDerivation::NumSes [protected, inherited]
number of sessions per derivation;
Definition at line 291 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues(), SBDerivation::numSes(), SBDerivation::operator=(), SBDerivation::SBDerivation(), and SBDerivation::setTimes().
QString SBSINEXParameter::PointCode [protected]
Definition at line 77 of file SbGeoSINEX.H'.
Referenced by pointCode(), SBSINEXParameter(), and setPointCode().
char SBParameter::Prefix [protected, inherited]
Definition at line 393 of file SbGeoParameter.H'.
Referenced by SBParameter::operator=(), and SBParameter::SBParameter().
double SBParameter::PSD_BN [protected, inherited]
PSD of White Noise used in break'.
Definition at line 391 of file SbGeoParameter.H'.
Referenced by SBParameter::operator=(), SBParameter::rw(), SBParameter::SBParameter(), and SBParameter::tuneParameter().
double SBParameter::PSD_RWN [protected, inherited]
PSD of Ruled White Noise'.
Definition at line 390 of file SbGeoParameter.H'.
Referenced by SBParameter::operator=(), SBParameter::rw(), SBParameter::SBParameter(), and SBParameter::tuneParameter().
double SBParameter::S [protected, inherited]
value of the solution;
Definition at line 382 of file SbGeoParameter.H'.
Referenced by SBParameter::clearValues(), SBParameter::operator=(), SBParameter::SBParameter(), and SBParameter::update().
double SBParameter::Scale [protected, inherited]
scale factor;
Definition at line 384 of file SbGeoParameter.H'.
Referenced by SBParameter::operator=(), SBStochParameter::report(), SBParameter::SBParameter(), and SBParameter::tuneParameter().
double SBParameter::SigmaAPriori [protected, inherited]
a priori std'. deviation (to init the Inform'. matrix)
Definition at line 388 of file SbGeoParameter.H'.
Referenced by SBParameter::operator=(), SBParameter::rw(), SBParameter::SBParameter(), and SBParameter::tuneParameter().
QString SBSINEXParameter::SiteCode [protected]
Definition at line 76 of file SbGeoSINEX.H'.
Referenced by SBSINEXParameter(), setSiteCode(), and siteCode().
QString SBSINEXParameter::SolutionID [protected]
Definition at line 78 of file SbGeoSINEX.H'.
Referenced by SBSINEXParameter(), setSolutionID(), and solutionID().
double SBParameter::Tau [protected, inherited]
time of relaxation (for stochastic parameters)
Definition at line 389 of file SbGeoParameter.H'.
Referenced by SBParameter::m(), SBParameter::operator=(), SBParameter::rw(), SBParameter::SBParameter(), and SBParameter::tuneParameter().
SBMJD SBDerivation::TFinis [protected, inherited]
MJD of the last measurement;'.
Definition at line 293 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues(), SBDerivation::operator=(), SBDerivation::SBDerivation(), SBDerivation::setD(), SBDerivation::setTimes(), and SBDerivation::tFinis().
SBMJD SBDerivation::TFinis_aux [protected, inherited]
MJD of the last measurement;'.
Definition at line 299 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues_aux(), SBDerivation::invertAux(), SBDerivation::operator=(), SBDerivation::SBDerivation(), SBDerivation::setD(), and SBDerivation::tFinis_aux().
SBMJD SBDerivation::TStart [protected, inherited]
MJD of the first measurement;'.
Definition at line 292 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues(), SBDerivation::operator=(), SBDerivation::SBDerivation(), SBDerivation::setD(), SBDerivation::setTimes(), SBStatistics::setTStart(), SBDerivation::tInterval(), SBDerivation::tStart(), and SBStatistics::tStart().
SBMJD SBDerivation::TStart_aux [protected, inherited]
MJD of the first measurement;'.
Definition at line 298 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues_aux(), SBDerivation::invertAux(), SBDerivation::operator=(), SBDerivation::SBDerivation(), SBDerivation::setD(), SBDerivation::tInterval_aux(), and SBDerivation::tStart_aux().
long double SBDerivation::TSum [protected, inherited]
the sum of the epochs of observation;
Definition at line 294 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues(), SBDerivation::operator=(), SBDerivation::SBDerivation(), SBDerivation::setD(), and SBDerivation::setTimes().
long double SBDerivation::TSum_aux [protected, inherited]
the sum of the epochs of observation;
Definition at line 300 of file SbGeoParameter.H'.
Referenced by SBDerivation::clearValues_aux(), SBDerivation::invertAux(), SBDerivation::operator=(), SBDerivation::SBDerivation(), and SBDerivation::setD().
SBMJD SBSINEXParameter::TValidEpoch [protected]
Definition at line 80 of file SbGeoSINEX.H'.
Referenced by SBSINEXParameter(), setTValidEpoch(), and tValidEpoch().
SType SBSINEXParameter::Type [protected]
Definition at line 75 of file SbGeoSINEX.H'.
Referenced by parameterType(), parameterUnits(), SBSINEXParameter(), setType(), and type().
double SBParameter::V [protected, inherited]
value of the parameter;
Definition at line 381 of file SbGeoParameter.H'.
Referenced by SBParameter::clearValues(), SBParameter::operator=(), SBParameter::SBParameter(), and SBParameter::update().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.