SBSolutionBrowser
NAME
SBSolutionBrowser -
SYNOPSIS
#include <SbISolution.H>
Inherits SBTabDialog'.
Public Member Functions
SBSolutionBrowser (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBSolutionBrowser ()
virtual QString ClassName () const
Protected Slots
void modified (bool)
void batch4StochStChanged (QListViewItem *)
void batch4StochSoChanged (QListViewItem *)
void batch4StochEOPChanged (QListViewItem *)
void dumpSolution ()
void updateCRF ()
void updateTRF ()
virtual void makeApply ()
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual void acquireData ()
Private Member Functions
QWidget * wGeneralInfo ()
QWidget * wWRMSs ()
QWidget * wGlobalPars ()
QWidget * wLocalStPars ()
QWidget * wLocalSoPars ()
QWidget * wLocalEOPPars ()
QWidget * wStochStPars ()
QWidget * wStochSoPars ()
QWidget * wStochEOPPars ()
void lookupParameters ()
Private Attributes
bool isModified
SBProject * Prj
SBSolution * Solution
QLabel * lGenVarF
QLabel * lGenWRMS
QLabel * lGenNumObs
QLabel * lGenNumPars
QListView * BatchesLV
bool IsGlobalPars
QListView * GlobalParsLV
SBPlotCarrier * PC_SessRMS
bool IsLocalSta
SBStochParameterList LocalStPars
SBPlotCarrier * PC_LocalStPars
QList< QString > LocStationParameters
SBStationInfoList LocStations
bool IsLocalSou
SBStochParameterList LocalSoPars
SBPlotCarrier * PC_LocalSoPars
QList< QString > LocSourceParameters
SBSourceInfoList LocSources
bool IsLocalEOP
SBStochParameterList LocalEOPPars
SBPlotCarrier * PC_LocalEOPPars
bool IsStochSta
SBStochParameterList StochStPars
SBPlotCarrier * StochasticsStationsPC
SBPlot * StochasticsStationsPlot
bool IsStochSou
SBStochParameterList StochSoPars
SBPlotCarrier * StochasticsSourcesPC
SBPlot * StochasticsSourcesPlot
bool IsStochEOP
SBStochParameterList StochEOPPars
SBPlotCarrier * StochasticsEOPsPC
SBPlot * StochasticsEOPsPlot
double Scale
QString ScaleName
Detailed Description
Definition at line 98 of file SbISolution.H'.
Constructor & Destructor Documentation
SBSolutionBrowser::SBSolutionBrowser (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 168 of file SbISolution.C'.
References ClassName(), dumpSolution(), SBLog::ERR, IsGlobalPars, IsLocalEOP, IsLocalSou, IsLocalSta, isModified, IsStochEOP, IsStochSou, IsStochSta, SBSetUp::loadProject(), Log, lookupParameters(), mainSetOperation(), SBNamed::name(), SBSetUp::path2Output(), PC_LocalEOPPars, PC_LocalSoPars, PC_LocalStPars, PC_SessRMS, Prj, SBLog::RUN, Scale, SBSetUp::scale(), ScaleName, SBSetUp::scaleName(), SBVersion::selfName(), SetUp, Solution, StochasticsEOPsPC, StochasticsEOPsPlot, StochasticsSourcesPC, StochasticsSourcesPlot, StochasticsStationsPC, StochasticsStationsPlot, updateCRF(), updateTRF(), Version, wGeneralInfo(), wGlobalPars(), wLocalEOPPars(), wLocalSoPars(), wLocalStPars(), SBLog::write(), wStochEOPPars(), wStochSoPars(), wStochStPars(), and wWRMSs().
SBSolutionBrowser::~SBSolutionBrowser ()
Definition at line 250 of file SbISolution.C'.
References PC_LocalEOPPars, PC_LocalSoPars, PC_LocalStPars, PC_SessRMS, Prj, Solution, StochasticsEOPsPC, StochasticsSourcesPC, and StochasticsStationsPC.
Member Function Documentation
virtual void SBTabDialog::acquireData () [inline, protected, virtual, inherited]
Reimplemented in SBVLBISessionEditor, SBStationEditor, SBSiteEditor, SBParametersEditor, SBSourceEditor, SBModelEditor, SBProjectEdit, and SBSetupDialog'.
Definition at line 91 of file SbInterface.H'.
Referenced by SBTabDialog::done(), and SBTabDialog::makeApply().
void SBSolutionBrowser::batch4StochEOPChanged (QListViewItem *LI) [protected, slot]
Definition at line 1335 of file SbISolution.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), SBStochParameterList::clear(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotBranch::data(), SBPlot::dataChanged(), SBParameter::e(), SBStochParameterList::find(), SBPlotBranch::Idx, SBStochParameterList::inSort(), SBNamed::name(), SBSolution::prepare4Batch(), Prj, SBParameter::s(), SBParameter::scale(), SBMatrix::set(), SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), Solution, SBSolution::stochastic(), StochasticsEOPsPC, StochasticsEOPsPlot, StochEOPPars, SBDerivation::tEpoch(), and SBParameter::v().
Referenced by wStochEOPPars().
void SBSolutionBrowser::batch4StochSoChanged (QListViewItem *LI) [protected, slot]
Definition at line 1148 of file SbISolution.C'.
References SBObjectObsInfo::aka(), SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), ClassName(), SBStochParameterList::clear(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotBranch::data(), SBPlot::dataChanged(), SBParameter::e(), SBLog::ERR, SBSourceInfoList::find(), SBStochParameterList::find(), SBPlotCarrier::findBranch(), SBPlotBranch::Idx, SBStochParameterList::inSort(), SBLog::INTERFACE, Log, SBNamed::name(), SBObjectObsInfo::num(), SBSolution::prepare4Batch(), Prj, SBParameter::s(), SBParameter::scale(), SBMatrix::set(), SBPlotCarrier::setFile4SaveBaseName(), SBObjectObsInfo::setNum(), SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), Solution, SBProject::sourceList(), SBSolution::stochastic(), StochasticsSourcesPC, StochasticsSourcesPlot, StochSoPars, SBDerivation::tEpoch(), SBParameter::v(), and SBLog::write().
Referenced by wStochSoPars().
void SBSolutionBrowser::batch4StochStChanged (QListViewItem *LI) [protected, slot]
Definition at line 942 of file SbISolution.C'.
References SBObjectObsInfo::aka(), SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), ClassName(), SBStochParameterList::clear(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotBranch::data(), SBPlot::dataChanged(), SBParameter::e(), SBLog::ERR, SBLog::ESTIMATOR, SBStationInfoList::find(), SBStochParameterList::find(), SBPlotCarrier::findBranch(), SBPlotBranch::Idx, SBStochParameterList::inSort(), SBLog::INTERFACE, Log, SBNamed::name(), SBObjectObsInfo::num(), SBSolution::prepare4Batch(), Prj, SBParameter::s(), SBParameter::scale(), SBMatrix::set(), SBPlotCarrier::setFile4SaveBaseName(), SBObjectObsInfo::setNum(), SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), Solution, SBProject::stationList(), SBSolution::stochastic(), StochasticsStationsPC, StochasticsStationsPlot, StochStPars, SBDerivation::tEpoch(), SBStationID::toString(), SBParameter::v(), and SBLog::write().
Referenced by wStochStPars().
virtual QString SBSolutionBrowser::ClassName () const [inline, virtual]
Definition at line 104 of file SbISolution.H'.
Referenced by batch4StochSoChanged(), batch4StochStChanged(), lookupParameters(), SBSolutionBrowser(), updateCRF(), updateTRF(), wLocalEOPPars(), wLocalSoPars(), and wLocalStPars().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
void SBSolutionBrowser::dumpSolution () [protected, slot]
Definition at line 312 of file SbISolution.C'.
References SBSolution::dumpParameters(), and Solution.
Referenced by SBSolutionBrowser().
void SBSolutionBrowser::lookupParameters () [private]
Definition at line 496 of file SbISolution.C'.
References SBObjectObsInfo::aka(), ClassName(), SBStochParameterList::clear(), SBLog::ERR, SBLog::ESTIMATOR, SBStationInfoList::find(), SBSourceInfoList::find(), SBStochParameterList::find(), SBSolution::global(), SBLog::INF, SBStochParameterList::inSort(), IsGlobalPars, IsLocalEOP, IsLocalSou, IsLocalSta, IsStochEOP, IsStochSou, IsStochSta, SBSolution::local(), LocalEOPPars, LocalSoPars, LocalStPars, LocSourceParameters, LocSources, LocStationParameters, LocStations, Log, SBNamed::name(), SBSolution::prepare4Batch(), Prj, SBParameter::scale(), SBObjectObsInfo::setNum(), Solution, SBProject::sourceList(), SBSolution::statByBatch(), SBProject::stationList(), SBSolution::stochastic(), SBStationID::toString(), and SBLog::write().
Referenced by SBSolutionBrowser().
virtual void SBTabDialog::makeApply () [inline, protected, virtual, slot, inherited]
Reimplemented in SBVLBISessionEditor, SBStationEditor, SBSiteEditor, SBParametersEditor, SBSourceEditor, SBModelEditor, SBProjectEdit, and SBSetupDialog'.
Definition at line 78 of file SbInterface.H'.
References SBTabDialog::acquireData().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBSolutionBrowser::modified (boolisModified_) [protected, slot]
Definition at line 307 of file SbISolution.C'.
References isModified.
void SBSolutionBrowser::updateCRF () [protected, slot]
Definition at line 1421 of file SbISolution.C'.
References SBAttributed::addAttr(), SBSymMatrix::at(), ClassName(), SBLog::DATA, SBLog::DBG, SBSource::dn_t(), SBSourceInfo::EstCoo, SBSourceInfoList::find(), SB_CRF::finisRun(), SB_CRF::first(), SBSource::getGlobalParameters4Report(), SBParameterList::idx(), SBAttributed::isAttr(), SBSetUp::loadCRF(), SBSolution::loadGlbCor(), Log, SB_CRF::next(), SBSourceInfo::notValid, SBSource::OrigEstimated, SBSource::p_DN(), SBSource::p_RA(), SB_CRF::prepare4Run(), Prj, SBSource::ra_t(), SBSetUp::saveCRF(), SBSource::setCorrRA_DN(), SBSource::setDN(), SBSource::setRA(), SetUp, Solution, SBProject::sourceList(), and SBLog::write().
Referenced by SBSolutionBrowser().
void SBSolutionBrowser::updateTRF () [protected, slot]
Definition at line 1476 of file SbISolution.C'.
References SBAttributed::addAttr(), ClassName(), SBLog::DATA, SBLog::DBG, SBStationInfo::EstCoo, SBStationInfoList::find(), SB_TRF::finisRun(), SBStationList::first(), SB_TRF::first(), SBStation::getGlobalParameters4UpdateTRF(), SBStation::id(), SBAttributed::isAttr(), SBSetUp::loadTRF(), Log, SBStationList::next(), SB_TRF::next(), SBStationInfo::notValid, SBStation::OrigEstimated, SB_TRF::prepare4Run(), Prj, SBSetUp::saveTRF(), SetUp, Solution, SBProject::stationList(), SBSite::stations(), and SBLog::write().
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wGeneralInfo () [private]
Definition at line 322 of file SbISolution.C'.
References BatchesLV, lGenNumObs, lGenNumPars, lGenVarF, lGenWRMS, SBStatistics::numConstr(), SBStatistics::numObs(), SBStatistics::numPars(), Scale, ScaleName, Solution, SBSolution::statByBatch(), SBSolution::statGeneral(), SBStatistics::VarFactor_unit(), and SBStatistics::WRMS_unit().
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wGlobalPars () [private]
Definition at line 417 of file SbISolution.C'.
References SBSolution::global(), GlobalParsLV, and Solution.
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wLocalEOPPars () [private]
Definition at line 829 of file SbISolution.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), ClassName(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotBranch::data(), SBParameter::e(), SBLog::ERR, SBPlotBranch::Idx, SBLog::INTERFACE, LocalEOPPars, Log, SBNamed::name(), PC_LocalEOPPars, Prj, SBParameter::s(), SBParameter::scale(), SBMatrix::set(), SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), SBDerivation::tEpoch(), SBParameter::v(), and SBLog::write().
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wLocalSoPars () [private]
Definition at line 745 of file SbISolution.C'.
References SBObjectObsInfo::aka(), SBPlotCarrier::AT_MJD, ClassName(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotBranch::data(), SBParameter::e(), SBLog::ERR, SBSourceInfoList::find(), SBPlotCarrier::findBranch(), SBPlotBranch::Idx, SBLog::INTERFACE, LocalSoPars, LocSourceParameters, LocSources, Log, SBNamed::name(), SBObjectObsInfo::num(), PC_LocalSoPars, Prj, SBParameter::s(), SBParameter::scale(), SBMatrix::set(), SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), SBDerivation::tEpoch(), SBParameter::v(), and SBLog::write().
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wLocalStPars () [private]
Definition at line 646 of file SbISolution.C'.
References SBObjectObsInfo::aka(), SBPlotCarrier::AT_MJD, ClassName(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotBranch::data(), SBParameter::e(), SBLog::ERR, SBLog::ESTIMATOR, SBStationInfoList::find(), SBPlotCarrier::findBranch(), SBPlotBranch::Idx, SBLog::INTERFACE, LocalStPars, LocStationParameters, LocStations, Log, SBNamed::name(), SBObjectObsInfo::num(), PC_LocalStPars, Prj, SBParameter::s(), SBParameter::scale(), SBMatrix::set(), SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), SBDerivation::tEpoch(), SBParameter::v(), and SBLog::write().
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wStochEOPPars () [private]
Definition at line 1288 of file SbISolution.C'.
References batch4StochEOPChanged(), SBNamed::name(), Prj, Scale, SBPlotCarrier::setFile4SaveBaseName(), Solution, SBSolution::statByBatch(), StochasticsEOPsPC, and StochasticsEOPsPlot.
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wStochSoPars () [private]
Definition at line 1101 of file SbISolution.C'.
References batch4StochSoChanged(), SBNamed::name(), Prj, Scale, SBPlotCarrier::setFile4SaveBaseName(), Solution, SBSolution::statByBatch(), StochasticsSourcesPC, and StochasticsSourcesPlot.
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wStochStPars () [private]
Definition at line 894 of file SbISolution.C'.
References batch4StochStChanged(), SBNamed::name(), Prj, Scale, SBPlotCarrier::setFile4SaveBaseName(), Solution, SBSolution::statByBatch(), StochasticsStationsPC, and StochasticsStationsPlot.
Referenced by SBSolutionBrowser().
QWidget * SBSolutionBrowser::wWRMSs () [private]
Definition at line 456 of file SbISolution.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotBranch::data(), SBPlotBranch::Idx, SBNamed::name(), PC_SessRMS, SBPlot::PM_HAS_HAVE_ZERO, SBPlot::PM_IMPULSE, Prj, SBSetUp::scale(), SBSetUp::scaleName(), SBMatrix::set(), SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setType(), SetUp, and SBProject::VLBIsessionList().
Referenced by SBSolutionBrowser().
Member Data Documentation
QListView* SBSolutionBrowser::BatchesLV [private]
Definition at line 142 of file SbISolution.H'.
Referenced by wGeneralInfo().
QListView* SBSolutionBrowser::GlobalParsLV [private]
Definition at line 148 of file SbISolution.H'.
Referenced by wGlobalPars().
bool SBSolutionBrowser::IsGlobalPars [private]
Definition at line 147 of file SbISolution.H'.
Referenced by lookupParameters(), and SBSolutionBrowser().
bool SBSolutionBrowser::IsLocalEOP [private]
Definition at line 169 of file SbISolution.H'.
Referenced by lookupParameters(), and SBSolutionBrowser().
bool SBSolutionBrowser::IsLocalSou [private]
Definition at line 162 of file SbISolution.H'.
Referenced by lookupParameters(), and SBSolutionBrowser().
bool SBSolutionBrowser::IsLocalSta [private]
Definition at line 155 of file SbISolution.H'.
Referenced by lookupParameters(), and SBSolutionBrowser().
bool SBSolutionBrowser::isModified [private]
Definition at line 117 of file SbISolution.H'.
Referenced by modified(), and SBSolutionBrowser().
bool SBSolutionBrowser::IsStochEOP [private]
Definition at line 190 of file SbISolution.H'.
Referenced by lookupParameters(), and SBSolutionBrowser().
bool SBSolutionBrowser::IsStochSou [private]
Definition at line 183 of file SbISolution.H'.
Referenced by lookupParameters(), and SBSolutionBrowser().
bool SBSolutionBrowser::IsStochSta [private]
Definition at line 177 of file SbISolution.H'.
Referenced by lookupParameters(), and SBSolutionBrowser().
QLabel* SBSolutionBrowser::lGenNumObs [private]
Definition at line 140 of file SbISolution.H'.
Referenced by wGeneralInfo().
QLabel* SBSolutionBrowser::lGenNumPars [private]
Definition at line 141 of file SbISolution.H'.
Referenced by wGeneralInfo().
QLabel* SBSolutionBrowser::lGenVarF [private]
Definition at line 138 of file SbISolution.H'.
Referenced by wGeneralInfo().
QLabel* SBSolutionBrowser::lGenWRMS [private]
Definition at line 139 of file SbISolution.H'.
Referenced by wGeneralInfo().
SBStochParameterList SBSolutionBrowser::LocalEOPPars [private]
Definition at line 170 of file SbISolution.H'.
Referenced by lookupParameters(), and wLocalEOPPars().
SBStochParameterList SBSolutionBrowser::LocalSoPars [private]
Definition at line 163 of file SbISolution.H'.
Referenced by lookupParameters(), and wLocalSoPars().
SBStochParameterList SBSolutionBrowser::LocalStPars [private]
Definition at line 156 of file SbISolution.H'.
Referenced by lookupParameters(), and wLocalStPars().
QList<QString> SBSolutionBrowser::LocSourceParameters [private]
Definition at line 165 of file SbISolution.H'.
Referenced by lookupParameters(), and wLocalSoPars().
SBSourceInfoList SBSolutionBrowser::LocSources [private]
Definition at line 166 of file SbISolution.H'.
Referenced by lookupParameters(), and wLocalSoPars().
QList<QString> SBSolutionBrowser::LocStationParameters [private]
Definition at line 158 of file SbISolution.H'.
Referenced by lookupParameters(), and wLocalStPars().
SBStationInfoList SBSolutionBrowser::LocStations [private]
Definition at line 159 of file SbISolution.H'.
Referenced by lookupParameters(), and wLocalStPars().
SBPlotCarrier* SBSolutionBrowser::PC_LocalEOPPars [private]
Definition at line 171 of file SbISolution.H'.
Referenced by SBSolutionBrowser(), wLocalEOPPars(), and ~SBSolutionBrowser().
SBPlotCarrier* SBSolutionBrowser::PC_LocalSoPars [private]
Definition at line 164 of file SbISolution.H'.
Referenced by SBSolutionBrowser(), wLocalSoPars(), and ~SBSolutionBrowser().
SBPlotCarrier* SBSolutionBrowser::PC_LocalStPars [private]
Definition at line 157 of file SbISolution.H'.
Referenced by SBSolutionBrowser(), wLocalStPars(), and ~SBSolutionBrowser().
SBPlotCarrier* SBSolutionBrowser::PC_SessRMS [private]
Definition at line 149 of file SbISolution.H'.
Referenced by SBSolutionBrowser(), wWRMSs(), and ~SBSolutionBrowser().
SBProject* SBSolutionBrowser::Prj [private]
Definition at line 118 of file SbISolution.H'.
Referenced by batch4StochEOPChanged(), batch4StochSoChanged(), batch4StochStChanged(), lookupParameters(), SBSolutionBrowser(), updateCRF(), updateTRF(), wLocalEOPPars(), wLocalSoPars(), wLocalStPars(), wStochEOPPars(), wStochSoPars(), wStochStPars(), wWRMSs(), and ~SBSolutionBrowser().
double SBSolutionBrowser::Scale [private]
Definition at line 200 of file SbISolution.H'.
Referenced by SBSolutionBrowser(), wGeneralInfo(), wStochEOPPars(), wStochSoPars(), and wStochStPars().
QString SBSolutionBrowser::ScaleName [private]
Definition at line 201 of file SbISolution.H'.
Referenced by SBSolutionBrowser(), and wGeneralInfo().
SBSolution* SBSolutionBrowser::Solution [private]
Definition at line 119 of file SbISolution.H'.
Referenced by batch4StochEOPChanged(), batch4StochSoChanged(), batch4StochStChanged(), dumpSolution(), lookupParameters(), SBSolutionBrowser(), updateCRF(), updateTRF(), wGeneralInfo(), wGlobalPars(), wStochEOPPars(), wStochSoPars(), wStochStPars(), and ~SBSolutionBrowser().
SBPlotCarrier* SBSolutionBrowser::StochasticsEOPsPC [private]
Definition at line 192 of file SbISolution.H'.
Referenced by batch4StochEOPChanged(), SBSolutionBrowser(), wStochEOPPars(), and ~SBSolutionBrowser().
SBPlot* SBSolutionBrowser::StochasticsEOPsPlot [private]
Definition at line 193 of file SbISolution.H'.
Referenced by batch4StochEOPChanged(), SBSolutionBrowser(), and wStochEOPPars().
SBPlotCarrier* SBSolutionBrowser::StochasticsSourcesPC [private]
Definition at line 185 of file SbISolution.H'.
Referenced by batch4StochSoChanged(), SBSolutionBrowser(), wStochSoPars(), and ~SBSolutionBrowser().
SBPlot* SBSolutionBrowser::StochasticsSourcesPlot [private]
Definition at line 186 of file SbISolution.H'.
Referenced by batch4StochSoChanged(), SBSolutionBrowser(), and wStochSoPars().
SBPlotCarrier* SBSolutionBrowser::StochasticsStationsPC [private]
Definition at line 179 of file SbISolution.H'.
Referenced by batch4StochStChanged(), SBSolutionBrowser(), wStochStPars(), and ~SBSolutionBrowser().
SBPlot* SBSolutionBrowser::StochasticsStationsPlot [private]
Definition at line 180 of file SbISolution.H'.
Referenced by batch4StochStChanged(), SBSolutionBrowser(), and wStochStPars().
SBStochParameterList SBSolutionBrowser::StochEOPPars [private]
Definition at line 191 of file SbISolution.H'.
Referenced by batch4StochEOPChanged().
SBStochParameterList SBSolutionBrowser::StochSoPars [private]
Definition at line 184 of file SbISolution.H'.
Referenced by batch4StochSoChanged().
SBStochParameterList SBSolutionBrowser::StochStPars [private]
Definition at line 178 of file SbISolution.H'.
Referenced by batch4StochStChanged().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.