SBSourceInfoList
NAME
SBSourceInfoList -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits QList< SBSourceInfo >'.
Public Member Functions
virtual QString ClassName () const
virtual int idx (const SBNamed *item)
virtual SBSourceInfo * find (const SBNamed *item)
void dumpUserInfo (QTextStream &ts)
bool restoreUserInfo (QTextStream &)
virtual void clearRMSs ()
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Detailed Description
List of source infos'.
Definition at line 499 of file SbGeoObsVLBI.H'.
Member Function Documentation
virtual QString SBSourceInfoList::ClassName () const [inline, virtual]
Definition at line 511 of file SbGeoObsVLBI.H'.
Referenced by restoreUserInfo().
virtual void SBSourceInfoList::clearRMSs () [inline, virtual]
Definition at line 521 of file SbGeoObsVLBI.H'.
Referenced by SBProject::clearRMSs(), and SBVLBISession::clearRMSs().
virtual int SBSourceInfoList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 502 of file SbGeoObsVLBI.H'.
void SBSourceInfoList::dumpUserInfo (QTextStream &ts) [inline]
Definition at line 518 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISession::dumpUserInfo().
virtual SBSourceInfo* SBSourceInfoList::find (const SBNamed *item) [inline, virtual]
Definition at line 513 of file SbGeoObsVLBI.H'.
Referenced by SBSolutionBrowser::batch4StochSoChanged(), SBRunManager::fillParameterList(), idx(), SBObsVLBIEntry::isEligible(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBVLBISession::parseObsDumpString(), SBObsVLBIEntry::process(), restoreUserInfo(), sinex_SourceIDBlock(), SBRunManager::stripCRF(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::wLocalSoPars().
virtual int SBSourceInfoList::idx (const SBNamed *item) [inline, virtual]
Definition at line 512 of file SbGeoObsVLBI.H'.
References find().
virtual QDataStream& SBSourceInfoList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 508 of file SbGeoObsVLBI.H'.
bool SBSourceInfoList::restoreUserInfo (QTextStream &ts)
Definition at line 481 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::DBG, find(), Log, SBSourceInfo::restoreUserInfo(), SBNamed::setName(), and SBLog::write().
Referenced by SBVLBISession::restoreUserInfo().
virtual QDataStream& SBSourceInfoList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 506 of file SbGeoObsVLBI.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.