SBSouInfoLI
NAME
SBSouInfoLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QListViewItem'.
Public Member Functions
SBSouInfoLI (QListView *parent, SBSourceInfo *SI_, BrowseMode Mode_, SBSource::SStatus Status_=SBSource::STATUS_UNKN, SBSource::SType Type_=SBSource::TYPE_UNKN, bool IsSuspected_=FALSE)
virtual QString ClassName () const
SBSourceInfo * sourceInfo ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBSourceInfo * SouInf
BrowseMode Mode
SBSource::SStatus Status
SBSource::SType Type
bool IsSuspected
Detailed Description
Definition at line 174 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBSouInfoLI::SBSouInfoLI (QListView *parent, SBSourceInfo *SI_, BrowseModeMode_, SBSource::SStatusStatus_ = SBSource::STATUS_UNKN, SBSource::STypeType_ = SBSource::TYPE_UNKN, boolIsSuspected_ = FALSE) [inline]
Definition at line 183 of file SbIObsVLBI.H'.
References IsSuspected, Mode, SouInf, Status, and Type.
Member Function Documentation
virtual QString SBSouInfoLI::ClassName () const [inline, virtual]
Definition at line 187 of file SbIObsVLBI.H'.
QString SBSouInfoLI::key (intcol, bool) const [virtual]
Definition at line 834 of file SbIObsVLBI.C'.
References SBObjectObsInfo::aka(), BM_GENERAL, BM_PROJECT, SBSourceInfo::ConstrCoo, SBSourceInfo::EstCoo, SBObjectObsInfo::idx(), SBAttributed::isAttr(), IsSuspected, Mode, SBNamed::name(), SBSourceInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBSetUp::scale(), SetUp, SouInf, Status, TmpString, Type, and SBObjectObsInfo::wrms().
SBSourceInfo* SBSouInfoLI::sourceInfo () [inline]
Definition at line 188 of file SbIObsVLBI.H'.
References SouInf.
QString SBSouInfoLI::text (intcol) const [virtual]
Definition at line 772 of file SbIObsVLBI.C'.
References SBObjectObsInfo::aka(), BM_GENERAL, BM_PROJECT, SBSourceInfo::ConstrCoo, SBSourceInfo::EstCoo, SBObjectObsInfo::idx(), SBAttributed::isAttr(), IsSuspected, Mode, SBNamed::name(), SBSourceInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBSetUp::scale(), SetUp, SouInf, Status, TmpString, Type, and SBObjectObsInfo::wrms().
Member Data Documentation
bool SBSouInfoLI::IsSuspected [private]
Definition at line 181 of file SbIObsVLBI.H'.
Referenced by key(), SBSouInfoLI(), and text().
BrowseMode SBSouInfoLI::Mode [private]
Definition at line 178 of file SbIObsVLBI.H'.
Referenced by key(), SBSouInfoLI(), and text().
SBSourceInfo* SBSouInfoLI::SouInf [private]
Definition at line 177 of file SbIObsVLBI.H'.
Referenced by key(), SBSouInfoLI(), sourceInfo(), and text().
SBSource::SStatus SBSouInfoLI::Status [private]
Definition at line 179 of file SbIObsVLBI.H'.
Referenced by key(), SBSouInfoLI(), and text().
SBSource::SType SBSouInfoLI::Type [private]
Definition at line 180 of file SbIObsVLBI.H'.
Referenced by key(), SBSouInfoLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.