SBSolution
NAME
SBSolution -
SYNOPSIS
#include <SbGeoParameter.H>
Public Member Functions
SBSolution (SBProject *=NULL, bool=TRUE)
~SBSolution ()
QString ClassName () const
SBProject * project () const
SBStatistics * statGeneral ()
SBStatisticsList & statByBatch ()
SBParameterList & global ()
SBParameterList & local ()
SBStochParameterList & stochastic ()
void setProject (SBProject *const P_)
void prepare4Batch (const QString &, bool=FALSE)
void submitGlobalParameters (SBParameterList *, const SBSymMatrix *)
void reportGlobalParameters ()
void submitLocalParameters (SBParameterList *, const SBSymMatrix *)
void reportLocalParameters ()
void submitStochasticParameters (SBParameterList *, const SBSymMatrix *)
void saveStochasticParameters ()
void reportStochasticParameters ()
void dumpParameters ()
bool loadGlbCor (SBParameterList *&, SBSymMatrix *&)
bool loadLocCor (const QString &, SBParameterList *&, SBSymMatrix *&)
SBStatistics * stat4CurrentBatch ()
void updateParameter (SBParameter *, const SBMJD &, bool=TRUE)
void getGlobalParameter4Report (SBParameter *)
void deleteSolution ()
bool isLocalModified () const
void setIsLocalModified (bool IsModified_)
QString guessParameterName (const QString &)
void saveNormalEqs (SBParameterList *, SBVector *, SBUpperMatrix *, SBParameterList *, SBVector *, SBUpperMatrix *, SBMatrix *, const QString &)
void loadNormalEqs (SBParameterList *&, SBVector *&, SBUpperMatrix *&, SBParameterList *&, SBVector *&, SBUpperMatrix *&, SBMatrix *&, const QString &)
Private Member Functions
void loadStatistics ()
bool loadGlbPar ()
bool loadLocPar (const QString &)
bool loadStcPar (const QString &)
void saveStatistics ()
void saveGlbPar ()
void saveGlbCor (SBParameterList *, const SBSymMatrix *)
void saveLocPar (const QString &)
void saveLocCor (const QString &, SBParameterList *, const SBSymMatrix *)
void saveStcPar (const QString &)
bool checkPath (const QString &, const QString &)
QString path2GlbDir () const
QString path2LocDir () const
QString path2StcDir () const
QString path2GlbFile () const
QString path2GlbFileCorr () const
QString path2LocFile (const QString &name_) const
QString path2LocFileCorr (const QString &name_) const
QString path2StcFile (const QString &name_) const
QString path2LocFileNormEqs (const QString &name_) const
Private Attributes
SBProject * Prj
project (not an owner of);
SBStatistics StatGeneral
general statistics information
SBStatisticsList StatByBatch
list of statistics info per a batch
bool IsModified
SBStatistics * Stat4CurrentBatch
QString StatisticsFile
SBParameterList Global
list of global parameters;
bool IsGlobalModified
SBParameterList Local
list of local parameters;
bool IsLocalModified
QString CurrentBatch
SBStochParameterList Stochastic
list of stochastic parameters;
bool IsStochasticModified
Static Private Attributes
static const QString DirGlobal
static const QString DirArc
static const QString DirLocal
static const QString DirStoch
Detailed Description
Class SBSolution, describes solution'. The solution is the set of global parameters (common for all data), local parameters (wich are depended on date of observation) and a stochastic parameters (date and time dependant)'.
Definition at line 821 of file SbGeoParameter.H'.
Constructor & Destructor Documentation
SBSolution::SBSolution (SBProject *Prj_ = NULL, boolisRealRun = TRUE)
Definition at line 1085 of file SbGeoParameter.C'.
References ClassName(), SBParameterList::clear(), SBStochParameterList::clear(), SBLog::CONFIG, SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, Global, IsGlobalModified, IsLocalModified, IsModified, IsStochasticModified, loadGlbPar(), loadStatistics(), Local, Log, SBNamed::name(), SBSetUp::path2Output(), SBSetUp::path2Sols(), Prj, SBLog::RUN, SBVersion::selfName(), SBNamed::setName(), SetUp, Stat4CurrentBatch, StatByBatch, StatGeneral, StatisticsFile, Stochastic, Version, and SBLog::write().
SBSolution::~SBSolution ()
Definition at line 1152 of file SbGeoParameter.C'.
References IsGlobalModified, IsModified, saveGlbPar(), saveStatistics(), Stat4CurrentBatch, and StatByBatch.
Member Function Documentation
bool SBSolution::checkPath (const QString &Path, const QString &File) [private]
Definition at line 1179 of file SbGeoParameter.C'.
References ClassName(), SBLog::CONFIG, SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, Log, SBVersion::selfName(), Version, and SBLog::write().
Referenced by dumpParameters(), loadGlbCor(), loadGlbPar(), loadLocCor(), loadLocPar(), loadNormalEqs(), loadStatistics(), and loadStcPar().
QString SBSolution::ClassName () const [inline]
Definition at line 901 of file SbGeoParameter.H'.
Referenced by checkPath(), deleteSolution(), dumpParameters(), loadGlbCor(), loadGlbPar(), loadLocCor(), loadLocPar(), loadNormalEqs(), loadStatistics(), loadStcPar(), saveGlbCor(), saveGlbPar(), saveLocCor(), saveLocPar(), saveNormalEqs(), saveStatistics(), saveStcPar(), and SBSolution().
void SBSolution::deleteSolution ()
Definition at line 1725 of file SbGeoParameter.C'.
References ClassName(), SBStatistics::clearStatistics(), SBLog::ERR, SBLog::ESTIMATOR, SBLog::IO, loadStatistics(), Log, SBNamed::name(), path2GlbDir(), path2GlbFile(), path2GlbFileCorr(), path2LocDir(), path2LocFile(), path2LocFileCorr(), path2LocFileNormEqs(), SBSetUp::path2Sols(), path2StcDir(), path2StcFile(), Prj, SetUp, StatByBatch, StatGeneral, StatisticsFile, and SBLog::write().
Referenced by SBVLBIPreProcess::clearPars(), SBProjectCreate::createProject(), SBVLBIPreProcess::currentSesChange(), SBMainWindow::ExecuteDrop(), and SBVLBIPreProcess::~SBVLBIPreProcess().
void SBSolution::dumpParameters ()
Definition at line 1861 of file SbGeoParameter.C'.
References SBStochParameter::addPar(), checkPath(), ClassName(), SBStochParameterList::clear(), SBLog::DBG, SBStochParameter::dump2File(), SBLog::ESTIMATOR, SBMJD::F_MJD, SBStochParameterList::find(), guessParameterName(), SBStochParameterList::inSort(), SBStationID::isValidStr(), Local, Log, SBVersion::name(), SBNamed::name(), SBSetUp::path2Output(), prepare4Batch(), Prj, SetUp, StatByBatch, Stochastic, SBStochParameter::tFinis(), TInf, SBMJD::toString(), SBStochParameter::tStart(), TZero, Version, and SBLog::write().
Referenced by SBSolutionBrowser::dumpSolution().
void SBSolution::getGlobalParameter4Report (SBParameter *P)
Definition at line 1711 of file SbGeoParameter.C'.
References SBParameter::e(), SBParameterList::find(), Global, SBNamed::name(), SBParameter::setE(), SBDerivation::setTimes(), SBParameter::setV(), and SBParameter::v().
Referenced by SBSource::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), and SBStation::getGlobalParameters4UpdateTRF().
SBParameterList& SBSolution::global () [inline]"Returns the list of global parameters'.
Definition at line 912 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), and SBSolutionBrowser::wGlobalPars().
QString SBSolution::guessParameterName (const QString &ParName)
Definition at line 1789 of file SbGeoParameter.C'.
References SBObjectObsInfo::aka(), SBStationInfoList::find(), SBStationID::isValidStr(), Prj, SBStationID::setID(), SBProject::stationList(), and SBStationID::toString().
Referenced by dumpParameters().
bool SBSolution::isLocalModified () const [inline]
Definition at line 942 of file SbGeoParameter.H'.
bool SBSolution::loadGlbCor (SBParameterList *&List, SBSymMatrix *&P)
Definition at line 1274 of file SbGeoParameter.C'.
References checkPath(), ClassName(), SBParameterList::clear(), SBFCList::close(), SBLog::DBG, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Log, SBFCList::open4In(), path2GlbDir(), path2GlbFileCorr(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by SBRunManager::makeReportCRF(), operator<<(), and SBSolutionBrowser::updateCRF().
bool SBSolution::loadGlbPar () [private]
Definition at line 1248 of file SbGeoParameter.C'.
References checkPath(), ClassName(), SBParameterList::clear(), SBFCList::close(), SBLog::DBG, SBLog::ESTIMATOR, SBSetUp::fcList(), Global, SBLog::IO, Log, SBFCList::open4In(), path2GlbDir(), path2GlbFile(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by SBSolution().
bool SBSolution::loadLocCor (const QString &BatchName, SBParameterList *&List, SBSymMatrix *&P)
Definition at line 1343 of file SbGeoParameter.C'.
References checkPath(), ClassName(), SBParameterList::clear(), SBFCList::close(), SBLog::DBG, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Log, SBFCList::open4In(), path2LocDir(), path2LocFileCorr(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportEOP().
bool SBSolution::loadLocPar (const QString &BatchName) [private]
Definition at line 1317 of file SbGeoParameter.C'.
References checkPath(), ClassName(), SBParameterList::clear(), SBFCList::close(), SBLog::DBG, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Local, Log, SBFCList::open4In(), path2LocDir(), path2LocFile(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by prepare4Batch().
void SBSolution::loadNormalEqs (SBParameterList *&Ys, SBVector *&Zy, SBUpperMatrix *&Ry, SBParameterList *&Xs, SBVector *&Zx, SBUpperMatrix *&Rx, SBMatrix *&Rxy, const QString &BatchName)
Definition at line 2142 of file SbGeoParameter.C'.
References checkPath(), ClassName(), SBParameterList::clear(), SBFCList::close(), SBLog::DBG, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Log, SBFCList::open4In(), path2LocDir(), path2LocFileNormEqs(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by SBRunManager::makeReportNormalEqs().
void SBSolution::loadStatistics () [private]
Definition at line 1219 of file SbGeoParameter.C'.
References checkPath(), ClassName(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBLog::IO, Log, SBNamed::name(), SBSetUp::path2Sols(), Prj, SetUp, StatByBatch, StatGeneral, StatisticsFile, SBLog::write(), and SBLog::WRN.
Referenced by deleteSolution(), and SBSolution().
bool SBSolution::loadStcPar (const QString &BatchName) [private]
Definition at line 1379 of file SbGeoParameter.C'.
References checkPath(), ClassName(), SBStochParameterList::clear(), SBFCList::close(), SBLog::DBG, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Log, SBFCList::open4In(), path2StcDir(), path2StcFile(), SetUp, Stochastic, SBLog::write(), and SBLog::WRN.
Referenced by prepare4Batch().
SBParameterList& SBSolution::local () [inline]"Returns the list of curent local parameters'.
Definition at line 914 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTRFVariations(), SBVLBIPreProcess::preProcess(), and SBVLBIPreProcess::procScenario_2().
QString SBSolution::path2GlbDir () const [private]
Definition at line 1162 of file SbGeoParameter.C'.
References DirGlobal, SBNamed::name(), SBSetUp::path2Sols(), Prj, and SetUp.
Referenced by deleteSolution(), loadGlbCor(), and loadGlbPar().
QString SBSolution::path2GlbFile () const [inline, private]
Definition at line 872 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadGlbPar(), and saveGlbPar().
QString SBSolution::path2GlbFileCorr () const [inline, private]
Definition at line 875 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadGlbCor(), and saveGlbCor().
QString SBSolution::path2LocDir () const [private]
Definition at line 1167 of file SbGeoParameter.C'.
References DirLocal, SBNamed::name(), SBSetUp::path2Sols(), Prj, and SetUp.
Referenced by deleteSolution(), loadLocCor(), loadLocPar(), and loadNormalEqs().
QString SBSolution::path2LocFile (const QString &name_) const [inline, private]
Definition at line 878 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadLocPar(), and saveLocPar().
QString SBSolution::path2LocFileCorr (const QString &name_) const [inline, private]
Definition at line 881 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadLocCor(), and saveLocCor().
QString SBSolution::path2LocFileNormEqs (const QString &name_) const [inline, private]
Definition at line 890 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadNormalEqs(), and saveNormalEqs().
QString SBSolution::path2StcDir () const [private]
Definition at line 1174 of file SbGeoParameter.C'.
References DirStoch, SBNamed::name(), SBSetUp::path2Sols(), Prj, and SetUp.
Referenced by deleteSolution(), and loadStcPar().
QString SBSolution::path2StcFile (const QString &name_) const [inline, private]
Definition at line 884 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadStcPar(), and saveStcPar().
void SBSolution::prepare4Batch (const QString &BatchName, boolIsRealRun = FALSE)
Definition at line 1564 of file SbGeoParameter.C'.
References SBStatistics::clearStatistics(), CurrentBatch, loadLocPar(), loadStcPar(), Stat4CurrentBatch, and StatByBatch.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), dumpParameters(), SBVLBIPreProcess::fillObsListView(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBRunManager::process_m1(), and SBEstimator::solveLocals().
SBProject* SBSolution::project () const [inline]"Returns project'.
Definition at line 906 of file SbGeoParameter.H'.
void SBSolution::reportGlobalParameters ()
Definition at line 1606 of file SbGeoParameter.C'.
References Global, and SBParameterList::report().
Referenced by SBEstimator::solveGlobals().
void SBSolution::reportLocalParameters ()
Definition at line 1639 of file SbGeoParameter.C'.
References Local, and SBParameterList::report().
Referenced by SBEstimator::solveLocals().
void SBSolution::reportStochasticParameters ()
Definition at line 1669 of file SbGeoParameter.C'.
References SBStochParameterList::report(), and Stochastic.
Referenced by SBEstimator::solveStochs().
void SBSolution::saveGlbCor (SBParameterList *List, const SBSymMatrix *P_GLB) [private]
Definition at line 1452 of file SbGeoParameter.C'.
References ClassName(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Log, SBFCList::open4Out(), path2GlbFileCorr(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by submitGlobalParameters().
void SBSolution::saveGlbPar () [private]
Definition at line 1425 of file SbGeoParameter.C'.
References ClassName(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), Global, SBLog::IO, IsGlobalModified, Log, SBFCList::open4Out(), path2GlbFile(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by ~SBSolution().
void SBSolution::saveLocCor (const QString &BatchName, SBParameterList *List, const SBSymMatrix *P_LOC) [private]
Definition at line 1511 of file SbGeoParameter.C'.
References ClassName(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Log, SBFCList::open4Out(), path2LocFileCorr(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by submitLocalParameters().
void SBSolution::saveLocPar (const QString &BatchName) [private]
Definition at line 1484 of file SbGeoParameter.C'.
References ClassName(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, IsLocalModified, Local, Log, SBFCList::open4Out(), path2LocFile(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by submitLocalParameters().
void SBSolution::saveNormalEqs (SBParameterList *Ys, SBVector *Zy, SBUpperMatrix *Ry, SBParameterList *Xs, SBVector *Zx, SBUpperMatrix *Rx, SBMatrix *Rxy, const QString &BatchName)
Definition at line 2110 of file SbGeoParameter.C'.
References ClassName(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, Log, SBFCList::open4Out(), path2LocFileNormEqs(), SetUp, SBLog::write(), and SBLog::WRN.
Referenced by SBEstimator::finisLocal().
void SBSolution::saveStatistics () [private]
Definition at line 1406 of file SbGeoParameter.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBLog::IO, Log, StatByBatch, StatGeneral, StatisticsFile, and SBLog::write().
Referenced by ~SBSolution().
void SBSolution::saveStcPar (const QString &BatchName) [private]
Definition at line 1537 of file SbGeoParameter.C'.
References ClassName(), SBFCList::close(), SBLog::DBG, SBLog::ERR, SBLog::ESTIMATOR, SBSetUp::fcList(), SBLog::IO, IsStochasticModified, Log, SBFCList::open4Out(), path2StcFile(), SetUp, Stochastic, SBLog::write(), and SBLog::WRN.
void SBSolution::saveStochasticParameters () [inline]
Definition at line 929 of file SbGeoParameter.H'.
Referenced by SBEstimator::solveStochs().
void SBSolution::setIsLocalModified (boolIsModified_) [inline]
Definition at line 943 of file SbGeoParameter.H'.
Referenced by SBVLBIPreProcess::preProcess().
void SBSolution::setProject (SBProject *constP_) [inline]"Sets up the project'.
Definition at line 919 of file SbGeoParameter.H'.
SBStatistics* SBSolution::stat4CurrentBatch () [inline]
Definition at line 937 of file SbGeoParameter.H'.
Referenced by SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBRunManager::process_m1(), SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBEstimator::processObs(), SBEstimator::solveLocals(), and writeNormalEquationSystem().
SBStatisticsList& SBSolution::statByBatch () [inline]"Returns the list of statistics per batch'.
Definition at line 910 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBSolutionBrowser::wGeneralInfo(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), and SBSolutionBrowser::wStochStPars().
SBStatistics* SBSolution::statGeneral () [inline]"Returns general statistics'.
Definition at line 908 of file SbGeoParameter.H'.
Referenced by SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), operator<<(), SBRunManager::prepare4Run_m1(), SBRunManager::process_m1(), SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBEstimator::processObs(), and SBSolutionBrowser::wGeneralInfo().
SBStochParameterList& SBSolution::stochastic () [inline]"Returns the list of curent stochastic parameters'.
Definition at line 916 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBVLBIPreProcess::fillObsListView(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), and SBRunManager::makeReportTRFVariations().
void SBSolution::submitGlobalParameters (SBParameterList *List, const SBSymMatrix *P)
Definition at line 1581 of file SbGeoParameter.C'.
References SBParameterList::find(), Global, SBParameterList::inSort(), IsGlobalModified, IsModified, SBNamed::name(), SBParameter::s(), saveGlbCor(), SBParameter::setV(), SBParameter::update(), and SBParameter::v().
Referenced by SBEstimator::solveGlobals().
void SBSolution::submitLocalParameters (SBParameterList *List, const SBSymMatrix *P)
Definition at line 1611 of file SbGeoParameter.C'.
References CurrentBatch, SBParameterList::find(), SBParameterList::inSort(), IsLocalModified, IsModified, Local, SBNamed::name(), SBParameter::s(), saveLocCor(), saveLocPar(), SBParameter::setV(), and SBParameter::update().
Referenced by SBVLBIPreProcess::preProcess(), and SBEstimator::solveLocals().
void SBSolution::submitStochasticParameters (SBParameterList *List, const SBSymMatrix *P)
Definition at line 1644 of file SbGeoParameter.C'.
References SBStochParameterList::find(), SBStochParameterList::inSort(), IsModified, IsStochasticModified, SBNamed::name(), SBParameter::scale(), Stochastic, and SBStochParameter::update().
Referenced by SBEstimator::solveStochs().
void SBSolution::updateParameter (SBParameter *P, const SBMJD &T, boolIsRealRun = TRUE)
Definition at line 1674 of file SbGeoParameter.C'.
References SBParameter::e(), SBStochParameter::e(), SBParameterList::find(), SBStochParameterList::find(), Global, Local, SBNamed::name(), SBDerivation::num(), SBStochParameter::num(), SBParameter::setE(), SBDerivation::setNum(), SBDerivation::setTimes(), SBParameter::setV(), Stochastic, SBParameter::v(), and SBStochParameter::v().
Referenced by SBSource::updateParameters(), SBEOP::updateParameters(), and SBStation::updateParameters().
Member Data Documentation
QString SBSolution::CurrentBatch [private]
Definition at line 840 of file SbGeoParameter.H'.
Referenced by prepare4Batch(), and submitLocalParameters().
const QString SBSolution::DirArc [static, private]
Definition at line 847 of file SbGeoParameter.H'.
const QString SBSolution::DirGlobal [static, private]
Definition at line 846 of file SbGeoParameter.H'.
Referenced by path2GlbDir().
const QString SBSolution::DirLocal [static, private]
Definition at line 848 of file SbGeoParameter.H'.
Referenced by path2LocDir().
const QString SBSolution::DirStoch [static, private]
Definition at line 849 of file SbGeoParameter.H'.
Referenced by path2StcDir().
SBParameterList SBSolution::Global [private]
list of global parameters;
Definition at line 833 of file SbGeoParameter.H'.
Referenced by getGlobalParameter4Report(), loadGlbPar(), reportGlobalParameters(), saveGlbPar(), SBSolution(), submitGlobalParameters(), and updateParameter().
bool SBSolution::IsGlobalModified [private]
Definition at line 834 of file SbGeoParameter.H'.
Referenced by saveGlbPar(), SBSolution(), submitGlobalParameters(), and ~SBSolution().
bool SBSolution::IsLocalModified [private]
Definition at line 839 of file SbGeoParameter.H'.
Referenced by saveLocPar(), SBSolution(), and submitLocalParameters().
bool SBSolution::IsModified [private]
Definition at line 828 of file SbGeoParameter.H'.
Referenced by SBSolution(), submitGlobalParameters(), submitLocalParameters(), submitStochasticParameters(), and ~SBSolution().
bool SBSolution::IsStochasticModified [private]
Definition at line 844 of file SbGeoParameter.H'.
Referenced by saveStcPar(), SBSolution(), and submitStochasticParameters().
SBParameterList SBSolution::Local [private]
list of local parameters;
Definition at line 838 of file SbGeoParameter.H'.
Referenced by dumpParameters(), loadLocPar(), reportLocalParameters(), saveLocPar(), SBSolution(), submitLocalParameters(), and updateParameter().
SBProject* SBSolution::Prj [private]
project (not an owner of);
Definition at line 825 of file SbGeoParameter.H'.
Referenced by deleteSolution(), dumpParameters(), guessParameterName(), loadStatistics(), path2GlbDir(), path2LocDir(), path2StcDir(), and SBSolution().
SBStatistics* SBSolution::Stat4CurrentBatch [private]
Definition at line 829 of file SbGeoParameter.H'.
Referenced by prepare4Batch(), SBSolution(), and ~SBSolution().
SBStatisticsList SBSolution::StatByBatch [private]
list of statistics info per a batch
Definition at line 827 of file SbGeoParameter.H'.
Referenced by deleteSolution(), dumpParameters(), loadStatistics(), prepare4Batch(), saveStatistics(), SBSolution(), and ~SBSolution().
SBStatistics SBSolution::StatGeneral [private]
general statistics information
Definition at line 826 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadStatistics(), saveStatistics(), and SBSolution().
QString SBSolution::StatisticsFile [private]
Definition at line 830 of file SbGeoParameter.H'.
Referenced by deleteSolution(), loadStatistics(), saveStatistics(), and SBSolution().
SBStochParameterList SBSolution::Stochastic [private]
list of stochastic parameters;
Definition at line 843 of file SbGeoParameter.H'.
Referenced by dumpParameters(), loadStcPar(), reportStochasticParameters(), saveStcPar(), SBSolution(), submitStochasticParameters(), and updateParameter().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.