SBSource
NAME
SBSource -
SYNOPSIS
#include <SbGeoSources.H>
Inherits SBNamed, and SBAttributed'.
Public Types
enum SStatus { STATUS_DEF, STATUS_CAND, STATUS_OTHER, STATUS_NEW, STATUS_UNKN }
enum SType { TYPE_QUASAR, TYPE_GALAXY, TYPE_BL_LAC, TYPE_BL_LAC_C, TYPE_OTHER, TYPE_UNKN }
enum SSpectrumClass { SP_SEYFERT, SP_SEYFERT1, SP_SEYFERT1_2, SP_SEYFERT2, SP_SEYFERT3, SP_HP, SP_OTHER, SP_UNKN }
enum Attributes { OrigImported = 1<<0, OrigEdited = 1<<1, OrigObsData = 1<<2, OrigEstimated = 1<<3, StatusSuspected = 1<<4, Analysed = 1<<5, AnalysConstr = 1<<6, Reserved_08 = 1<<7, Reserved_09 = 1<<8, Reserved_10 = 1<<9, Reserved_11 = 1<<10, Reserved_12 = 1<<11, Reserved_13 = 1<<12, Reserved_14 = 1<<13, Reserved_15 = 1<<14, Reserved_16 = 1<<15, Reserved_17 = 1<<16 }
Public Member Functions
SBSource (const QString &='0000+000', double=0.0, double=0.0)
SBSource (const SBSource &)
virtual ~SBSource ()
virtual QString ClassName () const
virtual SBSource & operator= (const SBSource &)
double ra () const
double dn () const
double ra_t () const
double dn_t () const
double ra_err () const
double dn_err () const
QString ICRFName () const
QString obsName () const
SStatus status () const
SType type () const
SSpectrumClass spectrum () const
float redShift () const
float flux1 () const
float flux2 () const
float spIdx () const
float mv () const
int nObsApr () const
int nSessApr () const
const SBMJD & meanMJD () const
const SBMJD & firstMJD () const
const SBMJD & lastMJD () const
double corrRA_DN () const
bool isHLink () const
int structIdxX () const
int structIdxS () const
SBParameter * p_RA ()
SBParameter * p_DN ()
QList< QString > * aliasesList ()
void clearAliasesList ()
void setRA (double RA_)
void setDN (double DN_)
void setRA_err (double dRA_)
void setDN_err (double dDN_)
void setICRFName (const QString &ICRF_)
void setObsName (const QString &ObsN_)
void setStatus (SStatus Status_)
void setType (SType Type_)
void setSpectrum (SSpectrumClass Sp_)
void setRedShift (float RedShift_)
void setFlux1 (float Flux1_)
void setFlux2 (float Flux2_)
void setSpIdx (float SpIdx_)
void setMv (float Mv_)
void setNObsApr (int NObsApr_)
void setNSessApr (int NSessApr_)
void setMeanMJD (const SBMJD &aMJD_)
void setFirstMJD (const SBMJD &aMJD_)
void setLastMJD (const SBMJD &aMJD_)
void setCorrRA_DN (double RA_DN_)
void setIsHLink (bool IsHLink_)
void setStructIdxX (int Idx_)
void setStructIdxS (int Idx_)
const QString & sinexCharID () const
void setSINEXCharID (const QString &S_)
void createParameters ()
void releaseParameters ()
void updateParameters (SBRunManager *, const SBMJD &, bool=TRUE)
void getGlobalParameters4Report (SBRunManager *)
void getParameters4Report (SBRunManager *)
QString RA2str () const
QString DN2str () const
virtual Vector3 rt () const
const QString & name () const
void setName (const QString &Name_)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Static Public Member Functions
static bool isValidICRFName (QString)
Protected Attributes
QString Name
Private Attributes
double RA
double dRA
double DN
double dDN
QString ICRF
QString ObsName
SStatus Status
SType Type
SSpectrumClass SpectrumClass
bool IsHLink
float RedShift
float Flux1
float Flux2
float SpIdx
float Mv
int NObsApr
int NSessApr
SBMJD MeanMJD
SBMJD FirstMJD
SBMJD LastMJD
double RA_DN
int StructIdxX
int StructIdxS
QList< QString > * aList
SBParameter * P_RA
estimation of the right ascension;
SBParameter * P_DN
estimation of the declination;
double RAt
double DNt
QString SINEXCharID
Friends
class SB_CRF
SBTS_dico & operator<< (SBTS_dico &, SB_CRF &)
QDataStream & operator<< (QDataStream &, const SBSource &)
QDataStream & operator>> (QDataStream &, SBSource &)
SBTS_rsc & operator<< (SBTS_rsc &, const SBSource &)
SBTS_rsc & operator>> (SBTS_rsc &, SBSource &)
SBTS_car & operator<< (SBTS_car &, const SBSource &)
SBTS_car & operator>> (SBTS_car &, SBSource &)
SBTS_report & operator<< (SBTS_report &, const SBSource &)
SBTS_report4IVS & operator<< (SBTS_report4IVS &, const SBSource &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Definition at line 80 of file SbGeoSources.H'.
Member Enumeration Documentation
enum SBSource::Attributes
Enumerator:
OrigImported
Info origin: imported;'.
OrigEdited
Info origin: has been edited (alterated by hand);'.
OrigObsData
Info origin: from obs data files;'.
OrigEstimated
Info origin: has been estimated;'.
StatusSuspected
a la `substatus': "indicates that the source is suspected to be not suitable to define the axes in the future
Analysed
temporary attr;
AnalysConstr
the coordinates of a source were used in constraint equations;
Reserved_08
reserved;
Reserved_09
reserved;
Reserved_10
reserved;
Reserved_11
reserved;
Reserved_12
reserved;
Reserved_13
reserved;
Reserved_14
reserved;
Reserved_15
reserved;
Reserved_16
reserved;
Reserved_17
reserved;
Definition at line 92 of file SbGeoSources.H'.
enum SBSource::SSpectrumClass
Enumerator:
SP_SEYFERT
SP_SEYFERT1
SP_SEYFERT1_2
SP_SEYFERT2
SP_SEYFERT3
SP_HP
SP_OTHER
SP_UNKN
Definition at line 89 of file SbGeoSources.H'.
enum SBSource::SStatus
Enumerator:
STATUS_DEF
STATUS_CAND
STATUS_OTHER
STATUS_NEW
STATUS_UNKN
Definition at line 86 of file SbGeoSources.H'.
enum SBSource::SType
Enumerator:
TYPE_QUASAR
TYPE_GALAXY
TYPE_BL_LAC
TYPE_BL_LAC_C
TYPE_OTHER
TYPE_UNKN
Definition at line 87 of file SbGeoSources.H'.
Constructor & Destructor Documentation
SBSource::SBSource (const QString &Name_ = '0000+000', doubleRA_ = 0.0, doubleDN_ = 0.0)
Definition at line 38 of file SbGeoSources.C'.
References aList, dDN, DEG2RAD, DN, DNt, dRA, FirstMJD, Flux1, Flux2, HR2RAD, ICRF, IsHLink, LastMJD, MeanMJD, Mv, NObsApr, NSessApr, ObsName, P_DN, P_RA, RA, RA_DN, RAt, RedShift, SINEXCharID, SP_UNKN, SpectrumClass, SpIdx, Status, STATUS_UNKN, StructIdxS, StructIdxX, Type, and TYPE_UNKN.
SBSource::SBSource (const SBSource &S)
Definition at line 73 of file SbGeoSources.C'.
References aList, dDN, DN, DNt, dRA, FirstMJD, Flux1, Flux2, ICRF, IsHLink, LastMJD, MeanMJD, Mv, NObsApr, NSessApr, ObsName, P_DN, P_RA, RA, RA_DN, RAt, RedShift, SINEXCharID, SpectrumClass, SpIdx, Status, StructIdxS, StructIdxX, and Type.
virtual SBSource::~SBSource () [inline, virtual]
Definition at line 153 of file SbGeoSources.H'.
References aList.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
QList<QString>* SBSource::aliasesList () [inline]
Definition at line 187 of file SbGeoSources.H'.
References aList.
Referenced by SBSourceEditor::wCoordinates().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBSource::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBAttributed'.
Definition at line 154 of file SbGeoSources.H'.
void SBSource::clearAliasesList () [inline]
Definition at line 188 of file SbGeoSources.H'.
References aList.
Referenced by SB_CRF::releaseObjAliases().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
double SBSource::corrRA_DN () const [inline]
Definition at line 179 of file SbGeoSources.H'.
References RA_DN.
Referenced by SBSourceEditor::acquireData(), operator<<(), and SBSourceEditor::wCoordinates().
void SBSource::createParameters ()
Definition at line 180 of file SbGeoSources.C'.
References SBNamed::name(), P_DN, and P_RA.
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
double SBSource::dn () const [inline]
Definition at line 159 of file SbGeoSources.H'.
References DN.
Referenced by SBSourceEditor::acquireData(), SBRunManager::constraintSourceCoord(), SBSourceImport::importICRF(), SBSourceListItem::key(), SB_CRF::lookupNearest(), SBRunManager::makeReportCRFVariations(), and SBSourceEditor::wCoordinates().
QString SBSource::DN2str () const
Definition at line 264 of file SbGeoSources.C'.
References DNt, and rad2dms().
Referenced by SBSourceListItem::text().
double SBSource::dn_err () const [inline]
Definition at line 163 of file SbGeoSources.H'.
References dDN.
Referenced by SBSourceEditor::acquireData(), SBSourceImport::importICRF(), SBSourceListItem::key(), operator<<(), SBSourceListItem::text(), and SBSourceEditor::wCoordinates().
double SBSource::dn_t () const [inline]
Definition at line 161 of file SbGeoSources.H'.
References DNt.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), operator<<(), rt(), and SBSolutionBrowser::updateCRF().
const SBMJD& SBSource::firstMJD () const [inline]
Definition at line 177 of file SbGeoSources.H'.
References FirstMJD.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), operator<<(), SBSourceListItem::text(), and SBSourceEditor::wStats().
float SBSource::flux1 () const [inline]
Definition at line 170 of file SbGeoSources.H'.
References Flux1.
Referenced by SBSourceEditor::acquireData(), operator<<(), and SBSourceEditor::wPhysChars().
float SBSource::flux2 () const [inline]
Definition at line 171 of file SbGeoSources.H'.
References Flux2.
Referenced by SBSourceEditor::acquireData(), operator<<(), and SBSourceEditor::wPhysChars().
void SBSource::getGlobalParameters4Report (SBRunManager *Mgr)
Definition at line 218 of file SbGeoSources.C'.
References dDN, DN, DNt, dRA, SBParameter::e(), FirstMJD, SBSolution::getGlobalParameter4Report(), LastMJD, MeanMJD, NObsApr, NSessApr, SBDerivation::num(), SBDerivation::numSes(), P_DN, P_RA, RA, RA_DN, RAt, SBRunManager::solution(), SBDerivation::tEpoch(), SBDerivation::tFinis(), SBDerivation::tStart(), and SBParameter::v().
Referenced by SBRunManager::makeReportCRF(), and SBSolutionBrowser::updateCRF().
void SBSource::getParameters4Report (SBRunManager *Mgr)
Definition at line 239 of file SbGeoSources.C'.
References dDN, dRA, SBParameter::e(), FirstMJD, LastMJD, MeanMJD, NObsApr, NSessApr, SBDerivation::num(), SBDerivation::numSes(), P_DN, P_RA, RA_DN, SBDerivation::tEpoch(), SBDerivation::tFinis(), SBDerivation::tStart(), TZero, and updateParameters().
Referenced by SBRunManager::makeReportCRFVariations4IVS().
QString SBSource::ICRFName () const [inline]
Definition at line 164 of file SbGeoSources.H'.
References ICRF.
Referenced by SBSourceEditor::acquireData(), operator>>(), and SBSourceEditor::wCoordinates().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
bool SBSource::isHLink () const [inline]
Definition at line 180 of file SbGeoSources.H'.
References IsHLink.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), operator<<(), SBSourceListItem::pixmap(), and SBSourceEditor::wCoordinates().
bool SBSource::isValidICRFName (QStringsICRF) [static]
Definition at line 149 of file SbGeoSources.C'.
Referenced by SBSourceEditor::acquireData(), and operator>>().
const SBMJD& SBSource::lastMJD () const [inline]
Definition at line 178 of file SbGeoSources.H'.
References LastMJD.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), operator<<(), SBSourceListItem::text(), and SBSourceEditor::wStats().
const SBMJD& SBSource::meanMJD () const [inline]
Definition at line 176 of file SbGeoSources.H'.
References MeanMJD.
Referenced by SBSourceEditor::acquireData(), operator<<(), and SBSourceEditor::wStats().
float SBSource::mv () const [inline]
Definition at line 173 of file SbGeoSources.H'.
References Mv.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), operator<<(), SBSourceListItem::text(), and SBSourceEditor::wPhysChars().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
int SBSource::nObsApr () const [inline]
Definition at line 174 of file SbGeoSources.H'.
References NObsApr.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), operator<<(), SBSourceListItem::text(), and SBSourceEditor::wStats().
int SBSource::nSessApr () const [inline]
Definition at line 175 of file SbGeoSources.H'.
References NSessApr.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), operator<<(), SBSourceListItem::text(), and SBSourceEditor::wStats().
QString SBSource::obsName () const [inline]
Definition at line 165 of file SbGeoSources.H'.
References ObsName.
SBSource & SBSource::operator= (const SBSource &S) [virtual]
Definition at line 108 of file SbGeoSources.C'.
References aList, dDN, DN, DNt, dRA, FirstMJD, Flux1, Flux2, ICRF, IsHLink, LastMJD, MeanMJD, Mv, NObsApr, NSessApr, ObsName, P_DN, P_RA, RA, RA_DN, RAt, RedShift, releaseParameters(), SINEXCharID, SpectrumClass, SpIdx, Status, StructIdxS, StructIdxX, and Type.
SBParameter* SBSource::p_DN () [inline]
Definition at line 185 of file SbGeoSources.H'.
References P_DN.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintSourceCoord(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::process_m1(), and SBSolutionBrowser::updateCRF().
SBParameter* SBSource::p_RA () [inline]
Definition at line 184 of file SbGeoSources.H'.
References P_RA.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintSourceCoord(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::process_m1(), and SBSolutionBrowser::updateCRF().
double SBSource::ra () const [inline]
Definition at line 158 of file SbGeoSources.H'.
References RA.
Referenced by SBSourceEditor::acquireData(), SBRunManager::constraintSourceCoord(), SBSourceImport::importICRF(), SBSourceListItem::key(), SB_CRF::lookupNearest(), SBRunManager::makeReportCRFVariations(), and SBSourceEditor::wCoordinates().
QString SBSource::RA2str () const
Definition at line 255 of file SbGeoSources.C'.
References rad2hms(), and RAt.
Referenced by SBSourceListItem::text().
double SBSource::ra_err () const [inline]
Definition at line 162 of file SbGeoSources.H'.
References dRA.
Referenced by SBSourceEditor::acquireData(), SBSourceImport::importICRF(), SBSourceListItem::key(), operator<<(), SBSourceListItem::text(), and SBSourceEditor::wCoordinates().
double SBSource::ra_t () const [inline]
Definition at line 160 of file SbGeoSources.H'.
References RAt.
Referenced by SBRefraction::altitudeCorr(), SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), operator<<(), rt(), and SBSolutionBrowser::updateCRF().
float SBSource::redShift () const [inline]
Definition at line 169 of file SbGeoSources.H'.
References RedShift.
Referenced by SBSourceEditor::acquireData(), operator<<(), and SBSourceEditor::wPhysChars().
void SBSource::releaseParameters ()
Definition at line 191 of file SbGeoSources.C'.
References P_DN, and P_RA.
Referenced by operator=().
virtual Vector3 SBSource::rt () const [inline, virtual]
Definition at line 230 of file SbGeoSources.H'.
References dn_t(), ra_t(), and sincos().
Referenced by SBDelay::calc().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBSource::setCorrRA_DN (doubleRA_DN_) [inline]
Definition at line 209 of file SbGeoSources.H'.
References RA_DN.
Referenced by SBSourceEditor::acquireData(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), operator>>(), and SBSolutionBrowser::updateCRF().
void SBSource::setDN (doubleDN_) [inline]
Definition at line 191 of file SbGeoSources.H'.
References DN.
Referenced by SBSourceEditor::acquireData(), SBSourceImport::importICRF(), operator>>(), and SBSolutionBrowser::updateCRF().
void SBSource::setDN_err (doubledDN_) [inline]
Definition at line 193 of file SbGeoSources.H'.
References dDN.
Referenced by SBSourceEditor::acquireData(), SBSourceImport::importICRF(), and operator>>().
void SBSource::setFirstMJD (const SBMJD &aMJD_) [inline]
Definition at line 207 of file SbGeoSources.H'.
References FirstMJD.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setFlux1 (floatFlux1_) [inline]
Definition at line 200 of file SbGeoSources.H'.
References Flux1.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setFlux2 (floatFlux2_) [inline]
Definition at line 201 of file SbGeoSources.H'.
References Flux2.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setICRFName (const QString &ICRF_) [inline]
Definition at line 194 of file SbGeoSources.H'.
References ICRF.
Referenced by SBSourceEditor::acquireData().
void SBSource::setIsHLink (boolIsHLink_) [inline]
Definition at line 210 of file SbGeoSources.H'.
References IsHLink.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setLastMJD (const SBMJD &aMJD_) [inline]
Definition at line 208 of file SbGeoSources.H'.
References LastMJD.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setMeanMJD (const SBMJD &aMJD_) [inline]
Definition at line 206 of file SbGeoSources.H'.
References MeanMJD.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setMv (floatMv_) [inline]
Definition at line 203 of file SbGeoSources.H'.
References Mv.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBSource::setNObsApr (intNObsApr_) [inline]
Definition at line 204 of file SbGeoSources.H'.
References NObsApr.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setNSessApr (intNSessApr_) [inline]
Definition at line 205 of file SbGeoSources.H'.
References NSessApr.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setObsName (const QString &ObsN_) [inline]
Definition at line 195 of file SbGeoSources.H'.
References ObsName.
void SBSource::setRA (doubleRA_) [inline]
Definition at line 190 of file SbGeoSources.H'.
References RA.
Referenced by SBSourceEditor::acquireData(), SBSourceImport::importICRF(), operator>>(), and SBSolutionBrowser::updateCRF().
void SBSource::setRA_err (doubledRA_) [inline]
Definition at line 192 of file SbGeoSources.H'.
References dRA.
Referenced by SBSourceEditor::acquireData(), SBSourceImport::importICRF(), and operator>>().
void SBSource::setRedShift (floatRedShift_) [inline]
Definition at line 199 of file SbGeoSources.H'.
References RedShift.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setSINEXCharID (const QString &S_) [inline]
Definition at line 216 of file SbGeoSources.H'.
References SINEXCharID.
Referenced by collectListOfSINEXParameters4NEQ().
void SBSource::setSpectrum (SSpectrumClassSp_) [inline]
Definition at line 198 of file SbGeoSources.H'.
References SpectrumClass.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setSpIdx (floatSpIdx_) [inline]
Definition at line 202 of file SbGeoSources.H'.
References SpIdx.
Referenced by SBSourceEditor::acquireData(), and operator>>().
void SBSource::setStatus (SStatusStatus_) [inline]
Definition at line 196 of file SbGeoSources.H'.
References Status.
Referenced by SBSourceEditor::acquireData().
void SBSource::setStructIdxS (intIdx_) [inline]
Definition at line 212 of file SbGeoSources.H'.
References StructIdxS.
Referenced by operator>>().
void SBSource::setStructIdxX (intIdx_) [inline]
Definition at line 211 of file SbGeoSources.H'.
References StructIdxX.
Referenced by operator>>().
void SBSource::setType (STypeType_) [inline]
Definition at line 197 of file SbGeoSources.H'.
References Type.
Referenced by SBSourceEditor::acquireData().
const QString& SBSource::sinexCharID () const [inline]
Definition at line 215 of file SbGeoSources.H'.
References SINEXCharID.
Referenced by collectListOfSINEXParameters4NEQ().
SSpectrumClass SBSource::spectrum () const [inline]
Definition at line 168 of file SbGeoSources.H'.
References SpectrumClass.
Referenced by SBSourceEditor::acquireData(), and SBSourceEditor::wPhysChars().
float SBSource::spIdx () const [inline]
Definition at line 172 of file SbGeoSources.H'.
References SpIdx.
Referenced by SBSourceEditor::acquireData(), operator<<(), and SBSourceEditor::wPhysChars().
SStatus SBSource::status () const [inline]
Definition at line 166 of file SbGeoSources.H'.
References Status.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), SBSourceListItem::pixmap(), SBBrowseSources::updateList(), and SBSourceEditor::wCoordinates().
int SBSource::structIdxS () const [inline]
Definition at line 182 of file SbGeoSources.H'.
References StructIdxS.
int SBSource::structIdxX () const [inline]
Definition at line 181 of file SbGeoSources.H'.
References StructIdxX.
SType SBSource::type () const [inline]
Definition at line 167 of file SbGeoSources.H'.
References Type.
Referenced by SBSourceEditor::acquireData(), SBSourceListItem::key(), SBSourceListItem::text(), SBBrowseSources::updateList(), and SBSourceEditor::wPhysChars().
void SBSource::updateParameters (SBRunManager *Mgr, const SBMJD &T, boolIsRealRun = TRUE)
Definition at line 205 of file SbGeoSources.C'.
References DN, DNt, P_DN, P_RA, RA, RAt, SBRunManager::solution(), SBSolution::updateParameter(), and SBParameter::v().
Referenced by collectListOfSINEXParameters4NEQ(), getParameters4Report(), operator<<(), and SBObsVLBIEntry::process().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
SBTS_dico& operator<< (SBTS_dico &s, SB_CRF &CRF) [friend]
Definition at line 1299 of file SbGeoSources.C'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBSource &S) [friend]
Definition at line 281 of file SbGeoSources.C'.
SBTS_rsc& operator<< (SBTS_rsc &s, const SBSource &S) [friend]
Definition at line 441 of file SbGeoSources.C'.
SBTS_car& operator<< (SBTS_car &s, const SBSource &S) [friend]
Definition at line 930 of file SbGeoSources.C'.
SBTS_report& operator<< (SBTS_report &s, const SBSource &S) [friend]
Definition at line 305 of file SbGeoSources.C'.
SBTS_report4IVS& operator<< (SBTS_report4IVS &s, const SBSource &S) [friend]
Definition at line 379 of file SbGeoSources.C'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBSource &S) [friend]
Definition at line 291 of file SbGeoSources.C'.
SBTS_rsc& operator>> (SBTS_rsc &s, SBSource &S) [friend]
Definition at line 494 of file SbGeoSources.C'.
SBTS_car& operator>> (SBTS_car &s, SBSource &S) [friend]
Definition at line 1009 of file SbGeoSources.C'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
friend class SB_CRF [friend]
Definition at line 82 of file SbGeoSources.H'.
Member Data Documentation
QList<QString>* SBSource::aList [private]
Definition at line 139 of file SbGeoSources.H'.
Referenced by aliasesList(), clearAliasesList(), SB_CRF::collectObjAliases(), operator<<(), operator=(), SB_CRF::prepareAliases4Output(), SB_CRF::releaseAliases4Output(), SBSource(), and ~SBSource().
double SBSource::dDN [private]
Definition at line 117 of file SbGeoSources.H'.
Referenced by dn_err(), getGlobalParameters4Report(), getParameters4Report(), operator<<(), operator=(), operator>>(), SBSource(), and setDN_err().
double SBSource::DN [private]
Definition at line 116 of file SbGeoSources.H'.
Referenced by dn(), getGlobalParameters4Report(), operator<<(), operator=(), operator>>(), SBSource(), setDN(), and updateParameters().
double SBSource::DNt [private]
Definition at line 145 of file SbGeoSources.H'.
Referenced by DN2str(), dn_t(), getGlobalParameters4Report(), operator=(), operator>>(), SBSource(), and updateParameters().
double SBSource::dRA [private]
Definition at line 115 of file SbGeoSources.H'.
Referenced by getGlobalParameters4Report(), getParameters4Report(), operator<<(), operator=(), operator>>(), ra_err(), SBSource(), and setRA_err().
SBMJD SBSource::FirstMJD [private]
Definition at line 132 of file SbGeoSources.H'.
Referenced by firstMJD(), getGlobalParameters4Report(), getParameters4Report(), operator<<(), operator=(), operator>>(), SBSource(), and setFirstMJD().
float SBSource::Flux1 [private]
Definition at line 125 of file SbGeoSources.H'.
Referenced by flux1(), operator<<(), operator=(), operator>>(), SBSource(), and setFlux1().
float SBSource::Flux2 [private]
Definition at line 126 of file SbGeoSources.H'.
Referenced by flux2(), operator<<(), operator=(), operator>>(), SBSource(), and setFlux2().
QString SBSource::ICRF [private]
Definition at line 118 of file SbGeoSources.H'.
Referenced by ICRFName(), operator<<(), operator=(), operator>>(), SBSource(), and setICRFName().
bool SBSource::IsHLink [private]
Definition at line 123 of file SbGeoSources.H'.
Referenced by isHLink(), operator<<(), operator=(), operator>>(), SBSource(), and setIsHLink().
SBMJD SBSource::LastMJD [private]
Definition at line 133 of file SbGeoSources.H'.
Referenced by getGlobalParameters4Report(), getParameters4Report(), lastMJD(), operator<<(), operator=(), operator>>(), SBSource(), and setLastMJD().
SBMJD SBSource::MeanMJD [private]
Definition at line 131 of file SbGeoSources.H'.
Referenced by getGlobalParameters4Report(), getParameters4Report(), meanMJD(), operator<<(), operator=(), operator>>(), SBSource(), and setMeanMJD().
float SBSource::Mv [private]
Definition at line 128 of file SbGeoSources.H'.
Referenced by mv(), operator<<(), operator=(), operator>>(), SBSource(), and setMv().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
int SBSource::NObsApr [private]
Definition at line 129 of file SbGeoSources.H'.
Referenced by getGlobalParameters4Report(), getParameters4Report(), nObsApr(), operator<<(), operator=(), operator>>(), SBSource(), and setNObsApr().
int SBSource::NSessApr [private]
Definition at line 130 of file SbGeoSources.H'.
Referenced by getGlobalParameters4Report(), getParameters4Report(), nSessApr(), operator<<(), operator=(), operator>>(), SBSource(), and setNSessApr().
QString SBSource::ObsName [private]
Definition at line 119 of file SbGeoSources.H'.
Referenced by obsName(), operator=(), SBSource(), and setObsName().
SBParameter* SBSource::P_DN [private]
estimation of the declination;
Definition at line 143 of file SbGeoSources.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getParameters4Report(), operator=(), p_DN(), releaseParameters(), SBSource(), and updateParameters().
SBParameter* SBSource::P_RA [private]
estimation of the right ascension;
Definition at line 142 of file SbGeoSources.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getParameters4Report(), operator=(), p_RA(), releaseParameters(), SBSource(), and updateParameters().
double SBSource::RA [private]
Definition at line 114 of file SbGeoSources.H'.
Referenced by getGlobalParameters4Report(), operator<<(), operator=(), operator>>(), ra(), SBSource(), setRA(), and updateParameters().
double SBSource::RA_DN [private]
Definition at line 134 of file SbGeoSources.H'.
Referenced by corrRA_DN(), getGlobalParameters4Report(), getParameters4Report(), operator<<(), operator=(), operator>>(), SBSource(), and setCorrRA_DN().
double SBSource::RAt [private]
Definition at line 144 of file SbGeoSources.H'.
Referenced by getGlobalParameters4Report(), operator=(), operator>>(), RA2str(), ra_t(), SBSource(), and updateParameters().
float SBSource::RedShift [private]
Definition at line 124 of file SbGeoSources.H'.
Referenced by operator<<(), operator=(), operator>>(), redShift(), SBSource(), and setRedShift().
QString SBSource::SINEXCharID [private]
Definition at line 148 of file SbGeoSources.H'.
Referenced by operator=(), operator>>(), SBSource(), setSINEXCharID(), and sinexCharID().
SSpectrumClass SBSource::SpectrumClass [private]
Definition at line 122 of file SbGeoSources.H'.
Referenced by operator<<(), operator=(), operator>>(), SBSource(), setSpectrum(), and spectrum().
float SBSource::SpIdx [private]
Definition at line 127 of file SbGeoSources.H'.
Referenced by operator<<(), operator=(), operator>>(), SBSource(), setSpIdx(), and spIdx().
SStatus SBSource::Status [private]
Definition at line 120 of file SbGeoSources.H'.
Referenced by operator<<(), operator=(), operator>>(), SBSource(), setStatus(), and status().
int SBSource::StructIdxS [private]
Definition at line 137 of file SbGeoSources.H'.
Referenced by operator<<(), operator=(), operator>>(), SBSource(), setStructIdxS(), and structIdxS().
int SBSource::StructIdxX [private]
Definition at line 136 of file SbGeoSources.H'.
Referenced by operator<<(), operator=(), operator>>(), SBSource(), setStructIdxX(), and structIdxX().
SType SBSource::Type [private]
Definition at line 121 of file SbGeoSources.H'.
Referenced by operator<<(), operator=(), operator>>(), SBSource(), setType(), and type().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.