SBSourceImport
NAME
SBSourceImport -
SYNOPSIS
#include <SbIStuffSource.H>
Inherits QWizard'.
Signals
void sourcesImported ()
Public Member Functions
SBSourceImport (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
void setupPage1 ()
void setupPage2_1 ()
void setupPage2_2 ()
void setupPage2_3 ()
void setupPage3 ()
bool checkFileExists (const QString &)
Private Types
enum FileFormat { F_UNKN = 0, F_ICRF95 = 1, F_ICRF99 = 2, F_ICRF2009 = 3 }
enum FileType { T_RSC = 0, T_CAR = 1, T_DICO = 2 }
enum ImportMode { REPLACE = 0, APP_ONLY = 1, APP_UPD = 2, UPD_ONLY = 3, UPD_COO_ONLY = 4 }
Private Slots
void accept ()
void formatChanged (int)
void modeChanged (int)
void selectRSCfile1995 ()
void selectCARfile1995 ()
void selectDICOfile1995 ()
void setRSCstate1995 (bool T)
void setCARstate1995 (bool T)
void setDICOstate1995 (bool T)
void fnRSCChanged1995 (const QString &FN_)
void fnCARChanged1995 (const QString &FN_)
void fnDICOChanged1995 (const QString &FN_)
void selectRSCDfile1999 ()
void selectRSCCfile1999 ()
void selectRSCOfile1999 ()
void selectRSCNfile1999 ()
void selectCARfile1999 ()
void selectDICOfile1999 ()
void setRSCDstate1999 (bool T)
void setRSCCstate1999 (bool T)
void setRSCOstate1999 (bool T)
void setRSCNstate1999 (bool T)
void setCARstate1999 (bool T)
void setDICOstate1999 (bool T)
void fnRSCDChanged1999 (const QString &FN_)
void fnRSCCChanged1999 (const QString &FN_)
void fnRSCOChanged1999 (const QString &FN_)
void fnRSCNChanged1999 (const QString &FN_)
void fnCARChanged1999 (const QString &FN_)
void fnDICOChanged1999 (const QString &FN_)
void selectRSCNonVCSFile2009 ()
void selectRSCVCSFile2009 ()
void selectCARFile2009 ()
void selectDICOFile2009 ()
void setRSCNonVCSState2009 (bool T)
void setRSCVCSState2009 (bool T)
void setCARState2009 (bool T)
void setDICOState2009 (bool T)
void fnRSCNonVCSChanged2009 (const QString &FN_)
void fnRSCVCSChanged2009 (const QString &FN_)
void fnCARChanged2009 (const QString &FN_)
void fnDICOChanged2009 (const QString &FN_)
Private Member Functions
void checkPage2_1State ()
void checkPage2_2State ()
void checkPage2_3State ()
void selectFile1995 (FileType)
void setState1995 (FileType, bool)
void fileNameChanged1995 (FileType, const QString &)
void selectFile1999 (int)
void setState1999 (int, bool)
void fileNameChanged1999 (int, const QString &)
void selectFile2009 (int)
void setState2009 (int, bool)
void fileNameChanged2009 (int, const QString &)
void importICRF ()
void loadFile1995 (SB_CRF *, QString, FileType, SBSource::SStatus=SBSource::STATUS_UNKN)
void loadFile1999 (SB_CRF *, QString, FileType)
Private Attributes
FileFormat FFormat
QWidget * page1
QWidget * page2_1
QWidget * page2_2
QWidget * page2_3
QWidget * page3
QString sFileName1995 [3]
QCheckBox * cbFileName1995 [3]
QLineEdit * leFileName1995 [3]
QPushButton * bFile1995 [3]
QString sFileName1999 [6]
QCheckBox * cbFileName1999 [6]
QLineEdit * leFileName1999 [6]
QPushButton * bFile1999 [6]
QString sFileName2009 [4]
QCheckBox * cbFileName2009 [4]
QLineEdit * leFileName2009 [4]
QPushButton * bFile2009 [4]
ImportMode Mode
Detailed Description
Definition at line 158 of file SbIStuffSource.H'.
Member Enumeration Documentation
enum SBSourceImport::FileFormat [private]
Enumerator:
F_UNKN
F_ICRF95
F_ICRF99
F_ICRF2009
Definition at line 166 of file SbIStuffSource.H'.
enum SBSourceImport::FileType [private]
Enumerator:
T_RSC
T_CAR
T_DICO
Definition at line 167 of file SbIStuffSource.H'.
enum SBSourceImport::ImportMode [private]
Enumerator:
REPLACE
APP_ONLY
APP_UPD
UPD_ONLY
UPD_COO_ONLY
Definition at line 168 of file SbIStuffSource.H'.
Constructor & Destructor Documentation
SBSourceImport::SBSourceImport (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 737 of file SbIStuffSource.C'.
References F_UNKN, FFormat, Mode, REPLACE, setupPage1(), setupPage2_1(), setupPage2_2(), setupPage2_3(), and setupPage3().
Member Function Documentation
void SBSourceImport::accept () [private, slot]
Definition at line 1191 of file SbIStuffSource.C'.
References ClassName(), SBLog::DBG, F_ICRF2009, F_ICRF95, F_ICRF99, FFormat, importICRF(), SBLog::INTERFACE, Log, SBLog::write(), and SBLog::WRN.
bool SBSourceImport::checkFileExists (const QString &fil) [protected]
Definition at line 803 of file SbIStuffSource.C'.
Referenced by checkPage2_1State(), checkPage2_2State(), checkPage2_3State(), setupPage2_1(), setupPage2_2(), and setupPage2_3().
void SBSourceImport::checkPage2_1State () [private]
Definition at line 1164 of file SbIStuffSource.C'.
References cbFileName1995, checkFileExists(), page2_1, and sFileName1995.
Referenced by fileNameChanged1995(), selectFile1995(), and setState1995().
void SBSourceImport::checkPage2_2State () [private]
Definition at line 1173 of file SbIStuffSource.C'.
References cbFileName1999, checkFileExists(), page2_2, and sFileName1999.
Referenced by fileNameChanged1999(), selectFile1999(), and setState1999().
void SBSourceImport::checkPage2_3State () [private]
Definition at line 1182 of file SbIStuffSource.C'.
References cbFileName2009, checkFileExists(), page2_3, and sFileName2009.
Referenced by fileNameChanged2009(), selectFile2009(), and setState2009().
virtual QString SBSourceImport::ClassName () const [inline, virtual]
Definition at line 163 of file SbIStuffSource.H'.
Referenced by accept(), importICRF(), and loadFile1995().
virtual void SBSourceImport::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 231 of file SbIStuffSource.H'.
void SBSourceImport::fileNameChanged1995 (FileTypeType, const QString &) [private]
Definition at line 1106 of file SbIStuffSource.C'.
References checkPage2_1State(), leFileName1995, and sFileName1995.
Referenced by fnCARChanged1995(), fnDICOChanged1995(), and fnRSCChanged1995().
void SBSourceImport::fileNameChanged1999 (intType, const QString &) [private]
Definition at line 1131 of file SbIStuffSource.C'.
References checkPage2_2State(), leFileName1999, and sFileName1999.
Referenced by fnCARChanged1999(), fnDICOChanged1999(), fnRSCCChanged1999(), fnRSCDChanged1999(), fnRSCNChanged1999(), and fnRSCOChanged1999().
void SBSourceImport::fileNameChanged2009 (intType, const QString &) [private]
Definition at line 1157 of file SbIStuffSource.C'.
References checkPage2_3State(), leFileName2009, and sFileName2009.
Referenced by fnCARChanged2009(), fnDICOChanged2009(), fnRSCNonVCSChanged2009(), and fnRSCVCSChanged2009().
void SBSourceImport::fnCARChanged1995 (const QString &FN_) [inline, private, slot]
Definition at line 188 of file SbIStuffSource.H'.
References fileNameChanged1995(), and T_CAR.
Referenced by setupPage2_1().
void SBSourceImport::fnCARChanged1999 (const QString &FN_) [inline, private, slot]
Definition at line 210 of file SbIStuffSource.H'.
References fileNameChanged1999().
Referenced by setupPage2_2().
void SBSourceImport::fnCARChanged2009 (const QString &FN_) [inline, private, slot]
Definition at line 226 of file SbIStuffSource.H'.
References fileNameChanged2009().
Referenced by setupPage2_3().
void SBSourceImport::fnDICOChanged1995 (const QString &FN_) [inline, private, slot]
Definition at line 189 of file SbIStuffSource.H'.
References fileNameChanged1995(), and T_DICO.
Referenced by setupPage2_1().
void SBSourceImport::fnDICOChanged1999 (const QString &FN_) [inline, private, slot]
Definition at line 211 of file SbIStuffSource.H'.
References fileNameChanged1999().
Referenced by setupPage2_2().
void SBSourceImport::fnDICOChanged2009 (const QString &FN_) [inline, private, slot]
Definition at line 227 of file SbIStuffSource.H'.
References fileNameChanged2009().
Referenced by setupPage2_3().
void SBSourceImport::fnRSCCChanged1999 (const QString &FN_) [inline, private, slot]
Definition at line 207 of file SbIStuffSource.H'.
References fileNameChanged1999().
Referenced by setupPage2_2().
void SBSourceImport::fnRSCChanged1995 (const QString &FN_) [inline, private, slot]
Definition at line 187 of file SbIStuffSource.H'.
References fileNameChanged1995(), and T_RSC.
Referenced by setupPage2_1().
void SBSourceImport::fnRSCDChanged1999 (const QString &FN_) [inline, private, slot]
Definition at line 206 of file SbIStuffSource.H'.
References fileNameChanged1999().
Referenced by setupPage2_2().
void SBSourceImport::fnRSCNChanged1999 (const QString &FN_) [inline, private, slot]
Definition at line 209 of file SbIStuffSource.H'.
References fileNameChanged1999().
Referenced by setupPage2_2().
void SBSourceImport::fnRSCNonVCSChanged2009 (const QString &FN_) [inline, private, slot]
Definition at line 224 of file SbIStuffSource.H'.
References fileNameChanged2009().
Referenced by setupPage2_3().
void SBSourceImport::fnRSCOChanged1999 (const QString &FN_) [inline, private, slot]
Definition at line 208 of file SbIStuffSource.H'.
References fileNameChanged1999().
Referenced by setupPage2_2().
void SBSourceImport::fnRSCVCSChanged2009 (const QString &FN_) [inline, private, slot]
Definition at line 225 of file SbIStuffSource.H'.
References fileNameChanged2009().
Referenced by setupPage2_3().
void SBSourceImport::formatChanged (intid) [private, slot]
Definition at line 750 of file SbIStuffSource.C'.
References F_ICRF2009, F_ICRF95, F_ICRF99, F_UNKN, FFormat, page1, page2_1, page2_2, and page2_3.
Referenced by setupPage1().
void SBSourceImport::importICRF () [private]
Definition at line 1215 of file SbIStuffSource.C'.
References SBCatalog::aliasDict(), APP_ONLY, APP_UPD, cbFileName1995, cbFileName1999, cbFileName2009, ClassName(), SBCatalog::comment(), SBLog::DBG, SBSource::dn(), SBSource::dn_err(), F_ICRF2009, F_ICRF95, F_ICRF99, FFormat, SB_CRF::find(), SB_CRF::first(), SBCatalog::inSort(), SBLog::INTERFACE, leFileName1995, leFileName1999, leFileName2009, SBSetUp::loadCRF(), loadFile1995(), Log, Mode, SB_CRF::next(), SBSource::ra(), SBSource::ra_err(), REPLACE, SBSetUp::saveCRF(), SBSource::setDN(), SBSource::setDN_err(), SBSource::setRA(), SBSource::setRA_err(), SetUp, sFileName1995, sFileName1999, sFileName2009, sourcesImported(), SBSource::STATUS_CAND, SBSource::STATUS_DEF, SBSource::STATUS_NEW, SBSource::STATUS_OTHER, SBSource::STATUS_UNKN, T_RSC, UPD_COO_ONLY, UPD_ONLY, SBLog::write(), and SBLog::WRN.
Referenced by accept().
void SBSourceImport::loadFile1995 (SB_CRF *W, QStringFileName, FileTypeType, SBSource::SStatusStatus = SBSource::STATUS_UNKN) [private]
Definition at line 1448 of file SbIStuffSource.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::IO, Log, SBTS_rsc::setAssignedStatus(), T_CAR, T_DICO, T_RSC, SBLog::write(), and SBLog::WRN.
Referenced by importICRF().
void SBSourceImport::loadFile1999 (SB_CRF *, QString, FileType) [private]
Definition at line 1486 of file SbIStuffSource.C'.
void SBSourceImport::modeChanged (intid) [private, slot]
Definition at line 786 of file SbIStuffSource.C'.
References APP_ONLY, APP_UPD, Mode, REPLACE, UPD_COO_ONLY, and UPD_ONLY.
Referenced by setupPage3().
void SBSourceImport::selectCARfile1995 () [inline, private, slot]
Definition at line 180 of file SbIStuffSource.H'.
References selectFile1995(), and T_CAR.
Referenced by setupPage2_1().
void SBSourceImport::selectCARfile1999 () [inline, private, slot]
Definition at line 196 of file SbIStuffSource.H'.
References selectFile1999().
Referenced by setupPage2_2().
void SBSourceImport::selectCARFile2009 () [inline, private, slot]
Definition at line 216 of file SbIStuffSource.H'.
References selectFile2009().
Referenced by setupPage2_3().
void SBSourceImport::selectDICOfile1995 () [inline, private, slot]
Definition at line 181 of file SbIStuffSource.H'.
References selectFile1995(), and T_DICO.
Referenced by setupPage2_1().
void SBSourceImport::selectDICOfile1999 () [inline, private, slot]
Definition at line 197 of file SbIStuffSource.H'.
References selectFile1999().
Referenced by setupPage2_2().
void SBSourceImport::selectDICOFile2009 () [inline, private, slot]
Definition at line 217 of file SbIStuffSource.H'.
References selectFile2009().
Referenced by setupPage2_3().
void SBSourceImport::selectFile1995 (FileTypeType) [private]
Definition at line 1087 of file SbIStuffSource.C'.
References checkPage2_1State(), leFileName1995, SBSetUp::path2ImpICRF(), SetUp, and sFileName1995.
Referenced by selectCARfile1995(), selectDICOfile1995(), and selectRSCfile1995().
void SBSourceImport::selectFile1999 (intType) [private]
Definition at line 1112 of file SbIStuffSource.C'.
References checkPage2_2State(), leFileName1999, SBSetUp::path2ImpICRF(), SetUp, and sFileName1999.
Referenced by selectCARfile1999(), selectDICOfile1999(), selectRSCCfile1999(), selectRSCDfile1999(), selectRSCNfile1999(), and selectRSCOfile1999().
void SBSourceImport::selectFile2009 (intType) [private]
Definition at line 1138 of file SbIStuffSource.C'.
References checkPage2_3State(), leFileName2009, SBSetUp::path2ImpICRF(), SetUp, and sFileName2009.
Referenced by selectCARFile2009(), selectDICOFile2009(), selectRSCNonVCSFile2009(), and selectRSCVCSFile2009().
void SBSourceImport::selectRSCCfile1999 () [inline, private, slot]
Definition at line 193 of file SbIStuffSource.H'.
References selectFile1999().
Referenced by setupPage2_2().
void SBSourceImport::selectRSCDfile1999 () [inline, private, slot]
Definition at line 192 of file SbIStuffSource.H'.
References selectFile1999().
Referenced by setupPage2_2().
void SBSourceImport::selectRSCfile1995 () [inline, private, slot]
Definition at line 179 of file SbIStuffSource.H'.
References selectFile1995(), and T_RSC.
Referenced by setupPage2_1().
void SBSourceImport::selectRSCNfile1999 () [inline, private, slot]
Definition at line 195 of file SbIStuffSource.H'.
References selectFile1999().
Referenced by setupPage2_2().
void SBSourceImport::selectRSCNonVCSFile2009 () [inline, private, slot]
Definition at line 214 of file SbIStuffSource.H'.
References selectFile2009().
Referenced by setupPage2_3().
void SBSourceImport::selectRSCOfile1999 () [inline, private, slot]
Definition at line 194 of file SbIStuffSource.H'.
References selectFile1999().
Referenced by setupPage2_2().
void SBSourceImport::selectRSCVCSFile2009 () [inline, private, slot]
Definition at line 215 of file SbIStuffSource.H'.
References selectFile2009().
Referenced by setupPage2_3().
void SBSourceImport::setCARstate1995 (boolT) [inline, private, slot]
Definition at line 184 of file SbIStuffSource.H'.
References setState1995(), and T_CAR.
Referenced by setupPage2_1().
void SBSourceImport::setCARstate1999 (boolT) [inline, private, slot]
Definition at line 203 of file SbIStuffSource.H'.
References setState1999().
Referenced by setupPage2_2().
void SBSourceImport::setCARState2009 (boolT) [inline, private, slot]
Definition at line 221 of file SbIStuffSource.H'.
References setState2009().
Referenced by setupPage2_3().
void SBSourceImport::setDICOstate1995 (boolT) [inline, private, slot]
Definition at line 185 of file SbIStuffSource.H'.
References setState1995(), and T_DICO.
Referenced by setupPage2_1().
void SBSourceImport::setDICOstate1999 (boolT) [inline, private, slot]
Definition at line 204 of file SbIStuffSource.H'.
References setState1999().
Referenced by setupPage2_2().
void SBSourceImport::setDICOState2009 (boolT) [inline, private, slot]
Definition at line 222 of file SbIStuffSource.H'.
References setState2009().
Referenced by setupPage2_3().
void SBSourceImport::setRSCCstate1999 (boolT) [inline, private, slot]
Definition at line 200 of file SbIStuffSource.H'.
References setState1999().
Referenced by setupPage2_2().
void SBSourceImport::setRSCDstate1999 (boolT) [inline, private, slot]
Definition at line 199 of file SbIStuffSource.H'.
References setState1999().
Referenced by setupPage2_2().
void SBSourceImport::setRSCNonVCSState2009 (boolT) [inline, private, slot]
Definition at line 219 of file SbIStuffSource.H'.
References setState2009().
Referenced by setupPage2_3().
void SBSourceImport::setRSCNstate1999 (boolT) [inline, private, slot]
Definition at line 202 of file SbIStuffSource.H'.
References setState1999().
Referenced by setupPage2_2().
void SBSourceImport::setRSCOstate1999 (boolT) [inline, private, slot]
Definition at line 201 of file SbIStuffSource.H'.
References setState1999().
Referenced by setupPage2_2().
void SBSourceImport::setRSCstate1995 (boolT) [inline, private, slot]
Definition at line 183 of file SbIStuffSource.H'.
References setState1995(), and T_RSC.
Referenced by setupPage2_1().
void SBSourceImport::setRSCVCSState2009 (boolT) [inline, private, slot]
Definition at line 220 of file SbIStuffSource.H'.
References setState2009().
Referenced by setupPage2_3().
void SBSourceImport::setState1995 (FileTypeType, boolT) [private]
Definition at line 1099 of file SbIStuffSource.C'.
References bFile1995, checkPage2_1State(), and leFileName1995.
Referenced by setCARstate1995(), setDICOstate1995(), and setRSCstate1995().
void SBSourceImport::setState1999 (intType, boolT) [private]
Definition at line 1124 of file SbIStuffSource.C'.
References bFile1999, checkPage2_2State(), and leFileName1999.
Referenced by setCARstate1999(), setDICOstate1999(), setRSCCstate1999(), setRSCDstate1999(), setRSCNstate1999(), and setRSCOstate1999().
void SBSourceImport::setState2009 (intType, boolT) [private]
Definition at line 1150 of file SbIStuffSource.C'.
References bFile2009, checkPage2_3State(), and leFileName2009.
Referenced by setCARState2009(), setDICOState2009(), setRSCNonVCSState2009(), and setRSCVCSState2009().
void SBSourceImport::setupPage1 () [protected]
Definition at line 809 of file SbIStuffSource.C'.
References formatChanged(), and page1.
Referenced by SBSourceImport().
void SBSourceImport::setupPage2_1 () [protected]
Definition at line 842 of file SbIStuffSource.C'.
References bFile1995, cbFileName1995, checkFileExists(), fnCARChanged1995(), fnDICOChanged1995(), fnRSCChanged1995(), leFileName1995, page2_1, SBSetUp::path2ImpICRF(), selectCARfile1995(), selectDICOfile1995(), selectRSCfile1995(), setCARstate1995(), setDICOstate1995(), setRSCstate1995(), SetUp, and sFileName1995.
Referenced by SBSourceImport().
void SBSourceImport::setupPage2_2 () [protected]
Definition at line 902 of file SbIStuffSource.C'.
References bFile1999, cbFileName1999, checkFileExists(), fnCARChanged1999(), fnDICOChanged1999(), fnRSCCChanged1999(), fnRSCDChanged1999(), fnRSCNChanged1999(), fnRSCOChanged1999(), leFileName1999, page2_2, SBSetUp::path2ImpICRF(), selectCARfile1999(), selectDICOfile1999(), selectRSCCfile1999(), selectRSCDfile1999(), selectRSCNfile1999(), selectRSCOfile1999(), setCARstate1999(), setDICOstate1999(), setRSCCstate1999(), setRSCDstate1999(), setRSCNstate1999(), setRSCOstate1999(), SetUp, and sFileName1999.
Referenced by SBSourceImport().
void SBSourceImport::setupPage2_3 () [protected]
Definition at line 982 of file SbIStuffSource.C'.
References bFile2009, cbFileName2009, checkFileExists(), fnCARChanged2009(), fnDICOChanged2009(), fnRSCNonVCSChanged2009(), fnRSCVCSChanged2009(), leFileName2009, page2_3, SBSetUp::path2ImpICRF(), selectCARFile2009(), selectDICOFile2009(), selectRSCNonVCSFile2009(), selectRSCVCSFile2009(), setCARState2009(), setDICOState2009(), setRSCNonVCSState2009(), setRSCVCSState2009(), SetUp, and sFileName2009.
Referenced by SBSourceImport().
void SBSourceImport::setupPage3 () [protected]
Definition at line 1052 of file SbIStuffSource.C'.
References Mode, modeChanged(), and page3.
Referenced by SBSourceImport().
void SBSourceImport::sourcesImported () [signal]
Definition at line 517 of file SbIStuffSource.moc.C'.
Referenced by importICRF().
Member Data Documentation
QPushButton* SBSourceImport::bFile1995[3] [private]
Definition at line 254 of file SbIStuffSource.H'.
Referenced by setState1995(), and setupPage2_1().
QPushButton* SBSourceImport::bFile1999[6] [private]
Definition at line 261 of file SbIStuffSource.H'.
Referenced by setState1999(), and setupPage2_2().
QPushButton* SBSourceImport::bFile2009[4] [private]
Definition at line 268 of file SbIStuffSource.H'.
Referenced by setState2009(), and setupPage2_3().
QCheckBox* SBSourceImport::cbFileName1995[3] [private]
Definition at line 252 of file SbIStuffSource.H'.
Referenced by checkPage2_1State(), importICRF(), and setupPage2_1().
QCheckBox* SBSourceImport::cbFileName1999[6] [private]
Definition at line 259 of file SbIStuffSource.H'.
Referenced by checkPage2_2State(), importICRF(), and setupPage2_2().
QCheckBox* SBSourceImport::cbFileName2009[4] [private]
Definition at line 266 of file SbIStuffSource.H'.
Referenced by checkPage2_3State(), importICRF(), and setupPage2_3().
FileFormat SBSourceImport::FFormat [private]
Definition at line 242 of file SbIStuffSource.H'.
Referenced by accept(), formatChanged(), importICRF(), and SBSourceImport().
QLineEdit* SBSourceImport::leFileName1995[3] [private]
Definition at line 253 of file SbIStuffSource.H'.
Referenced by fileNameChanged1995(), importICRF(), selectFile1995(), setState1995(), and setupPage2_1().
QLineEdit* SBSourceImport::leFileName1999[6] [private]
Definition at line 260 of file SbIStuffSource.H'.
Referenced by fileNameChanged1999(), importICRF(), selectFile1999(), setState1999(), and setupPage2_2().
QLineEdit* SBSourceImport::leFileName2009[4] [private]
Definition at line 267 of file SbIStuffSource.H'.
Referenced by fileNameChanged2009(), importICRF(), selectFile2009(), setState2009(), and setupPage2_3().
ImportMode SBSourceImport::Mode [private]
Definition at line 274 of file SbIStuffSource.H'.
Referenced by importICRF(), modeChanged(), SBSourceImport(), and setupPage3().
QWidget* SBSourceImport::page1 [private]
Definition at line 244 of file SbIStuffSource.H'.
Referenced by formatChanged(), and setupPage1().
QWidget* SBSourceImport::page2_1 [private]
Definition at line 245 of file SbIStuffSource.H'.
Referenced by checkPage2_1State(), formatChanged(), and setupPage2_1().
QWidget* SBSourceImport::page2_2 [private]
Definition at line 246 of file SbIStuffSource.H'.
Referenced by checkPage2_2State(), formatChanged(), and setupPage2_2().
QWidget* SBSourceImport::page2_3 [private]
Definition at line 247 of file SbIStuffSource.H'.
Referenced by checkPage2_3State(), formatChanged(), and setupPage2_3().
QWidget* SBSourceImport::page3 [private]
Definition at line 248 of file SbIStuffSource.H'.
Referenced by setupPage3().
QString SBSourceImport::sFileName1995[3] [private]
Definition at line 251 of file SbIStuffSource.H'.
Referenced by checkPage2_1State(), fileNameChanged1995(), importICRF(), selectFile1995(), and setupPage2_1().
QString SBSourceImport::sFileName1999[6] [private]
Definition at line 258 of file SbIStuffSource.H'.
Referenced by checkPage2_2State(), fileNameChanged1999(), importICRF(), selectFile1999(), and setupPage2_2().
QString SBSourceImport::sFileName2009[4] [private]
Definition at line 265 of file SbIStuffSource.H'.
Referenced by checkPage2_3State(), fileNameChanged2009(), importICRF(), selectFile2009(), and setupPage2_3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.