SBSolutionBatchLI
NAME
SBSolutionBatchLI -
SYNOPSIS
#include <SbISolution.H>
Inherits QListViewItem'.
Public Member Functions
SBSolutionBatchLI (QListView *parent, SBStatistics *S_, double Scale_)
SBStatistics * statistics ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBStatistics * S
double Scale
Detailed Description
Definition at line 65 of file SbISolution.H'.
Constructor & Destructor Documentation
SBSolutionBatchLI::SBSolutionBatchLI (QListView *parent, SBStatistics *S_, doubleScale_) [inline]
Definition at line 72 of file SbISolution.H'.
References S, and Scale.
Member Function Documentation
virtual QString SBSolutionBatchLI::ClassName () const [inline, virtual]
Definition at line 75 of file SbISolution.H'.
QString SBSolutionBatchLI::key (intcol, bool) const [virtual]
Definition at line 140 of file SbISolution.C'.
References SBMJD::F_INTERNAL, SBStatistics::numObs(), SBStatistics::numPars(), S, Scale, TmpString, SBMJD::toString(), SBStatistics::tStart(), SBStatistics::VarFactor_unit(), and SBStatistics::WRMS_unit().
SBStatistics* SBSolutionBatchLI::statistics () [inline]
Definition at line 74 of file SbISolution.H'.
References S.
QString SBSolutionBatchLI::text (intcol) const [virtual]
Definition at line 119 of file SbISolution.C'.
References SBNamed::name(), SBStatistics::numObs(), SBStatistics::numPars(), S, Scale, TmpString, SBStatistics::VarFactor_unit(), and SBStatistics::WRMS_unit().
Member Data Documentation
SBStatistics* SBSolutionBatchLI::S [private]
Definition at line 68 of file SbISolution.H'.
Referenced by key(), SBSolutionBatchLI(), statistics(), and text().
double SBSolutionBatchLI::Scale [private]
Definition at line 69 of file SbISolution.H'.
Referenced by key(), SBSolutionBatchLI(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.