SBSourceEditor
NAME
SBSourceEditor -
SYNOPSIS
#include <SbIStuffSource.H>
Inherits SBTabDialog'.
Signals
void SourceModified (bool)
Public Member Functions
SBSourceEditor (SBSourceListItem *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
SBSourceEditor (QListView *, SB_CRF *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBSourceEditor ()
virtual QString ClassName () const
Protected Slots
virtual void makeApply ()
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Member Functions
virtual void acquireData ()
void init ()
QWidget * wCoordinates ()
QWidget * wStats ()
QWidget * wPhysChars ()
Private Attributes
QListView * SourcesLV
SBSourceListItem * SrcItem
SBSource * Source
SB_CRF * Wcrf
bool isModified
bool isNew
QLineEdit * EName
QLineEdit * EICRF
QComboBox * CBAlias
QGroupBox * NameGBox
QLineEdit * ERAhr
QLineEdit * ERAmin
QLineEdit * ERAsec
QLineEdit * ERAunc
QLineEdit * EDNdg
QLineEdit * EDNmin
QLineEdit * EDNsec
QLineEdit * EDNunc
QLineEdit * ECorr
QCheckBox * CBHipp
QRadioButton * RBStatus [5]
QLineEdit * ENofObs
QLineEdit * ENofSes
QLineEdit * EFMJD
QLineEdit * EMMJD
QLineEdit * ELMJD
QCheckBox * CDOrigin [4]
QCheckBox * CDAttr [13]
QRadioButton * RBType [6]
QRadioButton * RBSpClass [8]
QLineEdit * EMv
QLineEdit * EFlux1
QLineEdit * EFlux2
QLineEdit * ESpIdx
QLineEdit * ERedShift
Detailed Description
Definition at line 302 of file SbIStuffSource.H'.
Constructor & Destructor Documentation
SBSourceEditor::SBSourceEditor (SBSourceListItem *SrcItem_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1498 of file SbIStuffSource.C'.
References init(), isNew, SBSourceListItem::Source, Source, SourcesLV, SrcItem, and Wcrf.
SBSourceEditor::SBSourceEditor (QListView *SourcesLV_, SB_CRF *Wcrf_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1511 of file SbIStuffSource.C'.
References init(), isNew, Source, SourcesLV, SrcItem, and Wcrf.
SBSourceEditor::~SBSourceEditor ()
Definition at line 1538 of file SbIStuffSource.C'.
References isModified, isNew, Source, and SourceModified().
Member Function Documentation
void SBSourceEditor::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 2142 of file SbIStuffSource.C'.
References CBHipp, SBSource::corrRA_DN(), dms2rad(), SBSource::dn(), SBSource::dn_err(), ECorr, EDNdg, EDNmin, EDNsec, EDNunc, EFlux1, EFlux2, EFMJD, EICRF, ELMJD, EMMJD, EMv, EName, ENofObs, ENofSes, ERAhr, ERAmin, ERAsec, ERAunc, ERedShift, ESpIdx, SBMJD::F_Short, SBSource::firstMJD(), SBSource::flux1(), SBSource::flux2(), hms2rad(), SBSource::ICRFName(), SBMJD::isGood(), SBSource::isHLink(), isModified, isNew, SBSource::isValidICRFName(), SBSource::lastMJD(), SBSource::meanMJD(), SBSource::mv(), SBNamed::name(), SBSource::nObsApr(), SBSource::nSessApr(), SBSource::ra(), SBSource::ra_err(), RBSpClass, RBStatus, RBType, SBSource::redShift(), SBSource::setCorrRA_DN(), SBSource::setDN(), SBSource::setDN_err(), SBSource::setFirstMJD(), SBSource::setFlux1(), SBSource::setFlux2(), SBSource::setICRFName(), SBSource::setIsHLink(), SBSource::setLastMJD(), SBSource::setMeanMJD(), SBMJD::setMJD(), SBSource::setMv(), SBNamed::setName(), SBSource::setNObsApr(), SBSource::setNSessApr(), SBSource::setRA(), SBSource::setRA_err(), SBSource::setRedShift(), SBSource::setSpectrum(), SBSource::setSpIdx(), SBSource::setStatus(), SBSource::setType(), Source, SBSource::SP_HP, SBSource::SP_OTHER, SBSource::SP_SEYFERT, SBSource::SP_SEYFERT1, SBSource::SP_SEYFERT1_2, SBSource::SP_SEYFERT2, SBSource::SP_SEYFERT3, SBSource::SP_UNKN, SBSource::spectrum(), SBSource::spIdx(), SBSource::status(), SBSource::STATUS_CAND, SBSource::STATUS_DEF, SBSource::STATUS_NEW, SBSource::STATUS_OTHER, SBSource::STATUS_UNKN, SBMJD::toString(), SBSource::type(), SBSource::TYPE_BL_LAC, SBSource::TYPE_BL_LAC_C, SBSource::TYPE_GALAXY, SBSource::TYPE_OTHER, SBSource::TYPE_QUASAR, and SBSource::TYPE_UNKN.
Referenced by makeApply().
virtual QString SBSourceEditor::ClassName () const [inline, virtual]
Definition at line 309 of file SbIStuffSource.H'.
Referenced by makeApply().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
void SBSourceEditor::init () [private]
Definition at line 1524 of file SbIStuffSource.C'.
References isModified, makeApply(), wCoordinates(), wPhysChars(), and wStats().
Referenced by SBSourceEditor().
void SBSourceEditor::makeApply () [protected, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 1544 of file SbIStuffSource.C'.
References acquireData(), SBAttributed::addAttr(), ClassName(), SBLog::DBG, EName, SB_CRF::find(), SBCatalog::inSort(), SBLog::INTERFACE, isModified, isNew, Log, SBNamed::name(), NameGBox, SBSource::OrigEdited, Source, SourcesLV, SrcItem, Wcrf, and SBLog::write().
Referenced by init().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBSourceEditor::SourceModified (boolt0) [signal]
Definition at line 592 of file SbIStuffSource.moc.C'.
Referenced by ~SBSourceEditor().
QWidget * SBSourceEditor::wCoordinates () [private]
Definition at line 1590 of file SbIStuffSource.C'.
References SBSource::aliasesList(), CBAlias, CBHipp, SBSource::corrRA_DN(), SBSource::dn(), SBSource::dn_err(), ECorr, EDNdg, EDNmin, EDNsec, EDNunc, EICRF, EName, ERAhr, ERAmin, ERAsec, ERAunc, SBSource::ICRFName(), SBSource::isHLink(), isNew, SBNamed::name(), NameGBox, SBSource::ra(), SBSource::ra_err(), rad2dms(), rad2hms(), RBStatus, Source, and SBSource::status().
Referenced by init().
QWidget * SBSourceEditor::wPhysChars () [private]
Definition at line 1837 of file SbIStuffSource.C'.
References EFlux1, EFlux2, EMv, ERedShift, ESpIdx, SBSource::flux1(), SBSource::flux2(), SBSource::mv(), RBSpClass, RBType, SBSource::redShift(), Source, SBSource::spectrum(), SBSource::spIdx(), and SBSource::type().
Referenced by init().
QWidget * SBSourceEditor::wStats () [private]
Definition at line 1984 of file SbIStuffSource.C'.
References SBSource::AnalysConstr, SBSource::Analysed, CDAttr, CDOrigin, EFMJD, ELMJD, EMMJD, ENofObs, ENofSes, SBMJD::F_Short, SBSource::firstMJD(), SBAttributed::isAttr(), SBSource::lastMJD(), SBSource::meanMJD(), SBSource::nObsApr(), SBSource::nSessApr(), SBSource::OrigEdited, SBSource::OrigEstimated, SBSource::OrigImported, SBSource::OrigObsData, SBSource::Reserved_08, SBSource::Reserved_09, SBSource::Reserved_10, SBSource::Reserved_11, SBSource::Reserved_12, SBSource::Reserved_13, SBSource::Reserved_14, SBSource::Reserved_15, SBSource::Reserved_16, SBSource::Reserved_17, Source, SBSource::StatusSuspected, and SBMJD::toString().
Referenced by init().
Member Data Documentation
QComboBox* SBSourceEditor::CBAlias [private]
Definition at line 335 of file SbIStuffSource.H'.
Referenced by wCoordinates().
QCheckBox* SBSourceEditor::CBHipp [private]
Definition at line 348 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QCheckBox* SBSourceEditor::CDAttr[13] [private]
Definition at line 358 of file SbIStuffSource.H'.
Referenced by wStats().
QCheckBox* SBSourceEditor::CDOrigin[4] [private]
Definition at line 357 of file SbIStuffSource.H'.
Referenced by wStats().
QLineEdit* SBSourceEditor::ECorr [private]
Definition at line 347 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::EDNdg [private]
Definition at line 343 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::EDNmin [private]
Definition at line 344 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::EDNsec [private]
Definition at line 345 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::EDNunc [private]
Definition at line 346 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::EFlux1 [private]
Definition at line 364 of file SbIStuffSource.H'.
Referenced by acquireData(), and wPhysChars().
QLineEdit* SBSourceEditor::EFlux2 [private]
Definition at line 365 of file SbIStuffSource.H'.
Referenced by acquireData(), and wPhysChars().
QLineEdit* SBSourceEditor::EFMJD [private]
Definition at line 354 of file SbIStuffSource.H'.
Referenced by acquireData(), and wStats().
QLineEdit* SBSourceEditor::EICRF [private]
Definition at line 334 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::ELMJD [private]
Definition at line 356 of file SbIStuffSource.H'.
Referenced by acquireData(), and wStats().
QLineEdit* SBSourceEditor::EMMJD [private]
Definition at line 355 of file SbIStuffSource.H'.
Referenced by acquireData(), and wStats().
QLineEdit* SBSourceEditor::EMv [private]
Definition at line 363 of file SbIStuffSource.H'.
Referenced by acquireData(), and wPhysChars().
QLineEdit* SBSourceEditor::EName [private]
Definition at line 333 of file SbIStuffSource.H'.
Referenced by acquireData(), makeApply(), and wCoordinates().
QLineEdit* SBSourceEditor::ENofObs [private]
Definition at line 352 of file SbIStuffSource.H'.
Referenced by acquireData(), and wStats().
QLineEdit* SBSourceEditor::ENofSes [private]
Definition at line 353 of file SbIStuffSource.H'.
Referenced by acquireData(), and wStats().
QLineEdit* SBSourceEditor::ERAhr [private]
Definition at line 339 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::ERAmin [private]
Definition at line 340 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::ERAsec [private]
Definition at line 341 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::ERAunc [private]
Definition at line 342 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBSourceEditor::ERedShift [private]
Definition at line 367 of file SbIStuffSource.H'.
Referenced by acquireData(), and wPhysChars().
QLineEdit* SBSourceEditor::ESpIdx [private]
Definition at line 366 of file SbIStuffSource.H'.
Referenced by acquireData(), and wPhysChars().
bool SBSourceEditor::isModified [private]
Definition at line 329 of file SbIStuffSource.H'.
Referenced by acquireData(), init(), makeApply(), and ~SBSourceEditor().
bool SBSourceEditor::isNew [private]
Definition at line 330 of file SbIStuffSource.H'.
Referenced by acquireData(), makeApply(), SBSourceEditor(), wCoordinates(), and ~SBSourceEditor().
QGroupBox* SBSourceEditor::NameGBox [private]
Definition at line 336 of file SbIStuffSource.H'.
Referenced by makeApply(), and wCoordinates().
QRadioButton* SBSourceEditor::RBSpClass[8] [private]
Definition at line 362 of file SbIStuffSource.H'.
Referenced by acquireData(), and wPhysChars().
QRadioButton* SBSourceEditor::RBStatus[5] [private]
Definition at line 349 of file SbIStuffSource.H'.
Referenced by acquireData(), and wCoordinates().
QRadioButton* SBSourceEditor::RBType[6] [private]
Definition at line 361 of file SbIStuffSource.H'.
Referenced by acquireData(), and wPhysChars().
SBSource* SBSourceEditor::Source [private]
Definition at line 327 of file SbIStuffSource.H'.
Referenced by acquireData(), makeApply(), SBSourceEditor(), wCoordinates(), wPhysChars(), wStats(), and ~SBSourceEditor().
QListView* SBSourceEditor::SourcesLV [private]
Definition at line 325 of file SbIStuffSource.H'.
Referenced by makeApply(), and SBSourceEditor().
SBSourceListItem* SBSourceEditor::SrcItem [private]
Definition at line 326 of file SbIStuffSource.H'.
Referenced by makeApply(), and SBSourceEditor().
SB_CRF* SBSourceEditor::Wcrf [private]
Definition at line 328 of file SbIStuffSource.H'.
Referenced by makeApply(), and SBSourceEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.