.TH "SBSolutionBatchLI" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBSolutionBatchLI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbISolution\&.H>\fP
.PP
Inherits \fBQListViewItem\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBSolutionBatchLI\fP (\fBQListView\fP *parent, \fBSBStatistics\fP *S_, double Scale_)"
.br
.ti -1c
.RI "\fBSBStatistics\fP * \fBstatistics\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.ti -1c
.RI "virtual QString \fBkey\fP (int, bool) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBStatistics\fP * \fBS\fP"
.br
.ti -1c
.RI "double \fBScale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file SbISolution\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBSolutionBatchLI::SBSolutionBatchLI (\fBQListView\fP *parent, \fBSBStatistics\fP *S_, doubleScale_)\fC [inline]\fP"
.PP
Definition at line 72 of file SbISolution\&.H'\&.
.PP
References S, and Scale\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBSolutionBatchLI::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 75 of file SbISolution\&.H'\&.
.SS "QString SBSolutionBatchLI::key (intcol, bool) const\fC [virtual]\fP"
.PP
Definition at line 140 of file SbISolution\&.C'\&.
.PP
References SBMJD::F_INTERNAL, SBStatistics::numObs(), SBStatistics::numPars(), S, Scale, TmpString, SBMJD::toString(), SBStatistics::tStart(), SBStatistics::VarFactor_unit(), and SBStatistics::WRMS_unit()\&.
.SS "\fBSBStatistics\fP* SBSolutionBatchLI::statistics ()\fC [inline]\fP"
.PP
Definition at line 74 of file SbISolution\&.H'\&.
.PP
References S\&.
.SS "QString SBSolutionBatchLI::text (intcol) const\fC [virtual]\fP"
.PP
Definition at line 119 of file SbISolution\&.C'\&.
.PP
References SBNamed::name(), SBStatistics::numObs(), SBStatistics::numPars(), S, Scale, TmpString, SBStatistics::VarFactor_unit(), and SBStatistics::WRMS_unit()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBStatistics\fP* \fBSBSolutionBatchLI::S\fP\fC [private]\fP"
.PP
Definition at line 68 of file SbISolution\&.H'\&.
.PP
Referenced by key(), SBSolutionBatchLI(), statistics(), and text()\&.
.SS "double \fBSBSolutionBatchLI::Scale\fP\fC [private]\fP"
.PP
Definition at line 69 of file SbISolution\&.H'\&.
.PP
Referenced by key(), SBSolutionBatchLI(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
