SBSolidTideLd
NAME
SBSolidTideLd -
SYNOPSIS
#include <SbGeoTide.H>
Inherits Vector3'.
Inherited by SBSolidTideLdIERS92, and SBSolidTideLdIERS96'.
Public Member Functions
SBSolidTideLd (const SBConfig *)
virtual ~SBSolidTideLd ()
virtual QString ClassName () const
virtual const Vector3 & operator() (SBStation *, SBEphem *, const SBFrame &)
const Vector3 & tideDeg2ip () const
const Vector3 & tideDeg3ip () const
const Vector3 & tideDeg2op () const
const Vector3 & tideLatDepend () const
const Vector3 & step1 () const
const Vector3 & step2 () const
Vector3 dTide_dLag (SBStation *, SBEphem *)
Vector3 dTide_dH2 (SBStation *, SBEphem *)
Vector3 dTide_dL2 (SBStation *, SBEphem *)
double & operator[] (DIRECTION i)
double at (DIRECTION i) const
double module () const
double phi () const
double lambda () const
Vector3 & unify ()
Vector3 unit () const
void clear ()
Vector3 & operator+= (const Vector3 &)
Vector3 & operator-= (const Vector3 &)
Vector3 & operator*= (double)
Vector3 & operator/= (double)
virtual void report2Log (SBLog::LogLevel, uint, const QString &, int, int, double=1.0) const
bool operator== (const Vector3 &v) const
bool operator!= (const Vector3 &v) const
Protected Member Functions
virtual double h2 (double phi, SBStation *) const
virtual double l2 (double phi, SBStation *) const
virtual double h3 () const
virtual double l3 () const
virtual Vector3 deg2InPhase (SBStation *, const Vector3 &)
virtual const Vector3 & makeStep1 (SBStation *, SBEphem *)
virtual const Vector3 & makeStep2 (SBStation *, const SBFrame &)
virtual Vector3 permTide (SBStation *)
Protected Attributes
const SBConfig * Cfg
double h_0
double h_2
double l_0
double l_2
Vector3 TideDeg2ip
Vector3 TideDeg3ip
Vector3 TideDeg2op
Vector3 TideLatDepend
Vector3 Step1
Vector3 Step2
double CoeffSun
double CoeffMoon
Vector3 Moon_TRS
Vector3 Sun_TRS
Matrix3 FmREN
transforms local radial-transverse coords to TRF
double vec [3]
Static Protected Attributes
static const double h_0_el = 0.6026
nominal value for h^(0), elastic
static const double h_2_el = -0.0006
nominal value for h^(2), elastic
static const double l_0_el = 0.0831
nominal value for l^(0), elastic
static const double l_2_el = 0.0002
nominal value for l^(2), elastic
static const double h_0_an = 0.6078
nominal value for h^(0), anelastic
static const double h_2_an = -0.0006
nominal value for h^(2), anelastic
static const double l_0_an = 0.0847
nominal value for l^(0), anelastic
static const double l_2_an = 0.0002
nominal value for l^(2), anelastic
Friends
Vector3 operator- (const Vector3 &)
Vector3 operator- (const Vector3 &, const Vector3 &)
Vector3 operator+ (const Vector3 &, const Vector3 &)
Vector3 operator/ (const Vector3 &, double)
Vector3 operator* (const Vector3 &, double)
Vector3 operator* (double, const Vector3 &)
double operator* (const Vector3 &, const Vector3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Vector3 operator% (const Vector3 &, const Vector3 &)
QDataStream & operator<< (QDataStream &s, const Vector3 &v)
QDataStream & operator>> (QDataStream &s, Vector3 &v)
Detailed Description
Station's displacement due to Solid Earth Tides (general interface)'. Inherits Vector3, represents local displacement in TRF'.
Definition at line 103 of file SbGeoTide.H'.
Constructor & Destructor Documentation
SBSolidTideLd::SBSolidTideLd (const SBConfig *Cfg_)"A constructor'. Creates a copy of object, inits love numbers with the corresponded values (anelastic or elastic case)'.
A constructor'. Creates a copy of object'.
Definition at line 290 of file SbGeoTide.C'.
References Cfg, CoeffMoon, CoeffSun, h_0, h_0_an, h_0_el, h_2, h_2_an, h_2_el, SBConfig::isSolidTideAnelastic(), l_0, l_0_an, l_0_el, l_2, l_2_an, and l_2_el.
virtual SBSolidTideLd::~SBSolidTideLd () [inline, virtual]"A destructor'.
Definition at line 163 of file SbGeoTide.H'.
Member Function Documentation
double Vector3::at (DIRECTIONi) const [inline, inherited]
Definition at line 72 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBStationEditor::acquireData(), SBDelay::calc(), SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBTestEphem::createWidget4Test(), SBPlateMotion::displacement(), SBTestEphem::displayCoo(), SBTestAPLoad::fillData4Plotting(), SBEccListItem::key(), SBCoordsListItem::key(), SBRunManager::makeReportMaps(), Matrix3::Matrix3(), operator<<(), SB_TRF::prepareEccs4Session(), SBRefraction::refrDir(), SBStationEcc::registerEcc(), SBCoordsEditor::SBCoordsEditor(), sinex_SiteEccentricityBlock(), sinex_tro_StaCoordinatesBlock(), SBEccListItem::text(), SBCoordsListItem::text(), SBPlateEntry::velocity(), SBPlateMotion::velocity(), SBStationEditor::wCoordinates(), and SBSiteEditor::wSite().
virtual QString SBSolidTideLd::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from Vector3'.
Reimplemented in SBSolidTideLdIERS96, and SBSolidTideLdIERS92'.
Definition at line 165 of file SbGeoTide.H'.
Referenced by operator()().
void Vector3::clear () [inline, inherited]
Definition at line 79 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), and operator()().
Vector3 SBSolidTideLd::deg2InPhase (SBStation *Station, const Vector3 &B) [protected, virtual]
Definition at line 349 of file SbGeoTide.C'.
References h2(), l2(), Vector3::module(), SBStation::p_TideLag(), Vector3::phi(), SBStation::rt(), Vector3::unify(), SBParameter::v(), and Z_AXIS.
Referenced by makeStep1().
Vector3 SBSolidTideLd::dTide_dH2 (SBStation *Station, SBEphem *Ephem)
Definition at line 408 of file SbGeoTide.C'.
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), Vector3::module(), Moon_TRS, SBStation::rt(), SBEphem::sun(), Sun_TRS, and Vector3::unit().
Referenced by SBDelay::calcDerivatives().
Vector3 SBSolidTideLd::dTide_dL2 (SBStation *Station, SBEphem *Ephem)
Definition at line 435 of file SbGeoTide.C'.
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), Vector3::module(), Moon_TRS, SBStation::rt(), SBEphem::sun(), Sun_TRS, and Vector3::unit().
Referenced by SBDelay::calcDerivatives().
Vector3 SBSolidTideLd::dTide_dLag (SBStation *Station, SBEphem *Ephem)
Definition at line 364 of file SbGeoTide.C'.
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), h2(), l2(), Vector3::module(), Moon_TRS, SBStation::p_TideLag(), Vector3::phi(), SBStation::rt(), SBEphem::sun(), Sun_TRS, SBParameter::v(), and Z_AXIS.
Referenced by SBDelay::calcDerivatives().
double SBSolidTideLd::h2 (doublephi, SBStation *Station) const [protected, virtual]"Returns Love number h_2'. Returns nominal Love number h_2 (in the case of no latitude dependancy) or latitude dependent h_2'.
Reimplemented in SBSolidTideLdIERS92'.
Definition at line 315 of file SbGeoTide.C'.
References Cfg, h_0, h_2, SBConfig::isSolidTideLatDepend(), SBStation::p_TideH2(), and SBParameter::v().
Referenced by deg2InPhase(), dTide_dLag(), and SBSolidTideLdIERS96::permTide().
virtual double SBSolidTideLd::h3 () const [inline, protected, virtual]"Returns Love number h_3'.
Definition at line 146 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96::deg3InPhase().
double SBSolidTideLd::l2 (doublephi, SBStation *Station) const [protected, virtual]"Returns Love number l_2'. Returns nominal Love number l_2 (in the case of no latitude dependancy) or latitude dependent l_2'.
Reimplemented in SBSolidTideLdIERS92'.
Definition at line 327 of file SbGeoTide.C'.
References Cfg, SBConfig::isSolidTideLatDepend(), l_0, l_2, SBStation::p_TideL2(), and SBParameter::v().
Referenced by deg2InPhase(), dTide_dLag(), and SBSolidTideLdIERS96::permTide().
virtual double SBSolidTideLd::l3 () const [inline, protected, virtual]"Returns Love number l_3'.
Definition at line 148 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96::deg3InPhase().
double Vector3::lambda () const [inline, inherited]
Definition at line 75 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), and operator()().
const Vector3 & SBSolidTideLd::makeStep1 (SBStation *Station, SBEphem *Ephem) [protected, virtual]
Reimplemented in SBSolidTideLdIERS96'.
Definition at line 462 of file SbGeoTide.C'.
References CoeffMoon, CoeffSun, deg2InPhase(), SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), Vector3::module(), Moon_TRS, SBStation::rt(), Step1, SBEphem::sun(), Sun_TRS, and TideDeg2ip.
Referenced by operator()().
const Vector3 & SBSolidTideLd::makeStep2 (SBStation *St, const SBFrame &Frame) [protected, virtual]
Reimplemented in SBSolidTideLdIERS96'.
Definition at line 480 of file SbGeoTide.C'.
References FmREN, SBFrame::gmst(), SBStation::latitude(), SBStation::longitude(), Step2, and Vector3::Vector3().
Referenced by operator()().
double Vector3::module () const [inline, inherited]
Definition at line 73 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBSolidTideLdIERS96::deg3InPhase(), SBTestEphem::displayCoo(), dTide_dH2(), dTide_dL2(), dTide_dLag(), SBStationImport::importITRF(), Vector3::lambda(), SBSolidTideLdIERS96::latDepend(), SBRunManager::makeReportMaps(), makeStep1(), Vector3::phi(), Vector3::report2Log(), Vector3::unify(), and Vector3::unit().
bool Vector3::operator!= (const Vector3 &v) const [inline, inherited]
Definition at line 102 of file SbVector3.H'.
const Vector3 & SBSolidTideLd::operator() (SBStation *Station, SBEphem *Ephem, const SBFrame &Frame) [virtual]"Calculates site's displacement vector corresponds to time T'. Calls SBSolidTideLd::makeStep1() and SBSolidTideLd::makeStep1(), then, if it is necessary, removes permanent tide'.
Definition at line 486 of file SbGeoTide.C'.
References Cfg, ClassName(), Vector3::clear(), CoeffMoon, CoeffSun, SBFrame::crs2trs(), SBLog::DBG, SBEphem::earth(), EAST, SBLog::ERR, SBMJD::F_MJD, SBMJD::F_Short, FmREN, SBStation::fmVEN(), SBEphem::geoMoon(), SBStation::id(), SBLog::isEligible(), SBConfig::isRemovePermTide(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), Vector3::lambda(), Log, makeStep1(), makeStep2(), Moon_TRS, SBNamed::name(), NORT, permTide(), Vector3::phi(), SBCelestBody::r(), Vector3::report2Log(), Matrix3::report2Log(), SBStation::rt(), Step1, Step2, SBEphem::sun(), Sun_TRS, SBTime::TAI(), SBLog::TIDES, SBFrame::time(), SBMJD::toString(), SBStationID::toString(), and SBLog::write().
Vector3 & Vector3::operator*= (doublev) [inline, inherited]
Definition at line 247 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator+= (const Vector3 &V) [inline, inherited]
Definition at line 235 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator-= (const Vector3 &V) [inline, inherited]
Definition at line 241 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator/= (doublev) [inline, inherited]
Definition at line 253 of file SbVector3.H'.
References Vector3::vec.
bool Vector3::operator== (const Vector3 &v) const [inline, inherited]
Definition at line 100 of file SbVector3.H'.
References Vector3::vec.
double& Vector3::operator[] (DIRECTIONi) [inline, inherited]
Definition at line 71 of file SbVector3.H'.
References Vector3::vec.
Vector3 SBSolidTideLd::permTide (SBStation *St) [protected, virtual]"Returns permanent tide displacement (TRF coordinate system)'.
Reimplemented in SBSolidTideLdIERS96'.
Definition at line 339 of file SbGeoTide.C'.
References SBStation::fmVEN(), Vector3::phi(), SBStation::rt(), sincos(), and Vector3::Vector3().
Referenced by operator()().
double Vector3::phi () const [inline, inherited]
Definition at line 74 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), dTide_dLag(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), operator()(), permTide(), and SBSolidTideLdIERS96::permTide().
void Vector3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref, intw_, intd_, doubleScale = 1.0) const [virtual, inherited]
Definition at line 39 of file SbVector3.C'.
References Log, Vector3::module(), Vector3::vec, and SBLog::write().
Referenced by SBStation::axisOffsetLenght(), SBDelay::calc(), SBEphem::calc(), SBAploEphem::displacement(), operator()(), SBTideLd::operator()(), and SBRefraction::operator()().
const Vector3& SBSolidTideLd::step1 () const [inline]
Definition at line 176 of file SbGeoTide.H'.
References Step1.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::step2 () const [inline]
Definition at line 177 of file SbGeoTide.H'.
References Step2.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideDeg2ip () const [inline]
Definition at line 171 of file SbGeoTide.H'.
References TideDeg2ip.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideDeg2op () const [inline]
Definition at line 173 of file SbGeoTide.H'.
References TideDeg2op.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideDeg3ip () const [inline]
Definition at line 172 of file SbGeoTide.H'.
References TideDeg3ip.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideLatDepend () const [inline]
Definition at line 174 of file SbGeoTide.H'.
References TideLatDepend.
Referenced by SBTestSolidTides::fillData4Plotting().
Vector3& Vector3::unify () [inline, inherited]
Definition at line 77 of file SbVector3.H'.
References Vector3::module().
Referenced by SBDelay::calc(), deg2InPhase(), SBSolidTideLdIERS96::deg3InPhase(), and SBSolidTideLdIERS96::latDepend().
Vector3 Vector3::unit () const [inline, inherited]
Definition at line 78 of file SbVector3.H'.
References Vector3::module(), and Vector3::Vector3().
Referenced by SBDelay::calc(), SBRunManager::constraintStationVeloc(), dTide_dH2(), and dTide_dL2().
Friends And Related Function Documentation
Vector3 operator% (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a vector product of two vectors (because '%' has a priority of '*')
makes vector product of two vectors'.
Definition at line 326 of file SbVector3.H'.
Vector3 operator* (const Vector3 &V1, doublev2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 302 of file SbVector3.H'.
Vector3 operator* (doublev1, const Vector3 &V2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 310 of file SbVector3.H'.
double operator* (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a scalar product of two vectors
makes scalar product of two vectors'.
Definition at line 318 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &M, const Vector3 &V) [friend, inherited]"makes a product of matrix and vector
Matrix3 makes product of matrix and vector'.
Definition at line 519 of file SbVector3.H'.
Vector3 operator+ (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 278 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V) [friend, inherited]
Definition at line 270 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 286 of file SbVector3.H'.
Vector3 operator/ (const Vector3 &V1, doublev2) [friend, inherited]
Definition at line 294 of file SbVector3.H'.
QDataStream& operator<< (QDataStream &s, const Vector3 &v) [friend, inherited]
Definition at line 103 of file SbVector3.H'.
QDataStream& operator>> (QDataStream &s, Vector3 &v) [friend, inherited]
Definition at line 105 of file SbVector3.H'.
Member Data Documentation
const SBConfig* SBSolidTideLd::Cfg [protected]
Definition at line 106 of file SbGeoTide.H'.
Referenced by h2(), l2(), SBSolidTideLdIERS96::makeStep1(), SBSolidTideLdIERS96::makeStep2(), operator()(), SBSolidTideLd(), and SBSolidTideLdIERS96::SBSolidTideLdIERS96().
double SBSolidTideLd::CoeffMoon [protected]
Definition at line 129 of file SbGeoTide.H'.
Referenced by makeStep1(), operator()(), and SBSolidTideLd().
double SBSolidTideLd::CoeffSun [protected]
Definition at line 128 of file SbGeoTide.H'.
Referenced by makeStep1(), operator()(), and SBSolidTideLd().
Matrix3 SBSolidTideLd::FmREN [protected]
transforms local radial-transverse coords to TRF
Definition at line 134 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96::deg2OutPhase(), SBSolidTideLdIERS96::latDepend(), makeStep2(), SBSolidTideLdIERS96::makeStep2(), and operator()().
double SBSolidTideLd::h_0 [protected]
Definition at line 116 of file SbGeoTide.H'.
Referenced by h2(), and SBSolidTideLd().
const double SBSolidTideLd::h_0_an = 0.6078 [static, protected]
nominal value for h^(0), anelastic
Definition at line 111 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
const double SBSolidTideLd::h_0_el = 0.6026 [static, protected]
nominal value for h^(0), elastic
Definition at line 107 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
double SBSolidTideLd::h_2 [protected]
Definition at line 117 of file SbGeoTide.H'.
Referenced by h2(), and SBSolidTideLd().
const double SBSolidTideLd::h_2_an = -0.0006 [static, protected]
nominal value for h^(2), anelastic
Definition at line 112 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
const double SBSolidTideLd::h_2_el = -0.0006 [static, protected]
nominal value for h^(2), elastic
Definition at line 108 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
double SBSolidTideLd::l_0 [protected]
Definition at line 118 of file SbGeoTide.H'.
Referenced by l2(), and SBSolidTideLd().
const double SBSolidTideLd::l_0_an = 0.0847 [static, protected]
nominal value for l^(0), anelastic
Definition at line 113 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
const double SBSolidTideLd::l_0_el = 0.0831 [static, protected]
nominal value for l^(0), elastic
Definition at line 109 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
double SBSolidTideLd::l_2 [protected]
Definition at line 119 of file SbGeoTide.H'.
Referenced by l2(), and SBSolidTideLd().
const double SBSolidTideLd::l_2_an = 0.0002 [static, protected]
nominal value for l^(2), anelastic
Definition at line 114 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
const double SBSolidTideLd::l_2_el = 0.0002 [static, protected]
nominal value for l^(2), elastic
Definition at line 110 of file SbGeoTide.H'.
Referenced by SBSolidTideLd().
Vector3 SBSolidTideLd::Moon_TRS [protected]
Definition at line 132 of file SbGeoTide.H'.
Referenced by dTide_dH2(), dTide_dL2(), dTide_dLag(), makeStep1(), SBSolidTideLdIERS96::makeStep1(), and operator()().
Vector3 SBSolidTideLd::Step1 [protected]
Definition at line 125 of file SbGeoTide.H'.
Referenced by makeStep1(), SBSolidTideLdIERS96::makeStep1(), operator()(), and step1().
Vector3 SBSolidTideLd::Step2 [protected]
Definition at line 126 of file SbGeoTide.H'.
Referenced by makeStep2(), SBSolidTideLdIERS96::makeStep2(), operator()(), and step2().
Vector3 SBSolidTideLd::Sun_TRS [protected]
Definition at line 133 of file SbGeoTide.H'.
Referenced by dTide_dH2(), dTide_dL2(), dTide_dLag(), makeStep1(), SBSolidTideLdIERS96::makeStep1(), and operator()().
Vector3 SBSolidTideLd::TideDeg2ip [protected]
Definition at line 121 of file SbGeoTide.H'.
Referenced by makeStep1(), SBSolidTideLdIERS96::makeStep1(), and tideDeg2ip().
Vector3 SBSolidTideLd::TideDeg2op [protected]
Definition at line 123 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96::makeStep1(), and tideDeg2op().
Vector3 SBSolidTideLd::TideDeg3ip [protected]
Definition at line 122 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96::makeStep1(), and tideDeg3ip().
Vector3 SBSolidTideLd::TideLatDepend [protected]
Definition at line 124 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96::makeStep1(), and tideLatDepend().
double Vector3::vec[3] [protected, inherited]
Definition at line 53 of file SbVector3.H'.
Referenced by Vector3::at(), Vector3::clear(), Vector3::lambda(), Vector3::module(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), Vector3::operator*=(), Vector3::operator+=(), Vector3::operator-=(), Vector3::operator/=(), Vector3::operator=(), Vector3::operator==(), Vector3::operator[](), Vector3::phi(), Vector3::report2Log(), and Vector3::Vector3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.