SBSolidTideLdIERS96
NAME
SBSolidTideLdIERS96 -
SYNOPSIS
#include <SbGeoTide.H>
Inherits SBSolidTideLd'.
Classes
struct TableEntry73a
struct TableEntry73b
Public Member Functions
SBSolidTideLdIERS96 (const SBConfig *)
virtual QString ClassName () const
virtual const Vector3 & operator() (SBStation *, SBEphem *, const SBFrame &)
const Vector3 & tideDeg2ip () const
const Vector3 & tideDeg3ip () const
const Vector3 & tideDeg2op () const
const Vector3 & tideLatDepend () const
const Vector3 & step1 () const
const Vector3 & step2 () const
Vector3 dTide_dLag (SBStation *, SBEphem *)
Vector3 dTide_dH2 (SBStation *, SBEphem *)
Vector3 dTide_dL2 (SBStation *, SBEphem *)
double & operator[] (DIRECTION i)
double at (DIRECTION i) const
double module () const
double phi () const
double lambda () const
Vector3 & unify ()
Vector3 unit () const
void clear ()
Vector3 & operator+= (const Vector3 &)
Vector3 & operator-= (const Vector3 &)
Vector3 & operator*= (double)
Vector3 & operator/= (double)
virtual void report2Log (SBLog::LogLevel, uint, const QString &, int, int, double=1.0) const
bool operator== (const Vector3 &v) const
bool operator!= (const Vector3 &v) const
Protected Member Functions
virtual double h_Id () const
virtual double l_Id () const
virtual double h_Is () const
virtual double l_Is () const
virtual double l_1d () const
virtual double l_1s () const
virtual Vector3 deg3InPhase (const Vector3 &, const Vector3 &)
virtual Vector3 deg2OutPhase (const Vector3 &, const Vector3 &)
virtual Vector3 latDepend (const Vector3 &St, const Vector3 &B)
virtual const Vector3 & makeStep1 (SBStation *, SBEphem *)
virtual const Vector3 & makeStep2 (SBStation *, const SBFrame &)
virtual Vector3 permTide (SBStation *)
virtual double h2 (double phi, SBStation *) const
virtual double l2 (double phi, SBStation *) const
virtual double h3 () const
virtual double l3 () const
virtual Vector3 deg2InPhase (SBStation *, const Vector3 &)
Protected Attributes
const TableEntry73a * Tab_73a
const TableEntry73b * Tab_73b
const SBConfig * Cfg
double h_0
double h_2
double l_0
double l_2
Vector3 TideDeg2ip
Vector3 TideDeg3ip
Vector3 TideDeg2op
Vector3 TideLatDepend
Vector3 Step1
Vector3 Step2
double CoeffSun
double CoeffMoon
Vector3 Moon_TRS
Vector3 Sun_TRS
Matrix3 FmREN
transforms local radial-transverse coords to TRF
double vec [3]
Static Protected Attributes
static const TableEntry73a Table_73a_el [11]
static const TableEntry73a Table_73a_an [11]
static const TableEntry73b Table_73b_el [5]
static const TableEntry73b Table_73b_an [5]
static const double h_0_el = 0.6026
nominal value for h^(0), elastic
static const double h_2_el = -0.0006
nominal value for h^(2), elastic
static const double l_0_el = 0.0831
nominal value for l^(0), elastic
static const double l_2_el = 0.0002
nominal value for l^(2), elastic
static const double h_0_an = 0.6078
nominal value for h^(0), anelastic
static const double h_2_an = -0.0006
nominal value for h^(2), anelastic
static const double l_0_an = 0.0847
nominal value for l^(0), anelastic
static const double l_2_an = 0.0002
nominal value for l^(2), anelastic
Friends
Vector3 operator- (const Vector3 &)
Vector3 operator- (const Vector3 &, const Vector3 &)
Vector3 operator+ (const Vector3 &, const Vector3 &)
Vector3 operator/ (const Vector3 &, double)
Vector3 operator* (const Vector3 &, double)
Vector3 operator* (double, const Vector3 &)
double operator* (const Vector3 &, const Vector3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
Vector3 operator% (const Vector3 &, const Vector3 &)
QDataStream & operator<< (QDataStream &s, const Vector3 &v)
QDataStream & operator>> (QDataStream &s, Vector3 &v)
Detailed Description
Station's displacement due to Solid Earth Tides, IERS96 Standards model'. Inherits Vector3 representing local displacement in TRF'.
Definition at line 212 of file SbGeoTide.H'.
Constructor & Destructor Documentation
SBSolidTideLdIERS96::SBSolidTideLdIERS96 (const SBConfig *Cfg_)"A constructor'.
Definition at line 582 of file SbGeoTide.C'.
References SBSolidTideLd::Cfg, SBConfig::isSolidTideAnelastic(), Tab_73a, Tab_73b, Table_73a_an, Table_73a_el, Table_73b_an, and Table_73b_el.
Member Function Documentation
double Vector3::at (DIRECTIONi) const [inline, inherited]
Definition at line 72 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBStationEditor::acquireData(), SBDelay::calc(), SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBTestEphem::createWidget4Test(), SBPlateMotion::displacement(), SBTestEphem::displayCoo(), SBTestAPLoad::fillData4Plotting(), SBEccListItem::key(), SBCoordsListItem::key(), SBRunManager::makeReportMaps(), Matrix3::Matrix3(), operator<<(), SB_TRF::prepareEccs4Session(), SBRefraction::refrDir(), SBStationEcc::registerEcc(), SBCoordsEditor::SBCoordsEditor(), sinex_SiteEccentricityBlock(), sinex_tro_StaCoordinatesBlock(), SBEccListItem::text(), SBCoordsListItem::text(), SBPlateEntry::velocity(), SBPlateMotion::velocity(), SBStationEditor::wCoordinates(), and SBSiteEditor::wSite().
virtual QString SBSolidTideLdIERS96::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBSolidTideLd'.
Definition at line 248 of file SbGeoTide.H'.
void Vector3::clear () [inline, inherited]
Definition at line 79 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), and SBSolidTideLd::operator()().
Vector3 SBSolidTideLd::deg2InPhase (SBStation *Station, const Vector3 &B) [protected, virtual, inherited]
Definition at line 349 of file SbGeoTide.C'.
References SBSolidTideLd::h2(), SBSolidTideLd::l2(), Vector3::module(), SBStation::p_TideLag(), Vector3::phi(), SBStation::rt(), Vector3::unify(), SBParameter::v(), and Z_AXIS.
Referenced by SBSolidTideLd::makeStep1().
Vector3 SBSolidTideLdIERS96::deg2OutPhase (const Vector3 &St, const Vector3 &B) [protected, virtual]"Calculates term from eqs'.(13), (14), IERS Standards 1996'. Calculates corresponded j-th celestial body degree 2 out-of-phase contribution from diurnal and semidiurnal tides term'. The term is not scaled by GMj/GMearth'.
Definition at line 611 of file SbGeoTide.C'.
References SBSolidTideLd::FmREN, h_Id(), h_Is(), l_Id(), l_Is(), Vector3::lambda(), Vector3::module(), Vector3::phi(), sincos(), and Vector3::Vector3().
Referenced by makeStep1().
Vector3 SBSolidTideLdIERS96::deg3InPhase (const Vector3 &St, const Vector3 &B) [protected, virtual]"Calculates term from eq'.(9), IERS Standards 1996'. Calculates corresponded j-th celestial body degree 3 in-phase tide contribution term'. The term is not scaled by GMj/GMearth'.
Definition at line 592 of file SbGeoTide.C'.
References SBSolidTideLd::h3(), SBSolidTideLd::l3(), Vector3::module(), and Vector3::unify().
Referenced by makeStep1().
Vector3 SBSolidTideLd::dTide_dH2 (SBStation *Station, SBEphem *Ephem) [inherited]
Definition at line 408 of file SbGeoTide.C'.
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), Vector3::module(), SBSolidTideLd::Moon_TRS, SBStation::rt(), SBEphem::sun(), SBSolidTideLd::Sun_TRS, and Vector3::unit().
Referenced by SBDelay::calcDerivatives().
Vector3 SBSolidTideLd::dTide_dL2 (SBStation *Station, SBEphem *Ephem) [inherited]
Definition at line 435 of file SbGeoTide.C'.
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), Vector3::module(), SBSolidTideLd::Moon_TRS, SBStation::rt(), SBEphem::sun(), SBSolidTideLd::Sun_TRS, and Vector3::unit().
Referenced by SBDelay::calcDerivatives().
Vector3 SBSolidTideLd::dTide_dLag (SBStation *Station, SBEphem *Ephem) [inherited]
Definition at line 364 of file SbGeoTide.C'.
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), SBSolidTideLd::h2(), SBSolidTideLd::l2(), Vector3::module(), SBSolidTideLd::Moon_TRS, SBStation::p_TideLag(), Vector3::phi(), SBStation::rt(), SBEphem::sun(), SBSolidTideLd::Sun_TRS, SBParameter::v(), and Z_AXIS.
Referenced by SBDelay::calcDerivatives().
double SBSolidTideLd::h2 (doublephi, SBStation *Station) const [protected, virtual, inherited]"Returns Love number h_2'. Returns nominal Love number h_2 (in the case of no latitude dependancy) or latitude dependent h_2'.
Reimplemented in SBSolidTideLdIERS92'.
Definition at line 315 of file SbGeoTide.C'.
References SBSolidTideLd::Cfg, SBSolidTideLd::h_0, SBSolidTideLd::h_2, SBConfig::isSolidTideLatDepend(), SBStation::p_TideH2(), and SBParameter::v().
Referenced by SBSolidTideLd::deg2InPhase(), SBSolidTideLd::dTide_dLag(), and permTide().
virtual double SBSolidTideLd::h3 () const [inline, protected, virtual, inherited]"Returns Love number h_3'.
Definition at line 146 of file SbGeoTide.H'.
Referenced by deg3InPhase().
virtual double SBSolidTideLdIERS96::h_Id () const [inline, protected, virtual]
Definition at line 232 of file SbGeoTide.H'.
Referenced by deg2OutPhase().
virtual double SBSolidTideLdIERS96::h_Is () const [inline, protected, virtual]
Definition at line 234 of file SbGeoTide.H'.
Referenced by deg2OutPhase().
double SBSolidTideLd::l2 (doublephi, SBStation *Station) const [protected, virtual, inherited]"Returns Love number l_2'. Returns nominal Love number l_2 (in the case of no latitude dependancy) or latitude dependent l_2'.
Reimplemented in SBSolidTideLdIERS92'.
Definition at line 327 of file SbGeoTide.C'.
References SBSolidTideLd::Cfg, SBConfig::isSolidTideLatDepend(), SBSolidTideLd::l_0, SBSolidTideLd::l_2, SBStation::p_TideL2(), and SBParameter::v().
Referenced by SBSolidTideLd::deg2InPhase(), SBSolidTideLd::dTide_dLag(), and permTide().
virtual double SBSolidTideLd::l3 () const [inline, protected, virtual, inherited]"Returns Love number l_3'.
Definition at line 148 of file SbGeoTide.H'.
Referenced by deg3InPhase().
virtual double SBSolidTideLdIERS96::l_1d () const [inline, protected, virtual]
Definition at line 236 of file SbGeoTide.H'.
Referenced by latDepend().
virtual double SBSolidTideLdIERS96::l_1s () const [inline, protected, virtual]
Definition at line 237 of file SbGeoTide.H'.
Referenced by latDepend().
virtual double SBSolidTideLdIERS96::l_Id () const [inline, protected, virtual]
Definition at line 233 of file SbGeoTide.H'.
Referenced by deg2OutPhase().
virtual double SBSolidTideLdIERS96::l_Is () const [inline, protected, virtual]
Definition at line 235 of file SbGeoTide.H'.
Referenced by deg2OutPhase().
double Vector3::lambda () const [inline, inherited]
Definition at line 75 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by deg2OutPhase(), SBTestEphem::displayCoo(), latDepend(), makeStep2(), and SBSolidTideLd::operator()().
Vector3 SBSolidTideLdIERS96::latDepend (const Vector3 &St, const Vector3 &B) [protected, virtual]"Calculates term from eqs'.(11), (12), IERS Standards 1996'. Calculates transverse displacement due to l(1) term corresponded to j-th celestial body'. The term is not scaled by GMj/GMearth'.
Definition at line 650 of file SbGeoTide.C'.
References SBSolidTideLd::FmREN, l_1d(), l_1s(), Vector3::lambda(), Vector3::module(), Vector3::phi(), sincos(), Vector3::unify(), Vector3::Vector3(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by makeStep1().
const Vector3 & SBSolidTideLdIERS96::makeStep1 (SBStation *Station, SBEphem *Ephem) [protected, virtual]
Reimplemented from SBSolidTideLd'.
Definition at line 687 of file SbGeoTide.C'.
References SBSolidTideLd::Cfg, deg2OutPhase(), deg3InPhase(), SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), latDepend(), SBSolidTideLd::Moon_TRS, SBStation::rt(), SBSolidTideLd::Step1, SBEphem::sun(), SBSolidTideLd::Sun_TRS, SBSolidTideLd::TideDeg2ip, SBSolidTideLd::TideDeg2op, SBSolidTideLd::TideDeg3ip, SBSolidTideLd::TideLatDepend, and v3Zero.
const Vector3 & SBSolidTideLdIERS96::makeStep2 (SBStation *St, const SBFrame &Frame) [protected, virtual]
Reimplemented from SBSolidTideLd'.
Definition at line 703 of file SbGeoTide.C'.
References SBSolidTideLd::Cfg, SBSolidTideLdIERS96::TableEntry73a::DR, SBSolidTideLdIERS96::TableEntry73b::DRip, SBSolidTideLdIERS96::TableEntry73b::DRop, SBSolidTideLdIERS96::TableEntry73a::DT, SBSolidTideLdIERS96::TableEntry73b::DTip, SBSolidTideLdIERS96::TableEntry73b::DTop, SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), SBSolidTideLd::FmREN, SBFrame::gmst(), SBConfig::isSolidTideAnelastic(), Vector3::lambda(), SBSolidTideLdIERS96::TableEntry73a::N, SBSolidTideLdIERS96::TableEntry73b::N, Vector3::phi(), SBStation::rt(), sincos(), SBSolidTideLd::Step2, Tab_73a, Tab_73b, SBFrame::time(), and Vector3::Vector3().
double Vector3::module () const [inline, inherited]
Definition at line 73 of file SbVector3.H'.
References Vector3::vec.
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), deg2OutPhase(), deg3InPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBStationImport::importITRF(), Vector3::lambda(), latDepend(), SBRunManager::makeReportMaps(), SBSolidTideLd::makeStep1(), Vector3::phi(), Vector3::report2Log(), Vector3::unify(), and Vector3::unit().
bool Vector3::operator!= (const Vector3 &v) const [inline, inherited]
Definition at line 102 of file SbVector3.H'.
const Vector3 & SBSolidTideLd::operator() (SBStation *Station, SBEphem *Ephem, const SBFrame &Frame) [virtual, inherited]"Calculates site's displacement vector corresponds to time T'. Calls SBSolidTideLd::makeStep1() and SBSolidTideLd::makeStep1(), then, if it is necessary, removes permanent tide'.
Definition at line 486 of file SbGeoTide.C'.
References SBSolidTideLd::Cfg, SBSolidTideLd::ClassName(), Vector3::clear(), SBSolidTideLd::CoeffMoon, SBSolidTideLd::CoeffSun, SBFrame::crs2trs(), SBLog::DBG, SBEphem::earth(), EAST, SBLog::ERR, SBMJD::F_MJD, SBMJD::F_Short, SBSolidTideLd::FmREN, SBStation::fmVEN(), SBEphem::geoMoon(), SBStation::id(), SBLog::isEligible(), SBConfig::isRemovePermTide(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), Vector3::lambda(), Log, SBSolidTideLd::makeStep1(), SBSolidTideLd::makeStep2(), SBSolidTideLd::Moon_TRS, SBNamed::name(), NORT, SBSolidTideLd::permTide(), Vector3::phi(), SBCelestBody::r(), Vector3::report2Log(), Matrix3::report2Log(), SBStation::rt(), SBSolidTideLd::Step1, SBSolidTideLd::Step2, SBEphem::sun(), SBSolidTideLd::Sun_TRS, SBTime::TAI(), SBLog::TIDES, SBFrame::time(), SBMJD::toString(), SBStationID::toString(), and SBLog::write().
Vector3 & Vector3::operator*= (doublev) [inline, inherited]
Definition at line 247 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator+= (const Vector3 &V) [inline, inherited]
Definition at line 235 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator-= (const Vector3 &V) [inline, inherited]
Definition at line 241 of file SbVector3.H'.
References Vector3::vec.
Vector3 & Vector3::operator/= (doublev) [inline, inherited]
Definition at line 253 of file SbVector3.H'.
References Vector3::vec.
bool Vector3::operator== (const Vector3 &v) const [inline, inherited]
Definition at line 100 of file SbVector3.H'.
References Vector3::vec.
double& Vector3::operator[] (DIRECTIONi) [inline, inherited]
Definition at line 71 of file SbVector3.H'.
References Vector3::vec.
Vector3 SBSolidTideLdIERS96::permTide (SBStation *St) [protected, virtual]"Returns permanent tide displacement (TRF coordinate system)'.
Reimplemented from SBSolidTideLd'.
Definition at line 748 of file SbGeoTide.C'.
References SBStation::fmVEN(), SBSolidTideLd::h2(), SBSolidTideLd::l2(), Vector3::phi(), SBStation::rt(), sincos(), and Vector3::Vector3().
double Vector3::phi () const [inline, inherited]
Definition at line 74 of file SbVector3.H'.
References Vector3::module(), and Vector3::vec.
Referenced by SBSolidTideLd::deg2InPhase(), deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dLag(), latDepend(), makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::permTide(), and permTide().
void Vector3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref, intw_, intd_, doubleScale = 1.0) const [virtual, inherited]
Definition at line 39 of file SbVector3.C'.
References Log, Vector3::module(), Vector3::vec, and SBLog::write().
Referenced by SBStation::axisOffsetLenght(), SBDelay::calc(), SBEphem::calc(), SBAploEphem::displacement(), SBSolidTideLd::operator()(), SBTideLd::operator()(), and SBRefraction::operator()().
const Vector3& SBSolidTideLd::step1 () const [inline, inherited]
Definition at line 176 of file SbGeoTide.H'.
References SBSolidTideLd::Step1.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::step2 () const [inline, inherited]
Definition at line 177 of file SbGeoTide.H'.
References SBSolidTideLd::Step2.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideDeg2ip () const [inline, inherited]
Definition at line 171 of file SbGeoTide.H'.
References SBSolidTideLd::TideDeg2ip.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideDeg2op () const [inline, inherited]
Definition at line 173 of file SbGeoTide.H'.
References SBSolidTideLd::TideDeg2op.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideDeg3ip () const [inline, inherited]
Definition at line 172 of file SbGeoTide.H'.
References SBSolidTideLd::TideDeg3ip.
Referenced by SBTestSolidTides::fillData4Plotting().
const Vector3& SBSolidTideLd::tideLatDepend () const [inline, inherited]
Definition at line 174 of file SbGeoTide.H'.
References SBSolidTideLd::TideLatDepend.
Referenced by SBTestSolidTides::fillData4Plotting().
Vector3& Vector3::unify () [inline, inherited]
Definition at line 77 of file SbVector3.H'.
References Vector3::module().
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), deg3InPhase(), and latDepend().
Vector3 Vector3::unit () const [inline, inherited]
Definition at line 78 of file SbVector3.H'.
References Vector3::module(), and Vector3::Vector3().
Referenced by SBDelay::calc(), SBRunManager::constraintStationVeloc(), SBSolidTideLd::dTide_dH2(), and SBSolidTideLd::dTide_dL2().
Friends And Related Function Documentation
Vector3 operator% (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a vector product of two vectors (because '%' has a priority of '*')
makes vector product of two vectors'.
Definition at line 326 of file SbVector3.H'.
Vector3 operator* (const Vector3 &V1, doublev2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 302 of file SbVector3.H'.
Vector3 operator* (doublev1, const Vector3 &V2) [friend, inherited]"multiplies vector by scalar'.
Definition at line 310 of file SbVector3.H'.
double operator* (const Vector3 &V1, const Vector3 &V2) [friend, inherited]"makes a scalar product of two vectors
makes scalar product of two vectors'.
Definition at line 318 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &M, const Vector3 &V) [friend, inherited]"makes a product of matrix and vector
Matrix3 makes product of matrix and vector'.
Definition at line 519 of file SbVector3.H'.
Vector3 operator+ (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 278 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V) [friend, inherited]
Definition at line 270 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V1, const Vector3 &V2) [friend, inherited]
Definition at line 286 of file SbVector3.H'.
Vector3 operator/ (const Vector3 &V1, doublev2) [friend, inherited]
Definition at line 294 of file SbVector3.H'.
QDataStream& operator<< (QDataStream &s, const Vector3 &v) [friend, inherited]
Definition at line 103 of file SbVector3.H'.
QDataStream& operator>> (QDataStream &s, Vector3 &v) [friend, inherited]
Definition at line 105 of file SbVector3.H'.
Member Data Documentation
const SBConfig* SBSolidTideLd::Cfg [protected, inherited]
Definition at line 106 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::h2(), SBSolidTideLd::l2(), makeStep1(), makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::SBSolidTideLd(), and SBSolidTideLdIERS96().
double SBSolidTideLd::CoeffMoon [protected, inherited]
Definition at line 129 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::makeStep1(), SBSolidTideLd::operator()(), and SBSolidTideLd::SBSolidTideLd().
double SBSolidTideLd::CoeffSun [protected, inherited]
Definition at line 128 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::makeStep1(), SBSolidTideLd::operator()(), and SBSolidTideLd::SBSolidTideLd().
Matrix3 SBSolidTideLd::FmREN [protected, inherited]
transforms local radial-transverse coords to TRF
Definition at line 134 of file SbGeoTide.H'.
Referenced by deg2OutPhase(), latDepend(), SBSolidTideLd::makeStep2(), makeStep2(), and SBSolidTideLd::operator()().
double SBSolidTideLd::h_0 [protected, inherited]
Definition at line 116 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::h2(), and SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::h_0_an = 0.6078 [static, protected, inherited]
nominal value for h^(0), anelastic
Definition at line 111 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::h_0_el = 0.6026 [static, protected, inherited]
nominal value for h^(0), elastic
Definition at line 107 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
double SBSolidTideLd::h_2 [protected, inherited]
Definition at line 117 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::h2(), and SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::h_2_an = -0.0006 [static, protected, inherited]
nominal value for h^(2), anelastic
Definition at line 112 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::h_2_el = -0.0006 [static, protected, inherited]
nominal value for h^(2), elastic
Definition at line 108 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
double SBSolidTideLd::l_0 [protected, inherited]
Definition at line 118 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::l2(), and SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::l_0_an = 0.0847 [static, protected, inherited]
nominal value for l^(0), anelastic
Definition at line 113 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::l_0_el = 0.0831 [static, protected, inherited]
nominal value for l^(0), elastic
Definition at line 109 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
double SBSolidTideLd::l_2 [protected, inherited]
Definition at line 119 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::l2(), and SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::l_2_an = 0.0002 [static, protected, inherited]
nominal value for l^(2), anelastic
Definition at line 114 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
const double SBSolidTideLd::l_2_el = 0.0002 [static, protected, inherited]
nominal value for l^(2), elastic
Definition at line 110 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::SBSolidTideLd().
Vector3 SBSolidTideLd::Moon_TRS [protected, inherited]
Definition at line 132 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), makeStep1(), and SBSolidTideLd::operator()().
Vector3 SBSolidTideLd::Step1 [protected, inherited]
Definition at line 125 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::makeStep1(), makeStep1(), SBSolidTideLd::operator()(), and SBSolidTideLd::step1().
Vector3 SBSolidTideLd::Step2 [protected, inherited]
Definition at line 126 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::makeStep2(), makeStep2(), SBSolidTideLd::operator()(), and SBSolidTideLd::step2().
Vector3 SBSolidTideLd::Sun_TRS [protected, inherited]
Definition at line 133 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), makeStep1(), and SBSolidTideLd::operator()().
const TableEntry73a* SBSolidTideLdIERS96::Tab_73a [protected]
Definition at line 229 of file SbGeoTide.H'.
Referenced by makeStep2(), and SBSolidTideLdIERS96().
const TableEntry73b* SBSolidTideLdIERS96::Tab_73b [protected]
Definition at line 230 of file SbGeoTide.H'.
Referenced by makeStep2(), and SBSolidTideLdIERS96().
const SBSolidTideLdIERS96::TableEntry73a SBSolidTideLdIERS96::Table_73a_an [static, protected]"Initial value:
{
  { { 1, 0, 2, 0, 2}, -0.09, 0.0 },
  { { 0, 0, 2, 0, 1}, -0.10, 0.0 },
  { { 0, 0, 2, 0, 2}, -0.53, 0.02},
  { { 1, 0, 0, 0, 0}, 0.06, 0.0 },
  { { 0, 1, 2,-2, 2}, -0.05, 0.0 },
  { { 0, 0, 2,-2, 2}, -1.23, 0.07},
  { { 0, 0, 0, 0,-1}, -0.22, 0.01},
  { { 0, 0, 0, 0, 0}, 12.04, -0.72},
  { { 0, 0, 0, 0, 1}, 1.74, -0.10},
  { { 0,-1, 0, 0, 0}, -0.50, 0.03},
  { { 0, 0,-2, 2,-2}, -0.11, 0.01}
}
Definition at line 226 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96().
const SBSolidTideLdIERS96::TableEntry73a SBSolidTideLdIERS96::Table_73a_el [static, protected]"Initial value:
{
  { { 1, 0, 2, 0, 2}, -0.11, -0.01},
  { { 0, 0, 2, 0, 1}, -0.12, -0.01},
  { { 0, 0, 2, 0, 2}, -0.63, -0.04},
  { { 1, 0, 0, 0, 0}, 0.07, 0.0 },
  { { 0, 1, 2,-2, 2}, -0.06, 0.0 },
  { { 0, 0, 2,-2, 2}, -1.29, 0.05},
  { { 0, 0, 0, 0,-1}, -0.23, 0.01},
  { { 0, 0, 0, 0, 0}, 12.25, -0.65},
  { { 0, 0, 0, 0, 1}, 1.77, -0.09},
  { { 0,-1, 0, 0, 0}, -0.51, 0.03},
  { { 0, 0,-2, 2,-2}, -0.11, 0.01}
}
Definition at line 225 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96().
const SBSolidTideLdIERS96::TableEntry73b SBSolidTideLdIERS96::Table_73b_an [static, protected]"Initial value:
{
  { { 0, 0, 0, 0, 1}, 0.47, 0.23, 0.16, 0.07},
  { { 0, 0,-2, 2,-2}, -0.20, -0.12,-0.11,-0.05},
  { {-1, 0, 0, 0, 0}, -0.11, -0.08,-0.09,-0.04},
  { { 0, 0,-2, 0,-2}, -0.13, -0.11,-0.15,-0.07},
  { { 0, 0,-2, 0,-1}, -0.05, -0.05,-0.06,-0.03}
}
Definition at line 228 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96().
const SBSolidTideLdIERS96::TableEntry73b SBSolidTideLdIERS96::Table_73b_el [static, protected]"Initial value:
{
  { { 0, 0, 0, 0, 1}, -0.05, 0.0 , 0.0 , 0.0 },
  { { 0, 0,-2, 2,-2}, 0.05, 0.0 , 0.0 , 0.0 },
  { {-1, 0, 0, 0, 0}, 0.06, 0.0 , 0.0 , 0.0 },
  { { 0, 0,-2, 0,-2}, 0.12, 0.0 , 0.0 , 0.0 },
  { { 0, 0,-2, 0,-1}, 0.05, 0.0 , 0.0 , 0.0 }
}
Definition at line 227 of file SbGeoTide.H'.
Referenced by SBSolidTideLdIERS96().
Vector3 SBSolidTideLd::TideDeg2ip [protected, inherited]
Definition at line 121 of file SbGeoTide.H'.
Referenced by SBSolidTideLd::makeStep1(), makeStep1(), and SBSolidTideLd::tideDeg2ip().
Vector3 SBSolidTideLd::TideDeg2op [protected, inherited]
Definition at line 123 of file SbGeoTide.H'.
Referenced by makeStep1(), and SBSolidTideLd::tideDeg2op().
Vector3 SBSolidTideLd::TideDeg3ip [protected, inherited]
Definition at line 122 of file SbGeoTide.H'.
Referenced by makeStep1(), and SBSolidTideLd::tideDeg3ip().
Vector3 SBSolidTideLd::TideLatDepend [protected, inherited]
Definition at line 124 of file SbGeoTide.H'.
Referenced by makeStep1(), and SBSolidTideLd::tideLatDepend().
double Vector3::vec[3] [protected, inherited]
Definition at line 53 of file SbVector3.H'.
Referenced by Vector3::at(), Vector3::clear(), Vector3::lambda(), Vector3::module(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), Vector3::operator*=(), Vector3::operator+=(), Vector3::operator-=(), Vector3::operator/=(), Vector3::operator=(), Vector3::operator==(), Vector3::operator[](), Vector3::phi(), Vector3::report2Log(), and Vector3::Vector3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.