.TH "SBSolidTideLdIERS96::TableEntry73a" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBSolidTideLdIERS96::TableEntry73a \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoTide\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBN\fP [5]"
.br
.ti -1c
.RI "double \fBDR\fP"
.br
.ti -1c
.RI "double \fBDT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 215 of file SbGeoTide\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBSolidTideLdIERS96::TableEntry73a::DR\fP"
.PP
Definition at line 218 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLdIERS96::makeStep2()\&.
.SS "double \fBSBSolidTideLdIERS96::TableEntry73a::DT\fP"
.PP
Definition at line 218 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLdIERS96::makeStep2()\&.
.SS "short \fBSBSolidTideLdIERS96::TableEntry73a::N\fP[5]"
.PP
Definition at line 217 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLdIERS96::makeStep2()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
