SBSolutionName
NAME
SBSolutionName -
SYNOPSIS
#include <SbGeo.H>
Public Types
enum SNType { TYPE_EOP, TYPE_SSC, TYPE_SSV, TYPE_RSC, TYPE_AAM, TYPE_UNKN }
Public Member Functions
SBSolutionName (SNType Type_=TYPE_UNKN)
SBSolutionName (const SBSolutionName &Solution)
SBSolutionName (SNType Type_, const QString &Acronym_, int Year_=0, Technique Tech_=TECH_VLBI, int Serial_=1)
virtual ~SBSolutionName ()
SNType type () const
Technique tech () const
QString acronym () const
int year () const
int serial () const
void setType (SNType Type_)
void setTech (Technique Tech_)
void setAcronym (const QString &Acronym_)
void setYear (int Year_)
void setSerial (int Serial_)
void setAttr (SNType Type_, const QString &Acronym_, int Year_=0, Technique Tech_=TECH_VLBI, int Serial_=1)
const QString Type2Str () const
const QString Tech2Str () const
const QString Acronym2Str () const
QString toString () const
void fromString (const QString &)
bool operator== (const SBSolutionName &label)
bool operator!= (const SBSolutionName &label)
Static Public Member Functions
static const QString & techAbbrev (Technique T)
static const QString & techName (Technique T)
Static Public Attributes
static const QString TypeNames []
static const QString TechNames []
static const QString Types []
static const QString Techs []
static const QString TechAbbrev []
Protected Attributes
SNType Type
Technique Tech
QString Acronym
int Year
int Serial
Friends
QDataStream & operator<< (QDataStream &, const SBSolutionName &)
QDataStream & operator>> (QDataStream &, SBSolutionName &)
QTextStream & operator<< (QTextStream &, const SBSolutionName &)
QTextStream & operator>> (QTextStream &, SBSolutionName &)
Detailed Description
Definition at line 365 of file SbGeo.H'.
Member Enumeration Documentation
enum SBSolutionName::SNType
Enumerator:
TYPE_EOP
TYPE_SSC
TYPE_SSV
TYPE_RSC
TYPE_AAM
TYPE_UNKN
Definition at line 382 of file SbGeo.H'.
Constructor & Destructor Documentation
SBSolutionName::SBSolutionName (SNTypeType_ = TYPE_UNKN) [inline]
Definition at line 419 of file SbGeo.H'.
References setAttr().
SBSolutionName::SBSolutionName (const SBSolutionName &Solution) [inline]
Definition at line 420 of file SbGeo.H'.
References Acronym, Serial, setAttr(), Tech, Type, and Year.
SBSolutionName::SBSolutionName (SNTypeType_, const QString &Acronym_, intYear_ = 0, TechniqueTech_ = TECH_VLBI, intSerial_ = 1) [inline]
Definition at line 423 of file SbGeo.H'.
References setAttr().
virtual SBSolutionName::~SBSolutionName () [inline, virtual]
Definition at line 427 of file SbGeo.H'.
Member Function Documentation
QString SBSolutionName::acronym () const [inline]
Definition at line 433 of file SbGeo.H'.
References Acronym.
const QString SBSolutionName::Acronym2Str () const [inline]
Definition at line 456 of file SbGeo.H'.
References Acronym, and SBInstitutionList::descr().
void SBSolutionName::fromString (const QString &str)
Definition at line 209 of file SbGeo.C'.
Referenced by SBStuffEOPs::accept(), SBStuffSources::accept(), and SBStuffStations::accept().
bool SBSolutionName::operator!= (const SBSolutionName &label) [inline]
Definition at line 465 of file SbGeo.H'.
bool SBSolutionName::operator== (const SBSolutionName &label) [inline]
Definition at line 461 of file SbGeo.H'.
References Acronym, Serial, Tech, Type, and Year.
int SBSolutionName::serial () const [inline]
Definition at line 435 of file SbGeo.H'.
References Serial.
void SBSolutionName::setAcronym (const QString &Acronym_) [inline]
Definition at line 438 of file SbGeo.H'.
References Acronym.
Referenced by SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF().
void SBSolutionName::setAttr (SNTypeType_, const QString &Acronym_, intYear_ = 0, TechniqueTech_ = TECH_VLBI, intSerial_ = 1) [inline]
Definition at line 441 of file SbGeo.H'.
References Acronym, Serial, Tech, Type, and Year.
Referenced by SBCatalog::SBCatalog(), SBEOP::SBEOP(), and SBSolutionName().
void SBSolutionName::setSerial (intSerial_) [inline]
Definition at line 440 of file SbGeo.H'.
References Serial.
Referenced by SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF().
void SBSolutionName::setTech (TechniqueTech_) [inline]
Definition at line 437 of file SbGeo.H'.
References Tech.
Referenced by SBStationImport::importITRF(), and SB_CRF::SB_CRF().
void SBSolutionName::setType (SNTypeType_) [inline]
Definition at line 436 of file SbGeo.H'.
References Type.
Referenced by SB_CRF::SB_CRF(), and SB_TRF::SB_TRF().
void SBSolutionName::setYear (intYear_) [inline]
Definition at line 439 of file SbGeo.H'.
References Year.
Referenced by SBStationImport::importITRF(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), and SBRunManager::makeReportTRF().
Technique SBSolutionName::tech () const [inline]
Definition at line 432 of file SbGeo.H'.
References Tech.
const QString SBSolutionName::Tech2Str () const [inline]
Definition at line 455 of file SbGeo.H'.
References Tech, and TechNames.
static const QString& SBSolutionName::techAbbrev (TechniqueT) [inline, static]
Definition at line 457 of file SbGeo.H'.
References TechAbbrev.
Referenced by SBTestStationLI::key(), SBStationListItem::text(), and SBTestStationLI::text().
static const QString& SBSolutionName::techName (TechniqueT) [inline, static]
Definition at line 458 of file SbGeo.H'.
References TechNames.
Referenced by SBStationEditor::wTechs().
QString SBSolutionName::toString () const
Definition at line 200 of file SbGeo.C'.
References Acronym, Serial, Tech, Techs, Type, Types, and Year.
Referenced by SBEOP::checkRanges(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffEOPs::createInfoGroup(), SBStuffEOPs::draw(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), operator<<(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), SBTestEOP::SBTestEOP(), and writeNormalEquationSystem().
SNType SBSolutionName::type () const [inline]
Definition at line 431 of file SbGeo.H'.
References Type.
const QString SBSolutionName::Type2Str () const [inline]
Definition at line 454 of file SbGeo.H'.
References Type, and TypeNames.
int SBSolutionName::year () const [inline]
Definition at line 434 of file SbGeo.H'.
References Year.
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBSolutionName &Sol) [friend]
Definition at line 223 of file SbGeo.C'.
QTextStream& operator<< (QTextStream &s, const SBSolutionName &Sol) [friend]
Definition at line 233 of file SbGeo.C'.
QDataStream& operator>> (QDataStream &s, SBSolutionName &Sol) [friend]
Definition at line 228 of file SbGeo.C'.
QTextStream& operator>> (QTextStream &s, SBSolutionName &Sol) [friend]
Definition at line 238 of file SbGeo.C'.
Member Data Documentation
QString SBSolutionName::Acronym [protected]
Definition at line 406 of file SbGeo.H'.
Referenced by acronym(), Acronym2Str(), operator<<(), operator==(), operator>>(), SBSolutionName(), setAcronym(), setAttr(), and toString().
int SBSolutionName::Serial [protected]
Definition at line 408 of file SbGeo.H'.
Referenced by operator<<(), operator==(), operator>>(), SBSolutionName(), serial(), setAttr(), setSerial(), and toString().
Technique SBSolutionName::Tech [protected]
Definition at line 405 of file SbGeo.H'.
Referenced by operator<<(), operator==(), operator>>(), SBSolutionName(), setAttr(), setTech(), tech(), Tech2Str(), and toString().
const QString SBSolutionName::TechAbbrev [static]"Initial value:
 
{ 'VLBI', 'OPTA', 'LLR', 'GPS', 'SLR', 'DORIS', 'COMB', 'CGEOD', 'ATM', 'TIE', 'UNKN'}
Definition at line 415 of file SbGeo.H'.
Referenced by techAbbrev().
const QString SBSolutionName::TechNames [static]"Initial value:
 
{
  'Very Long Baseline Interferometry',
  'Optical Astrometry',
  'Lunar Laser Ranging',
  'Global Positioning System',
  'Satellite Laser Ranging',
  'Doppler Orbit determination and Radiopositioning Intergrated on Satellite',
  'Combination of techniques',
  'Conventional Geodesy (for SSC)',
  'Atmospheric data',
  'TIE (I havn't found what it means)',
  'unknown'
}
Definition at line 412 of file SbGeo.H'.
Referenced by Tech2Str(), and techName().
const QString SBSolutionName::Techs [static]"Initial value:
 
{'R','A','M','P','L','D','C','G','*','T','?'}
Definition at line 414 of file SbGeo.H'.
Referenced by toString().
SNType SBSolutionName::Type [protected]
Definition at line 404 of file SbGeo.H'.
Referenced by operator<<(), operator==(), operator>>(), SBSolutionName(), setAttr(), setType(), toString(), type(), and Type2Str().
const QString SBSolutionName::TypeNames [static]"Initial value:
 
{
  'Earth Orientation Parameters',
  'Sets of Station Coordinates',
  'Sets of Station Velocities',
  'Radio Source Coordinates',
  'Atmospheric Angular Momentum',
  'unknown'
}
Definition at line 411 of file SbGeo.H'.
Referenced by Type2Str().
const QString SBSolutionName::Types [static]"Initial value:
 
{'EOP', 'SSC', 'SSV', 'RSC', 'AAM', '???'}
Definition at line 413 of file SbGeo.H'.
Referenced by toString().
int SBSolutionName::Year [protected]
Definition at line 407 of file SbGeo.H'.
Referenced by operator<<(), operator==(), operator>>(), SBSolutionName(), setAttr(), setYear(), toString(), and year().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.