.TH "SBSolidTideLdIERS96" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBSolidTideLdIERS96 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoTide\&.H>\fP
.PP
Inherits \fBSBSolidTideLd\fP'\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTableEntry73a\fP"
.br
.ti -1c
.RI "struct \fBTableEntry73b\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBSolidTideLdIERS96\fP (const \fBSBConfig\fP *)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual const \fBVector3\fP & \fBoperator()\fP (\fBSBStation\fP *, \fBSBEphem\fP *, const \fBSBFrame\fP &)"
.br
.ti -1c
.RI "const \fBVector3\fP & \fBtideDeg2ip\fP () const "
.br
.ti -1c
.RI "const \fBVector3\fP & \fBtideDeg3ip\fP () const "
.br
.ti -1c
.RI "const \fBVector3\fP & \fBtideDeg2op\fP () const "
.br
.ti -1c
.RI "const \fBVector3\fP & \fBtideLatDepend\fP () const "
.br
.ti -1c
.RI "const \fBVector3\fP & \fBstep1\fP () const "
.br
.ti -1c
.RI "const \fBVector3\fP & \fBstep2\fP () const "
.br
.ti -1c
.RI "\fBVector3\fP \fBdTide_dLag\fP (\fBSBStation\fP *, \fBSBEphem\fP *)"
.br
.ti -1c
.RI "\fBVector3\fP \fBdTide_dH2\fP (\fBSBStation\fP *, \fBSBEphem\fP *)"
.br
.ti -1c
.RI "\fBVector3\fP \fBdTide_dL2\fP (\fBSBStation\fP *, \fBSBEphem\fP *)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (\fBDIRECTION\fP i)"
.br
.ti -1c
.RI "double \fBat\fP (\fBDIRECTION\fP i) const "
.br
.ti -1c
.RI "double \fBmodule\fP () const "
.br
.ti -1c
.RI "double \fBphi\fP () const "
.br
.ti -1c
.RI "double \fBlambda\fP () const "
.br
.ti -1c
.RI "\fBVector3\fP & \fBunify\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP \fBunit\fP () const "
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP & \fBoperator+=\fP (const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP & \fBoperator-=\fP (const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP & \fBoperator*=\fP (double)"
.br
.ti -1c
.RI "\fBVector3\fP & \fBoperator/=\fP (double)"
.br
.ti -1c
.RI "virtual void \fBreport2Log\fP (\fBSBLog::LogLevel\fP, uint, const QString &, int, int, double=1\&.0) const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBVector3\fP &v) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBVector3\fP &v) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBh_Id\fP () const "
.br
.ti -1c
.RI "virtual double \fBl_Id\fP () const "
.br
.ti -1c
.RI "virtual double \fBh_Is\fP () const "
.br
.ti -1c
.RI "virtual double \fBl_Is\fP () const "
.br
.ti -1c
.RI "virtual double \fBl_1d\fP () const "
.br
.ti -1c
.RI "virtual double \fBl_1s\fP () const "
.br
.ti -1c
.RI "virtual \fBVector3\fP \fBdeg3InPhase\fP (const \fBVector3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "virtual \fBVector3\fP \fBdeg2OutPhase\fP (const \fBVector3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "virtual \fBVector3\fP \fBlatDepend\fP (const \fBVector3\fP &St, const \fBVector3\fP &B)"
.br
.ti -1c
.RI "virtual const \fBVector3\fP & \fBmakeStep1\fP (\fBSBStation\fP *, \fBSBEphem\fP *)"
.br
.ti -1c
.RI "virtual const \fBVector3\fP & \fBmakeStep2\fP (\fBSBStation\fP *, const \fBSBFrame\fP &)"
.br
.ti -1c
.RI "virtual \fBVector3\fP \fBpermTide\fP (\fBSBStation\fP *)"
.br
.ti -1c
.RI "virtual double \fBh2\fP (double phi, \fBSBStation\fP *) const "
.br
.ti -1c
.RI "virtual double \fBl2\fP (double phi, \fBSBStation\fP *) const "
.br
.ti -1c
.RI "virtual double \fBh3\fP () const "
.br
.ti -1c
.RI "virtual double \fBl3\fP () const "
.br
.ti -1c
.RI "virtual \fBVector3\fP \fBdeg2InPhase\fP (\fBSBStation\fP *, const \fBVector3\fP &)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBTableEntry73a\fP * \fBTab_73a\fP"
.br
.ti -1c
.RI "const \fBTableEntry73b\fP * \fBTab_73b\fP"
.br
.ti -1c
.RI "const \fBSBConfig\fP * \fBCfg\fP"
.br
.ti -1c
.RI "double \fBh_0\fP"
.br
.ti -1c
.RI "double \fBh_2\fP"
.br
.ti -1c
.RI "double \fBl_0\fP"
.br
.ti -1c
.RI "double \fBl_2\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBTideDeg2ip\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBTideDeg3ip\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBTideDeg2op\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBTideLatDepend\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBStep1\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBStep2\fP"
.br
.ti -1c
.RI "double \fBCoeffSun\fP"
.br
.ti -1c
.RI "double \fBCoeffMoon\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBMoon_TRS\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBSun_TRS\fP"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBFmREN\fP"
.br
.RI "\fItransforms local radial-transverse coords to TRF \fP"
.ti -1c
.RI "double \fBvec\fP [3]"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const \fBTableEntry73a\fP \fBTable_73a_el\fP [11]"
.br
.ti -1c
.RI "static const \fBTableEntry73a\fP \fBTable_73a_an\fP [11]"
.br
.ti -1c
.RI "static const \fBTableEntry73b\fP \fBTable_73b_el\fP [5]"
.br
.ti -1c
.RI "static const \fBTableEntry73b\fP \fBTable_73b_an\fP [5]"
.br
.ti -1c
.RI "static const double \fBh_0_el\fP = 0\&.6026"
.br
.RI "\fInominal value for h^(0), elastic \fP"
.ti -1c
.RI "static const double \fBh_2_el\fP = -0\&.0006"
.br
.RI "\fInominal value for h^(2), elastic \fP"
.ti -1c
.RI "static const double \fBl_0_el\fP = 0\&.0831"
.br
.RI "\fInominal value for l^(0), elastic \fP"
.ti -1c
.RI "static const double \fBl_2_el\fP = 0\&.0002"
.br
.RI "\fInominal value for l^(2), elastic \fP"
.ti -1c
.RI "static const double \fBh_0_an\fP = 0\&.6078"
.br
.RI "\fInominal value for h^(0), anelastic \fP"
.ti -1c
.RI "static const double \fBh_2_an\fP = -0\&.0006"
.br
.RI "\fInominal value for h^(2), anelastic \fP"
.ti -1c
.RI "static const double \fBl_0_an\fP = 0\&.0847"
.br
.RI "\fInominal value for l^(0), anelastic \fP"
.ti -1c
.RI "static const double \fBl_2_an\fP = 0\&.0002"
.br
.RI "\fInominal value for l^(2), anelastic \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBVector3\fP \fBoperator-\fP (const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator-\fP (const \fBVector3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator+\fP (const \fBVector3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator/\fP (const \fBVector3\fP &, double)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator*\fP (const \fBVector3\fP &, double)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator*\fP (double, const \fBVector3\fP &)"
.br
.ti -1c
.RI "double \fBoperator*\fP (const \fBVector3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator*\fP (const \fBMatrix3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator%\fP (const \fBVector3\fP &, const \fBVector3\fP &)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBVector3\fP &v)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBVector3\fP &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Station's displacement due to Solid Earth Tides, IERS96 Standards model'\&. Inherits \fBVector3\fP representing local displacement in TRF'\&. 
.PP
Definition at line 212 of file SbGeoTide\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBSolidTideLdIERS96::SBSolidTideLdIERS96 (const \fBSBConfig\fP *Cfg_)"A constructor'\&. 
.PP
Definition at line 582 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::Cfg, SBConfig::isSolidTideAnelastic(), Tab_73a, Tab_73b, Table_73a_an, Table_73a_el, Table_73b_an, and Table_73b_el\&.
.SH "Member Function Documentation"
.PP 
.SS "double Vector3::at (\fBDIRECTION\fPi) const\fC [inline, inherited]\fP"
.PP
Definition at line 72 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.PP
Referenced by SBStationEditor::acquireData(), SBDelay::calc(), SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBTestEphem::createWidget4Test(), SBPlateMotion::displacement(), SBTestEphem::displayCoo(), SBTestAPLoad::fillData4Plotting(), SBEccListItem::key(), SBCoordsListItem::key(), SBRunManager::makeReportMaps(), Matrix3::Matrix3(), operator<<(), SB_TRF::prepareEccs4Session(), SBRefraction::refrDir(), SBStationEcc::registerEcc(), SBCoordsEditor::SBCoordsEditor(), sinex_SiteEccentricityBlock(), sinex_tro_StaCoordinatesBlock(), SBEccListItem::text(), SBCoordsListItem::text(), SBPlateEntry::velocity(), SBPlateMotion::velocity(), SBStationEditor::wCoordinates(), and SBSiteEditor::wSite()\&.
.SS "virtual QString SBSolidTideLdIERS96::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info) 
.PP
Reimplemented from \fBSBSolidTideLd\fP'\&.
.PP
Definition at line 248 of file SbGeoTide\&.H'\&.
.SS "void Vector3::clear ()\fC [inline, inherited]\fP"
.PP
Definition at line 79 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.PP
Referenced by SBDelay::calc(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), and SBSolidTideLd::operator()()\&.
.SS "\fBVector3\fP SBSolidTideLd::deg2InPhase (\fBSBStation\fP *Station, const \fBVector3\fP &B)\fC [protected, virtual, inherited]\fP"
.PP
Definition at line 349 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::h2(), SBSolidTideLd::l2(), Vector3::module(), SBStation::p_TideLag(), Vector3::phi(), SBStation::rt(), Vector3::unify(), SBParameter::v(), and Z_AXIS\&.
.PP
Referenced by SBSolidTideLd::makeStep1()\&.
.SS "\fBVector3\fP SBSolidTideLdIERS96::deg2OutPhase (const \fBVector3\fP &St, const \fBVector3\fP &B)\fC [protected, virtual]\fP"Calculates term from eqs'\&.(13), (14), IERS Standards 1996'\&. Calculates corresponded j-th celestial body degree 2 out-of-phase contribution from diurnal and semidiurnal tides term'\&. The term is not scaled by GMj/GMearth'\&. 
.PP
Definition at line 611 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::FmREN, h_Id(), h_Is(), l_Id(), l_Is(), Vector3::lambda(), Vector3::module(), Vector3::phi(), sincos(), and Vector3::Vector3()\&.
.PP
Referenced by makeStep1()\&.
.SS "\fBVector3\fP SBSolidTideLdIERS96::deg3InPhase (const \fBVector3\fP &St, const \fBVector3\fP &B)\fC [protected, virtual]\fP"Calculates term from eq'\&.(9), IERS Standards 1996'\&. Calculates corresponded j-th celestial body degree 3 in-phase tide contribution term'\&. The term is not scaled by GMj/GMearth'\&. 
.PP
Definition at line 592 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::h3(), SBSolidTideLd::l3(), Vector3::module(), and Vector3::unify()\&.
.PP
Referenced by makeStep1()\&.
.SS "\fBVector3\fP SBSolidTideLd::dTide_dH2 (\fBSBStation\fP *Station, \fBSBEphem\fP *Ephem)\fC [inherited]\fP"
.PP
Definition at line 408 of file SbGeoTide\&.C'\&.
.PP
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), Vector3::module(), SBSolidTideLd::Moon_TRS, SBStation::rt(), SBEphem::sun(), SBSolidTideLd::Sun_TRS, and Vector3::unit()\&.
.PP
Referenced by SBDelay::calcDerivatives()\&.
.SS "\fBVector3\fP SBSolidTideLd::dTide_dL2 (\fBSBStation\fP *Station, \fBSBEphem\fP *Ephem)\fC [inherited]\fP"
.PP
Definition at line 435 of file SbGeoTide\&.C'\&.
.PP
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), Vector3::module(), SBSolidTideLd::Moon_TRS, SBStation::rt(), SBEphem::sun(), SBSolidTideLd::Sun_TRS, and Vector3::unit()\&.
.PP
Referenced by SBDelay::calcDerivatives()\&.
.SS "\fBVector3\fP SBSolidTideLd::dTide_dLag (\fBSBStation\fP *Station, \fBSBEphem\fP *Ephem)\fC [inherited]\fP"
.PP
Definition at line 364 of file SbGeoTide\&.C'\&.
.PP
References SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), SBSolidTideLd::h2(), SBSolidTideLd::l2(), Vector3::module(), SBSolidTideLd::Moon_TRS, SBStation::p_TideLag(), Vector3::phi(), SBStation::rt(), SBEphem::sun(), SBSolidTideLd::Sun_TRS, SBParameter::v(), and Z_AXIS\&.
.PP
Referenced by SBDelay::calcDerivatives()\&.
.SS "double SBSolidTideLd::h2 (doublephi, \fBSBStation\fP *Station) const\fC [protected, virtual, inherited]\fP"Returns Love number h_2'\&. Returns nominal Love number h_2 (in the case of no latitude dependancy) or latitude dependent h_2'\&. 
.PP
Reimplemented in \fBSBSolidTideLdIERS92\fP'\&.
.PP
Definition at line 315 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::Cfg, SBSolidTideLd::h_0, SBSolidTideLd::h_2, SBConfig::isSolidTideLatDepend(), SBStation::p_TideH2(), and SBParameter::v()\&.
.PP
Referenced by SBSolidTideLd::deg2InPhase(), SBSolidTideLd::dTide_dLag(), and permTide()\&.
.SS "virtual double SBSolidTideLd::h3 () const\fC [inline, protected, virtual, inherited]\fP"Returns Love number h_3'\&. 
.PP
Definition at line 146 of file SbGeoTide\&.H'\&.
.PP
Referenced by deg3InPhase()\&.
.SS "virtual double SBSolidTideLdIERS96::h_Id () const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 232 of file SbGeoTide\&.H'\&.
.PP
Referenced by deg2OutPhase()\&.
.SS "virtual double SBSolidTideLdIERS96::h_Is () const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 234 of file SbGeoTide\&.H'\&.
.PP
Referenced by deg2OutPhase()\&.
.SS "double SBSolidTideLd::l2 (doublephi, \fBSBStation\fP *Station) const\fC [protected, virtual, inherited]\fP"Returns Love number l_2'\&. Returns nominal Love number l_2 (in the case of no latitude dependancy) or latitude dependent l_2'\&. 
.PP
Reimplemented in \fBSBSolidTideLdIERS92\fP'\&.
.PP
Definition at line 327 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::Cfg, SBConfig::isSolidTideLatDepend(), SBSolidTideLd::l_0, SBSolidTideLd::l_2, SBStation::p_TideL2(), and SBParameter::v()\&.
.PP
Referenced by SBSolidTideLd::deg2InPhase(), SBSolidTideLd::dTide_dLag(), and permTide()\&.
.SS "virtual double SBSolidTideLd::l3 () const\fC [inline, protected, virtual, inherited]\fP"Returns Love number l_3'\&. 
.PP
Definition at line 148 of file SbGeoTide\&.H'\&.
.PP
Referenced by deg3InPhase()\&.
.SS "virtual double SBSolidTideLdIERS96::l_1d () const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 236 of file SbGeoTide\&.H'\&.
.PP
Referenced by latDepend()\&.
.SS "virtual double SBSolidTideLdIERS96::l_1s () const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 237 of file SbGeoTide\&.H'\&.
.PP
Referenced by latDepend()\&.
.SS "virtual double SBSolidTideLdIERS96::l_Id () const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 233 of file SbGeoTide\&.H'\&.
.PP
Referenced by deg2OutPhase()\&.
.SS "virtual double SBSolidTideLdIERS96::l_Is () const\fC [inline, protected, virtual]\fP"
.PP
Definition at line 235 of file SbGeoTide\&.H'\&.
.PP
Referenced by deg2OutPhase()\&.
.SS "double Vector3::lambda () const\fC [inline, inherited]\fP"
.PP
Definition at line 75 of file SbVector3\&.H'\&.
.PP
References Vector3::module(), and Vector3::vec\&.
.PP
Referenced by deg2OutPhase(), SBTestEphem::displayCoo(), latDepend(), makeStep2(), and SBSolidTideLd::operator()()\&.
.SS "\fBVector3\fP SBSolidTideLdIERS96::latDepend (const \fBVector3\fP &St, const \fBVector3\fP &B)\fC [protected, virtual]\fP"Calculates term from eqs'\&.(11), (12), IERS Standards 1996'\&. Calculates transverse displacement due to l(1) term corresponded to j-th celestial body'\&. The term is not scaled by GMj/GMearth'\&. 
.PP
Definition at line 650 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::FmREN, l_1d(), l_1s(), Vector3::lambda(), Vector3::module(), Vector3::phi(), sincos(), Vector3::unify(), Vector3::Vector3(), X_AXIS, Y_AXIS, and Z_AXIS\&.
.PP
Referenced by makeStep1()\&.
.SS "const \fBVector3\fP & SBSolidTideLdIERS96::makeStep1 (\fBSBStation\fP *Station, \fBSBEphem\fP *Ephem)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBSBSolidTideLd\fP'\&.
.PP
Definition at line 687 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::Cfg, deg2OutPhase(), deg3InPhase(), SBEphem::earth(), SBEphem::emRat(), SBCelestBody::gm(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), latDepend(), SBSolidTideLd::Moon_TRS, SBStation::rt(), SBSolidTideLd::Step1, SBEphem::sun(), SBSolidTideLd::Sun_TRS, SBSolidTideLd::TideDeg2ip, SBSolidTideLd::TideDeg2op, SBSolidTideLd::TideDeg3ip, SBSolidTideLd::TideLatDepend, and v3Zero\&.
.SS "const \fBVector3\fP & SBSolidTideLdIERS96::makeStep2 (\fBSBStation\fP *St, const \fBSBFrame\fP &Frame)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBSBSolidTideLd\fP'\&.
.PP
Definition at line 703 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::Cfg, SBSolidTideLdIERS96::TableEntry73a::DR, SBSolidTideLdIERS96::TableEntry73b::DRip, SBSolidTideLdIERS96::TableEntry73b::DRop, SBSolidTideLdIERS96::TableEntry73a::DT, SBSolidTideLdIERS96::TableEntry73b::DTip, SBSolidTideLdIERS96::TableEntry73b::DTop, SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), SBSolidTideLd::FmREN, SBFrame::gmst(), SBConfig::isSolidTideAnelastic(), Vector3::lambda(), SBSolidTideLdIERS96::TableEntry73a::N, SBSolidTideLdIERS96::TableEntry73b::N, Vector3::phi(), SBStation::rt(), sincos(), SBSolidTideLd::Step2, Tab_73a, Tab_73b, SBFrame::time(), and Vector3::Vector3()\&.
.SS "double Vector3::module () const\fC [inline, inherited]\fP"
.PP
Definition at line 73 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.PP
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), deg2OutPhase(), deg3InPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBStationImport::importITRF(), Vector3::lambda(), latDepend(), SBRunManager::makeReportMaps(), SBSolidTideLd::makeStep1(), Vector3::phi(), Vector3::report2Log(), Vector3::unify(), and Vector3::unit()\&.
.SS "bool Vector3::operator!= (const \fBVector3\fP &v) const\fC [inline, inherited]\fP"
.PP
Definition at line 102 of file SbVector3\&.H'\&.
.SS "const \fBVector3\fP & SBSolidTideLd::operator() (\fBSBStation\fP *Station, \fBSBEphem\fP *Ephem, const \fBSBFrame\fP &Frame)\fC [virtual, inherited]\fP"Calculates site's displacement vector corresponds to time T'\&. Calls \fBSBSolidTideLd::makeStep1()\fP and \fBSBSolidTideLd::makeStep1()\fP, then, if it is necessary, removes permanent tide'\&. 
.PP
Definition at line 486 of file SbGeoTide\&.C'\&.
.PP
References SBSolidTideLd::Cfg, SBSolidTideLd::ClassName(), Vector3::clear(), SBSolidTideLd::CoeffMoon, SBSolidTideLd::CoeffSun, SBFrame::crs2trs(), SBLog::DBG, SBEphem::earth(), EAST, SBLog::ERR, SBMJD::F_MJD, SBMJD::F_Short, SBSolidTideLd::FmREN, SBStation::fmVEN(), SBEphem::geoMoon(), SBStation::id(), SBLog::isEligible(), SBConfig::isRemovePermTide(), SBConfig::isSolidTideAnelastic(), SBConfig::isSolidTideLatDepend(), Vector3::lambda(), Log, SBSolidTideLd::makeStep1(), SBSolidTideLd::makeStep2(), SBSolidTideLd::Moon_TRS, SBNamed::name(), NORT, SBSolidTideLd::permTide(), Vector3::phi(), SBCelestBody::r(), Vector3::report2Log(), Matrix3::report2Log(), SBStation::rt(), SBSolidTideLd::Step1, SBSolidTideLd::Step2, SBEphem::sun(), SBSolidTideLd::Sun_TRS, SBTime::TAI(), SBLog::TIDES, SBFrame::time(), SBMJD::toString(), SBStationID::toString(), and SBLog::write()\&.
.SS "\fBVector3\fP & Vector3::operator*= (doublev)\fC [inline, inherited]\fP"
.PP
Definition at line 247 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.SS "\fBVector3\fP & Vector3::operator+= (const \fBVector3\fP &V)\fC [inline, inherited]\fP"
.PP
Definition at line 235 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.SS "\fBVector3\fP & Vector3::operator-= (const \fBVector3\fP &V)\fC [inline, inherited]\fP"
.PP
Definition at line 241 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.SS "\fBVector3\fP & Vector3::operator/= (doublev)\fC [inline, inherited]\fP"
.PP
Definition at line 253 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.SS "bool Vector3::operator== (const \fBVector3\fP &v) const\fC [inline, inherited]\fP"
.PP
Definition at line 100 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.SS "double& Vector3::operator[] (\fBDIRECTION\fPi)\fC [inline, inherited]\fP"
.PP
Definition at line 71 of file SbVector3\&.H'\&.
.PP
References Vector3::vec\&.
.SS "\fBVector3\fP SBSolidTideLdIERS96::permTide (\fBSBStation\fP *St)\fC [protected, virtual]\fP"Returns permanent tide displacement (TRF coordinate system)'\&. 
.PP
Reimplemented from \fBSBSolidTideLd\fP'\&.
.PP
Definition at line 748 of file SbGeoTide\&.C'\&.
.PP
References SBStation::fmVEN(), SBSolidTideLd::h2(), SBSolidTideLd::l2(), Vector3::phi(), SBStation::rt(), sincos(), and Vector3::Vector3()\&.
.SS "double Vector3::phi () const\fC [inline, inherited]\fP"
.PP
Definition at line 74 of file SbVector3\&.H'\&.
.PP
References Vector3::module(), and Vector3::vec\&.
.PP
Referenced by SBSolidTideLd::deg2InPhase(), deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dLag(), latDepend(), makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::permTide(), and permTide()\&.
.SS "void Vector3::report2Log (\fBSBLog::LogLevel\fPLev, uintFac, const QString &Pref, intw_, intd_, doubleScale = \fC1\&.0\fP) const\fC [virtual, inherited]\fP"
.PP
Definition at line 39 of file SbVector3\&.C'\&.
.PP
References Log, Vector3::module(), Vector3::vec, and SBLog::write()\&.
.PP
Referenced by SBStation::axisOffsetLenght(), SBDelay::calc(), SBEphem::calc(), SBAploEphem::displacement(), SBSolidTideLd::operator()(), SBTideLd::operator()(), and SBRefraction::operator()()\&.
.SS "const \fBVector3\fP& SBSolidTideLd::step1 () const\fC [inline, inherited]\fP"
.PP
Definition at line 176 of file SbGeoTide\&.H'\&.
.PP
References SBSolidTideLd::Step1\&.
.PP
Referenced by SBTestSolidTides::fillData4Plotting()\&.
.SS "const \fBVector3\fP& SBSolidTideLd::step2 () const\fC [inline, inherited]\fP"
.PP
Definition at line 177 of file SbGeoTide\&.H'\&.
.PP
References SBSolidTideLd::Step2\&.
.PP
Referenced by SBTestSolidTides::fillData4Plotting()\&.
.SS "const \fBVector3\fP& SBSolidTideLd::tideDeg2ip () const\fC [inline, inherited]\fP"
.PP
Definition at line 171 of file SbGeoTide\&.H'\&.
.PP
References SBSolidTideLd::TideDeg2ip\&.
.PP
Referenced by SBTestSolidTides::fillData4Plotting()\&.
.SS "const \fBVector3\fP& SBSolidTideLd::tideDeg2op () const\fC [inline, inherited]\fP"
.PP
Definition at line 173 of file SbGeoTide\&.H'\&.
.PP
References SBSolidTideLd::TideDeg2op\&.
.PP
Referenced by SBTestSolidTides::fillData4Plotting()\&.
.SS "const \fBVector3\fP& SBSolidTideLd::tideDeg3ip () const\fC [inline, inherited]\fP"
.PP
Definition at line 172 of file SbGeoTide\&.H'\&.
.PP
References SBSolidTideLd::TideDeg3ip\&.
.PP
Referenced by SBTestSolidTides::fillData4Plotting()\&.
.SS "const \fBVector3\fP& SBSolidTideLd::tideLatDepend () const\fC [inline, inherited]\fP"
.PP
Definition at line 174 of file SbGeoTide\&.H'\&.
.PP
References SBSolidTideLd::TideLatDepend\&.
.PP
Referenced by SBTestSolidTides::fillData4Plotting()\&.
.SS "\fBVector3\fP& Vector3::unify ()\fC [inline, inherited]\fP"
.PP
Definition at line 77 of file SbVector3\&.H'\&.
.PP
References Vector3::module()\&.
.PP
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), deg3InPhase(), and latDepend()\&.
.SS "\fBVector3\fP Vector3::unit () const\fC [inline, inherited]\fP"
.PP
Definition at line 78 of file SbVector3\&.H'\&.
.PP
References Vector3::module(), and Vector3::Vector3()\&.
.PP
Referenced by SBDelay::calc(), SBRunManager::constraintStationVeloc(), SBSolidTideLd::dTide_dH2(), and SBSolidTideLd::dTide_dL2()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBVector3\fP operator% (const \fBVector3\fP &V1, const \fBVector3\fP &V2)\fC [friend, inherited]\fP"makes a vector product of two vectors (because '%' has a priority of '*')
.PP
makes vector product of two vectors'\&. 
.PP
Definition at line 326 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator* (const \fBVector3\fP &V1, doublev2)\fC [friend, inherited]\fP"multiplies vector by scalar'\&. 
.PP
Definition at line 302 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator* (doublev1, const \fBVector3\fP &V2)\fC [friend, inherited]\fP"multiplies vector by scalar'\&. 
.PP
Definition at line 310 of file SbVector3\&.H'\&.
.SS "double operator* (const \fBVector3\fP &V1, const \fBVector3\fP &V2)\fC [friend, inherited]\fP"makes a scalar product of two vectors
.PP
makes scalar product of two vectors'\&. 
.PP
Definition at line 318 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator* (const \fBMatrix3\fP &M, const \fBVector3\fP &V)\fC [friend, inherited]\fP"makes a product of matrix and vector
.PP
\fBMatrix3\fP makes product of matrix and vector'\&. 
.PP
Definition at line 519 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator+ (const \fBVector3\fP &V1, const \fBVector3\fP &V2)\fC [friend, inherited]\fP"
.PP
Definition at line 278 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator- (const \fBVector3\fP &V)\fC [friend, inherited]\fP"
.PP
Definition at line 270 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator- (const \fBVector3\fP &V1, const \fBVector3\fP &V2)\fC [friend, inherited]\fP"
.PP
Definition at line 286 of file SbVector3\&.H'\&.
.SS "\fBVector3\fP operator/ (const \fBVector3\fP &V1, doublev2)\fC [friend, inherited]\fP"
.PP
Definition at line 294 of file SbVector3\&.H'\&.
.SS "QDataStream& operator<< (QDataStream &s, const \fBVector3\fP &v)\fC [friend, inherited]\fP"
.PP
Definition at line 103 of file SbVector3\&.H'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBVector3\fP &v)\fC [friend, inherited]\fP"
.PP
Definition at line 105 of file SbVector3\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBSBConfig\fP* \fBSBSolidTideLd::Cfg\fP\fC [protected, inherited]\fP"
.PP
Definition at line 106 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::h2(), SBSolidTideLd::l2(), makeStep1(), makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::SBSolidTideLd(), and SBSolidTideLdIERS96()\&.
.SS "double \fBSBSolidTideLd::CoeffMoon\fP\fC [protected, inherited]\fP"
.PP
Definition at line 129 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::makeStep1(), SBSolidTideLd::operator()(), and SBSolidTideLd::SBSolidTideLd()\&.
.SS "double \fBSBSolidTideLd::CoeffSun\fP\fC [protected, inherited]\fP"
.PP
Definition at line 128 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::makeStep1(), SBSolidTideLd::operator()(), and SBSolidTideLd::SBSolidTideLd()\&.
.SS "\fBMatrix3\fP \fBSBSolidTideLd::FmREN\fP\fC [protected, inherited]\fP"
.PP
transforms local radial-transverse coords to TRF 
.PP
Definition at line 134 of file SbGeoTide\&.H'\&.
.PP
Referenced by deg2OutPhase(), latDepend(), SBSolidTideLd::makeStep2(), makeStep2(), and SBSolidTideLd::operator()()\&.
.SS "double \fBSBSolidTideLd::h_0\fP\fC [protected, inherited]\fP"
.PP
Definition at line 116 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::h2(), and SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::h_0_an\fP = 0\&.6078\fC [static, protected, inherited]\fP"
.PP
nominal value for h^(0), anelastic 
.PP
Definition at line 111 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::h_0_el\fP = 0\&.6026\fC [static, protected, inherited]\fP"
.PP
nominal value for h^(0), elastic 
.PP
Definition at line 107 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "double \fBSBSolidTideLd::h_2\fP\fC [protected, inherited]\fP"
.PP
Definition at line 117 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::h2(), and SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::h_2_an\fP = -0\&.0006\fC [static, protected, inherited]\fP"
.PP
nominal value for h^(2), anelastic 
.PP
Definition at line 112 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::h_2_el\fP = -0\&.0006\fC [static, protected, inherited]\fP"
.PP
nominal value for h^(2), elastic 
.PP
Definition at line 108 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "double \fBSBSolidTideLd::l_0\fP\fC [protected, inherited]\fP"
.PP
Definition at line 118 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::l2(), and SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::l_0_an\fP = 0\&.0847\fC [static, protected, inherited]\fP"
.PP
nominal value for l^(0), anelastic 
.PP
Definition at line 113 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::l_0_el\fP = 0\&.0831\fC [static, protected, inherited]\fP"
.PP
nominal value for l^(0), elastic 
.PP
Definition at line 109 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "double \fBSBSolidTideLd::l_2\fP\fC [protected, inherited]\fP"
.PP
Definition at line 119 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::l2(), and SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::l_2_an\fP = 0\&.0002\fC [static, protected, inherited]\fP"
.PP
nominal value for l^(2), anelastic 
.PP
Definition at line 114 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "const double \fBSBSolidTideLd::l_2_el\fP = 0\&.0002\fC [static, protected, inherited]\fP"
.PP
nominal value for l^(2), elastic 
.PP
Definition at line 110 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::SBSolidTideLd()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::Moon_TRS\fP\fC [protected, inherited]\fP"
.PP
Definition at line 132 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), makeStep1(), and SBSolidTideLd::operator()()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::Step1\fP\fC [protected, inherited]\fP"
.PP
Definition at line 125 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::makeStep1(), makeStep1(), SBSolidTideLd::operator()(), and SBSolidTideLd::step1()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::Step2\fP\fC [protected, inherited]\fP"
.PP
Definition at line 126 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::makeStep2(), makeStep2(), SBSolidTideLd::operator()(), and SBSolidTideLd::step2()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::Sun_TRS\fP\fC [protected, inherited]\fP"
.PP
Definition at line 133 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBSolidTideLd::makeStep1(), makeStep1(), and SBSolidTideLd::operator()()\&.
.SS "const \fBTableEntry73a\fP* \fBSBSolidTideLdIERS96::Tab_73a\fP\fC [protected]\fP"
.PP
Definition at line 229 of file SbGeoTide\&.H'\&.
.PP
Referenced by makeStep2(), and SBSolidTideLdIERS96()\&.
.SS "const \fBTableEntry73b\fP* \fBSBSolidTideLdIERS96::Tab_73b\fP\fC [protected]\fP"
.PP
Definition at line 230 of file SbGeoTide\&.H'\&.
.PP
Referenced by makeStep2(), and SBSolidTideLdIERS96()\&.
.SS "const \fBSBSolidTideLdIERS96::TableEntry73a\fP \fBSBSolidTideLdIERS96::Table_73a_an\fP\fC [static, protected]\fP"\fBInitial value:\fP
.PP
.nf

{
  { { 1, 0, 2, 0, 2},  -0\&.09,  0\&.0 },
  { { 0, 0, 2, 0, 1},  -0\&.10,  0\&.0 },
  { { 0, 0, 2, 0, 2},  -0\&.53,  0\&.02},
  { { 1, 0, 0, 0, 0},   0\&.06,  0\&.0 },
  { { 0, 1, 2,-2, 2},  -0\&.05,  0\&.0 },
  { { 0, 0, 2,-2, 2},  -1\&.23,  0\&.07},
  { { 0, 0, 0, 0,-1},  -0\&.22,  0\&.01},
  { { 0, 0, 0, 0, 0},  12\&.04, -0\&.72},
  { { 0, 0, 0, 0, 1},   1\&.74, -0\&.10},
  { { 0,-1, 0, 0, 0},  -0\&.50,  0\&.03},
  { { 0, 0,-2, 2,-2},  -0\&.11,  0\&.01}
}
.fi
.PP
Definition at line 226 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLdIERS96()\&.
.SS "const \fBSBSolidTideLdIERS96::TableEntry73a\fP \fBSBSolidTideLdIERS96::Table_73a_el\fP\fC [static, protected]\fP"\fBInitial value:\fP
.PP
.nf

{
  { { 1, 0, 2, 0, 2},  -0\&.11, -0\&.01},
  { { 0, 0, 2, 0, 1},  -0\&.12, -0\&.01},
  { { 0, 0, 2, 0, 2},  -0\&.63, -0\&.04},
  { { 1, 0, 0, 0, 0},   0\&.07,  0\&.0 },
  { { 0, 1, 2,-2, 2},  -0\&.06,  0\&.0 },
  { { 0, 0, 2,-2, 2},  -1\&.29,  0\&.05},
  { { 0, 0, 0, 0,-1},  -0\&.23,  0\&.01},
  { { 0, 0, 0, 0, 0},  12\&.25, -0\&.65},
  { { 0, 0, 0, 0, 1},   1\&.77, -0\&.09},
  { { 0,-1, 0, 0, 0},  -0\&.51,  0\&.03},
  { { 0, 0,-2, 2,-2},  -0\&.11,  0\&.01}
}
.fi
.PP
Definition at line 225 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLdIERS96()\&.
.SS "const \fBSBSolidTideLdIERS96::TableEntry73b\fP \fBSBSolidTideLdIERS96::Table_73b_an\fP\fC [static, protected]\fP"\fBInitial value:\fP
.PP
.nf

{
  { { 0, 0, 0, 0, 1},   0\&.47,  0\&.23, 0\&.16, 0\&.07},
  { { 0, 0,-2, 2,-2},  -0\&.20, -0\&.12,-0\&.11,-0\&.05},
  { {-1, 0, 0, 0, 0},  -0\&.11, -0\&.08,-0\&.09,-0\&.04},
  { { 0, 0,-2, 0,-2},  -0\&.13, -0\&.11,-0\&.15,-0\&.07},
  { { 0, 0,-2, 0,-1},  -0\&.05, -0\&.05,-0\&.06,-0\&.03}
}
.fi
.PP
Definition at line 228 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLdIERS96()\&.
.SS "const \fBSBSolidTideLdIERS96::TableEntry73b\fP \fBSBSolidTideLdIERS96::Table_73b_el\fP\fC [static, protected]\fP"\fBInitial value:\fP
.PP
.nf

{
  { { 0, 0, 0, 0, 1},  -0\&.05,  0\&.0 , 0\&.0 , 0\&.0 },
  { { 0, 0,-2, 2,-2},   0\&.05,  0\&.0 , 0\&.0 , 0\&.0 },
  { {-1, 0, 0, 0, 0},   0\&.06,  0\&.0 , 0\&.0 , 0\&.0 },
  { { 0, 0,-2, 0,-2},   0\&.12,  0\&.0 , 0\&.0 , 0\&.0 },
  { { 0, 0,-2, 0,-1},   0\&.05,  0\&.0 , 0\&.0 , 0\&.0 }
}
.fi
.PP
Definition at line 227 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLdIERS96()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::TideDeg2ip\fP\fC [protected, inherited]\fP"
.PP
Definition at line 121 of file SbGeoTide\&.H'\&.
.PP
Referenced by SBSolidTideLd::makeStep1(), makeStep1(), and SBSolidTideLd::tideDeg2ip()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::TideDeg2op\fP\fC [protected, inherited]\fP"
.PP
Definition at line 123 of file SbGeoTide\&.H'\&.
.PP
Referenced by makeStep1(), and SBSolidTideLd::tideDeg2op()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::TideDeg3ip\fP\fC [protected, inherited]\fP"
.PP
Definition at line 122 of file SbGeoTide\&.H'\&.
.PP
Referenced by makeStep1(), and SBSolidTideLd::tideDeg3ip()\&.
.SS "\fBVector3\fP \fBSBSolidTideLd::TideLatDepend\fP\fC [protected, inherited]\fP"
.PP
Definition at line 124 of file SbGeoTide\&.H'\&.
.PP
Referenced by makeStep1(), and SBSolidTideLd::tideLatDepend()\&.
.SS "double \fBVector3::vec\fP[3]\fC [protected, inherited]\fP"
.PP
Definition at line 53 of file SbVector3\&.H'\&.
.PP
Referenced by Vector3::at(), Vector3::clear(), Vector3::lambda(), Vector3::module(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), Vector3::operator*=(), Vector3::operator+=(), Vector3::operator-=(), Vector3::operator/=(), Vector3::operator=(), Vector3::operator==(), Vector3::operator[](), Vector3::phi(), Vector3::report2Log(), and Vector3::Vector3()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
