SBSourceListItem
NAME
SBSourceListItem -
SYNOPSIS
#include <SbIStuffSource.H>
Inherits QListViewItem'.
Public Member Functions
SBSourceListItem (QListView *, SBSource *=0)
virtual ~SBSourceListItem ()
virtual QString ClassName () const
virtual QString text (int) const
QString key (int, bool) const
const QPixmap * pixmap (int) const
Private Attributes
SBSource * Source
bool isFaked
Friends
class SBStuffSources
class SBSourceEditor
Detailed Description
Definition at line 58 of file SbIStuffSource.H'.
Constructor & Destructor Documentation
SBSourceListItem::SBSourceListItem (QListView *parent, SBSource *Source_ = 0)
Definition at line 61 of file SbIStuffSource.C'.
References isFaked, and Source.
SBSourceListItem::~SBSourceListItem () [virtual]
Definition at line 73 of file SbIStuffSource.C'.
References isFaked, and Source.
Member Function Documentation
virtual QString SBSourceListItem::ClassName () const [inline, virtual]
Definition at line 66 of file SbIStuffSource.H'.
QString SBSourceListItem::key (intcol, bool) const
Definition at line 131 of file SbIStuffSource.C'.
References SBSource::dn(), SBSource::dn_err(), SBSource::firstMJD(), SBAttributed::isAttr(), SBSource::isHLink(), SBSource::lastMJD(), SBSource::mv(), SBNamed::name(), SBSource::nObsApr(), SBSource::nSessApr(), SBSource::ra(), SBSource::ra_err(), RAD2DEG, RAD2HR, Source, SBSource::status(), SBSource::StatusSuspected, TmpString, and SBSource::type().
const QPixmap * SBSourceListItem::pixmap (intcol) const
Definition at line 172 of file SbIStuffSource.C'.
References SBSource::isHLink(), pmSrcHLink, pmSrcStatus, Source, and SBSource::status().
QString SBSourceListItem::text (intcol) const [virtual]
Definition at line 79 of file SbIStuffSource.C'.
References SBSource::DN2str(), SBSource::dn_err(), SBSource::firstMJD(), SBAttributed::isAttr(), SBSource::lastMJD(), SBSource::mv(), SBNamed::name(), SBSource::nObsApr(), SBSource::nSessApr(), SBSource::RA2str(), SBSource::ra_err(), RAD2DEG, RAD2HR, Source, SBSource::StatusSuspected, TmpString, and SBSource::type().
Friends And Related Function Documentation
friend class SBSourceEditor [friend]
Definition at line 71 of file SbIStuffSource.H'.
friend class SBStuffSources [friend]
Definition at line 70 of file SbIStuffSource.H'.
Member Data Documentation
bool SBSourceListItem::isFaked [private]
Definition at line 62 of file SbIStuffSource.H'.
Referenced by SBSourceListItem(), and ~SBSourceListItem().
SBSource* SBSourceListItem::Source [private]
Definition at line 61 of file SbIStuffSource.H'.
Referenced by SBStuffSources::deleteEntryS(), key(), pixmap(), SBSourceEditor::SBSourceEditor(), SBSourceListItem(), text(), and ~SBSourceListItem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.