SBSpectrumAnalyserMEM
NAME
SBSpectrumAnalyserMEM -
SYNOPSIS
#include <SbIMEM.H>
Inherits QDialog'.
Public Member Functions
SBSpectrumAnalyserMEM (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBSpectrumAnalyserMEM ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
void readDataFile ()
void makeAnalysis ()
void scan4FPE ()
void resetLimits ()
void changeFilterOrder (int)
void setMEMAssumeEquiDistant (bool)
void setMEMFillMissingImag (bool)
void setMEMRemoveShifts (bool)
void setMEMRemoveTrends (bool)
void setMEMType (int)
void changeNumOfSpPts (const QString &)
void changeFStart (const QString &)
void changeFFinis (const QString &)
void changePStart (const QString &)
void changePFinis (const QString &)
void setRangeFreq (bool)
void changeFPE_Mstart (const QString &)
void changeFPE_Mfinis (const QString &)
void changeLine2Check (const QString &)
void setScalingCPD2CPY (bool)
void browseLimits ()
void checkLine ()
Private Member Functions
QWidget * wOptions ()
QWidget * wBrowseData ()
QWidget * wBrowseSpectrum ()
QWidget * wMEMCoeffList ()
void collectData ()
void redrawDataPlot ()
void redrawSpectrumPlot ()
void redrawFPEPlot ()
Private Attributes
SBMEM * MESA
SBMEM::MEMType MEMType
unsigned int M
unsigned int Mmin
unsigned int Mmax
QString Name
bool IsAutoCalc
unsigned int NSp
bool IsPlotFreq
double FStart
double FFinis
double PStart
double PFinis
double FLine
int FPE_Mstart
int FPE_Mfinis
bool IsScanning
bool IsScanStop
int MinFPEOrder
double MinFPE
bool ScaleCPD2CPY
QString Str
QTabWidget * Tab
QSpinBox * sbMval
QLabel * lImportedFileName
QLabel * lNumOfPts
QLabel * lDT
QLabel * lShiftR
QLabel * lTrendR
QLabel * lShiftI
QLabel * lTrendI
QLabel * lSampleVar
QRadioButton * rbMEMType [4]
QCheckBox * cbAssumeEquiDistant
QCheckBox * cbFillMissingImag
QCheckBox * cbRmShifts
QCheckBox * cbRmTrends
QLineEdit * leNumOfSpPts
QLineEdit * leFStart
QLineEdit * leFFinis
QLineEdit * lePStart
QLineEdit * lePFinis
QLineEdit * leFPEMstart
QLineEdit * leFPEMfinis
QLineEdit * leLine2Check
QDoubleValidator * dvFStart
QDoubleValidator * dvFFinis
QDoubleValidator * dvFLine
QDoubleValidator * dvPStart
QDoubleValidator * dvPFinis
QIntValidator * ivMscan
QLabel * lMinFPE
QLabel * lMinFPEOrder
QCheckBox * cbScaleCPD2CPY
QPushButton * ResetLimits
QPushButton * GetData
QPushButton * Analyse
QPushButton * Ok
QPushButton * Scan
SBPlotCarrier * PCData
SBPlot * PlotData
SBPlotCarrier * PCSpectrum
SBPlot * PlotSpectrum
SBPlotCarrier * PCFPE
SBPlot * PlotFPE
QAccel * accel
Detailed Description
Definition at line 78 of file SbIMEM.H'.
Constructor & Destructor Documentation
SBSpectrumAnalyserMEM::SBSpectrumAnalyserMEM (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 97 of file SbIMEM.C'.
References accel, accept(), Analyse, changeFilterOrder(), checkLine(), FFinis, FLine, FPE_Mfinis, FPE_Mstart, FStart, GetData, IsAutoCalc, IsPlotFreq, IsScanning, IsScanStop, M, makeAnalysis(), MEMType, MESA, MinFPE, MinFPEOrder, Mmax, Mmin, Name, NSp, Ok, PFinis, PStart, readDataFile(), resetLimits(), ResetLimits, sbMval, ScaleCPD2CPY, Scan, scan4FPE(), SBMEM::setType(), Str, Tab, SBMEM::Type_Recursion, wBrowseData(), wBrowseSpectrum(), wMEMCoeffList(), and wOptions().
SBSpectrumAnalyserMEM::~SBSpectrumAnalyserMEM ()
Definition at line 200 of file SbIMEM.C'.
References MESA, PCData, PCFPE, PCSpectrum, PlotData, PlotFPE, and PlotSpectrum.
Member Function Documentation
void SBSpectrumAnalyserMEM::accept () [protected, slot]
Definition at line 647 of file SbIMEM.C'.
Referenced by SBSpectrumAnalyserMEM().
void SBSpectrumAnalyserMEM::browseLimits () [protected, slot]
Definition at line 904 of file SbIMEM.C'.
References FFinis, FLine, FStart, leFFinis, leFStart, leLine2Check, lePFinis, lePStart, PFinis, PStart, and Str.
Referenced by resetLimits(), and setScalingCPD2CPY().
void SBSpectrumAnalyserMEM::changeFFinis (const QString &Str_) [protected, slot]
Definition at line 938 of file SbIMEM.C'.
References FFinis.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::changeFilterOrder (intM_) [protected, slot]
Definition at line 913 of file SbIMEM.C'.
References IsAutoCalc, M, and makeAnalysis().
Referenced by SBSpectrumAnalyserMEM().
void SBSpectrumAnalyserMEM::changeFPE_Mfinis (const QString &Str_) [protected, slot]
Definition at line 983 of file SbIMEM.C'.
References FPE_Mfinis.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::changeFPE_Mstart (const QString &Str_) [protected, slot]
Definition at line 974 of file SbIMEM.C'.
References FPE_Mstart.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::changeFStart (const QString &Str_) [protected, slot]
Definition at line 929 of file SbIMEM.C'.
References FStart.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::changeLine2Check (const QString &Str_) [protected, slot]
Definition at line 947 of file SbIMEM.C'.
References FLine.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::changeNumOfSpPts (const QString &Str_) [protected, slot]
Definition at line 920 of file SbIMEM.C'.
References NSp.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::changePFinis (const QString &Str_) [protected, slot]
Definition at line 965 of file SbIMEM.C'.
References PFinis.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::changePStart (const QString &Str_) [protected, slot]
Definition at line 956 of file SbIMEM.C'.
References PStart.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::checkLine () [protected, slot]
Definition at line 1167 of file SbIMEM.C'.
References SBMatrix::at(), ClassName(), SBPlotBranch::data(), SBLog::DATA, SBLog::DBG, SBPlotCarrier::findBranch(), FLine, SBLog::INF, SBMEM::isReady(), Log, SBMEM::m(), MESA, SBMEM::n(), SBPlotBranch::nR(), PCSpectrum, SBMEM::psd(), SBMEM::sampleVar(), ScaleCPD2CPY, Str, and SBLog::write().
Referenced by SBSpectrumAnalyserMEM().
virtual QString SBSpectrumAnalyserMEM::ClassName () const [inline, virtual]
Definition at line 84 of file SbIMEM.H'.
Referenced by checkLine(), makeAnalysis(), readDataFile(), and scan4FPE().
void SBSpectrumAnalyserMEM::collectData () [private]
Definition at line 821 of file SbIMEM.C'.
Referenced by makeAnalysis().
void SBSpectrumAnalyserMEM::makeAnalysis () [protected, slot]
Definition at line 826 of file SbIMEM.C'.
References ClassName(), collectData(), SBLog::DATA, SBMEM::fpe(), SBLog::INF, SBMEM::isOK(), SBMEM::isReady(), lMinFPE, lMinFPEOrder, Log, M, SBMEM::m(), MESA, MinFPE, MinFPEOrder, Name, SBMEM::prepareSpectrum(), redrawFPEPlot(), redrawSpectrumPlot(), SBMEM::setM(), Str, and SBLog::write().
Referenced by changeFilterOrder(), readDataFile(), SBSpectrumAnalyserMEM(), and scan4FPE().
void SBSpectrumAnalyserMEM::readDataFile () [protected, slot]
Definition at line 762 of file SbIMEM.C'.
References ClassName(), SBLog::DATA, SBMEM::dt(), dvFFinis, dvFLine, dvFStart, FFinis, FStart, SBLog::INF, SBMEM::isOK(), ivMscan, lDT, leFPEMfinis, leFPEMstart, lImportedFileName, lNumOfPts, Log, lSampleVar, lShiftI, lShiftR, lTrendI, lTrendR, makeAnalysis(), MESA, MinFPE, MinFPEOrder, Mmax, Mmin, SBMEM::n(), Name, SBSetUp::path2TimeSeries(), SBMEM::readDataFile(), redrawDataPlot(), resetLimits(), SBMEM::sampleVar(), sbMval, SetUp, SBMEM::shiftI(), SBMEM::shiftR(), Str, SBMEM::trendI(), SBMEM::trendR(), SBMEM::validM(), and SBLog::write().
Referenced by SBSpectrumAnalyserMEM().
void SBSpectrumAnalyserMEM::redrawDataPlot () [private]
Definition at line 992 of file SbIMEM.C'.
References SBVector::at(), SBPlotCarrier::branches(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, SBPlotBranch::data(), SBPlot::dataChanged(), SBMEM::isOK(), MESA, SBMEM::n(), Name, SBSetUp::path2TimeSeries(), PCData, PlotData, SBMatrix::set(), SBPlotCarrier::setAbsFile4SaveBaseName(), SetUp, SBMEM::x(), SBMEM::z_i(), and SBMEM::z_r().
Referenced by readDataFile().
void SBSpectrumAnalyserMEM::redrawFPEPlot () [private]
Definition at line 1131 of file SbIMEM.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, SBPlotBranch::data(), SBPlot::dataChanged(), SBMEM::fpe(), SBMEM::isReady(), SBMEM::m(), MESA, Mmax, Name, SBSetUp::path2TimeSeries(), PCFPE, PlotFPE, SBMatrix::set(), SBPlotCarrier::setAbsFile4SaveBaseName(), SBPlotBranch::setDataAttr(), and SetUp.
Referenced by makeAnalysis().
void SBSpectrumAnalyserMEM::redrawSpectrumPlot () [private]
Definition at line 1028 of file SbIMEM.C'.
References SBMatrix::at(), SBPlotCarrier::branches(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_BAR, SBPlotCarrier::DA_IGN, SBPlot::dataChanged(), FFinis, FLine, SBMEM::fN(), FStart, IsPlotFreq, SBMEM::isReady(), MESA, Name, NSp, SBSetUp::path2TimeSeries(), PCSpectrum, PFinis, PlotSpectrum, SBMEM::psd(), PStart, ScaleCPD2CPY, SBMatrix::set(), SBPlotCarrier::setAbsFile4SaveBaseName(), and SetUp.
Referenced by makeAnalysis(), setRangeFreq(), and setScalingCPD2CPY().
void SBSpectrumAnalyserMEM::reject () [protected, slot]
Definition at line 653 of file SbIMEM.C'.
void SBSpectrumAnalyserMEM::resetLimits () [protected, slot]
Definition at line 889 of file SbIMEM.C'.
References browseLimits(), FFinis, SBMEM::fN(), FStart, SBMEM::interval(), MESA, PFinis, PStart, and ScaleCPD2CPY.
Referenced by readDataFile(), and SBSpectrumAnalyserMEM().
void SBSpectrumAnalyserMEM::scan4FPE () [protected, slot]
Definition at line 858 of file SbIMEM.C'.
References ClassName(), SBLog::DATA, FPE_Mfinis, FPE_Mstart, SBLog::INF, SBMEM::isOK(), IsScanning, IsScanStop, Log, M, makeAnalysis(), MESA, Name, Ok, sbMval, Scan, and SBLog::write().
Referenced by SBSpectrumAnalyserMEM().
void SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant (boolIs_) [protected, slot]
Definition at line 659 of file SbIMEM.C'.
References SBAttributed::addAttr(), SBAttributed::delAttr(), SBMEM::ignoreNotEquidistant, and MESA.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::setMEMFillMissingImag (boolIs_) [protected, slot]
Definition at line 670 of file SbIMEM.C'.
References SBAttributed::addAttr(), SBAttributed::delAttr(), SBMEM::fillMissingImag, and MESA.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::setMEMRemoveShifts (boolIs_) [protected, slot]
Definition at line 681 of file SbIMEM.C'.
References SBAttributed::addAttr(), SBAttributed::delAttr(), MESA, and SBMEM::removeShifts.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::setMEMRemoveTrends (boolIs_) [protected, slot]
Definition at line 692 of file SbIMEM.C'.
References SBAttributed::addAttr(), SBAttributed::delAttr(), MESA, and SBMEM::removeTrends.
Referenced by wOptions().
void SBSpectrumAnalyserMEM::setMEMType (intid_) [protected, slot]
Definition at line 712 of file SbIMEM.C'.
References ivMscan, leFPEMfinis, MEMType, MESA, MinFPE, MinFPEOrder, Mmax, sbMval, SBMEM::setType(), Str, and SBMEM::validM().
Referenced by wOptions().
void SBSpectrumAnalyserMEM::setRangeFreq (boolIs_) [protected, slot]
Definition at line 703 of file SbIMEM.C'.
References IsPlotFreq, and redrawSpectrumPlot().
Referenced by wOptions().
void SBSpectrumAnalyserMEM::setScalingCPD2CPY (boolIs_) [protected, slot]
Definition at line 728 of file SbIMEM.C'.
References browseLimits(), dvFFinis, dvFLine, dvFStart, FFinis, FLine, SBMEM::fN(), FStart, MESA, redrawSpectrumPlot(), and ScaleCPD2CPY.
Referenced by wOptions().
QWidget * SBSpectrumAnalyserMEM::wBrowseData () [private]
Definition at line 559 of file SbIMEM.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, Name, SBSetUp::path2TimeSeries(), PCData, PlotData, SBPlotCarrier::setAbsFile4SaveBaseName(), and SetUp.
Referenced by SBSpectrumAnalyserMEM().
QWidget * SBSpectrumAnalyserMEM::wBrowseSpectrum () [private]
Definition at line 587 of file SbIMEM.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, Name, SBSetUp::path2TimeSeries(), PCSpectrum, PlotSpectrum, SBPlot::PM_LINES, SBPlot::PM_WO_BRANCH_NAMES, SBPlot::PM_WO_DOTS, SBPlotCarrier::setAbsFile4SaveBaseName(), and SetUp.
Referenced by SBSpectrumAnalyserMEM().
QWidget * SBSpectrumAnalyserMEM::wMEMCoeffList () [private]
Definition at line 621 of file SbIMEM.C'.
References SBPlotCarrier::branches(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBPlotCarrier::DA_IGN, Name, SBSetUp::path2TimeSeries(), PCFPE, PlotFPE, SBPlot::PM_WO_BRANCH_NAMES, SBPlotCarrier::setAbsFile4SaveBaseName(), and SetUp.
Referenced by SBSpectrumAnalyserMEM().
QWidget * SBSpectrumAnalyserMEM::wOptions () [private]
Definition at line 240 of file SbIMEM.C'.
References cbAssumeEquiDistant, cbFillMissingImag, cbRmShifts, cbRmTrends, cbScaleCPD2CPY, changeFFinis(), changeFPE_Mfinis(), changeFPE_Mstart(), changeFStart(), changeLine2Check(), changeNumOfSpPts(), changePFinis(), changePStart(), SBMEM::dt(), dvFFinis, dvFLine, dvFStart, dvPFinis, dvPStart, FFinis, FLine, FStart, ivMscan, lDT, leFFinis, leFPEMfinis, leFPEMstart, leFStart, leLine2Check, leNumOfSpPts, lePFinis, lePStart, lImportedFileName, lMinFPE, lMinFPEOrder, lNumOfPts, lSampleVar, lShiftI, lShiftR, lTrendI, lTrendR, MESA, MinFPE, MinFPEOrder, Mmax, Mmin, SBMEM::n(), NSp, PFinis, PStart, rbMEMType, SBMEM::sampleVar(), ScaleCPD2CPY, setMEMAssumeEquiDistant(), setMEMFillMissingImag(), setMEMRemoveShifts(), setMEMRemoveTrends(), setMEMType(), setRangeFreq(), setScalingCPD2CPY(), SBMEM::shiftI(), SBMEM::shiftR(), Str, SBMEM::trendI(), SBMEM::trendR(), and SBMEM::type().
Referenced by SBSpectrumAnalyserMEM().
Member Data Documentation
QAccel* SBSpectrumAnalyserMEM::accel [private]
Definition at line 218 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM().
QPushButton* SBSpectrumAnalyserMEM::Analyse [private]
Definition at line 189 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM().
QCheckBox* SBSpectrumAnalyserMEM::cbAssumeEquiDistant [private]
Definition at line 159 of file SbIMEM.H'.
Referenced by wOptions().
QCheckBox* SBSpectrumAnalyserMEM::cbFillMissingImag [private]
Definition at line 160 of file SbIMEM.H'.
Referenced by wOptions().
QCheckBox* SBSpectrumAnalyserMEM::cbRmShifts [private]
Definition at line 161 of file SbIMEM.H'.
Referenced by wOptions().
QCheckBox* SBSpectrumAnalyserMEM::cbRmTrends [private]
Definition at line 162 of file SbIMEM.H'.
Referenced by wOptions().
QCheckBox* SBSpectrumAnalyserMEM::cbScaleCPD2CPY [private]
Definition at line 183 of file SbIMEM.H'.
Referenced by wOptions().
QDoubleValidator* SBSpectrumAnalyserMEM::dvFFinis [private]
Definition at line 175 of file SbIMEM.H'.
Referenced by readDataFile(), setScalingCPD2CPY(), and wOptions().
QDoubleValidator* SBSpectrumAnalyserMEM::dvFLine [private]
Definition at line 176 of file SbIMEM.H'.
Referenced by readDataFile(), setScalingCPD2CPY(), and wOptions().
QDoubleValidator* SBSpectrumAnalyserMEM::dvFStart [private]
Definition at line 174 of file SbIMEM.H'.
Referenced by readDataFile(), setScalingCPD2CPY(), and wOptions().
QDoubleValidator* SBSpectrumAnalyserMEM::dvPFinis [private]
Definition at line 178 of file SbIMEM.H'.
Referenced by wOptions().
QDoubleValidator* SBSpectrumAnalyserMEM::dvPStart [private]
Definition at line 177 of file SbIMEM.H'.
Referenced by wOptions().
double SBSpectrumAnalyserMEM::FFinis [private]
Definition at line 128 of file SbIMEM.H'.
Referenced by browseLimits(), changeFFinis(), readDataFile(), redrawSpectrumPlot(), resetLimits(), SBSpectrumAnalyserMEM(), setScalingCPD2CPY(), and wOptions().
double SBSpectrumAnalyserMEM::FLine [private]
Definition at line 131 of file SbIMEM.H'.
Referenced by browseLimits(), changeLine2Check(), checkLine(), redrawSpectrumPlot(), SBSpectrumAnalyserMEM(), setScalingCPD2CPY(), and wOptions().
int SBSpectrumAnalyserMEM::FPE_Mfinis [private]
Definition at line 133 of file SbIMEM.H'.
Referenced by changeFPE_Mfinis(), SBSpectrumAnalyserMEM(), and scan4FPE().
int SBSpectrumAnalyserMEM::FPE_Mstart [private]
Definition at line 132 of file SbIMEM.H'.
Referenced by changeFPE_Mstart(), SBSpectrumAnalyserMEM(), and scan4FPE().
double SBSpectrumAnalyserMEM::FStart [private]
Definition at line 127 of file SbIMEM.H'.
Referenced by browseLimits(), changeFStart(), readDataFile(), redrawSpectrumPlot(), resetLimits(), SBSpectrumAnalyserMEM(), setScalingCPD2CPY(), and wOptions().
QPushButton* SBSpectrumAnalyserMEM::GetData [private]
Definition at line 188 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM().
bool SBSpectrumAnalyserMEM::IsAutoCalc [private]
Definition at line 124 of file SbIMEM.H'.
Referenced by changeFilterOrder(), and SBSpectrumAnalyserMEM().
bool SBSpectrumAnalyserMEM::IsPlotFreq [private]
Definition at line 126 of file SbIMEM.H'.
Referenced by redrawSpectrumPlot(), SBSpectrumAnalyserMEM(), and setRangeFreq().
bool SBSpectrumAnalyserMEM::IsScanning [private]
Definition at line 134 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM(), and scan4FPE().
bool SBSpectrumAnalyserMEM::IsScanStop [private]
Definition at line 135 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM(), and scan4FPE().
QIntValidator* SBSpectrumAnalyserMEM::ivMscan [private]
Definition at line 179 of file SbIMEM.H'.
Referenced by readDataFile(), setMEMType(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lDT [private]
Definition at line 151 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLineEdit* SBSpectrumAnalyserMEM::leFFinis [private]
Definition at line 166 of file SbIMEM.H'.
Referenced by browseLimits(), and wOptions().
QLineEdit* SBSpectrumAnalyserMEM::leFPEMfinis [private]
Definition at line 170 of file SbIMEM.H'.
Referenced by readDataFile(), setMEMType(), and wOptions().
QLineEdit* SBSpectrumAnalyserMEM::leFPEMstart [private]
Definition at line 169 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLineEdit* SBSpectrumAnalyserMEM::leFStart [private]
Definition at line 165 of file SbIMEM.H'.
Referenced by browseLimits(), and wOptions().
QLineEdit* SBSpectrumAnalyserMEM::leLine2Check [private]
Definition at line 171 of file SbIMEM.H'.
Referenced by browseLimits(), and wOptions().
QLineEdit* SBSpectrumAnalyserMEM::leNumOfSpPts [private]
Definition at line 163 of file SbIMEM.H'.
Referenced by wOptions().
QLineEdit* SBSpectrumAnalyserMEM::lePFinis [private]
Definition at line 168 of file SbIMEM.H'.
Referenced by browseLimits(), and wOptions().
QLineEdit* SBSpectrumAnalyserMEM::lePStart [private]
Definition at line 167 of file SbIMEM.H'.
Referenced by browseLimits(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lImportedFileName [private]
Definition at line 149 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lMinFPE [private]
Definition at line 181 of file SbIMEM.H'.
Referenced by makeAnalysis(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lMinFPEOrder [private]
Definition at line 182 of file SbIMEM.H'.
Referenced by makeAnalysis(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lNumOfPts [private]
Definition at line 150 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lSampleVar [private]
Definition at line 156 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lShiftI [private]
Definition at line 154 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lShiftR [private]
Definition at line 152 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lTrendI [private]
Definition at line 155 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
QLabel* SBSpectrumAnalyserMEM::lTrendR [private]
Definition at line 153 of file SbIMEM.H'.
Referenced by readDataFile(), and wOptions().
unsigned int SBSpectrumAnalyserMEM::M [private]
Definition at line 120 of file SbIMEM.H'.
Referenced by changeFilterOrder(), makeAnalysis(), SBSpectrumAnalyserMEM(), and scan4FPE().
SBMEM::MEMType SBSpectrumAnalyserMEM::MEMType [private]
Definition at line 119 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM(), and setMEMType().
SBMEM* SBSpectrumAnalyserMEM::MESA [private]
Definition at line 118 of file SbIMEM.H'.
Referenced by checkLine(), makeAnalysis(), readDataFile(), redrawDataPlot(), redrawFPEPlot(), redrawSpectrumPlot(), resetLimits(), SBSpectrumAnalyserMEM(), scan4FPE(), setMEMAssumeEquiDistant(), setMEMFillMissingImag(), setMEMRemoveShifts(), setMEMRemoveTrends(), setMEMType(), setScalingCPD2CPY(), wOptions(), and ~SBSpectrumAnalyserMEM().
double SBSpectrumAnalyserMEM::MinFPE [private]
Definition at line 137 of file SbIMEM.H'.
Referenced by makeAnalysis(), readDataFile(), SBSpectrumAnalyserMEM(), setMEMType(), and wOptions().
int SBSpectrumAnalyserMEM::MinFPEOrder [private]
Definition at line 136 of file SbIMEM.H'.
Referenced by makeAnalysis(), readDataFile(), SBSpectrumAnalyserMEM(), setMEMType(), and wOptions().
unsigned int SBSpectrumAnalyserMEM::Mmax [private]
Definition at line 122 of file SbIMEM.H'.
Referenced by readDataFile(), redrawFPEPlot(), SBSpectrumAnalyserMEM(), setMEMType(), and wOptions().
unsigned int SBSpectrumAnalyserMEM::Mmin [private]
Definition at line 121 of file SbIMEM.H'.
Referenced by readDataFile(), SBSpectrumAnalyserMEM(), and wOptions().
QString SBSpectrumAnalyserMEM::Name [private]
Definition at line 123 of file SbIMEM.H'.
Referenced by makeAnalysis(), readDataFile(), redrawDataPlot(), redrawFPEPlot(), redrawSpectrumPlot(), SBSpectrumAnalyserMEM(), scan4FPE(), wBrowseData(), wBrowseSpectrum(), and wMEMCoeffList().
unsigned int SBSpectrumAnalyserMEM::NSp [private]
Definition at line 125 of file SbIMEM.H'.
Referenced by changeNumOfSpPts(), redrawSpectrumPlot(), SBSpectrumAnalyserMEM(), and wOptions().
QPushButton* SBSpectrumAnalyserMEM::Ok [private]
Definition at line 190 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM(), and scan4FPE().
SBPlotCarrier* SBSpectrumAnalyserMEM::PCData [private]
Definition at line 203 of file SbIMEM.H'.
Referenced by redrawDataPlot(), wBrowseData(), and ~SBSpectrumAnalyserMEM().
SBPlotCarrier* SBSpectrumAnalyserMEM::PCFPE [private]
Definition at line 213 of file SbIMEM.H'.
Referenced by redrawFPEPlot(), wMEMCoeffList(), and ~SBSpectrumAnalyserMEM().
SBPlotCarrier* SBSpectrumAnalyserMEM::PCSpectrum [private]
Definition at line 208 of file SbIMEM.H'.
Referenced by checkLine(), redrawSpectrumPlot(), wBrowseSpectrum(), and ~SBSpectrumAnalyserMEM().
double SBSpectrumAnalyserMEM::PFinis [private]
Definition at line 130 of file SbIMEM.H'.
Referenced by browseLimits(), changePFinis(), redrawSpectrumPlot(), resetLimits(), SBSpectrumAnalyserMEM(), and wOptions().
SBPlot* SBSpectrumAnalyserMEM::PlotData [private]
Definition at line 204 of file SbIMEM.H'.
Referenced by redrawDataPlot(), wBrowseData(), and ~SBSpectrumAnalyserMEM().
SBPlot* SBSpectrumAnalyserMEM::PlotFPE [private]
Definition at line 214 of file SbIMEM.H'.
Referenced by redrawFPEPlot(), wMEMCoeffList(), and ~SBSpectrumAnalyserMEM().
SBPlot* SBSpectrumAnalyserMEM::PlotSpectrum [private]
Definition at line 209 of file SbIMEM.H'.
Referenced by redrawSpectrumPlot(), wBrowseSpectrum(), and ~SBSpectrumAnalyserMEM().
double SBSpectrumAnalyserMEM::PStart [private]
Definition at line 129 of file SbIMEM.H'.
Referenced by browseLimits(), changePStart(), redrawSpectrumPlot(), resetLimits(), SBSpectrumAnalyserMEM(), and wOptions().
QRadioButton* SBSpectrumAnalyserMEM::rbMEMType[4] [private]
Definition at line 158 of file SbIMEM.H'.
Referenced by wOptions().
QPushButton* SBSpectrumAnalyserMEM::ResetLimits [private]
Definition at line 187 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM().
QSpinBox* SBSpectrumAnalyserMEM::sbMval [private]
Definition at line 145 of file SbIMEM.H'.
Referenced by readDataFile(), SBSpectrumAnalyserMEM(), scan4FPE(), and setMEMType().
bool SBSpectrumAnalyserMEM::ScaleCPD2CPY [private]
Definition at line 138 of file SbIMEM.H'.
Referenced by checkLine(), redrawSpectrumPlot(), resetLimits(), SBSpectrumAnalyserMEM(), setScalingCPD2CPY(), and wOptions().
QPushButton* SBSpectrumAnalyserMEM::Scan [private]
Definition at line 191 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM(), and scan4FPE().
QString SBSpectrumAnalyserMEM::Str [private]
Definition at line 141 of file SbIMEM.H'.
Referenced by browseLimits(), checkLine(), makeAnalysis(), readDataFile(), SBSpectrumAnalyserMEM(), setMEMType(), and wOptions().
QTabWidget* SBSpectrumAnalyserMEM::Tab [private]
Definition at line 144 of file SbIMEM.H'.
Referenced by SBSpectrumAnalyserMEM().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.