.TH "SBSpline" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBSpline \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbMathSpline\&.H>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBSpline\fP (unsigned int, unsigned int=1)"
.br
.ti -1c
.RI "virtual \fB~SBSpline\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "unsigned int \fBnDimension\fP () const "
.br
.ti -1c
.RI "unsigned int \fBn\fP () const "
.br
.ti -1c
.RI "\fBSBMatrix\fP * \fBb\fP ()"
.br
.ti -1c
.RI "bool \fBisReady\fP () const "
.br
.ti -1c
.RI "virtual void \fBprepare4Spline\fP ()"
.br
.ti -1c
.RI "virtual double \fBspline\fP (unsigned int, double)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsolveSpline\fP (unsigned int)"
.br
.ti -1c
.RI "double \fBh\fP (unsigned int i) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSBMatrix\fP * \fBB\fP"
.br
.ti -1c
.RI "bool \fBIsOK\fP"
.br
.ti -1c
.RI "bool \fBIsReady\fP"
.br
.ti -1c
.RI "unsigned int \fBNDimension\fP"
.br
.RI "\fIthe dimension of a vector to spline \fP"
.ti -1c
.RI "unsigned int \fBN\fP"
.br
.RI "\fIthe number of points \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file SbMathSpline\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBSpline::SBSpline (unsigned intN_, unsigned intM_ = \fC1\fP)"
.PP
Definition at line 31 of file SbMathSpline\&.C'\&.
.PP
References B, ClassName(), SBLog::ERR, IsOK, IsReady, Log, N, NDimension, SBLog::SPLINE, and SBLog::write()\&.
.SS "SBSpline::~SBSpline ()\fC [virtual]\fP"A destructor'\&. 
.PP
Definition at line 49 of file SbMathSpline\&.C'\&.
.PP
References B\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSBMatrix\fP* SBSpline::b ()\fC [inline]\fP"
.PP
Definition at line 66 of file SbMathSpline\&.H'\&.
.PP
References B\&.
.PP
Referenced by SBTestAPLoad::fillData4Plotting(), SBAploEphem::getReady(), and SBEOP::prepare4Date()\&.
.SS "virtual QString SBSpline::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info)'\&. 
.PP
Definition at line 60 of file SbMathSpline\&.H'\&.
.PP
Referenced by prepare4Spline(), SBSpline(), and spline()\&.
.SS "double SBSpline::h (unsigned inti) const\fC [inline, protected]\fP"
.PP
Definition at line 51 of file SbMathSpline\&.H'\&.
.PP
References SBMatrix::at(), and B\&.
.PP
Referenced by solveSpline(), and spline()\&.
.SS "bool SBSpline::isReady () const\fC [inline]\fP"
.PP
Definition at line 67 of file SbMathSpline\&.H'\&.
.PP
References IsReady\&.
.PP
Referenced by SBAploEphem::displacement()\&.
.SS "unsigned int SBSpline::n () const\fC [inline]\fP"
.PP
Definition at line 65 of file SbMathSpline\&.H'\&.
.PP
References N\&.
.SS "unsigned int SBSpline::nDimension () const\fC [inline]\fP"
.PP
Definition at line 64 of file SbMathSpline\&.H'\&.
.PP
References NDimension\&.
.SS "void SBSpline::prepare4Spline ()\fC [virtual]\fP"
.PP
Definition at line 58 of file SbMathSpline\&.C'\&.
.PP
References SBMatrix::at(), B, ClassName(), SBLog::ERR, IsReady, Log, N, NDimension, solveSpline(), SBLog::SPLINE, and SBLog::write()\&.
.PP
Referenced by SBEOP::prepare4Date()\&.
.SS "void SBSpline::solveSpline (unsigned intnCol)\fC [protected]\fP"
.PP
Definition at line 82 of file SbMathSpline\&.C'\&.
.PP
References SBVector::at(), SBMatrix::at(), B, h(), N, and NDimension\&.
.PP
Referenced by prepare4Spline()\&.
.SS "double SBSpline::spline (unsigned intnCol, doublex)\fC [virtual]\fP"
.PP
Definition at line 112 of file SbMathSpline\&.C'\&.
.PP
References SBMatrix::at(), B, ClassName(), SBLog::ERR, h(), IsReady, Log, N, NDimension, SBLog::SPLINE, and SBLog::write()\&.
.PP
Referenced by SBAploEphem::displacement(), and SBEOP::interpolateEOPs()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBMatrix\fP* \fBSBSpline::B\fP\fC [protected]\fP"
.PP
Definition at line 44 of file SbMathSpline\&.H'\&.
.PP
Referenced by b(), h(), prepare4Spline(), SBSpline(), solveSpline(), spline(), and ~SBSpline()\&.
.SS "bool \fBSBSpline::IsOK\fP\fC [protected]\fP"
.PP
Definition at line 45 of file SbMathSpline\&.H'\&.
.PP
Referenced by SBSpline()\&.
.SS "bool \fBSBSpline::IsReady\fP\fC [protected]\fP"
.PP
Definition at line 46 of file SbMathSpline\&.H'\&.
.PP
Referenced by isReady(), prepare4Spline(), SBSpline(), and spline()\&.
.SS "unsigned int \fBSBSpline::N\fP\fC [protected]\fP"
.PP
the number of points 
.PP
Definition at line 48 of file SbMathSpline\&.H'\&.
.PP
Referenced by n(), prepare4Spline(), SBSpline(), solveSpline(), and spline()\&.
.SS "unsigned int \fBSBSpline::NDimension\fP\fC [protected]\fP"
.PP
the dimension of a vector to spline 
.PP
Definition at line 47 of file SbMathSpline\&.H'\&.
.PP
Referenced by nDimension(), prepare4Spline(), SBSpline(), solveSpline(), and spline()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
