SBSpline
NAME
SBSpline -
SYNOPSIS
#include <SbMathSpline.H>
Public Member Functions
SBSpline (unsigned int, unsigned int=1)
virtual ~SBSpline ()
virtual QString ClassName () const
unsigned int nDimension () const
unsigned int n () const
SBMatrix * b ()
bool isReady () const
virtual void prepare4Spline ()
virtual double spline (unsigned int, double)
Protected Member Functions
void solveSpline (unsigned int)
double h (unsigned int i) const
Protected Attributes
SBMatrix * B
bool IsOK
bool IsReady
unsigned int NDimension
the dimension of a vector to spline
unsigned int N
the number of points
Detailed Description
Definition at line 41 of file SbMathSpline.H'.
Constructor & Destructor Documentation
SBSpline::SBSpline (unsigned intN_, unsigned intM_ = 1)
Definition at line 31 of file SbMathSpline.C'.
References B, ClassName(), SBLog::ERR, IsOK, IsReady, Log, N, NDimension, SBLog::SPLINE, and SBLog::write().
SBSpline::~SBSpline () [virtual]"A destructor'.
Definition at line 49 of file SbMathSpline.C'.
References B.
Member Function Documentation
SBMatrix* SBSpline::b () [inline]
Definition at line 66 of file SbMathSpline.H'.
References B.
Referenced by SBTestAPLoad::fillData4Plotting(), SBAploEphem::getReady(), and SBEOP::prepare4Date().
virtual QString SBSpline::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Definition at line 60 of file SbMathSpline.H'.
Referenced by prepare4Spline(), SBSpline(), and spline().
double SBSpline::h (unsigned inti) const [inline, protected]
Definition at line 51 of file SbMathSpline.H'.
References SBMatrix::at(), and B.
Referenced by solveSpline(), and spline().
bool SBSpline::isReady () const [inline]
Definition at line 67 of file SbMathSpline.H'.
References IsReady.
Referenced by SBAploEphem::displacement().
unsigned int SBSpline::n () const [inline]
Definition at line 65 of file SbMathSpline.H'.
References N.
unsigned int SBSpline::nDimension () const [inline]
Definition at line 64 of file SbMathSpline.H'.
References NDimension.
void SBSpline::prepare4Spline () [virtual]
Definition at line 58 of file SbMathSpline.C'.
References SBMatrix::at(), B, ClassName(), SBLog::ERR, IsReady, Log, N, NDimension, solveSpline(), SBLog::SPLINE, and SBLog::write().
Referenced by SBEOP::prepare4Date().
void SBSpline::solveSpline (unsigned intnCol) [protected]
Definition at line 82 of file SbMathSpline.C'.
References SBVector::at(), SBMatrix::at(), B, h(), N, and NDimension.
Referenced by prepare4Spline().
double SBSpline::spline (unsigned intnCol, doublex) [virtual]
Definition at line 112 of file SbMathSpline.C'.
References SBMatrix::at(), B, ClassName(), SBLog::ERR, h(), IsReady, Log, N, NDimension, SBLog::SPLINE, and SBLog::write().
Referenced by SBAploEphem::displacement(), and SBEOP::interpolateEOPs().
Member Data Documentation
SBMatrix* SBSpline::B [protected]
Definition at line 44 of file SbMathSpline.H'.
Referenced by b(), h(), prepare4Spline(), SBSpline(), solveSpline(), spline(), and ~SBSpline().
bool SBSpline::IsOK [protected]
Definition at line 45 of file SbMathSpline.H'.
Referenced by SBSpline().
bool SBSpline::IsReady [protected]
Definition at line 46 of file SbMathSpline.H'.
Referenced by isReady(), prepare4Spline(), SBSpline(), and spline().
unsigned int SBSpline::N [protected]
the number of points
Definition at line 48 of file SbMathSpline.H'.
Referenced by n(), prepare4Spline(), SBSpline(), solveSpline(), and spline().
unsigned int SBSpline::NDimension [protected]
the dimension of a vector to spline
Definition at line 47 of file SbMathSpline.H'.
Referenced by nDimension(), prepare4Spline(), SBSpline(), solveSpline(), and spline().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.