SBSrcMap
NAME
SBSrcMap -
SYNOPSIS
#include <SbGeoSourceMap.H>
Inherits SBAttributed'.
Public Types
enum Attributes { One = 1<<0, Two = 2<<0 }
Public Member Functions
SBSrcMap ()
virtual ~SBSrcMap ()
virtual QString ClassName () const
bool importFITS (const QString &)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Private Attributes
QString FITSFileName
name of a FITS file from which the map was imported
QString kAuthor
an author of the FITS file
QString kCreator
program which produced FITS file
QString kCType1
axis #1 name
QString kCType2
axis #2 name
QString kCType3
axis #3 name
QString kCType4
axis #4 name
QString kDateObs
observation date
QString kInstrument
instrument used
QString kObject
name of observed source (IAU name?)
QString kObserver
VLBA experiment code'.
QString kOrigin
origin of data
QString kProject
QString kSegment
QString kTelescop
telescope used
QString kBUnit
unit of measurement
int kNIter
number of model components
double kBMaj
Clean beam major axis diameter (degrees)
double kBMin
Clean beam minor axis diameter (degrees)
double kBPA
Clean beam position angle (degrees)
double kCDelt1
Pixel increment for axis #1'.
double kCDelt2
Pixel increment for axis #2'.
double kCDelt3
Pixel increment for axis #3'.
double kCDelt4
Pixel increment for axis #4'.
double kCRota1
Axis #1 rotation'.
double kCRota2
Axis #2 rotation'.
double kCRota3
Axis #3 rotation'.
double kCRota4
Axis #4 rotation'.
double kCRPix1
Reference pixel for axis #1'.
double kCRPix2
Reference pixel for axis #2'.
double kCRPix3
Reference pixel for axis #3'.
double kCRPix4
Reference pixel for axis #4'.
double kCRVal1
Reference value in right ascens'. (deg)
double kCRVal2
Reference value in declination (deg)
double kCRVal3
Reference value for axis #3'.
double kCRVal4
Reference value for axis #4'.
double kEpoch
Equinox of coordinates'.
double kFluxInt
Total flux density integrated over the map (Jy)
double kFluxShr
Flux density at short baselines (Jy)
double kFluxUnr
Unresolved flux density at long baselines (Jy)
double kImageNoise
Image 1-sigma noise (Jy)
double kNoise
rms of the input visibilities (Jy)
double kObsDec
Antenna pointing Dec'.
double kObsRA
Antenna pointing RA'.
double kPOS_Err
1-sigma error ellipse semi-major axis (rad)
double kRA_D_Corr
Correl'. between right ascens'. and decl'. errors'.
double kDataMax
Max data'.
double kDataMin
Min data'.
SBMatrix Image
a map itself
QString Name
name of a source
Friends
QDataStream & operator<< (QDataStream &, const SBSrcMap &)
QDataStream & operator>> (QDataStream &, SBSrcMap &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Provides a map of brightness distribution for radio source'.
Definition at line 41 of file SbGeoSourceMap.H'.
Member Enumeration Documentation
enum SBSrcMap::Attributes
Enumerator:
One
test 1
Two
test 2
Definition at line 44 of file SbGeoSourceMap.H'.
Constructor & Destructor Documentation
SBSrcMap::SBSrcMap ()"A default constructor'. < an author of the FITS file
< program which produced FITS file
< axis #1 name
< axis #2 name
< axis #3 name
< axis #4 name
< observation date
< instrument used
< name of observed source (IAU name?)
< VLBA experiment code
< origin of data
<
<
< telescope used
< unit of measurement
< number of model components
< Clean beam major axis diameter (degrees)
< Clean beam minor axis diameter (degrees)
< Clean beam position angle (degrees)
< Pixel increment for axis #1
< Pixel increment for axis #2
< Pixel increment for axis #3
< Pixel increment for axis #4
< Axis #1 rotation
< Axis #2 rotation
< Axis #3 rotation
< Axis #4 rotation
< Reference pixel for axis #1
< Reference pixel for axis #2
< Reference pixel for axis #3
< Reference pixel for axis #4
< Reference value in right ascens'. (deg)
< Reference value in declination (deg)
< Reference value for axis #3
< Reference value for axis #4
< Equinox of coordinates
< Total flux density integrated over the map (Jy)
< Flux density at short baselines (Jy)
< Unresolved flux density at long baselines (Jy)
< Image 1-sigma noise (Jy)
< rms of the input visibilities (Jy)
< Antenna pointing Dec
< Antenna pointing RA
< 1-sigma error ellipse semi-major axis (rad)
< Correl'. between right ascens'. and decl'. errors
< Max data
< Min data
Definition at line 41 of file SbGeoSourceMap.C'.
References FITSFileName, kAuthor, kBMaj, kBMin, kBPA, kBUnit, kCDelt1, kCDelt2, kCDelt3, kCDelt4, kCreator, kCRota1, kCRota2, kCRota3, kCRota4, kCRPix1, kCRPix2, kCRPix3, kCRPix4, kCRVal1, kCRVal2, kCRVal3, kCRVal4, kCType1, kCType2, kCType3, kCType4, kDataMax, kDataMin, kDateObs, kEpoch, kFluxInt, kFluxShr, kFluxUnr, kImageNoise, kInstrument, kNIter, kNoise, kObject, kObsDec, kObserver, kObsRA, kOrigin, kPOS_Err, kProject, kRA_D_Corr, kSegment, kTelescop, and Name.
SBSrcMap::~SBSrcMap () [virtual]"A destructor'.
Definition at line 95 of file SbGeoSourceMap.C'.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual QString SBSrcMap::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBAttributed'.
Definition at line 114 of file SbGeoSourceMap.H'.
Referenced by importFITS().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
bool SBSrcMap::importFITS (const QString &FITSInputFileName)
Definition at line 99 of file SbGeoSourceMap.C'.
References ClassName(), FITSFileName, SBLog::IO, kAuthor, kBMaj, kBMin, kBPA, kBUnit, kCDelt1, kCDelt2, kCDelt3, kCDelt4, kCreator, kCRota1, kCRota2, kCRota3, kCRota4, kCRPix1, kCRPix2, kCRPix3, kCRPix4, kCRVal1, kCRVal2, kCRVal3, kCRVal4, kCType1, kCType2, kCType3, kCType4, kDataMax, kDataMin, kDateObs, kEpoch, kFluxInt, kFluxShr, kFluxUnr, kImageNoise, kInstrument, kNIter, kNoise, kObject, kObsDec, kObserver, kObsRA, kOrigin, kPOS_Err, kProject, kRA_D_Corr, kSegment, kTelescop, Log, SBLog::write(), and SBLog::WRN.
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
QDataStream & operator<< (QDataStream &s, const SBSrcMap &M) [friend]"Output to the data stream'.
Definition at line 577 of file SbGeoSourceMap.C'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream & operator>> (QDataStream &s, SBSrcMap &M) [friend]"Input from the data stream'.
Definition at line 640 of file SbGeoSourceMap.C'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
Member Data Documentation
QString SBSrcMap::FITSFileName [private]
name of a FITS file from which the map was imported
Definition at line 52 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
SBMatrix SBSrcMap::Image [private]
a map itself
Definition at line 102 of file SbGeoSourceMap.H'.
QString SBSrcMap::kAuthor [private]
an author of the FITS file
Definition at line 54 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kBMaj [private]
Clean beam major axis diameter (degrees)
Definition at line 70 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kBMin [private]
Clean beam minor axis diameter (degrees)
Definition at line 71 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kBPA [private]
Clean beam position angle (degrees)
Definition at line 72 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kBUnit [private]
unit of measurement
Definition at line 68 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCDelt1 [private]
Pixel increment for axis #1'.
Definition at line 73 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCDelt2 [private]
Pixel increment for axis #2'.
Definition at line 74 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCDelt3 [private]
Pixel increment for axis #3'.
Definition at line 75 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCDelt4 [private]
Pixel increment for axis #4'.
Definition at line 76 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kCreator [private]
program which produced FITS file
Definition at line 55 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRota1 [private]
Axis #1 rotation'.
Definition at line 77 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRota2 [private]
Axis #2 rotation'.
Definition at line 78 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRota3 [private]
Axis #3 rotation'.
Definition at line 79 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRota4 [private]
Axis #4 rotation'.
Definition at line 80 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRPix1 [private]
Reference pixel for axis #1'.
Definition at line 81 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRPix2 [private]
Reference pixel for axis #2'.
Definition at line 82 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRPix3 [private]
Reference pixel for axis #3'.
Definition at line 83 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRPix4 [private]
Reference pixel for axis #4'.
Definition at line 84 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRVal1 [private]
Reference value in right ascens'. (deg)
Definition at line 85 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRVal2 [private]
Reference value in declination (deg)
Definition at line 86 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRVal3 [private]
Reference value for axis #3'.
Definition at line 87 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kCRVal4 [private]
Reference value for axis #4'.
Definition at line 88 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kCType1 [private]
axis #1 name
Definition at line 56 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kCType2 [private]
axis #2 name
Definition at line 57 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kCType3 [private]
axis #3 name
Definition at line 58 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kCType4 [private]
axis #4 name
Definition at line 59 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kDataMax [private]
Max data'.
Definition at line 99 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kDataMin [private]
Min data'.
Definition at line 100 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kDateObs [private]
observation date
Definition at line 60 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kEpoch [private]
Equinox of coordinates'.
Definition at line 89 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kFluxInt [private]
Total flux density integrated over the map (Jy)
Definition at line 90 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kFluxShr [private]
Flux density at short baselines (Jy)
Definition at line 91 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kFluxUnr [private]
Unresolved flux density at long baselines (Jy)
Definition at line 92 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kImageNoise [private]
Image 1-sigma noise (Jy)
Definition at line 93 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kInstrument [private]
instrument used
Definition at line 61 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
int SBSrcMap::kNIter [private]
number of model components
Definition at line 69 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kNoise [private]
rms of the input visibilities (Jy)
Definition at line 94 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kObject [private]
name of observed source (IAU name?)
Definition at line 62 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kObsDec [private]
Antenna pointing Dec'.
Definition at line 95 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kObserver [private]
VLBA experiment code'.
Definition at line 63 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kObsRA [private]
Antenna pointing RA'.
Definition at line 96 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kOrigin [private]
origin of data
Definition at line 64 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kPOS_Err [private]
1-sigma error ellipse semi-major axis (rad)
Definition at line 97 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kProject [private]
Definition at line 65 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
double SBSrcMap::kRA_D_Corr [private]
Correl'. between right ascens'. and decl'. errors'.
Definition at line 98 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kSegment [private]
Definition at line 66 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::kTelescop [private]
telescope used
Definition at line 67 of file SbGeoSourceMap.H'.
Referenced by importFITS(), and SBSrcMap().
QString SBSrcMap::Name [private]
name of a source
Definition at line 103 of file SbGeoSourceMap.H'.
Referenced by SBSrcMap().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.