SBStationEditor
NAME
SBStationEditor -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits SBTabDialog'.
Signals
void stationModified (bool)
Public Member Functions
SBStationEditor (SBStationListItem *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
SBStationEditor (QListView *, SBSite *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBStationEditor ()
virtual QString ClassName () const
Protected Slots
virtual void makeApply ()
void addCoordinates ()
void delCoordinates ()
void editCoordinates (QListViewItem *)
void modified (bool)
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Member Functions
virtual void acquireData ()
void init ()
QWidget * wNames ()
QWidget * wTechs ()
QWidget * wCoordinates ()
QWidget * wCoordList (QWidget *)
QWidget * wStats ()
QWidget * wOLoad ()
Private Attributes
SBOLoadEditor * OLoadEditor
QListView * StationsLV
SBStationListItem * StationItem
SBStation * Station
SBSite * Site
bool isModified
bool isNew
QString Str
QLineEdit * EDome
QRadioButton * RBPtType [2]
QLineEdit * EName
QLineEdit * ECDP
QLineEdit * ECharID
QLineEdit * EDescr
QMultiLineEdit * MEComments
QGroupBox * NameGBox
QRadioButton * RBTech [11]
QListView * CoordsLV
QLineEdit * EV [3]
QLineEdit * EdV [3]
QRadioButton * RBMountType [6]
QLineEdit * EAxisOffset
QLabel * LLongitude
QLabel * LLatitude
QLabel * LHeight
QCheckBox * CDOrigin [4]
QCheckBox * CDAttr [4]
Detailed Description
Definition at line 497 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBStationEditor::SBStationEditor (SBStationListItem *StationItem_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 3017 of file SbIStuffStation.C'.
References init(), isNew, Site, SBStation::site(), SBStationListItem::Station, Station, StationItem, and StationsLV.
SBStationEditor::SBStationEditor (QListView *StationsLV_, SBSite *Site_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 3030 of file SbIStuffStation.C'.
References init(), isNew, Site, Station, StationItem, and StationsLV.
SBStationEditor::~SBStationEditor ()
Definition at line 3059 of file SbIStuffStation.C'.
References isModified, isNew, Station, and stationModified().
Member Function Documentation
void SBStationEditor::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 3666 of file SbIStuffStation.C'.
References Vector3::at(), SBStation::axisOffset(), SBStation::CDP(), SBStation::charID(), SBOLoadEditor::collectData(), SBStation::comments(), SBStation::createOLoad(), SBStation::deleteOLoad(), SBStation::description(), EAxisOffset, ECDP, ECharID, EDescr, EDome, EdV, EName, EV, SBStation::hasOwnOLoad, SBAttributed::isAttr(), SBOLoadEditor::isDisabled, isModified, isNew, MEComments, SBStation::Mnt_AZEL, SBStation::Mnt_EQUA, SBStation::Mnt_Richmond, SBStation::Mnt_Unkn, SBStation::Mnt_X_YE, SBStation::Mnt_X_YN, SBStation::mountType(), SBNamed::name(), SBOLoadEditor::OLoad, OLoadEditor, SBStation::Pt_Antenna, SBStation::Pt_Marker, RBMountType, RBPtType, RBTech, SBStation::setAxisOffset(), SBStation::setCDP(), SBStation::setCharID(), SBStation::setComments(), SBStation::setDescription(), SBStation::setDomeMinor(), SBStation::setMountType(), SBNamed::setName(), SBStation::setOLoad(), SBStation::setPointType(), SBStation::setTech(), SBStation::setV_err_i(), SBStation::setV_i(), Station, Str, SBStation::tech(), TECH_AD, TECH_CG, TECH_COMBINED, TECH_DORIS, TECH_GPS, TECH_LLR, TECH_OA, TECH_SLR, TECH_TIE, TECH_UNKN, TECH_VLBI, SBStation::v(), and SBStation::v_err().
Referenced by makeApply().
void SBStationEditor::addCoordinates () [protected, slot]
Definition at line 3637 of file SbIStuffStation.C'.
References CoordsLV, SBStation::dR_first(), modified(), SBStation::r_first(), SBStation::refPt(), Station, TZero, v3Unit, and v3Zero.
Referenced by wCoordList().
virtual QString SBStationEditor::ClassName () const [inline, virtual]
Definition at line 504 of file SbIStuffStation.H'.
Referenced by delCoordinates(), and makeApply().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
void SBStationEditor::delCoordinates () [protected, slot]
Definition at line 3610 of file SbIStuffStation.C'.
References ClassName(), SBCoordsListItem::coords(), CoordsLV, SBLog::ERR, SBLog::INTERFACE, isModified, Log, SBStation::refPt(), Station, SBMJD::toString(), and SBLog::write().
Referenced by wCoordList().
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
void SBStationEditor::editCoordinates (QListViewItem *) [protected, slot]
Definition at line 3649 of file SbIStuffStation.C'.
References CoordsLV, modified(), and Station.
Referenced by wCoordList().
void SBStationEditor::init () [private]
Definition at line 3043 of file SbIStuffStation.C'.
References isModified, makeApply(), wCoordinates(), wNames(), wOLoad(), wStats(), and wTechs().
Referenced by SBStationEditor().
void SBStationEditor::makeApply () [protected, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 3065 of file SbIStuffStation.C'.
References acquireData(), SBAttributed::addAttr(), SBSite::addStation(), ClassName(), SBLog::DBG, EDome, SBSite::find(), SBStation::height(), SBStation::id(), SBLog::INTERFACE, isModified, isNew, SBStation::latitude(), LHeight, LLatitude, LLongitude, Log, SBStation::longitude(), SBNamed::name(), SBStation::OrigEdited, rad2dms(), rad2dmsl(), Site, Station, StationItem, StationsLV, Str, SBStationID::toString(), TZero, SBStation::updateGeodCoo(), and SBLog::write().
Referenced by init().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBStationEditor::modified (boolIsModified_) [protected, slot]
Definition at line 3660 of file SbIStuffStation.C'.
References CoordsLV, and isModified.
Referenced by addCoordinates(), and editCoordinates().
void SBStationEditor::stationModified (boolt0) [signal]
Definition at line 903 of file SbIStuffStation.moc.C'.
Referenced by ~SBStationEditor().
QWidget * SBStationEditor::wCoordinates () [private]
Definition at line 3360 of file SbIStuffStation.C'.
References Vector3::at(), SBStation::axisOffset(), EAxisOffset, EdV, EV, SBStation::height(), SBStation::latitude(), LHeight, LLatitude, LLongitude, SBStation::longitude(), SBStation::mountType(), rad2dms(), rad2dmsl(), RBMountType, Station, Str, SBStation::v(), SBStation::v_err(), and wCoordList().
Referenced by init().
QWidget * SBStationEditor::wCoordList (QWidget *parent_) [private]
Definition at line 3281 of file SbIStuffStation.C'.
References addCoordinates(), CoordsLV, delCoordinates(), editCoordinates(), SBStation::refPt(), and Station.
Referenced by wCoordinates().
QWidget * SBStationEditor::wNames () [private]
Definition at line 3130 of file SbIStuffStation.C'.
References SBStation::CDP(), SBStation::charID(), SBStation::comments(), SBStation::description(), SBStation::domeMinor(), ECDP, ECharID, EDescr, EDome, EName, SBStation::id(), isNew, MEComments, SBNamed::name(), NameGBox, SBStation::pointType(), RBPtType, Station, Str, and SBStationID::toString().
Referenced by init().
QWidget * SBStationEditor::wOLoad () [private]
Definition at line 3597 of file SbIStuffStation.C'.
References SBStation::oLoad(), OLoadEditor, and Station.
Referenced by init().
QWidget * SBStationEditor::wStats () [private]
Definition at line 3523 of file SbIStuffStation.C'.
References SBStation::Analysed, CDAttr, CDOrigin, SBAttributed::isAttr(), SBStation::OrigEdited, SBStation::OrigEstimated, SBStation::OrigImported, SBStation::OrigObsData, SBStation::Reserved_10, SBStation::Reserved_11, SBStation::Reserved_12, and Station.
Referenced by init().
QWidget * SBStationEditor::wTechs () [private]
Definition at line 3247 of file SbIStuffStation.C'.
References RBTech, Station, SBStation::tech(), and SBSolutionName::techName().
Referenced by init().
Member Data Documentation
QCheckBox* SBStationEditor::CDAttr[4] [private]
Definition at line 563 of file SbIStuffStation.H'.
Referenced by wStats().
QCheckBox* SBStationEditor::CDOrigin[4] [private]
Definition at line 562 of file SbIStuffStation.H'.
Referenced by wStats().
QListView* SBStationEditor::CoordsLV [private]
Definition at line 551 of file SbIStuffStation.H'.
Referenced by addCoordinates(), delCoordinates(), editCoordinates(), modified(), and wCoordList().
QLineEdit* SBStationEditor::EAxisOffset [private]
Definition at line 556 of file SbIStuffStation.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBStationEditor::ECDP [private]
Definition at line 541 of file SbIStuffStation.H'.
Referenced by acquireData(), and wNames().
QLineEdit* SBStationEditor::ECharID [private]
Definition at line 542 of file SbIStuffStation.H'.
Referenced by acquireData(), and wNames().
QLineEdit* SBStationEditor::EDescr [private]
Definition at line 543 of file SbIStuffStation.H'.
Referenced by acquireData(), and wNames().
QLineEdit* SBStationEditor::EDome [private]
Definition at line 538 of file SbIStuffStation.H'.
Referenced by acquireData(), makeApply(), and wNames().
QLineEdit* SBStationEditor::EdV[3] [private]
Definition at line 553 of file SbIStuffStation.H'.
Referenced by acquireData(), and wCoordinates().
QLineEdit* SBStationEditor::EName [private]
Definition at line 540 of file SbIStuffStation.H'.
Referenced by acquireData(), and wNames().
QLineEdit* SBStationEditor::EV[3] [private]
Definition at line 552 of file SbIStuffStation.H'.
Referenced by acquireData(), and wCoordinates().
bool SBStationEditor::isModified [private]
Definition at line 533 of file SbIStuffStation.H'.
Referenced by acquireData(), delCoordinates(), init(), makeApply(), modified(), and ~SBStationEditor().
bool SBStationEditor::isNew [private]
Definition at line 534 of file SbIStuffStation.H'.
Referenced by acquireData(), makeApply(), SBStationEditor(), wNames(), and ~SBStationEditor().
QLabel* SBStationEditor::LHeight [private]
Definition at line 559 of file SbIStuffStation.H'.
Referenced by makeApply(), and wCoordinates().
QLabel* SBStationEditor::LLatitude [private]
Definition at line 558 of file SbIStuffStation.H'.
Referenced by makeApply(), and wCoordinates().
QLabel* SBStationEditor::LLongitude [private]
Definition at line 557 of file SbIStuffStation.H'.
Referenced by makeApply(), and wCoordinates().
QMultiLineEdit* SBStationEditor::MEComments [private]
Definition at line 544 of file SbIStuffStation.H'.
Referenced by acquireData(), and wNames().
QGroupBox* SBStationEditor::NameGBox [private]
Definition at line 545 of file SbIStuffStation.H'.
Referenced by wNames().
SBOLoadEditor* SBStationEditor::OLoadEditor [private]
Definition at line 528 of file SbIStuffStation.H'.
Referenced by acquireData(), and wOLoad().
QRadioButton* SBStationEditor::RBMountType[6] [private]
Definition at line 555 of file SbIStuffStation.H'.
Referenced by acquireData(), and wCoordinates().
QRadioButton* SBStationEditor::RBPtType[2] [private]
Definition at line 539 of file SbIStuffStation.H'.
Referenced by acquireData(), and wNames().
QRadioButton* SBStationEditor::RBTech[11] [private]
Definition at line 548 of file SbIStuffStation.H'.
Referenced by acquireData(), and wTechs().
SBSite* SBStationEditor::Site [private]
Definition at line 532 of file SbIStuffStation.H'.
Referenced by makeApply(), and SBStationEditor().
SBStation* SBStationEditor::Station [private]
Definition at line 531 of file SbIStuffStation.H'.
Referenced by acquireData(), addCoordinates(), delCoordinates(), editCoordinates(), makeApply(), SBStationEditor(), wCoordinates(), wCoordList(), wNames(), wOLoad(), wStats(), wTechs(), and ~SBStationEditor().
SBStationListItem* SBStationEditor::StationItem [private]
Definition at line 530 of file SbIStuffStation.H'.
Referenced by makeApply(), and SBStationEditor().
QListView* SBStationEditor::StationsLV [private]
Definition at line 529 of file SbIStuffStation.H'.
Referenced by makeApply(), and SBStationEditor().
QString SBStationEditor::Str [private]
Definition at line 535 of file SbIStuffStation.H'.
Referenced by acquireData(), makeApply(), wCoordinates(), and wNames().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.