.TH "SBSTideUT1::TableEntry" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBSTideUT1::TableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBN\fP [5]"
.br
.ti -1c
.RI "double \fBB\fP"
.br
.ti -1c
.RI "double \fBC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file SbGeoRefFrame\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBSTideUT1::TableEntry::B\fP"
.PP
Definition at line 124 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBSTideUT1::calc()\&.
.SS "double \fBSBSTideUT1::TableEntry::C\fP"
.PP
Definition at line 124 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBSTideUT1::calc()\&.
.SS "short \fBSBSTideUT1::TableEntry::N\fP[5]"
.PP
Definition at line 123 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by SBSTideUT1::calc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
