SBStuffSources
NAME
SBStuffSources -
SYNOPSIS
#include <SbIStuffSource.H>
Inherits QDialog'.
Public Member Functions
SBStuffSources (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBStuffSources ()
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Private Slots
void importData ()
void exportData ()
void accept ()
void reject ()
void reloadCRF ()
void editEntryA (QListViewItem *)
void insertEntryA ()
void deleteEntryA ()
void editEntryS (QListViewItem *)
void insertEntryS ()
void deleteEntryS ()
void CRFModified (bool)
Private Member Functions
void drawInfo ()
Private Attributes
SB_CRF * Wcrf
QString str
QListView * SourcesLV
QListView * AliasesLV
QLineEdit * CRFEpoch
QLineEdit * CRFLabel
QLineEdit * CRFComment
QLabel * NumSA
bool isModifiedCRF
int numOpenedWindows
Detailed Description
Definition at line 105 of file SbIStuffSource.H'.
Constructor & Destructor Documentation
SBStuffSources::SBStuffSources (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 240 of file SbIStuffSource.C'.
References accept(), SBCatalog::aliasDict(), AliasesLV, SBCatalog::comment(), CRFComment, CRFEpoch, CRFLabel, deleteEntryA(), deleteEntryS(), editEntryA(), editEntryS(), SBCatalog::epoch(), exportData(), SBMJD::F_Year, SB_CRF::first(), importData(), insertEntryA(), insertEntryS(), SBCatalog::inSort(), isModifiedCRF, SBCatalog::label(), SBSetUp::loadCRF(), SB_CRF::next(), numOpenedWindows, NumSA, SB_CRF::prepareAliases4Output(), reject(), SetUp, SourcesLV, str, SBMJD::toString(), SBSolutionName::toString(), and Wcrf.
SBStuffSources::~SBStuffSources ()
Definition at line 440 of file SbIStuffSource.C'.
References SB_CRF::releaseAliases4Output(), and Wcrf.
Member Function Documentation
void SBStuffSources::accept () [private, slot]
Definition at line 449 of file SbIStuffSource.C'.
References SBCatalog::comment(), CRFComment, CRFEpoch, CRFLabel, SBCatalog::epoch(), SBMJD::F_Year, SBSolutionName::fromString(), isModifiedCRF, SBCatalog::label(), numOpenedWindows, SBSetUp::saveCRF(), SBCatalog::setComment(), SBCatalog::setEpoch(), SBCatalog::setLabel(), SBMJD::setMJD(), SetUp, str, SBMJD::toString(), SBSolutionName::TYPE_RSC, and Wcrf.
Referenced by SBStuffSources().
virtual QString SBStuffSources::ClassName () const [inline, virtual]
Definition at line 112 of file SbIStuffSource.H'.
Referenced by deleteEntryA(), deleteEntryS(), editEntryA(), editEntryS(), exportData(), importData(), insertEntryA(), and insertEntryS().
virtual void SBStuffSources::closeEvent (QCloseEvent *e) [inline, protected, virtual]
Definition at line 147 of file SbIStuffSource.H'.
References numOpenedWindows.
void SBStuffSources::CRFModified (boolModified) [private, slot]
Definition at line 717 of file SbIStuffSource.C'.
References SBCatalog::aliasDict(), isModifiedCRF, numOpenedWindows, NumSA, str, and Wcrf.
Referenced by editEntryA(), editEntryS(), insertEntryA(), and insertEntryS().
void SBStuffSources::deleteEntryA () [private, slot]
Definition at line 629 of file SbIStuffSource.C'.
References SBAliasListItem::Alias, SBCatalog::aliasDict(), AliasesLV, ClassName(), SBLog::DBG, SBLog::ERR, SBLog::INTERFACE, isModifiedCRF, Log, numOpenedWindows, NumSA, SBAliasListItem::Reference, str, Wcrf, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::deleteEntryS () [private, slot]
Definition at line 683 of file SbIStuffSource.C'.
References SBCatalog::aliasDict(), ClassName(), SBLog::DBG, SBLog::ERR, SBLog::INTERFACE, isModifiedCRF, Log, SBNamed::name(), numOpenedWindows, NumSA, SBCatalog::remove(), SBSourceListItem::Source, SourcesLV, str, Wcrf, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::drawInfo () [private]
Definition at line 524 of file SbIStuffSource.C'.
References SBCatalog::aliasDict(), SBCatalog::comment(), CRFComment, CRFEpoch, CRFLabel, SBCatalog::epoch(), SBMJD::F_Year, SBCatalog::label(), NumSA, str, SBMJD::toString(), SBSolutionName::toString(), and Wcrf.
Referenced by reloadCRF().
void SBStuffSources::editEntryA (QListViewItem *AkaItem) [private, slot]
Definition at line 609 of file SbIStuffSource.C'.
References ClassName(), CRFModified(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, Wcrf, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::editEntryS (QListViewItem *SrcItem) [private, slot]
Definition at line 663 of file SbIStuffSource.C'.
References ClassName(), CRFModified(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::exportData () [private, slot]
Definition at line 555 of file SbIStuffSource.C'.
References ClassName(), SBLog::DBG, SBLog::ERR, SBLog::INTERFACE, SBLog::IO, Log, SBSetUp::path2Output(), SetUp, SBSetUp::sources(), Wcrf, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::importData () [private, slot]
Definition at line 535 of file SbIStuffSource.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, isModifiedCRF, Log, numOpenedWindows, reloadCRF(), SBSetUp::saveCRF(), SetUp, Wcrf, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::insertEntryA () [private, slot]
Definition at line 619 of file SbIStuffSource.C'.
References AliasesLV, ClassName(), CRFModified(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, Wcrf, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::insertEntryS () [private, slot]
Definition at line 673 of file SbIStuffSource.C'.
References ClassName(), CRFModified(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, SourcesLV, Wcrf, and SBLog::write().
Referenced by SBStuffSources().
void SBStuffSources::reject () [private, slot]
Definition at line 487 of file SbIStuffSource.C'.
References numOpenedWindows.
Referenced by SBStuffSources().
void SBStuffSources::reloadCRF () [private, slot]
Definition at line 495 of file SbIStuffSource.C'.
References SBCatalog::aliasDict(), AliasesLV, drawInfo(), SB_CRF::first(), SBSetUp::loadCRF(), SB_CRF::next(), SB_CRF::prepareAliases4Output(), SetUp, SourcesLV, and Wcrf.
Referenced by importData().
Member Data Documentation
QListView* SBStuffSources::AliasesLV [private]
Definition at line 136 of file SbIStuffSource.H'.
Referenced by deleteEntryA(), insertEntryA(), reloadCRF(), and SBStuffSources().
QLineEdit* SBStuffSources::CRFComment [private]
Definition at line 139 of file SbIStuffSource.H'.
Referenced by accept(), drawInfo(), and SBStuffSources().
QLineEdit* SBStuffSources::CRFEpoch [private]
Definition at line 137 of file SbIStuffSource.H'.
Referenced by accept(), drawInfo(), and SBStuffSources().
QLineEdit* SBStuffSources::CRFLabel [private]
Definition at line 138 of file SbIStuffSource.H'.
Referenced by accept(), drawInfo(), and SBStuffSources().
bool SBStuffSources::isModifiedCRF [private]
Definition at line 141 of file SbIStuffSource.H'.
Referenced by accept(), CRFModified(), deleteEntryA(), deleteEntryS(), importData(), and SBStuffSources().
int SBStuffSources::numOpenedWindows [private]
Definition at line 142 of file SbIStuffSource.H'.
Referenced by accept(), closeEvent(), CRFModified(), deleteEntryA(), deleteEntryS(), editEntryA(), editEntryS(), importData(), insertEntryA(), insertEntryS(), reject(), and SBStuffSources().
QLabel* SBStuffSources::NumSA [private]
Definition at line 140 of file SbIStuffSource.H'.
Referenced by CRFModified(), deleteEntryA(), deleteEntryS(), drawInfo(), and SBStuffSources().
QListView* SBStuffSources::SourcesLV [private]
Definition at line 135 of file SbIStuffSource.H'.
Referenced by deleteEntryS(), insertEntryS(), reloadCRF(), and SBStuffSources().
QString SBStuffSources::str [private]
Definition at line 132 of file SbIStuffSource.H'.
Referenced by accept(), CRFModified(), deleteEntryA(), deleteEntryS(), drawInfo(), and SBStuffSources().
SB_CRF* SBStuffSources::Wcrf [private]
Definition at line 131 of file SbIStuffSource.H'.
Referenced by accept(), CRFModified(), deleteEntryA(), deleteEntryS(), drawInfo(), editEntryA(), exportData(), importData(), insertEntryA(), insertEntryS(), reloadCRF(), SBStuffSources(), and ~SBStuffSources().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.