.TH "SBSTideUT1" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBSTideUT1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefFrame\&.H>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTableEntry\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBSTideUT1\fP ()"
.br
.ti -1c
.RI "virtual \fB~SBSTideUT1\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual void \fBcalc\fP (const \fBSBTime\fP &)"
.br
.ti -1c
.RI "virtual double \fBdUT1_UT1S\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBDUT1S\fP"
.br
.RI "\fIcalculated value of (UT1S-UTC) \fP"
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const \fBTableEntry\fP \fBTab\fP [62]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Solid tide variations in UT1'\&. Calculates solid tide variatons in UT1, Dickman, 1993'\&. 
.PP
Definition at line 118 of file SbGeoRefFrame\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBSTideUT1::SBSTideUT1 ()\fC [inline]\fP"A constructor'\&. Creates a copy of object'\&. 
.PP
Definition at line 132 of file SbGeoRefFrame\&.H'\&.
.PP
References DUT1S\&.
.SS "virtual SBSTideUT1::~SBSTideUT1 ()\fC [inline, virtual]\fP"A destructor'\&. 
.PP
Definition at line 134 of file SbGeoRefFrame\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBSTideUT1::calc (const \fBSBTime\fP &T)\fC [virtual]\fP"Calculates dUT1S for the time T'\&. 
.PP
Definition at line 1094 of file SbGeoRefFrame\&.C'\&.
.PP
References SBSTideUT1::TableEntry::B, SBSTideUT1::TableEntry::C, DUT1S, SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), SBSTideUT1::TableEntry::N, sincos(), and Tab\&.
.SS "virtual QString SBSTideUT1::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info) 
.PP
Definition at line 136 of file SbGeoRefFrame\&.H'\&.
.SS "virtual double SBSTideUT1::dUT1_UT1S ()\fC [inline, virtual]\fP"Returns calculated DUT1S'\&. 
.PP
Definition at line 140 of file SbGeoRefFrame\&.H'\&.
.PP
References DUT1S\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBSBSTideUT1::DUT1S\fP\fC [protected]\fP"
.PP
calculated value of (UT1S-UTC) 
.PP
Definition at line 126 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by calc(), dUT1_UT1S(), and SBSTideUT1()\&.
.SS "const \fBSBSTideUT1::TableEntry\fP \fBSBSTideUT1::Tab\fP\fC [static, protected]\fP"
.PP
Definition at line 127 of file SbGeoRefFrame\&.H'\&.
.PP
Referenced by calc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
