SBStatistics
NAME
SBStatistics -
SYNOPSIS
#include <SbGeoParameter.H>
Inherits SBNamed'.
Public Member Functions
SBStatistics (const QString &='Unknown')
~SBStatistics ()
QString ClassName () const
double wpfr () const
double wrms () const
unsigned int numObs () const
unsigned int numPars () const
unsigned int numConstr () const
const SBMJD & tStart () const
void setWPFR (double d)
void setWRMS (double d)
void addWPFR (double d)
void addWRMS (double O_C, double W)
void setNumObs (unsigned int n)
void setNumPars (unsigned int n)
void setNumConstr (unsigned int n)
void addNumObs (unsigned int n)
void addNumPars (unsigned int n)
void addNumConstr (unsigned int n)
void setTStart (const SBMJD &T_)
void clearStatistics ()
unsigned int numberOfObservations () const
unsigned int dof () const
double varFactor () const
double WRMS_unit () const
double VarFactor_unit () const
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
QString Name
Private Attributes
double WPFR
weighted post fit residuals (= V^(T)PV )
double WRMS
weighted root means squares (= sum(O_C^2))
double SumW
sum of weights
double SumW2
sum of squares of weights
unsigned int NumObs
number of observations
unsigned int NumPars
number of parameters
unsigned int NumConstr
number of constraints
SBMJD TStart
epoch of first observation
Friends
QDataStream & operator<< (QDataStream &, const SBStatistics &)
QDataStream & operator>> (QDataStream &, SBStatistics &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
Class SBStatistics, describes statistics info about a solution'.
Definition at line 708 of file SbGeoParameter.H'.
Constructor & Destructor Documentation
SBStatistics::SBStatistics (const QString &Name_ = 'Unknown')
Definition at line 1021 of file SbGeoParameter.C'.
References NumConstr, NumObs, NumPars, SumW, SumW2, TStart, TZero, WPFR, and WRMS.
SBStatistics::~SBStatistics () [inline]
Definition at line 725 of file SbGeoParameter.H'.
Member Function Documentation
void SBStatistics::addNumConstr (unsigned intn) [inline]"Increments the number of constraints
Definition at line 762 of file SbGeoParameter.H'.
Referenced by SBEstimator::processConstr(), and SBEstimator::processGlobalConstr().
void SBStatistics::addNumObs (unsigned intn) [inline]"Increments the number of observations
Definition at line 758 of file SbGeoParameter.H'.
Referenced by SBEstimator::dataUpdate(), and SBEstimator::dataUpdateGlobalConstr().
void SBStatistics::addNumPars (unsigned intn) [inline]"Increments the number of parameters
Definition at line 760 of file SbGeoParameter.H'.
Referenced by SBRunManager::prepare4Run_m1(), and SBRunManager::process_m1().
void SBStatistics::addWPFR (doubled) [inline]"Increments weighted post fit residuals
Definition at line 747 of file SbGeoParameter.H'.
References SBDerivation::d().
Referenced by SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), SBEstimator::moveGlobalInfo(), and SBEstimator::moveGlobalInfo_Old().
void SBStatistics::addWRMS (doubleO_C, doubleW) [inline]"Increments weighted root means squares
Definition at line 749 of file SbGeoParameter.H'.
Referenced by SBEstimator::processObs().
QString SBStatistics::ClassName () const [inline, virtual]
Reimplemented from SBNamed'.
Definition at line 726 of file SbGeoParameter.H'.
void SBStatistics::clearStatistics ()
Definition at line 1034 of file SbGeoParameter.C'.
References NumConstr, NumObs, NumPars, SumW, SumW2, TStart, TZero, WPFR, and WRMS.
Referenced by SBSolution::deleteSolution(), SBSolution::prepare4Batch(), and SBRunManager::prepare4Run_m1().
unsigned int SBStatistics::dof () const [inline]
Definition at line 772 of file SbGeoParameter.H'.
Referenced by sinex_SolutionStatisticsBlock().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
unsigned int SBStatistics::numberOfObservations () const [inline]"Returns `degree of freedom'
Definition at line 770 of file SbGeoParameter.H'.
Referenced by sinex_SolutionStatisticsBlock().
unsigned int SBStatistics::numConstr () const [inline]"Returns the number of constraints
Definition at line 739 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::wGeneralInfo().
unsigned int SBStatistics::numObs () const [inline]"Returns the number of observations
Definition at line 735 of file SbGeoParameter.H'.
Referenced by SBSolutionBatchLI::key(), SBRunManager::process_m1(), SBSolutionBatchLI::text(), and SBSolutionBrowser::wGeneralInfo().
unsigned int SBStatistics::numPars () const [inline]"Returns the number of parameters
Definition at line 737 of file SbGeoParameter.H'.
Referenced by SBSolutionBatchLI::key(), SBRunManager::process_m1(), sinex_SolutionStatisticsBlock(), SBSolutionBatchLI::text(), and SBSolutionBrowser::wGeneralInfo().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBStatistics::setNumConstr (unsigned intn) [inline]"Sets up the number of constraints
Definition at line 756 of file SbGeoParameter.H'.
void SBStatistics::setNumObs (unsigned intn) [inline]"Sets up the number of observations
Definition at line 752 of file SbGeoParameter.H'.
void SBStatistics::setNumPars (unsigned intn) [inline]"Sets up the number of parameters
Definition at line 754 of file SbGeoParameter.H'.
void SBStatistics::setTStart (const SBMJD &T_) [inline]
Definition at line 764 of file SbGeoParameter.H'.
References SBDerivation::TStart.
Referenced by SBEstimator::solveLocals().
void SBStatistics::setWPFR (doubled) [inline]"Sets up post fit residuals
Definition at line 743 of file SbGeoParameter.H'.
References SBDerivation::d().
void SBStatistics::setWRMS (doubled) [inline]"Sets up weighted root means squares
Definition at line 745 of file SbGeoParameter.H'.
References SBDerivation::d().
const SBMJD& SBStatistics::tStart () const [inline]"Returns the epoch of first observation
Definition at line 741 of file SbGeoParameter.H'.
References SBDerivation::TStart.
Referenced by SBSolutionBatchLI::key().
double SBStatistics::varFactor () const [inline]
Definition at line 773 of file SbGeoParameter.H'.
Referenced by sinex_SolutionStatisticsBlock().
double SBStatistics::VarFactor_unit () const [inline]"Returns WPFR per observations (per unit of weight)
Definition at line 780 of file SbGeoParameter.H'.
Referenced by SBSolutionBatchLI::key(), SBRunManager::process_m1(), SBSolutionBatchLI::text(), and SBSolutionBrowser::wGeneralInfo().
double SBStatistics::wpfr () const [inline]"Returns weighted post fit residuals
Definition at line 731 of file SbGeoParameter.H'.
Referenced by sinex_SolutionStatisticsBlock().
double SBStatistics::wrms () const [inline]"Returns weighted root means squares
Definition at line 733 of file SbGeoParameter.H'.
Referenced by sinex_SolutionStatisticsBlock().
double SBStatistics::WRMS_unit () const [inline]"Returns WRMS per observations (per unit of weight); dimension the same as obs
Definition at line 778 of file SbGeoParameter.H'.
Referenced by SBSolutionBatchLI::key(), SBRunManager::process_m1(), SBSolutionBatchLI::text(), and SBSolutionBrowser::wGeneralInfo().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &, const SBStatistics &) [friend]
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &, SBStatistics &) [friend]
Member Data Documentation
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
unsigned int SBStatistics::NumConstr [private]
number of constraints
Definition at line 718 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
unsigned int SBStatistics::NumObs [private]
number of observations
Definition at line 716 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
unsigned int SBStatistics::NumPars [private]
number of parameters
Definition at line 717 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
double SBStatistics::SumW [private]
sum of weights
Definition at line 714 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
double SBStatistics::SumW2 [private]
sum of squares of weights
Definition at line 715 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
SBMJD SBStatistics::TStart [private]
epoch of first observation
Definition at line 719 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
double SBStatistics::WPFR [private]
weighted post fit residuals (= V^(T)PV )
Definition at line 712 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
double SBStatistics::WRMS [private]
weighted root means squares (= sum(O_C^2))
Definition at line 713 of file SbGeoParameter.H'.
Referenced by clearStatistics(), and SBStatistics().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.