SBStationListItem
NAME
SBStationListItem -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QListViewItem'.
Public Member Functions
SBStationListItem (QListView *, SBStation *)
~SBStationListItem ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBStation * Station
bool isFaked
Friends
class SBSiteEditor
class SBStationEditor
Detailed Description
Definition at line 59 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBStationListItem::SBStationListItem (QListView *parent, SBStation *Station_)
Definition at line 62 of file SbIStuffStation.C'.
References isFaked, and Station.
SBStationListItem::~SBStationListItem ()
Definition at line 74 of file SbIStuffStation.C'.
References isFaked, and Station.
Member Function Documentation
virtual QString SBStationListItem::ClassName () const [inline, virtual]
Definition at line 67 of file SbIStuffStation.H'.
QString SBStationListItem::key (intcol, bool) const [virtual]
Definition at line 117 of file SbIStuffStation.C'.
References SBStation::CDP(), SBStation::charID(), SBStation::domeMinor(), SBStation::hasOwnOLoad, SBAttributed::isAttr(), SBStation::mountType(), SBNamed::name(), SBStation::pointType(), SBStation::Pt_Antenna, SBSite::r(), SBStation::r_first(), SBStation::refPt(), SBStation::site(), Station, SBStation::tech(), TmpString, SBStation::v(), SBSite::v(), and v3Zero.
QString SBStationListItem::text (intcol) const [virtual]
Definition at line 80 of file SbIStuffStation.C'.
References SBStation::CDP(), SBStation::charID(), SBStation::domeMinor(), SBStation::hasOwnOLoad, SBAttributed::isAttr(), SBStation::mountType(), SBNamed::name(), SBStation::pointType(), SBStation::Pt_Antenna, SBSite::r(), SBStation::r_first(), SBStation::refPt(), SBStation::site(), Station, SBStation::tech(), SBSolutionName::techAbbrev(), TmpString, SBStation::v(), SBSite::v(), and v3Zero.
Friends And Related Function Documentation
friend class SBSiteEditor [friend]
Definition at line 72 of file SbIStuffStation.H'.
friend class SBStationEditor [friend]
Definition at line 73 of file SbIStuffStation.H'.
Member Data Documentation
bool SBStationListItem::isFaked [private]
Definition at line 63 of file SbIStuffStation.H'.
Referenced by SBStationListItem(), and ~SBStationListItem().
SBStation* SBStationListItem::Station [private]
Definition at line 62 of file SbIStuffStation.H'.
Referenced by SBSiteEditor::deleteEntry(), key(), SBStationEditor::SBStationEditor(), SBStationListItem(), text(), and ~SBStationListItem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.