SBStationInfo
NAME
SBStationInfo -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBStationID, and SBObjectObsInfo'.
Public Types
enum Attributes { notValid = 1<<0, refClock = 1<<1, BadCable = 1<<2, BadMeteo = 1<<3, EstCoo = 1<<4, EstVel = 1<<5, ConstrCoo = 1<<6, ConstrVel = 1<<7, ArtMeteo = 1<<8, HasClockBreak = 1<<9, UseLocalClocks = 1<<10, UseLocalZenith = 1<<11, InvCable = 1<<12 }
Public Member Functions
SBStationInfo (const SBStationID &ID_, int Idx_=0, const QString &Aka_='unkn')
virtual QString ClassName () const
double cl_V (int i) const
double cl_E (int i) const
int cl_Order () const
double zw () const
double errZw () const
SBClockBreaksList & clockBreaks ()
SBParameterCfg & clocks ()
SBParameterCfg & zenith ()
void setCl_V (int i, double C_)
void setCl_E (int i, double E_)
void setCl_Order (int i)
void clearClocks ()
void setZw (double Z_)
void setErrZw (double E_)
void dumpUserInfo (QTextStream &)
bool restoreUserInfo (QTextStream &)
double clocksValue (double)
int domeMajor () const
int domeMinor () const
SBStation::SPointType ptType () const
void setDomeMajor (int Dome_)
void setDomeMinor (int Dome_)
void setPtType (SBStation::SPointType PtType_)
bool isValidId () const
void setID (const QString &)
void setID (const SBStationID &ID)
const QString toString () const
short int idx () const
unsigned int num () const
unsigned int procNum () const
const QString & aka () const
double wrms () const
void setIdx (int Idx_)
void setNum (unsigned int Num_)
void setProcNum (unsigned int ProcNum_)
void setAka (const QString &Aka_)
void incNum ()
void addWRMS (double o_c_, double w_)
void clearRMSs ()
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Static Public Member Functions
static bool isValidStr (const QString &)
Private Attributes
double Cl_V [10]
clock model
double Cl_E [10]
std'.vars of clock model
int Cl_Order
actual number of used Cl_*s
double Zw
wet zenith delay
double ErrZw
std var'. of wet zenith delay
SBClockBreaksList ClockBreaks
a list of epochs and values of clock breaks
SBParameterCfg Clocks
a descriptor of stoch'.parameter for clocks variations
SBParameterCfg Zenith
a descriptor of stoch'.parameter for wet z'.delay variations
Friends
bool operator== (const SBStationID &S1, const SBStationID &S2)
bool operator!= (const SBStationID &S1, const SBStationID &S2)
bool operator< (const SBStationID &S1, const SBStationID &S2)
bool operator> (const SBStationID &S1, const SBStationID &S2)
QDataStream & operator<< (QDataStream &s, const SBStationID &ID)
QDataStream & operator>> (QDataStream &s, SBStationID &ID)
QDataStream & operator<< (QDataStream &, const SBObjectObsInfo &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &, SBObjectObsInfo &)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Related Functions
(Note that these are not member functions'.)
QDataStream & operator<< (QDataStream &, const SBStationInfo &)
QDataStream & operator>> (QDataStream &, SBStationInfo &)
Detailed Description
Provides station's info to the SBVLBISession'. Keeps station's information (SBStationID)'.
Definition at line 229 of file SbGeoObsVLBI.H'.
Member Enumeration Documentation
enum SBStationInfo::Attributes"Station's attributes'. Describes station's behaviour related to the session'.
Enumerator:
notValid
omit this station
refClock
station's clock is a reference
BadCable
station has wrong cable correction
BadMeteo
station has wrong meteo data
EstCoo
make an estimation of coordinates
EstVel
make an estimation of velocities
ConstrCoo
use station's coordinates to fix TRF
ConstrVel
use station's velocities to fix veloc'.field
ArtMeteo
use artificial meteo paramaters
HasClockBreak
there is a break in clocks
UseLocalClocks
use local model of clocks
UseLocalZenith
use local model of zenith
InvCable
reserved
Definition at line 235 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBStationInfo::SBStationInfo (const SBStationID &ID_, intIdx_ = 0, const QString &Aka_ = 'unkn')"A constructor'. Creates a copy of object'.
Parameters:
ID_ station ID (Domes Number);
Idx_ session index of the station (default is 0);
Aka_ session alias of the station (default is 'unkn')'.
Definition at line 47 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), Cl_E, Cl_Order, Cl_V, Clocks, DefaultConfig, ErrZw, EstCoo, SBConfig::p(), SBParametersDesc::par(), Zenith, and Zw.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
void SBObjectObsInfo::addWRMS (doubleo_c_, doublew_) [inline, inherited]"Increments number of observation by one, adds RMS^2 to sum of (RMS^2)'.
Definition at line 112 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::ProcNum, SBObjectObsInfo::SWeight, and SBObjectObsInfo::SWRMS2.
Referenced by SBObsVLBIEntry::process().
const QString& SBObjectObsInfo::aka () const [inline, inherited]"Returns alias'.
Definition at line 98 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::Aka.
Referenced by SBProject::addSession(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBProject::delSession(), dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBSolution::guessParameterName(), SBObsVLBIEntry::isEligible(), SBCableLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRFVariations(), operator<<(), SBObsVLBIEntry::process(), SBSourceInfo::restoreUserInfo(), SBStaParsEditor::SBStaParsEditor(), sinex_tro_TropSolutionStation(), SBCableLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), and SBVLBISessionEditor::wObservs().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
double SBStationInfo::cl_E (inti) const [inline]
Definition at line 276 of file SbGeoObsVLBI.H'.
References Cl_E.
Referenced by SBStaInfoLI::key(), and SBStaInfoLI::text().
int SBStationInfo::cl_Order () const [inline]
Definition at line 277 of file SbGeoObsVLBI.H'.
References Cl_Order.
Referenced by SBStaParsEditor::acquireData(), SBRunManager::fillParameterList(), SBStaInfoLI::key(), SBObsVLBIEntry::process(), SBStaParsEditor::SBStaParsEditor(), and SBStaInfoLI::text().
double SBStationInfo::cl_V (inti) const [inline]
Definition at line 275 of file SbGeoObsVLBI.H'.
References Cl_V.
Referenced by SBStaInfoLI::key(), SBVLBIPreProcess::preProcess(), and SBStaInfoLI::text().
virtual QString SBStationInfo::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBObjectObsInfo'.
Definition at line 271 of file SbGeoObsVLBI.H'.
Referenced by restoreUserInfo().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
void SBStationInfo::clearClocks ()
Definition at line 238 of file SbGeoObsVLBI.C'.
References Cl_E, and Cl_V.
void SBObjectObsInfo::clearRMSs () [inline, inherited]
Definition at line 113 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::ProcNum, SBObjectObsInfo::SWeight, and SBObjectObsInfo::SWRMS2.
SBClockBreaksList& SBStationInfo::clockBreaks () [inline]
Definition at line 280 of file SbGeoObsVLBI.H'.
References ClockBreaks.
Referenced by SBStaParsEditor::deleteEntry(), SBStaParsEditor::insertEntry(), SBStaInfoLI::key(), SBObsVLBIEntry::process(), SBStaParsEditor::SBStaParsEditor(), and SBStaInfoLI::text().
SBParameterCfg& SBStationInfo::clocks () [inline]
Definition at line 281 of file SbGeoObsVLBI.H'.
References Clocks.
Referenced by SBStaParsEditor::editClocksPar(), and SBRunManager::fillParameterList().
double SBStationInfo::clocksValue (doubledt)
Definition at line 247 of file SbGeoObsVLBI.C'.
References Cl_Order, and Cl_V.
Referenced by SBObsVLBIEntry::process().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
int SBStationID::domeMajor () const [inline, inherited]
Definition at line 759 of file SbGeoStations.H'.
References SBStationID::DomeMajor.
Referenced by SBAploEphem::displacement(), SBAploChunk::entryByID(), SBAploEphem::importHPS(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), operator<<(), and operator>>().
int SBStationID::domeMinor () const [inline, inherited]
Definition at line 760 of file SbGeoStations.H'.
References SBStationID::DomeMinor.
Referenced by SBSite::firstUnusedNumber(), SBStationImport::loadNScodes(), and operator>>().
void SBStationInfo::dumpUserInfo (QTextStream &ts)
Definition at line 69 of file SbGeoObsVLBI.C'.
References SBObjectObsInfo::aka(), ArtMeteo, BadCable, BadMeteo, SBParameterCfg::breakNoise(), Cl_Order, ClockBreaks, Clocks, SBMJD::F_INTERNAL, HasClockBreak, InvCable, SBAttributed::isAttr(), notValid, refClock, SBStationID::toString(), UseLocalClocks, UseLocalZenith, SBParameterCfg::whiteNoise(), and Zenith.
double SBStationInfo::errZw () const [inline]
Definition at line 279 of file SbGeoObsVLBI.H'.
References ErrZw.
Referenced by SBStaInfoLI::key(), and SBStaInfoLI::text().
short int SBObjectObsInfo::idx () const [inline, inherited]"Returns local index'.
Definition at line 92 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::Idx.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBVLBISession::fillDicts(), SBCableLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBVLBISession::parseObsDumpString(), restoreUserInfo(), SBCableLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), and SBSouInfoLI::text().
void SBObjectObsInfo::incNum () [inline, inherited]"Increments number of observation by one'.
Definition at line 110 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::Num.
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
bool SBStationID::isValidId () const [inline, inherited]
Definition at line 786 of file SbGeoStations.H'.
References SBStationID::DomeMajor, SBStationID::DomeMinor, SBStation::Pt_Unkn, and SBStationID::PtType.
Referenced by SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBStationImport::loadOLoad(), and SBBaseInfoList::restoreUserInfo().
bool SBStationID::isValidStr (const QString &Str) [static, inherited]
Definition at line 1680 of file SbGeoStations.C'.
Referenced by SBSolution::dumpParameters(), SBSolution::guessParameterName(), SBStationImport::loadNScodes(), operator>>(), SBVLBISession::parseObsDumpString(), and SBStationID::setID().
unsigned int SBObjectObsInfo::num () const [inline, inherited]"Returns number of observations'.
Definition at line 94 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::Num.
Referenced by SBProject::addSession(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBProject::delSession(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBRunManager::makeReportCRFVariations4IVS(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBSolutionBrowser::wLocalSoPars(), and SBSolutionBrowser::wLocalStPars().
unsigned int SBObjectObsInfo::procNum () const [inline, inherited]"Returns number of processed observations'.
Definition at line 96 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::ProcNum.
Referenced by SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStaInfoLI::text(), SBBasInfoLI::text(), and SBSouInfoLI::text().
SBStation::SPointType SBStationID::ptType () const [inline, inherited]
Definition at line 761 of file SbGeoStations.H'.
References SBStationID::PtType.
Referenced by SBEcc::findEcc(), SBStationImport::loadNScodes(), operator>>(), and SBEcc::registerEcc().
bool SBStationInfo::restoreUserInfo (QTextStream &ts)
Definition at line 106 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), ArtMeteo, SBParameterBreak::b(), BadCable, BadMeteo, ClassName(), ClockBreaks, Clocks, SBLog::DATA, SBLog::DBG, SBAttributed::delAttr(), SBMJD::F_INTERNAL, HasClockBreak, SBObjectObsInfo::idx(), InvCable, Log, notValid, refClock, SBParameterBreak::setB(), SBParameterCfg::setBreakNoise(), setCl_Order(), SBMJD::setMJD(), SBParameterCfg::setWhiteNoise(), SBStationID::toString(), UseLocalClocks, UseLocalZenith, SBLog::write(), and Zenith.
Referenced by SBStationInfoList::restoreUserInfo().
void SBObjectObsInfo::setAka (const QString &Aka_) [inline, inherited]"Sets up alias'.
Definition at line 108 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::Aka.
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBStationInfo::setCl_E (inti, doubleE_) [inline]
Definition at line 285 of file SbGeoObsVLBI.H'.
References Cl_E.
Referenced by SBVLBIPreProcess::preProcess().
void SBStationInfo::setCl_Order (inti) [inline]
Definition at line 286 of file SbGeoObsVLBI.H'.
References Cl_Order.
Referenced by SBStaParsEditor::acquireData(), and restoreUserInfo().
void SBStationInfo::setCl_V (inti, doubleC_) [inline]
Definition at line 284 of file SbGeoObsVLBI.H'.
References Cl_V.
Referenced by SBVLBIPreProcess::preProcess().
void SBStationID::setDomeMajor (intDome_) [inline, inherited]
Definition at line 762 of file SbGeoStations.H'.
References SBStationID::DomeMajor.
Referenced by SBStation::id(), operator>>(), and SBOLoadCarrier::SBOLoadCarrier().
void SBStationID::setDomeMinor (intDome_) [inline, inherited]
Definition at line 763 of file SbGeoStations.H'.
References SBStationID::DomeMinor.
Referenced by SBStation::id(), and SBOLoadCarrier::SBOLoadCarrier().
void SBStationInfo::setErrZw (doubleE_) [inline]
Definition at line 289 of file SbGeoObsVLBI.H'.
References ErrZw.
Referenced by SBVLBIPreProcess::preProcess().
void SBStationID::setID (const QString &Str) [inherited]
Definition at line 1694 of file SbGeoStations.C'.
References SBStationID::DomeMajor, SBStationID::DomeMinor, SBStationID::isValidStr(), SBStation::Pt_Antenna, SBStation::Pt_Marker, SBStation::Pt_Unkn, and SBStationID::PtType.
Referenced by SBSolution::guessParameterName(), SBEcc::importEccDat(), SBStationImport::loadNScodes(), SB_TRF::lookupID(), SB_TRF::lookupStation(), SBRunManager::makeReportMaps(), operator>>(), SB_TRF::prepareEccs4Session(), SBBaseInfoList::restoreUserInfo(), and SBCablesBrowser::SBCablesBrowser().
void SBStationID::setID (const SBStationID &ID) [inline, inherited]
Reimplemented in SBStationEcc'.
Definition at line 790 of file SbGeoStations.H'.
References SBStationID::DomeMajor, SBStationID::DomeMinor, and SBStationID::PtType.
void SBObjectObsInfo::setIdx (intIdx_) [inline, inherited]"Sets up index'.
Definition at line 102 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::Idx.
void SBObjectObsInfo::setNum (unsigned intNum_) [inline, inherited]"Sets up number of observations per object'.
Definition at line 104 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::Num.
Referenced by SBProject::addSession(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBProject::delSession(), and SBSolutionBrowser::lookupParameters().
void SBObjectObsInfo::setProcNum (unsigned intProcNum_) [inline, inherited]"Sets up number of processed observations per object'.
Definition at line 106 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::ProcNum.
void SBStationID::setPtType (SBStation::SPointTypePtType_) [inline, inherited]
Definition at line 764 of file SbGeoStations.H'.
References SBStationID::PtType.
Referenced by SBStation::id(), and SBOLoadCarrier::SBOLoadCarrier().
void SBStationInfo::setZw (doubleZ_) [inline]
Definition at line 288 of file SbGeoObsVLBI.H'.
References Zw.
Referenced by SBVLBIPreProcess::preProcess().
const QString SBStationID::toString () const [inline, inherited]
Definition at line 792 of file SbGeoStations.H'.
References SBStationID::DomeMajor, SBStationID::DomeMinor, SBStation::Pt_Antenna, and SBStationID::PtType.
Referenced by SBSite::addStation(), SBSolutionBrowser::batch4StochStChanged(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffStationsEcc::deleteEntry(), SBPlateMotion::displacement(), SBAploEphem::displacement(), SBStuffAplo::draw(), dumpUserInfo(), SBAploChunk::entryByID(), SBAploChunk::fillDict(), SBVLBIPreProcess::fillObsListView(), SBEcc::findEcc(), SBSolution::guessParameterName(), SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBObsVLBIEntry::isEligible(), SBCableLI::key(), SBEccListItem::key(), SBStaInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolutionBrowser::lookupParameters(), SBStationEditor::makeApply(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBRefraction::operator()(), operator<<(), operator>>(), SBSite::prepareDicts(), SBObsVLBIEntry::process(), SBStationEcc::registerEcc(), SBEcc::registerEcc(), SBAploEphem::registerStation(), restoreUserInfo(), SBBaseInfoList::restoreUserInfo(), SBCoordsEditor::SBCoordsEditor(), sinex_tro_SiteIDBlock(), SBAploEphem::spline4station(), SBCableLI::text(), SBEccListItem::text(), SBStaInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBPlateMotion::velocity(), and SBStationEditor::wNames().
double SBObjectObsInfo::wrms () const [inline, inherited]
Definition at line 99 of file SbGeoObsVLBI.H'.
References SBObjectObsInfo::SWeight, and SBObjectObsInfo::SWRMS2.
Referenced by SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStaInfoLI::text(), SBBasInfoLI::text(), and SBSouInfoLI::text().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
SBParameterCfg& SBStationInfo::zenith () [inline]
Definition at line 282 of file SbGeoObsVLBI.H'.
References Zenith.
Referenced by SBStaParsEditor::editZenithPar(), and SBRunManager::fillParameterList().
double SBStationInfo::zw () const [inline]
Definition at line 278 of file SbGeoObsVLBI.H'.
References Zw.
Referenced by SBDelay::calc(), SBStaInfoLI::key(), operator<<(), SBVLBIPreProcess::preProcess(), and SBStaInfoLI::text().
Friends And Related Function Documentation
bool operator!= (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 772 of file SbGeoStations.H'.
bool operator< (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 773 of file SbGeoStations.H'.
QDataStream & operator<< (QDataStream &s, const SBObjectObsInfo &Oi) [friend, inherited]"Output to the data stream'.
Definition at line 122 of file SbGeoObsVLBI.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator<< (QDataStream &s, const SBStationInfo &St) [friend]"Saves to the data stream'.
Definition at line 267 of file SbGeoObsVLBI.C'.
QDataStream& operator<< (QDataStream &s, const SBStationID &ID) [friend, inherited]
Definition at line 800 of file SbGeoStations.H'.
bool operator== (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 767 of file SbGeoStations.H'.
bool operator> (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 779 of file SbGeoStations.H'.
QDataStream & operator>> (QDataStream &s, SBObjectObsInfo &Oi) [friend, inherited]"Input from the data stream'.
Definition at line 128 of file SbGeoObsVLBI.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBStationInfo &St) [friend]"Loads from the data stream'.
Definition at line 278 of file SbGeoObsVLBI.C'.
QDataStream& operator>> (QDataStream &s, SBStationID &ID) [friend, inherited]
Definition at line 802 of file SbGeoStations.H'.
Member Data Documentation
double SBStationInfo::Cl_E[10] [private]
std'.vars of clock model
Definition at line 254 of file SbGeoObsVLBI.H'.
Referenced by cl_E(), clearClocks(), operator<<(), operator>>(), SBStationInfo(), and setCl_E().
int SBStationInfo::Cl_Order [private]
actual number of used Cl_*s
Definition at line 255 of file SbGeoObsVLBI.H'.
Referenced by cl_Order(), clocksValue(), dumpUserInfo(), operator<<(), operator>>(), SBStationInfo(), and setCl_Order().
double SBStationInfo::Cl_V[10] [private]
clock model
Definition at line 253 of file SbGeoObsVLBI.H'.
Referenced by cl_V(), clearClocks(), clocksValue(), operator<<(), operator>>(), SBStationInfo(), and setCl_V().
SBClockBreaksList SBStationInfo::ClockBreaks [private]
a list of epochs and values of clock breaks
Definition at line 258 of file SbGeoObsVLBI.H'.
Referenced by clockBreaks(), dumpUserInfo(), operator<<(), operator>>(), and restoreUserInfo().
SBParameterCfg SBStationInfo::Clocks [private]
a descriptor of stoch'.parameter for clocks variations
Definition at line 259 of file SbGeoObsVLBI.H'.
Referenced by clocks(), dumpUserInfo(), operator<<(), operator>>(), restoreUserInfo(), and SBStationInfo().
double SBStationInfo::ErrZw [private]
std var'. of wet zenith delay
Definition at line 257 of file SbGeoObsVLBI.H'.
Referenced by errZw(), operator<<(), operator>>(), SBStationInfo(), and setErrZw().
SBParameterCfg SBStationInfo::Zenith [private]
a descriptor of stoch'.parameter for wet z'.delay variations
Definition at line 260 of file SbGeoObsVLBI.H'.
Referenced by dumpUserInfo(), operator<<(), operator>>(), restoreUserInfo(), SBStationInfo(), and zenith().
double SBStationInfo::Zw [private]
wet zenith delay
Definition at line 256 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator>>(), SBStationInfo(), setZw(), and zw().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.