SBStuffAplo
NAME
SBStuffAplo -
SYNOPSIS
#include <SbIStuff.H>
Inherits QDialog'.
Signals
void stBarReset ()
void stBarSetTotalSteps (int)
void stBarSetProgress (int)
void message (const QString &)
Public Member Functions
SBStuffAplo (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual QString ClassName () const
~SBStuffAplo ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
void blockInput ()
void restoreInput ()
Private Slots
void import ()
void importHPS ()
void updateEphem ()
void accept ()
void reject ()
void headerChanged (QListViewItem *)
void draw ()
Private Attributes
SBAploEphem * AploEphem
SBAploChunk * Chunk
bool isModified
bool isTRFModified
QListView * HeadersLV
QListView * EntriesLV
QLabel * LStatus
QLabel * LTStart
QLabel * LTFinis
QLabel * LNumChunks
QPushButton * Ok
QPushButton * Draw
QPushButton * Import
QPushButton * ImportHPS
QPushButton * Cancel
bool IsBlockedOkButton
bool IsBlockedDrawButton
bool IsBlockedImportButton
bool IsBlockedImportHPSButton
bool IsBlockedCancelButton
Detailed Description
Definition at line 232 of file SbIStuff.H'.
Constructor & Destructor Documentation
SBStuffAplo::SBStuffAplo (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 942 of file SbIStuff.C'.
References accept(), AploEphem, Cancel, Chunk, draw(), Draw, EntriesLV, SBMJD::F_Short, headerChanged(), HeadersLV, Import, importHPS(), ImportHPS, IsBlockedCancelButton, IsBlockedDrawButton, IsBlockedImportButton, IsBlockedImportHPSButton, IsBlockedOkButton, isModified, SBAploEphem::isOK(), isTRFModified, LNumChunks, SBSetUp::loadAploEphem(), SBAploEphem::loadChunk(), LStatus, LTFinis, LTStart, MainWin, message(), Ok, reject(), SetUp, stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), SBAploEphem::tFinis(), SBMJD::toString(), and SBAploEphem::tStart().
SBStuffAplo::~SBStuffAplo ()
Definition at line 1112 of file SbIStuff.C'.
References AploEphem.
Member Function Documentation
void SBStuffAplo::accept () [private, slot]
Definition at line 1126 of file SbIStuff.C'.
References AploEphem, isModified, SBSetUp::saveAploEphem(), and SetUp.
Referenced by SBStuffAplo().
void SBStuffAplo::blockInput () [protected]
Definition at line 1266 of file SbIStuff.C'.
References Cancel, Draw, Import, ImportHPS, IsBlockedCancelButton, IsBlockedDrawButton, IsBlockedImportButton, IsBlockedImportHPSButton, IsBlockedOkButton, and Ok.
Referenced by import(), and importHPS().
virtual QString SBStuffAplo::ClassName () const [inline, virtual]
Definition at line 237 of file SbIStuff.H'.
virtual void SBStuffAplo::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 257 of file SbIStuff.H'.
void SBStuffAplo::draw () [private, slot]
Definition at line 1235 of file SbIStuff.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), Chunk, SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), EAST, EntriesLV, SBAploEntry::id(), SBNamed::name(), NORT, SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setType(), SBStationID::toString(), and VERT.
Referenced by SBStuffAplo().
void SBStuffAplo::headerChanged (QListViewItem *Item) [private, slot]
Definition at line 1140 of file SbIStuff.C'.
References AploEphem, Chunk, EntriesLV, and SBAploEphem::loadChunk().
Referenced by SBStuffAplo().
void SBStuffAplo::import () [private, slot]
Definition at line 1186 of file SbIStuff.C'.
References AploEphem, blockInput(), SBAploEphem::importEphem(), isModified, SBSetUp::loadTRF(), SBSetUp::path2ImpAplo(), restoreInput(), SBSetUp::saveTRF(), SetUp, and updateEphem().
void SBStuffAplo::importHPS () [private, slot]
Definition at line 1212 of file SbIStuff.C'.
References AploEphem, blockInput(), SBAploEphem::importHPS(), isModified, SBSetUp::loadTRF(), SBSetUp::path2ImpAplo(), restoreInput(), SBSetUp::saveTRF(), SetUp, and updateEphem().
Referenced by SBStuffAplo().
void SBStuffAplo::message (const QString &t0) [signal]
Definition at line 412 of file SbIStuff.moc.C'.
Referenced by SBStuffAplo().
void SBStuffAplo::reject () [private, slot]
Definition at line 1134 of file SbIStuff.C'.
Referenced by SBStuffAplo().
void SBStuffAplo::restoreInput () [protected]
Definition at line 1297 of file SbIStuff.C'.
References Cancel, Draw, Import, ImportHPS, IsBlockedCancelButton, IsBlockedDrawButton, IsBlockedImportButton, IsBlockedImportHPSButton, IsBlockedOkButton, and Ok.
Referenced by import(), and importHPS().
void SBStuffAplo::stBarReset () [signal]
Definition at line 394 of file SbIStuff.moc.C'.
Referenced by SBStuffAplo().
void SBStuffAplo::stBarSetProgress (intt0) [signal]
Definition at line 406 of file SbIStuff.moc.C'.
Referenced by SBStuffAplo().
void SBStuffAplo::stBarSetTotalSteps (intt0) [signal]
Definition at line 400 of file SbIStuff.moc.C'.
Referenced by SBStuffAplo().
void SBStuffAplo::updateEphem () [private, slot]
Definition at line 1165 of file SbIStuff.C'.
References AploEphem, EntriesLV, SBMJD::F_Short, HeadersLV, SBAploEphem::isOK(), LNumChunks, LStatus, LTFinis, LTStart, SBAploEphem::tFinis(), SBMJD::toString(), and SBAploEphem::tStart().
Referenced by import(), and importHPS().
Member Data Documentation
SBAploEphem* SBStuffAplo::AploEphem [private]
Definition at line 263 of file SbIStuff.H'.
Referenced by accept(), headerChanged(), import(), importHPS(), SBStuffAplo(), updateEphem(), and ~SBStuffAplo().
QPushButton* SBStuffAplo::Cancel [private]
Definition at line 281 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
SBAploChunk* SBStuffAplo::Chunk [private]
Definition at line 264 of file SbIStuff.H'.
Referenced by draw(), headerChanged(), and SBStuffAplo().
QPushButton* SBStuffAplo::Draw [private]
Definition at line 278 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
QListView* SBStuffAplo::EntriesLV [private]
Definition at line 270 of file SbIStuff.H'.
Referenced by draw(), headerChanged(), SBStuffAplo(), and updateEphem().
QListView* SBStuffAplo::HeadersLV [private]
Definition at line 269 of file SbIStuff.H'.
Referenced by SBStuffAplo(), and updateEphem().
QPushButton* SBStuffAplo::Import [private]
Definition at line 279 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
QPushButton* SBStuffAplo::ImportHPS [private]
Definition at line 280 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
bool SBStuffAplo::IsBlockedCancelButton [private]
Definition at line 287 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
bool SBStuffAplo::IsBlockedDrawButton [private]
Definition at line 284 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
bool SBStuffAplo::IsBlockedImportButton [private]
Definition at line 285 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
bool SBStuffAplo::IsBlockedImportHPSButton [private]
Definition at line 286 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
bool SBStuffAplo::IsBlockedOkButton [private]
Definition at line 283 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
bool SBStuffAplo::isModified [private]
Definition at line 265 of file SbIStuff.H'.
Referenced by accept(), import(), importHPS(), and SBStuffAplo().
bool SBStuffAplo::isTRFModified [private]
Definition at line 266 of file SbIStuff.H'.
Referenced by SBStuffAplo().
QLabel* SBStuffAplo::LNumChunks [private]
Definition at line 275 of file SbIStuff.H'.
Referenced by SBStuffAplo(), and updateEphem().
QLabel* SBStuffAplo::LStatus [private]
Definition at line 272 of file SbIStuff.H'.
Referenced by SBStuffAplo(), and updateEphem().
QLabel* SBStuffAplo::LTFinis [private]
Definition at line 274 of file SbIStuff.H'.
Referenced by SBStuffAplo(), and updateEphem().
QLabel* SBStuffAplo::LTStart [private]
Definition at line 273 of file SbIStuff.H'.
Referenced by SBStuffAplo(), and updateEphem().
QPushButton* SBStuffAplo::Ok [private]
Definition at line 277 of file SbIStuff.H'.
Referenced by blockInput(), restoreInput(), and SBStuffAplo().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.