SBStationEcc
NAME
SBStationEcc -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBStationID'.
Public Member Functions
SBStationEcc ()
SBStationEcc (const SBStationEcc &Ecc_)
virtual ~SBStationEcc ()
QString ClassName () const
void setID (const SBStationID &ID_)
SBEccentriList & eccs ()
SBEccentricity * findEcc (const SBMJD &)
bool registerEcc (const SBEccentricity &)
int domeMajor () const
int domeMinor () const
SBStation::SPointType ptType () const
void setDomeMajor (int Dome_)
void setDomeMinor (int Dome_)
void setPtType (SBStation::SPointType PtType_)
bool isValidId () const
void setID (const QString &)
const QString toString () const
Static Public Member Functions
static bool isValidStr (const QString &)
Private Attributes
SBEccentriList Eccs
Friends
QDataStream & operator<< (QDataStream &s, const SBStationEcc &StEcc)
QDataStream & operator>> (QDataStream &s, SBStationEcc &StEcc)
bool operator== (const SBStationID &S1, const SBStationID &S2)
bool operator!= (const SBStationID &S1, const SBStationID &S2)
bool operator< (const SBStationID &S1, const SBStationID &S2)
bool operator> (const SBStationID &S1, const SBStationID &S2)
QDataStream & operator<< (QDataStream &s, const SBStationID &ID)
QDataStream & operator>> (QDataStream &s, SBStationID &ID)
Detailed Description
Definition at line 1071 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBStationEcc::SBStationEcc () [inline]
Definition at line 1079 of file SbGeoStations.H'.
References Eccs.
SBStationEcc::SBStationEcc (const SBStationEcc &Ecc_) [inline]
Definition at line 1080 of file SbGeoStations.H'.
References Eccs.
virtual SBStationEcc::~SBStationEcc () [inline, virtual]
Definition at line 1081 of file SbGeoStations.H'.
Member Function Documentation
QString SBStationEcc::ClassName () const [inline]
Reimplemented from SBStationID'.
Definition at line 1082 of file SbGeoStations.H'.
Referenced by registerEcc().
int SBStationID::domeMajor () const [inline, inherited]
Definition at line 759 of file SbGeoStations.H'.
References SBStationID::DomeMajor.
Referenced by SBAploEphem::displacement(), SBAploChunk::entryByID(), SBAploEphem::importHPS(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), operator<<(), and operator>>().
int SBStationID::domeMinor () const [inline, inherited]
Definition at line 760 of file SbGeoStations.H'.
References SBStationID::DomeMinor.
Referenced by SBSite::firstUnusedNumber(), SBStationImport::loadNScodes(), and operator>>().
SBEccentriList& SBStationEcc::eccs () [inline]
Definition at line 1087 of file SbGeoStations.H'.
References Eccs.
Referenced by SBStuffStationsEcc::deleteEntry(), and sinex_SiteEccentricityBlock().
SBEccentricity * SBStationEcc::findEcc (const SBMJD &T)
Definition at line 2375 of file SbGeoStations.C'.
References Eccs.
Referenced by SBEcc::findEcc(), and registerEcc().
bool SBStationID::isValidId () const [inline, inherited]
Definition at line 786 of file SbGeoStations.H'.
References SBStationID::DomeMajor, SBStationID::DomeMinor, SBStation::Pt_Unkn, and SBStationID::PtType.
Referenced by SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBStationImport::loadOLoad(), and SBBaseInfoList::restoreUserInfo().
bool SBStationID::isValidStr (const QString &Str) [static, inherited]
Definition at line 1680 of file SbGeoStations.C'.
Referenced by SBSolution::dumpParameters(), SBSolution::guessParameterName(), SBStationImport::loadNScodes(), operator>>(), SBVLBISession::parseObsDumpString(), and SBStationID::setID().
SBStation::SPointType SBStationID::ptType () const [inline, inherited]
Definition at line 761 of file SbGeoStations.H'.
References SBStationID::PtType.
Referenced by SBEcc::findEcc(), SBStationImport::loadNScodes(), operator>>(), and SBEcc::registerEcc().
bool SBStationEcc::registerEcc (const SBEccentricity &Ecc_)
Definition at line 2386 of file SbGeoStations.C'.
References SBEccentricity::aka(), Vector3::at(), ClassName(), SBLog::DATA, SBLog::DBG, SBEccentricity::ecc(), Eccs, SBEccentricity::ET_NEU, SBMJD::F_Short, findEcc(), Log, SBEccentricity::setTFinis(), SBEccentricity::setTStart(), SBLog::STATION, SBEccentricity::tFinis(), SBMJD::toString(), SBStationID::toString(), SBEccentricity::tStart(), SBEccentricity::type(), SBLog::write(), SBLog::WRN, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBEcc::registerEcc().
void SBStationID::setDomeMajor (intDome_) [inline, inherited]
Definition at line 762 of file SbGeoStations.H'.
References SBStationID::DomeMajor.
Referenced by SBStation::id(), operator>>(), and SBOLoadCarrier::SBOLoadCarrier().
void SBStationID::setDomeMinor (intDome_) [inline, inherited]
Definition at line 763 of file SbGeoStations.H'.
References SBStationID::DomeMinor.
Referenced by SBStation::id(), and SBOLoadCarrier::SBOLoadCarrier().
void SBStationID::setID (const QString &Str) [inherited]
Definition at line 1694 of file SbGeoStations.C'.
References SBStationID::DomeMajor, SBStationID::DomeMinor, SBStationID::isValidStr(), SBStation::Pt_Antenna, SBStation::Pt_Marker, SBStation::Pt_Unkn, and SBStationID::PtType.
Referenced by SBSolution::guessParameterName(), SBEcc::importEccDat(), SBStationImport::loadNScodes(), SB_TRF::lookupID(), SB_TRF::lookupStation(), SBRunManager::makeReportMaps(), operator>>(), SB_TRF::prepareEccs4Session(), SBBaseInfoList::restoreUserInfo(), and SBCablesBrowser::SBCablesBrowser().
void SBStationEcc::setID (const SBStationID &ID_) [inline]
Reimplemented from SBStationID'.
Definition at line 1086 of file SbGeoStations.H'.
Referenced by SBEcc::registerEcc(), and sinex_SiteEccentricityBlock().
void SBStationID::setPtType (SBStation::SPointTypePtType_) [inline, inherited]
Definition at line 764 of file SbGeoStations.H'.
References SBStationID::PtType.
Referenced by SBStation::id(), and SBOLoadCarrier::SBOLoadCarrier().
const QString SBStationID::toString () const [inline, inherited]
Definition at line 792 of file SbGeoStations.H'.
References SBStationID::DomeMajor, SBStationID::DomeMinor, SBStation::Pt_Antenna, and SBStationID::PtType.
Referenced by SBSite::addStation(), SBSolutionBrowser::batch4StochStChanged(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffStationsEcc::deleteEntry(), SBPlateMotion::displacement(), SBAploEphem::displacement(), SBStuffAplo::draw(), SBStationInfo::dumpUserInfo(), SBAploChunk::entryByID(), SBAploChunk::fillDict(), SBVLBIPreProcess::fillObsListView(), SBEcc::findEcc(), SBSolution::guessParameterName(), SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBObsVLBIEntry::isEligible(), SBCableLI::key(), SBEccListItem::key(), SBStaInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolutionBrowser::lookupParameters(), SBStationEditor::makeApply(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBRefraction::operator()(), operator<<(), operator>>(), SBSite::prepareDicts(), SBObsVLBIEntry::process(), registerEcc(), SBEcc::registerEcc(), SBAploEphem::registerStation(), SBStationInfo::restoreUserInfo(), SBBaseInfoList::restoreUserInfo(), SBCoordsEditor::SBCoordsEditor(), sinex_tro_SiteIDBlock(), SBAploEphem::spline4station(), SBCableLI::text(), SBEccListItem::text(), SBStaInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBPlateMotion::velocity(), and SBStationEditor::wNames().
Friends And Related Function Documentation
bool operator!= (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 772 of file SbGeoStations.H'.
bool operator< (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 773 of file SbGeoStations.H'.
QDataStream& operator<< (QDataStream &s, const SBStationID &ID) [friend, inherited]
Definition at line 800 of file SbGeoStations.H'.
QDataStream& operator<< (QDataStream &s, const SBStationEcc &StEcc) [friend]
Definition at line 1096 of file SbGeoStations.H'.
bool operator== (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 767 of file SbGeoStations.H'.
bool operator> (const SBStationID &S1, const SBStationID &S2) [friend, inherited]
Definition at line 779 of file SbGeoStations.H'.
QDataStream& operator>> (QDataStream &s, SBStationID &ID) [friend, inherited]
Definition at line 802 of file SbGeoStations.H'.
QDataStream& operator>> (QDataStream &s, SBStationEcc &StEcc) [friend]
Definition at line 1098 of file SbGeoStations.H'.
Member Data Documentation
SBEccentriList SBStationEcc::Eccs [private]
Definition at line 1074 of file SbGeoStations.H'.
Referenced by eccs(), findEcc(), registerEcc(), and SBStationEcc().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.