SBStuffEphem
NAME
SBStuffEphem -
SYNOPSIS
#include <SbIStuff.H>
Inherits QDialog'.
Signals
void stBarReset ()
void stBarSetTotalSteps (int)
void stBarSetProgress (int)
void message (const QString &)
Public Member Functions
SBStuffEphem (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual QString ClassName () const
~SBStuffEphem ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Slots
void import ()
void updateEphem ()
void accept ()
void reject ()
Private Attributes
SBEphem * Weph
QString str
QLabel * LStatus
QLabel * LTStart
QLabel * LTFinis
QLabel * LDt
QLabel * LNCoef
QLabel * LNRecs
QLabel * LAU
QLabel * LCLight
QLabel * LEMRat
QLabel * LBodyMass [11]
Detailed Description
Definition at line 138 of file SbIStuff.H'.
Constructor & Destructor Documentation
SBStuffEphem::SBStuffEphem (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 642 of file SbIStuff.C'.
References accept(), SBEphem::au(), SBEphem::body(), SBEphem::cLight(), Config, SBEphem::dt(), SBConfig::EM_LEDE200, SBConfig::EM_LEDE403, SBConfig::EM_LEDE405, SBEphem::emRat(), SBConfig::ephemModel(), SBMJD::F_Short, SBCelestBody::gm(), SBEphem::isOK(), LAU, LBodyMass, LCLight, LDt, LEMRat, LNCoef, LNRecs, LStatus, LTFinis, LTStart, MainWin, message(), SBNamed::name(), SBEphem::nRecCoef(), SBEphem::numRecs(), reject(), stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), str, SBEphem::sun(), SBEphem::tFinis(), SBMJD::toString(), SBEphem::tStart(), and Weph.
SBStuffEphem::~SBStuffEphem ()
Definition at line 796 of file SbIStuff.C'.
References Weph.
Member Function Documentation
void SBStuffEphem::accept () [private, slot]
Definition at line 801 of file SbIStuff.C'.
Referenced by SBStuffEphem().
virtual QString SBStuffEphem::ClassName () const [inline, virtual]
Definition at line 143 of file SbIStuff.H'.
virtual void SBStuffEphem::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 160 of file SbIStuff.H'.
void SBStuffEphem::import () [private, slot]
Definition at line 828 of file SbIStuff.C'.
References SBEphem::import(), SBSetUp::path2Import(), SetUp, updateEphem(), and Weph.
void SBStuffEphem::message (const QString &t0) [signal]
Definition at line 259 of file SbIStuff.moc.C'.
Referenced by SBStuffEphem().
void SBStuffEphem::reject () [private, slot]
Definition at line 807 of file SbIStuff.C'.
Referenced by SBStuffEphem().
void SBStuffEphem::stBarReset () [signal]
Definition at line 241 of file SbIStuff.moc.C'.
Referenced by SBStuffEphem().
void SBStuffEphem::stBarSetProgress (intt0) [signal]
Definition at line 253 of file SbIStuff.moc.C'.
Referenced by SBStuffEphem().
void SBStuffEphem::stBarSetTotalSteps (intt0) [signal]
Definition at line 247 of file SbIStuff.moc.C'.
Referenced by SBStuffEphem().
void SBStuffEphem::updateEphem () [private, slot]
Definition at line 813 of file SbIStuff.C'.
References SBEphem::au(), SBEphem::body(), SBEphem::cLight(), SBEphem::dt(), SBEphem::emRat(), SBMJD::F_Short, SBCelestBody::gm(), SBEphem::isOK(), LAU, LBodyMass, LCLight, LDt, LEMRat, LNCoef, LNRecs, LStatus, LTFinis, LTStart, SBEphem::nRecCoef(), SBEphem::numRecs(), str, SBEphem::sun(), SBEphem::tFinis(), SBMJD::toString(), SBEphem::tStart(), and Weph.
Referenced by import().
Member Data Documentation
QLabel* SBStuffEphem::LAU [private]
Definition at line 172 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LBodyMass[11] [private]
Definition at line 176 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LCLight [private]
Definition at line 173 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LDt [private]
Definition at line 169 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LEMRat [private]
Definition at line 174 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LNCoef [private]
Definition at line 170 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LNRecs [private]
Definition at line 171 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LStatus [private]
Definition at line 166 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LTFinis [private]
Definition at line 168 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QLabel* SBStuffEphem::LTStart [private]
Definition at line 167 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
QString SBStuffEphem::str [private]
Definition at line 164 of file SbIStuff.H'.
Referenced by SBStuffEphem(), and updateEphem().
SBEphem* SBStuffEphem::Weph [private]
Definition at line 160 of file SbIStuff.H'.
Referenced by import(), SBStuffEphem(), updateEphem(), and ~SBStuffEphem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.