.TH "SBStuffAplo" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBStuffAplo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIStuff\&.H>\fP
.PP
Inherits \fBQDialog\fP'\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstBarReset\fP ()"
.br
.ti -1c
.RI "void \fBstBarSetTotalSteps\fP (int)"
.br
.ti -1c
.RI "void \fBstBarSetProgress\fP (int)"
.br
.ti -1c
.RI "void \fBmessage\fP (const QString &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBStuffAplo\fP (\fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "\fB~SBStuffAplo\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *)"
.br
.ti -1c
.RI "void \fBblockInput\fP ()"
.br
.ti -1c
.RI "void \fBrestoreInput\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBimport\fP ()"
.br
.ti -1c
.RI "void \fBimportHPS\fP ()"
.br
.ti -1c
.RI "void \fBupdateEphem\fP ()"
.br
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.ti -1c
.RI "void \fBreject\fP ()"
.br
.ti -1c
.RI "void \fBheaderChanged\fP (\fBQListViewItem\fP *)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBAploEphem\fP * \fBAploEphem\fP"
.br
.ti -1c
.RI "\fBSBAploChunk\fP * \fBChunk\fP"
.br
.ti -1c
.RI "bool \fBisModified\fP"
.br
.ti -1c
.RI "bool \fBisTRFModified\fP"
.br
.ti -1c
.RI "\fBQListView\fP * \fBHeadersLV\fP"
.br
.ti -1c
.RI "\fBQListView\fP * \fBEntriesLV\fP"
.br
.ti -1c
.RI "QLabel * \fBLStatus\fP"
.br
.ti -1c
.RI "QLabel * \fBLTStart\fP"
.br
.ti -1c
.RI "QLabel * \fBLTFinis\fP"
.br
.ti -1c
.RI "QLabel * \fBLNumChunks\fP"
.br
.ti -1c
.RI "QPushButton * \fBOk\fP"
.br
.ti -1c
.RI "QPushButton * \fBDraw\fP"
.br
.ti -1c
.RI "QPushButton * \fBImport\fP"
.br
.ti -1c
.RI "QPushButton * \fBImportHPS\fP"
.br
.ti -1c
.RI "QPushButton * \fBCancel\fP"
.br
.ti -1c
.RI "bool \fBIsBlockedOkButton\fP"
.br
.ti -1c
.RI "bool \fBIsBlockedDrawButton\fP"
.br
.ti -1c
.RI "bool \fBIsBlockedImportButton\fP"
.br
.ti -1c
.RI "bool \fBIsBlockedImportHPSButton\fP"
.br
.ti -1c
.RI "bool \fBIsBlockedCancelButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 232 of file SbIStuff\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBStuffAplo::SBStuffAplo (\fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 942 of file SbIStuff\&.C'\&.
.PP
References accept(), AploEphem, Cancel, Chunk, draw(), Draw, EntriesLV, SBMJD::F_Short, headerChanged(), HeadersLV, Import, importHPS(), ImportHPS, IsBlockedCancelButton, IsBlockedDrawButton, IsBlockedImportButton, IsBlockedImportHPSButton, IsBlockedOkButton, isModified, SBAploEphem::isOK(), isTRFModified, LNumChunks, SBSetUp::loadAploEphem(), SBAploEphem::loadChunk(), LStatus, LTFinis, LTStart, MainWin, message(), Ok, reject(), SetUp, stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), SBAploEphem::tFinis(), SBMJD::toString(), and SBAploEphem::tStart()\&.
.SS "SBStuffAplo::~SBStuffAplo ()"
.PP
Definition at line 1112 of file SbIStuff\&.C'\&.
.PP
References AploEphem\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBStuffAplo::accept ()\fC [private, slot]\fP"
.PP
Definition at line 1126 of file SbIStuff\&.C'\&.
.PP
References AploEphem, isModified, SBSetUp::saveAploEphem(), and SetUp\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::blockInput ()\fC [protected]\fP"
.PP
Definition at line 1266 of file SbIStuff\&.C'\&.
.PP
References Cancel, Draw, Import, ImportHPS, IsBlockedCancelButton, IsBlockedDrawButton, IsBlockedImportButton, IsBlockedImportHPSButton, IsBlockedOkButton, and Ok\&.
.PP
Referenced by import(), and importHPS()\&.
.SS "virtual QString SBStuffAplo::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 237 of file SbIStuff\&.H'\&.
.SS "virtual void SBStuffAplo::closeEvent (QCloseEvent *)\fC [inline, protected, virtual]\fP"
.PP
Definition at line 257 of file SbIStuff\&.H'\&.
.SS "void SBStuffAplo::draw ()\fC [private, slot]\fP"
.PP
Definition at line 1235 of file SbIStuff\&.C'\&.
.PP
References SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), Chunk, SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), EAST, EntriesLV, SBAploEntry::id(), SBNamed::name(), NORT, SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setType(), SBStationID::toString(), and VERT\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::headerChanged (\fBQListViewItem\fP *Item)\fC [private, slot]\fP"
.PP
Definition at line 1140 of file SbIStuff\&.C'\&.
.PP
References AploEphem, Chunk, EntriesLV, and SBAploEphem::loadChunk()\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::import ()\fC [private, slot]\fP"
.PP
Definition at line 1186 of file SbIStuff\&.C'\&.
.PP
References AploEphem, blockInput(), SBAploEphem::importEphem(), isModified, SBSetUp::loadTRF(), SBSetUp::path2ImpAplo(), restoreInput(), SBSetUp::saveTRF(), SetUp, and updateEphem()\&.
.SS "void SBStuffAplo::importHPS ()\fC [private, slot]\fP"
.PP
Definition at line 1212 of file SbIStuff\&.C'\&.
.PP
References AploEphem, blockInput(), SBAploEphem::importHPS(), isModified, SBSetUp::loadTRF(), SBSetUp::path2ImpAplo(), restoreInput(), SBSetUp::saveTRF(), SetUp, and updateEphem()\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::message (const QString &t0)\fC [signal]\fP"
.PP
Definition at line 412 of file SbIStuff\&.moc\&.C'\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::reject ()\fC [private, slot]\fP"
.PP
Definition at line 1134 of file SbIStuff\&.C'\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::restoreInput ()\fC [protected]\fP"
.PP
Definition at line 1297 of file SbIStuff\&.C'\&.
.PP
References Cancel, Draw, Import, ImportHPS, IsBlockedCancelButton, IsBlockedDrawButton, IsBlockedImportButton, IsBlockedImportHPSButton, IsBlockedOkButton, and Ok\&.
.PP
Referenced by import(), and importHPS()\&.
.SS "void SBStuffAplo::stBarReset ()\fC [signal]\fP"
.PP
Definition at line 394 of file SbIStuff\&.moc\&.C'\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::stBarSetProgress (intt0)\fC [signal]\fP"
.PP
Definition at line 406 of file SbIStuff\&.moc\&.C'\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::stBarSetTotalSteps (intt0)\fC [signal]\fP"
.PP
Definition at line 400 of file SbIStuff\&.moc\&.C'\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "void SBStuffAplo::updateEphem ()\fC [private, slot]\fP"
.PP
Definition at line 1165 of file SbIStuff\&.C'\&.
.PP
References AploEphem, EntriesLV, SBMJD::F_Short, HeadersLV, SBAploEphem::isOK(), LNumChunks, LStatus, LTFinis, LTStart, SBAploEphem::tFinis(), SBMJD::toString(), and SBAploEphem::tStart()\&.
.PP
Referenced by import(), and importHPS()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBAploEphem\fP* \fBSBStuffAplo::AploEphem\fP\fC [private]\fP"
.PP
Definition at line 263 of file SbIStuff\&.H'\&.
.PP
Referenced by accept(), headerChanged(), import(), importHPS(), SBStuffAplo(), updateEphem(), and ~SBStuffAplo()\&.
.SS "QPushButton* \fBSBStuffAplo::Cancel\fP\fC [private]\fP"
.PP
Definition at line 281 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "\fBSBAploChunk\fP* \fBSBStuffAplo::Chunk\fP\fC [private]\fP"
.PP
Definition at line 264 of file SbIStuff\&.H'\&.
.PP
Referenced by draw(), headerChanged(), and SBStuffAplo()\&.
.SS "QPushButton* \fBSBStuffAplo::Draw\fP\fC [private]\fP"
.PP
Definition at line 278 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "\fBQListView\fP* \fBSBStuffAplo::EntriesLV\fP\fC [private]\fP"
.PP
Definition at line 270 of file SbIStuff\&.H'\&.
.PP
Referenced by draw(), headerChanged(), SBStuffAplo(), and updateEphem()\&.
.SS "\fBQListView\fP* \fBSBStuffAplo::HeadersLV\fP\fC [private]\fP"
.PP
Definition at line 269 of file SbIStuff\&.H'\&.
.PP
Referenced by SBStuffAplo(), and updateEphem()\&.
.SS "QPushButton* \fBSBStuffAplo::Import\fP\fC [private]\fP"
.PP
Definition at line 279 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "QPushButton* \fBSBStuffAplo::ImportHPS\fP\fC [private]\fP"
.PP
Definition at line 280 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "bool \fBSBStuffAplo::IsBlockedCancelButton\fP\fC [private]\fP"
.PP
Definition at line 287 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "bool \fBSBStuffAplo::IsBlockedDrawButton\fP\fC [private]\fP"
.PP
Definition at line 284 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "bool \fBSBStuffAplo::IsBlockedImportButton\fP\fC [private]\fP"
.PP
Definition at line 285 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "bool \fBSBStuffAplo::IsBlockedImportHPSButton\fP\fC [private]\fP"
.PP
Definition at line 286 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "bool \fBSBStuffAplo::IsBlockedOkButton\fP\fC [private]\fP"
.PP
Definition at line 283 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.
.SS "bool \fBSBStuffAplo::isModified\fP\fC [private]\fP"
.PP
Definition at line 265 of file SbIStuff\&.H'\&.
.PP
Referenced by accept(), import(), importHPS(), and SBStuffAplo()\&.
.SS "bool \fBSBStuffAplo::isTRFModified\fP\fC [private]\fP"
.PP
Definition at line 266 of file SbIStuff\&.H'\&.
.PP
Referenced by SBStuffAplo()\&.
.SS "QLabel* \fBSBStuffAplo::LNumChunks\fP\fC [private]\fP"
.PP
Definition at line 275 of file SbIStuff\&.H'\&.
.PP
Referenced by SBStuffAplo(), and updateEphem()\&.
.SS "QLabel* \fBSBStuffAplo::LStatus\fP\fC [private]\fP"
.PP
Definition at line 272 of file SbIStuff\&.H'\&.
.PP
Referenced by SBStuffAplo(), and updateEphem()\&.
.SS "QLabel* \fBSBStuffAplo::LTFinis\fP\fC [private]\fP"
.PP
Definition at line 274 of file SbIStuff\&.H'\&.
.PP
Referenced by SBStuffAplo(), and updateEphem()\&.
.SS "QLabel* \fBSBStuffAplo::LTStart\fP\fC [private]\fP"
.PP
Definition at line 273 of file SbIStuff\&.H'\&.
.PP
Referenced by SBStuffAplo(), and updateEphem()\&.
.SS "QPushButton* \fBSBStuffAplo::Ok\fP\fC [private]\fP"
.PP
Definition at line 277 of file SbIStuff\&.H'\&.
.PP
Referenced by blockInput(), restoreInput(), and SBStuffAplo()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
