SBStuffEOPs
NAME
SBStuffEOPs -
SYNOPSIS
#include <SbIStuff.H>
Inherits QDialog'.
Public Member Functions
SBStuffEOPs (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBStuffEOPs ()
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Slots
void modified (bool)
void childWindowClosed ()
void accept ()
void reject ()
void import ()
void draw ()
void showSeries ()
void updateEOP ()
Private Member Functions
QWidget * createInfoGroup (QWidget *)
QWidget * createOptionsGroup (QWidget *)
Private Attributes
SBEOP * Weop
QString str
QListView * EOPsLV
QLabel * EOPTStart
QLabel * EOPTFinis
QLabel * EOPNum
QLineEdit * EOPEpoch
QLineEdit * EOPLabel
QCheckBox * EOPHiTide
QCheckBox * EOPLoTide
QLineEdit * EOPXp
QLineEdit * EOPXps
QLineEdit * EOPYp
QLineEdit * EOPYps
QLineEdit * EOPUT
QLineEdit * EOPUTs
QLineEdit * EOPPsi
QLineEdit * EOPPsis
QLineEdit * EOPEps
QLineEdit * EOPEpss
bool isModified
int numOpenedWindows
SBPlotCarrier * PlotCarrier
Detailed Description
Definition at line 71 of file SbIStuff.H'.
Constructor & Destructor Documentation
SBStuffEOPs::SBStuffEOPs (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 122 of file SbIStuff.C'.
References accept(), createInfoGroup(), createOptionsGroup(), draw(), EOPsLV, isModified, SBSetUp::loadEOP(), numOpenedWindows, PlotCarrier, reject(), SetUp, showSeries(), and Weop.
SBStuffEOPs::~SBStuffEOPs () [virtual]
Definition at line 361 of file SbIStuff.C'.
References PlotCarrier, and Weop.
Member Function Documentation
void SBStuffEOPs::accept () [private, slot]
Definition at line 376 of file SbIStuff.C'.
References EOPEpoch, EOPEps, EOPEpss, EOPHiTide, EOPLabel, EOPLoTide, EOPPsi, EOPPsis, EOPUT, EOPUTs, EOPXp, EOPXps, EOPYp, EOPYps, SBEOP::epoch(), SBEOP::eps(), SBEOP::epss(), SBMJD::F_Year, SBSolutionName::fromString(), isModified, SBEOP::label(), numOpenedWindows, SBEOP::psi(), SBEOP::psis(), SBSetUp::saveEOP(), SBEOP::setEpoch(), SBEOP::setEps(), SBEOP::setEpss(), SBEOP::setLabel(), SBMJD::setMJD(), SBEOP::setPsi(), SBEOP::setPsis(), SetUp, SBEOP::setUt(), SBEOP::setUtHasHiTide(), SBEOP::setUtHasLoTide(), SBEOP::setUts(), SBEOP::setXp(), SBEOP::setXps(), SBEOP::setYp(), SBEOP::setYps(), SBSolutionName::TYPE_EOP, SBEOP::ut(), SBEOP::utHasHiTide(), SBEOP::utHasLoTide(), SBEOP::uts(), Weop, SBEOP::xp(), SBEOP::xps(), SBEOP::yp(), and SBEOP::yps().
Referenced by SBStuffEOPs().
void SBStuffEOPs::childWindowClosed () [private, slot]
Definition at line 495 of file SbIStuff.C'.
References numOpenedWindows.
Referenced by draw().
virtual QString SBStuffEOPs::ClassName () const [inline, virtual]
Definition at line 78 of file SbIStuff.H'.
Referenced by draw().
virtual void SBStuffEOPs::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 92 of file SbIStuff.H'.
QWidget * SBStuffEOPs::createInfoGroup (QWidget *parent) [private]
Definition at line 205 of file SbIStuff.C'.
References EOPEpoch, EOPLabel, EOPNum, EOPTFinis, EOPTStart, SBMJD::F_DDMonYYYY, SBMJD::F_Year, SBEOP::label(), str, SBEOP::tFinis(), SBMJD::toString(), SBSolutionName::toString(), SBEOP::tStart(), and Weop.
Referenced by SBStuffEOPs().
QWidget * SBStuffEOPs::createOptionsGroup (QWidget *parent) [private]
Definition at line 260 of file SbIStuff.C'.
References EOPEps, EOPEpss, EOPHiTide, EOPLoTide, EOPPsi, EOPPsis, EOPUT, EOPUTs, EOPXp, EOPXps, EOPYp, EOPYps, SBEOP::eps(), SBEOP::epss(), SBEOP::psi(), SBEOP::psis(), str, SBEOP::ut(), SBEOP::utHasHiTide(), SBEOP::uts(), Weop, SBEOP::xp(), SBEOP::xps(), SBEOP::yp(), and SBEOP::yps().
Referenced by SBStuffEOPs().
void SBStuffEOPs::draw () [private, slot]
Definition at line 570 of file SbIStuff.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::branches(), childWindowClosed(), ClassName(), SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBLog::DBG, SBLog::INTERFACE, SBEOP::label(), Log, numOpenedWindows, PlotCarrier, SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setType(), SBSolutionName::toString(), Weop, and SBLog::write().
Referenced by SBStuffEOPs().
void SBStuffEOPs::import () [private, slot]
Definition at line 529 of file SbIStuff.C'.
References EOPsLV, SBEOP::importSeries(), isModified, SBSetUp::loadEOP(), mainMessage(), mainPrBarReset(), mainPrBarSetProgress(), mainPrBarSetTotalSteps(), numOpenedWindows, SBSetUp::path2ImpEOP(), PlotCarrier, SBSetUp::saveEOP(), SetUp, updateEOP(), and Weop.
void SBStuffEOPs::modified (boolisModified_) [private, slot]
Definition at line 490 of file SbIStuff.C'.
References isModified.
void SBStuffEOPs::reject () [private, slot]
Definition at line 483 of file SbIStuff.C'.
References numOpenedWindows.
Referenced by SBStuffEOPs().
void SBStuffEOPs::showSeries () [private, slot]
Definition at line 607 of file SbIStuff.C'.
References EOPsLV, mainMessage(), and Weop.
Referenced by SBStuffEOPs(), and updateEOP().
void SBStuffEOPs::updateEOP () [private, slot]
Definition at line 500 of file SbIStuff.C'.
References EOPEpoch, EOPEps, EOPEpss, EOPHiTide, EOPLoTide, EOPNum, EOPPsi, EOPPsis, EOPTFinis, EOPTStart, EOPUT, EOPUTs, EOPXp, EOPXps, EOPYp, EOPYps, SBEOP::eps(), SBEOP::epss(), SBMJD::F_DDMonYYYY, SBMJD::F_Year, SBSetUp::loadEOP(), SBEOP::psi(), SBEOP::psis(), SetUp, showSeries(), str, SBEOP::tFinis(), SBMJD::toString(), SBEOP::tStart(), SBEOP::ut(), SBEOP::utHasHiTide(), SBEOP::uts(), Weop, SBEOP::xp(), SBEOP::xps(), SBEOP::yp(), and SBEOP::yps().
Referenced by import().
Member Data Documentation
QLineEdit* SBStuffEOPs::EOPEpoch [private]
Definition at line 102 of file SbIStuff.H'.
Referenced by accept(), createInfoGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPEps [private]
Definition at line 117 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPEpss [private]
Definition at line 118 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QCheckBox* SBStuffEOPs::EOPHiTide [private]
Definition at line 105 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPLabel [private]
Definition at line 103 of file SbIStuff.H'.
Referenced by accept(), and createInfoGroup().
QCheckBox* SBStuffEOPs::EOPLoTide [private]
Definition at line 106 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLabel* SBStuffEOPs::EOPNum [private]
Definition at line 101 of file SbIStuff.H'.
Referenced by createInfoGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPPsi [private]
Definition at line 115 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPPsis [private]
Definition at line 116 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QListView* SBStuffEOPs::EOPsLV [private]
Definition at line 98 of file SbIStuff.H'.
Referenced by import(), SBStuffEOPs(), and showSeries().
QLabel* SBStuffEOPs::EOPTFinis [private]
Definition at line 100 of file SbIStuff.H'.
Referenced by createInfoGroup(), and updateEOP().
QLabel* SBStuffEOPs::EOPTStart [private]
Definition at line 99 of file SbIStuff.H'.
Referenced by createInfoGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPUT [private]
Definition at line 113 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPUTs [private]
Definition at line 114 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPXp [private]
Definition at line 109 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPXps [private]
Definition at line 110 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPYp [private]
Definition at line 111 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
QLineEdit* SBStuffEOPs::EOPYps [private]
Definition at line 112 of file SbIStuff.H'.
Referenced by accept(), createOptionsGroup(), and updateEOP().
bool SBStuffEOPs::isModified [private]
Definition at line 120 of file SbIStuff.H'.
Referenced by accept(), import(), modified(), and SBStuffEOPs().
int SBStuffEOPs::numOpenedWindows [private]
Definition at line 121 of file SbIStuff.H'.
Referenced by accept(), childWindowClosed(), draw(), import(), reject(), and SBStuffEOPs().
SBPlotCarrier* SBStuffEOPs::PlotCarrier [private]
Definition at line 122 of file SbIStuff.H'.
Referenced by draw(), import(), SBStuffEOPs(), and ~SBStuffEOPs().
QString SBStuffEOPs::str [private]
Definition at line 96 of file SbIStuff.H'.
Referenced by createInfoGroup(), createOptionsGroup(), and updateEOP().
SBEOP* SBStuffEOPs::Weop [private]
Definition at line 92 of file SbIStuff.H'.
Referenced by accept(), createInfoGroup(), createOptionsGroup(), draw(), import(), SBStuffEOPs(), showSeries(), updateEOP(), and ~SBStuffEOPs().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.