SBStuffStationsEcc
NAME
SBStuffStationsEcc -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QDialog'.
Signals
void eccModified (bool)
Public Member Functions
SBStuffStationsEcc (SB_TRF *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBStuffStationsEcc ()
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Private Slots
void importData ()
void exportData ()
void accept ()
void reject ()
void editEntry (QListViewItem *)
void insertEntry ()
void deleteEntry ()
Private Attributes
SBEcc * Ecc
SB_TRF * Wtrf
QListView * EccLV
bool isModified
int numOpenedWindows
Detailed Description
Definition at line 213 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBStuffStationsEcc::SBStuffStationsEcc (SB_TRF *Wtrf_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 461 of file SbIStuffStation.C'.
References accept(), deleteEntry(), Ecc, SB_TRF::ecc(), EccLV, editEntry(), exportData(), importData(), insertEntry(), isModified, numOpenedWindows, reject(), and Wtrf.
SBStuffStationsEcc::~SBStuffStationsEcc ()
Definition at line 561 of file SbIStuffStation.C'.
References eccModified(), and isModified.
Member Function Documentation
void SBStuffStationsEcc::accept () [private, slot]
Definition at line 566 of file SbIStuffStation.C'.
References numOpenedWindows.
Referenced by SBStuffStationsEcc().
virtual QString SBStuffStationsEcc::ClassName () const [inline, virtual]
Definition at line 220 of file SbIStuffStation.H'.
Referenced by deleteEntry(), editEntry(), importData(), and insertEntry().
virtual void SBStuffStationsEcc::closeEvent (QCloseEvent *e) [inline, protected, virtual]
Definition at line 248 of file SbIStuffStation.H'.
References numOpenedWindows.
void SBStuffStationsEcc::deleteEntry () [private, slot]
Definition at line 618 of file SbIStuffStation.C'.
References SBEccentricity::aka(), ClassName(), SBLog::DBG, SBEccListItem::ecc(), Ecc, EccLV, SBStationEcc::eccs(), SBLog::ERR, SBMJD::F_DateShort, SBLog::INTERFACE, isModified, Log, SBEccListItem::stEcc(), SBEccentricity::tFinis(), SBMJD::toString(), SBStationID::toString(), SBEccentricity::tStart(), and SBLog::write().
Referenced by SBStuffStationsEcc().
void SBStuffStationsEcc::eccModified (boolt0) [signal]
Definition at line 279 of file SbIStuffStation.moc.C'.
Referenced by ~SBStuffStationsEcc().
void SBStuffStationsEcc::editEntry (QListViewItem *) [private, slot]
Definition at line 608 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by SBStuffStationsEcc().
void SBStuffStationsEcc::exportData () [private, slot]
Definition at line 604 of file SbIStuffStation.C'.
Referenced by SBStuffStationsEcc().
void SBStuffStationsEcc::importData () [private, slot]
Definition at line 580 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SB_TRF::ecc(), SBEcc::importEccDat(), SBLog::INTERFACE, isModified, Log, numOpenedWindows, SBSetUp::path2Import(), SetUp, SBLog::STATION, SBLog::write(), and Wtrf.
Referenced by SBStuffStationsEcc().
void SBStuffStationsEcc::insertEntry () [private, slot]
Definition at line 613 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by SBStuffStationsEcc().
void SBStuffStationsEcc::reject () [private, slot]
Definition at line 573 of file SbIStuffStation.C'.
References numOpenedWindows.
Referenced by SBStuffStationsEcc().
Member Data Documentation
SBEcc* SBStuffStationsEcc::Ecc [private]
Definition at line 239 of file SbIStuffStation.H'.
Referenced by deleteEntry(), and SBStuffStationsEcc().
QListView* SBStuffStationsEcc::EccLV [private]
Definition at line 242 of file SbIStuffStation.H'.
Referenced by deleteEntry(), and SBStuffStationsEcc().
bool SBStuffStationsEcc::isModified [private]
Definition at line 244 of file SbIStuffStation.H'.
Referenced by deleteEntry(), importData(), SBStuffStationsEcc(), and ~SBStuffStationsEcc().
int SBStuffStationsEcc::numOpenedWindows [private]
Definition at line 245 of file SbIStuffStation.H'.
Referenced by accept(), closeEvent(), importData(), reject(), and SBStuffStationsEcc().
SB_TRF* SBStuffStationsEcc::Wtrf [private]
Definition at line 240 of file SbIStuffStation.H'.
Referenced by importData(), and SBStuffStationsEcc().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.