SBStation
NAME
SBStation -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBNamed, and SBAttributed'.
Public Types
enum SPointType { Pt_Antenna, Pt_Marker, Pt_Unkn }
enum SMountType { Mnt_AZEL, Mnt_EQUA, Mnt_X_YN, Mnt_X_YE, Mnt_Richmond, Mnt_Unkn }
enum SClassCoord { Class_A, Class_B, Class_C, Class_D, Class_E, Class_Z, Class_Unknown }
enum Attributes { OrigImported = 1<<0, OrigEdited = 1<<1, OrigObsData = 1<<2, OrigEstimated = 1<<3, VelocImported = 1<<4, VelocEdited = 1<<5, VelocEstimated = 1<<6, hasOwnOLoad = 1<<7, Analysed = 1<<8, Reserved_10 = 1<<9, Reserved_11 = 1<<10, Reserved_12 = 1<<11 }
Public Member Functions
SBStation (SBSite *, const char *='ZABRISKI')
SBStation (SBSite *, const SBStation &)
virtual ~SBStation ()
virtual QString ClassName () const
virtual SBStation & operator= (const SBStation &)
int domeMinor () const
Technique tech () const
int CDP () const
SPointType pointType () const
SClassCoord classCoord () const
const QString & description () const
const QString & comments () const
SMountType mountType () const
double axisOffset () const
double longitude () const
double latitude () const
double height () const
const Matrix3 & fmVEN () const
const QString & charID () const
SBOLoad * oLoad () const
SBSite * site () const
SBReferencePoint & refPt ()
const Vector3 & r (const SBMJD &t)
const Vector3 & dR (const SBMJD &t)
const Vector3 & r_first () const
const Vector3 & dR_first () const
const Vector3 & rt () const
const Vector3 & ecc () const
const Vector3 & v () const
const Vector3 & v_err () const
const Vector3 & vt () const
Vector3 vModel (SBRunManager *)
SBParameter * p_C0 ()
SBParameter * p_C1 ()
SBParameter * p_C2 ()
SBParameter * p_Clock (int i)
SBParameter * p_Zenith ()
SBParameter * p_AtmGradN ()
SBParameter * p_AtmGradE ()
SBParameter * p_Axis ()
SBParameter * p_DRX ()
SBParameter * p_DRY ()
SBParameter * p_DRZ ()
SBParameter * p_DVX ()
SBParameter * p_DVY ()
SBParameter * p_DVZ ()
SBParameter * p_Cable ()
SBParameter * p_TideLag ()
SBParameter * p_TideH2 ()
SBParameter * p_TideL2 ()
SBParameter * p_Aplo ()
void setDomeMinor (int Domes_)
void setTech (Technique Tech_)
void setCDP (int CDPNum_)
void setPointType (SPointType PointType_)
void setClassCoord (SClassCoord ClassCoord_)
void setDescription (const char *Descr_)
void setComments (const char *Comments_)
void setMountType (SMountType MountType_)
void setAxisOffset (double AxisOffset_)
void setCoords (const Vector3 &R_, const Vector3 &dR_, const Vector3 &V_, const Vector3 &dV_, const SBMJD &T_, const QString &Name_)
void setEcc (const Vector3 &E_)
void setV (const Vector3 &V_)
void setV_i (DIRECTION i, double d_)
void setV_err (const Vector3 &dV_)
void setV_err_i (DIRECTION i, double d_)
void setCharID (const char *CharID_)
void setOLoad (const SBOLoad &OLoad_)
SBStationID id () const
void updateGeodCoo (const SBMJD &t)
void createOLoad (const SBOLoad &OLoad_, SBOLoad::PickUpBy PickedUp_=SBOLoad::P_Manual)
void deleteOLoad ()
void createParameters ()
void releaseParameters ()
void updateParameters (SBRunManager *, const SBMJD &, bool=TRUE)
void getGlobalParameters4Report (SBRunManager *)
void getGlobalParameters4Report4Axel (SBRunManager *)
void getGlobalParameters4UpdateTRF (SBRunManager *)
void calcDisplacement (SBRunManager *, const SBMJD &, bool=TRUE)
double axisOffsetLenght (const Vector3 &, const SBMJD &, double)
QString charID4SINEX ()
void updateStation (const SBStation &)
const QString & name () const
void setName (const QString &Name_)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Static Public Member Functions
static void calcRLF (Vector3, double &, double &, double &)
Protected Attributes
QString Name
Private Member Functions
double axisOffsett () const
Private Attributes
SBSite * Site
owner
int CDPNum
CDP Number'.
int DomeMinor
Domes Number: Site->DomeMajor + {M|S} + DomeMinor'.
Technique Tech
station's tech
SPointType PointType
Reference point type: Antenna or Ground marker'.
SClassCoord ClassCoord
coordinate class;
QString Description
station description, gets from ITRF files
QString Comments
station comments, filled by us
SMountType MountType
Mount type'.
double AxisOffset
station axis offset, m
SBReferencePoint RefPt
Vector3 Rt
station coordinates calculated for time t, m
Vector3 Ecc
eccentricity for the station
Vector3 V
station velocities, m/year
Vector3 Vt
actually used station velocities, m/yr
Vector3 dV
uncert'. of velocities, m/year
QString CharID
an id;
SBOLoad * OLoad
Ocean Loading parameters'.
double Height
station Height, m
double Longitude
station Longitude, rad
double Latitude
station Latitude, rad
Matrix3 FmVEN
matrix transformation from local VEN system
SBParameter * P_Clock [10]
clock offset;
SBParameter * P_Zenith
zenith delay;
SBParameter * P_AtmGradN
horizontal delay gradient North;
SBParameter * P_AtmGradE
horizontal delay gradient East;
SBParameter * P_Axis
axis offset;
SBParameter * P_DRX
correction to x-coordinate;
SBParameter * P_DRY
correction to y-coordinate;
SBParameter * P_DRZ
correction to z-coordinate;
SBParameter * P_DVX
correction to x-velocity;
SBParameter * P_DVY
correction to y-velocity;
SBParameter * P_DVZ
correction to z-velocity;
SBParameter * P_Cable
cable correction multiplier;
SBParameter * P_TideLag
SBParameter * P_TideH2
SBParameter * P_TideL2
SBParameter * P_Aplo
Friends
class SB_TRF
class SBSite
class SBStationList
bool operator== (const SBStation &S1, const SBStation &S2)
bool operator!= (const SBStation &S1, const SBStation &S2)
bool operator< (const SBStation &S1, const SBStation &S2)
bool operator> (const SBStation &S1, const SBStation &S2)
QDataStream & operator<< (QDataStream &, const SBStation &)
QDataStream & operator>> (QDataStream &, SBStation &)
SBTS_dir1994 & operator<< (SBTS_dir1994 &, const SBStation &)
SBTS_dir1994 & operator>> (SBTS_dir1994 &, SBStation &)
SBTS_dir2000 & operator<< (SBTS_dir2000 &, const SBStation &)
SBTS_dir2000 & operator>> (SBTS_dir2000 &, SBStation &)
SBTS_ssc1994 & operator<< (SBTS_ssc1994 &, const SBStation &)
SBTS_ssc2000 & operator<< (SBTS_ssc2000 &, const SBStation &)
SBTS_blqReq & operator<< (SBTS_blqReq &, const SBStation &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Definition at line 457 of file SbGeoStations.H'.
Member Enumeration Documentation
enum SBStation::Attributes
Enumerator:
OrigImported
Info origin: imported;'.
OrigEdited
Info origin: has been edited (alterated by hand);'.
OrigObsData
Info origin: from obs data files;'.
OrigEstimated
Info origin: has been estimated;'.
VelocImported
Info veloct: imported;'.
VelocEdited
Info veloct: has been edited (alterated by hand);'.
VelocEstimated
Info veloct: has been estimated;'.
hasOwnOLoad
station has own tide loading coeffs
Analysed
station was used in the analyses;
Reserved_10
reserved;
Reserved_11
reserved;
Reserved_12
reserved;
Definition at line 466 of file SbGeoStations.H'.
enum SBStation::SClassCoord
Enumerator:
Class_A
Class_B
Class_C
Class_D
Class_E
Class_Z
Class_Unknown
Definition at line 465 of file SbGeoStations.H'.
enum SBStation::SMountType
Enumerator:
Mnt_AZEL
Mnt_EQUA
Mnt_X_YN
Mnt_X_YE
Mnt_Richmond
Mnt_Unkn
Definition at line 464 of file SbGeoStations.H'.
enum SBStation::SPointType
Enumerator:
Pt_Antenna
Pt_Marker
Pt_Unkn
Definition at line 463 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBStation::SBStation (SBSite *Site_, const char *Name_ = 'ZABRISKI')
Definition at line 515 of file SbGeoStations.C'.
References AxisOffset, CDPNum, CharID, Class_Unknown, ClassCoord, Comments, SBAttributed::delAttr(), Description, DomeMinor, hasOwnOLoad, Height, Latitude, Longitude, Mnt_Unkn, MountType, OLoad, P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Cable, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, P_Zenith, PointType, Pt_Antenna, Site, Tech, and TECH_UNKN.
SBStation::SBStation (SBSite *Site_, const SBStation &S)
Definition at line 565 of file SbGeoStations.C'.
References AxisOffset, CDPNum, CharID, ClassCoord, Comments, Description, DomeMinor, Height, Latitude, Longitude, MountType, OLoad, P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Cable, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, P_Zenith, PointType, releaseParameters(), Site, and Tech.
virtual SBStation::~SBStation () [inline, virtual]
Definition at line 551 of file SbGeoStations.H'.
References hasOwnOLoad, SBAttributed::isAttr(), OLoad, and releaseParameters().
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
double SBStation::axisOffset () const [inline]
Definition at line 564 of file SbGeoStations.H'.
References AxisOffset.
Referenced by SBStationEditor::acquireData(), SBRefraction::altitudeCorr(), and SBStationEditor::wCoordinates().
double SBStation::axisOffsetLenght (const Vector3 &s, const SBMJD &T_, doublescal_)"Calculates the lenght caused by antenna axis offset, m'.
Definition at line 1237 of file SbGeoStations.C'.
References SBLog::AXISOFF, axisOffsett(), ClassName(), SBLog::DBG, DEG2RAD, fmVEN(), SBLog::isEligible(), Log, Mnt_AZEL, Mnt_EQUA, Mnt_Richmond, Mnt_Unkn, Mnt_X_YE, Mnt_X_YN, MountType, SBNamed::name(), P_Axis, Vector3::report2Log(), Rt, SBDerivation::setD(), SBLog::write(), SBLog::WRN, and Z_AXIS.
double SBStation::axisOffsett () const [private]
Definition at line 1232 of file SbGeoStations.C'.
References AxisOffset, P_Axis, and SBParameter::v().
Referenced by axisOffsetLenght().
void SBStation::calcDisplacement (SBRunManager *Mgr, const SBMJD &T, boolIsRealRun = TRUE)
Definition at line 1076 of file SbGeoStations.C'.
References SBRunManager::aploEphem(), calcRLF(), SBProject::cfg(), ClassName(), SBLog::DBG, SBAploEphem::displacement(), EAST, Ecc, SBCatalog::epoch(), FmVEN, Height, SBLog::isEligible(), SBConfig::isRollBack2Plates(), SBConfig::isUseAploEphem(), SBConfig::isUseStationVelocity(), Latitude, Log, Longitude, SBNamed::name(), NORT, P_Aplo, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, SBConfig::plateMotion(), SBLog::PLATES, SBRunManager::plates(), SBConfig::PM_NONE, SBRunManager::prj(), SBReferencePoint::r(), SBRunManager::refPlates(), RefPt, Rt, SBRunManager::trf(), TZero, updateParameters(), SBParameter::v(), SBReferencePoint::v(), V, v3Zero, SBPlateMotion::velocity(), Vt, SBLog::write(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), operator<<(), and SBObsVLBIEntry::process().
void SBStation::calcRLF (Vector3R_, double &Ro, double &Lam, double &Fi) [static]
Definition at line 1136 of file SbGeoStations.C'.
References r(), sign(), v(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by calcDisplacement(), operator>>(), setCoords(), and updateGeodCoo().
int SBStation::CDP () const [inline]
Definition at line 558 of file SbGeoStations.H'.
References CDPNum.
Referenced by SBStationEditor::acquireData(), SBStationListItem::key(), SBStationImport::loadOLoad(), operator<<(), operator>>(), SBOLoadCarrier::SBOLoadCarrier(), SBStationListItem::text(), and SBStationEditor::wNames().
const QString& SBStation::charID () const [inline]
Definition at line 571 of file SbGeoStations.H'.
References CharID.
Referenced by SBStationEditor::acquireData(), SBStationListItem::key(), SBStationImport::loadOLoad(), operator<<(), SBOLoadCarrier::SBOLoadCarrier(), SBStationListItem::text(), and SBStationEditor::wNames().
QString SBStation::charID4SINEX ()
Definition at line 1306 of file SbGeoStations.C'.
References CDPNum, and CharID.
Referenced by collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), sinex_tro_SiteIDBlock(), sinex_tro_StaCoordinatesBlock(), and sinex_tro_TropSolutionStation().
SClassCoord SBStation::classCoord () const [inline]
Definition at line 560 of file SbGeoStations.H'.
References ClassCoord.
Referenced by operator<<().
virtual QString SBStation::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBAttributed'.
Definition at line 552 of file SbGeoStations.H'.
Referenced by axisOffsetLenght(), and calcDisplacement().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
const QString& SBStation::comments () const [inline]
Definition at line 562 of file SbGeoStations.H'.
References Comments.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), and SBStationEditor::wNames().
void SBStation::createOLoad (const SBOLoad &OLoad_, SBOLoad::PickUpByPickedUp_ = SBOLoad::P_Manual) [inline]
Definition at line 647 of file SbGeoStations.H'.
References SBAttributed::addAttr(), hasOwnOLoad, and OLoad.
Referenced by SBStationEditor::acquireData(), and SBStationImport::loadOLoad().
void SBStation::createParameters ()
Definition at line 690 of file SbGeoStations.C'.
References P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Cable, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, and P_Zenith.
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
void SBStation::deleteOLoad () [inline]
Definition at line 654 of file SbGeoStations.H'.
References SBAttributed::delAttr(), hasOwnOLoad, and OLoad.
Referenced by SBStationEditor::acquireData().
const QString& SBStation::description () const [inline]
Definition at line 561 of file SbGeoStations.H'.
References Description.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), operator<<(), operator>>(), sinex_tro_SiteIDBlock(), and SBStationEditor::wNames().
int SBStation::domeMinor () const [inline]
Definition at line 556 of file SbGeoStations.H'.
References DomeMinor.
Referenced by SBSite::addStation(), SBSite::delStation(), SBStationListItem::key(), operator<<(), operator>>(), SBSite::prepareDicts(), SBStationListItem::text(), and SBStationEditor::wNames().
const Vector3& SBStation::dR (const SBMJD &t) [inline]
Definition at line 579 of file SbGeoStations.H'.
References SBReferencePoint::dR(), and RefPt.
const Vector3& SBStation::dR_first () const [inline]
Definition at line 582 of file SbGeoStations.H'.
References SBReferencePoint::dR_0(), and RefPt.
Referenced by SBStationEditor::addCoordinates(), and operator<<().
const Vector3& SBStation::ecc () const [inline]
Definition at line 585 of file SbGeoStations.H'.
References Ecc.
const Matrix3& SBStation::fmVEN () const [inline]
Definition at line 570 of file SbGeoStations.H'.
References FmVEN.
Referenced by axisOffsetLenght(), SBTestSolidTides::fillData4Plotting(), SBRunManager::makeReportTRFVariations(), SBSolidTideLd::operator()(), SBSolidTideLd::permTide(), SBSolidTideLdIERS96::permTide(), and SBRefraction::refrDir().
void SBStation::getGlobalParameters4Report (SBRunManager *Mgr)
Definition at line 873 of file SbGeoStations.C'.
References SBProject::cfg(), SBSolution::getGlobalParameter4Report(), SBConfig::isRollBack2Plates(), SBConfig::isUseStationVelocity(), P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, P_Zenith, SBConfig::plateMotion(), SBRunManager::plates(), SBConfig::PM_NONE, SBRunManager::prj(), SBReferencePoint::r(), SBRunManager::refPlates(), RefPt, Rt, SBRunManager::solution(), SBDerivation::tEpoch(), SBParameter::v(), SBReferencePoint::v(), V, v3Zero, SBPlateMotion::velocity(), Vt, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBRunManager::makeReportTRF().
void SBStation::getGlobalParameters4Report4Axel (SBRunManager *Mgr)
Definition at line 919 of file SbGeoStations.C'.
References SBProject::cfg(), dV, SBParameter::e(), SBSolution::getGlobalParameter4Report(), SBConfig::isRollBack2Plates(), SBConfig::isUseStationVelocity(), SBCoordinates::notValid, SBDerivation::num(), P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, P_Zenith, SBConfig::plateMotion(), SBRunManager::plates(), SBConfig::PM_NONE, SBRunManager::prj(), SBRunManager::refPlates(), RefPt, SBRunManager::solution(), SBDerivation::tEpoch(), SBParameter::v(), SBReferencePoint::v(), V, v3Zero, SBPlateMotion::velocity(), Vt, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBRunManager::makeReportTRF().
void SBStation::getGlobalParameters4UpdateTRF (SBRunManager *Mgr)
Definition at line 994 of file SbGeoStations.C'.
References SBProject::cfg(), dV, SBParameter::e(), SBSolution::getGlobalParameter4Report(), SBConfig::isRollBack2Plates(), SBConfig::isUseStationVelocity(), SBCoordinates::notValid, SBDerivation::num(), P_Axis, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, SBConfig::plateMotion(), SBRunManager::plates(), SBConfig::PM_NONE, SBRunManager::prj(), SBRunManager::refPlates(), RefPt, SBRunManager::solution(), SBDerivation::tEpoch(), SBParameter::v(), SBReferencePoint::v(), V, v3Zero, SBPlateMotion::velocity(), Vt, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by SBSolutionBrowser::updateTRF().
double SBStation::height () const [inline]
Definition at line 568 of file SbGeoStations.H'.
References Height.
Referenced by SBStationEditor::makeApply(), SBHZD_Saastamoinen::operator()(), SBWZD_Hopfield::operator()(), SBHMf_MTT::operator()(), SBWMf_MTT::operator()(), SBHMf_NMF::operator()(), sinex_tro_SiteIDBlock(), and SBStationEditor::wCoordinates().
SBStationID SBStation::id () const
Definition at line 680 of file SbGeoStations.C'.
References SBSite::domeMajor(), DomeMinor, PointType, SBStationID::setDomeMajor(), SBStationID::setDomeMinor(), SBStationID::setPtType(), and Site.
Referenced by SBSite::addStation(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSite::delStation(), SBPlateMotion::displacement(), SBTestAPLoad::fillData4Plotting(), SBSite::firstUnusedNumber(), SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBStationEditor::makeApply(), SBRunManager::makeReportTRF(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBRefraction::operator()(), operator<<(), SBSite::prepareDicts(), SBObsVLBIEntry::process(), SBAploEphem::registerStation(), SBCoordsEditor::SBCoordsEditor(), SBOLoadCarrier::SBOLoadCarrier(), sinex_tro_SiteIDBlock(), SBRunManager::stripTRF(), SBTestStationLI::text(), SBSite::updateStationsList(), SBSolutionBrowser::updateTRF(), SBPlateMotion::velocity(), and SBStationEditor::wNames().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and ~SBStation().
double SBStation::latitude () const [inline]
Definition at line 567 of file SbGeoStations.H'.
References Latitude.
Referenced by SBRefraction::altitudeCorr(), SBStationImport::loadOLoad(), SBStationEditor::makeApply(), SBSolidTideLd::makeStep2(), SBPolarTideLd::operator()(), SBHZD_Saastamoinen::operator()(), SBHMf_MTT::operator()(), SBWMf_MTT::operator()(), SBHMf_NMF::operator()(), SBWMf_NMF::operator()(), SBOLoadCarrier::SBOLoadCarrier(), sinex_tro_SiteIDBlock(), and SBStationEditor::wCoordinates().
double SBStation::longitude () const [inline]
Definition at line 565 of file SbGeoStations.H'.
References Longitude.
Referenced by SBRefraction::altitudeCorr(), SBStationImport::loadOLoad(), SBStationEditor::makeApply(), SBSolidTideLd::makeStep2(), SBPolarTideLd::operator()(), SBOLoadCarrier::SBOLoadCarrier(), sinex_tro_SiteIDBlock(), and SBStationEditor::wCoordinates().
SMountType SBStation::mountType () const [inline]
Definition at line 563 of file SbGeoStations.H'.
References MountType.
Referenced by SBStationEditor::acquireData(), SBRefraction::altitudeCorr(), SBStationListItem::key(), SBStationListItem::text(), and SBStationEditor::wCoordinates().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
SBOLoad* SBStation::oLoad () const [inline]
Definition at line 572 of file SbGeoStations.H'.
References OLoad.
Referenced by SBTestOceanTides::fillData4Plotting(), SBStationImport::loadOLoad(), SBTideLd::operator()(), SBOLoadCarrier::SBOLoadCarrier(), and SBStationEditor::wOLoad().
SBStation & SBStation::operator= (const SBStation &S) [virtual]
Definition at line 615 of file SbGeoStations.C'.
References AxisOffset, CDPNum, CharID, ClassCoord, Comments, Description, dV, Ecc, FmVEN, Height, Latitude, Longitude, MountType, SBNamed::Name, OLoad, P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Cable, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, P_Zenith, RefPt, releaseParameters(), Rt, Tech, V, and Vt.
Referenced by updateStation().
SBParameter* SBStation::p_Aplo () [inline]
Definition at line 610 of file SbGeoStations.H'.
References P_Aplo.
SBParameter* SBStation::p_AtmGradE () [inline]
Definition at line 597 of file SbGeoStations.H'.
References P_AtmGradE.
Referenced by SBRefraction::operator()(), and operator<<().
SBParameter* SBStation::p_AtmGradN () [inline]
Definition at line 596 of file SbGeoStations.H'.
References P_AtmGradN.
Referenced by SBRefraction::operator()(), and operator<<().
SBParameter* SBStation::p_Axis () [inline]
Definition at line 598 of file SbGeoStations.H'.
References P_Axis.
SBParameter* SBStation::p_C0 () [inline]
Definition at line 591 of file SbGeoStations.H'.
References P_Clock.
Referenced by SBRunManager::constrainClocks(), and SBObsVLBIEntry::process().
SBParameter* SBStation::p_C1 () [inline]
Definition at line 592 of file SbGeoStations.H'.
References P_Clock.
Referenced by SBRunManager::constrainClocks().
SBParameter* SBStation::p_C2 () [inline]
Definition at line 593 of file SbGeoStations.H'.
References P_Clock.
Referenced by SBRunManager::constrainClocks().
SBParameter* SBStation::p_Cable () [inline]
Definition at line 605 of file SbGeoStations.H'.
References P_Cable.
Referenced by SBObsVLBIEntry::process().
SBParameter* SBStation::p_Clock (inti) [inline]
Definition at line 594 of file SbGeoStations.H'.
References P_Clock.
Referenced by SBObsVLBIEntry::process().
SBParameter* SBStation::p_DRX () [inline]
Definition at line 599 of file SbGeoStations.H'.
References P_DRX.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::makeReportTRFVariations(), and sinex_tro_StaCoordinatesBlock().
SBParameter* SBStation::p_DRY () [inline]
Definition at line 600 of file SbGeoStations.H'.
References P_DRY.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::makeReportTRFVariations(), and sinex_tro_StaCoordinatesBlock().
SBParameter* SBStation::p_DRZ () [inline]
Definition at line 601 of file SbGeoStations.H'.
References P_DRZ.
Referenced by SBDelay::calcDerivatives(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::makeReportTRFVariations(), and sinex_tro_StaCoordinatesBlock().
SBParameter* SBStation::p_DVX () [inline]
Definition at line 602 of file SbGeoStations.H'.
References P_DVX.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::constraintStationVeloc().
SBParameter* SBStation::p_DVY () [inline]
Definition at line 603 of file SbGeoStations.H'.
References P_DVY.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::constraintStationVeloc().
SBParameter* SBStation::p_DVZ () [inline]
Definition at line 604 of file SbGeoStations.H'.
References P_DVZ.
Referenced by SBDelay::calcDerivatives(), and SBRunManager::constraintStationVeloc().
SBParameter* SBStation::p_TideH2 () [inline]
Definition at line 608 of file SbGeoStations.H'.
References P_TideH2.
Referenced by SBDelay::calcDerivatives(), SBSolidTideLd::h2(), and SBSolidTideLdIERS92::h2().
SBParameter* SBStation::p_TideL2 () [inline]
Definition at line 609 of file SbGeoStations.H'.
References P_TideL2.
Referenced by SBDelay::calcDerivatives(), SBSolidTideLd::l2(), and SBSolidTideLdIERS92::l2().
SBParameter* SBStation::p_TideLag () [inline]
Definition at line 607 of file SbGeoStations.H'.
References P_TideLag.
Referenced by SBDelay::calcDerivatives(), SBSolidTideLd::deg2InPhase(), and SBSolidTideLd::dTide_dLag().
SBParameter* SBStation::p_Zenith () [inline]
Definition at line 595 of file SbGeoStations.H'.
References P_Zenith.
Referenced by SBRefraction::operator()(), and operator<<().
SPointType SBStation::pointType () const [inline]
Definition at line 559 of file SbGeoStations.H'.
References PointType.
Referenced by SBSite::addStation(), SBSite::delStation(), SBStationListItem::key(), operator<<(), operator>>(), SBSite::prepareDicts(), SBStationListItem::text(), and SBStationEditor::wNames().
const Vector3& SBStation::r (const SBMJD &t) [inline]
Definition at line 578 of file SbGeoStations.H'.
References SBReferencePoint::r(), and RefPt.
Referenced by calcRLF(), collectListOfSINEXParameters(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SB_TRF::lookupNearest(), and sinex_tro_StaCoordinatesBlock().
const Vector3& SBStation::r_first () const [inline]
Definition at line 581 of file SbGeoStations.H'.
References SBReferencePoint::r_0(), and RefPt.
Referenced by SBStationEditor::addCoordinates(), SBStationImport::applyFilter(), SBAploChunk::import(), SBAploEphem::importHPS(), SBStationListItem::key(), SBStationImport::loadOLoad(), SBRunManager::makeReportTRFVariations(), operator<<(), SBStationListItem::text(), and SBPlateMotion::velocity().
SBReferencePoint& SBStation::refPt () [inline]
Definition at line 577 of file SbGeoStations.H'.
References RefPt.
Referenced by SBStationEditor::addCoordinates(), SBStationEditor::delCoordinates(), SBStationListItem::key(), SBStationListItem::text(), and SBStationEditor::wCoordList().
void SBStation::releaseParameters ()
Definition at line 738 of file SbGeoStations.C'.
References P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Cable, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, and P_Zenith.
Referenced by operator=(), SBStation(), updateStation(), and ~SBStation().
const Vector3& SBStation::rt () const [inline]
Definition at line 583 of file SbGeoStations.H'.
References Rt.
Referenced by SBDelay::calc(), collectListOfSINEXParameters4NEQ(), SBSolidTideLd::deg2InPhase(), SBPlateMotion::displacement(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBSolidTideLd::makeStep1(), SBSolidTideLdIERS96::makeStep1(), SBSolidTideLdIERS96::makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::permTide(), and SBSolidTideLdIERS96::permTide().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBStation::setAxisOffset (doubleAxisOffset_) [inline]
Definition at line 620 of file SbGeoStations.H'.
References AxisOffset.
Referenced by SBStationEditor::acquireData().
void SBStation::setCDP (intCDPNum_) [inline]
Definition at line 614 of file SbGeoStations.H'.
References CDPNum.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), and operator>>().
void SBStation::setCharID (const char *CharID_) [inline]
Definition at line 639 of file SbGeoStations.H'.
References CharID.
Referenced by SBStationEditor::acquireData(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBStationImport::loadNScodes(), and operator>>().
void SBStation::setClassCoord (SClassCoordClassCoord_) [inline]
Definition at line 616 of file SbGeoStations.H'.
References ClassCoord.
Referenced by operator>>().
void SBStation::setComments (const char *Comments_) [inline]
Definition at line 618 of file SbGeoStations.H'.
References Comments.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), and operator>>().
void SBStation::setCoords (const Vector3 &R_, const Vector3 &dR_, const Vector3 &V_, const Vector3 &dV_, const SBMJD &T_, const QString &Name_) [inline]
Definition at line 629 of file SbGeoStations.H'.
References calcRLF(), Height, Latitude, Longitude, RefPt, and SBReferencePoint::registerCoords().
Referenced by SBAploChunk::import(), SBAploEphem::importHPS(), and operator>>().
void SBStation::setDescription (const char *Descr_) [inline]
Definition at line 617 of file SbGeoStations.H'.
References Description.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), and operator>>().
void SBStation::setDomeMinor (intDomes_) [inline]
Definition at line 612 of file SbGeoStations.H'.
References DomeMinor.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), and operator>>().
void SBStation::setEcc (const Vector3 &E_) [inline]
Definition at line 634 of file SbGeoStations.H'.
References Ecc.
void SBStation::setMountType (SMountTypeMountType_) [inline]
Definition at line 619 of file SbGeoStations.H'.
References MountType.
Referenced by SBStationEditor::acquireData().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBStation::setOLoad (const SBOLoad &OLoad_) [inline]
Definition at line 640 of file SbGeoStations.H'.
References OLoad.
Referenced by SBStationEditor::acquireData().
void SBStation::setPointType (SPointTypePointType_) [inline]
Definition at line 615 of file SbGeoStations.H'.
References PointType.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), and operator>>().
void SBStation::setTech (TechniqueTech_) [inline]
Definition at line 613 of file SbGeoStations.H'.
References Tech.
Referenced by SBStationEditor::acquireData(), SBStationImport::loadNScodes(), and operator>>().
void SBStation::setV (const Vector3 &V_) [inline]
Definition at line 635 of file SbGeoStations.H'.
References V.
Referenced by SBAploChunk::import(), SBAploEphem::importHPS(), and operator>>().
void SBStation::setV_err (const Vector3 &dV_) [inline]
Definition at line 637 of file SbGeoStations.H'.
References dV.
Referenced by operator>>().
void SBStation::setV_err_i (DIRECTIONi, doubled_) [inline]
Definition at line 638 of file SbGeoStations.H'.
References dV.
Referenced by SBStationEditor::acquireData().
void SBStation::setV_i (DIRECTIONi, doubled_) [inline]
Definition at line 636 of file SbGeoStations.H'.
References V.
Referenced by SBStationEditor::acquireData().
SBSite* SBStation::site () const [inline]
Definition at line 573 of file SbGeoStations.H'.
References Site.
Referenced by SBPlateMotion::displacement(), SBTestOceanTides::fillData4Plotting(), SBAploChunk::import(), SBAploEphem::importHPS(), SBStationListItem::key(), SBRunManager::makeReportTRFVariations(), SBTideLd::operator()(), SBStationEditor::SBStationEditor(), SBStationListItem::text(), and SBPlateMotion::velocity().
Technique SBStation::tech () const [inline]
Definition at line 557 of file SbGeoStations.H'.
References Tech.
Referenced by SBStationEditor::acquireData(), SBStationImport::applyFilter(), SBStationListItem::key(), SBTestStationLI::key(), SB_TRF::lookupNearest(), operator<<(), SBStationListItem::text(), SBTestStationLI::text(), and SBStationEditor::wTechs().
void SBStation::updateGeodCoo (const SBMJD &t) [inline]
Definition at line 645 of file SbGeoStations.H'.
References calcRLF(), Height, Latitude, Longitude, SBReferencePoint::r(), RefPt, and v3Zero.
Referenced by SBStationEditor::makeApply().
void SBStation::updateParameters (SBRunManager *Mgr, const SBMJD &T, boolIsRealRun = TRUE)
Definition at line 826 of file SbGeoStations.C'.
References P_Aplo, P_AtmGradE, P_AtmGradN, P_Axis, P_Cable, P_Clock, P_DRX, P_DRY, P_DRZ, P_DVX, P_DVY, P_DVZ, P_TideH2, P_TideL2, P_TideLag, P_Zenith, SBRunManager::solution(), and SBSolution::updateParameter().
Referenced by calcDisplacement(), and sinex_tro_StaCoordinatesBlock().
void SBStation::updateStation (const SBStation &S)
Definition at line 1318 of file SbGeoStations.C'.
References CDPNum, CharID, ClassCoord, Comments, Description, dV, Ecc, FmVEN, Height, Latitude, Longitude, SBNamed::Name, OLoad, operator=(), RefPt, releaseParameters(), Rt, Tech, V, and Vt.
Referenced by SBSite::updateStationsList().
const Vector3& SBStation::v () const [inline]
Definition at line 587 of file SbGeoStations.H'.
References V.
Referenced by SBStationEditor::acquireData(), calcRLF(), SBStationListItem::key(), SBStationListItem::text(), and SBStationEditor::wCoordinates().
const Vector3& SBStation::v_err () const [inline]
Definition at line 588 of file SbGeoStations.H'.
References dV.
Referenced by SBStationEditor::acquireData(), and SBStationEditor::wCoordinates().
Vector3 SBStation::vModel (SBRunManager *Mgr)
Definition at line 859 of file SbGeoStations.C'.
References SBProject::cfg(), SBConfig::isRollBack2Plates(), SBConfig::isUseStationVelocity(), SBConfig::plateMotion(), SBRunManager::plates(), SBConfig::PM_NONE, SBRunManager::prj(), SBRunManager::refPlates(), V, v3Zero, and SBPlateMotion::velocity().
Referenced by collectListOfSINEXParameters().
const Vector3& SBStation::vt () const [inline]
Definition at line 589 of file SbGeoStations.H'.
References Vt.
Referenced by SBRunManager::constraintStationVeloc().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator!= (const SBStation &S1, const SBStation &S2) [friend]
Definition at line 540 of file SbGeoStations.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
bool operator< (const SBStation &S1, const SBStation &S2) [friend]
Definition at line 541 of file SbGeoStations.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator<< (QDataStream &s, const SBStation &S) [friend]
Definition at line 1393 of file SbGeoStations.C'.
SBTS_dir1994& operator<< (SBTS_dir1994 &s, const SBStation &S) [friend]
Definition at line 1425 of file SbGeoStations.C'.
SBTS_dir2000& operator<< (SBTS_dir2000 &s, const SBStation &S) [friend]
Definition at line 1487 of file SbGeoStations.C'.
SBTS_ssc1994& operator<< (SBTS_ssc1994 &s, const SBStation &S) [friend]
Definition at line 1568 of file SbGeoStations.C'.
SBTS_ssc2000& operator<< (SBTS_ssc2000 &s, const SBStation &S) [friend]
Definition at line 1593 of file SbGeoStations.C'.
SBTS_blqReq& operator<< (SBTS_blqReq &s, const SBStation &S) [friend]
Definition at line 1651 of file SbGeoStations.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator== (const SBStation &S1, const SBStation &S2) [friend]
Definition at line 538 of file SbGeoStations.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
bool operator> (const SBStation &S1, const SBStation &S2) [friend]
Definition at line 543 of file SbGeoStations.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBStation &S) [friend]
Definition at line 1403 of file SbGeoStations.C'.
SBTS_dir1994& operator>> (SBTS_dir1994 &s, SBStation &S) [friend]
Definition at line 1441 of file SbGeoStations.C'.
SBTS_dir2000& operator>> (SBTS_dir2000 &s, SBStation &S) [friend]
Definition at line 1502 of file SbGeoStations.C'.
friend class SB_TRF [friend]
Definition at line 459 of file SbGeoStations.H'.
friend class SBSite [friend]
Definition at line 460 of file SbGeoStations.H'.
friend class SBStationList [friend]
Definition at line 461 of file SbGeoStations.H'.
Member Data Documentation
double SBStation::AxisOffset [private]
station axis offset, m
Definition at line 493 of file SbGeoStations.H'.
Referenced by axisOffset(), axisOffsett(), operator<<(), operator=(), operator>>(), SBStation(), and setAxisOffset().
int SBStation::CDPNum [private]
CDP Number'.
Definition at line 485 of file SbGeoStations.H'.
Referenced by CDP(), charID4SINEX(), operator<<(), operator=(), operator>>(), SBStation(), setCDP(), and updateStation().
QString SBStation::CharID [private]
an id;
Definition at line 502 of file SbGeoStations.H'.
Referenced by charID(), charID4SINEX(), operator<<(), operator=(), operator>>(), SBStation(), setCharID(), and updateStation().
SClassCoord SBStation::ClassCoord [private]
coordinate class;
Definition at line 489 of file SbGeoStations.H'.
Referenced by classCoord(), operator<<(), operator=(), operator>>(), SBStation(), setClassCoord(), and updateStation().
QString SBStation::Comments [private]
station comments, filled by us
Definition at line 491 of file SbGeoStations.H'.
Referenced by comments(), operator<<(), operator=(), operator>>(), SBStation(), setComments(), and updateStation().
QString SBStation::Description [private]
station description, gets from ITRF files
Definition at line 490 of file SbGeoStations.H'.
Referenced by description(), operator<<(), operator=(), operator>>(), SBStation(), setDescription(), and updateStation().
int SBStation::DomeMinor [private]
Domes Number: Site->DomeMajor + {M|S} + DomeMinor'.
Definition at line 486 of file SbGeoStations.H'.
Referenced by domeMinor(), id(), operator<<(), operator>>(), SBStation(), and setDomeMinor().
Vector3 SBStation::dV [private]
uncert'. of velocities, m/year
Definition at line 501 of file SbGeoStations.H'.
Referenced by getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator<<(), operator=(), operator>>(), setV_err(), setV_err_i(), updateStation(), and v_err().
Vector3 SBStation::Ecc [private]
eccentricity for the station
Definition at line 498 of file SbGeoStations.H'.
Referenced by calcDisplacement(), ecc(), operator=(), setEcc(), and updateStation().
Matrix3 SBStation::FmVEN [private]
matrix transformation from local VEN system
Definition at line 509 of file SbGeoStations.H'.
Referenced by calcDisplacement(), fmVEN(), operator=(), operator>>(), and updateStation().
double SBStation::Height [private]
station Height, m
Definition at line 506 of file SbGeoStations.H'.
Referenced by calcDisplacement(), height(), operator=(), operator>>(), SBStation(), setCoords(), updateGeodCoo(), and updateStation().
double SBStation::Latitude [private]
station Latitude, rad
Definition at line 508 of file SbGeoStations.H'.
Referenced by calcDisplacement(), latitude(), operator=(), operator>>(), SBStation(), setCoords(), updateGeodCoo(), and updateStation().
double SBStation::Longitude [private]
station Longitude, rad
Definition at line 507 of file SbGeoStations.H'.
Referenced by calcDisplacement(), longitude(), operator=(), operator>>(), SBStation(), setCoords(), updateGeodCoo(), and updateStation().
SMountType SBStation::MountType [private]
Mount type'.
Definition at line 492 of file SbGeoStations.H'.
Referenced by axisOffsetLenght(), mountType(), operator<<(), operator=(), operator>>(), SBStation(), and setMountType().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and updateStation().
SBOLoad* SBStation::OLoad [private]
Ocean Loading parameters'.
Definition at line 503 of file SbGeoStations.H'.
Referenced by createOLoad(), deleteOLoad(), oLoad(), operator<<(), operator=(), operator>>(), SBStation(), setOLoad(), updateStation(), and ~SBStation().
SBParameter* SBStation::P_Aplo [private]
Definition at line 528 of file SbGeoStations.H'.
Referenced by calcDisplacement(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_Aplo(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_AtmGradE [private]
horizontal delay gradient East;
Definition at line 515 of file SbGeoStations.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_AtmGradE(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_AtmGradN [private]
horizontal delay gradient North;
Definition at line 514 of file SbGeoStations.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_AtmGradN(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_Axis [private]
axis offset;
Definition at line 516 of file SbGeoStations.H'.
Referenced by axisOffsetLenght(), axisOffsett(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), p_Axis(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_Cable [private]
cable correction multiplier;
Definition at line 523 of file SbGeoStations.H'.
Referenced by createParameters(), operator=(), p_Cable(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_Clock[10] [private]
clock offset;
Definition at line 512 of file SbGeoStations.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_C0(), p_C1(), p_C2(), p_Clock(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_DRX [private]
correction to x-coordinate;
Definition at line 517 of file SbGeoStations.H'.
Referenced by calcDisplacement(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), p_DRX(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_DRY [private]
correction to y-coordinate;
Definition at line 518 of file SbGeoStations.H'.
Referenced by calcDisplacement(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), p_DRY(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_DRZ [private]
correction to z-coordinate;
Definition at line 519 of file SbGeoStations.H'.
Referenced by calcDisplacement(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), p_DRZ(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_DVX [private]
correction to x-velocity;
Definition at line 520 of file SbGeoStations.H'.
Referenced by calcDisplacement(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), p_DVX(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_DVY [private]
correction to y-velocity;
Definition at line 521 of file SbGeoStations.H'.
Referenced by calcDisplacement(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), p_DVY(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_DVZ [private]
correction to z-velocity;
Definition at line 522 of file SbGeoStations.H'.
Referenced by calcDisplacement(), createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), p_DVZ(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_TideH2 [private]
Definition at line 526 of file SbGeoStations.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_TideH2(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_TideL2 [private]
Definition at line 527 of file SbGeoStations.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_TideL2(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_TideLag [private]
Definition at line 525 of file SbGeoStations.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_TideLag(), releaseParameters(), SBStation(), and updateParameters().
SBParameter* SBStation::P_Zenith [private]
zenith delay;
Definition at line 513 of file SbGeoStations.H'.
Referenced by createParameters(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), operator=(), p_Zenith(), releaseParameters(), SBStation(), and updateParameters().
SPointType SBStation::PointType [private]
Reference point type: Antenna or Ground marker'.
Definition at line 488 of file SbGeoStations.H'.
Referenced by id(), operator<<(), operator>>(), pointType(), SBStation(), and setPointType().
SBReferencePoint SBStation::RefPt [private]
Definition at line 496 of file SbGeoStations.H'.
Referenced by calcDisplacement(), dR(), dR_first(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator<<(), operator=(), operator>>(), r(), r_first(), refPt(), setCoords(), updateGeodCoo(), and updateStation().
Vector3 SBStation::Rt [private]
station coordinates calculated for time t, m
Definition at line 497 of file SbGeoStations.H'.
Referenced by axisOffsetLenght(), calcDisplacement(), getGlobalParameters4Report(), operator=(), operator>>(), rt(), and updateStation().
SBSite* SBStation::Site [private]
owner
Definition at line 484 of file SbGeoStations.H'.
Referenced by id(), SBSite::prepareDicts(), SBStation(), and site().
Technique SBStation::Tech [private]
station's tech
Definition at line 487 of file SbGeoStations.H'.
Referenced by operator<<(), operator=(), operator>>(), SBStation(), setTech(), tech(), and updateStation().
Vector3 SBStation::V [private]
station velocities, m/year
Definition at line 499 of file SbGeoStations.H'.
Referenced by calcDisplacement(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), SB_TRF::lookupNearest(), operator<<(), operator=(), operator>>(), setV(), setV_i(), updateStation(), v(), and vModel().
Vector3 SBStation::Vt [private]
actually used station velocities, m/yr
Definition at line 500 of file SbGeoStations.H'.
Referenced by calcDisplacement(), getGlobalParameters4Report(), getGlobalParameters4Report4Axel(), getGlobalParameters4UpdateTRF(), operator=(), updateStation(), and vt().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.