.TH "SBStaInfoLI" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBStaInfoLI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBI\&.H>\fP
.PP
Inherits \fBQListViewItem\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBStaInfoLI\fP (\fBQListView\fP *parent, \fBSBStationInfo\fP *SI_, \fBBrowseMode\fP Mode_)"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "\fBSBStationInfo\fP * \fBstationInfo\fP ()"
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.ti -1c
.RI "virtual QString \fBkey\fP (int, bool) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBStationInfo\fP * \fBStaInf\fP"
.br
.ti -1c
.RI "\fBBrowseMode\fP \fBMode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 130 of file SbIObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBStaInfoLI::SBStaInfoLI (\fBQListView\fP *parent, \fBSBStationInfo\fP *SI_, \fBBrowseMode\fPMode_)\fC [inline]\fP"
.PP
Definition at line 136 of file SbIObsVLBI\&.H'\&.
.PP
References Mode, and StaInf\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBStaInfoLI::ClassName () const\fC [inline, virtual]\fP"
.PP
Definition at line 138 of file SbIObsVLBI\&.H'\&.
.SS "QString SBStaInfoLI::key (intcol, bool) const\fC [virtual]\fP"
.PP
Definition at line 608 of file SbIObsVLBI\&.C'\&.
.PP
References SBObjectObsInfo::aka(), SBStationInfo::ArtMeteo, SBStationInfo::BadCable, SBStationInfo::BadMeteo, BM_GENERAL, BM_PROJECT, SBStationInfo::cl_E(), SBStationInfo::cl_Order(), SBStationInfo::cl_V(), SBStationInfo::clockBreaks(), SBStationInfo::ConstrCoo, SBStationInfo::ConstrVel, SBStationInfo::errZw(), SBStationInfo::EstCoo, SBStationInfo::EstVel, SBStationInfo::HasClockBreak, SBObjectObsInfo::idx(), SBStationInfo::InvCable, SBAttributed::isAttr(), Mode, SBStationInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBStationInfo::refClock, SBSetUp::scale(), SetUp, StaInf, TmpString, SBStationID::toString(), SBStationInfo::UseLocalClocks, SBStationInfo::UseLocalZenith, SBObjectObsInfo::wrms(), and SBStationInfo::zw()\&.
.SS "\fBSBStationInfo\fP* SBStaInfoLI::stationInfo ()\fC [inline]\fP"
.PP
Definition at line 139 of file SbIObsVLBI\&.H'\&.
.PP
References StaInf\&.
.SS "QString SBStaInfoLI::text (intcol) const\fC [virtual]\fP"
.PP
Definition at line 502 of file SbIObsVLBI\&.C'\&.
.PP
References SBObjectObsInfo::aka(), SBStationInfo::ArtMeteo, SBStationInfo::BadCable, SBStationInfo::BadMeteo, BM_GENERAL, BM_PROJECT, SBStationInfo::cl_E(), SBStationInfo::cl_Order(), SBStationInfo::cl_V(), SBStationInfo::clockBreaks(), SBStationInfo::ConstrCoo, SBStationInfo::ConstrVel, SBStationInfo::errZw(), SBStationInfo::EstCoo, SBStationInfo::EstVel, SBStationInfo::HasClockBreak, SBObjectObsInfo::idx(), SBStationInfo::InvCable, SBAttributed::isAttr(), Mode, SBStationInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBStationInfo::refClock, SBSetUp::scale(), SetUp, StaInf, TmpString, SBStationID::toString(), SBStationInfo::UseLocalClocks, SBStationInfo::UseLocalZenith, SBObjectObsInfo::wrms(), and SBStationInfo::zw()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBrowseMode\fP \fBSBStaInfoLI::Mode\fP\fC [private]\fP"
.PP
Definition at line 134 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by key(), SBStaInfoLI(), and text()\&.
.SS "\fBSBStationInfo\fP* \fBSBStaInfoLI::StaInf\fP\fC [private]\fP"
.PP
Definition at line 133 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by key(), SBStaInfoLI(), stationInfo(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
