SBStuffStations
NAME
SBStuffStations -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QDialog'.
Public Member Functions
SBStuffStations (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBStuffStations ()
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Private Slots
void importData ()
void exportData ()
void accept ()
void reject ()
void reloadTRF ()
void editEntryA (QListViewItem *)
void insertEntryA ()
void deleteEntryA ()
void editEntryS (QListViewItem *)
void insertEntryS ()
void deleteEntryS ()
void browseEcc ()
void TRFModified (bool)
Private Member Functions
void drawInfo ()
Private Attributes
SB_TRF * Wtrf
QString str
QListView * SitesLV
QListView * AliasesLV
QLineEdit * TRFEpoch
QLineEdit * TRFLabel
QLineEdit * TRFComment
QLabel * NumSA
bool isModifiedTRF
int numOpenedWindows
Detailed Description
Definition at line 155 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBStuffStations::SBStuffStations (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 665 of file SbIStuffStation.C'.
References accept(), SBSite::addStation(), SBCatalog::aliasDict(), AliasesLV, browseEcc(), SBCatalog::comment(), deleteEntryA(), deleteEntryS(), editEntryA(), editEntryS(), SBCatalog::epoch(), exportData(), SBMJD::F_Year, SB_TRF::first(), importData(), insertEntryA(), insertEntryS(), SB_TRF::inSort(), isModifiedTRF, SBCatalog::label(), SBSetUp::loadTRF(), SB_TRF::next(), numOpenedWindows, NumSA, reject(), SetUp, SitesLV, str, SBMJD::toString(), SBSolutionName::toString(), TRFComment, TRFEpoch, TRFLabel, and Wtrf.
SBStuffStations::~SBStuffStations ()
Definition at line 877 of file SbIStuffStation.C'.
References Wtrf.
Member Function Documentation
void SBStuffStations::accept () [private, slot]
Definition at line 882 of file SbIStuffStation.C'.
References SBCatalog::comment(), SBCatalog::epoch(), SBMJD::F_Year, SBSolutionName::fromString(), isModifiedTRF, SBCatalog::label(), numOpenedWindows, SBSetUp::saveTRF(), SBCatalog::setComment(), SBCatalog::setEpoch(), SBCatalog::setLabel(), SBMJD::setMJD(), SetUp, str, SBMJD::toString(), TRFComment, TRFEpoch, TRFLabel, SBSolutionName::TYPE_SSC, and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::browseEcc () [private, slot]
Definition at line 973 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, TRFModified(), SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
virtual QString SBStuffStations::ClassName () const [inline, virtual]
Definition at line 162 of file SbIStuffStation.H'.
Referenced by browseEcc(), deleteEntryA(), deleteEntryS(), editEntryA(), editEntryS(), exportData(), importData(), insertEntryA(), and insertEntryS().
virtual void SBStuffStations::closeEvent (QCloseEvent *e) [inline, protected, virtual]
Definition at line 201 of file SbIStuffStation.H'.
References numOpenedWindows.
void SBStuffStations::deleteEntryA () [private, slot]
Definition at line 1066 of file SbIStuffStation.C'.
References SBAliasListItem::Alias, SBCatalog::aliasDict(), AliasesLV, ClassName(), SBLog::DBG, SBLog::ERR, SBLog::INTERFACE, isModifiedTRF, Log, numOpenedWindows, NumSA, SBAliasListItem::Reference, str, SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::deleteEntryS () [private, slot]
Definition at line 1119 of file SbIStuffStation.C'.
References SBCatalog::aliasDict(), ClassName(), SBLog::DBG, SBLog::ERR, SBLog::INTERFACE, isModifiedTRF, Log, SBNamed::name(), NumSA, SB_TRF::remove(), SBSiteListItem::Site, SitesLV, str, SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::drawInfo () [private]
Definition at line 962 of file SbIStuffStation.C'.
References SBCatalog::aliasDict(), SBCatalog::comment(), SBCatalog::epoch(), SBMJD::F_Year, SBCatalog::label(), NumSA, str, SBMJD::toString(), SBSolutionName::toString(), TRFComment, TRFEpoch, TRFLabel, and Wtrf.
Referenced by reloadTRF().
void SBStuffStations::editEntryA (QListViewItem *AkaItem) [private, slot]
Definition at line 1046 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, TRFModified(), SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::editEntryS (QListViewItem *SiteItem) [private, slot]
Definition at line 1099 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, TRFModified(), and SBLog::write().
Referenced by SBStuffStations().
void SBStuffStations::exportData () [private, slot]
Definition at line 1000 of file SbIStuffStation.C'.
References SBStation::Class_A, SBStation::Class_B, SBStation::Class_C, SBStation::Class_D, SBStation::Class_Z, ClassName(), SBLog::DBG, SBLog::ERR, SBLog::INTERFACE, SBLog::IO, Log, SBSetUp::path2Output(), SetUp, SBSetUp::stations(), SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::importData () [private, slot]
Definition at line 984 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, isModifiedTRF, Log, numOpenedWindows, reloadTRF(), SBSetUp::saveTRF(), SetUp, SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::insertEntryA () [private, slot]
Definition at line 1056 of file SbIStuffStation.C'.
References AliasesLV, ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, TRFModified(), SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::insertEntryS () [private, slot]
Definition at line 1109 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, numOpenedWindows, SitesLV, TRFModified(), SBLog::write(), and Wtrf.
Referenced by SBStuffStations().
void SBStuffStations::reject () [private, slot]
Definition at line 920 of file SbIStuffStation.C'.
References numOpenedWindows.
Referenced by SBStuffStations().
void SBStuffStations::reloadTRF () [private, slot]
Definition at line 927 of file SbIStuffStation.C'.
References SBSite::addStation(), SBCatalog::aliasDict(), AliasesLV, drawInfo(), SB_TRF::first(), SB_TRF::inSort(), SBSetUp::loadTRF(), SB_TRF::next(), SetUp, SitesLV, and Wtrf.
Referenced by importData().
void SBStuffStations::TRFModified (boolModified) [private, slot]
Definition at line 1153 of file SbIStuffStation.C'.
References SBCatalog::aliasDict(), isModifiedTRF, numOpenedWindows, NumSA, str, and Wtrf.
Referenced by browseEcc(), editEntryA(), editEntryS(), insertEntryA(), and insertEntryS().
Member Data Documentation
QListView* SBStuffStations::AliasesLV [private]
Definition at line 189 of file SbIStuffStation.H'.
Referenced by deleteEntryA(), insertEntryA(), reloadTRF(), and SBStuffStations().
bool SBStuffStations::isModifiedTRF [private]
Definition at line 195 of file SbIStuffStation.H'.
Referenced by accept(), deleteEntryA(), deleteEntryS(), importData(), SBStuffStations(), and TRFModified().
int SBStuffStations::numOpenedWindows [private]
Definition at line 196 of file SbIStuffStation.H'.
Referenced by accept(), browseEcc(), closeEvent(), deleteEntryA(), editEntryA(), editEntryS(), importData(), insertEntryA(), insertEntryS(), reject(), SBStuffStations(), and TRFModified().
QLabel* SBStuffStations::NumSA [private]
Definition at line 194 of file SbIStuffStation.H'.
Referenced by deleteEntryA(), deleteEntryS(), drawInfo(), SBStuffStations(), and TRFModified().
QListView* SBStuffStations::SitesLV [private]
Definition at line 188 of file SbIStuffStation.H'.
Referenced by deleteEntryS(), insertEntryS(), reloadTRF(), and SBStuffStations().
QString SBStuffStations::str [private]
Definition at line 186 of file SbIStuffStation.H'.
Referenced by accept(), deleteEntryA(), deleteEntryS(), drawInfo(), SBStuffStations(), and TRFModified().
QLineEdit* SBStuffStations::TRFComment [private]
Definition at line 193 of file SbIStuffStation.H'.
Referenced by accept(), drawInfo(), and SBStuffStations().
QLineEdit* SBStuffStations::TRFEpoch [private]
Definition at line 191 of file SbIStuffStation.H'.
Referenced by accept(), drawInfo(), and SBStuffStations().
QLineEdit* SBStuffStations::TRFLabel [private]
Definition at line 192 of file SbIStuffStation.H'.
Referenced by accept(), drawInfo(), and SBStuffStations().
SB_TRF* SBStuffStations::Wtrf [private]
Definition at line 185 of file SbIStuffStation.H'.
Referenced by accept(), browseEcc(), deleteEntryA(), deleteEntryS(), drawInfo(), editEntryA(), exportData(), importData(), insertEntryA(), insertEntryS(), reloadTRF(), SBStuffStations(), TRFModified(), and ~SBStuffStations().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.