SBStaParsEditor
NAME
SBStaParsEditor -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QDialog'.
Signals
void staInfoModified (bool)
Public Member Functions
SBStaParsEditor (SBStationInfo *, const SBMJD &, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBStaParsEditor ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
void editEntry ()
void deleteEntry ()
void insertEntry ()
void modified (bool)
void editClocksPar ()
void editZenithPar ()
Private Member Functions
virtual void acquireData ()
Private Attributes
SBStationInfo * SI
SBMJD T0
bool isModified
QListView * ClockBreaksLV
QSpinBox * sbOrder
QCheckBox * cbClocks
QCheckBox * cbZenith
QCheckBox * cbAttrs [6]
QPushButton * CPButton
QPushButton * ZPButton
Detailed Description
Definition at line 771 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBStaParsEditor::SBStaParsEditor (SBStationInfo *SI_, const SBMJD &T0_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 3467 of file SbIObsVLBI.C'.
References accept(), SBObjectObsInfo::aka(), SBStationInfo::ArtMeteo, SBStationInfo::BadCable, SBStationInfo::BadMeteo, cbAttrs, cbClocks, cbZenith, SBStationInfo::cl_Order(), SBStationInfo::clockBreaks(), ClockBreaksLV, CPButton, deleteEntry(), editClocksPar(), editEntry(), editZenithPar(), insertEntry(), SBStationInfo::InvCable, SBAttributed::isAttr(), isModified, SBStationInfo::notValid, SBStationInfo::refClock, reject(), sbOrder, SI, T0, SBStationInfo::UseLocalClocks, SBStationInfo::UseLocalZenith, and ZPButton.
SBStaParsEditor::~SBStaParsEditor () [virtual]
Definition at line 3603 of file SbIObsVLBI.C'.
References isModified, SI, and staInfoModified().
Member Function Documentation
void SBStaParsEditor::accept () [protected, slot]
Definition at line 3609 of file SbIObsVLBI.C'.
References acquireData().
Referenced by SBStaParsEditor().
void SBStaParsEditor::acquireData () [private, virtual]
Definition at line 3616 of file SbIObsVLBI.C'.
References SBStationInfo::ArtMeteo, SBStationInfo::BadCable, SBStationInfo::BadMeteo, cbAttrs, cbClocks, cbZenith, SBStationInfo::cl_Order(), SBStationInfo::InvCable, SBAttributed::isAttr(), isModified, SBStationInfo::notValid, SBStationInfo::refClock, sbOrder, SBStationInfo::setCl_Order(), SI, SBStationInfo::UseLocalClocks, SBStationInfo::UseLocalZenith, and SBAttributed::xorAttr().
Referenced by accept().
virtual QString SBStaParsEditor::ClassName () const [inline, virtual]
Definition at line 777 of file SbIObsVLBI.H'.
Referenced by deleteEntry().
void SBStaParsEditor::deleteEntry () [protected, slot]
Definition at line 3670 of file SbIObsVLBI.C'.
References ClassName(), SBClockBreakLI::clockBreak(), SBStationInfo::clockBreaks(), ClockBreaksLV, SBLog::ERR, SBLog::INTERFACE, isModified, Log, SI, SBMJD::toString(), and SBLog::write().
Referenced by SBStaParsEditor().
void SBStaParsEditor::editClocksPar () [protected, slot]
Definition at line 3725 of file SbIObsVLBI.C'.
References SBStationInfo::clocks(), modified(), and SI.
Referenced by SBStaParsEditor().
void SBStaParsEditor::editEntry () [protected, slot]
Definition at line 3708 of file SbIObsVLBI.C'.
References ClockBreaksLV, and modified().
Referenced by SBStaParsEditor().
void SBStaParsEditor::editZenithPar () [protected, slot]
Definition at line 3732 of file SbIObsVLBI.C'.
References modified(), SI, and SBStationInfo::zenith().
Referenced by SBStaParsEditor().
void SBStaParsEditor::insertEntry () [protected, slot]
Definition at line 3697 of file SbIObsVLBI.C'.
References SBStationInfo::clockBreaks(), ClockBreaksLV, modified(), SI, and T0.
Referenced by SBStaParsEditor().
void SBStaParsEditor::modified (boolIsModified_) [protected, slot]
Definition at line 3719 of file SbIObsVLBI.C'.
References ClockBreaksLV, and isModified.
Referenced by editClocksPar(), editEntry(), editZenithPar(), and insertEntry().
void SBStaParsEditor::reject () [inline, protected, slot]
Definition at line 786 of file SbIObsVLBI.H'.
Referenced by SBStaParsEditor().
void SBStaParsEditor::staInfoModified (boolt0) [signal]
Definition at line 1403 of file SbIObsVLBI.moc.C'.
Referenced by ~SBStaParsEditor().
Member Data Documentation
QCheckBox* SBStaParsEditor::cbAttrs[6] [private]
Definition at line 805 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBStaParsEditor().
QCheckBox* SBStaParsEditor::cbClocks [private]
Definition at line 802 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBStaParsEditor().
QCheckBox* SBStaParsEditor::cbZenith [private]
Definition at line 803 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBStaParsEditor().
QListView* SBStaParsEditor::ClockBreaksLV [private]
Definition at line 800 of file SbIObsVLBI.H'.
Referenced by deleteEntry(), editEntry(), insertEntry(), modified(), and SBStaParsEditor().
QPushButton* SBStaParsEditor::CPButton [private]
Definition at line 807 of file SbIObsVLBI.H'.
Referenced by SBStaParsEditor().
bool SBStaParsEditor::isModified [private]
Definition at line 797 of file SbIObsVLBI.H'.
Referenced by acquireData(), deleteEntry(), modified(), SBStaParsEditor(), and ~SBStaParsEditor().
QSpinBox* SBStaParsEditor::sbOrder [private]
Definition at line 801 of file SbIObsVLBI.H'.
Referenced by acquireData(), and SBStaParsEditor().
SBStationInfo* SBStaParsEditor::SI [private]
Definition at line 795 of file SbIObsVLBI.H'.
Referenced by acquireData(), deleteEntry(), editClocksPar(), editZenithPar(), insertEntry(), SBStaParsEditor(), and ~SBStaParsEditor().
SBMJD SBStaParsEditor::T0 [private]
Definition at line 796 of file SbIObsVLBI.H'.
Referenced by insertEntry(), and SBStaParsEditor().
QPushButton* SBStaParsEditor::ZPButton [private]
Definition at line 808 of file SbIObsVLBI.H'.
Referenced by SBStaParsEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.