SBStaInfoLI
NAME
SBStaInfoLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QListViewItem'.
Public Member Functions
SBStaInfoLI (QListView *parent, SBStationInfo *SI_, BrowseMode Mode_)
virtual QString ClassName () const
SBStationInfo * stationInfo ()
virtual QString text (int) const
virtual QString key (int, bool) const
Private Attributes
SBStationInfo * StaInf
BrowseMode Mode
Detailed Description
Definition at line 130 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBStaInfoLI::SBStaInfoLI (QListView *parent, SBStationInfo *SI_, BrowseModeMode_) [inline]
Definition at line 136 of file SbIObsVLBI.H'.
References Mode, and StaInf.
Member Function Documentation
virtual QString SBStaInfoLI::ClassName () const [inline, virtual]
Definition at line 138 of file SbIObsVLBI.H'.
QString SBStaInfoLI::key (intcol, bool) const [virtual]
Definition at line 608 of file SbIObsVLBI.C'.
References SBObjectObsInfo::aka(), SBStationInfo::ArtMeteo, SBStationInfo::BadCable, SBStationInfo::BadMeteo, BM_GENERAL, BM_PROJECT, SBStationInfo::cl_E(), SBStationInfo::cl_Order(), SBStationInfo::cl_V(), SBStationInfo::clockBreaks(), SBStationInfo::ConstrCoo, SBStationInfo::ConstrVel, SBStationInfo::errZw(), SBStationInfo::EstCoo, SBStationInfo::EstVel, SBStationInfo::HasClockBreak, SBObjectObsInfo::idx(), SBStationInfo::InvCable, SBAttributed::isAttr(), Mode, SBStationInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBStationInfo::refClock, SBSetUp::scale(), SetUp, StaInf, TmpString, SBStationID::toString(), SBStationInfo::UseLocalClocks, SBStationInfo::UseLocalZenith, SBObjectObsInfo::wrms(), and SBStationInfo::zw().
SBStationInfo* SBStaInfoLI::stationInfo () [inline]
Definition at line 139 of file SbIObsVLBI.H'.
References StaInf.
QString SBStaInfoLI::text (intcol) const [virtual]
Definition at line 502 of file SbIObsVLBI.C'.
References SBObjectObsInfo::aka(), SBStationInfo::ArtMeteo, SBStationInfo::BadCable, SBStationInfo::BadMeteo, BM_GENERAL, BM_PROJECT, SBStationInfo::cl_E(), SBStationInfo::cl_Order(), SBStationInfo::cl_V(), SBStationInfo::clockBreaks(), SBStationInfo::ConstrCoo, SBStationInfo::ConstrVel, SBStationInfo::errZw(), SBStationInfo::EstCoo, SBStationInfo::EstVel, SBStationInfo::HasClockBreak, SBObjectObsInfo::idx(), SBStationInfo::InvCable, SBAttributed::isAttr(), Mode, SBStationInfo::notValid, SBObjectObsInfo::num(), SBObjectObsInfo::procNum(), SBStationInfo::refClock, SBSetUp::scale(), SetUp, StaInf, TmpString, SBStationID::toString(), SBStationInfo::UseLocalClocks, SBStationInfo::UseLocalZenith, SBObjectObsInfo::wrms(), and SBStationInfo::zw().
Member Data Documentation
BrowseMode SBStaInfoLI::Mode [private]
Definition at line 134 of file SbIObsVLBI.H'.
Referenced by key(), SBStaInfoLI(), and text().
SBStationInfo* SBStaInfoLI::StaInf [private]
Definition at line 133 of file SbIObsVLBI.H'.
Referenced by key(), SBStaInfoLI(), stationInfo(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.