SBSTideUT1
NAME
SBSTideUT1 -
SYNOPSIS
#include <SbGeoRefFrame.H>
Classes
struct TableEntry
Public Member Functions
SBSTideUT1 ()
virtual ~SBSTideUT1 ()
virtual QString ClassName () const
virtual void calc (const SBTime &)
virtual double dUT1_UT1S ()
Protected Attributes
double DUT1S
calculated value of (UT1S-UTC)
Static Protected Attributes
static const TableEntry Tab [62]
Detailed Description
Solid tide variations in UT1'. Calculates solid tide variatons in UT1, Dickman, 1993'.
Definition at line 118 of file SbGeoRefFrame.H'.
Constructor & Destructor Documentation
SBSTideUT1::SBSTideUT1 () [inline]"A constructor'. Creates a copy of object'.
Definition at line 132 of file SbGeoRefFrame.H'.
References DUT1S.
virtual SBSTideUT1::~SBSTideUT1 () [inline, virtual]"A destructor'.
Definition at line 134 of file SbGeoRefFrame.H'.
Member Function Documentation
void SBSTideUT1::calc (const SBTime &T) [virtual]"Calculates dUT1S for the time T'.
Definition at line 1094 of file SbGeoRefFrame.C'.
References SBSTideUT1::TableEntry::B, SBSTideUT1::TableEntry::C, DUT1S, SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), SBSTideUT1::TableEntry::N, sincos(), and Tab.
virtual QString SBSTideUT1::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Definition at line 136 of file SbGeoRefFrame.H'.
virtual double SBSTideUT1::dUT1_UT1S () [inline, virtual]"Returns calculated DUT1S'.
Definition at line 140 of file SbGeoRefFrame.H'.
References DUT1S.
Member Data Documentation
double SBSTideUT1::DUT1S [protected]
calculated value of (UT1S-UTC)
Definition at line 126 of file SbGeoRefFrame.H'.
Referenced by calc(), dUT1_UT1S(), and SBSTideUT1().
const SBSTideUT1::TableEntry SBSTideUT1::Tab [static, protected]
Definition at line 127 of file SbGeoRefFrame.H'.
Referenced by calc().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.