SBStationImport
NAME
SBStationImport -
SYNOPSIS
#include <SbIStuffStation.H>
Inherits QWizard'.
Signals
void stationsImported ()
Public Member Functions
SBStationImport (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual QString ClassName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
void setupPage1 ()
void setupPage2_1 ()
void setupPage2_2 ()
void setupPage3 ()
void setupPage4 ()
bool checkFileExists (const QString &)
Private Types
enum FileFormat { F_UNKN = 0, F_ITRF94 = 1, F_ITRF96 = 2, F_ITRF97 = 3, F_ITRF2000 = 4, F_SINEX = 5 }
enum FileType { SITE = 0, DIR = 1, SSC_Z = 2, DORIS = 2, SSC_C = 3, GPS = 3, SSC_B = 4, SLR = 4, SSC_A = 5, VLBI = 5, BLQ = 6 }
enum ImportMode { REPLACE = 0, APP_ONLY = 1, APP_UPD = 2, UPD_ONLY = 3 }
enum ImportFilter { FILT_COO = 0, FILT_TECH = 1, FILT_VLBI = 2, FILT_ALL = 3 }
Private Slots
void accept ()
void formatChanged (int)
void selectDIRfile1994 ()
void selectSITEfile1994 ()
void selectSSCAfile1994 ()
void selectSSCBfile1994 ()
void selectSSCCfile1994 ()
void selectSSCZfile1994 ()
void setDIRstate1994 (bool T)
void setSITEstate1994 (bool T)
void setSSCAstate1994 (bool T)
void setSSCBstate1994 (bool T)
void setSSCCstate1994 (bool T)
void setSSCZstate1994 (bool T)
void fnDIRChanged1994 (const QString &FN_)
void fnSITEChanged1994 (const QString &FN_)
void fnSSCAChanged1994 (const QString &FN_)
void fnSSCBChanged1994 (const QString &FN_)
void fnSSCCChanged1994 (const QString &FN_)
void fnSSCZChanged1994 (const QString &FN_)
void selectDIRfile2000 ()
void selectSITEfile2000 ()
void selectSSCAfile2000 ()
void selectSSCBfile2000 ()
void selectSSCCfile2000 ()
void selectSSCZfile2000 ()
void setDIRstate2000 (bool T)
void setSITEstate2000 (bool T)
void setSSCAstate2000 (bool T)
void setSSCBstate2000 (bool T)
void setSSCCstate2000 (bool T)
void setSSCZstate2000 (bool T)
void fnDIRChanged2000 (const QString &FN_)
void fnSITEChanged2000 (const QString &FN_)
void fnSSCAChanged2000 (const QString &FN_)
void fnSSCBChanged2000 (const QString &FN_)
void fnSSCCChanged2000 (const QString &FN_)
void fnSSCZChanged2000 (const QString &FN_)
void selectNSCfileAux ()
void selectECCfileAux ()
void selectBLQfileAux ()
void setNSCstateAux (bool T)
void setECCstateAux (bool T)
void setBLQstateAux (bool T)
void fnNSCChangedAux (const QString &FN_)
void fnECCChangedAux (const QString &FN_)
void fnBLQChangedAux (const QString &FN_)
void modeChanged (int)
void filterChanged (int)
Private Member Functions
void checkPage2_1State ()
void checkPage2_2State ()
void checkPage3State ()
void selectFile1994 (FileType)
void setState1994 (FileType, bool)
void fileNameChanged1994 (FileType, const QString &)
void selectFile2000 (FileType)
void setState2000 (FileType, bool)
void fileNameChanged2000 (FileType, const QString &)
void selectFileAux (int)
void setStateAux (int, bool)
void fileNameChangedAux (int, const QString &)
void importITRF ()
void loadFile1994 (SB_TRF *, const QString &, FileType)
void loadFile2000 (SB_TRF *, const QString &, FileType)
void applyFilter (ImportFilter, SB_TRF *)
bool loadOLoad (SB_TRF *, QString)
bool loadNScodes (SB_TRF *, const QString &)
bool loadECCdat (SB_TRF *, const QString &)
Private Attributes
FileFormat FFormat
QWidget * page1
QWidget * page2_1
QWidget * page2_2
QWidget * page3
QWidget * page4
const int NumOf1994Files
QString sFileName1994 [6]
QCheckBox * cbFileName1994 [6]
QLineEdit * leFileName1994 [6]
QPushButton * bFile1994 [6]
const int NumOf2000Files
QString sFileName2000 [6]
QCheckBox * cbFileName2000 [6]
QLineEdit * leFileName2000 [6]
QPushButton * bFile2000 [6]
const int NumOfAuxFiles
QString sFileNameAux [3]
QCheckBox * cbFileNameAux [3]
QLineEdit * leFileNameAux [3]
QPushButton * bFileAux [3]
ImportMode Mode
ImportFilter Filter
Detailed Description
Definition at line 260 of file SbIStuffStation.H'.
Member Enumeration Documentation
enum SBStationImport::FileFormat [private]
Enumerator:
F_UNKN
F_ITRF94
F_ITRF96
F_ITRF97
F_ITRF2000
F_SINEX
Definition at line 268 of file SbIStuffStation.H'.
enum SBStationImport::FileType [private]
Enumerator:
SITE
DIR
SSC_Z
DORIS
SSC_C
GPS
SSC_B
SLR
SSC_A
VLBI
BLQ
Definition at line 269 of file SbIStuffStation.H'.
enum SBStationImport::ImportFilter [private]
Enumerator:
FILT_COO
FILT_TECH
FILT_VLBI
FILT_ALL
Definition at line 272 of file SbIStuffStation.H'.
enum SBStationImport::ImportMode [private]
Enumerator:
REPLACE
APP_ONLY
APP_UPD
UPD_ONLY
Definition at line 271 of file SbIStuffStation.H'.
Constructor & Destructor Documentation
SBStationImport::SBStationImport (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1173 of file SbIStuffStation.C'.
References F_UNKN, FFormat, FILT_COO, Filter, Mode, REPLACE, setupPage1(), setupPage2_1(), setupPage2_2(), setupPage3(), and setupPage4().
Member Function Documentation
void SBStationImport::accept () [private, slot]
Definition at line 1657 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, F_ITRF2000, F_ITRF94, F_ITRF96, F_ITRF97, F_SINEX, FFormat, importITRF(), SBLog::INTERFACE, Log, SBLog::write(), and SBLog::WRN.
void SBStationImport::applyFilter (ImportFilterF, SB_TRF *W) [private]
Definition at line 2043 of file SbIStuffStation.C'.
References SBSite::delStation(), FILT_ALL, FILT_COO, FILT_TECH, FILT_VLBI, SBStation::r_first(), SB_TRF::remove(), SBSite::stations(), SBStation::tech(), TECH_UNKN, TECH_VLBI, and v3Zero.
Referenced by importITRF().
bool SBStationImport::checkFileExists (const QString &fil) [protected]
Definition at line 1252 of file SbIStuffStation.C'.
Referenced by checkPage2_1State(), checkPage2_2State(), checkPage3State(), setupPage2_1(), setupPage2_2(), and setupPage3().
void SBStationImport::checkPage2_1State () [private]
Definition at line 1577 of file SbIStuffStation.C'.
References cbFileName1994, checkFileExists(), NumOf1994Files, page2_1, and sFileName1994.
Referenced by fileNameChanged1994(), selectFile1994(), and setState1994().
void SBStationImport::checkPage2_2State () [private]
Definition at line 1612 of file SbIStuffStation.C'.
References cbFileName2000, checkFileExists(), NumOf2000Files, page2_2, and sFileName2000.
Referenced by fileNameChanged2000(), selectFile2000(), and setState2000().
void SBStationImport::checkPage3State () [private]
Definition at line 1648 of file SbIStuffStation.C'.
References cbFileNameAux, checkFileExists(), NumOfAuxFiles, page3, and sFileNameAux.
Referenced by fileNameChangedAux(), selectFileAux(), and setStateAux().
virtual QString SBStationImport::ClassName () const [inline, virtual]
Definition at line 265 of file SbIStuffStation.H'.
Referenced by accept(), importITRF(), loadECCdat(), loadFile1994(), loadFile2000(), loadNScodes(), and loadOLoad().
virtual void SBStationImport::closeEvent (QCloseEvent *) [inline, protected, virtual]
Definition at line 347 of file SbIStuffStation.H'.
void SBStationImport::fileNameChanged1994 (FileTypeType, const QString &) [private]
Definition at line 1571 of file SbIStuffStation.C'.
References checkPage2_1State(), leFileName1994, and sFileName1994.
Referenced by fnDIRChanged1994(), fnSITEChanged1994(), fnSSCAChanged1994(), fnSSCBChanged1994(), fnSSCCChanged1994(), and fnSSCZChanged1994().
void SBStationImport::fileNameChanged2000 (FileTypeType, const QString &) [private]
Definition at line 1606 of file SbIStuffStation.C'.
References checkPage2_2State(), leFileName2000, and sFileName2000.
Referenced by fnDIRChanged2000(), fnSITEChanged2000(), fnSSCAChanged2000(), fnSSCBChanged2000(), fnSSCCChanged2000(), and fnSSCZChanged2000().
void SBStationImport::fileNameChangedAux (intType, const QString &) [private]
Definition at line 1642 of file SbIStuffStation.C'.
References checkPage3State(), leFileNameAux, and sFileNameAux.
Referenced by fnBLQChangedAux(), fnECCChangedAux(), and fnNSCChangedAux().
void SBStationImport::filterChanged (intid) [private, slot]
Definition at line 1237 of file SbIStuffStation.C'.
References FILT_ALL, FILT_COO, FILT_TECH, FILT_VLBI, and Filter.
Referenced by setupPage4().
void SBStationImport::fnBLQChangedAux (const QString &FN_) [inline, private, slot]
Definition at line 340 of file SbIStuffStation.H'.
References fileNameChangedAux().
Referenced by setupPage3().
void SBStationImport::fnDIRChanged1994 (const QString &FN_) [inline, private, slot]
Definition at line 299 of file SbIStuffStation.H'.
References DIR, and fileNameChanged1994().
Referenced by setupPage2_1().
void SBStationImport::fnDIRChanged2000 (const QString &FN_) [inline, private, slot]
Definition at line 322 of file SbIStuffStation.H'.
References DIR, and fileNameChanged2000().
Referenced by setupPage2_2().
void SBStationImport::fnECCChangedAux (const QString &FN_) [inline, private, slot]
Definition at line 339 of file SbIStuffStation.H'.
References fileNameChangedAux().
Referenced by setupPage3().
void SBStationImport::fnNSCChangedAux (const QString &FN_) [inline, private, slot]
Definition at line 338 of file SbIStuffStation.H'.
References fileNameChangedAux().
Referenced by setupPage3().
void SBStationImport::fnSITEChanged1994 (const QString &FN_) [inline, private, slot]
Definition at line 300 of file SbIStuffStation.H'.
References fileNameChanged1994(), and SITE.
Referenced by setupPage2_1().
void SBStationImport::fnSITEChanged2000 (const QString &FN_) [inline, private, slot]
Definition at line 323 of file SbIStuffStation.H'.
References fileNameChanged2000(), and SITE.
Referenced by setupPage2_2().
void SBStationImport::fnSSCAChanged1994 (const QString &FN_) [inline, private, slot]
Definition at line 301 of file SbIStuffStation.H'.
References fileNameChanged1994(), and SSC_A.
Referenced by setupPage2_1().
void SBStationImport::fnSSCAChanged2000 (const QString &FN_) [inline, private, slot]
Definition at line 324 of file SbIStuffStation.H'.
References fileNameChanged2000(), and SSC_A.
Referenced by setupPage2_2().
void SBStationImport::fnSSCBChanged1994 (const QString &FN_) [inline, private, slot]
Definition at line 302 of file SbIStuffStation.H'.
References fileNameChanged1994(), and SSC_B.
Referenced by setupPage2_1().
void SBStationImport::fnSSCBChanged2000 (const QString &FN_) [inline, private, slot]
Definition at line 325 of file SbIStuffStation.H'.
References fileNameChanged2000(), and SSC_B.
Referenced by setupPage2_2().
void SBStationImport::fnSSCCChanged1994 (const QString &FN_) [inline, private, slot]
Definition at line 303 of file SbIStuffStation.H'.
References fileNameChanged1994(), and SSC_C.
Referenced by setupPage2_1().
void SBStationImport::fnSSCCChanged2000 (const QString &FN_) [inline, private, slot]
Definition at line 326 of file SbIStuffStation.H'.
References fileNameChanged2000(), and SSC_C.
Referenced by setupPage2_2().
void SBStationImport::fnSSCZChanged1994 (const QString &FN_) [inline, private, slot]
Definition at line 304 of file SbIStuffStation.H'.
References fileNameChanged1994(), and SSC_Z.
Referenced by setupPage2_1().
void SBStationImport::fnSSCZChanged2000 (const QString &FN_) [inline, private, slot]
Definition at line 327 of file SbIStuffStation.H'.
References fileNameChanged2000(), and SSC_Z.
Referenced by setupPage2_2().
void SBStationImport::formatChanged (intid) [private, slot]
Definition at line 1187 of file SbIStuffStation.C'.
References F_ITRF2000, F_ITRF94, F_ITRF96, F_ITRF97, F_SINEX, F_UNKN, FFormat, page1, page2_1, and page2_2.
Referenced by setupPage1().
void SBStationImport::importITRF () [private]
Definition at line 1691 of file SbIStuffStation.C'.
References SBCatalog::aliasDict(), APP_ONLY, APP_UPD, applyFilter(), cbFileName1994, cbFileName2000, cbFileNameAux, ClassName(), SBCatalog::comment(), SBLog::DBG, F_ITRF2000, F_ITRF94, FFormat, Filter, SB_TRF::find(), SB_TRF::first(), SB_TRF::inSort(), SBLog::INTERFACE, SBCatalog::label(), leFileName1994, leFileName2000, leFileNameAux, loadECCdat(), loadFile1994(), loadFile2000(), loadNScodes(), loadOLoad(), SBSetUp::loadTRF(), Log, Mode, Vector3::module(), SB_TRF::next(), NumOf1994Files, NumOf2000Files, SB_TRF::prepareDicts(), REPLACE, SBSetUp::saveTRF(), SBSolutionName::setAcronym(), SBCatalog::setComment(), SBCatalog::setLabel(), SBSolutionName::setTech(), SetUp, SBSite::setV(), SBSite::setV_err(), SBSolutionName::setYear(), sFileName1994, sFileName2000, sFileNameAux, SBSite::stations(), stationsImported(), TECH_COMBINED, UPD_ONLY, SBSite::updateSite(), v3Zero, SBLog::write(), and SBLog::WRN.
Referenced by accept().
bool SBStationImport::loadECCdat (SB_TRF *W, const QString &FileName) [private]
Definition at line 2574 of file SbIStuffStation.C'.
References ClassName(), SBLog::DBG, SB_TRF::ecc(), SBEcc::importEccDat(), SBLog::IO, Log, SBLog::write(), and SBLog::WRN.
Referenced by importITRF().
void SBStationImport::loadFile1994 (SB_TRF *W, const QString &FileName, FileTypeType) [private]
Definition at line 1955 of file SbIStuffStation.C'.
References BLQ, SBStation::Class_Z, ClassName(), SBLog::DBG, DIR, SBLog::ERR, SBLog::IO, Log, SITE, SSC_A, SSC_B, SSC_C, SSC_Z, SBLog::write(), and SBLog::WRN.
Referenced by importITRF().
void SBStationImport::loadFile2000 (SB_TRF *W, const QString &FileName, FileTypeType) [private]
Definition at line 1999 of file SbIStuffStation.C'.
References BLQ, ClassName(), SBLog::DBG, DIR, SBLog::ERR, SBLog::IO, Log, SITE, SSC_A, SSC_B, SSC_C, SSC_Z, SBLog::write(), and SBLog::WRN.
Referenced by importITRF().
bool SBStationImport::loadNScodes (SB_TRF *W, const QString &FileName) [private]
Definition at line 2450 of file SbIStuffStation.C'.
References SBSite::addStation(), SBCatalog::aliasDict(), ClassName(), SBStation::comments(), SBLog::DATA, SBLog::DBG, SBStation::description(), SBStationID::domeMajor(), SBStationID::domeMinor(), SB_TRF::find(), SBStation::id(), SBLog::INF, SB_TRF::inSort(), SBLog::IO, SBStationID::isValidStr(), Log, SB_TRF::lookupStation(), SBNamed::name(), SBStationID::ptType(), SBStation::setCDP(), SBStation::setCharID(), SBStation::setComments(), SBStation::setDescription(), SBStation::setDomeMinor(), SBStationID::setID(), SBStation::setPointType(), SBStation::setTech(), TECH_VLBI, SBStationID::toString(), SBLog::write(), and SBLog::WRN.
Referenced by importITRF().
bool SBStationImport::loadOLoad (SB_TRF *W, QStringFileName) [private]
Definition at line 2076 of file SbIStuffStation.C'.
References APP_ONLY, APP_UPD, SBOLoadCarrier::calcDistance(), SBSite::calcRLF(), SBStation::CDP(), SBOLoadCarrier::CDP(), SBStation::charID(), SBOLoadCarrier::charID(), ClassName(), SBStation::createOLoad(), SBLog::DBG, SBOLoad::dist(), SBStationID::domeMajor(), SB_TRF::find(), SBStation::hasOwnOLoad, SBStation::id(), SBOLoadCarrier::id(), SBOLoad::info(), SBLog::IO, SBAttributed::isAttr(), SBStationID::isValidId(), SBStation::latitude(), SBSite::latitude(), Log, SBStation::longitude(), SBSite::longitude(), Mode, SBNamed::name(), SBStation::oLoad(), SBSite::oLoad(), SBOLoadCarrier::oLoad(), SBOLoad::P_CDPNum, SBOLoad::P_Distance, SBOLoad::P_Domes, SBOLoad::P_DomesNum, SBOLoad::P_NA, SBOLoad::P_Name, SBOLoad::pickedUp(), SBSite::r(), SBStation::r_first(), REPLACE, SBOLoad::setDist(), SBOLoad::setInfo(), SBSite::setOLoad(), SBOLoad::setPickedUp(), SBSite::stations(), SBStationID::toString(), UPD_ONLY, v3Zero, SBLog::write(), and SBLog::WRN.
Referenced by importITRF().
void SBStationImport::modeChanged (intid) [private, slot]
Definition at line 1222 of file SbIStuffStation.C'.
References APP_ONLY, APP_UPD, Mode, REPLACE, and UPD_ONLY.
Referenced by setupPage4().
void SBStationImport::selectBLQfileAux () [inline, private, slot]
Definition at line 332 of file SbIStuffStation.H'.
References selectFileAux().
Referenced by setupPage3().
void SBStationImport::selectDIRfile1994 () [inline, private, slot]
Definition at line 285 of file SbIStuffStation.H'.
References DIR, and selectFile1994().
Referenced by setupPage2_1().
void SBStationImport::selectDIRfile2000 () [inline, private, slot]
Definition at line 308 of file SbIStuffStation.H'.
References DIR, and selectFile2000().
Referenced by setupPage2_2().
void SBStationImport::selectECCfileAux () [inline, private, slot]
Definition at line 331 of file SbIStuffStation.H'.
References selectFileAux().
Referenced by setupPage3().
void SBStationImport::selectFile1994 (FileTypeType) [private]
Definition at line 1551 of file SbIStuffStation.C'.
References checkPage2_1State(), leFileName1994, SBSetUp::path2ImpITRF(), SetUp, and sFileName1994.
Referenced by selectDIRfile1994(), selectSITEfile1994(), selectSSCAfile1994(), selectSSCBfile1994(), selectSSCCfile1994(), and selectSSCZfile1994().
void SBStationImport::selectFile2000 (FileTypeType) [private]
Definition at line 1586 of file SbIStuffStation.C'.
References checkPage2_2State(), leFileName2000, SBSetUp::path2ImpITRF(), SetUp, and sFileName2000.
Referenced by selectDIRfile2000(), selectSITEfile2000(), selectSSCAfile2000(), selectSSCBfile2000(), selectSSCCfile2000(), and selectSSCZfile2000().
void SBStationImport::selectFileAux (intType) [private]
Definition at line 1621 of file SbIStuffStation.C'.
References checkPage3State(), leFileNameAux, SBSetUp::path2ImpOLoad(), SBSetUp::path2Import(), SetUp, and sFileNameAux.
Referenced by selectBLQfileAux(), selectECCfileAux(), and selectNSCfileAux().
void SBStationImport::selectNSCfileAux () [inline, private, slot]
Definition at line 330 of file SbIStuffStation.H'.
References selectFileAux().
Referenced by setupPage3().
void SBStationImport::selectSITEfile1994 () [inline, private, slot]
Definition at line 286 of file SbIStuffStation.H'.
References selectFile1994(), and SITE.
Referenced by setupPage2_1().
void SBStationImport::selectSITEfile2000 () [inline, private, slot]
Definition at line 309 of file SbIStuffStation.H'.
References selectFile2000(), and SITE.
Referenced by setupPage2_2().
void SBStationImport::selectSSCAfile1994 () [inline, private, slot]
Definition at line 287 of file SbIStuffStation.H'.
References selectFile1994(), and SSC_A.
Referenced by setupPage2_1().
void SBStationImport::selectSSCAfile2000 () [inline, private, slot]
Definition at line 310 of file SbIStuffStation.H'.
References selectFile2000(), and SSC_A.
Referenced by setupPage2_2().
void SBStationImport::selectSSCBfile1994 () [inline, private, slot]
Definition at line 288 of file SbIStuffStation.H'.
References selectFile1994(), and SSC_B.
Referenced by setupPage2_1().
void SBStationImport::selectSSCBfile2000 () [inline, private, slot]
Definition at line 311 of file SbIStuffStation.H'.
References selectFile2000(), and SSC_B.
Referenced by setupPage2_2().
void SBStationImport::selectSSCCfile1994 () [inline, private, slot]
Definition at line 289 of file SbIStuffStation.H'.
References selectFile1994(), and SSC_C.
Referenced by setupPage2_1().
void SBStationImport::selectSSCCfile2000 () [inline, private, slot]
Definition at line 312 of file SbIStuffStation.H'.
References selectFile2000(), and SSC_C.
Referenced by setupPage2_2().
void SBStationImport::selectSSCZfile1994 () [inline, private, slot]
Definition at line 290 of file SbIStuffStation.H'.
References selectFile1994(), and SSC_Z.
Referenced by setupPage2_1().
void SBStationImport::selectSSCZfile2000 () [inline, private, slot]
Definition at line 313 of file SbIStuffStation.H'.
References selectFile2000(), and SSC_Z.
Referenced by setupPage2_2().
void SBStationImport::setBLQstateAux (boolT) [inline, private, slot]
Definition at line 336 of file SbIStuffStation.H'.
References setStateAux().
Referenced by setupPage3().
void SBStationImport::setDIRstate1994 (boolT) [inline, private, slot]
Definition at line 292 of file SbIStuffStation.H'.
References DIR, and setState1994().
Referenced by setupPage2_1().
void SBStationImport::setDIRstate2000 (boolT) [inline, private, slot]
Definition at line 315 of file SbIStuffStation.H'.
References DIR, and setState2000().
Referenced by setupPage2_2().
void SBStationImport::setECCstateAux (boolT) [inline, private, slot]
Definition at line 335 of file SbIStuffStation.H'.
References setStateAux().
Referenced by setupPage3().
void SBStationImport::setNSCstateAux (boolT) [inline, private, slot]
Definition at line 334 of file SbIStuffStation.H'.
References setStateAux().
Referenced by setupPage3().
void SBStationImport::setSITEstate1994 (boolT) [inline, private, slot]
Definition at line 293 of file SbIStuffStation.H'.
References setState1994(), and SITE.
Referenced by setupPage2_1().
void SBStationImport::setSITEstate2000 (boolT) [inline, private, slot]
Definition at line 316 of file SbIStuffStation.H'.
References setState2000(), and SITE.
Referenced by setupPage2_2().
void SBStationImport::setSSCAstate1994 (boolT) [inline, private, slot]
Definition at line 294 of file SbIStuffStation.H'.
References setState1994(), and SSC_A.
Referenced by setupPage2_1().
void SBStationImport::setSSCAstate2000 (boolT) [inline, private, slot]
Definition at line 317 of file SbIStuffStation.H'.
References setState2000(), and SSC_A.
Referenced by setupPage2_2().
void SBStationImport::setSSCBstate1994 (boolT) [inline, private, slot]
Definition at line 295 of file SbIStuffStation.H'.
References setState1994(), and SSC_B.
Referenced by setupPage2_1().
void SBStationImport::setSSCBstate2000 (boolT) [inline, private, slot]
Definition at line 318 of file SbIStuffStation.H'.
References setState2000(), and SSC_B.
Referenced by setupPage2_2().
void SBStationImport::setSSCCstate1994 (boolT) [inline, private, slot]
Definition at line 296 of file SbIStuffStation.H'.
References setState1994(), and SSC_C.
Referenced by setupPage2_1().
void SBStationImport::setSSCCstate2000 (boolT) [inline, private, slot]
Definition at line 319 of file SbIStuffStation.H'.
References setState2000(), and SSC_C.
Referenced by setupPage2_2().
void SBStationImport::setSSCZstate1994 (boolT) [inline, private, slot]
Definition at line 297 of file SbIStuffStation.H'.
References setState1994(), and SSC_Z.
Referenced by setupPage2_1().
void SBStationImport::setSSCZstate2000 (boolT) [inline, private, slot]
Definition at line 320 of file SbIStuffStation.H'.
References setState2000(), and SSC_Z.
Referenced by setupPage2_2().
void SBStationImport::setState1994 (FileTypeType, boolT) [private]
Definition at line 1564 of file SbIStuffStation.C'.
References bFile1994, checkPage2_1State(), and leFileName1994.
Referenced by setDIRstate1994(), setSITEstate1994(), setSSCAstate1994(), setSSCBstate1994(), setSSCCstate1994(), and setSSCZstate1994().
void SBStationImport::setState2000 (FileTypeType, boolT) [private]
Definition at line 1599 of file SbIStuffStation.C'.
References bFile2000, checkPage2_2State(), and leFileName2000.
Referenced by setDIRstate2000(), setSITEstate2000(), setSSCAstate2000(), setSSCBstate2000(), setSSCCstate2000(), and setSSCZstate2000().
void SBStationImport::setStateAux (intType, boolT) [private]
Definition at line 1635 of file SbIStuffStation.C'.
References bFileAux, checkPage3State(), and leFileNameAux.
Referenced by setBLQstateAux(), setECCstateAux(), and setNSCstateAux().
void SBStationImport::setupPage1 () [protected]
Definition at line 1258 of file SbIStuffStation.C'.
References formatChanged(), and page1.
Referenced by SBStationImport().
void SBStationImport::setupPage2_1 () [protected]
Definition at line 1292 of file SbIStuffStation.C'.
References bFile1994, cbFileName1994, checkFileExists(), fnDIRChanged1994(), fnSITEChanged1994(), fnSSCAChanged1994(), fnSSCBChanged1994(), fnSSCCChanged1994(), fnSSCZChanged1994(), leFileName1994, NumOf1994Files, page2_1, SBSetUp::path2ImpITRF(), selectDIRfile1994(), selectSITEfile1994(), selectSSCAfile1994(), selectSSCBfile1994(), selectSSCCfile1994(), selectSSCZfile1994(), setDIRstate1994(), setSITEstate1994(), setSSCAstate1994(), setSSCBstate1994(), setSSCCstate1994(), setSSCZstate1994(), SetUp, and sFileName1994.
Referenced by SBStationImport().
void SBStationImport::setupPage2_2 () [protected]
Definition at line 1367 of file SbIStuffStation.C'.
References bFile2000, cbFileName2000, checkFileExists(), fnDIRChanged2000(), fnSITEChanged2000(), fnSSCAChanged2000(), fnSSCBChanged2000(), fnSSCCChanged2000(), fnSSCZChanged2000(), leFileName2000, NumOf2000Files, page2_2, SBSetUp::path2ImpITRF(), selectDIRfile2000(), selectSITEfile2000(), selectSSCAfile2000(), selectSSCBfile2000(), selectSSCCfile2000(), selectSSCZfile2000(), setDIRstate2000(), setSITEstate2000(), setSSCAstate2000(), setSSCBstate2000(), setSSCCstate2000(), setSSCZstate2000(), SetUp, and sFileName2000.
Referenced by SBStationImport().
void SBStationImport::setupPage3 () [protected]
Definition at line 1443 of file SbIStuffStation.C'.
References bFileAux, cbFileNameAux, checkFileExists(), fnBLQChangedAux(), fnECCChangedAux(), fnNSCChangedAux(), leFileNameAux, NumOfAuxFiles, page3, SBSetUp::path2ImpOLoad(), SBSetUp::path2Import(), selectBLQfileAux(), selectECCfileAux(), selectNSCfileAux(), setBLQstateAux(), setECCstateAux(), setNSCstateAux(), SetUp, and sFileNameAux.
Referenced by SBStationImport().
void SBStationImport::setupPage4 () [protected]
Definition at line 1502 of file SbIStuffStation.C'.
References Filter, filterChanged(), Mode, modeChanged(), and page4.
Referenced by SBStationImport().
void SBStationImport::stationsImported () [signal]
Definition at line 690 of file SbIStuffStation.moc.C'.
Referenced by importITRF().
Member Data Documentation
QPushButton* SBStationImport::bFile1994[6] [private]
Definition at line 372 of file SbIStuffStation.H'.
Referenced by setState1994(), and setupPage2_1().
QPushButton* SBStationImport::bFile2000[6] [private]
Definition at line 381 of file SbIStuffStation.H'.
Referenced by setState2000(), and setupPage2_2().
QPushButton* SBStationImport::bFileAux[3] [private]
Definition at line 389 of file SbIStuffStation.H'.
Referenced by setStateAux(), and setupPage3().
QCheckBox* SBStationImport::cbFileName1994[6] [private]
Definition at line 370 of file SbIStuffStation.H'.
Referenced by checkPage2_1State(), importITRF(), and setupPage2_1().
QCheckBox* SBStationImport::cbFileName2000[6] [private]
Definition at line 379 of file SbIStuffStation.H'.
Referenced by checkPage2_2State(), importITRF(), and setupPage2_2().
QCheckBox* SBStationImport::cbFileNameAux[3] [private]
Definition at line 387 of file SbIStuffStation.H'.
Referenced by checkPage3State(), importITRF(), and setupPage3().
FileFormat SBStationImport::FFormat [private]
Definition at line 359 of file SbIStuffStation.H'.
Referenced by accept(), formatChanged(), importITRF(), and SBStationImport().
ImportFilter SBStationImport::Filter [private]
Definition at line 395 of file SbIStuffStation.H'.
Referenced by filterChanged(), importITRF(), SBStationImport(), and setupPage4().
QLineEdit* SBStationImport::leFileName1994[6] [private]
Definition at line 371 of file SbIStuffStation.H'.
Referenced by fileNameChanged1994(), importITRF(), selectFile1994(), setState1994(), and setupPage2_1().
QLineEdit* SBStationImport::leFileName2000[6] [private]
Definition at line 380 of file SbIStuffStation.H'.
Referenced by fileNameChanged2000(), importITRF(), selectFile2000(), setState2000(), and setupPage2_2().
QLineEdit* SBStationImport::leFileNameAux[3] [private]
Definition at line 388 of file SbIStuffStation.H'.
Referenced by fileNameChangedAux(), importITRF(), selectFileAux(), setStateAux(), and setupPage3().
ImportMode SBStationImport::Mode [private]
Definition at line 394 of file SbIStuffStation.H'.
Referenced by importITRF(), loadOLoad(), modeChanged(), SBStationImport(), and setupPage4().
const int SBStationImport::NumOf1994Files [private]
Definition at line 368 of file SbIStuffStation.H'.
Referenced by checkPage2_1State(), importITRF(), and setupPage2_1().
const int SBStationImport::NumOf2000Files [private]
Definition at line 377 of file SbIStuffStation.H'.
Referenced by checkPage2_2State(), importITRF(), and setupPage2_2().
const int SBStationImport::NumOfAuxFiles [private]
Definition at line 385 of file SbIStuffStation.H'.
Referenced by checkPage3State(), and setupPage3().
QWidget* SBStationImport::page1 [private]
Definition at line 361 of file SbIStuffStation.H'.
Referenced by formatChanged(), and setupPage1().
QWidget* SBStationImport::page2_1 [private]
Definition at line 362 of file SbIStuffStation.H'.
Referenced by checkPage2_1State(), formatChanged(), and setupPage2_1().
QWidget* SBStationImport::page2_2 [private]
Definition at line 363 of file SbIStuffStation.H'.
Referenced by checkPage2_2State(), formatChanged(), and setupPage2_2().
QWidget* SBStationImport::page3 [private]
Definition at line 364 of file SbIStuffStation.H'.
Referenced by checkPage3State(), and setupPage3().
QWidget* SBStationImport::page4 [private]
Definition at line 365 of file SbIStuffStation.H'.
Referenced by setupPage4().
QString SBStationImport::sFileName1994[6] [private]
Definition at line 369 of file SbIStuffStation.H'.
Referenced by checkPage2_1State(), fileNameChanged1994(), importITRF(), selectFile1994(), and setupPage2_1().
QString SBStationImport::sFileName2000[6] [private]
Definition at line 378 of file SbIStuffStation.H'.
Referenced by checkPage2_2State(), fileNameChanged2000(), importITRF(), selectFile2000(), and setupPage2_2().
QString SBStationImport::sFileNameAux[3] [private]
Definition at line 386 of file SbIStuffStation.H'.
Referenced by checkPage3State(), fileNameChangedAux(), importITRF(), selectFileAux(), and setupPage3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.