SBStationInfoList
NAME
SBStationInfoList -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits QList< SBStationInfo >'.
Public Member Functions
virtual QString ClassName () const
virtual SBStationInfo * find (const SBStationID *id)
void dumpUserInfo (QTextStream &ts)
bool restoreUserInfo (QTextStream &)
virtual void clearRMSs ()
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Detailed Description
List of station infos'.
Definition at line 316 of file SbGeoObsVLBI.H'.
Member Function Documentation
virtual QString SBStationInfoList::ClassName () const [inline, virtual]
Definition at line 330 of file SbGeoObsVLBI.H'.
Referenced by restoreUserInfo().
virtual void SBStationInfoList::clearRMSs () [inline, virtual]
Definition at line 339 of file SbGeoObsVLBI.H'.
Referenced by SBProject::clearRMSs(), and SBVLBISession::clearRMSs().
virtual int SBStationInfoList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 319 of file SbGeoObsVLBI.H'.
void SBStationInfoList::dumpUserInfo (QTextStream &ts) [inline]
Definition at line 336 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISession::dumpUserInfo().
virtual SBStationInfo* SBStationInfoList::find (const SBStationID *id) [inline, virtual]
Definition at line 331 of file SbGeoObsVLBI.H'.
Referenced by SBSolutionBrowser::batch4StochStChanged(), collectListOfSINEXParameters(), SBRunManager::fillParameterList(), SBSolution::guessParameterName(), SBObsVLBIEntry::isEligible(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBVLBISession::parseObsDumpString(), SB_TRF::prepareEccs4Session(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), restoreUserInfo(), SBCablesBrowser::SBCablesBrowser(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), SBRunManager::stripTRF(), SBSolutionBrowser::updateTRF(), and SBSolutionBrowser::wLocalStPars().
virtual QDataStream& SBStationInfoList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 327 of file SbGeoObsVLBI.H'.
bool SBStationInfoList::restoreUserInfo (QTextStream &ts)
Definition at line 297 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::DBG, find(), Log, SBStationInfo::restoreUserInfo(), and SBLog::write().
Referenced by SBVLBISession::restoreUserInfo().
virtual QDataStream& SBStationInfoList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 325 of file SbGeoObsVLBI.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.