SBStationList
NAME
SBStationList -
SYNOPSIS
#include <SbGeoStations.H>
Inherits SBNList'.
Public Member Functions
virtual SBStation * first ()
virtual SBStation * next ()
virtual SBStation * at (uint idx)
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Detailed Description
Definition at line 846 of file SbGeoStations.H'.
Member Function Documentation
virtual SBStation* SBStationList::at (uintidx) [inline, virtual]
Definition at line 864 of file SbGeoStations.H'.
Referenced by operator>>().
virtual int SBStationList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 849 of file SbGeoStations.H'.
virtual SBStation* SBStationList::first () [inline, virtual]
Definition at line 862 of file SbGeoStations.H'.
Referenced by SBSite::calcRLF(), SB_TRF::lookupNearest(), and SBSolutionBrowser::updateTRF().
virtual SBStation* SBStationList::next () [inline, virtual]
Definition at line 863 of file SbGeoStations.H'.
Referenced by SBSite::calcRLF(), SB_TRF::lookupNearest(), and SBSolutionBrowser::updateTRF().
virtual QDataStream& SBStationList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 856 of file SbGeoStations.H'.
virtual QDataStream& SBStationList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Reimplemented from SBNList'.
Definition at line 854 of file SbGeoStations.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.