SBStochParameterList
NAME
SBStochParameterList -
SYNOPSIS
#include <SbGeoParameter.H>
Inherits QList< SBStochParameter >'.
Public Member Functions
SBStochParameterList ()
virtual ~SBStochParameterList ()
virtual QString ClassName () const
virtual void inSort (const SBStochParameter *)
virtual bool remove (const QString &)
virtual SBStochParameter * find (const QString &p_) const
virtual int idx (const SBStochParameter *p_)
virtual int idx (const QString &p_)
virtual void clear ()
virtual void report ()
Protected Member Functions
virtual int compareItems (QCollection::Item p1, QCollection::Item p2)
virtual QDataStream & write (QDataStream &s, QCollection::Item E) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &E)
Protected Attributes
QDict< SBStochParameter > * ParByName
Private Member Functions
virtual bool remove (uint idx_)
virtual bool remove ()
Friends
QDataStream & operator<< (QDataStream &, const SBStochParameterList &)
QDataStream & operator>> (QDataStream &, SBStochParameterList &)
Detailed Description
SBStochParameterList'. List of stochastic parameters, ordered by name'.
Definition at line 641 of file SbGeoParameter.H'.
Constructor & Destructor Documentation
SBStochParameterList::SBStochParameterList () [inline]"A constructor'. Creates a copy of the object'.
Definition at line 659 of file SbGeoParameter.H'.
virtual SBStochParameterList::~SBStochParameterList () [inline, virtual]"A destructor'.
Definition at line 666 of file SbGeoParameter.H'.
Member Function Documentation
virtual QString SBStochParameterList::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Definition at line 668 of file SbGeoParameter.H'.
Referenced by inSort(), remove(), and report().
virtual void SBStochParameterList::clear () [inline, virtual]
Definition at line 682 of file SbGeoParameter.H'.
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBSolution::dumpParameters(), SBSolution::loadStcPar(), SBSolutionBrowser::lookupParameters(), SBParameterList::operator>>(), and SBSolution::SBSolution().
virtual int SBStochParameterList::compareItems (QCollection::Itemp1, QCollection::Itemp2) [inline, protected, virtual]
Definition at line 645 of file SbGeoParameter.H'.
References SBNamed::cmp.
virtual SBStochParameter* SBStochParameterList::find (const QString &p_) const [inline, virtual]
Definition at line 677 of file SbGeoParameter.H'.
References SBStochParameter::find().
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBSolution::dumpParameters(), SBVLBIPreProcess::fillObsListView(), SBSolutionBrowser::lookupParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBSolution::submitStochasticParameters(), and SBSolution::updateParameter().
virtual int SBStochParameterList::idx (const SBStochParameter *p_) [inline, virtual]"Returns an index of the parameter in the list
Definition at line 680 of file SbGeoParameter.H'.
virtual int SBStochParameterList::idx (const QString &p_) [inline, virtual]
Definition at line 681 of file SbGeoParameter.H'.
void SBStochParameterList::inSort (const SBStochParameter *p) [virtual]
Definition at line 936 of file SbGeoParameter.C'.
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, SBNamed::name(), ParByName, and SBLog::write().
Referenced by SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBSolution::dumpParameters(), SBSolutionBrowser::lookupParameters(), and SBSolution::submitStochasticParameters().
virtual QDataStream& SBStochParameterList::read (QDataStream &s, QCollection::Item &E) [inline, protected, virtual]
Definition at line 650 of file SbGeoParameter.H'.
bool SBStochParameterList::remove (const QString &key) [virtual]
Definition at line 956 of file SbGeoParameter.C'.
References ClassName(), SBLog::ERR, SBLog::ESTIMATOR, Log, ParByName, remove(), and SBLog::write().
virtual bool SBStochParameterList::remove (uintidx_) [inline, private, virtual]
Definition at line 686 of file SbGeoParameter.H'.
References SBNamed::name().
virtual bool SBStochParameterList::remove () [inline, private, virtual]
Definition at line 689 of file SbGeoParameter.H'.
References SBNamed::name().
Referenced by remove().
void SBStochParameterList::report () [virtual]
Definition at line 970 of file SbGeoParameter.C'.
References ClassName(), SBLog::DBG, SBLog::ESTIMATOR, Log, SBStochParameter::report(), SBLog::STOCHPARS, and SBLog::write().
Referenced by SBSolution::reportStochasticParameters().
virtual QDataStream& SBStochParameterList::write (QDataStream &s, QCollection::ItemE) const [inline, protected, virtual]
Definition at line 648 of file SbGeoParameter.H'.
Friends And Related Function Documentation
QDataStream & operator<< (QDataStream &s, const SBStochParameterList &P) [friend]"Output to the data stream'.
Definition at line 991 of file SbGeoParameter.C'.
QDataStream& operator>> (QDataStream &, SBStochParameterList &) [friend]
Member Data Documentation
QDict<SBStochParameter>* SBStochParameterList::ParByName [protected]
Definition at line 644 of file SbGeoParameter.H'.
Referenced by inSort(), SBParameterList::operator>>(), and remove().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.