SBStationID
NAME
SBStationID -
SYNOPSIS
#include <SbGeoStations.H>
Inherited by SBStationEcc, and SBStationInfo'.
Public Member Functions
SBStationID ()
SBStationID (int DomeMajor_, SBStation::SPointType PtType_, int DomeMinor_)
SBStationID (const SBStationID &ID)
QString ClassName () const
SBStationID & operator= (const SBStationID &ID)
int domeMajor () const
int domeMinor () const
SBStation::SPointType ptType () const
void setDomeMajor (int Dome_)
void setDomeMinor (int Dome_)
void setPtType (SBStation::SPointType PtType_)
bool isValidId () const
void setID (const QString &)
void setID (const SBStationID &ID)
const QString toString () const
Static Public Member Functions
static bool isValidStr (const QString &)
Private Attributes
int DomeMajor
SBStation::SPointType PtType
int DomeMinor
Friends
class SB_TRF
class SBStation
class SBSite
bool operator== (const SBStationID &S1, const SBStationID &S2)
bool operator!= (const SBStationID &S1, const SBStationID &S2)
bool operator< (const SBStationID &S1, const SBStationID &S2)
bool operator> (const SBStationID &S1, const SBStationID &S2)
QDataStream & operator<< (QDataStream &s, const SBStationID &ID)
QDataStream & operator>> (QDataStream &s, SBStationID &ID)
Detailed Description
Definition at line 739 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBStationID::SBStationID () [inline]
Definition at line 749 of file SbGeoStations.H'.
References DomeMajor, DomeMinor, SBStation::Pt_Unkn, and PtType.
SBStationID::SBStationID (intDomeMajor_, SBStation::SPointTypePtType_, intDomeMinor_) [inline]
Definition at line 750 of file SbGeoStations.H'.
References DomeMajor, DomeMinor, and PtType.
SBStationID::SBStationID (const SBStationID &ID) [inline]
Definition at line 752 of file SbGeoStations.H'.
References DomeMajor, DomeMinor, and PtType.
Member Function Documentation
QString SBStationID::ClassName () const [inline]
Reimplemented in SBStationEcc, and SBStationInfo'.
Definition at line 754 of file SbGeoStations.H'.
int SBStationID::domeMajor () const [inline]
Definition at line 759 of file SbGeoStations.H'.
References DomeMajor.
Referenced by SBAploEphem::displacement(), SBAploChunk::entryByID(), SBAploEphem::importHPS(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), operator<<(), and operator>>().
int SBStationID::domeMinor () const [inline]
Definition at line 760 of file SbGeoStations.H'.
References DomeMinor.
Referenced by SBSite::firstUnusedNumber(), SBStationImport::loadNScodes(), and operator>>().
bool SBStationID::isValidId () const [inline]
Definition at line 786 of file SbGeoStations.H'.
References DomeMajor, DomeMinor, SBStation::Pt_Unkn, and PtType.
Referenced by SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBStationImport::loadOLoad(), and SBBaseInfoList::restoreUserInfo().
bool SBStationID::isValidStr (const QString &Str) [static]
Definition at line 1680 of file SbGeoStations.C'.
Referenced by SBSolution::dumpParameters(), SBSolution::guessParameterName(), SBStationImport::loadNScodes(), operator>>(), SBVLBISession::parseObsDumpString(), and setID().
SBStationID& SBStationID::operator= (const SBStationID &ID) [inline]
Definition at line 755 of file SbGeoStations.H'.
References DomeMajor, DomeMinor, and PtType.
SBStation::SPointType SBStationID::ptType () const [inline]
Definition at line 761 of file SbGeoStations.H'.
References PtType.
Referenced by SBEcc::findEcc(), SBStationImport::loadNScodes(), operator>>(), and SBEcc::registerEcc().
void SBStationID::setDomeMajor (intDome_) [inline]
Definition at line 762 of file SbGeoStations.H'.
References DomeMajor.
Referenced by SBStation::id(), operator>>(), and SBOLoadCarrier::SBOLoadCarrier().
void SBStationID::setDomeMinor (intDome_) [inline]
Definition at line 763 of file SbGeoStations.H'.
References DomeMinor.
Referenced by SBStation::id(), and SBOLoadCarrier::SBOLoadCarrier().
void SBStationID::setID (const QString &Str)
Definition at line 1694 of file SbGeoStations.C'.
References DomeMajor, DomeMinor, isValidStr(), SBStation::Pt_Antenna, SBStation::Pt_Marker, SBStation::Pt_Unkn, and PtType.
Referenced by SBSolution::guessParameterName(), SBEcc::importEccDat(), SBStationImport::loadNScodes(), SB_TRF::lookupID(), SB_TRF::lookupStation(), SBRunManager::makeReportMaps(), operator>>(), SB_TRF::prepareEccs4Session(), SBBaseInfoList::restoreUserInfo(), and SBCablesBrowser::SBCablesBrowser().
void SBStationID::setID (const SBStationID &ID) [inline]
Reimplemented in SBStationEcc'.
Definition at line 790 of file SbGeoStations.H'.
References DomeMajor, DomeMinor, and PtType.
void SBStationID::setPtType (SBStation::SPointTypePtType_) [inline]
Definition at line 764 of file SbGeoStations.H'.
References PtType.
Referenced by SBStation::id(), and SBOLoadCarrier::SBOLoadCarrier().
const QString SBStationID::toString () const [inline]
Definition at line 792 of file SbGeoStations.H'.
References DomeMajor, DomeMinor, SBStation::Pt_Antenna, and PtType.
Referenced by SBSite::addStation(), SBSolutionBrowser::batch4StochStChanged(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBStuffStationsEcc::deleteEntry(), SBPlateMotion::displacement(), SBAploEphem::displacement(), SBStuffAplo::draw(), SBStationInfo::dumpUserInfo(), SBAploChunk::entryByID(), SBAploChunk::fillDict(), SBVLBIPreProcess::fillObsListView(), SBEcc::findEcc(), SBSolution::guessParameterName(), SBAploChunk::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBObsVLBIEntry::isEligible(), SBCableLI::key(), SBEccListItem::key(), SBStaInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolutionBrowser::lookupParameters(), SBStationEditor::makeApply(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBRefraction::operator()(), operator<<(), operator>>(), SBSite::prepareDicts(), SBObsVLBIEntry::process(), SBStationEcc::registerEcc(), SBEcc::registerEcc(), SBAploEphem::registerStation(), SBStationInfo::restoreUserInfo(), SBBaseInfoList::restoreUserInfo(), SBCoordsEditor::SBCoordsEditor(), sinex_tro_SiteIDBlock(), SBAploEphem::spline4station(), SBCableLI::text(), SBEccListItem::text(), SBStaInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBPlateMotion::velocity(), and SBStationEditor::wNames().
Friends And Related Function Documentation
bool operator!= (const SBStationID &S1, const SBStationID &S2) [friend]
Definition at line 772 of file SbGeoStations.H'.
bool operator< (const SBStationID &S1, const SBStationID &S2) [friend]
Definition at line 773 of file SbGeoStations.H'.
QDataStream& operator<< (QDataStream &s, const SBStationID &ID) [friend]
Definition at line 800 of file SbGeoStations.H'.
bool operator== (const SBStationID &S1, const SBStationID &S2) [friend]
Definition at line 767 of file SbGeoStations.H'.
bool operator> (const SBStationID &S1, const SBStationID &S2) [friend]
Definition at line 779 of file SbGeoStations.H'.
QDataStream& operator>> (QDataStream &s, SBStationID &ID) [friend]
Definition at line 802 of file SbGeoStations.H'.
friend class SB_TRF [friend]
Definition at line 741 of file SbGeoStations.H'.
friend class SBSite [friend]
Definition at line 743 of file SbGeoStations.H'.
friend class SBStation [friend]
Definition at line 742 of file SbGeoStations.H'.
Member Data Documentation
int SBStationID::DomeMajor [private]
Definition at line 745 of file SbGeoStations.H'.
Referenced by domeMajor(), isValidId(), operator=(), SBStationID(), setDomeMajor(), setID(), and toString().
int SBStationID::DomeMinor [private]
Definition at line 747 of file SbGeoStations.H'.
Referenced by domeMinor(), SBSite::find(), isValidId(), operator=(), SBStationID(), setDomeMinor(), setID(), and toString().
SBStation::SPointType SBStationID::PtType [private]
Definition at line 746 of file SbGeoStations.H'.
Referenced by SBSite::find(), isValidId(), operator=(), ptType(), SBStationID(), setID(), setPtType(), and toString().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.