SBSymMatrix
NAME
SBSymMatrix -
SYNOPSIS
#include <SbVector.H>
Inherits SBUpperMatrix'.
Public Member Functions
SBSymMatrix ()
SBSymMatrix (unsigned int N_, const QString &Name_, bool IsNeedClear=TRUE)
SBSymMatrix (const SBSymMatrix &M)
virtual ~SBSymMatrix ()
virtual QString ClassName () const
SBSymMatrix & operator= (const SBSymMatrix &M)
virtual SBSymMatrix & setCol (unsigned int i, const SBVector &V)
virtual SBMatrix T ()
virtual SBSymMatrix & operator= (double d)
virtual SBSymMatrix & operator+= (const SBSymMatrix &S)
virtual SBSymMatrix & operator-= (const SBSymMatrix &S)
virtual SBSymMatrix & operator*= (double d)
virtual SBSymMatrix & operator/= (double d)
virtual double at (unsigned int, unsigned int) const
unsigned int n () const
virtual double & operator() (unsigned int, unsigned int)
virtual void set (unsigned int, unsigned int, double)
virtual SBVector & setVector (unsigned int, SBVector &)
virtual void clear ()
virtual SBUpperMatrix & operator+= (const SBUpperMatrix &)
virtual SBMatrix & operator+= (const SBMatrix &)
virtual SBUpperMatrix & operator-= (const SBUpperMatrix &)
virtual SBMatrix & operator-= (const SBMatrix &)
virtual unsigned int nRow () const
virtual unsigned int nCol () const
void resize (unsigned int, unsigned int)
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
unsigned int NRow
unsigned int NCol
double ** B
double dTmp
QString Name
Private Member Functions
SBSymMatrix operator~ ()
SBMatrix operator* (const SBMatrix &)
Friends
SBSymMatrix operator/ (const SBSymMatrix &M, double f)
SBSymMatrix operator* (const SBSymMatrix &M, double f)
SBSymMatrix operator* (double f, const SBSymMatrix &M)
SBSymMatrix operator- (const SBSymMatrix &M)
SBSymMatrix operator+ (const SBSymMatrix &, const SBSymMatrix &)
SBSymMatrix operator- (const SBSymMatrix &, const SBSymMatrix &)
SBSymMatrix operator* (const SBSymMatrix &, const SBSymMatrix &)
SBSymMatrix QuadraticForm (const SBSymMatrix &, const SBMatrix &)
SBSymMatrix QuadraticForm (const SBSymMatrix &, const SBUpperMatrix &)
SBVector operator* (const SBSymMatrix &, const SBVector &)
SBVector matT_x_vec (const SBSymMatrix &, const SBVector &)
QDataStream & operator<< (QDataStream &, const SBSymMatrix &)
QDataStream & operator>> (QDataStream &, SBSymMatrix &)
SBUpperMatrix operator/ (const SBUpperMatrix &M, double f)
SBMatrix operator/ (const SBMatrix &M, double f)
SBUpperMatrix operator* (const SBUpperMatrix &M, double f)
SBUpperMatrix operator* (double f, const SBUpperMatrix &M)
SBUpperMatrix operator* (const SBUpperMatrix &, const SBUpperMatrix &)
SBVector operator* (const SBUpperMatrix &, const SBVector &)
SBMatrix operator* (const SBMatrix &M, double f)
SBMatrix operator* (double f, const SBMatrix &M)
SBMatrix operator* (const SBMatrix &, const SBMatrix &)
SBVector operator* (const SBMatrix &, const SBVector &)
SBUpperMatrix operator- (const SBUpperMatrix &M)
SBUpperMatrix operator- (const SBUpperMatrix &, const SBUpperMatrix &)
SBMatrix operator- (const SBMatrix &M)
SBMatrix operator- (const SBMatrix &, const SBMatrix &)
SBUpperMatrix operator+ (const SBUpperMatrix &, const SBUpperMatrix &)
SBMatrix operator+ (const SBMatrix &, const SBMatrix &)
SBUpperMatrix operator~ (const SBUpperMatrix &)
SBSymMatrix matT_x_mat (const SBUpperMatrix &, const SBUpperMatrix &)
SBMatrix matT_x_mat (const SBMatrix &, const SBMatrix &)
SBVector matT_x_vec (const SBUpperMatrix &, const SBVector &)
SBVector matT_x_vec (const SBMatrix &, const SBVector &)
SBSymMatrix & RRT (SBSymMatrix &, const SBUpperMatrix &)
SBSymMatrix & RTR (SBSymMatrix &, const SBUpperMatrix &)
SBVector & Solve (const SBUpperMatrix &, SBVector &, const SBVector &)
QDataStream & operator<< (QDataStream &, const SBUpperMatrix &)
QDataStream & operator<< (QDataStream &, const SBMatrix &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBUpperMatrix &)
QDataStream & operator>> (QDataStream &, SBMatrix &)
QDataStream & operator>> (QDataStream &, SBNamed &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
Detailed Description
Class SBSymMatrix'. This is the symmetric matrix'.
Definition at line 948 of file SbVector.H'.
Constructor & Destructor Documentation
SBSymMatrix::SBSymMatrix () [inline]"A constructor'. Creates an empty matrix (for I/O purposes)'.
Definition at line 956 of file SbVector.H'.
References SBMatrix::B, SBMatrix::dTmp, SBMatrix::NCol, and SBMatrix::NRow.
SBSymMatrix::SBSymMatrix (unsigned intN_, const QString &Name_, boolIsNeedClear = TRUE) [inline]"A constructor'. Creates a copy of object'.
Parameters:
N_ number of rows and columns;
IsNeedClear makes clearing of the allocated memmory;
Definition at line 962 of file SbVector.H'.
SBSymMatrix::SBSymMatrix (const SBSymMatrix &M) [inline]"A constructor'. Creates a copy of object'.
Parameters:
M values of the new object'.
Definition at line 968 of file SbVector.H'.
virtual SBSymMatrix::~SBSymMatrix () [inline, virtual]"A destructor'.
Definition at line 970 of file SbVector.H'.
Member Function Documentation
double SBSymMatrix::at (unsigned inti, unsigned intj) const [inline, virtual]"Returns value of the (i,j)-th element'.
Reimplemented from SBUpperMatrix'.
Definition at line 1055 of file SbVector.H'.
References SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), collectListOfSINEXParameters(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), operator*(), QuadraticForm(), sinex_SolutionMatrixEstimateBlock(), sinex_SolutionNormalEquationMatrixBlock(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), SBSolutionBrowser::updateCRF(), and SBParameterList::updateSolution().
virtual QString SBSymMatrix::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBUpperMatrix'.
Definition at line 972 of file SbVector.H'.
Referenced by at(), operator*(), operator+(), operator-(), operator~(), QuadraticForm(), RRT(), and RTR().
void SBUpperMatrix::clear () [inline, virtual, inherited]"Fills the matrix with zeros'.
Reimplemented from SBMatrix'.
Definition at line 775 of file SbVector.H'.
References SBMatrix::B, and SBMatrix::NCol.
Referenced by SBRunManager::makeReportCRFVariations4IVS(), and SBEstimator::solveStochs().
unsigned int SBUpperMatrix::n () const [inline, inherited]"Returns the number of rows/columns of the matrix'.
Definition at line 646 of file SbVector.H'.
References SBMatrix::nRow().
Referenced by makeHouseholder(), operator*(), operator~(), and SBParameterList::updateSolution().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual unsigned int SBMatrix::nCol () const [inline, virtual, inherited]"Returns number of columns'.
Definition at line 318 of file SbVector.H'.
References SBMatrix::NCol.
Referenced by SBPlotBranch::dataAttr(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBFilterGauss::readDataFile(), SBPlotBranch::setDataAttr(), sinex_SolutionMatrixEstimateBlock(), and sinex_SolutionNormalEquationMatrixBlock().
virtual unsigned int SBMatrix::nRow () const [inline, virtual, inherited]"Returns number of rows'.
Definition at line 316 of file SbVector.H'.
References SBMatrix::NRow.
Referenced by SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBPlotArea::getLimits(), makeHouseholder(), SBUpperMatrix::n(), QuadraticForm(), and SBFilterGauss::readDataFile().
double & SBUpperMatrix::operator() (unsigned inti, unsigned intj) [inline, virtual, inherited]"Returns reference to the (i,j)-th element'.
Reimplemented from SBMatrix'.
Definition at line 782 of file SbVector.H'.
References SBMatrix::B, SBUpperMatrix::ClassName(), SBMatrix::dTmp, SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBMatrix SBSymMatrix::operator* (const SBMatrix &) [inline, private]
Definition at line 1034 of file SbVector.H'.
References SBMatrix::SBMatrix().
virtual SBSymMatrix& SBSymMatrix::operator*= (doubled) [inline, virtual]"Multiplies the matrix by a double'.
Reimplemented from SBUpperMatrix'.
Definition at line 997 of file SbVector.H'.
SBMatrix & SBMatrix::operator+= (const SBMatrix &M) [inline, virtual, inherited]"Adds a matrix to the matrix'.
Definition at line 517 of file SbVector.H'.
References SBMatrix::B, SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix & SBUpperMatrix::operator+= (const SBUpperMatrix &M) [inline, virtual, inherited]"Adds a matrix to the matrix'.
Definition at line 856 of file SbVector.H'.
References SBMatrix::B, SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
virtual SBSymMatrix& SBSymMatrix::operator+= (const SBSymMatrix &S) [inline, virtual]"Adds a matrix to the matrix'.
Definition at line 991 of file SbVector.H'.
SBMatrix & SBMatrix::operator-= (const SBMatrix &M) [inline, virtual, inherited]"Substracts a matrix from the matrix'.
Definition at line 534 of file SbVector.H'.
References SBMatrix::B, SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix & SBUpperMatrix::operator-= (const SBUpperMatrix &M) [inline, virtual, inherited]"Substracts a matrix from the matrix'.
Definition at line 873 of file SbVector.H'.
References SBMatrix::B, SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
virtual SBSymMatrix& SBSymMatrix::operator-= (const SBSymMatrix &S) [inline, virtual]"Substracts a matrix from the matrix'.
Definition at line 994 of file SbVector.H'.
virtual SBSymMatrix& SBSymMatrix::operator/= (doubled) [inline, virtual]"Divides the matrix by a double'.
Reimplemented from SBUpperMatrix'.
Definition at line 1000 of file SbVector.H'.
SBSymMatrix& SBSymMatrix::operator= (const SBSymMatrix &M) [inline]"Assign the matix to another one'.
Definition at line 977 of file SbVector.H'.
Referenced by operator=().
virtual SBSymMatrix& SBSymMatrix::operator= (doubled) [inline, virtual]"Fills the matix with the double'.
Reimplemented from SBUpperMatrix'.
Definition at line 988 of file SbVector.H'.
References operator=().
SBSymMatrix SBSymMatrix::operator~ () [inline, private]"Returns inversed matrix'. This is time consumed operation, shouldn't use in ordinary operations'. M*~M==~M*M==1 (original matrix doesn't change)'.
Reimplemented from SBMatrix'.
Definition at line 1028 of file SbVector.H'.
References ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), and SBLog::write().
void SBMatrix::resize (unsigned intNRow_, unsigned intNCol_) [inherited]"Changes the size of a matrix'.
Definition at line 66 of file SbVector.C'.
References SBMatrix::B, SBMatrix::dTmp, SBMatrix::NCol, and SBMatrix::NRow.
Referenced by SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), and SBEOP::setPtNum().
void SBUpperMatrix::set (unsigned inti, unsigned intj, doubleA_) [inline, virtual, inherited]"Sets the (i,j)-th element to the double'.
Reimplemented from SBMatrix'.
Definition at line 808 of file SbVector.H'.
References SBMatrix::B, SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), collectListOfSINEXParameters(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), makeHouseholder(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBEstimator::prepare4Local(), SBEstimator::prepare4Run(), SBEstimator::propagateStochasticPars(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), and writeNormalEquationSystem().
virtual SBSymMatrix& SBSymMatrix::setCol (unsigned inti, const SBVector &V) [inline, virtual]"Sets i-th column to Vector'.
Reimplemented from SBUpperMatrix'.
Definition at line 980 of file SbVector.H'.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
SBVector & SBUpperMatrix::setVector (unsigned intN_, SBVector &V) [inline, virtual, inherited]"Assign to the vector the values of matrix'es column'.
Reimplemented from SBMatrix'.
Definition at line 923 of file SbVector.H'.
References SBVector::B, SBMatrix::B, SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBVector::N, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
virtual SBMatrix SBSymMatrix::T () [inline, virtual]"Returns transposed matrix (original matrix doesn't change)'.
Reimplemented from SBUpperMatrix'.
Definition at line 986 of file SbVector.H'.
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
SBMatrix matT_x_mat (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns a product of a transposed matrix and a matrix'. This function is equal to `M1'.T()*M2', but implements a more efficient realization'.
Definition at line 116 of file SbVector.C'.
SBSymMatrix matT_x_mat (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend, inherited]"Returns a product of a transposed matrix and a matrix'. This function is equal to `M1'.T()*M2', but implements a more efficient realization'.
Definition at line 195 of file SbVector.C'.
SBVector matT_x_vec (const SBMatrix &M, const SBVector &V) [friend, inherited]"Returns a product of a transposed matrix and a vector'. This function is equal to `M'.T()*V', but implements a more efficient realization'.
Definition at line 419 of file SbVector.C'.
SBVector matT_x_vec (const SBUpperMatrix &M, const SBVector &V) [friend, inherited]"Returns a product of a transposed upper triangular matrix and a vector'. This function is equal to `M'.T()*V', but implements a more efficient realization'.
Definition at line 219 of file SbVector.C'.
SBVector matT_x_vec (const SBSymMatrix &, const SBVector &) [friend]
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
SBMatrix operator* (const SBMatrix &M, doublef) [friend, inherited]"Returns matrix multiplied by float'.
Definition at line 356 of file SbVector.H'.
SBMatrix operator* (doublef, const SBMatrix &M) [friend, inherited]"Returns matrix multiplied by float'.
Definition at line 358 of file SbVector.H'.
SBMatrix operator* (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns product of two matrices'.
Definition at line 98 of file SbVector.C'.
SBVector operator* (const SBMatrix &M, const SBVector &V) [friend, inherited]"Returns a product of a matrix and a vector'.
Definition at line 397 of file SbVector.C'.
SBUpperMatrix operator* (const SBUpperMatrix &M, doublef) [friend, inherited]"Returns matrix multiplied by float'.
Definition at line 682 of file SbVector.H'.
SBUpperMatrix operator* (doublef, const SBUpperMatrix &M) [friend, inherited]"Returns matrix multiplied by float'.
Definition at line 684 of file SbVector.H'.
SBUpperMatrix operator* (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend, inherited]"Returns product of two matrices'.
Definition at line 177 of file SbVector.C'.
SBVector operator* (const SBUpperMatrix &, const SBVector &) [friend, inherited]
SBSymMatrix operator* (const SBSymMatrix &M, doublef) [friend]"Returns matrix multiplied by float'.
Definition at line 1010 of file SbVector.H'.
SBSymMatrix operator* (doublef, const SBSymMatrix &M) [friend]"Returns matrix multiplied by float'.
Definition at line 1012 of file SbVector.H'.
SBSymMatrix operator* (const SBSymMatrix &M1, const SBSymMatrix &M2) [friend]"Returns product of two matrices'.
Definition at line 445 of file SbVector.C'.
SBVector operator* (const SBSymMatrix &, const SBVector &) [friend]
SBMatrix operator+ (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns a sum of two matrices'.
Definition at line 1133 of file SbVector.H'.
SBUpperMatrix operator+ (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend, inherited]"Returns a sum of two matrices'.
Definition at line 1167 of file SbVector.H'.
SBSymMatrix operator+ (const SBSymMatrix &M1, const SBSymMatrix &M2) [friend]"Returns a sum of two matrices'.
Definition at line 1201 of file SbVector.H'.
SBMatrix operator- (const SBMatrix &M) [friend, inherited]"Returns matrix with reversed sign'.
Definition at line 360 of file SbVector.H'.
SBMatrix operator- (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns a difference of two matrices'.
Definition at line 1146 of file SbVector.H'.
SBUpperMatrix operator- (const SBUpperMatrix &M) [friend, inherited]"Returns matrix with reversed sign'.
Definition at line 686 of file SbVector.H'.
SBUpperMatrix operator- (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend, inherited]"Returns a difference of two matrices'.
Definition at line 1180 of file SbVector.H'.
SBSymMatrix operator- (const SBSymMatrix &M) [friend]"Returns matrix with reversed sign'.
Definition at line 1014 of file SbVector.H'.
SBSymMatrix operator- (const SBSymMatrix &M1, const SBSymMatrix &M2) [friend]"Returns a difference of two matrices'.
Definition at line 1214 of file SbVector.H'.
SBMatrix operator/ (const SBMatrix &M, doublef) [friend, inherited]"Returns matrix divided by float'.
Definition at line 354 of file SbVector.H'.
SBUpperMatrix operator/ (const SBUpperMatrix &M, doublef) [friend, inherited]"Returns matrix divided by float'.
Definition at line 680 of file SbVector.H'.
SBSymMatrix operator/ (const SBSymMatrix &M, doublef) [friend]"Returns matrix divided by float'.
Definition at line 1008 of file SbVector.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBMatrix &M) [friend, inherited]
Definition at line 135 of file SbVector.C'.
QDataStream& operator<< (QDataStream &s, const SBUpperMatrix &M) [friend, inherited]
Definition at line 352 of file SbVector.C'.
QDataStream& operator<< (QDataStream &s, const SBSymMatrix &M) [friend]
Definition at line 532 of file SbVector.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBMatrix &M) [friend, inherited]
Definition at line 143 of file SbVector.C'.
QDataStream& operator>> (QDataStream &s, SBUpperMatrix &M) [friend, inherited]
Definition at line 360 of file SbVector.C'.
QDataStream& operator>> (QDataStream &s, SBSymMatrix &M) [friend]
Definition at line 537 of file SbVector.C'.
SBUpperMatrix operator~ (const SBUpperMatrix &R) [friend, inherited]"Returns inversed matrix'. This is time consumed operation, shouldn't use in ordinary operations'. M*~M==~M*M==1 (original matrix doesn't change)'.
Definition at line 323 of file SbVector.C'.
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBMatrix &A) [friend]"Calculates the product of `A*P*A'.T()''. Returns symmetric matrix'.
Reimplemented from SBMatrix'.
Definition at line 468 of file SbVector.C'.
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBUpperMatrix &R) [friend]"Calculates the product of `A*P*A'.T()''. Returns symmetric matrix'.
Reimplemented from SBUpperMatrix'.
Definition at line 500 of file SbVector.C'.
SBSymMatrix& RRT (SBSymMatrix &M, const SBUpperMatrix &R) [friend, inherited]"Returns a product of a `R*R'.T()' -- a matrix and its transposed one'. This function is equal to `M1*M1'.T()', but [should] implements a more efficient realization'.
Definition at line 246 of file SbVector.C'.
SBSymMatrix& RTR (SBSymMatrix &M, const SBUpperMatrix &R) [friend, inherited]"Returns a product of a `R'.T()*R' -- a transposed matrix and the one'. This function is equal to `M1'.T()*M1', but [should] implements a more efficient realization'.
Definition at line 268 of file SbVector.C'.
SBVector& Solve (const SBUpperMatrix &R, SBVector &x, const SBVector &z) [friend, inherited]"Solves an equation `R*x=z''. Returns vector x'. The order of arguments is the same as in the equation: R, x and z'.
Definition at line 290 of file SbVector.C'.
Member Data Documentation
double** SBMatrix::B [protected, inherited]
Definition at line 282 of file SbVector.H'.
Referenced by SBMatrix::at(), SBUpperMatrix::at(), at(), SBMatrix::clear(), SBUpperMatrix::clear(), matT_x_mat(), SBMatrix::operator()(), SBUpperMatrix::operator()(), operator*(), SBMatrix::operator*=(), SBUpperMatrix::operator*=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBMatrix::operator/=(), SBUpperMatrix::operator/=(), operator<<(), SBMatrix::operator=(), SBUpperMatrix::operator=(), operator>>(), SBMatrix::resize(), SBMatrix::SBMatrix(), SBSymMatrix(), SBUpperMatrix::SBUpperMatrix(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBMatrix::setVector(), SBUpperMatrix::setVector(), SBMatrix::T(), SBUpperMatrix::T(), SBMatrix::~SBMatrix(), and SBUpperMatrix::~SBUpperMatrix().
double SBMatrix::dTmp [protected, inherited]
Definition at line 283 of file SbVector.H'.
Referenced by SBMatrix::operator()(), SBUpperMatrix::operator()(), SBMatrix::resize(), SBMatrix::SBMatrix(), SBSymMatrix(), and SBUpperMatrix::SBUpperMatrix().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
unsigned int SBMatrix::NCol [protected, inherited]
Definition at line 281 of file SbVector.H'.
Referenced by SBMatrix::at(), SBUpperMatrix::at(), at(), SBMatrix::clear(), SBUpperMatrix::clear(), matT_x_mat(), SBMatrix::nCol(), SBMatrix::operator()(), SBUpperMatrix::operator()(), operator*(), SBMatrix::operator*=(), SBUpperMatrix::operator*=(), operator+(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBMatrix::operator/=(), SBUpperMatrix::operator/=(), operator<<(), SBMatrix::operator=(), SBUpperMatrix::operator=(), operator>>(), QuadraticForm(), SBMatrix::resize(), RRT(), RTR(), SBMatrix::SBMatrix(), SBSymMatrix(), SBUpperMatrix::SBUpperMatrix(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBMatrix::setVector(), SBUpperMatrix::setVector(), SBMatrix::T(), SBUpperMatrix::T(), SBMatrix::~SBMatrix(), and SBUpperMatrix::~SBUpperMatrix().
unsigned int SBMatrix::NRow [protected, inherited]
Definition at line 280 of file SbVector.H'.
Referenced by SBMatrix::at(), SBUpperMatrix::at(), at(), SBMatrix::clear(), matT_x_mat(), SBMatrix::nRow(), SBMatrix::operator()(), SBUpperMatrix::operator()(), operator*(), SBMatrix::operator*=(), operator+(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBMatrix::operator/=(), operator<<(), SBMatrix::operator=(), SBUpperMatrix::operator=(), operator>>(), QuadraticForm(), SBMatrix::resize(), RRT(), RTR(), SBMatrix::SBMatrix(), SBSymMatrix(), SBUpperMatrix::SBUpperMatrix(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBMatrix::T(), and SBUpperMatrix::T().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.