SBTabDialog
NAME
SBTabDialog -
SYNOPSIS
#include <SbInterface.H>
Inherits QTabDialog'.
Inherited by SBModelEditor, SBObsVLBIStatBrowser, SBParametersEditor, SBProjectEdit, SBSetupDialog, SBSiteEditor, SBSolutionBrowser, SBSourceEditor, SBStationEditor, and SBVLBISessionEditor'.
Public Member Functions
SBTabDialog (QWidget *parent_, const char *name_, bool modal_, WFlags f)
SBTabDialog ()
Protected Slots
virtual void makeApply ()
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual void acquireData ()
Detailed Description
Definition at line 68 of file SbInterface.H'.
Constructor & Destructor Documentation
SBTabDialog::SBTabDialog (QWidget *parent_, const char *name_, boolmodal_, WFlagsf) [inline]
Definition at line 72 of file SbInterface.H'.
SBTabDialog::SBTabDialog () [inline]
Definition at line 74 of file SbInterface.H'.
Member Function Documentation
virtual void SBTabDialog::acquireData () [inline, protected, virtual]
Reimplemented in SBVLBISessionEditor, SBStationEditor, SBSiteEditor, SBParametersEditor, SBSourceEditor, SBModelEditor, SBProjectEdit, and SBSetupDialog'.
Definition at line 91 of file SbInterface.H'.
Referenced by done(), and makeApply().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References acquireData().
virtual void SBTabDialog::makeApply () [inline, protected, virtual, slot]
Reimplemented in SBVLBISessionEditor, SBStationEditor, SBSiteEditor, SBParametersEditor, SBSourceEditor, SBModelEditor, SBProjectEdit, and SBSetupDialog'.
Definition at line 78 of file SbInterface.H'.
References acquireData().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.