SBTestEphem
NAME
SBTestEphem -
SYNOPSIS
#include <SbITest.H>
Inherits SBTest'.
Public Member Functions
SBTestEphem (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBTestEphem ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual QWidget * auxWidgetRt (QWidget *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
QString str
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Private Types
enum EUnits { U_KM = 0, U_AU = 1, U_U = 2 }
enum EFrameType { FT_ORTH = 0, FT_SPH = 1 }
enum EFrame { F_CRS = 0, F_TRS = 1 }
Private Slots
virtual void recalc ()
void originChanged (int)
void unitChanged (int)
void frameTypeChanged (int)
void frameChanged (int)
Private Member Functions
virtual QWidget * createWidget4Test (QWidget *)
void displayCoo ()
Private Attributes
double Scale [3]
EUnits Units
EFrame Frame
EFrameType FrameType
SBEphem * Weph
SBFrame * Wref
const Vector3 * Origin
const Matrix3 * RF
Vector3 v0
Matrix3 m0
QLabel * LCoo [11][3]
QLabel * LCLabel [3]
Detailed Description
Definition at line 252 of file SbITest.H'.
Member Enumeration Documentation
enum SBTestEphem::EFrame [private]
Enumerator:
F_CRS
F_TRS
Definition at line 272 of file SbITest.H'.
enum SBTestEphem::EFrameType [private]
Enumerator:
FT_ORTH
FT_SPH
Definition at line 271 of file SbITest.H'.
enum SBTestEphem::EUnits [private]
Enumerator:
U_KM
U_AU
U_U
Definition at line 270 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestEphem::SBTestEphem (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 857 of file SbITest.C'.
References SBEphem::au(), Config, SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBConfig::EM_LEDE200, SBConfig::EM_LEDE403, SBConfig::EM_LEDE405, SBConfig::ephemModel(), F_CRS, Frame, FrameType, FT_ORTH, m0, SBNamed::name(), Origin, RF, Scale, SBConfig::STR_Classic, SBConfig::STR_NRO, SBConfig::sysTransform(), SBTest::TFinis, SBEphem::tFinis(), SBTest::TStart, SBEphem::tStart(), U_KM, Units, v0, Weph, and Wref.
SBTestEphem::~SBTestEphem () [virtual]
Definition at line 894 of file SbITest.C'.
References Weph, and Wref.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual QWidget* SBTest::auxWidgetRt (QWidget *) [inline, protected, virtual, inherited]
Reimplemented in SBTestAPLoad, SBTestPolarTides, SBTestOceanTides, SBTestSolidTides, SBTestDiurnEOP, and SBTestEOP'.
Definition at line 81 of file SbITest.H'.
Referenced by SBTest::createWidgets().
virtual QString SBTestEphem::ClassName () const [inline, virtual]
Reimplemented from SBTest'.
Definition at line 259 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestEphem::createWidget4Test (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 900 of file SbITest.C'.
References Vector3::at(), SBEphem::body(), SBEphem::calc(), SBTest::Date, frameChanged(), frameTypeChanged(), LCLabel, LCoo, SBNamed::name(), originChanged(), SBCelestBody::r(), Scale, SBTest::str, unitChanged(), Units, and Weph.
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides().
void SBTestEphem::displayCoo () [private]
Definition at line 1053 of file SbITest.C'.
References Vector3::at(), SBEphem::body(), F_CRS, Frame, FrameType, FT_ORTH, FT_SPH, Vector3::lambda(), LCLabel, LCoo, Vector3::module(), Origin, Vector3::phi(), SBCelestBody::r(), rad2dmsStr(), rad2hmsStr(), RF, Scale, SBTest::str, Units, and Weph.
Referenced by frameChanged(), frameTypeChanged(), originChanged(), recalc(), and unitChanged().
void SBTestEphem::frameChanged (inti) [private, slot]
Definition at line 1012 of file SbITest.C'.
References SBFrame::calc(), SBTest::Date, displayCoo(), F_CRS, F_TRS, Frame, m0, RF, and Wref.
Referenced by createWidget4Test().
void SBTestEphem::frameTypeChanged (inti) [private, slot]
Definition at line 1006 of file SbITest.C'.
References displayCoo(), and FrameType.
Referenced by createWidget4Test().
void SBTestEphem::originChanged (inti) [private, slot]
Definition at line 1028 of file SbITest.C'.
References SBEphem::body(), displayCoo(), Origin, SBCelestBody::r(), v0, and Weph.
Referenced by createWidget4Test().
void SBTestEphem::recalc () [private, virtual, slot]
Reimplemented from SBTest'.
Definition at line 1040 of file SbITest.C'.
References SBEphem::calc(), SBFrame::calc(), SBTest::Date, SBMJD::date(), displayCoo(), SBFrame::eop(), SBEphem::isOK(), SBEOP::prepare4Date(), SBEOP::t_4Prepare(), Weph, and Wref.
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
void SBTestEphem::unitChanged (inti) [private, slot]
Definition at line 1034 of file SbITest.C'.
References displayCoo(), and Units.
Referenced by createWidget4Test().
Member Data Documentation
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
EFrame SBTestEphem::Frame [private]
Definition at line 275 of file SbITest.H'.
Referenced by displayCoo(), frameChanged(), and SBTestEphem().
EFrameType SBTestEphem::FrameType [private]
Definition at line 276 of file SbITest.H'.
Referenced by displayCoo(), frameTypeChanged(), and SBTestEphem().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest().
QLabel* SBTestEphem::LCLabel[3] [private]
Definition at line 285 of file SbITest.H'.
Referenced by createWidget4Test(), and displayCoo().
QLabel* SBTestEphem::LCoo[11][3] [private]
Definition at line 284 of file SbITest.H'.
Referenced by createWidget4Test(), and displayCoo().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
Matrix3 SBTestEphem::m0 [private]
Definition at line 282 of file SbITest.H'.
Referenced by frameChanged(), and SBTestEphem().
const Vector3* SBTestEphem::Origin [private]
Definition at line 279 of file SbITest.H'.
Referenced by displayCoo(), originChanged(), and SBTestEphem().
const Matrix3* SBTestEphem::RF [private]
Definition at line 280 of file SbITest.H'.
Referenced by displayCoo(), frameChanged(), and SBTestEphem().
double SBTestEphem::Scale[3] [private]
Definition at line 273 of file SbITest.H'.
Referenced by createWidget4Test(), displayCoo(), and SBTestEphem().
QString SBTest::str [protected, inherited]
Reimplemented in SBTestFrame, SBTestNutation, SBTestPrecession, and SBTestMatrix'.
Definition at line 61 of file SbITest.H'.
Referenced by createWidget4Test(), SBTest::createWidgets(), displayCoo(), and SBTest::recalc().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
EUnits SBTestEphem::Units [private]
Definition at line 274 of file SbITest.H'.
Referenced by createWidget4Test(), displayCoo(), SBTestEphem(), and unitChanged().
Vector3 SBTestEphem::v0 [private]
Definition at line 281 of file SbITest.H'.
Referenced by originChanged(), and SBTestEphem().
SBEphem* SBTestEphem::Weph [private]
Definition at line 277 of file SbITest.H'.
Referenced by createWidget4Test(), displayCoo(), originChanged(), recalc(), SBTestEphem(), and ~SBTestEphem().
SBFrame* SBTestEphem::Wref [private]
Definition at line 278 of file SbITest.H'.
Referenced by frameChanged(), recalc(), SBTestEphem(), and ~SBTestEphem().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.