SBTestNutation
NAME
SBTestNutation -
SYNOPSIS
#include <SbITest.H>
Inherits SBTestMatrix'.
Public Member Functions
SBTestNutation (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBTestNutation ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual QWidget * createMatrixWidget (QWidget *)
virtual void closeEvent (QCloseEvent *)
virtual QWidget * auxWidgetRt (QWidget *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
Matrix3 * Mat
QLabel * LMat [3][3]
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Private Slots
virtual void recalc ()
Private Member Functions
virtual QWidget * createWidget4Test (QWidget *)
void displayValues ()
Private Attributes
QString str
SBNutation * Nut
SBTime * Time
SBEOP * Weop
QLabel * LThDeltaPsi
QLabel * LThDeltaEps
QLabel * LDeltaPsi
QLabel * LDeltaEps
QLabel * LMeanEps
QLabel * LTrueEps
QLabel * LEqEquinox
QLabel * LGeodesicNutation
QLabel * LTT
Detailed Description
Definition at line 160 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestNutation::SBTestNutation (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 448 of file SbITest.C'.
References Config, SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBConfig::eopNumIntrplPoints(), SBSetUp::loadEOP(), SBTestMatrix::Mat, SBNamed::name(), SBConfig::NM_IAU1980, SBConfig::NM_IAU2000, Nut, SBConfig::nutModel(), SBTime::setEOP(), SBEOP::setPtNum(), SetUp, SBTest::TFinis, SBEOP::tFinis(), SBNutation::theory(), Time, SBTest::TStart, SBEOP::tStart(), and Weop.
SBTestNutation::~SBTestNutation () [virtual]
Definition at line 483 of file SbITest.C'.
References Nut, Time, and Weop.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual QWidget* SBTest::auxWidgetRt (QWidget *) [inline, protected, virtual, inherited]
Reimplemented in SBTestAPLoad, SBTestPolarTides, SBTestOceanTides, SBTestSolidTides, SBTestDiurnEOP, and SBTestEOP'.
Definition at line 81 of file SbITest.H'.
Referenced by SBTest::createWidgets().
virtual QString SBTestNutation::ClassName () const [inline, virtual]
Reimplemented from SBTestMatrix'.
Definition at line 167 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestMatrix::createMatrixWidget (QWidget *parent) [protected, virtual, inherited]
Definition at line 299 of file SbITest.C'.
References Matrix3::at(), SBTestMatrix::LMat, SBTestMatrix::Mat, and SBTestMatrix::str.
Referenced by SBTestPrecession::createWidget4Test(), createWidget4Test(), and SBTestFrame::createWidget4Test().
QWidget * SBTestNutation::createWidget4Test (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 490 of file SbITest.C'.
References SBTestMatrix::createMatrixWidget(), SBTest::Date, SBNutThGeneral::deltaEps(), SBNutation::deltaEps(), SBNutThGeneral::deltaPsi(), SBNutation::deltaPsi(), SBNutation::eqEquinox(), SBMJD::F_Short, SBNutation::geodesicNutation(), SBEOP::interpolateEOPs(), LDeltaEps, LDeltaPsi, LEqEquinox, LGeodesicNutation, LMeanEps, LThDeltaEps, LThDeltaPsi, LTrueEps, LTT, SBNutation::meanEps(), Nut, SBEOP::prepare4Date(), rad2dmsStr(), RAD2SEC, SBTime::setUTC(), str, SBNutation::theory(), Time, SBNutation::trueEps(), and Weop.
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides().
void SBTestNutation::displayValues () [private]
Reimplemented from SBTestMatrix'.
Definition at line 605 of file SbITest.C'.
References SBNutThGeneral::deltaEps(), SBNutation::deltaEps(), SBNutThGeneral::deltaPsi(), SBNutation::deltaPsi(), SBNutation::eqEquinox(), SBMJD::F_Short, SBNutation::geodesicNutation(), LDeltaEps, LDeltaPsi, LEqEquinox, LGeodesicNutation, LMeanEps, LThDeltaEps, LThDeltaPsi, LTrueEps, LTT, SBNutation::meanEps(), Nut, rad2dmsStr(), RAD2SEC, str, SBNutation::theory(), Time, SBMJD::toString(), SBNutation::trueEps(), and SBTime::TT().
Referenced by recalc().
void SBTestNutation::recalc () [private, virtual, slot]
Reimplemented from SBTest'.
Definition at line 595 of file SbITest.C'.
References SBTest::Date, displayValues(), SBEOP::interpolateEOPs(), SBEOP::prepare4Date(), SBTime::setUTC(), Time, and Weop.
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
Member Data Documentation
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), recalc(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTestNutation::LDeltaEps [private]
Definition at line 181 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestNutation::LDeltaPsi [private]
Definition at line 180 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestNutation::LEqEquinox [private]
Definition at line 184 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestNutation::LGeodesicNutation [private]
Definition at line 185 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestMatrix::LMat[3][3] [protected, inherited]
Definition at line 108 of file SbITest.H'.
Referenced by SBTestMatrix::createMatrixWidget(), and SBTestMatrix::displayValues().
QLabel* SBTestNutation::LMeanEps [private]
Definition at line 182 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
QLabel* SBTestNutation::LThDeltaEps [private]
Definition at line 179 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestNutation::LThDeltaPsi [private]
Definition at line 178 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestNutation::LTrueEps [private]
Definition at line 183 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestNutation::LTT [private]
Definition at line 186 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
Matrix3* SBTestMatrix::Mat [protected, inherited]
Definition at line 103 of file SbITest.H'.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), SBTestFrame::SBTestFrame(), SBTestMatrix::SBTestMatrix(), SBTestNutation(), and SBTestPrecession::SBTestPrecession().
SBNutation* SBTestNutation::Nut [private]
Definition at line 174 of file SbITest.H'.
Referenced by createWidget4Test(), displayValues(), SBTestNutation(), and ~SBTestNutation().
QString SBTestNutation::str [private]
Reimplemented from SBTestMatrix'.
Definition at line 173 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SBTime* SBTestNutation::Time [private]
Definition at line 175 of file SbITest.H'.
Referenced by createWidget4Test(), displayValues(), recalc(), SBTestNutation(), and ~SBTestNutation().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
SBEOP* SBTestNutation::Weop [private]
Definition at line 176 of file SbITest.H'.
Referenced by createWidget4Test(), recalc(), SBTestNutation(), and ~SBTestNutation().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.