SBTestMatrix
NAME
SBTestMatrix -
SYNOPSIS
#include <SbITest.H>
Inherits SBTest'.
Inherited by SBTestFrame, SBTestNutation, and SBTestPrecession'.
Public Member Functions
SBTestMatrix (QWidget *parent=0, const char *name=0, bool modal=FALSE, WFlags f=0)
virtual ~SBTestMatrix ()
virtual QString ClassName () const
Protected Slots
void accept ()
virtual void recalc ()
void reject ()
Protected Member Functions
virtual QWidget * createMatrixWidget (QWidget *)
void displayValues ()
virtual void closeEvent (QCloseEvent *)
virtual QWidget * createWidget4Test (QWidget *)
virtual QWidget * auxWidgetRt (QWidget *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
Matrix3 * Mat
QString str
QLabel * LMat [3][3]
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Detailed Description
Definition at line 95 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestMatrix::SBTestMatrix (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0) [inline]
Definition at line 99 of file SbITest.H'.
References Mat.
virtual SBTestMatrix::~SBTestMatrix () [inline, virtual]
Definition at line 101 of file SbITest.H'.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual QWidget* SBTest::auxWidgetRt (QWidget *) [inline, protected, virtual, inherited]
Reimplemented in SBTestAPLoad, SBTestPolarTides, SBTestOceanTides, SBTestSolidTides, SBTestDiurnEOP, and SBTestEOP'.
Definition at line 81 of file SbITest.H'.
Referenced by SBTest::createWidgets().
virtual QString SBTestMatrix::ClassName () const [inline, virtual]
Reimplemented from SBTest'.
Reimplemented in SBTestFrame, SBTestNutation, and SBTestPrecession'.
Definition at line 103 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestMatrix::createMatrixWidget (QWidget *parent) [protected, virtual]
Definition at line 299 of file SbITest.C'.
References Matrix3::at(), LMat, Mat, and str.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), and SBTestFrame::createWidget4Test().
QWidget * SBTest::createWidget4Test (QWidget *parent) [protected, virtual, inherited]
Reimplemented in SBTestAPLoad, SBTestPolarTides, SBTestOceanTides, SBTestSolidTides, SBTestDiurnEOP, SBTestEOP, SBTestEphem, SBTestFrame, SBTestNutation, and SBTestPrecession'.
Definition at line 217 of file SbITest.C'.
Referenced by SBTest::createWidgets().
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides().
void SBTestMatrix::displayValues () [protected]
Reimplemented in SBTestFrame, SBTestNutation, and SBTestPrecession'.
Definition at line 334 of file SbITest.C'.
References Matrix3::at(), LMat, Mat, and str.
void SBTest::recalc () [protected, virtual, slot, inherited]
Reimplemented in SBTestAPLoad, SBTestPolarTides, SBTestOceanTides, SBTestSolidTides, SBTestDiurnEOP, SBTestEOP, SBTestEphem, SBTestFrame, SBTestNutation, and SBTestPrecession'.
Definition at line 242 of file SbITest.C'.
References SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_Short, SBMJD::hour(), SBTest::IsDateModified, SBTest::LDate, SBTest::LMJD, SBMJD::min(), SBMJD::month(), SBMJD::sec(), SBMJD::setMJD(), SBTest::str, SBTest::TFinis, SBMJD::toString(), SBTest::TStart, and SBMJD::year().
Referenced by SBTest::createWidgets().
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
Member Data Documentation
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTestMatrix::LMat[3][3] [protected]
Definition at line 108 of file SbITest.H'.
Referenced by createMatrixWidget(), and displayValues().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
Matrix3* SBTestMatrix::Mat [protected]
Definition at line 103 of file SbITest.H'.
Referenced by createMatrixWidget(), displayValues(), SBTestFrame::SBTestFrame(), SBTestMatrix(), SBTestNutation::SBTestNutation(), and SBTestPrecession::SBTestPrecession().
QString SBTestMatrix::str [protected]
Reimplemented from SBTest'.
Reimplemented in SBTestFrame, SBTestNutation, and SBTestPrecession'.
Definition at line 107 of file SbITest.H'.
Referenced by createMatrixWidget(), and displayValues().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.