.TH "SBTestSolidTides" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBTestSolidTides \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbITest\&.H>\fP
.PP
Inherits \fBSBTest\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBTestSolidTides\fP (\fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "virtual \fB~SBTestSolidTides\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.ti -1c
.RI "void \fBreject\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *)"
.br
.ti -1c
.RI "virtual void \fBcreateWidgets\fP ()"
.br
.ti -1c
.RI "virtual \fBSBMJD\fP * \fBtStart\fP ()"
.br
.ti -1c
.RI "virtual \fBSBMJD\fP * \fBtFinis\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QString \fBstr\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP * \fBDate\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP * \fBTStart\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP * \fBTFinis\fP"
.br
.ti -1c
.RI "QLabel * \fBLMJD\fP"
.br
.ti -1c
.RI "QLabel * \fBLDate\fP"
.br
.ti -1c
.RI "QLabel * \fBLRange\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEYear\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEMonth\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEDay\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEHour\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEMin\fP"
.br
.ti -1c
.RI "QLineEdit * \fBESec\fP"
.br
.ti -1c
.RI "bool \fBIsDateModified\fP"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "virtual void \fBrecalc\fP ()"
.br
.ti -1c
.RI "virtual void \fBstationChange\fP (\fBQListViewItem\fP *)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBfillData4Plotting\fP ()"
.br
.ti -1c
.RI "virtual \fBQWidget\fP * \fBcreateWidget4Test\fP (\fBQWidget\fP *)"
.br
.ti -1c
.RI "virtual \fBQWidget\fP * \fBauxWidgetRt\fP (\fBQWidget\fP *)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBFrame\fP * \fBFrame\fP"
.br
.ti -1c
.RI "\fBSBEphem\fP * \fBEphem\fP"
.br
.ti -1c
.RI "\fBSBSolidTideLd\fP * \fBSolidTide\fP"
.br
.ti -1c
.RI "\fBSB_TRF\fP * \fBTRF\fP"
.br
.ti -1c
.RI "\fBSBStation\fP * \fBStation\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBVectors\fP [7]"
.br
.ti -1c
.RI "QString \fBVectorNames\fP [7]"
.br
.ti -1c
.RI "unsigned int \fBNumOfPts\fP"
.br
.ti -1c
.RI "unsigned int \fBNumOfVecotors\fP"
.br
.ti -1c
.RI "double \fBStep\fP"
.br
.ti -1c
.RI "QLineEdit * \fBENumPts\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEStep\fP"
.br
.ti -1c
.RI "\fBQListView\fP * \fBStLV\fP"
.br
.ti -1c
.RI "\fBSBPlotCarrier\fP * \fBPlotCarrier\fP"
.br
.ti -1c
.RI "\fBSBPlot\fP * \fBPlot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 425 of file SbITest\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBTestSolidTides::SBTestSolidTides (\fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 1587 of file SbITest\&.C'\&.
.PP
References SBPlotCarrier::AT_MJD, SBPlotCarrier::columnNames(), Config, SBPlotCarrier::createBranch(), SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBConfig::EM_LEDE200, SBConfig::EM_LEDE403, SBConfig::EM_LEDE405, SBFrame::eop(), Ephem, SBConfig::ephemModel(), fillData4Plotting(), Frame, SBSetUp::loadTRF(), SBNamed::name(), NumOfPts, NumOfVecotors, PlotCarrier, SB_TRF::prepare4Run(), SBPlotCarrier::setFile4SaveBaseName(), SBEOP::setPtNum(), SBPlotCarrier::setType(), SetUp, SolidTide, SBConfig::solidTideLd(), SBConfig::ST_IERS92, SBConfig::ST_IERS96, Station, SB_TRF::stations(), Step, SBConfig::STR_Classic, SBConfig::STR_NRO, SBConfig::sysTransform(), SBTest::TFinis, SBEphem::tFinis(), SBEOP::tFinis(), TRF, SBTest::TStart, SBEphem::tStart(), SBEOP::tStart(), v3Zero, VectorNames, and Vectors\&.
.SS "SBTestSolidTides::~SBTestSolidTides ()\fC [virtual]\fP"
.PP
Definition at line 1673 of file SbITest\&.C'\&.
.PP
References Ephem, SB_TRF::finisRun(), Frame, PlotCarrier, SolidTide, and TRF\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBTest::accept ()\fC [protected, slot, inherited]\fP"
.PP
Definition at line 230 of file SbITest\&.C'\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "\fBQWidget\fP * SBTestSolidTides::auxWidgetRt (\fBQWidget\fP *parent)\fC [private, virtual]\fP"
.PP
Reimplemented from \fBSBTest\fP'\&.
.PP
Definition at line 1774 of file SbITest\&.C'\&.
.PP
References ENumPts, EStep, NumOfPts, stationChange(), SB_TRF::stations(), Step, StLV, and TRF\&.
.SS "virtual QString SBTestSolidTides::ClassName () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBTest\fP'\&.
.PP
Definition at line 432 of file SbITest\&.H'\&.
.SS "virtual void SBTest::closeEvent (QCloseEvent *)\fC [inline, protected, virtual, inherited]\fP"
.PP
Definition at line 61 of file SbITest\&.H'\&.
.SS "\fBQWidget\fP * SBTestSolidTides::createWidget4Test (\fBQWidget\fP *parent)\fC [private, virtual]\fP"
.PP
Reimplemented from \fBSBTest\fP'\&.
.PP
Definition at line 1707 of file SbITest\&.C'\&.
.PP
References Plot, and PlotCarrier\&.
.SS "void SBTest::createWidgets ()\fC [protected, virtual, inherited]\fP"
.PP
Definition at line 76 of file SbITest\&.C'\&.
.PP
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year()\&.
.PP
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides()\&.
.SS "void SBTestSolidTides::fillData4Plotting ()\fC [private]\fP"
.PP
Definition at line 1712 of file SbITest\&.C'\&.
.PP
References SBPlotCarrier::branches(), SBEphem::calc(), SBFrame::calc(), SBPlotBranch::data(), SBTest::Date, EAST, SBFrame::eop(), Ephem, SBPlotCarrier::findBranch(), SBStation::fmVEN(), Frame, SBMatrix::nCol(), NORT, SBMatrix::nRow(), NumOfPts, NumOfVecotors, PlotCarrier, SBEOP::prepare4Date(), SBMatrix::resize(), SBStation::rt(), SBMatrix::set(), SolidTide, Station, Step, SBSolidTideLd::step1(), SBSolidTideLd::step2(), SBTime::TDB(), SBSolidTideLd::tideDeg2ip(), SBSolidTideLd::tideDeg2op(), SBSolidTideLd::tideDeg3ip(), SBSolidTideLd::tideLatDepend(), SBFrame::time(), v3Zero, VectorNames, Vectors, VERT, X_AXIS, Y_AXIS, and Z_AXIS\&.
.PP
Referenced by recalc(), SBTestSolidTides(), and stationChange()\&.
.SS "void SBTestSolidTides::recalc ()\fC [private, virtual, slot]\fP"
.PP
Reimplemented from \fBSBTest\fP'\&.
.PP
Definition at line 1838 of file SbITest\&.C'\&.
.PP
References SBPlot::dataChanged(), ENumPts, SBFrame::eop(), EStep, fillData4Plotting(), Frame, SBTest::IsDateModified, NumOfPts, Plot, SBEOP::setPtNum(), and Step\&.
.PP
Referenced by stationChange()\&.
.SS "void SBTest::reject ()\fC [protected, slot, inherited]\fP"
.PP
Definition at line 236 of file SbITest\&.C'\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "void SBTestSolidTides::stationChange (\fBQListViewItem\fP *LI)\fC [private, virtual, slot]\fP"
.PP
Definition at line 1868 of file SbITest\&.C'\&.
.PP
References SBPlot::dataChanged(), fillData4Plotting(), SBNamed::name(), Plot, PlotCarrier, recalc(), SBNamed::setName(), and Station\&.
.PP
Referenced by auxWidgetRt()\&.
.SS "virtual \fBSBMJD\fP* SBTest::tFinis ()\fC [inline, protected, virtual, inherited]\fP"
.PP
Definition at line 84 of file SbITest\&.H'\&.
.PP
References SBTest::TFinis\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "virtual \fBSBMJD\fP* SBTest::tStart ()\fC [inline, protected, virtual, inherited]\fP"
.PP
Definition at line 83 of file SbITest\&.H'\&.
.PP
References SBTest::TStart\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBMJD\fP* \fBSBTest::Date\fP\fC [protected, inherited]\fP"
.PP
Definition at line 64 of file SbITest\&.H'\&.
.PP
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides(), and SBTest::~SBTest()\&.
.SS "QLineEdit* \fBSBTest::EDay\fP\fC [protected, inherited]\fP"
.PP
Definition at line 74 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::EHour\fP\fC [protected, inherited]\fP"
.PP
Definition at line 75 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::EMin\fP\fC [protected, inherited]\fP"
.PP
Definition at line 76 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::EMonth\fP\fC [protected, inherited]\fP"
.PP
Definition at line 73 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTestSolidTides::ENumPts\fP\fC [private]\fP"
.PP
Definition at line 454 of file SbITest\&.H'\&.
.PP
Referenced by auxWidgetRt(), and recalc()\&.
.SS "\fBSBEphem\fP* \fBSBTestSolidTides::Ephem\fP\fC [private]\fP"
.PP
Definition at line 441 of file SbITest\&.H'\&.
.PP
Referenced by fillData4Plotting(), SBTestSolidTides(), and ~SBTestSolidTides()\&.
.SS "QLineEdit* \fBSBTest::ESec\fP\fC [protected, inherited]\fP"
.PP
Definition at line 77 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTestSolidTides::EStep\fP\fC [private]\fP"
.PP
Definition at line 455 of file SbITest\&.H'\&.
.PP
Referenced by auxWidgetRt(), and recalc()\&.
.SS "QLineEdit* \fBSBTest::EYear\fP\fC [protected, inherited]\fP"
.PP
Definition at line 72 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "\fBSBFrame\fP* \fBSBTestSolidTides::Frame\fP\fC [private]\fP"
.PP
Definition at line 440 of file SbITest\&.H'\&.
.PP
Referenced by fillData4Plotting(), recalc(), SBTestSolidTides(), and ~SBTestSolidTides()\&.
.SS "bool \fBSBTest::IsDateModified\fP\fC [protected, inherited]\fP"
.PP
Definition at line 78 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest()\&.
.SS "QLabel* \fBSBTest::LDate\fP\fC [protected, inherited]\fP"
.PP
Definition at line 70 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLabel* \fBSBTest::LMJD\fP\fC [protected, inherited]\fP"
.PP
Definition at line 69 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLabel* \fBSBTest::LRange\fP\fC [protected, inherited]\fP"
.PP
Definition at line 71 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "unsigned int \fBSBTestSolidTides::NumOfPts\fP\fC [private]\fP"
.PP
Definition at line 448 of file SbITest\&.H'\&.
.PP
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestSolidTides()\&.
.SS "unsigned int \fBSBTestSolidTides::NumOfVecotors\fP\fC [private]\fP"
.PP
Definition at line 449 of file SbITest\&.H'\&.
.PP
Referenced by fillData4Plotting(), and SBTestSolidTides()\&.
.SS "\fBSBPlot\fP* \fBSBTestSolidTides::Plot\fP\fC [private]\fP"
.PP
Definition at line 461 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), recalc(), and stationChange()\&.
.SS "\fBSBPlotCarrier\fP* \fBSBTestSolidTides::PlotCarrier\fP\fC [private]\fP"
.PP
Definition at line 460 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), fillData4Plotting(), SBTestSolidTides(), stationChange(), and ~SBTestSolidTides()\&.
.SS "\fBSBSolidTideLd\fP* \fBSBTestSolidTides::SolidTide\fP\fC [private]\fP"
.PP
Definition at line 442 of file SbITest\&.H'\&.
.PP
Referenced by fillData4Plotting(), SBTestSolidTides(), and ~SBTestSolidTides()\&.
.SS "\fBSBStation\fP* \fBSBTestSolidTides::Station\fP\fC [private]\fP"
.PP
Definition at line 444 of file SbITest\&.H'\&.
.PP
Referenced by fillData4Plotting(), SBTestSolidTides(), and stationChange()\&.
.SS "double \fBSBTestSolidTides::Step\fP\fC [private]\fP"
.PP
Definition at line 450 of file SbITest\&.H'\&.
.PP
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestSolidTides()\&.
.SS "\fBQListView\fP* \fBSBTestSolidTides::StLV\fP\fC [private]\fP"
.PP
Definition at line 457 of file SbITest\&.H'\&.
.PP
Referenced by auxWidgetRt()\&.
.SS "QString \fBSBTest::str\fP\fC [protected, inherited]\fP"
.PP
Reimplemented in \fBSBTestFrame\fP, \fBSBTestNutation\fP, \fBSBTestPrecession\fP, and \fBSBTestMatrix\fP'\&.
.PP
Definition at line 61 of file SbITest\&.H'\&.
.PP
Referenced by SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEphem::displayCoo(), and SBTest::recalc()\&.
.SS "\fBSBMJD\fP* \fBSBTest::TFinis\fP\fC [protected, inherited]\fP"
.PP
Definition at line 66 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest()\&.
.SS "\fBSB_TRF\fP* \fBSBTestSolidTides::TRF\fP\fC [private]\fP"
.PP
Definition at line 443 of file SbITest\&.H'\&.
.PP
Referenced by auxWidgetRt(), SBTestSolidTides(), and ~SBTestSolidTides()\&.
.SS "\fBSBMJD\fP* \fBSBTest::TStart\fP\fC [protected, inherited]\fP"
.PP
Definition at line 65 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest()\&.
.SS "QString \fBSBTestSolidTides::VectorNames\fP[7]\fC [private]\fP"
.PP
Definition at line 446 of file SbITest\&.H'\&.
.PP
Referenced by fillData4Plotting(), and SBTestSolidTides()\&.
.SS "\fBVector3\fP \fBSBTestSolidTides::Vectors\fP[7]\fC [private]\fP"
.PP
Definition at line 445 of file SbITest\&.H'\&.
.PP
Referenced by fillData4Plotting(), and SBTestSolidTides()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
