SBTestFrame
NAME
SBTestFrame -
SYNOPSIS
#include <SbITest.H>
Inherits SBTestMatrix'.
Public Member Functions
SBTestFrame (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBTestFrame ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual QWidget * createMatrixWidget (QWidget *)
virtual void closeEvent (QCloseEvent *)
virtual QWidget * auxWidgetRt (QWidget *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
Matrix3 * Mat
QLabel * LMat [3][3]
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Private Slots
virtual void recalc ()
Private Member Functions
virtual QWidget * createWidget4Test (QWidget *)
void displayValues ()
Private Attributes
QString str
SBFrame * Frame
QLabel * LTAI
QLabel * LTT
QLabel * LUT1
QLabel * LArg0
QLabel * LArg1
QLabel * LArg2
QLabel * LArg3
QLabel * LArg4
QLabel * LArg5
QLabel * LGMST
QLabel * LGST
QLabel * LDiurnXP
QLabel * LDiurnYP
QLabel * LDiurnUT
Detailed Description
Definition at line 201 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestFrame::SBTestFrame (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 628 of file SbITest.C'.
References Config, SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBFrame::eop(), Frame, SBTestMatrix::Mat, SBNamed::name(), SBConfig::STR_Classic, SBConfig::STR_NRO, SBConfig::sysTransform(), SBTest::TFinis, SBEOP::tFinis(), SBTest::TStart, and SBEOP::tStart().
SBTestFrame::~SBTestFrame () [virtual]
Definition at line 652 of file SbITest.C'.
References Frame.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual QWidget* SBTest::auxWidgetRt (QWidget *) [inline, protected, virtual, inherited]
Reimplemented in SBTestAPLoad, SBTestPolarTides, SBTestOceanTides, SBTestSolidTides, SBTestDiurnEOP, and SBTestEOP'.
Definition at line 81 of file SbITest.H'.
Referenced by SBTest::createWidgets().
virtual QString SBTestFrame::ClassName () const [inline, virtual]
Reimplemented from SBTestMatrix'.
Definition at line 208 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestMatrix::createMatrixWidget (QWidget *parent) [protected, virtual, inherited]
Definition at line 299 of file SbITest.C'.
References Matrix3::at(), SBTestMatrix::LMat, SBTestMatrix::Mat, and SBTestMatrix::str.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), and createWidget4Test().
QWidget * SBTestFrame::createWidget4Test (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 657 of file SbITest.C'.
References SBFrame::calc(), SBTestMatrix::createMatrixWidget(), SBTest::Date, DAY2SEC, SBFrame::diurnalDUT1(), SBFrame::diurnalDX(), SBFrame::diurnalDY(), SBFrame::eop(), SBFrame::eopDiurnal(), SBMJD::F_Short, SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), SBTime::fArg_theta(), Frame, SBFrame::gmst(), SBFrame::gst(), LArg0, LArg1, LArg2, LArg3, LArg4, LArg5, LDiurnUT, LDiurnXP, LDiurnYP, LGMST, LGST, LTAI, LTT, LUT1, SBNamed::name(), SBEOP::prepare4Date(), rad2dmslStr(), RAD2SEC, str, SBTime::TAI(), SBFrame::time(), SBMJD::toString(), SBTime::TT(), and SBTime::UT1().
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides().
void SBTestFrame::displayValues () [private]
Reimplemented from SBTestMatrix'.
Definition at line 829 of file SbITest.C'.
References DAY2SEC, SBFrame::diurnalDUT1(), SBFrame::diurnalDX(), SBFrame::diurnalDY(), SBMJD::F_Short, SBTime::fArg_D(), SBTime::fArg_F(), SBTime::fArg_l(), SBTime::fArg_lPrime(), SBTime::fArg_Omega(), SBTime::fArg_theta(), Frame, SBFrame::gmst(), SBFrame::gst(), LArg0, LArg1, LArg2, LArg3, LArg4, LArg5, LDiurnUT, LDiurnXP, LDiurnYP, LGMST, LGST, LTAI, LTT, LUT1, rad2dmslStr(), RAD2SEC, str, SBTime::TAI(), SBFrame::time(), SBMJD::toString(), SBTime::TT(), and SBTime::UT1().
Referenced by recalc().
void SBTestFrame::recalc () [private, virtual, slot]
Reimplemented from SBTest'.
Definition at line 821 of file SbITest.C'.
References SBFrame::calc(), SBTest::Date, displayValues(), SBFrame::eop(), Frame, and SBEOP::prepare4Date().
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
Member Data Documentation
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
SBFrame* SBTestFrame::Frame [private]
Definition at line 215 of file SbITest.H'.
Referenced by createWidget4Test(), displayValues(), recalc(), SBTestFrame(), and ~SBTestFrame().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest().
QLabel* SBTestFrame::LArg0 [private]
Definition at line 223 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LArg1 [private]
Definition at line 224 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LArg2 [private]
Definition at line 225 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LArg3 [private]
Definition at line 226 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LArg4 [private]
Definition at line 227 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LArg5 [private]
Definition at line 228 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTestFrame::LDiurnUT [private]
Definition at line 237 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LDiurnXP [private]
Definition at line 235 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LDiurnYP [private]
Definition at line 236 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LGMST [private]
Definition at line 231 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LGST [private]
Definition at line 232 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestMatrix::LMat[3][3] [protected, inherited]
Definition at line 108 of file SbITest.H'.
Referenced by SBTestMatrix::createMatrixWidget(), and SBTestMatrix::displayValues().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
QLabel* SBTestFrame::LTAI [private]
Definition at line 218 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LTT [private]
Definition at line 219 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
QLabel* SBTestFrame::LUT1 [private]
Definition at line 220 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
Matrix3* SBTestMatrix::Mat [protected, inherited]
Definition at line 103 of file SbITest.H'.
Referenced by SBTestMatrix::createMatrixWidget(), SBTestMatrix::displayValues(), SBTestFrame(), SBTestMatrix::SBTestMatrix(), SBTestNutation::SBTestNutation(), and SBTestPrecession::SBTestPrecession().
QString SBTestFrame::str [private]
Reimplemented from SBTestMatrix'.
Definition at line 214 of file SbITest.H'.
Referenced by createWidget4Test(), and displayValues().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.