.TH "SBTestEphem" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBTestEphem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbITest\&.H>\fP
.PP
Inherits \fBSBTest\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBTestEphem\fP (\fBQWidget\fP *=0, const char *=0, bool=FALSE, WFlags=0)"
.br
.ti -1c
.RI "virtual \fB~SBTestEphem\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.ti -1c
.RI "void \fBreject\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *)"
.br
.ti -1c
.RI "virtual \fBQWidget\fP * \fBauxWidgetRt\fP (\fBQWidget\fP *)"
.br
.ti -1c
.RI "virtual void \fBcreateWidgets\fP ()"
.br
.ti -1c
.RI "virtual \fBSBMJD\fP * \fBtStart\fP ()"
.br
.ti -1c
.RI "virtual \fBSBMJD\fP * \fBtFinis\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QString \fBstr\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP * \fBDate\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP * \fBTStart\fP"
.br
.ti -1c
.RI "\fBSBMJD\fP * \fBTFinis\fP"
.br
.ti -1c
.RI "QLabel * \fBLMJD\fP"
.br
.ti -1c
.RI "QLabel * \fBLDate\fP"
.br
.ti -1c
.RI "QLabel * \fBLRange\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEYear\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEMonth\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEDay\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEHour\fP"
.br
.ti -1c
.RI "QLineEdit * \fBEMin\fP"
.br
.ti -1c
.RI "QLineEdit * \fBESec\fP"
.br
.ti -1c
.RI "bool \fBIsDateModified\fP"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum \fBEUnits\fP { \fBU_KM\fP = 0, \fBU_AU\fP = 1, \fBU_U\fP = 2 }"
.br
.ti -1c
.RI "enum \fBEFrameType\fP { \fBFT_ORTH\fP = 0, \fBFT_SPH\fP = 1 }"
.br
.ti -1c
.RI "enum \fBEFrame\fP { \fBF_CRS\fP = 0, \fBF_TRS\fP = 1 }"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "virtual void \fBrecalc\fP ()"
.br
.ti -1c
.RI "void \fBoriginChanged\fP (int)"
.br
.ti -1c
.RI "void \fBunitChanged\fP (int)"
.br
.ti -1c
.RI "void \fBframeTypeChanged\fP (int)"
.br
.ti -1c
.RI "void \fBframeChanged\fP (int)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBQWidget\fP * \fBcreateWidget4Test\fP (\fBQWidget\fP *)"
.br
.ti -1c
.RI "void \fBdisplayCoo\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBScale\fP [3]"
.br
.ti -1c
.RI "\fBEUnits\fP \fBUnits\fP"
.br
.ti -1c
.RI "\fBEFrame\fP \fBFrame\fP"
.br
.ti -1c
.RI "\fBEFrameType\fP \fBFrameType\fP"
.br
.ti -1c
.RI "\fBSBEphem\fP * \fBWeph\fP"
.br
.ti -1c
.RI "\fBSBFrame\fP * \fBWref\fP"
.br
.ti -1c
.RI "const \fBVector3\fP * \fBOrigin\fP"
.br
.ti -1c
.RI "const \fBMatrix3\fP * \fBRF\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBv0\fP"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBm0\fP"
.br
.ti -1c
.RI "QLabel * \fBLCoo\fP [11][3]"
.br
.ti -1c
.RI "QLabel * \fBLCLabel\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 252 of file SbITest\&.H'\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSBTestEphem::EFrame\fP\fC [private]\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIF_CRS \fP\fP
.TP
\fB\fIF_TRS \fP\fP

.PP
Definition at line 272 of file SbITest\&.H'\&.
.SS "enum \fBSBTestEphem::EFrameType\fP\fC [private]\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIFT_ORTH \fP\fP
.TP
\fB\fIFT_SPH \fP\fP

.PP
Definition at line 271 of file SbITest\&.H'\&.
.SS "enum \fBSBTestEphem::EUnits\fP\fC [private]\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIU_KM \fP\fP
.TP
\fB\fIU_AU \fP\fP
.TP
\fB\fIU_U \fP\fP

.PP
Definition at line 270 of file SbITest\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBTestEphem::SBTestEphem (\fBQWidget\fP *parent = \fC0\fP, const char *name = \fC0\fP, boolmodal = \fCFALSE\fP, WFlagsf = \fC0\fP)"
.PP
Definition at line 857 of file SbITest\&.C'\&.
.PP
References SBEphem::au(), Config, SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBConfig::EM_LEDE200, SBConfig::EM_LEDE403, SBConfig::EM_LEDE405, SBConfig::ephemModel(), F_CRS, Frame, FrameType, FT_ORTH, m0, SBNamed::name(), Origin, RF, Scale, SBConfig::STR_Classic, SBConfig::STR_NRO, SBConfig::sysTransform(), SBTest::TFinis, SBEphem::tFinis(), SBTest::TStart, SBEphem::tStart(), U_KM, Units, v0, Weph, and Wref\&.
.SS "SBTestEphem::~SBTestEphem ()\fC [virtual]\fP"
.PP
Definition at line 894 of file SbITest\&.C'\&.
.PP
References Weph, and Wref\&.
.SH "Member Function Documentation"
.PP 
.SS "void SBTest::accept ()\fC [protected, slot, inherited]\fP"
.PP
Definition at line 230 of file SbITest\&.C'\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "virtual \fBQWidget\fP* SBTest::auxWidgetRt (\fBQWidget\fP *)\fC [inline, protected, virtual, inherited]\fP"
.PP
Reimplemented in \fBSBTestAPLoad\fP, \fBSBTestPolarTides\fP, \fBSBTestOceanTides\fP, \fBSBTestSolidTides\fP, \fBSBTestDiurnEOP\fP, and \fBSBTestEOP\fP'\&.
.PP
Definition at line 81 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "virtual QString SBTestEphem::ClassName () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBSBTest\fP'\&.
.PP
Definition at line 259 of file SbITest\&.H'\&.
.SS "virtual void SBTest::closeEvent (QCloseEvent *)\fC [inline, protected, virtual, inherited]\fP"
.PP
Definition at line 61 of file SbITest\&.H'\&.
.SS "\fBQWidget\fP * SBTestEphem::createWidget4Test (\fBQWidget\fP *parent)\fC [private, virtual]\fP"
.PP
Reimplemented from \fBSBTest\fP'\&.
.PP
Definition at line 900 of file SbITest\&.C'\&.
.PP
References Vector3::at(), SBEphem::body(), SBEphem::calc(), SBTest::Date, frameChanged(), frameTypeChanged(), LCLabel, LCoo, SBNamed::name(), originChanged(), SBCelestBody::r(), Scale, SBTest::str, unitChanged(), Units, and Weph\&.
.SS "void SBTest::createWidgets ()\fC [protected, virtual, inherited]\fP"
.PP
Definition at line 76 of file SbITest\&.C'\&.
.PP
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year()\&.
.PP
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides()\&.
.SS "void SBTestEphem::displayCoo ()\fC [private]\fP"
.PP
Definition at line 1053 of file SbITest\&.C'\&.
.PP
References Vector3::at(), SBEphem::body(), F_CRS, Frame, FrameType, FT_ORTH, FT_SPH, Vector3::lambda(), LCLabel, LCoo, Vector3::module(), Origin, Vector3::phi(), SBCelestBody::r(), rad2dmsStr(), rad2hmsStr(), RF, Scale, SBTest::str, Units, and Weph\&.
.PP
Referenced by frameChanged(), frameTypeChanged(), originChanged(), recalc(), and unitChanged()\&.
.SS "void SBTestEphem::frameChanged (inti)\fC [private, slot]\fP"
.PP
Definition at line 1012 of file SbITest\&.C'\&.
.PP
References SBFrame::calc(), SBTest::Date, displayCoo(), F_CRS, F_TRS, Frame, m0, RF, and Wref\&.
.PP
Referenced by createWidget4Test()\&.
.SS "void SBTestEphem::frameTypeChanged (inti)\fC [private, slot]\fP"
.PP
Definition at line 1006 of file SbITest\&.C'\&.
.PP
References displayCoo(), and FrameType\&.
.PP
Referenced by createWidget4Test()\&.
.SS "void SBTestEphem::originChanged (inti)\fC [private, slot]\fP"
.PP
Definition at line 1028 of file SbITest\&.C'\&.
.PP
References SBEphem::body(), displayCoo(), Origin, SBCelestBody::r(), v0, and Weph\&.
.PP
Referenced by createWidget4Test()\&.
.SS "void SBTestEphem::recalc ()\fC [private, virtual, slot]\fP"
.PP
Reimplemented from \fBSBTest\fP'\&.
.PP
Definition at line 1040 of file SbITest\&.C'\&.
.PP
References SBEphem::calc(), SBFrame::calc(), SBTest::Date, SBMJD::date(), displayCoo(), SBFrame::eop(), SBEphem::isOK(), SBEOP::prepare4Date(), SBEOP::t_4Prepare(), Weph, and Wref\&.
.SS "void SBTest::reject ()\fC [protected, slot, inherited]\fP"
.PP
Definition at line 236 of file SbITest\&.C'\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "virtual \fBSBMJD\fP* SBTest::tFinis ()\fC [inline, protected, virtual, inherited]\fP"
.PP
Definition at line 84 of file SbITest\&.H'\&.
.PP
References SBTest::TFinis\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "virtual \fBSBMJD\fP* SBTest::tStart ()\fC [inline, protected, virtual, inherited]\fP"
.PP
Definition at line 83 of file SbITest\&.H'\&.
.PP
References SBTest::TStart\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "void SBTestEphem::unitChanged (inti)\fC [private, slot]\fP"
.PP
Definition at line 1034 of file SbITest\&.C'\&.
.PP
References displayCoo(), and Units\&.
.PP
Referenced by createWidget4Test()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBMJD\fP* \fBSBTest::Date\fP\fC [protected, inherited]\fP"
.PP
Definition at line 64 of file SbITest\&.H'\&.
.PP
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest()\&.
.SS "QLineEdit* \fBSBTest::EDay\fP\fC [protected, inherited]\fP"
.PP
Definition at line 74 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::EHour\fP\fC [protected, inherited]\fP"
.PP
Definition at line 75 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::EMin\fP\fC [protected, inherited]\fP"
.PP
Definition at line 76 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::EMonth\fP\fC [protected, inherited]\fP"
.PP
Definition at line 73 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::ESec\fP\fC [protected, inherited]\fP"
.PP
Definition at line 77 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLineEdit* \fBSBTest::EYear\fP\fC [protected, inherited]\fP"
.PP
Definition at line 72 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "\fBEFrame\fP \fBSBTestEphem::Frame\fP\fC [private]\fP"
.PP
Definition at line 275 of file SbITest\&.H'\&.
.PP
Referenced by displayCoo(), frameChanged(), and SBTestEphem()\&.
.SS "\fBEFrameType\fP \fBSBTestEphem::FrameType\fP\fC [private]\fP"
.PP
Definition at line 276 of file SbITest\&.H'\&.
.PP
Referenced by displayCoo(), frameTypeChanged(), and SBTestEphem()\&.
.SS "bool \fBSBTest::IsDateModified\fP\fC [protected, inherited]\fP"
.PP
Definition at line 78 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest()\&.
.SS "QLabel* \fBSBTestEphem::LCLabel\fP[3]\fC [private]\fP"
.PP
Definition at line 285 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), and displayCoo()\&.
.SS "QLabel* \fBSBTestEphem::LCoo\fP[11][3]\fC [private]\fP"
.PP
Definition at line 284 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), and displayCoo()\&.
.SS "QLabel* \fBSBTest::LDate\fP\fC [protected, inherited]\fP"
.PP
Definition at line 70 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLabel* \fBSBTest::LMJD\fP\fC [protected, inherited]\fP"
.PP
Definition at line 69 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets(), and SBTest::recalc()\&.
.SS "QLabel* \fBSBTest::LRange\fP\fC [protected, inherited]\fP"
.PP
Definition at line 71 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::createWidgets()\&.
.SS "\fBMatrix3\fP \fBSBTestEphem::m0\fP\fC [private]\fP"
.PP
Definition at line 282 of file SbITest\&.H'\&.
.PP
Referenced by frameChanged(), and SBTestEphem()\&.
.SS "const \fBVector3\fP* \fBSBTestEphem::Origin\fP\fC [private]\fP"
.PP
Definition at line 279 of file SbITest\&.H'\&.
.PP
Referenced by displayCoo(), originChanged(), and SBTestEphem()\&.
.SS "const \fBMatrix3\fP* \fBSBTestEphem::RF\fP\fC [private]\fP"
.PP
Definition at line 280 of file SbITest\&.H'\&.
.PP
Referenced by displayCoo(), frameChanged(), and SBTestEphem()\&.
.SS "double \fBSBTestEphem::Scale\fP[3]\fC [private]\fP"
.PP
Definition at line 273 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), displayCoo(), and SBTestEphem()\&.
.SS "QString \fBSBTest::str\fP\fC [protected, inherited]\fP"
.PP
Reimplemented in \fBSBTestFrame\fP, \fBSBTestNutation\fP, \fBSBTestPrecession\fP, and \fBSBTestMatrix\fP'\&.
.PP
Definition at line 61 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), SBTest::createWidgets(), displayCoo(), and SBTest::recalc()\&.
.SS "\fBSBMJD\fP* \fBSBTest::TFinis\fP\fC [protected, inherited]\fP"
.PP
Definition at line 66 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest()\&.
.SS "\fBSBMJD\fP* \fBSBTest::TStart\fP\fC [protected, inherited]\fP"
.PP
Definition at line 65 of file SbITest\&.H'\&.
.PP
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest()\&.
.SS "\fBEUnits\fP \fBSBTestEphem::Units\fP\fC [private]\fP"
.PP
Definition at line 274 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), displayCoo(), SBTestEphem(), and unitChanged()\&.
.SS "\fBVector3\fP \fBSBTestEphem::v0\fP\fC [private]\fP"
.PP
Definition at line 281 of file SbITest\&.H'\&.
.PP
Referenced by originChanged(), and SBTestEphem()\&.
.SS "\fBSBEphem\fP* \fBSBTestEphem::Weph\fP\fC [private]\fP"
.PP
Definition at line 277 of file SbITest\&.H'\&.
.PP
Referenced by createWidget4Test(), displayCoo(), originChanged(), recalc(), SBTestEphem(), and ~SBTestEphem()\&.
.SS "\fBSBFrame\fP* \fBSBTestEphem::Wref\fP\fC [private]\fP"
.PP
Definition at line 278 of file SbITest\&.H'\&.
.PP
Referenced by frameChanged(), recalc(), SBTestEphem(), and ~SBTestEphem()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
