SBTestStationLI
NAME
SBTestStationLI -
SYNOPSIS
#include <SbITest.H>
Inherits QListViewItem'.
Public Member Functions
SBTestStationLI (QListView *parent_, SBStation *Station_)
~SBTestStationLI ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
SBStation * station ()
Private Attributes
SBStation * Station
Detailed Description
Definition at line 403 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestStationLI::SBTestStationLI (QListView *parent_, SBStation *Station_) [inline]
Definition at line 408 of file SbITest.H'.
References Station.
SBTestStationLI::~SBTestStationLI () [inline]
Definition at line 410 of file SbITest.H'.
Member Function Documentation
virtual QString SBTestStationLI::ClassName () const [inline, virtual]
Definition at line 411 of file SbITest.H'.
QString SBTestStationLI::key (intcol, bool) const [virtual]
Definition at line 1563 of file SbITest.C'.
References SBStation::id(), SBNamed::name(), Station, SBStation::tech(), SBSolutionName::techAbbrev(), TmpString, and SBStationID::toString().
SBStation* SBTestStationLI::station () [inline]
Definition at line 414 of file SbITest.H'.
References Station.
QString SBTestStationLI::text (intcol) const [virtual]
Definition at line 1547 of file SbITest.C'.
References SBStation::id(), SBNamed::name(), Station, SBStation::tech(), SBSolutionName::techAbbrev(), TmpString, and SBStationID::toString().
Member Data Documentation
SBStation* SBTestStationLI::Station [private]
Definition at line 406 of file SbITest.H'.
Referenced by key(), SBTestStationLI(), station(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.