SBTestAPLoad
NAME
SBTestAPLoad -
SYNOPSIS
#include <SbITest.H>
Inherits SBTest'.
Public Member Functions
SBTestAPLoad (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBTestAPLoad ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
QString str
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Private Slots
virtual void recalc ()
virtual void stationChange (QListViewItem *)
Private Member Functions
void fillData4Plotting ()
virtual QWidget * createWidget4Test (QWidget *)
virtual QWidget * auxWidgetRt (QWidget *)
Private Attributes
SBAploEphem * AploEphem
SB_TRF * TRF
SBStation * Station
unsigned int NumOfPts
double Step
QLineEdit * ENumPts
QLineEdit * EStep
QListView * StLV
SBPlotCarrier * PlotCarrier
SBPlot * Plot
Detailed Description
Definition at line 581 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestAPLoad::SBTestAPLoad (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2375 of file SbITest.C'.
References AploEphem, SBPlotCarrier::AT_MJD, SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, fillData4Plotting(), SBAploEphem::interval(), SBSetUp::loadAploEphem(), SBSetUp::loadTRF(), SBNamed::name(), NumOfPts, PlotCarrier, SB_TRF::prepare4Run(), SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setType(), SetUp, Station, SB_TRF::stations(), Step, SBTest::TFinis, SBAploEphem::tFinis(), TRF, SBTest::TStart, and SBAploEphem::tStart().
SBTestAPLoad::~SBTestAPLoad () [virtual]
Definition at line 2418 of file SbITest.C'.
References AploEphem, SB_TRF::finisRun(), PlotCarrier, and TRF.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
QWidget * SBTestAPLoad::auxWidgetRt (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 2515 of file SbITest.C'.
References ENumPts, EStep, NumOfPts, stationChange(), SB_TRF::stations(), Step, StLV, and TRF.
virtual QString SBTestAPLoad::ClassName () const [inline, virtual]
Reimplemented from SBTest'.
Definition at line 588 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestAPLoad::createWidget4Test (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 2440 of file SbITest.C'.
References Plot, and PlotCarrier.
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides().
void SBTestAPLoad::fillData4Plotting () [private]
Definition at line 2445 of file SbITest.C'.
References AploEphem, Vector3::at(), SBMatrix::at(), SBSpline::b(), SBPlotCarrier::branches(), SBTest::Date, SBAploEphem::dismissed(), SBAploEphem::displacement(), SBAploEphem::getReady(), SBStation::id(), SBAploEphem::interval(), SBMatrix::nCol(), SBMatrix::nRow(), NumOfPts, PlotCarrier, SBAploEphem::registerStation(), SBMatrix::resize(), SBMatrix::set(), SBAploEphem::spline4station(), Station, Step, v3Zero, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by recalc(), SBTestAPLoad(), and stationChange().
void SBTestAPLoad::recalc () [private, virtual, slot]
Reimplemented from SBTest'.
Definition at line 2580 of file SbITest.C'.
References SBPlot::dataChanged(), ENumPts, EStep, fillData4Plotting(), SBTest::IsDateModified, NumOfPts, Plot, and Step.
Referenced by stationChange().
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
void SBTestAPLoad::stationChange (QListViewItem *LI) [private, virtual, slot]
Definition at line 2610 of file SbITest.C'.
References SBPlot::dataChanged(), fillData4Plotting(), SBNamed::name(), Plot, PlotCarrier, recalc(), SBNamed::setName(), and Station.
Referenced by auxWidgetRt().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
Member Data Documentation
SBAploEphem* SBTestAPLoad::AploEphem [private]
Definition at line 597 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestAPLoad(), and ~SBTestAPLoad().
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestAPLoad::ENumPts [private]
Definition at line 606 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestAPLoad::EStep [private]
Definition at line 607 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), recalc(), and SBTest::SBTest().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
unsigned int SBTestAPLoad::NumOfPts [private]
Definition at line 601 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestAPLoad().
SBPlot* SBTestAPLoad::Plot [private]
Definition at line 613 of file SbITest.H'.
Referenced by createWidget4Test(), recalc(), and stationChange().
SBPlotCarrier* SBTestAPLoad::PlotCarrier [private]
Definition at line 612 of file SbITest.H'.
Referenced by createWidget4Test(), fillData4Plotting(), SBTestAPLoad(), stationChange(), and ~SBTestAPLoad().
SBStation* SBTestAPLoad::Station [private]
Definition at line 599 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestAPLoad(), and stationChange().
double SBTestAPLoad::Step [private]
Definition at line 602 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestAPLoad().
QListView* SBTestAPLoad::StLV [private]
Definition at line 609 of file SbITest.H'.
Referenced by auxWidgetRt().
QString SBTest::str [protected, inherited]
Reimplemented in SBTestFrame, SBTestNutation, SBTestPrecession, and SBTestMatrix'.
Definition at line 61 of file SbITest.H'.
Referenced by SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEphem::displayCoo(), and SBTest::recalc().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SB_TRF* SBTestAPLoad::TRF [private]
Definition at line 598 of file SbITest.H'.
Referenced by auxWidgetRt(), SBTestAPLoad(), and ~SBTestAPLoad().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.