SBTestOceanTides
NAME
SBTestOceanTides -
SYNOPSIS
#include <SbITest.H>
Inherits SBTest'.
Public Member Functions
SBTestOceanTides (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBTestOceanTides ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
QString str
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Private Slots
virtual void recalc ()
virtual void stationChange (QListViewItem *)
Private Member Functions
void fillData4Plotting ()
virtual QWidget * createWidget4Test (QWidget *)
virtual QWidget * auxWidgetRt (QWidget *)
Private Attributes
SBFrame * Frame
SBOceanTideLd * OceanTide
SB_TRF * TRF
SBStation * Station
Vector3 Vectors [1]
QString VectorNames [1]
unsigned int NumOfPts
unsigned int NumOfVecotors
double Step
QLineEdit * ENumPts
QLineEdit * EStep
QListView * StLV
SBPlotCarrier * PlotCarrier
SBPlot * Plot
Detailed Description
Definition at line 477 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestOceanTides::SBTestOceanTides (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1890 of file SbITest.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::columnNames(), Config, SBPlotCarrier::createBranch(), SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBFrame::eop(), fillData4Plotting(), Frame, SBSetUp::loadTRF(), SBNamed::name(), NumOfPts, NumOfVecotors, OceanTide, PlotCarrier, SB_TRF::prepare4Run(), SBPlotCarrier::setFile4SaveBaseName(), SBEOP::setPtNum(), SBPlotCarrier::setType(), SetUp, Station, SB_TRF::stations(), Step, SBConfig::STR_Classic, SBConfig::STR_NRO, SBConfig::sysTransform(), SBTest::TFinis, SBEOP::tFinis(), TRF, SBTest::TStart, SBEOP::tStart(), v3Zero, VectorNames, and Vectors.
SBTestOceanTides::~SBTestOceanTides () [virtual]
Definition at line 1946 of file SbITest.C'.
References SB_TRF::finisRun(), Frame, OceanTide, PlotCarrier, and TRF.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
QWidget * SBTestOceanTides::auxWidgetRt (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 2017 of file SbITest.C'.
References ENumPts, EStep, NumOfPts, stationChange(), SB_TRF::stations(), Step, StLV, and TRF.
virtual QString SBTestOceanTides::ClassName () const [inline, virtual]
Reimplemented from SBTest'.
Definition at line 484 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestOceanTides::createWidget4Test (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 1974 of file SbITest.C'.
References Plot, and PlotCarrier.
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides().
void SBTestOceanTides::fillData4Plotting () [private]
Definition at line 1979 of file SbITest.C'.
References SBPlotCarrier::branches(), SBFrame::calc(), SBPlotBranch::data(), SBTest::Date, EAST, SBFrame::eop(), SBPlotCarrier::findBranch(), Frame, SBMatrix::nCol(), NORT, SBMatrix::nRow(), NumOfPts, NumOfVecotors, SBStation::oLoad(), SBSite::oLoad(), PlotCarrier, SBEOP::prepare4Date(), SBMatrix::resize(), SBStation::rt(), SBMatrix::set(), SBStation::site(), Station, Step, SBFrame::time(), v3Zero, VectorNames, Vectors, and VERT.
Referenced by recalc(), SBTestOceanTides(), and stationChange().
void SBTestOceanTides::recalc () [private, virtual, slot]
Reimplemented from SBTest'.
Definition at line 2081 of file SbITest.C'.
References SBPlot::dataChanged(), ENumPts, SBFrame::eop(), EStep, fillData4Plotting(), Frame, SBTest::IsDateModified, NumOfPts, Plot, SBEOP::setPtNum(), and Step.
Referenced by stationChange().
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
void SBTestOceanTides::stationChange (QListViewItem *LI) [private, virtual, slot]
Definition at line 2111 of file SbITest.C'.
References SBPlot::dataChanged(), fillData4Plotting(), SBNamed::name(), Plot, PlotCarrier, recalc(), SBNamed::setName(), and Station.
Referenced by auxWidgetRt().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
Member Data Documentation
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestOceanTides::ENumPts [private]
Definition at line 505 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestOceanTides::EStep [private]
Definition at line 506 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
SBFrame* SBTestOceanTides::Frame [private]
Definition at line 492 of file SbITest.H'.
Referenced by fillData4Plotting(), recalc(), SBTestOceanTides(), and ~SBTestOceanTides().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
unsigned int SBTestOceanTides::NumOfPts [private]
Definition at line 499 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestOceanTides().
unsigned int SBTestOceanTides::NumOfVecotors [private]
Definition at line 500 of file SbITest.H'.
Referenced by fillData4Plotting(), and SBTestOceanTides().
SBOceanTideLd* SBTestOceanTides::OceanTide [private]
Definition at line 493 of file SbITest.H'.
Referenced by SBTestOceanTides(), and ~SBTestOceanTides().
SBPlot* SBTestOceanTides::Plot [private]
Definition at line 512 of file SbITest.H'.
Referenced by createWidget4Test(), recalc(), and stationChange().
SBPlotCarrier* SBTestOceanTides::PlotCarrier [private]
Definition at line 511 of file SbITest.H'.
Referenced by createWidget4Test(), fillData4Plotting(), SBTestOceanTides(), stationChange(), and ~SBTestOceanTides().
SBStation* SBTestOceanTides::Station [private]
Definition at line 495 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestOceanTides(), and stationChange().
double SBTestOceanTides::Step [private]
Definition at line 501 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestOceanTides().
QListView* SBTestOceanTides::StLV [private]
Definition at line 508 of file SbITest.H'.
Referenced by auxWidgetRt().
QString SBTest::str [protected, inherited]
Reimplemented in SBTestFrame, SBTestNutation, SBTestPrecession, and SBTestMatrix'.
Definition at line 61 of file SbITest.H'.
Referenced by SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEphem::displayCoo(), and SBTest::recalc().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SB_TRF* SBTestOceanTides::TRF [private]
Definition at line 494 of file SbITest.H'.
Referenced by auxWidgetRt(), SBTestOceanTides(), and ~SBTestOceanTides().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
QString SBTestOceanTides::VectorNames[1] [private]
Definition at line 497 of file SbITest.H'.
Referenced by fillData4Plotting(), and SBTestOceanTides().
Vector3 SBTestOceanTides::Vectors[1] [private]
Definition at line 496 of file SbITest.H'.
Referenced by fillData4Plotting(), and SBTestOceanTides().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.