SBTestSolidTides
NAME
SBTestSolidTides -
SYNOPSIS
#include <SbITest.H>
Inherits SBTest'.
Public Member Functions
SBTestSolidTides (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBTestSolidTides ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
QString str
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Private Slots
virtual void recalc ()
virtual void stationChange (QListViewItem *)
Private Member Functions
void fillData4Plotting ()
virtual QWidget * createWidget4Test (QWidget *)
virtual QWidget * auxWidgetRt (QWidget *)
Private Attributes
SBFrame * Frame
SBEphem * Ephem
SBSolidTideLd * SolidTide
SB_TRF * TRF
SBStation * Station
Vector3 Vectors [7]
QString VectorNames [7]
unsigned int NumOfPts
unsigned int NumOfVecotors
double Step
QLineEdit * ENumPts
QLineEdit * EStep
QListView * StLV
SBPlotCarrier * PlotCarrier
SBPlot * Plot
Detailed Description
Definition at line 425 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestSolidTides::SBTestSolidTides (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1587 of file SbITest.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::columnNames(), Config, SBPlotCarrier::createBranch(), SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBConfig::EM_LEDE200, SBConfig::EM_LEDE403, SBConfig::EM_LEDE405, SBFrame::eop(), Ephem, SBConfig::ephemModel(), fillData4Plotting(), Frame, SBSetUp::loadTRF(), SBNamed::name(), NumOfPts, NumOfVecotors, PlotCarrier, SB_TRF::prepare4Run(), SBPlotCarrier::setFile4SaveBaseName(), SBEOP::setPtNum(), SBPlotCarrier::setType(), SetUp, SolidTide, SBConfig::solidTideLd(), SBConfig::ST_IERS92, SBConfig::ST_IERS96, Station, SB_TRF::stations(), Step, SBConfig::STR_Classic, SBConfig::STR_NRO, SBConfig::sysTransform(), SBTest::TFinis, SBEphem::tFinis(), SBEOP::tFinis(), TRF, SBTest::TStart, SBEphem::tStart(), SBEOP::tStart(), v3Zero, VectorNames, and Vectors.
SBTestSolidTides::~SBTestSolidTides () [virtual]
Definition at line 1673 of file SbITest.C'.
References Ephem, SB_TRF::finisRun(), Frame, PlotCarrier, SolidTide, and TRF.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
QWidget * SBTestSolidTides::auxWidgetRt (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 1774 of file SbITest.C'.
References ENumPts, EStep, NumOfPts, stationChange(), SB_TRF::stations(), Step, StLV, and TRF.
virtual QString SBTestSolidTides::ClassName () const [inline, virtual]
Reimplemented from SBTest'.
Definition at line 432 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestSolidTides::createWidget4Test (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 1707 of file SbITest.C'.
References Plot, and PlotCarrier.
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides().
void SBTestSolidTides::fillData4Plotting () [private]
Definition at line 1712 of file SbITest.C'.
References SBPlotCarrier::branches(), SBEphem::calc(), SBFrame::calc(), SBPlotBranch::data(), SBTest::Date, EAST, SBFrame::eop(), Ephem, SBPlotCarrier::findBranch(), SBStation::fmVEN(), Frame, SBMatrix::nCol(), NORT, SBMatrix::nRow(), NumOfPts, NumOfVecotors, PlotCarrier, SBEOP::prepare4Date(), SBMatrix::resize(), SBStation::rt(), SBMatrix::set(), SolidTide, Station, Step, SBSolidTideLd::step1(), SBSolidTideLd::step2(), SBTime::TDB(), SBSolidTideLd::tideDeg2ip(), SBSolidTideLd::tideDeg2op(), SBSolidTideLd::tideDeg3ip(), SBSolidTideLd::tideLatDepend(), SBFrame::time(), v3Zero, VectorNames, Vectors, VERT, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by recalc(), SBTestSolidTides(), and stationChange().
void SBTestSolidTides::recalc () [private, virtual, slot]
Reimplemented from SBTest'.
Definition at line 1838 of file SbITest.C'.
References SBPlot::dataChanged(), ENumPts, SBFrame::eop(), EStep, fillData4Plotting(), Frame, SBTest::IsDateModified, NumOfPts, Plot, SBEOP::setPtNum(), and Step.
Referenced by stationChange().
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
void SBTestSolidTides::stationChange (QListViewItem *LI) [private, virtual, slot]
Definition at line 1868 of file SbITest.C'.
References SBPlot::dataChanged(), fillData4Plotting(), SBNamed::name(), Plot, PlotCarrier, recalc(), SBNamed::setName(), and Station.
Referenced by auxWidgetRt().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
Member Data Documentation
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestSolidTides::ENumPts [private]
Definition at line 454 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
SBEphem* SBTestSolidTides::Ephem [private]
Definition at line 441 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestSolidTides(), and ~SBTestSolidTides().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestSolidTides::EStep [private]
Definition at line 455 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
SBFrame* SBTestSolidTides::Frame [private]
Definition at line 440 of file SbITest.H'.
Referenced by fillData4Plotting(), recalc(), SBTestSolidTides(), and ~SBTestSolidTides().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTestEOP::recalc(), SBTestDiurnEOP::recalc(), recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
unsigned int SBTestSolidTides::NumOfPts [private]
Definition at line 448 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestSolidTides().
unsigned int SBTestSolidTides::NumOfVecotors [private]
Definition at line 449 of file SbITest.H'.
Referenced by fillData4Plotting(), and SBTestSolidTides().
SBPlot* SBTestSolidTides::Plot [private]
Definition at line 461 of file SbITest.H'.
Referenced by createWidget4Test(), recalc(), and stationChange().
SBPlotCarrier* SBTestSolidTides::PlotCarrier [private]
Definition at line 460 of file SbITest.H'.
Referenced by createWidget4Test(), fillData4Plotting(), SBTestSolidTides(), stationChange(), and ~SBTestSolidTides().
SBSolidTideLd* SBTestSolidTides::SolidTide [private]
Definition at line 442 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestSolidTides(), and ~SBTestSolidTides().
SBStation* SBTestSolidTides::Station [private]
Definition at line 444 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestSolidTides(), and stationChange().
double SBTestSolidTides::Step [private]
Definition at line 450 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestSolidTides().
QListView* SBTestSolidTides::StLV [private]
Definition at line 457 of file SbITest.H'.
Referenced by auxWidgetRt().
QString SBTest::str [protected, inherited]
Reimplemented in SBTestFrame, SBTestNutation, SBTestPrecession, and SBTestMatrix'.
Definition at line 61 of file SbITest.H'.
Referenced by SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEphem::displayCoo(), and SBTest::recalc().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SB_TRF* SBTestSolidTides::TRF [private]
Definition at line 443 of file SbITest.H'.
Referenced by auxWidgetRt(), SBTestSolidTides(), and ~SBTestSolidTides().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
QString SBTestSolidTides::VectorNames[7] [private]
Definition at line 446 of file SbITest.H'.
Referenced by fillData4Plotting(), and SBTestSolidTides().
Vector3 SBTestSolidTides::Vectors[7] [private]
Definition at line 445 of file SbITest.H'.
Referenced by fillData4Plotting(), and SBTestSolidTides().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.