SBTestEOP
NAME
SBTestEOP -
SYNOPSIS
#include <SbITest.H>
Inherits SBTest'.
Public Member Functions
SBTestEOP (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBTestEOP ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
virtual void createWidgets ()
virtual SBMJD * tStart ()
virtual SBMJD * tFinis ()
Protected Attributes
QString str
SBMJD * Date
SBMJD * TStart
SBMJD * TFinis
QLabel * LMJD
QLabel * LDate
QLabel * LRange
QLineEdit * EYear
QLineEdit * EMonth
QLineEdit * EDay
QLineEdit * EHour
QLineEdit * EMin
QLineEdit * ESec
bool IsDateModified
Private Slots
virtual void recalc ()
Private Member Functions
void fillData4Plotting ()
virtual QWidget * createWidget4Test (QWidget *)
virtual QWidget * auxWidgetRt (QWidget *)
Private Attributes
SBEOP * Weop
SBTime * Time
SBNutThGeneral * Theory
unsigned int NumOfPts
unsigned int NumOfSplines
double Step
QLineEdit * ENumPts
QLineEdit * EStep
QLabel * LNumOfSplines
SBPlotCarrier * PlotCarrier
SBPlot * Plot
Detailed Description
Definition at line 303 of file SbITest.H'.
Constructor & Destructor Documentation
SBTestEOP::SBTestEOP (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1100 of file SbITest.C'.
References SBPlotCarrier::AT_MJD, SBPlotCarrier::columnNames(), Config, SBPlotCarrier::createBranch(), SBTest::createWidgets(), SBMJD::currentMJD(), SBTest::Date, SBConfig::eopNumIntrplPoints(), fillData4Plotting(), SBEOP::label(), SBSetUp::loadEOP(), SBConfig::NM_IAU1980, SBConfig::NM_IAU1996, SBConfig::NM_IAU2000, NumOfPts, NumOfSplines, SBConfig::nutModel(), PlotCarrier, SBPlotCarrier::setFile4SaveBaseName(), SBEOP::setPtNum(), SBPlotCarrier::setType(), SetUp, Step, SBTest::TFinis, SBEOP::tFinis(), Theory, Time, SBSolutionName::toString(), SBTest::TStart, SBEOP::tStart(), and Weop.
SBTestEOP::~SBTestEOP () [virtual]
Definition at line 1158 of file SbITest.C'.
References PlotCarrier, Theory, Time, and Weop.
Member Function Documentation
void SBTest::accept () [protected, slot, inherited]
Definition at line 230 of file SbITest.C'.
Referenced by SBTest::createWidgets().
QWidget * SBTestEOP::auxWidgetRt (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 1256 of file SbITest.C'.
References ENumPts, EStep, LNumOfSplines, NumOfPts, NumOfSplines, and Step.
virtual QString SBTestEOP::ClassName () const [inline, virtual]
Reimplemented from SBTest'.
Definition at line 310 of file SbITest.H'.
virtual void SBTest::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Definition at line 61 of file SbITest.H'.
QWidget * SBTestEOP::createWidget4Test (QWidget *parent) [private, virtual]
Reimplemented from SBTest'.
Definition at line 1186 of file SbITest.C'.
References Plot, and PlotCarrier.
void SBTest::createWidgets () [protected, virtual, inherited]
Definition at line 76 of file SbITest.C'.
References SBTest::accept(), SBTest::auxWidgetRt(), SBTest::createWidget4Test(), SBTest::Date, SBMJD::day(), SBTest::EDay, SBTest::EHour, SBTest::EMin, SBTest::EMonth, SBTest::ESec, SBTest::EYear, SBMJD::F_DDMonYYYY, SBMJD::F_Short, SBMJD::hour(), SBTest::LDate, SBTest::LMJD, SBTest::LRange, SBMJD::min(), SBMJD::month(), SBTest::recalc(), SBTest::reject(), SBMJD::sec(), SBTest::str, SBTest::tFinis(), SBMJD::toString(), SBTest::tStart(), and SBMJD::year().
Referenced by SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), and SBTestSolidTides::SBTestSolidTides().
void SBTestEOP::fillData4Plotting () [private]
Definition at line 1191 of file SbITest.C'.
References SBMatrix::at(), SBPlotCarrier::branches(), SBEOP::cache4Interpolation(), SBNutThGeneral::calc(), SBTest::Date, DAY2SEC, SBNutThGeneral::deltaEps(), SBNutThGeneral::deltaPsi(), SBEOP::dEps(), SBEOP::dLOD(), SBEOP::dPsi(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBEOP::interpolateEOPs(), SBMatrix::nCol(), SBMatrix::nRow(), NumOfPts, NumOfSplines, PlotCarrier, SBEOP::prepare4Date(), SBMatrix::resize(), SEC2RAD, SBMatrix::set(), SBEOP::setPtNum(), SBTime::setUTC(), Step, Theory, SBMJD::time(), Time, and Weop.
Referenced by recalc(), and SBTestEOP().
void SBTestEOP::recalc () [private, virtual, slot]
Reimplemented from SBTest'.
Definition at line 1294 of file SbITest.C'.
References SBPlot::dataChanged(), ENumPts, EStep, fillData4Plotting(), SBTest::IsDateModified, LNumOfSplines, NumOfPts, NumOfSplines, Plot, and Step.
void SBTest::reject () [protected, slot, inherited]
Definition at line 236 of file SbITest.C'.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tFinis () [inline, protected, virtual, inherited]
Definition at line 84 of file SbITest.H'.
References SBTest::TFinis.
Referenced by SBTest::createWidgets().
virtual SBMJD* SBTest::tStart () [inline, protected, virtual, inherited]
Definition at line 83 of file SbITest.H'.
References SBTest::TStart.
Referenced by SBTest::createWidgets().
Member Data Documentation
SBMJD* SBTest::Date [protected, inherited]
Definition at line 64 of file SbITest.H'.
Referenced by SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBTest::createWidgets(), fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBTestEphem::frameChanged(), SBTest::recalc(), SBTestPrecession::recalc(), SBTestNutation::recalc(), SBTestFrame::recalc(), SBTestEphem::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and SBTest::~SBTest().
QLineEdit* SBTest::EDay [protected, inherited]
Definition at line 74 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EHour [protected, inherited]
Definition at line 75 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMin [protected, inherited]
Definition at line 76 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTest::EMonth [protected, inherited]
Definition at line 73 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestEOP::ENumPts [private]
Definition at line 323 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLineEdit* SBTest::ESec [protected, inherited]
Definition at line 77 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLineEdit* SBTestEOP::EStep [private]
Definition at line 324 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLineEdit* SBTest::EYear [protected, inherited]
Definition at line 72 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
bool SBTest::IsDateModified [protected, inherited]
Definition at line 78 of file SbITest.H'.
Referenced by SBTest::recalc(), recalc(), SBTestDiurnEOP::recalc(), SBTestSolidTides::recalc(), SBTestOceanTides::recalc(), SBTestPolarTides::recalc(), SBTestAPLoad::recalc(), and SBTest::SBTest().
QLabel* SBTest::LDate [protected, inherited]
Definition at line 70 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTest::LMJD [protected, inherited]
Definition at line 69 of file SbITest.H'.
Referenced by SBTest::createWidgets(), and SBTest::recalc().
QLabel* SBTestEOP::LNumOfSplines [private]
Definition at line 325 of file SbITest.H'.
Referenced by auxWidgetRt(), and recalc().
QLabel* SBTest::LRange [protected, inherited]
Definition at line 71 of file SbITest.H'.
Referenced by SBTest::createWidgets().
unsigned int SBTestEOP::NumOfPts [private]
Definition at line 320 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestEOP().
unsigned int SBTestEOP::NumOfSplines [private]
Definition at line 321 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestEOP().
SBPlot* SBTestEOP::Plot [private]
Definition at line 328 of file SbITest.H'.
Referenced by createWidget4Test(), and recalc().
SBPlotCarrier* SBTestEOP::PlotCarrier [private]
Definition at line 327 of file SbITest.H'.
Referenced by createWidget4Test(), fillData4Plotting(), SBTestEOP(), and ~SBTestEOP().
double SBTestEOP::Step [private]
Definition at line 322 of file SbITest.H'.
Referenced by auxWidgetRt(), fillData4Plotting(), recalc(), and SBTestEOP().
QString SBTest::str [protected, inherited]
Reimplemented in SBTestFrame, SBTestNutation, SBTestPrecession, and SBTestMatrix'.
Definition at line 61 of file SbITest.H'.
Referenced by SBTestEphem::createWidget4Test(), SBTest::createWidgets(), SBTestEphem::displayCoo(), and SBTest::recalc().
SBMJD* SBTest::TFinis [protected, inherited]
Definition at line 66 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tFinis(), and SBTest::~SBTest().
SBNutThGeneral* SBTestEOP::Theory [private]
Definition at line 319 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestEOP(), and ~SBTestEOP().
SBTime* SBTestEOP::Time [private]
Definition at line 318 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestEOP(), and ~SBTestEOP().
SBMJD* SBTest::TStart [protected, inherited]
Definition at line 65 of file SbITest.H'.
Referenced by SBTest::recalc(), SBTest::SBTest(), SBTestAPLoad::SBTestAPLoad(), SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBTest::tStart(), and SBTest::~SBTest().
SBEOP* SBTestEOP::Weop [private]
Definition at line 317 of file SbITest.H'.
Referenced by fillData4Plotting(), SBTestEOP(), and ~SBTestEOP().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.