SBTime
NAME
SBTime -
SYNOPSIS
#include <SbGeoTime.H>
Inherits SBMJD'.
Public Types
enum Format { F_YYYYMMDD, F_DDMonYYYY, F_Short, F_Long, F_Year, F_YYMonDD, F_HHMMSS, F_YYYYMMDDSSSSSS, F_INTERNAL, F_YYYYMMDDHHMMSSSS, F_DateShort, F_TimeShort, F_TimeVShort, F_ECCDAT, F_MJD, F_UNIX, F_SINEX, F_SINEX_S }
Public Member Functions
virtual QString ClassName () const
SBTime (SBEOP *=NULL)
SBTime (const SBTime &)
virtual ~SBTime ()
void setEOP (SBEOP *EOP_)
SBEOP * eop ()
virtual double fArg (int i) const
virtual void fArgs (double A[6]) const
virtual double fArg_l () const
virtual double fArg_lPrime () const
virtual double fArg_F () const
virtual double fArg_D () const
virtual double fArg_Omega () const
virtual double fArg_theta () const
virtual double omega () const
virtual void setUTC (const SBMJD &UTC_)
virtual double TAI_UTC () const
virtual SBMJD UTC () const
virtual SBMJD TAI () const
virtual SBMJD TT () const
virtual SBMJD UT1 () const
virtual SBMJD TDB () const
virtual void setMJD (int, int, int, int=0, int=0, double=0.0, bool=TRUE)
virtual void setMJD (Format, QString, bool=TRUE)
virtual void setDate (int Date_)
virtual void setTime (long double Time_)
virtual QString toString (Format=F_Short) const
virtual bool isGood ()
virtual operator long double () const
virtual bool operator== (const SBMJD &) const
virtual bool operator!= (const SBMJD &) const
virtual bool operator< (const SBMJD &) const
virtual bool operator<= (const SBMJD &) const
virtual bool operator> (const SBMJD &) const
virtual bool operator> (double) const
virtual bool operator>= (const SBMJD &) const
virtual SBMJD & operator+= (const SBMJD &MJD)
virtual SBMJD & operator-= (const SBMJD &MJD)
int date () const
long double time () const
int year () const
int month () const
int hour () const
int min () const
double sec () const
QString month2Str () const
int day () const
int dayOfYear () const
int dayOfWeek () const
QString dayOfWeek2Str () const
Static Public Member Functions
static int MJD_date (int, int, int)
static long double MJD_time (int, int, double)
static void MJD_rev (int, long double, int &, int &, int &, int &, int &, double &)
static SBMJD currentMJD ()
Static Public Attributes
static const double fTT_TAI = 32.184/DAY2SEC
Protected Member Functions
virtual void DefineTAI_UTC ()
virtual void FundamentalArgs ()
virtual void Zero ()
Protected Attributes
double fTAI_UTC
double fUT1_UTC
double fUT1_UT1R
double fTDB_TDT
double FArgs [6]
double Omega
SBEOP * EOP
Static Protected Attributes
static const char * monthNames []
static const char * weekdayNames []
Friends
SBMJD operator+ (const SBMJD &, const SBMJD &)
SBMJD operator+ (const SBMJD &, long double)
SBMJD operator+ (const SBMJD &, double)
SBMJD operator+ (const SBMJD &, float)
SBMJD operator+ (long double, const SBMJD &)
SBMJD operator+ (double, const SBMJD &)
SBMJD operator+ (float, const SBMJD &)
SBMJD operator- (const SBMJD &, const SBMJD &)
SBMJD operator- (const SBMJD &, long double)
SBMJD operator- (const SBMJD &, double)
SBMJD operator- (long double, const SBMJD &)
SBMJD operator- (int, const SBMJD &)
QDataStream & operator<< (QDataStream &, const SBMJD &)
QDataStream & operator>> (QDataStream &, SBMJD &)
Detailed Description
Definition at line 144 of file SbGeoTime.H'.
Member Enumeration Documentation
enum SBMJD::Format [inherited]
Enumerator:
F_YYYYMMDD
F_DDMonYYYY
F_Short
F_Long
F_Year
F_YYMonDD
F_HHMMSS
F_YYYYMMDDSSSSSS
F_INTERNAL
F_YYYYMMDDHHMMSSSS
F_DateShort
F_TimeShort
F_TimeVShort
F_ECCDAT
F_MJD
F_UNIX
F_SINEX
F_SINEX_S
Definition at line 49 of file SbGeoTime.H'.
Constructor & Destructor Documentation
SBTime::SBTime (SBEOP *EOP_ = NULL)
Definition at line 574 of file SbGeoTime.C'.
References EOP, and Zero().
SBTime::SBTime (const SBTime &T)
Definition at line 580 of file SbGeoTime.C'.
References EOP, FArgs, fTAI_UTC, fUT1_UT1R, and fUT1_UTC.
virtual SBTime::~SBTime () [inline, virtual]
Definition at line 165 of file SbGeoTime.H'.
References EOP.
Member Function Documentation
virtual QString SBTime::ClassName () const [inline, virtual]
Reimplemented from SBMJD'.
Definition at line 161 of file SbGeoTime.H'.
Referenced by setUTC().
SBMJD SBMJD::currentMJD () [static, inherited]
Definition at line 134 of file SbGeoTime.C'.
Referenced by operator<<(), SBRunManager::process_m1(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and writeNormalEquationSystem().
int SBMJD::date () const [inline, inherited]
Definition at line 121 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBNutation::calcGST(), DefineTAI_UTC(), SBRunManager::loadVLBISession_m1(), operator<<(), operator>>(), SBTestEphem::recalc(), and setUTC().
int SBMJD::day () const [inherited]
Definition at line 208 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), operator<<(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
int SBMJD::dayOfWeek () const [inherited]
Definition at line 225 of file SbGeoTime.C'.
References SBMJD::Date, and SBMJD::SBMJD().
Referenced by SBMJD::dayOfWeek2Str().
QString SBMJD::dayOfWeek2Str () const [inherited]
Definition at line 231 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::dayOfWeek(), and SBMJD::weekdayNames.
Referenced by SBMJD::toString().
int SBMJD::dayOfYear () const [inherited]
Definition at line 220 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), and SBMJD::year().
Referenced by SBHMf_NMF::operator()(), and SBMJD::toString().
void SBTime::DefineTAI_UTC () [protected, virtual]
Definition at line 611 of file SbGeoTime.C'.
References SBMJD::date(), DAY2SEC, and fTAI_UTC.
Referenced by setUTC().
SBEOP* SBTime::eop () [inline]
Definition at line 168 of file SbGeoTime.H'.
References EOP.
virtual double SBTime::fArg (inti) const [inline, virtual]
Definition at line 170 of file SbGeoTime.H'.
References FArgs.
virtual double SBTime::fArg_D () const [inline, virtual]
Definition at line 178 of file SbGeoTime.H'.
References FArgs.
Referenced by SBSTideUT1::calc(), SBOTideEOPGenS::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBOTideEOPRay1994_2003::calc(), SBATideEOP_BBP_02::calc(), SBNonTideEOP_Viron_02::calc(), SBGravTideEOP_B_02::calc(), SBNut_IAU2000::calcGST(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), and SBSolidTideLdIERS96::makeStep2().
virtual double SBTime::fArg_F () const [inline, virtual]
Definition at line 177 of file SbGeoTime.H'.
References FArgs.
Referenced by SBSTideUT1::calc(), SBOTideEOPGenS::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBOTideEOPRay1994_2003::calc(), SBATideEOP_BBP_02::calc(), SBNonTideEOP_Viron_02::calc(), SBGravTideEOP_B_02::calc(), SBNut_IAU2000::calcGST(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), and SBSolidTideLdIERS96::makeStep2().
virtual double SBTime::fArg_l () const [inline, virtual]
Definition at line 175 of file SbGeoTime.H'.
References FArgs.
Referenced by SBSTideUT1::calc(), SBOTideEOPGenS::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBOTideEOPRay1994_2003::calc(), SBATideEOP_BBP_02::calc(), SBNonTideEOP_Viron_02::calc(), SBGravTideEOP_B_02::calc(), SBNut_IAU2000::calcGST(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), and SBSolidTideLdIERS96::makeStep2().
virtual double SBTime::fArg_lPrime () const [inline, virtual]
Definition at line 176 of file SbGeoTime.H'.
References FArgs.
Referenced by SBSTideUT1::calc(), SBOTideEOPGenS::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBOTideEOPRay1994_2003::calc(), SBATideEOP_BBP_02::calc(), SBNonTideEOP_Viron_02::calc(), SBGravTideEOP_B_02::calc(), SBNut_IAU2000::calcGST(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBNut_IAU1980::geodesicNutation(), SBPrecNutNRO::geodesicNutation(), and SBSolidTideLdIERS96::makeStep2().
virtual double SBTime::fArg_Omega () const [inline, virtual]
Definition at line 179 of file SbGeoTime.H'.
References FArgs.
Referenced by SBSTideUT1::calc(), SBOTideEOPGenS::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBOTideEOPRay1994_2003::calc(), SBATideEOP_BBP_02::calc(), SBNonTideEOP_Viron_02::calc(), SBGravTideEOP_B_02::calc(), SBNut_IAU2000::calcGST(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBSolidTideLdIERS96::makeStep2(), SBOceanTideLd::operator()(), and SBNut_IAU1980::operator()().
virtual double SBTime::fArg_theta () const [inline, virtual]
Definition at line 180 of file SbGeoTime.H'.
References FArgs.
Referenced by SBOTideEOPGenS::calc(), SBOTideEOPRay1994_2003::calc(), SBATideEOP_BBP_02::calc(), SBNonTideEOP_Viron_02::calc(), SBGravTideEOP_B_02::calc(), SBTestFrame::createWidget4Test(), and SBTestFrame::displayValues().
virtual void SBTime::fArgs (doubleA[6]) const [inline, virtual]
Definition at line 171 of file SbGeoTime.H'.
References FArgs.
void SBTime::FundamentalArgs () [protected, virtual]
Definition at line 634 of file SbGeoTime.C'.
References FArgs, Omega, SEC2RAD, TEphem, TT(), and UTC().
Referenced by setUTC().
int SBMJD::hour () const [inherited]
Definition at line 167 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
virtual bool SBMJD::isGood () [inline, virtual, inherited]
Definition at line 87 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBSourceEditor::acquireData(), SBAploChunk::import(), SBEcc::importEccDat(), operator>>(), and SBVLBISession::parseObsDumpString().
int SBMJD::min () const [inherited]
Definition at line 179 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
int SBMJD::MJD_date (inty, intm, intd) [static, inherited]
Definition at line 72 of file SbGeoTime.C'.
Referenced by SBMJD::dayOfYear(), and SBMJD::setMJD().
void SBMJD::MJD_rev (intdate_, long doubletime_, int &y, int &m, int &d, int &hr, int &mi, double &se) [static, inherited]
Definition at line 95 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::day(), SBMJD::hour(), SBMJD::min(), SBMJD::month(), SBMJD::sec(), SBMJD::toString(), and SBMJD::year().
long double SBMJD::MJD_time (intHour, intMin, doubleSec) [static, inherited]
Definition at line 90 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::setMJD().
int SBMJD::month () const [inherited]
Definition at line 155 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBMJD::month2Str(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
QString SBMJD::month2Str () const [inherited]
Definition at line 203 of file SbGeoTime.C'.
References SBMJD::month(), and SBMJD::monthNames.
Referenced by operator<<().
virtual double SBTime::omega () const [inline, virtual]
Definition at line 181 of file SbGeoTime.H'.
References Omega.
Referenced by SBDelay::calcDerivatives(), SBEOP::dUT1_UTC(), SBEOP::dX(), and SBEOP::dY().
virtual SBMJD::operator long double () const [inline, virtual, inherited]
Definition at line 89 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator!= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 206 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator+= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 254 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator-= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 262 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator< (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 211 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator<= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 217 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator== (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 201 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator> (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 223 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator> (doubled) const [inline, virtual, inherited]
Definition at line 229 of file SbGeoTime.H'.
References SBMJD::SBMJD().
bool SBMJD::operator>= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 234 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
double SBMJD::sec () const [inherited]
Definition at line 191 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
virtual void SBMJD::setDate (intDate_) [inline, virtual, inherited]
Definition at line 81 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBAploChunk::import().
void SBTime::setEOP (SBEOP *EOP_) [inline]
Definition at line 167 of file SbGeoTime.H'.
References EOP.
Referenced by SBFrame::SBFrame(), and SBTestNutation::SBTestNutation().
void SBMJD::setMJD (intYear, intMonth, intDay, intHour = 0, intMin = 0, doubleSec = 0.0, bool = TRUE) [virtual, inherited]
Definition at line 64 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), SBMJD::MJD_time(), and SBMJD::Time.
Referenced by SBStuffEOPs::accept(), SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBEcc::importEccDat(), operator>>(), SBVLBISession::parseObsDumpString(), SBTest::recalc(), SBStationInfo::restoreUserInfo(), SBMJD::SBMJD(), and SBMJD::setMJD().
void SBMJD::setMJD (FormatF, QStrings, boolisReset = TRUE) [virtual, inherited]
Definition at line 357 of file SbGeoTime.C'.
References SBMJD::ClassName(), SBMJD::Date, SBLog::ERR, SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::INF, Log, SBMJD::min(), SBMJD::MJD_date(), SBMJD::monthNames, SBMJD::sec(), SBMJD::setMJD(), SBMJD::Time, SBLog::TIME, SBLog::write(), and SBLog::WRN.
virtual void SBMJD::setTime (long doubleTime_) [inline, virtual, inherited]
Definition at line 82 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBAploChunk::import().
void SBTime::setUTC (const SBMJD &UTC_) [virtual]
Definition at line 694 of file SbGeoTime.C'.
References ClassName(), SBMJD::date(), DAY2SEC, SBLog::DBG, DefineTAI_UTC(), DEG2RAD, SBEOP::dUT1_UTC(), EOP, FArgs, fTAI_UTC, fTDB_TDT, FundamentalArgs(), fUT1_UTC, SBLog::isEligible(), Log, SBMJD::operator=(), rad2dmslStr(), rad2hmsStr(), TAI(), TDB(), TEphem, SBLog::TIME, SBMJD::toString(), TT(), UT1(), and SBLog::write().
Referenced by SBFrameClassic::calc(), SBFrameNRO::calc(), SBTestPrecession::createWidget4Test(), SBTestNutation::createWidget4Test(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestPrecession::recalc(), and SBTestNutation::recalc().
virtual SBMJD SBTime::TAI () const [inline, virtual]
Definition at line 186 of file SbGeoTime.H'.
References fTAI_UTC, and SBMJD::SBMJD().
Referenced by SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), SBSolidTideLd::operator()(), SBTideLd::operator()(), and setUTC().
virtual double SBTime::TAI_UTC () const [inline, virtual]
Definition at line 184 of file SbGeoTime.H'.
References fTAI_UTC.
virtual SBMJD SBTime::TDB () const [inline, virtual]
Definition at line 189 of file SbGeoTime.H'.
References fTAI_UTC, fTDB_TDT, fTT_TAI, and SBMJD::SBMJD().
Referenced by SBDelay::calc(), SBTestSolidTides::fillData4Plotting(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), and setUTC().
long double SBMJD::time () const [inline, inherited]
Definition at line 122 of file SbGeoTime.H'.
References SBMJD::Time.
Referenced by SBOceanTideLd::ARG_IERS(), SBNutation::calcGST(), and SBTestEOP::fillData4Plotting().
QString SBMJD::toString (FormatF = F_Short) const [virtual, inherited]
Definition at line 243 of file SbGeoTime.C'.
References SBMJD::Date, DAY2SEC, SBMJD::dayOfWeek2Str(), SBMJD::dayOfYear(), SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_MJD, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_UNIX, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBMJD::F_YYYYMMDDSSSSSS, SBMJD::min(), SBMJD::MJD_rev(), SBMJD::monthNames, SBMJD::sec(), SBMJD::Time, TUnix0, TZero, and SBMJD::year().
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBEphem::calcI(), SBRunManager::checkParameterLists(), SBEOP::checkRanges(), SBStuffEOPs::createInfoGroup(), SBTestFrame::createWidget4Test(), SBTest::createWidgets(), SBStationEditor::delCoordinates(), SBStuffStationsEcc::deleteEntry(), SBStaParsEditor::deleteEntry(), SBEOP::dEps(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), SBEOP::dLOD(), SBEOP::dPsi(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBPlotArea::drawXmjdTics(), SBDBHHistTriplet::dump(), SBDBHStartBlock::dump(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBVLBIPreProcess::fillSessAttr(), SBEstimator::GroupList::find(), SBStochParameter::find(), SBAploEphem::getReady(), SBEphem::import(), SBEstimator::GroupList::inSort(), SBEOP::interpolateEOPs(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBSolutionBatchLI::key(), SBObsVLBIStatRecordLI::key(), SBEccListItem::key(), SBCoordsListItem::key(), SBAploHeaderLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBAploHeader::name(), SBEphem::openFile(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), operator<<(), operator>>(), SBEOP::prepare4Date(), SBTest::recalc(), SBStationEcc::registerEcc(), SBEstimator::GroupList::remove(), SBParameterList::report(), SBStochParameter::report(), SBStuffAplo::SBStuffAplo(), SBStuffEphem::SBStuffEphem(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), setUTC(), sinex_HeaderLine(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_SiteEccentricityBlock(), sinex_SolutionEpochsBlock(), sinex_tro_HeaderLine(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBVLBIObsPPLI::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBObsVLBIStatRecordLI::text(), SBEccListItem::text(), SBVLBIObsLI::text(), SBCoordsListItem::text(), SBAploHeaderLI::text(), SBClockBreakLI::text(), SBParameter::timeStamp(), SBStuffEOPs::updateEOP(), SBStuffEphem::updateEphem(), SBStuffAplo::updateEphem(), SBVLBIPreProcess::wAttributes(), SBVLBISessionEditor::wParameters(), and SBSourceEditor::wStats().
virtual SBMJD SBTime::TT () const [inline, virtual]
Definition at line 187 of file SbGeoTime.H'.
References fTAI_UTC, fTT_TAI, and SBMJD::SBMJD().
Referenced by SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBNROThIAU2000A::calc(), SBOTideEOPRay1994_1996::calc(), SBNut_IAU2000::calcGST(), SBTestFrame::createWidget4Test(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), FundamentalArgs(), SBPrec_IAU1976::operator()(), SBPrec_IAU2000::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolusNRO::operator()(), and setUTC().
virtual SBMJD SBTime::UT1 () const [inline, virtual]
Definition at line 188 of file SbGeoTime.H'.
References fUT1_UTC, and SBMJD::SBMJD().
Referenced by SBOceanTideLd::ARG_IERS(), SBFrameClassic::calc(), SBFrameNRO::calc(), SBNutation::calcGST(), SBNut_IAU2000::calcGST(), SBTestFrame::createWidget4Test(), SBTestFrame::displayValues(), and setUTC().
virtual SBMJD SBTime::UTC () const [inline, virtual]
Definition at line 185 of file SbGeoTime.H'.
Referenced by FundamentalArgs(), and SBPolus::operator()().
int SBMJD::year () const [inherited]
Definition at line 143 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBVLBISesInfo::checkPath(), SBTest::createWidgets(), SBMJD::dayOfYear(), SBVLBISesInfo::fileName(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), and SBMJD::toString().
void SBTime::Zero () [protected, virtual]
Definition at line 595 of file SbGeoTime.C'.
References FArgs, fTAI_UTC, fTDB_TDT, fUT1_UT1R, fUT1_UTC, and Omega.
Referenced by SBTime().
Friends And Related Function Documentation
SBMJD operator+ (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 270 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 275 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 280 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, floatb) [friend, inherited]
Definition at line 285 of file SbGeoTime.H'.
SBMJD operator+ (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 290 of file SbGeoTime.H'.
SBMJD operator+ (doublea, const SBMJD &B) [friend, inherited]
Definition at line 295 of file SbGeoTime.H'.
SBMJD operator+ (floata, const SBMJD &B) [friend, inherited]
Definition at line 300 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 305 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 310 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 315 of file SbGeoTime.H'.
SBMJD operator- (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 320 of file SbGeoTime.H'.
SBMJD operator- (inta, const SBMJD &B) [friend, inherited]
Definition at line 325 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBMJD &MJD) [friend, inherited]
Definition at line 330 of file SbGeoTime.H'.
QDataStream& operator>> (QDataStream &s, SBMJD &MJD) [friend, inherited]
Definition at line 337 of file SbGeoTime.H'.
Member Data Documentation
SBEOP* SBTime::EOP [protected]
Definition at line 158 of file SbGeoTime.H'.
Referenced by eop(), SBTime(), setEOP(), setUTC(), and ~SBTime().
double SBTime::FArgs[6] [protected]
Definition at line 152 of file SbGeoTime.H'.
Referenced by fArg(), fArg_D(), fArg_F(), fArg_l(), fArg_lPrime(), fArg_Omega(), fArg_theta(), fArgs(), FundamentalArgs(), SBTime(), setUTC(), and Zero().
double SBTime::fTAI_UTC [protected]
Definition at line 147 of file SbGeoTime.H'.
Referenced by DefineTAI_UTC(), SBTime(), setUTC(), TAI(), TAI_UTC(), TDB(), TT(), and Zero().
double SBTime::fTDB_TDT [protected]
Definition at line 150 of file SbGeoTime.H'.
Referenced by setUTC(), TDB(), and Zero().
const double SBTime::fTT_TAI = 32.184/DAY2SEC [static]
Definition at line 160 of file SbGeoTime.H'.
Referenced by TDB(), and TT().
double SBTime::fUT1_UT1R [protected]
Definition at line 149 of file SbGeoTime.H'.
Referenced by SBTime(), and Zero().
double SBTime::fUT1_UTC [protected]
Definition at line 148 of file SbGeoTime.H'.
Referenced by SBTime(), setUTC(), UT1(), and Zero().
const char * SBMJD::monthNames [static, protected, inherited]"Initial value:
 
{
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
}
Definition at line 63 of file SbGeoTime.H'.
Referenced by SBMJD::month2Str(), SBMJD::setMJD(), and SBMJD::toString().
double SBTime::Omega [protected]
Definition at line 153 of file SbGeoTime.H'.
Referenced by FundamentalArgs(), omega(), and Zero().
const char * SBMJD::weekdayNames [static, protected, inherited]"Initial value:
{
  'Mon','Tue','Wed','Thu','Fri','Sat','Sun'
}
Definition at line 64 of file SbGeoTime.H'.
Referenced by SBMJD::dayOfWeek2Str().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.