SBTropRecord
NAME
SBTropRecord -
SYNOPSIS
#include <SbGeoSINEX.H>
Inherits SBMJD'.
Public Types
enum Format { F_YYYYMMDD, F_DDMonYYYY, F_Short, F_Long, F_Year, F_YYMonDD, F_HHMMSS, F_YYYYMMDDSSSSSS, F_INTERNAL, F_YYYYMMDDHHMMSSSS, F_DateShort, F_TimeShort, F_TimeVShort, F_ECCDAT, F_MJD, F_UNIX, F_SINEX, F_SINEX_S }
Public Member Functions
SBTropRecord ()
SBTropRecord (const SBTropRecord &)
virtual ~SBTropRecord ()
virtual QString ClassName () const
double totZenith () const
double wetZenith () const
double wetZenithErr () const
double gradNorth () const
double gradNorthErr () const
double gradEast () const
double gradEastErr () const
double temp () const
double pres () const
double rh () const
int numPts () const
int numProc () const
void setTotZenith (double z_)
void setWetZenith (double z_)
void setWetZenithErr (double z_)
void setGradNorth (double z_)
void setGradNorthErr (double z_)
void setGradEast (double z_)
void setGradEastErr (double z_)
void setTemp (double z_)
void setPres (double z_)
void setRH (double z_)
void setNumPts (int n_)
SBMJD realEpoch () const
bool operator== (const SBTropRecord &TR) const
bool operator!= (const SBTropRecord &TR) const
void clear ()
void collect (SBTropRecord *)
void processCollected ()
virtual void setMJD (int, int, int, int=0, int=0, double=0.0, bool=TRUE)
virtual void setMJD (Format, QString, bool=TRUE)
virtual void setDate (int Date_)
virtual void setTime (long double Time_)
virtual QString toString (Format=F_Short) const
virtual bool isGood ()
virtual operator long double () const
virtual bool operator== (const SBMJD &) const
virtual bool operator!= (const SBMJD &) const
virtual bool operator< (const SBMJD &) const
virtual bool operator<= (const SBMJD &) const
virtual bool operator> (const SBMJD &) const
virtual bool operator> (double) const
virtual bool operator>= (const SBMJD &) const
virtual SBMJD & operator+= (const SBMJD &MJD)
virtual SBMJD & operator-= (const SBMJD &MJD)
int date () const
long double time () const
int year () const
int month () const
int hour () const
int min () const
double sec () const
QString month2Str () const
int day () const
int dayOfYear () const
int dayOfWeek () const
QString dayOfWeek2Str () const
Static Public Member Functions
static int MJD_date (int, int, int)
static long double MJD_time (int, int, double)
static void MJD_rev (int, long double, int &, int &, int &, int &, int &, double &)
static SBMJD currentMJD ()
Protected Attributes
double TotZenith
double WetZenith
double WetZenithErr
double GradNorth
double GradNorthErr
double GradEast
double GradEastErr
double Temp
double Pres
double RH
int NumPts
bool IsCollecting
long double TSum
double aleph [3]
double beta [3]
double gamma [3]
double delta [3]
int NumProc
Static Protected Attributes
static const char * monthNames []
static const char * weekdayNames []
Friends
SBMJD operator+ (const SBMJD &, const SBMJD &)
SBMJD operator+ (const SBMJD &, long double)
SBMJD operator+ (const SBMJD &, double)
SBMJD operator+ (const SBMJD &, float)
SBMJD operator+ (long double, const SBMJD &)
SBMJD operator+ (double, const SBMJD &)
SBMJD operator+ (float, const SBMJD &)
SBMJD operator- (const SBMJD &, const SBMJD &)
SBMJD operator- (const SBMJD &, long double)
SBMJD operator- (const SBMJD &, double)
SBMJD operator- (long double, const SBMJD &)
SBMJD operator- (int, const SBMJD &)
QDataStream & operator<< (QDataStream &, const SBMJD &)
QDataStream & operator>> (QDataStream &, SBMJD &)
Detailed Description
Class SBTropRecord
Definition at line 165 of file SbGeoSINEX.H'.
Member Enumeration Documentation
enum SBMJD::Format [inherited]
Enumerator:
F_YYYYMMDD
F_DDMonYYYY
F_Short
F_Long
F_Year
F_YYMonDD
F_HHMMSS
F_YYYYMMDDSSSSSS
F_INTERNAL
F_YYYYMMDDHHMMSSSS
F_DateShort
F_TimeShort
F_TimeVShort
F_ECCDAT
F_MJD
F_UNIX
F_SINEX
F_SINEX_S
Definition at line 49 of file SbGeoTime.H'.
Constructor & Destructor Documentation
SBTropRecord::SBTropRecord ()"A constructor'.
Definition at line 158 of file SbGeoSINEX.C'.
References aleph, beta, delta, gamma, GradEast, GradEastErr, GradNorth, GradNorthErr, IsCollecting, NumProc, NumPts, Pres, RH, Temp, TotZenith, TSum, WetZenith, and WetZenithErr.
SBTropRecord::SBTropRecord (const SBTropRecord &TR)"A constructor'.
Definition at line 182 of file SbGeoSINEX.C'.
References aleph, beta, delta, gamma, GradEast, GradEastErr, GradNorth, GradNorthErr, IsCollecting, NumProc, NumPts, Pres, RH, Temp, TotZenith, TSum, WetZenith, and WetZenithErr.
virtual SBTropRecord::~SBTropRecord () [inline, virtual]"A destructor'.
Definition at line 194 of file SbGeoSINEX.H'.
Member Function Documentation
virtual QString SBTropRecord::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBMJD'.
Definition at line 196 of file SbGeoSINEX.H'.
void SBTropRecord::clear ()
Definition at line 206 of file SbGeoSINEX.C'.
References aleph, beta, delta, gamma, GradEast, GradEastErr, GradNorth, GradNorthErr, IsCollecting, NumProc, NumPts, Pres, RH, Temp, TotZenith, TSum, WetZenith, and WetZenithErr.
Referenced by collect().
void SBTropRecord::collect (SBTropRecord *Tr)
Definition at line 229 of file SbGeoSINEX.C'.
References aleph, beta, clear(), delta, gamma, GradEast, GradEastErr, GradNorth, GradNorthErr, IsCollecting, NumProc, NumPts, Pres, RH, Temp, TotZenith, TSum, WetZenith, and WetZenithErr.
Referenced by sinex_tro_MakeMeansTrops().
SBMJD SBMJD::currentMJD () [static, inherited]
Definition at line 134 of file SbGeoTime.C'.
Referenced by operator<<(), SBRunManager::process_m1(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEOP::SBTestEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestPrecession::SBTestPrecession(), SBTestSolidTides::SBTestSolidTides(), and writeNormalEquationSystem().
int SBMJD::date () const [inline, inherited]
Definition at line 121 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBNutation::calcGST(), SBTime::DefineTAI_UTC(), SBRunManager::loadVLBISession_m1(), operator<<(), operator>>(), SBTestEphem::recalc(), and SBTime::setUTC().
int SBMJD::day () const [inherited]
Definition at line 208 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), operator<<(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
int SBMJD::dayOfWeek () const [inherited]
Definition at line 225 of file SbGeoTime.C'.
References SBMJD::Date, and SBMJD::SBMJD().
Referenced by SBMJD::dayOfWeek2Str().
QString SBMJD::dayOfWeek2Str () const [inherited]
Definition at line 231 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::dayOfWeek(), and SBMJD::weekdayNames.
Referenced by SBMJD::toString().
int SBMJD::dayOfYear () const [inherited]
Definition at line 220 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), and SBMJD::year().
Referenced by SBHMf_NMF::operator()(), and SBMJD::toString().
double SBTropRecord::gradEast () const [inline]
Definition at line 205 of file SbGeoSINEX.H'.
References GradEast.
Referenced by operator==().
double SBTropRecord::gradEastErr () const [inline]
Definition at line 206 of file SbGeoSINEX.H'.
References GradEastErr.
Referenced by operator==().
double SBTropRecord::gradNorth () const [inline]
Definition at line 203 of file SbGeoSINEX.H'.
References GradNorth.
Referenced by operator==().
double SBTropRecord::gradNorthErr () const [inline]
Definition at line 204 of file SbGeoSINEX.H'.
References GradNorthErr.
Referenced by operator==().
int SBMJD::hour () const [inherited]
Definition at line 167 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
virtual bool SBMJD::isGood () [inline, virtual, inherited]
Definition at line 87 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBSourceEditor::acquireData(), SBAploChunk::import(), SBEcc::importEccDat(), operator>>(), and SBVLBISession::parseObsDumpString().
int SBMJD::min () const [inherited]
Definition at line 179 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
int SBMJD::MJD_date (inty, intm, intd) [static, inherited]
Definition at line 72 of file SbGeoTime.C'.
Referenced by SBMJD::dayOfYear(), and SBMJD::setMJD().
void SBMJD::MJD_rev (intdate_, long doubletime_, int &y, int &m, int &d, int &hr, int &mi, double &se) [static, inherited]
Definition at line 95 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::day(), SBMJD::hour(), SBMJD::min(), SBMJD::month(), SBMJD::sec(), SBMJD::toString(), and SBMJD::year().
long double SBMJD::MJD_time (intHour, intMin, doubleSec) [static, inherited]
Definition at line 90 of file SbGeoTime.C'.
References DAY2SEC.
Referenced by SBMJD::setMJD().
int SBMJD::month () const [inherited]
Definition at line 155 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBMJD::month2Str(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), and SBCoordsEditor::SBCoordsEditor().
QString SBMJD::month2Str () const [inherited]
Definition at line 203 of file SbGeoTime.C'.
References SBMJD::month(), and SBMJD::monthNames.
Referenced by operator<<().
int SBTropRecord::numProc () const [inline]
Definition at line 211 of file SbGeoSINEX.H'.
References NumProc.
int SBTropRecord::numPts () const [inline]
Definition at line 210 of file SbGeoSINEX.H'.
References NumPts.
Referenced by operator==().
virtual SBMJD::operator long double () const [inline, virtual, inherited]
Definition at line 89 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator!= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 206 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBTropRecord::operator!= (const SBTropRecord &TR) const [inline]
Definition at line 242 of file SbGeoSINEX.H'.
SBMJD & SBMJD::operator+= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 254 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
SBMJD & SBMJD::operator-= (const SBMJD &MJD) [inline, virtual, inherited]
Definition at line 262 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator< (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 211 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator<= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 217 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator== (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 201 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBTropRecord::operator== (const SBTropRecord &TR) const [inline]
Definition at line 228 of file SbGeoSINEX.H'.
References GradEast, gradEast(), GradEastErr, gradEastErr(), GradNorth, gradNorth(), GradNorthErr, gradNorthErr(), NumPts, numPts(), TotZenith, totZenith(), WetZenith, wetZenith(), WetZenithErr, and wetZenithErr().
bool SBMJD::operator> (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 223 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
bool SBMJD::operator> (doubled) const [inline, virtual, inherited]
Definition at line 229 of file SbGeoTime.H'.
References SBMJD::SBMJD().
bool SBMJD::operator>= (const SBMJD &MJD) const [inline, virtual, inherited]
Definition at line 234 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
double SBTropRecord::pres () const [inline]
Definition at line 208 of file SbGeoSINEX.H'.
References Pres.
void SBTropRecord::processCollected ()
Definition at line 265 of file SbGeoSINEX.C'.
References aleph, beta, delta, GradEast, GradEastErr, GradNorth, GradNorthErr, IsCollecting, NumProc, NumPts, Pres, RH, Temp, TotZenith, WetZenith, and WetZenithErr.
SBMJD SBTropRecord::realEpoch () const [inline]
Definition at line 226 of file SbGeoSINEX.H'.
References NumPts, and TSum.
double SBTropRecord::rh () const [inline]
Definition at line 209 of file SbGeoSINEX.H'.
References RH.
double SBMJD::sec () const [inherited]
Definition at line 191 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBTest::createWidgets(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), SBMJD::setMJD(), and SBMJD::toString().
virtual void SBMJD::setDate (intDate_) [inline, virtual, inherited]
Definition at line 81 of file SbGeoTime.H'.
References SBMJD::Date.
Referenced by SBAploChunk::import().
void SBTropRecord::setGradEast (doublez_) [inline]
Definition at line 219 of file SbGeoSINEX.H'.
References GradEast.
Referenced by operator<<().
void SBTropRecord::setGradEastErr (doublez_) [inline]
Definition at line 220 of file SbGeoSINEX.H'.
References GradEastErr.
Referenced by operator<<().
void SBTropRecord::setGradNorth (doublez_) [inline]
Definition at line 217 of file SbGeoSINEX.H'.
References GradNorth.
Referenced by operator<<().
void SBTropRecord::setGradNorthErr (doublez_) [inline]
Definition at line 218 of file SbGeoSINEX.H'.
References GradNorthErr.
Referenced by operator<<().
void SBMJD::setMJD (intYear, intMonth, intDay, intHour = 0, intMin = 0, doubleSec = 0.0, bool = TRUE) [virtual, inherited]
Definition at line 64 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_date(), SBMJD::MJD_time(), and SBMJD::Time.
Referenced by SBStuffEOPs::accept(), SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBEcc::importEccDat(), operator>>(), SBVLBISession::parseObsDumpString(), SBTest::recalc(), SBStationInfo::restoreUserInfo(), SBMJD::SBMJD(), and SBMJD::setMJD().
void SBMJD::setMJD (FormatF, QStrings, boolisReset = TRUE) [virtual, inherited]
Definition at line 357 of file SbGeoTime.C'.
References SBMJD::ClassName(), SBMJD::Date, SBLog::ERR, SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBLog::INF, Log, SBMJD::min(), SBMJD::MJD_date(), SBMJD::monthNames, SBMJD::sec(), SBMJD::setMJD(), SBMJD::Time, SBLog::TIME, SBLog::write(), and SBLog::WRN.
void SBTropRecord::setNumPts (intn_) [inline]
Definition at line 224 of file SbGeoSINEX.H'.
References NumPts.
Referenced by operator<<().
void SBTropRecord::setPres (doublez_) [inline]
Definition at line 222 of file SbGeoSINEX.H'.
References Pres.
Referenced by operator<<().
void SBTropRecord::setRH (doublez_) [inline]
Definition at line 223 of file SbGeoSINEX.H'.
References RH.
Referenced by operator<<().
void SBTropRecord::setTemp (doublez_) [inline]
Definition at line 221 of file SbGeoSINEX.H'.
References Temp.
Referenced by operator<<().
virtual void SBMJD::setTime (long doubleTime_) [inline, virtual, inherited]
Definition at line 82 of file SbGeoTime.H'.
References SBMJD::Date, and SBMJD::Time.
Referenced by SBAploChunk::import().
void SBTropRecord::setTotZenith (doublez_) [inline]
Definition at line 214 of file SbGeoSINEX.H'.
References TotZenith.
Referenced by operator<<().
void SBTropRecord::setWetZenith (doublez_) [inline]
Definition at line 215 of file SbGeoSINEX.H'.
References WetZenith.
Referenced by operator<<().
void SBTropRecord::setWetZenithErr (doublez_) [inline]
Definition at line 216 of file SbGeoSINEX.H'.
References WetZenithErr.
Referenced by operator<<().
double SBTropRecord::temp () const [inline]
Definition at line 207 of file SbGeoSINEX.H'.
References Temp.
long double SBMJD::time () const [inline, inherited]
Definition at line 122 of file SbGeoTime.H'.
References SBMJD::Time.
Referenced by SBOceanTideLd::ARG_IERS(), SBNutation::calcGST(), and SBTestEOP::fillData4Plotting().
QString SBMJD::toString (FormatF = F_Short) const [virtual, inherited]
Definition at line 243 of file SbGeoTime.C'.
References SBMJD::Date, DAY2SEC, SBMJD::dayOfWeek2Str(), SBMJD::dayOfYear(), SBMJD::F_DateShort, SBMJD::F_DDMonYYYY, SBMJD::F_ECCDAT, SBMJD::F_HHMMSS, SBMJD::F_INTERNAL, SBMJD::F_Long, SBMJD::F_MJD, SBMJD::F_Short, SBMJD::F_SINEX, SBMJD::F_SINEX_S, SBMJD::F_TimeShort, SBMJD::F_TimeVShort, SBMJD::F_UNIX, SBMJD::F_Year, SBMJD::F_YYMonDD, SBMJD::F_YYYYMMDD, SBMJD::F_YYYYMMDDHHMMSSSS, SBMJD::F_YYYYMMDDSSSSSS, SBMJD::min(), SBMJD::MJD_rev(), SBMJD::monthNames, SBMJD::sec(), SBMJD::Time, TUnix0, TZero, and SBMJD::year().
Referenced by SBStuffSources::accept(), SBStuffStations::accept(), SBSourceEditor::acquireData(), SBDelay::calc(), SBEphem::calc(), SBFrameClassic::calc(), SBNutThIAU1980::calc(), SBNutThIAU1996::calc(), SBNutThIAU2000A::calc(), SBEphem::calcI(), SBRunManager::checkParameterLists(), SBEOP::checkRanges(), SBStuffEOPs::createInfoGroup(), SBTestFrame::createWidget4Test(), SBTest::createWidgets(), SBStationEditor::delCoordinates(), SBStuffStationsEcc::deleteEntry(), SBStaParsEditor::deleteEntry(), SBEOP::dEps(), SBTestPrecession::displayValues(), SBTestNutation::displayValues(), SBTestFrame::displayValues(), SBEOP::dLOD(), SBEOP::dPsi(), SBStuffSources::drawInfo(), SBStuffStations::drawInfo(), SBPlotArea::drawXmjdTics(), SBDBHHistTriplet::dump(), SBDBHStartBlock::dump(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBEOP::dUT1_UTC(), SBEOP::dX(), SBEOP::dY(), SBVLBIPreProcess::fillSessAttr(), SBEstimator::GroupList::find(), SBStochParameter::find(), SBAploEphem::getReady(), SBEphem::import(), SBEstimator::GroupList::inSort(), SBEOP::interpolateEOPs(), SBObsVLBIStatSrcLI::key(), SBObsVLBIStatStaLI::key(), SBSolutionBatchLI::key(), SBObsVLBIStatRecordLI::key(), SBEccListItem::key(), SBCoordsListItem::key(), SBAploHeaderLI::key(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportTRFVariations(), SBAploHeader::name(), SBEphem::openFile(), SBSolidTideLd::operator()(), SBPrec_IAU1976::operator()(), SBTideLd::operator()(), SBPrec_IAU2000::operator()(), SBRefraction::operator()(), SBNut_IAU1980::operator()(), SBNut_IAU2000::operator()(), SBPolus::operator()(), operator<<(), operator>>(), SBEOP::prepare4Date(), SBTest::recalc(), SBStationEcc::registerEcc(), SBEstimator::GroupList::remove(), SBParameterList::report(), SBStochParameter::report(), SBStuffAplo::SBStuffAplo(), SBStuffEphem::SBStuffEphem(), SBStuffSources::SBStuffSources(), SBStuffStations::SBStuffStations(), SBTime::setUTC(), sinex_HeaderLine(), sinex_InputFilesBlock(), sinex_InputHistoryBlock(), sinex_SiteEccentricityBlock(), sinex_SolutionEpochsBlock(), sinex_tro_HeaderLine(), SBObsVLBIStatSrcLI::text(), SBParameterLI::text(), SBVLBIObsPPLI::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBObsVLBIStatRecordLI::text(), SBEccListItem::text(), SBVLBIObsLI::text(), SBCoordsListItem::text(), SBAploHeaderLI::text(), SBClockBreakLI::text(), SBParameter::timeStamp(), SBStuffEOPs::updateEOP(), SBStuffEphem::updateEphem(), SBStuffAplo::updateEphem(), SBVLBIPreProcess::wAttributes(), SBVLBISessionEditor::wParameters(), and SBSourceEditor::wStats().
double SBTropRecord::totZenith () const [inline]
Definition at line 200 of file SbGeoSINEX.H'.
References TotZenith.
Referenced by operator==().
double SBTropRecord::wetZenith () const [inline]
Definition at line 201 of file SbGeoSINEX.H'.
References WetZenith.
Referenced by operator==().
double SBTropRecord::wetZenithErr () const [inline]
Definition at line 202 of file SbGeoSINEX.H'.
References WetZenithErr.
Referenced by operator==().
int SBMJD::year () const [inherited]
Definition at line 143 of file SbGeoTime.C'.
References SBMJD::Date, SBMJD::MJD_rev(), and SBMJD::Time.
Referenced by SBVLBISesInfo::checkPath(), SBTest::createWidgets(), SBMJD::dayOfYear(), SBVLBISesInfo::fileName(), SBTest::recalc(), SBClockBreakEditor::SBClockBreakEditor(), SBCoordsEditor::SBCoordsEditor(), and SBMJD::toString().
Friends And Related Function Documentation
SBMJD operator+ (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 270 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 275 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 280 of file SbGeoTime.H'.
SBMJD operator+ (const SBMJD &A, floatb) [friend, inherited]
Definition at line 285 of file SbGeoTime.H'.
SBMJD operator+ (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 290 of file SbGeoTime.H'.
SBMJD operator+ (doublea, const SBMJD &B) [friend, inherited]
Definition at line 295 of file SbGeoTime.H'.
SBMJD operator+ (floata, const SBMJD &B) [friend, inherited]
Definition at line 300 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, const SBMJD &B) [friend, inherited]
Definition at line 305 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, long doubleb) [friend, inherited]
Definition at line 310 of file SbGeoTime.H'.
SBMJD operator- (const SBMJD &A, doubleb) [friend, inherited]
Definition at line 315 of file SbGeoTime.H'.
SBMJD operator- (long doublea, const SBMJD &B) [friend, inherited]
Definition at line 320 of file SbGeoTime.H'.
SBMJD operator- (inta, const SBMJD &B) [friend, inherited]
Definition at line 325 of file SbGeoTime.H'.
QDataStream& operator<< (QDataStream &s, const SBMJD &MJD) [friend, inherited]
Definition at line 330 of file SbGeoTime.H'.
QDataStream& operator>> (QDataStream &s, SBMJD &MJD) [friend, inherited]
Definition at line 337 of file SbGeoTime.H'.
Member Data Documentation
double SBTropRecord::aleph[3] [protected]
Definition at line 183 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), processCollected(), and SBTropRecord().
double SBTropRecord::beta[3] [protected]
Definition at line 183 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), processCollected(), and SBTropRecord().
double SBTropRecord::delta[3] [protected]
Definition at line 183 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), processCollected(), and SBTropRecord().
double SBTropRecord::gamma[3] [protected]
Definition at line 183 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), and SBTropRecord().
double SBTropRecord::GradEast [protected]
Definition at line 173 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), gradEast(), operator==(), processCollected(), SBTropRecord(), and setGradEast().
double SBTropRecord::GradEastErr [protected]
Definition at line 174 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), gradEastErr(), operator==(), processCollected(), SBTropRecord(), and setGradEastErr().
double SBTropRecord::GradNorth [protected]
Definition at line 171 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), gradNorth(), operator==(), processCollected(), SBTropRecord(), and setGradNorth().
double SBTropRecord::GradNorthErr [protected]
Definition at line 172 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), gradNorthErr(), operator==(), processCollected(), SBTropRecord(), and setGradNorthErr().
bool SBTropRecord::IsCollecting [protected]
Definition at line 179 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), processCollected(), and SBTropRecord().
const char * SBMJD::monthNames [static, protected, inherited]"Initial value:
 
{
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
}
Definition at line 63 of file SbGeoTime.H'.
Referenced by SBMJD::month2Str(), SBMJD::setMJD(), and SBMJD::toString().
int SBTropRecord::NumProc [protected]
Definition at line 184 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), numProc(), processCollected(), and SBTropRecord().
int SBTropRecord::NumPts [protected]
Definition at line 178 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), numPts(), operator==(), processCollected(), realEpoch(), SBTropRecord(), and setNumPts().
double SBTropRecord::Pres [protected]
Definition at line 176 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), pres(), processCollected(), SBTropRecord(), and setPres().
double SBTropRecord::RH [protected]
Definition at line 177 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), processCollected(), rh(), SBTropRecord(), and setRH().
double SBTropRecord::Temp [protected]
Definition at line 175 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), processCollected(), SBTropRecord(), setTemp(), and temp().
double SBTropRecord::TotZenith [protected]
Definition at line 168 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), operator==(), processCollected(), SBTropRecord(), setTotZenith(), and totZenith().
long double SBTropRecord::TSum [protected]
Definition at line 182 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), realEpoch(), and SBTropRecord().
const char * SBMJD::weekdayNames [static, protected, inherited]"Initial value:
{
  'Mon','Tue','Wed','Thu','Fri','Sat','Sun'
}
Definition at line 64 of file SbGeoTime.H'.
Referenced by SBMJD::dayOfWeek2Str().
double SBTropRecord::WetZenith [protected]
Definition at line 169 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), operator==(), processCollected(), SBTropRecord(), setWetZenith(), and wetZenith().
double SBTropRecord::WetZenithErr [protected]
Definition at line 170 of file SbGeoSINEX.H'.
Referenced by clear(), collect(), operator==(), processCollected(), SBTropRecord(), setWetZenithErr(), and wetZenithErr().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.