SBTS_SINEX
NAME
SBTS_SINEX -
SYNOPSIS
#include <SbGeoStations.H>
Inherits QTextStream'.
Public Member Functions
SBTS_SINEX ()
SBTS_SINEX (QByteArray a, int mode)
SBTS_SINEX (QIODevice *iod)
SBTS_SINEX (QString &str, int fmode)
SBTS_SINEX (QString *str, int fmode)
SBTS_SINEX (FILE *fh, int mode)
SBRunManager * runMgr () const
void setRunMgr (SBRunManager *Mgr_)
Private Attributes
SBRunManager * RunMgr
Detailed Description
Definition at line 124 of file SbGeoStations.H'.
Constructor & Destructor Documentation
SBTS_SINEX::SBTS_SINEX () [inline]
Definition at line 129 of file SbGeoStations.H'.
References RunMgr.
SBTS_SINEX::SBTS_SINEX (QByteArraya, intmode) [inline]
Definition at line 130 of file SbGeoStations.H'.
References RunMgr.
SBTS_SINEX::SBTS_SINEX (QIODevice *iod) [inline]
Definition at line 131 of file SbGeoStations.H'.
References RunMgr.
SBTS_SINEX::SBTS_SINEX (QString &str, intfmode) [inline]
Definition at line 132 of file SbGeoStations.H'.
References RunMgr.
SBTS_SINEX::SBTS_SINEX (QString *str, intfmode) [inline]
Definition at line 133 of file SbGeoStations.H'.
References RunMgr.
SBTS_SINEX::SBTS_SINEX (FILE *fh, intmode) [inline]
Definition at line 134 of file SbGeoStations.H'.
References RunMgr.
Member Function Documentation
SBRunManager* SBTS_SINEX::runMgr () const [inline]
Definition at line 135 of file SbGeoStations.H'.
References RunMgr.
Referenced by operator<<(), and writeNormalEquationSystem().
void SBTS_SINEX::setRunMgr (SBRunManager *Mgr_) [inline]
Definition at line 136 of file SbGeoStations.H'.
References RunMgr.
Referenced by SBRunManager::makeReportNormalEqs(), SBRunManager::makeReportTRF(), and SBRunManager::makeReportTroposphere().
Member Data Documentation
SBRunManager* SBTS_SINEX::RunMgr [private]
Definition at line 127 of file SbGeoStations.H'.
Referenced by runMgr(), SBTS_SINEX(), and setRunMgr().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.