.TH "SBTS_rsc" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBTS_rsc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoSources\&.H>\fP
.PP
Inherits \fBQTextStream\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBTS_rsc\fP ()"
.br
.ti -1c
.RI "void \fBsetAssignedStatus\fP (\fBSBSource::SStatus\fP AS_)"
.br
.ti -1c
.RI "\fBSBSource::SStatus\fP \fBassignedStatus\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBSource::SStatus\fP \fBAssignedStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 261 of file SbGeoSources\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBTS_rsc::SBTS_rsc ()\fC [inline]\fP"
.PP
Definition at line 266 of file SbGeoSources\&.H'\&.
.PP
References AssignedStatus, and SBSource::STATUS_UNKN\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSBSource::SStatus\fP SBTS_rsc::assignedStatus () const\fC [inline]\fP"
.PP
Definition at line 268 of file SbGeoSources\&.H'\&.
.PP
References AssignedStatus\&.
.PP
Referenced by operator>>()\&.
.SS "void SBTS_rsc::setAssignedStatus (\fBSBSource::SStatus\fPAS_)\fC [inline]\fP"
.PP
Definition at line 267 of file SbGeoSources\&.H'\&.
.PP
References AssignedStatus\&.
.PP
Referenced by SBSourceImport::loadFile1995()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBSource::SStatus\fP \fBSBTS_rsc::AssignedStatus\fP\fC [private]\fP"
.PP
Definition at line 264 of file SbGeoSources\&.H'\&.
.PP
Referenced by assignedStatus(), SBTS_rsc(), and setAssignedStatus()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
