.TH "SBTS_ssc1994" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBTS_ssc1994 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoStations\&.H>\fP
.PP
Inherits \fBQTextStream\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBTS_ssc1994\fP (\fBSBStation::SClassCoord\fP ClassCoord_)"
.br
.ti -1c
.RI "\fBSBTS_ssc1994\fP (\fBSBStation::SClassCoord\fP ClassCoord_, QByteArray a, int mode)"
.br
.ti -1c
.RI "\fBSBTS_ssc1994\fP (\fBSBStation::SClassCoord\fP ClassCoord_, QIODevice *d)"
.br
.ti -1c
.RI "\fBSBTS_ssc1994\fP (\fBSBStation::SClassCoord\fP ClassCoord_, FILE *fh, int mode)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSBStation::SClassCoord\fP \fBClassCoord\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 704 of file SbGeoStations\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBTS_ssc1994::SBTS_ssc1994 (\fBSBStation::SClassCoord\fPClassCoord_)\fC [inline]\fP"
.PP
Definition at line 708 of file SbGeoStations\&.H'\&.
.PP
References ClassCoord\&.
.SS "SBTS_ssc1994::SBTS_ssc1994 (\fBSBStation::SClassCoord\fPClassCoord_, QByteArraya, intmode)\fC [inline]\fP"
.PP
Definition at line 710 of file SbGeoStations\&.H'\&.
.PP
References ClassCoord\&.
.SS "SBTS_ssc1994::SBTS_ssc1994 (\fBSBStation::SClassCoord\fPClassCoord_, QIODevice *d)\fC [inline]\fP"
.PP
Definition at line 712 of file SbGeoStations\&.H'\&.
.PP
References ClassCoord\&.
.SS "SBTS_ssc1994::SBTS_ssc1994 (\fBSBStation::SClassCoord\fPClassCoord_, FILE *fh, intmode)\fC [inline]\fP"
.PP
Definition at line 714 of file SbGeoStations\&.H'\&.
.PP
References ClassCoord\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBStation::SClassCoord\fP \fBSBTS_ssc1994::ClassCoord\fP"
.PP
Definition at line 707 of file SbGeoStations\&.H'\&.
.PP
Referenced by operator<<(), and SBTS_ssc1994()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
