SBUpperMatrix
NAME
SBUpperMatrix -
SYNOPSIS
#include <SbVector.H>
Inherits SBMatrix'.
Inherited by SBSymMatrix'.
Public Member Functions
SBUpperMatrix ()
SBUpperMatrix (unsigned int, const QString &, bool=TRUE)
SBUpperMatrix (const SBUpperMatrix &)
virtual ~SBUpperMatrix ()
virtual QString ClassName () const
unsigned int n () const
virtual double & operator() (unsigned int, unsigned int)
virtual double at (unsigned int, unsigned int) const
virtual void set (unsigned int, unsigned int, double)
SBUpperMatrix & operator= (const SBUpperMatrix &)
virtual SBUpperMatrix & setCol (unsigned int, const SBVector &)
virtual SBVector & setVector (unsigned int, SBVector &)
virtual void clear ()
virtual SBMatrix T ()
virtual SBUpperMatrix & operator= (double)
virtual SBUpperMatrix & operator+= (const SBUpperMatrix &)
virtual SBUpperMatrix & operator-= (const SBUpperMatrix &)
virtual SBUpperMatrix & operator*= (double)
virtual SBUpperMatrix & operator/= (double)
virtual unsigned int nRow () const
virtual unsigned int nCol () const
virtual SBMatrix & operator+= (const SBMatrix &)
virtual SBMatrix & operator-= (const SBMatrix &)
void resize (unsigned int, unsigned int)
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
unsigned int NRow
unsigned int NCol
double ** B
double dTmp
QString Name
Friends
SBUpperMatrix operator/ (const SBUpperMatrix &M, double f)
SBUpperMatrix operator* (const SBUpperMatrix &M, double f)
SBUpperMatrix operator* (double f, const SBUpperMatrix &M)
SBUpperMatrix operator- (const SBUpperMatrix &M)
SBUpperMatrix operator+ (const SBUpperMatrix &, const SBUpperMatrix &)
SBUpperMatrix operator- (const SBUpperMatrix &, const SBUpperMatrix &)
SBUpperMatrix operator* (const SBUpperMatrix &, const SBUpperMatrix &)
SBUpperMatrix operator~ (const SBUpperMatrix &)
SBSymMatrix matT_x_mat (const SBUpperMatrix &, const SBUpperMatrix &)
SBVector operator* (const SBUpperMatrix &, const SBVector &)
SBVector matT_x_vec (const SBUpperMatrix &, const SBVector &)
SBSymMatrix & RRT (SBSymMatrix &, const SBUpperMatrix &)
SBSymMatrix & RTR (SBSymMatrix &, const SBUpperMatrix &)
SBVector & Solve (const SBUpperMatrix &, SBVector &, const SBVector &)
SBSymMatrix QuadraticForm (const SBSymMatrix &, const SBUpperMatrix &)
QDataStream & operator<< (QDataStream &, const SBUpperMatrix &)
QDataStream & operator>> (QDataStream &, SBUpperMatrix &)
SBMatrix operator/ (const SBMatrix &M, double f)
SBMatrix operator* (const SBMatrix &M, double f)
SBMatrix operator* (double f, const SBMatrix &M)
SBMatrix operator* (const SBMatrix &, const SBMatrix &)
SBVector operator* (const SBMatrix &, const SBVector &)
SBMatrix operator- (const SBMatrix &M)
SBMatrix operator- (const SBMatrix &, const SBMatrix &)
SBMatrix operator+ (const SBMatrix &, const SBMatrix &)
SBSymMatrix QuadraticForm (const SBSymMatrix &, const SBMatrix &)
SBMatrix matT_x_mat (const SBMatrix &, const SBMatrix &)
SBVector matT_x_vec (const SBMatrix &, const SBVector &)
QDataStream & operator<< (QDataStream &, const SBMatrix &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBMatrix &)
QDataStream & operator>> (QDataStream &, SBNamed &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
Detailed Description
class SBUpperMatrix'. Upper triangular matrix'.
Definition at line 618 of file SbVector.H'.
Constructor & Destructor Documentation
SBUpperMatrix::SBUpperMatrix () [inline]"A constructor'. Creates an empty matrix (for I/O purposes)'.
Definition at line 626 of file SbVector.H'.
SBUpperMatrix::SBUpperMatrix (unsigned intN_, const QString &Name_, boolIsNeedClear = TRUE) [inline]"A constructor'. Creates a copy of object'.
Parameters:
N number of rows and columns;
IsNeedClear makes clearing of the allocated memmory;
Definition at line 736 of file SbVector.H'.
References SBMatrix::B, SBMatrix::dTmp, SBMatrix::NCol, and SBMatrix::NRow.
SBUpperMatrix::SBUpperMatrix (const SBUpperMatrix &M) [inline]"A constructor'. Creates a copy of object'.
Parameters:
M values of the new object'.
Definition at line 750 of file SbVector.H'.
References SBMatrix::B, SBMatrix::dTmp, SBMatrix::NCol, and SBMatrix::NRow.
SBUpperMatrix::~SBUpperMatrix () [inline, virtual]"A destructor'.
Definition at line 764 of file SbVector.H'.
References SBMatrix::B, and SBMatrix::NCol.
Member Function Documentation
double SBUpperMatrix::at (unsigned inti, unsigned intj) const [inline, virtual]"Returns value of the (i,j)-th element'.
Reimplemented from SBMatrix'.
Reimplemented in SBSymMatrix'.
Definition at line 797 of file SbVector.H'.
References SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Referenced by SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), makeHouseholder(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), operator~(), SBEstimator::propagateStochasticPars(), QuadraticForm(), RRT(), RTR(), Solve(), and writeNormalEquationSystem().
virtual QString SBUpperMatrix::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBMatrix'.
Reimplemented in SBSymMatrix'.
Definition at line 641 of file SbVector.H'.
Referenced by at(), matT_x_mat(), operator()(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator=(), operator~(), set(), setCol(), setVector(), and Solve().
void SBUpperMatrix::clear () [inline, virtual]"Fills the matrix with zeros'.
Reimplemented from SBMatrix'.
Definition at line 775 of file SbVector.H'.
References SBMatrix::B, and SBMatrix::NCol.
Referenced by SBRunManager::makeReportCRFVariations4IVS(), and SBEstimator::solveStochs().
unsigned int SBUpperMatrix::n () const [inline]"Returns the number of rows/columns of the matrix'.
Definition at line 646 of file SbVector.H'.
References SBMatrix::nRow().
Referenced by makeHouseholder(), operator*(), operator~(), and SBParameterList::updateSolution().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), set(), SBMatrix::setCol(), setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
virtual unsigned int SBMatrix::nCol () const [inline, virtual, inherited]"Returns number of columns'.
Definition at line 318 of file SbVector.H'.
References SBMatrix::NCol.
Referenced by SBPlotBranch::dataAttr(), SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBFilterGauss::readDataFile(), SBPlotBranch::setDataAttr(), sinex_SolutionMatrixEstimateBlock(), and sinex_SolutionNormalEquationMatrixBlock().
virtual unsigned int SBMatrix::nRow () const [inline, virtual, inherited]"Returns number of rows'.
Definition at line 316 of file SbVector.H'.
References SBMatrix::NRow.
Referenced by SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBPlotArea::getLimits(), makeHouseholder(), n(), QuadraticForm(), and SBFilterGauss::readDataFile().
double & SBUpperMatrix::operator() (unsigned inti, unsigned intj) [inline, virtual]"Returns reference to the (i,j)-th element'.
Reimplemented from SBMatrix'.
Definition at line 782 of file SbVector.H'.
References SBMatrix::B, ClassName(), SBMatrix::dTmp, SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix & SBUpperMatrix::operator*= (doublef) [inline, virtual]"Multiplies the matrix by a double'.
Reimplemented from SBMatrix'.
Reimplemented in SBSymMatrix'.
Definition at line 890 of file SbVector.H'.
References SBMatrix::B, and SBMatrix::NCol.
SBMatrix & SBMatrix::operator+= (const SBMatrix &M) [inline, virtual, inherited]"Adds a matrix to the matrix'.
Definition at line 517 of file SbVector.H'.
References SBMatrix::B, SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix & SBUpperMatrix::operator+= (const SBUpperMatrix &M) [inline, virtual]"Adds a matrix to the matrix'.
Definition at line 856 of file SbVector.H'.
References SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBMatrix & SBMatrix::operator-= (const SBMatrix &M) [inline, virtual, inherited]"Substracts a matrix from the matrix'.
Definition at line 534 of file SbVector.H'.
References SBMatrix::B, SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix & SBUpperMatrix::operator-= (const SBUpperMatrix &M) [inline, virtual]"Substracts a matrix from the matrix'.
Definition at line 873 of file SbVector.H'.
References SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix & SBUpperMatrix::operator/= (doublef) [inline, virtual]"Divides the matrix by a double'.
Reimplemented from SBMatrix'.
Reimplemented in SBSymMatrix'.
Definition at line 899 of file SbVector.H'.
References SBMatrix::B, and SBMatrix::NCol.
SBUpperMatrix & SBUpperMatrix::operator= (const SBUpperMatrix &M) [inline]"Assign the matix to another one
Definition at line 830 of file SbVector.H'.
References SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix & SBUpperMatrix::operator= (doublef) [inline, virtual]"Fills the matix with the double'.
Reimplemented from SBMatrix'.
Reimplemented in SBSymMatrix'.
Definition at line 847 of file SbVector.H'.
References SBMatrix::B, and SBMatrix::NCol.
void SBMatrix::resize (unsigned intNRow_, unsigned intNCol_) [inherited]"Changes the size of a matrix'.
Definition at line 66 of file SbVector.C'.
References SBMatrix::B, SBMatrix::dTmp, SBMatrix::NCol, and SBMatrix::NRow.
Referenced by SBTestEOP::fillData4Plotting(), SBTestDiurnEOP::fillData4Plotting(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), and SBEOP::setPtNum().
void SBUpperMatrix::set (unsigned inti, unsigned intj, doubleA_) [inline, virtual]"Sets the (i,j)-th element to the double'.
Reimplemented from SBMatrix'.
Definition at line 808 of file SbVector.H'.
References SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), collectListOfSINEXParameters(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), makeHouseholder(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBEstimator::prepare4Local(), SBEstimator::prepare4Run(), SBEstimator::propagateStochasticPars(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), and writeNormalEquationSystem().
SBUpperMatrix & SBUpperMatrix::setCol (unsigned intN_, const SBVector &V) [inline, virtual]"Sets i-th column to Vector'.
Reimplemented from SBMatrix'.
Reimplemented in SBSymMatrix'.
Definition at line 908 of file SbVector.H'.
References SBVector::B, SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBVector::N, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
SBVector & SBUpperMatrix::setVector (unsigned intN_, SBVector &V) [inline, virtual]"Assign to the vector the values of matrix'es column'.
Reimplemented from SBMatrix'.
Definition at line 923 of file SbVector.H'.
References SBVector::B, SBMatrix::B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBVector::N, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBMatrix SBUpperMatrix::T () [inline, virtual]"Returns transposed matrix (original matrix doesn't change)'.
Reimplemented from SBMatrix'.
Reimplemented in SBSymMatrix'.
Definition at line 820 of file SbVector.H'.
References SBMatrix::B, SBNamed::name(), SBMatrix::NCol, and SBMatrix::NRow.
Referenced by SBEstimator::solveStochs().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
SBMatrix matT_x_mat (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns a product of a transposed matrix and a matrix'. This function is equal to `M1'.T()*M2', but implements a more efficient realization'.
Definition at line 116 of file SbVector.C'.
SBSymMatrix matT_x_mat (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend]"Returns a product of a transposed matrix and a matrix'. This function is equal to `M1'.T()*M2', but implements a more efficient realization'.
Definition at line 195 of file SbVector.C'.
SBVector matT_x_vec (const SBMatrix &M, const SBVector &V) [friend, inherited]"Returns a product of a transposed matrix and a vector'. This function is equal to `M'.T()*V', but implements a more efficient realization'.
Definition at line 419 of file SbVector.C'.
SBVector matT_x_vec (const SBUpperMatrix &M, const SBVector &V) [friend]"Returns a product of a transposed upper triangular matrix and a vector'. This function is equal to `M'.T()*V', but implements a more efficient realization'.
Definition at line 219 of file SbVector.C'.
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
SBMatrix operator* (const SBMatrix &M, doublef) [friend, inherited]"Returns matrix multiplied by float'.
Definition at line 356 of file SbVector.H'.
SBMatrix operator* (doublef, const SBMatrix &M) [friend, inherited]"Returns matrix multiplied by float'.
Definition at line 358 of file SbVector.H'.
SBMatrix operator* (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns product of two matrices'.
Definition at line 98 of file SbVector.C'.
SBVector operator* (const SBMatrix &M, const SBVector &V) [friend, inherited]"Returns a product of a matrix and a vector'.
Definition at line 397 of file SbVector.C'.
SBUpperMatrix operator* (const SBUpperMatrix &M, doublef) [friend]"Returns matrix multiplied by float'.
Definition at line 682 of file SbVector.H'.
SBUpperMatrix operator* (doublef, const SBUpperMatrix &M) [friend]"Returns matrix multiplied by float'.
Definition at line 684 of file SbVector.H'.
SBUpperMatrix operator* (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend]"Returns product of two matrices'.
Definition at line 177 of file SbVector.C'.
SBVector operator* (const SBUpperMatrix &, const SBVector &) [friend]
SBMatrix operator+ (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns a sum of two matrices'.
Definition at line 1133 of file SbVector.H'.
SBUpperMatrix operator+ (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend]"Returns a sum of two matrices'.
Definition at line 1167 of file SbVector.H'.
SBMatrix operator- (const SBMatrix &M) [friend, inherited]"Returns matrix with reversed sign'.
Definition at line 360 of file SbVector.H'.
SBMatrix operator- (const SBMatrix &M1, const SBMatrix &M2) [friend, inherited]"Returns a difference of two matrices'.
Definition at line 1146 of file SbVector.H'.
SBUpperMatrix operator- (const SBUpperMatrix &M) [friend]"Returns matrix with reversed sign'.
Definition at line 686 of file SbVector.H'.
SBUpperMatrix operator- (const SBUpperMatrix &M1, const SBUpperMatrix &M2) [friend]"Returns a difference of two matrices'.
Definition at line 1180 of file SbVector.H'.
SBMatrix operator/ (const SBMatrix &M, doublef) [friend, inherited]"Returns matrix divided by float'.
Definition at line 354 of file SbVector.H'.
SBUpperMatrix operator/ (const SBUpperMatrix &M, doublef) [friend]"Returns matrix divided by float'.
Definition at line 680 of file SbVector.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBMatrix &M) [friend, inherited]
Definition at line 135 of file SbVector.C'.
QDataStream& operator<< (QDataStream &s, const SBUpperMatrix &M) [friend]
Definition at line 352 of file SbVector.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBMatrix &M) [friend, inherited]
Definition at line 143 of file SbVector.C'.
QDataStream& operator>> (QDataStream &s, SBUpperMatrix &M) [friend]
Definition at line 360 of file SbVector.C'.
SBUpperMatrix operator~ (const SBUpperMatrix &R) [friend]"Returns inversed matrix'. This is time consumed operation, shouldn't use in ordinary operations'. M*~M==~M*M==1 (original matrix doesn't change)'.
Definition at line 323 of file SbVector.C'.
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBMatrix &A) [friend, inherited]
Reimplemented in SBSymMatrix'.
Definition at line 468 of file SbVector.C'.
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBUpperMatrix &R) [friend]"Calculates the product of `A*P*A'.T()''. Returns symmetric matrix'.
Reimplemented in SBSymMatrix'.
Definition at line 500 of file SbVector.C'.
SBSymMatrix& RRT (SBSymMatrix &M, const SBUpperMatrix &R) [friend]"Returns a product of a `R*R'.T()' -- a matrix and its transposed one'. This function is equal to `M1*M1'.T()', but [should] implements a more efficient realization'.
Definition at line 246 of file SbVector.C'.
SBSymMatrix& RTR (SBSymMatrix &M, const SBUpperMatrix &R) [friend]"Returns a product of a `R'.T()*R' -- a transposed matrix and the one'. This function is equal to `M1'.T()*M1', but [should] implements a more efficient realization'.
Definition at line 268 of file SbVector.C'.
SBVector& Solve (const SBUpperMatrix &R, SBVector &x, const SBVector &z) [friend]"Solves an equation `R*x=z''. Returns vector x'. The order of arguments is the same as in the equation: R, x and z'.
Definition at line 290 of file SbVector.C'.
Member Data Documentation
double** SBMatrix::B [protected, inherited]
Definition at line 282 of file SbVector.H'.
Referenced by SBMatrix::at(), at(), SBSymMatrix::at(), SBMatrix::clear(), clear(), matT_x_mat(), SBMatrix::operator()(), operator()(), operator*(), SBMatrix::operator*=(), operator*=(), SBMatrix::operator+=(), operator+=(), SBMatrix::operator-=(), operator-=(), SBMatrix::operator/=(), operator/=(), operator<<(), SBMatrix::operator=(), operator=(), operator>>(), SBMatrix::resize(), SBMatrix::SBMatrix(), SBSymMatrix::SBSymMatrix(), SBUpperMatrix(), SBMatrix::set(), set(), SBMatrix::setCol(), setCol(), SBMatrix::setVector(), setVector(), SBMatrix::T(), T(), SBMatrix::~SBMatrix(), and ~SBUpperMatrix().
double SBMatrix::dTmp [protected, inherited]
Definition at line 283 of file SbVector.H'.
Referenced by SBMatrix::operator()(), operator()(), SBMatrix::resize(), SBMatrix::SBMatrix(), SBSymMatrix::SBSymMatrix(), and SBUpperMatrix().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
unsigned int SBMatrix::NCol [protected, inherited]
Definition at line 281 of file SbVector.H'.
Referenced by SBMatrix::at(), at(), SBSymMatrix::at(), SBMatrix::clear(), clear(), matT_x_mat(), SBMatrix::nCol(), SBMatrix::operator()(), operator()(), operator*(), SBMatrix::operator*=(), operator*=(), operator+(), SBMatrix::operator+=(), operator+=(), operator-(), SBMatrix::operator-=(), operator-=(), SBMatrix::operator/=(), operator/=(), operator<<(), SBMatrix::operator=(), operator=(), operator>>(), QuadraticForm(), SBMatrix::resize(), RRT(), RTR(), SBMatrix::SBMatrix(), SBSymMatrix::SBSymMatrix(), SBUpperMatrix(), SBMatrix::set(), set(), SBMatrix::setCol(), setCol(), SBMatrix::setVector(), setVector(), SBMatrix::T(), T(), SBMatrix::~SBMatrix(), and ~SBUpperMatrix().
unsigned int SBMatrix::NRow [protected, inherited]
Definition at line 280 of file SbVector.H'.
Referenced by SBMatrix::at(), at(), SBSymMatrix::at(), SBMatrix::clear(), matT_x_mat(), SBMatrix::nRow(), SBMatrix::operator()(), operator()(), operator*(), SBMatrix::operator*=(), operator+(), SBMatrix::operator+=(), operator+=(), operator-(), SBMatrix::operator-=(), operator-=(), SBMatrix::operator/=(), operator<<(), SBMatrix::operator=(), operator=(), operator>>(), QuadraticForm(), SBMatrix::resize(), RRT(), RTR(), SBMatrix::SBMatrix(), SBSymMatrix::SBSymMatrix(), SBUpperMatrix(), SBMatrix::set(), set(), SBMatrix::setCol(), setCol(), SBMatrix::setVector(), setVector(), Solve(), SBMatrix::T(), and T().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.