SbVector3.C
NAME
SbVector3.C -
SYNOPSIS
#include 'SbVector3.H'
Functions
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2)
Matrix3 operator~ (const Matrix3 &M1)
Variables
const Vector3 v3Zero (0.0, 0.0, 0.0)
const Vector3 v3Unit (1.0, 1.0, 1.0)
const Matrix3 m3E (Vector3(1.0, 0.0, 0.0), Vector3(0.0, 1.0, 0.0), Vector3(0.0, 0.0, 1.0))
Function Documentation
Matrix3 operator* (const Matrix3 &M1, const Matrix3 &M2)
Definition at line 59 of file SbVector3.C'.
References Matrix3::mat.
Matrix3 operator~ (const Matrix3 &M1)"Returns inversed matrix: A*~A=~A*A=1 (original matrix does'n change)'.
Definition at line 95 of file SbVector3.C'.
References Matrix3::ClassName(), SBLog::ERR, Log, Matrix3::mat, SBLog::MATRIX3D, Matrix3::module(), and SBLog::write().
Variable Documentation
const Matrix3 m3E(Vector3(1.0, 0.0, 0.0), Vector3(0.0, 1.0, 0.0), Vector3(0.0, 0.0, 1.0))
const Vector3 v3Unit(1.0, 1.0, 1.0)
Referenced by SBStationEditor::addCoordinates(), SBAploChunk::import(), SBAploEphem::importHPS(), and operator>>().
const Vector3 v3Zero(0.0, 0.0, 0.0)
Referenced by SBStationEditor::addCoordinates(), SBStationImport::applyFilter(), SBStation::calcDisplacement(), SBSite::calcRLF(), SBRunManager::constraintStationVeloc(), SBPlateMotion::displacement(), SBAploEphem::displacement(), SBReferencePoint::dR(), SBReferencePoint::dR_0(), SBReferencePoint::dV(), SBReferencePoint::dV_0(), SBTestSolidTides::fillData4Plotting(), SBTestOceanTides::fillData4Plotting(), SBTestPolarTides::fillData4Plotting(), SBTestAPLoad::fillData4Plotting(), SBStation::getGlobalParameters4Report(), SBStation::getGlobalParameters4Report4Axel(), SBStation::getGlobalParameters4UpdateTRF(), SBAploChunk::import(), SBAploEphem::importHPS(), SBStationImport::importITRF(), SBStationListItem::key(), SBStationImport::loadOLoad(), SBRunManager::makeReportTRFVariations(), SBSolidTideLdIERS96::makeStep1(), operator<<(), operator>>(), SBReferencePoint::r(), SBReferencePoint::r_0(), SBReferencePoint::registerCoords(), SBEcc::registerEcc(), SBCoordinates::SBCoordinates(), SBEccentricity::SBEccentricity(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), sinex_tro_StaCoordinatesBlock(), SBStationListItem::text(), SBStation::updateGeodCoo(), SBReferencePoint::v(), SBReferencePoint::v_0(), SBPlateEntry::velocity(), SBPlateMotion::velocity(), and SBStation::vModel().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.