SbVector.H
NAME
SbVector.H -
SYNOPSIS
#include <config.h>
#include <math.h>
#include <string.h>
#include 'SbGeneral.H'
#include 'SbGeo.H'
Classes
class SBVector
class SBMatrix
class SBUpperMatrix
class SBSymMatrix
Functions
SBMatrix operator+ (const SBMatrix &M1, const SBMatrix &M2)
SBMatrix operator- (const SBMatrix &M1, const SBMatrix &M2)
SBUpperMatrix operator+ (const SBUpperMatrix &M1, const SBUpperMatrix &M2)
SBUpperMatrix operator- (const SBUpperMatrix &M1, const SBUpperMatrix &M2)
SBSymMatrix operator+ (const SBSymMatrix &M1, const SBSymMatrix &M2)
SBSymMatrix operator- (const SBSymMatrix &M1, const SBSymMatrix &M2)
Function Documentation
SBMatrix operator+ (const SBMatrix &M1, const SBMatrix &M2)"Returns a sum of two matrices'.
Definition at line 1133 of file SbVector.H'.
References SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix operator+ (const SBUpperMatrix &M1, const SBUpperMatrix &M2)"Returns a sum of two matrices'.
Definition at line 1167 of file SbVector.H'.
References SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBSymMatrix operator+ (const SBSymMatrix &M1, const SBSymMatrix &M2)"Returns a sum of two matrices'.
Definition at line 1201 of file SbVector.H'.
References SBSymMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBMatrix operator- (const SBMatrix &M1, const SBMatrix &M2)"Returns a difference of two matrices'.
Definition at line 1146 of file SbVector.H'.
References SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix operator- (const SBUpperMatrix &M1, const SBUpperMatrix &M2)"Returns a difference of two matrices'.
Definition at line 1180 of file SbVector.H'.
References SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBSymMatrix operator- (const SBSymMatrix &M1, const SBSymMatrix &M2)"Returns a difference of two matrices'.
Definition at line 1214 of file SbVector.H'.
References SBSymMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.