SbVector.C
NAME
SbVector.C -
SYNOPSIS
#include 'SbVector.H'
Functions
QDataStream & operator<< (QDataStream &s, const SBVector &V)
QDataStream & operator>> (QDataStream &s, SBVector &V)
SBMatrix operator* (const SBMatrix &M1, const SBMatrix &M2)
SBMatrix matT_x_mat (const SBMatrix &M1, const SBMatrix &M2)
QDataStream & operator<< (QDataStream &s, const SBMatrix &M)
QDataStream & operator>> (QDataStream &s, SBMatrix &M)
SBUpperMatrix operator* (const SBUpperMatrix &M1, const SBUpperMatrix &M2)
SBSymMatrix matT_x_mat (const SBUpperMatrix &M1, const SBUpperMatrix &M2)
SBSymMatrix & RRT (SBSymMatrix &M, const SBUpperMatrix &R)
SBSymMatrix & RTR (SBSymMatrix &M, const SBUpperMatrix &R)
SBVector & Solve (const SBUpperMatrix &R, SBVector &x, const SBVector &z)
SBUpperMatrix operator~ (const SBUpperMatrix &R)
QDataStream & operator<< (QDataStream &s, const SBUpperMatrix &M)
QDataStream & operator>> (QDataStream &s, SBUpperMatrix &M)
SBSymMatrix operator* (const SBSymMatrix &M1, const SBSymMatrix &M2)
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBMatrix &A)
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBUpperMatrix &R)
QDataStream & operator<< (QDataStream &s, const SBSymMatrix &M)
QDataStream & operator>> (QDataStream &s, SBSymMatrix &M)
Function Documentation
SBMatrix matT_x_mat (const SBMatrix &M1, const SBMatrix &M2)"Returns a product of a transposed matrix and a matrix'. This function is equal to `M1'.T()*M2', but implements a more efficient realization'.
Definition at line 116 of file SbVector.C'.
References SBMatrix::B, SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBSymMatrix matT_x_mat (const SBUpperMatrix &M1, const SBUpperMatrix &M2)"Returns a product of a transposed matrix and a matrix'. This function is equal to `M1'.T()*M2', but implements a more efficient realization'.
Definition at line 195 of file SbVector.C'.
References SBMatrix::B, SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBMatrix operator* (const SBMatrix &M1, const SBMatrix &M2)"Returns product of two matrices'.
Definition at line 98 of file SbVector.C'.
References SBMatrix::B, SBMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBUpperMatrix operator* (const SBUpperMatrix &M1, const SBUpperMatrix &M2)"Returns product of two matrices'.
Definition at line 177 of file SbVector.C'.
References SBMatrix::B, SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
SBSymMatrix operator* (const SBSymMatrix &M1, const SBSymMatrix &M2)"Returns product of two matrices'.
Definition at line 445 of file SbVector.C'.
References SBSymMatrix::at(), SBSymMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBUpperMatrix::n(), SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
QDataStream& operator<< (QDataStream &s, const SBVector &V)
Definition at line 42 of file SbVector.C'.
References SBVector::B, and SBVector::N.
QDataStream& operator<< (QDataStream &s, const SBMatrix &M)
Definition at line 135 of file SbVector.C'.
References SBMatrix::B, SBMatrix::NCol, and SBMatrix::NRow.
QDataStream& operator<< (QDataStream &s, const SBUpperMatrix &M)
Definition at line 352 of file SbVector.C'.
References SBMatrix::B, and SBMatrix::NCol.
QDataStream& operator<< (QDataStream &s, const SBSymMatrix &M)
Definition at line 532 of file SbVector.C'.
QDataStream& operator>> (QDataStream &s, SBVector &V)
Definition at line 48 of file SbVector.C'.
References SBVector::B, and SBVector::N.
QDataStream& operator>> (QDataStream &s, SBMatrix &M)
Definition at line 143 of file SbVector.C'.
References SBMatrix::B, SBLog::ERR, SBLog::IO, Log, SBLog::MATRIX, SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
QDataStream& operator>> (QDataStream &s, SBUpperMatrix &M)
Definition at line 360 of file SbVector.C'.
References SBMatrix::B, SBLog::ERR, SBLog::IO, Log, SBLog::MATRIX, SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
QDataStream& operator>> (QDataStream &s, SBSymMatrix &M)
Definition at line 537 of file SbVector.C'.
SBUpperMatrix operator~ (const SBUpperMatrix &R)"Returns inversed matrix'. This is time consumed operation, shouldn't use in ordinary operations'. M*~M==~M*M==1 (original matrix doesn't change)'.
Definition at line 323 of file SbVector.C'.
References SBUpperMatrix::at(), SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBUpperMatrix::n(), SBNamed::name(), and SBLog::write().
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBMatrix &A)"Calculates the product of `A*P*A'.T()''. Returns symmetric matrix'.
Definition at line 468 of file SbVector.C'.
References SBMatrix::at(), SBSymMatrix::at(), SBSymMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Referenced by SBEstimator::solveLocals(), and SBEstimator::solveStochs().
SBSymMatrix QuadraticForm (const SBSymMatrix &P, const SBUpperMatrix &R)"Calculates the product of `A*P*A'.T()''. Returns symmetric matrix'.
Definition at line 500 of file SbVector.C'.
References SBUpperMatrix::at(), SBSymMatrix::at(), SBSymMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, SBMatrix::nRow(), and SBLog::write().
SBSymMatrix& RRT (SBSymMatrix &M, const SBUpperMatrix &R)"Returns a product of a `R*R'.T()' -- a matrix and its transposed one'. This function is equal to `M1*M1'.T()', but [should] implements a more efficient realization'.
Definition at line 246 of file SbVector.C'.
References SBUpperMatrix::at(), SBSymMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), SBEstimator::solveGlobals(), SBEstimator::solveLocals(), and SBEstimator::solveStochs().
SBSymMatrix& RTR (SBSymMatrix &M, const SBUpperMatrix &R)"Returns a product of a `R'.T()*R' -- a transposed matrix and the one'. This function is equal to `M1'.T()*M1', but [should] implements a more efficient realization'.
Definition at line 268 of file SbVector.C'.
References SBUpperMatrix::at(), SBSymMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBNamed::name(), SBMatrix::NCol, SBMatrix::NRow, and SBLog::write().
Referenced by writeNormalEquationSystem().
SBVector& Solve (const SBUpperMatrix &R, SBVector &x, const SBVector &z)"Solves an equation `R*x=z''. Returns vector x'. The order of arguments is the same as in the equation: R, x and z'.
Definition at line 290 of file SbVector.C'.
References SBVector::at(), SBUpperMatrix::at(), SBUpperMatrix::ClassName(), SBLog::ERR, Log, SBLog::MATRIX, SBVector::N, SBNamed::name(), SBMatrix::NRow, and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), SBEstimator::solveGlobals(), SBEstimator::solveLocals(), and SBEstimator::solveStochs().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.