SBVector
NAME
SBVector -
SYNOPSIS
#include <SbVector.H>
Inherits SBNamed'.
Public Member Functions
SBVector ()
SBVector (unsigned int N_, const QString &Name_, bool IsNeedClear=TRUE)
SBVector (const SBVector &V)
virtual ~SBVector ()
virtual QString ClassName () const
unsigned int n () const
double & operator() (unsigned int)
void set (unsigned int, double)
double at (unsigned int) const
double module () const
SBVector & unify ()
SBVector unit () const
void clear ()
SBVector & operator= (const SBVector &)
SBVector & operator= (double)
SBVector & operator+= (const SBVector &)
SBVector & operator-= (const SBVector &)
SBVector & operator*= (double)
SBVector & operator/= (double)
bool operator== (const SBVector &) const
bool operator!= (const SBVector &V) const
const QString & name () const
void setName (const QString &Name_)
Protected Attributes
unsigned int N
double * B
QString Name
Friends
class SBMatrix
class SBUpperMatrix
SBVector operator- (const SBVector &V)
SBVector operator/ (const SBVector &V, double f)
SBVector operator* (const SBVector &V, double f)
SBVector operator* (double f, const SBVector &V)
SBVector operator+ (const SBVector &, const SBVector &)
SBVector operator- (const SBVector &, const SBVector &)
double operator* (const SBVector &, const SBVector &)
SBVector operator* (const SBMatrix &, const SBVector &)
SBVector matT_x_vec (const SBMatrix &, const SBVector &)
SBVector matT_x_vec (const SBUpperMatrix &, const SBVector &)
SBVector retVector (unsigned int, const SBVector &)
SBVector & Solve (const SBUpperMatrix &, SBVector &, const SBVector &)
QDataStream & operator<< (QDataStream &, const SBVector &)
QDataStream & operator>> (QDataStream &, SBVector &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
Detailed Description
class Vector'.
Definition at line 55 of file SbVector.H'.
Constructor & Destructor Documentation
SBVector::SBVector () [inline]"A constructor'. Creates an empty vector (for I/O purposes)'.
Definition at line 69 of file SbVector.H'.
References B, and N.
Referenced by unit().
SBVector::SBVector (unsigned intN_, const QString &Name_, boolIsNeedClear = TRUE) [inline]"A constructor'. Creates a copy of object'.
Parameters:
N number of elements'.
Definition at line 74 of file SbVector.H'.
References B, clear(), and N.
SBVector::SBVector (const SBVector &V) [inline]"A constructor'. Creates a copy of object'.
Parameters:
V values of the new object'.
Definition at line 81 of file SbVector.H'.
References B, and N.
virtual SBVector::~SBVector () [inline, virtual]"A destructor'.
Definition at line 85 of file SbVector.H'.
References B.
Member Function Documentation
double SBVector::at (unsigned inti) const [inline]"Returns value of i-th element'.
Definition at line 177 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, N, SBNamed::name(), and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), SBMEM::calcA_Recusion(), SBFilterGauss::calcSigma(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), SBFilterModel::eliminateBefore(), SBFilterGauss::interpolate(), SBFilterGauss::interpolateMinusModel(), SBMEM::interval(), makeHouseholder(), SBEstimator::mapContStochs4NewBatch(), SBFilterModel::modelFull(), SBFilterModel::modelKeep(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), operator<<(), SBFilterGauss::prepareModels(), SBEstimator::processObs(), SBEstimator::propagateStochasticPars(), SBMEM::readDataFile(), SBSpectrumAnalyserMEM::redrawDataPlot(), SBMEM::removeShiftsFromData(), SBMEM::removeTrendsFromData(), SBFilterGauss::sigma(), sinex_SolutionNormalEquationVectorBlock(), Solve(), SBEstimator::solveLocals(), SBSpline::solveSpline(), SBEstimator::solveStochs(), SBParameterList::updateSolution(), and writeNormalEquationSystem().
virtual QString SBVector::ClassName () const [inline, virtual]"Refers to a class name (debug info)'.
Reimplemented from SBNamed'.
Definition at line 87 of file SbVector.H'.
Referenced by at(), operator()(), operator+=(), operator-=(), operator=(), operator==(), and set().
void SBVector::clear () [inline]"Fills elements with zero'.
Definition at line 109 of file SbVector.H'.
References B, and N.
Referenced by SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), makeHouseholder(), operator=(), SBEstimator::propagateStochasticPars(), SBVector(), SBFilterModel::setNumOfHarmonics(), SBFilterModel::setNumOfPolinoms(), and writeNormalEquationSystem().
double SBVector::module () const [inline]"Returns vector's module'.
Definition at line 187 of file SbVector.H'.
References B, and N.
Referenced by unify(), and unit().
unsigned int SBVector::n () const [inline]"Returns number of elements'.
Definition at line 92 of file SbVector.H'.
References N.
Referenced by SBDataSeriesEntry::n(), operator<<(), SBFilterGauss::readDataFile(), and SBParameterList::updateSolution().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
bool SBVector::operator!= (const SBVector &V) const [inline]"Comperes vector with another one, returns TRUE if values are different'.
Definition at line 125 of file SbVector.H'.
double & SBVector::operator() (unsigned inti) [inline]"Returns the reference to i-th element'.
Definition at line 156 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, N, SBNamed::name(), and SBLog::write().
SBVector & SBVector::operator*= (doublef) [inline]"Multiplies vector by scalar'.
Definition at line 239 of file SbVector.H'.
References B, and N.
SBVector & SBVector::operator+= (const SBVector &V) [inline]"Increments vector by another one'.
Definition at line 213 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, N, SBNamed::name(), and SBLog::write().
SBVector & SBVector::operator-= (const SBVector &V) [inline]"Decrements vector by another one'.
Definition at line 226 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, N, SBNamed::name(), and SBLog::write().
SBVector & SBVector::operator/= (doublef) [inline]"Divides vector by scalar'.
Definition at line 246 of file SbVector.H'.
References B, and N.
SBVector & SBVector::operator= (const SBVector &V) [inline]"Assign the vector to another one'.
Definition at line 194 of file SbVector.H'.
References B, ClassName(), clear(), SBLog::ERR, Log, SBLog::MATRIX, N, SBNamed::name(), and SBLog::write().
SBVector & SBVector::operator= (doublef) [inline]"Fills the vector with a double'.
Definition at line 206 of file SbVector.H'.
References B, and N.
bool SBVector::operator== (const SBVector &V) const [inline]"Comperes vector with another one, returns TRUE if values are equal'.
Definition at line 253 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, N, SBNamed::name(), and SBLog::write().
void SBVector::set (unsigned inti, doubled_) [inline]"Sets the i-th element to the double'.
Definition at line 166 of file SbVector.H'.
References B, ClassName(), SBLog::ERR, Log, SBLog::MATRIX, N, SBNamed::name(), and SBLog::write().
Referenced by SBFilterModel::analyseSeries(), SBMEM::calcA_LSBackward(), SBMEM::calcA_LSFnB(), SBMEM::calcA_LSForward(), SBFilterGauss::calcSigma(), SBEstimator::dataUpdate(), SBEstimator::dataUpdateGlobalConstr(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBFilterGauss::interpolate(), SBFilterGauss::interpolateMinusModel(), makeHouseholder(), SBEstimator::mapContStochs4NewBatch(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBEstimator::processConstr(), SBEstimator::processGlobalConstr(), SBEstimator::processObs(), SBEstimator::propagateStochasticPars(), SBMEM::readDataFile(), SBFilterGauss::readDataFile(), SBMEM::removeShiftsFromData(), SBMEM::removeTrendsFromData(), SBEstimator::solveLocals(), SBEstimator::solveStochs(), and writeNormalEquationSystem().
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
SBVector& SBVector::unify () [inline]"Unifies vector and returns reference to it'.
Definition at line 105 of file SbVector.H'.
References module().
SBVector SBVector::unit () const [inline]"Returns value of unified vector'.
Definition at line 107 of file SbVector.H'.
References module(), and SBVector().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
SBVector matT_x_vec (const SBMatrix &, const SBVector &) [friend]
SBVector matT_x_vec (const SBUpperMatrix &, const SBVector &) [friend]
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
SBVector operator* (const SBVector &V, doublef) [friend]
Definition at line 131 of file SbVector.H'.
SBVector operator* (doublef, const SBVector &V) [friend]
Definition at line 132 of file SbVector.H'.
double operator* (const SBVector &V1, const SBVector &V2) [friend]"Returns a scalar product of two vectors
Definition at line 1112 of file SbVector.H'.
SBVector operator* (const SBMatrix &, const SBVector &) [friend]
SBVector operator+ (const SBVector &V1, const SBVector &V2) [friend]"Returns a sum of two vectors
Definition at line 1082 of file SbVector.H'.
SBVector operator- (const SBVector &V) [friend]
Definition at line 129 of file SbVector.H'.
SBVector operator- (const SBVector &V1, const SBVector &V2) [friend]"Returns a difference of two vectors
Definition at line 1097 of file SbVector.H'.
SBVector operator/ (const SBVector &V, doublef) [friend]
Definition at line 130 of file SbVector.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBVector &V) [friend]
Definition at line 42 of file SbVector.C'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBVector &V) [friend]
Definition at line 48 of file SbVector.C'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
SBVector retVector (unsignedint, const SBVector &) [friend]
friend class SBMatrix [friend]
Definition at line 57 of file SbVector.H'.
friend class SBUpperMatrix [friend]
Definition at line 58 of file SbVector.H'.
SBVector& Solve (const SBUpperMatrix &R, SBVector &x, const SBVector &z) [friend]
Definition at line 290 of file SbVector.C'.
Member Data Documentation
double* SBVector::B [protected]
Definition at line 61 of file SbVector.H'.
Referenced by at(), clear(), module(), operator()(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<(), operator=(), operator==(), operator>>(), SBVector(), set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBMatrix::setVector(), SBUpperMatrix::setVector(), and ~SBVector().
unsigned int SBVector::N [protected]
Definition at line 60 of file SbVector.H'.
Referenced by at(), clear(), module(), n(), operator()(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<(), operator=(), operator==(), operator>>(), SBVector(), set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBMatrix::setVector(), SBUpperMatrix::setVector(), and Solve().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.