SBVersion
NAME
SBVersion -
SYNOPSIS
#include <SbGeneral.H>
Public Member Functions
SBVersion (int Major_=2, int Minor_=0, int Teeny_=0)
QString toString () const
const QString & selfName () const
QString name () const
bool operator== (const SBVersion &v) const
bool operator!= (const SBVersion &v) const
bool operator< (const SBVersion &v) const
bool operator<= (const SBVersion &v) const
bool operator> (const SBVersion &v) const
bool operator>= (const SBVersion &v) const
Protected Attributes
int MajorVersion
int MinorVersion
int TeenyVersion
Static Protected Attributes
static QString SelfName
Friends
QDataStream & operator<< (QDataStream &s, const SBVersion &v)
QDataStream & operator>> (QDataStream &s, SBVersion &v)
Detailed Description
Definition at line 161 of file SbGeneral.H'.
Constructor & Destructor Documentation
SBVersion::SBVersion (intMajor_ = 2, intMinor_ = 0, intTeeny_ = 0) [inline]
Definition at line 169 of file SbGeneral.H'.
Member Function Documentation
QString SBVersion::name () const [inline]
Definition at line 176 of file SbGeneral.H'.
References MajorVersion, MinorVersion, SelfName, and TeenyVersion.
Referenced by SBSolution::dumpParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRFVariations(), and SBMainWindow::setupStatusBar().
bool SBVersion::operator!= (const SBVersion &v) const [inline]
Definition at line 189 of file SbGeneral.H'.
bool SBVersion::operator< (const SBVersion &v) const [inline]
Definition at line 190 of file SbGeneral.H'.
References MajorVersion, MinorVersion, and TeenyVersion.
bool SBVersion::operator<= (const SBVersion &v) const [inline]
Definition at line 196 of file SbGeneral.H'.
References MajorVersion, MinorVersion, and TeenyVersion.
bool SBVersion::operator== (const SBVersion &v) const [inline]
Definition at line 183 of file SbGeneral.H'.
References MajorVersion, MinorVersion, and TeenyVersion.
bool SBVersion::operator> (const SBVersion &v) const [inline]
Definition at line 202 of file SbGeneral.H'.
References MajorVersion, MinorVersion, and TeenyVersion.
bool SBVersion::operator>= (const SBVersion &v) const [inline]
Definition at line 208 of file SbGeneral.H'.
References MajorVersion, MinorVersion, and TeenyVersion.
const QString& SBVersion::selfName () const [inline]
Definition at line 175 of file SbGeneral.H'.
References SelfName.
Referenced by SBSetUp::CheckDir(), SBSolution::checkPath(), SBMainWindow::ExecuteDrop(), handlerSIGs(), SBMainWindow::HelpAbout(), SBMainWindow::HelpAboutQt(), SBSetUp::LoadConfig(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRFVariations(), SBEstimator::prepare4Local(), SBPlot::save2PS(), SBEstimator::SBEstimator(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), and sinex_FileReferenceBlock().
QString SBVersion::toString () const [inline]
Definition at line 172 of file SbGeneral.H'.
References MajorVersion, MinorVersion, and TeenyVersion.
Referenced by handlerSIGs(), SBMainWindow::HelpAbout(), SBPlot::save2PS(), and sinex_FileReferenceBlock().
Friends And Related Function Documentation
QDataStream& operator<< (QDataStream &s, const SBVersion &v) [friend]
Definition at line 179 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBVersion &v) [friend]
Definition at line 181 of file SbGeneral.H'.
Member Data Documentation
int SBVersion::MajorVersion [protected]
Definition at line 164 of file SbGeneral.H'.
Referenced by name(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and toString().
int SBVersion::MinorVersion [protected]
Definition at line 165 of file SbGeneral.H'.
Referenced by name(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and toString().
QString SBVersion::SelfName [static, protected]
Definition at line 167 of file SbGeneral.H'.
Referenced by name(), and selfName().
int SBVersion::TeenyVersion [protected]
Definition at line 166 of file SbGeneral.H'.
Referenced by name(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and toString().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.