.TH "SBVersion" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBVersion \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeneral\&.H>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBVersion\fP (int Major_=2, int Minor_=0, int Teeny_=0)"
.br
.ti -1c
.RI "QString \fBtoString\fP () const "
.br
.ti -1c
.RI "const QString & \fBselfName\fP () const "
.br
.ti -1c
.RI "QString \fBname\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSBVersion\fP &v) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSBVersion\fP &v) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSBVersion\fP &v) const "
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBSBVersion\fP &v) const "
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBSBVersion\fP &v) const "
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBSBVersion\fP &v) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBMajorVersion\fP"
.br
.ti -1c
.RI "int \fBMinorVersion\fP"
.br
.ti -1c
.RI "int \fBTeenyVersion\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static QString \fBSelfName\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBSBVersion\fP &v)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSBVersion\fP &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 161 of file SbGeneral\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBVersion::SBVersion (intMajor_ = \fC2\fP, intMinor_ = \fC0\fP, intTeeny_ = \fC0\fP)\fC [inline]\fP"
.PP
Definition at line 169 of file SbGeneral\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "QString SBVersion::name () const\fC [inline]\fP"
.PP
Definition at line 176 of file SbGeneral\&.H'\&.
.PP
References MajorVersion, MinorVersion, SelfName, and TeenyVersion\&.
.PP
Referenced by SBSolution::dumpParameters(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRFVariations(), and SBMainWindow::setupStatusBar()\&.
.SS "bool SBVersion::operator!= (const \fBSBVersion\fP &v) const\fC [inline]\fP"
.PP
Definition at line 189 of file SbGeneral\&.H'\&.
.SS "bool SBVersion::operator< (const \fBSBVersion\fP &v) const\fC [inline]\fP"
.PP
Definition at line 190 of file SbGeneral\&.H'\&.
.PP
References MajorVersion, MinorVersion, and TeenyVersion\&.
.SS "bool SBVersion::operator<= (const \fBSBVersion\fP &v) const\fC [inline]\fP"
.PP
Definition at line 196 of file SbGeneral\&.H'\&.
.PP
References MajorVersion, MinorVersion, and TeenyVersion\&.
.SS "bool SBVersion::operator== (const \fBSBVersion\fP &v) const\fC [inline]\fP"
.PP
Definition at line 183 of file SbGeneral\&.H'\&.
.PP
References MajorVersion, MinorVersion, and TeenyVersion\&.
.SS "bool SBVersion::operator> (const \fBSBVersion\fP &v) const\fC [inline]\fP"
.PP
Definition at line 202 of file SbGeneral\&.H'\&.
.PP
References MajorVersion, MinorVersion, and TeenyVersion\&.
.SS "bool SBVersion::operator>= (const \fBSBVersion\fP &v) const\fC [inline]\fP"
.PP
Definition at line 208 of file SbGeneral\&.H'\&.
.PP
References MajorVersion, MinorVersion, and TeenyVersion\&.
.SS "const QString& SBVersion::selfName () const\fC [inline]\fP"
.PP
Definition at line 175 of file SbGeneral\&.H'\&.
.PP
References SelfName\&.
.PP
Referenced by SBSetUp::CheckDir(), SBSolution::checkPath(), SBMainWindow::ExecuteDrop(), handlerSIGs(), SBMainWindow::HelpAbout(), SBMainWindow::HelpAboutQt(), SBSetUp::LoadConfig(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRFVariations(), SBEstimator::prepare4Local(), SBPlot::save2PS(), SBEstimator::SBEstimator(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), and sinex_FileReferenceBlock()\&.
.SS "QString SBVersion::toString () const\fC [inline]\fP"
.PP
Definition at line 172 of file SbGeneral\&.H'\&.
.PP
References MajorVersion, MinorVersion, and TeenyVersion\&.
.PP
Referenced by handlerSIGs(), SBMainWindow::HelpAbout(), SBPlot::save2PS(), and sinex_FileReferenceBlock()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream &s, const \fBSBVersion\fP &v)\fC [friend]\fP"
.PP
Definition at line 179 of file SbGeneral\&.H'\&.
.SS "QDataStream& operator>> (QDataStream &s, \fBSBVersion\fP &v)\fC [friend]\fP"
.PP
Definition at line 181 of file SbGeneral\&.H'\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBSBVersion::MajorVersion\fP\fC [protected]\fP"
.PP
Definition at line 164 of file SbGeneral\&.H'\&.
.PP
Referenced by name(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and toString()\&.
.SS "int \fBSBVersion::MinorVersion\fP\fC [protected]\fP"
.PP
Definition at line 165 of file SbGeneral\&.H'\&.
.PP
Referenced by name(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and toString()\&.
.SS "QString \fBSBVersion::SelfName\fP\fC [static, protected]\fP"
.PP
Definition at line 167 of file SbGeneral\&.H'\&.
.PP
Referenced by name(), and selfName()\&.
.SS "int \fBSBVersion::TeenyVersion\fP\fC [protected]\fP"
.PP
Definition at line 166 of file SbGeneral\&.H'\&.
.PP
Referenced by name(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and toString()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
