SBVLBIObsLI
NAME
SBVLBIObsLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QListViewItem'.
Inherited by SBVLBIObsPPLI'.
Public Member Functions
SBVLBIObsLI (QListView *parent, SBVLBISession *Sess_, SBObsVLBIEntry *Obs_)
SBObsVLBIEntry * obs ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Protected Attributes
SBObsVLBIEntry * Obs
SBVLBISession * Sess
Detailed Description
Definition at line 107 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBIObsLI::SBVLBIObsLI (QListView *parent, SBVLBISession *Sess_, SBObsVLBIEntry *Obs_) [inline]
Definition at line 113 of file SbIObsVLBI.H'.
References Obs, and Sess.
Member Function Documentation
virtual QString SBVLBIObsLI::ClassName () const [inline, virtual]
Reimplemented in SBVLBIObsPPLI'.
Definition at line 116 of file SbIObsVLBI.H'.
QString SBVLBIObsLI::key (intcol, bool) const [virtual]
Reimplemented in SBVLBIObsPPLI'.
Definition at line 415 of file SbIObsVLBI.C'.
References SBObsVLBIEntry::ambiguityFactor(), SBObsVLBIEntry::BadCable1, SBObsVLBIEntry::BadCable2, SBObsVLBIEntry::BadMeteo1, SBObsVLBIEntry::BadMeteo2, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBObsVLBIEntry::delayErr(), SBObsVLBIEntry::delayRes(), SBObsVLBIEntry::dUFlag(), SBObservation::idx(), SBObsVLBIEntry::ionErrorFlag(), SBAttributed::isAttr(), SBObservation::mjd(), SBObservation::notValid, Obs, SBObsVLBIEntry::qualCode(), SBObsVLBIEntry::rateErr(), SBObsVLBIEntry::rateRes(), SBObsVLBIEntry::rUFlag(), Sess, SBObsVLBIEntry::sourceIdx(), SBVLBISession::sourceInfo(), SBObsVLBIEntry::station_1Idx(), SBObsVLBIEntry::station_2Idx(), SBVLBISession::stationInfo(), and TmpString.
SBObsVLBIEntry* SBVLBIObsLI::obs () [inline]
Definition at line 115 of file SbIObsVLBI.H'.
References Obs.
QString SBVLBIObsLI::text (intcol) const [virtual]
Reimplemented in SBVLBIObsPPLI'.
Definition at line 339 of file SbIObsVLBI.C'.
References SBObsVLBIEntry::ambiguityFactor(), SBObsVLBIEntry::BadCable1, SBObsVLBIEntry::BadCable2, SBObsVLBIEntry::BadMeteo1, SBObsVLBIEntry::BadMeteo2, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBDelay::CLight, SBObsVLBIEntry::delayErr(), SBObsVLBIEntry::delayRes(), SBObsVLBIEntry::dUFlag(), SBMJD::F_HHMMSS, SBObservation::idx(), SBObsVLBIEntry::ionErrorFlag(), SBAttributed::isAttr(), SBObservation::notValid, Obs, SBObsVLBIEntry::qualCode(), SBObsVLBIEntry::rateErr(), SBObsVLBIEntry::rateRes(), SBObsVLBIEntry::rUFlag(), Sess, SetUp, SBObsVLBIEntry::sourceIdx(), SBVLBISession::sourceInfo(), SBObsVLBIEntry::station_1Idx(), SBObsVLBIEntry::station_2Idx(), SBVLBISession::stationInfo(), TmpString, SBMJD::toString(), SBSetUp::U_INCH, SBSetUp::U_METER, SBSetUp::U_SEC, and SBSetUp::units().
Member Data Documentation
SBObsVLBIEntry* SBVLBIObsLI::Obs [protected]
Definition at line 110 of file SbIObsVLBI.H'.
Referenced by SBVLBIObsPPLI::key(), key(), obs(), SBVLBIObsPPLI::paintCell(), SBVLBIObsLI(), SBVLBIObsPPLI::text(), and text().
SBVLBISession* SBVLBIObsLI::Sess [protected]
Definition at line 111 of file SbIObsVLBI.H'.
Referenced by SBVLBIObsPPLI::key(), key(), SBVLBIObsPPLI::paintCell(), SBVLBIObsLI(), SBVLBIObsPPLI::text(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.