SBVLBISetView
NAME
SBVLBISetView -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits SBVLBISetViewBase'.
Signals
void stBarReset ()
void stBarSetTotalSteps (int)
void stBarSetProgress (int)
void message (const QString &)
Public Member Functions
SBVLBISetView (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBVLBISetView ()
virtual QString ClassName () const
Protected Member Functions
virtual void drawInfo ()
virtual QWidget * VLBIList (QWidget *, BrowseMode, SBProject *)
virtual QWidget * unitsGroup (QWidget *)
virtual QWidget * infoGroup (QWidget *)
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
SBVLBISet * Wvlbi
QString str
SBBrowseSessions * brwsSes
QLabel * LNumSes
QLabel * LNumObs
QLabel * LNumPPS
QRadioButton * RBUnit [3]
bool isModified
int numOpenedWindows
Private Slots
void networksModified (bool, SBVLBISet::NetList *)
void masterRecordModified (bool)
void importNGS ()
void importDBH ()
void import (SBVLBISession::ObsImportedFrom)
void editEntry (QListViewItem *)
void deleteEntry ()
void editNetworks ()
void browseMRecords ()
Private Member Functions
virtual void init ()
virtual QWidget * optionsGroup (QWidget *)
Private Attributes
QCheckBox * CBDump
QPushButton * Delete
QRadioButton * RBIfExistedAskUser
QRadioButton * RBIfExistedDrop
QRadioButton * RBIfExistedImport
Detailed Description
Definition at line 467 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBISetView::SBVLBISetView (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 1912 of file SbIObsVLBI.C'.
References init().
virtual SBVLBISetView::~SBVLBISetView () [inline, virtual]
Definition at line 472 of file SbIObsVLBI.H'.
Member Function Documentation
void SBVLBISetView::browseMRecords () [private, slot]
Definition at line 2168 of file SbIObsVLBI.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, masterRecordModified(), SBVLBISetViewBase::numOpenedWindows, SBLog::write(), and SBVLBISetViewBase::Wvlbi.
Referenced by init().
virtual QString SBVLBISetView::ClassName () const [inline, virtual]
Reimplemented from SBVLBISetViewBase'.
Definition at line 474 of file SbIObsVLBI.H'.
Referenced by browseMRecords(), deleteEntry(), editEntry(), editNetworks(), and import().
virtual void SBVLBISetViewBase::closeEvent (QCloseEvent *e) [inline, protected, virtual, inherited]
Definition at line 456 of file SbIObsVLBI.H'.
References SBVLBISetViewBase::numOpenedWindows.
void SBVLBISetView::deleteEntry () [private, slot]
Definition at line 2054 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, ClassName(), SBLog::DBG, Delete, SBVLBISetViewBase::drawInfo(), SBLog::INTERFACE, SBVLBISetViewBase::isModified, Log, SBBrowseSessions::lvSessions(), SBNamed::name(), SBVLBISet::removeSession(), SBVLBISesInfoLI::sessionInfo(), SBVLBISetViewBase::str, SBLog::write(), and SBVLBISetViewBase::Wvlbi.
Referenced by init().
void SBVLBISetViewBase::drawInfo () [protected, virtual, inherited]
Reimplemented in SBProjectCreate'.
Definition at line 1883 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, SBVLBISetViewBase::LNumObs, SBVLBISetViewBase::LNumPPS, SBVLBISetViewBase::LNumSes, SBBrowseSessions::numPPSess(), SBVLBISetViewBase::str, SBVLBISet::totalObs(), and SBVLBISetViewBase::Wvlbi.
Referenced by deleteEntry(), import(), and SBVLBISetViewBase::infoGroup().
void SBVLBISetView::editEntry (QListViewItem *SesItem) [private, slot]
Definition at line 2044 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::childWindowClosed(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, SBVLBISetViewBase::modified(), SBVLBISetViewBase::numOpenedWindows, SBLog::write(), and SBVLBISetViewBase::Wvlbi.
void SBVLBISetView::editNetworks () [private, slot]
Definition at line 2158 of file SbIObsVLBI.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, networksModified(), SBVLBISetViewBase::numOpenedWindows, SBLog::write(), and SBVLBISetViewBase::Wvlbi.
Referenced by init().
void SBVLBISetView::import (SBVLBISession::ObsImportedFromIType) [private, slot]
Definition at line 2084 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, CBDump, ClassName(), SBLog::DATA, SBLog::DBG, SBVLBISetViewBase::drawInfo(), SBVLBISet::import(), SBLog::INTERFACE, SBLog::IO, SBVLBISetViewBase::isModified, SBVLBISet::loadMaster(), Log, message(), SBVLBISetViewBase::numOpenedWindows, SBSetUp::path2Compil(), RBIfExistedDrop, RBIfExistedImport, SBVLBISet::releaseMaster(), SetUp, stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), SBBrowseSessions::updateList(), SBLog::write(), and SBVLBISetViewBase::Wvlbi.
void SBVLBISetView::importDBH () [inline, private, slot]
Definition at line 488 of file SbIObsVLBI.H'.
References SBVLBISesInfo::IF_DBH.
Referenced by init().
void SBVLBISetView::importNGS () [inline, private, slot]
Definition at line 487 of file SbIObsVLBI.H'.
References SBVLBISesInfo::IF_NGS.
Referenced by init().
QWidget * SBVLBISetViewBase::infoGroup (QWidget *parent) [protected, virtual, inherited]
Definition at line 1828 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, SBVLBISetViewBase::drawInfo(), SBVLBISetViewBase::LNumObs, SBVLBISetViewBase::LNumPPS, SBVLBISetViewBase::LNumSes, SBBrowseSessions::numObs(), SBBrowseSessions::numPPSess(), SBVLBISetViewBase::str, and SBVLBISetViewBase::Wvlbi.
Referenced by SBProjectCreate::init(), and init().
void SBVLBISetView::init () [private, virtual]
Implements SBVLBISetViewBase'.
Definition at line 1918 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::accept(), BM_GENERAL, browseMRecords(), Delete, deleteEntry(), editNetworks(), importDBH(), importNGS(), SBVLBISetViewBase::infoGroup(), MainWin, message(), optionsGroup(), SBVLBISetViewBase::reject(), stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), SBVLBISetViewBase::unitsGroup(), and SBVLBISetViewBase::VLBIList().
Referenced by SBVLBISetView().
void SBVLBISetView::masterRecordModified (boolisModified_) [private, slot]
Definition at line 2035 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::isModified, and SBVLBISetViewBase::numOpenedWindows.
Referenced by browseMRecords().
void SBVLBISetView::message (const QString &t0) [signal]
Definition at line 687 of file SbIObsVLBI.moc.C'.
Referenced by import(), and init().
void SBVLBISetView::networksModified (boolisModified_, SBVLBISet::NetList *Nets_) [private, slot]
Definition at line 2023 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::isModified, SBVLBISet::networks(), SBVLBISetViewBase::numOpenedWindows, and SBVLBISetViewBase::Wvlbi.
Referenced by editNetworks().
QWidget * SBVLBISetView::optionsGroup (QWidget *parent) [private, virtual]
Reimplemented from SBVLBISetViewBase'.
Definition at line 1983 of file SbIObsVLBI.C'.
References CBDump, RBIfExistedAskUser, RBIfExistedDrop, and RBIfExistedImport.
Referenced by init().
void SBVLBISetView::stBarReset () [signal]
Definition at line 669 of file SbIObsVLBI.moc.C'.
Referenced by import(), and init().
void SBVLBISetView::stBarSetProgress (intt0) [signal]
Definition at line 681 of file SbIObsVLBI.moc.C'.
Referenced by import(), and init().
void SBVLBISetView::stBarSetTotalSteps (intt0) [signal]
Definition at line 675 of file SbIObsVLBI.moc.C'.
Referenced by import(), and init().
QWidget * SBVLBISetViewBase::unitsGroup (QWidget *parent) [protected, virtual, inherited]
Definition at line 1803 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::RBUnit, SetUp, SBSetUp::units(), and SBVLBISetViewBase::unitsChanged().
Referenced by SBProjectCreate::init(), and init().
QWidget * SBVLBISetViewBase::VLBIList (QWidget *parent, BrowseModeMode_, SBProject *Prj) [protected, virtual, inherited]
Reimplemented in SBVLBIPreProcess'.
Definition at line 1793 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, SBBrowseSessions::lvSessions(), and SBVLBISetViewBase::Wvlbi.
Referenced by SBProjectCreate::init(), and init().
Member Data Documentation
SBBrowseSessions* SBVLBISetViewBase::brwsSes [protected, inherited]
Definition at line 441 of file SbIObsVLBI.H'.
Referenced by SBVLBIPreProcess::auxWindowsChanged(), SBVLBIPreProcess::blockInput(), SBProjectCreate::createProject(), deleteEntry(), SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), import(), SBVLBISetViewBase::infoGroup(), SBProjectCreate::init(), SBVLBIPreProcess::procScenario_4(), SBVLBIPreProcess::restoreInput(), SBProjectCreate::selectAll(), SBProjectCreate::unselectAll(), SBVLBIPreProcess::VLBIList(), and SBVLBISetViewBase::VLBIList().
QCheckBox* SBVLBISetView::CBDump [private]
Definition at line 497 of file SbIObsVLBI.H'.
Referenced by import(), and optionsGroup().
QPushButton* SBVLBISetView::Delete [private]
Definition at line 499 of file SbIObsVLBI.H'.
Referenced by deleteEntry(), and init().
bool SBVLBISetViewBase::isModified [protected, inherited]
Definition at line 446 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), deleteEntry(), import(), masterRecordModified(), SBVLBISetViewBase::modified(), networksModified(), SBVLBIPreProcess::saveSession(), SBVLBISetViewBase::SBVLBISetViewBase(), SBVLBIPreProcess::toggleEntryMarkEnable(), SBVLBIPreProcess::toggleEntryMoveEnable(), and SBVLBIPreProcess::~SBVLBIPreProcess().
QLabel* SBVLBISetViewBase::LNumObs [protected, inherited]
Definition at line 443 of file SbIObsVLBI.H'.
Referenced by SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
QLabel* SBVLBISetViewBase::LNumPPS [protected, inherited]
Definition at line 444 of file SbIObsVLBI.H'.
Referenced by SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
QLabel* SBVLBISetViewBase::LNumSes [protected, inherited]
Definition at line 442 of file SbIObsVLBI.H'.
Referenced by SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
int SBVLBISetViewBase::numOpenedWindows [protected, inherited]
Definition at line 447 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), browseMRecords(), SBVLBISetViewBase::childWindowClosed(), SBVLBISetViewBase::closeEvent(), SBProjectCreate::editEntry(), editEntry(), editNetworks(), import(), masterRecordModified(), networksModified(), SBVLBISetViewBase::reject(), and SBVLBISetViewBase::SBVLBISetViewBase().
QRadioButton* SBVLBISetView::RBIfExistedAskUser [private]
Definition at line 500 of file SbIObsVLBI.H'.
Referenced by optionsGroup().
QRadioButton* SBVLBISetView::RBIfExistedDrop [private]
Definition at line 501 of file SbIObsVLBI.H'.
Referenced by import(), and optionsGroup().
QRadioButton* SBVLBISetView::RBIfExistedImport [private]
Definition at line 502 of file SbIObsVLBI.H'.
Referenced by import(), and optionsGroup().
QRadioButton* SBVLBISetViewBase::RBUnit[3] [protected, inherited]
Definition at line 445 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::unitsGroup().
QString SBVLBISetViewBase::str [protected, inherited]
Definition at line 439 of file SbIObsVLBI.H'.
Referenced by deleteEntry(), SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
SBVLBISet* SBVLBISetViewBase::Wvlbi [protected, inherited]
Definition at line 436 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), browseMRecords(), SBVLBIPreProcess::clearPars(), SBProjectCreate::createProject(), SBVLBIPreProcess::currentSesChange(), deleteEntry(), SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), SBProjectCreate::editEntry(), editEntry(), editNetworks(), SBVLBIPreProcess::fillSessAttr(), SBVLBIPreProcess::fixSession(), import(), SBVLBISetViewBase::infoGroup(), networksModified(), SBVLBIPreProcess::preProcess(), SBVLBIPreProcess::saveSession(), SBVLBISetViewBase::SBVLBISetViewBase(), SBVLBIPreProcess::VLBIList(), SBVLBISetViewBase::VLBIList(), SBVLBIPreProcess::wAttributes(), SBVLBIPreProcess::~SBVLBIPreProcess(), and SBVLBISetViewBase::~SBVLBISetViewBase().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.