SBVLBINetworkEditor
NAME
SBVLBINetworkEditor -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QDialog'.
Classes
class NetworkListItem
Signals
void networksModified (bool, SBVLBISet::NetList *)
Public Member Functions
SBVLBINetworkEditor (SBVLBISet *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBVLBINetworkEditor ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
void addEntry ()
void editEntry ()
void deleteEntry ()
void entryModified (bool, SBVLBISet::Network *)
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Private Attributes
SBVLBISet * Wvlbi
SBVLBISet::NetList * Nets
bool isModified
int numOpenedWindows
QString Str
QListView * NetsLV
Detailed Description
Definition at line 586 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBINetworkEditor::SBVLBINetworkEditor (SBVLBISet *W_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2756 of file SbIObsVLBI.C'.
References accept(), addEntry(), deleteEntry(), editEntry(), isModified, Nets, NetsLV, SBVLBISet::networks(), numOpenedWindows, reject(), and Wvlbi.
SBVLBINetworkEditor::~SBVLBINetworkEditor ()
Definition at line 2839 of file SbIObsVLBI.C'.
References isModified, Nets, and networksModified().
Member Function Documentation
void SBVLBINetworkEditor::accept () [protected, slot]
Definition at line 2844 of file SbIObsVLBI.C'.
References numOpenedWindows.
Referenced by SBVLBINetworkEditor().
void SBVLBINetworkEditor::addEntry () [protected, slot]
Definition at line 2858 of file SbIObsVLBI.C'.
References ClassName(), SBLog::DBG, entryModified(), SBLog::INTERFACE, Log, numOpenedWindows, and SBLog::write().
Referenced by SBVLBINetworkEditor().
virtual QString SBVLBINetworkEditor::ClassName () const [inline, virtual]
Definition at line 592 of file SbIObsVLBI.H'.
Referenced by addEntry(), deleteEntry(), and editEntry().
virtual void SBVLBINetworkEditor::closeEvent (QCloseEvent *e) [inline, protected, virtual]
Definition at line 626 of file SbIObsVLBI.H'.
References numOpenedWindows.
void SBVLBINetworkEditor::deleteEntry () [protected, slot]
Definition at line 2881 of file SbIObsVLBI.C'.
References ClassName(), SBLog::DBG, SBLog::INTERFACE, isModified, Log, Nets, NetsLV, and SBLog::write().
Referenced by SBVLBINetworkEditor().
void SBVLBINetworkEditor::editEntry () [protected, slot]
Definition at line 2869 of file SbIObsVLBI.C'.
References ClassName(), SBLog::DBG, entryModified(), SBLog::INTERFACE, Log, NetsLV, numOpenedWindows, and SBLog::write().
Referenced by SBVLBINetworkEditor().
void SBVLBINetworkEditor::entryModified (boolisModified_, SBVLBISet::Network *N_) [protected, slot]
Definition at line 2902 of file SbIObsVLBI.C'.
References isModified, Nets, NetsLV, and numOpenedWindows.
Referenced by addEntry(), and editEntry().
void SBVLBINetworkEditor::networksModified (boolt0, SBVLBISet::NetList *t1) [signal]
Definition at line 919 of file SbIObsVLBI.moc.C'.
Referenced by ~SBVLBINetworkEditor().
void SBVLBINetworkEditor::reject () [protected, slot]
Definition at line 2851 of file SbIObsVLBI.C'.
References numOpenedWindows.
Referenced by SBVLBINetworkEditor().
Member Data Documentation
bool SBVLBINetworkEditor::isModified [private]
Definition at line 620 of file SbIObsVLBI.H'.
Referenced by deleteEntry(), entryModified(), SBVLBINetworkEditor(), and ~SBVLBINetworkEditor().
SBVLBISet::NetList* SBVLBINetworkEditor::Nets [private]
Definition at line 619 of file SbIObsVLBI.H'.
Referenced by deleteEntry(), entryModified(), SBVLBINetworkEditor(), and ~SBVLBINetworkEditor().
QListView* SBVLBINetworkEditor::NetsLV [private]
Definition at line 624 of file SbIObsVLBI.H'.
Referenced by deleteEntry(), editEntry(), entryModified(), and SBVLBINetworkEditor().
int SBVLBINetworkEditor::numOpenedWindows [private]
Definition at line 621 of file SbIObsVLBI.H'.
Referenced by accept(), addEntry(), closeEvent(), editEntry(), entryModified(), reject(), and SBVLBINetworkEditor().
QString SBVLBINetworkEditor::Str [private]
Definition at line 622 of file SbIObsVLBI.H'.
SBVLBISet* SBVLBINetworkEditor::Wvlbi [private]
Definition at line 618 of file SbIObsVLBI.H'.
Referenced by SBVLBINetworkEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.