SBVLBIPreProcess
NAME
SBVLBIPreProcess -
SYNOPSIS
#include <SbIPreProcessing.H>
Inherits SBVLBISetViewBase'.
Signals
void stBarReset ()
void stBarSetTotalSteps (int)
void stBarSetProgress (int)
void message (const QString &)
void run (bool)
Public Member Functions
SBVLBIPreProcess (QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
virtual ~SBVLBIPreProcess ()
virtual QString ClassName () const
Protected Member Functions
virtual void drawInfo ()
virtual QWidget * unitsGroup (QWidget *)
virtual QWidget * optionsGroup (QWidget *)
virtual QWidget * infoGroup (QWidget *)
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
SBVLBISet * Wvlbi
QString str
SBBrowseSessions * brwsSes
QLabel * LNumSes
QLabel * LNumObs
QLabel * LNumPPS
QRadioButton * RBUnit [3]
bool isModified
int numOpenedWindows
Private Slots
void auxWindowsChanged (bool)
void currentSesChange (QListViewItem *)
void preProcess ()
void doubleProc ()
void procScenario_1 ()
void procScenario_2 ()
void procScenario_3 ()
void procScenario_4 ()
void stopLongRun ()
void fixSession ()
void clearPars ()
void toggleEntryMarkEnable (int, QListViewItem *, const QPoint &, int)
void toggleEntryMoveEnable (QListViewItem *, int, Qt::ButtonState)
void dumpUI ()
void restoreUI ()
void ambigJumpChanged (int)
Private Member Functions
virtual QWidget * VLBIList (QWidget *, BrowseMode, SBProject *)
virtual void init ()
virtual QWidget * sesTab (QWidget *)
QWidget * wEstPars (QWidget *)
QWidget * wObservs ()
QWidget * wAttributes ()
QWidget * wDataPlotsByBases ()
QWidget * wDataPlotsByStations ()
QWidget * wDataPlotsBySources ()
void saveSession ()
void updateSession ()
void fillObsListView ()
void fillSessAttr ()
void blockInput ()
void restoreInput ()
Private Attributes
bool IsNeedEstimateCables
QTabWidget * SesTab
QPushButton * Clear
QPushButton * Run
QPushButton * Fix
QPushButton * Ok
QPushButton * DumpUI
QPushButton * RestoreUI
bool IsBlockedSessionList
bool IsBlockedStationList
bool IsBlockedHistoryList
bool IsBlockedClearButton
bool IsBlockedRunButton
bool IsBlockedFixButton
bool IsBlockedOkButton
bool IsBlockedDumpUIButton
bool IsBlockedRestoreUIButton
volatile bool IsLongRun
int NumAuxWindows
QRadioButton * RBClocks [3]
QRadioButton * RBZenith [3]
QLineEdit * LEClkPSD
QLineEdit * LEZenPSD
int AmbigJump
SBVLBISesPreProcLI * CurrentSesLI
SBVLBISesInfo * SesInfo
SBVLBISession * Session
My_QListView * ObservLV
SBBrowseStations * brwsSta
SBBrowseSources * brwsSou
SBBrowseBases * brwsBas
SBBrowseHistory * brwsHist
QLabel * lSesName
QLabel * lOfficialName
QLabel * lCorrName
QLabel * lTStart
QLabel * lTFinis
QLabel * lTMean
QLabel * lTofVer
QLabel * lExpDescr
QLineEdit * GrAmbig
QLineEdit * RefFreq
QComboBox * NetID
QComboBox * UFlag
QSpinBox * sbAmbigJump
SBPlotCarrier * PC_Bases
SBPlotCarrier * PC_Stations
SBPlotCarrier * PC_Sources
SBPlot * PlotBases
SBPlot * PlotStations
SBPlot * PlotSources
SBProject * Prj
SBSolution * Solution
bool IsRunning
QAccel * accel
Static Private Attributes
static const char * sUFlags []
Detailed Description
Definition at line 154 of file SbIPreProcessing.H'.
Constructor & Destructor Documentation
SBVLBIPreProcess::SBVLBIPreProcess (QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 429 of file SbIPreProcessing.C'.
References accel, AmbigJump, SBPlotCarrier::AT_MJD, brwsBas, brwsHist, brwsSou, brwsSta, Clear, SBPlotCarrier::columnNames(), CurrentSesLI, DumpUI, Fix, init(), IsBlockedClearButton, IsBlockedDumpUIButton, IsBlockedFixButton, IsBlockedHistoryList, IsBlockedOkButton, IsBlockedRestoreUIButton, IsBlockedRunButton, IsBlockedSessionList, IsBlockedStationList, IsLongRun, IsNeedEstimateCables, IsRunning, NumAuxWindows, ObservLV, Ok, PC_Bases, PC_Sources, PC_Stations, Prj, RestoreUI, Run, SBSetUp::scaleName(), SesInfo, Session, SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), SetUp, and Solution.
SBVLBIPreProcess::~SBVLBIPreProcess () [virtual]
Definition at line 549 of file SbIPreProcessing.C'.
References SBSolution::deleteSolution(), SBVLBISetViewBase::isModified, PC_Bases, PC_Sources, PC_Stations, Prj, SBVLBISet::saveSession(), SesInfo, Session, Solution, and SBVLBISetViewBase::Wvlbi.
Member Function Documentation
void SBVLBIPreProcess::ambigJumpChanged (intJ) [private, slot]
Definition at line 1249 of file SbIPreProcessing.C'.
References AmbigJump.
Referenced by wEstPars().
void SBVLBIPreProcess::auxWindowsChanged (boolIsTmp) [private, slot]
Definition at line 752 of file SbIPreProcessing.C'.
References SBVLBISetViewBase::brwsSes, SBBrowseSessions::lvSessions(), and NumAuxWindows.
Referenced by sesTab().
void SBVLBIPreProcess::blockInput () [private]
Definition at line 672 of file SbIPreProcessing.C'.
References accel, brwsHist, SBVLBISetViewBase::brwsSes, brwsSta, Clear, DumpUI, Fix, IsBlockedClearButton, IsBlockedDumpUIButton, IsBlockedFixButton, IsBlockedHistoryList, IsBlockedOkButton, IsBlockedRestoreUIButton, IsBlockedRunButton, IsBlockedSessionList, IsBlockedStationList, SBBrowseHistory::lvHistory(), SBBrowseSessions::lvSessions(), SBBrowseStations::lvStations(), Ok, RestoreUI, and Run.
Referenced by clearPars(), currentSesChange(), fixSession(), preProcess(), and restoreUI().
virtual QString SBVLBIPreProcess::ClassName () const [inline, virtual]
Reimplemented from SBVLBISetViewBase'.
Definition at line 161 of file SbIPreProcessing.H'.
Referenced by clearPars(), currentSesChange(), fillObsListView(), and preProcess().
void SBVLBIPreProcess::clearPars () [private, slot]
Definition at line 1881 of file SbIPreProcessing.C'.
References SBVLBISession::addHistoryLine(), blockInput(), ClassName(), SBVLBISession::clearRMSs(), SBLog::DBG, SBAttributed::delAttr(), SBSolution::deleteSolution(), SBLog::ERR, SBLog::INTERFACE, IsRunning, SBVLBISet::loadSession(), Log, SBNamed::name(), SBLog::PREPROC, SBVLBISesInfo::preProc, Prj, RBClocks, RBZenith, restoreInput(), saveSession(), SesInfo, Session, Solution, SBVLBISession::stationList(), updateSession(), SBLog::write(), and SBVLBISetViewBase::Wvlbi.
Referenced by init().
virtual void SBVLBISetViewBase::closeEvent (QCloseEvent *e) [inline, protected, virtual, inherited]
Definition at line 456 of file SbIObsVLBI.H'.
References SBVLBISetViewBase::numOpenedWindows.
void SBVLBIPreProcess::currentSesChange (QListViewItem *SesItem_) [private, slot]
Definition at line 1556 of file SbIPreProcessing.C'.
References SBProject::addSession(), SBVLBISession::baseList(), blockInput(), SBPlotCarrier::branches(), ClassName(), SBPlotCarrier::createBranch(), CurrentSesLI, SBSolution::deleteSolution(), SBLog::ERR, IsRunning, SBVLBISet::loadSession(), Log, SBNamed::name(), SBStationInfo::notValid, SBBaseInfo::notValid, SBSourceInfo::notValid, ObservLV, PC_Bases, PC_Sources, PC_Stations, SBLog::PREPROC, Prj, restoreInput(), SesInfo, Session, SBVLBISesInfoLI::sessionInfo(), SBPlotCarrier::setFile4SaveBaseName(), SBNamed::setName(), Solution, SBVLBISession::sourceList(), SBVLBISession::stationList(), updateSession(), SBLog::write(), and SBVLBISetViewBase::Wvlbi.
Referenced by VLBIList().
void SBVLBIPreProcess::doubleProc () [private, slot]
Definition at line 1963 of file SbIPreProcessing.C'.
References preProcess().
Referenced by init(), and procScenario_4().
void SBVLBISetViewBase::drawInfo () [protected, virtual, inherited]
Reimplemented in SBProjectCreate'.
Definition at line 1883 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, SBVLBISetViewBase::LNumObs, SBVLBISetViewBase::LNumPPS, SBVLBISetViewBase::LNumSes, SBBrowseSessions::numPPSess(), SBVLBISetViewBase::str, SBVLBISet::totalObs(), and SBVLBISetViewBase::Wvlbi.
Referenced by SBVLBISetView::deleteEntry(), SBVLBISetView::import(), and SBVLBISetViewBase::infoGroup().
void SBVLBIPreProcess::dumpUI () [private, slot]
Definition at line 1942 of file SbIPreProcessing.C'.
References SBVLBISession::dumpUserInfo(), SBSetUp::path2UIDump(), Session, and SetUp.
Referenced by init().
void SBVLBIPreProcess::fillObsListView () [private]
Definition at line 1304 of file SbIPreProcessing.C'.
References SBObjectObsInfo::aka(), SBVLBISession::baseInfo(), SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, ClassName(), SBPlotCarrier::DA_BAR, SBPlotCarrier::DA_IGN, SBPlotBranch::data(), SBStochParameter::e(), SBLog::ERR, SBStochParameterList::find(), SBPlotCarrier::findBranch(), SBVLBISession::first(), SBPlotBranch::Idx, SBLog::INTERFACE, SBAttributed::isAttr(), Log, SBNamed::name(), SBVLBISession::next(), SBStationInfo::notValid, SBBaseInfo::notValid, SBSourceInfo::notValid, ObservLV, PC_Bases, PC_Sources, PC_Stations, SBSolution::prepare4Batch(), SBObsVLBIEntry::processed, SBSetUp::scale(), Session, SBMatrix::set(), SBPlotBranch::setDataAttr(), SetUp, Solution, SBVLBISession::sourceInfo(), SBVLBISession::stationInfo(), SBSolution::stochastic(), SBStationID::toString(), SBStochParameter::v(), and SBLog::write().
Referenced by updateSession(), and wObservs().
void SBVLBIPreProcess::fillSessAttr () [private]
Definition at line 1254 of file SbIPreProcessing.C'.
References SBVLBISesInfo::code(), SBVLBISesInfo::correlatorName(), SBVLBISesInfo::dateCreat(), SBVLBISesInfo::expDescr(), SBMJD::F_Short, GrAmbig, SBVLBISession::grDelayAmbig(), lCorrName, lExpDescr, lOfficialName, lSesName, lTFinis, lTMean, lTofVer, lTStart, SBNamed::name(), NetID, SBVLBISesInfo::networkID(), SBVLBISet::networks(), SBVLBISesInfo::officialName(), RefFreq, SBVLBISession::refFreq(), Session, sUFlags, SBVLBISesInfo::tFinis(), SBVLBISesInfo::tMean(), SBMJD::toString(), SBVLBISesInfo::tStart(), UFlag, SBVLBISesInfo::userFlag(), and SBVLBISetViewBase::Wvlbi.
Referenced by updateSession().
void SBVLBIPreProcess::fixSession () [private, slot]
Definition at line 1637 of file SbIPreProcessing.C'.
References SBAttributed::addAttr(), SBVLBISession::addHistoryLine(), blockInput(), IsRunning, SBVLBISesInfo::preProc, restoreInput(), saveSession(), SBSetUp::saveVLBI(), Session, SetUp, and SBVLBISetViewBase::Wvlbi.
Referenced by init().
QWidget * SBVLBISetViewBase::infoGroup (QWidget *parent) [protected, virtual, inherited]
Definition at line 1828 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::brwsSes, SBVLBISetViewBase::drawInfo(), SBVLBISetViewBase::LNumObs, SBVLBISetViewBase::LNumPPS, SBVLBISetViewBase::LNumSes, SBBrowseSessions::numObs(), SBBrowseSessions::numPPSess(), SBVLBISetViewBase::str, and SBVLBISetViewBase::Wvlbi.
Referenced by SBProjectCreate::init(), and SBVLBISetView::init().
void SBVLBIPreProcess::init () [private, virtual]
Implements SBVLBISetViewBase'.
Definition at line 589 of file SbIPreProcessing.C'.
References accel, SBVLBISetViewBase::accept(), BM_PREPROCESS, Clear, clearPars(), doubleProc(), dumpUI(), DumpUI, Fix, fixSession(), MainWin, message(), Ok, preProcess(), procScenario_1(), procScenario_2(), procScenario_3(), procScenario_4(), restoreUI(), RestoreUI, run(), Run, sesTab(), stBarReset(), stBarSetProgress(), stBarSetTotalSteps(), stopLongRun(), VLBIList(), and wEstPars().
Referenced by SBVLBIPreProcess().
void SBVLBIPreProcess::message (const QString &t0) [signal]
Definition at line 431 of file SbIPreProcessing.moc.C'.
Referenced by init().
virtual QWidget* SBVLBISetViewBase::optionsGroup (QWidget *) [inline, protected, virtual, inherited]
Reimplemented in SBVLBISetView, and SBProjectCreate'.
Definition at line 453 of file SbIObsVLBI.H'.
void SBVLBIPreProcess::preProcess () [private, slot]
Definition at line 1651 of file SbIPreProcessing.C'.
References SBProject::addSession(), blockInput(), SBParametersDesc::cable(), SBStationInfo::cl_V(), ClassName(), SBParametersDesc::clock0(), Config, SBLog::DBG, SBParameter::e(), SBLog::ERR, SBStationInfoList::find(), SBLog::INTERFACE, IsNeedEstimateCables, IsRunning, LEClkPSD, LEZenPSD, SBVLBISet::loadSession(), SBSolution::local(), Log, SBNamed::name(), SBConfig::p(), SBProject::p(), SBLog::PREPROC, Prj, SBRunManager::process(), SBParameterCfg::PT_LOC, SBParameterCfg::PT_NONE, SBParameterCfg::PT_STH, RBClocks, RBZenith, restoreInput(), run(), saveSession(), SBVLBISet::saveSession(), SesInfo, Session, SBProject::setAllPars2Type(), SBParametersDesc::setCable(), SBParametersDesc::setCableType(), SBProject::setCfg(), SBStationInfo::setCl_E(), SBStationInfo::setCl_V(), SBParametersDesc::setClock0(), SBParametersDesc::setClock0Type(), SBParametersDesc::setClock1Type(), SBParametersDesc::setClock2Type(), SBParameterCfg::setConvAPriori(), SBStationInfo::setErrZw(), SBConfig::setIsChanged(), SBSolution::setIsLocalModified(), SBConfig::setP(), SBProject::setP(), SBParameter::setS(), SBParameter::setV(), SBParameterCfg::setWhiteNoise(), SBParametersDesc::setZenith(), SBParametersDesc::setZenithType(), SBStationInfo::setZw(), Solution, SBVLBISession::stationList(), SBSolution::submitLocalParameters(), updateSession(), SBParameter::v(), SBParameterCfg::whiteNoise(), SBLog::write(), SBVLBISetViewBase::Wvlbi, SBParametersDesc::zenith(), and SBStationInfo::zw().
Referenced by doubleProc(), init(), procScenario_1(), procScenario_2(), and procScenario_3().
void SBVLBIPreProcess::procScenario_1 () [private, slot]
Definition at line 1971 of file SbIPreProcessing.C'.
References preProcess(), RBClocks, and RBZenith.
Referenced by init(), and procScenario_3().
void SBVLBIPreProcess::procScenario_2 () [private, slot]
Definition at line 1986 of file SbIPreProcessing.C'.
References SBParameterList::inSort(), IsNeedEstimateCables, SBSolution::local(), SBNamed::name(), preProcess(), Session, Solution, and SBVLBISession::stationList().
Referenced by init().
void SBVLBIPreProcess::procScenario_3 () [private, slot]
Definition at line 2005 of file SbIPreProcessing.C'.
References preProcess(), and procScenario_1().
Referenced by init().
void SBVLBIPreProcess::procScenario_4 () [private, slot]
Definition at line 2012 of file SbIPreProcessing.C'.
References SBVLBISetViewBase::brwsSes, doubleProc(), IsLongRun, SBBrowseSessions::lvSessions(), and saveSession().
Referenced by init().
void SBVLBIPreProcess::restoreInput () [private]
Definition at line 725 of file SbIPreProcessing.C'.
References accel, brwsHist, SBVLBISetViewBase::brwsSes, brwsSta, Clear, DumpUI, Fix, IsBlockedClearButton, IsBlockedDumpUIButton, IsBlockedFixButton, IsBlockedHistoryList, IsBlockedOkButton, IsBlockedRestoreUIButton, IsBlockedRunButton, IsBlockedSessionList, IsBlockedStationList, SBBrowseHistory::lvHistory(), SBBrowseSessions::lvSessions(), SBBrowseStations::lvStations(), Ok, RestoreUI, and Run.
Referenced by clearPars(), currentSesChange(), fixSession(), preProcess(), and restoreUI().
void SBVLBIPreProcess::restoreUI () [private, slot]
Definition at line 1948 of file SbIPreProcessing.C'.
References blockInput(), IsRunning, SBSetUp::path2UIDump(), restoreInput(), SBVLBISession::restoreUserInfo(), saveSession(), Session, SetUp, and updateSession().
Referenced by init().
void SBVLBIPreProcess::run (boolt0) [signal]
Definition at line 437 of file SbIPreProcessing.moc.C'.
Referenced by init(), and preProcess().
void SBVLBIPreProcess::saveSession () [private]
Definition at line 1924 of file SbIPreProcessing.C'.
References SBVLBISession::checkAttributres(), CurrentSesLI, SBVLBISetViewBase::isModified, NetID, SBVLBISesInfo::networkID(), SBVLBISet::networks(), SBVLBISet::saveSession(), SesInfo, Session, SBVLBISesInfo::setNetworkID(), SBVLBISesInfo::setUserFlag(), UFlag, SBVLBISesInfo::userFlag(), and SBVLBISetViewBase::Wvlbi.
Referenced by clearPars(), fixSession(), preProcess(), procScenario_4(), and restoreUI().
QWidget * SBVLBIPreProcess::sesTab (QWidget *parent_) [private, virtual]
Definition at line 785 of file SbIPreProcessing.C'.
References auxWindowsChanged(), SBVLBISession::baseList(), BM_GENERAL, brwsBas, brwsHist, brwsSou, brwsSta, SBVLBISession::dbhHistory(), SBVLBISession::localHistory(), SBVLBISesInfo::localVersion(), Session, SesTab, SBVLBISession::sourceList(), SBVLBISession::stationList(), SBVLBISesInfo::tStart(), wAttributes(), wDataPlotsByBases(), wDataPlotsBySources(), wDataPlotsByStations(), and wObservs().
Referenced by init().
void SBVLBIPreProcess::stBarReset () [signal]
Definition at line 413 of file SbIPreProcessing.moc.C'.
Referenced by init().
void SBVLBIPreProcess::stBarSetProgress (intt0) [signal]
Definition at line 425 of file SbIPreProcessing.moc.C'.
Referenced by init().
void SBVLBIPreProcess::stBarSetTotalSteps (intt0) [signal]
Definition at line 419 of file SbIPreProcessing.moc.C'.
Referenced by init().
void SBVLBIPreProcess::stopLongRun () [private, slot]
Definition at line 2035 of file SbIPreProcessing.C'.
References IsLongRun.
Referenced by init().
void SBVLBIPreProcess::toggleEntryMarkEnable (intbutton, QListViewItem *Item, const QPoint &, intn) [private, slot]
Definition at line 866 of file SbIPreProcessing.C'.
References SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBVLBISetViewBase::isModified, IsRunning, and SBAttributed::xorAttr().
Referenced by wObservs().
void SBVLBIPreProcess::toggleEntryMoveEnable (QListViewItem *Item, intn, Qt::ButtonStateMouseButtonState) [private, slot]
Definition at line 909 of file SbIPreProcessing.C'.
References AmbigJump, SBObsVLBIEntry::decAmbigFactor(), SBObsVLBIEntry::incAmbigFactor(), SBVLBISetViewBase::isModified, IsRunning, SBObservation::notValid, and SBAttributed::xorAttr().
Referenced by wObservs().
QWidget * SBVLBISetViewBase::unitsGroup (QWidget *parent) [protected, virtual, inherited]
Definition at line 1803 of file SbIObsVLBI.C'.
References SBVLBISetViewBase::RBUnit, SetUp, SBSetUp::units(), and SBVLBISetViewBase::unitsChanged().
Referenced by SBProjectCreate::init(), and SBVLBISetView::init().
void SBVLBIPreProcess::updateSession () [private]
Definition at line 1484 of file SbIPreProcessing.C'.
References SBVLBISession::baseList(), SBPlotCarrier::branches(), brwsBas, brwsHist, brwsSou, brwsSta, SBPlotCarrier::createBranch(), CurrentSesLI, SBPlot::dataChanged(), SBVLBISession::dbhHistory(), fillObsListView(), fillSessAttr(), SBVLBISession::localHistory(), SBVLBISesInfo::localVersion(), SBNamed::name(), SBStationInfo::notValid, SBBaseInfo::notValid, SBSourceInfo::notValid, PC_Bases, PC_Sources, PC_Stations, PlotBases, PlotSources, PlotStations, Session, SBBrowseBases::setBasInfoList(), SBPlotCarrier::setFile4SaveBaseName(), SBBrowseHistory::setHistories(), SBNamed::setName(), SBBrowseSources::setSouInfoList(), SBBrowseStations::setStaInfoList(), SBBrowseStations::setT0(), SBVLBISession::sourceList(), SBVLBISession::stationList(), and SBVLBISesInfo::tStart().
Referenced by clearPars(), currentSesChange(), preProcess(), and restoreUI().
QWidget * SBVLBIPreProcess::VLBIList (QWidget *parent, BrowseModeMode_, SBProject *Prj) [private, virtual]
Reimplemented from SBVLBISetViewBase'.
Definition at line 764 of file SbIPreProcessing.C'.
References SBVLBISetViewBase::brwsSes, currentSesChange(), SBBrowseSessions::layout(), SBBrowseSessions::lvSessions(), and SBVLBISetViewBase::Wvlbi.
Referenced by init().
QWidget * SBVLBIPreProcess::wAttributes () [private]
Definition at line 950 of file SbIPreProcessing.C'.
References SBVLBISesInfo::code(), SBVLBISesInfo::correlatorName(), SBVLBISesInfo::dateCreat(), SBVLBISesInfo::expDescr(), SBMJD::F_Short, GrAmbig, SBVLBISession::grDelayAmbig(), lCorrName, lExpDescr, lOfficialName, lSesName, lTFinis, lTMean, lTofVer, lTStart, SBNamed::name(), NetID, SBVLBISesInfo::networkID(), SBVLBISet::networks(), SBVLBISesInfo::officialName(), RefFreq, SBVLBISession::refFreq(), Session, sUFlags, SBVLBISesInfo::tFinis(), SBVLBISesInfo::tMean(), SBMJD::toString(), SBVLBISesInfo::tStart(), UFlag, SBVLBISesInfo::userFlag(), and SBVLBISetViewBase::Wvlbi.
Referenced by sesTab().
QWidget * SBVLBIPreProcess::wDataPlotsByBases () [private]
Definition at line 1104 of file SbIPreProcessing.C'.
References PC_Bases, and PlotBases.
Referenced by sesTab().
QWidget * SBVLBIPreProcess::wDataPlotsBySources () [private]
Definition at line 1128 of file SbIPreProcessing.C'.
References PC_Sources, and PlotSources.
Referenced by sesTab().
QWidget * SBVLBIPreProcess::wDataPlotsByStations () [private]
Definition at line 1116 of file SbIPreProcessing.C'.
References PC_Stations, and PlotStations.
Referenced by sesTab().
QWidget * SBVLBIPreProcess::wEstPars (QWidget *parent_) [private]
Definition at line 1140 of file SbIPreProcessing.C'.
References ambigJumpChanged(), SBParametersDesc::clock0(), Config, LEClkPSD, LEZenPSD, SBConfig::p(), RBClocks, RBZenith, sbAmbigJump, SBParameterCfg::whiteNoise(), and SBParametersDesc::zenith().
Referenced by init().
QWidget * SBVLBIPreProcess::wObservs () [private]
Definition at line 804 of file SbIPreProcessing.C'.
References fillObsListView(), ObservLV, toggleEntryMarkEnable(), and toggleEntryMoveEnable().
Referenced by sesTab().
Member Data Documentation
QAccel* SBVLBIPreProcess::accel [private]
Definition at line 291 of file SbIPreProcessing.H'.
Referenced by blockInput(), init(), restoreInput(), and SBVLBIPreProcess().
int SBVLBIPreProcess::AmbigJump [private]
Definition at line 246 of file SbIPreProcessing.H'.
Referenced by ambigJumpChanged(), SBVLBIPreProcess(), and toggleEntryMoveEnable().
SBBrowseBases* SBVLBIPreProcess::brwsBas [private]
Definition at line 258 of file SbIPreProcessing.H'.
Referenced by SBVLBIPreProcess(), sesTab(), and updateSession().
SBBrowseHistory* SBVLBIPreProcess::brwsHist [private]
Definition at line 259 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), SBVLBIPreProcess(), sesTab(), and updateSession().
SBBrowseSessions* SBVLBISetViewBase::brwsSes [protected, inherited]
Definition at line 441 of file SbIObsVLBI.H'.
Referenced by auxWindowsChanged(), blockInput(), SBProjectCreate::createProject(), SBVLBISetView::deleteEntry(), SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), SBVLBISetView::import(), SBVLBISetViewBase::infoGroup(), SBProjectCreate::init(), procScenario_4(), restoreInput(), SBProjectCreate::selectAll(), SBProjectCreate::unselectAll(), VLBIList(), and SBVLBISetViewBase::VLBIList().
SBBrowseSources* SBVLBIPreProcess::brwsSou [private]
Definition at line 257 of file SbIPreProcessing.H'.
Referenced by SBVLBIPreProcess(), sesTab(), and updateSession().
SBBrowseStations* SBVLBIPreProcess::brwsSta [private]
Definition at line 256 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), SBVLBIPreProcess(), sesTab(), and updateSession().
QPushButton* SBVLBIPreProcess::Clear [private]
Definition at line 219 of file SbIPreProcessing.H'.
Referenced by blockInput(), init(), restoreInput(), and SBVLBIPreProcess().
SBVLBISesPreProcLI* SBVLBIPreProcess::CurrentSesLI [private]
Definition at line 249 of file SbIPreProcessing.H'.
Referenced by currentSesChange(), saveSession(), SBVLBIPreProcess(), and updateSession().
QPushButton* SBVLBIPreProcess::DumpUI [private]
Definition at line 223 of file SbIPreProcessing.H'.
Referenced by blockInput(), init(), restoreInput(), and SBVLBIPreProcess().
QPushButton* SBVLBIPreProcess::Fix [private]
Definition at line 221 of file SbIPreProcessing.H'.
Referenced by blockInput(), init(), restoreInput(), and SBVLBIPreProcess().
QLineEdit* SBVLBIPreProcess::GrAmbig [private]
Definition at line 271 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
bool SBVLBIPreProcess::IsBlockedClearButton [private]
Definition at line 229 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedDumpUIButton [private]
Definition at line 234 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedFixButton [private]
Definition at line 231 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedHistoryList [private]
Definition at line 227 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedOkButton [private]
Definition at line 232 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedRestoreUIButton [private]
Definition at line 235 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedRunButton [private]
Definition at line 230 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedSessionList [private]
Definition at line 225 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsBlockedStationList [private]
Definition at line 226 of file SbIPreProcessing.H'.
Referenced by blockInput(), restoreInput(), and SBVLBIPreProcess().
volatile bool SBVLBIPreProcess::IsLongRun [private]
Definition at line 236 of file SbIPreProcessing.H'.
Referenced by procScenario_4(), SBVLBIPreProcess(), and stopLongRun().
bool SBVLBISetViewBase::isModified [protected, inherited]
Definition at line 446 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), SBVLBISetView::deleteEntry(), SBVLBISetView::import(), SBVLBISetView::masterRecordModified(), SBVLBISetViewBase::modified(), SBVLBISetView::networksModified(), saveSession(), SBVLBISetViewBase::SBVLBISetViewBase(), toggleEntryMarkEnable(), toggleEntryMoveEnable(), and ~SBVLBIPreProcess().
bool SBVLBIPreProcess::IsNeedEstimateCables [private]
Definition at line 191 of file SbIPreProcessing.H'.
Referenced by preProcess(), procScenario_2(), and SBVLBIPreProcess().
bool SBVLBIPreProcess::IsRunning [private]
Definition at line 288 of file SbIPreProcessing.H'.
Referenced by clearPars(), currentSesChange(), fixSession(), preProcess(), restoreUI(), SBVLBIPreProcess(), toggleEntryMarkEnable(), and toggleEntryMoveEnable().
QLabel* SBVLBIPreProcess::lCorrName [private]
Definition at line 264 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QLineEdit* SBVLBIPreProcess::LEClkPSD [private]
Definition at line 243 of file SbIPreProcessing.H'.
Referenced by preProcess(), and wEstPars().
QLabel* SBVLBIPreProcess::lExpDescr [private]
Definition at line 269 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QLineEdit* SBVLBIPreProcess::LEZenPSD [private]
Definition at line 244 of file SbIPreProcessing.H'.
Referenced by preProcess(), and wEstPars().
QLabel* SBVLBISetViewBase::LNumObs [protected, inherited]
Definition at line 443 of file SbIObsVLBI.H'.
Referenced by SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
QLabel* SBVLBISetViewBase::LNumPPS [protected, inherited]
Definition at line 444 of file SbIObsVLBI.H'.
Referenced by SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
QLabel* SBVLBISetViewBase::LNumSes [protected, inherited]
Definition at line 442 of file SbIObsVLBI.H'.
Referenced by SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
QLabel* SBVLBIPreProcess::lOfficialName [private]
Definition at line 263 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QLabel* SBVLBIPreProcess::lSesName [private]
Definition at line 262 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QLabel* SBVLBIPreProcess::lTFinis [private]
Definition at line 266 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QLabel* SBVLBIPreProcess::lTMean [private]
Definition at line 267 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QLabel* SBVLBIPreProcess::lTofVer [private]
Definition at line 268 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QLabel* SBVLBIPreProcess::lTStart [private]
Definition at line 265 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QComboBox* SBVLBIPreProcess::NetID [private]
Definition at line 273 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), saveSession(), and wAttributes().
int SBVLBIPreProcess::NumAuxWindows [private]
Definition at line 238 of file SbIPreProcessing.H'.
Referenced by auxWindowsChanged(), and SBVLBIPreProcess().
int SBVLBISetViewBase::numOpenedWindows [protected, inherited]
Definition at line 447 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), SBVLBISetView::browseMRecords(), SBVLBISetViewBase::childWindowClosed(), SBVLBISetViewBase::closeEvent(), SBProjectCreate::editEntry(), SBVLBISetView::editEntry(), SBVLBISetView::editNetworks(), SBVLBISetView::import(), SBVLBISetView::masterRecordModified(), SBVLBISetView::networksModified(), SBVLBISetViewBase::reject(), and SBVLBISetViewBase::SBVLBISetViewBase().
My_QListView* SBVLBIPreProcess::ObservLV [private]
Definition at line 254 of file SbIPreProcessing.H'.
Referenced by currentSesChange(), fillObsListView(), SBVLBIPreProcess(), and wObservs().
QPushButton* SBVLBIPreProcess::Ok [private]
Definition at line 222 of file SbIPreProcessing.H'.
Referenced by blockInput(), init(), restoreInput(), and SBVLBIPreProcess().
SBPlotCarrier* SBVLBIPreProcess::PC_Bases [private]
Definition at line 278 of file SbIPreProcessing.H'.
Referenced by currentSesChange(), fillObsListView(), SBVLBIPreProcess(), updateSession(), wDataPlotsByBases(), and ~SBVLBIPreProcess().
SBPlotCarrier* SBVLBIPreProcess::PC_Sources [private]
Definition at line 280 of file SbIPreProcessing.H'.
Referenced by currentSesChange(), fillObsListView(), SBVLBIPreProcess(), updateSession(), wDataPlotsBySources(), and ~SBVLBIPreProcess().
SBPlotCarrier* SBVLBIPreProcess::PC_Stations [private]
Definition at line 279 of file SbIPreProcessing.H'.
Referenced by currentSesChange(), fillObsListView(), SBVLBIPreProcess(), updateSession(), wDataPlotsByStations(), and ~SBVLBIPreProcess().
SBPlot* SBVLBIPreProcess::PlotBases [private]
Definition at line 281 of file SbIPreProcessing.H'.
Referenced by updateSession(), and wDataPlotsByBases().
SBPlot* SBVLBIPreProcess::PlotSources [private]
Definition at line 283 of file SbIPreProcessing.H'.
Referenced by updateSession(), and wDataPlotsBySources().
SBPlot* SBVLBIPreProcess::PlotStations [private]
Definition at line 282 of file SbIPreProcessing.H'.
Referenced by updateSession(), and wDataPlotsByStations().
SBProject* SBVLBIPreProcess::Prj [private]
Definition at line 286 of file SbIPreProcessing.H'.
Referenced by clearPars(), currentSesChange(), preProcess(), SBVLBIPreProcess(), and ~SBVLBIPreProcess().
QRadioButton* SBVLBIPreProcess::RBClocks[3] [private]
Definition at line 241 of file SbIPreProcessing.H'.
Referenced by clearPars(), preProcess(), procScenario_1(), and wEstPars().
QRadioButton* SBVLBISetViewBase::RBUnit[3] [protected, inherited]
Definition at line 445 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::unitsGroup().
QRadioButton* SBVLBIPreProcess::RBZenith[3] [private]
Definition at line 242 of file SbIPreProcessing.H'.
Referenced by clearPars(), preProcess(), procScenario_1(), and wEstPars().
QLineEdit* SBVLBIPreProcess::RefFreq [private]
Definition at line 272 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QPushButton* SBVLBIPreProcess::RestoreUI [private]
Definition at line 224 of file SbIPreProcessing.H'.
Referenced by blockInput(), init(), restoreInput(), and SBVLBIPreProcess().
QPushButton* SBVLBIPreProcess::Run [private]
Definition at line 220 of file SbIPreProcessing.H'.
Referenced by blockInput(), init(), restoreInput(), and SBVLBIPreProcess().
QSpinBox* SBVLBIPreProcess::sbAmbigJump [private]
Definition at line 275 of file SbIPreProcessing.H'.
Referenced by wEstPars().
SBVLBISesInfo* SBVLBIPreProcess::SesInfo [private]
Definition at line 250 of file SbIPreProcessing.H'.
Referenced by clearPars(), currentSesChange(), preProcess(), saveSession(), SBVLBIPreProcess(), and ~SBVLBIPreProcess().
SBVLBISession* SBVLBIPreProcess::Session [private]
Definition at line 251 of file SbIPreProcessing.H'.
Referenced by clearPars(), currentSesChange(), dumpUI(), fillObsListView(), fillSessAttr(), fixSession(), preProcess(), procScenario_2(), restoreUI(), saveSession(), SBVLBIPreProcess(), sesTab(), updateSession(), wAttributes(), and ~SBVLBIPreProcess().
QTabWidget* SBVLBIPreProcess::SesTab [private]
Definition at line 216 of file SbIPreProcessing.H'.
Referenced by sesTab().
SBSolution* SBVLBIPreProcess::Solution [private]
Definition at line 287 of file SbIPreProcessing.H'.
Referenced by clearPars(), currentSesChange(), fillObsListView(), preProcess(), procScenario_2(), SBVLBIPreProcess(), and ~SBVLBIPreProcess().
QString SBVLBISetViewBase::str [protected, inherited]
Definition at line 439 of file SbIObsVLBI.H'.
Referenced by SBVLBISetView::deleteEntry(), SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), and SBVLBISetViewBase::infoGroup().
const char * SBVLBIPreProcess::sUFlags [static, private]"Initial value:
 
{
  'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'
}
Definition at line 193 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), and wAttributes().
QComboBox* SBVLBIPreProcess::UFlag [private]
Definition at line 274 of file SbIPreProcessing.H'.
Referenced by fillSessAttr(), saveSession(), and wAttributes().
SBVLBISet* SBVLBISetViewBase::Wvlbi [protected, inherited]
Definition at line 436 of file SbIObsVLBI.H'.
Referenced by SBVLBISetViewBase::accept(), SBVLBISetView::browseMRecords(), clearPars(), SBProjectCreate::createProject(), currentSesChange(), SBVLBISetView::deleteEntry(), SBProjectCreate::drawInfo(), SBVLBISetViewBase::drawInfo(), SBProjectCreate::editEntry(), SBVLBISetView::editEntry(), SBVLBISetView::editNetworks(), fillSessAttr(), fixSession(), SBVLBISetView::import(), SBVLBISetViewBase::infoGroup(), SBVLBISetView::networksModified(), preProcess(), saveSession(), SBVLBISetViewBase::SBVLBISetViewBase(), VLBIList(), SBVLBISetViewBase::VLBIList(), wAttributes(), ~SBVLBIPreProcess(), and SBVLBISetViewBase::~SBVLBISetViewBase().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.