SBVLBISesPreProcLI
NAME
SBVLBISesPreProcLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits SBVLBISesInfoLI'.
Public Member Functions
SBVLBISesPreProcLI (QListView *parent_, SBVLBISesInfo *SI_, BrowseMode Mode_)
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
SBVLBISesInfo * sessionInfo ()
Protected Attributes
SBVLBISesInfo * SI
BrowseMode Mode
Detailed Description
Definition at line 88 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBISesPreProcLI::SBVLBISesPreProcLI (QListView *parent_, SBVLBISesInfo *SI_, BrowseModeMode_) [inline]
Definition at line 91 of file SbIObsVLBI.H'.
Member Function Documentation
virtual QString SBVLBISesPreProcLI::ClassName () const [inline, virtual]
Reimplemented from SBVLBISesInfoLI'.
Definition at line 93 of file SbIObsVLBI.H'.
QString SBVLBISesPreProcLI::key (intcol, bool) const [virtual]
Reimplemented from SBVLBISesInfoLI'.
Definition at line 295 of file SbIObsVLBI.C'.
References SBVLBISesInfo::ArtAllMeteos, SBVLBISesInfo::ArtMeteo, SBVLBISesInfo::BadAllCables, SBVLBISesInfo::BadAllMeteos, SBVLBISesInfo::BadCable, SBVLBISesInfo::BadMeteo, SBVLBISesInfo::dWRMS(), SBVLBISesInfo::HasClockBreak, SBAttributed::isAttr(), SBVLBISesInfo::numObs(), SBVLBISesInfo::preProc, SBSetUp::scale(), SetUp, SBVLBISesInfoLI::SI, TmpString, and SBVLBISesInfo::tStart().
SBVLBISesInfo* SBVLBISesInfoLI::sessionInfo () [inline, inherited]
Definition at line 73 of file SbIObsVLBI.H'.
References SBVLBISesInfoLI::SI.
Referenced by SBVLBIPreProcess::currentSesChange(), SBVLBISetView::deleteEntry(), SBProjectEdit::delSession(), and SBVLBISessionEditor::SBVLBISessionEditor().
QString SBVLBISesPreProcLI::text (intcol) const [virtual]
Reimplemented from SBVLBISesInfoLI'.
Definition at line 245 of file SbIObsVLBI.C'.
References SBVLBISesInfo::ArtAllMeteos, SBVLBISesInfo::ArtMeteo, SBVLBISesInfo::BadAllCables, SBVLBISesInfo::BadAllMeteos, SBVLBISesInfo::BadCable, SBVLBISesInfo::BadMeteo, SBDelay::CLight, SBVLBISesInfo::dWRMS(), SBVLBISesInfo::HasClockBreak, SBAttributed::isAttr(), SBNamed::name(), SBVLBISesInfo::numObs(), SBVLBISesInfo::preProc, SetUp, SBVLBISesInfoLI::SI, TmpString, SBSetUp::U_INCH, SBSetUp::U_METER, SBSetUp::U_SEC, and SBSetUp::units().
Member Data Documentation
BrowseMode SBVLBISesInfoLI::Mode [protected, inherited]
Definition at line 66 of file SbIObsVLBI.H'.
Referenced by SBVLBISesInfoLI::key(), SBVLBISesInfoLI::SBVLBISesInfoLI(), and SBVLBISesInfoLI::text().
SBVLBISesInfo* SBVLBISesInfoLI::SI [protected, inherited]
Definition at line 65 of file SbIObsVLBI.H'.
Referenced by SBVLBISesInfoLI::key(), key(), SBVLBISesInfoLI::SBVLBISesInfoLI(), SBVLBISesInfoLI::sessionInfo(), SBVLBISesInfoLI::text(), text(), and SBVLBISesInfoLI::~SBVLBISesInfoLI().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.