SBVLBISet
NAME
SBVLBISet -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBVLBISesInfoList'.
Classes
class NetList
class Network
Public Member Functions
SBVLBISet ()
~SBVLBISet ()
virtual QString ClassName () const
unsigned int totalObs () const
NetList * networks ()
SBMaster * master ()
SBVLBISesInfo * import (SBVLBISession::ObsImportedFrom, const QString &, bool, int)
void loadMaster ()
void releaseMaster ()
SBVLBISesInfo * sessionInfo (const QString &Name_) const
SBVLBISession * loadSession (const QString &, SBVLBISession *=NULL) const
SBVLBISession * saveSession (SBVLBISession *) const
void removeSession (const QString &)
void dumpUserInfo ()
void restoreUserInfo ()
Protected Member Functions
void fillDicts ()
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
Protected Attributes
QDict< SBVLBISesInfo > * SessionByName
NetList Networks
SBMaster * Master
unsigned int TotalNumObs
Friends
QDataStream & operator<< (QDataStream &, const SBVLBISet &)
QDataStream & operator>> (QDataStream &, SBVLBISet &)
Detailed Description
List of sessions'.
Definition at line 1242 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBISet::SBVLBISet ()"A constructor'. Creates a copy of object'.
Definition at line 2423 of file SbGeoObsVLBI.C'.
References SBVLBISet::Network::addKey(), Master, Networks, SessionByName, and TotalNumObs.
SBVLBISet::~SBVLBISet ()"A destructor'.
Definition at line 3455 of file SbGeoObsVLBI.C'.
References Master, and SessionByName.
Member Function Documentation
virtual QString SBVLBISet::ClassName () const [inline, virtual]
Definition at line 1304 of file SbGeoObsVLBI.H'.
Referenced by fillDicts(), import(), loadSession(), removeSession(), and saveSession().
virtual int SBVLBISesInfoList::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual, inherited]
Definition at line 931 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::tFinis(), and SBVLBISesInfo::tStart().
void SBVLBISet::dumpUserInfo ()
Definition at line 3839 of file SbGeoObsVLBI.C'.
References SBVLBISession::dumpUserInfo(), loadSession(), mainMessage(), mainPrBarReset(), mainPrBarSetProgress(), mainPrBarSetTotalSteps(), mainSetOperation(), mainSetProcSes(), mainSetSessName(), SBNamed::name(), SBSetUp::path2UIDump(), and SetUp.
Referenced by SBMainWindow::UtilitiesDumpUI().
void SBVLBISet::fillDicts () [protected]"Updates dictionary'.
Definition at line 3472 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, Log, SBNamed::name(), SBVLBISesInfo::numObs(), SessionByName, TotalNumObs, and SBLog::write().
SBVLBISesInfo * SBVLBISet::import (SBVLBISession::ObsImportedFromIType, const QString &FName, boolisNeedDump, intExistedSessMode)"Makes import session from the NGS or MkIII DBH file'.
Parameters:
FName_ file name'.
isNeedDump controls dump;
Definition at line 3514 of file SbGeoObsVLBI.C'.
References SBVLBISession::addHistoryLine(), SBVLBISession::calcTMean(), SBVLBISession::checkArtMeteo(), SBVLBISesInfo::checkPath(), ClassName(), SBFCList::close(), SBMasterRecord::correlatorName(), SBLog::DATA, SBLog::DBG, SBFCList::defaultExt(), SBVLBISesInfo::expDescr(), SBSetUp::fcList(), SBVLBISesInfo::fileName(), SBVLBISesInfo::FT_AUX, SBVLBISesInfo::FT_DAT, SBVLBISesInfo::IF_DBH, SBVLBISesInfo::IF_NGS, SBVLBISesInfo::IF_UNKN, SBVLBISesInfo::IF_VBD, SBLog::IO, Log, SBVLBISet::NetList::lookup(), SBMaster::lookupMR(), Master, SBNamed::name(), SBVLBISesInfo::networkID(), Networks, SBVLBISession::numObs(), SBFCList::open4In(), SBSetUp::path2Compil(), SBSetUp::path2Output(), SessionByName, SBMasterRecord::sessionCode(), SBMasterRecord::sessionName(), SBVLBISesInfo::setCode(), SBVLBISesInfo::setCorrelatorName(), SBVLBISession::setDump(), SBNamed::setName(), SBVLBISesInfo::setNetworkID(), SBVLBISesInfo::setOfficialName(), SetUp, SBVLBISesInfo::setUserFlag(), TotalNumObs, SBVLBISesInfo::version(), SBLog::write(), and SBLog::WRN.
Referenced by SBVLBISetView::import().
void SBVLBISet::loadMaster ()"Load Master File info'.
Definition at line 3493 of file SbGeoObsVLBI.C'.
References Master, SBSetUp::masterFileName(), and SetUp.
Referenced by SBVLBISetView::import(), SBRunManager::makeReportEOP(), SBRunManager::makeReportTroposphere(), and SBMasterRecBrowser::SBMasterRecBrowser().
SBVLBISession * SBVLBISet::loadSession (const QString &Name_, SBVLBISession *W = NULL) const"Loads session'. THESE STUPIDNESS HAVE TO BE OVERWRITEN'.
Parameters:
Name_ session ID'.
W points to session;
Returns:
loaded session'.
Definition at line 3682 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBVLBISesInfo::delayRMS2(), SBVLBISesInfo::DelaySumW2, SBLog::ERR, SBVLBISesInfo::fileName(), SBVLBISesInfo::FT_AUX, SBVLBISesInfo::FT_DAT, Log, SBVLBISesInfo::rateRMS2(), SBVLBISesInfo::RateSumW2, SessionByName, SBVLBISesInfo::setDelayRMS2(), SBVLBISesInfo::setDelaySumW2(), SBNamed::setName(), SBVLBISesInfo::setRateRMS2(), SBVLBISesInfo::setRateSumW2(), and SBLog::write().
Referenced by SBProject::addSession(), SBVLBIPreProcess::clearPars(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBProject::delSession(), dumpUserInfo(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTroposphere(), SBVLBIPreProcess::preProcess(), restoreUserInfo(), SBVLBISessionEditor::SBVLBISessionEditor(), and sinex_SiteEccentricityBlock().
SBMaster* SBVLBISet::master () [inline]
Definition at line 1309 of file SbGeoObsVLBI.H'.
References Master.
Referenced by SBRunManager::makeReportEOP(), SBRunManager::makeReportTroposphere(), and SBMasterRecBrowser::SBMasterRecBrowser().
NetList* SBVLBISet::networks () [inline]
Definition at line 1308 of file SbGeoObsVLBI.H'.
References Networks.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBIPreProcess::fillSessAttr(), SBVLBISetView::networksModified(), SBVLBIPreProcess::saveSession(), SBVLBINetworkEditor::SBVLBINetworkEditor(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
virtual QDataStream& SBVLBISesInfoList::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual, inherited]
Definition at line 940 of file SbGeoObsVLBI.H'.
void SBVLBISet::releaseMaster () [inline]
Definition at line 1314 of file SbGeoObsVLBI.H'.
References Master.
Referenced by SBVLBISetView::import(), SBRunManager::makeReportEOP(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReportTroposphere(), and SBMasterRecBrowser::~SBMasterRecBrowser().
void SBVLBISet::removeSession (const QString &Name_)"Deletes session from the database'.
Parameters:
Name_ session ID'.
It also removes data files ('.dat & '.aux) from the disk'.
Definition at line 3806 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, SBVLBISesInfo::fileName(), SBVLBISesInfo::FT_AUX, SBVLBISesInfo::FT_DAT, SBLog::INF, Log, SBNamed::name(), SessionByName, and SBLog::write().
Referenced by SBVLBISetView::deleteEntry().
void SBVLBISet::restoreUserInfo ()
Definition at line 3868 of file SbGeoObsVLBI.C'.
References loadSession(), mainMessage(), mainPrBarReset(), mainPrBarSetProgress(), mainPrBarSetTotalSteps(), mainSetOperation(), mainSetProcSes(), mainSetSessName(), SBSetUp::path2UIDump(), saveSession(), and SetUp.
Referenced by SBMainWindow::UtilitiesRestoreUI().
SBVLBISession * SBVLBISet::saveSession (SBVLBISession *W) const"Saves session'.
Parameters:
Name_ session ID'.
W session to save;
Returns:
saved session'.
Definition at line 3751 of file SbGeoObsVLBI.C'.
References SBVLBISession::calcTMean(), ClassName(), SBLog::DATA, SBVLBISesInfo::delayRMS2(), SBVLBISesInfo::DelaySumW2, SBLog::ERR, SBVLBISesInfo::fileName(), SBVLBISesInfo::FT_AUX, Log, SBNamed::name(), SBVLBISesInfo::rateRMS2(), SBVLBISesInfo::RateSumW2, SessionByName, SBVLBISesInfo::setDelayRMS2(), SBVLBISesInfo::setDelaySumW2(), SBVLBISesInfo::setRateRMS2(), SBVLBISesInfo::setRateSumW2(), SBVLBISesInfo::setTFinis(), SBVLBISesInfo::setTMean(), SBVLBISesInfo::setTStart(), SBVLBISesInfo::tFinis(), SBVLBISesInfo::tMean(), SBVLBISesInfo::tStart(), and SBLog::write().
Referenced by SBVLBIPreProcess::preProcess(), restoreUserInfo(), SBVLBIPreProcess::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBVLBIPreProcess::~SBVLBIPreProcess(), and SBVLBISessionEditor::~SBVLBISessionEditor().
SBVLBISesInfo* SBVLBISet::sessionInfo (const QString &Name_) const [inline]
Definition at line 1318 of file SbGeoObsVLBI.H'.
References SessionByName.
Referenced by SBMasterRecBrowser::SBMasterRecBrowser().
unsigned int SBVLBISet::totalObs () const [inline]
Definition at line 1307 of file SbGeoObsVLBI.H'.
References TotalNumObs.
Referenced by SBVLBISetViewBase::drawInfo().
virtual QDataStream& SBVLBISesInfoList::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual, inherited]
Definition at line 938 of file SbGeoObsVLBI.H'.
Friends And Related Function Documentation
QDataStream & operator<< (QDataStream &s, const SBVLBISet &S) [friend]"Saves data to the data stream'.
Definition at line 3910 of file SbGeoObsVLBI.C'.
QDataStream & operator>> (QDataStream &s, SBVLBISet &S) [friend]"Loads data from the data stream'.
Definition at line 3919 of file SbGeoObsVLBI.C'.
Member Data Documentation
SBMaster* SBVLBISet::Master [protected]
Definition at line 1296 of file SbGeoObsVLBI.H'.
Referenced by import(), loadMaster(), master(), releaseMaster(), SBVLBISet(), and ~SBVLBISet().
NetList SBVLBISet::Networks [protected]
Definition at line 1295 of file SbGeoObsVLBI.H'.
Referenced by import(), networks(), and SBVLBISet().
QDict<SBVLBISesInfo>* SBVLBISet::SessionByName [protected]
Definition at line 1294 of file SbGeoObsVLBI.H'.
Referenced by fillDicts(), import(), loadSession(), removeSession(), saveSession(), SBVLBISet(), sessionInfo(), and ~SBVLBISet().
unsigned int SBVLBISet::TotalNumObs [protected]
Definition at line 1298 of file SbGeoObsVLBI.H'.
Referenced by fillDicts(), import(), SBVLBISet(), and totalObs().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.