.TH "SBVLBINetworkEditor::NetworkListItem" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBVLBINetworkEditor::NetworkListItem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQListViewItem\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkListItem\fP (\fBQListView\fP *parent, \fBSBVLBISet::Network\fP *N_)"
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.ti -1c
.RI "\fBSBVLBISet::Network\fP * \fBnetwork\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSBVLBISet::Network\fP * \fBNetwork\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 607 of file SbIObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBVLBINetworkEditor::NetworkListItem::NetworkListItem (\fBQListView\fP *parent, \fBSBVLBISet::Network\fP *N_)\fC [inline]\fP"
.PP
Definition at line 612 of file SbIObsVLBI\&.H'\&.
.PP
References Network\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSBVLBISet::Network\fP* SBVLBINetworkEditor::NetworkListItem::network ()\fC [inline]\fP"
.PP
Definition at line 615 of file SbIObsVLBI\&.H'\&.
.PP
References Network\&.
.SS "QString SBVLBINetworkEditor::NetworkListItem::text (intcol) const\fC [virtual]\fP"
.PP
Definition at line 2728 of file SbIObsVLBI\&.C'\&.
.PP
References SBVLBISet::Network::descr(), SBVLBISet::Network::keys(), SBNamed::name(), Network, and TmpString\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBVLBISet::Network\fP* \fBSBVLBINetworkEditor::NetworkListItem::Network\fP\fC [private]\fP"
.PP
Definition at line 610 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by network(), NetworkListItem(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
