SBVLBISessionEditor
NAME
SBVLBISessionEditor -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits SBTabDialog'.
Signals
void sessionModified (bool)
void windowClosed ()
Public Member Functions
SBVLBISessionEditor (SBVLBISesInfoLI *, SBVLBISet *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBVLBISessionEditor ()
virtual QString ClassName () const
Protected Slots
void modified (bool)
void toggleEntryMarkEnable (int, QListViewItem *, const QPoint &, int)
virtual void makeApply ()
virtual void histModified (bool B)
void histVerInced ()
void refClockChange (SBStationInfo *)
virtual void makeDefaults ()
virtual void done (int r)
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Private Member Functions
virtual void acquireData ()
QWidget * wObservs ()
QWidget * wParameters ()
QWidget * wHistory ()
QWidget * wDataPlotsByBases ()
QWidget * wDataPlotsByStations ()
Private Attributes
SBVLBISesInfoLI * SIItem
SBVLBISesInfo * SI
SBVLBISession * Sess
SBVLBISet * Wvlbi
bool isModified
QString Str
QListView * ObservLV
SBBrowseStations * brwsSta
SBBrowseSources * brwsSou
SBBrowseBases * brwsBas
SBBrowseHistory * brwsHist
QLineEdit * GrAmbig
QLineEdit * RefFreq
QComboBox * NetID
QComboBox * UFlag
SBPlotCarrier * PC_Bases
SBPlotCarrier * PC_Stations
double scale
QString ScaleName
Detailed Description
Definition at line 516 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBISessionEditor::SBVLBISessionEditor (SBVLBISesInfoLI *SIItem_, SBVLBISet *Wvlbi_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2185 of file SbIObsVLBI.C'.
References SBPlotCarrier::AT_MJD, SBVLBISession::baseList(), BM_GENERAL, brwsBas, brwsHist, brwsSou, brwsSta, ClassName(), SBDelay::CLight, SBPlotCarrier::columnNames(), SBPlotCarrier::createBranch(), SBVLBISession::dbhHistory(), SBLog::ERR, histModified(), histVerInced(), SBLog::INTERFACE, isModified, SBVLBISet::loadSession(), SBVLBISession::localHistory(), SBVLBISesInfo::localVersion(), Log, makeApply(), modified(), SBNamed::name(), SBStationInfo::notValid, SBBaseInfo::notValid, ObservLV, PC_Bases, PC_Stations, refClockChange(), scale, ScaleName, Sess, SBVLBISesInfoLI::sessionInfo(), SBPlotCarrier::setFile4SaveBaseName(), SBPlotCarrier::setStdVarIdx(), SBPlotCarrier::setType(), SetUp, SI, SIItem, SBVLBISession::sourceList(), SBVLBISession::stationList(), Str, toggleEntryMarkEnable(), SBVLBISesInfo::tStart(), SBSetUp::U_INCH, SBSetUp::U_METER, SBSetUp::U_SEC, SBSetUp::units(), SBVLBISesInfo::version(), wDataPlotsByBases(), wDataPlotsByStations(), wObservs(), wParameters(), SBLog::write(), and Wvlbi.
SBVLBISessionEditor::~SBVLBISessionEditor ()
Definition at line 2296 of file SbIObsVLBI.C'.
References SBAttributed::attributes(), SBVLBISession::checkAttributres(), isModified, PC_Bases, PC_Stations, SBVLBISet::saveSession(), Sess, sessionModified(), SBAttributed::setAttributes(), SI, SIItem, windowClosed(), and Wvlbi.
Member Function Documentation
void SBVLBISessionEditor::acquireData () [private, virtual]
Reimplemented from SBTabDialog'.
Definition at line 2659 of file SbIObsVLBI.C'.
References isModified, NetID, SBVLBISesInfo::networkID(), SBVLBISet::networks(), Sess, SBVLBISesInfo::setNetworkID(), SBVLBISesInfo::setUserFlag(), Str, UFlag, SBVLBISesInfo::userFlag(), and Wvlbi.
Referenced by makeApply().
virtual QString SBVLBISessionEditor::ClassName () const [inline, virtual]
Definition at line 523 of file SbIObsVLBI.H'.
Referenced by makeApply(), SBVLBISessionEditor(), and wObservs().
virtual void SBTabDialog::closeEvent (QCloseEvent *) [inline, protected, virtual, inherited]
Reimplemented in SBSiteEditor, and SBParametersEditor'.
Definition at line 90 of file SbInterface.H'.
virtual void SBTabDialog::done (intr) [inline, protected, virtual, slot, inherited]
Reimplemented in SBSiteEditor, and SBProjectEdit'.
Definition at line 82 of file SbInterface.H'.
References SBTabDialog::acquireData().
virtual void SBVLBISessionEditor::histModified (boolB) [inline, protected, virtual, slot]
Definition at line 534 of file SbIObsVLBI.H'.
References isModified.
Referenced by SBVLBISessionEditor().
void SBVLBISessionEditor::histVerInced () [inline, protected, slot]
Definition at line 535 of file SbIObsVLBI.H'.
References SBVLBISesInfo::incVersion(), isModified, and Sess.
Referenced by SBVLBISessionEditor().
void SBVLBISessionEditor::makeApply () [protected, virtual, slot]
Reimplemented from SBTabDialog'.
Definition at line 2324 of file SbIObsVLBI.C'.
References acquireData(), ClassName(), SBLog::DBG, SBLog::INTERFACE, Log, and SBLog::write().
Referenced by SBVLBISessionEditor().
virtual void SBTabDialog::makeDefaults () [inline, protected, virtual, slot, inherited]
Reimplemented in SBSetupDialog'.
Definition at line 79 of file SbInterface.H'.
void SBVLBISessionEditor::modified (boolisModified_) [protected, slot]
Definition at line 2710 of file SbIObsVLBI.C'.
References isModified.
Referenced by SBVLBISessionEditor().
void SBVLBISessionEditor::refClockChange (SBStationInfo *) [protected, slot]
Definition at line 2715 of file SbIObsVLBI.C'.
Referenced by SBVLBISessionEditor().
void SBVLBISessionEditor::sessionModified (boolt0) [signal]
Definition at line 803 of file SbIObsVLBI.moc.C'.
Referenced by ~SBVLBISessionEditor().
void SBVLBISessionEditor::toggleEntryMarkEnable (intbutton, QListViewItem *Item, const QPoint &, intn) [protected, slot]
Definition at line 2673 of file SbIObsVLBI.C'.
References SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBObsVLBIEntry::decAmbigFactor(), SBObsVLBIEntry::incAmbigFactor(), isModified, and SBObservation::notValid.
Referenced by SBVLBISessionEditor().
QWidget * SBVLBISessionEditor::wDataPlotsByBases () [private]
Definition at line 2635 of file SbIObsVLBI.C'.
References PC_Bases.
Referenced by SBVLBISessionEditor().
QWidget * SBVLBISessionEditor::wDataPlotsByStations () [private]
Definition at line 2647 of file SbIObsVLBI.C'.
References PC_Stations.
Referenced by SBVLBISessionEditor().
QWidget* SBVLBISessionEditor::wHistory () [private]
void SBVLBISessionEditor::windowClosed () [signal]
Definition at line 809 of file SbIObsVLBI.moc.C'.
Referenced by ~SBVLBISessionEditor().
QWidget * SBVLBISessionEditor::wObservs () [private]
Definition at line 2331 of file SbIObsVLBI.C'.
References SBObjectObsInfo::aka(), SBVLBISession::baseInfo(), SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, ClassName(), SBPlotCarrier::DA_BAR, SBPlotCarrier::DA_IGN, SBPlotBranch::data(), SBLog::ERR, SBPlotCarrier::findBranch(), SBVLBISession::first(), SBPlotBranch::Idx, SBLog::INTERFACE, SBAttributed::isAttr(), Log, SBNamed::name(), SBVLBISession::next(), SBStationInfo::notValid, SBBaseInfo::notValid, ObservLV, PC_Bases, PC_Stations, SBObsVLBIEntry::processed, scale, Sess, SBMatrix::set(), SBPlotBranch::setDataAttr(), SBVLBISession::stationInfo(), and SBLog::write().
Referenced by SBVLBISessionEditor().
QWidget * SBVLBISessionEditor::wParameters () [private]
Definition at line 2477 of file SbIObsVLBI.C'.
References SBVLBISesInfo::code(), SBVLBISesInfo::correlatorName(), SBVLBISesInfo::dateCreat(), SBVLBISesInfo::expDescr(), SBMJD::F_Short, GrAmbig, SBVLBISession::grDelayAmbig(), SBNamed::name(), NetID, SBVLBISesInfo::networkID(), SBVLBISet::networks(), SBVLBISesInfo::officialName(), RefFreq, SBVLBISession::refFreq(), Sess, Str, SBVLBISesInfo::tFinis(), SBVLBISesInfo::tMean(), SBMJD::toString(), SBVLBISesInfo::tStart(), UFlag, SBVLBISesInfo::userFlag(), and Wvlbi.
Referenced by SBVLBISessionEditor().
Member Data Documentation
SBBrowseBases* SBVLBISessionEditor::brwsBas [private]
Definition at line 562 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor().
SBBrowseHistory* SBVLBISessionEditor::brwsHist [private]
Definition at line 563 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor().
SBBrowseSources* SBVLBISessionEditor::brwsSou [private]
Definition at line 561 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor().
SBBrowseStations* SBVLBISessionEditor::brwsSta [private]
Definition at line 560 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor().
QLineEdit* SBVLBISessionEditor::GrAmbig [private]
Definition at line 566 of file SbIObsVLBI.H'.
Referenced by wParameters().
bool SBVLBISessionEditor::isModified [private]
Definition at line 544 of file SbIObsVLBI.H'.
Referenced by acquireData(), histModified(), histVerInced(), modified(), SBVLBISessionEditor(), toggleEntryMarkEnable(), and ~SBVLBISessionEditor().
QComboBox* SBVLBISessionEditor::NetID [private]
Definition at line 568 of file SbIObsVLBI.H'.
Referenced by acquireData(), and wParameters().
QListView* SBVLBISessionEditor::ObservLV [private]
Definition at line 557 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor(), and wObservs().
SBPlotCarrier* SBVLBISessionEditor::PC_Bases [private]
Definition at line 572 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor(), wDataPlotsByBases(), wObservs(), and ~SBVLBISessionEditor().
SBPlotCarrier* SBVLBISessionEditor::PC_Stations [private]
Definition at line 573 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor(), wDataPlotsByStations(), wObservs(), and ~SBVLBISessionEditor().
QLineEdit* SBVLBISessionEditor::RefFreq [private]
Definition at line 567 of file SbIObsVLBI.H'.
Referenced by wParameters().
double SBVLBISessionEditor::scale [private]
Definition at line 574 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor(), and wObservs().
QString SBVLBISessionEditor::ScaleName [private]
Definition at line 575 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor().
SBVLBISession* SBVLBISessionEditor::Sess [private]
Definition at line 541 of file SbIObsVLBI.H'.
Referenced by acquireData(), histVerInced(), SBVLBISessionEditor(), wObservs(), wParameters(), and ~SBVLBISessionEditor().
SBVLBISesInfo* SBVLBISessionEditor::SI [private]
Definition at line 540 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor(), and ~SBVLBISessionEditor().
SBVLBISesInfoLI* SBVLBISessionEditor::SIItem [private]
Definition at line 539 of file SbIObsVLBI.H'.
Referenced by SBVLBISessionEditor(), and ~SBVLBISessionEditor().
QString SBVLBISessionEditor::Str [private]
Definition at line 545 of file SbIObsVLBI.H'.
Referenced by acquireData(), SBVLBISessionEditor(), and wParameters().
QComboBox* SBVLBISessionEditor::UFlag [private]
Definition at line 569 of file SbIObsVLBI.H'.
Referenced by acquireData(), and wParameters().
SBVLBISet* SBVLBISessionEditor::Wvlbi [private]
Definition at line 542 of file SbIObsVLBI.H'.
Referenced by acquireData(), SBVLBISessionEditor(), wParameters(), and ~SBVLBISessionEditor().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.