SBVLBINetEntryEditor
NAME
SBVLBINetEntryEditor -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QDialog'.
Signals
void networkModified (bool, SBVLBISet::Network *)
Public Member Functions
SBVLBINetEntryEditor (SBVLBISet::Network *, QListViewItem *, QWidget *=0, const char *=0, bool=FALSE, WFlags=0)
~SBVLBINetEntryEditor ()
virtual QString ClassName () const
Protected Slots
void accept ()
void reject ()
void delKey ()
void addKey ()
void modKey ()
void showKey (int)
Protected Member Functions
virtual void closeEvent (QCloseEvent)
Private Attributes
SBVLBISet::Network * Network
QListViewItem * LI
bool isModified
QString Str
QLineEdit * ID
QMultiLineEdit * Descr
QLineEdit * Key
QListBox * KeyList
Detailed Description
Definition at line 637 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBINetEntryEditor::SBVLBINetEntryEditor (SBVLBISet::Network *N_, QListViewItem *LI_, QWidget *parent = 0, const char *name = 0, boolmodal = FALSE, WFlagsf = 0)
Definition at line 2928 of file SbIObsVLBI.C'.
References accept(), addKey(), delKey(), Descr, SBVLBISet::Network::descr(), ID, isModified, Key, KeyList, SBVLBISet::Network::keys(), LI, modKey(), SBNamed::name(), Network, reject(), and showKey().
SBVLBINetEntryEditor::~SBVLBINetEntryEditor ()
Definition at line 3032 of file SbIObsVLBI.C'.
References isModified, Network, and networkModified().
Member Function Documentation
void SBVLBINetEntryEditor::accept () [protected, slot]
Definition at line 3078 of file SbIObsVLBI.C'.
References Descr, SBVLBISet::Network::descr(), ID, isModified, LI, SBNamed::name(), Network, SBVLBISet::Network::setDescr(), SBNamed::setName(), and Str.
Referenced by SBVLBINetEntryEditor().
void SBVLBINetEntryEditor::addKey () [protected, slot]
Definition at line 3054 of file SbIObsVLBI.C'.
References SBVLBISet::Network::addKey(), isModified, Key, KeyList, SBVLBISet::Network::keys(), Network, and Str.
Referenced by SBVLBINetEntryEditor().
virtual QString SBVLBINetEntryEditor::ClassName () const [inline, virtual]
Definition at line 644 of file SbIObsVLBI.H'.
virtual void SBVLBINetEntryEditor::closeEvent (QCloseEvent) [inline, protected, virtual]
Definition at line 668 of file SbIObsVLBI.H'.
void SBVLBINetEntryEditor::delKey () [protected, slot]
Definition at line 3042 of file SbIObsVLBI.C'.
References isModified, KeyList, SBVLBISet::Network::keys(), Network, and Str.
Referenced by SBVLBINetEntryEditor().
void SBVLBINetEntryEditor::modKey () [protected, slot]
Definition at line 3065 of file SbIObsVLBI.C'.
References SBVLBISet::Network::addKey(), isModified, Key, KeyList, SBVLBISet::Network::keys(), Network, and Str.
Referenced by SBVLBINetEntryEditor().
void SBVLBINetEntryEditor::networkModified (boolt0, SBVLBISet::Network *t1) [signal]
Definition at line 1072 of file SbIObsVLBI.moc.C'.
Referenced by ~SBVLBINetEntryEditor().
void SBVLBINetEntryEditor::reject () [inline, protected, slot]
Definition at line 652 of file SbIObsVLBI.H'.
Referenced by SBVLBINetEntryEditor().
void SBVLBINetEntryEditor::showKey (intidx) [protected, slot]
Definition at line 3037 of file SbIObsVLBI.C'.
References Key, and KeyList.
Referenced by SBVLBINetEntryEditor().
Member Data Documentation
QMultiLineEdit* SBVLBINetEntryEditor::Descr [private]
Definition at line 664 of file SbIObsVLBI.H'.
Referenced by accept(), and SBVLBINetEntryEditor().
QLineEdit* SBVLBINetEntryEditor::ID [private]
Definition at line 663 of file SbIObsVLBI.H'.
Referenced by accept(), and SBVLBINetEntryEditor().
bool SBVLBINetEntryEditor::isModified [private]
Definition at line 661 of file SbIObsVLBI.H'.
Referenced by accept(), addKey(), delKey(), modKey(), SBVLBINetEntryEditor(), and ~SBVLBINetEntryEditor().
QLineEdit* SBVLBINetEntryEditor::Key [private]
Definition at line 665 of file SbIObsVLBI.H'.
Referenced by addKey(), modKey(), SBVLBINetEntryEditor(), and showKey().
QListBox* SBVLBINetEntryEditor::KeyList [private]
Definition at line 666 of file SbIObsVLBI.H'.
Referenced by addKey(), delKey(), modKey(), SBVLBINetEntryEditor(), and showKey().
QListViewItem* SBVLBINetEntryEditor::LI [private]
Definition at line 660 of file SbIObsVLBI.H'.
Referenced by accept(), and SBVLBINetEntryEditor().
SBVLBISet::Network* SBVLBINetEntryEditor::Network [private]
Definition at line 659 of file SbIObsVLBI.H'.
Referenced by accept(), addKey(), delKey(), modKey(), SBVLBINetEntryEditor(), and ~SBVLBINetEntryEditor().
QString SBVLBINetEntryEditor::Str [private]
Definition at line 662 of file SbIObsVLBI.H'.
Referenced by accept(), addKey(), delKey(), and modKey().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.