SBVLBISesInfo
NAME
SBVLBISesInfo -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBNamed, and SBAttributed'.
Inherited by SBVLBISession'.
Public Types
enum Attributes { preProc = 1<<0, notValid = 1<<1, BadCable = 1<<2, BadAllCables = 1<<3, BadMeteo = 1<<4, BadAllMeteos = 1<<5, HasClockBreak = 1<<6, ConstrEOP = 1<<7, ArtMeteo = 1<<8, ArtAllMeteos = 1<<9 }
enum ObsImportedFrom { IF_NGS = 0, IF_VBD = 1, IF_DBH = 2, IF_UNKN = 3 }
enum ObsDelayType { DT_GR = 0, DT_PH = 1, DT_UNKN = 2 }
Public Member Functions
SBVLBISesInfo (const QString &='70JAN01ZZ')
SBVLBISesInfo (const SBVLBISesInfo &)
SBVLBISesInfo & operator= (const SBVLBISesInfo &)
virtual QString ClassName () const
ObsImportedFrom importedFrom () const
const SBMJD & dateCreat () const
const SBMJD & tStart () const
const SBMJD & tFinis () const
const SBMJD & tMean () const
double tInterval () const
int version () const
int localVersion () const
const QString & subKey () const
const QString & networkID () const
const QString & expDescr () const
const QString & userFlag () const
const QString & officialName () const
const QString & code () const
const QString & correlatorName () const
ObsDelayType delayType () const
virtual int numSta () const
virtual int numBas () const
virtual int numSou () const
virtual int numObs () const
double delayRMS2 () const
double rateRMS2 () const
double delaySumW2 () const
double rateSumW2 () const
void setImportedFrom (ObsImportedFrom ImportedFrom_)
void setTStart (SBMJD TStart_)
void setTFinis (SBMJD TFinis_)
void setTMean (SBMJD TMean_)
void setDateCreat (SBMJD DateCreat_)
void setVersion (int V_)
void setSubKey (QString SubKey_)
void setNetworkID (QString NetworkID_)
void setExpDescr (QString ExpDescr_)
void setUserFlag (QString UserFlag_)
void setOfficialName (QString OfficialName_)
void setCode (QString Code_)
void setCorrelatorName (QString CName_)
void setDelayType (ObsDelayType DelayType_)
void setDelayRMS2 (double DelayRMS_)
void setRateRMS2 (double RateRMS_)
void setDelaySumW2 (double d_)
void setRateSumW2 (double d_)
void addDelayRMS (double o_c_, double w_)
void addRateRMS (double o_c_, double w_)
virtual void clearRMSs ()
virtual bool operator== (const SBVLBISesInfo &I) const
virtual void incVersion ()
double dWRMS () const
double rWRMS () const
const QString & name () const
void setName (const QString &Name_)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Types
enum File_Type { FT_DAT = 0, FT_AUX = 1, FT_UNKN = 2 }
Protected Member Functions
QString fileName (File_Type=FT_DAT)
void checkPath ()
virtual void calcTMean ()
Protected Attributes
ObsImportedFrom ImportedFrom
origin of the session;
SBMJD DateCreat
date of MkIII creation (just for curiosity);
SBMJD TStart
first epoch of the observations;
SBMJD TFinis
last epoch of the observations;
SBMJD TMean
mean epoch of the observations;
QString SubKey
aux key;
QString NetworkID
Network ID (a key);'.
QString ExpDescr
Experiment description;'.
QString UserFlag
Flag assigned by user'.
QString OfficialName
Official Name (from MasterFile)
QString Code
Code (from MasterFile)
QString CorrelatorName
Correlator Name (from MasterFile)
ObsDelayType DelayType
type of delay;
int NumSta
int NumBas
int NumSou
int NumObs
double DelayRMS2
double RateRMS2
double DelaySumW2
double RateSumW2
int Version
version;
int LocalVersion
QString Name
Friends
class SBVLBISet
QDataStream & operator<< (QDataStream &, const SBVLBISesInfo &)
QDataStream & operator>> (QDataStream &, SBVLBISesInfo &)
SBDS_dat & operator<< (SBDS_dat &, const SBVLBISesInfo &)
SBDS_dat & operator>> (SBDS_dat &, SBVLBISesInfo &)
SBDS_aux & operator<< (SBDS_aux &, const SBVLBISesInfo &)
SBDS_aux & operator>> (SBDS_aux &, SBVLBISesInfo &)
bool operator== (const SBNamed &, const SBNamed &)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator>> (QDataStream &, SBNamed &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
Detailed Description
Definition at line 793 of file SbGeoObsVLBI.H'.
Member Enumeration Documentation
enum SBVLBISesInfo::Attributes
Enumerator:
preProc
session is preprocessed
notValid
omit this session from the project
BadCable
has at least one station without cable correction
BadAllCables
has all stations without cable correction
BadMeteo
has at least one station without meteo data
BadAllMeteos
has all stations without meteo data
HasClockBreak
there is/are `clock break(s)'
ConstrEOP
ArtMeteo
has at least one station with artificial meteo data
ArtAllMeteos
has all stations with artificial meteo data
Definition at line 797 of file SbGeoObsVLBI.H'.
enum SBVLBISesInfo::File_Type [protected]
Enumerator:
FT_DAT
FT_AUX
FT_UNKN
Definition at line 814 of file SbGeoObsVLBI.H'.
enum SBVLBISesInfo::ObsDelayType
Enumerator:
DT_GR
DT_PH
DT_UNKN
Definition at line 811 of file SbGeoObsVLBI.H'.
enum SBVLBISesInfo::ObsImportedFrom
Enumerator:
IF_NGS
IF_VBD
IF_DBH
IF_UNKN
Definition at line 810 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBISesInfo::SBVLBISesInfo (const QString &Name_ = '70JAN01ZZ')
Definition at line 1071 of file SbGeoObsVLBI.C'.
References Code, CorrelatorName, DateCreat, DelayRMS2, DelaySumW2, DelayType, DT_UNKN, ExpDescr, IF_UNKN, ImportedFrom, LocalVersion, NetworkID, NumBas, NumObs, NumSou, NumSta, OfficialName, RateRMS2, RateSumW2, SubKey, TFinis, TMean, TStart, TZero, UserFlag, and Version.
SBVLBISesInfo::SBVLBISesInfo (const SBVLBISesInfo &Si)
Definition at line 1098 of file SbGeoObsVLBI.C'.
References Code, code(), CorrelatorName, correlatorName(), DateCreat, dateCreat(), DelayRMS2, delayRMS2(), DelaySumW2, DelayType, delayType(), ExpDescr, expDescr(), ImportedFrom, importedFrom(), LocalVersion, localVersion(), NetworkID, networkID(), NumBas, numBas(), NumObs, numObs(), NumSou, numSou(), NumSta, numSta(), OfficialName, officialName(), RateRMS2, rateRMS2(), RateSumW2, SubKey, subKey(), TFinis, tFinis(), TMean, TStart, tStart(), UserFlag, userFlag(), Version, and version().
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
void SBVLBISesInfo::addDelayRMS (doubleo_c_, doublew_) [inline]
Definition at line 896 of file SbGeoObsVLBI.H'.
References DelayRMS2, and DelaySumW2.
Referenced by SBObsVLBIEntry::process().
void SBVLBISesInfo::addRateRMS (doubleo_c_, doublew_) [inline]
Definition at line 897 of file SbGeoObsVLBI.H'.
References RateRMS2, and RateSumW2.
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
virtual void SBVLBISesInfo::calcTMean () [inline, protected, virtual]
Reimplemented in SBVLBISession'.
Definition at line 842 of file SbGeoObsVLBI.H'.
References TFinis, TMean, and TStart.
void SBVLBISesInfo::checkPath () [protected]
Definition at line 1163 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBLog::ERR, Log, SBSetUp::path2Data(), SetUp, SubKey, TStart, SBLog::write(), and SBMJD::year().
Referenced by SBVLBISet::import().
virtual QString SBVLBISesInfo::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBAttributed'.
Reimplemented in SBVLBISession'.
Definition at line 850 of file SbGeoObsVLBI.H'.
Referenced by checkPath().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
virtual void SBVLBISesInfo::clearRMSs () [inline, virtual]
Reimplemented in SBVLBISession'.
Definition at line 899 of file SbGeoObsVLBI.H'.
References DelayRMS2, DelaySumW2, RateRMS2, and RateSumW2.
Referenced by SBProject::addSession().
const QString& SBVLBISesInfo::code () const [inline]
Definition at line 866 of file SbGeoObsVLBI.H'.
References Code.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBRunManager::makeReportSessionStatistics(), operator=(), SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
const QString& SBVLBISesInfo::correlatorName () const [inline]
Definition at line 867 of file SbGeoObsVLBI.H'.
References CorrelatorName.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBVLBISesInfoLI::key(), operator=(), SBVLBISesInfo(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
const SBMJD& SBVLBISesInfo::dateCreat () const [inline]
Definition at line 854 of file SbGeoObsVLBI.H'.
References DateCreat.
Referenced by SBVLBIPreProcess::fillSessAttr(), operator=(), SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), SBVLBISession::checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
double SBVLBISesInfo::delayRMS2 () const [inline]
Definition at line 873 of file SbGeoObsVLBI.H'.
References DelayRMS2.
Referenced by SBVLBISet::loadSession(), operator=(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), and SBVLBISesInfo().
double SBVLBISesInfo::delaySumW2 () const [inline]
Definition at line 875 of file SbGeoObsVLBI.H'.
References DelaySumW2.
Referenced by SBRunManager::saveVLBISessions_m1().
ObsDelayType SBVLBISesInfo::delayType () const [inline]
Definition at line 868 of file SbGeoObsVLBI.H'.
References DelayType.
Referenced by operator=(), and SBVLBISesInfo().
double SBVLBISesInfo::dWRMS () const [inline]
Definition at line 907 of file SbGeoObsVLBI.H'.
References DelayRMS2, and DelaySumW2.
Referenced by SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBISesInfoLI::text(), and SBVLBISesPreProcLI::text().
const QString& SBVLBISesInfo::expDescr () const [inline]
Definition at line 863 of file SbGeoObsVLBI.H'.
References ExpDescr.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBVLBISet::import(), operator=(), SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
QString SBVLBISesInfo::fileName (File_TypeFType = FT_DAT) [protected]
Definition at line 1155 of file SbGeoObsVLBI.C'.
References FT_DAT, SBNamed::Name, SBSetUp::path2Data(), SetUp, SubKey, TStart, Version, and SBMJD::year().
Referenced by SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISet::removeSession(), and SBVLBISet::saveSession().
ObsImportedFrom SBVLBISesInfo::importedFrom () const [inline]
Definition at line 853 of file SbGeoObsVLBI.H'.
References ImportedFrom.
Referenced by SBVLBISesInfoLI::key(), operator=(), SBVLBISesInfo(), and SBVLBISesInfoLI::text().
virtual void SBVLBISesInfo::incVersion () [inline, virtual]
Definition at line 905 of file SbGeoObsVLBI.H'.
References LocalVersion.
Referenced by SBVLBISessionEditor::histVerInced().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), SBVLBISession::checkArtMeteo(), SBVLBISession::checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
int SBVLBISesInfo::localVersion () const [inline]
Definition at line 860 of file SbGeoObsVLBI.H'.
References LocalVersion.
Referenced by SBVLBISession::addHistoryLine(), operator=(), SBVLBISesInfo(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), SBVLBISesInfoLI::text(), and SBVLBIPreProcess::updateSession().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), SBVLBISession::dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), SBVLBISession::restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBVLBISesPreProcLI::text(), SBObsVLBIStatRecordLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
const QString& SBVLBISesInfo::networkID () const [inline]
Definition at line 862 of file SbGeoObsVLBI.H'.
References NetworkID.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBIPreProcess::fillSessAttr(), SBVLBISet::import(), SBVLBISesInfoLI::key(), operator=(), SBVLBIPreProcess::saveSession(), SBVLBISesInfo(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
virtual int SBVLBISesInfo::numBas () const [inline, virtual]
Reimplemented in SBVLBISession'.
Definition at line 870 of file SbGeoObsVLBI.H'.
References NumBas.
Referenced by SBVLBISesInfoLI::key(), operator=(), SBVLBISesInfo(), and SBVLBISesInfoLI::text().
virtual int SBVLBISesInfo::numObs () const [inline, virtual]
Reimplemented in SBVLBISession'.
Definition at line 872 of file SbGeoObsVLBI.H'.
References NumObs.
Referenced by SBVLBISet::fillDicts(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), operator=(), SBVLBISesInfo(), SBProjectCreate::selChanged(), SBVLBISesInfoLI::text(), and SBVLBISesPreProcLI::text().
virtual int SBVLBISesInfo::numSou () const [inline, virtual]
Reimplemented in SBVLBISession'.
Definition at line 871 of file SbGeoObsVLBI.H'.
References NumSou.
Referenced by SBVLBISesInfoLI::key(), operator=(), SBVLBISesInfo(), and SBVLBISesInfoLI::text().
virtual int SBVLBISesInfo::numSta () const [inline, virtual]
Reimplemented in SBVLBISession'.
Definition at line 869 of file SbGeoObsVLBI.H'.
References NumSta.
Referenced by SBVLBISesInfoLI::key(), operator=(), SBVLBISesInfo(), and SBVLBISesInfoLI::text().
const QString& SBVLBISesInfo::officialName () const [inline]
Definition at line 865 of file SbGeoObsVLBI.H'.
References OfficialName.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBRunManager::makeReportSessionStatistics(), operator<<(), operator=(), SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
SBVLBISesInfo & SBVLBISesInfo::operator= (const SBVLBISesInfo &Si)
Definition at line 1125 of file SbGeoObsVLBI.C'.
References Code, code(), CorrelatorName, correlatorName(), DateCreat, dateCreat(), DelayRMS2, delayRMS2(), DelaySumW2, DelayType, delayType(), ExpDescr, expDescr(), ImportedFrom, importedFrom(), LocalVersion, localVersion(), SBNamed::name(), NetworkID, networkID(), NumBas, numBas(), NumObs, numObs(), NumSou, numSou(), NumSta, numSta(), OfficialName, officialName(), RateRMS2, rateRMS2(), RateSumW2, SBNamed::setName(), SubKey, subKey(), TFinis, tFinis(), TMean, tMean(), TStart, tStart(), UserFlag, userFlag(), Version, and version().
virtual bool SBVLBISesInfo::operator== (const SBVLBISesInfo &I) const [inline, virtual]
Definition at line 901 of file SbGeoObsVLBI.H'.
References SBNamed::name().
double SBVLBISesInfo::rateRMS2 () const [inline]
Definition at line 874 of file SbGeoObsVLBI.H'.
References RateRMS2.
Referenced by SBVLBISet::loadSession(), operator=(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), and SBVLBISesInfo().
double SBVLBISesInfo::rateSumW2 () const [inline]
Definition at line 876 of file SbGeoObsVLBI.H'.
References RateSumW2.
Referenced by SBRunManager::saveVLBISessions_m1().
double SBVLBISesInfo::rWRMS () const [inline]
Definition at line 908 of file SbGeoObsVLBI.H'.
References RateRMS2, and RateSumW2.
Referenced by SBVLBISesInfoLI::key(), and SBVLBISesInfoLI::text().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBVLBISesInfo::setCode (QStringCode_) [inline]
Definition at line 889 of file SbGeoObsVLBI.H'.
References Code.
Referenced by SBVLBISet::import().
void SBVLBISesInfo::setCorrelatorName (QStringCName_) [inline]
Definition at line 890 of file SbGeoObsVLBI.H'.
References CorrelatorName.
Referenced by SBVLBISet::import().
void SBVLBISesInfo::setDateCreat (SBMJDDateCreat_) [inline]
Definition at line 882 of file SbGeoObsVLBI.H'.
References DateCreat.
void SBVLBISesInfo::setDelayRMS2 (doubleDelayRMS_) [inline]
Definition at line 892 of file SbGeoObsVLBI.H'.
References DelayRMS2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISesInfo::setDelaySumW2 (doubled_) [inline]
Definition at line 894 of file SbGeoObsVLBI.H'.
References DelaySumW2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISesInfo::setDelayType (ObsDelayTypeDelayType_) [inline]
Definition at line 891 of file SbGeoObsVLBI.H'.
References DelayType.
void SBVLBISesInfo::setExpDescr (QStringExpDescr_) [inline]
Definition at line 886 of file SbGeoObsVLBI.H'.
References ExpDescr.
void SBVLBISesInfo::setImportedFrom (ObsImportedFromImportedFrom_) [inline]
Definition at line 878 of file SbGeoObsVLBI.H'.
References ImportedFrom.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBVLBISesInfo::setNetworkID (QStringNetworkID_) [inline]
Definition at line 885 of file SbGeoObsVLBI.H'.
References NetworkID.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBISet::import(), SBVLBISession::restoreUserInfo(), and SBVLBIPreProcess::saveSession().
void SBVLBISesInfo::setOfficialName (QStringOfficialName_) [inline]
Definition at line 888 of file SbGeoObsVLBI.H'.
References OfficialName.
Referenced by SBVLBISet::import().
void SBVLBISesInfo::setRateRMS2 (doubleRateRMS_) [inline]
Definition at line 893 of file SbGeoObsVLBI.H'.
References RateRMS2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISesInfo::setRateSumW2 (doubled_) [inline]
Definition at line 895 of file SbGeoObsVLBI.H'.
References RateSumW2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISesInfo::setSubKey (QStringSubKey_) [inline]
Definition at line 884 of file SbGeoObsVLBI.H'.
References SubKey.
void SBVLBISesInfo::setTFinis (SBMJDTFinis_) [inline]
Definition at line 880 of file SbGeoObsVLBI.H'.
References TFinis.
Referenced by SBVLBISet::saveSession().
void SBVLBISesInfo::setTMean (SBMJDTMean_) [inline]
Definition at line 881 of file SbGeoObsVLBI.H'.
References TMean.
Referenced by SBVLBISet::saveSession().
void SBVLBISesInfo::setTStart (SBMJDTStart_) [inline]
Definition at line 879 of file SbGeoObsVLBI.H'.
References TStart.
Referenced by SBVLBISet::saveSession().
void SBVLBISesInfo::setUserFlag (QStringUserFlag_) [inline]
Definition at line 887 of file SbGeoObsVLBI.H'.
References UserFlag.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBISet::import(), SBVLBISession::restoreUserInfo(), and SBVLBIPreProcess::saveSession().
void SBVLBISesInfo::setVersion (intV_) [inline]
Definition at line 883 of file SbGeoObsVLBI.H'.
References Version.
const QString& SBVLBISesInfo::subKey () const [inline]
Definition at line 861 of file SbGeoObsVLBI.H'.
References SubKey.
Referenced by operator=(), and SBVLBISesInfo().
const SBMJD& SBVLBISesInfo::tFinis () const [inline]
Definition at line 856 of file SbGeoObsVLBI.H'.
References TFinis.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISesInfoList::compareItems(), SBVLBIPreProcess::fillSessAttr(), SBRunManager::loadVLBISession_m1(), SBRunManager::makeReportSessionStatistics(), operator=(), SBVLBISet::saveSession(), SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
double SBVLBISesInfo::tInterval () const [inline]
Definition at line 858 of file SbGeoObsVLBI.H'.
References TFinis, and TStart.
Referenced by SBVLBISesInfoLI::key(), and SBVLBISesInfoLI::text().
const SBMJD& SBVLBISesInfo::tMean () const [inline]
Definition at line 857 of file SbGeoObsVLBI.H'.
References TMean.
Referenced by SBVLBIPreProcess::fillSessAttr(), operator<<(), operator=(), SBObsVLBIEntry::process(), SBVLBISet::saveSession(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
const SBMJD& SBVLBISesInfo::tStart () const [inline]
Definition at line 855 of file SbGeoObsVLBI.H'.
References TStart.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISesInfoList::compareItems(), SBVLBIPreProcess::fillSessAttr(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBRunManager::makeReportSessionStatistics(), operator=(), SBVLBISet::saveSession(), SBVLBISesInfo(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::updateSession(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
const QString& SBVLBISesInfo::userFlag () const [inline]
Definition at line 864 of file SbGeoObsVLBI.H'.
References UserFlag.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBIPreProcess::fillSessAttr(), SBVLBISesInfoLI::key(), operator=(), SBVLBIPreProcess::saveSession(), SBVLBISesInfo(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
int SBVLBISesInfo::version () const [inline]
Definition at line 859 of file SbGeoObsVLBI.H'.
References Version.
Referenced by SBVLBISet::import(), SBVLBISesInfoLI::key(), operator<<(), operator=(), SBVLBISesInfo(), SBVLBISessionEditor::SBVLBISessionEditor(), and SBVLBISesInfoLI::text().
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator<< (QDataStream &s, const SBVLBISesInfo &S) [friend]
Definition at line 1188 of file SbGeoObsVLBI.C'.
SBDS_dat& operator<< (SBDS_dat &s, const SBVLBISesInfo &S) [friend]
Definition at line 1214 of file SbGeoObsVLBI.C'.
SBDS_aux& operator<< (SBDS_aux &s, const SBVLBISesInfo &S) [friend]
Definition at line 1230 of file SbGeoObsVLBI.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBVLBISesInfo &S) [friend]
Definition at line 1200 of file SbGeoObsVLBI.C'.
SBDS_dat& operator>> (SBDS_dat &s, SBVLBISesInfo &S) [friend]
Definition at line 1222 of file SbGeoObsVLBI.C'.
SBDS_aux& operator>> (SBDS_aux &s, SBVLBISesInfo &S) [friend]
Definition at line 1235 of file SbGeoObsVLBI.C'.
friend class SBVLBISet [friend]
Reimplemented in SBVLBISession'.
Definition at line 795 of file SbGeoObsVLBI.H'.
Member Data Documentation
QString SBVLBISesInfo::Code [protected]
Code (from MasterFile)
Definition at line 826 of file SbGeoObsVLBI.H'.
Referenced by code(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setCode().
QString SBVLBISesInfo::CorrelatorName [protected]
Correlator Name (from MasterFile)
Definition at line 827 of file SbGeoObsVLBI.H'.
Referenced by correlatorName(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setCorrelatorName().
SBMJD SBVLBISesInfo::DateCreat [protected]
date of MkIII creation (just for curiosity);
Definition at line 817 of file SbGeoObsVLBI.H'.
Referenced by dateCreat(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setDateCreat().
double SBVLBISesInfo::DelayRMS2 [protected]
Definition at line 833 of file SbGeoObsVLBI.H'.
Referenced by addDelayRMS(), clearRMSs(), delayRMS2(), dWRMS(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setDelayRMS2().
double SBVLBISesInfo::DelaySumW2 [protected]
Definition at line 835 of file SbGeoObsVLBI.H'.
Referenced by addDelayRMS(), clearRMSs(), delaySumW2(), dWRMS(), SBVLBISet::loadSession(), operator<<(), operator=(), operator>>(), SBVLBISet::saveSession(), SBVLBISesInfo(), and setDelaySumW2().
ObsDelayType SBVLBISesInfo::DelayType [protected]
type of delay;
Definition at line 828 of file SbGeoObsVLBI.H'.
Referenced by delayType(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setDelayType().
QString SBVLBISesInfo::ExpDescr [protected]
Experiment description;'.
Definition at line 823 of file SbGeoObsVLBI.H'.
Referenced by expDescr(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setExpDescr().
ObsImportedFrom SBVLBISesInfo::ImportedFrom [protected]
origin of the session;
Definition at line 816 of file SbGeoObsVLBI.H'.
Referenced by importedFrom(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setImportedFrom().
int SBVLBISesInfo::LocalVersion [protected]
Definition at line 838 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISession::addHistoryLine(), incVersion(), localVersion(), operator<<(), operator=(), operator>>(), and SBVLBISesInfo().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
QString SBVLBISesInfo::NetworkID [protected]
Network ID (a key);'.
Definition at line 822 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISession::dumpUserInfo(), networkID(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setNetworkID().
int SBVLBISesInfo::NumBas [protected]
Definition at line 830 of file SbGeoObsVLBI.H'.
Referenced by numBas(), operator<<(), operator=(), operator>>(), and SBVLBISesInfo().
int SBVLBISesInfo::NumObs [protected]
Definition at line 832 of file SbGeoObsVLBI.H'.
Referenced by numObs(), operator<<(), operator=(), operator>>(), and SBVLBISesInfo().
int SBVLBISesInfo::NumSou [protected]
Definition at line 831 of file SbGeoObsVLBI.H'.
Referenced by numSou(), operator<<(), operator=(), operator>>(), and SBVLBISesInfo().
int SBVLBISesInfo::NumSta [protected]
Definition at line 829 of file SbGeoObsVLBI.H'.
Referenced by numSta(), operator<<(), operator=(), operator>>(), and SBVLBISesInfo().
QString SBVLBISesInfo::OfficialName [protected]
Official Name (from MasterFile)
Definition at line 825 of file SbGeoObsVLBI.H'.
Referenced by officialName(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), and setOfficialName().
double SBVLBISesInfo::RateRMS2 [protected]
Definition at line 834 of file SbGeoObsVLBI.H'.
Referenced by addRateRMS(), clearRMSs(), operator<<(), operator=(), operator>>(), rateRMS2(), rWRMS(), SBVLBISesInfo(), and setRateRMS2().
double SBVLBISesInfo::RateSumW2 [protected]
Definition at line 836 of file SbGeoObsVLBI.H'.
Referenced by addRateRMS(), clearRMSs(), SBVLBISet::loadSession(), operator<<(), operator=(), operator>>(), rateSumW2(), rWRMS(), SBVLBISet::saveSession(), SBVLBISesInfo(), and setRateSumW2().
QString SBVLBISesInfo::SubKey [protected]
aux key;
Definition at line 821 of file SbGeoObsVLBI.H'.
Referenced by checkPath(), fileName(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), setSubKey(), and subKey().
SBMJD SBVLBISesInfo::TFinis [protected]
last epoch of the observations;
Definition at line 819 of file SbGeoObsVLBI.H'.
Referenced by calcTMean(), SBVLBISession::calcTMean(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), setTFinis(), tFinis(), and tInterval().
SBMJD SBVLBISesInfo::TMean [protected]
mean epoch of the observations;
Definition at line 820 of file SbGeoObsVLBI.H'.
Referenced by calcTMean(), SBVLBISession::calcTMean(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), setTMean(), and tMean().
SBMJD SBVLBISesInfo::TStart [protected]
first epoch of the observations;
Definition at line 818 of file SbGeoObsVLBI.H'.
Referenced by calcTMean(), SBVLBISession::calcTMean(), checkPath(), fileName(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), setTStart(), tInterval(), and tStart().
QString SBVLBISesInfo::UserFlag [protected]
Flag assigned by user'.
Definition at line 824 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISession::dumpUserInfo(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), setUserFlag(), and userFlag().
int SBVLBISesInfo::Version [protected]
version;
Definition at line 837 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISession::dumpUserInfo(), fileName(), operator<<(), operator=(), operator>>(), SBVLBISesInfo(), setVersion(), and version().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.