SBVLBISesInfoLI
NAME
SBVLBISesInfoLI -
SYNOPSIS
#include <SbIObsVLBI.H>
Inherits QListViewItem'.
Inherited by SBVLBISesPreProcLI'.
Public Member Functions
SBVLBISesInfoLI (QListView *parent_, SBVLBISesInfo *SI_, BrowseMode Mode_)
~SBVLBISesInfoLI ()
SBVLBISesInfo * sessionInfo ()
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
Protected Attributes
SBVLBISesInfo * SI
BrowseMode Mode
Detailed Description
Definition at line 62 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBISesInfoLI::SBVLBISesInfoLI (QListView *parent_, SBVLBISesInfo *SI_, BrowseModeMode_) [inline]
Definition at line 69 of file SbIObsVLBI.H'.
References Mode, and SI.
SBVLBISesInfoLI::~SBVLBISesInfoLI () [inline]
Definition at line 72 of file SbIObsVLBI.H'.
References SI.
Member Function Documentation
virtual QString SBVLBISesInfoLI::ClassName () const [inline, virtual]
Reimplemented in SBVLBISesPreProcLI'.
Definition at line 74 of file SbIObsVLBI.H'.
QString SBVLBISesInfoLI::key (intcol, bool) const [virtual]
Reimplemented in SBVLBISesPreProcLI'.
Definition at line 149 of file SbIObsVLBI.C'.
References SBVLBISesInfo::ArtAllMeteos, SBVLBISesInfo::ArtMeteo, SBVLBISesInfo::BadAllCables, SBVLBISesInfo::BadAllMeteos, SBVLBISesInfo::BadCable, SBVLBISesInfo::BadMeteo, BM_PROJECT, SBVLBISesInfo::ConstrEOP, SBVLBISesInfo::correlatorName(), SBVLBISesInfo::dWRMS(), SBVLBISesInfo::HasClockBreak, SBVLBISesInfo::importedFrom(), SBAttributed::isAttr(), Mode, SBNamed::name(), SBVLBISesInfo::networkID(), SBVLBISesInfo::notValid, SBVLBISesInfo::numBas(), SBVLBISesInfo::numObs(), SBVLBISesInfo::numSou(), SBVLBISesInfo::numSta(), SBVLBISesInfo::preProc, SBVLBISesInfo::rWRMS(), SBSetUp::scale(), SetUp, SI, SBVLBISesInfo::tInterval(), TmpString, SBVLBISesInfo::tStart(), SBVLBISesInfo::userFlag(), and SBVLBISesInfo::version().
SBVLBISesInfo* SBVLBISesInfoLI::sessionInfo () [inline]
Definition at line 73 of file SbIObsVLBI.H'.
References SI.
Referenced by SBVLBIPreProcess::currentSesChange(), SBVLBISetView::deleteEntry(), SBProjectEdit::delSession(), and SBVLBISessionEditor::SBVLBISessionEditor().
QString SBVLBISesInfoLI::text (intcol) const [virtual]
Reimplemented in SBVLBISesPreProcLI'.
Definition at line 62 of file SbIObsVLBI.C'.
References SBVLBISesInfo::ArtAllMeteos, SBVLBISesInfo::ArtMeteo, SBVLBISesInfo::BadAllCables, SBVLBISesInfo::BadAllMeteos, SBVLBISesInfo::BadCable, SBVLBISesInfo::BadMeteo, BM_PROJECT, SBDelay::CLight, SBVLBISesInfo::ConstrEOP, SBVLBISesInfo::correlatorName(), SBVLBISesInfo::dWRMS(), SBMJD::F_DDMonYYYY, SBVLBISesInfo::HasClockBreak, SBVLBISesInfo::importedFrom(), SBAttributed::isAttr(), SBVLBISesInfo::localVersion(), Mode, SBNamed::name(), SBVLBISesInfo::networkID(), SBVLBISesInfo::notValid, SBVLBISesInfo::numBas(), SBVLBISesInfo::numObs(), SBVLBISesInfo::numSou(), SBVLBISesInfo::numSta(), SBVLBISesInfo::preProc, rad2hms(), SBVLBISesInfo::rWRMS(), SetUp, SI, SBVLBISesInfo::tInterval(), TmpString, SBMJD::toString(), SBVLBISesInfo::tStart(), SBSetUp::U_INCH, SBSetUp::U_METER, SBSetUp::U_SEC, SBSetUp::units(), SBVLBISesInfo::userFlag(), and SBVLBISesInfo::version().
Member Data Documentation
BrowseMode SBVLBISesInfoLI::Mode [protected]
Definition at line 66 of file SbIObsVLBI.H'.
Referenced by key(), SBVLBISesInfoLI(), and text().
SBVLBISesInfo* SBVLBISesInfoLI::SI [protected]
Definition at line 65 of file SbIObsVLBI.H'.
Referenced by key(), SBVLBISesPreProcLI::key(), SBVLBISesInfoLI(), sessionInfo(), text(), SBVLBISesPreProcLI::text(), and ~SBVLBISesInfoLI().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.