SBVLBINetworkEditor::NetworkListItem
NAME
SBVLBINetworkEditor::NetworkListItem -
SYNOPSIS
Inherits QListViewItem'.
Public Member Functions
NetworkListItem (QListView *parent, SBVLBISet::Network *N_)
virtual QString text (int) const
SBVLBISet::Network * network ()
Private Attributes
SBVLBISet::Network * Network
Detailed Description
Definition at line 607 of file SbIObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBINetworkEditor::NetworkListItem::NetworkListItem (QListView *parent, SBVLBISet::Network *N_) [inline]
Definition at line 612 of file SbIObsVLBI.H'.
References Network.
Member Function Documentation
SBVLBISet::Network* SBVLBINetworkEditor::NetworkListItem::network () [inline]
Definition at line 615 of file SbIObsVLBI.H'.
References Network.
QString SBVLBINetworkEditor::NetworkListItem::text (intcol) const [virtual]
Definition at line 2728 of file SbIObsVLBI.C'.
References SBVLBISet::Network::descr(), SBVLBISet::Network::keys(), SBNamed::name(), Network, and TmpString.
Member Data Documentation
SBVLBISet::Network* SBVLBINetworkEditor::NetworkListItem::Network [private]
Definition at line 610 of file SbIObsVLBI.H'.
Referenced by network(), NetworkListItem(), and text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.