SBVLBISession
NAME
SBVLBISession -
SYNOPSIS
#include <SbGeoObsVLBI.H>
Inherits SBObsVLBIList, and SBVLBISesInfo'.
Public Types
enum Attributes { preProc = 1<<0, notValid = 1<<1, BadCable = 1<<2, BadAllCables = 1<<3, BadMeteo = 1<<4, BadAllMeteos = 1<<5, HasClockBreak = 1<<6, ConstrEOP = 1<<7, ArtMeteo = 1<<8, ArtAllMeteos = 1<<9 }
enum ObsImportedFrom { IF_NGS = 0, IF_VBD = 1, IF_DBH = 2, IF_UNKN = 3 }
enum ObsDelayType { DT_GR = 0, DT_PH = 1, DT_UNKN = 2 }
Public Member Functions
SBVLBISession ()
virtual ~SBVLBISession ()
virtual QString ClassName () const
double refFreq () const
double grDelayAmbig () const
virtual int numSta () const
virtual int numBas () const
virtual int numSou () const
virtual int numObs () const
void addHistoryLine (const QString &T_, int V_=-1)
SBHistory * dbhHistory ()
SBHistory * localHistory ()
SBObsVLBIEntry * first ()
SBObsVLBIEntry * next ()
void setRefFreq (double RefFreq_)
void setGrDelayAmbig (double GrDelayAmbig_)
virtual bool operator== (const SBVLBISession &S) const
void fillDicts ()
void checkArtMeteo ()
void checkAttributres ()
SBStationInfoList * stationList ()
SBBaseInfoList * baseList ()
SBSourceInfoList * sourceList ()
SBStationInfo * stationInfo (short int Idx_) const
SBStationInfo * stationInfo (const char *Aka_) const
SBBaseInfo * baseInfo (short int Idx_) const
SBBaseInfo * baseInfo (const char *Aka_) const
SBSourceInfo * sourceInfo (short int Idx_) const
SBSourceInfo * sourceInfo (const char *Aka_) const
void setDump (QTextStream *Dump_)
QTextStream * dump ()
virtual void clearRMSs ()
void dumpUserInfo (const QString &)
bool restoreUserInfo (const QString &)
ObsImportedFrom importedFrom () const
const SBMJD & dateCreat () const
const SBMJD & tStart () const
const SBMJD & tFinis () const
const SBMJD & tMean () const
double tInterval () const
int version () const
int localVersion () const
const QString & subKey () const
const QString & networkID () const
const QString & expDescr () const
const QString & userFlag () const
const QString & officialName () const
const QString & code () const
const QString & correlatorName () const
ObsDelayType delayType () const
double delayRMS2 () const
double rateRMS2 () const
double delaySumW2 () const
double rateSumW2 () const
void setImportedFrom (ObsImportedFrom ImportedFrom_)
void setTStart (SBMJD TStart_)
void setTFinis (SBMJD TFinis_)
void setTMean (SBMJD TMean_)
void setDateCreat (SBMJD DateCreat_)
void setVersion (int V_)
void setSubKey (QString SubKey_)
void setNetworkID (QString NetworkID_)
void setExpDescr (QString ExpDescr_)
void setUserFlag (QString UserFlag_)
void setOfficialName (QString OfficialName_)
void setCode (QString Code_)
void setCorrelatorName (QString CName_)
void setDelayType (ObsDelayType DelayType_)
void setDelayRMS2 (double DelayRMS_)
void setRateRMS2 (double RateRMS_)
void setDelaySumW2 (double d_)
void setRateSumW2 (double d_)
void addDelayRMS (double o_c_, double w_)
void addRateRMS (double o_c_, double w_)
virtual bool operator== (const SBVLBISesInfo &I) const
virtual void incVersion ()
double dWRMS () const
double rWRMS () const
const QString & name () const
void setName (const QString &Name_)
uint attributes () const
void setAttributes (uint A_)
void addAttr (uint A_)
void delAttr (uint A_)
void xorAttr (uint A_)
bool isAttr (uint A_) const
void clearAll ()
Protected Types
enum File_Type { FT_DAT = 0, FT_AUX = 1, FT_UNKN = 2 }
Protected Member Functions
virtual int compareItems (QCollection::Item item1, QCollection::Item item2)
virtual QDataStream & write (QDataStream &s, QCollection::Item Entry) const
virtual QDataStream & read (QDataStream &s, QCollection::Item &Entry)
virtual void calcTMean ()
SBObsVLBIEntry * parseObsDumpString (const QString &, SBMJD &, SBStationInfo *&, SBStationInfo *&, SBSourceInfo *&)
QString fileName (File_Type=FT_DAT)
void checkPath ()
Protected Attributes
SBHistory DBHHistory
DBH History'.
SBHistory LocalHistory
local History
SBStationInfoList StationList
QIntDict< SBStationInfo > * StationByIdx
QDict< SBStationInfo > * StationByAka
SBSourceInfoList SourceList
QIntDict< SBSourceInfo > * SourceByIdx
QDict< SBSourceInfo > * SourceByAka
SBBaseInfoList BaseList
QIntDict< SBBaseInfo > * BaseByIdx
QDict< SBBaseInfo > * BaseByAka
double RefFreq
Reference frequency (MHz)
double GrDelayAmbig
Group delay ambiguity spacing (sec)
QTextStream * Dump
ObsImportedFrom ImportedFrom
origin of the session;
SBMJD DateCreat
date of MkIII creation (just for curiosity);
SBMJD TStart
first epoch of the observations;
SBMJD TFinis
last epoch of the observations;
SBMJD TMean
mean epoch of the observations;
QString SubKey
aux key;
QString NetworkID
Network ID (a key);'.
QString ExpDescr
Experiment description;'.
QString UserFlag
Flag assigned by user'.
QString OfficialName
Official Name (from MasterFile)
QString Code
Code (from MasterFile)
QString CorrelatorName
Correlator Name (from MasterFile)
ObsDelayType DelayType
type of delay;
int NumSta
int NumBas
int NumSou
int NumObs
double DelayRMS2
double RateRMS2
double DelaySumW2
double RateSumW2
int Version
version;
int LocalVersion
QString Name
Friends
class SBVLBISet
SBDS_dat & operator<< (SBDS_dat &, const SBVLBISession &)
SBDS_dat & operator>> (SBDS_dat &, SBVLBISession &)
SBDS_aux & operator<< (SBDS_aux &, SBVLBISession &)
SBDS_aux & operator>> (SBDS_aux &, SBVLBISession &)
SBTS_ngs & operator<< (SBTS_ngs &, const SBVLBISession &)
SBTS_ngs & operator>> (SBTS_ngs &, SBVLBISession &)
SBDS_dbh & operator<< (SBDS_dbh &, const SBVLBISession &)
SBDS_dbh & operator>> (SBDS_dbh &, SBVLBISession &)
SBTS_SINEX & operator<< (SBTS_SINEX &, SBVLBISession &)
bool operator== (const SBNamed &, const SBNamed &)
QDataStream & operator<< (QDataStream &, const SBVLBISesInfo &)
SBDS_dat & operator<< (SBDS_dat &, const SBVLBISesInfo &)
SBDS_aux & operator<< (SBDS_aux &, const SBVLBISesInfo &)
QDataStream & operator<< (QDataStream &, const SBNamed &)
QDataStream & operator<< (QDataStream &s, const SBAttributed &A)
QDataStream & operator>> (QDataStream &, SBVLBISesInfo &)
SBDS_dat & operator>> (SBDS_dat &, SBVLBISesInfo &)
SBDS_aux & operator>> (SBDS_aux &, SBVLBISesInfo &)
QDataStream & operator>> (QDataStream &, SBNamed &)
QDataStream & operator>> (QDataStream &s, SBAttributed &A)
bool operator!= (const SBNamed &, const SBNamed &)
bool operator< (const SBNamed &, const SBNamed &)
bool operator> (const SBNamed &, const SBNamed &)
int cmp (const SBNamed &, const SBNamed &)
Detailed Description
A session of VLBI observation'. This is a list of SBObsVLBIEntry objects, sorted by date'. Keeps information on stations and sources participated in the observations'.
Definition at line 956 of file SbGeoObsVLBI.H'.
Member Enumeration Documentation
enum SBVLBISesInfo::Attributes [inherited]
Enumerator:
preProc
session is preprocessed
notValid
omit this session from the project
BadCable
has at least one station without cable correction
BadAllCables
has all stations without cable correction
BadMeteo
has at least one station without meteo data
BadAllMeteos
has all stations without meteo data
HasClockBreak
there is/are `clock break(s)'
ConstrEOP
ArtMeteo
has at least one station with artificial meteo data
ArtAllMeteos
has all stations with artificial meteo data
Definition at line 797 of file SbGeoObsVLBI.H'.
enum SBVLBISesInfo::File_Type [protected, inherited]
Enumerator:
FT_DAT
FT_AUX
FT_UNKN
Definition at line 814 of file SbGeoObsVLBI.H'.
enum SBVLBISesInfo::ObsDelayType [inherited]
Enumerator:
DT_GR
DT_PH
DT_UNKN
Definition at line 811 of file SbGeoObsVLBI.H'.
enum SBVLBISesInfo::ObsImportedFrom [inherited]
Enumerator:
IF_NGS
IF_VBD
IF_DBH
IF_UNKN
Definition at line 810 of file SbGeoObsVLBI.H'.
Constructor & Destructor Documentation
SBVLBISession::SBVLBISession ()"A constructor'.
Definition at line 1250 of file SbGeoObsVLBI.C'.
References BaseByAka, BaseByIdx, BaseList, Dump, GrDelayAmbig, RefFreq, SourceByAka, SourceByIdx, SourceList, StationByAka, StationByIdx, and StationList.
SBVLBISession::~SBVLBISession () [virtual]"A destructor'.
Definition at line 1278 of file SbGeoObsVLBI.C'.
References BaseByAka, BaseByIdx, SourceByAka, SourceByIdx, StationByAka, and StationByIdx.
Member Function Documentation
void SBAttributed::addAttr (uintA_) [inline, inherited]"Adds the attribute to the storage'.
Definition at line 247 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by checkArtMeteo(), checkAttributres(), SBStation::createOLoad(), SBVLBIPreProcess::fixSession(), SBAploChunk::import(), SBAploEphem::importHPS(), SBMaster::importMF(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBSourceEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), operator>>(), SBFilterGauss::prepareModels(), SBObsVLBIEntry::process(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), restoreUserInfo(), SBEphem::SBEphem(), SBSourceInfo::SBSourceInfo(), SBStationInfo::SBStationInfo(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), SBParameter::tuneParameter(), SBSolutionBrowser::updateCRF(), and SBSolutionBrowser::updateTRF().
void SBVLBISesInfo::addDelayRMS (doubleo_c_, doublew_) [inline, inherited]
Definition at line 896 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelayRMS2, and SBVLBISesInfo::DelaySumW2.
Referenced by SBObsVLBIEntry::process().
void SBVLBISession::addHistoryLine (const QString &T_, intV_ = -1) [inline]
Definition at line 1010 of file SbGeoObsVLBI.H'.
References SBHistory::addHistoryLine(), LocalHistory, SBVLBISesInfo::LocalVersion, and SBVLBISesInfo::localVersion().
Referenced by checkArtMeteo(), SBVLBIPreProcess::clearPars(), SBVLBIPreProcess::fixSession(), and SBVLBISet::import().
void SBVLBISesInfo::addRateRMS (doubleo_c_, doublew_) [inline, inherited]
Definition at line 897 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::RateRMS2, and SBVLBISesInfo::RateSumW2.
uint SBAttributed::attributes () const [inline, inherited]"Returns the attributes'.
Definition at line 243 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCoordinates::operator==(), and SBVLBISessionEditor::~SBVLBISessionEditor().
SBBaseInfo* SBVLBISession::baseInfo (short intIdx_) const [inline]
Definition at line 1033 of file SbGeoObsVLBI.H'.
References BaseByIdx.
Referenced by SBVLBIPreProcess::fillObsListView(), and SBVLBISessionEditor::wObservs().
SBBaseInfo* SBVLBISession::baseInfo (const char *Aka_) const [inline]
Definition at line 1034 of file SbGeoObsVLBI.H'.
References BaseByAka.
SBBaseInfoList* SBVLBISession::baseList () [inline]
Definition at line 1028 of file SbGeoObsVLBI.H'.
References BaseList.
Referenced by SBProject::addSession(), SBVLBIPreProcess::currentSesChange(), SBProject::delSession(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), and SBVLBIPreProcess::updateSession().
void SBVLBISession::calcTMean () [protected, virtual]
Reimplemented from SBVLBISesInfo'.
Definition at line 1350 of file SbGeoObsVLBI.C'.
References first(), next(), SBObservation::notValid, SBVLBISesInfo::TFinis, SBVLBISesInfo::TMean, and SBVLBISesInfo::TStart.
Referenced by SBVLBISet::import(), and SBVLBISet::saveSession().
void SBVLBISession::checkArtMeteo ()
Definition at line 1364 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), addHistoryLine(), SBVLBISesInfo::ArtAllMeteos, SBStationInfo::ArtMeteo, SBVLBISesInfo::ArtMeteo, SBObsVLBIEntry::AtmHum_1, SBObsVLBIEntry::AtmHum_2, SBObsVLBIEntry::AtmPress_1, SBObsVLBIEntry::AtmPress_2, SBObsVLBIEntry::AtmTemp_1, SBObsVLBIEntry::AtmTemp_2, first(), SBObjectObsInfo::idx(), SBAttributed::isAttr(), next(), SBObsVLBIEntry::Station_1, SBObsVLBIEntry::Station_2, and StationList.
Referenced by SBVLBISet::import().
void SBVLBISession::checkAttributres ()
Definition at line 1445 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), SBVLBISesInfo::ArtAllMeteos, SBStationInfo::ArtMeteo, SBVLBISesInfo::ArtMeteo, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBAttributed::delAttr(), first(), SBStationInfo::HasClockBreak, SBVLBISesInfo::HasClockBreak, SBObjectObsInfo::idx(), SBAttributed::isAttr(), next(), SBObsVLBIEntry::Station_1, SBObsVLBIEntry::Station_2, and StationList.
Referenced by SBVLBIPreProcess::saveSession(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBVLBISesInfo::checkPath () [protected, inherited]
Definition at line 1163 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::ClassName(), SBLog::DATA, SBLog::ERR, Log, SBSetUp::path2Data(), SetUp, SBVLBISesInfo::SubKey, SBVLBISesInfo::TStart, SBLog::write(), and SBMJD::year().
Referenced by SBVLBISet::import().
virtual QString SBVLBISession::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBVLBISesInfo'.
Definition at line 998 of file SbGeoObsVLBI.H'.
Referenced by dumpUserInfo(), fillDicts(), parseObsDumpString(), and restoreUserInfo().
void SBAttributed::clearAll () [inline, inherited]"Removes all attributes'.
Definition at line 255 of file SbGeneral.H'.
References SBAttributed::Attr.
virtual void SBVLBISession::clearRMSs () [inline, virtual]
Reimplemented from SBVLBISesInfo'.
Definition at line 1039 of file SbGeoObsVLBI.H'.
References BaseList, SBStationInfoList::clearRMSs(), SBBaseInfoList::clearRMSs(), SBSourceInfoList::clearRMSs(), SourceList, and StationList.
Referenced by SBVLBIPreProcess::clearPars(), and SBRunManager::loadVLBISession_m1().
const QString& SBVLBISesInfo::code () const [inline, inherited]
Definition at line 866 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::Code.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBRunManager::makeReportSessionStatistics(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
virtual int SBVLBISession::compareItems (QCollection::Itemitem1, QCollection::Itemitem2) [inline, protected, virtual]
Definition at line 960 of file SbGeoObsVLBI.H'.
const QString& SBVLBISesInfo::correlatorName () const [inline, inherited]
Definition at line 867 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::CorrelatorName.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBVLBISesInfoLI::key(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
const SBMJD& SBVLBISesInfo::dateCreat () const [inline, inherited]
Definition at line 854 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DateCreat.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
SBHistory* SBVLBISession::dbhHistory () [inline]
Definition at line 1012 of file SbGeoObsVLBI.H'.
References DBHHistory.
Referenced by SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), and SBVLBIPreProcess::updateSession().
void SBAttributed::delAttr (uintA_) [inline, inherited]"Deletes the attribute from the storage'.
Definition at line 249 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBProject::addSession(), checkAttributres(), SBVLBIPreProcess::clearPars(), SBStation::deleteOLoad(), SBObsVLBIEntry::isEligible(), SBFilteringGauss::makeAnalysisWith3Sigma(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportTRF(), SBStationInfo::restoreUserInfo(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), restoreUserInfo(), SBParameter::rw(), SBEphem::SBEphem(), SBStation::SBStation(), SBSpectrumAnalyserMEM::setMEMAssumeEquiDistant(), SBSpectrumAnalyserMEM::setMEMFillMissingImag(), SBSpectrumAnalyserMEM::setMEMRemoveShifts(), SBSpectrumAnalyserMEM::setMEMRemoveTrends(), and SBParameter::tuneParameter().
double SBVLBISesInfo::delayRMS2 () const [inline, inherited]
Definition at line 873 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelayRMS2.
Referenced by SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), and SBVLBISesInfo::SBVLBISesInfo().
double SBVLBISesInfo::delaySumW2 () const [inline, inherited]
Definition at line 875 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelaySumW2.
Referenced by SBRunManager::saveVLBISessions_m1().
ObsDelayType SBVLBISesInfo::delayType () const [inline, inherited]
Definition at line 868 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelayType.
Referenced by SBVLBISesInfo::operator=(), and SBVLBISesInfo::SBVLBISesInfo().
QTextStream* SBVLBISession::dump () [inline]
Definition at line 1038 of file SbGeoObsVLBI.H'.
References Dump.
void SBVLBISession::dumpUserInfo (const QString &Path)
Definition at line 1496 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::ArtAllMeteos, SBVLBISesInfo::ArtMeteo, SBVLBISesInfo::BadAllCables, SBVLBISesInfo::BadAllMeteos, SBVLBISesInfo::BadCable, SBVLBISesInfo::BadMeteo, BaseList, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, ClassName(), SBFCList::close(), SBVLBISesInfo::ConstrEOP, SBLog::DATA, SBLog::DBG, SBFCList::defaultExt(), SBStationInfoList::dumpUserInfo(), SBBaseInfoList::dumpUserInfo(), SBSourceInfoList::dumpUserInfo(), SBMJD::F_INTERNAL, SBSetUp::fcList(), first(), SBVLBISesInfo::HasClockBreak, SBAttributed::isAttr(), Log, SBNamed::name(), SBVLBISesInfo::NetworkID, next(), SBObservation::notValid, SBVLBISesInfo::notValid, SBFCList::open4OutDflt(), SBVLBISesInfo::preProc, SetUp, sourceInfo(), SourceList, stationInfo(), StationList, SBVLBISesInfo::UserFlag, SBVLBISesInfo::Version, and SBLog::write().
Referenced by SBVLBIPreProcess::dumpUI(), and SBVLBISet::dumpUserInfo().
double SBVLBISesInfo::dWRMS () const [inline, inherited]
Definition at line 907 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelayRMS2, and SBVLBISesInfo::DelaySumW2.
Referenced by SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBISesInfoLI::text(), and SBVLBISesPreProcLI::text().
const QString& SBVLBISesInfo::expDescr () const [inline, inherited]
Definition at line 863 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::ExpDescr.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBVLBISet::import(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
QString SBVLBISesInfo::fileName (File_TypeFType = FT_DAT) [protected, inherited]
Definition at line 1155 of file SbGeoObsVLBI.C'.
References SBVLBISesInfo::FT_DAT, SBNamed::Name, SBSetUp::path2Data(), SetUp, SBVLBISesInfo::SubKey, SBVLBISesInfo::TStart, SBVLBISesInfo::Version, and SBMJD::year().
Referenced by SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISet::removeSession(), and SBVLBISet::saveSession().
void SBVLBISession::fillDicts ()"Updates dictionaries'. This function have to be called after loading session from a stream to keep the dictionaries (SBVLBISession::StationByIdx, SBVLBISession::StationByAka, SBVLBISession::SourceByIdx and SBVLBISession::SourceByAka) up to date'.
Definition at line 1293 of file SbGeoObsVLBI.C'.
References SBObjectObsInfo::aka(), BaseByAka, BaseByIdx, BaseList, ClassName(), SBLog::DATA, SBLog::ERR, SBObjectObsInfo::idx(), Log, SourceByAka, SourceByIdx, SourceList, StationByAka, StationByIdx, StationList, and SBLog::write().
Referenced by operator>>().
SBObsVLBIEntry* SBVLBISession::first () [inline]
Definition at line 1014 of file SbGeoObsVLBI.H'.
Referenced by calcTMean(), checkArtMeteo(), checkAttributres(), dumpUserInfo(), SBVLBIPreProcess::fillObsListView(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), operator<<(), operator>>(), parseObsDumpString(), SBRunManager::saveVLBISessions_m2(), and SBVLBISessionEditor::wObservs().
double SBVLBISession::grDelayAmbig () const [inline]
Definition at line 1003 of file SbGeoObsVLBI.H'.
References GrDelayAmbig.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
ObsImportedFrom SBVLBISesInfo::importedFrom () const [inline, inherited]
Definition at line 853 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::ImportedFrom.
Referenced by SBVLBISesInfoLI::key(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfoLI::text().
virtual void SBVLBISesInfo::incVersion () [inline, virtual, inherited]
Definition at line 905 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::LocalVersion.
Referenced by SBVLBISessionEditor::histVerInced().
bool SBAttributed::isAttr (uintA_) const [inline, inherited]"Returns TRUE if the attribute is set'.
Definition at line 253 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStationEditor::acquireData(), SBStaParsEditor::acquireData(), SBObsVLBIEntry::ambientH_1(), SBObsVLBIEntry::ambientH_2(), SBObsVLBIEntry::ambientP_1(), SBObsVLBIEntry::ambientP_2(), SBObsVLBIEntry::ambientT_1(), SBObsVLBIEntry::ambientT_2(), SBDelay::calc(), checkArtMeteo(), checkAttributres(), collectListOfSINEXParameters(), SBStationInfo::dumpUserInfo(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), dumpUserInfo(), SBFilterModel::eliminateAfter(), SBFilterModel::eliminateBefore(), SBVLBIPreProcess::fillObsListView(), SBRunManager::fillParameterList(), SBMEM::fpe(), SBFilterGauss::interpolate(), SBObservation::isEligible(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBVLBIObsLI::key(), SBStaInfoLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBStationImport::loadOLoad(), SBParameter::m(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportMaps(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), operator<<(), operator>>(), SBVLBIObsPPLI::paintCell(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBMEM::readDataFile(), SBParameter::rw(), SBStaParsEditor::SBStaParsEditor(), SBProjectCreate::selChanged(), sinex_SiteEccentricityBlock(), sinex_SiteIDBlock(), sinex_SourceIDBlock(), SBParameter::str4compare(), SBVLBIObsPPLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBVLBISesInfoLI::text(), SBVLBISesPreProcLI::text(), SBVLBIObsLI::text(), SBStaInfoLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBMasterRecBrowser::SBMRListItem::text(), SBSolutionBrowser::updateCRF(), SBBrowseSources::updateList(), SBSolutionBrowser::updateTRF(), SBVLBISessionEditor::wObservs(), SBSourceEditor::wStats(), SBStationEditor::wStats(), and SBStation::~SBStation().
SBHistory* SBVLBISession::localHistory () [inline]
Definition at line 1013 of file SbGeoObsVLBI.H'.
References LocalHistory.
Referenced by SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), and SBVLBIPreProcess::updateSession().
int SBVLBISesInfo::localVersion () const [inline, inherited]
Definition at line 860 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::LocalVersion.
Referenced by addHistoryLine(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), SBVLBISesInfoLI::text(), and SBVLBIPreProcess::updateSession().
const QString& SBNamed::name () const [inline, inherited]
Definition at line 215 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBStochParameter::addPar(), SBProject::addSession(), SBSite::addStation(), SBParameterList::append(), SBVector::at(), SBMatrix::at(), SBUpperMatrix::at(), SBSymMatrix::at(), SBStation::axisOffsetLenght(), SBSolutionBrowser::batch4StochEOPChanged(), SBSolutionBrowser::batch4StochSoChanged(), SBSolutionBrowser::batch4StochStChanged(), SBEphem::calc(), SBStation::calcDisplacement(), SBSetupDialog::chkPacker(), SBVLBIPreProcess::clearPars(), SBEstimator::collectContStochs4NextBatch(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SB_CRF::collectObjAliases(), SBObsVLBIStatistics::collectStatistics(), SBRunManager::constraintSourceCoord(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBSource::createParameters(), SBProjectCreate::createProject(), SBTestFrame::createWidget4Test(), SBTestEphem::createWidget4Test(), SBVLBIPreProcess::currentSesChange(), SBPlotArea::defineAreas(), SBSiteEditor::deleteEntry(), SBVLBISetView::deleteEntry(), SBStuffSources::deleteEntryS(), SBStuffStations::deleteEntryS(), SBSolution::deleteSolution(), SBSetupDialog::delInst(), SBSetupDialog::delPacker(), SBEstimator::Group::delParameter(), SBProjectEdit::delSession(), SBProject::delSession(), SBSite::delStation(), SBPlateMotion::displacement(), SBStuffAplo::draw(), SBPlotArea::drawFrames(), SBStochParameter::dump2File(), SBSolution::dumpParameters(), SBBaseInfo::dumpUserInfo(), SBSourceInfo::dumpUserInfo(), dumpUserInfo(), SBVLBISet::dumpUserInfo(), SBParametersEditor::editParameter(), SBAploChunk::fillDict(), SBVLBISet::fillDicts(), SBVLBIPreProcess::fillObsListView(), SBVLBIPreProcess::fillSessAttr(), SBCatalog::find(), SBSolution::getGlobalParameter4Report(), SBAploChunk::import(), SBVLBISet::import(), SBEcc::importEccDat(), SBAploEphem::importHPS(), SBMaster::importMF(), SBProjectCreate::init(), SBFCList::insert(), SBInstitutionList::insert(), SBCatalog::insert(), SBParameterList::inSort(), SBCatalog::inSort(), SBStochParameterList::inSort(), SB_TRF::inSort(), SBObsVLBIStatSrcLI::key(), SBParameterLI::key(), SBSourceListItem::key(), SBStationListItem::key(), SBObsVLBIStatStaLI::key(), SBVLBISesInfoLI::key(), SBSiteListItem::key(), SBObsVLBIStatRecordLI::key(), SBBasInfoLI::key(), SBSouInfoLI::key(), SBAploEntryLI::key(), SBTestStationLI::key(), SBStationImport::loadNScodes(), SBStationImport::loadOLoad(), SBSolution::loadStatistics(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), SB_CRF::lookupNearest(), SB_TRF::lookupNearest(), SBSolutionBrowser::lookupParameters(), SBSourceEditor::makeApply(), SBSiteEditor::makeApply(), SBStationEditor::makeApply(), SBRunManager::makeReportCRF(), SBRunManager::makeReportCRFVariations(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportEOP(), SBRunManager::makeReportMaps(), SBRunManager::makeReportNormalEqs(), SBRunManager::makeReports(), SBRunManager::makeReportSessionStatistics(), SBRunManager::makeReportTRF(), SBRunManager::makeReportTRFVariations(), SBRunManager::makeReportTroposphere(), SBEstimator::mapContStochs4NewBatch(), SBMaster::mapFiles(), SBMaster::mapRecords(), matT_x_mat(), SBEstimator::moveGlobalInfo(), SBEstimator::moveGlobalInfo_Old(), SBFileConv::open4In(), SBFileConv::open4Out(), SBEphem::openFile(), SBVector::operator()(), SBSolidTideLd::operator()(), SBTideLd::operator()(), SBMatrix::operator()(), SBRefraction::operator()(), SBUpperMatrix::operator()(), operator*(), operator+(), SBVector::operator+=(), SBMatrix::operator+=(), SBUpperMatrix::operator+=(), operator-(), SBVector::operator-=(), SBMatrix::operator-=(), SBUpperMatrix::operator-=(), SBObsVLBIEntry::operator<(), operator<<(), SBVector::operator=(), SBMatrix::operator=(), SBUpperMatrix::operator=(), SBVLBISesInfo::operator=(), SBVector::operator==(), SBObsVLBIEntry::operator==(), SBVLBISesInfo::operator==(), operator>>(), operator~(), SBSymMatrix::operator~(), SBPlotArea::output4Files(), SBSolution::path2GlbDir(), SBSolution::path2LocDir(), SBSolution::path2StcDir(), SBEstimator::prepare4Local(), SBSite::prepareDicts(), SBVLBIPreProcess::preProcess(), SBObsVLBIEntry::process(), SBRunManager::process_m1(), SBRunManager::process_m2(), SBVLBIPreProcess::procScenario_2(), SBProjectSel::ProjectListItem::ProjectListItem(), QuadraticForm(), SBRefraction::refrDir(), SBAploEphem::registerStation(), SBInstitutionList::remove(), SBParameterList::remove(), SBStochParameterList::remove(), SBVLBISet::removeSession(), SBParameterList::report(), SBStochParameter::report(), SBBaseInfo::restoreUserInfo(), SBSourceInfo::restoreUserInfo(), restoreUserInfo(), RRT(), RTR(), SBParameter::rw(), SBPlot::save2PS(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), SBRunManager::saveVLBISessions_m2(), SBCoordsEditor::SBCoordsEditor(), SBEstimator::SBEstimator(), SBModelEditor::SBModelEditor(), SBObsVLBIStatBrowser::SBObsVLBIStatBrowser(), SBObsVLBIStatSrc::SBObsVLBIStatSrc(), SBObsVLBIStatSta::SBObsVLBIStatSta(), SBParametersEditor::SBParametersEditor(), SBPlateMotion::SBPlateMotion(), SBPlot::SBPlot(), SBPlotDialog::SBPlotDialog(), SBProjectEdit::SBProjectEdit(), SBRunManager::SBRunManager(), SBSolution::SBSolution(), SBSolutionBrowser::SBSolutionBrowser(), SBStuffEphem::SBStuffEphem(), SBTestAPLoad::SBTestAPLoad(), SBTestDiurnEOP::SBTestDiurnEOP(), SBTestEphem::SBTestEphem(), SBTestFrame::SBTestFrame(), SBTestNutation::SBTestNutation(), SBTestOceanTides::SBTestOceanTides(), SBTestPolarTides::SBTestPolarTides(), SBTestSolidTides::SBTestSolidTides(), SBVLBINetEntryEditor::SBVLBINetEntryEditor(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVector::set(), SBMatrix::set(), SBUpperMatrix::set(), SBMatrix::setCol(), SBUpperMatrix::setCol(), SBFCList::setDefault(), SB_TRF::setSiteName(), SBMatrix::setVector(), SBUpperMatrix::setVector(), Solve(), SBEstimator::solveLocals(), SBObsVLBIEntry::source(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), SBParameter::str4compare(), SBRunManager::stripTRF(), SBSolution::submitGlobalParameters(), SBSolution::submitLocalParameters(), SBSolution::submitStochasticParameters(), SBMatrix::T(), SBUpperMatrix::T(), SBFileConvLI::text(), SBParameterLI::text(), SBObsVLBIStatSrcLI::text(), SBSourceListItem::text(), SBStationListItem::text(), SBObsVLBIStatStaLI::text(), SBVLBISesInfoLI::text(), SBSolutionBatchLI::text(), SBSiteListItem::text(), SBObsVLBIStatRecordLI::text(), SBVLBISesPreProcLI::text(), SBSetupDialog::SBInstLI::text(), SBBasInfoLI::text(), SBSouInfoLI::text(), SBAploEntryLI::text(), SBTestStationLI::text(), SBVLBINetworkEditor::NetworkListItem::text(), SBMasterRecBrowser::SBMRListItem::text(), SBStochParameter::update(), SBSolution::updateParameter(), SBVLBIPreProcess::updateSession(), SBParameterList::updateSolution(), SBMainWindow::UtilitiesCollectStat4Prj(), SBPlateMotion::velocity(), SBVLBIPreProcess::wAttributes(), SBSourceEditor::wCoordinates(), SBParametersEditor::wEOPParameters(), SBSolutionBrowser::wLocalEOPPars(), SBSolutionBrowser::wLocalSoPars(), SBSolutionBrowser::wLocalStPars(), SBStationEditor::wNames(), SBVLBISessionEditor::wObservs(), SBParametersEditor::wOtherParameters(), SBVLBISessionEditor::wParameters(), writeNormalEquationSystem(), SBSiteEditor::wSite(), SBParametersEditor::wSourceParameters(), SBParametersEditor::wStationParameters(), SBSolutionBrowser::wStochEOPPars(), SBSolutionBrowser::wStochSoPars(), SBSolutionBrowser::wStochStPars(), SBParametersEditor::wTestParameters(), and SBSolutionBrowser::wWRMSs().
const QString& SBVLBISesInfo::networkID () const [inline, inherited]
Definition at line 862 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::NetworkID.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBIPreProcess::fillSessAttr(), SBVLBISet::import(), SBVLBISesInfoLI::key(), SBVLBISesInfo::operator=(), SBVLBIPreProcess::saveSession(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
SBObsVLBIEntry* SBVLBISession::next () [inline]
Definition at line 1015 of file SbGeoObsVLBI.H'.
Referenced by calcTMean(), checkArtMeteo(), checkAttributres(), dumpUserInfo(), SBVLBIPreProcess::fillObsListView(), SBRunManager::loadVLBISession_m1(), SBRunManager::loadVLBISessions_m2(), operator<<(), operator>>(), parseObsDumpString(), SBRunManager::saveVLBISessions_m2(), and SBVLBISessionEditor::wObservs().
virtual int SBVLBISession::numBas () const [inline, virtual]
Reimplemented from SBVLBISesInfo'.
Definition at line 1005 of file SbGeoObsVLBI.H'.
References BaseList.
virtual int SBVLBISession::numObs () const [inline, virtual]
Reimplemented from SBVLBISesInfo'.
Definition at line 1007 of file SbGeoObsVLBI.H'.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISet::import(), and SBRunManager::makeReportSessionStatistics().
virtual int SBVLBISession::numSou () const [inline, virtual]
Reimplemented from SBVLBISesInfo'.
Definition at line 1006 of file SbGeoObsVLBI.H'.
References SourceList.
Referenced by SBRunManager::makeReportSessionStatistics().
virtual int SBVLBISession::numSta () const [inline, virtual]
Reimplemented from SBVLBISesInfo'.
Definition at line 1004 of file SbGeoObsVLBI.H'.
References StationList.
Referenced by SBRunManager::makeReportSessionStatistics().
const QString& SBVLBISesInfo::officialName () const [inline, inherited]
Definition at line 865 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::OfficialName.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBRunManager::makeReportSessionStatistics(), operator<<(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
virtual bool SBVLBISesInfo::operator== (const SBVLBISesInfo &I) const [inline, virtual, inherited]
Definition at line 901 of file SbGeoObsVLBI.H'.
References SBNamed::name().
virtual bool SBVLBISession::operator== (const SBVLBISession &S) const [inline, virtual]
Definition at line 1020 of file SbGeoObsVLBI.H'.
SBObsVLBIEntry * SBVLBISession::parseObsDumpString (const QString &Str, SBMJD &t, SBStationInfo *&St_1, SBStationInfo *&St_2, SBSourceInfo *&So) [protected]
Definition at line 1770 of file SbGeoObsVLBI.C'.
References ClassName(), SBLog::DATA, SBMJD::F_INTERNAL, SBStationInfoList::find(), SBSourceInfoList::find(), first(), SBObjectObsInfo::idx(), SBMJD::isGood(), SBStationID::isValidStr(), Log, next(), SBMJD::setMJD(), SBObsVLBIEntry::sourceIdx(), SourceList, SBObsVLBIEntry::station_1Idx(), SBObsVLBIEntry::station_2Idx(), StationList, SBLog::write(), and SBLog::WRN.
Referenced by restoreUserInfo().
double SBVLBISesInfo::rateRMS2 () const [inline, inherited]
Definition at line 874 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::RateRMS2.
Referenced by SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), SBVLBISet::saveSession(), SBRunManager::saveVLBISessions_m1(), and SBVLBISesInfo::SBVLBISesInfo().
double SBVLBISesInfo::rateSumW2 () const [inline, inherited]
Definition at line 876 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::RateSumW2.
Referenced by SBRunManager::saveVLBISessions_m1().
virtual QDataStream& SBVLBISession::read (QDataStream &s, QCollection::Item &Entry) [inline, protected, virtual]
Definition at line 966 of file SbGeoObsVLBI.H'.
double SBVLBISession::refFreq () const [inline]
Definition at line 1002 of file SbGeoObsVLBI.H'.
References RefFreq.
Referenced by SBVLBIPreProcess::fillSessAttr(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
bool SBVLBISession::restoreUserInfo (const QString &Path)
Definition at line 1564 of file SbGeoObsVLBI.C'.
References SBAttributed::addAttr(), SBVLBISesInfo::ArtAllMeteos, SBVLBISesInfo::ArtMeteo, SBVLBISesInfo::BadAllCables, SBVLBISesInfo::BadAllMeteos, SBVLBISesInfo::BadCable, SBVLBISesInfo::BadMeteo, BaseList, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, ClassName(), SBFCList::close(), SBVLBISesInfo::ConstrEOP, SBLog::DATA, SBLog::DBG, SBAttributed::delAttr(), SBSetUp::fcList(), SBFCList::guessFileType(), SBVLBISesInfo::HasClockBreak, Log, SBNamed::name(), SBObservation::notValid, SBVLBISesInfo::notValid, SBFCList::open4In(), parseObsDumpString(), SBVLBISesInfo::preProc, SBStationInfoList::restoreUserInfo(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBObsVLBIEntry::setAmbiguityFactor(), SBVLBISesInfo::setNetworkID(), SetUp, SBVLBISesInfo::setUserFlag(), SourceList, StationList, SBLog::write(), and SBLog::WRN.
Referenced by SBVLBIPreProcess::restoreUI().
double SBVLBISesInfo::rWRMS () const [inline, inherited]
Definition at line 908 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::RateRMS2, and SBVLBISesInfo::RateSumW2.
Referenced by SBVLBISesInfoLI::key(), and SBVLBISesInfoLI::text().
void SBAttributed::setAttributes (uintA_) [inline, inherited]"Sets up the attributes'.
Definition at line 245 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBCelestBody::SBCelestBody(), and SBVLBISessionEditor::~SBVLBISessionEditor().
void SBVLBISesInfo::setCode (QStringCode_) [inline, inherited]
Definition at line 889 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::Code.
Referenced by SBVLBISet::import().
void SBVLBISesInfo::setCorrelatorName (QStringCName_) [inline, inherited]
Definition at line 890 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::CorrelatorName.
Referenced by SBVLBISet::import().
void SBVLBISesInfo::setDateCreat (SBMJDDateCreat_) [inline, inherited]
Definition at line 882 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DateCreat.
void SBVLBISesInfo::setDelayRMS2 (doubleDelayRMS_) [inline, inherited]
Definition at line 892 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelayRMS2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISesInfo::setDelaySumW2 (doubled_) [inline, inherited]
Definition at line 894 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelaySumW2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISesInfo::setDelayType (ObsDelayTypeDelayType_) [inline, inherited]
Definition at line 891 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::DelayType.
void SBVLBISession::setDump (QTextStream *Dump_) [inline]
Definition at line 1037 of file SbGeoObsVLBI.H'.
References Dump.
Referenced by SBVLBISet::import().
void SBVLBISesInfo::setExpDescr (QStringExpDescr_) [inline, inherited]
Definition at line 886 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::ExpDescr.
void SBVLBISession::setGrDelayAmbig (doubleGrDelayAmbig_) [inline]
Definition at line 1018 of file SbGeoObsVLBI.H'.
References GrDelayAmbig.
void SBVLBISesInfo::setImportedFrom (ObsImportedFromImportedFrom_) [inline, inherited]
Definition at line 878 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::ImportedFrom.
void SBNamed::setName (const QString &Name_) [inline, inherited]
Definition at line 216 of file SbGeo.H'.
References SBNamed::Name.
Referenced by SBVLBINetEntryEditor::accept(), SBSourceEditor::acquireData(), SBSiteEditor::acquireData(), SBStationEditor::acquireData(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBVLBISet::import(), SBVLBISet::loadSession(), SBVLBISesInfo::operator=(), operator>>(), SBPlotArea::output4Files(), SBFilteringGauss::redrawDataPlot_ExpMode(), SBBaseInfoList::restoreUserInfo(), SBSourceInfoList::restoreUserInfo(), SBMasterRecord::SBMasterRecord(), SBSolution::SBSolution(), SB_TRF::setSiteName(), SBTestSolidTides::stationChange(), SBTestOceanTides::stationChange(), SBTestPolarTides::stationChange(), SBTestAPLoad::stationChange(), and SBVLBIPreProcess::updateSession().
void SBVLBISesInfo::setNetworkID (QStringNetworkID_) [inline, inherited]
Definition at line 885 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::NetworkID.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBISet::import(), restoreUserInfo(), and SBVLBIPreProcess::saveSession().
void SBVLBISesInfo::setOfficialName (QStringOfficialName_) [inline, inherited]
Definition at line 888 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::OfficialName.
Referenced by SBVLBISet::import().
void SBVLBISesInfo::setRateRMS2 (doubleRateRMS_) [inline, inherited]
Definition at line 893 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::RateRMS2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISesInfo::setRateSumW2 (doubled_) [inline, inherited]
Definition at line 895 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::RateSumW2.
Referenced by SBVLBISet::loadSession(), SBVLBISet::saveSession(), and SBRunManager::saveVLBISessions_m1().
void SBVLBISession::setRefFreq (doubleRefFreq_) [inline]
Definition at line 1017 of file SbGeoObsVLBI.H'.
References RefFreq.
void SBVLBISesInfo::setSubKey (QStringSubKey_) [inline, inherited]
Definition at line 884 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::SubKey.
void SBVLBISesInfo::setTFinis (SBMJDTFinis_) [inline, inherited]
Definition at line 880 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::TFinis.
Referenced by SBVLBISet::saveSession().
void SBVLBISesInfo::setTMean (SBMJDTMean_) [inline, inherited]
Definition at line 881 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::TMean.
Referenced by SBVLBISet::saveSession().
void SBVLBISesInfo::setTStart (SBMJDTStart_) [inline, inherited]
Definition at line 879 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::TStart.
Referenced by SBVLBISet::saveSession().
void SBVLBISesInfo::setUserFlag (QStringUserFlag_) [inline, inherited]
Definition at line 887 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::UserFlag.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBISet::import(), restoreUserInfo(), and SBVLBIPreProcess::saveSession().
void SBVLBISesInfo::setVersion (intV_) [inline, inherited]
Definition at line 883 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::Version.
SBSourceInfo* SBVLBISession::sourceInfo (short intIdx_) const [inline]
Definition at line 1035 of file SbGeoObsVLBI.H'.
References SourceByIdx.
Referenced by dumpUserInfo(), SBVLBIPreProcess::fillObsListView(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), SBObsVLBIEntry::sourceInfo(), SBVLBIObsPPLI::text(), and SBVLBIObsLI::text().
SBSourceInfo* SBVLBISession::sourceInfo (const char *Aka_) const [inline]
Definition at line 1036 of file SbGeoObsVLBI.H'.
References SourceByAka.
SBSourceInfoList* SBVLBISession::sourceList () [inline]
Definition at line 1029 of file SbGeoObsVLBI.H'.
References SourceList.
Referenced by SBProject::addSession(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBProject::delSession(), SBRunManager::makeReportCRFVariations4IVS(), SBRunManager::makeReportSessionStatistics(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), and SBVLBIPreProcess::updateSession().
SBStationInfo* SBVLBISession::stationInfo (short intIdx_) const [inline]
Definition at line 1031 of file SbGeoObsVLBI.H'.
References StationByIdx.
Referenced by dumpUserInfo(), SBVLBIPreProcess::fillObsListView(), SBObsVLBIEntry::isEligible(), SBVLBIObsPPLI::key(), SBVLBIObsLI::key(), SBObsVLBIEntry::station1Info(), SBObsVLBIEntry::station2Info(), SBVLBIObsPPLI::text(), SBVLBIObsLI::text(), and SBVLBISessionEditor::wObservs().
SBStationInfo* SBVLBISession::stationInfo (const char *Aka_) const [inline]
Definition at line 1032 of file SbGeoObsVLBI.H'.
References StationByAka.
SBStationInfoList* SBVLBISession::stationList () [inline]
Definition at line 1027 of file SbGeoObsVLBI.H'.
References StationList.
Referenced by SBProject::addSession(), SBVLBIPreProcess::clearPars(), SBObsVLBIStatistics::collectStatistics(), SBVLBIPreProcess::currentSesChange(), SBProject::delSession(), SBRunManager::makeReportSessionStatistics(), operator<<(), SB_TRF::prepareEccs4Session(), SBVLBIPreProcess::preProcess(), SBVLBIPreProcess::procScenario_2(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), sinex_SiteEccentricityBlock(), sinex_tro_TropDescriptionBlock(), sinex_tro_TropSolutionBlock(), and SBVLBIPreProcess::updateSession().
const QString& SBVLBISesInfo::subKey () const [inline, inherited]
Definition at line 861 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::SubKey.
Referenced by SBVLBISesInfo::operator=(), and SBVLBISesInfo::SBVLBISesInfo().
const SBMJD& SBVLBISesInfo::tFinis () const [inline, inherited]
Definition at line 856 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::TFinis.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISesInfoList::compareItems(), SBVLBIPreProcess::fillSessAttr(), SBRunManager::loadVLBISession_m1(), SBRunManager::makeReportSessionStatistics(), SBVLBISesInfo::operator=(), SBVLBISet::saveSession(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
double SBVLBISesInfo::tInterval () const [inline, inherited]
Definition at line 858 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::TFinis, and SBVLBISesInfo::TStart.
Referenced by SBVLBISesInfoLI::key(), and SBVLBISesInfoLI::text().
const SBMJD& SBVLBISesInfo::tMean () const [inline, inherited]
Definition at line 857 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::TMean.
Referenced by SBVLBIPreProcess::fillSessAttr(), operator<<(), SBVLBISesInfo::operator=(), SBObsVLBIEntry::process(), SBVLBISet::saveSession(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
const SBMJD& SBVLBISesInfo::tStart () const [inline, inherited]
Definition at line 855 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::TStart.
Referenced by SBObsVLBIStatistics::collectStatistics(), SBVLBISesInfoList::compareItems(), SBVLBIPreProcess::fillSessAttr(), SBVLBISesInfoLI::key(), SBVLBISesPreProcLI::key(), SBRunManager::makeReportSessionStatistics(), SBVLBISesInfo::operator=(), SBVLBISet::saveSession(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISessionEditor::SBVLBISessionEditor(), SBVLBIPreProcess::sesTab(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::updateSession(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
const QString& SBVLBISesInfo::userFlag () const [inline, inherited]
Definition at line 864 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::UserFlag.
Referenced by SBVLBISessionEditor::acquireData(), SBVLBIPreProcess::fillSessAttr(), SBVLBISesInfoLI::key(), SBVLBISesInfo::operator=(), SBVLBIPreProcess::saveSession(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfoLI::text(), SBVLBIPreProcess::wAttributes(), and SBVLBISessionEditor::wParameters().
int SBVLBISesInfo::version () const [inline, inherited]
Definition at line 859 of file SbGeoObsVLBI.H'.
References SBVLBISesInfo::Version.
Referenced by SBVLBISet::import(), SBVLBISesInfoLI::key(), operator<<(), SBVLBISesInfo::operator=(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISessionEditor::SBVLBISessionEditor(), and SBVLBISesInfoLI::text().
virtual QDataStream& SBVLBISession::write (QDataStream &s, QCollection::ItemEntry) const [inline, protected, virtual]
Definition at line 964 of file SbGeoObsVLBI.H'.
void SBAttributed::xorAttr (uintA_) [inline, inherited]"Toggles the attribute in the storage'.
Definition at line 251 of file SbGeneral.H'.
References SBAttributed::Attr.
Referenced by SBStaParsEditor::acquireData(), SBVLBIPreProcess::toggleEntryMarkEnable(), and SBVLBIPreProcess::toggleEntryMoveEnable().
Friends And Related Function Documentation
int cmp (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed, returns (-1:0:+1)'.
Definition at line 253 of file SbGeo.H'.
Referenced by SBStochParameterList::compareItems(), and SBMasterFile::compareItems().
bool operator!= (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 238 of file SbGeo.H'.
bool operator< (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 243 of file SbGeo.H'.
QDataStream & operator<< (QDataStream &s, const SBNamed &W) [friend, inherited]"Saves object to the data stream'.
Definition at line 258 of file SbGeo.H'.
QDataStream& operator<< (QDataStream &s, const SBAttributed &A) [friend, inherited]
Definition at line 259 of file SbGeneral.H'.
QDataStream& operator<< (QDataStream &s, const SBVLBISesInfo &S) [friend, inherited]
Definition at line 1188 of file SbGeoObsVLBI.C'.
SBDS_dat& operator<< (SBDS_dat &s, const SBVLBISesInfo &S) [friend, inherited]
Definition at line 1214 of file SbGeoObsVLBI.C'.
SBDS_aux& operator<< (SBDS_aux &s, const SBVLBISesInfo &S) [friend, inherited]
Definition at line 1230 of file SbGeoObsVLBI.C'.
SBDS_dat& operator<< (SBDS_dat &s, const SBVLBISession &S) [friend]
Definition at line 1867 of file SbGeoObsVLBI.C'.
SBDS_aux& operator<< (SBDS_aux &s, SBVLBISession &S) [friend]
Definition at line 1880 of file SbGeoObsVLBI.C'.
SBTS_ngs& operator<< (SBTS_ngs &s, const SBVLBISession &) [friend]
Definition at line 47 of file SbGeoObsVLBI_IO.C'.
SBDS_dbh& operator<< (SBDS_dbh &, const SBVLBISession &) [friend]
SBTS_SINEX& operator<< (SBTS_SINEX &s, SBVLBISession &Session) [friend]
Definition at line 1845 of file SbGeoSINEX.C'.
bool operator== (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 233 of file SbGeo.H'.
bool operator> (const SBNamed &N1, const SBNamed &N2) [friend, inherited]"Compares two instances of SBNamed'.
Definition at line 248 of file SbGeo.H'.
QDataStream & operator>> (QDataStream &s, SBNamed &W) [friend, inherited]"Loads object from the data stream'.
Definition at line 263 of file SbGeo.H'.
QDataStream& operator>> (QDataStream &s, SBAttributed &A) [friend, inherited]
Definition at line 260 of file SbGeneral.H'.
QDataStream& operator>> (QDataStream &s, SBVLBISesInfo &S) [friend, inherited]
Definition at line 1200 of file SbGeoObsVLBI.C'.
SBDS_dat& operator>> (SBDS_dat &s, SBVLBISesInfo &S) [friend, inherited]
Definition at line 1222 of file SbGeoObsVLBI.C'.
SBDS_aux& operator>> (SBDS_aux &s, SBVLBISesInfo &S) [friend, inherited]
Definition at line 1235 of file SbGeoObsVLBI.C'.
SBDS_dat& operator>> (SBDS_dat &s, SBVLBISession &S) [friend]
Definition at line 1873 of file SbGeoObsVLBI.C'.
SBDS_aux& operator>> (SBDS_aux &s, SBVLBISession &S) [friend]
Definition at line 1888 of file SbGeoObsVLBI.C'.
SBTS_ngs & operator>> (SBTS_ngs &s, SBVLBISession &Session) [friend]"Makes data import from a file in NGS format'.
Parameters:
s input stream, NGS format;
Session imported session'.
NGS Format desription'.
The NGS data parsering has been implemented according to the following e-mail (thanx to Konstantin Nurutdinov and Michael D'. Abell):
From glas!nurut@astri.uni.torun.pl Mon May 9 18:32:00 1994
Received: by gluk.apc.org (smail2.5)
        id AA09735; 9 May 94 18:32:13 EET (Mon)
Received: from vega.astri.uni.torun.pl by glas.apc.org with smtp
        (Smail3.1.28.1 #7) id m0q0X6n-0006z8N; Mon, 9 May 94 19:19 +0400
Received: by vega.astri.uni.torun.pl (4.1/SMI-4.1.jv)
        id AA10431; Mon, 9 May 94 17:15:50 +0200
From: nurut@astri.uni.torun.pl (Konstantin Nurutdinov)
Message-Id: <9405091515.AA10431@vega.astri.uni.torun.pl>
Subject: NGS Format for VLBI Data (fwd) - BOLOTINu S.
To: maouas@gluk.apc.org
Date: Mon, 9 May 1994 17:15:49 +0200 (MET DST)
Reply-To: nurut@astri.uni.torun.pl
X-Mailer: ELM [version 2.4 PL22]
Content-Type: text
Content-Length: 9428
Status: R
Forwarded message:
>From mikea@ray.grdl.noaa.gov Mon May 9 16:46:30 1994
Message-Id: <9405091445.AA10221@vega.astri.uni.torun.pl>
From: Mike Abell <mikea@ray.grdl.noaa.gov>
Subject: NGS Format for VLBI Data
To: nurut@astri.uni.torun.pl
Date: Mon, 9 May 94 10:49:04 EDT
Cc: jimr@ray.grdl.noaa.gov (Jim Ray (NOAA))
Mailer: Elm [revision: 72.14]
Konstantin Kh. NURUTDINOV.
Senior Research Worker
Main Astronomical Observatory,
Goloseevo, Kiev-22, 252022
UKRAINE
Dear Dr. Nurutdinov,
   I received your telemail message and attempted to fax the
information you requested, but with no success. Therefore,
I retyped it on my computer (it originally was typed on an
old-fashioned electric typewriter!), and so now I can simply
e-mail it to you. This should be better, actually, since
now we do not have to worry about print quality from the
fax machines.
Sincerely,
Michael D. Abell
NOAA/NOS/OES
Geosciences Laboratory
                    NGS Format for VLBI Data Transfer
                              10/20/83
 1. Header Card - 80 column ASCII descriptor for the data set
 2. Site Cards
       Col 1- 8: Eight character site name
       Col 11-25: X-component of the site position (meters)
       Col 26-40: Y-component of the site position (meters)
       Col 41-55: Z-component of the site position (meters)
       Col 57-60: Axis type (must be AZEL, EQUA, X-YN (for
                   X axis N, or X-YE)
       Col 61-70: Axis offset (meters)
    End of site cards is indicated by a card with $END in Col 1-4
 3. Radio source position cards
       Col 1- 8: Eight character source name
       Col 11-12: Right ascension hours
       Col 14-15: Right ascension minutes
       Col 17-28: Right ascension seconds
       Col 30: Declination sign
       Col 31-32: Declination degrees
       Col 34-35: Declination minutes
       Col 37-48: Declination seconds
    End of source cards is indicated by a card with $END in Col 1-4
 4. Auxiliary parameters
       Col 1-20: Reference frequency (MHz)
       Col 21-30: Group delay ambiguity spacing (nsec)
       Col 32-33: Delay type (GR-group, PH-phase)
       Col 35-36: Delay rate type (GR-group, PH-phase)
    This card must be followed by a card with $END in Col 1-4
 4. Data Cards
    Card #1:
       Col 1- 8: Eight character site name for site 1
       Col 11-18: Eight character site name for site 2
       Col 21-28: Eight character source name for radio source
       Col 30-33: Year of observation (e.g. 1993)
       Col 35-36: Month
       Col 38-39: Day
       Col 41-42: Hour
       Col 44-45: Minute
       Col 47-60: Seconds
       Col 61-70: Run identification code (if desired)
       Col 71-78: Sequence number
       Col 79-80: 01
    Card #2:
       Col 1-20: Observed delay (ns)
       Col 21-30: Formal error for the observed delay (ns)
       Col 31-50: Observed delay rate (ps/sec)
       Col 51-60: Formal error for the observed delay rate (ps/sec)
       Col 61-62: Data quality flag (blank or 0 indicates good data)
       Col 64-65: Delay type (blank if same as in Auxiliary Parameters)
       Col 67-68: Delay rate type (blank if same as in Auxiliary Parameters)
       Col 71-78: Sequence number
       Col 79-80: 02
    Card #3:
       Col 1-10: Correlation coefficient (0-1)
       Col 11-20: Formal error for correlation coefficient
       Col 21-30: Fringe amplitude (J)
       Col 31-40: Formal error for fringe amplitude (J)
       Col 41-60: Total fringe phase (radians)
       Col 61-70: Formal error for total fringe phase (radians)
       Col 71-78: Sequence number
       Col 79-80: 03
    Card #4:
       Col 1-10: System temperature at site 1 (K)
       Col 11-15: Formal error for system temperature at site 1 (K)
       Col 16-25: System temperature at site 2 (K)
       Col 26-30: Formal error for system temperature at site 2 (K)
       Col 31-40: Antenna temperature at site 1 (K)
       Col 41-45: Formal error for antenna temperature at site 1 (K)
       Col 46-55: Antenna temperature at site 2 (K)
       Col 56-60: Formal error for antenna temperature at site 2 (K)
       Col 71-78: Sequence number
       Col 79-80: 04
    Card #5:
       Col 1-10: Cable calibration correction (one-way) for site 1 (ns)
       Col 11-20: Cable calibration correction (one-way) for site 2 (ns)
       Col 21-30: Water vapor radiometer parameter at site 1 (ns)
       Col 31-40: Formal error for water vapor radiometer at site 1 (ns)
       Col 41-50: Water vapor radiometer parameter at site 2 (ns)
       Col 51-60: Formal error for water vapor radiometer at site 2 (ns)
       Col 62 : Water vapor radiometer parameter definition code for
                   site 1 as follows:
                  0 - parameter is zenith path delay
                  1 - parameter is path delay along line-of-sight
       Col 64 : Water vapor radiometer parameter definition code for
                   site 2 (see above)
       Col 71-78: Sequence number
       Col 79-80: 05
    Card #6:
       Col 1-10: Ambient atmospheric temperature at site 1 (deg. C)
       Col 11-20: Ambient atmospheric temperature at site 2 (deg. C)
       Col 21-30: Ambient atmospheric barometric pressure at site 1 (mb)
       Col 31-40: Ambient atmospheric barometric pressure at site 2 (mb)
       Col 41-50: Ambient atmospheric humidity parameter at site 1
       Col 51-60: Ambient atmospheric humidity parameter at site 2
       Col 62 : Humidity parameter definition code for site 1 as follows:
                  0 - humidity parameter is relative humidity (%)
                  1 - humidity parameter is dew point (deg. C)
                  2 - humidity parameter is wet bulb temperature (deg. C)
       Col 64 : Humidity parameter definition code for site 2 (see above)
       Col 71-78: Sequence number
       Col 79-80: 06
    Card #7:
       Col 1-10: Time difference between the reference epoch (card 1) and
                   the start of the observations (e.g. -60.) (seconds)
       Col 11-20: Duration of the observation (seconds)
       Col 21-30: A priori UTC offset at site 1 (if any) (seconds)
       Col 31-50: Observation frequency (MHz) (blank if same as in
                   Auxiliary Parameter)
       Col 51-60: Group delay ambiguity (ns) (blank if same as in Auxiliary
                   Parameter)
       Col 71-78: Sequence number
       Col 79-80: 07
    Card #8:
       Col 1-20: Delay ionosphere correction (ns)
       Col 21-30: Delay ionosphere correction formal error (ns)
       Col 31-50: Delay rate ionosphere correction (ps/s)
       Col 51-60: Delay rate ionosphere correction formal error (ps/s)
       Col 62-63: Ionosphere error flag (0 = ionosphere correction OK)
       Col 71-78: Sequence number
       Col 79-80: 08
    Card #9:
       Col 1-70: Comment text
       Col 71-78: Sequence number
       Col 79-80: 09
    Notes:
 1. All values should include a decimal point or be right-hand justified in
    the indicated fields.
 2. Station coordinates are given in a Greenwich right-hand Cartesian
    coordinate system (e.g., Z-axis toward the CIO pole, X-axis toward
    the Greenwich meridian and Y-axis toward the 90 deg. east meridian).
 3. Source coordinates are given in J2000.0 coordinates using the IAU 1984
    definitions for precession, nutation, aberration, etc.
 4. The reference frequency is defined as the frequency to which the total
    fringe phase observable (Card #4) is referred.
 5. The epoch of the observation is defined as the UTC epoch at which the
    signal arrived at site 1; i.e., the site identified in columns 1-8 of
    card #1.
 6. The sequence number in columns 71-78 of the data cards is to be the same
    number for each data card associated with a given observation. The
    numbers in columns 79-80 serve to sequence the cards within a given
    observation.
 7. The delay is defined as:
                    D = T2 - T1
    where
                   T1 = time of signal arrival at site 1 as measured
                        by the site clock at site 1
                   T2 = time of signal arrival at site 2 as measured
                        by the site clock at site 2
    No calibration corrections (e.g. atmosphere corrections) have been added
    to or subtracted from these values.
 8. The delay rate is defined as the derivative of delay with respect to time
    as measured by the clock at site 1.
 9. The sense of the cable calibration is that an increase means an increase
    in the (one-way) electrical length of the cable carrying the phase
    calibration signal to the receiver box.
10. The barometric pressure should not be corrected to sea level.
11. It is not necessary to include blank data cards for missing data. For
    example, if no meteorological data are available, card #6 may be deleted.
12. Card #1 may not be deleted.
13. Data should be arranged in time order.
14. If the cards are put on tape, the tape should be 9 track with the
    following DCB:
                   DCB = (RECFM=FB,LRECL=80,BLKSIZE=3200)
--
===================================================
Konstantin Kh. NURUTDINOV, Senior Research Worker
Main Astronomical Observatory, Goloseevo,Kiev-22,
252022, Ukraine
E-mail: till 21.05.94 - nurut@astri.uni.torun.pl
        since 21.05.94 - nurut@gao.kiev.ua
                         maouas@gluk.apc.org
***************************************************
Definition at line 62 of file SbGeoObsVLBI_IO.C'.
SBDS_dbh & operator>> (SBDS_dbh &s, SBVLBISession &Session) [friend]"Makes data import from a file in MkIII DBH format'.
Parameters:
s input data stream, DBH format;
Session imported session'.
DBH Format desription'.
The DBH data parser has been implemented according to the following part of 'VORIN' software description (thanx to Leonid Petrov):
19-APR-1996 18:42:35
                I. MARK-III DBH .
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        1.1. MARK-III DBH .
    - MARK-III DBH .
          
   OS-IV Hewlet-Packard.
   , .
    .
    :
________________________________________________________
| HDD1 | DD1 | EDD1 | HD2 | logical record | ED2 |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   6 :
HDD1 ( 4 ) -- .
                                   
                                  I4 (HP-code).
                                  2.
DD1 ( HDD1 ) -- .
                                    I2 (HP-code).
                                    .
EDD1 ( 4 ) -- .
                                    
                                 I4. ,
                                HDD1.
HD2 ( 4 ) -- .
                                    I4.
                               , HDD1, .
                                   2.
logical record ( HD2 ) -- , ,
                               .
ED2 ( 4 ) -- .
                                    I4.
                               , HD2.
         18
 , .
    , -,
, - .
        1.2. MARK-III DBH .
     (
 ) : , .
      ,
. .
    .
       , :
, .
______________________________________________________________________________
| | | | |
| | | | |
|--------|----------|--------------------------|-----------------------------|
| HS | 2 | HS | |
| | | | . |
|--------|----------|--------------------------|-----------------------------|
| Z1 | 4 | ZZ//CHAR(000)//CHAR(000) | |
| | | | . |
|--------|----------|--------------------------|-----------------------------|
| Z2 | 4 | ZZ//CHAR(007)//CHAR(208) | |
| | | | |
| | | | I- . |
|--------|----------|--------------------------|-----------------------------|
| Z3 | 4 | ZZ//() | |
| | | | I- |
| | | INTEGER*2 (HP-code) | II- . |
| | | | |
| | | 0 < < 2000 | DR |
|--------|----------|--------------------------|-----------------------------|
| TE | 2 | TE | |
|--------|----------|--------------------------|-----------------------------|
| TC | 2 | TC | |
|--------|----------|--------------------------|-----------------------------|
| DR | 2 | DR | |
|--------|----------|--------------------------|-----------------------------|
| I2 | 2 | +g | |
|--------|----------|--------------------------|-----------------------------|
| A2 | 2 | 11 | |
|--------|----------|--------------------------|-----------------------------|
| R8 | 8 | CHAR(067)//CHAR(015)// | |
| | | CHAR(148)//CHAR(101)// | |
| | | CHAR(184)//CHAR(171)// | |
| | | CHAR(142)//CHAR(056) | |
|--------|----------|--------------------------|-----------------------------|
| D8 | 8 | CHAR(066)//CHAR(004)// | |
| | | CHAR(178)//CHAR(048)// | |
| | | CHAR(206)//CHAR(056)// | |
| | | CHAR(000)//CHAR(000) | |
|--------|----------|--------------------------|-----------------------------|
| F8 | 8 | CHAR(109)//CHAR(182)// | |
| | | CHAR(109)//CHAR(182) | |
| | | ( 4 | |
| | | ) | |
|--------|----------|--------------------------|-----------------------------|
| J4 | 4 | CHAR(066)//CHAR(058)// | |
| | | CHAR(053)//CHAR(199) | |
|--------|----------|--------------------------|-----------------------------|
| P1 | 0 | | 7 . |
|--------|----------|--------------------------|-----------------------------|
| P2 | 0 | | |
| | | | HS-. |
|--------|----------|--------------------------|-----------------------------|
| P3 | 0 | | TE-. |
|--------|----------|--------------------------|-----------------------------|
| P4 | 0 | | P3-. |
|________|__________|__________________________|_____________________________|
   HS, Z1, Z2, Z3, Z4, Z5, TC, TE, DR, DE -- ,
               12 ( 24 ).
         I2, A2, R8, D8, F8, J4 -- ,
         P1, P2, P3, P4 -- .
        1.2.1. .
        ~~~~~~~~~~~~~~~~~~~~~~~~~
 7 ( ) .
 1 ( kA2) A2.
 2 ( 5I2) 5 , .
 3 ( kA2)
 4 ( kA2) .
 5 ( kA2) .
 6 ( I2) .
 7 ( kA2) .
  8- , -
Z1 .
 : 1- HS-, 2- HS-,
  . .
( DBH, 256
). ,
  .
    1- HS-. : A2,11I2
________________________________________________________________________
| A1 | P1 | P2 | P3 | P4 | P5 | P6 | P7 | P8 | P9 | P10 | P11 |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 -- ( A2 ) -- ( HS )
P2 -- ( I2 ) -- .
P2-P6 -- ( I2 ) -- .
P7 -- ( I2 ) -- .
P8-P11 -- ( I2 ) -- ( ).
    2- HS-. : A2,4I2,3A2,4I2
________________________________________________________________________
| A1 | P1 | P2 | P3 | P4 | A2 | A3 | A4 | P5 | P6 | P7 | P8 |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 -- ( A2 ) -- ( HS )
P1 -- ( I2 ) -- machine type number for this version of
                           the data base handler. (1 for hp 21mx)
P2 -- ( I2 ) -- machine number on which the data base
                           handler was run. ( 1 for gsfc 21mx)
P3 -- ( I2 ) -- instalation number (1 for gsfc)
P4 -- ( I2 ) -- data base handler version number (1996 for DBASE96)
A2-A4 -- ( A2 ) -- 6
P5-P8 -- ( I2 ) -- ( ).
        1.2.2. .
        ~~~~~~~~~~~~~~~~~~~~~~~~~~
    Z1 .
      8 ,
   32 , ,
,
        .
      k ( k=3 ) TC-. TC-
  TC-, l TE-. TE-
TE-, P3-, P4-.
      Z2-
         TC-:
________________________________________________________________________
| A1 | P1 | P2 | P3 | P4 | P5 | P6 | P7 | P8 | P9 | P10 | P11 |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 -- ( A2 ) -- ( TC )
P1 -- ( I2 ) -- TC-. TOC-
P2 -- ( I2 ) -- TE-, TC-.
P3-P11 -- ( I2 ) -- ( ).
         TE-:
________________________________________________________________________
| A1 | P1 | P2 | P3 | P4 | P5 | P6 | P7 | P8 | P9 | P10 | P11 |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 -- ( A2 ) -- ( TC )
P1 -- ( I2 ) -- TE-.
P2 -- ( I2 ) -- I-FILLER ( ).
P3 -- ( I2 ) -- A-FILLER ( ).
P4 -- ( I2 ) -- D-FILLER ( ).
P5 -- ( I2 ) -- R8,
                           TE-.
P6 -- ( I2 ) -- I2,
                           TE-.
P7 -- ( I2 ) -- A2,
                           TE-.
P8 -- ( I2 ) -- J-FILLER ( ).
P9 -- ( I2 ) -- .
P10 -- ( I2 ) -- D8,
                           TE-.
P11 -- ( I2 ) -- J4,
                           TE-.
         P3-:
________________________________________________________________________
| A1_1 | P1_1 | P2_1 | P3_1 | P4_1 | A1_1 | P1_1 | P2_1 | P3_1 | P4_1 | ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  / /
 ~~~~~~~~~~~~~~~\/~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~\/~~~~~~~~~~~~~~~~~
            1- 2-
      P9 TE-.
  .
A8 -- ( A8 ) -- FILLER.
P1 -- ( I2 ) -- 1- .
P2 -- ( I2 ) -- 2- .
P3 -- ( I2 ) -- 3- .
P4 -- ( I2 ) -- ,
                         .
         P4-:
_________________________________________
| A1_1 | A2_1 | A3_1 | A4_1 | ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        / / / /
 ~~~ ~~~ ~~~ ~~~ ~~~ ~~~ ~~~ ~~~
    \/ \/ \/ \/
1- 2- 3- 4- ...
      P9 TE-. : A32
 , , . ,
 FILLER', 32- .
     , MARK-III DBH
:
 1) . A1 P3-.
 2) . A1 P4-.
 3) . P1 P3-.
 4) . P2 P3-.
 5) . P3 P3-.
 6) , .
       P4 P3-.
 7) . FILLER- P3-.
    R8, I2, A2, D8, J4. J4 . D8, F8, R8
    .
 8) TOC-. TC-,
    .
 9) TE-. TE-,
     .
10) .
11) .
        1.2.3. .
        ~~~~~~~~~~~~~~~~~~~~~~
           1- .
, . 2- 3-
  , .
   :
  |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
  | I- ( ) |
  |_______________________________________________________|
                      |~~~~~~~~~~~~~|
                      | Z3- |
                      |_____________|
  |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
  | II- ( 1- ) |
  |_______________________________________________________|
                      |~~~~~~~~~~~~~|
                      | Z3- |
                      |_____________|
  |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
  | III- ( 1- ) |
  |_______________________________________________________|
                      |~~~~~~~~~~~~~|
                      | Z3- |
                      |_____________|
  |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
  | II- ( 2- ) |
  |_______________________________________________________|
                      |~~~~~~~~~~~~~|
                      | Z3- |
                      |_____________|
  |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
  | III- ( 2- ) |
  |_______________________________________________________|
                      |~~~~~~~~~~~~~|
                      | Z3- |
                      |_____________|
       . .
     ,
III- . ,
. , , II- III-
. .
       :
1) II- ; 2)
III- , II- .
    .
        1.2.3.1. .
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DR P1 P2
DE P1 P2 P3 P4 P5 P6 P7 <--------------
  ####
  ####
DE
  ----
ZZ
Warning:
This text is in koi-8 codepage and was written in Russian; unfortunately, I haven't got English version of this document'.
Definition at line 1129 of file SbGeoObsVLBI_IO.C'.
friend class SBVLBISet [friend]
Reimplemented from SBVLBISesInfo'.
Definition at line 958 of file SbGeoObsVLBI.H'.
Member Data Documentation
QDict<SBBaseInfo>* SBVLBISession::BaseByAka [protected]
Definition at line 983 of file SbGeoObsVLBI.H'.
Referenced by baseInfo(), fillDicts(), SBVLBISession(), and ~SBVLBISession().
QIntDict<SBBaseInfo>* SBVLBISession::BaseByIdx [protected]
Definition at line 982 of file SbGeoObsVLBI.H'.
Referenced by baseInfo(), fillDicts(), SBVLBISession(), and ~SBVLBISession().
SBBaseInfoList SBVLBISession::BaseList [protected]
Definition at line 981 of file SbGeoObsVLBI.H'.
Referenced by baseList(), clearRMSs(), dumpUserInfo(), fillDicts(), numBas(), operator<<(), operator>>(), restoreUserInfo(), and SBVLBISession().
QString SBVLBISesInfo::Code [protected, inherited]
Code (from MasterFile)
Definition at line 826 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::code(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setCode().
QString SBVLBISesInfo::CorrelatorName [protected, inherited]
Correlator Name (from MasterFile)
Definition at line 827 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::correlatorName(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setCorrelatorName().
SBMJD SBVLBISesInfo::DateCreat [protected, inherited]
date of MkIII creation (just for curiosity);
Definition at line 817 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::dateCreat(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setDateCreat().
SBHistory SBVLBISession::DBHHistory [protected]
DBH History'.
Definition at line 967 of file SbGeoObsVLBI.H'.
Referenced by dbhHistory(), operator<<(), and operator>>().
double SBVLBISesInfo::DelayRMS2 [protected, inherited]
Definition at line 833 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::addDelayRMS(), SBVLBISesInfo::clearRMSs(), SBVLBISesInfo::delayRMS2(), SBVLBISesInfo::dWRMS(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setDelayRMS2().
double SBVLBISesInfo::DelaySumW2 [protected, inherited]
Definition at line 835 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::addDelayRMS(), SBVLBISesInfo::clearRMSs(), SBVLBISesInfo::delaySumW2(), SBVLBISesInfo::dWRMS(), SBVLBISet::loadSession(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISet::saveSession(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setDelaySumW2().
ObsDelayType SBVLBISesInfo::DelayType [protected, inherited]
type of delay;
Definition at line 828 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::delayType(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setDelayType().
QTextStream* SBVLBISession::Dump [protected]
Definition at line 987 of file SbGeoObsVLBI.H'.
Referenced by dump(), SBVLBISession(), and setDump().
QString SBVLBISesInfo::ExpDescr [protected, inherited]
Experiment description;'.
Definition at line 823 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::expDescr(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setExpDescr().
double SBVLBISession::GrDelayAmbig [protected]
Group delay ambiguity spacing (sec)
Definition at line 986 of file SbGeoObsVLBI.H'.
Referenced by grDelayAmbig(), operator<<(), operator>>(), SBVLBISession(), and setGrDelayAmbig().
ObsImportedFrom SBVLBISesInfo::ImportedFrom [protected, inherited]
origin of the session;
Definition at line 816 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::importedFrom(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setImportedFrom().
SBHistory SBVLBISession::LocalHistory [protected]
local History
Definition at line 971 of file SbGeoObsVLBI.H'.
Referenced by addHistoryLine(), localHistory(), operator<<(), and operator>>().
int SBVLBISesInfo::LocalVersion [protected, inherited]
Definition at line 838 of file SbGeoObsVLBI.H'.
Referenced by addHistoryLine(), SBVLBISesInfo::incVersion(), SBVLBISesInfo::localVersion(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), and SBVLBISesInfo::SBVLBISesInfo().
QString SBNamed::Name [protected, inherited]
Definition at line 206 of file SbGeo.H'.
Referenced by SBVLBISesInfo::fileName(), SBNamed::name(), operator<<(), SBNamed::operator=(), SBStation::operator=(), SBSite::operator=(), SBOLoadCarrier::operator==(), operator>>(), SBStochParameter::report(), SBNamed::SBNamed(), SBNamed::setName(), SBSite::updateSite(), and SBStation::updateStation().
QString SBVLBISesInfo::NetworkID [protected, inherited]
Network ID (a key);'.
Definition at line 822 of file SbGeoObsVLBI.H'.
Referenced by dumpUserInfo(), SBVLBISesInfo::networkID(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setNetworkID().
int SBVLBISesInfo::NumBas [protected, inherited]
Definition at line 830 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::numBas(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), and SBVLBISesInfo::SBVLBISesInfo().
int SBVLBISesInfo::NumObs [protected, inherited]
Definition at line 832 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::numObs(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), and SBVLBISesInfo::SBVLBISesInfo().
int SBVLBISesInfo::NumSou [protected, inherited]
Definition at line 831 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::numSou(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), and SBVLBISesInfo::SBVLBISesInfo().
int SBVLBISesInfo::NumSta [protected, inherited]
Definition at line 829 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::numSta(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), and SBVLBISesInfo::SBVLBISesInfo().
QString SBVLBISesInfo::OfficialName [protected, inherited]
Official Name (from MasterFile)
Definition at line 825 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::officialName(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setOfficialName().
double SBVLBISesInfo::RateRMS2 [protected, inherited]
Definition at line 834 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::addRateRMS(), SBVLBISesInfo::clearRMSs(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::rateRMS2(), SBVLBISesInfo::rWRMS(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setRateRMS2().
double SBVLBISesInfo::RateSumW2 [protected, inherited]
Definition at line 836 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::addRateRMS(), SBVLBISesInfo::clearRMSs(), SBVLBISet::loadSession(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::rateSumW2(), SBVLBISesInfo::rWRMS(), SBVLBISet::saveSession(), SBVLBISesInfo::SBVLBISesInfo(), and SBVLBISesInfo::setRateSumW2().
double SBVLBISession::RefFreq [protected]
Reference frequency (MHz)
Definition at line 985 of file SbGeoObsVLBI.H'.
Referenced by operator<<(), operator>>(), refFreq(), SBVLBISession(), and setRefFreq().
QDict<SBSourceInfo>* SBVLBISession::SourceByAka [protected]
Definition at line 979 of file SbGeoObsVLBI.H'.
Referenced by fillDicts(), SBVLBISession(), sourceInfo(), and ~SBVLBISession().
QIntDict<SBSourceInfo>* SBVLBISession::SourceByIdx [protected]
Definition at line 978 of file SbGeoObsVLBI.H'.
Referenced by fillDicts(), SBVLBISession(), sourceInfo(), and ~SBVLBISession().
SBSourceInfoList SBVLBISession::SourceList [protected]
Definition at line 977 of file SbGeoObsVLBI.H'.
Referenced by clearRMSs(), dumpUserInfo(), fillDicts(), numSou(), operator<<(), operator>>(), parseObsDumpString(), restoreUserInfo(), SBVLBISession(), and sourceList().
QDict<SBStationInfo>* SBVLBISession::StationByAka [protected]
Definition at line 975 of file SbGeoObsVLBI.H'.
Referenced by fillDicts(), SBVLBISession(), stationInfo(), and ~SBVLBISession().
QIntDict<SBStationInfo>* SBVLBISession::StationByIdx [protected]
Definition at line 974 of file SbGeoObsVLBI.H'.
Referenced by fillDicts(), SBVLBISession(), stationInfo(), and ~SBVLBISession().
SBStationInfoList SBVLBISession::StationList [protected]
Definition at line 973 of file SbGeoObsVLBI.H'.
Referenced by checkArtMeteo(), checkAttributres(), clearRMSs(), dumpUserInfo(), fillDicts(), numSta(), operator<<(), operator>>(), parseObsDumpString(), restoreUserInfo(), SBVLBISession(), and stationList().
QString SBVLBISesInfo::SubKey [protected, inherited]
aux key;
Definition at line 821 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::checkPath(), SBVLBISesInfo::fileName(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfo::setSubKey(), and SBVLBISesInfo::subKey().
SBMJD SBVLBISesInfo::TFinis [protected, inherited]
last epoch of the observations;
Definition at line 819 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::calcTMean(), calcTMean(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfo::setTFinis(), SBVLBISesInfo::tFinis(), and SBVLBISesInfo::tInterval().
SBMJD SBVLBISesInfo::TMean [protected, inherited]
mean epoch of the observations;
Definition at line 820 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::calcTMean(), calcTMean(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfo::setTMean(), and SBVLBISesInfo::tMean().
SBMJD SBVLBISesInfo::TStart [protected, inherited]
first epoch of the observations;
Definition at line 818 of file SbGeoObsVLBI.H'.
Referenced by SBVLBISesInfo::calcTMean(), calcTMean(), SBVLBISesInfo::checkPath(), SBVLBISesInfo::fileName(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfo::setTStart(), SBVLBISesInfo::tInterval(), and SBVLBISesInfo::tStart().
QString SBVLBISesInfo::UserFlag [protected, inherited]
Flag assigned by user'.
Definition at line 824 of file SbGeoObsVLBI.H'.
Referenced by dumpUserInfo(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfo::setUserFlag(), and SBVLBISesInfo::userFlag().
int SBVLBISesInfo::Version [protected, inherited]
version;
Definition at line 837 of file SbGeoObsVLBI.H'.
Referenced by dumpUserInfo(), SBVLBISesInfo::fileName(), operator<<(), SBVLBISesInfo::operator=(), operator>>(), SBVLBISesInfo::SBVLBISesInfo(), SBVLBISesInfo::setVersion(), and SBVLBISesInfo::version().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.