.TH "SBVLBIObsLI" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBVLBIObsLI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbIObsVLBI\&.H>\fP
.PP
Inherits \fBQListViewItem\fP'\&.
.PP
Inherited by \fBSBVLBIObsPPLI\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBVLBIObsLI\fP (\fBQListView\fP *parent, \fBSBVLBISession\fP *Sess_, \fBSBObsVLBIEntry\fP *Obs_)"
.br
.ti -1c
.RI "\fBSBObsVLBIEntry\fP * \fBobs\fP ()"
.br
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int) const "
.br
.ti -1c
.RI "virtual QString \fBkey\fP (int, bool) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSBObsVLBIEntry\fP * \fBObs\fP"
.br
.ti -1c
.RI "\fBSBVLBISession\fP * \fBSess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file SbIObsVLBI\&.H'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SBVLBIObsLI::SBVLBIObsLI (\fBQListView\fP *parent, \fBSBVLBISession\fP *Sess_, \fBSBObsVLBIEntry\fP *Obs_)\fC [inline]\fP"
.PP
Definition at line 113 of file SbIObsVLBI\&.H'\&.
.PP
References Obs, and Sess\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBVLBIObsLI::ClassName () const\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBSBVLBIObsPPLI\fP'\&.
.PP
Definition at line 116 of file SbIObsVLBI\&.H'\&.
.SS "QString SBVLBIObsLI::key (intcol, bool) const\fC [virtual]\fP"
.PP
Reimplemented in \fBSBVLBIObsPPLI\fP'\&.
.PP
Definition at line 415 of file SbIObsVLBI\&.C'\&.
.PP
References SBObsVLBIEntry::ambiguityFactor(), SBObsVLBIEntry::BadCable1, SBObsVLBIEntry::BadCable2, SBObsVLBIEntry::BadMeteo1, SBObsVLBIEntry::BadMeteo2, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBObsVLBIEntry::delayErr(), SBObsVLBIEntry::delayRes(), SBObsVLBIEntry::dUFlag(), SBObservation::idx(), SBObsVLBIEntry::ionErrorFlag(), SBAttributed::isAttr(), SBObservation::mjd(), SBObservation::notValid, Obs, SBObsVLBIEntry::qualCode(), SBObsVLBIEntry::rateErr(), SBObsVLBIEntry::rateRes(), SBObsVLBIEntry::rUFlag(), Sess, SBObsVLBIEntry::sourceIdx(), SBVLBISession::sourceInfo(), SBObsVLBIEntry::station_1Idx(), SBObsVLBIEntry::station_2Idx(), SBVLBISession::stationInfo(), and TmpString\&.
.SS "\fBSBObsVLBIEntry\fP* SBVLBIObsLI::obs ()\fC [inline]\fP"
.PP
Definition at line 115 of file SbIObsVLBI\&.H'\&.
.PP
References Obs\&.
.SS "QString SBVLBIObsLI::text (intcol) const\fC [virtual]\fP"
.PP
Reimplemented in \fBSBVLBIObsPPLI\fP'\&.
.PP
Definition at line 339 of file SbIObsVLBI\&.C'\&.
.PP
References SBObsVLBIEntry::ambiguityFactor(), SBObsVLBIEntry::BadCable1, SBObsVLBIEntry::BadCable2, SBObsVLBIEntry::BadMeteo1, SBObsVLBIEntry::BadMeteo2, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBDelay::CLight, SBObsVLBIEntry::delayErr(), SBObsVLBIEntry::delayRes(), SBObsVLBIEntry::dUFlag(), SBMJD::F_HHMMSS, SBObservation::idx(), SBObsVLBIEntry::ionErrorFlag(), SBAttributed::isAttr(), SBObservation::notValid, Obs, SBObsVLBIEntry::qualCode(), SBObsVLBIEntry::rateErr(), SBObsVLBIEntry::rateRes(), SBObsVLBIEntry::rUFlag(), Sess, SetUp, SBObsVLBIEntry::sourceIdx(), SBVLBISession::sourceInfo(), SBObsVLBIEntry::station_1Idx(), SBObsVLBIEntry::station_2Idx(), SBVLBISession::stationInfo(), TmpString, SBMJD::toString(), SBSetUp::U_INCH, SBSetUp::U_METER, SBSetUp::U_SEC, and SBSetUp::units()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSBObsVLBIEntry\fP* \fBSBVLBIObsLI::Obs\fP\fC [protected]\fP"
.PP
Definition at line 110 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBVLBIObsPPLI::key(), key(), obs(), SBVLBIObsPPLI::paintCell(), SBVLBIObsLI(), SBVLBIObsPPLI::text(), and text()\&.
.SS "\fBSBVLBISession\fP* \fBSBVLBIObsLI::Sess\fP\fC [protected]\fP"
.PP
Definition at line 111 of file SbIObsVLBI\&.H'\&.
.PP
Referenced by SBVLBIObsPPLI::key(), key(), SBVLBIObsPPLI::paintCell(), SBVLBIObsLI(), SBVLBIObsPPLI::text(), and text()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
