SBVLBIObsPPLI
NAME
SBVLBIObsPPLI -
SYNOPSIS
#include <SbIPreProcessing.H>
Inherits SBVLBIObsLI'.
Public Member Functions
SBVLBIObsPPLI (QListView *parent_, SBVLBISession *Sess_, SBObsVLBIEntry *Obs_)
virtual QString ClassName () const
virtual QString text (int) const
virtual QString key (int, bool) const
virtual void paintCell (QPainter *, const QColorGroup &, int, int, int)
SBObsVLBIEntry * obs ()
Protected Attributes
SBObsVLBIEntry * Obs
SBVLBISession * Sess
Detailed Description
Definition at line 47 of file SbIPreProcessing.H'.
Constructor & Destructor Documentation
SBVLBIObsPPLI::SBVLBIObsPPLI (QListView *parent_, SBVLBISession *Sess_, SBObsVLBIEntry *Obs_) [inline]
Definition at line 50 of file SbIPreProcessing.H'.
Member Function Documentation
virtual QString SBVLBIObsPPLI::ClassName () const [inline, virtual]
Reimplemented from SBVLBIObsLI'.
Definition at line 52 of file SbIPreProcessing.H'.
QString SBVLBIObsPPLI::key (intcol, bool) const [virtual]
Reimplemented from SBVLBIObsLI'.
Definition at line 117 of file SbIPreProcessing.C'.
References SBObsVLBIEntry::ambiguityFactor(), SBObsVLBIEntry::BadCable1, SBObsVLBIEntry::BadCable2, SBObsVLBIEntry::BadMeteo1, SBObsVLBIEntry::BadMeteo2, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBObsVLBIEntry::delayErr(), SBObsVLBIEntry::delayRes(), SBObsVLBIEntry::dUFlag(), SBObservation::idx(), SBObsVLBIEntry::ionErrorFlag(), SBAttributed::isAttr(), SBObservation::mjd(), SBObservation::notValid, SBVLBIObsLI::Obs, SBObsVLBIEntry::qualCode(), SBObsVLBIEntry::rUFlag(), SBVLBIObsLI::Sess, SBObsVLBIEntry::sourceIdx(), SBVLBISession::sourceInfo(), SBObsVLBIEntry::station_1Idx(), SBObsVLBIEntry::station_2Idx(), SBVLBISession::stationInfo(), and TmpString.
SBObsVLBIEntry* SBVLBIObsLI::obs () [inline, inherited]
Definition at line 115 of file SbIObsVLBI.H'.
References SBVLBIObsLI::Obs.
void SBVLBIObsPPLI::paintCell (QPainter *p, const QColorGroup &cg, intcolumn, intwidth, intalign) [virtual]
Definition at line 169 of file SbIPreProcessing.C'.
References SBObsVLBIEntry::delayRes(), SBObsVLBIEntry::dUFlag(), SBAttributed::isAttr(), SBObservation::notValid, SBVLBIObsLI::Obs, and SBVLBIObsLI::Sess.
QString SBVLBIObsPPLI::text (intcol) const [virtual]
Reimplemented from SBVLBIObsLI'.
Definition at line 60 of file SbIPreProcessing.C'.
References SBObsVLBIEntry::ambiguityFactor(), SBObsVLBIEntry::BadCable1, SBObsVLBIEntry::BadCable2, SBObsVLBIEntry::BadMeteo1, SBObsVLBIEntry::BadMeteo2, SBObsVLBIEntry::breakClock1, SBObsVLBIEntry::breakClock2, SBObsVLBIEntry::delayErr(), SBObsVLBIEntry::delayRes(), SBObsVLBIEntry::dUFlag(), SBMJD::F_HHMMSS, SBObservation::idx(), SBObsVLBIEntry::ionErrorFlag(), SBAttributed::isAttr(), SBObservation::notValid, SBVLBIObsLI::Obs, SBObsVLBIEntry::qualCode(), SBObsVLBIEntry::rUFlag(), SBSetUp::scale(), SBVLBIObsLI::Sess, SetUp, SBObsVLBIEntry::sourceIdx(), SBVLBISession::sourceInfo(), SBObsVLBIEntry::station_1Idx(), SBObsVLBIEntry::station_2Idx(), SBVLBISession::stationInfo(), TmpString, and SBMJD::toString().
Member Data Documentation
SBObsVLBIEntry* SBVLBIObsLI::Obs [protected, inherited]
Definition at line 110 of file SbIObsVLBI.H'.
Referenced by key(), SBVLBIObsLI::key(), SBVLBIObsLI::obs(), paintCell(), SBVLBIObsLI::SBVLBIObsLI(), text(), and SBVLBIObsLI::text().
SBVLBISession* SBVLBIObsLI::Sess [protected, inherited]
Definition at line 111 of file SbIObsVLBI.H'.
Referenced by key(), SBVLBIObsLI::key(), paintCell(), SBVLBIObsLI::SBVLBIObsLI(), text(), and SBVLBIObsLI::text().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.