SBWMf_NMF
NAME
SBWMf_NMF -
SYNOPSIS
#include <SbGeoRefraction.H>
Inherits SBMappingFunc'.
Public Member Functions
virtual QString ClassName () const
virtual double operator() (double, float, float, float, const SBStation *, const SBMJD &)
Private Member Functions
double linterpol (double, double, double, double, double)
Static Private Attributes
static const double ModelArg [5]
static const double ModelA_avg [5]
static const double ModelB_avg [5]
static const double ModelC_avg [5]
Detailed Description
NMF Wet mapping Function by Niell, 1996'.
Definition at line 317 of file SbGeoRefraction.H'.
Member Function Documentation
virtual QString SBWMf_NMF::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBMappingFunc'.
Definition at line 327 of file SbGeoRefraction.H'.
double SBWMf_NMF::linterpol (doublex1, doublex2, doubley1, doubley2, doublex) [private]
Definition at line 480 of file SbGeoRefraction.C'.
Referenced by operator()().
double SBWMf_NMF::operator() (doubleE, float, float, float, const SBStation *Station, const SBMJD &) [virtual]"Calcs wet mapping function'.
Parameters:
E is a source elevation angle, rad;
T is an atmospheric temperature, C;
P is an atmospheric pressure, mbar;
RH is an atmospheric relative humidity, %;
Station is a pointer to the SBStation;
MJD is a epoch of observation'.
Returns:
wet mapping function value'.
A'.E'. Niell, 'Global mapping functions for the atmosphere delay at radio wavelengths', J'.G'.R'. 101, b2, 3227-3246, 1996 (Equations 4 and 5 corrected)
available on <http://web.haystack.mit.edu/Geodesy/GeodesyIndex.html>, thanks to Arthur
Reimplemented from SBMappingFunc'.
Definition at line 496 of file SbGeoRefraction.C'.
References SBStation::latitude(), linterpol(), ModelA_avg, ModelArg, ModelB_avg, and ModelC_avg.
Member Data Documentation
const double SBWMf_NMF::ModelA_avg [static, private]"Initial value:
{ 5.8021897e-4, 5.6794847e-4, 5.8118019e-4, 5.9727542e-4, 6.1641693e-4}
Definition at line 321 of file SbGeoRefraction.H'.
Referenced by operator()().
const double SBWMf_NMF::ModelArg [static, private]"Initial value:
{ 15.0*DEG2RAD, 30.0*DEG2RAD, 45.0*DEG2RAD, 60.0*DEG2RAD, 75.0*DEG2RAD}
Definition at line 320 of file SbGeoRefraction.H'.
Referenced by operator()().
const double SBWMf_NMF::ModelB_avg [static, private]"Initial value:
{ 1.4275268e-3, 1.5138625e-3, 1.4572752e-3, 1.5007428e-3, 1.7599082e-3}
Definition at line 322 of file SbGeoRefraction.H'.
Referenced by operator()().
const double SBWMf_NMF::ModelC_avg [static, private]"Initial value:
{ 4.3472961e-2, 4.6729510e-2, 4.3908931e-2, 4.4626982e-2, 5.4736038e-2}
Definition at line 323 of file SbGeoRefraction.H'.
Referenced by operator()().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.