.TH "SBWMf_NMF" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBWMf_NMF \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefraction\&.H>\fP
.PP
Inherits \fBSBMappingFunc\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual double \fBoperator()\fP (double, float, float, float, const \fBSBStation\fP *, const \fBSBMJD\fP &)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "double \fBlinterpol\fP (double, double, double, double, double)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static const double \fBModelArg\fP [5]"
.br
.ti -1c
.RI "static const double \fBModelA_avg\fP [5]"
.br
.ti -1c
.RI "static const double \fBModelB_avg\fP [5]"
.br
.ti -1c
.RI "static const double \fBModelC_avg\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
NMF Wet mapping Function by Niell, 1996'\&. 
.PP
Definition at line 317 of file SbGeoRefraction\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBWMf_NMF::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info) 
.PP
Reimplemented from \fBSBMappingFunc\fP'\&.
.PP
Definition at line 327 of file SbGeoRefraction\&.H'\&.
.SS "double SBWMf_NMF::linterpol (doublex1, doublex2, doubley1, doubley2, doublex)\fC [private]\fP"
.PP
Definition at line 480 of file SbGeoRefraction\&.C'\&.
.PP
Referenced by operator()()\&.
.SS "double SBWMf_NMF::operator() (doubleE, float, float, float, const \fBSBStation\fP *Station, const \fBSBMJD\fP &)\fC [virtual]\fP"Calcs wet mapping function'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIE\fP is a source elevation angle, rad; 
.br
\fIT\fP is an atmospheric temperature, C; 
.br
\fIP\fP is an atmospheric pressure, mbar; 
.br
\fIRH\fP is an atmospheric relative humidity, %; 
.br
\fIStation\fP is a pointer to the \fBSBStation\fP; 
.br
\fIMJD\fP is a epoch of observation'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
wet mapping function value'\&. 
.RE
.PP
A'\&.E'\&. Niell, 'Global mapping functions for the atmosphere delay at radio wavelengths', J'\&.G'\&.R'\&. 101, b2, 3227-3246, 1996 (Equations 4 and 5 corrected)
.PP
available on <http://web.haystack.mit.edu/Geodesy/GeodesyIndex.html>, thanks to Arthur
.PP
Reimplemented from \fBSBMappingFunc\fP'\&.
.PP
Definition at line 496 of file SbGeoRefraction\&.C'\&.
.PP
References SBStation::latitude(), linterpol(), ModelA_avg, ModelArg, ModelB_avg, and ModelC_avg\&.
.SH "Member Data Documentation"
.PP 
.SS "const double \fBSBWMf_NMF::ModelA_avg\fP\fC [static, private]\fP"\fBInitial value:\fP
.PP
.nf

{ 5\&.8021897e-4, 5\&.6794847e-4, 5\&.8118019e-4, 5\&.9727542e-4, 6\&.1641693e-4}
.fi
.PP
Definition at line 321 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()()\&.
.SS "const double \fBSBWMf_NMF::ModelArg\fP\fC [static, private]\fP"\fBInitial value:\fP
.PP
.nf

{ 15\&.0*DEG2RAD, 30\&.0*DEG2RAD, 45\&.0*DEG2RAD, 60\&.0*DEG2RAD, 75\&.0*DEG2RAD}
.fi
.PP
Definition at line 320 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()()\&.
.SS "const double \fBSBWMf_NMF::ModelB_avg\fP\fC [static, private]\fP"\fBInitial value:\fP
.PP
.nf

{ 1\&.4275268e-3, 1\&.5138625e-3, 1\&.4572752e-3, 1\&.5007428e-3, 1\&.7599082e-3}
.fi
.PP
Definition at line 322 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()()\&.
.SS "const double \fBSBWMf_NMF::ModelC_avg\fP\fC [static, private]\fP"\fBInitial value:\fP
.PP
.nf

{ 4\&.3472961e-2, 4\&.6729510e-2, 4\&.3908931e-2, 4\&.4626982e-2, 5\&.4736038e-2}
.fi
.PP
Definition at line 323 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by operator()()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
