.TH "SBWZD_Saastamoinen" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBWZD_Saastamoinen \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SbGeoRefraction\&.H>\fP
.PP
Inherits \fBSBZenithDelay\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual QString \fBClassName\fP () const "
.br
.ti -1c
.RI "virtual double \fBoperator()\fP (float, float, float, const \fBSBStation\fP *)"
.br
.ti -1c
.RI "double \fBk1\fP () const "
.br
.ti -1c
.RI "double \fBk2\fP () const "
.br
.ti -1c
.RI "double \fBk3\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBvapourPress\fP (float, float)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const double \fBK1\fP = 77\&.604"
.br
.RI "\fIrefraction coeff'\&. #1, K/mbar; Thayer, 1974 \fP"
.ti -1c
.RI "static const double \fBK2\fP = 64\&.79"
.br
.RI "\fIrefraction coeff'\&. #2, K/mbar; Thayer, 1974 \fP"
.ti -1c
.RI "static const double \fBK3\fP = 3\&.776e+5"
.br
.RI "\fIrefraction coeff'\&. #3, K/mbar^2; Thayer, 1974 \fP"
.in -1c
.SH "Detailed Description"
.PP 
Wet Zenith delay model by Saastamoinen, 1973'\&. 
.PP
Definition at line 163 of file SbGeoRefraction\&.H'\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QString SBWZD_Saastamoinen::ClassName () const\fC [inline, virtual]\fP"Refers to a class name (debug info) 
.PP
Reimplemented from \fBSBZenithDelay\fP'\&.
.PP
Definition at line 167 of file SbGeoRefraction\&.H'\&.
.SS "double SBZenithDelay::k1 () const\fC [inline, inherited]\fP"Returns refraction coefficient k1, K/mbar'\&. 
.PP
Definition at line 55 of file SbGeoRefraction\&.H'\&.
.PP
References SBZenithDelay::K1\&.
.PP
Referenced by SBHZD_Hopfield::operator()(), and SBWZD_Hopfield::operator()()\&.
.SS "double SBZenithDelay::k2 () const\fC [inline, inherited]\fP"Returns refraction coefficient k2, K/mbar'\&. 
.PP
Definition at line 57 of file SbGeoRefraction\&.H'\&.
.PP
References SBZenithDelay::K2\&.
.PP
Referenced by SBWZD_Hopfield::operator()()\&.
.SS "double SBZenithDelay::k3 () const\fC [inline, inherited]\fP"Returns refraction coefficient k3, K/mbar^2'\&. 
.PP
Definition at line 59 of file SbGeoRefraction\&.H'\&.
.PP
References SBZenithDelay::K3\&.
.PP
Referenced by SBWZD_Hopfield::operator()()\&.
.SS "double SBWZD_Saastamoinen::operator() (floatT, float, floatRH, const \fBSBStation\fP *)\fC [virtual]\fP"Calcs wet zenith delay'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIT\fP is an atmospheric temperature, C; 
.br
\fIP\fP is an atmospheric pressure, mbar; 
.br
\fIRH\fP is an atmospheric relative humidity, %; 
.br
\fIStation\fP is a pointer to the \fBSBStation\fP'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
wet zenith delay, m'\&. 
.RE
.PP

.PP
Reimplemented from \fBSBZenithDelay\fP'\&.
.PP
Definition at line 158 of file SbGeoRefraction\&.C'\&.
.PP
References SBZenithDelay::vapourPress()\&.
.SS "double SBZenithDelay::vapourPress (floatT, floatRH)\fC [static, inherited]\fP"Calcs partial water vapour pressure, mbar'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIT\fP is a dry temperature, C; 
.br
\fIRH\fP is a relative humidity, %'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
partial water vapour pressure, mbar'\&. 
.RE
.PP
J'\&.A'\&.Estefan, O'\&.J'\&.Sovers, 'A Comparative Survey of Current and Proposed Tropospheric
 Refraction-Delay Models for DSN Radio Metric Data Calibration', JPL Publication 94-24, October 1994'\&. Page 14, Eq'\&. (16): ''\&.'\&.'\&.a variation of the simple model of Bean and Dutton [1966]:'
.PP
Definition at line 55 of file SbGeoRefraction\&.C'\&.
.PP
Referenced by SBWZD_Hopfield::operator()(), operator()(), SBHMf_CfA2p2::operator()(), SBHMf_Ifadis::operator()(), SBWMf_Ifadis::operator()(), and SBRefraction::operator()()\&.
.SH "Member Data Documentation"
.PP 
.SS "const double \fBSBZenithDelay::K1\fP = 77\&.604\fC [static, protected, inherited]\fP"
.PP
refraction coeff'\&. #1, K/mbar; Thayer, 1974 
.PP
Definition at line 44 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by SBZenithDelay::k1()\&.
.SS "const double \fBSBZenithDelay::K2\fP = 64\&.79\fC [static, protected, inherited]\fP"
.PP
refraction coeff'\&. #2, K/mbar; Thayer, 1974 
.PP
Definition at line 45 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by SBZenithDelay::k2()\&.
.SS "const double \fBSBZenithDelay::K3\fP = 3\&.776e+5\fC [static, protected, inherited]\fP"
.PP
refraction coeff'\&. #3, K/mbar^2; Thayer, 1974 
.PP
Definition at line 46 of file SbGeoRefraction\&.H'\&.
.PP
Referenced by SBZenithDelay::k3()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
