SBWZD_Saastamoinen
NAME
SBWZD_Saastamoinen -
SYNOPSIS
#include <SbGeoRefraction.H>
Inherits SBZenithDelay'.
Public Member Functions
virtual QString ClassName () const
virtual double operator() (float, float, float, const SBStation *)
double k1 () const
double k2 () const
double k3 () const
Static Public Member Functions
static double vapourPress (float, float)
Static Protected Attributes
static const double K1 = 77.604
refraction coeff'. #1, K/mbar; Thayer, 1974
static const double K2 = 64.79
refraction coeff'. #2, K/mbar; Thayer, 1974
static const double K3 = 3.776e+5
refraction coeff'. #3, K/mbar^2; Thayer, 1974
Detailed Description
Wet Zenith delay model by Saastamoinen, 1973'.
Definition at line 163 of file SbGeoRefraction.H'.
Member Function Documentation
virtual QString SBWZD_Saastamoinen::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented from SBZenithDelay'.
Definition at line 167 of file SbGeoRefraction.H'.
double SBZenithDelay::k1 () const [inline, inherited]"Returns refraction coefficient k1, K/mbar'.
Definition at line 55 of file SbGeoRefraction.H'.
References SBZenithDelay::K1.
Referenced by SBHZD_Hopfield::operator()(), and SBWZD_Hopfield::operator()().
double SBZenithDelay::k2 () const [inline, inherited]"Returns refraction coefficient k2, K/mbar'.
Definition at line 57 of file SbGeoRefraction.H'.
References SBZenithDelay::K2.
Referenced by SBWZD_Hopfield::operator()().
double SBZenithDelay::k3 () const [inline, inherited]"Returns refraction coefficient k3, K/mbar^2'.
Definition at line 59 of file SbGeoRefraction.H'.
References SBZenithDelay::K3.
Referenced by SBWZD_Hopfield::operator()().
double SBWZD_Saastamoinen::operator() (floatT, float, floatRH, const SBStation *) [virtual]"Calcs wet zenith delay'.
Parameters:
T is an atmospheric temperature, C;
P is an atmospheric pressure, mbar;
RH is an atmospheric relative humidity, %;
Station is a pointer to the SBStation'.
Returns:
wet zenith delay, m'.
Reimplemented from SBZenithDelay'.
Definition at line 158 of file SbGeoRefraction.C'.
References SBZenithDelay::vapourPress().
double SBZenithDelay::vapourPress (floatT, floatRH) [static, inherited]"Calcs partial water vapour pressure, mbar'.
Parameters:
T is a dry temperature, C;
RH is a relative humidity, %'.
Returns:
partial water vapour pressure, mbar'.
J'.A'.Estefan, O'.J'.Sovers, 'A Comparative Survey of Current and Proposed Tropospheric
 Refraction-Delay Models for DSN Radio Metric Data Calibration', JPL Publication 94-24, October 1994'. Page 14, Eq'. (16): ''.'.'.a variation of the simple model of Bean and Dutton [1966]:'
Definition at line 55 of file SbGeoRefraction.C'.
Referenced by SBWZD_Hopfield::operator()(), operator()(), SBHMf_CfA2p2::operator()(), SBHMf_Ifadis::operator()(), SBWMf_Ifadis::operator()(), and SBRefraction::operator()().
Member Data Documentation
const double SBZenithDelay::K1 = 77.604 [static, protected, inherited]
refraction coeff'. #1, K/mbar; Thayer, 1974
Definition at line 44 of file SbGeoRefraction.H'.
Referenced by SBZenithDelay::k1().
const double SBZenithDelay::K2 = 64.79 [static, protected, inherited]
refraction coeff'. #2, K/mbar; Thayer, 1974
Definition at line 45 of file SbGeoRefraction.H'.
Referenced by SBZenithDelay::k2().
const double SBZenithDelay::K3 = 3.776e+5 [static, protected, inherited]
refraction coeff'. #3, K/mbar^2; Thayer, 1974
Definition at line 46 of file SbGeoRefraction.H'.
Referenced by SBZenithDelay::k3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.