SBZenithDelay
NAME
SBZenithDelay -
SYNOPSIS
#include <SbGeoRefraction.H>
Inherited by SBHZD_Hopfield, SBHZD_Saastamoinen, SBWZD_Hopfield, and SBWZD_Saastamoinen'.
Public Member Functions
SBZenithDelay ()
virtual ~SBZenithDelay ()
virtual QString ClassName () const
double k1 () const
double k2 () const
double k3 () const
virtual double operator() (float, float, float, const SBStation *)
Static Public Member Functions
static double vapourPress (float, float)
Static Protected Attributes
static const double K1 = 77.604
refraction coeff'. #1, K/mbar; Thayer, 1974
static const double K2 = 64.79
refraction coeff'. #2, K/mbar; Thayer, 1974
static const double K3 = 3.776e+5
refraction coeff'. #3, K/mbar^2; Thayer, 1974
Detailed Description
Zenith delay, general interface'. This is a common class for all classes deal with zenith (hydrostatic (aka 'dry') and wet) delay'. However, this class can be used to describe an absence of the zenith delay model(s)'.
Definition at line 41 of file SbGeoRefraction.H'.
Constructor & Destructor Documentation
SBZenithDelay::SBZenithDelay () [inline]"A constructor'.
Definition at line 49 of file SbGeoRefraction.H'.
virtual SBZenithDelay::~SBZenithDelay () [inline, virtual]"A destructor'.
Definition at line 51 of file SbGeoRefraction.H'.
Member Function Documentation
virtual QString SBZenithDelay::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented in SBWZD_Saastamoinen, SBWZD_Hopfield, SBHZD_Saastamoinen, and SBHZD_Hopfield'.
Definition at line 53 of file SbGeoRefraction.H'.
Referenced by SBRefraction::operator()().
double SBZenithDelay::k1 () const [inline]"Returns refraction coefficient k1, K/mbar'.
Definition at line 55 of file SbGeoRefraction.H'.
References K1.
Referenced by SBHZD_Hopfield::operator()(), and SBWZD_Hopfield::operator()().
double SBZenithDelay::k2 () const [inline]"Returns refraction coefficient k2, K/mbar'.
Definition at line 57 of file SbGeoRefraction.H'.
References K2.
Referenced by SBWZD_Hopfield::operator()().
double SBZenithDelay::k3 () const [inline]"Returns refraction coefficient k3, K/mbar^2'.
Definition at line 59 of file SbGeoRefraction.H'.
References K3.
Referenced by SBWZD_Hopfield::operator()().
virtual double SBZenithDelay::operator() (float, float, float, const SBStation *) [inline, virtual]"Calcs hydrostatic zenith delay'.
Parameters:
T is an atmospheric temperature, C;
P is an atmospheric pressure, mbar;
RH is an atmospheric relative humidity, %;
Station is a pointer to the SBStation'.
Returns:
0'.0 meters (dumb class)'.
Reimplemented in SBWZD_Saastamoinen, SBWZD_Hopfield, SBHZD_Saastamoinen, and SBHZD_Hopfield'.
Definition at line 67 of file SbGeoRefraction.H'.
double SBZenithDelay::vapourPress (floatT, floatRH) [static]"Calcs partial water vapour pressure, mbar'.
Parameters:
T is a dry temperature, C;
RH is a relative humidity, %'.
Returns:
partial water vapour pressure, mbar'.
J'.A'.Estefan, O'.J'.Sovers, 'A Comparative Survey of Current and Proposed Tropospheric
 Refraction-Delay Models for DSN Radio Metric Data Calibration', JPL Publication 94-24, October 1994'. Page 14, Eq'. (16): ''.'.'.a variation of the simple model of Bean and Dutton [1966]:'
Definition at line 55 of file SbGeoRefraction.C'.
Referenced by SBWZD_Hopfield::operator()(), SBWZD_Saastamoinen::operator()(), SBHMf_CfA2p2::operator()(), SBHMf_Ifadis::operator()(), SBWMf_Ifadis::operator()(), and SBRefraction::operator()().
Member Data Documentation
const double SBZenithDelay::K1 = 77.604 [static, protected]
refraction coeff'. #1, K/mbar; Thayer, 1974
Definition at line 44 of file SbGeoRefraction.H'.
Referenced by k1().
const double SBZenithDelay::K2 = 64.79 [static, protected]
refraction coeff'. #2, K/mbar; Thayer, 1974
Definition at line 45 of file SbGeoRefraction.H'.
Referenced by k2().
const double SBZenithDelay::K3 = 3.776e+5 [static, protected]
refraction coeff'. #3, K/mbar^2; Thayer, 1974
Definition at line 46 of file SbGeoRefraction.H'.
Referenced by k3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.