.TH "SteelBreeze.C" 3 "Mon May 14 2012" "Version 2.0.2" "SteelBreeze Reference Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SteelBreeze.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <qapplication\&.h>\fP
.br
\fC#include <qmessagebox\&.h>\fP
.br
\fC#include 'SbIMainWin\&.H'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhandlerSIGs\fP (int signum)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct sigaction \fBsaveSIGFPE\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGILL\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGSEGV\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGABRT\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGBUS\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGINT\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGHUP\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGTERM\fP"
.br
.ti -1c
.RI "struct sigaction \fBsaveSIGDFL\fP"
.br
.ti -1c
.RI "const char * \fBoptions\fP = 'dqa'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void handlerSIGs (intsignum)"
.PP
Definition at line 50 of file SteelBreeze\&.C'\&.
.PP
References SBLog::ERR, SBLog::INTERFACE, Log, saveSIGABRT, saveSIGBUS, saveSIGDFL, saveSIGFPE, saveSIGHUP, saveSIGILL, saveSIGINT, saveSIGSEGV, saveSIGTERM, SBVersion::selfName(), SBVersion::toString(), Version, and SBLog::write()\&.
.PP
Referenced by main()\&.
.SS "int main (intargc, char **argv)"
.PP
Definition at line 104 of file SteelBreeze\&.C'\&.
.PP
References handlerSIGs(), MainWin, options, saveSIGABRT, saveSIGBUS, saveSIGDFL, saveSIGFPE, saveSIGHUP, saveSIGILL, saveSIGINT, saveSIGSEGV, and saveSIGTERM\&.
.SH "Variable Documentation"
.PP 
.SS "const char* \fBoptions\fP = 'dqa'"
.PP
Definition at line 48 of file SteelBreeze\&.C'\&.
.PP
Referenced by main()\&.
.SS "struct sigaction \fBsaveSIGABRT\fP"
.PP
Definition at line 37 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGBUS\fP"
.PP
Definition at line 38 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGDFL\fP"
.PP
Definition at line 46 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGFPE\fP"
.PP
Definition at line 34 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGHUP\fP"
.PP
Definition at line 42 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGILL\fP"
.PP
Definition at line 35 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGINT\fP"
.PP
Definition at line 41 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGSEGV\fP"
.PP
Definition at line 36 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SS "struct sigaction \fBsaveSIGTERM\fP"
.PP
Definition at line 43 of file SteelBreeze\&.C'\&.
.PP
Referenced by handlerSIGs(), and main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'\&.
