Vector3
NAME
Vector3 -
SYNOPSIS
#include <SbVector3.H>
Inherited by SBOceanTideLd, SBPolarTideLd, SBSolidTideLd, and SBTideLd'.
Public Member Functions
Vector3 ()
Vector3 (double v1, double v2, double v3)
Vector3 (const Vector3 &V)
virtual ~Vector3 ()
virtual QString ClassName () const
double & operator[] (DIRECTION i)
double at (DIRECTION i) const
double module () const
double phi () const
double lambda () const
Vector3 & unify ()
Vector3 unit () const
void clear ()
Vector3 & operator= (const Vector3 &)
Vector3 & operator+= (const Vector3 &)
Vector3 & operator-= (const Vector3 &)
Vector3 & operator*= (double)
Vector3 & operator/= (double)
virtual void report2Log (SBLog::LogLevel, uint, const QString &, int, int, double=1.0) const
bool operator== (const Vector3 &v) const
bool operator!= (const Vector3 &v) const
Protected Attributes
double vec [3]
Friends
Vector3 operator- (const Vector3 &)
Vector3 operator+ (const Vector3 &, const Vector3 &)
Vector3 operator- (const Vector3 &, const Vector3 &)
Vector3 operator/ (const Vector3 &, double)
Vector3 operator* (const Vector3 &, double)
Vector3 operator* (double, const Vector3 &)
double operator* (const Vector3 &, const Vector3 &)
Vector3 operator% (const Vector3 &, const Vector3 &)
Vector3 operator* (const Matrix3 &, const Vector3 &)
QDataStream & operator<< (QDataStream &s, const Vector3 &v)
QDataStream & operator>> (QDataStream &s, Vector3 &v)
Detailed Description
3d vector'.
Definition at line 50 of file SbVector3.H'.
Constructor & Destructor Documentation
Vector3::Vector3 () [inline]"A constructor'. Creates a copy of object'.
Definition at line 60 of file SbVector3.H'.
References vec.
Referenced by SBSolidTideLdIERS96::deg2OutPhase(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLd::makeStep2(), SBSolidTideLdIERS96::makeStep2(), SBSolidTideLd::permTide(), SBSolidTideLdIERS96::permTide(), and unit().
Vector3::Vector3 (doublev1, doublev2, doublev3) [inline]
Definition at line 61 of file SbVector3.H'.
References vec.
Vector3::Vector3 (const Vector3 &V) [inline]"A constructor'. Creates a copy of object'.
Parameters:
V values of the new object'.
Definition at line 66 of file SbVector3.H'.
References vec.
virtual Vector3::~Vector3 () [inline, virtual]"A destructor'.
Definition at line 68 of file SbVector3.H'.
Member Function Documentation
double Vector3::at (DIRECTIONi) const [inline]
Definition at line 72 of file SbVector3.H'.
References vec.
Referenced by SBStationEditor::acquireData(), SBDelay::calc(), SBDelay::calcDerivatives(), collectListOfSINEXParameters(), collectListOfSINEXParameters4NEQ(), SBRunManager::constraintStationCoord(), SBRunManager::constraintStationVeloc(), SBTestEphem::createWidget4Test(), SBPlateMotion::displacement(), SBTestEphem::displayCoo(), SBTestAPLoad::fillData4Plotting(), SBEccListItem::key(), SBCoordsListItem::key(), SBRunManager::makeReportMaps(), Matrix3::Matrix3(), operator<<(), SB_TRF::prepareEccs4Session(), SBRefraction::refrDir(), SBStationEcc::registerEcc(), SBCoordsEditor::SBCoordsEditor(), sinex_SiteEccentricityBlock(), sinex_tro_StaCoordinatesBlock(), SBEccListItem::text(), SBCoordsListItem::text(), SBPlateEntry::velocity(), SBPlateMotion::velocity(), SBStationEditor::wCoordinates(), and SBSiteEditor::wSite().
virtual QString Vector3::ClassName () const [inline, virtual]"Refers to a class name (debug info)
Reimplemented in SBTideLd, SBSolidTideLdIERS96, SBSolidTideLdIERS92, SBSolidTideLd, SBPolarTideLd, and SBOceanTideLd'.
Definition at line 70 of file SbVector3.H'.
void Vector3::clear () [inline]
Definition at line 79 of file SbVector3.H'.
References vec.
Referenced by SBDelay::calc(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), and SBSolidTideLd::operator()().
double Vector3::lambda () const [inline]
Definition at line 75 of file SbVector3.H'.
References module(), and vec.
Referenced by SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), and SBSolidTideLd::operator()().
double Vector3::module () const [inline]
Definition at line 73 of file SbVector3.H'.
References vec.
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBSolidTideLdIERS96::deg3InPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dH2(), SBSolidTideLd::dTide_dL2(), SBSolidTideLd::dTide_dLag(), SBStationImport::importITRF(), lambda(), SBSolidTideLdIERS96::latDepend(), SBRunManager::makeReportMaps(), SBSolidTideLd::makeStep1(), phi(), report2Log(), unify(), and unit().
bool Vector3::operator!= (const Vector3 &v) const [inline]
Definition at line 102 of file SbVector3.H'.
Vector3 & Vector3::operator*= (doublev) [inline]
Definition at line 247 of file SbVector3.H'.
References vec.
Vector3 & Vector3::operator+= (const Vector3 &V) [inline]
Definition at line 235 of file SbVector3.H'.
References vec.
Vector3 & Vector3::operator-= (const Vector3 &V) [inline]
Definition at line 241 of file SbVector3.H'.
References vec.
Vector3 & Vector3::operator/= (doublev) [inline]
Definition at line 253 of file SbVector3.H'.
References vec.
Vector3 & Vector3::operator= (const Vector3 &V) [inline]
Definition at line 229 of file SbVector3.H'.
References vec.
bool Vector3::operator== (const Vector3 &v) const [inline]
Definition at line 100 of file SbVector3.H'.
References vec.
double& Vector3::operator[] (DIRECTIONi) [inline]
Definition at line 71 of file SbVector3.H'.
References vec.
double Vector3::phi () const [inline]
Definition at line 74 of file SbVector3.H'.
References module(), and vec.
Referenced by SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg2OutPhase(), SBTestEphem::displayCoo(), SBSolidTideLd::dTide_dLag(), SBSolidTideLdIERS96::latDepend(), SBSolidTideLdIERS96::makeStep2(), SBSolidTideLd::operator()(), SBSolidTideLd::permTide(), and SBSolidTideLdIERS96::permTide().
void Vector3::report2Log (SBLog::LogLevelLev, uintFac, const QString &Pref, intw_, intd_, doubleScale = 1.0) const [virtual]
Definition at line 39 of file SbVector3.C'.
References Log, module(), vec, and SBLog::write().
Referenced by SBStation::axisOffsetLenght(), SBDelay::calc(), SBEphem::calc(), SBAploEphem::displacement(), SBSolidTideLd::operator()(), SBTideLd::operator()(), and SBRefraction::operator()().
Vector3& Vector3::unify () [inline]
Definition at line 77 of file SbVector3.H'.
References module().
Referenced by SBDelay::calc(), SBSolidTideLd::deg2InPhase(), SBSolidTideLdIERS96::deg3InPhase(), and SBSolidTideLdIERS96::latDepend().
Vector3 Vector3::unit () const [inline]
Definition at line 78 of file SbVector3.H'.
References module(), and Vector3().
Referenced by SBDelay::calc(), SBRunManager::constraintStationVeloc(), SBSolidTideLd::dTide_dH2(), and SBSolidTideLd::dTide_dL2().
Friends And Related Function Documentation
Vector3 operator% (const Vector3 &V1, const Vector3 &V2) [friend]"makes a vector product of two vectors (because '%' has a priority of '*')
makes vector product of two vectors'.
Definition at line 326 of file SbVector3.H'.
Vector3 operator* (const Vector3 &V1, doublev2) [friend]"multiplies vector by scalar'.
Definition at line 302 of file SbVector3.H'.
Vector3 operator* (doublev1, const Vector3 &V2) [friend]"multiplies vector by scalar'.
Definition at line 310 of file SbVector3.H'.
double operator* (const Vector3 &V1, const Vector3 &V2) [friend]"makes a scalar product of two vectors
makes scalar product of two vectors'.
Definition at line 318 of file SbVector3.H'.
Vector3 operator* (const Matrix3 &M, const Vector3 &V) [friend]"makes a product of matrix and vector
Matrix3 makes product of matrix and vector'.
Definition at line 519 of file SbVector3.H'.
Vector3 operator+ (const Vector3 &V1, const Vector3 &V2) [friend]
Definition at line 278 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V) [friend]
Definition at line 270 of file SbVector3.H'.
Vector3 operator- (const Vector3 &V1, const Vector3 &V2) [friend]
Definition at line 286 of file SbVector3.H'.
Vector3 operator/ (const Vector3 &V1, doublev2) [friend]
Definition at line 294 of file SbVector3.H'.
QDataStream& operator<< (QDataStream &s, const Vector3 &v) [friend]
Definition at line 103 of file SbVector3.H'.
QDataStream& operator>> (QDataStream &s, Vector3 &v) [friend]
Definition at line 105 of file SbVector3.H'.
Member Data Documentation
double Vector3::vec[3] [protected]
Definition at line 53 of file SbVector3.H'.
Referenced by at(), clear(), lambda(), module(), SBOceanTideLd::operator()(), SBPolarTideLd::operator()(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), operator==(), operator[](), phi(), report2Log(), and Vector3().
Author
Generated automatically by Doxygen for SteelBreeze Reference Manual from the source code'.