/*
 * This file is part of SteelBreeze.
 *
 * SteelBreeze, the geodetic VLBI data analysing software.
 * Copyright (C) 1998-2002 Sergei Bolotin, MAO NASU, Kiev, Ukraine.
 *
 * SteelBreeze is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * SteelBreeze is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SteelBreeze; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Overview:	keeps determined compile time info.
 *
 */

#define SB_COMP_NAME "gcc"
#define SB_COMP_VERSION __VERSION__
#define SB_COMP_DATE __DATE__
#define SB_COMP_TIME __TIME__
#define SB_COMP_OS "Linux Scorpius #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 3.19.0-15-generic x86_64"
#define SB_COMP_HOST_NAME "Scorpius"
#define SB_COMP_LOGIN_NAME "misha"
#define SB_COMP_USER_NAME "Mykhailo Lytvyn"
#define SB_VER_MAJOR 2
#define SB_VER_MINOR 0
#define SB_VER_PATCHLEVEL 2
